### ISSUE TITLE
无法登陆，一直转圈圈

### ISSUE THREAD

**Issue by scemsjyd** [whyour/qinglong#1000]
![image](https://user-images.githubusercontent.com/14870062/146167764-c88ba3f8-8240-40c1-a161-6824f2021f37.png)
像这样一直转圈圈

![image](https://user-images.githubusercontent.com/14870062/146167901-ebbb8144-4b2f-4e96-a32f-7921b0124303.png)

**Comment by BinZhiZhu** [comment]
我的js报错，login不了
