### ISSUE TITLE
希望增加获取青龙版本的openapi

### ISSUE THREAD

**Issue by zhangyiqiu** [whyour/qinglong#1001]
做了个iOS端的青龙面板App，对接了openapi，但是由于版本差异，发布之后出现某些功能有的版本的用户可以用，有的版本的用户不能用的情况，最后确定是因为他们部署的青龙版本不一样，所以希望openapi中能提供一个获取当前版本的接口

**Comment by inoyna12** [comment]
可以做个安卓版的吗

**Comment by zhangyiqiu** [comment]
app即将上线
https://apps.apple.com/cn/app/%E9%9D%92%E9%BE%99%E9%9D%A2%E6%9D%BFlite/id1601574974

**Comment by whyour** [comment]
> 做了个iOS端的青龙面板App，对接了openapi，但是由于版本差异，发布之后出现某些功能有的版本的用户可以用，有的版本的用户不能用的情况，最后确定是因为他们部署的青龙版本不一样，所以希望openapi中能提供一个获取当前版本的接口

open/system

**Comment by zhangyiqiu** [comment]
看到了

**Comment by zhangyiqiu** [comment]
> > 做了个iOS端的青龙面板App，对接了openapi，但是由于版本差异，发布之后出现某些功能有的版本的用户可以用，有的版本的用户不能用的情况，最后确定是因为他们部署的青龙版本不一样，所以希望openapi中能提供一个获取当前版本的接口
> 
> open/system

有点点问题，api/system无需授权，open/system反而要授权了

**Comment by whyour** [comment]
@zhangyiqiu 嗯，openapi的是根据模块来的，没做其他白名单
