### ISSUE TITLE
青龙面板打开空白，怎么解决？

### ISSUE THREAD

**Issue by cui8** [whyour/qinglong#1009]
问题截图：
![](https://i.bmp.ovh/imgs/2021/12/7361cbda2ccabe0e.png)

执行青龙命令：ql check截图
![](https://i.bmp.ovh/imgs/2021/12/d9bac5a4db95892f.png)

怎么解决，求大佬解答

**Comment by acoolbook** [comment]
我也遇到了，今天几个青龙都是面板打不开。 ql check ql update都没用

**Comment by cjuwen** [comment]
我也是今天遇到这个情况

**Comment by atyvcn** [comment]
cdn 出问题了 证书过期了

**Comment by atyvcn** [comment]
反正就是 使用的cdn出问题了

**Comment by atyvcn** [comment]
解决方法就是替换cdn或者挂vpn

**Comment by nethawkhu** [comment]
挂科学上网就正常了。

**Comment by gzmars** [comment]
> 解决方法就是替换cdn或者挂vpn

感谢指导，挂梯解决。

**Comment by mjyhj** [comment]
添加host
cdn.jsdelivr.net解析IP改成 104.16.87.20

**Comment by KristHu** [comment]
> dn或者挂vpn

赞呀，挂梯解决

**Comment by cui8** [comment]
我的linux系统有机场了，但是青龙还是打不开，怎么才能让docker连接到本地clash
![](https://i.bmp.ovh/imgs/2021/12/9d343921b76838fc.png)

**Comment by cui8** [comment]
> 添加host cdn.jsdelivr.net解析IP改成 104.16.87.20

可以说下命令吗？大佬

**Comment by Jesn** [comment]
host 文件加入解析

`
104.16.87.20 cdn.jsdelivr.net
`

**Comment by mygod123982** [comment]
我这边替换了 cdn ok了

**Comment by nethawkhu** [comment]
> 我的linux系统有机场了，但是青龙还是打不开，怎么才能让docker连接到本地clash ![](https://camo.githubusercontent.com/39898216b1a2a145d7f8509c83b7e47b79998d37ef0b059efab5cecf006b8c02/68747470733a2f2f692e626d702e6f76682f696d67732f323032312f31322f396433343339323162373638333866632e706e67)

你自己电脑上挂VPN去访问，这和你Docker上有没有机场无关。

**Comment by yaojin2070** [comment]
> host 文件加入解析
> 
> `104.16.87.20 cdn.jsdelivr.net`

![image](https://user-images.githubusercontent.com/48686959/146730156-975eb1de-aff6-42ed-a123-db7915dc2fb6.png)
还是不行 是我添加错误了吗?我记得是这样添加的..

**Comment by clocker321** [comment]
本机加hosts后可以访问了

**Comment by yaojin2070** [comment]
> 本机加hosts后可以访问了
不错, 完美解决我的问题
