### ISSUE TITLE
换个靠谱点的CDN吧,这个CDN之前就屏蔽过国内IP

### ISSUE THREAD

**Issue by Smart-Yi** [whyour/qinglong#1010]

**Comment by justmd5** [comment]
建议更换：https://staticfile.org/

**Comment by 1955782864** [comment]
不管用啊

**Comment by qeqeq1** [comment]
cdn.jsdelivr.net不是屏蔽了国内IP，而是其ICP备案被大陆管局吊销了....
之前故障原因是网宿把他证书从证书链错误移除了
所以不是jsd不愿意合作，人家很想合作，还花血本买了网宿的cdn=-=
