### ISSUE TITLE
注册账号出现这个错误

### ISSUE THREAD

**Issue by yaojin2070** [whyour/qinglong#1011]
![企业微信截图_16399858754751](https://user-images.githubusercontent.com/48686959/146730367-1dbd3583-a7d9-419b-93e3-dce5d8fcd58d.png)
为啥会403, 有懂的告诉下吗, 是因为我挂了梯子访问的原因吗? 刚刚听说cdn挂了额

**Comment by yangdaozhao** [comment]
挂了 等修复吧

**Comment by yaojin2070** [comment]
> 挂了 等修复吧

我现在挂梯子能访问页面了, 可是注册账号会报403, 是什么问题, 我配置问题吗

**Comment by yangdaozhao** [comment]
我挂个梯子好了 你清空缓存刷新下试试

**Comment by yaojin2070** [comment]
> 我挂个梯子好了 你清空缓存刷新下试试

不行, 还是403, 似乎不关cdn的问题

**Comment by yangdaozhao** [comment]
那就不太清楚了 反正现在cdn是有问题的

**Comment by yaojin2070** [comment]
已解决, 代理的问题, 导致403
