### ISSUE TITLE
增删脚本已经没有通知了吗？

### ISSUE THREAD

**Issue by EchoChan314** [whyour/qinglong#1018]
![image](https://user-images.githubusercontent.com/5077551/146979297-c3192ba8-91a1-437b-91e0-98a5cc253ed2.png)

之前是有通知的，但现在不行了，是取消了吗？还是我没设置对。现在脚本的运行是有通知的，反而系统增删脚本没有通知。

**Comment by aliyy2021** [comment]
我也是，全部删掉重新安装就可以了，过段时间又不通知，我重装几次了，崩溃😭
