### ISSUE TITLE
2.10.12获取脚本管理接口报错429

### ISSUE THREAD

**Issue by shiruchao** [whyour/qinglong#1019]
脚本管理页面接口请求https://o1051273.ingest.sentry.io/api/6047851/envelope/?sentry_key=ea2fede373244db99c536210b910d9da&sentry_version=7；报错状态码429，导致页面持续loding,没有错误提示也没有关闭loding

**Comment by shiruchao** [comment]
{"detail":"event rejected due to rate limit"}

**Comment by HelperInCa** [comment]
v2.10.2 +1
