### ISSUE TITLE
更新后两个问题

### ISSUE THREAD

**Issue by woboo110** [whyour/qinglong#102]
一是更新面板任务一直显示运行中
二是定时任务好像都失效了，没有按时执行

**Comment by yang7758258** [comment]
对，一样的

**Comment by x1iu** [comment]
貌似每个任务要手动运行一次，才会按时执行

**Comment by yang7758258** [comment]
我重新部署容器了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月12日(星期三) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whyour/qinglong] 更新后两个问题 (#102)

**Comment by woboo110** [comment]
> 我重新部署容器了------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年5月12日(星期三) 下午2:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [whyour/qinglong] 更新后两个问题 (#102)

解决了？

**Comment by yang7758258** [comment]
暂时执行了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月12日(星期三) 下午2:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whyour/qinglong] 更新后两个问题 (#102)
