### ISSUE TITLE
login页面打不开，有js报错

### ISSUE THREAD

**Issue by BinZhiZhu** [whyour/qinglong#1020]
![image](https://user-images.githubusercontent.com/35824900/147028552-0707d8ea-a05b-4b0d-b0ac-04fb13617a78.png)

老哥们能登录后台吗？？

**Comment by GanHuaLin** [comment]
我的也是这个问题

**Comment by GanHuaLin** [comment]
mac系统下黑暗模式就会出这个问题，关闭系统的黑暗模式就好了

**Comment by whyour** [comment]
@GanHuaLin 更新最新版

**Comment by CAB233** [comment]
确实，pc上用edge浏览器的黑暗模式会显示不出界面，浅色界面就没问题

**Comment by BinZhiZhu** [comment]
> mac系统下黑暗模式就会出这个问题，关闭系统的黑暗模式就好了

这么坑的吗。。。

**Comment by BinZhiZhu** [comment]
> @GanHuaLin 更新最新版

最新版可以解决吗，我看看最近有无类似的commit

**Comment by BinZhiZhu** [comment]
老哥们，关掉黑暗模式没报错了，但是提示：

```
失败次数过多，请462167秒后重试
```

![image](https://user-images.githubusercontent.com/35824900/147843428-0ee5a3b3-417c-4ab2-9dec-2f0903761abb.png)


是有人一直扫描吗????

**Comment by BinZhiZhu** [comment]
> 老哥们，关掉黑暗模式没报错了，但是提示：
> 
> ```
> 失败次数过多，请462167秒后重试
> ```
> 
> ![image](https://user-images.githubusercontent.com/35824900/147843428-0ee5a3b3-417c-4ab2-9dec-2f0903761abb.png)
> 
> 是有人一直扫描吗????

sorry，已经解决了，查了一下可以自己脚本重置失败次数,希望对其他人有帮助

```
docker exec -it qinglong ql resetlet
```
