### ISSUE TITLE
bug反馈 设置了所有通知，都不通知，

### ISSUE THREAD

**Issue by 929126387** [whyour/qinglong#1023]
只有保存通知设置，和登录青龙，通知，脚本执行都不通知  
![QQ截图20211222220355](https://user-images.githubusercontent.com/77496052/147104901-b1232f86-e71b-4d87-ad56-cc51248a1a60.png)

**Comment by cc9014** [comment]
脚本类通知在“配置文件”里设置。

**Comment by jinghua625** [comment]
> 脚本类通知在“配置文件”里设置。

请问如何设置个别任务发送通知，不希望所有任务执行完了都发通知。

**Comment by Jingle-Pan** [comment]
> 脚本类通知在“配置文件”里设置。

同问，如何设置

**Comment by cc9014** [comment]
青龙里面有两个地方设置通知，在最右边的面板那里。
1. “系统设置”配置的是青龙本身的通知，例如登录成功/失败等
2. “配置文件”配置的是脚本类的通知，需要先在“通知环境变量”里面自己填写通知的账号信息（server酱，TG等）

至于要控制个别任务发通知，需要去对应脚本里面设置，具体看脚本的说明

**Comment by Jingle-Pan** [comment]
> 

没看懂脚本说明邮件发送的设置在哪里

**Comment by Jingle-Pan** [comment]
> 青龙里面有两个地方设置通知，在最右边的面板那里。
> 
> 1. “系统设置”配置的是青龙本身的通知，例如登录成功/失败等
> 2. “配置文件”配置的是脚本类的通知，需要先在“通知环境变量”里面自己填写通知的账号信息（server酱，TG等）
> 
> 至于要控制个别任务发通知，需要去对应脚本里面设置，具体看脚本的说明

没看懂脚本说明邮件发送的设置在哪里
