### ISSUE TITLE
青龙iOS beta版频繁在异地登录

### ISSUE THREAD

**Issue by linyongfu2013** [whyour/qinglong#1031]
前几天试用了iOS beta 版，之后，每天都收到几条异地登录失败的通知，是不是账号被盗了？

**Comment by zhangyiqiu** [comment]
关app啥事，不用app的还不是被扫，建议更换默认端口，别用5700
你账号都保存在app里面，要是app盗你账号，还会登录失败？

**Comment by zhangyiqiu** [comment]
> 前几天试用了iOS beta 版，之后，每天都收到几条异地登录失败的通知，是不是账号被盗了？

给你参考一下

【云服务器青龙被扫？建议改端口吧】
玩家：奔三的孽障
查看：https://www.kejiwanjia.com/jiaocheng/59387.html

**Comment by linyongfu2013** [comment]
@zhangyiqiu 
因为用青龙很久了，都没出现过类似情况，就前几天体验了一下app，之后开始就连续收到被人异地登录的推送，这种巧合就难免让人猜疑啊

**Comment by linyongfu2013** [comment]
而且，消息上面写的都是在 mobile 端登录，而不是web端

```
你于2021/12/26 下午5:22:34在 湖南省衡阳市 | 电信 mobile端 登录失败，ip地址 124.228.126.9
```

**Comment by cc9014** [comment]
我最近也经常碰到，应该是端口被别人扫到了而已。我反正是开了2FA的，直接不理会了。如果觉得难受就换个端口。

**Comment by zhangyiqiu** [comment]
开个双重认证吧

**Comment by linyongfu2013** [comment]
@zhangyiqiu 试了你发那个方法，改了端口，重启容器后端口并没有变，还是5700

**Comment by cc9014** [comment]
如果用docker-compose启动的话，直接docker-compose down删了这个容器，然后在yml文件里重新写端口。如果是用的命令行，就删了容器后，在命令行里改端口。
`-p 5700:5700 \`

**Comment by zhxingway** [comment]
> 

改了vi hostconfig.json这个文件，然后重启docker,发现文件又恢复回去了，端口还是5700
