### ISSUE TITLE
最近有一些无良的人，一直在扫青龙的IP登录

### ISSUE THREAD

**Issue by 465509522** [whyour/qinglong#1034]
![Screenshot_2021-12-27-12-57-32-982_com tencent mm](https://user-images.githubusercontent.com/74142114/147436069-6ebd6a62-ee41-42ed-88e9-06aacff851d6.jpg)

**Comment by xixici** [comment]
+ 1

**Comment by jeck5001** [comment]
我的也是

**Comment by qsjc** [comment]
我也是 hhhh 换了个端口好了

**Comment by yaojin2070** [comment]
我也是, 给爆破到10多万秒登录了, 完蛋.... 怎么解决

**Comment by Spongebaby819** [comment]
> 我也是 hhhh 换了个端口好了

老哥怎么修改的端口？

**Comment by flatpig** [comment]
是的 目前只能通过明确重置失败倒计时
# 重置登录错误次数
ql resetlet  
端口改了不生效

**Comment by flatpig** [comment]
> 我也是, 给爆破到10多万秒登录了, 完蛋.... 怎么解决

ql resetlet

**Comment by flatpig** [comment]
刚才更新了下qinglong，改了docker-compose.yml
```yml
 ports:
      - "0.0.0.0:5700(更改这个端口):5700"
```
改完重启
```bash
docker-compose up -d
```

**Comment by WangJiyuanYo** [comment]
真是孤儿行为，今天早晨给我攻了，晚上登录发现超时

**Comment by hu-qi** [comment]
直接改的 nginx ，希望能长久有效

![image](https://user-images.githubusercontent.com/17986122/147997247-b921c223-d6f1-4f3c-8b7a-3de4f2d7a323.png)
