### ISSUE TITLE
【功能请求】路径前缀配置支持

### ISSUE THREAD

**Issue by RyoLee** [whyour/qinglong#1035]
问题：

url无法定制，导致使用traefik的PathPrefix识别转发时，无法正确返回响应

举例：

配置Host(`abc.com`) && PathPrefix(`/ql`) 转发至青龙5700端口

访问首页url http://abc.com/ql/

返回包含url http://abc.com/umi.f778bd55.css

实际正确url http://abc.com/ql/umi.f778bd55.css

建议配置增加类似prefix=/

以上例子中配置对应改为prefix=/ql

修改应该主要涉及router的几个use和nginx的conf文件

**Comment by AmazingXiaomi** [comment]
how to fixed it
