### ISSUE TITLE
批量执行任务时的并发数设置的 5 ，但是在同一时间仍然超过了这个数

### ISSUE THREAD

**Issue by yunxi993** [whyour/qinglong#1039]
![image](https://user-images.githubusercontent.com/59167936/147587707-d5e7765a-3472-438e-8b68-1aab2fbf0c23.png)
设置后有重启.
面板版本：v2.10.13

**Comment by zhxingway** [comment]
解决了？

**Comment by yunxi993** [comment]
> 解决了？

没有啊.

**Comment by zyystudio** [comment]
我也有这个问题 总是10个10个的运行中 没用定时调度cron 还是应该是程序中设置的问题 这个参数该为2也没用
