### ISSUE TITLE
青龙面板Android端助手

### ISSUE THREAD

**Issue by l123456789jy** [whyour/qinglong#1041]
# 青龙安卓面板

#### 介绍
青龙安卓面板

#### 软件架构
支持基本所有安卓手机

### 下载地址
[青龙安卓下载地址](https://www.pgyer.com/ne8D)

gitee下载地址 ： https://gitee.com/jingyuanliu/qinglongAndroid/blob/master/QingLongAndroid.apk

### TG，频道下载地址 : 
https://t.me/QingLongAndroid

#### 安装教程

直接下载安装就可以

#### 支持以下功能

1.  账号密码登录
2.  定时任务列表查看
3.  定时任务停止，运行
4.  定时任务禁止和启用
5.  定时任务删除
6.  定时任务日志查看
7.  添加定时任务
8.  搜索定时任务
9.  增加环境变量管理
10. 增加多账号管理
11. CK 助手
12. 增加二次登录，定时任务，环境变量可编辑，修改CK 奔溃

13.适配高版本青龙登录

**Comment by zhangyiqiu** [comment]
大佬，私聊我一下，https://t.me/ql_dev_bot
备注下安卓端开发者

**Comment by xy1661c** [comment]
感谢分享

**Comment by a512154224** [comment]
谢谢这位大佬的分享，但是在这个四处到CK的年代，不是开源的，估计没几个人会用

**Comment by a512154224** [comment]
谢谢这位大佬的分享，但是在这个四处盗CK的年代，不是开源的，估计没几个人会用
