### ISSUE TITLE
更新任务状态失败(jwt expired)

### ISSUE THREAD

**Issue by shenmadouyaowen** [whyour/qinglong#1049]
大佬,任务列表查看日志不是最新的,然后去任务日志里面查看发现有报"更新任务状态失败(jwt expired)" ,这个怎么处理?但是文件里的日志是存在的

![image](https://user-images.githubusercontent.com/12426724/148005263-b82770d6-55f3-4ed9-a067-7562d9a77eda.png)
![image](https://user-images.githubusercontent.com/12426724/148005295-79b6623e-835f-4ae5-b5f8-005a811c779b.png)

**Comment by hua12lao** [comment]
> 大佬,任务列表查看日志不是最新的,然后去任务日志里面查看发现有报"更新任务状态失败(jwt expired)" ,这个怎么处理?但是文件里的日志是存在的
> 
> ![image](https://user-images.githubusercontent.com/12426724/148005263-b82770d6-55f3-4ed9-a067-7562d9a77eda.png) ![image](https://user-images.githubusercontent.com/12426724/148005295-79b6623e-835f-4ae5-b5f8-005a811c779b.png)

重新登入面板，面板token失效了

**Comment by shenmadouyaowen** [comment]
> > 大佬,任务列表查看日志不是最新的,然后去任务日志里面查看发现有报"更新任务状态失败(jwt expired)" ,这个怎么处理?但是文件里的日志是存在的
> > ![image](https://user-images.githubusercontent.com/12426724/148005263-b82770d6-55f3-4ed9-a067-7562d9a77eda.png) ![image](https://user-images.githubusercontent.com/12426724/148005295-79b6623e-835f-4ae5-b5f8-005a811c779b.png)
> 
> 重新登入面板，面板token失效了

哦哦,好的,谢谢

**Comment by sxx0527** [comment]
> > > 大佬,任务列表查看日志不是最新的,然后去任务日志里面查看发现有报"更新任务状态失败(jwt expired)" ,这个怎么处理?但是文件里的日志是存在的
> > > ![image](https://user-images.githubusercontent.com/12426724/148005263-b82770d6-55f3-4ed9-a067-7562d9a77eda.png) ![image](https://user-images.githubusercontent.com/12426724/148005295-79b6623e-835f-4ae5-b5f8-005a811c779b.png)
> > 
> > 
> > 重新登入面板，面板token失效了
> 
> 哦哦,好的,谢谢

你可以了？我试了一下重登还是没同步日志啊。日志还是只在日志管理里面显示
