### ISSUE TITLE
Docker怎么新建容器装青龙   不会覆盖原有容器里的青龙

### ISSUE THREAD

**Issue by By-The** [whyour/qinglong#1056]

**Comment by cc9014** [comment]
新创建的容器名字和现有的不一样，映射的目录也不同就行了。

**Comment by By-The** [comment]
> 新创建的容器名字和现有的不一样，映射的目录也不同就行了。

有没有可以参考的口令

**Comment by cc9014** [comment]
就是readme里面写的命令啊
`docker run -dit \
  -v $PWD/ql/config:/ql/config \
  -v $PWD/ql/log:/ql/log \
  -v $PWD/ql/db:/ql/db \
  -v $PWD/ql/repo:/ql/repo \
  -v $PWD/ql/raw:/ql/raw \
  -v $PWD/ql/scripts:/ql/scripts \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest`

其中/ql的文件夹要替换，name和hostname的名字要替换

**Comment by weiyongzenqi** [comment]
把目录和容器名称都改了就行
