### ISSUE TITLE
容器镜像迁移保留数据

### ISSUE THREAD

**Issue by yuxuan0107** [whyour/qinglong#1057]
现在想从容器A将青龙迁移到容器B,请问如何操作可以保留青龙里面的数据,做到无数据丢失的迁移?
青龙的数据存在ql这个文件夹下,copy过去之后依旧是没有数据的,包括变量等,请问如何操作或者复制哪些文件夹可以做到无损迁移?

**Comment by cc9014** [comment]
有的，创建好容器。再把ql里的东西覆盖进去是可以的。
