### ISSUE TITLE
请问如何把现有青龙的端口换一下呢

### ISSUE THREAD

**Issue by CoderAWei** [whyour/qinglong#1063]
怎么操作啊。感觉有人在扫端口然后疯狂尝试登录😥

**Comment by cc9014** [comment]
用命令创建一个新的容器，命令里面把端口号改了。映射的文件夹不变的话，应该是继承之前的配置等文件的。

**Comment by weiyongzenqi** [comment]
把"-p 5700:5700 \"左边的一个5700改成你需要的
如:"-p 2333:5700 \"
