### ISSUE TITLE
请问一下拉库出现上千条任务重复如何解决?

### ISSUE THREAD

**Issue by weiyongzenqi** [whyour/qinglong#1067]
手动拉库没啥问题,定时自动拉库就出现,版本:2.10.13
系统:openwrt_arm64
而且大概率出现死循环导致系统直接死机

**Comment by SoyaDokio** [comment]
请参考

> 禁用重复任务
> https://github.com/shufflewzc/faker2/blob/main/jd_identical.py

**Comment by weiyongzenqi** [comment]
> 请参考
> 
> > 禁用重复任务
> > https://github.com/shufflewzc/faker2/blob/main/jd_identical.py

非常感谢你的回答,但是我拉的就是faker2的库,前一天晚上任务数还是150左右,第二天就变成1000+任务了,还有概率死循环无限吃内存死机

**Comment by weiyongzenqi** [comment]
https://github.com/smiek2121/scripts.git
![IMG_20220112_104707](https://user-images.githubusercontent.com/67868002/149054765-17967d58-05d3-48d0-a05f-da3b25dd8887.jpg)
补一下图，拉的https://github.com/smiek2121/scripts.git 这个仓库，本来还带一个faker2，自动拉faker2的话基本直接死机了

**Comment by SunnyQQQ** [comment]
我也是自动更新faker2库发生过死循环问题，现在都是手动运行脚本更新了

**Comment by weiyongzenqi** [comment]
> 我也是自动更新faker2库发生过死循环问题，现在都是手动运行脚本更新了

嗯好的，谢谢！我现在临时性解决方案也是把脚本改到12月31日运行，想起来的时候就手动拉一下

**Comment by sdokio** [comment]
应该是[smiek2121/scripts](https://github.com/smiek2121/scripts)这个库的代码有问题
我在用的库是[shufflewzc/faker2](https://github.com/shufflewzc/faker2)，目前没有问题
