### ISSUE TITLE
BUG Python依赖安装失败

### ISSUE THREAD

**Issue by sdokio** [whyour/qinglong#1068]
青龙版本：v2.10.13
操作步骤：依赖管理→Python3→新建依赖→numpy→确定
参考了类似问题 #990 中大佬 @dclemon 的解答：

> 在网页端依赖管理里面选linux依赖，依次安装python3-dev,gcc,musl-dev,libxslt-dev，安装完后再安装python依赖，wheel和lxml

但不幸的是，于我无效...

下面是从网页端获取的完整日志：
```
开始安装依赖 numpy，开始时间 2022/1/11 下午8:41:18

Collecting numpy

  Using cached numpy-1.22.0.zip (11.3 MB)

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

    Preparing wheel metadata: started

    Preparing wheel metadata: finished with status 'done'

Building wheels for collected packages: numpy

  Building wheel for numpy (PEP 517): started

  Building wheel for numpy (PEP 517): still running...

  Building wheel for numpy (PEP 517): finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pep517/_in_process.py build_wheel /tmp/tmpuuyb6quk
       cwd: /tmp/pip-install-j2gz45dm/numpy
  Complete output (251 lines):
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/bit_generator.pyx
  Processing numpy/random/_bounded_integers.pyx.in
  Processing numpy/random/_generator.pyx
  Processing numpy/random/_pcg64.pyx
  Processing numpy/random/_sfc64.pyx
  Processing numpy/random/mtrand.pyx
  Processing numpy/random/_philox.pyx
  Processing numpy/random/_mt19937.pyx
  Processing numpy/random/_common.pyx
  Cythonizing sources
  INFO: blas_opt_info:
  INFO: blas_armpl_info:
  INFO: customize UnixCCompiler
  INFO:   libraries armpl_lp64_mp not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: blas_mkl_info:
  INFO:   libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: blis_info:
  INFO:   libraries blis not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: openblas_info:
  INFO:   libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: accelerate_info:
  INFO:   NOT AVAILABLE
  INFO:
  INFO: atlas_3_10_blas_threads_info:
  INFO: Setting PTATLAS=ATLAS
  INFO:   libraries tatlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: atlas_3_10_blas_info:
  INFO:   libraries satlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: atlas_blas_threads_info:
  INFO: Setting PTATLAS=ATLAS
  INFO:   libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: atlas_blas_info:
  INFO:   libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: blas_info:
  INFO:   libraries blas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: blas_src_info:
  INFO:   NOT AVAILABLE
  INFO:
  INFO:   NOT AVAILABLE
  INFO:
  non-existing path in 'numpy/distutils': 'site.cfg'
  INFO: lapack_opt_info:
  INFO: lapack_armpl_info:
  INFO:   libraries armpl_lp64_mp not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: lapack_mkl_info:
  INFO:   libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: openblas_lapack_info:
  INFO:   libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: openblas_clapack_info:
  INFO:   libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: flame_info:
  INFO:   libraries flame not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: atlas_3_10_threads_info:
  INFO: Setting PTATLAS=ATLAS
  INFO:   libraries tatlas,tatlas not found in /usr/local/lib
  INFO:   libraries tatlas,tatlas not found in /usr/lib
  INFO:   libraries tatlas,tatlas not found in /usr/lib/
  INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  INFO:   NOT AVAILABLE
  INFO:
  INFO: atlas_3_10_info:
  INFO:   libraries satlas,satlas not found in /usr/local/lib
  INFO:   libraries satlas,satlas not found in /usr/lib
  INFO:   libraries satlas,satlas not found in /usr/lib/
  INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
  INFO:   NOT AVAILABLE
  INFO:
  INFO: atlas_threads_info:
  INFO: Setting PTATLAS=ATLAS
  INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
  INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
  INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
  INFO:   NOT AVAILABLE
  INFO:
  INFO: atlas_info:
  INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib
  INFO:   libraries f77blas,cblas,atlas not found in /usr/lib
  INFO:   libraries f77blas,cblas,atlas not found in /usr/lib/
  INFO: <class 'numpy.distutils.system_info.atlas_info'>
  INFO:   NOT AVAILABLE
  INFO:
  INFO: lapack_info:
  INFO:   libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
  INFO:   NOT AVAILABLE
  INFO:
  INFO: lapack_src_info:
  INFO:   NOT AVAILABLE
  INFO:
  INFO:   NOT AVAILABLE
  INFO:
  INFO: numpy_linalg_lapack_lite:
  INFO:   FOUND:
  INFO:     language = c
  INFO:     define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
  INFO:
  running bdist_wheel
  running build
  running config_cc
  INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  INFO: build_src
  INFO: building py_modules sources
  creating build
  creating build/src.linux-x86_64-3.8
  creating build/src.linux-x86_64-3.8/numpy
  creating build/src.linux-x86_64-3.8/numpy/distutils
  INFO: building library "npymath" sources
  WARN: Could not locate executable armflang
  WARN: Could not locate executable gfortran
  WARN: Could not locate executable f95
  WARN: Could not locate executable ifort
  WARN: Could not locate executable ifc
  WARN: Could not locate executable lf95
  WARN: Could not locate executable pgfortran
  WARN: Could not locate executable nvfortran
  WARN: Could not locate executable f90
  WARN: Could not locate executable f77
  WARN: Could not locate executable fort
  WARN: Could not locate executable efort
  WARN: Could not locate executable efc
  WARN: Could not locate executable g77
  WARN: Could not locate executable g95
  WARN: Could not locate executable pathf95
  WARN: Could not locate executable nagfor
  WARN: Could not locate executable frt
  WARN: don't know how to compile Fortran code on platform 'posix'
  Running from numpy source directory.
  /tmp/pip-install-j2gz45dm/numpy/numpy/distutils/system_info.py:2077: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  /tmp/pip-install-j2gz45dm/numpy/numpy/distutils/system_info.py:2077: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  /tmp/pip-install-j2gz45dm/numpy/numpy/distutils/system_info.py:2077: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
  /tmp/pip-install-j2gz45dm/numpy/numpy/distutils/system_info.py:1902: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  /tmp/pip-install-j2gz45dm/numpy/numpy/distutils/system_info.py:1902: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  Warning: attempted relative import with no known parent package
  /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
    warnings.warn(msg)
  
  
  [Errno 2] No such file or directory: 'g++'
  
  
  Traceback (most recent call last):
    File "/usr/lib/python3.8/site-packages/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/lib/python3.8/site-packages/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/lib/python3.8/site-packages/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 450, in <module>
      setup_package()
    File "setup.py", line 442, in setup_package
      setup(**metadata)
    File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/command/build.py", line 61, in run
      old_build.run(self)
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/command/build_src.py", line 144, in run
      self.build_sources()
    File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
      self.build_library_sources(*libname_info)
    File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
      sources = self.generate_sources(sources, (lib_name, build_info))
    File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
      source = func(extension, build_dir)
    File "/tmp/pip-install-j2gz45dm/numpy/numpy/core/setup.py", line 701, in get_mathlib_info
      raise RuntimeError(
  RuntimeError: Broken toolchain: cannot link a simple C++ program. note: A compiler with support for C++11 language features is required.
  ----------------------------------------

  ERROR: Failed building wheel for numpy

Failed to build numpy

ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly

依赖安装失败，结束时间 2022/1/11 下午8:45:11，耗时 232.967 秒
```

**Comment by dclemon** [comment]
这种问题一般是因为docker打包的环境不完整，看样子缺了几个c++的编译库，你可以用关键词docker、numpy搜索看看


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whyour/qinglong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 晚上9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[whyour/qinglong] BUG Python依赖安装失败 (Issue #1068)





 
青龙版本：v2.10.13
 操作步骤：依赖管理→Python3→新建依赖→numpy→确定
 参考了类似问题 #990 中大佬 @dclemon 的解答：
  
在网页端依赖管理里面选linux依赖，依次安装python3-dev,gcc,musl-dev,libxslt-dev，安装完后再安装python依赖，wheel和lxml
  
但不幸的是，于我无效...
 
下面是从网页端获取的完整日志：
 开始安装依赖 numpy，开始时间 2022/1/11 下午8:41:18 Collecting numpy   Using cached numpy-1.22.0.zip (11.3 MB)   Installing build dependencies: started   Installing build dependencies: finished with status 'done'   Getting requirements to build wheel: started   Getting requirements to build wheel: finished with status 'done'     Preparing wheel metadata: started     Preparing wheel metadata: finished with status 'done' Building wheels for collected packages: numpy   Building wheel for numpy (PEP 517): started   Building wheel for numpy (PEP 517): still running...   Building wheel for numpy (PEP 517): finished with status 'error'   ERROR: Command errored out with exit status 1:    command: /usr/bin/python3 /usr/lib/python3.8/site-packages/pep517/_in_process.py build_wheel /tmp/tmpuuyb6quk        cwd: /tmp/pip-install-j2gz45dm/numpy   Complete output (251 lines):   Processing numpy/random/_bounded_integers.pxd.in   Processing numpy/random/bit_generator.pyx   Processing numpy/random/_bounded_integers.pyx.in   Processing numpy/random/_generator.pyx   Processing numpy/random/_pcg64.pyx   Processing numpy/random/_sfc64.pyx   Processing numpy/random/mtrand.pyx   Processing numpy/random/_philox.pyx   Processing numpy/random/_mt19937.pyx   Processing numpy/random/_common.pyx   Cythonizing sources   INFO: blas_opt_info:   INFO: blas_armpl_info:   INFO: customize UnixCCompiler   INFO:   libraries armpl_lp64_mp not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: blas_mkl_info:   INFO:   libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: blis_info:   INFO:   libraries blis not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: openblas_info:   INFO:   libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: accelerate_info:   INFO:   NOT AVAILABLE   INFO:   INFO: atlas_3_10_blas_threads_info:   INFO: Setting PTATLAS=ATLAS   INFO:   libraries tatlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: atlas_3_10_blas_info:   INFO:   libraries satlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: atlas_blas_threads_info:   INFO: Setting PTATLAS=ATLAS   INFO:   libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: atlas_blas_info:   INFO:   libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: blas_info:   INFO:   libraries blas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: blas_src_info:   INFO:   NOT AVAILABLE   INFO:   INFO:   NOT AVAILABLE   INFO:   non-existing path in 'numpy/distutils': 'site.cfg'   INFO: lapack_opt_info:   INFO: lapack_armpl_info:   INFO:   libraries armpl_lp64_mp not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: lapack_mkl_info:   INFO:   libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: openblas_lapack_info:   INFO:   libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: openblas_clapack_info:   INFO:   libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: flame_info:   INFO:   libraries flame not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: atlas_3_10_threads_info:   INFO: Setting PTATLAS=ATLAS   INFO:   libraries tatlas,tatlas not found in /usr/local/lib   INFO:   libraries tatlas,tatlas not found in /usr/lib   INFO:   libraries tatlas,tatlas not found in /usr/lib/   INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'&gt;   INFO:   NOT AVAILABLE   INFO:   INFO: atlas_3_10_info:   INFO:   libraries satlas,satlas not found in /usr/local/lib   INFO:   libraries satlas,satlas not found in /usr/lib   INFO:   libraries satlas,satlas not found in /usr/lib/   INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'&gt;   INFO:   NOT AVAILABLE   INFO:   INFO: atlas_threads_info:   INFO: Setting PTATLAS=ATLAS   INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib   INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib   INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib/   INFO: <class 'numpy.distutils.system_info.atlas_threads_info'&gt;   INFO:   NOT AVAILABLE   INFO:   INFO: atlas_info:   INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib   INFO:   libraries f77blas,cblas,atlas not found in /usr/lib   INFO:   libraries f77blas,cblas,atlas not found in /usr/lib/   INFO: <class 'numpy.distutils.system_info.atlas_info'&gt;   INFO:   NOT AVAILABLE   INFO:   INFO: lapack_info:   INFO:   libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']   INFO:   NOT AVAILABLE   INFO:   INFO: lapack_src_info:   INFO:   NOT AVAILABLE   INFO:   INFO:   NOT AVAILABLE   INFO:   INFO: numpy_linalg_lapack_lite:   INFO:   FOUND:   INFO:     language = c   INFO:     define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]   INFO:   running bdist_wheel   running build   running config_cc   INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options   running config_fc   INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options   running build_src   INFO: build_src   INFO: building py_modules sources   creating build   creating build/src.linux-x86_64-3.8   creating build/src.linux-x86_64-3.8/numpy   creating build/src.linux-x86_64-3.8/numpy/distutils   INFO: building library "npymath" sources   WARN: Could not locate executable armflang   WARN: Could not locate executable gfortran   WARN: Could not locate executable f95   WARN: Could not locate executable ifort   WARN: Could not locate executable ifc   WARN: Could not locate executable lf95   WARN: Could not locate executable pgfortran   WARN: Could not locate executable nvfortran   WARN: Could not locate executable f90   WARN: Could not locate executable f77   WARN: Could not locate executable fort   WARN: Could not locate executable efort   WARN: Could not locate executable efc   WARN: Could not locate executable g77   WARN: Could not locate executable g95   WARN: Could not locate executable pathf95   WARN: Could not locate executable nagfor   WARN: Could not locate executable frt   WARN: don't know how to compile Fortran code on platform 'posix'   Running from numpy source directory.   /tmp/pip-install-j2gz45dm/numpy/numpy/distutils/system_info.py:2077: UserWarning:       Optimized (vendor) Blas libraries are not found.       Falls back to netlib Blas library which has worse performance.       A better performance should be easily gained by switching       Blas library.     if self._calc_info(blas):   /tmp/pip-install-j2gz45dm/numpy/numpy/distutils/system_info.py:2077: UserWarning:       Blas (http://www.netlib.org/blas/) libraries not found.       Directories to search for the libraries can be specified in the       numpy/distutils/site.cfg file (section [blas]) or by setting       the BLAS environment variable.     if self._calc_info(blas):   /tmp/pip-install-j2gz45dm/numpy/numpy/distutils/system_info.py:2077: UserWarning:       Blas (http://www.netlib.org/blas/) sources not found.       Directories to search for the sources can be specified in the       numpy/distutils/site.cfg file (section [blas_src]) or by setting       the BLAS_SRC environment variable.     if self._calc_info(blas):   /tmp/pip-install-j2gz45dm/numpy/numpy/distutils/system_info.py:1902: UserWarning:       Lapack (http://www.netlib.org/lapack/) libraries not found.       Directories to search for the libraries can be specified in the       numpy/distutils/site.cfg file (section [lapack]) or by setting       the LAPACK environment variable.     return getattr(self, '_calc_info_{}'.format(name))()   /tmp/pip-install-j2gz45dm/numpy/numpy/distutils/system_info.py:1902: UserWarning:       Lapack (http://www.netlib.org/lapack/) sources not found.       Directories to search for the sources can be specified in the       numpy/distutils/site.cfg file (section [lapack_src]) or by setting       the LAPACK_SRC environment variable.     return getattr(self, '_calc_info_{}'.format(name))()   Warning: attempted relative import with no known parent package   /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'     warnings.warn(msg)         [Errno 2] No such file or directory: 'g++'         Traceback (most recent call last):     File "/usr/lib/python3.8/site-packages/pep517/_in_process.py", line 280, in <module&gt;       main()     File "/usr/lib/python3.8/site-packages/pep517/_in_process.py", line 263, in main       json_out['return_val'] = hook(**hook_input['kwargs'])     File "/usr/lib/python3.8/site-packages/pep517/_in_process.py", line 204, in build_wheel       return _build_backend().build_wheel(wheel_directory, config_settings,     File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 230, in build_wheel       return self._build_with_temp_dir(['bdist_wheel'], '.whl',     File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir       self.run_setup()     File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 267, in run_setup       super(_BuildMetaLegacyBackend,     File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup       exec(compile(code, __file__, 'exec'), locals())     File "setup.py", line 450, in <module&gt;       setup_package()     File "setup.py", line 442, in setup_package       setup(**metadata)     File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/core.py", line 169, in setup       return old_setup(**new_attr)     File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup       return distutils.core.setup(**attrs)     File "/usr/lib/python3.8/distutils/core.py", line 148, in setup       dist.run_commands()     File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands       self.run_command(cmd)     File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command       cmd_obj.run()     File "/tmp/pip-build-env-nnmicgq1/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run       self.run_command('build')     File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command       self.distribution.run_command(command)     File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command       cmd_obj.run()     File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/command/build.py", line 61, in run       old_build.run(self)     File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run       self.run_command(cmd_name)     File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command       self.distribution.run_command(command)     File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command       cmd_obj.run()     File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/command/build_src.py", line 144, in run       self.build_sources()     File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources       self.build_library_sources(*libname_info)     File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources       sources = self.generate_sources(sources, (lib_name, build_info))     File "/tmp/pip-install-j2gz45dm/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources       source = func(extension, build_dir)     File "/tmp/pip-install-j2gz45dm/numpy/numpy/core/setup.py", line 701, in get_mathlib_info       raise RuntimeError(   RuntimeError: Broken toolchain: cannot link a simple C++ program. note: A compiler with support for C++11 language features is required.   ----------------------------------------   ERROR: Failed building wheel for numpy Failed to build numpy ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly 依赖安装失败，结束时间 2022/1/11 下午8:45:11，耗时 232.967 秒

**Comment by sdokio** [comment]
感谢解答 我去弄下库文件吧

**Comment by orency** [comment]
https://github.com/whyour/qinglong/issues/1162#issuecomment-1041138224)
这个方法要好得多

**Comment by sdokio** [comment]
> [#1162 (comment)](https://github.com/whyour/qinglong/issues/1162#issuecomment-1041138224)) 这个方法要好得多

感谢提醒
在服务器命令行执行命令：apk add py3-numpy
