### ISSUE TITLE
建议在面板界面中增加当前版本号显示

### ISSUE THREAD

**Issue by lxr760** [whyour/qinglong#107]
最新更新的比较频繁            但是却无法从当前环境中得知版本号 

建议增加版本号显示

**Comment by swzsweet** [comment]
+1

**Comment by whyour** [comment]
@swzsweet 建议的人给画个图看看

**Comment by lxr760** [comment]
> @swzsweet 建议的人给画个图看看

![image](https://user-images.githubusercontent.com/8476457/120133431-c4a60280-c1fe-11eb-92ac-569693ce94dc.png)

大概是这个意思，当然字体样式颜色什么的   可以弄的更好看些

**Comment by nxppru** [comment]
希望浏览器标签能显示面板<title>
