### ISSUE TITLE
青龙怎么回退上个版本？

### ISSUE THREAD

**Issue by nethawkhu** [whyour/qinglong#1071]
新版更新后，所有的 CK 变量顺序全部乱掉，然后任务出现重复，任务执行的日志也不更新，这升级前有小范围测试过吗？

**Comment by braless** [comment]
docker pull whyour/qinglong:2.10.13  然后 指定这个镜像 重新构建

**Comment by github-xihe** [comment]
确实问题很大

**Comment by kissfast** [comment]
感谢

> docker pull whyour/qinglong:2.10.13 然后 指定这个镜像 重新构建

感谢大神，升级了后台直接进不去了，ql check也无效
回退了就可以了
btw，我是arm的，不知道是不是有关系

**Comment by kikispenser** [comment]
> 感谢
> 
> > docker pull whyour/qinglong:2.10.13 然后 指定这个镜像 重新构建
> 
> 感谢大神，升级了后台直接进不去了，ql check也无效 回退了就可以了 btw，我是arm的，不知道是不是有关系

x86的也不行了，升级2.11后问题挺多的，后台到是能上，就是都不能用了，拉库也不行

**Comment by phb1253439** [comment]
1、青龙面板历史版本下载地址

https://hub.docker.com/r/hushunxu/qinglong_base/tags
2、拉取想要安装的版本

docker pull hushunxu/qinglong_base:2.10.0
如果想要其他版本就把2.10.0 换成其他版本好
3、安装青龙面板

docker run -dit \
-v $PWD/ql/config:/ql/config \
-v $PWD/ql/log:/ql/log \
-v $PWD/ql/db:/ql/db \
-v $PWD/ql/repo:/ql/repo \
-v $PWD/ql/raw:/ql/raw \
-v $PWD/ql/scripts:/ql/scripts \
-v $PWD/ql/jbot:/ql/jbot \
-v $PWD/ql/ninja:/ql/ninja \
-p 5700:5700 \
-p 5701:5701 \
--name qinglong \
--hostname qinglong \
--restart unless-stopped \
hushunxu/qinglong_base:2.10.13
