### ISSUE TITLE
v2.11.0 认证接口失效

### ISSUE THREAD

**Issue by necan** [whyour/qinglong#1073]
接口 `open/auth/token` 失效，返回
```
{
    "code": 500,
    "message": "SQLITE_ERROR: no such column: App.where"
}
```

**Comment by shenmadouyaowen** [comment]
接口/api/envs?searchValue=ck 返回
{'code': 500, 'message': 'SQLITE_ERROR: no such column: Env.command'}

**Comment by whyour** [comment]
强制更新下

**Comment by shenmadouyaowen** [comment]
> 强制更新下

docker exec -it qinglong ql -l update

后还是返回{'code': 500, 'message': 'SQLITE_ERROR: no such column: Env.command'}
