### ISSUE TITLE
2.11.0 环境变量排序失效

### ISSUE THREAD

**Issue by wxdfun** [whyour/qinglong#1076]
环境变量强制为默认排序，拖动后刷新再次变为默认排序

**Comment by whyour** [comment]
强制更新下

**Comment by wxdfun** [comment]
排序问题解决了  可是今天的环境变量每个都是双份的。

**Comment by kikispenser** [comment]
> 排序问题解决了 可是今天的环境变量每个都是双份的。

双份的你解决了吗，我这个现在删了重新拉库都不行了
