### ISSUE TITLE
如果能推出非docker版就好了

### ISSUE THREAD

**Issue by Vason-Hsueh** [whyour/qinglong#1089]
看了之前作者说Windows不好部署，但是我觉得如果能有非docker版的就能直接在Windows的Linux子系统上部署，更加方便，希望作者考虑一下

**Comment by jackadam1981** [comment]
对N多小白而言，能导入的虚拟机，或许是更方便的

**Comment by jackadam1981** [comment]
花了半小时，装了一个虚拟机。
https://cloud.189.cn/web/share?code=AryQZfbE3eAn（访问码：8aff）
ova格式，导入虚拟机即可。

注意网卡为桥接模式，linux用户名：root，密码：qinglong
进入linux，  输入ip addr（中间有空格）就可以看到虚拟机IP了，如果不是你的网段，那就是网卡模式没设为桥接模式。

默认带有watchtower，自动升级docker容器，可以说是跟随青龙升级。配置文件按青龙的说明，会被映射保存，自动升级docker容器，不丢配置。

访问你的linxuIP:5700,就可以开始青龙了。
依赖没搞。
有依赖问题再说吧。

**Comment by Vason-Hsueh** [comment]
> 花了半小时，装了一个虚拟机。 [https://cloud.189.cn/web/share?code=AryQZfbE3eAn（访问码：8aff）](https://cloud.189.cn/web/share?code=AryQZfbE3eAn%EF%BC%88%E8%AE%BF%E9%97%AE%E7%A0%81%EF%BC%9A8aff%EF%BC%89) ova格式，导入虚拟机即可。
> 
> 注意网卡为桥接模式，linux用户名：root，密码：qinglong 进入linux， 输入ip addr（中间有空格）就可以看到虚拟机IP了，如果不是你的网段，那就是网卡模式没设为桥接模式。
> 
> 默认带有watchtower，自动升级docker容器，可以说是跟随青龙升级。配置文件按青龙的说明，会被映射保存，自动升级docker容器，不丢配置。
> 
> 访问你的linxuIP:5700,就可以开始青龙了。 依赖没搞。 有依赖问题再说吧。

**Comment by Vason-Hsueh** [comment]
> 对N多小白而言，能导入的虚拟机，或许是更方便的

不是不会安装，而是想在Windows上用，Windows的wsl不支持docker

**Comment by jackadam1981** [comment]
@Vason-Hsueh 
用上了么？
关闭前也给个反馈啊。

**Comment by Vason-Hsueh** [comment]
> 对N多小白而言，能导入的虚拟机，或许是更方便的
我尝试用dockerfile在本地安装，不是不自动执行任务就是web面板出错

**Comment by jackadam1981** [comment]
dockerfile 应该不出错啊
我试试

**Comment by xiaoxiaofeixf** [comment]
> > 对N多小白而言，能导入的虚拟机，或许是更方便的
> > 我尝试用dockerfile在本地安装，不是不自动执行任务就是web面板出错

dockerfile部署，任务执行不了，对吧。

**Comment by jackadam1981** [comment]
docker build 可以

**Comment by iamtsm** [comment]
linux 本机部署也是可行的，参考下  本机部署 v2.11.2 #1163
