### ISSUE TITLE
2.11最新版本 运行脚本更新任务状态失败 

### ISSUE THREAD

**Issue by jiujiu-666** [whyour/qinglong#1092]
![image](https://user-images.githubusercontent.com/82791035/149624246-f567ac98-b067-4993-9daf-7d1b6b5fb69a.png)
![image](https://user-images.githubusercontent.com/82791035/149624262-7a5dd5ec-3ac4-4254-8b6f-c86982868f64.png)

**Comment by whyour** [comment]
删掉 task_before.sh 里的内容
