### ISSUE TITLE
希望青龙面板增加禁用重复任务功能

### ISSUE THREAD

**Issue by chenyajunai** [whyour/qinglong#1096]
之前有脚本可以去重
现在更新到新版，去重功能不能用了，找打了其它去重的脚本提示完成，但是查看还是没有成功

**Comment by jackadam1981** [comment]
我也在找去重
看了看源码，似乎是API修改了？
No authorization token was found

**Comment by jackadam1981** [comment]
去重脚本出错了，我也没找到原作者。
水平有限，我正在重写。

**Comment by chenyajunai** [comment]
> 去重脚本出错了，我没有找到作者 水平有限，我正在原著。

哦 加油

**Comment by jackadam1981** [comment]
https://github.com/shufflewzc/faker2/blob/main/jd_identical.py
93行：  _id  改为 id 
这样就可以正常禁用了。

但是推送企业微信，要media_id,继续看怎么修复。
`# -*- coding:utf-8 -*-
"""
cron: 50 * * * *
new Env('禁用重复任务');
"""

import json
import logging
import os
import sys
import time
import traceback

import requests

logger = logging.getLogger(name=None)  # 创建一个日志对象
logging.Formatter("%(message)s")  # 日志内容格式化
logger.setLevel(logging.INFO)  # 设置日志等级
logger.addHandler(logging.StreamHandler())  # 添加控制台日志
# logger.addHandler(logging.FileHandler(filename="text.log", mode="w"))  # 添加文件日志


ipport = os.getenv("IPPORT")
if not ipport:
    logger.info(
        "如果报错请在环境变量中添加你的真实 IP:端口\n名称：IPPORT\t值：127.0.0.1:5700\n或在 config.sh 中添加 export IPPORT='127.0.0.1:5700'"
    )
    ipport = "localhost:5700"
else:
    ipport = ipport.lstrip("http://").rstrip("/")
sub_str = os.getenv("RES_SUB", "shufflewzc_faker2")
sub_list = sub_str.split("&")
res_only = os.getenv("RES_ONLY", True)
headers = {
    "Accept": "application/json",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
}


def load_send() -> None:
    logger.info("加载推送功能中...")
    global send
    send = None
    cur_path = os.path.abspath(os.path.dirname(__file__))
    sys.path.append(cur_path)
    if os.path.exists(cur_path + "/notify.py"):
        try:
            from notify import send
        except Exception:
            send = None
            logger.info(f"❌加载通知服务失败!!!\n{traceback.format_exc()}")


def get_tasklist() -> list:
    tasklist = []
    t = round(time.time() * 1000)
    url = f"http://{ipport}/api/crons?searchValue=&t={t}"
    response = requests.get(url=url, headers=headers)
    datas = json.loads(response.content.decode("utf-8"))
    if datas.get("code") == 200:
        tasklist = datas.get("data")
    return tasklist


def filter_res_sub(tasklist: list) -> tuple:
    filter_list = []
    res_list = []
    for task in tasklist:
        for sub in sub_list:
            if task.get("command").find(sub) == -1:
                flag = False
            else:
                flag = True
                break
        if flag:
            res_list.append(task)
        else:
            filter_list.append(task)
    return filter_list, res_list


def get_index(lst: list, item: str) -> list:
    return [index for (index, value) in enumerate(lst) if value == item]


def get_duplicate_list(tasklist: list) -> tuple:
    logger.info("\n=== 第一轮初筛开始 ===")

    ids = []
    names = []
    cmds = []
    for task in tasklist:
        ids.append(task.get("id"))
        names.append(task.get("name"))
        cmds.append(task.get("command"))

    name_list = []
    for i, name in enumerate(names):
        if name not in name_list:
            name_list.append(name)

    tem_tasks = []
    tem_ids = []
    dup_ids = []
    for name2 in name_list:
        name_index = get_index(names, name2)
        for i in range(len(name_index)):
            if i == 0:
                logger.info(f"【✅保留】{cmds[name_index[0]]}")
                tem_tasks.append(tasklist[name_index[0]])
                tem_ids.append(ids[name_index[0]])
            else:
                logger.info(f"【🚫禁用】{cmds[name_index[i]]}")
                dup_ids.append(ids[name_index[i]])
        logger.info("")

    logger.info("=== 第一轮初筛结束 ===")

    return tem_ids, tem_tasks, dup_ids


def reserve_task_only(
    tem_ids: list, tem_tasks: list, dup_ids: list, res_list: list
) -> list:
    if len(tem_ids) == 0:
        return tem_ids

    logger.info("\n=== 最终筛选开始 ===")
    task3 = None
    for task1 in tem_tasks:
        for task2 in res_list:
            if task1.get("name") == task2.get("name"):
                dup_ids.append(task1.get("_id"))
                logger.info(f"【✅保留】{task2.get('command')}")
                task3 = task1
        if task3:
            logger.info(f"【🚫禁用】{task3.get('command')}\n")
            task3 = None
    logger.info("=== 最终筛选结束 ===")
    return dup_ids


def disable_duplicate_tasks(ids: list) -> None:
    t = round(time.time() * 1000)
    url = f"http://{ipport}/api/crons/disable?t={t}"
    data = json.dumps(ids)
    headers["Content-Type"] = "application/json;charset=UTF-8"
    response = requests.put(url=url, headers=headers, data=data)
    datas = json.loads(response.content.decode("utf-8"))
    if datas.get("code") != 200:
        logger.info(f"❌出错!!!错误信息为：{datas}")
    else:
        logger.info("🎉成功禁用重复任务~")


def get_token() -> str or None:
    try:
        with open("/ql/config/auth.json", "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        logger.info(f"❌无法获取 token!!!\n{traceback.format_exc()}")
        send("💔禁用重复任务失败", "无法获取 token!!!")
        exit(1)
    return data.get("token")


if __name__ == "__main__":
    logger.info("===> 禁用重复任务开始 <===")
    load_send()
    token = get_token()
    headers["Authorization"] = f"Bearer {token}"

    # 获取过滤后的任务列表
    sub_str = "\n".join(sub_list)
    logger.info(f"\n=== 你选择过滤的任务前缀为 ===\n{sub_str}")
    tasklist = get_tasklist()
    if len(tasklist) == 0:
        logger.info("❌无法获取 tasklist!!!")
        exit(1)
    filter_list, res_list = filter_res_sub(tasklist)

    tem_ids, tem_tasks, dup_ids = get_duplicate_list(filter_list)
    # 是否在重复任务中只保留设置的前缀
    if res_only:
        ids = reserve_task_only(tem_ids, tem_tasks, dup_ids, res_list)
    else:
        ids = dup_ids
        logger.info("你选择保留除了设置的前缀以外的其他任务")

    sum = f"所有任务数量为：{len(tasklist)}"
    filter = f"过滤的任务数量为：{len(res_list)}"
    disable = f"禁用的任务数量为：{len(ids)}"
    logging.info("\n=== 禁用数量统计 ===\n" + sum + "\n" + filter + "\n" + disable)

    if len(ids) == 0:
        logger.info("😁没有重复任务~")
    else:
        disable_duplicate_tasks(ids)
    if send:
        send("💖禁用重复任务成功", f"\n{sum}\n{filter}\n{disable}")`

**Comment by jackadam1981** [comment]
打开 https://github.com/shufflewzc/faker2/blob/main/jd_identical.py  复制代码，改93行

**Comment by chenyajunai** [comment]
好了，谢谢你，93行还有133行

**Comment by jackadam1981** [comment]
作者删库了

**Comment by Lucien6699** [comment]
禁用重复任务报错 无法获取token 怎么办
Traceback (most recent call last):
 File "/ql/data/scripts/raw_py_disable.py", line 158, in get_token
    with open("/ql/config/auth.json", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/ql/config/auth.json'

**Comment by cc9014** [comment]
> 

新版本把目录都移动到ql/data里面了，脚本报错的原因是无法在/ql/config/下找到。
你可以尝试修改这个脚本，看了下我的版本，大概在158行的位置，把路径改为 "/ql/data/config/auth.json"。然后你再试试行不行。
`        with open("/ql/config/auth.json", "r", encoding="utf-8") as f:`

**Comment by Lucien6699** [comment]
> 

我好像不是很理解“新目录把移动到ql/data里面”指的是哪个目录的什么文件移动到这里

**Comment by cc9014** [comment]
> > 
> 
> 我好像不是很理解“新目录把移动到ql/data里面”指的是哪个目录的什么文件移动到这里

原来目录都在ql下面，现在新版全部在ql/data下面。脚本还是在原来目录里找，自然找不到auth.json的文件。你只需要去脚本里面把路径改了就行。

**Comment by Lucien6699** [comment]
> > > 
> > 
> > 
> > 我理解“新目录移动到ql/data里面”不是很指哪个目录的什么文件移动到这里
> 
> 原来目录在ql下面，现在新版全部在ql/data下面。剧本还是在原来目录里找，自然找不到把au.json的文件。

我看了下ql下好像并没有 data这个文件夹，根目录下只有config这个文件夹，而且config文件夹里面有auth.json这个文件
![1](https://user-images.githubusercontent.com/70841606/162110984-3c083452-7f16-4d14-95cc-4cf8930138ee.png)
![2](https://user-images.githubusercontent.com/70841606/162110992-cf8d6fda-a9cb-46c1-963e-30a972cc7bf4.png)
![3](https://user-images.githubusercontent.com/70841606/162111184-e4bcf910-83e5-4222-92e6-97a1965f46a2.png)

**Comment by cc9014** [comment]
你是什么版本的qinglong，2.12.0开始改的。

**Comment by Lucien6699** [comment]
> 你是什么版本的qinglong，2.12.0开始改的。

 就是20.12.0，问题是根目录下怎么没有data的
![image](https://user-images.githubusercontent.com/70841606/162111685-ec8a1a07-e5db-4f1a-9f57-11f418322cad.png)

**Comment by cc9014** [comment]
我理解你可能是没有重新映射，直接升级就这样了……要么退回去老版本。要么重新建个容器，然后再把现有的文件夹拷贝进去。
建容器建议用docker-compose，映射创建删除都方便。

**Comment by ghsssss** [comment]
我也不能禁用重复任务，报文件找不到，请问怎么解决

**Comment by Lucien6699** [comment]
> 我也不能禁用重复任务，报文件找不到，请问怎么解决

我找人帮我重新写了一份 就好使了

**Comment by ghsssss** [comment]
> > 我也不能禁用重复任务，报文件找不到，请问怎么解决
> 
> 我找人帮我重新写了一份 就好使了

我也解决了，地址改一下就行了

**Comment by ONELIANGGG** [comment]
> > > 我不能也禁止重复任务，报文件找不到，请问怎么解决
> > 
> > 
> > 我找人帮我重新写了一份就好了
> 
> 我也解决了，地址改一下就行了

能细说下吗？

**Comment by ONELIANGGG** [comment]
> nfig/

能分享下吗

**Comment by lucien2023** [comment]
你只需要更新到最新的青龙面板，之后重新拉一下源 就行啦，几个大佬已经适配过了

**Comment by ONELIANGGG** [comment]
> 你只需要更新到最新的青龙面板，之后重新拉一下源 就行啦，几个大佬已经适配过了

![image](https://user-images.githubusercontent.com/88072388/189537789-69ef489f-100b-4ab6-8c9d-fb1012278e95.png)
不行啊，能分享下库吗。

**Comment by lucien2023** [comment]
> 

你用的是谁的库？

**Comment by lucien2023** [comment]
> > 你只需要更新到最新的青龙面板，之后重新拉一下源 就行啦，几个大佬已经适配过了
> 
> ![image](https://user-images.githubusercontent.com/88072388/189537789-69ef489f-100b-4ab6-8c9d-fb1012278e95.png) 不行啊，能分享下库吗。

kr拉库
ql repo https://github.com/KingRan/KR.git "jd_|jx_|jdCookie" "activity|backUp" "^jd[^_]|USER|utils|function|sign|sendNotify|ql|JDJR"
时间0 3 * * *

拉库619
ql repo https://github.com/gys619/jdd.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace|JDJRValidator_|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD" "main"
时间0 3 * * *

**Comment by ONELIANGGG** [comment]
> > > 你只需要更新到最新的青龙面板，之后重新拉一下源 就行啦，几个大佬已经适配过了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/88072388/189537789-69ef489f-100b-4ab6-8c9d-fb1012278e95.png) 不行啊，能分享下库吗。
> 
> kr拉库 ql repo https://github.com/KingRan/KR.git "jd_|jx_|jdCookie" "activity|backUp" "^jd[^_]|USER|utils|function|sign|sendNotify|ql|JDJR" 时间0 3 * * *
> 
> 拉库619 ql repo https://github.com/gys619/jdd.git "jd_|jx_|jddj_|gua_|getJDCookie|wskey" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace|JDJRValidator_|sign_graphics_validate|jddj_cookie|function|ql|magic|JDJR|JD" "main" 时间0 3 * * *

谢谢
