### ISSUE TITLE
请问青龙的环境变量保存在哪个文件中呢？

### ISSUE THREAD

**Issue by whyichn** [whyour/qinglong#1097]
尝试过找env.ts config等，并没有找到。
动机是想要迁移容器到另一台电脑上，但是环境变量太多了懒得一个一个重复写。

**Comment by whyour** [comment]
在数据库里，db下的sqlite

**Comment by whyichn** [comment]
感谢，找到了

**Comment by jjjyyyllll** [comment]
> 在数据库里，db下的sqlite

db文件夹下并没有这个文件？ 只有crontab env app auth dependence等db文件？ 还是env这个？
