### ISSUE TITLE
对不懂的小白，windows虚拟机可能更方便一些，分享一个。请用户反馈。

### ISSUE THREAD

**Issue by jackadam1981** [whyour/qinglong#1099]
花了半小时，装了一个虚拟机。
https://cloud.189.cn/web/share?code=AryQZfbE3eAn（访问码：8aff）
ova格式，导入虚拟机即可。

注意网卡为桥接模式，linux用户名：root，密码：qinglong
进入linux， 输入ip addr（中间有空格）就可以看到虚拟机IP了，如果不是你的网段，那就是网卡模式没设为桥接模式。

默认带有watchtower，自动升级docker容器，可以说是跟随青龙升级。配置文件按青龙的说明，会被映射保存，自动升级docker容器，不丢配置。

访问你的linxuIP:5700,就可以开始青龙了。
依赖没搞。
有依赖问题再说吧。

**Comment by xiaofsu** [comment]
使用他人提供的青龙谨防被盗。

**Comment by Ubugs** [comment]
这么玩也太麻烦了吧 直接电脑安装docker 有电脑版的 然后拉青龙不就行了

**Comment by UniQiu** [comment]
首先谢谢大佬分享，直接导入到虚拟机里挺好用，目前存在一个问题，如何挂载文件夹，与本机共享，小白不懂，请大佬解决一下，谢谢🙏

**Comment by jackadam1981** [comment]
这是方便使用的虚拟机，有的人会装docker，有的人不会，有的人会装虚拟机，有的人不会。

基本没有挂载文件夹需求，脚本是通过命令来拉取的，无需下载。
青龙WEB面板也可以管理脚本，管理依赖，管理日志。

而且挂载文件夹，这是虚拟机和linux共同配置才能实现，也没多大必要。
