### ISSUE TITLE
大佬不出个Windows Server版本么

### ISSUE THREAD

**Issue by zhyueyueniao** [whyour/qinglong#1101]
服务器是Windows Server装不了青龙呢

**Comment by Ubugs** [comment]
你装个docker 然后拉青龙不就行了

**Comment by zhyueyueniao** [comment]
> 你装个docker 然后拉青龙不就行了

server不支持Linux docker，要装linux docker还能装个虚拟机，便宜服务器本来性能都不太好了，通过虚拟机装docker那不得卡死啊

**Comment by xiaoxiaofeixf** [comment]
> > 你装个docker 然后拉青龙不就行了
> 
> win server系统不支持Linux docker，要装linux docker还得装个虚拟机，便宜服务器本来性能都不太好了，通过虚拟机装docker那不得卡死啊

那你装linux服务器就行了

**Comment by jackadam1981** [comment]
是的，有什么是必须使用windows server么？
sql server 也有docker了。

**Comment by zhyueyueniao** [comment]
> 是的，有什么是必须使用windows server么？ sql server 也有docker了。

垃圾.net开发者还没法脱离windows，需要Windows服务器部署相关win专用服务和网站
