### ISSUE TITLE
jsdelivr挂了，进不去登录界面，麻烦更换下cdn

### ISSUE THREAD

**Issue by hexin1314** [whyour/qinglong#1106]
jsdelivr挂了，进不去登录界面，麻烦更换下cdn，（貌似可以替换为unpkg.zhimg.com）

**Comment by frsoul** [comment]
+1，顶一个

**Comment by lovemei2u4ever** [comment]
dev支线已经在改了[d3009f8](https://github.com/whyour/qinglong/commit/c5c41c085915d74672738003413ef37ac1921159)

**Comment by JoveYu** [comment]
大部分都是本地部署没必要用cdn啦    为什么不用本地文件？
