### ISSUE TITLE
新增加的定时任务怎么跑到最后面去啦！！

### ISSUE THREAD

**Issue by hubumulity** [whyour/qinglong#1107]

**Comment by weilai-all** [comment]
https://github.com/whyour/qinglong/commit/0eb9a1fdb0a79c3e9438f3a9c3cf2814213abb34

**Comment by hubumulity** [comment]
> [0eb9a1f](https://github.com/whyour/qinglong/commit/0eb9a1fdb0a79c3e9438f3a9c3cf2814213abb34)

请问可以改回来吗
