### ISSUE TITLE
2.11.1版本的 通知设置 无法更改

### ISSUE THREAD

**Issue by HeiSeven** [whyour/qinglong#1109]
如题，就比如我一开始设置了server酱方式，然后我想修改为pushplus，点击保存，测试成功，然后刷新，他还是显示为server酱的方式，然后我现在想关闭通知，修改之后保存，刷新之后，他还是提示为server酱方式

**Comment by dgzd** [comment]
我也遇到了无法设置通知的问题，提示 `Timeout awaiting 'request' for 10000ms`

**Comment by QiHsMing** [comment]
我改成pushplus，点击保存，显示通知设置失败。明明pushplus接口能用的
