### ISSUE TITLE
青龙v2.0.0-05122302 报错[PM2][WARN] panel doesn't exist

### ISSUE THREAD

**Issue by lxr760** [whyour/qinglong#111]
![image](https://user-images.githubusercontent.com/8476457/118006975-4df3b300-b37e-11eb-9a08-48dd88213705.png)
![Snipaste_2021-05-13_00-00-51](https://user-images.githubusercontent.com/8476457/118006984-51873a00-b37e-11eb-864c-b0d79544a389.jpg)

如图    报错      面板无法安装     导致docker自动退出

**Comment by whyour** [comment]
你这咋拉取不了gitee的代码，检查下你的网络

**Comment by lxr760** [comment]
> 你这咋拉取不了gitee的代码，检查下你的网络

找到原因了，最新的镜像不能选bridge桥接模式，不然就没有网络。选host可以

但是，之前1.几的版本是可以选桥接的，2.0第一个版本也可以。就是从后面开始的镜像选bridge就有问题。请大佬看下能否修复这个bug

**Comment by whyour** [comment]
docker run -ti --rm node:lts-alpine3.13 ping -c 1 me-api.jd.com 

你在你的机器上执行这个，看有没有输出

**Comment by lxr760** [comment]
> docker run -ti --rm node:lts-alpine3.13 ping -c 1 me-api.jd.com
> 
> 你在你的机器上执行这个，看有没有输出

![image](https://user-images.githubusercontent.com/8476457/118100609-3ca3b880-b409-11eb-9b5f-e3261ebcf8db.png)

**Comment by whyour** [comment]
> > docker run -ti --rm node:lts-alpine3.13 ping -c 1 me-api.jd.com
> > 你在你的机器上执行这个，看有没有输出
> 
> ![image](https://user-images.githubusercontent.com/8476457/118100609-3ca3b880-b409-11eb-9b5f-e3261ebcf8db.png)

你用最新的镜像另外起个容器试试，看能不能访问网络
![image](https://user-images.githubusercontent.com/22700758/118100939-a2904000-b409-11eb-9ca2-d5499a63d81e.png)

**Comment by lxr760** [comment]
> > > docker run -ti --rm node:lts-alpine3.13 ping -c 1 me-api.jd.com
> > > 你在你的机器上执行这个，看有没有输出
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/8476457/118100609-3ca3b880-b409-11eb-9b5f-e3261ebcf8db.png)
> 
> 你用最新的镜像另外起个容器试试，看能不能访问网络
> ![image](https://user-images.githubusercontent.com/22700758/118100939-a2904000-b409-11eb-9ca2-d5499a63d81e.png)

这个是截止目前最新的镜像吗？     能否以后在telegram更新日志里写一下这个digest的号

**Comment by cd382** [comment]
同样的问题，重建镜像后报错panel doesn't exist
