### ISSUE TITLE
jsdelivr 地址还存在 进不去配置文件页面

### ISSUE THREAD

**Issue by ergoucj** [whyour/qinglong#1112]
![image](https://user-images.githubusercontent.com/23370727/150629150-20aef9a3-73ce-4fcf-ad5c-a764d8149ec8.png)

**Comment by 592732377** [comment]
两种方法：
法1: 修改hosts  104.16.87.20 cdn.jsdelivr.net
法2:使用梯子访问jsdelivr.net。
