### ISSUE TITLE
脚本运行报错internal/modules/cjs/loader.js:883

### ISSUE THREAD

**Issue by a393310872** [whyour/qinglong#112]
日志-京东资产变动通知
开始执行...

Thu May 13 2021 00:32:39 GMT+0800 (中国标准时间)
ls: cannot access '/ql/log/code': No such file or directory

🔔京东资产变动通知, 开始!
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './jdCookie.js'
Require stack:
- /ql/scripts/chinnkarahoi_jd_bean_change.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/ql/scripts/chinnkarahoi_jd_bean_change.js:31:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/chinnkarahoi_jd_bean_change.js' ]
}

执行结束...

直接拉取的镜像.映射了.LOG CONFIG SCRIPTS DB目录.然后添加了https://ghproxy.com/https://github.com/chinnkarahoi/jd_scripts.git仓库.尝试运行某个脚本.就提示以上错误...

**Comment by Acr05s** [comment]
昨天 我也是这样，现在要新加一个映射目录 repo放脚本。

**Comment by sunyh87** [comment]
> 昨天 我也是这样，现在要新加一个映射目录 repo放脚本。

现在需要映射哪些文件夹啊 我怎么更新后 报错了
![`~C88H$R`03RL0NP1P`78$W](https://user-images.githubusercontent.com/20852855/118070151-f41fd700-b3d7-11eb-8939-c78d1a8caa68.png)

**Comment by Acr05s** [comment]
> > 昨天 我也是这样，现在要新加一个映射目录 repo放脚本。
> 
> 现在需要映射哪些文件夹啊 我怎么更新后 报错了
> ![~C88H$R03RL0NP1P`78$W](https://user-images.githubusercontent.com/20852855/118070151-f41fd700-b3d7-11eb-8939-c78d1a8caa68.png)

现在更新2.0后要把所有的定时任务删了重新拉一个库，因为命令格式已经变了，已经没有js 这个命令了，现在是 task

**Comment by sunyh87** [comment]
> > > 昨天 我也是这样，现在要新加一个映射目录 repo放脚本。
> > 
> > 
> > 现在需要映射哪些文件夹啊 我怎么更新后 报错了
> > ![~C88H$R03RL0NP1P`78$W](https://user-images.githubusercontent.com/20852855/118070151-f41fd700-b3d7-11eb-8939-c78d1a8caa68.png)
> 
> 现在更新2.0后要把所有的定时任务删了重新拉一个库，因为命令格式已经变了，已经没有js 这个命令了，现在是 task
只要增加一个repo文件夹映射吗？

**Comment by whyour** [comment]
> > > > 昨天 我也是这样，现在要新加一个映射目录 repo放脚本。
> > > 
> > > 
> > > 现在需要映射哪些文件夹啊 我怎么更新后 报错了
> > > ![~C88H$R03RL0NP1P`78$W](https://user-images.githubusercontent.com/20852855/118070151-f41fd700-b3d7-11eb-8939-c78d1a8caa68.png)
> > 
> > 
> > 现在更新2.0后要把所有的定时任务删了重新拉一个库，因为命令格式已经变了，已经没有js 这个命令了，现在是 task
> > 只要增加一个repo文件夹映射吗？

删除镜像容器，重新拉，你这都啥时候的了，把映射目录删了

**Comment by sunyh87** [comment]
> > > 昨天 我也是这样，现在要新加一个映射目录 repo放脚本。
> > 
> > 
> > 现在需要映射哪些文件夹啊 我怎么更新后 报错了
> > ![~C88H$R03RL0NP1P`78$W](https://user-images.githubusercontent.com/20852855/118070151-f41fd700-b3d7-11eb-8939-c78d1a8caa68.png)
> 
> 现在更新2.0后要把所有的定时任务删了重新拉一个库，因为命令格式已经变了，已经没有js 这个命令了，现在是 task

![A2TKOEAL95GE1P$VY@`{@C7](https://user-images.githubusercontent.com/20852855/118078435-cb540d80-b3e8-11eb-8b4a-1cac27bf37bf.png)
映射了repo 怎么也是这样
