### ISSUE TITLE
手动部署

### ISSUE THREAD

**Issue by a512154224** [whyour/qinglong#1122]
大佬，什么时候完善手动部署，我根据Dockerfile安装的，每次打开都是提示执行ql check，但是执行后还是打不开，很多报错的

**Comment by xiaoxiaofeixf** [comment]
> 大佬，什么时候完善手动部署，我根据Dockerfile安装的，每次打开都是提示执行ql check，但是执行后还是打不开，很多报错的

手动部署后不能拉库，总之很bug

**Comment by a512154224** [comment]
是缺少命令吧，像ql、task等等这些命令没有的，昨天试了部署成功了，但是重启后又起不来了，今天在研究下
