### ISSUE TITLE
请问，面板->环境变量->每行变量的备注。备注是保存在青龙的哪个位置？

### ISSUE THREAD

**Issue by DeSireFire** [whyour/qinglong#1123]
请问，面板->环境变量->每行变量的备注。备注是保存在青龙的哪个位置？
![image](https://user-images.githubusercontent.com/18726905/151116169-dabcac4f-db92-4371-a459-c2b0ce9cc9df.png)
相关变量信息，可以在/ql/config/env.sh中找到，
但是备注信息却不知道是保存在什么地方。
是保存在哪里的？想拿到变量和备注的对应关系应该怎么做？

**Comment by Purple-wind-bell** [comment]
应该是db/database.sqlite的数据库里

**Comment by DeSireFire** [comment]
> db/database.sqlite

好的，感谢！
