### ISSUE TITLE
由于网络波动导致所有任务被删除

### ISSUE THREAD

**Issue by Jiaswa** [whyour/qinglong#1124]
日志如下：
`更新/ql/repo/Aaron-lv_sync_jd_scripts失败，重新下载全新仓库...

开始克隆仓库 https://github.com/Aaron-lv/sync.git 到 /ql/repo/Aaron-lv_sync_jd_scripts

更新/ql/repo/Aaron-lv_sync_jd_scripts成功...

检测到有失效的定时任务：
…
…
…
开始尝试自动删除失效的定时任务...`

由于众所周知的原因，github国内访问并不稳定，ghproxy 也并非百分百保险，如果ql repo 拉取的时候刚好网络不可达的话，整个仓库的任务就会全部被删除。
是否考虑在更新失败的时候忽略，而不是重新下载，因为重新下载也失败的话，就是个空的仓库。

**Comment by whyour** [comment]
重新下载失败是不会进行比对脚本的。最新的获取拉取状态有点问题
