### ISSUE TITLE
请问无法打来面板 运行ql check 出现SQLITE_BUSY: database is locked怎么解决呀 

### ISSUE THREAD

**Issue by gx19970920** [whyour/qinglong#1126]
请问无法打来面板 运行ql check 出现SQLITE_BUSY: database is locked怎么解决呀

**Comment by SunnyQQQ** [comment]
我也是，更新面板也没反应了，是不是只能重装了

**Comment by gx19970920** [comment]
我重装之后也是这个提示，不知道什么办法可以解决

**Comment by gx19970920** [comment]
现在已知可以在终端机运行ql check然后莫名其妙就可可以登上了
