### ISSUE TITLE
Cookie己加，但任务执行一直提票没有cookie

### ISSUE THREAD

**Issue by seasky8866** [whyour/qinglong#113]
====================共0个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/5/13 上午6:58:49=====================

==============📣系统通知📣==============
半点京豆雨
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取
https://bean.m.jd.com/

**Comment by seasky8866** [comment]
> ====================共0个京东账号Cookie=========
> 
> ==================脚本执行- 北京时间(UTC+8)：2021/5/13 上午6:58:49=====================
> 
> ==============📣系统通知📣==============
> 半点京豆雨
> 【提示】请先获取京东账号一cookie
> 直接使用NobyDa的京东签到获取
> https://bean.m.jd.com/

**Comment by hbin** [comment]
请问这个问题如何解决？
