### ISSUE TITLE
2.11.2 update错误

### ISSUE THREAD

**Issue by zhengwz** [whyour/qinglong#1131]
升级2.11.2后，打不开了，ql ckeck也没用。

**Comment by whyour** [comment]
@zhengwz 再更新一次

**Comment by FDrag0n** [comment]
一样的问题，面板显示异常，让ql check。但是ql check是通过的

**Comment by zhengwz** [comment]
再ql update一次也是通过没报错。但是就是异常进不去。

**Comment by mishi321** [comment]
![image](https://user-images.githubusercontent.com/75570320/151705224-e97e0d06-56c1-408d-811b-1274c2a4c447.png)
ql check 两次后好像正常了能进去了,中间ql update好像没反应给终止掉了

**Comment by FDrag0n** [comment]
试了好多次ql check，还是显示：”服务异常，请手动执行ql check检查服务状态

**Comment by zhengwz** [comment]
![Screenshot_2022-01-31-00-12-30-850_com sonelli juicessh](https://user-images.githubusercontent.com/20317922/151707596-d305d41e-ea88-4f5b-adf7-56dc49f00e50.jpg)
![Screenshot_2022-01-31-00-12-36-050_com sonelli juicessh](https://user-images.githubusercontent.com/20317922/151707598-3eae08b0-8f6f-40c1-8b28-63eabd28bbc1.jpg)
执行ql check的部分日志

**Comment by smdk000** [comment]
我也遇到了同样的问题，貌似不是少数人都遇到了同样的问题

**Comment by zhengwz** [comment]
大佬，有没有指令回退版本，我想先回退到上两个版本先用着。。。

**Comment by bonnyandsky** [comment]
lz解决了么？我更新后也这样了

**Comment by bonnyandsky** [comment]
> lz解决了么？我更新后也这样了

暂时拉了2.10.12的镜像，能用上了

**Comment by zhengwz** [comment]
@bonnyandsky 还没解决，还是打不开。
@whyour 大佬什么时候有空处理一下，或者回退一下版本。

**Comment by HongjieCN** [comment]
这是一个网络问题，手动进入容器bash，进入/ql/config，用vi编辑config.sh，把GithubProxyUrl=""里面填入https://ghproxy.com/即可，估计是你拉库的时候把代理去掉了，然后更新的时候无法获取最新文件导致的。

**Comment by zhengwz** [comment]
> 这是一个网络问题，手动进入容器bash，进入/ql/config，用vi编辑config.sh，把GithubProxyUrl=""里面填入https://ghproxy.com/ 即可，估计是你拉库的时候把代理去掉了，然后更新的时候无法获取最新文件导致的。

不是代理问题，国外机，更新时拉文件正常。

**Comment by bugme2** [comment]
arm设备panel同款错误
ql check无效果
![Screenshot_2022-02-02-01-09-47-64_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/40169265/152016528-a4b2bceb-7178-49b7-9296-3747bb5a31aa.jpg)

**Comment by zhengwz** [comment]
@bonnyandsky @FDrag0n @smdk000 兄弟们，找到问题及解决方法了。
#进入容器内
docker exec -it qinglong bash

#查看占用5700端口的进程(或者你青龙面板修改成了其他端口)
netstat -ntlp

#kill掉占用端口的进程(我这里是nginx)
kill -9 PID

#重新update
ql update

**Comment by naiveclub** [comment]
> @bonnyandsky @FDrag0n @smdk000 兄弟们，找到问题及解决方法了。
> #进入容器内
> docker exec -it qinglong bash
> 
> #查看占用5700端口的进程(或者你青龙面板修改成了其他端口)
> netstat -ntlp
> 
> #kill掉占用端口的进程(我这里是nginx)
> kill -9 PID
> 
> #重新update
> ql update

我执行 ql update之后就没有反应了。。。

**Comment by ryan016** [comment]
> ql update

按照你的方法，成功解决问题了，谢谢！！！

**Comment by ryan016** [comment]
不过手动运行脚本，“暂无日志”显示。。。

**Comment by bertms** [comment]
还是不行，如何回退版本

**Comment by wxmbaci** [comment]
我今天（2.4）升级的，看报错，是cdn有问题。

**Comment by caowenwei** [comment]
> @bonnyandsky @FDrag0n @smdk000 兄弟们，找到问题及解决方法了。 #进入容器内 docker exec -it qinglong bash
> 
> #查看占用5700端口的进程(或者你青龙面板修改成了其他端口) netstat -ntlp
> 
> #kill掉占用端口的进程(我这里是nginx) kill -9 PID
> 
> #重新update ql update

按照这个操作，面板恢复能用了。
ql update的最后阶段报错这个，没搜到解决方法
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)

**Comment by caowenwei** [comment]
> > @bonnyandsky @FDrag0n @smdk000 兄弟们，找到问题及解决方法了。 #进入容器内 docker exec -it qinglong bash
> > #查看占用5700端口的进程(或者你青龙面板修改成了其他端口) netstat -ntlp
> > #kill掉占用端口的进程(我这里是nginx) kill -9 PID
> > #重新update ql update
> 
> 按照这个操作，面板恢复能用了。 ql update的最后阶段报错这个，没搜到解决方法 nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)

![image](https://user-images.githubusercontent.com/1859735/161543701-40c0d122-bac8-41e0-9232-11f27ad4c36f.png)
