### ISSUE TITLE
ql command not found

### ISSUE THREAD

**Issue by zhxingway** [whyour/qinglong#1132]
![image](https://user-images.githubusercontent.com/43720357/151712211-0a2dc824-f50f-49a6-a89a-be0f25727c0a.png)

面板又可以正常使用的，这是咱回事呢？

**Comment by cc9014** [comment]
需要先进入容器。docker exec -it qinglong bash

**Comment by zhxingway** [comment]
> docker exec -it qinglong bash

非常感谢。
