### ISSUE TITLE
登录提示执行ql check,进入容器执行ql check无响应

### ISSUE THREAD

**Issue by bertms** [whyour/qinglong#1134]
一直无法登录，重启面板，重启服务器都试过了。

**Comment by xxyyyx** [comment]
一样 有解决方案吗

**Comment by Karmylr** [comment]
手残升级了吧

**Comment by zhengwz** [comment]
暂时也是没找到解决方案，定时任务还能运行，就暂时用着，等大佬更新了。

**Comment by zhengwz** [comment]
> > 暂时也是没找到解决方案，定时任务还能运行，就暂时用着，等大佬更新了。
> 
> 我退了版本 就能用了

怎么退版本？

**Comment by Karmylr** [comment]
> > > 暂时也是没找到解决方案，定时任务还能运行，就暂时用着，等大佬更新了。
> > 
> > 
> > 我退了版本 就能用了
> 
> 怎么退版本？

重装

**Comment by zhengwz** [comment]
> > > > 暂时也是没找到解决方案，定时任务还能运行，就暂时用着，等大佬更新了。
> > > 
> > > 
> > > 我退了版本 就能用了
> > 
> > 
> > 怎么退版本？
> 
> 重装

😂懒得折腾了，定时任务后台还能运行就先不管了，等更新。

**Comment by HongjieCN** [comment]
手动进入/ql/config/config.sh 把代理加回去，然后再ql update就好了

**Comment by bertms** [comment]
> 

加在什么位置我是国外机

**Comment by zhengwz** [comment]
@xxyyyx @bertms @Karmylr  兄弟们，找到问题及解决方法了。
#进入容器内
docker exec -it qinglong bash

#查看占用5700端口的进程(或者你青龙面板修改成了其他端口)
netstat -ntlp

#kill掉占用端口的进程(我这里是nginx)
kill -9 PID

#重新update
ql update

**Comment by bertms** [comment]
我还是一样，ql check可以成功运行，但是还是进不去面板。
 WARN  GET https://registry.npm.taobao.org/pnpm error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npm.taobao.org/@sentry%2Fnode error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npm.taobao.org/@sentry%2Ftracing error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npm.taobao.org/darkreader error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npm.taobao.org/esbuild error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npm.taobao.org/@sentry%2Freact error (undefined). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npm.taobao.org/concurrently error (undefined). Will retry in 10 seconds. 2 retries left.
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 9, reused 9, downloaded 0, added 0
Progress: resolved 17, reused 17, downloaded 0, added 0
Progress: resolved 18, reused 17, downloaded 0, added 0
Progress: resolved 29, reused 29, downloaded 0, added 0
Progress: resolved 36, reused 36, downloaded 0, added 0
Progress: resolved 51, reused 51, downloaded 0, added 0
 WARN  GET https://registry.npm.taobao.org/pnpm error (undefined). Will retry in 1 minute. 1 retries left.
Progress: resolved 64, reused 64, downloaded 0, added 0
 WARN  GET https://registry.npm.taobao.org/@sentry%2Fnode error (undefined). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npm.taobao.org/@sentry%2Ftracing error (undefined). Will retry in 1 minute. 1 retries left.
Progress: resolved 67, reused 67, downloaded 0, added 0
 WARN  GET https://registry.npm.taobao.org/darkreader error (undefined). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npm.taobao.org/esbuild error (undefined). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npm.taobao.org/@sentry%2Freact error (undefined). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npm.taobao.org/concurrently error (undefined). Will retry in 1 minute. 1 retries left.
Progress: resolved 68, reused 67, downloaded 0, added 0
Progress: resolved 70, reused 70, downloaded 0, added 0
Progress: resolved 71, reused 70, downloaded 0, added 0
Progress: resolved 73, reused 73, downloaded 0, added 0
 ERROR  invalid json response body at https://registry.npm.taobao.org/pnpm reason: Unexpected token  in JSON at position 0

**Comment by Edcwsyh** [comment]
> > > 暂时也是没找到解决方案，定时任务还能运行，就暂时用着，等大佬更新了。
> > 
> > 
> > 我退了版本 就能用了
> 
> 怎么退版本？

docker exec -it [容器名称] /bin/sh -c 'bash' 登录到docker容器
git log显示提交记录找到需要回退的版本
git -reset --hard [需要回退的版本]
ql check
就可以了, 目前我回退到了d3009f82dd9698aac02c81b050427b8d3784bb40这个提交, 已经可以登录到面板了

**Comment by zhengwz** [comment]
> > > > 暂时也是没找到解决方案，定时任务还能运行，就暂时用着，等大佬更新了。
> > > 
> > > 
> > > 我退了版本 就能用了
> > 
> > 
> > 怎么退版本？
> 
> docker exec -it [容器名称] /bin/sh -c 'bash' 登录到docker容器 git log显示提交记录找到需要回退的版本 git -reset --hard [需要回退的版本] ql check 就可以了, 目前我回退到了d3009f82dd9698aac02c81b050427b8d3784bb40这个提交, 已经可以登录到面板了

我回退到2.10.12后还是不行，我又执行了如下操作
pm2 stop all
ql update
这次更新到2.11.2后就能正常使用了，感觉应该是跟ninja冲突了。

**Comment by ddkk3000** [comment]
我也遇到这个问题解决不了。

**Comment by yuhuangniu** [comment]
> 

老哥的这个解决方法有用，进入容器然后执行：
`git reset --hard d3009f82dd9698aac02c81b050427b8d3784bb40`
在执行：
`ql check`
即可。

**Comment by yuhuangniu** [comment]
> > > > 暂时也是没找到解决方案，定时任务还能运行，就暂时用着，等大佬更新了。
> > > 
> > > 
> > > 我退了版本 就能用了
> > 
> > 
> > 怎么退版本？
> 
> docker exec -it [容器名称] /bin/sh -c 'bash' 登录到docker容器 git log显示提交记录找到需要回退的版本 git -reset --hard [需要回退的版本] ql check 就可以了, 目前我回退到了d3009f82dd9698aac02c81b050427b8d3784bb40这个提交, 已经可以登录到面板了

老哥的这个解决方法有用，进入容器然后执行：
`git reset --hard d3009f82dd9698aac02c81b050427b8d3784bb40`
在执行：
`ql check`
即可。

**Comment by kekeguai** [comment]
git reset --hard d3009f82dd9698aac02c81b050427b8d3784bb40
HEAD is now at d3009f8 移除默认github代理，增加http或者socks代理参数

**Comment by ddkk3000** [comment]
> ql check

仍然不行啊

**Comment by ddkk3000** [comment]
突然好了，有点奇怪。

**Comment by bertms** [comment]
我只能删除容器重新弄才对。

**Comment by lovestudygithub** [comment]
> > > > > 暂时也是没找到解决方案，定时任务还能运行，就暂时用着，等大佬更新了。
> > > > 
> > > > 
> > > > 我退了版本 就能用了
> > > 
> > > 
> > > 怎么退版本？
> > 
> > 
> > docker exec -it [容器名称] /bin/sh -c 'bash' 登录到docker容器 git log显示提交记录找到需要回退的版本 git -reset --hard [需要回退的版本] ql check 就可以了, 目前我回退到了d3009f82dd9698aac02c81b050427b8d3784bb40这个提交, 已经可以登录到面板了
> 
> 我回退到2.10.12后还是不行，我又执行了如下操作 pm2 stop all ql update 这次更新到2.11.2后就能正常使用了，感觉应该是跟ninja冲突了。

感谢，用你的办法搞定了，但是我没安装ninja，可能与ninja无关。

我是注析掉了加速代理，而且本地有旁路由，所以连仓库的加速代理也去掉了https://ghproxy.com/。

**Comment by weishaopenggege** [comment]
> > > > > 暂时也是没找到解决方案，定时任务还能运行，就暂时用着，等大佬更新了。
> > > > 
> > > > 
> > > > 我退了版本 就能用了
> > > 
> > > 
> > > 怎么退版本？
> > 
> > 
> > docker exec -it [容器名称] /bin/sh -c 'bash' 登录到docker容器 git log显示提交记录找到需要回退的版本 git -reset --hard [需要回退的版本] ql check 就可以了, 目前我回退到了d3009f82dd9698aac02c81b050427b8d3784bb40这个提交, 已经可以登录到面板了
> 
> 我回退到2.10.12后还是不行，我又执行了如下操作 pm2 stop all ql update 这次更新到2.11.2后就能正常使用了，感觉应该是跟ninja冲突了。

解决了, 百度跟谷歌都解决不了, 还好看到你这个

**Comment by xufeiwu123** [comment]
能看下完整命令嘛？

**Comment by xufeiwu123** [comment]
> 可以看看你的完整命令嘛？

**Comment by haohongwei** [comment]
> 可以看看你的完整命令嘛？

docker exec -it qinglong bash
git reset --hard d3009f82dd9698aac02c81b050427b8d3784bb40
ql check
pm2 stop all
ql update

**Comment by Edisonmai** [comment]
> 

终于解决了，就是端口占用了
