### ISSUE TITLE
我发现安装2.11以上版本后添加多个库任务的时候，无法禁用重复的任务

### ISSUE THREAD

**Issue by homestoo** [whyour/qinglong#1135]
版本2.11/2.11.1/2.11.2都有安装试过，都会出现这个问题，添加多个库相同的任务时候，无法禁用重复的，退回2.10.9和2.10.13的时候都是可以禁用重复的，不知道是不是bug,有出现同样情况的吗

**Comment by zhengwz** [comment]
这个问题2.11.1的时候就发现了

**Comment by homestoo** [comment]
> 这个问题2.11.1的时候就发现了

我也是安装升级到2.11.1的时候发现的，然后升级到2.11.2还是有，还以为自己服务器的问题。。然后每个版本都试来遍，发现是2.11以上都有这情况😅
