### ISSUE TITLE
N1新装的2.11.2，感觉资源占用更多了，Load Average经常破2

### ISSUE THREAD

**Issue by keai-1989** [whyour/qinglong#1136]
以前用的话，同时运行三五个任务的话Load Average显示0.5甚至更低

现在升级到2.11.2      哪怕一个任务都不运行Load Average就几乎在1左右徘徊。

运行三五个任务在1.5左右，有时能升到2

有没有也是N1用的2.11.2？Load Average也是变高了吗？

**Comment by passengerya** [comment]
青龙版本为2.10.3，你的固件负载低吗，我的不装傻妞和nodeonebot，负载在个位数，跑的时候20%；但是装了傻妞和nodeonebot之后，负载不知道为什么又是就飙升，

**Comment by passengerya** [comment]
![Screenshot_20220213_015213_com sonelli juicessh](https://user-images.githubusercontent.com/88080424/153722401-91cb6fcb-7eb2-4cb3-b309-79b3e0abd5b3.jpg)
并没有

**Comment by passengerya** [comment]
并没有，看图
![Uploading Screenshot_20220213_015213_com.sonelli.juicessh_edit_92406832868190.jpg…]()

**Comment by passengerya** [comment]
![Uploading Screenshot_20220213_015213_com.sonelli.juicessh_edit_92406832868190.jpg…]()
