### ISSUE TITLE
Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by Karmylr** [whyour/qinglong#1137]
![image](https://user-images.githubusercontent.com/69903376/152321295-3ba5215f-6dca-4b66-a785-bb6af3693a3f.png)

**Comment by Plus-xu** [comment]
遇到了同样的问题，容器内能ping通，但是通知里设置正确的TG ID后依然400 无法发送通知

**Comment by 9528apcx** [comment]
Server酱也是，填入SendKey时也报这个错误
