### ISSUE TITLE
nginx反代 location /正常访问but设置^~/ql访问404

### ISSUE THREAD

**Issue by RatedR9** [whyour/qinglong#1138]
location  ^~/ql{
 proxy_pass http://127.0.0.1:5700;
            proxy_http_version    1.1;
            proxy_cache_bypass    $http_upgrade;
            proxy_set_header Upgrade            $http_upgrade;
            proxy_set_header Connection         "upgrade";
            proxy_set_header Host               $host;
            proxy_set_header X-Real-IP          $remote_addr;
            proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto  $scheme;
            proxy_set_header X-Forwarded-Host   $host;
            proxy_set_header X-Forwarded-Port   $server_port;

}

**Comment by HongjieCN** [comment]
location / {
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://localhost:5700;
        }

直接这样就可以访问所有青龙功能了，不如设置二级域名，不要用/ql的形式，设置ql.xxx.com即可

**Comment by linrol** [comment]
希望大佬能在启动参数加个设置青龙面板访问路径的，类似于--prefix=/ql，这个问题就能解决了

**Comment by tashifool** [comment]
同问这个问题有什么解决办法？
