### ISSUE TITLE
有些通知发4遍

### ISSUE THREAD

**Issue by woboo110** [whyour/qinglong#114]
大佬，有些通知连发4遍是怎么回事，京喜农场

**Comment by whyour** [comment]
> 大佬，有些通知连发4遍是怎么回事，京喜农场

搜下定时任务是不是多个，删了其他的

**Comment by woboo110** [comment]
> > 大佬，有些通知连发4遍是怎么回事，京喜农场
> 
> 搜下定时任务是不是多个，删了其他的
定时任务不是多个，目前东东农场和京喜农场是连着4遍通知

**Comment by whyour** [comment]
@woboo110 删除容器镜像，保留db下的数据，你的config.sh重新来一下

**Comment by woboo110** [comment]
> @woboo110 删除容器镜像，保留db下的数据，你的config.sh重新来一下

好的
