### ISSUE TITLE
如何使用代理跑脚本，而不是只在拉库时生效

### ISSUE THREAD

**Issue by usjinbao** [whyour/qinglong#1144]
请问我想把青龙任务都通过代理IP执行怎么弄，这样我就只需要不定时的更换代理服务器的IP，而不需要在青龙服务器做任何操作
我用这个只在拉库时候流量经过代理服务器export ALL_PROXY="socks://XXX:XXX"

**Comment by xx668888** [comment]
我也想  不知道怎么弄

**Comment by RoromoriYuzu** [comment]
我也想按网上的教程设置环境变量，shell可以走代理，但js还是没有

**Comment by CN-YoungYang** [comment]
你们解决这个问题了么
