### ISSUE TITLE
Telegram通知总是失败

### ISSUE THREAD

**Issue by MilesPoupart** [whyour/qinglong#1145]
最近青龙面板的Telegram通知总是失败，软路由上的代理正常，可以正常拉库，同一软路由下的设备也能正常访问telegram，`docker -exec -it qinglong bash`后执行`curl https://api.telegram.org/botxxx:xxx/sendMessage`能得到`{"ok":false,"error_code":400,"description":"Bad Request: message text is empty"}`的结果，但是脚本执行和系统设置-通知设置中总是会报以下异常（这也导致每次登录面板时总要等待一段时间）：

```
telegram发送通知消息失败！！

RequestError: Timeout awaiting 'request' for 15000ms
    at ClientRequest.<anonymous> (/ql/scripts/node_modules/.pnpm/registry.npmmirror.com+got@11.8.3/node_modules/got/dist/source/core/index.js:962:65)
    at Object.onceWrapper (node:events:640:26)
    at ClientRequest.emit (node:events:532:35)
    at ClientRequest.origin.emit (/ql/scripts/node_modules/.pnpm/registry.npmmirror.com+@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Timeout.timeoutHandler [as _onTimeout] (/ql/scripts/node_modules/.pnpm/registry.npmmirror.com+got@11.8.3/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1644242820131,
    socket: 1644242820134,
    lookup: 1644242820179,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1644242835139,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 45,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 15008
    }
  },
  event: 'request'
}
```
使用pushplus和iGot等不需要代理的通知则无此问题。这一问题是在某次容器重启后出现的，后来多次重启容器、重装容器、重拉镜像重装容器、重刷系统重拉镜像重装容器、更换代理、更换代理插件也没能解决。
想请教下应该如何排查解决这一问题，谢谢！

**Comment by yrwy** [comment]
docker的DNS解析不对。。。

**Comment by MilesPoupart** [comment]
> docker的DNS解析不对。。。

感谢！已排查到是软路由SmartDNS的配置问题，已解决。

**Comment by showme2005** [comment]
> > docker的DNS解析不对。。。
> 
> 感谢！已排查到是软路由SmartDNS的配置问题，已解决。

可以告知一下解决方法吗?谢谢.我也是和你一样..但是我设置通知机械人的时候 直接 是400错误

**Comment by MilesPoupart** [comment]
> > > docker的DNS解析不对。。。
> > 
> > 
> > 感谢！已排查到是软路由SmartDNS的配置问题，已解决。
> 
> 可以告知一下解决方法吗?谢谢.我也是和你一样..但是我设置通知机械人的时候 直接 是400错误

因为我的代理节点不支持ipv6，但smartDNS会把api.telegram.org解析到一个ipv6的地址，我的解决方法是开启了smartDns用于解析海外地址的服务器的Force AAAA SOA选项，应该是强制解析到ipv4地址。如果你没有使用smartDNS，你也可以尝试在代理中换一个DNS服务器。

**Comment by hashming** [comment]
> > > > docker的DNS解析不对。。。
> > > 
> > > 
> > > 感谢！已排查到是软路由SmartDNS的配置问题，已解决。
> > 
> > 
> > 可以告知一下解决方法吗?谢谢.我也是和你一样..但是我设置通知机械人的时候 直接 是400错误
> 
> 因为我的代理节点不支持ipv6，但smartDNS会把api.telegram.org解析到一个ipv6的地址，我的解决方法是开启了smartDns用于解析海外地址的服务器的Force AAAA SOA选项，应该是强制解析到ipv4地址。如果你没有使用smartDNS，你也可以尝试在代理中换一个DNS服务器。

大佬有教程或者完整的步骤吗，看您的文字说明还是不太懂

**Comment by MilesPoupart** [comment]
> > > > > docker的DNS解析不对。。。
> > > > 
> > > > 
> > > > 感谢！已排查到是软路由SmartDNS的配置问题，已解决。
> > > 
> > > 
> > > 可以告知一下解决方法吗?谢谢.我也是和你一样..但是我设置通知机械人的时候 直接 是400错误
> > 
> > 
> > 因为我的代理节点不支持ipv6，但smartDNS会把api.telegram.org解析到一个ipv6的地址，我的解决方法是开启了smartDns用于解析海外地址的服务器的Force AAAA SOA选项，应该是强制解析到ipv4地址。如果你没有使用smartDNS，你也可以尝试在代理中换一个DNS服务器。
> 
> 大佬有教程或者完整的步骤吗，看您的文字说明还是不太懂

我是在软路由上的docker里部署的青龙，可能你使用的是其他环境下的docker，可以检查下你的docker、对应容器或所用代理的DNS配置...

**Comment by lazygoat644** [comment]
挺好的讨论。同时补充一个情况，青龙面板的”配置文件“和”系统通知“给telegram设置的反代地址参数并不通用……如果两个地方都设置了相关参数的朋友遇到了”系统通知“部分检测正常，但js通知错误的情况，可以检查一下。

**Comment by LevineWoo** [comment]
我现在是面板进不去。登录不了。账号密码也是对的。很神奇，点了登录就一直在转圈，重新拉镜像重装过整个青龙都是一样的。

**Comment by D-Jie01** [comment]
你好，我情况和你一模一样。我现在op是旁路由，配置dns，然后centos 安装的docker（安装青龙），我设置其实都是以前的设置，没有变动过。今天突然就不能通知的。  青龙系统设置里面的通知正常，但是任务的通知就提示你这个代码。
想问下，这个的话，是需要我去op设置dns？ （我也开了IPv6的）
