### ISSUE TITLE
Qinglong API 文档

### ISSUE THREAD

**Issue by Ukenn2112** [whyour/qinglong#1151]
# Qinglong API 文档 （第三方）

- 文档链接：https://qinglong.ukenn.top/

- 文档项目：https://github.com/Ukenn2112/qinglongAPI_doc

# 说明

- 此文档使用 [Swagger-Editor](https://github.com/swagger-api/swagger-editor) 编写
- 此文档是我根据 [qinglong api 源码](https://github.com/whyour/qinglong/tree/develop/back/api) 自己理解编写，可能有表述等不正确的，欢迎 PR 修正，同时也欢迎参与编写
- 文档中的`【未知问题】`为不清楚具体是如何使用或是使用错误未知解决办法的标识，如果您知道具体的使用或者解决方法，欢迎在**文档项目**发送issue提出

**Comment by kidoneself** [comment]
你好，我想问一下通过appid获取到的token 如何使用，两份token不太相同

**Comment by Ukenn2112** [comment]
> 你好，我想问一下通过appid获取到的token 如何使用，两份token不太相同

都是一样用法吧 放入请求头里
![image](https://user-images.githubusercontent.com/60847880/155131532-179cfd08-97cf-4990-8723-8c143953ef69.png)

**Comment by kidoneself** [comment]
![GB$20H$DFH144SMIAQOWKU](https://user-images.githubusercontent.com/47913364/155132630-71a1e9b6-e3e1-48cf-88a3-5d46c3249b69.png)
我这样使用添加对变量进行操作都是验证不通过么，我想问一下，需要怎么操作变量通过api调用，是我其他地方错了么。

**Comment by Ukenn2112** [comment]
> ![GB$20H$DFH144SMIAQOWKU](https://user-images.githubusercontent.com/47913364/155132630-71a1e9b6-e3e1-48cf-88a3-5d46c3249b69.png) 我这样使用添加对变量进行操作都是验证不通过么，我想问一下，需要怎么操作变量通过api调用，是我其他地方错了么。

目前envs的post添加有点问题貌似，我请求也是这样返回500

**Comment by kidoneself** [comment]
解决了，他这envs添加我是实际是支持批量的，所以是个list，改成数组就行了

**Comment by Ukenn2112** [comment]
> 解决了，他这envs添加我是实际是支持批量的，所以是个list，改成数组就行了

是么，原来是这样

**Comment by snow922841** [comment]
打不开网站啊

**Comment by Ukenn2112** [comment]
> 打不开网站啊

？？打得开啊我这

**Comment by snow922841** [comment]
> > 打不开网站啊
> 
> ？？打得开啊我这

可以了

**Comment by snow922841** [comment]
> > 打不开网站啊
> 
> ？？打得开啊我这

大佬方便留个TG咨询一下问题吗

**Comment by ImWhyZf** [comment]
![image](https://user-images.githubusercontent.com/19197480/155909049-2d8de0a1-3203-482e-b4f7-fb2829d75929.png)
认证信息放这个里面

**Comment by Ukenn2112** [comment]
> ![image](https://user-images.githubusercontent.com/19197480/155909049-2d8de0a1-3203-482e-b4f7-fb2829d75929.png) 认证信息放这个里面

你IP都不打个码的么

**Comment by ImWhyZf** [comment]
忘记了。修改了一下，你回复的删除一下把

**Comment by snow922841** [comment]
用python put一直500，好难搞哦。

**Comment by JoeJoeLam** [comment]
> ![GB$20H$DFH144SMIAQOWKU](https://user-images.githubusercontent.com/47913364/155132630-71a1e9b6-e3e1-48cf-88a3-5d46c3249b69.png) 我这样使用添加对变量进行操作都是验证不通过么，我想问一下，需要怎么操作变量通过api调用，是我其他地方错了么。

这个是怎么部署的呢？

**Comment by ImWhyZf** [comment]
把token &nbsp;放到认证里面



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JoeJoeLam ***@***.***&gt;
发送时间: 2022年3月21日 18:31
收件人: whyour/qinglong ***@***.***&gt;
抄送: 佛系撸码人 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[whyour/qinglong] Qinglong API 文档 (Issue #1151)





  
 我这样使用添加对变量进行操作都是验证不通过么，我想问一下，需要怎么操作变量通过api调用，是我其他地方错了么。
  
这个是怎么部署的呢？

**Comment by Ukenn2112** [comment]
> > ![GB$20H$DFH144SMIAQOWKU](https://user-images.githubusercontent.com/47913364/155132630-71a1e9b6-e3e1-48cf-88a3-5d46c3249b69.png) 我这样使用添加对变量进行操作都是验证不通过么，我想问一下，需要怎么操作变量通过api调用，是我其他地方错了么。
> 
> 
> 
> 这个是怎么部署的呢？

postman

**Comment by suhuamo** [comment]
感谢大佬，终于找到解决的办法了。
