### ISSUE TITLE
求取消 ql 命令中自动增加的https://ghproxy.com/ 加速服务

### ISSUE THREAD

**Issue by singyueyang** [whyour/qinglong#1152]
因为部分仓库被 https://ghproxy.com/ 给拉到黑名单了，现在使用ql 命令仍然会增加 https://ghproxy.com/ 加速，导致仓库无法拉取，求各位大佬如何才能取消自动增加的这个加速代理呢？

**Comment by Acr05s** [comment]
早就没了，是不是还没删除config.sh里面的配置项

**Comment by singyueyang** [comment]
> 早就没了，是不是还没删除config.sh里面的配置项

感谢感谢，学到新技能了。

**Comment by chj-damon** [comment]
请问这个config.sh 是在哪里？我的windows上不知道怎么找
