### ISSUE TITLE
服务异常,请手动执行ql check检查服务状态

### ISSUE THREAD

**Issue by xufeiwu123** [whyour/qinglong#1157]
![111838a031417541](https://user-images.githubusercontent.com/34909400/153706160-86409601-1faf-4550-a4ad-82bc6c6aeb67.png)
里面的脚本可以运行，但是就是无法访问面板

**Comment by Inliang** [comment]
“提示 ql check 时，目前需要进容器执行命令查看具体日志 pm2 logs panel --lines 500”
运行日志如下：


root@qinglong:/ql $ pm2 logs panel --lines 500
[TAILING] Tailing last 500 lines for [panel] process (change the value with --lines option)
/root/.pm2/logs/panel-error.log last 500 lines:
4|panel    | 2022-03-01T19:03:55: Error: Cannot find module 'sequelize'
4|panel    | 2022-03-01T19:03:55: Require stack:
4|panel    | 2022-03-01T19:03:55: - /ql/build/data/index.js
4|panel    | 2022-03-01T19:03:55: - /ql/build/data/env.js
4|panel    | 2022-03-01T19:03:55: - /ql/build/loaders/db.js
4|panel    | 2022-03-01T19:03:55: - /ql/build/app.js
4|panel    | 2022-03-01T19:03:55:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
4|panel    | 2022-03-01T19:03:55:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
4|panel    | 2022-03-01T19:03:55:     at require (node:internal/modules/cjs/helpers:102:18)
4|panel    | 2022-03-01T19:03:55:     at Object.<anonymous> (/ql/back/data/index.ts:1:1)
4|panel    | 2022-03-01T19:03:55:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
4|panel    | 2022-03-01T19:03:55:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
4|panel    | 2022-03-01T19:03:55:     at Module.load (node:internal/modules/cjs/loader:981:32)
4|panel    | 2022-03-01T19:03:55:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
4|panel    | 2022-03-01T19:03:55:     at Module.require (node:internal/modules/cjs/loader:1005:19)
4|panel    | 2022-03-01T19:03:55:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39) {
4|panel    | 2022-03-01T19:03:55:   code: 'MODULE_NOT_FOUND',
4|panel    | 2022-03-01T19:03:55:   requireStack: [
4|panel    | 2022-03-01T19:03:55:     '/ql/build/data/index.js',
4|panel    | 2022-03-01T19:03:55:     '/ql/build/data/env.js',
4|panel    | 2022-03-01T19:03:55:     '/ql/build/loaders/db.js',
4|panel    | 2022-03-01T19:03:55:     '/ql/build/app.js'
4|panel    | 2022-03-01T19:03:55:   ]
4|panel    | 2022-03-01T19:03:55: }
4|panel    | 2022-03-01T19:03:55: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
4|panel    | 2022-03-01T19:03:55: Error: Cannot find module 'sequelize'
4|panel    | 2022-03-01T19:03:55: Require stack:
4|panel    | 2022-03-01T19:03:55: - /ql/build/data/index.js
4|panel    | 2022-03-01T19:03:55: - /ql/build/data/env.js
4|panel    | 2022-03-01T19:03:55: - /ql/build/loaders/db.js
4|panel    | 2022-03-01T19:03:55: - /ql/build/app.js
4|panel    | 2022-03-01T19:03:55:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
4|panel    | 2022-03-01T19:03:55:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
4|panel    | 2022-03-01T19:03:55:     at require (node:internal/modules/cjs/helpers:102:18)
4|panel    | 2022-03-01T19:03:55:     at Object.<anonymous> (/ql/back/data/index.ts:1:1)
4|panel    | 2022-03-01T19:03:55:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
4|panel    | 2022-03-01T19:03:55:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
4|panel    | 2022-03-01T19:03:55:     at Module.load (node:internal/modules/cjs/loader:981:32)
4|panel    | 2022-03-01T19:03:55:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
4|panel    | 2022-03-01T19:03:55:     at Module.require (node:internal/modules/cjs/loader:1005:19)
4|panel    | 2022-03-01T19:03:55:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)

/root/.pm2/logs/panel-out.log last 500 lines:
4|panel    | 2022-03-01T19:15:48: info:    ✌️ Sock loaded
4|panel    | 2022-03-01T19:15:48: error:   listen EADDRINUSE: address already in use :::5700
4|panel    | 2022-03-01T19:15:49: info:    ✌️ Init file down
4|panel    | 2022-03-01T19:15:49: info:    ✌️ Sentry loaded
4|panel    | 2022-03-01T19:15:49: info:    ✌️ DB loaded
4|panel    | 2022-03-01T19:15:49: info:    ✌️ Dependency Injector loaded
4|panel    | 2022-03-01T19:15:49: info:    ✌️ Express loaded
4|panel    | 2022-03-01T19:15:50: info:    ✌️ init data loaded
4|panel    | 2022-03-01T19:15:50: info:    ✌️ link deps
4|panel    | 2022-03-01T19:15:50: info:    ✌️ Sock loaded

**Comment by wangshiw** [comment]
同样需要ql check ，运行日志
/root/.pm2/logs/panel-error.log last 500 lines:
4|panel    | 2022-03-07T11:46:48:     at Module.require (node:internal/modules/cjs/loader:999:19)
4|panel    | 2022-03-07T11:46:48:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
4|panel    | 2022-03-07T11:46:48:     at require (node:internal/modules/cjs/helpers:102:18)
4|panel    | 2022-03-07T11:46:48:     at Object.<anonymous> (/ql/back/app.ts:3:1)
4|panel    | 2022-03-07T11:46:48:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
4|panel    | 2022-03-07T11:46:49: Error: ⚠️  Couldn't find .env file  ⚠️
4|panel    | 2022-03-07T11:46:49:     at Object.<anonymous> (/ql/back/config/index.ts:36:9)
4|panel    | 2022-03-07T11:46:49:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
4|panel    | 2022-03-07T11:46:49:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
4|panel    | 2022-03-07T11:46:49:     at Module.load (node:internal/modules/cjs/loader:975:32)
4|panel    | 2022-03-07T11:46:49:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
4|panel    | 2022-03-07T11:46:49:     at Module.require (node:internal/modules/cjs/loader:999:19)
4|panel    | 2022-03-07T11:46:49:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
4|panel    | 2022-03-07T11:46:49:     at require (node:internal/modules/cjs/helpers:102:18)
4|panel    | 2022-03-07T11:46:49:     at Object.<anonymous> (/ql/back/app.ts:3:1)
4|panel    | 2022-03-07T11:46:49:     at Module._compile (node:internal/modules/cjs/loader:1097:14)

**Comment by vc5** [comment]
遇到了同样的问题，青龙每隔1天就提示“服务异常,请手动执行ql check检查服务状态”，重新创建容器后才会恢复正常

**Comment by liesauer** [comment]
所以这就被closed了？

**Comment by liesauer** [comment]
跑得好好的，啥也没升级，前一两个星期，打开的web页无端端频繁提示服务异常，然后自动刷新网页，现在刚重启没多久，直接就GG了，报服务异常，请稍后刷新！根本进不去了
![image](https://user-images.githubusercontent.com/8676741/202937110-f33782bf-dce2-4d61-ae46-49eaf0bc9b53.png)

**Comment by liesauer** [comment]
ql check后没过多久又崩了
