### ISSUE TITLE
更新后需要增加哪些映射文件夹啊

### ISSUE THREAD

**Issue by sunyh87** [whyour/qinglong#116]
更新后 啥也没动 运行脚本报错
![`~C88H$R`03RL0NP1P`78$W](https://user-images.githubusercontent.com/20852855/118069440-c8502180-b3d6-11eb-9957-dced5e1a4c07.png)

**Comment by Acr05s** [comment]
所有定时任务删除重新新取

**Comment by sunyh87** [comment]
> 所有定时任务删除重新新取

怎么没看到更新后的脚本
![3EMY$XA4%ITA7_}~ABAYL4T](https://user-images.githubusercontent.com/20852855/118073258-1288d100-b3de-11eb-80fa-a7b5ee218686.png)

**Comment by sunyh87** [comment]
> 所有定时任务删除重新新取

![9H(K`$I7YZ%WR$O(NX5Y55](https://user-images.githubusercontent.com/20852855/118073523-95119080-b3de-11eb-9dad-9f3c9907e7d0.png)
这是什么情况

**Comment by 123feng** [comment]
我的也这样

**Comment by Acr05s** [comment]
等一下就好了，然后就添加库就行了

**Comment by whyour** [comment]
中间的任务日志都不看吗
