### ISSUE TITLE
PushDeer 推送支持

### ISSUE THREAD

**Issue by NekoMio** [whyour/qinglong#1161]
希望能增加PushDeer的推送支持

[http://www.pushdeer.com/](http://www.pushdeer.com/)

**Comment by zhuweitung** [comment]
附议，[pushdeer github地址](https://github.com/easychen/pushdeer#%E5%8F%91%E9%80%81%E5%AE%9E%E4%BE%8B)

**Comment by NekoMio** [comment]
我这里简单的写了一下 #1194
