### ISSUE TITLE
本机部署  v2.11.2

### ISSUE THREAD

**Issue by iamtsm** [whyour/qinglong#1163]
前两天是本机部署测试了下，发现一直拉不了js库，中午看了下代码，本机应该可行。步骤如下

首先需要是一台正常的服务器，有git , node , npm , python等等。假设你下载的青龙面板放在这个目录下： /home/admin/qinglong

1. 进入青龙项目目录
        cd /home/admin/qinglong
2. 安装依赖 （不仅限于这些，看看漏了哪些自己补充下）
        apt-get install -y coreutils moreutils jq 
3. 给脚本执行权限
        chmod +x /home/admin/qinglong/shell/*.sh
4. 模拟docker目录
        ln -s /home/admin/qinglong/shell /ql
5. 模拟docker中ql，task 等命令
        ln -s /home/admin/qinglong/shell/bot.sh /usr/local/bin/bot
        ln -s /home/admin/qinglong/shell/check.sh /usr/local/bin/check
        ln -s /home/admin/qinglong/shell/notify.sh /usr/local/bin/notify
        ln -s /home/admin/qinglong/shell/share.sh /usr/local/bin/share
        ln -s /home/admin/qinglong/shell/task.sh /usr/local/bin/task
        ln -s /home/admin/qinglong/shell/rmlog.sh /usr/local/bin/rmlog
        ln -s /home/admin/qinglong/shell/update.sh /usr/local/bin/ql
        ln -s /home/admin/qinglong/shell/api.sh /usr/local/bin/api
6. 完成，现在就可以正常执行ql 等命令了
        比如 : ql repo   <repourl>  <path>  <blacklist>  <dependence>  <branch>
                                   “库地址”  “拉哪些”   “不拉哪些”     “依赖文件”        “分支”

**Comment by iamtsm** [comment]
测试拉取一些脚本，虽然会有一些警告，问题不大。实际可以成功的

![image](https://user-images.githubusercontent.com/44826979/154216474-258c30e5-f856-45e2-84e5-3e9b4df3bc2f.png)

![image](https://user-images.githubusercontent.com/44826979/154216623-eb7545b1-601a-46fa-a761-7647988feb5c.png)

![image](https://user-images.githubusercontent.com/44826979/154216666-7a9ef0c8-e38b-4640-8b36-e1393f3886eb.png)

![image](https://user-images.githubusercontent.com/44826979/154216707-f2bce780-5c5c-415f-afe3-373c3ebc9028.png)

脚本运行界面 : 
![image](https://user-images.githubusercontent.com/44826979/154216792-7693a46d-ab89-4f93-9e38-f9db183a3edb.png)

![image](https://user-images.githubusercontent.com/44826979/154217102-3aa61eff-e100-47d2-bba2-78477567c43a.png)

项目本机部署dev界面
![image](https://user-images.githubusercontent.com/44826979/154217170-c61dc3d5-8199-4bef-aaf6-8bf04c7a4b9d.png)

**Comment by iamtsm** [comment]
> 问下是怎么启动的

青龙文档里面的开发模式启动就行

**Comment by lq-259** [comment]
请教一下还需要哪些依赖，我现在用用yarn install之后跑yarn start之后卡在这里了
![Screenshot_20220226-115621_JuiceSSH](https://user-images.githubusercontent.com/60541200/155828105-42c5f1e7-8b79-4b29-8848-8b4383b4a5d7.png)
面板也访问不了

**Comment by iamtsm** [comment]
> 面板编译好了访问又报错了 ![Screenshot_20220226-122918_Kiwi Browser](https://user-images.githubusercontent.com/60541200/155828947-e719b81e-5cef-446f-947f-4848b3a4bac5.png) ![Screenshot_20220226-122433_JuiceSSH](https://user-images.githubusercontent.com/60541200/155828949-c004cedc-412e-4715-bd3c-33b394b18486.png)

你这是改了原有的端口么，怎么5700变成5777了

**Comment by lq-259** [comment]
> > 面板编译好了访问又报错了 ![Screenshot_20220226-122918_Kiwi Browser](https://user-images.githubusercontent.com/60541200/155828947-e719b81e-5cef-446f-947f-4848b3a4bac5.png) ![Screenshot_20220226-122433_JuiceSSH](https://user-images.githubusercontent.com/60541200/155828949-c004cedc-412e-4715-bd3c-33b394b18486.png)
> 
> 你这是改了原有的端口么，怎么5700变成5777了

是的，我有其他程序用了5700就改了，还是现在想想是不是需要先改端口再yarn install？

**Comment by iamtsm** [comment]
> 

看报错是可能你改动端口代码有些地方遗漏了哦。想换端口，具体可以去看看代码
建议沿用原来的端口~

**Comment by whyour** [comment]
> > > 面板编译好了访问又报错了 ![Screenshot_20220226-122918_Kiwi Browser](https://user-images.githubusercontent.com/60541200/155828947-e719b81e-5cef-446f-947f-4848b3a4bac5.png) ![Screenshot_20220226-122433_JuiceSSH](https://user-images.githubusercontent.com/60541200/155828949-c004cedc-412e-4715-bd3c-33b394b18486.png)
> > 
> > 
> > 你这是改了原有的端口么，怎么5700变成5777了
> 
> 是的，我有其他程序用了5700就改了，还是现在想想是不是需要先改端口再yarn install？

别改5600，把5666换回去

**Comment by lq-259** [comment]
> > 
> 
> 看报错是可能你改动端口代码有些地方遗漏了哦。想换端口，具体可以去看看代码 建议沿用原来的端口~

好的，我改回去试试

**Comment by lq-259** [comment]
> > > > 面板编译好了访问又报错了 ![Screenshot_20220226-122918_Kiwi Browser](https://user-images.githubusercontent.com/60541200/155828947-e719b81e-5cef-446f-947f-4848b3a4bac5.png) ![Screenshot_20220226-122433_JuiceSSH](https://user-images.githubusercontent.com/60541200/155828949-c004cedc-412e-4715-bd3c-33b394b18486.png)
> > > 
> > > 
> > > 你这是改了原有的端口么，怎么5700变成5777了
> > 
> > 
> > 是的，我有其他程序用了5700就改了，还是现在想想是不是需要先改端口再yarn install？
> 
> 别改5600，把5666换回去

好的

**Comment by iamtsm** [comment]
> 启动成功了又有别的问题，拉库的时候已经登录了还是让我登录 ![Screenshot_20220226-174252_JuiceSSH](https://user-images.githubusercontent.com/60541200/155838425-4149e984-652b-46cd-87f0-4be445bd8da0.png) 脚本不会自动运行 ![Screenshot_20220226-174243_Kiwi Browser](https://user-images.githubusercontent.com/60541200/155838432-d5ed5c63-047a-4468-aeb7-690fd15ef386.png)

![1645869113(1)](https://user-images.githubusercontent.com/44826979/155838624-77f6c925-751c-45cc-8f92-cac26f006391.png)
注释掉get_user_info就好啦

**Comment by lq-259** [comment]
> > 启动成功了又有别的问题，拉库的时候已经登录了还是让我登录 ![Screenshot_20220226-174252_JuiceSSH](https://user-images.githubusercontent.com/60541200/155838425-4149e984-652b-46cd-87f0-4be445bd8da0.png) 脚本不会自动运行 ![Screenshot_20220226-174243_Kiwi Browser](https://user-images.githubusercontent.com/60541200/155838432-d5ed5c63-047a-4468-aeb7-690fd15ef386.png)
> 
> ![1645869113(1)](https://user-images.githubusercontent.com/44826979/155838624-77f6c925-751c-45cc-8f92-cac26f006391.png) 注释掉get_user_info就好啦

我才知道每秒执行是不执行的，改成每分也不行，cron也没问题
![Screenshot_20220226-203915_JuiceSSH](https://user-images.githubusercontent.com/60541200/155843723-01c69139-dfb2-4884-afcd-d69b4b187ecf.png)
![Screenshot_20220226-203851_Kiwi Browser](https://user-images.githubusercontent.com/60541200/155843727-730c7ae2-ca09-42a0-8b92-453b5060cfd8.png)

**Comment by lq-259** [comment]
> > > > 面板编译好了访问又报错了 ![Screenshot_20220226-122918_Kiwi Browser](https://user-images.githubusercontent.com/60541200/155828947-e719b81e-5cef-446f-947f-4848b3a4bac5.png) ![Screenshot_20220226-122433_JuiceSSH](https://user-images.githubusercontent.com/60541200/155828949-c004cedc-412e-4715-bd3c-33b394b18486.png)
> > > 
> > > 
> > > 你这是改了原有的端口么，怎么5700变成5777了
> > 
> > 
> > 是的，我有其他程序用了5700就改了，还是现在想想是不是需要先改端口再yarn install？
> 
> 别改5600，把5666换回去

任务不会自动执行，crond是在运行的，该怎么排查问题

**Comment by lq-259** [comment]
> 启动成功了又有别的问题，拉库的时候已经登录了还是让我登录 ![Screenshot_20220226-174252_JuiceSSH](https://user-images.githubusercontent.com/60541200/155838425-4149e984-652b-46cd-87f0-4be445bd8da0.png) 脚本不会自动运行 ![Screenshot_20220226-174243_Kiwi Browser](https://user-images.githubusercontent.com/60541200/155838432-d5ed5c63-047a-4468-aeb7-690fd15ef386.png)

好了，apt装的cron需要PATH而青龙生成的crontab.list没有，我直接换了一个不需要PATH的

**Comment by alphaerp** [comment]
> 请教一下还需要哪些依赖，我现在用用yarn install之后跑yarn start之后卡在这里了 ![Screenshot_20220226-115621_JuiceSSH](https://user-images.githubusercontent.com/60541200/155828105-42c5f1e7-8b79-4b29-8848-8b4383b4a5d7.png) 面板也访问不了



> 前两天是本机部署测试了下，发现一直拉不了js库，中午看了下代码，本机应该可行。步骤如下
> 
> 首先需要是一台正常的服务器，有git , node , npm , python等等。假设你下载的青龙面板放在这个目录下： /home/admin/qinglong
> 
> 1. 进入青龙项目目录
>    cd /home/admin/qinglong
> 2. 安装依赖 （不仅限于这些，看看漏了哪些自己补充下）
>    apt-get install -y coreutils moreutils jq
> 3. 给脚本执行权限
>    chmod +x /home/admin/qinglong/shell/*.sh
> 4. 模拟docker目录
>    ln -s /home/admin/qinglong/shell /ql
> 5. 模拟docker中ql，task 等命令
>    ln -s /home/admin/qinglong/shell/bot.sh /usr/local/bin/bot
>    ln -s /home/admin/qinglong/shell/check.sh /usr/local/bin/check
>    ln -s /home/admin/qinglong/shell/notify.sh /usr/local/bin/notify
>    ln -s /home/admin/qinglong/shell/share.sh /usr/local/bin/share
>    ln -s /home/admin/qinglong/shell/task.sh /usr/local/bin/task
>    ln -s /home/admin/qinglong/shell/rmlog.sh /usr/local/bin/rmlog
>    ln -s /home/admin/qinglong/shell/update.sh /usr/local/bin/ql
>    ln -s /home/admin/qinglong/shell/api.sh /usr/local/bin/api
> 6. 完成，现在就可以正常执行ql 等命令了
>    比如 : ql repo           
>    “库地址”  “拉哪些”   “不拉哪些”     “依赖文件”        “分支”

不用这么麻烦，你可以看下它的dockerfile文件，里面有配置环境变量的脚本。 按着这条路，你会找到share.sh这个里面有个link_shell函数。没那么难,把dockerfile和docker-entrypoint.sh看明白就可以线下部署。
