### ISSUE TITLE
求证：开发者之一hanhh家庭发生意外是真的吗？

### ISSUE THREAD

**Issue by yinmoyu** [whyour/qinglong#1168]
https://t.me/TestFlightCN/12180

如题，想求证消息是否真实，捐款渠道是否可信

**Comment by whyour** [comment]
> https://t.me/TestFlightCN/12180
> 
> 如题，想求证消息是否真实，捐款渠道是否可信

是真实的，原始消息 https://t.me/jiao_long/278，渠道可信。感谢🙏🏻
