### ISSUE TITLE
提个建议,auth.json里密码使用非可逆密文存储.

### ISSUE THREAD

**Issue by ilaotan** [whyour/qinglong#1169]
对密码进行几次md5,或者直接sha256计算. 反正别明文了吧. 有群友跑脚本,让脚本直接读取到配置文件把密码偷去了.

**Comment by 1027603857** [comment]
做个反向代理，脚本压根不知道你的ip，一劳永逸

**Comment by ilaotan** [comment]
> 做个反向代理，脚本压根不知道你的ip，一劳永逸

脚本往外发请求,接收方可以识别出发送方ip吧.  如果有域名,禁止ip登录应该能防住.
另外我发现wskey更新ck,会读取青龙的账号密码,模拟登录.  密码加密可能会影响该功能.

**Comment by 1027603857** [comment]
脚本只知道你的服务器ip，你把服务器设置为白名单模式，只对自己开放。如果你有公网ip，通过公网ip代理访问服务器，脚本并不知道你的白名单公网ip。

**Comment by 1027603857** [comment]
> > 做个反向代理，脚本压根不知道你的ip，一劳永逸
> 
> 脚本往外发请求,接收方可以识别出发送方ip吧. 如果有域名,禁止ip登录应该能防住. 另外我发现wskey更新ck,会读取青龙的账号密码,模拟登录. 密码加密可能会影响该功能.

脚本只知道你的服务器ip，你把服务器设置为白名单模式，只对自己开放。如果你有公网ip，白名单添加此ip，通过公网ip代理访问服务器，脚本并不知道你的白名单公网ip。

**Comment by JoeJoeLam** [comment]
> 



> > > 做个反向代理，脚本压根不知道你的ip，一劳永逸
> > 
> > 
> > 脚本往外发请求,接收方可以识别出发送方ip吧. 如果有域名,禁止ip登录应该能防住. 另外我发现wskey更新ck,会读取青龙的账号密码,模拟登录. 密码加密可能会影响该功能.
> 
> 脚本只知道你的服务器ip，你把服务器设置为白名单模式，只对自己开放。如果你有公网ip，白名单添加此ip，通过公网ip代理访问服务器，脚本并不知道你的白名单公网ip。

从服务器对外访问，白名单公网ip策略应该无法控制吧？
