### ISSUE TITLE
运行就报错 大概怎么解决啊

### ISSUE THREAD

**Issue by sunyh87** [whyour/qinglong#117]
不怎么会用这个2.0 怎么解决这个报错
![A2TKOEAL95GE1P$VY@`{@C7](https://user-images.githubusercontent.com/20852855/118078811-7ebd0200-b3e9-11eb-970b-65c33770229b.png)

**Comment by whyour** [comment]
> 不怎么会用这个2.0 怎么解决这个报错
> ![A2TKOEAL95GE1P$VY@`{@C7](https://user-images.githubusercontent.com/20852855/118078811-7ebd0200-b3e9-11eb-970b-65c33770229b.png)

你这肯定不是用的示例项目的命令，你既然自己改了，你得知道ql repo的命令的参数是什么意思

**Comment by sunyh87** [comment]
> > 不怎么会用这个2.0 怎么解决这个报错
> > ![A2TKOEAL95GE1P$VY@`{@C7](https://user-images.githubusercontent.com/20852855/118078811-7ebd0200-b3e9-11eb-970b-65c33770229b.png)
> 
> 你这肯定不是用的示例项目的命令，你既然自己改了，你得知道ql repo的命令的参数是什么意思

重新安装的 就是用的实例命令拉取的

**Comment by whyour** [comment]
定时任务批量删了，重新执行你的 repo 命令

**Comment by sunyh87** [comment]
> 定时任务批量删了，重新执行你的 repo 命令

刚全删了 用的频道示例命令 ql repo https://ghproxy.com/https://github.com/chinnkarahoi/jd_scripts.git
还是这样。。。不知道哪个地方缺少什么

**Comment by whyour** [comment]
@sunyh87 频道命令就这么点吗，拷贝全执行

**Comment by sunyh87** [comment]
> @sunyh87 频道命令就这么点吗，拷贝全执行

可以了 谢谢
