### ISSUE TITLE
好几次升级都是服务异常,请手动执行ql check检查服务状态，执行无果，然后只能重装容器，能不能统一下备份的内容，方便重装

### ISSUE THREAD

**Issue by EchoChan314** [whyour/qinglong#1175]
复制旧容器的config文件夹和db文件夹及文件到新容器的同名目录中，这样定时任务和环境变量还是空白的。

**Comment by 1027603857** [comment]
你要-v挂载出来

**Comment by crane168** [comment]
> 

怎么弄？我也出现ql check检查服务状态

**Comment by nopaben** [comment]
直接docker-compose down 然后在 up 就好了，就会回到 2.10.13 就是可能会丢失数据
