### ISSUE TITLE
更新失败怎么弄

### ISSUE THREAD

**Issue by Jingle-Pan** [whyour/qinglong#1176]
检查更新提示有新版本，点确认后总是失败：更新/ql失败，请检查原因...fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': Empty reply from server

**Comment by cc9014** [comment]
配置文件里面删除GithubProxyUrl里的内容

**Comment by Jingle-Pan** [comment]
> 配置文件里面删除GithubProxyUrl里的内容

按照方法可以更新，但是更新到中途卡住不动，过了3小时还不行就重启，结果不能用，重新拉镜像才行，所以设置重新来，太麻烦了

**Comment by cc9014** [comment]
换一个加速器就行。或者参照教程自己搭一个。
