### ISSUE TITLE
取不到互助码

### ISSUE THREAD

**Issue by daitangjun** [whyour/qinglong#118]
拉取的取互助码的脚本可以顺利取到互助码，面板内置的脚本取不到，怎么回事哦

# 你选择的互助码模板为：按账号编号优先。

**Comment by daitangjun** [comment]
实际上产生了日志的。

**Comment by e8732** [comment]
我也出现了这种情况

**Comment by whyour** [comment]
https://t.me/qiongqiya/80
不能发消息好好看妈

**Comment by hunter8605** [comment]
> https://t.me/qiongqiya/80
> 不能发消息好好看吗

大佬这个能重新发一下吗,账户不存在了
