### ISSUE TITLE
青龙最近CPU经常100%

### ISSUE THREAD

**Issue by zwb0619** [whyour/qinglong#1180]
[1645359066912](https://user-images.githubusercontent.com/44602137/154841923-451bd09e-9e30-4600-8368-fdba003c185e.jpg)
青龙最近资源占用特别厉害，请问下，这是些什么进程？耗费了大量cpu和内存。现在CPU经常100%

**Comment by keai-1989** [comment]
你什么配置？我N1升级2.11后，资源占用确实多很多

**Comment by zwb0619** [comment]
i5 8500，给了2个核心，4G内存，虚拟了个群晖，在群晖里面跑的。关掉青龙CPU占用个位数，开了以后，一会儿就100%

**Comment by Tao173** [comment]
arm64 RK3399，时常CPU显示百分之几百。

**Comment by Jingle-Pan** [comment]
新版本都这样吗？

**Comment by zwb0619** [comment]
现在把青龙暂时停了，等有新版本更新一下再说

**Comment by JuvenileQ** [comment]
中挖矿病毒了，我也中毒了，在使用docker安装完，阿里云安全预警，给我提示。你可以根剧这个脚本检查一下你的服务器
![image](https://user-images.githubusercontent.com/39209399/188878999-936527bf-9451-4cbd-aa5a-d020ab74a6d5.png)

**Comment by hhls** [comment]
官方都不处理（有意为之），大家别用了，之前我以为是bug，限制cpu后有时候服务直接无响应
