### ISSUE TITLE
ql repo 默认带通知文件问题

### ISSUE THREAD

**Issue by shenmadouyaowen** [whyour/qinglong#1184]
大佬,ql repo 拉库的时候默认带通知文件，有没有可能设置不带这两个通知文件
![image](https://user-images.githubusercontent.com/12426724/155077293-04afa9de-7683-44d5-90d2-c1aeb4fcb8d3.png)

**Comment by ololllolo** [comment]
有几个库用的都是自己的sendNotif.js，一拉库就被这两个文件覆盖了，只好手动粘贴过去，把这个文件删除，一拉库就重新复制了一份。
这个逻辑是不是可以改成，如果库需要这个依赖，并且自身不带，就从公用的目录复制过去，如果自己带了，就不要再复制了。

**Comment by ihuanran** [comment]
我也发现这个问题了

**Comment by cc9014** [comment]
qinglong的tg频道之前有说过这个问题，提供了一个解决方案。

> ql repo拉库逻辑
> ql repo会默认复制deps目录下的文件到仓库目录，所以你要固定你的sendNotify或者其他文件时，只需要把文件放到deps目录即可

**Comment by ihuanran** [comment]
@cc9014 刚加了tg，看到了。可以解决问题

**Comment by shenmadouyaowen** [comment]
> 
我觉得这个办法不是最终的解决办法,最好是在拉库的时候加一个选择

**Comment by wodeweiyimpm** [comment]
已运行的青龙怎么映射deps文件夹出来？

**Comment by cc9014** [comment]
不能映射，需要把容器删了。要么就是docker cp把文件从外部拷贝到内部。

**Comment by shenmadouyaowen** [comment]
> 已运行的青龙怎么映射deps文件夹出来？

可以修改和增加映射文件,具体的参考：https://www.csdn.net/tags/MtjaYg3sOTcwOTItYmxvZwO0O0OO0O0O.html
