### ISSUE TITLE
（已解决）openapi能否整个说明文档

### ISSUE THREAD

**Issue by Wpenga** [whyour/qinglong#1185]
频道的说明有些稀碎
现在知道获取环境变量是
http://$host/open/envs?searchValue=&t=$t
脚本管理又是什么
有如何设置变量到青龙

**Comment by Wpenga** [comment]
不好意思，找到相关文档了，建议放到项目说明那

**Comment by Ukenn2112** [comment]
按照我自己理解写的文档，可能表述有些不准确，欢迎指正 https://github.com/whyour/qinglong/issues/1151

**Comment by faymanwang** [comment]
请问文档在那个位置啊？

**Comment by Ukenn2112** [comment]
> 请问文档在那个位置啊？

第三方文档
https://github.com/whyour/qinglong/issues/1151

**Comment by faymanwang** [comment]
谢谢
