### ISSUE TITLE
telegram机器人通知设置bug

### ISSUE THREAD

**Issue by MrChenYoung** [whyour/qinglong#1186]
配置文件里的TG_BOT_TOKEN和TG_USER_ID设置完一段时间后会被清空，导致telegram机器人收不到通知

**Comment by zhuweitung** [comment]
我之前用2.11.2版本也有这个问题，升级成2.11.3后解决

**Comment by MrChenYoung** [comment]
我就是2.11.3版本的，不知道是不是需要设置别的什么
