### ISSUE TITLE
图标无法加载

### ISSUE THREAD

**Issue by Karmylr** [whyour/qinglong#1187]
![image](https://user-images.githubusercontent.com/69903376/155271303-818e4bc6-0f7d-402c-8413-c99b522be9f3.png)
![image](https://user-images.githubusercontent.com/69903376/155271308-02cd1975-f216-4ef3-bd29-c97b2813647e.png)

**Comment by zhuweitung** [comment]
这个版本问题很多，建议升级到v2.11.3
```shell
docker pull whyour/qinglong:latest
or
docker pull whyour/qinglong:2.11.3
```
