### ISSUE TITLE
2.11.2 使用ql update更新失败，之后面板无法进入

### ISSUE THREAD

**Issue by wangkangfeng99** [whyour/qinglong#1188]
之后使用 ql check 检测修复之后 仍然无法进入
![image](https://user-images.githubusercontent.com/68324194/155312308-e9419da6-1e92-45bd-8a1f-2d58d4b8cae6.png)

**Comment by langren1353** [comment]
经检查发现是/ql/.env环境中缺少环境变量：BACK_PORT
修改后可用：
```MONGODB_URI='mongodb://'
YIYAN_MONGODB_URI=''

CRON_PORT=5500
PORT=5700
BACK_PORT=5600
LOG_LEVEL='debug'

SECRET='whyour'
```

**Comment by jiayiwang5** [comment]
我也没法进面板，但是确实在运行。从2.8更新到2.11就这样了

**Comment by wangkangfeng99** [comment]
> 这个文件在什么位置  找不到
![image](https://user-images.githubusercontent.com/68324194/155968315-45ce89a8-33df-4372-a636-3a5053bfd67e.png)
