### ISSUE TITLE
无法更新chinnkarahoi仓库的脚本

### ISSUE THREAD

**Issue by lxr760** [whyour/qinglong#119]
无论是否翻墙     都无法更新这个脚本库       但是其他脚本库更新正常

![Snipaste_2021-05-14_01-16-13](https://user-images.githubusercontent.com/8476457/118161353-0c343c80-b452-11eb-82c1-e8eca6fea91d.jpg)

**Comment by whyour** [comment]
@lxr760 把repo下的那个仓库删了

**Comment by lxr760** [comment]
> @lxr760 把repo下的那个仓库删了

啥意思？是把/ql/repo/chinnkarahoi里的文件删除。还是删了这个repo，用别的库同步脚本？

**Comment by whyour** [comment]
@lxr760 删了这个文件夹/ql/repo/chinnkarahoi，重新执行命令

**Comment by lxr760** [comment]
> @lxr760 删了这个文件夹/ql/repo/chinnkarahoi，重新执行命令

脚本能更新了



另外那个桥接没有网的issue  大佬帮忙看下    ping京东是通的   但是docker里无网
