### ISSUE TITLE
2.11.3的可能bug（通过api接口无法更新ck）

### ISSUE THREAD

**Issue by bonnyandsky** [whyour/qinglong#1193]
用了saobing，也用了jdx，发现在没有ck的情况下，可以新增ck。
但是如果在青龙面板里已有此ck，不管是运行状态，还是禁用状态。都无法在现有基础上更新ck内容。

**Comment by bonnyandsky** [comment]
对了2.10.12没这个问题

**Comment by wangyiidii** [comment]
> 对了2.10.12没这个问题

JDX将对_id和id进行兼容

**Comment by bonnyandsky** [comment]
> 

太好了

**Comment by hu5871** [comment]
你好，请问envs  delete 能请求成功吗，我一直尝试都是500
