### ISSUE TITLE
如何关闭青龙重启时的自动重装依赖，以及求教，之前已安装，自动重装依赖失败如何解决

### ISSUE THREAD

**Issue by gxhunter1982** [whyour/qinglong#1196]
因为青龙装路由上，路由有时需要维护重启下。
而每次重启后，青龙会自动把已安装的依赖都重装一遍，有办法关闭吗。

现在的情况是，之前已安装的依赖，有时会在自动重装依赖时失败，就再也装不上了，有没有办法解决。

**Comment by cc9014** [comment]
检查/config里的task_before.sh和task_after.sh之类的文件，可能里面写了安装依赖的命令。

**Comment by gxhunter1982** [comment]
> 检查/config里的task_before.sh和task_after.sh之类的文件，可能里面写了安装依赖的命令。

这两个文件都是空的，只有默认的注释掉的默认内容
"#!/usr/bin/env bash"

除此之外，此目录下，几个配置文件都看过了，没有啥安装依赖的命令。
而且这些依赖都是我自己在“依赖管理”里安装的，现在有几个就是安装失败的状态，也没法修复。

**Comment by cc9014** [comment]
> > 检查/config里的task_before.sh和task_after.sh之类的文件，可能里面写了安装依赖的命令。
> 
> 这两个文件都是空的，只有默认的注释掉的默认内容 "#!/usr/bin/env bash"
> 
> 除此之外，此目录下，几个配置文件都看过了，没有啥安装依赖的命令。 而且这些依赖都是我自己在“依赖管理”里安装的，现在有几个就是安装失败的状态，也没法修复。

那就不清楚了，我安装依赖都是用命令行装的。感觉qinglong里的“依赖管理”不好用，我之前也出现过安装失败的问题，后来全删了改用命令行，就几行命令装好后就一劳永逸了。

**Comment by 445081431** [comment]
遇到了一样的问题，删除用一件安装依赖的脚本安装提示成功，但是运行还是出错。

**Comment by mContext** [comment]
+1 重装慢也就算了 关键还会失败

**Comment by cddjr** [comment]
最简单的方式就是依赖装好后请把列表清了。

**Comment by mContext** [comment]
> 最简单的方式就是依赖装好后请把列表清了。

清了是🈯️删除吗？

**Comment by mContext** [comment]
> +1 重装慢也就算了 关键还会失败

我这个是因为网络问题 重装慢+失败  解决了网络问题 重装还是挺快的~

**Comment by xuexijiaoben** [comment]
> 



> > > 检查/config里的task_before.sh和task_after.sh之类的文件，可能里面写了安装依赖的命令。
> > 
> > 
> > 这两个文件都是空的，只有默认的注释掉的默认内容 "#!/usr/bin/env bash"
> > 除此之外，此目录下，几个配置文件都看过了，没有啥安装依赖的命令。 而且这些依赖都是我自己在“依赖管理”里安装的，现在有几个就是安装失败的状态，也没法修复。
> 
> 那就不清楚了，我安装依赖都是用命令行装的。感觉qinglong里的“依赖管理”不好用，我之前也出现过安装失败的问题，后来全删了改用命令行，就几行命令装好后就一劳永逸了。

请问，这几个命令能分享下不，谢谢啦
