### ISSUE TITLE
不想走https://ghproxy.com/加速怎么设置

### ISSUE THREAD

**Issue by MrWQ** [whyour/qinglong#1199]
![image](https://user-images.githubusercontent.com/31604279/156324288-1e0f7471-6ccb-4bc7-b9ab-d6eea3e8cb09.png)

**Comment by chj-damon** [comment]
请问这个配置文件，是在哪里？找了半天没找到

**Comment by cc9014** [comment]
打开网页，左边的“配置文件”tab

**Comment by huangcun200816** [comment]
我已经删了这个代理配置，但青龙拉取仓库代码的时候，还是会使用这个代理，不知道是不是成了默认使用的
