### ISSUE TITLE
多帐号，互相助力，需要后续有打乱cookies顺序，随机助力

### ISSUE THREAD

**Issue by piaoyun** [whyour/qinglong#12]
假设有帐号8个

按照现在的助力，一直都是1助力后面的2.3.4.5.6.7.8

2助力的有是1.3.4.5.6.7.8

希望后续支持，打乱顺序。每天随机助力。

**Comment by monk-coder** [comment]
> 假设有帐号8个
> 
> 按照现在的助力，一直都是1助力后面的2.3.4.5.6.7.8
> 
> 2助力的有是1.3.4.5.6.7.8
> 
> 希望后续支持，打乱顺序。每天随机助力。

有这个必要么。。。。

**Comment by q123458384** [comment]
v4里面好像有随机助力的设置
