### ISSUE TITLE
连续2天一过0点就不自动运行脚本了，手动可以运行。

### ISSUE THREAD

**Issue by rogerujn** [whyour/qinglong#120]
昨天早上发现这个问题，删除镜像、删除ql文件夹全新安装了一遍，可以正常运行了。今天早上看日志，发现又是0点以后不自动运行了，这次重启了一下容器就正常了。日志里有很多类似下面的提示：
crond[155]:USER root pid 621 cmd run-parts/etc/periodic/15 min
crond[155]:USER root pid 622 cmd run-parts/etc/periodic/hourly

**Comment by WYEEE** [comment]
我也是今天过了0点进不去面板，重启也不行。
a padding to disable MSIE and Chrome friendly error page

**Comment by whyour** [comment]
把你们ql update的定时时间发出来
手动执行下 docker exec -it qinglong ql update

**Comment by rogerujn** [comment]
ql update的定时时间，默认的没改过    38 14,7,12,4,20,6,16 * * *
有个细节：
从京豆收益来看，东东超市兑换奖品	task chinnkarahoi_jd_blueCoin.js  0 0 0 * * *，这个是运行了，这个corn是6位的。另外我把多合一签到的时间由默认的“0 6 * * *”改成了“0 0 * * *”5位的。
这个有影响吗？

**Comment by whyour** [comment]
> ql update的定时时间，默认的没改过 38 14,7,12,4,20,6,16 * * *
> 有个细节：
> 从京豆收益来看，东东超市兑换奖品 task chinnkarahoi_jd_blueCoin.js 0 0 0 * * *，这个是运行了，这个corn是6位的。另外我把多合一签到的时间由默认的“0 6 * * *”改成了“0 0 * * *”5位的。
> 这个有影响吗？

貌似没影响，你执行下ql update然后重启下容器，再观察下

**Comment by rogerujn** [comment]
今天没有出现，我再观察观察。
