### ISSUE TITLE
更新后，重启就启动不了了，报错5700端口被占用

### ISSUE THREAD

**Issue by maglcal** [whyour/qinglong#1201]
![image](https://user-images.githubusercontent.com/23492228/156577476-ae0249d4-6af9-4c64-848d-e74fabca5fed.png)何解？

**Comment by maglcal** [comment]
> 使用“lsof -i:5700”或者“netstat -tunlp | grep 5700” 类的命令来查看是哪个程序占用了。直接kill掉，再启动qinglong

试过，结束不了~

**Comment by maglcal** [comment]
> 用 “lsof -i:5700” 或者 “netstat -tunlp | grep 5700” 之类的命令来查看究竟是哪个程序占用了。直接kill掉，再启动qinglong

结束后，重启青龙，然后还是报同样的错

**Comment by cc9014** [comment]
还是报同样的端口占用的错？那就证明原来的进程没有被结束或者被杀的时候，立马重开了一个，PID号变了。
可能有systemctl或者其他守护进程保护了？你可以自己排查下。或者你kill的权限不够，用root了么？

**Comment by maglcal** [comment]
> 还是报同样的端口占用的错？那就证明原来的进程没有被结束或者被杀的时候，立马重开了一个，PID号变了。 可能有systemctl或者其他守护进程保护了？你可以自己排查下。或者你kill的权限不够，用root了么？

是root操作的，应该不是权限问题

**Comment by maglcal** [comment]
> > 还是报同样的端口占用的错？那就证明原来的进程没有被结束或者被杀的时候，立马重开了一个，PID号变了。 可能有systemctl或者其他守护进程保护了？你可以自己排查下。或者你kill的权限不够，用root了么？
> 
> 是root操作的，应该不是权限问题

![image](https://user-images.githubusercontent.com/23492228/156686370-0e36a27d-e42d-490d-8021-97ebe649213c.png)

**Comment by cc9014** [comment]
我自己大概试验了下，用 netstat -tunlp | grep 5700 得到的结果 占用的是 41/ngix.conf，直接好像杀不了这个进程。
然后用ps -a查看进程，会找到两个ngix的进程，其中一个就是运行的 ngix -c /etc XXXX。我理解需要把这个进程杀了。
你可以再试试。

**Comment by jason1004** [comment]
遇到同样问题，怎样解决
