### ISSUE TITLE
推送到Telegram失败 设置里面不能成功添加推送到Telegram 

### ISSUE THREAD

**Issue by Stdocdure** [whyour/qinglong#1211]
telegram发送通知消息失败！！

HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/ql/scripts/node_modules/.pnpm/registry.npmmirror.com+got@11.8.3/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: [1646548454824](tel:1646548454824),
    socket: [1646548454824](tel:1646548454824),
    lookup: [1646548455154](tel:1646548455154),
    connect: 1646548455156,
    secureConnect: [1646548456199](tel:1646548456199),
    upload: 1646548456200,
    response: [1646548456888](tel:1646548456888),
    end: 1646548456889,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 330,
      tcp: 2,
      tls: 1043,
      request: 1,
      firstByte: 688,
      download: 1,
      total: 2065
    }
  }
}

**Comment by wakaka123wakaka** [comment]
这种问题应该是因为推送到telegram的内容过多导致的
