### ISSUE TITLE
/envs delete api 类型要求是number  但是得到的环境变量id却是string

### ISSUE THREAD

**Issue by hu5871** [whyour/qinglong#1213]
![image](https://user-images.githubusercontent.com/68421705/156924859-2a889e7f-fe65-4981-8e9d-73339fa0de81.png)
![image](https://user-images.githubusercontent.com/68421705/156924875-7e1ddbcb-32bc-4997-bdea-670ba59a0042.png)
我该如何修改

**Comment by LevenYi** [comment]
不明白加一，哥们你弄清楚了吗

**Comment by hu5871** [comment]
@LevenYi 低版本的青龙添加环境变量是string类型，更新版本就好
