### ISSUE TITLE
关于拉取第3方库

### ISSUE THREAD

**Issue by woboo110** [whyour/qinglong#122]
大佬，拉取第3方库，如何只拉取js文件，且过滤掉其中的不想用的文件? 看了你的实例仓库写法，拉的不太准确，能说说规则吗

**Comment by whyour** [comment]
ql repo 仓库地址 白名单 黑名单 依赖文件

依赖文件不添加作者前缀

**Comment by woboo110** [comment]
好的，感谢大佬
