### ISSUE TITLE
小白想问一下这个目录下怎么啥也没有啊

### ISSUE THREAD

**Issue by lfscqk67** [whyour/qinglong#1225]
要想上传本地脚本的话该怎么办呢
![image](https://user-images.githubusercontent.com/37235589/157893247-394000ae-4689-4e3c-b8b0-037ca1d1ae80.png)

**Comment by cc9014** [comment]
可能和 #1197 是一个情况。

**Comment by lfscqk67** [comment]
我的N1得用这个才行
docker run -dit \
  -v $PWD/ql/config:/ql/config \
  -v $PWD/ql/log:/ql/log \
  -v $PWD/ql/db:/ql/db \
  -v $PWD/ql/repo:/ql/repo \
  -v $PWD/ql/raw:/ql/raw \
  -v $PWD/ql/scripts:/ql/scripts \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest
