### ISSUE TITLE
添加示例仓库的时候报错

### ISSUE THREAD

**Issue by Shawt310** [whyour/qinglong#123]
大佬，更新到2.0以后定时任务只有几个了，但是添加示例仓库的时候却如此报错，帮忙看看如何解决吧，谢谢

root@qinglong:/ql $ ql repo https://ghproxy.com/https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"
--------------------------------------------------------------

开始更新仓库：/ql/repo/chinnkarahoi_jd_scripts

Fetching origin
HEAD is now at 3f94d7b2 fix
Already up to date.

更新/ql/repo/chinnkarahoi_jd_scripts成功...

/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 322: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_scripts.list: No such file or directory
/usr/local/bin/ql: line 324: /ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_user.list: No such file or directory
cp: cannot stat '/ql/log/.tmp//ql/repo/chinnkarahoi_jd_scripts_user.list': No such file or directory

**Comment by whyour** [comment]
ql update更新下，上午的一个bug
