### ISSUE TITLE
更新到2.11.3之后拉库提示检查网络 完全重装还是不行

### ISSUE THREAD

**Issue by qilongcainiao** [whyour/qinglong#1232]
## 开始执行... 2022-03-17 09:58:40

开始克隆仓库 https://ghproxy.com/github.com/KingRan/JDJB.git 到 /ql/repo/KingRan_JDJB

更新/ql/repo/KingRan_JDJB失败，请检查网络...

## 执行结束... 2022-03-17 09:58:40  耗时 0 秒

**Comment by cc9014** [comment]
删除ghproxy.com/部分，如果是国内机器，另外找加速器或者自己搭一个
