### ISSUE TITLE
sendNotify.js文件无法覆盖v2.11.3

### ISSUE THREAD

**Issue by zspro** [whyour/qinglong#1233]
仓库里有sendNotify.js文件，依赖里也添加了sendNotify，但是拉库之后scripts文件夹里根目录和仓库的的sendNotify.js都是自动生成的应该，仓库里自己的sendNotify.js无法覆盖

**Comment by niangao0813** [comment]
2.11.2也有这个问题，请问有什么解决办法吗？

**Comment by wodeweiyimpm** [comment]
2.10.11也是这样  手动建文件夹deps 放进去一样没用

**Comment by cc9014** [comment]
手动建deps没用，需要创建容器的时候映射好。进入qinglong容器，里面应该已经有deps文件夹了，把要固化的文件从外部传进去即可。

**Comment by YugaoX** [comment]
> 手动建deps没用，需要创建容器的时候映射好。进入qinglong容器，里面应该已经有deps文件夹了，把要固化的文件从外部传进去即可。

创建容器的时候已经映射过了 但是还是不覆盖
