### ISSUE TITLE
dev版本青龙目录为空，怎么重新映射

### ISSUE THREAD

**Issue by catseie** [whyour/qinglong#1236]
![image](https://user-images.githubusercontent.com/10432233/158991446-117f9311-b735-430a-945e-afb4a5b5fdb6.png)

这样启动容器的
docker run -dit \
  -v $PWD/ql:/ql/data \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest

**Comment by cc9014** [comment]
这个容器删了，重新创建一个。
建议用docker-compose的方式来创建和启动，方便点。
