### ISSUE TITLE
最新版本的青龙又不支持ipv6访问了吗？

### ISSUE THREAD

**Issue by allonmymind** [whyour/qinglong#1243]
历史issues里看到有人问过类似问题，front文件增加的监听ipv6的那一行代码在最新版本里没有了。不巧的是我也是arm设备加移动家宽，不知道能否完美使用ipv6访问？望大佬解决下

**Comment by jackadam1981** [comment]
确实又丢了。

**Comment by 392377870** [comment]
有解决办法吗？旧版是支持ipv6的
