### ISSUE TITLE
请问哪里可以设置python的版本吗？3.9的版本有些模块安装不了

### ISSUE THREAD

**Issue by zengaorong** [whyour/qinglong#1245]

**Comment by ji5261** [comment]
cryptography 依赖管理里怎么能装上？

**Comment by zengaorong** [comment]
在项目的linux依赖里面安装python3-dev gcc g++ musl-dev libxslt-dev  如果要使用java 使用openjdk13
这个系统是Alpine，里面安装东西使用apk add命令

**Comment by ji5261** [comment]
> 在项目的linux依赖里面安装python3-dev gcc g++ musl-dev libxslt-dev 如果要使用java 使用openjdk13 这个系统是Alpine，里面安装东西使用apk add命令

非常感谢。我是这方面的小白，看您回复非常感激，照猫画虎一顿操作下来居然成了，谢谢。

**Comment by jasonhuizhang** [comment]
> 在项目的linux依赖里面安装python3-dev gcc g++ musl-dev libxslt-dev 如果要使用java 使用openjdk13 这个系统是Alpine，里面安装东西使用apk add命令

是docker exec -it qinglong bash里面输入python3-dev gcc g++ musl-dev libxslt-dev吗？谢谢
