### ISSUE TITLE
pm2 logs panel 暂无日志

### ISSUE THREAD

**Issue by xiao468657802** [whyour/qinglong#1252]
xxx.xx.xx.xx:5801/error
服务错误

pm2 logs panel
暂无日志

root@ql:~ $ pm2 restart panp
Use --update-env to update environment variables
[PM2][ERROR] Process or Namespace panp not found
root@ql:~ $ pm2 restart panel
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [panel](ids: [ 0 ])
[PM2] [panel](0) ✓
┌─────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ panel       │ default     │ N/A     │ fork    │ 1001     │ 0s     │ 1    │ online    │ 0%       │ 7.5mb    │ root     │ disabled │
│ 1   │ schedule    │ default     │ N/A     │ fork    │ 107      │ 17m    │ 0    │ online    │ 0%       │ 83.8mb   │ root     │ disabled │
└─────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
root@ql:~ $ pm2 restart schedule
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [schedule](ids: [ 1 ])
[PM2] [schedule](1) ✓
┌─────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ panel       │ default     │ N/A     │ fork    │ 1001     │ 11s    │ 1    │ online    │ 0%       │ 88.3mb   │ root     │ disabled │
│ 1   │ schedule    │ default     │ N/A     │ fork    │ 1029     │ 0s     │ 1    │ online    │ 0%       │ 8.5mb    │ root     │ disabled │
└─────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
root@ql:~ $ pm2 log panel
[TAILING] Tailing last 15 lines for [panel] process (change the value with --lines option)
/root/.pm2/logs/panel-out.log last 15 lines:
0|panel    | 2022-03-24T16:55:41: info:    ✌️ Sentry loaded
0|panel    | 2022-03-24T16:55:42: info:    ✌️ DB load failed
0|panel    | 2022-03-24T16:55:42: info:    SQLITE_CANTOPEN: unable to open database file
0|panel    | 2022-03-24T16:57:05: info:    ✌️ Init file down
0|panel    | 2022-03-24T16:57:06: info:    ✌️ Sentry loaded
0|panel    | 2022-03-24T16:57:07: info:    ✌️ DB load failed
0|panel    | 2022-03-24T16:57:07: info:    SQLITE_CANTOPEN: unable to open database file
0|panel    | 2022-03-24T17:00:09: info:    ✌️ Init file down
0|panel    | 2022-03-24T17:00:09: info:    ✌️ Sentry loaded
0|panel    | 2022-03-24T17:00:10: info:    ✌️ DB load failed
0|panel    | 2022-03-24T17:00:10: info:    SQLITE_CANTOPEN: unable to open database file
0|panel    | 2022-03-24T17:17:12: info:    ✌️ Init file down
0|panel    | 2022-03-24T17:17:12: info:    ✌️ Sentry loaded
0|panel    | 2022-03-24T17:17:12: info:    ✌️ DB load failed
0|panel    | 2022-03-24T17:17:12: info:    SQLITE_CANTOPEN: unable to open database file

/root/.pm2/logs/panel-error.log last 15 lines:
0|panel    | 2022-03-24T17:17:13:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
0|panel    | 2022-03-24T17:17:13:     at Module.require (node:internal/modules/cjs/loader:1005:19)
0|panel    | 2022-03-24T17:17:13:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
0|panel    | 2022-03-24T17:17:13:     at require (node:internal/modules/cjs/helpers:102:18)
0|panel    | 2022-03-24T17:17:13:     at Object.<anonymous> (/back/services/user.ts:13:1)
0|panel    | 2022-03-24T17:17:13:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
0|panel    | 2022-03-24T17:17:13:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
0|panel    | 2022-03-24T17:17:13:     at Module.load (node:internal/modules/cjs/loader:981:32)
0|panel    | 2022-03-24T17:17:13:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
0|panel    | 2022-03-24T17:17:13:     at Module.require (node:internal/modules/cjs/loader:1005:19)
0|panel    | 2022-03-24T17:17:13:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
0|panel    | 2022-03-24T17:17:13:     at require (node:internal/modules/cjs/helpers:102:18)
0|panel    | 2022-03-24T17:17:13:     at Object.<anonymous> (/back/api/user.ts:6:1)
0|panel    | 2022-03-24T17:17:13:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
0|panel    | 2022-03-24T17:17:13:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by blankvip** [comment]
我也是这个问题，ql check和ql update  这两个命令都操作了，问题还是这样

**Comment by xiao468657802** [comment]
我就是执行过 ql update  之后出现这个报错的，我当初怀疑是内存太小，但清理过之后，启动ql，还剩400M内存，也还是不行，现在我也不知道怎么办

**Comment by jqjhl** [comment]
我也是执行过 ql update 之后出现
pm2 logs panel
暂无日志

**Comment by Fate-yo** [comment]
执行 `docker exec -it qinglong /bin/bash ql check` 来修复一下呢
