### ISSUE TITLE
今天被自动升级2.12了。。以前的库和环境变量都没了。。

### ISSUE THREAD

**Issue by mangrove2014** [whyour/qinglong#1254]
大佬能在哪里设置关闭自动升级不？

**Comment by changyizhen** [comment]
不可能没了 移动下文件夹就行了

**Comment by mangrove2014** [comment]
> 

真的吗 他去哪个文件夹下了？

**Comment by Cyiming** [comment]
你们真是不看更新说明就硬更啊

我一切正常 除了个库文件路径有点问题 联系作者解决了 目前没有任何问题

**Comment by gradypark86** [comment]
惭愧，确实没看更新说明，Watchtower 直接自动升上来了
7. 调整数据目录，log、db、scripts、config等目录迁移到 /ql/data 目录，docker映射只需映射data目录



| |
gradypark
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月24日 23:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [whyour/qinglong] 今天被自动升级2.12了。。以前的库和环境变量都没了。。 (Issue #1254) |

你们真是不看更新说明就硬更啊

我一切正常 除了个库文件路径有点问题 联系作者解决了 目前没有任何问题

**Comment by blankvip** [comment]
> 你们真是不看更新说明就硬更啊
> 
> 我一切正常 除了个库文件路径有点问题 联系作者解决了 目前没有任何问题

怎么操作可以指导一下吗？没看懂

**Comment by mangrove2014** [comment]
我没主动升级，能不能关闭自动升级啊？

**Comment by gradypark86** [comment]
> > 你们真是不看更新说明就硬更啊
> > 我一切正常 除了个库文件路径有点问题 联系作者解决了 目前没有任何问题
> 
> 怎么操作可以指导一下吗？没看懂

原来docker映射目录的时候是log db config等单独映射的，例如
```
      - /Container/qinglong/config:/ql/config
      - /Container/qinglong/log:/ql/log
      - /Container/qinglong/db:/ql/db
      - /Container/qinglong/scripts:/ql/scripts
      - /Container/qinglong/repo:/ql/repo
      - /Container/qinglong/raw:/ql/raw
```
现在只需要映射一个 `- /Container/qinglong:/ql/data` 即可

**Comment by blankvip** [comment]
> > > 你们真是不看更新说明就硬更啊
> > > 我一切正常 除了个库文件路径有点问题 联系作者解决了 目前没有任何问题
> > 
> > 
> > 怎么操作可以指导一下吗？没看懂
> 
> 原来docker映射目录的时候是log db config等单独映射的，例如
> 
> ```
>       - /Container/qinglong/config:/ql/config
>       - /Container/qinglong/log:/ql/log
>       - /Container/qinglong/db:/ql/db
>       - /Container/qinglong/scripts:/ql/scripts
>       - /Container/qinglong/repo:/ql/repo
>       - /Container/qinglong/raw:/ql/raw
> ```
> 
> 现在只需要映射一个 `- /Container/qinglong:/ql/data` 即可

具体命令怎么操作可以说一下吗？我不知道怎么运行命令来映射 谢谢

**Comment by gradypark86** [comment]
> > > > 你们真是不看更新说明就硬更啊
> > > > 我一切正常 除了个库文件路径有点问题 联系作者解决了 目前没有任何问题
> > > 
> > > 
> > > 怎么操作可以指导一下吗？没看懂
> > 
> > 
> > 原来docker映射目录的时候是log db config等单独映射的，例如
> > ```
> >       - /Container/qinglong/config:/ql/config
> >       - /Container/qinglong/log:/ql/log
> >       - /Container/qinglong/db:/ql/db
> >       - /Container/qinglong/scripts:/ql/scripts
> >       - /Container/qinglong/repo:/ql/repo
> >       - /Container/qinglong/raw:/ql/raw
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 现在只需要映射一个 `- /Container/qinglong:/ql/data` 即可
> 
> 具体命令怎么操作可以说一下吗？我不知道怎么运行命令来映射 谢谢

可以参考项目首页的 README 说明进行部署，里面的命令是新的。简单点你可以把原来的容器删掉重新部署一个，数据不会丢失。假设你用 docker 命令，那么如下，其中 `PWD` 为青龙路径。
```
docker run -dit \
  -v $PWD/ql:/ql/data \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest
```

**Comment by sofs2005** [comment]
单青龙的话改大映射是可以的，多青龙共用scripts等目录就不行，还是得单独映射出来

**Comment by Cyiming** [comment]
我最开始好好的 但是后来自动就删掉了data恢复了原来路径 关键还不报错

看了下 映射还是data

我试着创建data 手动移动 但是面板打不开 太神奇了

我这变相的兼容了新老版本？

**Comment by sofs2005** [comment]
> 

有个ql update可以迁移，但是迁的不完整

**Comment by gba3455** [comment]
> 你们真是不看更新说明就硬更啊
> 
> 我一切正常 除了个库文件路径有点问题 联系作者解决了 目前没有任何问题

感谢大佬。一语点醒。
我是从v2.12.2一下升到v.2.15.4，跨度太大无法自动升级，用watchtower升级的，
没想到中间目录有迁移改变。
难怪升级后数据丢失大半。
看了你的说明，回去看了更新日志，
自己琢磨一下，把旧的文件备份出来，
考进新的容器里，重启，
一切都回来了。完美。
