### ISSUE TITLE
2.12.0最新版 拉库添加定时任务成功之后发送通知失败！！！

### ISSUE THREAD

**Issue by Kaystar** [whyour/qinglong#1266]
<img width="389" alt="微信截图_20220325191714" src="https://user-images.githubusercontent.com/71498983/160111719-93ef31f4-605f-40f0-995b-b67645ac4616.png">
新建的容器，并且网络正常。本地机和云服务器上都试过，都不能发送通知。

**Comment by monkey-sking** [comment]
表示有同样的问题
另外大概一个页面10+之后的人生点不了执行、日志、更多这些按钮
还有，点击任务弹出的窗口，有些没有日志

**Comment by aliyy2021** [comment]
同样问题，楼上兄弟解决了吗

**Comment by Kaystar** [comment]
> 同样问题，楼上兄弟解决了吗

木有，估计要等大佬下次更新了
