### ISSUE TITLE
2.12青龙问题

### ISSUE THREAD

**Issue by gz83** [whyour/qinglong#1271]
2.12青龙运行脚本的时候提示缺少auth文件，请问这个问题怎么办？

**Comment by gz83** [comment]
已通过修改脚本解决

**Comment by oudaiyi** [comment]
请问怎么解决的？

**Comment by gz83** [comment]
> 请问怎么解决的？

新版青龙改了auth文件的路径，改为了/ql/data/config/auth.json

手动去有问题的脚本里面改掉路径就行。
