### ISSUE TITLE
文件夹路径为ql/data导致许多脚本找不到文件

### ISSUE THREAD

**Issue by Pollo3470** [whyour/qinglong#1276]
最新2.12版
映射改为了ql/data，但很多脚本里路径写的是ql/，例如如ql/config，然而实际路径为ql/data/config导致找不到对应文件
请问这种情况该怎么解？

**Comment by jzl2163** [comment]
似乎可以尝试软链接，但我尝试删除旧的config文件夹时提示 Resource busy 无法删除

**Comment by Pollo3470** [comment]
我已经退回到旧版了，但我看到群里有人提供了软链接的脚本，过段时间看看情况再更新吧

**Comment by c270348095** [comment]
不看的么？-v $PWD/ql:/ql/data \   
![image](https://user-images.githubusercontent.com/12913916/160751973-f4eaf1f1-aaaf-49de-af5a-c739dd853551.png)

**Comment by Pollo3470** [comment]
> 不看的么？-v $PWD/ql:/ql/data \ ![image](https://user-images.githubusercontent.com/12913916/160751973-f4eaf1f1-aaaf-49de-af5a-c739dd853551.png)

所以呢，我问题描述说的很清楚了，你不看的么？

**Comment by chunkingzou** [comment]
我的也是如此，想要进去删除拉库的文件夹现在也删不了了
