### ISSUE TITLE
执行repo和raw指令时一直提醒“请先登录！”

### ISSUE THREAD

**Issue by CiaranZhou** [whyour/qinglong#129]
今天设置了一下服务器代理，重新启动容器之后就出现这种情况
面板已登录，cookie也填写好了，不知道是哪里出了问题
![image](https://user-images.githubusercontent.com/33545847/118351392-62a69580-b58e-11eb-888e-41420e1fd83c.png)

**Comment by whyour** [comment]
出现这个就是面板没登录

**Comment by CiaranZhou** [comment]
> 出现这个就是面板没登录

确定面板登录了的，甚至还试过换密码和账密一起换，依然提醒如此

在关闭服务器代理之后就好了

**Comment by woshiliuxu** [comment]
> 

你好 能具体说说这个关闭服务器代理在那个位置吗
