### ISSUE TITLE
拉库的通知没有详细内容了，上一版本正常

### ISSUE THREAD

**Issue by 450abba** [whyour/qinglong#1296]
其他脚本运行的通知完全正常，仅仅拉库的这个通知是这样的，不输出详细内容

![QQ图片20220402204333](https://user-images.githubusercontent.com/6029449/161383893-265d737a-96d0-4501-abbd-2cfe33aff96d.jpg)
![QQ图片20220402204323](https://user-images.githubusercontent.com/6029449/161383894-4acef1f7-b1b5-453f-874e-728967ecba49.jpg)

**Comment by 450abba** [comment]
v2.12.0  版本

**Comment by q8018414** [comment]
我v2.12.1拉库物权没有任何通知了。。每日都只能去看任务日志。

**Comment by q8018414** [comment]
通知正常的。任务日志没有办法在任务列表里面看了。。
