### ISSUE TITLE
早上新安装打不开

### ISSUE THREAD

**Issue by chenyajunai** [whyour/qinglong#1298]
已经解决了

**Comment by Hxina** [comment]
> 

你好，我现在也无法打开面板了，请问你是如何解决的？

**Comment by chenyajunai** [comment]
> > 
> 
> 你好，我也无法打开面板了，请问你现在是如何解决的？

我是删除容器重新部署了一下

**Comment by chenyajunai** [comment]
> 



> 如何备份容器让数据不丢失，重新部署呀

还是原来的挂载目录啊
