### ISSUE TITLE
刚更新的最新版，ql repo拉库添加定时任务还是不能发送通知，而且拉库日志在面板上也看不到了

### ISSUE THREAD

**Issue by Kaystar** [whyour/qinglong#1299]

**Comment by ShCby** [comment]
确实，我也发现了，请尽快修复

**Comment by a7590370** [comment]
早知道不升级了，每次升级都有各种奇怪BUG，任务里面没有日子，所有脚本运行都是1秒，没日志，没运行

**Comment by Kaystar** [comment]
> 早知道不升级了，每次升级都有各种奇怪BUG，任务里面没有日子，所有脚本运行都是1秒，没日志，没运行

哈哈哈，看来你还是太年轻啊，希望下个版本能搞定吧

**Comment by fghwett** [comment]
搞了半天，一直以为是我的问题，没想到是新版有问题了
