### ISSUE TITLE
chenzhe仓库更新失败

### ISSUE THREAD

**Issue by ramain828** [whyour/qinglong#13]
Fetching origin                                                                 
Username for 'https://github.com.cnpmjs.org':               
Password for 'https://@github.com.cnpmjs.org':               
remote: Repository not found.                                                   
fatal: repository 'https://github.com.cnpmjs.org/i-chenzhe/qx.git/' not found   
error: Could not fetch origin                                                   
HEAD is now at 28f510a Update jd_entertainment.js                               
Username for 'https://github.com.cnpmjs.org':                
Password for 'https://@github.com.cnpmjs.org':               
remote: Repository not found.                                                   
fatal: repository 'https://github.com.cnpmjs.org/i-chenzhe/qx.git/' not found   
i-chenzhe 仓库更新失败了. 

大佬，新手请教这是我的问题还是仓库不见了？

**Comment by whyour** [comment]
@ramain828 把你的crontab.list删了，执行git_pull重新生成下

**Comment by ramain828** [comment]
谢大佬
