### ISSUE TITLE
新版本如何自定义环境变量

### ISSUE THREAD

**Issue by Muqiqi** [whyour/qinglong#130]
更新新版后配置文件没有自定义环境变量了..
请问偶教程嘛

**Comment by Muqiqi** [comment]
我在env_name和var_name分别定义了QYWX_AM和QYWX_AM的值
并没有成功推送是我使用错误吗

![image](https://user-images.githubusercontent.com/26044865/118371975-abd40500-b5e1-11eb-8966-94e09a77332a.png)

**Comment by Acr05s** [comment]
你截图这部份是用来查找日志，取得互助码的，你把原来的备份出来推送那些复制过来才加在最后面就行了

**Comment by whyour** [comment]
这个只是个控制台，没有内置任何脚本，请参照https://t.me/qiongqiya/80 手动添加脚本
