### ISSUE TITLE
更新了最新版  面板serve报错了

### ISSUE THREAD

**Issue by CasbaL** [whyour/qinglong#1301]
![image](https://user-images.githubusercontent.com/26603379/161533459-5cd3c9a4-326e-4224-931e-28f6c3c19f95.png)
![image](https://user-images.githubusercontent.com/26603379/161533690-8e4dc8f8-ad20-4c6e-b548-dac9e8333961.png)

**Comment by whyour** [comment]
@CasbaL 你自动清除日志的频率写的太大了吧，先改成28天以下吧

**Comment by CasbaL** [comment]
> @CasbaL 你自动清除日志的频率写的太大了吧，先改成28天以下吧

z这个是要在哪里配置的😯

**Comment by whyour** [comment]
@CasbaL 系统设置 其他设置

**Comment by CasbaL** [comment]
> @CasbaL 系统设置 其他设置

刚才是进不去面板的😂 删了服务器上的之前的`/root/ql/scripts`重置了配置 🎉🎉🎉

**Comment by CasbaL** [comment]
> @CasbaL 系统设置 其他设置

刚才是进不去面板的😂 删了服务器上的之前的`/root/ql/scripts`重置了配置 🎉🎉🎉
