### ISSUE TITLE
aiohttp依赖无法安装，其他都没问题，求教谢谢！

### ISSUE THREAD

**Issue by swRains** [whyour/qinglong#1302]
开始安装依赖 aiohttp，开始时间 2022/4/4 21:13:52
Collecting aiohttp
  Using cached aiohttp-3.8.1.tar.gz (7.3 MB)
  Installing build dependencies: started
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.2.tar.gz (50 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/lib/python3.9/site-packages (from aiohttp) (2.0.7)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting attrs>=17.3.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.0.tar.gz (65 kB)
  Installing build dependencies: started
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.7.2.tar.gz (168 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: idna>=2.0 in /usr/lib/python3.9/site-packages (from yarl<2.0,>=1.0->aiohttp) (3.3)
  Building wheel for aiohttp (PEP 517): started
  Building wheel for frozenlist (PEP 517): started
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp6y8if91b
       cwd: /tmp/pip-install-0qgmjlow/frozenlist_5db3e36a18464d898f381e70b2d23bf6
  Complete output (36 lines):
  **********************
  * Accellerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/frozenlist
  copying frozenlist/__init__.py -> build/lib.linux-x86_64-3.9/frozenlist
  running egg_info
  writing frozenlist.egg-info/PKG-INFO
  writing dependency_links to frozenlist.egg-info/dependency_links.txt
  writing top-level names to frozenlist.egg-info/top_level.txt
  reading manifest file 'frozenlist.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '*.lib' found anywhere in distribution
  warning: no previously-included files matching '*.dll' found anywhere in distribution
  warning: no previously-included files matching '*.a' found anywhere in distribution
  warning: no previously-included files matching '*.obj' found anywhere in distribution
  warning: no previously-included files found matching 'frozenlist/*.html'
  no previously-included directories found matching 'docs/_build'
  adding license file 'LICENSE'
  writing manifest file 'frozenlist.egg-info/SOURCES.txt'
  copying frozenlist/__init__.pyi -> build/lib.linux-x86_64-3.9/frozenlist
  copying frozenlist/_frozenlist.pyx -> build/lib.linux-x86_64-3.9/frozenlist
  copying frozenlist/py.typed -> build/lib.linux-x86_64-3.9/frozenlist
  running build_ext
  building 'frozenlist._frozenlist' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/frozenlist
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.9 -c frozenlist/_frozenlist.c -o build/temp.linux-x86_64-3.9/frozenlist/_frozenlist.o
  error: command 'gcc' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for frozenlist
  Building wheel for multidict (PEP 517): started
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpb93lwijc
       cwd: /tmp/pip-install-0qgmjlow/multidict_c22c701cb76b48fd824fae236d16537e
  Complete output (36 lines):
  *********************
  * Accelerated build *
  *********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/multidict
  copying multidict/_multidict_base.py -> build/lib.linux-x86_64-3.9/multidict
  copying multidict/__init__.py -> build/lib.linux-x86_64-3.9/multidict
  copying multidict/_compat.py -> build/lib.linux-x86_64-3.9/multidict
  copying multidict/_abc.py -> build/lib.linux-x86_64-3.9/multidict
  copying multidict/_multidict_py.py -> build/lib.linux-x86_64-3.9/multidict
  running egg_info
  writing multidict.egg-info/PKG-INFO
  writing dependency_links to multidict.egg-info/dependency_links.txt
  writing top-level names to multidict.egg-info/top_level.txt
  reading manifest file 'multidict.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files found matching 'multidict/_multidict.html'
  warning: no previously-included files found matching 'multidict/*.so'
  warning: no previously-included files found matching 'multidict/*.pyd'
  warning: no previously-included files found matching 'multidict/*.pyd'
  no previously-included directories found matching 'docs/_build'
  adding license file 'LICENSE'
  writing manifest file 'multidict.egg-info/SOURCES.txt'
  copying multidict/__init__.pyi -> build/lib.linux-x86_64-3.9/multidict
  copying multidict/py.typed -> build/lib.linux-x86_64-3.9/multidict
  running build_ext
  building 'multidict._multidict' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/multidict
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.9 -c multidict/_multidict.c -o build/temp.linux-x86_64-3.9/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  error: command 'gcc' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for multidict
  Building wheel for yarl (PEP 517): started
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp16v_w8og
       cwd: /tmp/pip-install-0qgmjlow/yarl_aa3b56cf1c7a42298801d6c6f56a79b5
  Complete output (39 lines):
  **********************
  * Accelerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/yarl
  copying yarl/_quoting_py.py -> build/lib.linux-x86_64-3.9/yarl
  copying yarl/_quoting.py -> build/lib.linux-x86_64-3.9/yarl
  copying yarl/__init__.py -> build/lib.linux-x86_64-3.9/yarl
  copying yarl/_url.py -> build/lib.linux-x86_64-3.9/yarl
  running egg_info
  writing yarl.egg-info/PKG-INFO
  writing dependency_links to yarl.egg-info/dependency_links.txt
  writing requirements to yarl.egg-info/requires.txt
  writing top-level names to yarl.egg-info/top_level.txt
  reading manifest file 'yarl.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.cache' found anywhere in distribution
  warning: no previously-included files found matching 'yarl/*.html'
  warning: no previously-included files found matching 'yarl/*.so'
  warning: no previously-included files found matching 'yarl/*.pyd'
  no previously-included directories found matching 'docs/_build'
  adding license file 'LICENSE'
  writing manifest file 'yarl.egg-info/SOURCES.txt'
  copying yarl/__init__.pyi -> build/lib.linux-x86_64-3.9/yarl
  copying yarl/_quoting_c.c -> build/lib.linux-x86_64-3.9/yarl
  copying yarl/_quoting_c.pyi -> build/lib.linux-x86_64-3.9/yarl
  copying yarl/_quoting_c.pyx -> build/lib.linux-x86_64-3.9/yarl
  copying yarl/py.typed -> build/lib.linux-x86_64-3.9/yarl
  running build_ext
  building 'yarl._quoting_c' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/yarl
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.9 -c yarl/_quoting_c.c -o build/temp.linux-x86_64-3.9/yarl/_quoting_c.o
  error: command 'gcc' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for yarl
ERROR: Could not build wheels for aiohttp, frozenlist, multidict, yarl which use PEP 517 and cannot be installed directly
依赖安装失败，结束时间 2022/4/4 21:15:01，耗时 69.031 秒

**Comment by bugme2** [comment]
先升级pip就能安装了

**Comment by swRains** [comment]
> 先升级pip就能安装了

谢谢，成功了
