### ISSUE TITLE
[BUG] 青龙v2.12.1 升级失败 且 运行脚本时日志文件夹创建位置错误

### ISSUE THREAD

**Issue by IITII** [whyour/qinglong#1303]
* 一开始是直接升级失败，感觉像是脚本判断有问题，提示了一些 git checkout - 之类的错误
> 这个不是很在意，直接最新版重建容器了  

* 重建之后发现定时任务没有触发，又重建了一次还是不行，排查如下：

```
# docker logs
# task 直接运行
root@qinglong:/ql $ task gys619_Absinthe_main/jd_ms.js now
/usr/local/bin/task: line 107: /ql/data/log/gys619_Absinthe_main_jd_ms/2022-04-05-01-54-03.log: No such file or directory
```
* 检查 `/ql/data/log/` 确实没有创建对应文件夹
* 检查 `/ql` 发现多了很多奇奇怪怪的文件，grep 了一下，包含上面缺少的文件夹
> 这说明是文件夹创建的时候目录选择错了

**Comment by sukanka** [comment]
我也是,遇到了同样的问题,同样的版本,正在手动创建文件夹

**Comment by IITII** [comment]
阿哲，其实我最开始的时候就把日志删除了。。。
* 现在回滚了上一个版本
