### ISSUE TITLE
没有日志

### ISSUE THREAD

**Issue by CkeWMX** [whyour/qinglong#1304]
我执行任何脚本  点开日志 都显示的暂无日志 求解

**Comment by a7590370** [comment]
升级2.12.1，没日志，所有脚本都是运行1秒

**Comment by CkeWMX** [comment]
> 升级2.12.1，没日志，所有脚本都是运行1秒

对 就这个情况

**Comment by xhackf** [comment]
看到不止我一个人这样心里就踏实了。坐等修复。。

**Comment by CkeWMX** [comment]
> 看到不止我一个人这样心里就踏实了。坐等修复。。

好像可以了  我一直没动  但是我现在用  有日志了

**Comment by Zayia** [comment]
害我重装了一遍，还以为自己的问题

**Comment by feiniao025** [comment]
拉的最新版本重新安装也是没日志
