### ISSUE TITLE
大佬，求修复通知啊，持续两个版本了，拉库添加定时任务成功都不能发送通知！！！！

### ISSUE THREAD

**Issue by Kaystar** [whyour/qinglong#1308]

**Comment by Zayia** [comment]
我拉库就成功不了

**Comment by IITII** [comment]
这个配置需要你手动写进config里面，配置文件编辑那里

**Comment by Zayia** [comment]
> 

更新了docker镜像后重启了docker容器后问题得到了解决，日志也恢复正常了

**Comment by Kaystar** [comment]
> > 
> 
> 更新了docker镜像后重启了docker容器后问题得到了解决，日志也恢复正常了

拉库添加定时任务有通知了？

**Comment by Zayia** [comment]
> > > 
> > 
> > 
> > 更新了docker镜像后重启了docker容器后问题得到了解决，日志也恢复正常了
> 
> 拉库添加定时任务有通知了？

全部恢复正常了

**Comment by Kaystar** [comment]
> > > > 
> > > 
> > > 
> > > 更新了docker镜像后重启了docker容器后问题得到了解决，日志也恢复正常了
> > 
> > 
> > 拉库添加定时任务有通知了？
> 
> 全部恢复正常了

哪个版本的镜像，确实是拉库添加定时任务有通知？
