### ISSUE TITLE
无法更新脚本 2.0.0版本

### ISSUE THREAD

**Issue by CrazyMouse** [whyour/qinglong#131]
手动执行，显示

docker exec -it qinglong ql update
--------------------------------------------------------------

开始更新仓库：/ql

Fetching origin
HEAD is now at 7ff6909 修复build action
Already up to date.

更新/ql成功...

开始更新仓库：/ql/repo/static

Fetching origin
HEAD is now at 02a7136 copy static at 2021-05-14 17:55:51
Already up to date.

更新/ql/repo/static成功...

重启面板中...

然后页面没有任何变化，重启docker也不行

**Comment by HaneRo** [comment]
这个只是个控制台，没有内置任何脚本，请参照https://t.me/qiongqiya/80 手动添加脚本

**Comment by CrazyMouse** [comment]
> 这个只是个控制台，没有内置任何脚本，请参照https://t.me/qiongqiya/80 手动添加脚本

收到，非常感谢
