### ISSUE TITLE
提几个功能建议

### ISSUE THREAD

**Issue by Luxuslaerm** [whyour/qinglong#1317]
1. 免密登录。我部署在内网，安全性要求没那么高，有时候会用mac或pc不同设备登录，发现会把其他设备的登录挤掉，虽然浏览器保存了密码，但每次都多点那么两下，还是很不方便
2. 定时任务增加按标签筛选功能。现在任务可以打标签，但是这个标签好像没有任何作用。我拉了很多库，一个使用中的痛点是想分类筛选一下，没有筛选功能，只有一个简陋的搜索框（还不如ctrl+f快哈哈）
3.关闭登录通知。每次登录进来右上角的登录通知弹框很鸡肋，还得手动关掉，逼死强迫症（有效信息太少，所以基本很少去看，要么只提示异常信息，要么设置成可关闭通知）

**Comment by zoulux** [comment]
同求 标签筛选功能
