### ISSUE TITLE
大哥们 为啥每次青龙面板一更新我的就成这样了啊，要重新安装？

### ISSUE THREAD

**Issue by mangrove2014** [whyour/qinglong#1320]
![image](https://user-images.githubusercontent.com/7719372/162648868-d4477880-8cc0-4aa9-82f2-9c1a75c23e0b.png)

**Comment by mangrove2014** [comment]
已经遇到好多次了 心好累

**Comment by mangrove2014** [comment]
哥哥们 求帮助

**Comment by ShellMonster** [comment]
没有 -v保存配置，参考readme的安装方式吧

**Comment by jackadam1981** [comment]
docker run -dit \
  -v $PWD/ql/config:/ql/config \
  -v $PWD/ql/log:/ql/log \
  -v $PWD/ql/db:/ql/db \
  -v $PWD/ql/repo:/ql/repo \
  -v $PWD/ql/raw:/ql/raw \
  -v $PWD/ql/scripts:/ql/scripts \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest



podman run -dit \
  --network bridge \
  -v $PWD/ql:/ql/data \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  docker.io/whyour/qinglong:latest

持久化路径改了。
我也纳闷呢，仔细看了readme，存储路径改了，修改你的启动命令，docker-compose吧。
