### ISSUE TITLE
升级到v2.12.1版本后运行速度慢多了

### ISSUE THREAD

**Issue by miaoyanginfo** [whyour/qinglong#1325]
升级到v2.12.1版本后，搜索输入关键字、切换导航的时候感觉很卡顿，没有之前流畅了。

**Comment by maryjeck** [comment]
是的，我也慢了好多，一个一个字母的蹦出来

**Comment by tvrohd** [comment]
这个版本的配置文件在哪里啊  找半天都没找到

**Comment by miaoyanginfo** [comment]
> 是的，我也慢了好多，一个一个字母的蹦出来

把能装的依赖都装一遍，会好一点。
