### ISSUE TITLE
[BUG] 多行环境变量添加问题

### ISSUE THREAD

**Issue by xjasonlyu** [whyour/qinglong#1331]
### 版本：v2.12.1

在青龙面板里添加一些多行的环境变量时，会出现一些奇怪的问题，例如：

### 1. 空格丢失

想要添加如下`CURL`变量：

```shell
curl -k -X GET -H "Content-Type: application/json" -H "Host: example.com" -H "Connection: keep-alive" "https://example.com"
```
在env.sh文件中会变成如下所示，失去了空格：

```
export CURL='curl-k-XGET-H"Content-Type:application/json"-H"Host:example.com"-H"Connection:keep-alive""https://example.com"'
```

### 2. 引号转译问题

想要添加如下`CURL`变量：

```shell
curl 'https://example.com' \
  -H 'authority: example.com' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
  -H 'dnt: 1' \
  -H 'referer: https://example.com' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed
```
在env.sh文件中会变成如下所示，单引号字符串错了（空格也丢失了）：

```
export CURL='curl'https://example.com'\
-H'authority:example.com\
-H'accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'\
-H'accept-language:en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7'\
-H'dnt:1'\
-H'referer:https://example.com/'\
-H'sec-ch-ua:"NotA;Brand";v="99","Chromium";v="100","GoogleChrome";v="100"'\
-H'sec-ch-ua-mobile:?0'\
-H'sec-ch-ua-platform:"macOS"'\
--compressed'

```

**Comment by JerryWn12** [comment]
<del>你这网站搞黄色啊</del>

**Comment by xjasonlyu** [comment]
这个问题在`v2.12.2`中依旧没有解决。

添加一段环境变量，在env.sh中引号转译依然存在问题：
`export CURL="curl -k -X GET -H "Content-Type: application/json" -H "Connection: keep-alive" "https://example.com""`

可以从Chrome中随机打开一个网址然后copy as curl作为环境变量添加进青龙即可复现。

**Comment by whyour** [comment]
> 这个问题在`v2.12.2`中依旧没有解决。
> 
> 添加一段环境变量，在env.sh中引号转译依然存在问题： `export CURL="curl -k -X GET -H "Content-Type: application/json" -H "Connection: keep-alive" "https://example.com""`
> 
> 可以从Chrome中随机打开一个网址然后copy as curl作为环境变量添加进青龙即可复现。

这个不影响你脚本使用吧，里面的引号都转义了，你写个脚本获取这个环境变量试试

**Comment by xjasonlyu** [comment]
而且还有个问题就是，反斜杠`\`被去掉了。

**Comment by whyour** [comment]
@xjasonlyu task执行的？ 反斜杠本来就是个没有意义的符号，会自动转成一行执行

**Comment by xjasonlyu** [comment]
在task里执行依旧是不完整的，因为env.sh里的语义就错误了：

<img width="1283" alt="Screen Shot 2022-04-25 at 8 46 50 PM" src="https://user-images.githubusercontent.com/28824352/165092054-7a89faa5-3c99-4886-858e-a39daa05a969.png">

> 反斜杠本来就是个没有意义的符号，会自动转成一行执行

反斜杠作为一个符号时是有意义的，例如我有个脚本需要从环境变量获取一个密钥，但是密钥里有个反斜杠，这时在青龙里就会报错。

例如添加`\it's a special key\`作为变量，运行就会出错：

<img width="1013" alt="Screen Shot 2022-04-25 at 8 55 06 PM" src="https://user-images.githubusercontent.com/28824352/165093313-f800b8b8-bbd1-434c-920c-4dc55da7e4c3.png">

**Comment by whyour** [comment]
> \it's a special key\

c0d401e296ae6d99a81d4a22c47f586567ff3c8b 这样应该就行了，可以用develop镜像试试
