### ISSUE TITLE
删除日志错误

### ISSUE THREAD

**Issue by woboo110** [whyour/qinglong#134]
![image](https://user-images.githubusercontent.com/68997087/118388341-6dc4f880-b656-11eb-8a06-36f304c3bbc4.png)

**Comment by woboo110** [comment]
已解决

**Comment by woboo110** [comment]
貌似是遇到bot日志文件无法删除出错

**Comment by whyour** [comment]
> 貌似是遇到bot日志文件无法删除出错

是的，我改下

**Comment by whyour** [comment]
https://t.me/qiongqiya/88
使用最新版试试

**Comment by woboo110** [comment]
> https://t.me/qiongqiya/88
> 使用最新版试试

可以了，大佬辛苦
