### ISSUE TITLE
python依赖lxml安装失败

### ISSUE THREAD

**Issue by zhengwei77** [whyour/qinglong#1343]
开始安装依赖 lxml，开始时间 2022/4/19 10:42:40
Collecting lxml
  Using cached lxml-4.8.0.tar.gz (3.2 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/3b/94/e2b1b3bad91d15526c7e38918795883cee18b93f6785ea8ecf13f8ffa01e/lxml-4.8.0.tar.gz#sha256=f63f62fc60e6228a4ca9abae28228f35e1bd3ce675013d1dfb828688d50c6e23 (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lxml-4.7.1.tar.gz (3.2 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/84/74/4a97db45381316cd6e7d4b1eb707d7f60d38cb2985b5dfd7251a340404da/lxml-4.7.1.tar.gz#sha256=a1613838aa6b89af4ba10a0f3a972836128801ed008078f8c1244e65958f1b24 (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lxml-4.6.5.tar.gz (3.2 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/e6/e1/34b3ab08553fe9a30e15b2bb9d1803a49d7d907dd9f245638839190042f0/lxml-4.6.5.tar.gz#sha256=6e84edecc3a82f90d44ddee2ee2a2630d4994b8471816e226d2b771cda7ac4ca (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lxml-4.6.4.tar.gz (3.2 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/fe/4c/a4dbb4e389f75e69dbfb623462dfe0d0e652107a95481d40084830d29b37/lxml-4.6.4.tar.gz#sha256=daf9bd1fee31f1c7a5928b3e1059e09a8d683ea58fb3ffc773b6c88cb8d1399c (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lxml-4.6.3.tar.gz (3.2 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/e5/21/a2e4517e3d216f0051687eea3d3317557bde68736f038a3b105ac3809247/lxml-4.6.3.tar.gz#sha256=39b78571b3b30645ac77b95f7c69d1bffc4cf8c3b157c435a34da72e78c82468 (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lxml-4.6.2.tar.gz (3.2 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/db/f7/43fecb94d66959c1e23aa53d6161231dca0e93ec500224cf31b3c4073e37/lxml-4.6.2.tar.gz#sha256=cd11c7e8d21af997ee8079037fff88f16fda188a9776eb4b81c7e4c9c0a7d7fc (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lxml-4.6.1.tar.gz (3.2 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/c5/2f/a0d8aa3eee6d53d5723d89e1fc32eee11e76801b424e30b55c7aa6302b01/lxml-4.6.1.tar.gz#sha256=c152b2e93b639d1f36ec5a8ca24cde4a8eefb2b6b83668fcd8e83a67badcb367 (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lxml-4.6.0.tar.gz (3.2 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/3c/5a/81446fb5a4706bb07a98427634ab93219dc7fa393841d81f5da5c7e151b7/lxml-4.6.0.tar.gz#sha256=8319abacbbe9fd9791c2e3c23deb9b6a16abc0fcbdfcc26722035e865b3d207f (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lxml-4.5.2.tar.gz (4.5 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/2c/4d/3ec1ea8512a7fbf57f02dee3035e2cce2d63d0e9c0ab8e4e376e01452597/lxml-4.5.2.tar.gz#sha256=cdc13a1682b2a6241080745b1953719e7fe0850b40a5c71ca574f090a1391df6 (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lxml-4.5.1.tar.gz (4.5 MB)
WARNING: Discarding https://files.pythonhosted.org/packages/03/a8/73d795778143be51d8b86750b371b3efcd7139987f71618ad9f4b8b65543/lxml-4.5.1.tar.gz#sha256=27ee0faf8077c7c1a589573b1450743011117f1aa1a91d5ae776bbc5ca6070f2 (from https://pypi.org/simple/lxml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, != 3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lxml-4.5.0.tar.gz (4.5 MB)
Using legacy 'setup.py install' for lxml, since package 'wheel' is not installed.
    Running setup.py install for lxml: started
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4lmw6nd6/lxml_d65dc11115274c14ba6cbe3b6aa4800c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4lmw6nd6/lxml_d65dc11115274c14ba6cbe3b6aa4800c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6v52x1kq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/lxml
         cwd: /tmp/pip-install-4lmw6nd6/lxml_d65dc11115274c14ba6cbe3b6aa4800c/
    Complete output (87 lines):
    Building lxml version 4.5.0.
    Building without Cython.
    ERROR: b'/bin/sh: xslt-config: not found\n'
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.9
    creating build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/builder.py -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/sax.py -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/__init__.py -> build/lib.linux-aarch64-3.9/lxml
    creating build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-aarch64-3.9/lxml/includes
    creating build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-aarch64-3.9/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-aarch64-3.9/lxml/html
    creating build/lib.linux-aarch64-3.9/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-aarch64-3.9/lxml/isoschematron
    copying src/lxml/etree.h -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/etree_api.h -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/lxml.etree.h -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-aarch64-3.9/lxml
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/__init__.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-aarch64-3.9/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-aarch64-3.9/lxml/includes
    creating build/lib.linux-aarch64-3.9/lxml/isoschematron/resources
    creating build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/rng
    creating build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/xsl
    creating build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-aarch64-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-aarch64-3.9
    creating build/temp.linux-aarch64-3.9/src
    creating build/temp.linux-aarch64-3.9/src/lxml
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g -fno-semantic-interposition -g -fno-semantic-interposition -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/include/python3.9 -c src/lxml/etree.c -o build/temp.linux-aarch64-3.9/src/lxml/etree.o -w
    Compile failed: command 'gcc' failed: No such file or directory
    creating tmp
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitpjdm8ksp.c -o tmp/xmlXPathInitpjdm8ksp.o
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'gcc' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4lmw6nd6/lxml_d65dc11115274c14ba6cbe3b6aa4800c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4lmw6nd6/lxml_d65dc11115274c14ba6cbe3b6aa4800c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6v52x1kq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/lxml Check the logs for full command output.
依赖安装失败，结束时间 2022/4/19 10:44:26，耗时 106.883 秒

**Comment by Hchunjun** [comment]
尝试好几次，都是失败的
