### ISSUE TITLE
通过面板安装的依赖有重复的，但删不掉，请问有没有清空面板上依赖的方法？

### ISSUE THREAD

**Issue by wallinwind** [whyour/qinglong#1347]
强迫症有点受不了，难道只能重装》

**Comment by SkysCrystal** [comment]
一直显示安装中和删除中，不知要如何处理。
![image](https://user-images.githubusercontent.com/49473463/164726036-a9a25613-5ae0-42a0-ad4a-56154e6bfee4.png)
现在新的依赖似乎安装不上了

**Comment by qqsir-dev** [comment]
确实删不掉，我的也是，不小心忘记拆分了，结果安装失败，但是还删不掉。
开始删除依赖 canvas
requests
ping3
jieba，开始时间 2022/4/23 12:33:53
WARNING: Skipping canvas as it is not installed.
/bin/bash: line 2: requests: command not found
ping 'example.com' ... 152ms
ping 'example.com' ... 152ms
ping 'example.com' ... 152ms
ping 'example.com' ... 152ms
ping '8.8.8.8' ... 40ms
ping '8.8.8.8' ... 40ms
ping '8.8.8.8' ... 40ms
ping '8.8.8.8' ... 40ms
依赖删除失败，结束时间 2022/4/23 12:33:55，耗时 1.195 秒

**Comment by wrx0804** [comment]
不小心忘记拆分了，一直显示删除中，其他的重名的依赖 一直在里面，明明有这个依赖文件，最后跑脚本的时候，又说，缺乏这个文件。
