### ISSUE TITLE
拉取的脚本也有随意执行`ql repo`的权限

### ISSUE THREAD

**Issue by donething** [whyour/qinglong#1349]
我用`ql repo`设置的每天晚上8点拉取更新某个仓库，但实际上这个仓库每几十分钟都会自己执行`ql repo`，而且不受我设置的黑名单限制，多拉取一些统计脚本。

这种设计是否有问题？

希望能限制脚本执行`ql repo`的能力，至少要按照最开始设置的黑白名单拉取新代码。

**Comment by kuilei0926** [comment]
脚本是有所有权限的，包括格式化你的计算机

**Comment by donething** [comment]
> 

谢谢，不过青龙运行在容器中，不担心对主机的安全问题。

只是拉库时设置的黑名单成了摆设，意义不大了。
