### ISSUE TITLE
bot无法通知

### ISSUE THREAD

**Issue by CrazyMouse** [whyour/qinglong#135]
确认bot已经启动，因为TG直接和bot对话有响应，各种都正常，现在就不知道为啥bot不给发通知，比如说我手动执行“资产变动通知”的脚本，它也不给发通知，不知道哪位知道可能是什么原因，望告知，非常感谢！

**Comment by cjh19831115** [comment]
同样。更新以后就不能用了

**Comment by whyour** [comment]
> 确认bot已经启动，因为TG直接和bot对话有响应，各种都正常，现在就不知道为啥bot不给发通知，比如说我手动执行“资产变动通知”的脚本，它也不给发通知，不知道哪位知道可能是什么原因，望告知，非常感谢！

bot启动，脚本需要的环境变量配置加了吗。https://t.me/qiongqiya/81

**Comment by CrazyMouse** [comment]
> > 确认bot已经启动，因为TG直接和bot对话有响应，各种都正常，现在就不知道为啥bot不给发通知，比如说我手动执行“资产变动通知”的脚本，它也不给发通知，不知道哪位知道可能是什么原因，望告知，非常感谢！
> 
> bot启动，脚本需要的环境变量配置加了吗。https://t.me/qiongqiya/81

bot.json 加上了，config.sh 还要重复添加一遍么？

**Comment by whyour** [comment]
@CrazyMouse 目前不是这个东西

**Comment by CrazyMouse** [comment]
> @CrazyMouse 目前不是这个东西

我想请教一下，我在config.sh配置了toke+userID,并且bot.json配置了相应的4个参数就起来了，并且可以正常发通知了。总感觉这配置两遍有点多余，是否有考虑把通知部分直接集成进来，在config.sh里面配置一遍就行了。另外，bot.json需要4个参数，我自己go写的通知，实际上一个token外加一个userID就可以搞定的

**Comment by whyour** [comment]
> > @CrazyMouse 目前不是这个东西
> 
> 我想请教一下，我在config.sh配置了toke+userID,并且bot.json配置了相应的4个参数就起来了，并且可以正常发通知了。总感觉这配置两遍有点多余，是否有考虑把通知部分直接集成进来，在config.sh里面配置一遍就行了。另外，bot.json需要4个参数，我自己go写的通知，实际上一个token外加一个userID就可以搞定的

这是两个项目，如果bot那边可以直接读取环境变量就不需要bot.json了
