### ISSUE TITLE
拉库添加脚本成功，通知发送失败的问题已经持续三个版本了？什么时候能解决一下呢？

### ISSUE THREAD

**Issue by Kaystar** [whyour/qinglong#1358]

**Comment by Kaystar** [comment]
从2.12.0到2.12.1，现在都2.12.2了，三个版本了，一直在反映这个问题，太难了。。。。。

**Comment by whyour** [comment]
@Kaystar 系统设置添加通知方式

**Comment by Kaystar** [comment]
> @Kaystar 系统设置添加通知方式

大佬，这样的话每次登录都会发通知，而且使用bot的时候也会有问题，这个之前我也提过。毕竟不是每个人都需要登录通知的嘛，以前那样系统通知和拉库脚本通知分开就挺好，能否改回以前那样呢？

**Comment by whyour** [comment]
> > @Kaystar 系统设置添加通知方式
> 
> 大佬，这样的话每次登录都会发通知，而且使用bot的时候也会有问题，这个之前我也提过。毕竟不是每个人都需要登录通知的嘛，以前那样系统通知和拉库脚本通知分开就挺好，能否改回以前那样呢？

脚本那么多通知，多一个登录通知也没啥问题吧，拉库属于系统操作，不属于脚本的通知。所以跟登录用同一个我觉得是没问题的。即使后面单独设置脚本的通知方式，拉取仓库应该也是用系统的通知

**Comment by Kaystar** [comment]
> > > @Kaystar 系统设置添加通知方式
> > 
> > 
> > 大佬，这样的话每次登录都会发通知，而且使用bot的时候也会有问题，这个之前我也提过。毕竟不是每个人都需要登录通知的嘛，以前那样系统通知和拉库脚本通知分开就挺好，能否改回以前那样呢？
> 
> 脚本那么多通知，多一个登录通知也没啥问题吧，拉库属于系统操作，不属于脚本的通知。所以跟登录用同一个我觉得是没问题的。即使后面单独设置脚本的通知方式，拉取仓库应该也是用系统的通知

登录通知和拉库通知都是系统通知用一个通知没问题，但是也没有要使用拉库通知就必须要使用登录通知的道理嘛。是否可以给登录通知一个开关呢？给个选择让我们自己选择嘛，登录通知真的不是每个人都需要的，脚本通知虽然多，但是可以屏蔽不需要的通知。

**Comment by showmexlq** [comment]
@whyour 确实我也建议系统通知和登录分开来设置比较好
