### ISSUE TITLE
更新后，面板空白

### ISSUE THREAD

**Issue by woboo110** [whyour/qinglong#136]
更新完，刷新后面板一片空白

**Comment by cjh19831115** [comment]
我的也一样

**Comment by 231838238** [comment]
too

**Comment by yaojia25** [comment]
+1

**Comment by whyour** [comment]
把你们更新完的日志贴出来

**Comment by 231838238** [comment]
开始更新仓库：/ql

Fetching origin
HEAD is now at 5b6a754 更新config.sample
Updating 5b6a754..4f0121e
Fast-forward
 src/pages/crontab/index.tsx | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

更新/ql成功...

开始更新仓库：/ql/repo/static

Fetching origin
HEAD is now at 2194821 copy static at 2021-05-16 12:08:13
Updating 2194821..8edd1a7
Fast-forward
 dist/index.html         |   2 +-
 dist/umi.8a9214f7.js    |   1 +
 dist/umi.8a9214f7.js.gz | Bin 0 -> 465541 bytes
 3 files changed, 2 insertions(+), 1 deletion(-)
 create mode 100644 dist/umi.8a9214f7.js
 create mode 100644 dist/umi.8a9214f7.js.gz

更新/ql/repo/static成功...

重启面板中...

**Comment by woboo110** [comment]
> 把你们更新完的日志贴出来

--------------------------------------------------------------

开始更新仓库：/ql

Fetching origin
HEAD is now at 4f0121e 更新队列中图标
Already up to date.

更新/ql成功...

开始更新仓库：/ql/repo/static

Fetching origin
HEAD is now at 8edd1a7 copy static at 2021-05-16 12:37:28
Already up to date.

更新/ql/repo/static成功...

重启面板中...

**Comment by whyour** [comment]
再刷新一次

**Comment by 231838238** [comment]
不行，没有更新的一样没有管理页面

**Comment by lunjielee** [comment]
启动不起来，yarn安装了p-queue也不行
pm2 logs
```
1|schedule  | Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /ql/node_modules/p-queue/dist/index.js
1|schedule  | require() of ES modules is not supported.
1|schedule  | require() of /ql/node_modules/p-queue/dist/index.js from /ql/build/services/cron.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
1|schedule  | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /ql/node_modules/p-queue/package.json.
1|schedule  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
1|schedule  |     at Module.load (internal/modules/cjs/loader.js:928:32)
1|schedule  |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
1|schedule  |     at Module.require (internal/modules/cjs/loader.js:952:19)
1|schedule  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
1|schedule  |     at require (internal/modules/cjs/helpers.js:88:18)
1|schedule  |     at Object.<anonymous> (/ql/back/services/cron.ts:10:1)
1|schedule  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
1|schedule  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
1|schedule  |     at Module.load (internal/modules/cjs/loader.js:928:32) {
1|schedule  |   code: 'ERR_REQUIRE_ESM'
1|schedule  | }
0|panel     | Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /ql/node_modules/p-queue/dist/index.js
0|panel     | require() of ES modules is not supported.
0|panel     | require() of /ql/node_modules/p-queue/dist/index.js from /ql/build/services/cron.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
0|panel     | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /ql/node_modules/p-queue/package.json.
0|panel     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
0|panel     |     at Module.load (internal/modules/cjs/loader.js:928:32)
0|panel     |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
0|panel     |     at Module.require (internal/modules/cjs/loader.js:952:19)
0|panel     |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|panel     |     at require (internal/modules/cjs/helpers.js:88:18)
0|panel     |     at Object.<anonymous> (/ql/back/services/cron.ts:10:1)
0|panel     |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|panel     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
0|panel     |     at Module.load (internal/modules/cjs/loader.js:928:32) {
0|panel     |   code: 'ERR_REQUIRE_ESM'
0|panel     | }
```

**Comment by daitangjun** [comment]
一样。。。

**Comment by 231838238** [comment]
任务可以正常执行，就是登陆不了后台

**Comment by whyour** [comment]
再执行一次 ql update

**Comment by lunjielee** [comment]
启动了，具体解决方法如下：

1. 进入qinglong容器
`sudo docker exec -it qinglong /bin/sh`
2. 确保当前目录是/ql(通常情况下是的)，检查pm2日志查看是否缺少p-queue
`pm2 logs panel`
3. 安装p-queue
`yarn add p-queue`
速度太慢的话先添加淘宝源
`yarn config set registry https://registry.npm.taobao.org/`
4. 移除所有的pm2进程
`pm2 stop all && pm2 delete all`
5. 重新在/ql目录运行下yarn install
`yarn install`
6. 手动运行api看看是否正常
`node build/app.js`
输出下图为正常: 
```
1|schedule | info:
1|schedule |       ################################################
1|schedule |       🛡️  Schedule listening on port: 5500 🛡️
1|schedule |       ################################################
1|schedule |
```
7. 退出容器并重启容器

**Comment by whyour** [comment]
> 启动了，具体解决方法如下：
> 
> 1. 进入qinglong容器
>    `sudo docker exec -it qinglong /bin/sh`
> 2. 确保当前目录是/ql(通常情况下是的)，检查pm2日志查看是否缺少p-queue
>    `pm2 logs panel`
> 3. 安装p-queue
>    `yarn add p-queue`
>    速度太慢的话先添加淘宝源
>    `yarn config set registry https://registry.npm.taobao.org/`
> 4. 移除所有的pm2进程
>    `pm2 stop all && pm2 delete all`
> 5. 重新在/ql目录运行下yarn install
>    `yarn install`
> 6. 手动运行api看看是否正常
>    `node build/app.js`
>    输出下图为正常:
> 
> ```
> 1|schedule | info:
> 1|schedule |       ################################################
> 1|schedule |       🛡️  Schedule listening on port: 5500 🛡️
> 1|schedule |       ################################################
> 1|schedule |
> ```
> 
> 1. 退出容器并重启容器

不需要，执行ql update就行了

**Comment by woboo110** [comment]
好了

**Comment by li258w** [comment]
2次都卡在这里不动了

root@OpenWrt-DaHuiLang:/# docker exec -it qinglong ql update
--------------------------------------------------------------

开始更新仓库：/ql

Fetching origin
HEAD is now at 0247750 修复ql依赖无法安装
Already up to date.

更新/ql成功...

检测到 /ql 的依赖包有变化，运行 npm install...

检测到本机安装了 yarn，使用 yarn 替代 npm...

yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...

**Comment by woboo110** [comment]
> 2次都卡在这里不动了
> 
> ## root@OpenWrt-DaHuiLang:/# docker exec -it qinglong ql update
> 开始更新仓库：/ql
> 
> Fetching origin
> HEAD is now at [0247750](https://github.com/whyour/qinglong/commit/024775011fad9a8793241864ff23d38534b7f548) 修复ql依赖无法安装
> Already up to date.
> 
> 更新/ql成功...
> 
> 检测到 /ql 的依赖包有变化，运行 npm install...
> 
> 检测到本机安装了 yarn，使用 yarn 替代 npm...
> 
> yarn install v1.22.5
> [1/4] Resolving packages...
> [2/4] Fetching packages...

等着，很慢

**Comment by cjh19831115** [comment]
速度很慢

**Comment by 231838238** [comment]
> > 2次都卡在这里不动了
> > ## root@OpenWrt-DaHuiLang:/# docker exec -it qinglong ql update
> > 开始更新仓库：/ql
> > Fetching origin
> > HEAD is now at [0247750](https://github.com/whyour/qinglong/commit/024775011fad9a8793241864ff23d38534b7f548) 修复ql依赖无法安装
> > Already up to date.
> > 更新/ql成功...
> > 检测到 /ql 的依赖包有变化，运行 npm install...
> > 检测到本机安装了 yarn，使用 yarn 替代 npm...
> > yarn install v1.22.5
> > [1/4] Resolving packages...
> > [2/4] Fetching packages...
> 
> 等着，很慢

不用等 关了再来就行

**Comment by 231838238** [comment]
> 2次都卡在这里不动了
> 
> ## root@OpenWrt-DaHuiLang:/# docker exec -it qinglong ql update
> 开始更新仓库：/ql
> 
> Fetching origin
> HEAD is now at [0247750](https://github.com/whyour/qinglong/commit/024775011fad9a8793241864ff23d38534b7f548) 修复ql依赖无法安装
> Already up to date.
> 
> 更新/ql成功...
> 
> 检测到 /ql 的依赖包有变化，运行 npm install...
> 
> 检测到本机安装了 yarn，使用 yarn 替代 npm...
> 
> yarn install v1.22.5
> [1/4] Resolving packages...
> [2/4] Fetching packages...

不用等 关了再来一次就行

**Comment by li258w** [comment]
确实很慢，10分钟。ok了，多谢！
