### ISSUE TITLE
青龙代理

### ISSUE THREAD

**Issue by doudouded** [whyour/qinglong#1361]
好哥哥，青龙怎么加代理呀，让青龙里面的脚本走代理。

**Comment by doudouded** [comment]
大佬这样好像不行呀，这样设置完后用python文件测试ip还是服务器的ip,只有您下面写的那个查询脚本是代理脚本

**Comment by doudouded** [comment]
![屏幕截图 2022-05-18 082923](https://user-images.githubusercontent.com/90878738/168933460-ea9bb980-a8e8-42be-a16a-2c4871c8cfff.png)

**Comment by Xgzy** [comment]
可以看下这个教程
https://www.kejiwanjia.com/jiaocheng/91928.html
