### ISSUE TITLE
2.12.2版本获取不到青龙auth.json文件

### ISSUE THREAD

**Issue by 18ghwg** [whyour/qinglong#1365]
![image](https://user-images.githubusercontent.com/50222226/165473402-24af3ecf-e61f-4698-82a0-5dfc7770addc.png)
用python写的，获取到的结果为False
另外，旧版本变量移动不了，刷新后就回到原来位置了

**Comment by 18ghwg** [comment]
旧版本用的是2.10.13

**Comment by whyour** [comment]
@18ghwg 最新的在 /ql/data/config 目录

**Comment by 18ghwg** [comment]
好的，谢谢

**Comment by 18ghwg** [comment]
好的

**Comment by heiren001** [comment]
我草感谢，我是说我看ninja怎么获取不到余量，我查了下ninja api那个是{"code":500,"message":"Response code 401 (Unauthorized)"} 后面改了下代码就好了
