### ISSUE TITLE
不能更新 https://ghproxy.com/ 这个代理怎么去除

### ISSUE THREAD

**Issue by niyueyeee** [whyour/qinglong#1366]
开始更新仓库：/ql

Fetching origin
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': The requested URL returned error: 403
error: Could not fetch origin
HEAD is now at e129485 更新版本 v2.10.10
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': The requested URL returned error: 403

更新/ql失败，请检查原因...

开始克隆仓库 https://ghproxy.com/https://github.com/whyour/qinglong-static.git 到 /ql/repo/static

Cloning into '/ql/repo/static'...
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong-static.git/': The requested URL returned error: 403

更新/ql失败，请检查原因...

**Comment by niyueyeee** [comment]
应该是 代理的问题

**Comment by niyueyeee** [comment]
进入 容器  删除 shell/update.sh 代理配置  可以更新了

**Comment by niyueyeee** [comment]
能更新  但不成功

**Comment by cc9014** [comment]
在面板的配置文件里面更新

> ## 由于github仓库拉取较慢，所以会默认添加代理前缀，如不需要请移除
GithubProxyUrl="https://ghproxy.com/"

**Comment by niyueyeee** [comment]
> 在面板的配置文件里面更新
> 
> > github拉仓库取较较，所以会默认添加代理前置，如不需要移除
> > GithubProxyUrl=" https://ghproxy.com/ "

设为空  已解决

**Comment by niyueyeee** [comment]
> 在面板的配置文件里面更新
> 
> > github拉取仓库较较较，所以会默认添加授权，如[不](https://ghproxy.com/)添加
> > Githubghproxy.com/ ”[](https://ghproxy.com/)

能更新了  但是服务起不来了  ql check 无响应  这是怎么回事  谢谢大佬
