### ISSUE TITLE
用户掉线后将无法后台自动更新仓库任务到定时任务中

### ISSUE THREAD

**Issue by kukushouhou** [whyour/qinglong#1372]
看api.sh的代码是直接在auth.json文件中取的用户登录Token来请求的Api接口.

然后因为用户Token失效导致接口都返回的
`{"code":401,"message":"jwt expired"} `

因此定时更新任务无法在用户长期不登陆的情况下完成.

是否考虑增加一个永久生效的系统Token来解决这个问题?

**Comment by gitiray** [comment]
我就说怎么我的定时任务有时候会莫名其妙不运行，认真排查发现真的是这个原因，设计bug有点严重啊
