### ISSUE TITLE
在script这个文件夹自己添加脚本的话如何直接读到env.sh的环境变量？，不想用正则的方式来解析env.sh文件

### ISSUE THREAD

**Issue by Z-JHAO** [whyour/qinglong#1374]
如题

**Comment by whyour** [comment]
@Z-JHAO 你是什么语言，就用什么语言获取环境变量，读env.sh干啥

**Comment by Z-JHAO** [comment]
用的是python，运行下面代码，但是输出的不是env.sh的内容，想拿到env.sh的内容，因为env.sh的内容不就是面板上的设置的环境变量内容吗？
`#!/usr/bin/env python3
# _*_ coding:utf-8 _*_
import os
cookie = os.environ
print(cookie)`

![image](https://user-images.githubusercontent.com/79096844/166944036-de29e3a1-d032-457f-a8ad-763a1a69c90a.png)

**Comment by Z-JHAO** [comment]
with open('/config/env.sh', "r", encoding="utf-8") as f:
                    cks = f.read()
                    f.close()
主要是不想用这种方式来读取env.sh的来读环境变量

**Comment by Z-JHAO** [comment]
task xxx.py <env_name>  这个env_name可以写的env.sh这个文件的路径吗？

**Comment by whyour** [comment]
@Z-JHAO 那是环境变量的名称，就是你get里的，也没有你条命令啊，后面那个env_name不需要

**Comment by Z-JHAO** [comment]
我的问题，python3 xxx.py来执行拿不到环境变量， task xxx.py可以，谢谢大佬
