### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by qqsir-dev** [whyour/qinglong#1378]
Docker 部署的，看到这里的更新是需要更新docker image还是web管理中强制更新就可以？

**Comment by whyour** [comment]
@qqsir-dev 都可以

**Comment by qqsir-dev** [comment]
好的，如果是更新dockerimage的话，配置会不会丢？是不是不删除宿主机中的data目录配置就丢不了吧？

**Comment by whyour** [comment]
@qqsir-dev 是的

**Comment by qqsir-dev** [comment]
谢谢！
