### ISSUE TITLE
【请教】如何找到导致内存cpu 100%的脚本？

### ISSUE THREAD

**Issue by Cyiming** [whyour/qinglong#1379]
最近服务器几个小时就出现一次内存cpu 100%

面板打不开 ssh连接不上  尝试靠最后运行时间禁用了几个脚本还是不行 每次只能重启服务器 能好几个小时

**Comment by bugme2** [comment]
确实，n1设备，隔几个小时就打不开了，日志也没有什么明显错误，就挺多"crond[160]: user root: parse error at 7"这种日志
![Screenshot_2022-05-11-09-59-35-94_11d59881ebb69c15251b128bef75a7ea](https://user-images.githubusercontent.com/40169265/167753832-234e5fd5-ed90-4c03-8922-9038a557d86b.jpg)

**Comment by AtWhuhu** [comment]
一样的问题，跑几天发现服务就死了，ssh也连不上，只能重启

**Comment by AsoulDianava** [comment]
> 

我也是 经常跑着跑着就炸了

**Comment by MangoDong** [comment]
我天天炸。。。也不知道是什么情况  查看了cpu的排名 只是发现执行的里面有一个丢失

**Comment by AsoulDianava** [comment]
> 我天天炸。。。也不知道是什么情况 查看了cpu的排名 只是发现执行的里面有一个丢失

![Screenshot_2022-06-10-11-08-36-647_com sonelli juicessh](https://user-images.githubusercontent.com/93473203/172983167-55bcc54d-9751-4221-a8ac-332335e397ad.jpg)

**Comment by Cyiming** [comment]
一气之下从阿里云转到了腾讯云 暂时这几天没炸 否则天天凌晨炸

**Comment by JuvenileQ** [comment]
中挖矿病毒了，我也中毒了，在使用docker安装完，阿里云安全预警，给我提示。你可以根剧这个脚本检查一下你的服务器
![image](https://user-images.githubusercontent.com/39209399/188878999-936527bf-9451-4cbd-aa5a-d020ab74a6d5.png)
