### ISSUE TITLE
互助问题，求帮忙

### ISSUE THREAD

**Issue by daitangjun** [whyour/qinglong#138]
日志-互助码 里已经能正常取得账号互助码数据，为什么执行其他互助任务，日志里提示没有提供shareCode？
（由于您第 个京东账号未提供shareCode,将采纳本脚本自带的助力码）
AutoHelpOther="true"已经改了，求帮助
我是前几天直接安装的2.0版本，不知道之前怎么操作的，
之前您回复，请阅读https://t.me/qiongqiya/80 说明，看了半天也没看出哪里没弄对，我把配置都贴上来了，麻烦帮我看看，谢谢
折腾一天了，也不知道什么情况，谢谢

<img width="663" alt="1" src="https://user-images.githubusercontent.com/39112109/118401217-6245f180-b697-11eb-88ff-a0b209c8a24d.png">
<img width="376" alt="2" src="https://user-images.githubusercontent.com/39112109/118401219-640fb500-b697-11eb-9eea-43ff92a3d3ee.png">
<img width="378" alt="3" src="https://user-images.githubusercontent.com/39112109/118401220-64a84b80-b697-11eb-91fd-d9de70b75a81.png">

**Comment by moxinshi** [comment]
这个好像只需要配置config.sh里的那几个字段就行了，不过我配置了也不管事，其它人可以。。。奇了怪了

**Comment by daitangjun** [comment]
> 这个好像只需要配置config.sh里的那几个字段就行了，不过我配置了也不管事，其它人可以。。。奇了怪了

你也不行吗？

**Comment by moxinshi** [comment]
> > 这个好像只需要配置config.sh里的那几个字段就行了，不过我配置了也不管事，其它人可以。。。奇了怪了
> 
> 你也不行吗？

是啊，研究了半天脑仁疼，不行就不行吧，还是v4那个好使，只是没这个脚本多

**Comment by whyour** [comment]
> > 这个好像只需要配置config.sh里的那几个字段就行了，不过我配置了也不管事，其它人可以。。。奇了怪了
> 
> 你也不行吗？

远程看看  todesk

**Comment by whyour** [comment]
> 怪了

贴你的 todesk 码

**Comment by Apocalypsor** [comment]
> > 怪了
> 
> 贴你的 todesk 码

大佬你好，请问互助码除了账号互相助力外，如何能手动加上别的？

**Comment by daitangjun** [comment]
> > 怪了
> 
> 贴你的 todesk 码

ToDesk:
设备代码:115 245 500

**Comment by lin114514** [comment]
我的也是不能助力，而且运行ql code显示没有日志
![Uploading 5DB088BE-CB8D-410B-B7A9-BD2D39D57DCA.jpeg…]()

**Comment by lin114514** [comment]
![6C973BC3-5AB0-454B-9CB7-C3FE9B10277D](https://user-images.githubusercontent.com/73464705/118749350-e82c8d00-b88f-11eb-88f2-ace1d71039df.jpeg)

**Comment by lin114514** [comment]
> 我的也是不能助力，而且运行ql code显示没有日志

ql code显示没有日志好像是因为日志文件夹是chinnkarahoi_jd_xx
