### ISSUE TITLE
反向代理要怎么做呢？

### ISSUE THREAD

**Issue by wyfang** [whyour/qinglong#1382]
我直接把0.0.0.0改成127.0.0.1，似乎访问不上：

version: '2'
services:
  web:
    image: whyour/qinglong:latest
    volumes:
      - ./data:/ql/data
    ports:
      - "127.0.0.1:5700:5700"
    restart: unless-stopped

**Comment by hellosee** [comment]
在nginx里面配置：
 location / {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_redirect off;
                proxy_pass http://127.0.0.1:5700;
        }

**Comment by wyfang** [comment]
> 在nginx里面配置： location / { proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header Host $http_host; proxy_set_header X-Real-IP $remote_addr; proxy_redirect off; proxy_pass http://127.0.0.1:5700; }

可以了，我的CF问题，缓存问题。
