### ISSUE TITLE
DB数据库不通用

### ISSUE THREAD

**Issue by qqhbc5918** [whyour/qinglong#1385]
新版青龙database.sqlite
旧版的青龙DB文件不通用，怎么将数据导入新版的呀，尝试了多种，都没有办法呀
133637497@qq.com

**Comment by E2077** [comment]
环境变量用拆分,定时重新拉库就有了,配置文件直接复制就OK了

**Comment by qqhbc5918** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whyour/qinglong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 下午3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whyour/qinglong] DB数据库不通用 (Issue #1385)





 
环境变量用拆分,定时重新拉库就有了,配置文件直接复制就OK了
