### ISSUE TITLE
随机延迟设置  RandomDelay="1800" 不生效是为什么呢, 还有其他的开关或者限制吗吗?

### ISSUE THREAD

**Issue by DaZhuangNiu** [whyour/qinglong#1386]
随机延迟设置  RandomDelay="1800" 不生效是为什么呢, 还有其他的开关或者限制吗吗?
定时设置 0 0 10 * * *

**Comment by cddjr** [comment]
作者对于设定为0分或30分或不是JS脚本的任务不作延迟处理
你的定时刚好在0分执行，所以被忽略了。如果不是js脚本也不会有随机延迟

这里估计需要一个PR改进
