### ISSUE TITLE
新装的面板或者清了缓存的面板好像都进不去了

### ISSUE THREAD

**Issue by AmazingXiaomi** [whyour/qinglong#1392]
rt

**Comment by AmazingXiaomi** [comment]
![image](https://user-images.githubusercontent.com/30220803/168718031-e9b0364c-57dc-460e-863a-aa41528e38c0.png)
cdn出问题拉

**Comment by liu366138159** [comment]
应该是jsdelivr又挂了,不只作者能否换成本地cdn

**Comment by whyour** [comment]
@liu366138159 请使用最新版

**Comment by AmazingXiaomi** [comment]
> 

docker拉取的不是最新版吗，或者说怎么才能使用最新版

**Comment by whyour** [comment]
@AmazingXiaomi 如果你是源没问题就是最新的，但是你的bug肯定是最新版没有的，你的版本号 也没截图，多点几次更新吧  https://t.me/jiao_long

**Comment by Hopetree** [comment]
@whyour 拉不到最新的版本，latest怎么拉都是4个月前的版本，develop倒是新的但是不能通用

我还特意换成了官方默认的源：docker pull docker.io/whyour/qinglong:latest
<img width="795" alt="image" src="https://user-images.githubusercontent.com/30201215/168728659-1b520854-6412-4861-b539-843ac352c83d.png">

**Comment by AmazingXiaomi** [comment]
我知道个方案，访问的时候挂个全局的梯子，访问一次会有缓存，不清缓存的话下次还能继续用

**Comment by whyour** [comment]
@Hopetree latest换成2吧，拉不到最新的肯定是源的问题，了解下docker源修改

**Comment by liu366138159** [comment]
用的阿里云的源 latest拉下来是2.10.13, 居然还一直没注意, 拉了2.12.2的成功解决问题
