### ISSUE TITLE
2.10.13版本电脑端查看脚本卡在loading

### ISSUE THREAD

**Issue by kuikoukou** [whyour/qinglong#1393]
![image](https://user-images.githubusercontent.com/104774441/168944068-f7037d99-1cc5-4cc7-a2bb-069da44d8fb5.png)

**Comment by GitHub-Stock** [comment]
一样

**Comment by nkym233** [comment]
开代理就行了。cdn.jsdelivr.net挂了

**Comment by GitHub-Stock** [comment]
> 

但是手机端不用代理就可以正常加载

**Comment by kuikoukou** [comment]
知道cdn挂了，本地挂代理很麻烦，想知道能去哪改cdn

**Comment by kuikoukou** [comment]
知道cdn挂了，本地挂代理很麻烦，想知道能去哪改cdn
