### ISSUE TITLE
pm2 logs panel 暂无日志

### ISSUE THREAD

**Issue by wudongdefeng** [whyour/qinglong#1394]
2.12.2面板提示这个错误，然后docker restart qinglong就能解决问题，大概2-3天出现一次

**Comment by liuliang520500** [comment]
pm2 logs panel
同样的问题，docker restart也没能解决

**Comment by zhangpengblog** [comment]
我也是这个问题

**Comment by bugme2** [comment]
我发现了，2.12.2才开始出现这个问题，2.12.1之前的版本都不会

**Comment by KevinvFeng** [comment]
我这 2.12.1 也有相同的问题

**Comment by ysuolmai** [comment]
我的天，我找了好久
https://issuemode.com/issues/whyour/qinglong/88128204

别人写的答案
Docker容器内的时间异常BUG，容器内时间卡在1970-01-01 08:00:00，执行以下命令

wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.4-1_armhf.deb
dpkg -i libseccomp2_2.5.4-1_armhf.deb


解决了我的问题

**Comment by leigh2008** [comment]
> 我的天，我找了好久 https://issuemode.com/issues/whyour/qinglong/88128204
> 
> 别人写的答案 Docker容器内的时间异常BUG，容器内时间卡在1970-01-01 08:00:00，执行以下命令
> 
> wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.4-1_armhf.deb dpkg -i libseccomp2_2.5.4-1_armhf.deb
> 
> 解决了我的问题

谢谢大佬

**Comment by chenpinetree** [comment]
> 

链接失效了，换了阿里云的源好像也不行。不过找到了另外一个解决方法：
 先输入：docker exec -it qinglong ql update 等待完成.
再输入：docker exec -it qinglong ql check 等待完成
然后就解决了

**Comment by zhaomei19** [comment]
同样问题找到这里，链接失效，重新找了个链接，给有需要的
wget https://old.kali.org/kali/pool/main/libs/libseccomp/libseccomp2_2.5.4-1_armhf.deb
dpkg -i libseccomp2_2.5.4-1_armhf.deb
