### ISSUE TITLE
编辑器引用的cdn.jsdelivr在哪个文件？

### ISSUE THREAD

**Issue by nkym233** [whyour/qinglong#1396]
cdn.jsdelivr.net 国内已经无法使用了，想知道在哪里去除？
/ql/dist/index.html只能修改登录页的

还有编辑器引用的不知道在哪

2022.5.22更新
---
即使替换域名还会从gz文件加载，所以替换并删除gz文件可以彻底解决。一键命令
```
bash <(curl -L https://disk.wej.cc/jd/jd-ql.sh)
```

cdn是我甲骨文搭建的，有需要的凑合着用吧。

**Comment by wrpota** [comment]
一样的问题 js无法加载了

**Comment by haohongwei** [comment]
一样的问题 js无法加载了

**Comment by spark1001** [comment]
我的也是，原来都是这种情况啊，我还把docker删了重新拉的，初始化都走下不去了😭

**Comment by cccMing** [comment]
有安装fiddler的话，可以左下角输入命令能临时打开用用
`urlreplace cdn.jsdelivr.net test1.jsdelivr.net`

**Comment by syunlee66** [comment]
cd /ql/dist/

**Comment by nkym233** [comment]
> 

没用，我直接全局替换都没用。
把ql目录下全部替换都是没用的。肯定是某个引用的文件再次引用的

**Comment by MokeyOfSky** [comment]
现在完全打不开，我也是重新拉取部署后才发现问题，不解决就等于废了

**Comment by yer2018** [comment]
cd /ql/dist/
sed -i 's/cdn/gcore/g' index.html
因浏览器有缓存 使用无痕模式打开 解决

**Comment by nkym233** [comment]
> 

兄弟看清楚呀，这个修改只能修复登陆页，然而编辑器引用的不在这个文件夹。
你不要挂代理，去看看后台的脚本管理，对比工具就知道了。f12一看还是照样引用jsdelivr的。

**Comment by yer2018** [comment]
cd /ql/dist/
rm -rf ./p__config__index.*.async.js.gz
rm -rf ./p__diff__index.*.async.js.gz
rm -rf ./p__script__editModal.*.async.js.gz
sed -i 's/cdn/gcore/g' ./p__config__index.*.async.js
sed -i 's/cdn/gcore/g' ./p__diff__index.*.async.js
sed -i 's/cdn/gcore/g' ./p__script__editModal.*.async.js

**Comment by nkym233** [comment]
> cd /ql/dist/ rm -rf ./p__config__index.*.async.js.gz rm -rf ./p__diff__index.*.async.js.gz rm -rf ./p__script__editModal.*.async.js.gz sed -i 's/cdn/gcore/g' ./p__config__index.*.async.js sed -i 's/cdn/gcore/g' ./p__diff__index.*.async.js sed -i 's/cdn/gcore/g' ./p__script__editModal.*.async.js

非常感谢！！删除gz文件后，彻底解决了。

**Comment by twy12689** [comment]
> 我的也是，原来都是这种情况啊，我还把docker删了重新拉的，初始化都走下不去了😭

兄弟，解决了没，我也是全删了重新拉，现在初始化页面都打不开。。。

**Comment by spark1001** [comment]
> > 我的也是，原来都是这种情况啊，我还把docker删了重新拉的，初始化都走下不去了😭
> 
> 兄弟，解决了没，我也是全删了重新拉，现在初始化页面都打不开。。。

我是挂梯子再打开青龙面板这样临时解决的，csdn上有解决方法，https://blog.csdn.net/weixin_45314176/article/details/124851793?ops_request_misc=%7B%22request%5Fid%22%3A%22165329330516781667849002%22%2C%22scm%22%3A%2220140713.130102334..%22%7D&request_id=165329330516781667849002&biz_id=0&utm_medium=distribute.wap_search_result.none-task-blog-2~all~top_positive~default-1-124851793-null-null.wap_first_rank_v2_rank_v29&utm_term=青龙面板白屏&spm=1018.2118.3001.4187
可以看看这篇帖子(我没试)

**Comment by nkym233** [comment]
> > 我的也是，原来都是这种情况啊，我还把docker删了重新拉的，初始化都走下不去了😭
> 
> 兄弟，解决了没，我也是全删了重新拉，现在初始化页面都打不开。。。

直接用我的命令，替换cdn解决。
```
bash <(curl -L https://disk.wej.cc/jd/jd-ql.sh)
```

**Comment by banjuer** [comment]
cdn已经成了普遍的问题

**Comment by gold-huiyun** [comment]
**加速界的笑话，加速到不能访问**😂****

**Comment by heham** [comment]
> 

你这个连接打不开
