### ISSUE TITLE
develop版本的订阅管理老出现SQLITE_ERROR: no such column: extensions

### ISSUE THREAD

**Issue by sevensevenmi** [whyour/qinglong#1399]
SQLITE_ERROR: no such column: extensions

**Comment by whyour** [comment]
> SQLITE_ERROR: no such column: extensions

在面板上 设置 -> 其他设置 -> 检查更新 -> 强制更新

**Comment by Jone2008** [comment]
> > SQLITE_ERROR: no such column: extensions
> 
> 在面板上 设置 -> 其他设置 -> 检查更新 -> 强制更新

更新后已正常
