### ISSUE TITLE
奇怪的问题 Argument list too long

### ISSUE THREAD

**Issue by Muqiqi** [whyour/qinglong#140]
/usr/local/bin/task: line 17: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 115: /bin/date: Argument list too long
/ql/shell/share.sh: line 69: /bin/mkdir: Argument list too long
/usr/local/bin/task: line 119: /usr/bin/tee: Argument list too long

手动运行定时任务后显示这个
任何定时任务都是这样

**Comment by Muqiqi** [comment]
似乎是日志太多造成的。..

**Comment by Muqiqi** [comment]
log太多导致被塞满。...
定时删除似乎未生效

**Comment by fzls** [comment]
试试这个方案
[解决 青龙面板中存放的cookie数目过多（如超过45）时，会报 Argument list too long 而无法正常执行部分脚本的问题](https://gist.github.com/fzls/14f8d1d3ebb2fef64750ad91d268e4f6)
