### ISSUE TITLE
请问青龙面板添加的依赖重启后是否会重新安装？

### ISSUE THREAD

**Issue by heimawsw** [whyour/qinglong#1403]
我是在面板中添加的依赖，我重启后，查看linux的进程，发现有npm的进程在运行。
然后去青龙面板中刷新一下依赖的界面，显示正在安装，日志也是正在安装。

请问每次重启后面板中的依赖是重新安装吗？
如何避免这样的重复安装呢？

**Comment by inoyna12** [comment]
+1

**Comment by heimawsw** [comment]
改用一键脚本了，不用面板依赖了

**Comment by baece** [comment]
请问一键脚本是啥？另一种依赖的形式？

**Comment by ErixWong** [comment]
+1 由于网络访问问题现在还安装不了了。之前容器挂代理能装，装完之后去掉代理，又没了。真的是费劲。

**Comment by tencentbook** [comment]
+1

**Comment by wm918** [comment]
+1
