### ISSUE TITLE
青龙版本2.11.3 本地电脑unbuntu搭建青龙，配置文件、脚本管理、任务日志加载不出来，显示loading？

### ISSUE THREAD

**Issue by Origin-wu** [whyour/qinglong#1406]
刚开始搭建时配置文件、脚本管理、任务日志可以加载的，最近突然就不能加载，一直显示loading，环境变量栏能加载出来，大佬们有没有什么排查方向之类的，小弟感激不尽！

**Comment by jerrie610** [comment]
同样的问题。。。手机加载正常

**Comment by Origin-wu** [comment]
从其他帖子上找到临时解决方案：
cd /ql/dist/
rm -rf ./p__config__index.*.async.js.gz
rm -rf ./p__diff__index.*.async.js.gz
rm -rf ./p__script__editModal.*.async.js.gz
sed -i 's/cdn/gcore/g' ./p__config__index.*.async.js
sed -i 's/cdn/gcore/g' ./p__diff__index.*.async.js
sed -i 's/cdn/gcore/g' ./p__script__editModal.*.async.js

浏览器用无痕模式登录，是可以被正常加载的

**Comment by sundys** [comment]
> 

2.11.3没有dist目录

**Comment by Origin-wu** [comment]
docker容器里面/ql/dist吗？如果没有那就是安装的问题吧

**Comment by qianlongzhou** [comment]
同样的问题, 而且我傻妞也打开js 显示loading
