### ISSUE TITLE
想知道环境变量接口中的 api/envs?searchValue=&t=？这里的t代表的什么，该怎么获取呢。

### ISSUE THREAD

**Issue by suhuamo** [whyour/qinglong#1408]
如题

**Comment by whyour** [comment]
@suhuamo 时间戳

**Comment by suhuamo** [comment]
额，请问是指 now date() 吗

**Comment by whyour** [comment]
@suhuamo +new Date()

**Comment by suhuamo** [comment]
> @suhuamo +new Date()
噢噢，是 System.currentTimeMillis(), 请问怎么用呀，我直接在参数后面加这个报的401
![image](https://user-images.githubusercontent.com/92418767/169750999-70b92ca5-f760-474c-a992-2bf859de227f.png)

**Comment by suhuamo** [comment]
> @suhuamo +new Date()

想自己写个接口函数来调用这个函数，这样就不需要每次都登录网站了。 (*^▽^*)

**Comment by suhuamo** [comment]
> @suhuamo +new Date()

在issue中找到了其他大佬写的开发文档，已经解决了，再次感谢大佬提供的青龙面板。\(^o^)/~
