### ISSUE TITLE
查看脚本页面一直Loading，加载不出来

### ISSUE THREAD

**Issue by Jesn** [whyour/qinglong#1409]
![image](https://user-images.githubusercontent.com/5728274/169753548-1894300d-9e88-4cea-97cb-a8b68c644a5a.png)

**Comment by jerrie610** [comment]
我的也一样。。。用手机浏览正常

**Comment by newhackerman** [comment]
一样，以为是墙，但不是

**Comment by newhackerman** [comment]
加载脚本为什么要访问这个地址：https://o1098464.ingest.sentry.io/api/6122818/envelope/?sentry_key=3406424fb1dc4813a62d39e844a9d0ac&sentry_version=7,并且是要上传一堆东西。

**Comment by newhackerman** [comment]
是在这个脚本里调用用的：layouts__index.e420751c.async.js，麻烦高人解释一下，查看本机的脚本为什么要去访问一个远程的地址，且把最近的脚本文件信息给post

**Comment by newhackerman** [comment]
把那个脚本删除并与对应的gz也删除，并在docker外面加上 ufw deny 那个地址，加载脚本秒出来

**Comment by newhackerman** [comment]
解决办法：
去ql/data/static/dist目录下，然后 grep ingest.sentry * -r 找到对应的文件，把含有“ingest.sentry” 这个的那句代码删除掉，重启docker 完美，脚本秒开
