### ISSUE TITLE
docker最新版定时任务只有三个

### ISSUE THREAD

**Issue by qsect** [whyour/qinglong#141]
自5月10日更新后，无法使用了，全部删除后重新在docker下创建任务，定时任务只有三个，删除日志、更新面板和互助码，点更新面板也没反应，看日志里倒是有数据，不跟之前一样会有四页的任务，请问这个怎么解决呢？

**Comment by Acr05s** [comment]
新版本需要自行添加定时任务，包括更新JS

**Comment by qsect** [comment]
你好：请问怎么添加定时任务以及更新JS，谢谢。

发送自 Windows 10 版邮件应用

发件人: Acr05s
发送时间: 2021年5月17日 14:50
收件人: whyour/qinglong
抄送: qsect; Author
主题: Re: [whyour/qinglong] docker最新版定时任务只有三个 (#141)

新版本需要自行添加定时任务，包括更新JS

**Comment by whyour** [comment]
https://t.me/qiongqiya/79  看频道通知
