### ISSUE TITLE
有大佬指导白屏怎么处理啊，把docker删了重新拉的，现在初始化界面都进不去了。。。

### ISSUE THREAD

**Issue by twy12689** [whyour/qinglong#1410]
如题。

**Comment by johnny23857** [comment]
换个浏览器就好了,我也折腾得要死,结果是浏览器问题,要清空数据了

**Comment by MuzheSU** [comment]
暂时没有解决办法

**Comment by spark1001** [comment]
挂上梯子再进青龙面板，可以这样临时解决，或者看看这个链接[csdn](https://blog.csdn.net/weixin_45314176/article/details/124851793?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165330811116781683951696%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=165330811116781683951696&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~top_positive~default-1-124851793-null-null.142^v10^pc_search_result_control_group,157^v8^control&utm_term=%E9%9D%92%E9%BE%99%E9%9D%A2%E6%9D%BF%E7%99%BD%E5%B1%8F&spm=1018.2226.3001.4187)

**Comment by Jayzongzer** [comment]
ssh进入青龙文件夹后
bash <(curl -ls https://gitee.com/suiyuehq/ziyong/raw/master/ql_cdn/v2.10.13/bpxf.sh)
建议直接选PC端那个

**Comment by twy12689** [comment]
> ssh进入青龙文件夹后 bash <(curl -ls https://gitee.com/suiyuehq/ziyong/raw/master/ql_cdn/v2.10.13/bpxf.sh) 建议直接选PC端那个

白屏打不开初始化界面，所以文件夹都是空的，死循环了，目前能查到的方法都是全局挂梯子，哎。。。

**Comment by hzk2006** [comment]
运行那个命令重新 安装 选择自动更新  更新到[v2.12.2]后问题解决 我也碰到同样的问题 然后是这样解决了

**Comment by MuzheSU** [comment]
我重装了2.11.3版本解决了这个问题

**Comment by twy12689** [comment]
> 运行那个命令重新 安装 选择自动更新 更新到[v2.12.2]后问题解决 我也碰到同样的问题 然后是这样解决了

感谢，成功了！

**Comment by hzk2006** [comment]
白屏运行—键修改命令:【适用v2.9-v2.11.1版本】:`bash <(curl -ls https://gitee.com/suiyuehq/ziyong/raw/master/ql_cdn/v2.10.13/bpxf.sh)`
