### ISSUE TITLE
请问在docker下面部署qinglong.为什么我指定映射的目录下没有文件.反而跑到其它地方去了.

### ISSUE THREAD

**Issue by showme2005** [whyour/qinglong#1411]
之前的版本没有这个问题..最近几个版本出现这个情况..我明明已经映射到/opt/目录下..但是这个目录没有文件...反儿在系统自动挂载了一个"overlay | /opt/docker/overlay2/{一长串ID}/merged" 目录..我的青龙也在这个目录下面..

**Comment by cc9014** [comment]
贴下你的docker创建命令或者docker compose文件才能确定。

**Comment by showme2005** [comment]
> 贴下你的docker创建命令或者docker compose文件才能确定。

docker run -dit \
   -v /opt/ql/config:/ql/config \
   -v /opt/ql/log:/ql/log \
   -v /opt/ql/db:/ql/db \
   -v /opt/ql/repo:/ql/repo \
   -v /opt/ql/raw:/ql/raw \
   -v /opt/ql/scripts:/ql/scripts \
   -v /opt/ql/jbot:/ql/jbot \
   -p 5700:5700 \
   --net=mynet \
   --name qinglong \
   --restart unless-stopped \
   whyour/qinglong:latest
用的这个..之前一直用的这个.没有问题../opt/ql下面正常..

**Comment by Jone2008** [comment]
> > 贴下你的docker创建命令或者docker compose文件才能确定。
> 
> docker run -dit -v /opt/ql/config:/ql/config -v /opt/ql/log:/ql/log -v /opt/ql/db:/ql/db -v /opt/ql/repo:/ql/repo -v /opt/ql/raw:/ql/raw -v /opt/ql/scripts:/ql/scripts -v /opt/ql/jbot:/ql/jbot -p 5700:5700 --net=mynet --name qinglong --restart unless-stopped whyour/qinglong:latest 用的这个..之前一直用的这个.没有问题../opt/ql下面正常...另外创建QB下载的时候映射目录正常.

一段即可 文件夹几个版本以前已经集合到data里面 试下：
  -v /opt/ql:/ql/data \

**Comment by showme2005** [comment]
> -v /opt/ql:/ql/data \

感谢..刚才试了一下...好像正常了..
