### ISSUE TITLE
环境变量启用后1个小时左右会变成禁用

### ISSUE THREAD

**Issue by linanir77** [whyour/qinglong#1413]
青龙面板版本V2.12.1，使用威联通的docker，开始一切正常，十几天后发现京东签到停了，上docker看了一下，青龙面板停了，重新打开青龙面板，运行脚本还是无法签到，看日志发现京东账号是0个，到环境变量一看，是京东的环境变量被禁用了，重新启用环境变量后，一个小时左右刷新青龙面板就会发现环境变量又变成禁用了，升级到v2.12.2也不行，问题依旧。

**Comment by Zy143L** [comment]
检查你的脚本

**Comment by linanir77** [comment]
多谢提醒，把所有脚本都禁用，一共100多个脚本，分10组批量运行，运行到第三组发现环境变量被禁用了，然后把第三组这10个依次运行，发现是一个“京东ck检测”的脚本导致的，打开脚本代码，发现这是一个检查cookie的脚本，一旦发现cookie失效，会自动禁用环境变量。原来问题出在我的cookie失效了，重新登录手机版京东，获取cookie，更新环境变量，然后再运行，ck检查通过了。非常感谢。
