### ISSUE TITLE
jsdelivr被墙了

### ISSUE THREAD

**Issue by cike-567** [whyour/qinglong#1416]
jsdelivr被墙了好几次，更换cdn或者本地加载。

**Comment by jerrie610** [comment]
如何本地加载？

**Comment by cike-567** [comment]
js文件放在本地，需要的时候直接调用。这个要开发者弄了。普通人就进入容器，敲下面的命令能暂时解决
bash <(curl -ls&nbsp;https://gitee.com/suiyuehq/ziyong/raw/master/ql_cdn/v2.10.13/bpxf.sh)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 下午3:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] jsdelivr被墙了 (Issue #1416)





 
如何本地加载？

**Comment by xiayuyuyu** [comment]
Debian 系统执行上面的命令可能不太好使，执行上面命令会出现
/bin/sh: syntax error: unexpected "("
原因是因为 通过 sh 来执行脚本时，在Debian和Ubuntu中，/bin/sh默认已经指向dash所以会有问题
所以可以按照下面来执行，进入容器后，先下载作者提供的sh文件，在手动执行   
curl -O https://gitee.com/suiyuehq/ziyong/raw/master/ql_cdn/v2.10.13/bpxf.sh
chmod +x bpxf.sh
./bpxf.sh 
然后按照脚本里的步骤来进行操作即可
