### ISSUE TITLE
青龙把服务器搞死了

### ISSUE THREAD

**Issue by Luxuslaerm** [whyour/qinglong#1418]
安装的青龙最新版本，现在是一运行脚本整个服务器都失联了。原先在N1上跑的，怀疑是N1的问题，换了腾讯云轻量，结果一样，腾讯云也卡死SSH连接不上。
大佬帮忙分析一下原因是什么，是跑的脚本把服务卡死的吗？还是其它原因

**Comment by JuvenileQ** [comment]
中挖矿病毒了，我也中毒了，在使用docker安装完，阿里云安全预警，给我提示。你可以根剧这个脚本检查一下你的服务器
![image](https://user-images.githubusercontent.com/39209399/188878999-936527bf-9451-4cbd-aa5a-d020ab74a6d5.png)
