### ISSUE TITLE
豆子变动的Js运行出错

### ISSUE THREAD

**Issue by Acr05s** [whyour/qinglong#142]
任务面板运行就是这样，包括定时任务或者手动点执行
🔔京东资产变动通知, 开始!

====================共14个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/5/17上午9:53:48=====================
然后就没结果

但是在通过命令终端task 运行是可以正常执行的
$ task chinnkarahoi_jd_bean_change.js now

**Comment by whyour** [comment]
你这问题执行下 ql update 试试，不行新建个task chinnkarahoi_jd_bean_change.js now 任务执行试试

**Comment by Acr05s** [comment]
> 你这问题执行下 ql update 试试，不行新建个task chinnkarahoi_jd_bean_change.js now 任务执行试试

好像不影响运行，有些脚本就有这种情况。
