### ISSUE TITLE
面板报错，一直登录显示这个

### ISSUE THREAD

**Issue by zuozihan** [whyour/qinglong#1426]
![image](https://user-images.githubusercontent.com/45542784/170481089-916a9c4f-52f0-4536-b266-4ff10fb4b626.png)

**Comment by Huansheng1** [comment]
ssh 登录服务器，进入青龙docker，执行ql check应该可解决

**Comment by lbbboy** [comment]
一样蛋疼找不到解决方法ARM版本。
