### ISSUE TITLE
2.13.0 强制更新后无法进web

### ISSUE THREAD

**Issue by babyvox550** [whyour/qinglong#1431]
![image](https://user-images.githubusercontent.com/13328183/170808710-ad03e254-f972-4de2-b3b5-5a55420cbaa8.png)
pm2 logs panel显示如下：

[TAILING] Tailing last 15 lines for [panel] process (change the value with --lines option)
/root/.pm2/logs/panel-out.log last 15 lines:
4|panel    | 2022-05-28T10:22:25:       ################################################
4|panel    | 2022-05-28T10:22:25:       🛡️  Server listening on port: 5600 🛡️
4|panel    | 2022-05-28T10:22:25:       ################################################
4|panel    | 2022-05-28T10:22:25:
4|panel    | 2022-05-28T10:27:02: info:    task okyyds_yyds_master/jd_exchangejxbeans.js pid: 10136 exit 0 signal null
4|panel    | 2022-05-28T10:27:02: info:    task okyyds_yyds_master/jd_exchangejxbeans.js pid: 10136 closed 0
4|panel    | 2022-05-28T11:34:15: info:    ✌️ Server need close
4|panel    | 2022-05-28T11:34:28: info:    ✌️ Init file down
4|panel    | 2022-05-28T11:34:29: info:    ✌️ Sentry loaded
4|panel    | 2022-05-28T11:34:36: info:    ✌️ DB loaded
4|panel    | 2022-05-28T11:34:38: info:    ✌️ Dependency Injector loaded
4|panel    | 2022-05-28T11:34:39: info:    ✌️ Express loaded
4|panel    | 2022-05-28T11:34:39: info:    ✌️ init data loaded
4|panel    | 2022-05-28T11:34:39: info:    ✌️ link deps loaded
4|panel    | 2022-05-28T11:34:39: info:    ✌️ init task loaded

/root/.pm2/logs/panel-error.log last 15 lines:
4|panel    | 2022-05-28T11:34:39: RangeError: options.port should be >= 0 and < 65536. Received NaN.
4|panel    | 2022-05-28T11:34:39:     at new NodeError (node:internal/errors:371:5)
4|panel    | 2022-05-28T11:34:39:     at validatePort (node:internal/validators:216:11)
4|panel    | 2022-05-28T11:34:39:     at Server.listen (node:net:1461:5)
4|panel    | 2022-05-28T11:34:39:     at Function.listen (/ql/node_modules/.pnpm/registry.npmmirror.com+express@4.18.1/node_modules/express/lib/application.js:635:24)
4|panel    | 2022-05-28T11:34:39:     at startServer (/back/app.ts:21:6) {
4|panel    | 2022-05-28T11:34:39:   code: 'ERR_SOCKET_BAD_PORT'
4|panel    | 2022-05-28T11:34:39: }
4|panel    | 2022-05-28T11:34:39: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
4|panel    | 2022-05-28T11:34:39: RangeError: options.port should be >= 0 and < 65536. Received NaN.
4|panel    | 2022-05-28T11:34:39:     at new NodeError (node:internal/errors:371:5)
4|panel    | 2022-05-28T11:34:39:     at validatePort (node:internal/validators:216:11)
4|panel    | 2022-05-28T11:34:39:     at Server.listen (node:net:1461:5)
4|panel    | 2022-05-28T11:34:39:     at Function.listen (/ql/node_modules/.pnpm/registry.npmmirror.com+express@4.18.1/node_modules/express/lib/application.js:635:24)
4|panel    | 2022-05-28T11:34:39:     at startServer (/back/app.ts:21:6)

**Comment by Cluxifa** [comment]
过一会 就能进了  可能是设备性能不够导致的。

**Comment by Babyvox550** [comment]
过了一小时还进不了

**Comment by yangyang0223** [comment]
同样的问题你解决了吗？

**Comment by Babyvox550** [comment]
等大佬现身，还是不能用

**Comment by yangyang0223** [comment]
ql chack就好了

**Comment by xionghaizhi** [comment]
+1 我的也是这样  ql check 后还是进不去
