### ISSUE TITLE
2.13强制更新后仍然无法安装linux下依赖

### ISSUE THREAD

**Issue by hzyhzc** [whyour/qinglong#1432]
2.13更新后无法安装nodejs和linux下依赖 强制更新后可以安装nodejs但是仍然无法安装linux下的

**Comment by hzyhzc** [comment]
开始安装依赖 bizMsg，开始时间 2022/5/28 12:58:20

  bizMsg (no such package):

依赖安装失败，结束时间 2022/5/28 12:58:21，耗时 1.266 秒

**Comment by ledehaha** [comment]
linux下依赖安装全部失败。

**Comment by sensenboylg** [comment]
一样　linux下依赖安装全部失败。

**Comment by group-by** [comment]
一样　linux下依赖安装全部失败

**Comment by xiaotianshuai** [comment]
一样　linux下依赖安装全部失败

**Comment by TheKing1991** [comment]
![image](https://user-images.githubusercontent.com/81273686/180613428-20c0a3ba-33ce-4f28-8497-0a3342849904.jpeg)一样　linux下依赖安装全部失败

**Comment by AdeSpike** [comment]
一样，linux下的依赖安装失败
