### ISSUE TITLE
2.13.0 ARM32 无法启动找不到原因求助。

### ISSUE THREAD

**Issue by lbbboy** [whyour/qinglong#1435]
```
=====> 面板服务启动正常

=====> 检测nginx服务
   66 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
   67 root      0:00 nginx: worker process
   69 root      0:00 nginx: worker process
   70 root      0:00 nginx: worker process
   71 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志

=====> 检测后台



=====> 后台服务异常，重置基础环境并重启后台

---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

检测到 /ql 的依赖包有变化，运行 npm install...

---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

检测到 /ql/data/scripts 的依赖包有变化，运行 npm install...

---> 脚本依赖安装完成


=====> 检测结束


## 执行结束... 1970-01-01 08:00:00  耗时 0 秒

```
服务错误
<div class="react-terminal-wrapper react-terminal-light" data-terminal-name="服务错误"><div class="react-terminal"><span class="react-terminal-line react-terminal-input">pm2 logs panel</span><span class="react-terminal-line"><pre><code><span>暂无日志</span></code></pre></span></div></div>

**Comment by whyour** [comment]
再执行 ql update

**Comment by liujwcn** [comment]
Docker容器内的时间异常BUG，执行以下命令
1. wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.4-1_armhf.deb
2. dpkg -i libseccomp2_2.5.4-1_armhf.deb

**Comment by x1737886903** [comment]
> Docker容器内的时间异常BUG，容器内时间卡在1970-01-01 08:00:00，执行以下命令
> 
> 1. wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.4-1_armhf.deb
> 2. dpkg -i libseccomp2_2.5.4-1_armhf.deb

请问实在容器内运行这2个代码吗

**Comment by x1737886903** [comment]
> 2\. dpkg -i

![image](https://user-images.githubusercontent.com/52018129/190886964-6de9584c-8ddf-4ce8-a755-89cb3ab42e91.png)
还是不行
