### ISSUE TITLE
关于bot

### ISSUE THREAD

**Issue by woboo110** [whyour/qinglong#144]
现在每次执行完ql update ，都得手动执行一次ql bot，不然bot无法启动，如何能update后自动启动bot？只能加定时吗？配置文件里的自动启动好像不起作用，那个是不是重启容器才会自动启动？

**Comment by CrazyMouse** [comment]
还有bot 那个/bean 命令，会报错
something wrong,I'm sorry
Command 'jcsv' returned non-zero exit status 127.

**Comment by woboo110** [comment]
> 还有bot 那个/bean 命令，会报错
> something wrong,I'm sorry
> Command 'jcsv' returned non-zero exit status 127.

这不是青龙的问题，而且机器人昨天更新了，bean和chart功能都正常了

**Comment by CrazyMouse** [comment]
> > 还有bot 那个/bean 命令，会报错
> > something wrong,I'm sorry
> > Command 'jcsv' returned non-zero exit status 127.
> 
> 这不是青龙的问题，而且机器人昨天更新了，bean和chart功能都正常了

我的目前版本这样
Fetching origin
HEAD is now at 09b9076 fix bug
Already up to date.

chart 功能正常，bean 功能还是不正常

**Comment by woboo110** [comment]
> > > 还有bot 那个/bean 命令，会报错
> > > something wrong,I'm sorry
> > > Command 'jcsv' returned non-zero exit status 127.
> > 
> > 
> > 这不是青龙的问题，而且机器人昨天更新了，bean和chart功能都正常了
> 
> 我的目前版本这样
> Fetching origin
> HEAD is now at 09b9076 fix bug
> Already up to date.
> 
> chart 功能正常，bean 功能还是不正常

我这正常

**Comment by whyour** [comment]
https://github.com/SuMaiKaDe/jddockerbot/tree/master
bot相关
