### ISSUE TITLE
青龙更新后直接进入初始化面板页面

### ISSUE THREAD

**Issue by JamYiz** [whyour/qinglong#1440]
好几次了，数据是全丢了吗？

**Comment by jyh9521** [comment]
+1，又得重新配置，哎。

**Comment by JamYiz** [comment]
> +1，又得重新配置，哎。

出现这个问题好多次了，之前还以为是我的问题，人麻了

**Comment by victorpzg** [comment]
你不是一个人，更新后，我的也试过好几次初始化

**Comment by jyh9521** [comment]
可能是因为路径问题，2.12.2以前映射的目录是/ql/xxx，之后的新版是/ql/data/xxx，在原基础上添加/data。
