### ISSUE TITLE
所有的nodejs安装失败

### ISSUE THREAD

**Issue by sofs2005** [whyour/qinglong#1441]
刚刚更新了新版的青龙2.13.1，nodejs和linux的依赖全部安装失败
日志：
开始安装依赖 fs，开始时间 2022/5/29 14:56:00

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.

开始安装依赖 bizCode，开始时间 2022/5/29 14:50:26

  bizCode (no such package):

依赖安装失败，结束时间 2022/5/29 14:50:27，耗时 0.363 秒

**Comment by whyour** [comment]
@sofs2005 强制更新下，这个问题下个版本上，或者可以使用develop镜像

**Comment by WZJB18CM** [comment]
一个样，死活不行，在怎么强制都没办法装，还有那个订阅怎么搞阿，死活也刷不出，格式出一份嘛

**Comment by sofs2005** [comment]
> @sofs2005 强制更新下，这个问题下个版本上，或者可以使用develop镜像

我回退了2.12了，等你更新

**Comment by hzk2006** [comment]
nodejs和linux的依赖全部安装失败但是看到脚本好像还是在跑的 挺奇怪的.订阅好像目前还没大佬写出来.

**Comment by ElonWang8** [comment]
是的我这也是这个报错 搞不好了

开始安装依赖 crypto-js
2022/6/1 11:11:30
，开始时间
Run
"ppm setup"
to create
it
automatically,
or set the global
bin-dir setting,
or the PNPM HOME
env variable.
The global bin
directory should be in the PATH.
依赖安装失败，
结束时间 2022/6/1
11:11:32，耗时 2.026 秒![image](https://user-images.githubusercontent.com/102503134/171320447-533ef443-7f8d-4dfd-ad70-bf87b7e6bbf6.jpeg)

**Comment by hzk2006** [comment]
更新到青龙2.13.2，nodejs依赖恢复了 linux的依赖还是依旧失败 估计还要等下一个版本修复

**Comment by zxqugn** [comment]
v2.13.6也出现同样的问题，nodejs和linux的依赖全部安装失败。
