### ISSUE TITLE
没法拉最新的，只能拉2.10.3 ，求解！感谢

### ISSUE THREAD

**Issue by danshn** [whyour/qinglong#1442]
docker run -dit \
  -v /mnt/user/appdata/ql:/ql/data \
  -v /mnt/user/appdata/ql/ninja:/ql/ninja \
  -p 5700:5700 \
  -p 5701:5701 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest

**Comment by xiaobucvg** [comment]
docker run -dit
-v /mnt/user/appdata/ql:/ql/data
-v /mnt/user/appdata/ql/ninja:/ql/ninja
-p 5700:5700
-p 5701:5701
--name qinglong
--hostname qinglong
--restart unless-stopped
whyour/qinglong:develop  

最新的是测似版，还没有正式的，想用测试的话可以拉测试的。
