### ISSUE TITLE
2.13.1还是有问题阿

### ISSUE THREAD

**Issue by WZJB18CM** [whyour/qinglong#1443]
Nodejs的依赖死活装不上阿，开始安装依赖 crypto-js  ，开始时间 2022/5/29 18:22:24

 ERROR  Unable to find the global bin directory

依赖安装失败，结束时间 2022/5/29 18:22:25，耗时 0.742 秒

**Comment by whyour** [comment]
@WZJB18CM 点系统的强制更新

**Comment by WZJB18CM** [comment]
> @WZJB18CM 点系统的强制更新

没用，点了一天还是一样

**Comment by whyour** [comment]
@WZJB18CM 什么系统

**Comment by WZJB18CM** [comment]
> @WZJB18CM 什么系统
阿里云轻量+CentOS7.6+拉的docker+最新青龙，昨天也试了腾讯云的，Nodejs的依赖能装了，后面的两个就不行了，阿里就1和3装不了，怎么都死活没反应，强制也秒失败

**Comment by whyour** [comment]
@WZJB18CM 分别报什么错，就是轻量云一直是失败的？

**Comment by WZJB18CM** [comment]
> @WZJB18CM 分别报什么错，就是轻量云一直是失败的？

点强制就秒失败，其他系统我没试过。阿里和腾讯都试了旧版本都是秒装上，不知道怎么回事开始安装依赖 crypto-js  ，开始时间 2022/5/29 18:22:24

 ERROR  Unable to find the global bin directory

依赖安装失败，结束时间 2022/5/29 18:22:25，耗时 0.742 秒
日志都是秒失败

**Comment by whyour** [comment]
@WZJB18CM 轻量云在容器里 执行npm i -g pnpm试试

**Comment by WZJB18CM** [comment]
> @WZJB18CM 轻量云在容器里 执行npm i -g pnpm试试

docker exec -it qinglong ql npm i -g pnpm命令错误

**Comment by WZJB18CM** [comment]
> @WZJB18CM 轻量云在容器里 执行npm i -g pnpm试试

#＃ 执行结束.2022-05-29 19:25:42
耗时0
[rooteiZwz9grliwh29l2bb4ekmeZ~]＃ npm
-g pnpm
-bash: npm： command not found
[rooteizwz99rliwh29l2bb4ekmeZ ~]# docker exec -it npm i-g
pnpm
Error: No such container: npm
[rooteizwz99rllwh2912bb4ekmeZ ~]# docker exec -it qinglong
npm
§ pnpm
changed 1 package, and audited 2 packages in 8s
1 package is Looking for fund ing
run
npm fund^ for details
found
vulnerabilities
npm notice
npm
notice New minor version of npm available! 8.9.0
8.
11.0
npm notice Changelog: https: //github.com/npm/cli /releases/
tag/v8.11.0
npm notice Run npm install -g npme8. 11.0 to update!
npm notice

**Comment by whyour** [comment]
@WZJB18CM 你查查docker咋用 你这命令什么鬼

**Comment by hgh188** [comment]
root@TWO:/ql $ npm i -g pnpm
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 1 package in 6s
root@TWO:/ql $

**Comment by hgh188** [comment]
root@TWO:/ql $ npm i -g pnpm
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 1 package in 6s
root@TWO:/ql $ cd /ql/data/
root@TWO:/ql/data $  npm i -g pnpm
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 1 package in 6s
root@TWO:/ql/data $

**Comment by whyour** [comment]
@hgh188 然后再装node依赖还是不行？

**Comment by hgh188** [comment]
是

**Comment by WZJB18CM** [comment]
> @WZJB18CM 你查查docker咋用 你这命令什么鬼

现在应该对了
unknown shorthand flag: 'g'in -g
See Idocker --help'.
Usage：
docker LOPTIONS] COMMAND
A self-sufficient runtime for containers
Options:
--config string
Locat ion of client
config files (de fault
"/root/.docker"）
-c, --context string
Name of the context to
use to connect to the
daemon (overrides
DOCKER HOST env var and
default context set with
"docker context use")
-D, --debug
Enable debug mode
-H，--host list
Daemon socket(s) to
connect to
-1,--10g-level string
Set the logging Level
"fatal") (default "info")
("debug"I"info"l"warn"I"error"1
--tls
Use TLS; implied by
--tlscacert string
--tlsverify
Trust certs signed only
by this CA (de fault
--tlscert string
“/root/.docker /ca.pem"）
Path to TLS certificate
file (default
--tlskey string
"/root/.docker /cert. pem")
Path to TLS key file
(default
"/root/. docker /key . pem")
--tlsverify
-V,--version
use TLS and veri fy the remote
Print version
information and quit
Management Commands:
app*
Docker App (Docker Inc., vO.9.1-beta3)
builder
Manage builds
buildx*
Docker Buildx (Docker Inc., vO.8.2-docker)
compose*
config
Docker Compose (Docker Inc.,v2.5.0)
Manage Docker configs
container
Manage containers
context
Manage contexts
image
Manage images
manifest
Manage Docker image mani fests and manifest 1
ists
network
Manage networks

**Comment by whyour** [comment]
@WZJB18CM 这很明显是错的

**Comment by WZJB18CM** [comment]
> @WZJB18CM 这很明显是错的

晕了哈，不知道怎么弄了

**Comment by whyour** [comment]
@WZJB18CM 进容器，执行我发的。

**Comment by WZJB18CM** [comment]
> @WZJB18CM 轻量云在容器里 执行npm i -g pnpm试试

[rooteizwz99rl1wh29l2bb4ekmeZ ~]# docker exec -it qing Long
bash
rooteqinglong:/ql $ npm i -g pnpm
changed 1 package, and audited 2 packages in 2s
1 package is Looking for funding
run
npm fund* for details
found o vulnerabilities
rooteqinglong:/ql [
这样对了吧？

**Comment by whyour** [comment]
@WZJB18CM 现在安装还是报错吗

**Comment by WZJB18CM** [comment]
> @WZJB18CM 现在安装还是报错吗

还是失败，docker不用重启吧

**Comment by whyour** [comment]
@WZJB18CM 不用  一样的错？

**Comment by WZJB18CM** [comment]
> @WZJB18CM 不用  一样的错？

是的，点强制也是秒失败

**Comment by hgh188** [comment]
更新日志
开始更新系统
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 1 package in 6s
Configuration already up-to-date in /root/.bashrc

Setup complete. Open a new terminal to start using pnpm.
Reset branch 'develop'
Your branch is up to date with 'origin/develop'.
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
开始更新仓库：/ql

Fetching origin
fatal: unable to access 'https://github.com/whyour/qinglong.git/': SSL certificate problem: self signed certificate
error: Could not fetch origin
Reset branch 'develop'
Your branch is up to date with 'origin/develop'.
Branch 'develop' set up to track remote branch 'develop' from 'origin'.

更新青龙源文件失败，请检查原因...

开始克隆仓库 https://github.com/whyour/qinglong-static.git 到 /ql/data/repo/static

fatal: destination path '/ql/data/repo/static' already exists and is not an empty directory.

更新青龙静态资源失败，请检查原因...


## 执行结束... 2022-05-29 19:58:07  耗时 13 秒

强制更新

**Comment by jing5460** [comment]
在线等，同样的问题两台机器  强制更新无日志
一个百度轻量
![image](https://user-images.githubusercontent.com/38358681/170871468-01ad2927-cc2b-454d-a950-a9b0b90e15e3.png)
![image](https://user-images.githubusercontent.com/38358681/170871796-72a0b507-b928-43f4-b32d-d3786733c484.png)

  一个Oracle
![image](https://user-images.githubusercontent.com/38358681/170871488-2543396f-44e8-4d04-9736-7ee973458f72.png)

**Comment by shmitoy** [comment]
强制更新后，nodejs和python3可以安装，linux还是安装失败
开始安装依赖 bizCode，开始时间 2022/5/29 22:23:33

  bizCode (no such package):

依赖安装失败，结束时间 2022/5/29 22:23:34，耗时 0.785 秒

开始安装依赖 bizMsg，开始时间 2022/5/29 22:23:35

  bizMsg (no such package):

依赖安装失败，结束时间 2022/5/29 22:23:36，耗时 0.841 秒

开始安装依赖 lxml，开始时间 2022/5/29 22:23:38

  lxml (no such package):

依赖安装失败，结束时间 2022/5/29 22:23:38，耗时 0.813 秒

**Comment by ICU2Vmile** [comment]
nodejs和python依赖无问题了，就是linux依赖安装不上，问题同上，请问大佬怎么处理

**Comment by luckyreny** [comment]
linux依赖安装不上，问题同上，请问大佬怎么处理。显示no such package
