### ISSUE TITLE
昨天开始bot报错

### ISSUE THREAD

**Issue by supermenno1** [whyour/qinglong#145]
something wrong,I'm sorry
'list' object has no attribute 'SUBCLASS_OF_ID'

请问老哥如何解决一下？

**Comment by whyour** [comment]
> something wrong,I'm sorry
> 'list' object has no attribute 'SUBCLASS_OF_ID'
> 
> 请问老哥如何解决一下？

这是bot相关
https://github.com/SuMaiKaDe/jddockerbot/tree/master
