### ISSUE TITLE
启动成功，面板不能访问

### ISSUE THREAD

**Issue by hhxplz** [whyour/qinglong#1450]
启动成功，面板不能访问，访问 ip:5700空白，之前都是可以的，就是最近不可以，我看了防火墙是关闭的，阿里云访问的端口都有配置。
![20220531075217](https://user-images.githubusercontent.com/93975500/171069133-7f4caaea-24ac-4b5b-a469-2958c2eed0a5.png)

**Comment by senhao-xu** [comment]
https://cdn.jsdelivr.net/npm/ 污染无法访问的问题

**Comment by CoderAWei** [comment]
启动面板命令是什么呀？

**Comment by heham** [comment]
> https://cdn.jsdelivr.net/npm/ 污染无法访问的问题

那怎么解决呢？

**Comment by senhao-xu** [comment]
最新版的镜像修复了该问题
