### ISSUE TITLE
什么时候能出个本机部署的教程啊

### ISSUE THREAD

**Issue by sunlifei1** [whyour/qinglong#1452]
什么时候能出个本机部署的教程啊

**Comment by JianJia2018** [comment]
https://mengkunsoft.github.io/lmbtfy/?q=V2luZG93czEw5a6J6KOFZG9ja2VyIGRlc2t0b3A=

**Comment by gold-huiyun** [comment]
自己安装个alpine系统。把dockerfile的命令执行一下。安卓机的Linuxdeploy和termux就是这样。
