### ISSUE TITLE
删除任务task的命令

### ISSUE THREAD

**Issue by NaroisCool** [whyour/qinglong#1453]
请教大佬，该脚本是否支持删除某个任务的命令，似乎只有task命令用来添加定时任务，没有类似task remove TASKNAME 这样的命令。因为我改进了一下cron的执行时间策略，把执行时间设置成随机时间，因为考虑到脚本运行时间有个弊端就是固定执行，导致容易被系统或者网管发现作弊嫌疑。当我修改好了策略后，发现需要重新添加一遍task任务才会刷新时间执行策略，所以有了这个问题。如果没有这个命令，能否把删除task的操作写进命令里，将不胜感激！

**Comment by Jone2008** [comment]
## 在运行 task 命令时，随机延迟启动任务的最大延迟时间
## 默认给javascript任务加随机延迟，如 RandomDelay="300" ，表示任务将在 1-300 秒内随机延迟一个秒数，然后再运行，取消延迟赋值为空
RandomDelay="3000"

**Comment by NaroisCool** [comment]
> 在运行 task 命令时，随机延迟启动任务的最大延迟时间
> 
> 默认给javascript任务加随机延迟，如 RandomDelay="300" ，表示任务将在 1-300 秒内随机延迟一个秒数，然后再运行，取消延迟赋值为空
> 
> RandomDelay="3000"

感谢大神，原来已经有这个功能

**Comment by NaroisCool** [comment]
> 在运行 task 命令时，随机延迟启动任务的最大延迟时间 默认给javascript任务加随机延迟，如 RandomDelay="300" ，表示任务将在 1-300 秒内随机延迟一个秒数，然后再运行，取消延迟赋值为空 RandomDelay="3000"
我看了一下我的配置里是一直有配置RandomDelay="300"，但是我的日志里task执行的时间并没有延迟，和cron的时间一致。请问是什么问题？

**Comment by NaroisCool** [comment]
> 

我看了一下我的配置里是一直有配置RandomDelay="300"，但是我的日志里task执行的时间并没有延迟，和cron的时间一致。请问是什么问题？

**Comment by NaroisCool** [comment]
> 在运行 task 命令时，随机延迟启动任务的最大延迟时间 默认给javascript任务加随机延迟，如 RandomDelay="300" ，表示任务将在 1-300 秒内随机延迟一个秒数，然后再运行，取消延迟赋值为空 RandomDelay="3000"

我看了一下我的配置里是一直有配置RandomDelay="300"，但是我的日志里task执行的时间并没有延迟，和cron的时间一致。请问是什么问题？
