### ISSUE TITLE
ts-node安装失败

### ISSUE THREAD

**Issue by qiurigao** [whyour/qinglong#1455]
pnpm add -g pm2 ts-node typescript tslib
+ pnpm add -g pm2 ts-node typescript tslib
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Already up-to-date                                                        Progress: resolved 198, reused 118, downloaded 0, added 0, done
 WARN  tslib has no binaries
 WARN  Issues with peer dependencies found
.
└─┬ ts-node
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"  
root@localhost:~ $

**Comment by jiuyaozhuce** [comment]
咋解决的？
