### ISSUE TITLE
青龙2.10.9打开脚本管理页面，显示"ENOENT: no such file or directory, stat '/ql/scripts/scripts"

### ISSUE THREAD

**Issue by ji-nian** [whyour/qinglong#1458]
如何修改路径为'/ql/scripts'呢？
![error](https://user-images.githubusercontent.com/67409497/171322806-71881750-1a10-4b69-b5da-e61f722d92d3.png)

**Comment by ji-nian** [comment]
ql check的结果如下：
![error2](https://user-images.githubusercontent.com/67409497/171323040-f5f94a3e-142c-4961-8fe0-be3ffc243e98.png)

**Comment by zhanggaolei001** [comment]
同样问题,no such file or directory, stat '/ql/scripts/scripts'

**Comment by ji-nian** [comment]
> 同样问题,no such file or directory, stat '/ql/scripts/scripts'

你可以看看"/ql/scripts"这个路径下是不是有"scripts"这个文件，删掉就能进了。好像是有个库里的任务叫mount.sh什么的导致的，可以看下日志、定时任务，删掉这个任务就不会了
