### ISSUE TITLE
网页提示 服务错误

### ISSUE THREAD

**Issue by LOVE2CMOL** [whyour/qinglong#1459]
版本[v2.13.2]
运行pm2 logs panel

输出日志
![image](https://user-images.githubusercontent.com/28857775/171352485-b57af189-7e12-49db-b453-8f0989d0f043.png)

重启后会恢复正常 
qm check也会恢复正常
但是过一个晚上又不行了
定时任务好像是运行的 但是面板不会自动拉库 脚本的运行日志也没有记录

.env文件是在的
已经尝试过重新部署 换过机器 重新安装

**Comment by LOVE2CMOL** [comment]
另外 我看见有人ql update 会出现这个问题 我也看过脚本的运行日志 
都是ql update执行时间之前才有记录 推断是ql update导致的问题
现在已经把ql update的定时任务关掉 观察几天试试

**Comment by 11ren** [comment]
我也有这种情况，请问ql update的定时任务怎么关掉？

**Comment by LOVE2CMOL** [comment]
> 我也有这种情况，请问ql update的定时任务怎么关掉？

定时任务里面 有个ql update的定时任务 禁用即可

**Comment by LOVE2CMOL** [comment]
3天过去 异常未出现
