### ISSUE TITLE
安装之后报错  打开面板提示pm2 logs panel 暂无日志

### ISSUE THREAD

**Issue by sanxianla** [whyour/qinglong#1464]
![屏幕截图 2022-06-03 090410](http://feixiang.eu.org/i/2022/06/03/fhe6sa.png)
docker日志如下
`./docker/docker-entrypoint.sh: line 30:    68 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/app.js -n panel --source-map-support --time
,控制面板启动成功...
,
,======================6. 启动定时任务========================
,
,./docker/docker-entrypoint.sh: line 34:    79 Trace/breakpoint trap   (core dumped) pm2 delete schedule &> /dev/null
,
,
,#
,# Fatal error in , line 0
,# unreachable code
,#
,#
,#
,#FailureMessage Object: 0xbea6c11c
,./docker/docker-entrypoint.sh: line 35:    90 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/schedule.js -n schedule --source-map-support --time
,定时任务启动成功...
,
,======================8. 执行自定义脚本========================
,
,自定义脚本后台执行中...
,
,############################################################
,
,容器启动成功...
,
,请先访问5700端口，登录成功面板之后再执行添加定时任务...
,############################################################
,
,crond[102]: crond (busybox 1.34.1) started, log level 8
,======================1. 检测配置文件========================
,
,'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
,'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
,./docker/docker-entrypoint.sh: line 12:    16 Trace/breakpoint trap   (core dumped) pm2 l &> /dev/null
,
,======================2. 安装依赖========================
,
,
,======================3. 启动nginx========================
,
,nginx启动成功...
,
,======================4. 启动面板监控========================
,
,./docker/docker-entrypoint.sh: line 24:    36 Trace/breakpoint trap   (core dumped) pm2 delete public &> /dev/null
,
,
,#
,# Fatal error in , line 0
,# unreachable code
,#
,#
,#
,#FailureMessage Object: 0xbec1d11c
,./docker/docker-entrypoint.sh: line 25:    47 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/public.js -n public --source-map-support --time
,监控服务启动成功...
,
,======================5. 启动控制面板========================
,
,./docker/docker-entrypoint.sh: line 29:    58 Trace/breakpoint trap   (core dumped) pm2 delete panel &> /dev/null
,
,
,#
,# Fatal error in , line 0
,# unreachable code
,#
,#
,#
,#FailureMessage Object: 0xbe89111c
,./docker/docker-entrypoint.sh: line 30:    69 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/app.js -n panel --source-map-support --time
,控制面板启动成功...
,
,======================6. 启动定时任务========================
,
,./docker/docker-entrypoint.sh: line 34:    80 Trace/breakpoint trap   (core dumped) pm2 delete schedule &> /dev/null
,
,
,#
,# Fatal error in , line 0
,# unreachable code
,#
,#
,#
,#FailureMessage Object: 0xbebe811c
,./docker/docker-entrypoint.sh: line 35:    91 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/schedule.js -n schedule --source-map-support --time
,定时任务启动成功...
,
,======================8. 执行自定义脚本========================
,
,自定义脚本后台执行中...
,
,############################################################
,
,容器启动成功...
,
,请先访问5700端口，登录成功面板之后再执行添加定时任务...
,############################################################
,
,crond[103]: crond (busybox 1.34.1) started, log level 8
,`

**Comment by DorkyRabbit** [comment]
我也是这样，重装还是不行

**Comment by funyhook** [comment]
重启就可以了

**Comment by sanxianla** [comment]
> 重启就可以了

我试过无数次重启 不管是重启青龙还是重启docker又或者重启玩客云都没用

**Comment by In-clude** [comment]
树莓派zerow 同错误 重装重启无效

**Comment by lipwah** [comment]
一样问题，重启都不行
