### ISSUE TITLE
请教订阅管理怎么用？ 如何拆解？

### ISSUE THREAD

**Issue by ixmu** [whyour/qinglong#1465]

**Comment by whyour** [comment]
@ixmu 复制原来的ql repi命令，打开新建订阅 随便粘贴，注意新建订阅旁边的小字

**Comment by ixmu** [comment]
> @ixmu 复制原来的ql repi命令，打开新建订阅 随便粘贴，注意新建订阅旁边的小字

例如ql repo https://github.com/shufflewzc/faker2.git "jd_|jx_|gua_|jddj_|jdCookie" "activity|backUp" "^jd[^_]|USER|function|utils|sendNotify|ZooFaker_Necklace.js|JDJRValidator_|sign_graphics_validate|ql|JDSignValidator|magic" "main"
这个里面哪个是白名单，哪个是黑名单，activity|backUp放在哪儿？

**Comment by whyour** [comment]
@ixmu 把这条命令拷贝，新建订阅，粘贴整条命令，这很难理解吗，粘贴完你可以看看

**Comment by ixmu** [comment]
> @ixmu 把这条命令拷贝，新建订阅，粘贴整条命令，这很难理解吗，粘贴完你可以看看

这个操作理解的，只是想了解一下新版本qinglong

**Comment by ixmu** [comment]
我愚钝了，感谢大佬
