### ISSUE TITLE
2.13.2更新后仍然无法安装linux下依赖

### ISSUE THREAD

**Issue by onego1998** [whyour/qinglong#1466]
开始安装依赖 bizCode，开始时间 2022/6/3 13:39:03

  bizCode (no such package):

依赖安装失败，结束时间 2022/6/3 13:39:05，耗时 1.862 秒

**Comment by whyour** [comment]
@china168 你确定有这依赖，把这个删掉。以前的没报错有问题

**Comment by china168** [comment]
> @china168 你确定有这依赖，把这个删掉。以前的没报错有问题

好吧!
bizCode，bizMsg，lxml三个都是这样，以前的没报错是也没装成功吗。

**Comment by china168** [comment]
@whyour
 好吧!
bizCode，bizMsg，lxml三个都是这样，以前的没报错是也没装成功吗。

**Comment by whyour** [comment]
@china168 no such package   翻译下

**Comment by china168** [comment]
@whyour 我是看老版本可以装,原来压根没有这个依赖

**Comment by china168** [comment]
@whyour ![2137](https://user-images.githubusercontent.com/61273164/171814644-0eab9179-bbc0-4a14-8356-77412a4f7da1.png)
第一次安装是这个提示。

**Comment by pkaewwc** [comment]
我也是bizCode，bizMsg，lxml三个 bizCode (no such package): 都是这个错误

**Comment by studentluo** [comment]
![image](https://user-images.githubusercontent.com/68803942/172576836-da149076-5870-41b8-bc80-b1d4a90ff800.png)

**Comment by Wesleycwx** [comment]
请教哪个大佬有解决方法吗？

**Comment by fengdan2021** [comment]
我也是。

**Comment by d8899p** [comment]
我的也是这个问题

**Comment by TheKing1991** [comment]
![image](https://user-images.githubusercontent.com/81273686/180613391-85f446b4-bfc3-4868-b25e-f9758c268cff.jpeg)有人解决吗？

**Comment by luckyreny** [comment]
同样的问题，最新版也有这个问题，请问是不需要这3个依赖了吗？

**Comment by cc9014** [comment]
需不需要这3个依赖是看你跑的脚本是否需要。建议先看脚本日志，提示了缺了再安装。不要参照网上教程一股脑把用不上的依赖都装一遍，有些教程挺老的了。
另外安装依赖感觉用命令行好点

**Comment by xuexijiaoben** [comment]
lxml用命令安装上了，但是面板里还是显示失败，其他两个没找到，
折腾了一晚上终于找到答案了，谢谢啦，

**Comment by ykf158** [comment]
> lxml用命令安装上了，但是面板里还是显示失败，其他两个没找到， 折腾了一晚上终于找到答案了，谢谢啦，

请问你是怎么解决的啊，我的也是安装不上

**Comment by xuexijiaoben** [comment]
> 

上面不都说了么，这些都不需要，教程太老了，脚本运行没问题就行

**Comment by xuexijiaoben** [comment]
> > lxml用命令安装上了，但是面板里还是显示失败，其他两个没找到， 折腾了一晚上终于找到答案了，谢谢啦，
> 
> 请问你是怎么解决的啊，我的也是安装不上


上面不都说了么，这些都不需要，教程太老了，脚本运行没问题就行

**Comment by bbhsky** [comment]
> > > lxml用命令安装上了，但是面板里还是显示失败，其他两个没找到， 折腾了一晚上终于找到答案了，谢谢啦，
> > 
> > 
> > 请问你是怎么解决的啊，我的也是安装不上
> 
> 上面不都说了么，这些都不需要，教程太老了，脚本运行没问题就行

问题就是脚本里要用，
TypeError: Cannot read properties of undefined (reading 'bizCode')
    at /ql/data/scripts/shufflewzc_faker2_main/jd_get_share_code.js:481:25
    at got.post.then.message (/ql/data/scripts/shufflewzc_faker2_main/jd_get_share_code.js:677:5772)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

lxml可以下载相关包下来直接安装  bizcode没找到是哪个包

**Comment by pygcnm** [comment]
我的也安装不上着三个依赖 bizCode，bizMsg，lxml

**Comment by zjkal** [comment]
我也安装不了这三个依赖
![image](https://github.com/whyour/qinglong/assets/15082976/f28699ba-3a3a-4b61-8e09-1f17175de0f2)

**Comment by mjy378283319** [comment]
哪位大佬解决了，还是装不上这三个依赖

**Comment by pengpengzhenshuai** [comment]
![1728459656203](https://github.com/user-attachments/assets/1ae7961a-d31b-4172-af31-aef987d929e8)

我这基本上linux 依赖全都是失败，求大佬解答

**Comment by zjkal** [comment]
我已经放弃了

**Comment by alienbigking** [comment]
我是用docker容器安装的，我用以下方法清除原来的错误的镜像源后，就可以安装成功了
可以在命令行窗口执行以下的内容

1、删除原来有问题的镜像源

rm -rf /etc/apt/sources.list.d/*

2、替换 /etc/apt/sources.list

echo "deb http://deb.debian.org/debian bookworm main" > /etc/apt/sources.list
echo "deb http://security.debian.org/debian-security bookworm-security main" >> /etc/apt/sources.list
echo "deb http://deb.debian.org/debian bookworm-updates main" >> /etc/apt/sources.list

3、更新软件源索引

apt-get update

4、回到青龙面板重新安装即可
