### ISSUE TITLE
能不能加个环境变量导出的功能

### ISSUE THREAD

**Issue by fengchenzhihun1** [whyour/qinglong#1469]
如题能不能增加一个环境变量导出导入的功能

**Comment by q8018414** [comment]
同求,且不止环境变量,现在的订阅也建议添加。变量和库同步转移，其他参数自行配置。迁移轻松了一大截，上次迁移，用了2小时。主要就是环境变量问题与库拉取。

**Comment by Nicolas-Gong** [comment]
在镜像内可以直接复制env文件，但是在青龙面板上不会显示。。。但是不影响读取，想要修改就得先添加了，确实需要一个导出导入功能，点击导出复制一个json到粘贴板，导入直接用json导入就可以了，还可以自己在json上修改添加，也省去了excel之类复杂的功能。
