### ISSUE TITLE
配置RandomDelay="300"延迟执行任务无效果

### ISSUE THREAD

**Issue by NaroisCool** [whyour/qinglong#1475]
config配置里有写RandomDelay="300"，但是下次执行task的时间和日志里显示task执行的时间都没有延迟，和cron的时间一致！

**Comment by cddjr** [comment]
作者对于设定为0分或30分或不是JS脚本的任务不作延迟处理
所以你需要看看你的脚本cron是不是刚好设定在这两个特殊时间点上了。
另外如果不是js脚本（比如python脚本）也不会有随机延迟

这里估计需要一个PR改进
