### ISSUE TITLE
2.12我都找不到青龙文件夹了，2.13更好了青龙自己都读取不到文件了，看图

### ISSUE THREAD

**Issue by studentluo** [whyour/qinglong#1483]
![QQ截图20220608165720](https://user-images.githubusercontent.com/68803942/172576287-021bb0b4-bb3f-4c19-acc0-f91844f71163.png)
脚本运行正常，debian10操作系统找了所有文件夹都找不到文件，神奇的是脚本居然运行正常，在面板里面新+一个脚本，刷新就没有了

**Comment by studentluo** [comment]
![image](https://user-images.githubusercontent.com/68803942/172576923-cdb2b3ce-3413-4066-999d-8ccf1ee9274d.png)

**Comment by fengchenzhihun1** [comment]
问题解决了不

**Comment by studentluo** [comment]
> 问题解决了不

退版本解决一切问题 淦
