### ISSUE TITLE
还是找不到文件夹问题

### ISSUE THREAD

**Issue by studentluo** [whyour/qinglong#1484]
![image](https://user-images.githubusercontent.com/68803942/172577870-4062d525-cbf1-41cc-a13d-ec06c522fde3.png)
所有的node和linux依赖安装都提示找不到文件夹，脚本运行正常

脚本管理功能也找不到任何文件，新建也不行，又遇到的吗。不行我还是装2.10吧啥问题都没有，自从2.12改了什么ql/data目录之后我从来没有见过文件，全盘翻烂了都没有

**Comment by ereere** [comment]
它让你运行 pnpm setup 了，执行后会添加 export PNPM_HOME=/root/.local/share/pnpm 和 export path 2行
