### ISSUE TITLE
每次版本更新都是强制升级？

### ISSUE THREAD

**Issue by victorpzg** [whyour/qinglong#1486]
每次版本更新都是强制升级？
1、能否给用户一个选择的机会呢？
每次强制升级都需要重新配置，这个也需要一定工作量和时间嘛~~~
希望大佬给用户一个可选择升级的机会可以不？
2、至少提供一个备份的时间呀再升级呀，
能否开发一个一键备份配置，升级后可以倒回备份的功能呀？

每次强升都重新配置，累觉不爱呀，5555

**Comment by cc9014** [comment]
？qinglong并不会强制升级啊，我一直用的2.10.13，没有被升级过。

**Comment by hzk2006** [comment]
在安装的时候不是提醒你了么 自动更新或者手动更新 默认手动更新....

**Comment by victorpzg** [comment]
抱歉哈，原来我装了watchtower，所以自动升级了。我的锅

**Comment by q8018414** [comment]
麻烦关闭一下issues呀。不求贡献，但求随开随关
