### ISSUE TITLE
【BUG】CPU爆的问题！建议优先修复这个问题！

### ISSUE THREAD

**Issue by MangoDong** [whyour/qinglong#1489]
CPU爆的问题！建议优先修复这个问题！

**Comment by tanranran** [comment]
+1

**Comment by FakeRosmontis** [comment]
是啊 每天都吃满

**Comment by showmexlq** [comment]
> CPU爆的问题！建议优先修复这个问题！



> +1



> CPU爆的问题！建议优先修复这个问题！
有可能是6379端口打开没设置密码被挖矿了,我之前遇到过,基本只能重装https://baijiahao.baidu.com/s?id=1721397787724438089&wfr=spider&for=pc

**Comment by FakeRosmontis** [comment]
> > CPU爆的问题！建议优先修复这个问题！
> 
> > +1
> 
> > CPU爆的问题！建议优先修复这个问题！
> > 有可能是6379端口打开没设置密码被挖矿了,我之前遇到过,基本只能重装https://baijiahao.baidu.com/s?id=1721397787724438089&wfr=spider&for=pc

我用的私钥，不是这个问题

**Comment by goodjimli** [comment]
+10086

**Comment by JuvenileQ** [comment]
中挖矿病毒了，我也中毒了，在使用docker安装完，阿里云安全预警，给我提示。你可以根剧这个脚本检查一下你的服务器
![image](https://user-images.githubusercontent.com/39209399/188878999-936527bf-9451-4cbd-aa5a-d020ab74a6d5.png)
