### ISSUE TITLE
所有脚本不运行

### ISSUE THREAD

**Issue by zhongdi520** [whyour/qinglong#149]
开始执行...

Wed May 19 2021 01:58:31 GMT+0800 (中国标准时间)
/bin/sh: js: not found

执行结束...
![1C915CAF-BE22-4428-9822-C39F5BE34610](https://user-images.githubusercontent.com/63575963/118701025-d6be9300-b845-11eb-8909-6ce612a81659.png)

**Comment by whyour** [comment]
删除镜像容器db目录下的数据，重新来
