### ISSUE TITLE
原淘宝 npm 域名即将停止解析，安装依赖会报错

### ISSUE THREAD

**Issue by chenmi2017** [whyour/qinglong#1499]
ERR_PNPM_REGISTRIES_MISMATCH This modules directory was created using the following registries configuration: {"default":"https://registry.npmjs.org/"}. The current configuration is {"default":"https://registry.npm.taobao.org/"}. To recreate the modules directory using the new settings, run "pnpm install".

估计是.npmrc文件
sentrycli_cdnurl=https://cdn.npm.taobao.org/dist/sentry-cli
strict-peer-dependencies=false

**可以直接打开地址**
https://cdn.npm.taobao.org/dist/sentry-cli
_可以发现已经报错了_

安装依赖会报错

**重置为官方源解决问题**
npm config set registry https://registry.npmjs.org/

**Comment by tabris233** [comment]
新的镜像换到了 https://registry.npmmirror.com ，但还是不行。

用 https://registry.npmjs.org/ 才 可以
