### ISSUE TITLE
V1.1版本 自定义任务 没有大部分任务没有禁用选项

### ISSUE THREAD

**Issue by doube1008** [whyour/qinglong#15]
![image](https://user-images.githubusercontent.com/28523974/113502726-b28e4780-9560-11eb-9782-c5914450500b.png)
![image](https://user-images.githubusercontent.com/28523974/113502728-b91cbf00-9560-11eb-8ea4-94bdc0bd0af3.png)

**Comment by whyour** [comment]
@doube1008 已修复，等待30分钟后最新镜像打包完成
