### ISSUE TITLE
订阅管理在登录失效的情况下无法定时执行

### ISSUE THREAD

**Issue by u2gign** [whyour/qinglong#1500]
## 开始执行... 2022-06-14 01:04:00

请先登录！

## 执行结束... 2022-06-14 01:04:00  耗时 0 秒
希望修复下，不然还需要经常登录青龙，保证登录不失效才行

**Comment by gujiangjiang** [comment]
我也是这个情况，提示请先登录

**Comment by nionionping** [comment]
我也同样是这个情况，提示请先登录
