### ISSUE TITLE
关于如何在青龙面板中执行php脚本

### ISSUE THREAD

**Issue by hainuo** [whyour/qinglong#1504]
请问一下  怎么集成php到青龙面板中呢
跟docker一样的操作吗？
我目前所有的终端脚本都是通过php来写的

**Comment by xu1xiang** [comment]
https://github.com/whyour/qinglong/blob/develop/docker/Dockerfile#L18-L35

你可以在这里装一下 php

**Comment by hainuo** [comment]
谢谢。假期有时间 研究下这个docker
