### ISSUE TITLE
所有的脚本拉库日志都不显示.

### ISSUE THREAD

**Issue by Core-pulling** [whyour/qinglong#1505]
运行的脚本都是正常的.但是拉取库的日志全部都是暂无日志.  青龙版本 2.13.3 .

**Comment by fengai230** [comment]
我的也没有日志，而且linux依赖安装不成功

**Comment by Core-pulling** [comment]
是的.我也是.LINUX依赖好像只能安卓gcc其他依赖安装失败.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月17日(星期五) 中午1:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 所有的脚本拉库日志都不显示. (Issue #1505)






我的也没有日志，而且linux依赖安装不成功

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您创建了这个线程。留言 ID ***@***.***与&gt;

**Comment by hiiseeu** [comment]
我也出不来，难受了，昨晚刚搭的，我还郁闷呢

**Comment by feitxue** [comment]
新版本应该是去订阅管理那里拉库。
我刚才也遇到了。

**Comment by tommyhe1217** [comment]
最新的镜像，最新的v2.13.3版本，订阅管理中运行有新增或删除的文件，日支中显示“通知失败(UnauthorizedError)”，手机也确实收不到通知。

**Comment by hiiseeu** [comment]
这个问题很致命啊，希望早日能够修复

**Comment by hiiseeu** [comment]
搞定了，自己手动在配置文件里面配置一下通知要用的参数；安装的时候配置的参数没有同步到配置文件里！
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/66768092/175283975-d64a870a-8a59-4131-8066-c24f8bcf50a6.png">

**Comment by tommyhe1217** [comment]
配置文件配置后正常的通知会有。但是订阅文件运行增加脚本的通知不提醒

hiiseeu ***@***.***>于2022年6月23日 周四19:01写道：

**Comment by winmerdx** [comment]
你们订阅管理里面填拉库链接都能正常拉库吗？为啥我要不拉不到要不就很快就显示拉成功了，但是看脚本里只拉取了很小一部分脚本，定时任务也没新增，服务器和本地机都是一样的问题（

**Comment by winterz1984** [comment]
> 新版本应该是去订阅管理那里拉库。 我刚才也遇到了。

牛逼啊，确实如此。解决了
