### ISSUE TITLE
点开环境变量页面有奇怪的上传请求https://o1098464.ingest.sentry.io/api/6122818/envelope/?sentry_key=xxxxx

### ISSUE THREAD

**Issue by huiyi9420** [whyour/qinglong#1509]
<img width="1162" alt="iShot_2022-06-19_14 36 18" src="https://user-images.githubusercontent.com/36962444/174468974-87010c1d-0429-4681-8af8-d02e8177ca4b.png">

**Comment by qqsir-dev** [comment]
值得关注！！

**Comment by h6fYe34KFSiH** [comment]
监控错误报告的 https://github.com/getsentry/sentry

**Comment by zhqu1148980644** [comment]
什么鬼，强制收集用户数据

**Comment by Vulcanraven91** [comment]
Atleast add a function to disable it. Thanks for the spam.
