### ISSUE TITLE
青龙面板安装并启动成功，但无法访问！！

### ISSUE THREAD

**Issue by 18201485644** [whyour/qinglong#1515]
执行日志：
![image](https://user-images.githubusercontent.com/55091666/175514717-11010974-276a-41fd-8e0f-c80cfd4b79a9.png)
![image](https://user-images.githubusercontent.com/55091666/175514782-4430c592-c302-46d4-837d-fe022fe2a2a5.png)
访问页面效果：
![image](https://user-images.githubusercontent.com/55091666/175514906-7a3678eb-c515-4ebc-958b-f541ae8ccb95.png)

**Comment by kuilei0926** [comment]
检查你的防火墙

**Comment by 18201485644** [comment]
> 检查你的防火墙

防火墙已经关闭

**Comment by 18201485644** [comment]
首次安装青龙时，容器启动日志在npm安装上有报错
![image](https://user-images.githubusercontent.com/55091666/175846335-c9c345f3-7b64-4393-9294-8b768194f7c3.png)

**Comment by heham** [comment]
一样的问题，开始可以访问，升级青龙后原来的脚本还在运行但是管理页面打不开了
