### ISSUE TITLE
从2.12.2 更新到2.13.3后，面板中安装依赖报错

### ISSUE THREAD

**Issue by tnnevol** [whyour/qinglong#1519]
一直提示pnpm环境变量有问题
![image](https://user-images.githubusercontent.com/28475939/176082184-d63278b5-64e6-493c-9838-fc63626a6ffc.png)
进入容器查看到pnpm环境变量已添加
![image](https://user-images.githubusercontent.com/28475939/176082377-8c60fd5a-c978-4f15-a4c3-336d7ab9ac63.png)
容器内可以正常全局安装包，并且之前的全局包可以查看到
![image](https://user-images.githubusercontent.com/28475939/176082511-25b6738a-8792-4dbf-b244-f0a7441f2519.png)

希望给一个解决方案

**Comment by tnnevol** [comment]
这个问题修复了么...

**Comment by whyour** [comment]
> 这个问题修复了么...

建议用最新版了再问，就是头铁？发包日志不看？
