### ISSUE TITLE
有没有人知道现在想手动去管理拉的脚本或者上传脚本在什么目录

### ISSUE THREAD

**Issue by sanxianla** [whyour/qinglong#1525]
找了半天脚本发现不在/root/ql/scripts里面
想使用dailycheckin的时候需要新建config.json  在root/ql/scripts新建好之后运行任务一直提示找不到脚本
之后在青龙面板新建才能找到脚本 
青龙面板新建的脚本在哪个文件夹啊有人知道吗

**Comment by rnadow** [comment]
东西在docker内，用`docker exec -it qinglong bash`，cd scripts之后ls就好，青龙里面好像也可以
![image](https://user-images.githubusercontent.com/56780236/178749470-a694b7a7-51c4-4f06-847a-19c8d1f11abc.png)
