### ISSUE TITLE
请问下互助码填写方式!!!

### ISSUE THREAD

**Issue by gcbzq32l** [whyour/qinglong#153]
![image](https://user-images.githubusercontent.com/43922414/118755740-ff717780-b89b-11eb-94be-94e05608ebb2.png)
填写了3个cookie    4-8的互助码都是和别人换的,,脚本运行的时候现在"只提交了3个互助码"
![image](https://user-images.githubusercontent.com/43922414/118755877-4a8b8a80-b89c-11eb-8721-809713a3e352.png)
是我的填写方式错了吗?

**Comment by whyour** [comment]
把自动互助的配置关了
