### ISSUE TITLE
最新的2.13.4 版本 运行任务 之后 最新运行时间 和 最后运行时常 不显示时间

### ISSUE THREAD

**Issue by lucien2023** [whyour/qinglong#1533]
![image](https://user-images.githubusercontent.com/70841606/179357347-6c2f00cc-d663-43e6-805c-3a607987c1c9.png)
更新了下 发现有这个问题，删除后 建了个新的 还是这样子

**Comment by Silentely** [comment]
同样 更新2.13.4后最后运行时间与最后运行时长都不更新了，但是实际脚本有定时执行

**Comment by Lucien6699** [comment]
> 同样 更新2.13.4后最后运行时间与最后运行时长都不更新了，但是实际脚本有定时执行

是的 他实际上运行了 有运行完成的日志 推送 信息都正常

**Comment by Jingle-Pan** [comment]
感觉变慢了，退回到旧版本

**Comment by VincentWilson525** [comment]
> 

请问一下如何退回？

**Comment by Silentely** [comment]
> 

简单 自己改拉取的tag
 docker pull whyour/qinglong:2.13.3

**Comment by Silentely** [comment]
> > 
> 
> 请问一下如何退回？

简单 自己改拉取的tag
docker pull whyour/qinglong:2.13.3

**Comment by Ecalose** [comment]
同样的问题，等大佬修吧

**Comment by Silentely** [comment]
> 同样的问题，等大佬修吧

等不及修复可以手动进容器更新ql/shell/share.sh和ql/shell/task.sh 文件

**Comment by lucien2023** [comment]
我也退回了
退回方式：拉取上一版的镜像
docker pull whyour/qinglong:2.13.3
之后重新创建原目录

**Comment by Ecalose** [comment]
> > 同样的问题，等大佬修吧
> 
> 等不及修复可以手动进容器更新ql/shell/share.sh和ql/shell/task.sh 文件

ok，我直接拉dev的镜像了

**Comment by Kaystar** [comment]
而且任务状态也不显示了
