### ISSUE TITLE
并发执行任务数量默认10的修改

### ISSUE THREAD

**Issue by zyystudio** [whyour/qinglong#1534]
全部选取执行发现基本是10个并发执行任务，占用cpu到99%，能否告知什么地方可以修改减少下？谢谢

**Comment by kuilei0926** [comment]
config.sh

**Comment by zyystudio** [comment]
改为2好像没有起效哦。全选700+个后运行，还是10个在运行中，cpu占用99%

## 设置批量执行任务时的并发数，默认同时执行5个任务
MaxConcurrentNum="2"

**Comment by cddjr** [comment]
> 改为2没有起效。全选700+个后运行，还是10个10个在运行中，cpu占用99%
> 
> 设置批量执行任务时的并发数，默认同时执行5个任务 MaxConcurrentNum="2"

MaxConcurrentNum这个参数已经废弃了，一切按设定的时间来运行。如果不希望同时执行太多就去修改任务的cron规则。

**Comment by zyystudio** [comment]
> > 改为2没有起效。全选700+个后运行，还是10个10个在运行中，cpu占用99%
> > 设置批量执行任务时的并发数，默认同时执行5个任务 MaxConcurrentNum="2"
> 
> MaxConcurrentNum这个参数已经废弃了，一切按设定的时间来运行。如果不希望同时执行太多就去修改任务的cron规则。

我理解你说的废弃了 并且修改cron定时启动即可。我想问的是如果全选几百个任务一起执行是不是就没有办法并发控制了

**Comment by cddjr** [comment]
https://github.com/whyour/qinglong/blob/06723407d2560883e09bf32537610a286dbf7e5a/back/services/cron.ts#L182-L185

184行的10就是最大并发数，似乎只能改代码了

**Comment by zyystudio** [comment]
> https://github.com/whyour/qinglong/blob/06723407d2560883e09bf32537610a286dbf7e5a/back/services/cron.ts#L182-L185
> 
> 184行的10就是最大并发数，似乎只能改代码了

多谢！改了这个地方之后，如何build？直接改了docker上的这个地方重启后也没有效果

**Comment by bylengfeng** [comment]
现在可以了，面板没有出现的话，通过api: http://localhost:5600/open/system/config/cron-concurrency
请求后会显示的
