### ISSUE TITLE
2.13.4的几个问题

### ISSUE THREAD

**Issue by Kaystar** [whyour/qinglong#1536]
更新之前添加的脚本：运行状态不显示，最后运行时间，最后运行时长不更新，点击操作下面的日志是空白的，点任务本身弹框中可以查看日志，日志最后出现     ## 更新任务状态失败(UnauthorizedError)

更新之后添加的脚本：运行状态不显示，最后运行时间和最后运行时长显示为 -   点击操作下面的日志是空白的，点任务本身弹框中也不显示日志，脚本运行完进容器查看日志，最后出现     ## 更新任务状态失败(UnauthorizedError)

**Comment by kuilei0926** [comment]
2.13.5依旧存在

**Comment by caneman** [comment]
2.13.7依然存在
