### ISSUE TITLE
在 Xshell执行 docker logs -f qinglong时，log显示从创建容器时一直到现在，这怎么定期删除呢

### ISSUE THREAD

**Issue by ycyfff** [whyour/qinglong#1537]
如题，
1.系统设置-其他设置-日志删除频率设置为1天，删除不掉运行日志
2./var/lib/docker/overlay2/fc0313136759b44f23a1fd6d601201be8162fbd41f26906d918c5f83fcc448fd/merged/var/log/nginx  这个青龙docker目录下的access.log文件肉眼可见的增长，每天增加，10天的时间5个G

**Comment by ycyfff** [comment]
![image](https://user-images.githubusercontent.com/82076423/179389649-9dc01b56-1bb2-419e-97cc-df309add5e6a.png)

**Comment by ycyfff** [comment]
![image](https://user-images.githubusercontent.com/82076423/179389732-3cb13365-da52-4e6b-ba43-9f636647de0f.png)

**Comment by ycyfff** [comment]
![image](https://user-images.githubusercontent.com/82076423/179389762-d6ad1291-f825-4303-9169-0f13ef3208c5.png)

**Comment by Silentely** [comment]
你可以自己设置容器的日志大小 

vim /etc/docker/daemon.json

{
  "log-driver":"json-file",
  "log-opts": {"max-size":"500m", "max-file":"3"}
}

max-size=500m，意味着一个容器日志大小上限是500M， 
max-file=3，意味着一个容器有三个日志，分别是id+.json、id+1.json、id+2.json。
载入并重启
systemctl daemon-reload
systemctl restart docker

只针对后续新建容器

docker-compose.yml中也可以限制 
nginx:
  image: nginx:1.12.1
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "5g"

docker run中限制
docker run -d --log-opt max-size=1g nginx

**Comment by ycyfff** [comment]
![image](https://user-images.githubusercontent.com/82076423/179390726-32e2afd4-3ebe-4301-92ec-d0676c6f7ac3.png)
这是新建的青龙，access.log文件还很小可以直接打开。

![image](https://user-images.githubusercontent.com/82076423/179390773-151026c0-62af-493c-843d-056430a92ec7.png)
过10天就5个G了

**Comment by ycyfff** [comment]
> 

您看下容器内Nginx的access.log文件，也是一直增加吗？

**Comment by Silentely** [comment]
> > 
> 
> 您看下容器内Nginx的access.log文件，也是一直增加吗？

我的事下午2点左右新建的 目前18M
![](https://s3.bmp.ovh/imgs/2022/07/17/e6d73e6c14580287.png)
容器限制了在150M 需要过几天再观察是否超过限制
        logging: 
            driver: "json-file"
            options: 
                max-size: "150m"
                max-file: "3"

**Comment by ycyfff** [comment]
> > > 
> > 
> > 
> > 您看下容器内Nginx的access.log文件，也是一直增加吗？
> 
> 我的事下午2点左右新建的 目前18M ![](https://camo.githubusercontent.com/0e82fdba3969049f801800d2f8f3725ea552f4b64d350e59c124dfd279c4070a/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30372f31372f653664373365366331343538303238372e706e67) 容器限制了在150M 需要过几天再观察是否超过限制 logging: driver: "json-file" options: max-size: "150m" max-file: "3"

我这文件一删除，跑任务是就code 429了。所以想找个办法抑制增长，等你后续反馈下，谢谢

**Comment by ycyfff** [comment]
> > > 
> > 
> > 
> > 您看下容器内Nginx的access.log文件，也是一直增加吗？
> 
> 我的事下午2点左右新建的 目前18M ![](https://camo.githubusercontent.com/0e82fdba3969049f801800d2f8f3725ea552f4b64d350e59c124dfd279c4070a/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30372f31372f653664373365366331343538303238372e706e67) 容器限制了在150M 需要过几天再观察是否超过限制 logging: driver: "json-file" options: max-size: "150m" max-file: "3"

还有个问题想请教，在shell执行命令docker logs qinglong -f 时，就显示了从容器创建到现在的所有运行日志，这日志拖的太长了，有办法定时删除吗?在青龙面板创建 ql rmlog 3 任务只能删除ql/log文件夹内单个任务3天前的日志，删除不掉在shell执行命令docker logs qinglong -f 时显示的运行日志。

**Comment by Silentely** [comment]
> > > > 
> > > 
> > > 
> > > 您看下容器内Nginx的access.log文件，也是一直增加吗？
> > 
> > 
> > 我的事下午2点左右新建的 目前18M ![](https://camo.githubusercontent.com/0e82fdba3969049f801800d2f8f3725ea552f4b64d350e59c124dfd279c4070a/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30372f31372f653664373365366331343538303238372e706e67) 容器限制了在150M 需要过几天再观察是否超过限制 logging: driver: "json-file" options: max-size: "150m" max-file: "3"
> 
> 我这文件一删除，跑任务是就code 429了。所以想找个办法抑制增长，等你后续反馈下，谢谢

其实有个办法可以解决，在容器里添加个定时任务清理access.log日志
echo "" > /var/log/nginx/access.log

或者一劳永逸 在nginx配置文件中关闭log日志即可
/etc/nginx/nginx.conf里access_log /var/log/nginx/access.log main; 更改为access_log off;
后在重新载入nginx 
nginx -s reload

**Comment by Silentely** [comment]
> 

因为logs这个命令执行的是容器日志，并不是脚本日志记录，操作是在宿主机操作的，不像你清理脚本日志ql rmlog 3是需要进入容器执行命令，你可以执行命令来查看容器日志最后一百条docker logs -f -t --tail=100 qinglong
如果你是要删除docker logs -f qinglong的日志的话 可以尝试以下办法

找出docker container日志文件所在的路径
docker inspect --format='{{.LogPath}}' <container_name_or_id>
删除或者清空日志文件内容
echo |sudo tee $(docker inspect --format='{{.LogPath}}' <container_name_or_id>)

**Comment by ycyfff** [comment]
> 

Nginx文件夹内的access.log文件可以删除吗？我的5个G的文件，我上次删除后跑任务显示code 429，我以为是因为我删除后才导致code 429的，所以后面就新建了个容器，10天就5个G了。甲骨文云不足50G的存储，分分钟塞满了，请问这文件可以删吗？

**Comment by Silentely** [comment]
> 

你在nginx.conf里将日志关闭就可以不用理这个文件，日志关闭这个文件也不会新增内容了，你要删掉也可以，但前提是你关闭了日志

**Comment by ycyfff** [comment]
> > 
> 
> 你在nginx.conf里将日志关闭就可以不用理这个文件，日志关闭这个文件也不会新增内容了，你要删掉也可以，但前提是你关闭了日志
