### ISSUE TITLE
2.11.3升级失败

### ISSUE THREAD

**Issue by justdoiting** [whyour/qinglong#1538]
![image](https://user-images.githubusercontent.com/109136320/179399187-a9c3b994-c983-4c8d-8c4c-5f07b6df92ce.png)

下面这个升级方式直接GG，会卡死，然后进不去面板
![image](https://user-images.githubusercontent.com/109136320/179399212-d780462e-076d-464a-8dbb-1f6fbf58e845.png)

用ql update命令也是失败
![image](https://user-images.githubusercontent.com/109136320/179399450-dbda50f0-eaa8-44af-9cc3-ffae0e99d46a.png)

我的环境是IBM的Linuxone的Ubuntu 20.04.4 (GNU/Linux 5.4.0-121-generic s390x)

之前是用网上的一键傻瓜式安装的2.11.3，现在想升级2.13.4实在不会

之前的安装脚本 curl -sSL https://js.dayplus.xyz/https://raw.githubusercontent.com/6dylan6/jdpro/main/docker/ql1key.sh -o install.sh && bash install.sh

**Comment by hosts765614407** [comment]
一样，暂时还在2.11.3，不知道这么才可以升上去

**Comment by justdoiting** [comment]
> 一样，暂时还在2.11.3，不知道这么才可以升上去

升不了，2.11.3是最后一个支持s390x的，往上没有了

**Comment by rnadow** [comment]
一样，直接gg,然后修复，接着就404了，是不是nginx的问题
