### ISSUE TITLE
私有仓库拉取失败

### ISSUE THREAD

**Issue by zhangli29827** [whyour/qinglong#1539]
![11111111](https://user-images.githubusercontent.com/77035905/179442559-0f402541-a519-4977-941a-e0fc8ecbf7c1.png)
仓库是存在的，同时配置了私玥

**Comment by Silentely** [comment]
不考虑下网络问题？ 你机器上curl能连上github么？

**Comment by zhangli29827** [comment]
> 不考虑下网络问题？ 你机器上curl能连上github么？
拉取过其他GitHub的库，是可以成功拉取的
