### ISSUE TITLE
极速版里的金币任务  只有第一个cookies能跑完整，第二个跑一部分，第三个账户完全没跑

### ISSUE THREAD

**Issue by zhangj3** [whyour/qinglong#154]
极速版里的金币任务  只有第一个cookies能跑完整，第二个跑一部分，后面的账户就没日志输出了，查询获取金币记录，第三个账户就没有

附上日志

🔔京东极速版, 开始!

====================共3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/5/18 上午7:00:01=====================

******开始【京东账号1】*********

【幸运大转盘】剩余抽奖机会：1
幸运大转盘抽奖获得：【15-12福利神券-老人】

去做任务转盘抽奖逛会场
任务完成成功
【幸运大转盘】剩余抽奖机会：1
幸运大转盘抽奖获得：【29-20福利神券-老人】

签到获得0.07现金，共计获得6.93
【1/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得35金币
【2/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得45金币
【3/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得32金币
【4/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得48金币
【5/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得67金币
【6/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得45金币
【7/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得36金币
【8/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得44金币
【9/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得35金币
【10/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得71金币
【11/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得34金币
【12/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得46金币
【13/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得33金币
【14/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得47金币
【15/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得70金币
【16/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得35金币
【17/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得26金币
【18/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得34金币
【19/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得25金币
【20/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得71金币
【21/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得26金币
【22/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得34金币
【23/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得27金币
【24/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得33金币
【25/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得70金币
【26/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得33金币
【27/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得26金币
【28/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得34金币
【29/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得18金币
【30/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得72金币
【31/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得18金币
【32/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得22金币
【33/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得18金币
【34/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得22金币
【35/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得66金币
【36/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得23金币
【37/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得17金币
【38/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得23金币
【39/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得18金币
【40/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得74金币
【41/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得9金币
【42/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得11金币
【43/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得9金币
【44/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得11金币
【45/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得61金币
【46/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得11金币
【47/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得9金币
【48/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得11金币
【49/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得8金币
【50/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得63金币
【51/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得8金币
【52/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得12金币
【53/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得9金币
【54/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得11金币
【55/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得62金币
逛商品赚金币任务开启失败，任务已达上限
【1/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得60金币
【2/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得120金币
【3/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得60金币
【4/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得120金币
【5/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得60金币
【6/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得120金币
【7/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得60金币
【8/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得120金币
【9/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得60金币
【10/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得120金币
逛活动赚金币任务开启失败，任务已达上限
【1/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【2/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【3/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【4/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【5/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【6/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【7/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【8/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【9/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【10/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【11/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【12/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【13/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【14/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【15/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【16/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【17/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【18/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【19/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【20/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【21/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【22/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【23/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【24/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【25/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【26/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【27/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【28/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【29/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【30/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【31/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【32/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【33/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【34/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【35/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【36/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【37/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【38/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【39/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【40/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得120金币
【41/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【42/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【43/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【44/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【45/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得120金币
【46/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【47/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【48/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【49/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【50/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得120金币
【51/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【52/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【53/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【54/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【55/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得120金币
【56/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【57/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【58/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【59/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【60/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得120金币
【61/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【62/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【63/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【64/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【65/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得60金币
【66/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【67/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【68/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【69/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【70/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得60金币
【71/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【72/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【73/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【74/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【75/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得60金币
【76/85】浏览商品任务记录成功，等待30秒
看视频赚金币任务完成，获得5金币
【77/85】浏览商品任务记录成功，等待30秒
看视频赚金币任务完成，获得5金币
【78/85】浏览商品任务记录成功，等待30秒
看视频赚金币任务完成，获得5金币
【79/85】浏览商品任务记录成功，等待30秒
看视频赚金币任务完成，获得5金币
【80/85】浏览商品任务记录成功，等待30秒
看视频赚金币任务完成，获得40金币
【81/85】浏览商品任务记录成功，等待30秒
看视频赚金币任务完成，获得5金币
【82/85】浏览商品任务记录成功，等待30秒
看视频赚金币任务完成，获得5金币
【83/85】浏览商品任务记录成功，等待30秒
看视频赚金币任务完成，获得5金币
【84/85】浏览商品任务记录成功，等待30秒
看视频赚金币任务完成，获得5金币
【85/85】浏览商品任务记录成功，等待30秒
看视频赚金币任务完成，获得40金币
看视频赚金币任务已达上限
邀好友赚金币任务完成成功，预计获得60金币
拆红包得现金任务完成成功，预计获得60金币
借1元得20话费任务完成成功，预计获得60金币
签到提现任务完成成功，预计获得60金币
东东爱消除任务完成成功，预计获得60金币
一元赢大奖任务完成成功，预计获得60金币
幸运转盘任务完成成功，预计获得60金币
现金签到任务完成成功，预计获得60金币
推推赚大钱任务完成成功，预计获得60金币
天天抽奖任务完成成功，预计获得60金币
水果免费领任务完成成功，预计获得60金币
砍价免费拿任务完成成功，预计获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币
气泡收取成功，获得60金币

==============📣系统通知📣==============
京东极速版
京东账号1D
幸运大转盘抽奖获得：【15-12福利神券-老人】
幸运大转盘抽奖获得：【29-20福利神券-老人】
本次运行获得6678金币，共计158078金币
可兑换 15.81 元京东红包
兑换入口：京东极速版->我的->金币

******开始【京东账号2】*********

【幸运大转盘】剩余抽奖机会：1
幸运大转盘抽奖获得：【29-20福利神券-老人】

去做任务转盘抽奖逛会场
任务完成成功
【幸运大转盘】剩余抽奖机会：1
幸运大转盘抽奖获得：【28-19福利神券-老人】

签到获得0.5现金，共计获得6.74
【1/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得45金币
【2/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得35金币
【3/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得48金币
【4/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得32金币
【5/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得61金币
【6/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得35金币
【7/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得44金币
【8/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得36金币
【9/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得45金币
【10/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得74金币
【11/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得46金币
【12/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得34金币
【13/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得47金币
【14/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得33金币
【15/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得69金币
【16/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得25金币
【17/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得34金币
【18/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得26金币
【19/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得35金币
【20/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得69金币
【21/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得34金币
【22/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得26金币
【23/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得33金币
【24/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得27金币
【25/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得76金币
【26/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得27金币
【27/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得34金币
【28/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得26金币
【29/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得22金币
【30/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得63金币
【31/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得22金币
【32/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得18金币
【33/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得22金币
【34/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得18金币
【35/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得70金币
【36/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得17金币
【37/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得23金币
【38/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得17金币
【39/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得22金币
【40/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得63金币
【41/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得11金币
【42/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得9金币
【43/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得11金币
【44/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得9金币
【45/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得71金币
【46/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得9金币
【47/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得11金币
【48/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得9金币
【49/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得12金币
【50/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得74金币
【51/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得12金币
【52/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得8金币
【53/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得11金币
【54/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得9金币
【55/55】浏览商品任务记录成功，等待5秒
逛商品赚金币任务完成，获得63金币
逛商品赚金币任务开启失败，任务已达上限
【1/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得60金币
【2/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得120金币
【3/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得60金币
【4/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得120金币
【5/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得60金币
【6/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得120金币
【7/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得60金币
【8/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得120金币
【9/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得60金币
【10/10】浏览商品任务记录成功，等待10秒
逛活动赚金币任务完成，获得120金币
逛活动赚金币任务开启失败，任务已达上限
【1/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【2/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【3/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【4/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【5/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【6/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【7/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【8/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【9/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【10/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【11/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【12/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【13/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【14/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【15/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【16/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【17/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【18/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【19/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【20/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【21/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【22/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【23/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【24/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【25/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【26/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【27/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【28/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【29/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【30/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【31/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【32/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【33/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【34/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得30金币
【35/85】浏览商品任务记录成功，等待15秒
看视频赚金币任务完成，获得120金币
【36/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【37/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【38/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【39/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【40/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得120金币
【41/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【42/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【43/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【44/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【45/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得120金币
【46/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【47/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【48/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【49/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【50/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得120金币
【51/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【52/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【53/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【54/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【55/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得120金币
【56/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【57/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【58/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【59/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得25金币
【60/85】浏览商品任务记录成功，等待18秒
看视频赚金币任务完成，获得120金币
【61/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【62/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【63/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【64/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【65/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得60金币
【66/85】浏览商品任务记录成功，等待20秒
看视频赚金币任务完成，获得10金币
【67/85】浏览商品任务记录成功，等待20秒

**Comment by zhangj3** [comment]
我猜测 是不是账户太多的原因，策略算了下 第一个账户的所有任务+第二个账号的部分任务 时间总和在一个小时，到了8点可能有其他任务要跑吧

**Comment by woboo110** [comment]
配置文件里的定时任务执行的超时时间改长点，默认1小时执行不玩就杀死进程了，这个任务耗时太长

**Comment by whyour** [comment]
> 我猜测 是不是账户太多的原因，策略算了下 第一个账户的所有任务+第二个账号的部分任务 时间总和在一个小时，到了8点可能有其他任务要跑吧

你可以改成并发，也可以把配置里的超时时间加长

**Comment by woboo110** [comment]
> 我猜测 是不是账户太多的原因，策略算了下 第一个账户的所有任务+第二个账号的部分任务 时间总和在一个小时，到了8点可能有其他任务要跑吧

跟其他任务没关系啊，账号如果较多，任务是按账号顺序执行，导致这一个任务耗时太长，配置文件里有超时设置，超过那个时间， 这个任务就被强行停止了，所以有可能只跑完了俩账号就超时停止了，你可以把任务改成并发，就是所有账号同时跑，这样对机子性能要求较高，再就是改超时设置，把时间改长

**Comment by zhangj3** [comment]
> > 我猜测 是不是账户太多的原因，策略算了下 第一个账户的所有任务+第二个账号的部分任务 时间总和在一个小时，到了8点可能有其他任务要跑吧
> 
> 你可以改成并发，也可以把配置里的超时时间加长

收到，谢谢大家~~~
