### ISSUE TITLE
青龙 2.13.6 重启后依赖重新安装一次？

### ISSUE THREAD

**Issue by woniubenben** [whyour/qinglong#1542]
容器重启后，所有依赖重新安装。这个怎么解决

**Comment by sunopen1979** [comment]
我是重新拉取的也不行，所有依赖都变成安装失败，最后试了一下ql check，现在依赖都能安装了

**Comment by Jingle-Pan** [comment]
执行定时任务延时比较厉害，长达5分钟

**Comment by DanielEcho** [comment]
蹲一个如何解决，每次重启容器都会重装所有依赖

**Comment by ErixWong** [comment]
之前默认镜像，每次安装依赖都失败。现在换了debian镜像之后，能自动安装成功了。很奇怪。
