### ISSUE TITLE
重启青龙容器后进入死循环无限重启

### ISSUE THREAD

**Issue by sherlockQvQ** [whyour/qinglong#1547]
docker logs 青龙提示以下
======================1. 检测配置文件========================

/ql/shell/share.sh: line 83: /bin/mkdir: Argument list too long
./docker/docker-entrypoint.sh: line 10: /bin/cp: Argument list too long
./docker/docker-entrypoint.sh: line 11: /bin/cp: Argument list too long

======================2. 安装依赖========================

/ql/shell/share.sh: line 276: /usr/bin/diff: Argument list too long

======================3. 启动nginx========================

./docker/docker-entrypoint.sh: line 20: /usr/sbin/nginx: Argument list too long
nginx启动成功...

======================4. 启动控制面板========================

./docker/docker-entrypoint.sh: line 25: /usr/local/bin/pm2: Argument list too long
控制面板启动成功...

======================5. 启动定时任务========================

./docker/docker-entrypoint.sh: line 30: /usr/local/bin/pm2: Argument list too long

请问该如何解决该问题？

**Comment by code-ooo** [comment]
解决了吗，我也有类似的问题
