### ISSUE TITLE
armv8 最新版青龙linux依赖,全部安装失败

### ISSUE THREAD

**Issue by TheKing1991** [whyour/qinglong#1550]
谁知道怎么解决啊？换源,乱七八糟的都试过了,没有用!

**Comment by TheKing1991** [comment]
![image](https://user-images.githubusercontent.com/81273686/180613252-7961f070-2fee-4fd8-9133-d380c3079f6e.jpeg)困扰我很长时间了!

**Comment by whyour** [comment]
都删了就行了  谁告诉你有这三个依赖的
