### ISSUE TITLE
青龙订阅拉库问题

### ISSUE THREAD

**Issue by heimawsw** [whyour/qinglong#1551]
fatal: not a git repository (or any parent up to mount point /ql)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

fatal: not a git repository (or any parent up to mount point /ql)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

fatal: not a git repository (or any parent up to mount point /ql)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

fatal: not a git repository (or any parent up to mount point /ql)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by whyour** [comment]
不允许直接挂载 ql 目录

**Comment by heimawsw** [comment]
> 直接直接挂载 ql 目录

麻烦具体说一下，我没有挂载ql目录呀，突然发现订阅这样了

**Comment by heimawsw** [comment]
repo全删除，重拉解决问题，谢谢
