### ISSUE TITLE
TS运行环境下sendNotify.js引用错误问题

### ISSUE THREAD

**Issue by charmingYouYou** [whyour/qinglong#1552]
https://github.com/whyour/qinglong/blob/f0869567de580fc252a178f8db2ce8c8d8634db3/sample/notify.js#L726
在ts环境下没有对变量进行var, const, let的声明
![image](https://user-images.githubusercontent.com/31199453/180629596-5a013215-388f-4633-b8b0-f726ba8f389e.png)

**Comment by whyour** [comment]
PR is welcoming!

**Comment by charmingYouYou** [comment]
> PR is welcoming!

PR is coming #1553
