### ISSUE TITLE
新建订阅时, 文件后缀匹配问题错误

### ISSUE THREAD

**Issue by charmingYouYou** [whyour/qinglong#1554]
https://github.com/whyour/qinglong/blob/cb004cfbf547b304cedf776b8b2ff1086b955dc2/src/pages/subscription/modal.tsx#L205
![image](https://user-images.githubusercontent.com/31199453/180633669-854f08e1-68d3-4ed5-9f15-830367ec2076.png)
预期: 匹配后缀js ts
实际: 只匹配到了js
问题: 使用split(' ')匹配命令, 但是extensions也是用空格分割的, 导致无法匹配

**Comment by whyour** [comment]
链接只要链接   不是整个命令

**Comment by charmingYouYou** [comment]
![image](https://user-images.githubusercontent.com/31199453/180633796-7b8a6833-ed0d-484f-b2d6-31b93cbc1cbd.png)
但是这块有个剪切板解析的逻辑啊, 如果我粘贴的ql repo命令, 解析还是会有空格的问题

**Comment by charmingYouYou** [comment]
> 链接只要链接 不是整个命令

这个剪切板使用场景是什么样的呢?

**Comment by whyour** [comment]
@charmingYouYou 剪贴板是打开弹框直接粘贴  不是粘到链接里

**Comment by charmingYouYou** [comment]
![image](https://user-images.githubusercontent.com/31199453/180633939-ba5a8693-c052-406a-96e0-64839e6f818b.png)

**Comment by whyour** [comment]
@charmingYouYou 你这样写是有问题  可以提pr

**Comment by charmingYouYou** [comment]
> @charmingYouYou 你这样写是有问题 可以提pr

可以考虑文件后缀也用`|`分割吗?因为我看别的参数都是这样, 只有文件后缀是空格分割

**Comment by whyour** [comment]
@charmingYouYou 也是可以
