### ISSUE TITLE
index file smaller than expected

### ISSUE THREAD

**Issue by jjkk52** [whyour/qinglong#1558]
开始更新仓库：/ql/data/repo/KingRan_KR
fatal: .git/index: index file smaller than expected
更新/ql/data/repo/KingRan_KR失败，请检查网络...

网上解决方案：
git checkout -f master
git reset --hard origin/master

好像没有用呀，还是我操作不对！！

**Comment by whyour** [comment]
把仓库目录删了 重新拉取
