### ISSUE TITLE
2.13.6版本硬盘异常大量读取导致死机

### ISSUE THREAD

**Issue by SekiBetu** [whyour/qinglong#1561]
![image](https://user-images.githubusercontent.com/38283893/181559111-1b35b058-b868-4d26-9069-ee6f66c23693.png)
我完全没有头绪如何解决这个问题，用了几小时就卡死，卡死状态不能查询进程，又没有手段查看历史进程的状态，用一会儿就要重启服务器

服务器上只有一个docker，只有一个青龙镜像，很干净的Debian11系统
青龙镜像版本是latest，显示的是2.13.6
拉了faker2的库，难道这个库有问题

查了腾讯云服务器历史，7月17日的时候出现的问题，根据docker更新日期，推测2.13.3版本好像没问题，目前回退至2.13.4测试几天

**Comment by SekiBetu** [comment]
目前运行了一天了，正常，说明2.13.4以上版本可能有问题

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/181879006-d0babc24-b535-4461-869b-f93350c6a979.png)
2.13.4版本有问题，继续降级到2.13.3测试

**Comment by whyour** [comment]
限制下容器的资源，然后观察容器内进程状态

**Comment by SekiBetu** [comment]
2.13.3版本运行正常

**Comment by gyumyo** [comment]
同样问题，一天死机一次，已经卸载了。能提供一下2.13.3版本的拉取方法吗？

**Comment by klxyy** [comment]
> 同样问题，一天死机一次，已经卸载了。能提供一下2.13.3版本的拉取方法吗？

拉取的时候加上版本号即可

**Comment by talentyao** [comment]
2.13.3的版本是真的好用！升了几次还是退回用这个版本了。

**Comment by gujiangjiang** [comment]
我也是，总是死机，限制了资源也死机，什么pm error什么的，页面都进不去，每天都要死一次，每天都要重启docker，今天打开群晖一看，好家伙，CPU直接拉满了，99%，一看全是qinglong，但是页面依然打不开，而且没有error日志，太奇怪了，以前qinglong稳定跑几个月都没事，最近几个版本不知道怎么回事，频繁的卡死，还总是出现99%的占资源现象，不解。。
<img width="968" alt="QQ20220811-075403@2x" src="https://user-images.githubusercontent.com/13273955/184042601-81704a06-12fd-45d4-bf6c-a92f593f429a.png">
。

**Comment by Mioscout** [comment]
2.13.7有同样问题，回退到2.13.3正常（OP上的docker，会导致软路由死机）

**Comment by lostme01** [comment]
怎么才能回退？

**Comment by SekiBetu** [comment]
鼓起勇气升级到了2.14.5，目前没有问题2天了

**Comment by zhaoguomanong** [comment]
> 鼓起勇气升级到了2.14.5，目前没有问题2天了

现在在用什么版本？ 最新版本读写硬盘太离谱了，想找个好用的历史版本
