### ISSUE TITLE
订阅管理拉库报错

### ISSUE THREAD

**Issue by a1564471347** [whyour/qinglong#1565]
![473D7D54-86C3-4F89-B29B-17595B2C38B6](https://user-images.githubusercontent.com/65760851/182894404-3e79c0e7-187c-43b4-9863-fb3b61725d19.jpeg)

**Comment by ixmu** [comment]
请问解决了吗？

我添加任务一直提示UnauthorizedError

**Comment by cddjr** [comment]
你是把订阅命令当url网址填进去了吧
