### ISSUE TITLE
升级后管理页面进不去总算解决了，记录一下吧

### ISSUE THREAD

**Issue by heham** [whyour/qinglong#1568]
原来是从官方这里安装的
docker run -dit \
  -v $PWD/ql:/ql/data \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest

不过这个版本是老的，升级后就会管理页面进不去，网上找的什么cnd试了都不行，挂梯子也不行，但是又想要用到新版，那只需要到package发布那里找到最新的，比如我是arm64的docker pull ghcr.io/whyour/qinglong:develop@sha256:f9d4b17a1f774068aa4bbb1d3ed71c9c4a162e7959066463f8c3bc0956b8dec9，去掉docker pull 保留后面的，用这个替换掉上面的最后一行whyour/qinglong:latest，完整的就是
docker run -dit \
  -v $PWD/ql:/ql/data \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  ghcr.io/whyour/qinglong:develop@sha256:f9d4b17a1f774068aa4bbb1d3ed71c9c4a162e7959066463f8c3bc0956b8dec9
这样安装的就是最新版，装完也不会登录不上去了，之前一直不知道，可能大多数大佬早就知道，希望有同样的问题还不知道怎么解决的借鉴一下。

**Comment by lun9090** [comment]
试试docker pull ghcr.io/whyour/qinglong:develop
