### ISSUE TITLE
git clone 失败

### ISSUE THREAD

**Issue by wudongdefeng** [whyour/qinglong#157]
github屏蔽了git clone https://gitee.com的功能吗

**Comment by whyour** [comment]
> github屏蔽了git clone [https://gitee.com的功能吗](https://gitee.com%E7%9A%84%E5%8A%9F%E8%83%BD%E5%90%97)

可能是你的网络问题，docker启动改成host模式试试

**Comment by wudongdefeng** [comment]
![image](https://user-images.githubusercontent.com/32961310/118938000-b5ae8d00-b980-11eb-9e2c-367ff6651522.png)
青龙大佬我说的是这个

**Comment by whyour** [comment]
> ![image](https://user-images.githubusercontent.com/32961310/118938000-b5ae8d00-b980-11eb-9e2c-367ff6651522.png)
> 青龙大佬我说的是这个

不知道，我也在尝试，不知道这是咋了

**Comment by whyour** [comment]
@biewenwoshishui021 我只能说你试试了，我没有设备，有问题来提bug
