### ISSUE TITLE
【20220830】再次测试-armv7部署最新版本报错

### ISSUE THREAD

**Issue by lun9090** [whyour/qinglong#1574]
- 系统相关信息
Debian GNU/Linux 10 (buster) with Linux 5.9.0-rc7-aml-s812
cpu：ARMv7 Processor rev 1 (v7l)

- 容器拉取命令
docker pull ghcr.io/whyour/qinglong:develop@sha256:c6cc827be1a30ab6918b918de83bd7a1341823de23c5cdfd1f13479fc17dac41

- 容器启动命令：
docker run -dit \
-v $PWD/ql/config:/ql/config \
-v $PWD/ql/log:/ql/log \
-v $PWD/ql/db:/ql/db \
-p 5600:5600 \
-p 5700:5700 \
--name qinglong \
--hostname qinglong \
--restart always \
ghcr.io/whyour/qinglong@sha256:c6cc827be1a30ab6918b918de83bd7a1341823de23c5cdfd1f13479fc17dac41

- 容器运行日志：

> 复制一份 /ql/sample/config.sample.sh 为 /ql/data/config/config.sh，随后请按注释编辑你的配置文件：/ql/data/config/config.sh
> 
> '/ql/sample/config.sample.sh' -> '/ql/data/config/config.sh'
> 
> 检测到config配置目录下不存在env.sh，创建一个空文件用于初始化...
> 
> 
> 复制一份 /ql/sample/task.sample.sh 为 /ql/data/config/task_before.sh
> 
> '/ql/sample/task.sample.sh' -> '/ql/data/config/task_before.sh'
> 
> 复制一份 /ql/sample/task.sample.sh 为 /ql/data/config/task_after.sh
> 
> '/ql/sample/task.sample.sh' -> '/ql/data/config/task_after.sh'
> 
> 复制一份 /ql/sample/extra.sample.sh 为 /ql/data/config/extra.sh
> 
> '/ql/sample/extra.sample.sh' -> '/ql/data/config/extra.sh'
> 
> 复制一份 /ql/sample/auth.sample.json 为 /ql/data/config/auth.json
> 
> '/ql/sample/auth.sample.json' -> '/ql/data/config/auth.json'
> 
> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py
> 
> '/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'
> 
> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js
> 
> '/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
> 
> 复制一份 /ql/sample/notify.js 为 /ql/data/deps/sendNotify.js
> 
> '/ql/sample/notify.js' -> '/ql/data/deps/sendNotify.js'
> 
> 复制一份 /ql/sample/notify.py 为 /ql/data/deps/notify.py
> 
> '/ql/sample/notify.py' -> '/ql/data/deps/notify.py'
> 
> ======================1. 检测配置文件========================
> 
> '/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
> '/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
> ./docker/docker-entrypoint.sh: line 12:    38 Trace/breakpoint trap   (core dumped) pm2 l &> /dev/null
> 
> ======================2. 安装依赖========================
> 
> 检测到 /ql/data/scripts 的依赖包有变化，运行 npm install...
> 
> 
> 
> #
> # Fatal error in , line 0
> # unreachable code
> #
> #
> #
> #FailureMessage Object: 0xbed0d17c
> /ql/shell/share.sh: line 246:    52 Trace/breakpoint trap   (core dumped) pnpm install --loglevel error --production --registry=https://registry.npmmirror.com
> 
> 
> #
> # Fatal error in , line 0
> # unreachable code
> #
> #
> #
> #FailureMessage Object: 0xbeecf1ac
> /ql/shell/share.sh: line 246:    58 Trace/breakpoint trap   (core dumped) pnpm install --production --loglevel error
> 
> ======================3. 启动nginx========================
> 
> nginx启动成功...
> 
> ======================4. 启动面板监控========================
> 
> ./docker/docker-entrypoint.sh: line 24:    70 Trace/breakpoint trap   (core dumped) pm2 delete public &> /dev/null
> 
> 
> #
> # Fatal error in , line 0
> # unreachable code
> #
> #
> #
> #FailureMessage Object: 0xbeded12c
> ./docker/docker-entrypoint.sh: line 25:    82 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/public.js -n public --source-map-support --time
> 监控服务启动成功...
> 
> ======================5. 启动控制面板========================
> 
> ./docker/docker-entrypoint.sh: line 29:    93 Trace/breakpoint trap   (core dumped) pm2 delete panel &> /dev/null
> 
> 
> #
> # Fatal error in , line 0
> # unreachable code
> #
> #
> #
> #FailureMessage Object: 0xbe82a12c
> ./docker/docker-entrypoint.sh: line 30:   104 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/app.js -n panel --source-map-support --time
> 控制面板启动成功...
> 
> ======================6. 启动定时任务========================
> 
> ./docker/docker-entrypoint.sh: line 34:   115 Trace/breakpoint trap   (core dumped) pm2 delete schedule &> /dev/null
> 
> 
> #
> # Fatal error in , line 0
> # unreachable code
> #
> #
> #
> #FailureMessage Object: 0xbeb0012c
> ./docker/docker-entrypoint.sh: line 35:   126 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/schedule.js -n schedule --source-map-support --time
> 定时任务启动成功...
> 
> ======================8. 执行自定义脚本========================
> 
> 自定义脚本后台执行中...
> 
> ############################################################
> 
> 容器启动成功...
> 
> 请先访问5700端口，登录成功面板之后再执行添加定时任务...
> ############################################################
> 
> crond[138]: crond (busybox 1.35.0) started, log level 8

**Comment by lun9090** [comment]
正在尝试https://github.com/whyour/qinglong/pkgs/container/qinglong/34591556?tag=latest这个页面
- 拉取镜像
docker pull ghcr.io/whyour/qinglong:2.13.8@sha256:1b22e3587a9cb9650c55ebf0f0b261689338541e3105e83e4d2f4f53100c04a5

**Comment by lun9090** [comment]
【20220830】再次尝试

- 系统相关信息
Debian GNU/Linux 10 (buster) with Linux 5.9.0-rc7-aml-s812
cpu：ARMv7 Processor rev 1 (v7l)
- 容器启动命令
docker run -dit \
-p 15700:5700 \
-p 15600:5600 \
--name qinglongtest \
--hostname qinglongtest \
--restart unless-stopped \
ghcr.dockerproxy.com/whyour/qinglong:develop@sha256:c600c82cd48b903629fc4cf3d752bccc487dd35ac0c143e7dfad66e1b2799dfd

报错：

> 复制一份 /ql/sample/notify.js 为 /ql/data/deps/sendNotify.js
,
,'/ql/sample/notify.js' -> '/ql/data/deps/sendNotify.js'
,
,复制一份 /ql/sample/notify.py 为 /ql/data/deps/notify.py
,
,'/ql/sample/notify.py' -> '/ql/data/deps/notify.py'
,
,======================1. 检测配置文件========================
,
,'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
,'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
,./docker/docker-entrypoint.sh: line 12:    37 Trace/breakpoint trap   (core dumped) pm2 l &> /dev/null
,
,======================2. 安装依赖========================
,
,检测到 /ql/data/scripts 的依赖包有变化，运行 npm install...
,
,
,
,#
,# Fatal error in , line 0
,# unreachable code
,#
,#
,#
,#FailureMessage Object: 0xbeacd0e4
,/ql/shell/share.sh: line 246:    51 Trace/breakpoint trap   (core dumped) pnpm install --loglevel error --production --registry=https://registry.npmmirror.com
,
,
,#
,# Fatal error in , line 0
,# unreachable code
,#
,#
,#
,#FailureMessage Object: 0xbea38114
,/ql/shell/share.sh: line 246:    57 Trace/breakpoint trap   (core dumped) pnpm install --production --loglevel error
,
,======================3. 启动nginx========================
,
,nginx启动成功...
,
,======================4. 启动面板监控========================
,
,./docker/docker-entrypoint.sh: line 24:    68 Trace/breakpoint trap   (core dumped) pm2 delete public &> /dev/null
,
,
,#
,# Fatal error in , line 0
,# unreachable code
,#
,#
,#
,#FailureMessage Object: 0xbe8cb094
,./docker/docker-entrypoint.sh: line 25:    81 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/public.js -n public --source-map-support --time
,监控服务启动成功...
,
,======================5. 启动控制面板========================
,
,./docker/docker-entrypoint.sh: line 29:    92 Trace/breakpoint trap   (core dumped) pm2 delete panel &> /dev/null
,
,
,#
,# Fatal error in , line 0
,# unreachable code
,#
,#
,#
,#FailureMessage Object: 0xbeaab094
,./docker/docker-entrypoint.sh: line 30:   103 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/app.js -n panel --source-map-support --time
,控制面板启动成功...
,
,======================6. 启动定时任务========================
,
,./docker/docker-entrypoint.sh: line 34:   114 Trace/breakpoint trap   (core dumped) pm2 delete schedule &> /dev/null
,
,
,#
,# Fatal error in , line 0
,# unreachable code
,#
,#
,#
,#FailureMessage Object: 0xbeb69094
,./docker/docker-entrypoint.sh: line 35:   125 Trace/breakpoint trap   (core dumped) pm2 start $dir_static/build/schedule.js -n schedule --source-map-support --time
,定时任务启动成功...
,
,======================8. 执行自定义脚本========================
,
,自定义脚本后台执行中...
,
,############################################################
,
,容器启动成功...
,
,请先访问5700端口，登录成功面板之后再执行添加定时任务...
,############################################################
,
,crond[137]: crond (busybox 1.35.0) started, log level 8
,

**Comment by whyour** [comment]
@lun9090 什么机器

**Comment by lun9090** [comment]
玩客云，我找到了正式版本，看了下dockerfile，根据那个修改了下，正在重建，我看看情况

**Comment by whyour** [comment]
@lun9090 https://github.com/whyour/qinglong/issues/897

**Comment by lun9090** [comment]
嗯嗯 我改做了，改成
`FROM node:lts-alpine3.12`
应该是FROM node:16.13.0-alpine3.12
正在测试，如果没问题，我提交dockfile文件名为dockerfile_arm32v7吧

**Comment by lun9090** [comment]
为了这个项目可持续发展下去，避免被有心人利用，建议你做好声明，可以把python那一快儿拓展下，可以跑python项目包之类的，这样，能应用的范围就大很多了，后面就能可持续了

**Comment by lun9090** [comment]
解决方案：
- 构建命令
`docker build -t whyour/qinglong:arm32v7 ./`
- 测试启动命令
最新版：
```
docker run -dit \
-p 15700:5700 \
-p 15600:5600 \
--name qinglongtest \
--hostname qinglongtest \
--restart unless-stopped \
whyour/qinglong:arm32v7
```

结果成功！

**Comment by creazy412** [comment]
留给有缘人，我的树莓派3B+解决方案是：
1. 创建容器的时候加了 --privileged=true 参数
2. 容器内执行：ql -l check

**Comment by cyk2018** [comment]
> 留给有缘人，我的树莓派3B+解决方案是：
> 
>     1. 创建容器的时候加了 --privileged=true 参数
> 
>     2. 容器内执行：ql -l check

太牛了哥
