### ISSUE TITLE
以订阅的方式添加的定时任务脚本只会放在一个根目录下

### ISSUE THREAD

**Issue by alonelycat** [whyour/qinglong#1575]
以订阅的方式添加定时任务脚本，原代码仓中的各个目录下的脚本都只会被放在根目录下，部分脚本引用不到其他目录下的脚本导致执行失败，不知道是不是我订阅配置的问题

**Comment by cddjr** [comment]
显然是你的问题，其它目录的脚本你得配置仓库的“依赖”。。

**Comment by alonelycat** [comment]
> 显然是你的问题，其它目录的脚本你得配置仓库的“依赖”。。
感谢，正解问题已解决
