### ISSUE TITLE
青龙面板怎么设置成域名登录，就像xui那样设置个路径，端口

### ISSUE THREAD

**Issue by 286700234** [whyour/qinglong#1576]
青龙面板怎么设置成域名登录，就像xui那样设置个路径，端口

**Comment by Mpk2022** [comment]
我试了反代，貌似不行

**Comment by sapolang** [comment]
我试了反代，貌似不行

**Comment by SilveryX** [comment]
Nginx可以反代，我一直使用域名登录的，不会写conf文档的话可以用Nginx Proxy Manager

**Comment by sapolang** [comment]
> 

域名后面的后缀来做反代不行

**Comment by yijiangchengming** [comment]
青龙docker已经具有nginx代理，但是仍然可以为其设置一个前置代理。直接监听5700端口即可。

**Comment by sapolang** [comment]
> 青龙docker已经具有nginx代理，但是仍然可以为其设置一个前置代理。直接监听5700端口即可。

nginx配置前缀不行， 里面的静态文件地址写死了

**Comment by yijiangchengming** [comment]
> 
![image](https://user-images.githubusercontent.com/30022966/187033290-cf4c71f0-a147-4c43-b30a-0b52eb416f5a.png)
这是可以的，在青龙前再部署一个代理。
浏览器->nginx (https:443)->docker:5700 [docker nginx:5700->青龙静态文件和后端]
前置部署代理nginx负责路由到青龙容器。
如果你不想再部署前置代理，可以将容器内/etc/nginx/conf.d目录映射到本地文件夹或卷以保持数据持久化，然后修改里面的front.conf文件。或者你可以fork这个项目，然后自行构建自定义镜像。也可以基于青龙镜像然后使用Dockfile构建新镜像。

**Comment by dillion007** [comment]
设置了nginx反向代理之后，登录页显示不出来，控制台报错如下：
![image](https://user-images.githubusercontent.com/16933905/190396778-9b65cdb0-52a6-4eb0-9a45-010f43e855ef.png)

nginx配置如下

location / {
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_redirect off;
proxy_pass http://127.0.0.1:5700/;
}
