### ISSUE TITLE
请问如何完全的删除一个仓库

### ISSUE THREAD

**Issue by xia1001** [whyour/qinglong#1578]
包括定时任务和本地脚本

**Comment by cddjr** [comment]
我的笨办法是

1. 首先删除这个仓库的订阅任务
2. 在定时任务页的右上角有一个搜索功能，直接搜仓库名
如无意外都是这个仓库的，只需要全选然后删除即可(自己看清楚是不是)
3. rm -rf /ql/data/repo/仓库名
_v2.12之前的旧版青龙是rm -rf /ql/repo/仓库名_

**Comment by xia1001** [comment]
> 

这是手动方法，一次选中好像只能选一页，太慢了，有时候拉取仓库的时候它出错可以直接删除全部脚本，应该有命令自动完成

**Comment by cddjr** [comment]
1、关于全选是一页还是所有页我没去验证，我印象中是所有页。 另外右下角分页大小那可以改成1000每页，应该足够减少手动的工作量了。
2、没有删仓库的命令
