### ISSUE TITLE
执行自动拉库任务导致好多任务被删除

### ISSUE THREAD

**Issue by Peter-90** [whyour/qinglong#1579]
青龙面板版本：v2.13.8
docker版本：
![iShot_2022-08-16_10 13 34](https://user-images.githubusercontent.com/22003137/184783927-6226c7fb-d80b-474e-947c-9363ce3f6de4.png)
 使用改命令安装的青龙：
docker run -dit \
    -v $PWD/ql/config:/ql/config \
    -v $PWD/ql/log:/ql/log \
    -v $PWD/ql/db:/ql/db \
    -p 5700:5700 \
    --name qinglong \
    --hostname qinglong \
    --restart always \
    whyour/qinglong:latest
跑在本机的docker容器里面
没有使用docker-compose，也没有切docker的源地址，只用了上述命令安装之后接在docker应用的里面运行的，docker跑在本地自己的电脑上

### 下面是我用到的几个库和拉库命令：
![iShot_2022-08-16_10 04 57](https://user-images.githubusercontent.com/22003137/184783023-3f472592-fd5f-40a3-889a-af4464311614.png)
![iShot_2022-08-16_09 57 10](https://user-images.githubusercontent.com/22003137/184783026-b964f783-49d0-45ab-8a66-4fff273c8fbb.png)

**从昨天半夜一点执行拉kr库任务的时候bark从1点到2点收到很多类似这样的提示信息：**
![IMG_7813](https://user-images.githubusercontent.com/22003137/184783139-7530ab4c-9a97-4763-9781-7afe6d22e0f4.PNG)
![IMG_6F77071C3900-1](https://user-images.githubusercontent.com/22003137/184783151-8ce82840-b864-4428-bd9c-a3213a23d70a.jpeg)
### 只有少数几个添加任务的推送：
![IMG_0ED68DA8D423-1](https://user-images.githubusercontent.com/22003137/184783264-d2cc8cf6-7a2d-43aa-a1d9-1dba00d62f93.jpeg)

该问题导致少了很多定时任务，最后只要十几个任务在跑了，目前原因尚未找到，麻烦大佬能看一下吗？确认是一下是bug还是我个人的配置原因

**Comment by xia1001** [comment]
一样，间歇性抽风全删，要么就给你来一堆重复任务

**Comment by hxchtiewei** [comment]
拉库不是在“订阅管理”里操作吗？不是在定时任务里新建。

**Comment by cddjr** [comment]
虽然不知原因，但是看你docker参数估计还是老教程提供的，只适合青龙2.12之前的老版本。
建议删掉容器，全部重来。

以下命令会在当前目录保存青龙的脚本、仓库、参数，所以确保当前目录可写、空间足够！
```
docker run -dit \
  -v $PWD/ql:/ql/data \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest
```

另外就是仓库的订阅不要在定时任务中进行，改为去订阅管理。

**Comment by showmexlq** [comment]
> 虽然不知原因，但是看你docker参数估计还是老教程提供的，只适合青龙2.12之前的老版本。 建议删掉容器，全部重来。
> 
> 以下命令会在当前目录保存青龙的脚本、仓库、参数，所以确保当前目录可写、空间足够！
> 
> ```
> docker run -dit \
>   -v $PWD/ql:/ql/data \
>   -p 5700:5700 \
>   --name qinglong \
>   --hostname qinglong \
>   --restart unless-stopped \
>   whyour/qinglong:latest
> ```
> 
> 另外就是仓库的订阅不要在定时任务中进行，改为去订阅管理。

订阅管理还是一样的,每次都要重复删除再新增(相当于重新拉库)导致我的禁用任务不生效

**Comment by cddjr** [comment]
> 订阅管理还是一样的,每次都要重复删除再新增(相当于重新拉库)导致我的禁用任务不生效

把订阅的log发出来，或许能看到错误提示
