### ISSUE TITLE
定时任务跑不起来怎么办

### ISSUE THREAD

**Issue by zhoutank** [whyour/qinglong#158]
运行定时任务会显示
timeout: failed to run command ‘export_sharecodes’: No such file or directory
timeout: failed to run command ‘js’: No such file or directory

**Comment by whyour** [comment]
> 运行定时任务会显示
> timeout: failed to run command ‘export_sharecodes’: No such file or directory
> timeout: failed to run command ‘js’: No such file or directory

删除db目录下的 crontab.db 重启容器
