### ISSUE TITLE
定时任务没有执行, 手动可以执行

### ISSUE THREAD

**Issue by FairyWorld** [whyour/qinglong#1581]
15号进行定时配置，理论上16号，18号...，隔两天执行一次。
16号定时任务没有执行，也没有日志, 但是下次运行时间的那一栏的日期是根据定时规则变成18号了。任务手动是可以执行成功。不知道哪里出了问题

![image](https://user-images.githubusercontent.com/32956212/184888143-325e8daf-80d1-49de-9d87-1930ce8f79ac.png)

**Comment by FairyWorld** [comment]
> 15号进行定时配置，理论上16号，18号...，隔两天执行一次。 16号定时任务没有执行，也没有日志, 但是下次运行时间的那一栏的日期是根据定时规则变成18号了。任务手动是可以执行成功。不知道哪里出了问题
> 
> ![image](https://user-images.githubusercontent.com/32956212/184888143-325e8daf-80d1-49de-9d87-1930ce8f79ac.png)

0 1 1/2 * *, 这种格式是不是不支持, 0 1 1 * *这种格式是正常的，也有可能是我重启了一次就好了

**Comment by FairyWorld** [comment]
> 0 1 1/2 * *

经过多次测试，0 1 1/2 * *这种格式是不支持的

**Comment by cddjr** [comment]
格式是否支持取决于你系统的crontab命令。如果版本较老的话可能还会报错(青龙应该会有一个不起眼的小错误提示告知)

另外可以尝试添加“秒”的单位，涉及到秒的定时用的另一套实现，不依赖系统的cron了

**Comment by FairyWorld** [comment]
> 也有可能是系统的cron服务不支持？可以尝试用crontab -e手动输入这个时间规则看是否会出错
> 
> 或者尝试添加“秒”的单位，涉及到秒的定时用的另一套方案实现，不依赖系统的cron了

确实是系统不支持导致的, 系统支持"0 */2 * * *"但不支持"0 1/2 * * *", 目前可以通过你说的加上"秒"解决或者改为"0 1,3,5 * * *"解决。还想请教下linux怎么升级crontab服务或者怎么配置使系统支持这种特殊格式, 我在google搜了一圈没有搜到不支持特殊cron的更新升级linux的解决方案

**Comment by cddjr** [comment]
> > 也有可能是系统的cron服务不支持？可以尝试用crontab -e手动输入这个时间规则看是否会出错
> > 或者尝试添加“秒”的单位，涉及到秒的定时用的另一套方案实现，不依赖系统的cron了
> 
> 确实是系统不支持导致的, 系统支持"0 */2 * * *"但不支持"0 1/2 * * *", 目前可以通过你说的加上"秒"解决或者改为"0 1,3,5 * * *"解决。还想请教下linux怎么升级crontab服务或者怎么配置使系统支持这种特殊格式, 我在google搜了一圈没有搜到不支持特殊cron的更新升级linux的解决方案

没试过呢，一般用docker就能解决掉这些奇奇怪怪的依赖问题了。
