### ISSUE TITLE
定时任务运行一遍后就自动禁用了

### ISSUE THREAD

**Issue by wolfcdd** [whyour/qinglong#1583]
部分定时任务运行一遍后就自动禁用了，即使手动启用，并手动运行一遍后一样就禁用了，想明白是什么原因导致的。

**Comment by cddjr** [comment]
说明你的定时任务里面有检测cookie的脚本，一旦失效就会禁用。 你可以关闭这个issue了

**Comment by w-jx** [comment]
> 部分定时任务运行一遍后就自动禁用了，即使手动启用，并手动运行一遍后一样就禁用了，想明白是什么原因导致的。

想问下你用的库是什么?有地址吗?
