### ISSUE TITLE
Debian11拉取latest镜像，部署的面板是2.10.13版本的

### ISSUE THREAD

**Issue by Wyatt323** [whyour/qinglong#1584]

**Comment by cddjr** [comment]
可能是索引或镜像加速配置有误？ 所以拉不到最新的？ 


索引服务器地址 | https://index.docker.io/v1/
-- | --
镜像加速器 | https://mirror.baidubce.com/, https://hub-mirror.c.163.com/

**Comment by Wyatt323** [comment]
用加速和不用都试过了，拉到的都是2.10.13，同时也没办法更新，在群晖里面拉取的镜像也是这样

**Comment by shengmean** [comment]
拉取后，tag不一样，images ID是一样的，群晖环境如此。今天拉的。

**Comment by Wyatt323** [comment]
目前已经解决，是阿里云镜像加速的问题，去掉镜像加速就是最新版本了
