### ISSUE TITLE
定时任务不能正确执行

### ISSUE THREAD

**Issue by MaChao-Code** [whyour/qinglong#1586]
同一个脚本，例如test.py，当设定一个定时任务0 * * * * * ，命令是task test.py，如果没错的话应该是每分钟0秒一直运行下去。此时，想再设置一个定时任务，0/10 * * * * *，命令同样是task test.py。此时，之前设置的定时任务类似于被覆盖掉了。只会每10秒运行一次，每分钟的就不正常运行了。不知道是我使用的问题的，还是原因，望解答！谢谢！

**Comment by MaChao-Code** [comment]
我现在的需求是同一个脚本，需要设置3种不同的运行规则。工作日9-15点每10秒运行一次，工作日0-9，15-23点每10分钟运行一次，周末每10分钟运行一次。最后设置的总是会影响前面的设定的定时任务。

**Comment by Vason-Hsueh** [comment]
有没有一种可能你可以copy三份同样的脚本改成不同的名字

**Comment by cddjr** [comment]
脚本相同的情况下，状态、日志都可能会被覆盖，让你误以为没有执行，实际都是按时执行了

建议重命名脚本，这样就肯定没问题了
