### ISSUE TITLE
占用cpu的程序

### ISSUE THREAD

**Issue by shenmadouyaowen** [whyour/qinglong#1588]
这个运行的是什么?一直在不断的重复运行占用cpu
node /root/.local/share/pnpm/global/5/.pnpm/pm2@5.2.0/node_modules/pm2/lib/ProcessContainerFork.js

![image](https://user-images.githubusercontent.com/12426724/186101590-efc234bb-b246-4e8f-9650-000b6103b4b4.png)

**Comment by JuvenileQ** [comment]
中挖矿病毒了，我也中毒了，在使用docker安装完，阿里云安全预警，给我提示。你可以根剧这个脚本检查一下你的服务器
![image](https://user-images.githubusercontent.com/39209399/188878999-936527bf-9451-4cbd-aa5a-d020ab74a6d5.png)

**Comment by shenmadouyaowen** [comment]
> 中挖矿病毒了，我也中毒了，在使用docker安装完，阿里云安全预警，给我提示。你可以根剧这个脚本检查一下你的服务器 ![image](https://user-images.githubusercontent.com/39209399/188878999-936527bf-9451-4cbd-aa5a-d020ab74a6d5.png)

没有这些,青龙版本升级13.8 就没有出现cpu经常占用过多问题了

**Comment by JuvenileQ** [comment]
> > 你可以在这款游戏中完成了，我也中毒了，使用docker安装阿里云安全预警，给我安装提示。![图片](https://user-images.githubusercontent.com/39209399/188878999-936527bf-9451-4cbd-aa5a-d020ab74a6d5.png)
> 
> 没有这些,青龙版本升级13.8就没有出现cpu频繁占用过多问题了

我昨天（2022年9月7日 下午）安装的是最新版，是有病毒的。问了一个安全的朋友，说 青龙好像本身就自带挖矿

**Comment by shenmadouyaowen** [comment]
> > > 你可以在这款游戏中完成了，我也中毒了，使用docker安装阿里云安全预警，给我安装提示。![图片](https://user-images.githubusercontent.com/39209399/188878999-936527bf-9451-4cbd-aa5a-d020ab74a6d5.png)
> > 
> > 
> > 没有这些,青龙版本升级13.8就没有出现cpu频繁占用过多问题了
> 
> 我昨天（2022年9月7日 下午）安装的是最新版，是有病毒的。问了一个安全的朋友，说 青龙好像本身就自带挖矿
你运行了什么脚本?把所有脚本都暂停,然后去top看看还有没有
