### ISSUE TITLE
请问看不到内部文件是怎么回事呢

### ISSUE THREAD

**Issue by lfscqk67** [whyour/qinglong#1589]
![image](https://user-images.githubusercontent.com/37235589/186441316-9cf1fc16-b5bd-44d4-a064-6940d1a74905.png)

**Comment by rnadow** [comment]
`ocker exec -it qinglong bash`

**Comment by lfscqk67** [comment]
> `ocker exec -it qinglong bash`

没看明白

**Comment by cc9014** [comment]
可能没映射成功。楼上的意思是让你进到容器内部看。
`docker exec -it qinglong bash`

**Comment by rnadow** [comment]
> 

打错命令了，少了个d，docker。
就是进docker里面看，外面是真机，具体我也不懂，命令就是那个
