### ISSUE TITLE
容器一直重启

### ISSUE THREAD

**Issue by uesrnameisnull** [whyour/qinglong#159]
![截图](https://user-images.githubusercontent.com/33957547/118932089-374eec80-b97a-11eb-99e7-989ce6bd361f.png)

**Comment by whyour** [comment]
docker logs QL 看下日志

**Comment by whyour** [comment]
两个是不同的代码，你这是网络有问题，docker 容器启动改成host模式

**Comment by uesrnameisnull** [comment]
我找朋友借了一台服务器也测试了一下, 就是gitee的问题, gitee的通信不通, 从gitee上拉取任何代码都报错, 但是从github上就没问题

**Comment by whyour** [comment]
> 我找朋友借了一台服务器也测试了一下, 就是gitee的问题, gitee的通信不通, 从gitee上拉取任何代码都报错, 但是从github上就没问题

执行 docker exec -it qinglong ql update 试试

**Comment by uesrnameisnull** [comment]
> > 我找朋友借了一台服务器也测试了一下, 就是gitee的问题, gitee的通信不通, 从gitee上拉取任何代码都报错, 但是从github上就没问题
> 
> 执行 docker exec -it qinglong ql update 试试

一样的报错

**Comment by whyour** [comment]
> > > 我找朋友借了一台服务器也测试了一下, 就是gitee的问题, gitee的通信不通, 从gitee上拉取任何代码都报错, 但是从github上就没问题
> > 
> > 
> > 执行 docker exec -it qinglong ql update 试试
> 
> 一样的报错

多执行两次，已经改成github上的了

**Comment by uesrnameisnull** [comment]
> > > > 我找朋友借了一台服务器也测试了一下, 就是gitee的问题, gitee的通信不通, 从gitee上拉取任何代码都报错, 但是从github上就没问题
> > > 
> > > 
> > > 执行 docker exec -it qinglong ql update 试试
> > 
> > 
> > 一样的报错
> 
> 多执行两次，已经改成github上的了

完美解决
