### ISSUE TITLE
钉钉通知设置问题

### ISSUE THREAD

**Issue by miaoyanginfo** [whyour/qinglong#1592]
请教一下，我已经配置了钉钉机器人，也能收到测试消息。但是任务执行完之后收不到推送消息，请问题一下还需要在哪里进行设置？
另外如何指定某条任务发送通知？

**Comment by cddjr** [comment]
任务有没有通知取决于这个任务脚本自身有没有实现这个功能，或者说任务脚本自己实现了一套通知推送需要单独配置参数。
具体你得看脚本作者有没有提供说明。

**Comment by miaoyanginfo** [comment]
了解了，感谢。我看下脚本代码。

**Comment by W1ndys** [comment]
@cddjr  你好，请教一下，如何实现自己写的Python脚本可以调用青龙推送钉钉消息，我遇到了和楼主一样的问题
