### ISSUE TITLE
更新后打不开了

### ISSUE THREAD

**Issue by rnadow** [whyour/qinglong#1595]
首先用命令更新`docker pull whyour/qinglong:latest`，提示`latest: Pulling from whyour/qinglong
Digest: sha256:9c3136f2f0f45a009dab06ec56530bc6595570454e20a068827a22e6caf37ffd
Status: Image is up to date for whyour/qinglong:latest
docker.io/whyour/qinglong:latest`，之后登录面板，发现有新版遂点击更新，之后提示错误，打不开，用`ql check`检查，提示`
npm notice
npm notice New minor version of npm available! 8.13.2 -> 8.18.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.18.0
npm notice Run npm install -g npm@8.18.0 to update!
npm notice

`

**Comment by rnadow** [comment]
> 首先用命令更新`docker pull whyour/qinglong:latest`，提示`latest: Pulling from whyour/qinglong Digest: sha256:9c3136f2f0f45a009dab06ec56530bc6595570454e20a068827a22e6caf37ffd Status: Image is up to date for whyour/qinglong:latest docker.io/whyour/qinglong:latest`，之后登录面板，发现有新版遂点击更新，之后提示错误，打不开，用`ql check`检查，提示` npm notice npm notice New minor version of npm available! 8.13.2 -> 8.18.0 npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.18.0 npm notice Run npm install -g npm@8.18.0 to update! npm notice
> 
> `

这不算问题吗，怎么关闭了

**Comment by whyour** [comment]
> > 首先用命令更新`docker pull whyour/qinglong:latest`，提示`latest: Pulling from whyour/qinglong Digest: sha256:9c3136f2f0f45a009dab06ec56530bc6595570454e20a068827a22e6caf37ffd Status: Image is up to date for whyour/qinglong:latest docker.io/whyour/qinglong:latest`，之后登录面板，发现有新版遂点击更新，之后提示错误，打不开，用`ql check`检查，提示` npm notice npm notice New minor version of npm available! 8.13.2 -> 8.18.0 npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.18.0 npm notice Run npm install -g npm@8.18.0 to update! npm notice
> 
> > 
> 
> > `
> 
> 
> 
> 这不算问题吗，怎么关闭了

这有说哪错了？
