### ISSUE TITLE
小白求教个问题，现在是V2.13.8，定时任务不能推送通知，求教

### ISSUE THREAD

**Issue by taoqiko** [whyour/qinglong#1602]
小白求教个问题，现在是V2.13.8，使用的bark通知，在设置页面保存了bark通知之后，手机会收到青龙的测试通知，但是定时任务完成没有通知，不知道是我设置问题，还是哪里需要修改的

**Comment by Hxina** [comment]
config.sh里配置参数填上，不嫌麻烦通知脚本里面的也全填上。

**Comment by taoqiko** [comment]
> config.sh里配置参数填上，不嫌麻烦通知脚本里面的也全填上。

就是都填了，config，还有系统设置，我能看到的地方，都设置了。就是没见通知，所以我才纳闷的，就是不知道哪里出错了。

**Comment by Hxina** [comment]
看看是不是脚本的问题，有些脚本默认关闭通知需要自己修改打开通知，有些脚本是没有通知的。

**Comment by cddjr** [comment]
通知是由脚本自己主动发送的，青龙不会推脚本执行通知

**Comment by xuexijiaoben** [comment]
> 看看是不是脚本的问题，有些脚本默认关闭通知需要自己修改打开通知，有些脚本是没有通知的。

请问大佬，我在脚本管理里，notify.py sendnotify.js，这两个的push+里都配好了TOKEN，还是接收不到通知，比如
jd_pet.js里有以下语句，
const $ = new Env('东东萌宠助力池版');
......
let cookiesArr = [], cookie = '', jdPetShareArr = [], isBox = false, allMessage = '';
let message = '', subTitle = '', option = {};
let jdNotify = false; //是否关闭通知，false打开通知推送，true关闭通知推送
........
let notify = $.isNode() ? require('./sendNotify') : '';
.......
let WP_APP_TOKEN_ONE = "";
if ($.isNode()) {
    if (process.env.WP_APP_TOKEN_ONE) {
        WP_APP_TOKEN_ONE = process.env.WP_APP_TOKEN_ONE;
    }
}
if (WP_APP_TOKEN_ONE)
    console.log(`检测到已配置Wxpusher的Token，启用一对一推送...`);
else
    console.log(`检测到未配置Wxpusher的Token，禁用一对一推送...`);


请问如何具体设置才可以通知呀，主要需要js_pet和js_fruit通知
感谢！
