### ISSUE TITLE
2.13.9订阅管理的黑白名单问题

### ISSUE THREAD

**Issue by Peter-90** [whyour/qinglong#1603]
拉取命令如图：
![iShot_2022-09-01_13 50 14](https://user-images.githubusercontent.com/22003137/187841325-33a499cf-8640-41c9-97c6-9c296dd2956c.png)
拉取后还是有黑名单里面的东西，如图：
![iShot_2022-09-01_13 50 42](https://user-images.githubusercontent.com/22003137/187841398-a710c47a-4482-4c62-a116-54ce2fc2e919.png)
我测试过把sendNotify.js删除，加入黑名单，重新拉取后还是获取了这个文件

**Comment by whyour** [comment]
@Peter-90 黑名单意思是建不建任务，通知文件是默认的都会加，你可以在执行后空里填命令把那个文件删掉

**Comment by Peter-90** [comment]
@whyour 好的 明白了
