### ISSUE TITLE
Linux依赖安装失败

### ISSUE THREAD

**Issue by sanwecn** [whyour/qinglong#1604]
开始安装依赖 bizCode，开始时间 2022-09-01 16:47:43

fetch https://mirrors.aliyun.com/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]

依赖安装失败，结束时间 2022-09-01 16:48:05，耗时 21 秒

**Comment by cddjr** [comment]
无视，百度搜的教程不一定靠谱。

**Comment by DanielEcho** [comment]
-> 有些bizCode、bizMsg依赖安装不成功的，这些依赖就不存在，删除就好了。别被有些教程忽悠了
