### ISSUE TITLE
定时任务全没有了，只剩下更新面板 删除任务 和互助码了

### ISSUE THREAD

**Issue by zhoutank** [whyour/qinglong#161]
删除db目录下的 crontab.db ，所有的JD任务都没有了

**Comment by Acr05s** [comment]
这个就是记录任务的数据库，你为什么要删

**Comment by zhoutank** [comment]
> 这个就是记录任务的数据库，你为什么要删

因为我的js脚本一直无法跑起来

**Comment by whyour** [comment]
https://t.me/qiongqiya/78

看频道通知
