### ISSUE TITLE
v2.14.1 多级目录的定时任务访问报错(EISDIR: illegal operation on a directory, read)

### ISSUE THREAD

**Issue by We41w4e** [whyour/qinglong#1614]
这个问题在多个版本都是同样的问题
![image](https://user-images.githubusercontent.com/111553542/188345265-c118c673-cbc0-4ec6-b99f-53cc7fa96874.png)

**Comment by We41w4e** [comment]
点击任务名称访问脚本的时候，其实也存在同样的问题，是一并修复的吗

**Comment by cddjr** [comment]
其实这个错误就是因为访问脚本而触发的，因为路径不对导致读不出脚本。

> 点击任务名称访问脚本的时候，其实也存在同样的问题，是一并修复的吗

**Comment by We41w4e** [comment]
> 其实这个错误就是因为访问脚本而触发的，因为路径不对导致读不出脚本。
> 
> > 点击任务名称访问脚本的时候，其实也存在同样的问题，是一并修复的吗

好的，明白了，谢谢
