### ISSUE TITLE
可否支持再设置中自定义端口号

### ISSUE THREAD

**Issue by xmoxmo** [whyour/qinglong#1615]
每次更新后都要到
vi /ql/docker/front.conf

**Comment by xmoxmo** [comment]
每次更新后都要到
vi /ql/docker/front.conf
修改默认端口号为之前设置的端口号
如果设置端口转发的话，每次登录的ip都是本机地址

**Comment by whyour** [comment]
你的nginx转发的时候带上  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  就行了
