### ISSUE TITLE
2.14.1 str没有get方法

### ISSUE THREAD

**Issue by DanielEcho** [whyour/qinglong#1619]
无法运行带走这个函数的脚本。
另：cpu占用很高，重启后几乎百分百，过几分钟没有脚本运行也保持在30多以上

**Comment by cddjr** [comment]
重启后它会重新装一遍依赖，估计cpu在这里消耗了吧？

**Comment by XiaokangLi** [comment]
## 开始执行... 2022-09-12 22:15:39

===> 禁用重复任务开始 <===
加载推送功能中...

=== 你选择过滤的任务前缀为 ===
KingRan_KR
Traceback (most recent call last):
  File "/ql/data/scripts/KingRan_KR/jd_disable.py", line 192, in <module>
    filter_list, res_list = filter_res_sub(tasklist)
  File "/ql/data/scripts/KingRan_KR/jd_disable.py", line 70, in filter_res_sub
    if task.get("command").find(sub) == -1:
AttributeError: 'str' object has no attribute 'get'

## 执行结束... 2022-09-12 22:15:39 耗时 0 秒

**Comment by j-share** [comment]
> ## 开始执行... 2022-09-12 22:15:39
> ===> 禁用重复任务开始 <=== 加载推送功能中...
> 
> === 你选择过滤的任务前缀为 === KingRan_KR Traceback (most recent call last): File "/ql/data/scripts/KingRan_KR/jd_disable.py", line 192, in filter_list, res_list = filter_res_sub(tasklist) File "/ql/data/scripts/KingRan_KR/jd_disable.py", line 70, in filter_res_sub if task.get("command").find(sub) == -1: AttributeError: 'str' object has no attribute 'get'
> 
> ## 执行结束... 2022-09-12 22:15:39 耗时 0 秒

你好 这个问题最后解决了么

**Comment by whyour** [comment]
@j-share 脚本的错误找脚本

**Comment by cddjr** [comment]
似乎最近某个版本更新后，就会出这个AttributeError: 'str' object has no attribute 'get'错误了。

**Comment by cddjr** [comment]
> @j-share 脚本的错误找脚本

@whyour 
定位到问题点了，由于这个提交 102e447f785c35e95b97a94c52e884db377bd08c 导致青龙返回任务列表的json结构产生了变化，从而导致脚本在解析列表时出错。

之前列表是这样返回
https://github.com/whyour/qinglong/blob/28ea160004c4df8d59ed387720df916d37f38e6c/back/services/cron.ts#L166
现在是这样
https://github.com/whyour/qinglong/blob/6e56a55f6f627aaebb9df829189bf7f09e6dc56f/back/services/cron.ts#L289

这导致脚本需要的data数组被额外嵌套进了一个对象中

如果确定这是预期的格式，那就需要让脚本来主动兼容适配了
