### ISSUE TITLE
组间切换非常缓慢

### ISSUE THREAD

**Issue by oldye2020** [whyour/qinglong#1620]
### Clear and concise description of the problem

2.14.2最新版本，添加分组后，在分组间切换非常缓慢，通常加载好几秒才会出现分组的任务

### Suggested solution

希望能够实现分组间的切换无缝衔接

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by cddjr** [comment]
也许是分页太大了吧？ 试试看每页20以内
