### ISSUE TITLE
首页加载的时候访问服务器外资源并且点击搜索响应很慢

### ISSUE THREAD

**Issue by lun9090** [whyour/qinglong#1622]
### Qinglong version

develop

### Steps to reproduce

1. 输入网址
2. 输入用户名密码点击登陆
3. 加载很慢

### What is expected?

![image](https://user-images.githubusercontent.com/78783303/189824325-38c5a9f8-20ba-4f4b-8617-84b17b171089.png)
1. 更新后，系统访问比较慢，简单抓了个包没发现在访问这个地址，不知道是为啥
2. 点击搜索，并输入内容，响应非常慢。

### What is actually happening?

修复一下

**Comment by whyour** [comment]
@lun9090 复现步骤和预期结果和实际结果没关系
无关的自己关心就去搜索搜索

**Comment by lun9090** [comment]
刚才搜索了下，看了看，是一个前端的框架，虽然不大懂....
