### ISSUE TITLE
Slack webhook support

### ISSUE THREAD

**Issue by EINDEX** [whyour/qinglong#1623]
### Clear and concise description of the problem

希望有webhook支持

### Suggested solution

支持一下 slack webhook 作为通知方式，或者其他webhook通知方式

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
@EINDEX 能举个栗子吗

**Comment by EINDEX** [comment]
### Slack Webhook 支持
[见文档](https://api.slack.com/messaging/webhooks#posting_with_webhooks)

### 通用 Webhook 支持
支持可见下图，自己可以提供一个 webhook 连接和 request body teamplate 和 header，这样就可以快速支持大多数 webhook 了。
校验webhook有效的方式可以用 http response status: 20x 即可。

<img width="600" alt="image" src="https://user-images.githubusercontent.com/13883964/190059662-1c3b76ba-95e4-4b0d-94f1-cca027e111e8.png">
图片截取自 healthchecks.io
