### ISSUE TITLE
设置了nginx反向代理之后，登录页面空白

### ISSUE THREAD

**Issue by dillion007** [whyour/qinglong#1624]
### Qinglong version

2.14.0

### Steps to reproduce

1. docker安装青龙面板
docker run -dit \
-v $PWD/ql/config:/ql/config \
-v $PWD/ql/log:/ql/log \
-v $PWD/ql/db:/ql/db \
-p 5600:5600 \
--name qinglong \
--hostname qinglong \
--restart always \
whyour/qinglong:latest

2. 设置nginx代理
location / {
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_redirect off;
proxy_pass http://127.0.0.1:5600/;
}

3. 浏览器打开网页 http://域名:5600 可以正常访问
4. 浏览器打开网页 http://域名，页面空白，不显示登录框，截图如下 
![image](https://user-images.githubusercontent.com/16933905/190541324-c70adabb-971e-4ee0-be8c-abeac82e6f4c.png)

### What is expected?

显示登录页面，功能正常可用

### What is actually happening?

空白页面，控制台报错

**Comment by whyour** [comment]
你设置的nginx代理是你自己的？自己的nginx配置，完整的域名监听呢？
建议都用5700

**Comment by dillion007** [comment]
是自己的nginx代理，域名监听都配置好了，其他容器如protainer都可以代理成功
好的，我用5700试一下

**Comment by whyour** [comment]
> 是自己的nginx代理，域名监听都配置好了，其他容器如protainer都可以代理成功 好的，我用5700试一下

你这启动方式也有问题啊，参考项目readme

**Comment by dillion007** [comment]
> > 是自己的nginx代理，域名监听都配置好了，其他容器如protainer都可以代理成功 好的，我用5700试一下
> 
> 你这启动方式也有问题啊，参考项目readme

按照readme的方式启动了另一个容器
docker run -dit   -v $PWD/ql/data:/ql/data   -p 5700:5700   --name qinglong2   --hostname qinglong2   --restart unless-stopped   whyour/qinglong:latest

直接用域名加端口的方式可以访问到
![image](https://user-images.githubusercontent.com/16933905/190615295-c9f8a976-aa31-4b03-88b4-5e163d7a5eee.png)

设置了代理方式
![image](https://user-images.githubusercontent.com/16933905/190615701-70996021-ae03-4625-9eb3-ced91901db74.png)

用域名+path的方式还是不行，错误依旧
![image](https://user-images.githubusercontent.com/16933905/190615943-5c884743-178d-496f-9b59-0b48be33c596.png)

帮忙看看是哪里的问题

**Comment by whyour** [comment]
@dillion007 path本来就不支持啊，等支持吧

**Comment by shenzihang** [comment]
遇到了一样的问题，部分docker应用支持path二级路径反代，部分不支持.....想问一下楼主解决这个问题了吗？

**Comment by PDxtXHd** [comment]
@whyour 请问现在是否仍然未支持path？我尝试用path访问仍然是白屏
