### ISSUE TITLE
青龙任务列表的API改变了数据结构导致已有脚本不兼容

### ISSUE THREAD

**Issue by cddjr** [whyour/qinglong#1625]
### Qinglong version

2.13.9~2.14.3

### Steps to reproduce

第三方脚本通过青龙api请求任务列表

### What is expected?

{
    'code': 200,
    'data': [
       task ...
    ]
}

### What is actually happening?

{
    'code': 200,
    'data': {
        'data': [
            task ...
        ],
        'total': ...
    }
}

### Any additional comments?

由于这个提交 102e447f785c35e95b97a94c52e884db377bd08c 导致青龙返回任务列表的json结构产生了变化，从而导致脚本在解析列表时出错。 (详见 #1619 )

之前列表是这样返回
https://github.com/whyour/qinglong/blob/28ea160004c4df8d59ed387720df916d37f38e6c/back/services/cron.ts#L166
现在是这样
https://github.com/whyour/qinglong/blob/6e56a55f6f627aaebb9df829189bf7f09e6dc56f/back/services/cron.ts#L289

三方脚本需要的data数组被额外嵌套进了另一个data对象中

如果确定这是预期的格式，那就需要让脚本来主动兼容适配了

**Comment by whyour** [comment]
@cddjr 你是不是理解错方向了，导致脚本不兼容？那不得脚本更新吗

**Comment by cddjr** [comment]
> @cddjr 你是不是理解错方向了，导致脚本不兼容？那不得脚本更新吗

所以我在最后提出这种格式的调整是不是预期中的，如果是就让脚本适配！

**Comment by whyour** [comment]
@cddjr 不是预期的话total怎么返回呢

**Comment by cddjr** [comment]
嗯，既然是预期行为，那就只能让脚本维护者尽快适配了。 本议案关闭
