### ISSUE TITLE
定时任务正常运行 但是没有执行日志

### ISSUE THREAD

**Issue by hootinwang** [whyour/qinglong#1628]
### Qinglong version

2.14.4

### Steps to reproduce

![image](https://user-images.githubusercontent.com/41067842/191886127-fdc97b7a-6c4e-4974-8a63-3b763abc717d.png)

### What is expected?

能显示日志

### What is actually happening?

定时任务列表-点击进入任务详情-没有展示执行日志

### System Info

```shell
docker
image version: whyour/qinglong:2.14
```

**Comment by whyour** [comment]
你这任务没有最后运行时间，是刚建的？

**Comment by whyour** [comment]
脚本建议在脚本管理中添加，也就是 /ql/data/scripts 目录中。创建任务时可以直接使用相对目录，不包含 /ql/data/scripts
