### ISSUE TITLE
邮箱发送无法使用

### ISSUE THREAD

**Issue by lucc1832** [whyour/qinglong#1629]
### Qinglong version

2.14.4

### Steps to reproduce

设置完 无法保存显示connect ECONNREFUSED 127.0.0.1:587

### What is expected?

更新

### What is actually happening?

保存不了

**Comment by whyour** [comment]
具体是怎么设置的

**Comment by lucc1832** [comment]
1
***@***.***





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "whyour/qinglong"                                                                                    ***@***.***>;
发送时间: 2022年9月26日(星期一) 下午4:28
收件人: ***@***.***>;
抄送: ***@***.******@***.***>;
主题: Re: [whyour/qinglong] 邮箱发送无法使用 (Issue #1629)



具体是怎么设置的
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: <whyour qinglong="" issues="" 1629="" ***@***.***="">

***@***.******@***.******@***.***>

**Comment by liaoyuan18** [comment]
你是用的python脚本发送邮箱吗？
python调用发送邮箱他好像就没有写，我式自己写了python发送邮件的方法

**Comment by CMJNB** [comment]
![image](https://github.com/whyour/qinglong/assets/53365071/67028fa5-0c84-4c90-819d-68f9b99a9d4e)
这个邮箱通知是这样配置吗

**Comment by whyour** [comment]
@CMJNB emailService 填的是邮箱的类别， QQ 126 等等，不是 smtp 服务的地址，支持的邮箱看输入框下面的链接

**Comment by CMJNB** [comment]
> @CMJNB emailService 填的是邮箱的类别， QQ 126 等等，不是 smtp 服务的地址，支持的邮箱看输入框下面的链接

恩，谢谢
