### ISSUE TITLE
奇怪的问题 Argument list too long

### ISSUE THREAD

**Issue by Muqiqi** [whyour/qinglong#163]
这个到底该怎么解决 难道每天手动删一次日志吗 
![CWRB4P0N(W1@0AJ$HUR (YL](https://user-images.githubusercontent.com/26044865/118980889-56ff0880-b9ac-11eb-89c3-0b582c8a22aa.png)

**Comment by hnlymmx** [comment]
解决了吗？也遇到这个问题了。

**Comment by Muqiqi** [comment]
> 解决了吗？也遇到了这个问题。

手动删除logs内部分日志可以解决

**Comment by fzls** [comment]
试试这个方案
[解决 青龙面板中存放的cookie数目过多（如超过45）时，会报 Argument list too long 而无法正常执行部分脚本的问题](https://gist.github.com/fzls/14f8d1d3ebb2fef64750ad91d268e4f6)
