### ISSUE TITLE
用户名密码输入正确登录不上? 

### ISSUE THREAD

**Issue by Dev-Wiki** [whyour/qinglong#1631]
### Qinglong version

latest docker 镜像

### Steps to reproduce

打开登录界面输入正确的账号密码, 提示账号密码错误!

![image](https://user-images.githubusercontent.com/12946956/192106729-a94f3382-4418-4647-99f5-321172d08d1c.png)

### What is expected?

能正常登录

### What is actually happening?

无法登录!

### System Info

```shell
docker 镜像安装 威联通nas

version: '2'
services:
  web:
    image: whyour/qinglong:latest
    volumes:
      - ./data:/ql/data
    ports:
      - "0.0.0.0:2056:5700"
    restart: unless-stopped
```

**Comment by Dev-Wiki** [comment]
使用http 模拟请求 post 又是可以的, 但是在浏览器就是不行.

![image](https://user-images.githubusercontent.com/12946956/192107426-af970db5-f468-48d9-bdfb-29b2f915a42c.png)

**Comment by whyour** [comment]
@Dev-Wiki 大小写不看看？

**Comment by Dev-Wiki** [comment]
我眼瞎了 [手动捂脸]
