### ISSUE TITLE
为什么ql update失败

### ISSUE THREAD

**Issue by getr00t** [whyour/qinglong#1632]
### Clear and concise description of the problem

![image](https://user-images.githubusercontent.com/12257416/192140051-bfdc6ede-58ea-45b1-a395-3063a76dd695.png)

### Suggested solution

这是什么情况？被墙了吗?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
访问不了 github, 在 config.sh 里配置 ProxyUrl
