### ISSUE TITLE
日志管理报错

### ISSUE THREAD

**Issue by lun9090** [whyour/qinglong#1638]
### Qinglong version

2.14.5

### Steps to reproduce

重新docker构建最新版本容器
启动命令：
docker run -dit \
-v $PWD/ql/config:/ql/config \
-v $PWD/ql/log:/ql/log \
-v $PWD/ql/db:/ql/db \
-p 5600:5600 \
-p 5700:5700 \
--name qinglong \
--hostname qinglong \
--restart always \
whyour/qinglong:arm32v75
登陆青龙面板，点击日志管理

### What is expected?

修复bug

### What is actually happening?

提示ENOENT: no such file or directory, stat '/ql/data/log/ql/node_modules/deps'

### System Info

```shell
System:
    OS: Linux 5.9 Alpine Linux
    CPU: (4) arm ARMv7 Processor rev 1 (v7l)
    Memory: 30.24 MB / 989.28 MB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
```

**Comment by whyour** [comment]
@lun9090 你这构建容器的命令都错了，你这能创建出来容器？参考readme

**Comment by lun9090** [comment]
这是启动命令，构建的dockerfile在这里
[Dockerfile.zip](https://github.com/whyour/qinglong/files/9672599/Dockerfile.zip)

**Comment by lun9090** [comment]
是不是目录映射导致的问题

**Comment by whyour** [comment]
> 是不是目录映射导致的问题

我没有这个镜像啊，你这bug我不知道你什么意思

**Comment by lun9090** [comment]
镜像是我用dockerfile自己构建的

**Comment by whyour** [comment]
> 镜像是我用dockerfile自己构建的

你构建的报这个bug是什么意思，官方的不能用？

**Comment by lun9090** [comment]
我不知道最新的容器修复没修复玩客云的bug，之前不是不能用么，玩客云的系统得自己构建

**Comment by whyour** [comment]
> 我不知道最新的容器修复没修复玩客云的bug，之前不是不能用么，玩客云的系统得自己构建

<img width="998" alt="image" src="https://user-images.githubusercontent.com/22700758/192981299-b4407db0-20ad-413d-bc38-968a5999cda8.png">
上次不是回复你了吗？系统docker 的问题。不操作下？

**Comment by lun9090** [comment]
没注意，抱歉抱歉
