### ISSUE TITLE
task_before 无法获取命令参数

### ISSUE THREAD

**Issue by miniers** [whyour/qinglong#1640]
### Qinglong version

2.14.6

### Steps to reproduce

task_before.sh 中 无法获取 task命令传递的参数 $1

### What is expected?

可以正确获取参数

### What is actually happening?

$1参数为空

### Any additional comments?

大概看了下这个版本改动的代码，task.sh 中抽出了一个 handle_task_before 函数，task_before.sh是在该函数中执行的，但是在其他函数中，例如 run_normal 中 调用 handle_task_before时，并没有传递参数，导致 执行task_before.sh 也没有参数了
<img width="707" alt="image" src="https://user-images.githubusercontent.com/2039910/193180937-17db7274-0cb3-4f57-b645-2505b5958ef0.png">

**Comment by whyour** [comment]
2,14,7
