### ISSUE TITLE
青龙无法安装python3的pycryptodome依赖

### ISSUE THREAD

**Issue by yeli008** [whyour/qinglong#1645]
### Qinglong version

V2.14.7

### Steps to reproduce

![Snipaste_2022-10-07_11-36-28](https://user-images.githubusercontent.com/66049634/194462755-3220f3e6-095e-4239-8327-3285ae3bd58a.jpg)
请见附图。

### What is expected?

我要运行一个脚本必须要有这个依赖pycryptodome，想要安装。

### What is actually happening?

无法安装这个python3  的  pycryptodome依赖

**Comment by sdhzwc** [comment]
正常 这是由于apline简版系统导致 很多依赖也是无法下载 例如cx_oracle 我遇到的

**Comment by Timiyu** [comment]
![image](https://user-images.githubusercontent.com/17613068/194544305-f7fdbcfc-2800-4229-a380-78b8f07336c5.png)
尝试安装所有C编译环境吧，毕竟有些包是c写的，qinglong好像没有手动安装包的WEBUI方式，没法安装whl包

**Comment by whyour** [comment]
alpine-sdk
autoconf 
automake
libtool
gcc

linux 里把这几个依赖装上

**Comment by whyour** [comment]
gcc应该sdk会自动装，前四个应该就行了

**Comment by yeli008** [comment]
> alpine-sdk autoconf automake libtool gcc
> 
> linux 里把这几个依赖装上

大佬我装了你上面几个linux依赖后可以安装pycryptodome依赖了，但是python3的tools.aes_encrypt依赖装不了。

**Comment by yeli008** [comment]
tools.aes_encrypt

**Comment by 2331892928** [comment]
无法构建，你的库不支持python3.10

**Comment by whyour** [comment]
canvas 安装失败，linux 添加如下依赖

build-base
g++
cairo-dev
jpeg-dev
pango-dev
giflib-dev

**Comment by whyour** [comment]
cryptg 安装失败，linux 添加如下依赖
```
rust
cargo
```

**Comment by demostars** [comment]
@whyour  感谢作者，我遇到类似的问题，无法pip install ddddocr。

原因如下：
`The conflict is caused by:
    ddddocr 1.4.7 depends on onnxruntime
    ddddocr 1.4.6 depends on onnxruntime
    ddddocr 1.4.5 depends on onnxruntime
    ddddocr 1.0.6 depends on onnxruntime

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
root@qinglong:/ql/data/scripts/gqbre_emby-server-checkin $pip install onnxruntime
Looking in indexes: https://pypi.doubanio.com/simple/
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime`

我尝试fork 修改dockerfile 为基于python-slim的版本（这个版本可以安装），暂时没有成功发布到DockerHub上，因此真诚建议作者是否可以新建一个 基于 python-slim的版本的镜像，用于性能更好的，不那么在乎镜像体积的设备使用。以下是我修改的代码，仅供参考。
`#  修改记录：
# 将 python:3.10-alpine 替换成 python:3.10-slim
# 将 apk 命令替换成 apt-get
# 尚未替换国内镜像

FROM python:3.10-slim as builder 
COPY package.json .npmrc pnpm-lock.yaml /tmp/build/
RUN set -x \
    && apt-get update \
    && apt-get install -y --no-install-recommends nodejs npm git \
    && npm i -g pnpm \
    && cd /tmp/build \
    && pnpm install --prod

FROM python:3.10-slim

ARG QL_MAINTAINER="whyour"
LABEL maintainer="${QL_MAINTAINER}"
ARG QL_URL=https://github.com/${QL_MAINTAINER}/qinglong.git
ARG QL_BRANCH=develop

ENV PNPM_HOME=/root/.local/share/pnpm \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules:$PNPM_HOME \
    NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules \
    LANG=zh_CN.UTF-8 \
    SHELL=/bin/bash \
    PS1="\u@\h:\w \$ " \
    QL_DIR=/ql \
    QL_BRANCH=${QL_BRANCH}

RUN set -x \
    && apt-get update -f \
    && apt-get upgrade -y \
    && apt-get --no-install-recommends -y install bash \
                                                  coreutils \
                                                  moreutils \
                                                  git \
                                                  curl \
                                                  wget \
                                                  tzdata \
                                                  perl \
                                                  openssl \
                                                  nginx \
                                                  nodejs \
                                                  jq \
                                                  openssh-client \
                                                  npm \
    && rm -rf /var/cache/apt/* \
    && apt-get update \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && git config --global user.email "qinglong@@users.noreply.github.com" \
    && git config --global user.name "qinglong" \
    && git config --global http.postBuffer 524288000 \
    && npm install -g pnpm \
    && pnpm add -g pm2 ts-node typescript tslib \
    && rm -rf /root/.pnpm-store \
    && rm -rf /root/.local/share/pnpm/store \
    && rm -rf /root/.cache \
    && rm -rf /root/.npm

ARG SOURCE_COMMIT
RUN git clone -b ${QL_BRANCH} ${QL_URL} ${QL_DIR} \
    && cd ${QL_DIR} \
    && cp -f .env.example .env \
    && chmod 777 ${QL_DIR}/shell/*.sh \
    && chmod 777 ${QL_DIR}/docker/*.sh \
    && git clone -b ${QL_BRANCH} https://github.com/${QL_MAINTAINER}/qinglong-static.git /static \
    && mkdir -p ${QL_DIR}/static \
    && cp -rf /static/* ${QL_DIR}/static \
    && rm -rf /static

COPY --from=builder /tmp/build/node_modules/. /ql/node_modules/

WORKDIR ${QL_DIR}
    
ENTRYPOINT ["./docker/docker-entrypoint.sh"]
`

**Comment by vtumi** [comment]
上传了一个居于Debian的容器镜像，需要的可以试试
docker pull tumi/qinglong

**Comment by whyour** [comment]
> @whyour 感谢作者，我遇到类似的问题，无法pip install ddddocr。
> 
> 原因如下：
> 
> ```
> The conflict is caused by:
>     ddddocr 1.4.7 depends on onnxruntime
>     ddddocr 1.4.6 depends on onnxruntime
>     ddddocr 1.4.5 depends on onnxruntime
>     ddddocr 1.0.6 depends on onnxruntime
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> root@qinglong:/ql/data/scripts/gqbre_emby-server-checkin $pip install onnxruntime
> Looking in indexes: https://pypi.doubanio.com/simple/
> ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
> ERROR: No matching distribution found for onnxruntime
> ```
> 
> 我尝试fork 修改dockerfile 为基于python-slim的版本（这个版本可以安装），暂时没有成功发布到DockerHub上，因此真诚建议作者是否可以新建一个 基于 python-slim的版本的镜像，用于性能更好的，不那么在乎镜像体积的设备使用。以下是我修改的代码，仅供参考。
> 
> ```
> #  修改记录：
> # 将 python:3.10-alpine 替换成 python:3.10-slim
> # 将 apk 命令替换成 apt-get
> # 尚未替换国内镜像
> 
> FROM python:3.10-slim as builder 
> COPY package.json .npmrc pnpm-lock.yaml /tmp/build/
> RUN set -x \
>     && apt-get update \
>     && apt-get install -y --no-install-recommends nodejs npm git \
>     && npm i -g pnpm \
>     && cd /tmp/build \
>     && pnpm install --prod
> 
> FROM python:3.10-slim
> 
> ARG QL_MAINTAINER="whyour"
> LABEL maintainer="${QL_MAINTAINER}"
> ARG QL_URL=https://github.com/${QL_MAINTAINER}/qinglong.git
> ARG QL_BRANCH=develop
> 
> ENV PNPM_HOME=/root/.local/share/pnpm \
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules:$PNPM_HOME \
>     NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules \
>     LANG=zh_CN.UTF-8 \
>     SHELL=/bin/bash \
>     PS1="\u@\h:\w \$ " \
>     QL_DIR=/ql \
>     QL_BRANCH=${QL_BRANCH}
> 
> RUN set -x \
>     && apt-get update -f \
>     && apt-get upgrade -y \
>     && apt-get --no-install-recommends -y install bash \
>                                                   coreutils \
>                                                   moreutils \
>                                                   git \
>                                                   curl \
>                                                   wget \
>                                                   tzdata \
>                                                   perl \
>                                                   openssl \
>                                                   nginx \
>                                                   nodejs \
>                                                   jq \
>                                                   openssh-client \
>                                                   npm \
>     && rm -rf /var/cache/apt/* \
>     && apt-get update \
>     && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
>     && echo "Asia/Shanghai" > /etc/timezone \
>     && git config --global user.email "qinglong@@users.noreply.github.com" \
>     && git config --global user.name "qinglong" \
>     && git config --global http.postBuffer 524288000 \
>     && npm install -g pnpm \
>     && pnpm add -g pm2 ts-node typescript tslib \
>     && rm -rf /root/.pnpm-store \
>     && rm -rf /root/.local/share/pnpm/store \
>     && rm -rf /root/.cache \
>     && rm -rf /root/.npm
> 
> ARG SOURCE_COMMIT
> RUN git clone -b ${QL_BRANCH} ${QL_URL} ${QL_DIR} \
>     && cd ${QL_DIR} \
>     && cp -f .env.example .env \
>     && chmod 777 ${QL_DIR}/shell/*.sh \
>     && chmod 777 ${QL_DIR}/docker/*.sh \
>     && git clone -b ${QL_BRANCH} https://github.com/${QL_MAINTAINER}/qinglong-static.git /static \
>     && mkdir -p ${QL_DIR}/static \
>     && cp -rf /static/* ${QL_DIR}/static \
>     && rm -rf /static
> 
> COPY --from=builder /tmp/build/node_modules/. /ql/node_modules/
> 
> WORKDIR ${QL_DIR}
>     
> ENTRYPOINT ["./docker/docker-entrypoint.sh"]
> ```

依赖管理也需要改下，如果有好的自动化 slim 的镜像，欢迎提 PR

**Comment by demostars** [comment]
> 

多谢作者回复，实不相瞒，我在Windows 下并没有成功 Build 出我想要的镜像。我目前没有排查出问题出在哪里，我也看了下作者你的 Github Action中关于docker build & push 的部分，static 静态资源也是必须项。

我对于Dockerfile 和 Github Action 都三脚猫，暂时没有完整的解决方案，所以无法PR。

**Comment by sailor613** [comment]
> > @whyour 感谢作者，我遇到类似的问题，无法pip install ddddocr。
> > 原因如下：
> > ```
> > The conflict is caused by:
> >     ddddocr 1.4.7 depends on onnxruntime
> >     ddddocr 1.4.6 depends on onnxruntime
> >     ddddocr 1.4.5 depends on onnxruntime
> >     ddddocr 1.0.6 depends on onnxruntime
> > 
> > To fix this you could try to:
> > 1. loosen the range of package versions you've specified
> > 2. remove package versions to allow pip attempt to solve the dependency conflict
> > 
> > ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> > root@qinglong:/ql/data/scripts/gqbre_emby-server-checkin $pip install onnxruntime
> > Looking in indexes: https://pypi.doubanio.com/simple/
> > ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
> > ERROR: No matching distribution found for onnxruntime
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我尝试fork 修改dockerfile 为基于python-slim的版本（这个版本可以安装），暂时没有成功发布到DockerHub上，因此真诚建议作者是否可以新建一个 基于 python-slim的版本的镜像，用于性能更好的，不那么在乎镜像体积的设备使用。以下是我修改的代码，仅供参考。
> > ```
> > #  修改记录：
> > # 将 python:3.10-alpine 替换成 python:3.10-slim
> > # 将 apk 命令替换成 apt-get
> > # 尚未替换国内镜像
> > 
> > FROM python:3.10-slim as builder 
> > COPY package.json .npmrc pnpm-lock.yaml /tmp/build/
> > RUN set -x \
> >     && apt-get update \
> >     && apt-get install -y --no-install-recommends nodejs npm git \
> >     && npm i -g pnpm \
> >     && cd /tmp/build \
> >     && pnpm install --prod
> > 
> > FROM python:3.10-slim
> > 
> > ARG QL_MAINTAINER="whyour"
> > LABEL maintainer="${QL_MAINTAINER}"
> > ARG QL_URL=https://github.com/${QL_MAINTAINER}/qinglong.git
> > ARG QL_BRANCH=develop
> > 
> > ENV PNPM_HOME=/root/.local/share/pnpm \
> >     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules:$PNPM_HOME \
> >     NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules \
> >     LANG=zh_CN.UTF-8 \
> >     SHELL=/bin/bash \
> >     PS1="\u@\h:\w \$ " \
> >     QL_DIR=/ql \
> >     QL_BRANCH=${QL_BRANCH}
> > 
> > RUN set -x \
> >     && apt-get update -f \
> >     && apt-get upgrade -y \
> >     && apt-get --no-install-recommends -y install bash \
> >                                                   coreutils \
> >                                                   moreutils \
> >                                                   git \
> >                                                   curl \
> >                                                   wget \
> >                                                   tzdata \
> >                                                   perl \
> >                                                   openssl \
> >                                                   nginx \
> >                                                   nodejs \
> >                                                   jq \
> >                                                   openssh-client \
> >                                                   npm \
> >     && rm -rf /var/cache/apt/* \
> >     && apt-get update \
> >     && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
> >     && echo "Asia/Shanghai" > /etc/timezone \
> >     && git config --global user.email "qinglong@@users.noreply.github.com" \
> >     && git config --global user.name "qinglong" \
> >     && git config --global http.postBuffer 524288000 \
> >     && npm install -g pnpm \
> >     && pnpm add -g pm2 ts-node typescript tslib \
> >     && rm -rf /root/.pnpm-store \
> >     && rm -rf /root/.local/share/pnpm/store \
> >     && rm -rf /root/.cache \
> >     && rm -rf /root/.npm
> > 
> > ARG SOURCE_COMMIT
> > RUN git clone -b ${QL_BRANCH} ${QL_URL} ${QL_DIR} \
> >     && cd ${QL_DIR} \
> >     && cp -f .env.example .env \
> >     && chmod 777 ${QL_DIR}/shell/*.sh \
> >     && chmod 777 ${QL_DIR}/docker/*.sh \
> >     && git clone -b ${QL_BRANCH} https://github.com/${QL_MAINTAINER}/qinglong-static.git /static \
> >     && mkdir -p ${QL_DIR}/static \
> >     && cp -rf /static/* ${QL_DIR}/static \
> >     && rm -rf /static
> > 
> > COPY --from=builder /tmp/build/node_modules/. /ql/node_modules/
> > 
> > WORKDIR ${QL_DIR}
> >     
> > ENTRYPOINT ["./docker/docker-entrypoint.sh"]
> > ```
> 
> 依赖管理也需要改下，如果有好的自动化 slim 的镜像，欢迎提 PR 另外，你这镜像build完多大呢

我也遇到了，后面通过ddddocr直接搭了个api解决的，反正都是在docker里面运行 也不算麻烦。

**Comment by demostars** [comment]
> > > @whyour 感谢作者，我遇到类似的问题，无法pip install ddddocr。
> > > 原因如下：
> > > ```
> > > The conflict is caused by:
> > >     ddddocr 1.4.7 depends on onnxruntime
> > >     ddddocr 1.4.6 depends on onnxruntime
> > >     ddddocr 1.4.5 depends on onnxruntime
> > >     ddddocr 1.0.6 depends on onnxruntime
> > > 
> > > To fix this you could try to:
> > > 1. loosen the range of package versions you've specified
> > > 2. remove package versions to allow pip attempt to solve the dependency conflict
> > > 
> > > ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> > > root@qinglong:/ql/data/scripts/gqbre_emby-server-checkin $pip install onnxruntime
> > > Looking in indexes: https://pypi.doubanio.com/simple/
> > > ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
> > > ERROR: No matching distribution found for onnxruntime
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我尝试fork 修改dockerfile 为基于python-slim的版本（这个版本可以安装），暂时没有成功发布到DockerHub上，因此真诚建议作者是否可以新建一个 基于 python-slim的版本的镜像，用于性能更好的，不那么在乎镜像体积的设备使用。以下是我修改的代码，仅供参考。
> > > ```
> > > #  修改记录：
> > > # 将 python:3.10-alpine 替换成 python:3.10-slim
> > > # 将 apk 命令替换成 apt-get
> > > # 尚未替换国内镜像
> > > 
> > > FROM python:3.10-slim as builder 
> > > COPY package.json .npmrc pnpm-lock.yaml /tmp/build/
> > > RUN set -x \
> > >     && apt-get update \
> > >     && apt-get install -y --no-install-recommends nodejs npm git \
> > >     && npm i -g pnpm \
> > >     && cd /tmp/build \
> > >     && pnpm install --prod
> > > 
> > > FROM python:3.10-slim
> > > 
> > > ARG QL_MAINTAINER="whyour"
> > > LABEL maintainer="${QL_MAINTAINER}"
> > > ARG QL_URL=https://github.com/${QL_MAINTAINER}/qinglong.git
> > > ARG QL_BRANCH=develop
> > > 
> > > ENV PNPM_HOME=/root/.local/share/pnpm \
> > >     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules:$PNPM_HOME \
> > >     NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules \
> > >     LANG=zh_CN.UTF-8 \
> > >     SHELL=/bin/bash \
> > >     PS1="\u@\h:\w \$ " \
> > >     QL_DIR=/ql \
> > >     QL_BRANCH=${QL_BRANCH}
> > > 
> > > RUN set -x \
> > >     && apt-get update -f \
> > >     && apt-get upgrade -y \
> > >     && apt-get --no-install-recommends -y install bash \
> > >                                                   coreutils \
> > >                                                   moreutils \
> > >                                                   git \
> > >                                                   curl \
> > >                                                   wget \
> > >                                                   tzdata \
> > >                                                   perl \
> > >                                                   openssl \
> > >                                                   nginx \
> > >                                                   nodejs \
> > >                                                   jq \
> > >                                                   openssh-client \
> > >                                                   npm \
> > >     && rm -rf /var/cache/apt/* \
> > >     && apt-get update \
> > >     && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
> > >     && echo "Asia/Shanghai" > /etc/timezone \
> > >     && git config --global user.email "qinglong@@users.noreply.github.com" \
> > >     && git config --global user.name "qinglong" \
> > >     && git config --global http.postBuffer 524288000 \
> > >     && npm install -g pnpm \
> > >     && pnpm add -g pm2 ts-node typescript tslib \
> > >     && rm -rf /root/.pnpm-store \
> > >     && rm -rf /root/.local/share/pnpm/store \
> > >     && rm -rf /root/.cache \
> > >     && rm -rf /root/.npm
> > > 
> > > ARG SOURCE_COMMIT
> > > RUN git clone -b ${QL_BRANCH} ${QL_URL} ${QL_DIR} \
> > >     && cd ${QL_DIR} \
> > >     && cp -f .env.example .env \
> > >     && chmod 777 ${QL_DIR}/shell/*.sh \
> > >     && chmod 777 ${QL_DIR}/docker/*.sh \
> > >     && git clone -b ${QL_BRANCH} https://github.com/${QL_MAINTAINER}/qinglong-static.git /static \
> > >     && mkdir -p ${QL_DIR}/static \
> > >     && cp -rf /static/* ${QL_DIR}/static \
> > >     && rm -rf /static
> > > 
> > > COPY --from=builder /tmp/build/node_modules/. /ql/node_modules/
> > > 
> > > WORKDIR ${QL_DIR}
> > >     
> > > ENTRYPOINT ["./docker/docker-entrypoint.sh"]
> > > ```
> > 
> > 
> > 依赖管理也需要改下，如果有好的自动化 slim 的镜像，欢迎提 PR 另外，你这镜像build完多大呢
> 
> 我也遇到了，后面通过ddddocr直接搭了个api解决的，反正都是在docker里面运行 也不算麻烦。

我重新做了个镜像，内置了从源码编译的DDDDOCR，但是，我用telegram bot，好像也有问题，ssl 的错啦，gcc的错啦。。我还在研究怎么把原是镜像改成slim。

**Comment by whyour** [comment]
> 遇到类似问题。
> 
> 在容器内部安装 [playwright](https://pypi.org/project/playwright/) 提示平台不支持。 ![容器内安装失败](https://user-images.githubusercontent.com/21218296/253989527-1805bc78-6c43-4145-b8b0-337fd3b0d23f.png)
> 
> 容器外部能正常安装。 ![容器外安装成功](https://user-images.githubusercontent.com/21218296/253989540-1249b5a9-2c75-42c0-993d-a919292cf796.png)
> 
> 从 [YusukeIwaki/playwright-python-remote](https://github.com/YusukeIwaki/playwright-python-remote) 找到解决办法：
> 
> ```shell
> FROM python:3.9-alpine
> 
> RUN apk add --no-cache --virtual .install-deps build-base curl git \
>     && pip install git+https://github.com/microsoft/playwright-python@v1.20.0 \
>     && pip install git+https://github.com/YusukeIwaki/playwright-python-remote \
>     && apk del .install-deps
> ```
> 
> 或者在外部搭建 playwright-server,内部使用 playwright_remote 连接 websocket 后调用。
> 
> ```python
> from playwright_remote.sync_api import sync_playwright_remote
> 
> with sync_playwright_remote('ws://127.0.0.1:8080/ws') as playwright:
>   with playwright.chromium.launch() as browser:
>     page = browser.new_page()
>     page.goto('https://github.com/YusukeIwaki')
>     page.screenshot(path='YusukeIwaki.png')
> ```
> 
> ![image](https://user-images.githubusercontent.com/21218296/254038043-ff050bcf-4223-40dc-a2c6-4257251d4950.png)

可以使用 whyour/qinglong:debian 镜像

**Comment by Evilmass** [comment]
> > 遇到类似问题。
> > 在容器内部安装 [playwright](https://pypi.org/project/playwright/) 提示平台不支持。 ![容器内安装失败](https://user-images.githubusercontent.com/21218296/253989527-1805bc78-6c43-4145-b8b0-337fd3b0d23f.png)
> > 容器外部能正常安装。 ![容器外安装成功](https://user-images.githubusercontent.com/21218296/253989540-1249b5a9-2c75-42c0-993d-a919292cf796.png)
> > 从 [YusukeIwaki/playwright-python-remote](https://github.com/YusukeIwaki/playwright-python-remote) 找到解决办法：
> > ```shell
> > FROM python:3.9-alpine
> > 
> > RUN apk add --no-cache --virtual .install-deps build-base curl git \
> >     && pip install git+https://github.com/microsoft/playwright-python@v1.20.0 \
> >     && pip install git+https://github.com/YusukeIwaki/playwright-python-remote \
> >     && apk del .install-deps
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 或者在外部搭建 playwright-server,内部使用 playwright_remote 连接 websocket 后调用。
> > ```python
> > from playwright_remote.sync_api import sync_playwright_remote
> > 
> > with sync_playwright_remote('ws://127.0.0.1:8080/ws') as playwright:
> >   with playwright.chromium.launch() as browser:
> >     page = browser.new_page()
> >     page.goto('https://github.com/YusukeIwaki')
> >     page.screenshot(path='YusukeIwaki.png')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/21218296/254038043-ff050bcf-4223-40dc-a2c6-4257251d4950.png)
> 
> 可以使用 whyour/qinglong:debian 镜像

谢谢，正头疼怎么改 alpine 的 dockerfile 呢。

**Comment by Turkeyer** [comment]
> canvas 安装失败，linux 添加如下依赖
> 
> ```
> build-base
> pkgconfig 
> pixman-dev 
> cairo-dev 
> pango-dev 
> make 
> g++
> ```

无用。这些依赖安装了，但那个还是不行

**Comment by tianjiao96176** [comment]
> > canvas 安装失败，linux 添加如下依赖
> > ```
> > build-base
> > pkgconfig 
> > pixman-dev 
> > cairo-dev 
> > pango-dev 
> > make 
> > g++
> > ```
> 
> 无用。这些依赖安装了，但那个还是不行

添加了 还是安装不成功日志 - canvas
开始安装依赖 canvas，开始时间 2024-03-21 10:47:57

ERROR: Ignored the following versions that require a different python version: 0.1.4 Requires-Python >=3.12,<4.0
ERROR: Could not find a version that satisfies the requirement canvas (from versions: none)
ERROR: No matching distribution found for canvas

**Comment by tasty007** [comment]
> > > > canvas 安装失败，linux 添加如下依赖
> > > > ```
> > > > build-base
> > > > pkgconfig 
> > > > pixman-dev 
> > > > cairo-dev 
> > > > pango-dev 
> > > > make 
> > > > g++
> > > > ```
> > > 
> > > 
> > > 无用。这些依赖安装了，但那个还是不行
> > 
> > 
> > 添加了 还是安装不成功日志 - canvas 开始安装依赖 canvas，开始时间 2024-03-21 10:47:57
> > ERROR: Ignored the following versions that require a different python version: 0.1.4 Requires-Python >=3.12,<4.0 ERROR: Could not find a version that satisfies the requirement canvas (from versions: none) ERROR: No matching distribution found for canvas
> 
> 你不会看日志吗，python下的canvas支持python版本>=3.12,你的版本低，当然报错

大佬有什么解决办法吗...

**Comment by shinesky** [comment]
> canvas 安装失败，linux 添加如下依赖
> 
> ```
> build-base
> pkgconfig 
> pixman-dev 
> cairo-dev 
> pango-dev 
> make 
> g++
> ```

这几个依赖装完后还是不行，canvas依然安装失败，提示如下：
ERROR: No matching distribution found for canvas

**Comment by snaketzy** [comment]
> > > 遇到类似问题。
> > > 在容器内部安装 [playwright](https://pypi.org/project/playwright/) 提示平台不支持。 ![容器内安装失败](https://user-images.githubusercontent.com/21218296/253989527-1805bc78-6c43-4145-b8b0-337fd3b0d23f.png)
> > > 容器外部能正常安装。 ![容器外安装成功](https://user-images.githubusercontent.com/21218296/253989540-1249b5a9-2c75-42c0-993d-a919292cf796.png)
> > > 从 [YusukeIwaki/playwright-python-remote](https://github.com/YusukeIwaki/playwright-python-remote) 找到解决办法：
> > > FROM python:3.9-alpine
> > > 
> > > RUN apk add --no-cache --virtual .install-deps build-base curl git \
> > >     && pip install git+https://github.com/microsoft/playwright-python@v1.20.0 \
> > >     && pip install git+https://github.com/YusukeIwaki/playwright-python-remote \
> > >     && apk del .install-deps
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 或者在外部搭建 playwright-server,内部使用 playwright_remote 连接 websocket 后调用。
> > > from playwright_remote.sync_api import sync_playwright_remote
> > > 
> > > with sync_playwright_remote('ws://127.0.0.1:8080/ws') as playwright:
> > >   with playwright.chromium.launch() as browser:
> > >     page = browser.new_page()
> > >     page.goto('https://github.com/YusukeIwaki')
> > >     page.screenshot(path='YusukeIwaki.png')
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![image](https://user-images.githubusercontent.com/21218296/254038043-ff050bcf-4223-40dc-a2c6-4257251d4950.png)
> > 
> > 
> > 可以使用 whyour/qinglong:debian 镜像
> 
> 谢谢，正头疼怎么改 alpine 的 dockerfile 呢。

如果是在宝塔的docker面板里面，可以手工改

<img width="1900" height="1030" alt="Image" src="https://github.com/user-attachments/assets/59952312-eb0c-4fb4-9e15-a9c0dbcf443a" />
