### ISSUE TITLE
vscode remote ssh无法连接，希望有非alpine底包的版本

### ISSUE THREAD

**Issue by HanEightTurtle** [whyour/qinglong#1646]
### Clear and concise description of the problem

vscode remote ssh无法连接，查询 https://code.visualstudio.com/docs/remote/linux 发现是底包alpine不支持。

### Suggested solution

是否考虑建立新tag以debian等发行版作为底包。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
Alpine Linux 64-bit x86 containers or WSL hosts (3.9+) in Dev Containers, WSL

这不就是 alpine ?

**Comment by We41w4e** [comment]
> Alpine Linux 64-bit x86 containers or WSL hosts (3.9+) in Dev Containers, WSL
> 
> 这不就是 alpine ?

他想操作系统是Debian的而不是apline
