### ISSUE TITLE
请问青龙能备份脚本配置文件和环境变量降级安装吗

### ISSUE THREAD

**Issue by wh-990624** [whyour/qinglong#1647]
### Clear and concise description of the problem

请问青龙能备份脚本配置文件和环境变量降级安装吗

### Suggested solution

请问青龙能备份脚本配置文件和环境变量降级安装吗

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
docker 映射目录 重新启动指定版本
