### ISSUE TITLE
飞书通知不可用

### ISSUE THREAD

**Issue by xmoxmo** [whyour/qinglong#1657]
### Clear and concise description of the problem

看到notify.PY中支持飞书，调试的时候可以发送消息到飞书，如何才能添加通知方式

### Suggested solution

看到notify.PY中支持飞书，调试的时候可以发送消息到飞书，如何才能添加通知方式

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
是脚本用  还是系统设置里

**Comment by xmoxmo** [comment]
主要是就和钉钉一样的推送脚本的信息

**Comment by whyour** [comment]
v2.14.9 支持

**Comment by xmoxmo** [comment]
> v2.14.9 支持

感谢，辛苦啦
