### ISSUE TITLE
edge浏览器主页加载很慢的问题

### ISSUE THREAD

**Issue by showmexlq** [whyour/qinglong#1658]
### Qinglong version

2.14.7

### Steps to reproduce

直接请求自己搭建的青龙面板的主页列表,查看请求日志和事件时间

### What is expected?

优化以下加载的速度,不知道是不是个例,已经跟着升级了很多个版本都有这个问题才提出来的

### What is actually happening?

在3-4s的时候服务器请求已经完成,然后处理数据的时候我发现有几个地方很耗时间,而且得等它们处理完了页面才会完全显示,最终导致实际的时间会多差不多11s以上,以下是一些Edge浏览器事件日志截图
![image](https://user-images.githubusercontent.com/25734955/196850542-0597b829-1159-41f6-bafc-0a80ba33bcfd.png)
以上截图事件已经过滤掉上述3-4s的前的所有正常事件,圈主的地方比较耗时,我用手机的safari打开网页加载速度就很快

### System Info

```shell
青龙运行环境:系统：windows/10浏览器：chrome/106.0.0.0内核：webkit/537.36
```

### Any additional comments?

还有上述的那个wss是干嘛的,也是请求失败,需要跟进处理问题的时候再提供更多的信息吧,主要也不清楚哪些有用

**Comment by whyour** [comment]
wss自己研究，慢的问题欢迎提PR
