### ISSUE TITLE
依赖安装失败，只有py3在面板里显示己安装，Linux,node 面板里显示都是安装失败，没有一个成功

### ISSUE THREAD

**Issue by Unicorni** [whyour/qinglong#1660]
### Qinglong version

v.2.14.7

### Steps to reproduce

我的是群辉容器加青龙，昨天刚升级了一下青龙版本v.2.14.7，用的是面板里自动升级的，然后出来了之后发现依赖全部失效了，然后我用命令安装，一直安装不成功，不知道怎么看错误还望大佬提示帮忙。

这是我用命令安装依赖的。错误的过程,我不知道为什么一直依赖安装不上，网上这些个教程也很少。不知道为什么出错了，帮帮我

我是需要重新装青龙了吗那么我该如何备份我的脚本呢？它在容器内有没有好的教程参考一下？

root@DiskStation:# docker restart qinglong
qinglong
root@DiskStation:# docker exec -it qinglong bash -c "$(curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh)"
sh: line 40: 当前node版本(如果没有node，请自行安装): : command not found
sh: line 44: 当前npm版本(如果没有npm，请自行安装): : command not found
sh: line 48: cd: /ql: No such file or directory
sh: line 49: pnpm: command not found
sh: line 51: pnpm: command not found
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE package: 'jsdom@20.0.1',
npm WARN EBADENGINE required: { node: '>=14' },
npm WARN EBADENGINE current: { node: 'v12.22.7', npm: '8.19.2' }
npm WARN EBADENGINE }
sh: line 55: pnpm: command not found
sh: line 57: pip3: command not found
sh: line 59: cd: /ql/scripts/: No such file or directory
sh: line 60: cd: /ql: No such file or directory
sh: line 61: apk: command not found
sh: line 62: cd: /ql: No such file or directory
sh: line 63: apk: command not found
bash: line 4: $'\E[36m\E[0m': command not found
bash: line 4: $'1m安装依赖...\E[0m': command not found
bash: line 6: $'\E[36m\E[0m': command not found
bash: line 6: $'1m安装依赖需要时间，请耐心等待!\E[0m': command not found
bash: line 11: v12.22.7: command not found
bash: line 13: 8.19.2: command not found
bash: line 15: added: command not found
bash: line 17: 11: command not found
bash: line 18: run: command not found
bash: line 20: $'\E[36m\E[0m': command not found
bash: line 20: 1m依赖安装完毕...建议重启: command not found
bash: line 22: $'\E[36m\E[0m': command not found
bash: line 22: 1m有任何问题，请在此仓库提交Issue：: command not found

### What is expected?

青龙v.2.14.7新版本挺好的，添加一个订阅功能，但是不是很会用，没有说特别好的说明教程。能不能集成一些大佬的脚本库啊？但是感觉还有很多需要改进的地方。感觉现在也就是定时任务上好，可以使用js,py命令脚本，还有很多需要完善的地方啊。

### What is actually happening?

-================这是我运行部分脚本出现错误，感觉像是缺少了什么依赖。========================

zero205/JD_tencent_scf80+

开始执行... 2022-10-20 10:13:19
/bin/bash: line 1: USER: command not found
/bin/bash: line 1: sendNotify: command not found
/bin/bash: line 1: sign_graphics_validate: command not found
/bin/bash: line 2: $'ql main\n': command not found
/bin/bash: line 1: JDJR: command not found
/bin/bash: line 1: JDSign: command not found
/bin/bash: line 1: icon ^jd[^_]: command not found
/bin/bash: line 1: jdCookie backUp: command not found
/bin/bash: line 1: jx_: command not found

执行结束... 2022-10-20 10:13:19 耗时 0 秒
收藏大师-关注商品

开始执行... 2022-10-20 10:14:13
🔔收藏大师-关注商品, 开始!

====================共2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/10/20 10:14:15=====================

KingRan 频道通知：https://t.me/KingRan521

node:internal/modules/cjs/loader:936
throw err;
^

Error: Cannot find module 'ds'
Require stack:

/ql/data/scripts/KingRan_KR/function/cache/index.js
/ql/data/scripts/KingRan_KR/function/krgetToken.js
/ql/data/scripts/KingRan_KR/jd_txzj_collect_shop.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:999:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object. (/ql/data/scripts/KingRan_KR/function/cache/index.js:1:9455)
at Module._compile (node:internal/modules/cjs/loader:1099:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:975:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:999:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/ql/data/scripts/KingRan_KR/function/cache/index.js',
'/ql/data/scripts/KingRan_KR/function/krgetToken.js',
'/ql/data/scripts/KingRan_KR/jd_txzj_collect_shop.js'
]
}

**Comment by Unicorni** [comment]
https://github.com/whyour/qinglong/issues/1441跟我出现同样的问题升级到青龙v.2.14.7，nodejs和linux的依赖全部安装失败。

**Comment by Unicorni** [comment]
v2.13.7也出现同样的问题，nodejs和linux的依赖全部安装失败。

**Comment by whyour** [comment]
命令谁写的找谁，面板安装失败，看日志

**Comment by gujiangjiang** [comment]
2.14.8刚升级完，也全部安全失败，2.14.7没问题的，试过重装也不行，不知道原因了
<img width="952" alt="image" src="https://user-images.githubusercontent.com/13273955/197336464-397d9f0f-092b-499b-95b6-92c077d1a6f3.png">

**Comment by whyour** [comment]
@gujiangjiang 看日志

**Comment by gujiangjiang** [comment]
@whyour 

`开始安装依赖 png-js，开始时间 2022-10-22 19:33:33

 WARN  GET https://registry.npmmirror.com/pidusage/-/pidusage-3.0.1.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/pidusage/-/pidusage-3.0.1.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_FETCH_404  GET https://registry.npmmirror.com/pidusage/-/pidusage-3.0.1.tgz: Not Found - 404

No authorization header was set for the request.

依赖安装失败，结束时间 2022-10-22 19:34:53，耗时 79 秒`

所有的js都提示这个错误，但是网络是好的，
<img width="591" alt="image" src="https://user-images.githubusercontent.com/13273955/197337004-d71dc2d1-54c2-47aa-95a7-e3e720a2bbee.png">

**Comment by whyour** [comment]
@gujiangjiang 把配置里的proxyurl删了吧，这个镜像仓库这个包有问题。然后重启下容器

**Comment by gujiangjiang** [comment]
@whyour 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/13273955/197337066-78895188-46b1-4409-942d-45a324daadcc.png">

我没有开这个镜像地址，我是全局openclash+adguardhome，是clash的问题？

**Comment by whyour** [comment]
@gujiangjiang 配置文件里  npm 的镜像地址

**Comment by gujiangjiang** [comment]
@whyour 
您是说这个嘛
<img width="412" alt="image" src="https://user-images.githubusercontent.com/13273955/197337137-337153f6-9cd0-40c4-8d6e-6adae42b0761.png">

**Comment by gujiangjiang** [comment]
python没问题，正常安装，就node不行
<img width="566" alt="image" src="https://user-images.githubusercontent.com/13273955/197337158-74aeab2f-9bd8-4fe8-a885-ae8dbe756a8f.png">

**Comment by whyour** [comment]
@gujiangjiang 对  下面那个的问题

**Comment by gujiangjiang** [comment]
@whyour 
搞不清楚问题了，换成了淘宝源依然不行。
<img width="569" alt="image" src="https://user-images.githubusercontent.com/13273955/197337492-9c6b6f37-56fc-4adf-8d0d-785420b22d95.png">

**Comment by whyour** [comment]
@gujiangjiang 删了就行  用官方的  然后重启容器

**Comment by gujiangjiang** [comment]
改不过来了。。。明明删掉了，重启容器后还是淘宝。。。
<img width="379" alt="image" src="https://user-images.githubusercontent.com/13273955/197337948-9db00876-fb82-4ca3-aeb9-5697bfdb22a2.png">
<img width="598" alt="image" src="https://user-images.githubusercontent.com/13273955/197337951-a54070cc-97f4-4c5a-9108-7fbf184b3823.png">

**Comment by gujiangjiang** [comment]
@whyour 
手动改成官方源，解决问题，感谢

**Comment by loa123** [comment]
> @whyour 
> 手动改成官方源，解决问题，感谢
> <img width="397" alt="image" src="https://user-images.githubusercontent.com/13273955/197338314-135d30af-2373-42c6-93d8-f0a98136e956.png">
> 
> 
> <img width="737" alt="image" src="https://user-images.githubusercontent.com/13273955/197338303-53b65d14-8993-4dcf-ac44-3aff1da75120.png">
> 

终于也成功了。。

**Comment by yunli45** [comment]
是在宿主机还是docker下更改为官方源啊

**Comment by yunli45** [comment]
@loa123 @gujiangjiang @whyour 是在宿主机还是docker下更改为官方源啊
