### ISSUE TITLE
脚本日志有个错误，上个版本没哟

### ISSUE THREAD

**Issue by xmoxmo** [whyour/qinglong#1661]
### Clear and concise description of the problem

/ql/shell/otask.sh: line 86: [[: 27
27
27: syntax error in expression (error token is "27
27")

### Suggested solution

/ql/shell/otask.sh: line 86: [[: 27
27
27: syntax error in expression (error token is "27
27")

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
@xmoxmo 你的资源限制参数咋写的

**Comment by xmoxmo** [comment]
## 资源告警阙值，默认CPU 80%、内存80%、磁盘90%
CpuWarn=80
MemoryWarn=80
DiskWarn=90

**Comment by xmoxmo** [comment]
@whyour 默认的

**Comment by xmoxmo** [comment]
我也不清楚怎么回事，上一个版本没问题，刚刚更新了.8版本后，每个脚本日志中都有这个错误提示，麻烦帮忙看下如何排除是哪里的问题吧

**Comment by whyour** [comment]
@xmoxmo top -b -n 1 | grep CPU | grep -v -E 'grep|PID' | awk '{print $2}' | cut -f 1 -d "%"

free -m | grep "Mem" | awk '{print $3}'
free -m | grep "Mem" | awk '{print $2}'

df -P | grep /dev | grep -v -E '(tmp|boot|shm)' | awk '{print $5}' | cut -f 1 -d "%"

容器里执行这几行  看输出

**Comment by xmoxmo** [comment]
root@whyour-qinglong1:/ql/shell $ top -b -n 1 | grep CPU | grep -v -E 'grep|PID' | awk '{print $2}' | cut -f 1 -d "%"
2
root@whyour-qinglong1:/ql/shell $ free -m | grep "Mem" | awk '{print $3}'
2176
root@whyour-qinglong1:/ql/shell $ free -m | grep "Mem" | awk '{print $2}'
9796
root@whyour-qinglong1:/ql/shell $ df -P | grep /dev | grep -v -E '(tmp|boot|shm)' | awk '{print $5}' | cut -f 1 -d "%"
27
27
27

**Comment by whyour** [comment]
@xmoxmo 你这是挂了好几个盘？

**Comment by xmoxmo** [comment]
root@whyour-qinglong1:/ql/shell $ df -P
Filesystem             1024-blocks      Used  Available Capacity Mounted on
/dev/mapper/cachedev_0  1870732988 500103440 1370629548      27% /
tmpfs                        65536         0      65536       0% /dev
tmpfs                      5015700         0    5015700       0% /sys/fs/cgroup
shm                          65536         0      65536       0% /dev/shm
/dev/mapper/cachedev_0  1870732988 500103440 1370629548      27% /etc/hosts
/dev/mapper/cachedev_0  1870732988 500103440 1370629548      27% /ql/data/db
tmpfs                      5015700         0    5015700       0% /proc/acpi
tmpfs                      5015700         0    5015700       0% /proc/scsi
tmpfs                      5015700         0    5015700       0% /sys/firmware

**Comment by whyour** [comment]
@xmoxmo 你这为什么有三个27的盘

**Comment by xmoxmo** [comment]
我也不知道，我看了别的容器也是差不多
bash-5.1# df -P                                                                                                                                                                                       
Filesystem           1024-blocks    Used Available Capacity Mounted on                                                                                                                                
/dev/mapper/cachedev_0   1870732988 500115764 1370617224  27% /                                                                                                                                       
tmpfs                    65536         0     65536   0% /dev                                                                                                                                          
tmpfs                  5015700         0   5015700   0% /sys/fs/cgroup                                                                                                                                
shm                      65536         0     65536   0% /dev/shm                                                                                                                                      
/dev/mapper/cachedev_0   1870732988 500115764 1370617224  27% /etc/resolv.conf                                                                                                                        
/dev/mapper/cachedev_0   1870732988 500115764 1370617224  27% /etc/hostname                                                                                                                           
/dev/mapper/cachedev_0   1870732988 500115764 1370617224  27% /etc/hosts                                                                                                                              
/dev/md0               2385528   1813372    453372  80% /var/lib/zerotier-one                                                                                                                         
tmpfs                  5015700         0   5015700   0% /proc/acpi                                                                                                                                    
tmpfs                    65536         0     65536   0% /proc/kcore                                                                                                                                   
tmpfs                    65536         0     65536   0% /proc/keys                                                                                                                                    
tmpfs                    65536         0     65536   0% /proc/timer_list                                                                                                                              
tmpfs                    65536         0     65536   0% /proc/sched_debug                                                                                                                             
tmpfs                  5015700         0   5015700   0% /proc/scsi                                                                                                                                    
tmpfs                  5015700         0   5015700   0% /sys/firmware

**Comment by xmoxmo** [comment]
群晖ds720+

**Comment by whyour** [comment]
@xmoxmo 这个没影响，下个版本改。你要改 /ql/shell/otask.sh  84行 改成   disk_use=$(df -P | grep /dev | grep -v -E '(tmp|boot|shm)' | awk '{print $5}' | cut -f 1 -d "%" | head -n 1)

**Comment by xmoxmo** [comment]
![image](https://user-images.githubusercontent.com/112841961/197398665-59bd7f85-1ca6-4f61-a218-1fc9506574d3.png)

我又看了看日志，其实一直都有这个信息，只不过这个版本把他输出到日志里了？

**Comment by xmoxmo** [comment]
ok谢谢，我先改着用，这么晚麻烦了

**Comment by xmoxmo** [comment]
太棒了，改了就没有了，太感谢啦

**Comment by Michaol** [comment]
我遇到的问题一样
/ql/shell/otask.sh: line 86: [[: 22
22
22: syntax error in expression (error token is "22
22")

**Comment by xmoxmo** [comment]
@whyour 您好，看到您更新修复了这个问题，但是我点击检查更新，强制更新的时候为什么没有拉取到最新更新，并且我自己按照您的要求修改的也会回复成原来的样子，这具体是哪的问题。
强制更新显示成功，但是代码回复成和原来一样，我自己打开otask文件随便改点东西，然后再强制更新，又回去了，问题是回到未修复这个问题的版本，是因为这个修复在下一个版本才生效吗。

**Comment by whyour** [comment]
@xmoxmo 你改的是develop镜像，你用的是latest

**Comment by whyour** [comment]
v2.14.9 修复

**Comment by xmoxmo** [comment]
> v2.14.9 修复
![image](https://user-images.githubusercontent.com/112841961/198869687-8256a609-21ff-4824-ac5f-5795e68300b2.png)
这个问题也是一并修复的吗？
2.14.9版本还是有这个报错的。
![image](https://user-images.githubusercontent.com/112841961/198869702-4d2ebb7f-beca-482f-a395-f154986f654e.png)

这个如何进一步看到您的回复是说定时规则的问题，如何进一步排查是什么样的定时规则造成的，我把执行情况按照定时规则的时间审查了一遍，暂时还没有发现按照设定时间而未执行的定时任务。

**Comment by whyour** [comment]
> > v2.14.9 修复
> > ![image](https://user-images.githubusercontent.com/112841961/198869687-8256a609-21ff-4824-ac5f-5795e68300b2.png)
> > 这个问题也是一并修复的吗？
> > 2.14.9版本还是有这个报错的。
> > ![image](https://user-images.githubusercontent.com/112841961/198869702-4d2ebb7f-beca-482f-a395-f154986f654e.png)
> 
> 这个如何进一步看到您的回复是说定时规则的问题，如何进一步排查是什么样的定时规则造成的，我把执行情况按照定时规则的时间审查了一遍，暂时还没有发现按照设定时间而未执行的定时任务。

不是一个问题，要看你的定时规则，如果不行，给前面加上秒就行了
