### ISSUE TITLE
2.14.8版本  nodejs依赖全部安装失败

### ISSUE THREAD

**Issue by xiaolong52** [whyour/qinglong#1662]
### Qinglong version

2.14.8

### Steps to reproduce

新装的2.14.8版本  nodejs依赖全部安装失败  Python的正常
用之前的2.13.3 是正常的

### What is expected?

请求大佬帮看看

### What is actually happening?

开始安装依赖 axios，开始时间 2022-10-23 22:35:26

Progress: resolved 0, reused 1, downloaded 0, added 0
 WARN  GET https://registry.npmmirror.com/pidusage/-/pidusage-3.0.1.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
Progress: resolved 58, reused 58, downloaded 0, added 0
 WARN  GET https://registry.npmmirror.com/pidusage/-/pidusage-3.0.1.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_FETCH_404  GET https://registry.npmmirror.com/pidusage/-/pidusage-3.0.1.tgz: Not Found - 404

No authorization header was set for the request.

**Comment by whyour** [comment]
@xiaolong52 这个npm源不知道啥问题，可以在配置文件里把npm源改成官方的，然后重启下容器

**Comment by xiaolong52** [comment]
感谢大佬，换了官方源可以

**Comment by LiteCoder** [comment]
> 请问官方源是那个？

https://registry.npmjs.org 我的改为这个可以了，今天早上才发现依赖全安装失败了

**Comment by ayurnero** [comment]
在哪里换源

**Comment by jameszhu1987** [comment]
换了还是安装失败 只有data一个可以安装成功

**Comment by imuccc** [comment]
大佬们,怎么换NPM源啊

**Comment by ayurnero** [comment]
> 大佬们，怎么换NPM源啊

拉一个最新的青龙，把里面的config打开就能看到，直升上来的没有

**Comment by loa123** [comment]
> @xiaolong52 这个npm源不知道啥问题，可以在配置文件里把npm源改成官方的，然后重启下容器

开始安装依赖 png-js，开始时间 2022-11-11 20:06:37

Progress: resolved 0, reused 1, downloaded 0, added 0
Progress: resolved 4, reused 4, downloaded 0, added 0
 WARN  GET https://registry.npmjs.org/png-js error (EAI_AGAIN). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/png-js error (EAI_AGAIN). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/png-js: request to https://registry.npmjs.org/png-js failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

This error happened while installing a direct dependency of /root/.local/share/pnpm/global/5

依赖安装失败，结束时间 2022-11-11 20:08:03，耗时 85 秒

js也是安装失败

**Comment by loa123** [comment]
> > @xiaolong52 这个npm源不知道啥问题，可以在配置文件里把npm源改成官方的，然后重启下容器
> 
> 开始安装依赖 png-js，开始时间 2022-11-11 20:06:37
> 
> Progress: resolved 0, reused 1, downloaded 0, added 0
> Progress: resolved 4, reused 4, downloaded 0, added 0
>  WARN  GET https://registry.npmjs.org/png-js error (EAI_AGAIN). Will retry in 10 seconds. 2 retries left.
>  WARN  GET https://registry.npmjs.org/png-js error (EAI_AGAIN). Will retry in 1 minute. 1 retries left.
>  ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/png-js: request to https://registry.npmjs.org/png-js failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
> 
> This error happened while installing a direct dependency of /root/.local/share/pnpm/global/5
> 
> 依赖安装失败，结束时间 2022-11-11 20:08:03，耗时 85 秒
> 
> js也是安装失败
> 

已解决
