### ISSUE TITLE
/ql/shell/otask.sh报错

### ISSUE THREAD

**Issue by dycwuxing** [whyour/qinglong#1663]
### Qinglong version

V2.14.8

### Steps to reproduce

每一个脚本的顶部都会提示
/ql/shell/otask.sh: line 86: [[: 90
0: syntax error in expression (error token is "0")
![image](https://user-images.githubusercontent.com/44988562/197429326-020877ee-9c26-4d0b-b4bc-3e105aee2640.png)

### What is expected?

对脚本实际运行好像是没有影响?我也不知道

### What is actually happening?

小白一个,不知道发生了什么

### System Info

```shell
System:
    OS: Linux 5.4 Alpine Linux
    CPU: (4) x64 Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
    Memory: 2.52 GB / 15.53 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/bin/node
    npm: 8.10.0 - /usr/bin/npm
```

**Comment by EchoChan314** [comment]
同样也有，运行在wsl2上。

**Comment by whyour** [comment]
参考 https://github.com/whyour/qinglong/issues/1661#issuecomment-1288128956

**Comment by dycwuxing** [comment]
已收到,谢谢大佬解答~
