### ISSUE TITLE
类似 0 1/4 * * * 的非标准 cron 无法按预期执行

### ISSUE THREAD

**Issue by Potat0000** [whyour/qinglong#1667]
### Clear and concise description of the problem

`0 1/4 * * *` 等价于 `0 1,5,9,13,17,21 * * *`。在网页端上可以被正确识别并显示出下次运行时间，但实际上无法按期执行。

### Suggested solution

使得类似语法可以被正确执行。

### Alternative

如果实现困难，能否退一步，将该语法在网页端显示为非法，保证前后端行为一致？

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
可以加上秒，就正常执行了。  应该是系统crontab不支持

**Comment by Potat0000** [comment]
> 可以加上秒，就正常执行了。 应该是系统crontab不支持

哦哦，确实，加上秒就好了。感谢回复！

**Comment by OwnerCM** [comment]
> 可以加上秒，就正常执行了。 应该是系统crontab不支持

请教一下为什么：59 59 9 * * * ，这个没法在每日9点59分59秒执行？

**Comment by whyour** [comment]
@OwnerCM 有4位的表达式？

**Comment by OwnerCM** [comment]
> @OwnerCM 有4位的表达式？

没明白，上面不是6位的表达式吗？ 59 59 9 * * * ？
其实我想说的就是5位设置到分钟的表达式可以正常运行，但是6位配置到秒的就没法运行，版本号：2.15.11

**Comment by whyour** [comment]
> > @OwnerCM 有4位的表达式？
> 
> 没明白，上面不是6位的表达式吗？ 59 59 9 * * * ？ 其实我想说的就是5位设置到分钟的表达式可以正常运行，但是6位配置到秒的就没法运行，版本号：2.15.11

ql check 下
