### ISSUE TITLE
卡在V2.14.2无法升级

### ISSUE THREAD

**Issue by zhigao1986** [whyour/qinglong#1668]
### Qinglong version

卡在V2.14.2无法升级

### Steps to reproduce

开始更新系统
No changes to the environment were made. Everything is already up to date.
Reset branch 'master'
Your branch is up to date with 'origin/master'.
Branch 'master' set up to track remote branch 'master' from 'origin'.
开始更新仓库：/ql

Fetching origin
fatal: unable to access 'https://github.com/whyour/qinglong.git/': Failed to connect to github.com port 443 after 15 ms: Connection refused
error: Could not fetch origin
Reset branch 'master'
Your branch is up to date with 'origin/master'.
Branch 'master' set up to track remote branch 'master' from 'origin'.

更新青龙源文件失败，请检查原因...

Reset branch 'master'
Your branch is up to date with 'origin/master'.
Branch 'master' set up to track remote branch 'master' from 'origin'.
开始更新仓库：/ql/data/repo/static

Fetching origin
fatal: unable to access 'https://github.com/whyour/qinglong-static.git/': Failed to connect to github.com port 443 after 14 ms: Connection refused
error: Could not fetch origin
Reset branch 'master'
Your branch is up to date with 'origin/master'.
Branch 'master' set up to track remote branch 'master' from 'origin'.

更新青龙静态资源失败，请检查原因...

## 执行结束... 2022-10-25 09:16:28  耗时 2 秒

卡在V2.14.2 更新一直提示这个，用设置界面更新，提示该错误信息后也无法退出提示框。脚本运行正常，但脚本更新也提示错误，重新启动DOCKER 故障依旧

### What is expected?

。

### What is actually happening?

。

**Comment by geekofrosty** [comment]
2.14.8同样问题
`开始更新仓库：/ql

Fetching origin
fatal: unable to access 'https://github.com/whyour/qinglong.git/': Could not resolve host: github.com
error: could not fetch origin

更新青龙源文件失败，请检查网络...
`

**Comment by geekofrosty** [comment]
2.14.8同样问题

**Comment by whyour** [comment]
使用   `docker run --rm   -v /var/run/docker.sock:/var/run/docker.sock   containrrr/watchtower -cR  ql`更新
ql 为你容器名称

**Comment by cy920820** [comment]
更新是在容器中执行 ql update 吗？我执行之后还是v2.11.3，没有更新到最新版本 - - @whyour
