### ISSUE TITLE
控制面板退出登录后，有些命令并不会自动运行

### ISSUE THREAD

**Issue by gxhunter1982** [whyour/qinglong#167]
1，在控制面板的定时任务里，添加了“ql repo xxxxx”拉取脚本库的命令，几次发现手动都能运行，但没有自动运行。进log目录，也发现并没有自动运行的log文件。
2，后来，把4条 “ql repo xxxxx”添加到自定义脚本，定时任务里添加了"ql extra"这个任务，一样手动运行没问题，自动运行不行。进log目录查看，自动运行的时间，并没有产生那4个拉取脚本库的log，只有一个extra.log，里面显示
"
请先登录！
请先登录！
请先登录！
请先登录！
"

看到此提示，发现自己每次退出控制面板时，都是点击“退出登录”。
尝试不点击"退出登录"，而是直接关闭窗口。
问题解决。

总结：
点击“退出登录”后，一些任务（命令）会没有执行权限。

**Comment by woboo110** [comment]
> 1，在控制面板的定时任务里，添加了“ql repo xxxxx”拉取脚本库的命令，几次发现手动都能运行，但没有自动运行。进log目录，也发现并没有自动运行的log文件。
> 2，后来，把4条 “ql repo xxxxx”添加到自定义脚本，定时任务里添加了"ql extra"这个任务，一样手动运行没问题，自动运行不行。进log目录查看，自动运行的时间，并没有产生那4个拉取脚本库的log，只有一个extra.log，里面显示
> "
> 请先登录！
> 请先登录！
> 请先登录！
> 请先登录！
> "
> 
> 看到此提示，发现自己每次退出控制面板时，都是点击“退出登录”。
> 尝试不点击"退出登录"，而是直接关闭窗口。
> 问题解决。
> 
> 总结：
> 点击“退出登录”后，一些任务（命令）会没有执行权限。

拉库的log不是单独的，跟update的在一块，你去update的log里找

**Comment by gxhunter1982** [comment]
> > 1，在控制面板的定时任务里，添加了“ql repo xxxxx”拉取脚本库的命令，几次发现手动都能运行，但没有自动运行。进log目录，也发现并没有自动运行的log文件。
> > 2，后来，把4条 “ql repo xxxxx”添加到自定义脚本，定时任务里添加了"ql extra"这个任务，一样手动运行没问题，自动运行不行。进log目录查看，自动运行的时间，并没有产生那4个拉取脚本库的log，只有一个extra.log，里面显示
> > "
> > 请先登录！
> > 请先登录！
> > 请先登录！
> > 请先登录！
> > "
> > 看到此提示，发现自己每次退出控制面板时，都是点击“退出登录”。
> > 尝试不点击"退出登录"，而是直接关闭窗口。
> > 问题解决。
> > 总结：
> > 点击“退出登录”后，一些任务（命令）会没有执行权限。
> 
> 拉库的log不是单独的，跟update的在一块，你去update的log里找

我知道，拉库的日志在update目录里。
如果我按了“退出登录”，那么自动运行时就只在这个目录产生extra.log一个日志文件，里面就是我前面提到的“请先登录”。

如果我没按退出登录，而是直接关闭窗口，update目录里，在自动运行的时间，除了extra.log文件，还会产生longzhuzhu.log、hundun.log、dust.log、jd_scripts.log共5个文件了。

**Comment by whyour** [comment]
> > > 1，在控制面板的定时任务里，添加了“ql repo xxxxx”拉取脚本库的命令，几次发现手动都能运行，但没有自动运行。进log目录，也发现并没有自动运行的log文件。
> > > 2，后来，把4条 “ql repo xxxxx”添加到自定义脚本，定时任务里添加了"ql extra"这个任务，一样手动运行没问题，自动运行不行。进log目录查看，自动运行的时间，并没有产生那4个拉取脚本库的log，只有一个extra.log，里面显示
> > > "
> > > 请先登录！
> > > 请先登录！
> > > 请先登录！
> > > 请先登录！
> > > "
> > > 看到此提示，发现自己每次退出控制面板时，都是点击“退出登录”。
> > > 尝试不点击"退出登录"，而是直接关闭窗口。
> > > 问题解决。
> > > 总结：
> > > 点击“退出登录”后，一些任务（命令）会没有执行权限。
> > 
> > 
> > 拉库的log不是单独的，跟update的在一块，你去update的log里找
> 
> 我知道，拉库的日志在update目录里。
> 如果我按了“退出登录”，那么自动运行时就只在这个目录产生extra.log一个日志文件，里面就是我前面提到的“请先登录”。
> 
> 如果我没按退出登录，而是直接关闭窗口，update目录里，在自动运行的时间，除了extra.log文件，还会产生longzhuzhu.log、hundun.log、dust.log、jd_scripts.log共5个文件了。

你为什么要退出，退出不能执行添加删除任务的操作

**Comment by gxhunter1982** [comment]
> > > > 1，在控制面板的定时任务里，添加了“ql repo xxxxx”拉取脚本库的命令，几次发现手动都能运行，但没有自动运行。进log目录，也发现并没有自动运行的log文件。
> > > > 2，后来，把4条 “ql repo xxxxx”添加到自定义脚本，定时任务里添加了"ql extra"这个任务，一样手动运行没问题，自动运行不行。进log目录查看，自动运行的时间，并没有产生那4个拉取脚本库的log，只有一个extra.log，里面显示
> > > > "
> > > > 请先登录！
> > > > 请先登录！
> > > > 请先登录！
> > > > 请先登录！
> > > > "
> > > > 看到此提示，发现自己每次退出控制面板时，都是点击“退出登录”。
> > > > 尝试不点击"退出登录"，而是直接关闭窗口。
> > > > 问题解决。
> > > > 总结：
> > > > 点击“退出登录”后，一些任务（命令）会没有执行权限。
> > > 
> > > 
> > > 拉库的log不是单独的，跟update的在一块，你去update的log里找
> > 
> > 
> > 我知道，拉库的日志在update目录里。
> > 如果我按了“退出登录”，那么自动运行时就只在这个目录产生extra.log一个日志文件，里面就是我前面提到的“请先登录”。
> > 如果我没按退出登录，而是直接关闭窗口，update目录里，在自动运行的时间，除了extra.log文件，还会产生longzhuzhu.log、hundun.log、dust.log、jd_scripts.log共5个文件了。
> 
> 你为什么要退出，退出不能执行添加删除任务的操作

以前养成的习惯，因为要登录的东西，在自己离开时，都登出。不然别人碰了如果乱改………………
只是没想到，登出会出现这种情况。
