### ISSUE TITLE
执行task 命令报错

### ISSUE THREAD

**Issue by didiplus** [whyour/qinglong#1672]
### Qinglong version

v2.14.8

### Steps to reproduce

`root@a0fcc446af0c:/ql $ task  Juejin.py
 开始执行... 2022-10-26 09:31:11

/ql/shell/otask.sh: line 86: [[: 2
8: syntax error in expression (error token is "8")
hello

执行结束... 2022-10-26 09:31:11  耗时 0 秒

　　　　　
root@a0fcc446af0c:/ql $`

### What is expected?

无

### What is actually happening?

无

**Comment by cddjr** [comment]
善用搜索功能，这个是已知问题。
这个下一版修复，不影响使用。
