### ISSUE TITLE
青龙出错

### ISSUE THREAD

**Issue by zhansanku** [whyour/qinglong#1673]
### Qinglong version

最新版本

### Steps to reproduce

/ql/shell/otask.sh: line 86: [[: 4
80
4: syntax error in expression (error token is "80
4")

### What is expected?

/ql/shell/otask.sh: line 86: [[: 4
80
4: syntax error in expression (error token is "80
4")

### What is actually happening?

运行TAASK日志总有个错误，重装也没用

### System Info

```shell
/ql/shell/otask.sh: line 86: [[: 4
80
4: syntax error in expression (error token is "80
4")
```

**Comment by lukemin** [comment]
https://github.com/whyour/qinglong/issues/1661#issuecomment-1288128956

**Comment by whyour** [comment]
与 https://github.com/whyour/qinglong/issues/1661 相同
