### ISSUE TITLE
能否设置conc并发数量？没有的话希望大佬更新一下

### ISSUE THREAD

**Issue by cairong** [whyour/qinglong#1676]
### Clear and concise description of the problem

能否设置conc并发数量？没有的话希望大佬更新一下

### Suggested solution

能否设置conc并发数量？没有的话希望大佬更新一下

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
conc Test 1-20
