### ISSUE TITLE
docker中启动日志中频繁出现报错是否正常

### ISSUE THREAD

**Issue by xmoxmo** [whyour/qinglong#1677]
### Qinglong version

2.14.8

### Steps to reproduce

![image](https://user-images.githubusercontent.com/112841961/198221210-25af667f-691f-49da-b7f2-6f7eb50e1427.png)

### What is expected?

![image](https://user-images.githubusercontent.com/112841961/198221251-a56c160a-4e9a-4da5-9cf3-e56d604b88f5.png)

### What is actually happening?

![image](https://user-images.githubusercontent.com/112841961/198221270-c505bc9d-b5d2-4224-ad44-9e9af8bc3af0.png)

**Comment by lukemin** [comment]
https://github.com/whyour/qinglong/issues/1661#issuecomment-1288128956

**Comment by lukemin** [comment]
同样的问题

**Comment by lukemin** [comment]
/ql/shell/otask.sh: line 86: [[: 7
7
7: syntax error in expression (error token is "7
7")

**Comment by primovist** [comment]
> /ql/shell/otask.sh: line 86: [[: 7
> 
> 7
> 
> 7: syntax error in expression (error token is "7
> 
> 7")
> 
> 
> 
> root@qinglong:/ql $ df -P | grep /dev | grep -v -E '(tmp|boot|shm)' | awk '{print $5}' | cut -f 1 -d "%"
> 
> 7
> 
> 7
> 
> 7
> 
> 
> 
> 

我的是这样

/ql/shell/otask.sh: line 86: [[: 36
36
36: syntax error in expression (error token is "36
36")

**Comment by whyour** [comment]
> ### Qinglong version
> 2.14.8
> 
> ### Steps to reproduce
> ![image](https://user-images.githubusercontent.com/112841961/198221210-25af667f-691f-49da-b7f2-6f7eb50e1427.png)
> 
> ### What is expected?
> ![image](https://user-images.githubusercontent.com/112841961/198221251-a56c160a-4e9a-4da5-9cf3-e56d604b88f5.png)
> 
> ### What is actually happening?
> ![image](https://user-images.githubusercontent.com/112841961/198221270-c505bc9d-b5d2-4224-ad44-9e9af8bc3af0.png)
> 
> ### System Info
> _No response_
> 
> ### Any additional comments?
> _No response_

你这是有个定时任务的规则有问题

**Comment by lukemin** [comment]
> > ### Qinglong version
> > 2.14.8
> > ### Steps to reproduce
> > ![image](https://user-images.githubusercontent.com/112841961/198221210-25af667f-691f-49da-b7f2-6f7eb50e1427.png)
> > ### What is expected?
> > ![image](https://user-images.githubusercontent.com/112841961/198221251-a56c160a-4e9a-4da5-9cf3-e56d604b88f5.png)
> > ### What is actually happening?
> > ![image](https://user-images.githubusercontent.com/112841961/198221270-c505bc9d-b5d2-4224-ad44-9e9af8bc3af0.png)
> > ### System Info
> > _No response_
> > ### Any additional comments?
> > _No response_
> 
> 你这是有个定时任务的规则有问题

出错规则是这样的 `33 0-23/4 * * *`，符合要求啊

**Comment by whyour** [comment]
> > > ### Qinglong version
> > > 2.14.8
> > > ### Steps to reproduce
> > > ![image](https://user-images.githubusercontent.com/112841961/198221210-25af667f-691f-49da-b7f2-6f7eb50e1427.png)
> > > ### What is expected?
> > > ![image](https://user-images.githubusercontent.com/112841961/198221251-a56c160a-4e9a-4da5-9cf3-e56d604b88f5.png)
> > > ### What is actually happening?
> > > ![image](https://user-images.githubusercontent.com/112841961/198221270-c505bc9d-b5d2-4224-ad44-9e9af8bc3af0.png)
> > > ### System Info
> > > _No response_
> > > ### Any additional comments?
> > > _No response_
> > 
> > 
> > 你这是有个定时任务的规则有问题
> 
> 出错规则是这样的 `33 0-23/4 * * *`，符合要求吗？

确定是这个？

**Comment by xmoxmo** [comment]
> 

那种规则是不合要求的？
报错附近的规则有像这样的
![image](https://user-images.githubusercontent.com/112841961/198869173-b7efe842-7fd0-44b3-bb6d-ffda1ddec92e.png)
![image](https://user-images.githubusercontent.com/112841961/198869184-9c6f05f9-f8dc-4885-879c-40612c2f1679.png)
![image](https://user-images.githubusercontent.com/112841961/198869199-ebe9af6a-8b94-4571-af5d-3c4640e3abbd.png)

如果是这种有问题，如何修改，或者其他的那种有问题

**Comment by lukemin** [comment]
@whyour fake2的脚本，用2.11.3版本青龙版本，没问题。

**Comment by whyour** [comment]
> > 
> 
> 那种规则是不合要求的？ 报错附近的规则有像这样的 ![image](https://user-images.githubusercontent.com/112841961/198869173-b7efe842-7fd0-44b3-bb6d-ffda1ddec92e.png) ![image](https://user-images.githubusercontent.com/112841961/198869184-9c6f05f9-f8dc-4885-879c-40612c2f1679.png) ![image](https://user-images.githubusercontent.com/112841961/198869199-ebe9af6a-8b94-4571-af5d-3c4640e3abbd.png)
> 
> 如果是这种有问题，如何修改，或者其他的那种有问题

改成6位就行了
