### ISSUE TITLE
运行脚本出现这样，是什么问题？

### ISSUE THREAD

**Issue by jjss520** [whyour/qinglong#168]
开始执行...
Fri May 21 2021 19:22:26 GMT+0800 (中国标准时间)
(node:5453) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5453) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by whyour** [comment]
貌似你网络是不是有点问题

**Comment by jjss520** [comment]
是的，要挂代理才行
