### ISSUE TITLE
希望webhook 通知的webhookBody 支持嵌套对象

### ISSUE THREAD

**Issue by leochen-g** [whyour/qinglong#1681]
### Qinglong version

v2.14.7

### Steps to reproduce

使用`webhook`的时候`webhookBody`只能单层`key：value`，如果`value` 也是一个对象的话就无法使用了，例如下面的`message`字段其实是一个对象，我看代码解析出来的是字符串，所以就无法使用了
```
{
    "apiKey": "apiKey",
    "roomName": "微信每日说",
    "message": {
      "type": 1,
      "content": "文字内容"
    }
  }
```

### What is expected?

希望`webhook` 的`webhookBody`可以支持多层嵌套

### What is actually happening?

实际上是没办法发送这种数据格式的

**Comment by whyour** [comment]
v2.14.9 支持

**Comment by hqb72** [comment]
2024年了, 什么反人类设计啊
