### ISSUE TITLE
什么时候出一版本地部署方案

### ISSUE THREAD

**Issue by nanjingyuhuawuyanzu** [whyour/qinglong#1682]
### Clear and concise description of the problem

什么时候出一版本地部署方案

### Suggested solution

什么时候出一版本地部署方案

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wingser** [comment]
同问，我正尝试开发环境运行。。。。

**Comment by glenq** [comment]
+1 ，大佬有空出一个本地部署方案。

**Comment by wf851128** [comment]
同求一个本地部署方案

**Comment by jy1989** [comment]
docker版本不就可以本地部署么？

**Comment by wingser** [comment]
> 同问，我正尝试开发环境运行。。。。

后悔之前说过开发环境部署了，结果开发大佬就不提供其他本地方案了。开发环境太卡了，还是希望有个本地部署方案。

**Comment by wingser** [comment]
> > 同问，我正尝试开发环境运行。。。。
> 
> 后悔之前说过开发环境部署了，结果开发大佬就不提供其他本地方案了。开发环境太卡了，还是希望有个本地部署方案。

已经搞定了,对照dockerfile文件的步骤,操作一遍就完了,我也懒得写脚本了,部署之后效果好很多,goorm能只用不到20%内存跑起来2.15版本.

和大家简单说下思路吧.
1. 环境安装,依赖包,pnpm等,
2. 拷贝项目,包含两个,一个qinglong,一个qinglong-static
3. 构建,拷贝几个pnpm构建需要的文件,构建出依赖
4. 依赖文件,和静态文件拷贝到项目中.
5. docker入口文件启动项目就可以了.
