### ISSUE TITLE
日志没有输出 为空白

### ISSUE THREAD

**Issue by zry9815** [whyour/qinglong#1683]
### Qinglong version

2.14.8

### Steps to reproduce

![QQ截图20221029182428](https://user-images.githubusercontent.com/67041916/198826297-aaf37692-5d0f-4a04-b015-d002af6486af.png)
执行ql repo 拉库任务 日志一直不显示 如图

### What is expected?

1

### What is actually happening?

1

**Comment by whyour** [comment]
在订阅管理里添加
