### ISSUE TITLE
style：定时任务-视图管理-双滚动条问题

### ISSUE THREAD

**Issue by tnnevol** [whyour/qinglong#1684]
### Qinglong version

v2.14.9

### Steps to reproduce

从全部任务视图切换到新创建的任务视图（这个视图任务要多一些）出现双滚动条样式bug。
![image](https://user-images.githubusercontent.com/28475939/198830649-ba394b56-6919-46fb-9b33-5bdfbd8e5358.png)

### What is expected?

去除外层多余滚动条

### What is actually happening?

视图出现双层滚动条

**Comment by whyour** [comment]
2.14.11修复
