### ISSUE TITLE
http静态链接被浏览器自动升级https无法访问

### ISSUE THREAD

**Issue by Timiyu** [whyour/qinglong#1686]
### Qinglong version

2.14.9

### Steps to reproduce

通过https链接访问时，会导致浏览器自动将http链接升级https，证书失效，无法访问logo.png

### What is expected?

![image](https://user-images.githubusercontent.com/17613068/198840977-819bea5b-7df3-40be-a318-67c4fc5efc85.png)

### What is actually happening?

![image](https://user-images.githubusercontent.com/17613068/198840856-ea2efa23-751b-4a45-a811-c31171701067.png)

**Comment by whyour** [comment]
刷新
