### ISSUE TITLE
环境变量新添加内容在最前面

### ISSUE THREAD

**Issue by keai-1989** [whyour/qinglong#1690]
### Qinglong version

2.10.13

### Steps to reproduce

最近环境变量里新添加的内容，添加后显示在所有内容的底部，但刷新后却在最前面。

前几天才刚刚出现的，之前没有这个情况。

另外就是配置文件里，在有些变量前加 ##屏蔽，但脚本运行依旧识别到该变量

### What is expected?

改问题不仅仅是2.10.13出现过，在另一个x86的nas机子上也出现过，版本号为2.14.8，但情况略微不一样。

当将环境变量的第一行禁用，此时添加的新内容会在最前方出现，如果环境变量的第一行是启动状态，新添加内容则会在最后出现

### What is actually happening?

环境变量新添加内容位置异常

**Comment by whyour** [comment]
使用 2.14.9
