### ISSUE TITLE
Error: Cannot find module '@sindresorhus/is'

### ISSUE THREAD

**Issue by seryte** [whyour/qinglong#1691]
### Qinglong version

v2.14.9

### Steps to reproduce

任何脚本执行都报： Error: Cannot find module '@sindresorhus/is'
在依赖管理中安装了sindresorhus，仍提示Cannot find module '@sindresorhus/is'
<img width="1581" alt="image" src="https://user-images.githubusercontent.com/17977783/198924225-3b83a958-44ff-43ca-a880-7287e01c2e92.png">

```
## 开始执行... 2022-10-31 11:15:19


🔔自动评价, 开始!
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '@sindresorhus/is'
Require stack:
- /ql/data/scripts/node_modules/got/dist/source/create.js
- /ql/data/scripts/node_modules/got/dist/source/index.js
- /ql/data/scripts/okyyds_yyds_master/ql.js
- /ql/data/scripts/okyyds_yyds_master/sendNotify.js
- /ql/data/scripts/okyyds_yyds_master/jd_autocomment.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/data/scripts/node_modules/got/dist/source/create.js:14:14)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/data/scripts/node_modules/got/dist/source/create.js',
    '/ql/data/scripts/node_modules/got/dist/source/index.js',
    '/ql/data/scripts/okyyds_yyds_master/ql.js',
    '/ql/data/scripts/okyyds_yyds_master/sendNotify.js',
    '/ql/data/scripts/okyyds_yyds_master/jd_autocomment.js'
  ]
}


## 执行结束... 2022-10-31 11:15:22  耗时 3 秒
　　　　　
```
![image](https://user-images.githubusercontent.com/17977783/198924522-311611f4-4ded-45cc-a0b4-b2c7c9bbfb6c.png)

### What is expected?

脚本能够正常运行，或者依赖能够自动安装

### What is actually happening?

缺少依赖包

**Comment by seryte** [comment]
> 重新装下 got 试试

@whyour 
error啊
![image](https://user-images.githubusercontent.com/17977783/199869282-442e0089-8f72-4e4e-b091-5beb323832d7.png)

**Comment by whyour** [comment]
> > 重新装下 got 试试
> 
> 
> 
> @whyour 
> 
> error啊
> 
> ![image](https://user-images.githubusercontent.com/17977783/199869282-442e0089-8f72-4e4e-b091-5beb323832d7.png)
> 
> 

面板装啊

**Comment by seryte** [comment]
> > > 重新装下 got 试试
> > 
> > 
> > @whyour
> > error啊
> > ![image](https://user-images.githubusercontent.com/17977783/199869282-442e0089-8f72-4e4e-b091-5beb323832d7.png)
> 
> 面板装啊

@whyour 装了没有用，仍一样的报错
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/17977783/199873912-c231eb05-944a-4e6e-a72a-d44c085bcf3c.png">

**Comment by iyangpengyu** [comment]
+1

**Comment by iyangpengyu** [comment]
@whyour 问题并未解决
