### ISSUE TITLE
执行一条任务，自动添加了2个冒号

### ISSUE THREAD

**Issue by fatalyang** [whyour/qinglong#1692]
### Qinglong version

2.14.9

### Steps to reproduce

比如在 面板添加 任务   task pip3 install dailycheckin --upgrade   设置好定时等。执行就是下面结果。2.14.7及以前的版本都执行正常没任何问题

## 开始执行... 2022-11-01 15:59:12

通知失败(Unexpected token 
 in JSON at position 102)
ERROR: unknown command ""install"" - maybe you meant "install"

### What is expected?

修复

### What is actually happening?

同Steps to reproduce

### System Info

```shell
root@qinglong:/ql $ npx envinfo --system --binaries --browsers        
  System:
    OS: Linux 4.2 Alpine Linux
    CPU: (2) arm Annapurna Labs Alpine AL212 Dual-core ARM Cortex-A15 CPU @ 1.70GHz
    Memory: 228.78 MB / 1000.34 MB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.1 - /usr/bin/node
    npm: 8.10.0 - /usr/bin/npm
```

**Comment by whyour** [comment]
在依赖管理中添加依赖

**Comment by fatalyang** [comment]
说错了是2个双引号不是冒号。dailycheck等依赖已经添加成功了，不是依赖的问题。同样的装在2.14.7以前的版本执行就没问题啊。
