### ISSUE TITLE
最近都有dailycheckin执行task无法识别第二个参数问题

### ISSUE THREAD

**Issue by zyystudio** [whyour/qinglong#1696]
### Qinglong version

2.14.8 2.14.9

### Steps to reproduce

docker安装好后pip install dailycheckin后执行如下

root@ql:/ql $ task pip install dailycheckin --upgrade
## 开始执行... 2022-11-02 11:41:19

通知失败(Unexpected token 
 in JSON at position 102)
ERROR: unknown command ""install"" - maybe you meant "install"

### What is expected?

以前都是正常执行

### What is actually happening?

无法识别第二个参数

### Any additional comments?

是版本升级后哪里改变了么！谢谢！

**Comment by whyour** [comment]
2.14.10修复
