### ISSUE TITLE
N1

### ISSUE THREAD

**Issue by zhansanku** [whyour/qinglong#1697]
### Qinglong version

青龙崩溃

### Steps to reproduce

PM2 日志面板
[TAILING] Tailing last 500 lines for [panel] process (change the value with --lines option)
/root/.pm2/logs/panel-error.log last 500 lines:
/root/.pm2/logs/panel-out.log last 500 lines:
3|panel    | 2022-10-30T22:32:02: info:    任务 ql raw "https://raw.githubusercontent.com/LinYuanovo/scripts/main/lxzx.js" 进程id: 20466 退出，退出码 0
3|panel    | 2022-10-30T22:32:02: info:    任务 ql raw "https://raw.githubusercontent.com/leafTheFish/DeathNote/main/gqcq_wx.js" 进程id: 20478 退出，退出码 0
3|panel    | 2022-10-30T22:32:02: info:    任务 ql raw "https://raw.githubusercontent.com/leafTheFish/DeathNote/main/meituan.js" 进程id: 20452 退出，退出码 0
3|panel    | 2022-10-30T22:32:02: info:    任务 ql raw "https://raw.githubusercontent.com/LinYuanovo/scripts/main/mbz.js" 进程id: 20445 退出，退出码 0
3|panel    | 2022-11-02T21:15:18: info:    任务 ql raw " http://23.94.255.219/javascript/qwsj.js" 进程id: 26906 退出，退出码 0
3|panel    | 202-11-02T21:15:44: info:    [取消interval任务]，任务ID: 3，任务名：删除日志
3|panel    | 2022-11-02T21:15:44: info:    [创建interval任务]，任务ID: 3，任务名: 删除日志，执行命令: ql rmlog 4
3|panel    | 2022-11-02T21:21:18: info:    任务 ql rmlog 4 进程id: 26981 退出，退出码 0
3|panel    | 2022-11-02T21:21:56: info:    [取消定时任务]，任务名：1
3|panel    | 2022-11-02T21:22:29: info:    任务 task raw_main_elm.js 进程id: 10804 退出，退出码 0
3|panel    | 2022-11-02T21:22:30: info:    任务 task raw_main_mbz.js 进程id: 10865 退出，退出码 0
3|panel    | 2022-11-02T21:23:01: info:    任务 task raw_main_meituan.js 进程id: 10739 退出，退出码 0
3|panel    | 2022-11-02T21:26:22: info:    任务 task raw_main_mbz.js 进程id: 10987 退出，退出码 0
3|panel    | 2022-11-02T21:38:00: info:    任务 task raw_main_meituan.js 进程id: 11140 退出，退出码 0
3|panel    | 2022-11-02T21:40:31: info:    任务 task raw_main_mbz.js 进程id: 11224 退出，退出码 0
3|panel    | 2022-11-02T21:47:51: info:    任务 task raw_main_elm.js 进程id: 11071 退出，退出码 0
3|panel    | 2022-11-02T21:53:48: info:    任务 task raw_main_elm.js 进程id: 11323 退出，退出码 0

### What is expected?

1

### What is actually happening?

间接性的会崩溃，N1盒子op系统里的docker搭建的

**Comment by whyour** [comment]
日志看着没问题
