### ISSUE TITLE
新版本青龙怎么去屏蔽某些CK不执行任务

### ISSUE THREAD

**Issue by rollingmea** [whyour/qinglong#1700]
### Qinglong version

2.14.9

### Steps to reproduce

一直在用2.11的版本，升级到最新后发现不能屏蔽CK执行任务了。
##         ;;

这个命令在新版中没有生效，设置后还是全部的CK在运行。

### What is expected?

怎么能跳过部分CK

### What is actually happening?

功能失效？

**Comment by whyour** [comment]
青龙自身不支持此功能
