### ISSUE TITLE
能否固定PY版本

### ISSUE THREAD

**Issue by shange1993** [whyour/qinglong#1707]
### Clear and concise description of the problem

能不能更改PY版本呢！或者说PY版本能不能固定呢，每次更新新版本的青龙PY版本也更新到最新，但是一些脚本或者依赖对PY最新版本并不支持，导致脚本无法运行

### Suggested solution

能否给python固定版本，或者可以给一个环境变量，如export python="3.10" 类似这样定义PY版本呢！我记得以前频道有一个问卷调查，貌似大部分的人希望能够固定，但是这个功能始终未实现，比较遗憾

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sdhzwc** [comment]
> ### Clear and concise description of the problem
> 能不能更改PY版本呢！或者说PY版本能不能固定呢，每次更新新版本的青龙PY版本也更新到最新，但是一些脚本或者依赖对PY最新版本并不支持，导致脚本无法运行
> 
> ### Suggested solution
> 能否给python固定版本，或者可以给一个环境变量，如export python="3.10" 类似这样定义PY版本呢！我记得以前频道有一个问卷调查，貌似大部分的人希望能够固定，但是这个功能始终未实现，比较遗憾
> 
> ### Alternative
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Validations
> * [x]  Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

作者已经给出了Dockfile,可以自己指定alpine-python版本进行构建

**Comment by shange1993** [comment]
> > ### 清晰简洁地描述问题
> > 能不能更改PY版本呢！或者说PY版本能不能固定呢，每次更新新版本的青龙PY版本也更新到最新，但是一些脚本或者依赖对PY最新版本并不支持，导致脚本无法运行
> > ### 建议的解决方案
> > 能否给python固定版本，或者可以给一个环境变量，如export python=“3.10” 类似这样定义PY版本呢！我记得以前频道有一个问卷调查，貌似大部分的人希望能够固定，但是这个功能始终未实现，比较遗憾
> > ### 另类
> > _无响应_
> > ### 其他上下文
> > _无响应_
> > ### 验证
> > 
> > * [x] 检查是否还没有请求相同功能的问题，以避免创建重复项。
> 
> 作者已经给出了Dockfile，可以自己指定alpine-python版本进行构建

并非每个人都有那么高的专业知识和能力去构建使用，有能力的完全能二次开发使用，但是使用者大部分都是普通人而已，很抱歉我也属于普通人的范畴，不会自行构建

**Comment by ji5261** [comment]
有没有办法降级py版本呢？

**Comment by heimawsw** [comment]
https://github.com/whyour/qinglong/issues/1717

我想升级PY版本。。。
