### ISSUE TITLE
ck数量显示异常

### ISSUE THREAD

**Issue by kid-oh** [whyour/qinglong#1708]
### Qinglong version

v2.14.12

### Steps to reproduce

通过全选变量-批量导出env.json后，将env.json导入新的同版本青龙面板后运行脚本会显示：“当前总共 1 个 JD_COOKIE。优先固定账号数量不得大于或等于有效账号总量，本次暂不重组 Cookie ...”。但所有ck可以按默认顺序跑完执行的脚本，就是不能通过脚本对ck进行调序，因为会显示“只有一个JD_COOKIE”

### What is expected?

排查是哪方面的原因

### What is actually happening?

ck调序脚本无法正常运行

**Comment by whyour** [comment]
面板负责导入成功，任务里提示几个都是脚本管的，自己排查
