### ISSUE TITLE
环境变量已删除，可是不生效还是使用了环境变量

### ISSUE THREAD

**Issue by goodwenhao** [whyour/qinglong#1710]
### Qinglong version

2.11.3

### Steps to reproduce

在config.sh里配置的

### What is expected?

这是版本bug吗？

### What is actually happening?

发现很多次这样了。

**Comment by goodwenhao** [comment]
感觉是缓存到哪里，重启容器才行，变量才删除掉

**Comment by whyour** [comment]
最新版试试
