### ISSUE TITLE
[建议]支持pushdeer自架版本

### ISSUE THREAD

**Issue by chenyinhf** [whyour/qinglong#1711]
### Clear and concise description of the problem

希望在qinglong的未来的版本支持pushdeer自架版本推送。

### Suggested solution

写死的api作为配置项配置即可，但是增加了很多的灵活性。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
2.15.1 支持
