### ISSUE TITLE
SequelizeDatabaseError SQLITE_ERROR: no such column: filterRelation

### ISSUE THREAD

**Issue by hgh188** [whyour/qinglong#1712]
### Qinglong version

2.15

### Steps to reproduce

SequelizeDatabaseError SQLITE_ERROR: no such column: filterRelation

### What is expected?

SequelizeDatabaseError SQLITE_ERROR: no such column: filterRelation

### What is actually happening?

SequelizeDatabaseError SQLITE_ERROR: no such column: filterRelation

**Comment by whyour** [comment]
强制更新下

**Comment by hgh188** [comment]
> 
pm2 logs panel
[TAILING] Tailing last 500 lines for [panel] process (change the value with --lines option)
/root/.pm2/logs/panel-out.log last 500 lines:

**Comment by hgh188** [comment]
强制更新后直接报废

**Comment by hgh188** [comment]
pm2 logs panel
[TAILING] Tailing last 500 lines for [panel] process (change the value with --lines option)
/root/.pm2/logs/panel-out.log last 500 lines:
1|panel    | 2022-11-14T22:13:55: info:    ✌️ DB load failed
1|panel    | 2022-11-14T22:13:55: info:    SQLITE_ERROR: table Subscriptions_backup has 23 columns but 24 values were supplied
1|panel    | 2022-11-14T22:13:55: info:    ✌️ Init file down
1|panel    | 2022-11-14T22:13:56: info:    ✌️ Sentry loaded
1|panel    | 2022-11-14T22:13:59: info:    ✌️ Dependency Injector loaded
1|panel    | 2022-11-14T22:13:59: info:    ✌️ Express loaded
1|panel    | 2022-11-14T22:21:07: info:    ✌️ DB load failed
1|panel    | 2022-11-14T22:21:07: info:    SQLITE_ERROR: table Subscriptions_backup has 23 columns but 24 values were supplied
1|panel    | 2022-11-14T22:21:07: info:    ✌️ Init file down
1|panel    | 2022-11-14T22:21:08: info:    ✌️ Sentry loaded
1|panel    | 2022-11-14T22:21:19: info:    ✌️ Dependency Injector loaded
1|panel    | 2022-11-14T22:21:19: info:    ✌️ Express loaded

**Comment by whyour** [comment]
> pm2 logs panel [TAILING] Tailing last 500 lines for [panel] process (change the value with --lines option) /root/.pm2/logs/panel-out.log last 500 lines: 1|panel | 2022-11-14T22:13:55: info: ✌️ DB load failed 1|panel | 2022-11-14T22:13:55: info: SQLITE_ERROR: table Subscriptions_backup has 23 columns but 24 values were supplied 1|panel | 2022-11-14T22:13:55: info: ✌️ Init file down 1|panel | 2022-11-14T22:13:56: info: ✌️ Sentry loaded 1|panel | 2022-11-14T22:13:59: info: ✌️ Dependency Injector loaded 1|panel | 2022-11-14T22:13:59: info: ✌️ Express loaded 1|panel | 2022-11-14T22:21:07: info: ✌️ DB load failed 1|panel | 2022-11-14T22:21:07: info: SQLITE_ERROR: table Subscriptions_backup has 23 columns but 24 values were supplied 1|panel | 2022-11-14T22:21:07: info: ✌️ Init file down 1|panel | 2022-11-14T22:21:08: info: ✌️ Sentry loaded 1|panel | 2022-11-14T22:21:19: info: ✌️ Dependency Injector loaded 1|panel | 2022-11-14T22:21:19: info: ✌️ Express loaded

你改订阅了？多更新几次？不行远程下
