### ISSUE TITLE
服务器资源异常怎么关闭推送？

### ISSUE THREAD

**Issue by TTCLB** [whyour/qinglong#1714]
服务器资源异常怎么关闭推送？

**Comment by dgnabob** [comment]
我也想知道，服务器资源异常一弹就好几个，希望可以设置是否需要推送。

**Comment by dgnabob** [comment]
本来那一刻系统资源就紧张，这么一大串推送，反而令系统资源更紧张。

**Comment by nibazshab** [comment]
这是什么情况？以前没有提示服务器资源异常啊，现在老是提示

**Comment by edison0354** [comment]
已知可以手动拉高阈值，但我也想知道怎么彻底关掉

## 资源告警阙值，默认CPU 80%、内存80%、磁盘90%
CpuWarn=80
MemoryWarn=80
DiskWarn=90

**Comment by whyour** [comment]
这是瞬间的，可以在config里设置参数大于100就可以关闭了
