### ISSUE TITLE
建议增加项目管理和文件管理图片预览功能

### ISSUE THREAD

**Issue by bitxx** [whyour/qinglong#1716]
### Clear and concise description of the problem

增加文件管理器。项目管理器的图片预览功能

### Suggested solution

现在无法阅读图片，缺少图片预览功能，此功能实际上还是挺重要的。有一些项目产生的图片比如二维码需要预览一下。比如我需要扫码登陆时产生一个二维码。然后生成了一个图片储存在了本地，这时就可以去文件管理查看这张图片。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by HuanLinMaster** [comment]
可以自行pr一个 这个功能看起来比较好实现
