### ISSUE TITLE
青龙内python版本升级

### ISSUE THREAD

**Issue by heimawsw** [whyour/qinglong#1717]
### Qinglong version

2.15.0

### Steps to reproduce

青龙面板刚安装了最新版本，进入容器后 发现python版本是3.11
想把python版本升级到3.9

请问有什么方法吗？

### What is expected?

python版本升级到3.9

### What is actually happening?

python版本

### System Info

```shell
python版本
```

**Comment by fujie-xiyou** [comment]
你管这叫升级吗

**Comment by heimawsw** [comment]
> 你管这叫升级吗

那叫什么。。。。换个python版本

**Comment by areny7** [comment]
你这个叫降版本

**Comment by heimawsw** [comment]
> 你这个叫降版本

python3.11到3.9    这叫降级？

**Comment by cc9014** [comment]
11比9新，数字也大。当然是降级。如果使用上没有问题，不需要动python版本。

**Comment by heimawsw** [comment]
> 11比9新，数字也大。当然是降级。如果使用上没有问题，不需要动python版本。

擦。。。刚仔细看了一下，我蒙了，谢谢

**Comment by cqmzgg** [comment]
所有到底有没有办法降级
