### ISSUE TITLE
服务器资源占用异常

### ISSUE THREAD

**Issue by MiracleHYH** [whyour/qinglong#1721]
### Qinglong version

2.15.0

### Steps to reproduce

在每天04:32提示cpu占用过高，即使我不在青龙中跑任何脚本。

### What is expected?

不触发警报

### What is actually happening?

 服务器资源异常警告，提示CPU占用超过80%。

### System Info

```shell
服务器资源异常警告

当前CPU占用 82% 内存占用 12% 磁盘占用 6% 
资源占用详情 

 PID     %VSZ  %CPU COMMAND
22970     0%  8% jq -r .message
22993     0%  8% jq -r .message
22990     0%  8% jq -r .code
23009     0%  5% jq -r .code
12526     1%  0% node /ql/static/build/app.js
108     1%  0% node /ql/static/build/public.js
18925     1%  0% node /ql/static/build/schedule.js
28     1%  0% PM2 v5.2.2: God Daemon (/root/.pm2)
83     0%  0% nginx: worker process
```

## 运行环境
Docker版青龙运行在PVE下ubuntu虚拟机中

## 其他工作
根据青龙打印的log并未发现异常进程。且pve的监控记录中，在青龙报告的异常时间段docker宿主ubuntu的CPU占用都在50%以下

**Comment by whyour** [comment]
这是瞬间的，可以在config里设置参数大于100就可以关闭了

**Comment by OwnerCM** [comment]
> 这是瞬间的，可以在config里设置参数大于100就可以关闭了

监控设置100只是不提示了，想问下这几个脚本是做什么用途，是否还可以优化？

**Comment by Declarcall** [comment]
> > 这是瞬间的，可以在config里设置参数大于100就可以关闭了
> 
> 监控设置100只是不提示了，想问下这几个脚本是做什么用途，是否还可以优化？

jq调用相关代码看以下链接

https://github.com/whyour/qinglong/commit/17c50d0c9e8e998342edd34c83df6b2e3c413b0d

这里的jq是用于shell中处理json数据格式的，大概jq本身就比较吃cpu吧。不知道有没有替代方案
