### ISSUE TITLE
任务多后系统承载不行，不定期崩溃，崩溃后无限服务错误，只能重做容器，隔一段时间又崩，无限循环

### ISSUE THREAD

**Issue by liesauer** [whyour/qinglong#1722]
### Qinglong version

v2.14.7

### Steps to reproduce

之前还好好的，没啥毛病，随着更多任务的添加，我就发现端倪了
大概加了6、7个的时候，网页端还能进去，但是会不定期且很频繁弹出服务错误，然后网页会自动刷新，但还能访问
然后继续添加（后面添加的多数是5-20分钟级任务，也有1分钟级，任务时长10-30s），运行一段时间后，目前一天左右，就崩掉了
崩掉后，无论`ql check`还是其他方式都无法恢复，只能重做容器

截图已经能看出系统出现混乱了
1. 我每个任务都自带超时处理，图上跑出十几二十分钟是不可能的
2. 显示的最后运行时间、下次运行时间与设定的定时规则不吻合，完全是无秩序的在跑

![image](https://user-images.githubusercontent.com/8676741/203217210-f5e4aa0e-96e4-4bbf-8b9c-f8f8583864d2.png)

### What is expected?

提高系统健壮性，并发承载能力

### What is actually happening?

隔一段时间无限循环崩溃

**Comment by whyour** [comment]
@liesauer 你脚本，机器配置。任务数，错误日志呢。
你这issue提了等于没提

**Comment by liesauer** [comment]
1. 脚本无法提供，但都是非常简单的node程序，axios请求后做轻量数据处理通知
2. 机器为1C1G，且远未达到硬件瓶颈
![image](https://user-images.githubusercontent.com/8676741/203243452-b58113f4-f0d3-4504-9d1d-404bfc258b8b.png)
![image](https://user-images.githubusercontent.com/8676741/203243552-a00704ac-1831-49fb-942c-897551340363.png)
3. 目前共12个任务，我已经将全部任务改成30分钟级，其余配置全没改过，全自己写的任务，非拉库的
4. 网页提示服务错误时，网页无法读取日志，是空的。目前容器已重置，无保留日志，无法进shell提取，只能等测试30分钟级看看状况先

**Comment by liesauer** [comment]
新容器问题依旧，还是时不时服务异常

`get24hrGainer`任务是30分钟级的，`0 0/30 0-1,8-23 * * ?`，日志出现了好几次是因为我手动执行的

![image](https://user-images.githubusercontent.com/8676741/203249926-b1553507-e6cc-445a-9f29-ee6e0cafa27a.png)

```text
pm2 logs panel
[TAILING] Tailing last 500 lines for [panel] process (change the value with --lines option)
/root/.pm2/logs/panel-error.log last 500 lines:
/root/.pm2/logs/panel-out.log last 500 lines:
1|panel    | 2022-11-22T14:56:38: info:    ✌️ DB loaded
1|panel    | 2022-11-22T14:56:38: info:    ✌️ Init file down
1|panel    | 2022-11-22T14:56:39: info:    ✌️ Sentry loaded
1|panel    | 2022-11-22T14:56:40: info:    ✌️ Dependency Injector loaded
1|panel    | 2022-11-22T14:56:40: info:    ✌️ Express loaded
1|panel    | 2022-11-22T14:56:41: info:    ✌️ init data loaded
1|panel    | 2022-11-22T14:56:41: info:    ✌️ link deps loaded
1|panel    | 2022-11-22T14:56:41: info:    ✌️ init task loaded
1|panel    | 2022-11-22T14:56:41: info:    ✌️ Sock loaded
1|panel    | 2022-11-22T14:56:41: info:    [创建interval任务]，任务ID: NaN，任务名: 生成token，执行命令: ts-node-transpile-only /ql/back/token.ts
1|panel    | 2022-11-22T14:56:41: debug:   ✌️ 后端服务启动成功！
1|panel    | 2022-11-22T14:56:48: info:    任务 ts-node-transpile-only /ql/back/token.ts 进程id: 224 退出，退出码 0
1|panel    | 2022-11-22T15:09:46: info:    任务 task xxx/get24hrGainer.ts 进程id: 1011 退出，退出码 0
1|panel    | 2022-11-22T15:12:17: info:    任务 task xxx/get24hrGainer.ts 进程id: 1181 退出，退出码 0
1|panel    | 2022-11-22T15:16:58: info:    任务 task xxx/get24hrGainer.ts 进程id: 1257 退出，退出码 0
1|panel    | 2022-11-22T15:17:30: info:    任务 task xxx/get24hrGainer.ts 进程id: 1349 退出，退出码 0
1|panel    | 2022-11-22T15:18:26: info:    任务 task xxx/get24hrGainer.ts 进程id: 1425 退出，退出码 0
```

**Comment by whyour** [comment]
> 新容器问题依旧，还是时不时服务异常
> 
> `get24hrGainer`任务是30分钟级的，`0 0/30 0-1,8-23 * * ?`，日志出现了好几次是因为我手动执行的
> 
> ![image](https://user-images.githubusercontent.com/8676741/203249926-b1553507-e6cc-445a-9f29-ee6e0cafa27a.png)
> 
> ```
> pm2 logs panel
> [TAILING] Tailing last 500 lines for [panel] process (change the value with --lines option)
> /root/.pm2/logs/panel-error.log last 500 lines:
> /root/.pm2/logs/panel-out.log last 500 lines:
> 1|panel    | 2022-11-22T14:56:38: info:    ✌️ DB loaded
> 1|panel    | 2022-11-22T14:56:38: info:    ✌️ Init file down
> 1|panel    | 2022-11-22T14:56:39: info:    ✌️ Sentry loaded
> 1|panel    | 2022-11-22T14:56:40: info:    ✌️ Dependency Injector loaded
> 1|panel    | 2022-11-22T14:56:40: info:    ✌️ Express loaded
> 1|panel    | 2022-11-22T14:56:41: info:    ✌️ init data loaded
> 1|panel    | 2022-11-22T14:56:41: info:    ✌️ link deps loaded
> 1|panel    | 2022-11-22T14:56:41: info:    ✌️ init task loaded
> 1|panel    | 2022-11-22T14:56:41: info:    ✌️ Sock loaded
> 1|panel    | 2022-11-22T14:56:41: info:    [创建interval任务]，任务ID: NaN，任务名: 生成token，执行命令: ts-node-transpile-only /ql/back/token.ts
> 1|panel    | 2022-11-22T14:56:41: debug:   ✌️ 后端服务启动成功！
> 1|panel    | 2022-11-22T14:56:48: info:    任务 ts-node-transpile-only /ql/back/token.ts 进程id: 224 退出，退出码 0
> 1|panel    | 2022-11-22T15:09:46: info:    任务 task xxx/get24hrGainer.ts 进程id: 1011 退出，退出码 0
> 1|panel    | 2022-11-22T15:12:17: info:    任务 task xxx/get24hrGainer.ts 进程id: 1181 退出，退出码 0
> 1|panel    | 2022-11-22T15:16:58: info:    任务 task xxx/get24hrGainer.ts 进程id: 1257 退出，退出码 0
> 1|panel    | 2022-11-22T15:17:30: info:    任务 task xxx/get24hrGainer.ts 进程id: 1349 退出，退出码 0
> 1|panel    | 2022-11-22T15:18:26: info:    任务 task xxx/get24hrGainer.ts 进程id: 1425 退出，退出码 0
> ```

日志没有问题，看api返回，或者远程吧，另外检查下你的网络

**Comment by liesauer** [comment]
第一个截图是我按f5刷新页面时刚好碰到然后截图了，然后确实跳转到error页面了，我日志也是在这里复制的

**Comment by whyour** [comment]
/root/.pm2/logs/panel-error.log
/root/.pm2/logs/panel-out.log 

把容器内这两个文件拷出来看看，最后500行日志是没错的。

服务器执行 `npx envinfo --system --binaries --browsers` 也贴出来

**Comment by liesauer** [comment]
[panel-out.log](https://github.com/whyour/qinglong/files/10065174/panel-out.log)
[panel-error.log](https://github.com/whyour/qinglong/files/10065175/panel-error.log)


```
liesauer@VM37850:~$ npx envinfo --system --binaries --browsers
  System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2696 v3 @ 2.30GHz
    Memory: 427.96 MB / 976.82 MB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    npm: 9.1.1 - /usr/local/bin/npm
```

**Comment by whyour** [comment]
按你说运行这么长时间了，就这几行日志？你可以脱敏放出来。从目前日志看，青龙运行没问题。

**Comment by liesauer** [comment]
> 按你说运行这么长时间了，就这几行日志？你可以脱敏放出来。从目前日志看，青龙运行没问题。

确实就这几行，原封不动的拷贝出来

**Comment by whyour** [comment]
> > 按你说运行这么长时间了，就这几行日志？你可以脱敏放出来。从目前日志看，青龙运行没问题。
> 
> 确实就这几行，原封不动的拷贝出来

那只能说明容器运行正常，下次出错的时候看是哪个接口报的错。另外建议更新最新版
