### ISSUE TITLE
开发环境启动报错

### ISSUE THREAD

**Issue by zhuangyong666** [whyour/qinglong#1726]
### Qinglong version

最新版

### Steps to reproduce

![Uploading image.png…]()

### What is expected?

![image](https://user-images.githubusercontent.com/18116324/203576281-61c65b87-da4b-4ffd-82a5-69e45dc93e18.png)

### What is actually happening?

![image](https://user-images.githubusercontent.com/18116324/203576301-5807da50-53d8-4152-bcc7-8c8a8d3fc4a5.png)

**Comment by 1947839940** [comment]
请问你开发环境报错是如何解决的？我目前发现在windows下有这个问题，mac，Linux下没问题

**Comment by whyour** [comment]
windows下没有crontab服务，建议在windows中linux子系统运行
