### ISSUE TITLE
怎么取消服务器异常警告通知

### ISSUE THREAD

**Issue by yeyinghai** [whyour/qinglong#1727]
### Qinglong version

正式版 v2.15.1

### Steps to reproduce

怎么取消服务器异常警告通知

### What is expected?

怎么取消服务器异常警告通知

### What is actually happening?

怎么取消服务器异常警告通知

**Comment by number2021620** [comment]
config.sh里第22行到25行用#注释掉

**Comment by yeyinghai** [comment]
谢谢



在 2022-11-25 04:15:48，"number2021620" ***@***.***> 写道：

config.sh里第22行到25行用#注释掉

**Comment by yeyinghai** [comment]
不对啊







在 2022-11-25 04:15:48，"number2021620" ***@***.***> 写道：

config.sh里第22行到25行用#注释掉

**Comment by number2021620** [comment]
> 

怎么了

**Comment by yeyinghai** [comment]
我的config.sh里面没有报警阈值的代码，缺会报警

**Comment by number2021620** [comment]
> 



> 我的config.sh里面没有报警阈值的代码，缺会报警
牛的，这个有点牛逼

**Comment by number2021620** [comment]
> 我的config.sh里面没有报警阈值的代码，缺会报警

你应该是大规模更改过，你找找，肯定有，不然不会调用的

**Comment by number2021620** [comment]
打开对比更容易找到

**Comment by Seraphwx** [comment]
> 
一样情况，干脆把config删了重新生成。
CpuWarn=80
MemoryWarn=80
DiskWarn=100
代码是有了，注销了一样推送

**Comment by dgnabob** [comment]
作者在已关闭的另一个贴中已回复过了，将config中下面三个阀值设置大于100就可以取消了。
CpuWarn=80
MemoryWarn=80
DiskWarn=100
