### ISSUE TITLE
2.15.1 新版本脚本管理无法在网页载入

### ISSUE THREAD

**Issue by number2021620** [whyour/qinglong#1728]
### Qinglong version

2.15.1

### Steps to reproduce

保留了原文件

容器指令
docker run -dit \
  -v $PWD/ql:/ql/data \（原-v $PWD/ql/data:/ql/data \）
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest

没法正常访问脚本管理scripts

提示：ENOENT: no such file or directory, stat '/ql/data/scripts/�����ظ�����.js'

### What is expected?

无法打开脚本管理

### What is actually happening?

提示ENOENT: no such file or directory, stat '/ql/data/scripts/�����ظ�����.js'

### System Info

```shell
我家云openwrt flippy 6.0.9-78+
docker
```

### Any additional comments?

求助，虽然还是可以正常使用，但是就是没法在网页打开脚本管理

**Comment by whyour** [comment]
你这文件名有问题
