### ISSUE TITLE
cookie无法识别问题

### ISSUE THREAD

**Issue by JohnHa0** [whyour/qinglong#174]
面板上cookie状态都OK，但是任务运行后日志提示请获取账号一的cookie，识别不到面板里的cookie，这是啥原因呢？

====================共0个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/5/23下午1:50:50=====================

**Comment by whyour** [comment]
重启下容器

**Comment by JohnHa0** [comment]
重启还是不行，尝试删除容器也不行，我是不是要把所有全删除重新来啊

Sent from my iPhone

On May 24, 2021, at 2:10 PM, whyour ***@***.***> wrote:

﻿

重启下容器
