### ISSUE TITLE
版本 v2.15.2使用TG推送，全是服务器资源异常警告

### ISSUE THREAD

**Issue by Whattotake** [whyour/qinglong#1743]
### Qinglong version

v2.15.2

### Steps to reproduce

订阅的时候，TG机器人提示正常的拉取XX活动，添加成功
运行中，比如说手动点“京豆详情统计”，TG机器人推送的信息并非是XX账户多少京东，而是一个服务器资源异常警告，如：
服务器资源异常警告

当前CPU占用 24% 内存占用 45% 磁盘占用 98% 
资源占用详情 

 PID     %VSZ  %CPU COMMAND
28838     0%  24% jq -r .message
190     32%  0% node /ql/static/build/app.js
151     30%  0% node /ql/static/build/public.js
28566     30%  0% node /ql/static/build/schedule.js
55     29%  0% PM2 v5.2.2: God Daemon (/root/.pm2)
123     1%  0% nginx: worker process
124     1%  0% nginx: worker process
126     1%  0% nginx: worker process
125     1%  0% nginx: worker process

### What is expected?

想看到正常的内容，不知道是否是版本问题

### What is actually happening?

机器人推送的信息，跟想要的不符合

**Comment by OwnerCM** [comment]
这个问题大佬一直没想到解决办法吗？

**Comment by Declarcall** [comment]
我也遇到这种情况，我的服务器芯片是arm架构的
```
服务器资源异常警告

当前CPU占用 85% 内存占用 36% 磁盘占用 1% 
资源占用详情 

 PID     %VSZ  %CPU COMMAND
15146     0%  17% jq -r .message
15085     13%  14% node jd_jdfactory.js
15190     0%  14% jq -r .code
15139     0%  14% jq -r .message
12450     17%  2% node /ql/static/build/schedule.js
15228     0%  2% top -b -n 1
162     18%  0% node /ql/static/build/app.js
122     17%  0% node /ql/static/build/public.js
27     16%  0% PM2 v5.2.2: God Daemon (/root/.pm2)
```
同问
