### ISSUE TITLE
TG推送异常

### ISSUE THREAD

**Issue by ouyanglong721** [whyour/qinglong#1744]
### Qinglong version

2.15.3

### Steps to reproduce

使用反向代理地址进行tg推送，
![image](https://user-images.githubusercontent.com/52189456/206905398-fd1adda1-ed31-48ed-b146-5d7f3fd898c3.png)

不使用反向代理推送：
![image](https://user-images.githubusercontent.com/52189456/206905418-520034e3-edbb-4536-879d-47dc8a13180b.png)

### What is expected?

TLS异常

脚本报错：
![image](https://user-images.githubusercontent.com/52189456/206905542-bb451941-e80f-4237-aa5b-ca246df91101.png)

### What is actually happening?

无法设置

**Comment by fengmikaelson** [comment]
为什么我pull镜像安装后，访问网页打开面板还是显示2.11啊

**Comment by ouyanglong721** [comment]
@fengmikaelson 手动指定镜像版本就行
