### ISSUE TITLE
定时任务运行：cd folder_name，报错

### ISSUE THREAD

**Issue by lx1054331851** [whyour/qinglong#1751]
### Qinglong version

 v2.15.3

### Steps to reproduce

定时任务运行：cd folder_name，报错：timeout: failed to run command ‘cd’: No such file or directory
但是定时任务设置成：ls，就没有问题。
任务设置成：cd /，都报同样的错误

### What is expected?

能正常运行命令

### What is actually happening?

定时任务报错

### System Info

```shell
docker-compose运行
```

**Comment by whyour** [comment]
无法复现，手动输入下
