### ISSUE TITLE
重启总是会自动重置config.sh，有人有同样的问题的吗？

### ISSUE THREAD

**Issue by YonQua** [whyour/qinglong#1753]
### Qinglong version

2.15.3

### Steps to reproduce

重启总是会自动重置config.sh，有人有同样的问题的吗？

### What is expected?

重启总是会自动重置config.sh，有人有同样的问题的吗？

### What is actually happening?

重启总是会自动重置config.sh，有人有同样的问题的吗？

**Comment by tianwulele** [comment]
一样，服务器意外断电重启。 之后config.sh 恢复到了一个月前升级的时候的状态。  我快要炸了

**Comment by whyour** [comment]
启动容器要映射目录，使用最新镜像再观察吧
