### ISSUE TITLE
运行任务日志界面卡住不刷新

### ISSUE THREAD

**Issue by bestruirui** [whyour/qinglong#1758]
### Qinglong version

2.15.3

### Steps to reproduce

这个问题这几天发现的，在这之前一直没有动过青龙，最近几天，任务执行着就卡住

### What is expected?

希望得到解决

### What is actually happening?

有些脚本在运行时，经常卡住不动，表现为一直显示正在运行，但日志不刷新，而且任务也确实没有做。并不是整个容器卡住，而是就是这一个脚本卡住，别的脚本还能正常运行

### System Info

```shell
root@65b29685dbc7:/ql $npx envinfo --system --binaries --browsers
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: Linux 5.15 Alpine Linux
    CPU: (4) x64 Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz
    Memory: 739.61 MB / 3.74 GB
    Container: Yes
    Shell: 5.2.12 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 9.1.2 - /usr/bin/npm

root@65b29685dbc7:/ql $
```

**Comment by bestruirui** [comment]
![IMG_20221227_234018](https://user-images.githubusercontent.com/89796393/209689077-32e4f4d2-e1bd-4db6-9063-e2a28acff95b.jpg)
![IMG_20221227_234122](https://user-images.githubusercontent.com/89796393/209689084-6fe45e70-7a66-4994-b4e0-dd9eed5b2522.jpg)

黑号会直接有报错提示什么的，然后跳过这个账号，继续下一个账号，但现在是，没有报错，没有跳过，直接卡住。

这个bug不是某个脚本，是随机脚本，可能同一个脚本这次
运行会卡住，但下次就好了，也可能这个脚本好好的，下次运行就卡住了

**Comment by whyour** [comment]
无法复现
