### ISSUE TITLE
系统原有定时任务被清空

### ISSUE THREAD

**Issue by zhaoguomanong** [whyour/qinglong#1761]
### Qinglong version

latest

### Steps to reproduce

往文件 /var/spool/cron/crontabs/root 中添加任意一个定时任务
主机直接启动青龙:

pnpm start

稍后会发现/var/spool/cron/crontabs/root 中的原来的定时任务被删除了

### What is expected?

请保留系统原有的cron定时任务

### What is actually happening?

系统定时任务被全部清空

### System Info

ubuntu 18.04
部署方案参考的开发一栏在主机上直接部署:

```shell

$ git clone git@github.com:whyour/qinglong.git
$ cd qinglong
$ cp .env.example .env
# 推荐使用 pnpm https://pnpm.io/zh/installation
$ npm install -g pnpm
$ pnpm install
$ pnpm start

```

### Any additional comments?

只要/var/spool/cron/crontabs/root 文件里面有如下记录后，原来的任务就被删光了

```
# (/opt/qinglong/data/config/crontab.list installed on Wed Dec 28 17:19:08 2022)

```

_No response_

**Comment by lq-259** [comment]
青龙的 cron数据是放在db里面又放到crontab.list里面再更新进系统的cron里 被清空是必然的 要么把你的任务放青龙里要么用容器
