### ISSUE TITLE
SSL UNSAFE_LEGACY_RENEGOTIATION_DISABLED 升级后部分脚本错误

### ISSUE THREAD

**Issue by zxerqw** [whyour/qinglong#1765]
### Qinglong version

 v2.15.3

### Steps to reproduce

升级之后一些py或者js脚本都出现了这个ssl错误

### What is expected?

HTTPSConnectionPool(host='enjoy.test.com', port=443): Max retries exceeded with url: /status (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))

### What is actually happening?

![image](https://user-images.githubusercontent.com/16666177/209942742-19eccd12-8b33-4ced-b537-43fc7b4c07f9.png)

**Comment by whyour** [comment]
使用最新镜像重建吧  docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>

**Comment by zxerqw** [comment]
更新到版本v2.15.5了还是这样，我电脑用node v18跑也是这个问题，降到v16倒是没问题, python也是，降级后没问题。不过这个好像目前只出现在农行的网址上
![image](https://user-images.githubusercontent.com/16666177/210906396-428c435e-3ba6-4f52-b2d3-981e1fe40459.png)

**Comment by whyour** [comment]
> 更新到版本v2.15.5了还是这样，我电脑用node v18跑也是这个问题，降到v16倒是没问题, python也是，降级后没问题。不过这个好像目前只出现在农行的网址上 ![image](https://user-images.githubusercontent.com/16666177/210906396-428c435e-3ba6-4f52-b2d3-981e1fe40459.png)

```py
import urllib3
from urllib3.util.ssl_ import create_urllib3_context

ctx = create_urllib3_context()
ctx.load_default_certs()
ctx.options |= 0x4  # ssl.OP_LEGACY_SERVER_CONNECT

with urllib3.PoolManager(ssl_context=ctx) as http:
    r = http.request("GET", "https://nomads.ncep.noaa.gov/")
    print(r.status)
```
可以试试，这部分是 openssl 3.0的限制，openssl 1.1.1 9月就不维护了
https://github.com/urllib3/urllib3/issues/2653

**Comment by zxerqw** [comment]
感谢，修改了一下可以了

**Comment by dreamfly32** [comment]
1,脚本管理，新建文件：openssl.conf
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Options = UnsafeLegacyRenegotiation

2，环境变量，添加：OPENSSL_CONF=/ql/data/scripts/openssl.conf

**Comment by zxerqw** [comment]
添加后试了试nodejs没效果啊

`reason: write EPROTO 68E12BE3207F0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:ssl/statem/extensions.c:893:`
