### ISSUE TITLE
手动添加定时任务不执行

### ISSUE THREAD

**Issue by lx1054331851** [whyour/qinglong#1766]
### Qinglong version

 v2.15.3

### Steps to reproduce

1. 新建test.sh
![image](https://user-images.githubusercontent.com/12423206/209966198-4087389d-4e51-498d-851e-7ecdff6dcc72.png)

2. 测试脚本
![image](https://user-images.githubusercontent.com/12423206/209966292-b669d5be-6026-4e51-bf8d-dfff6b177679.png)

3. 设置定时任务
![image](https://user-images.githubusercontent.com/12423206/209967121-7b4c0b0d-67d7-4ad1-8887-6023106cba24.png)

4. 过了几分钟，一直不运行
![image](https://user-images.githubusercontent.com/12423206/209968116-6b6e9afe-5298-4750-9937-9372537e9713.png)

5. docker里也没有任何日志
6. 点击定时任务管理界面右侧的运行按钮，可以运行
![image](https://user-images.githubusercontent.com/12423206/209970406-4360c80e-8d0e-46cd-a527-a311a5a19dc5.png)

### What is expected?

让脚本运行起来

### What is actually happening?

定时任务不运行

**Comment by whyour** [comment]
需要使用 task 执行 sh 文件，py/js/sh 文件都用 task 执行，并且 /ql/data/scripts 目录可以省略

**Comment by whyour** [comment]
2.15.5 已支持
