### ISSUE TITLE
环境变量页面列表添加占满屏后闪屏

### ISSUE THREAD

**Issue by OwnerCM** [whyour/qinglong#1767]
### Qinglong version

2.15.4

### Steps to reproduce

环境变量列表添加到超过一页后，滚动条不断闪动

### What is expected?

环境变量列表添加到超过一页后，滚动条不断闪动

### What is actually happening?

环境变量列表添加到超过一页后，滚动条不断闪动

**Comment by whyour** [comment]
@OwnerCM 建议使用 chrome 浏览器

**Comment by OwnerCM** [comment]
> @OwnerCM 建议使用 chrome 浏览器

我使用的是edge浏览器，和chrome内核一样，可能我的问题遇到的人不多吧！我现在是网页缩放让页面不到一屏这样可用解决这个闪屏问题。
简单看了下应该是计算页面高度，处理页面多滚动条的方法有问题

**Comment by whyour** [comment]
@OwnerCM windows 的 edge？有截图吗

**Comment by Jone2008** [comment]
Chrome也是一样，把浏览器缩小就正常，全屏就会闪

**Comment by whyour** [comment]
可以录视频看下，这边无法复现

**Comment by OwnerCM** [comment]
> 可以录视频看下，这边无法复现

不知道GitHub怎么直接上传视频，录屏我放到网盘了，需要麻烦下载一下。
地址：[https://wwww.lanzoub.com/iBHVs0kbwzod](url)

**Comment by OwnerCM** [comment]
https://user-images.githubusercontent.com/22722811/211128524-dfef8a3f-ce97-4680-b041-060ea3861937.mp4



> 可以录视频看下，这边无法复现
请查看录屏，浏览器版本：
Microsoft Edge
版本 108.0.1462.54 (正式版本) (64 位)

**Comment by whyour** [comment]
> 

我下载了 edge 还是没法稳定复现，会突然闪一下，你进来就一直闪了？

**Comment by whyour** [comment]
有时间可以远程下

**Comment by OwnerCM** [comment]
> > 
> 
> 我下载了 edge 还是没法稳定复现，会突然闪一下，你进来就一直闪了？

进页面就一直闪屏，可能没法给大佬远程了，我已经退回2.13老版本了
