### ISSUE TITLE
Nodejs依赖无法安装

### ISSUE THREAD

**Issue by anzhefun** [whyour/qinglong#1769]
### Qinglong version

2.15.4

### Steps to reproduce

使用面板里面安装依赖中的NODE所有依赖

### What is expected?

解决这个问题

### What is actually happening?

开始安装依赖 moment，开始时间 2023-01-04 00:07:20

For help, run: pnpm help add

依赖安装失败，结束时间 2023-01-04 00:07:21，耗时 1 秒
或者是提示类似CLI没有写入权限的话术

**Comment by whyour** [comment]
容器内执行 ql check
