### ISSUE TITLE
助力问题

### ISSUE THREAD

**Issue by YYplus** [whyour/qinglong#177]
老大，问一下像lxk大佬的这种默认内部账号自动互助的脚本，环境变量咋设置，试了好多总是找不到助力码，
`开始获取京东手机狂欢城配置文件

共9个京东账号

您提供了0个账号的京东手机狂欢城助力码`
谢谢

**Comment by lc0088** [comment]
同问，在config.sh里找不到填写互助码的地方，请教详细配置

**Comment by whyour** [comment]
https://t.me/qiongqiya/80
阅读下

**Comment by lc0088** [comment]
该用户名(@qiongqiya)不存在。

**Comment by lc0088** [comment]
> https://t.me/qiongqiya/80
> 阅读下

TG显示 该用户名(@qiongqiya)不存在

**Comment by lc0088** [comment]
![image](https://user-images.githubusercontent.com/77963060/119424450-14388a00-bd38-11eb-8f42-5649e235ebf5.png)

**Comment by whyour** [comment]
@lc0088 https://t.me/qiongqin/80

**Comment by TEAMO233** [comment]
> @lc0088 https://t.me/qiongqin/80

老哥这个用户还是不存在，还能看吗？
