### ISSUE TITLE
【催更】什么时候添加path的支持？静态资源写死了...

### ISSUE THREAD

**Issue by terauu** [whyour/qinglong#1771]
### Clear and concise description of the problem

Nginx想多代理几个服务，静态资源写死了访问资源会404错误

### Suggested solution

希望大佬抽空改一下

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wang-st** [comment]
我也在等这个功能

**Comment by zuoteamleader** [comment]
加一

**Comment by CraKeyBoy** [comment]
+1

**Comment by whyour** [comment]
whyour/qinglong:develop 镜像已经支持，可以测试下
