### ISSUE TITLE
requests 安装上后依然检测不到

### ISSUE THREAD

**Issue by heishanmao** [whyour/qinglong#1772]
### Qinglong version

2.15.5

### Steps to reproduce

![image](https://user-images.githubusercontent.com/16098881/211132577-87a95512-4f1e-46e5-9142-44de5d0a12d5.png)
![image](https://user-images.githubusercontent.com/16098881/211132597-bd1ca940-8f6f-48da-8a91-03ebdd616254.png)
![image](https://user-images.githubusercontent.com/16098881/211132638-9711e4fb-25e7-4809-8a41-b4a970310c35.png)
![image](https://user-images.githubusercontent.com/16098881/211132676-24d5b364-bd2c-4800-9eba-3829eb04f1ea.png)

![image](https://user-images.githubusercontent.com/16098881/211132622-9419a7a2-a7d2-4fff-8cd6-c0385f7e6b35.png)

### What is expected?

requests can not instaleed.

### What is actually happening?

bugs

### System Info

```shell
Alpian docker host
```

**Comment by whyour** [comment]
脚本检查的结果建议找脚本作者
