### ISSUE TITLE
手动点击停止按钮，页面上现实任务停止了，但是任务还在后台执行

### ISSUE THREAD

**Issue by lx1054331851** [whyour/qinglong#1773]
### Qinglong version

 v2.15.5

### Steps to reproduce

手动点击停止按钮，页面上现实任务停止了，但是任务还在后台执行

### What is expected?

点击停止按钮后，任务停止

### What is actually happening?

手动点击停止按钮，页面上现实任务停止了，但是任务还在后台执行

**Comment by lx1054331851** [comment]
bash脚本，bash里面运行的是python脚本。
哦，突然有点明白了。是不是通过bash启动的python脚本的进程已经不是青龙监控的进程ID了，所以是没法终止的？

**Comment by whyour** [comment]
@lx1054331851 最新版是支持的

**Comment by whyour** [comment]
> bash脚本，bash里面运行的是python脚本。 哦，突然有点明白了。是不是通过bash启动的python脚本的进程已经不是青龙监控的进程ID了，所以是没法终止的？

python 脚本不是用 python3/python/task xxx.py 这跟 bash 有啥关系

**Comment by lx1054331851** [comment]
用的scrapy脚本，需要cd到项目目录下执行：scrapy crawl xxx. 只能通过bash脚本实现。
