### ISSUE TITLE
npm安装依赖报错，cpu爆满

### ISSUE THREAD

**Issue by Marblog** [whyour/qinglong#1775]
### Qinglong version

last

### Steps to reproduce

青龙面板执行npm install axios，安装依赖报错，error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/usr/local/share/.cache/yarn/v6/npm-lru-cache-6.0.0-6d6fe6570ebd96aaf90fcad1dafa3b2566db3a94-integrity/node_modules/lru-cache/LICENSE' -> '/ql/node_modules/sequelize/node_modules/lru-cache/LICENSE'".

之后日志一直提示crond[195]: user root: parse error at 7
crond[195]: user root: parse error at 7
crond[195]: user root: parse error at 7

cpu一直爆满状态

### What is expected?

0

### What is actually happening?

0

**Comment by Marblog** [comment]
/usr/local/bin/ql: line 431: /ql/data/log/check/2023-01-12-10-22-13.log: No space left on device

**Comment by PAINCLOWN** [comment]
同样的问题crond[53]: user root: parse error at 7

**Comment by whyour** [comment]
> 同样的问题crond[53]: user root: parse error at 7

忽略

**Comment by whyour** [comment]
> /usr/local/bin/ql: line 431: /ql/data/log/check/2023-01-12-10-22-13.log: No space left on device

没空间了，依赖在依赖管理中装，nodejs依赖填 axios
