### ISSUE TITLE
希望支持下linux/386 架构的docker镜像

### ISSUE THREAD

**Issue by kongwf5813** [whyour/qinglong#1779]
### Clear and concise description of the problem

希望支持下linux/386 架构的docker镜像

### Suggested solution

可以采用docker buildx build来构建不同架构的镜像。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
docker pull whyour/qinglong:test  可以使用这个镜像测试下

**Comment by whyour** [comment]
2.15.7 支持
