### ISSUE TITLE
Error: Cannot find module './ jdCookie.js'

### ISSUE THREAD

**Issue by lc0088** [whyour/qinglong#178]
Error: Cannot find module './ jdCookie.js'

请教大老，docker 日志里，出现这个提示，请问哪里配置不正确？
面板里的coookie验证都是正常的

**Comment by whyour** [comment]
https://t.me/qiongqiya/80
执行示例仓库第一个

**Comment by lc0088** [comment]
该用户名(@qiongqiya)不存在。

**Comment by lc0088** [comment]
> https://t.me/qiongqiya/80
> 执行示例仓库第一个

TG显示  该用户名(@qiongqiya)不存在。

**Comment by lc0088** [comment]
![image](https://user-images.githubusercontent.com/77963060/119424495-26b2c380-bd38-11eb-929e-2f2f5c8b3fbd.png)
