### ISSUE TITLE
环境变量调整到底部刷新后位置不对

### ISSUE THREAD

**Issue by Alone4869** [whyour/qinglong#1780]
### Qinglong version

2.15.3-2.15.5

### Steps to reproduce

1、如果移动已启用的变量到所有变量的最后，刷新之后会跳到已启用变量的倒数第二个
2、如果移动已启用的变量到已启用变量的最后(禁用变量之前)，刷新之后会跳到未知位置，比如我想移到已启用变量最后一个69位，刷新之后跳到了48位

### What is expected?

两种情况都移动到已启用变量的最后一位

### What is actually happening?

移动位置不正确，非预期

**Comment by whyour** [comment]
导出重新导入下
