### ISSUE TITLE
N1使用Docker安装的青龙，依赖安装好，重启容器依赖就会重新自动重新安装。

### ISSUE THREAD

**Issue by ulifuqiang** [whyour/qinglong#1781]
### Qinglong version

 v2.15.5

### Steps to reproduce

一次安装多个依赖。会安装成功，重启容器后，依赖又在自动安装。

### What is expected?

一次安装多个依赖。会安装成功，重启容器后，依赖又在自动安装。

### What is actually happening?

一次安装多个依赖。会安装成功，重启容器后，依赖又在自动安装。

**Comment by whyour** [comment]
没有影响
