### ISSUE TITLE
手机端不能新建脚本

### ISSUE THREAD

**Issue by dreamfly32** [whyour/qinglong#1782]
### Qinglong version

2.15.5

### Steps to reproduce

2.15.5版，脚本管理，点击新建没反应，2.10.13版本是可以的，无论是chrome模拟移动端还是真机via浏览器4.4.7版本都不行，点击新建没反应。
![image](https://user-images.githubusercontent.com/32086491/215248022-0e553bd2-0494-4d54-b392-9aa30481e63d.png)

### What is expected?

弹出创建框

### What is actually happening?

点击新建没反应

**Comment by whyour** [comment]
2.15.7 修复
