### ISSUE TITLE
配置文件总是被清除，恢复成默认的了，是什么问题？

### ISSUE THREAD

**Issue by shangjiazi** [whyour/qinglong#1783]
### Qinglong version

v2.15.5

### Steps to reproduce

配置文件总是被清除，恢复成默认的了，是什么问题？

### What is expected?

配置文件总是被清除，恢复成默认的了，是什么问题？

### What is actually happening?

配置文件总是被清除，恢复成默认的了，是什么问题？

**Comment by creazy412** [comment]
同问
正在想办法找到配置文件路径，进行每天的自动备份配置文件，来弥补被清除的麻烦

**Comment by creazy412** [comment]
> 同问 正在想办法找到配置文件路径，进行每天的自动备份配置文件，来弥补被清除的麻烦

环境变量配置在“db/env.db”文件里

**Comment by whyour** [comment]
无法复现
