### ISSUE TITLE
无法安装python 依赖 cryptg和numpy

### ISSUE THREAD

**Issue by jsdfhasuh** [whyour/qinglong#1784]
### Qinglong version

2.15.2

### Steps to reproduce

在依赖管理里面添加这两个依赖

### What is expected?

应该会安装上的

### What is actually happening?

开始安装依赖 numpy，开始时间 2023-01-30 15:29:07

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting numpy
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ce/b8/c170db50ec49d5845bd771bc5549fe734ee73083c5c52791915f95d8e2bc/numpy-1.24.1.tar.gz (10.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml): started
  Building wheel for numpy (pyproject.toml): finished with status 'error'
Failed to build numpy

依赖安装失败，结束时间 2023-01-30 15:29:24，耗时 16 秒

开始安装依赖 cryptg，开始时间 2023-01-30 22:09:06

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting cryptg
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0d/a1/e4f55e5b22979da39f3afa7c10748e6480ca6f8d94cdf0cb938aa6db1e2d/cryptg-0.4.0.tar.gz (14 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: cryptg
  Building wheel for cryptg (pyproject.toml): started
  Building wheel for cryptg (pyproject.toml): finished with status 'error'
Failed to build cryptg

依赖安装失败，结束时间 2023-01-30 22:09:11，耗时 4 秒

**Comment by Todddday** [comment]
踩了同一个坑，建议换青龙版本，我换了2.13.6是能成功安装了

**Comment by ykk648** [comment]
check https://github.com/whyour/qinglong/issues/1645#issuecomment-1272506522

**Comment by jsdfhasuh** [comment]
> check https://github.com/whyour/qinglong/issues/1645#issuecomment-1272506522

还是不行

**Comment by ykk648** [comment]
> > check [#1645 (comment)](https://github.com/whyour/qinglong/issues/1645#issuecomment-1272506522)
> 
> 还是不行

apk add linux-headers

**Comment by whyour** [comment]
cryptography 和 cryptg 什么区别，装前面的是不是也行

**Comment by jsdfhasuh** [comment]
> cryptography 和 cryptg 什么区别，装前面的是不是也行
我在尝试跑 这个项目https://github.com/kuaizi/telegram_channel_downloader，它标明需要这个依赖
cyptg 这是python 3的一个小c扩展，可以帮助需要 使用Telegram API，它使用不常见的AES-IGE模式
cryptography是用来加密。
两者应该不同

**Comment by whyour** [comment]
> > cryptography 和 cryptg 什么区别，装前面的是不是也行
> > 我在尝试跑 这个项目[https://github.com/kuaizi/telegram_channel_downloader，它标明需要这个依赖](https://github.com/kuaizi/telegram_channel_downloader%EF%BC%8C%E5%AE%83%E6%A0%87%E6%98%8E%E9%9C%80%E8%A6%81%E8%BF%99%E4%B8%AA%E4%BE%9D%E8%B5%96)
> > cyptg 这是python 3的一个小c扩展，可以帮助需要 使用Telegram API，它使用不常见的AES-IGE模式
> > cryptography是用来加密。
> > 两者应该不同

cryptg也是加解密的，你安装前面的试试

**Comment by whyour** [comment]
linux 安装 
```
rust 
cargo
```
