### ISSUE TITLE
执行curl时没有反应

### ISSUE THREAD

**Issue by chenjingchun** [whyour/qinglong#1786]
### Qinglong version

v2.15.6

### Steps to reproduce

此curl在Cronjobs中运行正常
具体测试内容私发给你gmail
![image](https://user-images.githubusercontent.com/4917940/216219025-a1dbff4a-ce94-45aa-bd6a-37f5ee896f1e.png)

### What is expected?

运行成功

### What is actually happening?

没有反应，没有日志

### System Info

```shell
docker安装whyour/qinglong
执行京东的task是可以的
```

**Comment by whyour** [comment]
1. 使用 develop 镜像测试下
2. 过于复杂的命令可以使用脚本管理，添加 shell 脚本执行

**Comment by whyour** [comment]
2.15.7 修复
