### ISSUE TITLE
青龙2.11.3版本升级

### ISSUE THREAD

**Issue by karhow** [whyour/qinglong#1787]
### Qinglong version

2.11.5

### Steps to reproduce

<img width="910" alt="image" src="https://user-images.githubusercontent.com/32405381/216538778-8c924446-20d2-4279-a269-84b0df45f96c.png">
从2.11.3升级到2.15.5，从容器命令行执行的ql update升级方式会失败，然后访问5700端口显示会页面错误；

### What is expected?

请问现在是不能使用命令行ql update 或者页面的检查更新从2.11.3升级到2.15.5吗？

### What is actually happening?

是不是2.11.3之后的版本升级只能通过更改容器镜像，但是2.11.3和之后的2.15后的版本的数据挂载目录是不一样的，这样数据不就丢失了？怎么才可以保留数据从2.11.3升级到2.15之后的版本？

**Comment by karhow** [comment]
@whyour /help

**Comment by whyour** [comment]
新建一个最新版容器，映射 data 目录和原来的 db config scripts 等目录，启动容器

**Comment by karhow** [comment]
thanks
