### ISSUE TITLE
移动端定时任务界面无法横向滚动

### ISSUE THREAD

**Issue by kingsleygithub001** [whyour/qinglong#1788]
### Qinglong version

2.15.6

### Steps to reproduce

移动端chrome登录青龙，选择定时任务菜单

### What is expected?

无法横向滚动查看定时任务列表

### What is actually happening?

定时任务列表可以横向滚动

**Comment by whyour** [comment]
@kingsleygithub001 强制更新下

**Comment by kingsleygithub001** [comment]
> @kingsleygithub001强制更新下

好耶，更新后已修复
