### ISSUE TITLE
update问题 0 6 * * *又来了··

### ISSUE THREAD

**Issue by syfirefox** [whyour/qinglong#179]
update问题 0 6 * * * 脚本重新命名 加了一堆······任务时间都是0 6 * * *

**Comment by Code365Yes** [comment]
面板还默认更新的，神坑

**Comment by x-dr** [comment]
新拉取的任务时间全都是0 6 * * *

**Comment by synoman** [comment]
昨天安装的，按照教程，点了更新，没用啊，定时任务始终只有默认的三项，咋回事？
