### ISSUE TITLE
青龙面板里能安装Git吗

### ISSUE THREAD

**Issue by ghost** [whyour/qinglong#1795]
### Clear and concise description of the problem

想问问，青龙面板里能安装Git吗？我想试试能不能拉取仓库以及推送仓库，以达到自动镜像仓库的能力。

虽然我有脚本，但是觉得可视化管理任务更加直观一些。

### Suggested solution

讨论板块发了一天没人回复，只能到这里来问问了。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
本来就自带 git 的
