### ISSUE TITLE
app.db

### ISSUE THREAD

**Issue by JoeJoeLam** [whyour/qinglong#1797]
### Qinglong version

2.10.13

### Steps to reproduce

面板跑了一段时间，app.db文件夹会变得超级巨大，不知道是啥情况

### What is expected?

app.db能够后限制大小

### What is actually happening?

手动删除后面板重启后无法进入。

### System Info

```shell
CentOS7.6
```

**Comment by whyour** [comment]
@JoeJoeLam 升级最新版

**Comment by JoeJoeLam** [comment]
> 

大神，有没办法无缝升级？

**Comment by whyour** [comment]
> > 
> 
> 大神，有没办法无缝升级？

参考 https://github.com/whyour/qinglong/issues/1787#issuecomment-1415970035
