### ISSUE TITLE
订阅管理增加设置项

### ISSUE THREAD

**Issue by nsv2051** [whyour/qinglong#1798]
### Clear and concise description of the problem

AutoAddCron、AutoDelCron
这两个开关能否转移到所订阅项目的设置项中，针对单一项目进行限制

### Suggested solution

暂无相关设置

### Alternative

暂无能够针对单一项目进行设置的方法

### Additional context

![image](https://user-images.githubusercontent.com/39900381/217413389-80520763-039e-4b6d-95ea-1eb7a07c79d8.png)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
2.15.7 支持
