### ISSUE TITLE
2.15.6版本  ql repo 日志一直显示任务未运行或运行失败，请尝试手动运行，实际上运行成功的

### ISSUE THREAD

**Issue by iboytech** [whyour/qinglong#1801]
### Qinglong version

2.15.6

### Steps to reproduce

在任务列表针对拉库任务点击执行操作

### What is expected?

显示拉库的过程

### What is actually happening?

所有拉库的任务日志都显示任务未运行或运行失败，请尝试手动运行

**Comment by whyour** [comment]
拷贝到订阅管理中
