### ISSUE TITLE
视图管理增加更多一级标签

### ISSUE THREAD

**Issue by OwnerCM** [whyour/qinglong#1804]
### Clear and concise description of the problem

![image](https://user-images.githubusercontent.com/22722811/218026590-fef270d3-e36e-4eb1-a9c1-97665c697707.png)
目前只能放3个标签，其他标签会被折叠隐藏，建议可以开放更多

### Suggested solution

![image](https://user-images.githubusercontent.com/22722811/218026590-fef270d3-e36e-4eb1-a9c1-97665c697707.png)
目前只能放3个标签，其他标签会被折叠隐藏，建议可以开放更多

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sdhzwc** [comment]
同求

**Comment by whyour** [comment]
更多一级意思是变成4个？

**Comment by OwnerCM** [comment]
> 更多一级意思是变成4个？

如果可以根据浏览器的宽度自适应是最好的，如果不行的话建议默认5个吧！
