### ISSUE TITLE
重启青龙后，linux依赖全部安装失败

### ISSUE THREAD

**Issue by jsdfhasuh** [whyour/qinglong#1806]
### Qinglong version

2.15.2

### Steps to reproduce

每一次重启青龙，都会导致linux的依赖全部安装失败，都需要我重新手动点击安装

### What is expected?

安装成功

### What is actually happening?

![image](https://user-images.githubusercontent.com/49879362/218046263-93e25b1d-aa6f-4d11-8273-e9638ff6ac5a.png)
![image](https://user-images.githubusercontent.com/49879362/218046404-ce4ac51a-f9ae-4384-8e7c-03a8aa3114d1.png)

**Comment by whyour** [comment]
容器启动的时候你用其他命令也在安装linux依赖，冲突了

**Comment by jsdfhasuh** [comment]
> 容器启动的时候你用其他命令也在安装linux依赖，冲突了

root@336627d4ebd9:/ql/data/scripts/test $ apk add grep
ERROR: Unable to lock database: temporary error (try again later)
ERROR: Failed to open apk database: temporary error (try again later)
我已经把extra文件里面的都清空，但仍然无法安装
