### ISSUE TITLE
建议增加一个删除存量订阅仓库的功能

### ISSUE THREAD

**Issue by kingsleygithub001** [whyour/qinglong#1807]
### Clear and concise description of the problem

大量订阅以后，以后有的仓库已经不再维护，只能手动到后台删除，可视化和易用性低

### Suggested solution

建议增加一个删除订阅仓库的功能

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
2.16.0 已支持
