### ISSUE TITLE
订阅那里单文件拉下来自动添加的任务执行不了

### ISSUE THREAD

**Issue by iboytech** [whyour/qinglong#1809]
### Qinglong version

2.15.7

### Steps to reproduce

在订阅那里添加单个文件 ql raw https://github.com/xxx/test.js

### What is expected?

自动添加任务后点执行可以运行 ql task raw_test.js

### What is actually happening?

订阅拉取的单文件test.js存放在/ql/data/raw目录下，ql task 执行的是 /ql/data/scripts 的 test.js 文件，而青龙/ql/data/scripts 的 test.js文件内容为空

**Comment by hzexe** [comment]
同样问题
版本：v2.15.7
点击确定按钮后console输出的信息如下 ，似乎是验证的问题:
Validate Failed: 
``` JSON
{
	"values": {
		"type": "file",
		"url": "https://raw.githubusercontent.com/dongfangbeimu/shouji/b66f2ab738c15b9a13559c13658ca7bb72568020/aqc_jk.js",
		"alias": "",
		"schedule_type": "crontab",
		"schedule": "* * 5 * * *",
		"autoAddCron": true,
		"autoDelCron": true
	},
	"errorFields": [{
		"name": ["alias"],
		"errors": [""],
		"warnings": []
	}],
	"outOfDate": false
}
```

**Comment by whyour** [comment]
2.15.8 修复

**Comment by iboytech** [comment]
> 2.15.8 修复

🐂批

**Comment by iboytech** [comment]
> 2.15.8 修复

刚试了一下，订阅那里拉下来的文件还是不能直接执行，文件在/ql/data/script/下的映射内容是空的

**Comment by whyour** [comment]
> > 2.15.8 修复
> 
> 刚试了一下，订阅那里拉下来的文件还是不能直接执行，文件在/ql/data/script/下的映射内容是空的

文件名是不一样的，raw_xxx

**Comment by iboytech** [comment]
> > > 2.15.8 修复
> > 
> > 
> > 刚试了一下，订阅那里拉下来的文件还是不能直接执行，文件在/ql/data/script/下的映射内容是空的
> 
> 文件名是不一样的，raw_xxx
从订阅管理那里拉取单文件
开始下载：https://github.com/liyw0205/Connection-margin-v3-/raw/main/Script/10010.js
保存路径：/ql/data/raw/Script_10010.js
/ql/data/script/ 下的文件名是 raw_Script_10010.js 但是文件里面内容是空的  
/ql/data/raw下 Script_10010.js 内容不为空
实际上订阅管理拉取脚本后自动添加的任务执行的是/ql/data/script/ 下内容为空的脚本
导致无法正常执行

**Comment by whyour** [comment]
@iboytech 文件链接有问题，拷贝重定向后的链接

**Comment by iboytech** [comment]
> @iboytech 文件链接有问题，拷贝重定向后的链接
解决了，感谢大佬
