### ISSUE TITLE
对于面板的备份功能设想

### ISSUE THREAD

**Issue by hzfla** [whyour/qinglong#1813]
### Clear and concise description of the problem

面板好像没有备份功能，搬服务器的时候比较麻烦，希望可以简单的做一下备份和还原功能

### Suggested solution

直接将数据打包，包括脚本，新机器读取即可

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hzfla** [comment]
感谢分享，只是感觉这样没那么方便> 用Docker安装指定的文件夹不就是备份数据吗？把宿主机指定下的目录拷贝到任何机器，重新运行相同配置运行后数据都一样。

**Comment by whyour** [comment]
2.16.0 已支持备份恢复功能
