### ISSUE TITLE
服务器资源异常警告

### ISSUE THREAD

**Issue by hitjob** [whyour/qinglong#1814]
### Qinglong version

 v2.15.7

### Steps to reproduce

不定期发生，有时候服务器长时间无反应，要等jq命令执行完毕才恢复。

### What is expected?

减小资源占用情况

### What is actually happening?

频繁收到服务器资源异常警告：
有时候由于服务器资源占用太多，导致服务器假死，无法连接；
有时候可以连接，查看服务器进程，基本都是几个jq命令在同时运行占用大量cpu资源；
TG里面一样有很多人发现这个问题，但一直都没有解决方案；

![image](https://user-images.githubusercontent.com/84832666/219245343-bac97f90-d02f-4267-8bf5-67742722ab6f.png)
![image](https://user-images.githubusercontent.com/84832666/219245406-39a6a61b-8862-4ad8-9395-4e5d6080a837.png)
![image](https://user-images.githubusercontent.com/84832666/219245444-00cbe89a-6e0f-4d7e-b204-6c97775c3e2f.png)

**Comment by hitjob** [comment]
昨天重装了系统，重装了青龙最新版，没有用原来的配置文件完全重新配置的，还是出现同样情况：
![image](https://user-images.githubusercontent.com/84832666/219523570-687d8829-a8fa-4282-b67a-6e1f48569001.png)

**Comment by erchezhang** [comment]
+1

**Comment by whyour** [comment]
cpu性能太差了吧

**Comment by vision820** [comment]
关不了呀。删除了通知还在推送
