### ISSUE TITLE
v2.15.6无法在线更新

### ISSUE THREAD

**Issue by euzenlee** [whyour/qinglong#1815]
### Qinglong version

v2.15.6

### Steps to reproduce

ql update

### What is expected?

无法更新，开始以为是网络问题，后面发现有 fatal: Out of memory, malloc failed (tried to allocate 524288000 bytes) 的报错。

### What is actually happening?

使用 github 源更新...

开始更新仓库：/ql

Fetching origin
fatal: Out of memory, malloc failed (tried to allocate 524288000 bytes)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin

更新青龙源文件失败，请检查网络...

### System Info

```shell
ARMBIAN 5.44 user-built Ubuntu 18.04.6 LTS 3.14.29
SOC: AMLogic S905

按Dockfile自建的docker
```

**Comment by whyour** [comment]
为什么要自建呢

**Comment by euzenlee** [comment]
> 为什么要自建呢

有建好的arm docker镜像吗？

**Comment by euzenlee** [comment]
> 

不知道为什么，下载只能下到2.10.x 这样子。以为到这个版本后就没有了。

**Comment by whyour** [comment]
docker 源有问题吧

**Comment by whyour** [comment]
docker pull ghcr.io/whyour/qinglong 也可以拉取 github 的

**Comment by euzenlee** [comment]
> docker pull ghcr.io/whyour/qinglong 也可以拉取 github 的
果然可以拉到了。

**Comment by euzenlee** [comment]
下回来是2.15.7，完美运行，还顺利更新到2.15.8 !!
