### ISSUE TITLE
中文Cookie问题

### ISSUE THREAD

**Issue by PACEJJ27** [whyour/qinglong#1817]
### Qinglong version

latest

### Steps to reproduce

因为之前注册的账号是带中文的，所以获取到的pt_bin的值也是带中文，试过了纯英文的cookie请求没问题，带中文的就不行，能不能加一下处理中文的代码，谢谢！

### What is expected?

无法处理中文报错，无法获取到账号信息

### What is actually happening?

无法处理中文报错，无法获取到账号信息

**Comment by whyour** [comment]
不行是什么不行，问题都没描述

**Comment by PACEJJ27** [comment]
就是在环境变量添加的JD_COOKIE提示是没有问题的，pt_pin的值是带中文的
![image](https://user-images.githubusercontent.com/21055456/219937939-5a20cf50-6a73-4528-b2e6-2182f7580e41.png)
然后用了faker2的仓库的脚本，试了一下京豆的统计功能和其他脚本，执行的时候查看日志，提示说cookie有问题。
![image](https://user-images.githubusercontent.com/21055456/219938035-0876e1a8-f42f-4af1-8899-ec09141d6c63.png)

然后自己拿其他账号来试，试过了pt_pin里面的值是纯英文的cookie请求没问题，一单有中文，所有的请求都是失败。
所以想球球大佬能不能加一下处理中文的代码QAQ

**Comment by whyour** [comment]
@PACEJJ27 那找脚本啊，系统肯定是你输入什么就是什么

**Comment by PACEJJ27** [comment]
好吧
