### ISSUE TITLE
升级面板异常会造成密码异常

### ISSUE THREAD

**Issue by seakyqiu** [whyour/qinglong#1819]
### Qinglong version

2.12升级2.84

### Steps to reproduce

升级面板出错，造成无法登陆，一直密码错误，auth的密码已经是初始化的了，建议增加命令重置密码，恢复默认原始密码

### What is expected?

尽快修复

### What is actually happening?

直接在系统点升级的

**Comment by whyour** [comment]
2.84是什么版本，建议看是否是官方镜像，命令查看项目readme
