### ISSUE TITLE
大佬看下，昨天更新了下。显示这个错误。

### ISSUE THREAD

**Issue by abigailpake** [whyour/qinglong#182]
![微信截图_20210525092331](https://user-images.githubusercontent.com/24457300/119426612-1e5c8780-bd3c-11eb-935c-96b551a8d58d.png)
执行 docker exec -it qinglong ql update 显示下面这个错误

Error response from daemon: Container 4423c2236a819a47b658b96ebe7220c2df1e7fe51c3fa0f9319b87be594c2860 is restarting, wait until the container is running

**Comment by whyour** [comment]
> ![微信截图_20210525092331](https://user-images.githubusercontent.com/24457300/119426612-1e5c8780-bd3c-11eb-935c-96b551a8d58d.png)
> 执行 docker exec -it qinglong ql update 显示下面这个错误
> 
> Error response from daemon: Container 4423c2236a819a47b658b96ebe7220c2df1e7fe51c3fa0f9319b87be594c2860 is restarting, wait until the container is running

删了容器重新运行吧
