### ISSUE TITLE
新版本问题

### ISSUE THREAD

**Issue by xn9527** [whyour/qinglong#1822]
### Qinglong version

 正式版 v2.15.8

### Steps to reproduce

我在使用新版本运行js脚本的时候发现，在请求api的时候自动携带cookie，目前不知道是谁么问题。但是相同的代码放到版本2.14.8是可以正常运行的，而且相关的模块版本都一样。以下是我的请求代码
![image](https://user-images.githubusercontent.com/122341186/219989501-097d5965-dd08-4d62-a46e-02d28fc5200b.png)
打印出来的请求参数，自动带上了莫名的参数，很奇怪
![image](https://user-images.githubusercontent.com/122341186/219989617-f57dbc05-ba18-4ed9-b99a-243a303dedb4.png)

### What is expected?

可以帮忙看下是什么问题吗？

### What is actually happening?

谢谢了

**Comment by whyour** [comment]
如果不想有，别用 $.post 请求，换个库试试吧，那不是写了 tough-cookie 加的吗
