### ISSUE TITLE
添加间隔一定时间执行功能，例如每1441分钟执行一次任务

### ISSUE THREAD

**Issue by HaneRo** [whyour/qinglong#1828]
### Clear and concise description of the problem

添加间隔一定时间执行功能，例如每1441分钟执行一次任务

使用场景，需要间隔24小时执行一次，如果使用每天定时执行会因网络或时间误差导致两次执行间隔少于24小时

### Suggested solution

无

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
你这种场景可以脚本内部来延迟执行吧，不管怎么定时都会有你说的网络问题，时间误差不知道你说的是什么

**Comment by HaneRo** [comment]
> 你这种场景可以脚本内部来延迟执行吧，不管怎么定时都会有你说的网络问题，时间误差不知道你说的是什么

这个签到不是一天签一次的，而是间隔24个小时，例如：我在1号的10点03分签到了，那么我在2号的10点03分之前是不能签到的，而因为网络或其他问题导致签到时间有几秒误差导致两次签到之间少于24小时就会签到失败

**Comment by whyour** [comment]
> > 你这种场景可以脚本内部来延迟执行吧，不管怎么定时都会有你说的网络问题，时间误差不知道你说的是什么
> 
> 这个签到不是一天签一次的，而是间隔24个小时，例如：我在1号的10点03分签到了，那么我在2号的10点03分之前是不能签到的，而因为网络或其他问题导致签到时间有几秒误差导致两次签到之间少于24小时就会签到失败

系统不知道你签到成功没有，定时逻辑是根据任务开始时间。这个需求你可以脚本内判断成功后间隔24小时，再次执行
