### ISSUE TITLE
希望添加性能告警的开关

### ISSUE THREAD

**Issue by hzexe** [whyour/qinglong#1829]
### Clear and concise description of the problem

用N1跑的镜像，性能本来就不怎么样，最近因性能频繁告警，pushplus推送功能因频繁消息一直被禁用状态，并且告警一直在发，所以也无法自动恢复。造成所有推送失效。

### Suggested solution

想到的：
1.默认不启用性能检测
2..配置项可以提供关闭性能监测的开关，而不是去研究配置项改成一个很大的数值

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
最新版默认就是关闭的
