### ISSUE TITLE
termux安装失败

### ISSUE THREAD

**Issue by inoyna12** [whyour/qinglong#1831]
### Qinglong version

2.15.8

### Steps to reproduce

![Screenshot_2023-02-28-04-51-08-692_com termux](https://user-images.githubusercontent.com/86736950/221683332-b4d228a1-917a-42a5-a702-2f6cc6e2531a.jpg)
![Screenshot_2023-02-28-04-51-16-817_mark via](https://user-images.githubusercontent.com/86736950/221683347-811900ee-7545-4164-9671-d01fc9b78ad5.jpg)
步骤是按照Dockerfile文件进行安装的，去年2.12版本的时候还可以安装，版本更新过后试了好几次都失败了

### What is expected?

希望出一个安装教程

### What is actually happening?

。。

**Comment by euzenlee** [comment]
按Dockerfile在arm的环境中成功生成过镜像，所以应该是本身硬件、网络环境的原因吧？

**Comment by whyour** [comment]
@inoyna12 你这 ql -l check
