### ISSUE TITLE
自定义通知配置报错

### ISSUE THREAD

**Issue by muziling** [whyour/qinglong#1835]
### Qinglong version

v2.15.9

### Steps to reproduce

自己搞了一个HTTP服务，自定义通知的URL配置
http://192.168.222.200:7778/?from=$title&to=myidddd&content=$content&redirect=
点保存提示Cannot read properties of undefined (reading 'replaceAll')

### What is expected?

保存成功

### What is actually happening?

保存报错

**Comment by whyour** [comment]
2.15.10修复
