### ISSUE TITLE
Docker Npm 初始化同步失败

### ISSUE THREAD

**Issue by ShanshanHY** [whyour/qinglong#1838]
### Qinglong version

2.15.9

### Steps to reproduce

在网络访问registry.npmjs.org不通畅时，初始化docker容器会卡在第一步无法继续

### What is expected?

期望docker容器正常初始化

## 问题排查：
经检查，初始化第一步卡在了`pnpm add -g pm2 ts-node typescript tslib`这条命令上

输入`pnpm get registry` 检查镜像源，显示正常，但在进行手动同步的时候，会有网络超时的 ***WARN***：
``` 
 WARN  GET https://registry.npmjs.org/ts-node error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/pidusage error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/pm2-multimeter error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
```

在arch下使用docker，且使用clash tun模式全局代理并查看logs，同样发现初始化的时候全程使用[官方源](https://registry.npmjs.org/)进行同步

进入docker内部，输入```pnpm install -g```后，依然使用官方源作为默认初始化同步源，只能添加```--registry=[国内镜像]```

## 临时解决方法：
在启动docker容器后，进入容器内部修改[shell/share.sh](https://github.com/whyour/qinglong/blob/develop/shell/share.sh)后，重启容器可正常运行：
```
441 441    # 兼容pnpm@7
442 442    pnpm setup &>/dev/null
443 443    source ~/.bashrc
444      - pnpm install -g &>/dev/null
    444  + pnpm install -g --registry=[国内镜像] &>/dev/null
445 445  
446 446    if [[ -f "$dir_root/db/cookie.db" ]]; then
447 447      echo -e "检测到旧的db文件，拷贝为新db...\n"
448 448      mv $dir_root/db/cookie.db $dir_root/db/env.db
449 449      rm -rf $dir_root/db/cookie.db
450 450      echo
451 451    fi
452 452  
453      - pnpm add -g pm2 ts-node typescript tslib
    453  + pnpm add -g pm2 ts-node typescript tslib --registry=[国内镜像]
454 454  
455 455    git config --global pull.rebase false
```

### System Info

```shell
Ubuntu&Docker(s905l3a)：
  System:
    OS: Linux 6.1 Alpine Linux
    CPU: (4) arm64 ARMv8 Processor rev 4 (v8l)
    Memory: 1.26 GB / 1.90 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.14.2 - /usr/bin/node
    npm: 9.1.2 - /usr/bin/npm
```

### Any additional comments?

更新 docker镜像 后应用新版，修改内容会丢失，所以希望官方可以解决这一问题

**Comment by whyour** [comment]
@ShanshanHY 配置文件 npmmirror 配置镜像源

**Comment by ShanshanHY** [comment]
> @ShanshanHY 配置文件 npmmirror 配置镜像源
```
## 安装python依赖时指定pip源PipMirror="https://pypi.doubanio.com/simple/"

## 安装node依赖时指定npm源NpmMirror="https://registry.npmmirror.com"
```
默认已经指定，但依然无用

**Comment by ShanshanHY** [comment]
> @ShanshanHY 配置文件 npmmirror 配置镜像源

进入docker内部使用```pnpm get registry```和```npm config get registry```都是镜像源，但依然存在上述问题

**Comment by whyour** [comment]
> > @ShanshanHY 配置文件 npmmirror 配置镜像源
> 
> 进入docker内部使用`pnpm get registry`和`npm config get registry`都是镜像源，但依然存在上述问题

最新版是否还有问题

**Comment by whyour** [comment]
2.15.12 已修复

**Comment by LordHumphrey** [comment]
> https://registry.npmmirror.com

我这里还是有这个问题，v2.15.17，容器中镜像配置与配置文件相同。
> root@qinglong:/ql $ npm config get registry
https://registry.npmmirror.com
root@qinglong:/ql $ pnpm get registry
https://registry.npmmirror.com
root@qinglong:/ql $

容器中访问镜像地址，能够获得响应
> root@qinglong:/ql $ curl https://registry.npmmirror.com/
{"last_package":"clinica_amandao","last_package_version":"@uniformdev/canvas-kontent@19.30.1-alpha.5","doc_count":3281986,"doc_version_count":33401725,"download":{"today":10928239,"yesterday":65860075,"samedayLastweek":125079287,"thisweek":10928239,"thismonth":76788314,"thisyear":21141444802,"lastweek":1135833437,"lastmonth":5058299758,"lastyear":35082329272},"update_seq":61029546,"sync_model":"all","

安装依赖提示
> Progress: resolved 0, reused 1, downloaded 0, added 0
Progress: resolved 1, reused 1, downloaded 0, added 0
 WARN  GET https://registry.npmmirror.com/request error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/tsx/-/tsx-3.12.7.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/tsx/-/tsx-3.12.7.tgz error (ERR_SOCKET_TIMEOUT). Will retry in 1 minute. 1 retries left.

**Comment by qian9008** [comment]
同样问题 ，装不上阿  正式版 v2.16.5
