### ISSUE TITLE
订阅时选择interval类型并写一个特别大的数会造成青龙直接卡死，cpu负载直接拉满

### ISSUE THREAD

**Issue by canxin121** [whyour/qinglong#1840]
### Qinglong version

2.15.9

### Steps to reproduce

订阅时选择interval类型并写一个特别大的数

### What is expected?

应该是正常的定时运行

### What is actually happening?

直接卡死，cpu拉满，进不去web界面

### Any additional comments?

建议增加一个不自动运行选项，并限制interval的数值大小

**Comment by whyour** [comment]
设置了多大的
