### ISSUE TITLE
JS脚本调试模式下运行无日志输出

### ISSUE THREAD

**Issue by OwnerCM** [whyour/qinglong#1842]
### Qinglong version

 正式版 v2.15.9

### Steps to reproduce

JS脚本——脚本管理——调试——运行，右侧无任何内容输出，非常不方便，只能写完脚本保存后到任务执行看日志。
前几个版本没有这个问题。

### What is expected?

调试模式下运行右侧输出相关日志

### What is actually happening?

右侧空白，无任何输出

**Comment by whyour** [comment]
刷新下
