### ISSUE TITLE
宿主机关闭ipv6，nginx报错无法启动

### ISSUE THREAD

**Issue by redjumper** [whyour/qinglong#1843]
### Qinglong version

2.15.9

### Steps to reproduce

宿主机关闭ipv6，nginx报错无法启动。2.15.8没有问题

### What is expected?

宿主机禁用ipv6，nginx也能启动

### What is actually happening?

nginx无法启动

### Any additional comments?

nginx错误日志

> 2023/03/10 15:13:24 [notice] 94#94: signal process started
> 2023/03/10 15:13:24 [error] 94#94: open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
> 2023/03/10 15:13:24 [emerg] 95#95: socket() [::]:5700 failed (97: Address family not supported by protocol)

**Comment by whyour** [comment]
为什么要关闭呢

**Comment by redjumper** [comment]
虽然现在tenable和cis提倡开启ipv6，但因为网络中完全没有使用到ipv6，关闭了ipv6
> If dual stack and IPv6 are not used in your environment, IPv6 may be disabled to
> reduce the attack surface of the system

**Comment by WinterBoring** [comment]
我也是同样问题，ubuntu禁用了ipv6，青龙2.15.9就进不到面板，实际是启动成功了的！2.15.8就没问题！看日志就是ipv6的问题，但找不到解决办法，加禁用ipv6的参数也不行

**Comment by xlh001** [comment]
手动禁用容器中/etc/nginx/conf.d/front.conf 配置文件的[::]:5700配置即可。
docker exec -it ql bash
vi /etc/nginx/conf.d/front.conf 
# listen [::]:5700
:wq # 保存
nginx # 启动nginx服务
exit # 退出容器

**Comment by whyour** [comment]
2.15.10修复
