### ISSUE TITLE
脚本无法设置环境变量

### ISSUE THREAD

**Issue by jiumoshou** [whyour/qinglong#1844]
### Qinglong version

2.11.3

### Steps to reproduce

AttributeError: module 'os' has no attribute 'setenv'

### What is expected?

脚本不应该支持设置环境变量，供整体脚本使用吗

### What is actually happening?

脚本不应该支持设置环境变量，供整体脚本使用吗

**Comment by whyour** [comment]
请更新到最新版

**Comment by jiumoshou** [comment]
版本已更新依然如此，版本号：2.15.9


 File "/ql/data/scripts/arthury/login.swap.py", line 61, in login
    os.setEnv("arthury_authorization", authorization)
AttributeError: module 'os' has no attribute 'setEnv'. Did you mean: 'getenv'?

**Comment by whyour** [comment]
> 版本已更新依然如此，版本号：2.15.9
> 
> File "/ql/data/scripts/arthury/login.swap.py", line 61, in login os.setEnv("arthury_authorization", authorization) AttributeError: module 'os' has no attribute 'setEnv'. Did you mean: 'getenv'?

自己查询 python os 模块的 api
