### ISSUE TITLE
日志归档问题

### ISSUE THREAD

**Issue by zhengjiacheng** [whyour/qinglong#1845]
### Clear and concise description of the problem

问题：现在看起来日期文件存放是按照每次运行来存放的，只看到了清理间隔时间的配置，没有发现有归档相关的配置，这样的话如果一个任务每分钟都会运行，就会产生海量的文件。脚本多起来了全文筛查日志关键词很不方便。

### Suggested solution

建议：可否增加一个归档配置？比如按照每天产生一个文件、或者一个文件大小在多大的阈值后，再生成第二个文件，每个文件按照索引顺序0、1、2、3这样归档。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
不是很理解这个功能具体作用，日志永久保留？而不是删除？

**Comment by zhengjiacheng** [comment]
> 不是很理解这个功能具体作用，日志永久保留？而不是删除？

现有的定时清理有阈值就可以，举例：现在的日志管理->打开后一个执行任务会产生一个日志目录，每次执行都会产生一个日志文件，一个任务5分钟执行一次，一天1440分钟，就会产生288个文件，如果想全文检索当日的日志内容，就得自己用脚本定时将碎片文件归档到一个文件中，是这个意思～大佬

**Comment by whyour** [comment]
> 

是不是日志管理需要一个搜索日志内容的功能
