### ISSUE TITLE
脚本无法设置环境变量

### ISSUE THREAD

**Issue by jiumoshou** [whyour/qinglong#1848]
### Qinglong version

2.15.9

### Steps to reproduce

File "/ql/data/scripts/arthury/login.swap.py", line 60, in login
    os.setEnvEnv("arthury_authorization", authorization)
AttributeError: module 'os' has no attribute 'setEnvEnv'

### What is expected?

脚本不应该支持设置环境变量，供整体脚本使用吗

### What is actually happening?

脚本不应该支持设置环境变量，供整体脚本使用吗

**Comment by whyour** [comment]
@jiumoshou 这跟系统有啥关系python 的os模块没有这个方法啊，去查查os api吧
