### ISSUE TITLE
手机端管理APP

### ISSUE THREAD

**Issue by FuShengPing** [whyour/qinglong#1851]
### Clear and concise description of the problem

青龙面板网页在手机端操作不是很方便，很早之前就看到有人提议作者出个手机APP。

### Suggested solution

将网页版功能移至到手机APP上，提供便捷操作。

### Alternative

我也看到网上有人针对此开发了app，但功能点非常有限，并且代码不开源，用户可能对安全性存在顾虑。因此，我基于2.10.13版本的API开发了一款APP，基本支持面板所有原生功能，并且还提供了额外的拓展模块。APP代码开源，用户可以选择下载安装包或者源码自行构建。

[gitee](https://gitee.com/wsfsp4/QingLong)
[github](https://github.com/FuShengPing/android-qinglong)

### Additional context

<img src="https://gitee.com/wsfsp4/QingLong/raw/master/static/imgs/preview_1.jpg" width="20%">
<img src="https://gitee.com/wsfsp4/QingLong/raw/master/static/imgs/preview_2.jpg" width="20%">
<img src="https://gitee.com/wsfsp4/QingLong/raw/master/static/imgs/preview_3.jpg" width="20%">

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
就支持旧版本的安卓，这是什么意思
