### ISSUE TITLE
最新版Docker启动后报错Error: Please install sqlite3 package manually

### ISSUE THREAD

**Issue by Vision0220** [whyour/qinglong#1856]
### Qinglong version

v2.15.10

### Steps to reproduce

下载docker image，使用docker或docker compose拉起，进入5700页面直接报错
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/48614196/226151233-a2d8b7a0-6684-4d7b-8ee4-1145fa0e9f41.png">

### What is expected?

在docker image中包含sqlite3组件

### What is actually happening?

系统无法运行

**Comment by whyour** [comment]
ql -l check
