### ISSUE TITLE
青龙读取环境字符串长度超了怎么处理呢

### ISSUE THREAD

**Issue by ww176883** [whyour/qinglong#1859]
### Qinglong version

2.15.8

### Steps to reproduce

... 59298 more characters,青龙读取环境字符串长度超了怎么处理呢

### What is expected?

青龙读取环境字符串长度超了

### What is actually happening?

我有几百个同名ck,读取出来只显示前几个... 59298 more characters,我就没法分割出所有的

**Comment by whyour** [comment]
这是你所用打印方法问题，查询相关能完整打印的api   或者写进文件去看文件吧
