### ISSUE TITLE
请问大佬，carinvalcity.js互助码env_name是JD818_SHARECODES吗？var_name、name_config赋值分别是什么？

### ISSUE THREAD

**Issue by cjh19831115** [whyour/qinglong#186]
想用ql code 导出互助吗，始终提升该脚本未运行，实际上name_js=chinnkarahoi_jd_carnivalcity已经运行。不懂求教？

**Comment by whyour** [comment]
@cjh19831115 最新版的是  chinnkarahoi_jd_scripts_jd_carnivalcity 避免同一个作者多仓库

**Comment by cjh19831115** [comment]
env_name=JD818_SHARECODES对吗？
var_name=ForOtherCarni还是ForOtherCarnival?
name_config=Carni还是carnival?

**Comment by cjh19831115** [comment]
> @cjh19831115 最新版的是 chinnkarahoi_jd_scripts_jd_carnivalcity 避免同一个作者多仓库

多谢提示，已经改过了，谢谢
