### ISSUE TITLE
青龙拉取项目之后,定时任务不执行,手动执行没问题.

### ISSUE THREAD

**Issue by wingser** [whyour/qinglong#1861]
### Qinglong version

v2.15.0

### Steps to reproduce

拉取项目后,手动执行,看日志,都正常.
![image](https://user-images.githubusercontent.com/13481389/226586210-87d52ed4-6fb7-462c-8be0-9c168bb5f6ff.png)

### What is expected?

但是调整时间到下一分钟观察日志,没有执行脚本,日志也没有输出.
查看后端服务,状态也都是正常的.
![image](https://user-images.githubusercontent.com/13481389/226586614-ee9c2e9c-bb8b-42b8-9744-a8de9ff8993b.png)

### What is actually happening?

后台执行ql check 日志如下.
[rs.log](https://github.com/whyour/qinglong/files/11027524/rs.log)

### Any additional comments?

求大神帮忙看看,到底是哪里的问题.

**Comment by whyour** [comment]
用最新镜像重建下容器
