### ISSUE TITLE
用API修改变量返回celebrate request validation failed

### ISSUE THREAD

**Issue by longhao1987** [whyour/qinglong#1862]
### Qinglong version

2.11.3

### Steps to reproduce

![1679473502192](https://user-images.githubusercontent.com/37317006/226842662-345aad97-471a-4b10-b767-b1cb0ccff9ce.png)
![1679473510506](https://user-images.githubusercontent.com/37317006/226842684-58d4c5e6-42ba-48a4-a142-781439521efd.png)

### What is expected?

希望能够修改环境变量

### What is actually happening?

{
	"code": 500,
	"message": "celebrate request validation failed"
}

**Comment by whyour** [comment]
参数有误，可以使用最新版试试
