### ISSUE TITLE
能否添加设置，使环境变量的顺序不做调整

### ISSUE THREAD

**Issue by yemingjkl** [whyour/qinglong#1864]
### Clear and concise description of the problem

每次在cookie被禁用之后，顺序都会改变，不能按照预期的顺序跑任务

### Suggested solution

能否添加设置固定环境变量位置，使环境变量的顺序不做任何调整的选项，禁用之后仍保持在原有的位置，不选择该选项则环境变量随现有逻辑调整

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
取消禁用会恢复原来的位置
