### ISSUE TITLE
最新版的在Arm架构的设备上面，无法安装依赖，云端也没有生成日志文件

### ISSUE THREAD

**Issue by Whys8182** [whyour/qinglong#1866]
### Qinglong version

v2.15.10

### Steps to reproduce

从零安装

### What is expected?

修复安装依赖的问题，

### What is actually happening?

安装完依赖，不能用，也不显示。

**Comment by whyour** [comment]
无法安装什么依赖？一点错误没有？

**Comment by Whys8182** [comment]
不知道文件在服务器的哪里，全服务器都搜索不到这些脚本，但面板却可以加载。只是加载的速度特别慢，而且服务器里日志也是空的，关于任务的开启，运行进程日志，也不能马上看到，需要等一会儿才有。比起旧版，问题多了太多了。
![例子参数](https://user-images.githubusercontent.com/96385676/228462256-dc814934-aef5-428c-b0be-d40c081812b4.png)
![例子截图1](https://user-images.githubusercontent.com/96385676/228462274-757eb501-487d-45ed-8a6d-5ef824a1f95a.png)
![例子截图2](https://user-images.githubusercontent.com/96385676/228462300-36af458f-1b2b-4dc1-a9ed-036dc47d55df.png)

**Comment by whyour** [comment]
你都用脚本安装依赖了，还管依赖管理有没有，生不生效检查你 脚本安装方式吧
没有文件，检查你映射目录，容器内的文件在  /ql/data/ 目录下

**Comment by Whys8182** [comment]
我的这个目录文件是空的，我也不知道为什么

在 2023年3月29日，下午10:43，whyour ***@***.***> 写道：

﻿

你都用脚本安装依赖了，还管依赖管理有没有，生不生效检查你 脚本安装方式吧
没有文件，检查你映射目录，容器内的文件在 /ql/data/ 目录下
