### ISSUE TITLE
青龙容器镜像怎么迁移

### ISSUE THREAD

**Issue by Will-Dong** [whyour/qinglong#1868]
### Qinglong version

2.11.3

### Steps to reproduce

想将qinglong docker容器从虚拟机A迁移到虚拟机B
试了docker export和docker save去迁移，在虚拟机B启动容器后是初始化的青龙环境
请问有什么好办法可以带用户数据迁移？

### What is expected?

如上

### What is actually happening?

如上

**Comment by whyour** [comment]
把映射的目录拷贝过去，新容器用相同映射
