### ISSUE TITLE
青龙  v2.15.10 任务分页数量有问题

### ISSUE THREAD

**Issue by elunez** [whyour/qinglong#1869]
### Qinglong version

2.15.10

### Steps to reproduce

在全部任务中，筛选空闲中的任务。

### What is expected?

得到的应该是总的空闲中任务的数量和页数

### What is actually happening?

实际得到的是全部任务的数量和页数，后面的页数内容都是空数据

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/42142420/228737780-c5cd5fca-57d4-438c-9096-55c05bb96f5c.png">

**Comment by whyour** [comment]
不能复现，你这什么浏览器

**Comment by whyour** [comment]
不能复现，你这什么浏览器

**Comment by elunez** [comment]
> 不能复现，你这什么浏览器

谷歌，我明天录个视频

**Comment by elunez** [comment]
已录屏

https://user-images.githubusercontent.com/42142420/229301473-ec321dfa-274e-40bd-8ee1-5d19d8b5ea1e.mp4

> 不能复现，你这什么浏览器

**Comment by whyour** [comment]
下个版本 修复

**Comment by whyour** [comment]
2.15.12 已修复
