### ISSUE TITLE
更新后所有任务被清空

### ISSUE THREAD

**Issue by wpcsx** [whyour/qinglong#1871]
### Qinglong version

111

### Steps to reproduce

各位大佬，为什么每次我的青龙自动更新后，我所有的设置全部都被清空了？？这个这么解决

### What is expected?

升级后保留个人设置

### What is actually happening?

每次升级后

**Comment by cn0068** [comment]
我的也是，全都被清空了。好不容易设置的。

**Comment by whyour** [comment]
认真映射目录   -v $PWD/ql/data:/ql/data \
