### ISSUE TITLE
我的青龙面板无法连接网络

### ISSUE THREAD

**Issue by hw1481826110** [whyour/qinglong#1874]
### Qinglong version

最新版

### Steps to reproduce

![image](https://user-images.githubusercontent.com/30165316/229328521-9e23b543-4335-4a04-95b6-8e44a19695d8.png)
无法连接网络，依赖包也安装不了 不知道怎么解决

### What is expected?

正常使用网络

### What is actually happening?

不知道

**Comment by whyour** [comment]
依赖包安装报什么错

**Comment by hw1481826110** [comment]
> 依赖包安装报什么错

开始安装依赖 json，开始时间 2023/4/2 下午12:18:10

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))': /simple/json/

WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))': /simple/json/

WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))': /simple/json/

WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))': /simple/json/

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))': /simple/json/

Could not fetch URL https://pypi.org/simple/json/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/json/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))) - skipping

ERROR: Could not find a version that satisfies the requirement json (from versions: none)

ERROR: No matching distribution found for json

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))) - skipping

依赖安装失败，结束时间 2023/4/2 下午12:18:29，耗时 19.145 秒

**Comment by jokerknight** [comment]
一样的问题，docker 部署，没有抓包工具，挺奇怪
