### ISSUE TITLE
更新报错

### ISSUE THREAD

**Issue by zhang52ren** [whyour/qinglong#1875]
### Qinglong version

2.12.1

### Steps to reproduce

docker进入终端bash，命令更新

### What is expected?

更新青龙

### What is actually happening?

开始更新系统/ql/shell/api.sh: line 4: syntax error near unexpected token `<<<'
/ql/shell/api.sh: line 4: `<<<<<<< HEAD'
/usr/local/bin/ql: line 391: syntax error near unexpected token `<<<'
/usr/local/bin/ql: line 391: `<<<<<<< HEAD'

### System Info

```shell
系统报错如上
```

### Any additional comments?

期待官方解决

**Comment by whyour** [comment]
用最新镜像重建吧，你这自己改过系统文件
