### ISSUE TITLE
青龙配置了通知方式为邮箱，计划任务脚本执行不通知

### ISSUE THREAD

**Issue by ChinaParrot** [whyour/qinglong#1876]
### Qinglong version

v2.15.11

### Steps to reproduce

青龙配置了通知方式为邮箱，接收到了测试邮件，计划任务脚本执行不通知。

我看日志是
Node 环境 尝试加载 sendNotify
sendNotify 文件: /ql/data/scripts/sendNotify.js
Node 环境 将使用 sendNotify

### What is expected?

怎么配置才能收到邮件通知？config.sh 也配置了。也不能够生效，配置的是qq邮箱。

### What is actually happening?

计划任务脚本执行邮箱配置不通知。

**Comment by ChinaParrot** [comment]
## 14. SMTP
## 暂时只支持在 Python 中调用 notify.py 以发送 SMTP 邮件通知
## smtp_server 填写 SMTP 发送邮件服务器，形如 smtp.exmail.qq.com:465
export SMTP_SERVER="smtp.qq.com:465"
## smtp_ssl 填写 SMTP 发送邮件服务器是否使用 SSL，内容应为 true 或 false
export SMTP_SSL="true"
## smtp_email 填写 SMTP 收发件邮箱，通知将会由自己发给自己
export SMTP_EMAIL="xxx@qq.com"
## smtp_password 填写 SMTP 登录密码，也可能为特殊口令，视具体邮件服务商说明而定
export SMTP_PASSWORD="xxx"
## smtp_name 填写 SMTP 收发件人姓名，可随意填写
export SMTP_NAME="联通沃派余额查询"

**Comment by whyour** [comment]
要使用系统内置的 sendnotify 文件，你这明显不是，系统内置的没有 `Node 环境 尝试加载 sendNotify` 这种提示

**Comment by ChinaParrot** [comment]
> 要使用系统内置的 sendnotify 文件，你这明显不是，系统内置的没有 `Node 环境 尝试加载 sendNotify` 这种提示

具体有没配置文档

**Comment by chenmiao1991** [comment]
后来有解决吗
