### ISSUE TITLE
v2.15.10 LINUX下的依赖无法安装

### ISSUE THREAD

**Issue by wmusic** [whyour/qinglong#1878]
### Clear and concise description of the problem

v2.15.10 LINUX下的依赖无法安装
bizCode
bizMsg
lxml

依赖安装失败，请问如何解决。

### Suggested solution

无

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
https://github.com/whyour/qinglong/issues/1645#issuecomment-1272506522
