### ISSUE TITLE
自动执行任务的时候不能立即执行，需要手动添加 now

### ISSUE THREAD

**Issue by elunez** [whyour/qinglong#1879]
### Clear and concise description of the problem

命令未添加 "now"，随机延迟 146 秒后执行

有时候一些需要立即执行的活动，由于随机执行机制，可能错过豆子

### Suggested solution

能不能添加一个变量，可以控制定时任务立即执行，或者使用随机延迟对手秒执行。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
## 默认给javascript任务加随机延迟，如 RandomDelay="300" ，表示任务将在 1-300 秒内随机延迟一个秒数，然后再运行，取消延迟赋值为空
RandomDelay="300"
