### ISSUE TITLE
用python:3.10-slim构建后，容器一直restarting

### ISSUE THREAD

**Issue by wu695208428** [whyour/qinglong#1880]
由于Alpine中ddddocr库无法安装，故使用python:3.10-slim构建
`docker logs -f qinglong`
`请先访问5700端口，登录成功面板之后再执行添加定时任务...
############################################################

./docker/docker-entrypoint.sh: line 59: crond: command not found
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

======================2. 安装依赖========================

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动面板监控========================

[32m[PM2] [39mStarting /ql/static/build/public.js in fork_mode (1 instance)
[32m[PM2] [39mDone.
[90m┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐[39m
[90m│[39m[1m[36m id [39m[22m[90m│[39m[1m[36m name               [39m[22m[90m│[39m[1m[36m mode     [39m[22m[90m│[39m[1m[36m ↺    [39m[22m[90m│[39m[1m[36m status    [39m[22m[90m│[39m[1m[36m cpu      [39m[22m[90m│[39m[1m[36m memory   [39m[22m[90m│[39m
[90m├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤[39m
[90m│[39m[1m[36m [1m[36m0[39m[36m[22m[1m  [39m[22m[90m│[39m public             [90m│[39m [7m[1mfork[22m[27m     [90m│[39m 0    [90m│[39m [32m[1monline[22m[39m    [90m│[39m 0%       [90m│[39m 35.5mb   [90m│[39m
[90m└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘[39m
监控服务启动成功...

======================5. 启动主服务========================

[32m[PM2] [39mStarting /ql/static/build/app.js in fork_mode (1 instance)
[32m[PM2] [39mDone.
[90m┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐[39m
[90m│[39m[1m[36m id [39m[22m[90m│[39m[1m[36m name               [39m[22m[90m│[39m[1m[36m mode     [39m[22m[90m│[39m[1m[36m ↺    [39m[22m[90m│[39m[1m[36m status    [39m[22m[90m│[39m[1m[36m cpu      [39m[22m[90m│[39m[1m[36m memory   [39m[22m[90m│[39m
[90m├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤[39m
[90m│[39m[1m[36m [1m[36m1[39m[36m[22m[1m  [39m[22m[90m│[39m panel              [90m│[39m [7m[1mfork[22m[27m     [90m│[39m 0    [90m│[39m [32m[1monline[22m[39m    [90m│[39m 0%       [90m│[39m 3.3mb    [90m│[39m
[90m│[39m[1m[36m [1m[36m0[39m[36m[22m[1m  [39m[22m[90m│[39m public             [90m│[39m [7m[1mfork[22m[27m     [90m│[39m 0    [90m│[39m [32m[1monline[22m[39m    [90m│[39m 200%     [90m│[39m 74.2mb   [90m│[39m
[90m└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘[39m
主服务启动成功...

======================6. 启动定时任务========================

[32m[PM2] [39mStarting /ql/static/build/schedule.js in fork_mode (1 instance)
[32m[PM2] [39mDone.
[90m┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐[39m
[90m│[39m[1m[36m id [39m[22m[90m│[39m[1m[36m name               [39m[22m[90m│[39m[1m[36m mode     [39m[22m[90m│[39m[1m[36m ↺    [39m[22m[90m│[39m[1m[36m status    [39m[22m[90m│[39m[1m[36m cpu      [39m[22m[90m│[39m[1m[36m memory   [39m[22m[90m│[39m
[90m├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤[39m
[90m│[39m[1m[36m [1m[36m1[39m[36m[22m[1m  [39m[22m[90m│[39m panel              [90m│[39m [7m[1mfork[22m[27m     [90m│[39m 0    [90m│[39m [32m[1monline[22m[39m    [90m│[39m 150%     [90m│[39m 78.5mb   [90m│[39m
[90m│[39m[1m[36m [1m[36m0[39m[36m[22m[1m  [39m[22m[90m│[39m public             [90m│[39m [7m[1mfork[22m[27m     [90m│[39m 0    [90m│[39m [32m[1monline[22m[39m    [90m│[39m 0%       [90m│[39m 88.0mb   [90m│[39m
[90m│[39m[1m[36m [1m[36m2[39m[36m[22m[1m  [39m[22m[90m│[39m schedule           [90m│[39m [7m[1mfork[22m[27m     [90m│[39m 0    [90m│[39m [32m[1monline[22m[39m    [90m│[39m 0%       [90m│[39m 15.9mb   [90m│[39m
[90m└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘[39m
定时任务启动成功...

======================8. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...

请先访问5700端口，登录成功面板之后再执行添加定时任务...
############################################################

./docker/docker-entrypoint.sh: line 59: crond: command not found
`

这是Dockerfile
`FROM python:3.10-slim as builder 
COPY package.json .npmrc pnpm-lock.yaml /tmp/build/
RUN apt update && apt upgrade -y && apt install curl -y
#RUN set -x \&& sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \                          && sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - 
RUN apt install -y nodejs
RUN set -x \
    && apt-get update \
    && apt-get install -y --no-install-recommends git \
    && npm i -g pnpm \
    && cd /tmp/build \
    && pnpm install --prod

FROM python:3.10-slim

ARG QL_MAINTAINER="whyour"
LABEL maintainer="${QL_MAINTAINER}"
ARG QL_URL=https://kgithub.com/${QL_MAINTAINER}/qinglong.git
ARG QL_BRANCH=develop

ENV PNPM_HOME=/root/.local/share/pnpm \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules:$PNPM_HOME \
    NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules \
    LANG=zh_CN.UTF-8 \
    SHELL=/bin/bash \
    PS1="\u@\h:\w \$ " \
    QL_DIR=/ql \
    QL_BRANCH=${QL_BRANCH}

RUN set -x \&& sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
&& sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list \
    && apt-get update  \
    && apt-get upgrade -y \
    && apt-get --no-install-recommends -y install bash \
                                                  coreutils \
                                                  moreutils \
                                                  git \
                                                  curl \
                                                  wget \
                                                  tzdata \
                                                  perl \
                                                  openssl \
                                                  nginx \
                                                  jq \
                                                  openssh-client \
curl \
&& curl -fsSL https://deb.nodesource.com/setup_16.x | bash - &&\
apt-get install -y nodejs\
    && rm -rf /var/cache/apt/* \
    && apt-get update \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && git config --global user.email "qinglong@@users.noreply.github.com" \
    && git config --global user.name "qinglong" \
    && git config --global http.postBuffer 524288000 \
    && npm install -g pnpm \
    && pnpm add -g pm2 ts-node typescript tslib \
    && rm -rf /root/.pnpm-store \
    && rm -rf /root/.local/share/pnpm/store \
    && rm -rf /root/.cache \
    && rm -rf /root/.npm

ARG SOURCE_COMMIT
RUN git clone -b ${QL_BRANCH} ${QL_URL} ${QL_DIR} \
    && cd ${QL_DIR} \
    && cp -f .env.example .env \
    && chmod 777 ${QL_DIR}/shell/*.sh \
    && chmod 777 ${QL_DIR}/docker/*.sh \
    && git clone -b ${QL_BRANCH} https://kgithub.com/${QL_MAINTAINER}/qinglong-static.git /static \
    && mkdir -p ${QL_DIR}/static \
    && cp -rf /static/* ${QL_DIR}/static \
    && rm -rf /static

COPY --from=builder /tmp/build/node_modules/. /ql/node_modules/

WORKDIR ${QL_DIR}
    
ENTRYPOINT ["./docker/docker-entrypoint.sh"]
`

**Comment by whyour** [comment]
./docker/docker-entrypoint.sh: line 59: crond: command not found

**Comment by wu695208428** [comment]
> ./docker/docker-entrypoint.sh: line 59: crond: command not found

请问这要怎么改？是改成cron吗😂😂

**Comment by whyour** [comment]
> > ./docker/docker-entrypoint.sh: line 59: crond: command not found
> 
> 请问这要怎么改？是改成cron吗😂😂

你都自己构建了，你去查下 slim 里的定时任务包

**Comment by wu695208428** [comment]
> > > ./docker/docker-entrypoint.sh: line 59: crond: command not found
> > 
> > 
> > 请问这要怎么改？是改成cron吗😂😂
> 
> 你都自己构建了，你去查下 slim 里的定时任务包

将docker-entrypoint.sh内的crond -f 替换成service cron restart后好像没报错了，但是还是restarting，容器logs如下：
`======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

======================2. 安装依赖========================


======================3. 启动nginx========================

nginx启动成功...

======================4. 启动面板监控========================

[PM2] Starting /ql/static/build/public.js in fork_mode (1 instance)
[PM2] Done.
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ public             │ fork     │ 0    │ online    │ 0%       │ 32.5mb   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
监控服务启动成功...

======================5. 启动主服务========================

[PM2] Starting /ql/static/build/app.js in fork_mode (1 instance)
[PM2] Done.
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 1  │ panel              │ fork     │ 0    │ online    │ 0%       │ 4.0kb    │
│ 0  │ public             │ fork     │ 0    │ online    │ 100%     │ 69.0mb   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
主服务启动成功...

======================6. 启动定时任务========================

[PM2] Starting /ql/static/build/schedule.js in fork_mode (1 instance)
[PM2] Done.
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 1  │ panel              │ fork     │ 0    │ online    │ 150%     │ 77.7mb   │
│ 0  │ public             │ fork     │ 0    │ online    │ 0%       │ 89.1mb   │
│ 2  │ schedule           │ fork     │ 0    │ online    │ 0%       │ 4.0kb    │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
定时任务启动成功...

======================8. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...

请先访问5700端口，登录成功面板之后再执行添加定时任务...
############################################################`

**Comment by whyour** [comment]
那块需要个前台进程，你 restart ，容器没有执行完就结束了

**Comment by wu695208428** [comment]
> 那块需要个前台进程，你 restart ，容器没有执行完就结束了
感谢👍
解决方法：
```
1、构建时要 apt install cron
2、修改docker-entrypoint.sh中68行：
/usr/sbin/cron -f  >/dev/null
```
