### ISSUE TITLE
IPV6无法访问

### ISSUE THREAD

**Issue by z940407** [whyour/qinglong#1884]
### Qinglong version

2.15.11

### Steps to reproduce

在群晖Dokcer上安装的
启动后通过局域网IP:5700能正常访问
之后在外面通过IPV6无法正常访问
群晖上其他软件通过IPV是可以正常访问的

### What is expected?

IPV6能正常访问

### What is actually happening?

不知

**Comment by whyour** [comment]
容器内执行 ip a 看是否有 ipv6 地址，如果有 执行 ql check 下，如果没有说明没开启容器 ipv6 访问
