### ISSUE TITLE
blacklist不能是文件的问题

### ISSUE THREAD

**Issue by maYunLaoXi** [whyour/qinglong#1886]
### Clear and concise description of the problem

blacklist如果是目录是生效的，但是如果写文件名则无效

版本:2.11.3

### Suggested solution

建议加入排除文件的功能

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
文件也是生效的，可以使用最新版尝试
