### ISSUE TITLE
定时任务中定时规则设置秒后无法自动运行

### ISSUE THREAD

**Issue by OwnerCM** [whyour/qinglong#1887]
### Qinglong version

2.15.11

### Steps to reproduce

定时任务中定时规则设置秒后无法自动运行，已确认规则设置正确，且设置在分钟可以正常运行。
青龙重启可以解决

### What is expected?

定时任务中定时规则设置秒后无法自动运行，已确认规则设置正确，且设置在分钟可以正常运行。
青龙重启可以解决

### What is actually happening?

定时任务中定时规则设置秒后无法自动运行，已确认规则设置正确，且设置在分钟可以正常运行。
青龙重启可以解决

**Comment by whyour** [comment]
ql check 下
