### ISSUE TITLE
日志不正常

### ISSUE THREAD

**Issue by 839777408** [whyour/qinglong#1889]
### Qinglong version

2.15.11

### Steps to reproduce

脚本点击运行后查看日志，日志还是以前的，在日志最下方打印了/ql/shell/api.sh: line 9: tsx: command not found，而且任务的最后运行时间一直不会更新

### What is expected?

正常显示日志

### What is actually happening?

显示不正常

**Comment by whyour** [comment]
ql check 下，这是本地运行的？

**Comment by 839777408** [comment]
> ql check 下，这是本地运行的？

本地的，ql check中的执行任务都是失败，例如
2023-04-07T21:09:07: info:    [执行任务失败] tsx /ql/back/token.ts，时间：2023/4/7 下午9:09:07, 错误信息："/bin/bash: tsx: command not found\n"
2023-04-07T21:09:07: info:    [执行任务失败] SUB_ID=1 ql repo "https://github.com/KingRan/KR.git" "jd_|jx_|jdCookie" "activity|backUp" "^jd[^_]|USER|utils|function|sign|sendNotify|ql|JDJR" "" "" "" "true" "true"，时间：2023/4/7 下午9:09:07, 错误信息："/ql/shell/api.sh: line 9: tsx: command not found\n"

后面的报错：
2023-02-02T00:33:29: Error: Please install sqlite3 package manually

**Comment by whyour** [comment]
> > ql check 下，这是本地运行的？
> 
> 本地的，ql check中的执行任务都是失败，例如 2023-04-07T21:09:07: info: [执行任务失败] tsx /ql/back/token.ts，时间：2023/4/7 下午9:09:07, 错误信息："/bin/bash: tsx: command not found\n" 2023-04-07T21:09:07: info: [执行任务失败] SUB_ID=1 ql repo "https://github.com/KingRan/KR.git" "jd_|jx_|jdCookie" "activity|backUp" "^jd[^_]|USER|utils|function|sign|sendNotify|ql|JDJR" "" "" "" "true" "true"，时间：2023/4/7 下午9:09:07, 错误信息："/ql/shell/api.sh: line 9: tsx: command not found\n"
> 
> 后面的报错： 2023-02-02T00:33:29: Error: Please install sqlite3 package manually

本地重装下项目依赖

**Comment by whyour** [comment]
> > > ql check 下，这是本地运行的？
> > 
> > 
> > 本地的，ql check中的执行任务都是失败，例如 2023-04-07T21:09:07: info: [执行任务失败] tsx /ql/back/token.ts，时间：2023/4/7 下午9:09:07, 错误信息："/bin/bash: tsx: command not found\n" 2023-04-07T21:09:07: info: [执行任务失败] SUB_ID=1 ql repo "https://github.com/KingRan/KR.git" "jd_|jx_|jdCookie" "activity|backUp" "^jd[^_]|USER|utils|function|sign|sendNotify|ql|JDJR" "" "" "" "true" "true"，时间：2023/4/7 下午9:09:07, 错误信息："/ql/shell/api.sh: line 9: tsx: command not found\n"
> > 后面的报错： 2023-02-02T00:33:29: Error: Please install sqlite3 package manually
> 
> 本地重装下项目依赖，pnpm 用 v8
