### ISSUE TITLE
请问是否可以提两个建议。1.日志列表直接放在左边。2.code脚本无法获取助力码

### ISSUE THREAD

**Issue by Clown666** [whyour/qinglong#189]
1. 日志列表可以直接展示在左侧，就像下图这样。
![image](https://user-images.githubusercontent.com/55350689/119584476-30e9c600-bdfb-11eb-825f-c5d9749c6ae2.png)
2.code脚本无法获取助力码，系统为ubuntu。始终为未产生日志。
![image](https://user-images.githubusercontent.com/55350689/119584725-c1280b00-bdfb-11eb-8934-76cd81053b13.png)
经过查询发现问题如下：
shell脚本存放在docker目录下，以本人为例，如下图所在位置。而此处的log文件夹和scripts均为空，实际存放目录为root/ql/log。
![image](https://user-images.githubusercontent.com/55350689/119585735-e0279c80-bdfd-11eb-8026-207f31d8344b.png)

**Comment by whyour** [comment]
https://t.me/qiongqin/80  看注意事项

**Comment by Clown666** [comment]
已解决，谢谢您啦。
