### ISSUE TITLE
一拉取最后的版本，只能拉取到2.10.13

### ISSUE THREAD

**Issue by number2021620** [whyour/qinglong#1890]
### Qinglong version

2.10.13

### Steps to reproduce

使用的页面最新拉取指令但是不是最新版
docker run -dit \
  -v $PWD/ql/data:/ql/data \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest

### What is expected?

不知道怎么回事

### What is actually happening?

现版本是2.15.11就是拉取不到

**Comment by number2021620** [comment]
我再试试吧。。。

**Comment by number2021620** [comment]
已解决，不要用科学

**Comment by wifisky-feilian** [comment]
没用科学，原生态联网为什么拉取的一直是V2.10.13版本呢
docker run -dit \
  -v /Volume1/public/Docker/ql/data:/ql/data \
  -p 5700:5700 \
  -e QlBaseUrl="/" \
  --name qinglong \
  --hostname qinglong \
  --restart always \
  whyour/qinglong:latest

谁知道什么原因，怎样解决这个难题啊，试了月把了，只要不指定版本，用latest拉取的一直是V2.10.13
