### ISSUE TITLE
Mac OS 本地每次关闭 docker 客户端，再打开就要重新初始化 青龙面板

### ISSUE THREAD

**Issue by cy920820** [whyour/qinglong#1891]
### Qinglong version

 2.11.3

### Steps to reproduce

每次重启 docker 客户端都要初始化一下青龙面板，并且进去之后任务都没了，环境变量什么都没有了

### What is expected?

每次打开都有数据才行

### What is actually happening?

每次打开数据都没了，要重新初始化面板，进去之后任务也都没了

![image](https://user-images.githubusercontent.com/21211512/230717017-77e311c0-1004-4347-861a-45c56c6c98c7.png)

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 162.53 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 108.0.1
    Safari: 16.4
```

**Comment by whyour** [comment]
没有映射目录吧

**Comment by cy920820** [comment]
> 没有映射目录吧

大佬怎么操作啊，能直接在客户端去映射目录吗？没有搜到

**Comment by whyour** [comment]
> > 没有映射目录吧
> 
> 大佬怎么操作啊，能直接在客户端去映射目录吗？没有搜到

启动桌面端后，也可以在命令行使用 docker 命令。直接用项目 readme 里的命令就行。docker desktop 输入容器名称的时候，下面不就是映射目录
