### ISSUE TITLE
修改面板定时,脚本名称会重置排序 置顶

### ISSUE THREAD

**Issue by qianlongzhou** [whyour/qinglong#1892]
### Qinglong version

2.15.11

### Steps to reproduce

1

### What is expected?

1

### What is actually happening?

1

### System Info

```shell
1
```

### Any additional comments?

1

**Comment by whyour** [comment]
2.15.12 已修复

**Comment by qianlongzhou** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
