### ISSUE TITLE
建议使用debian作为docker基础系统

### ISSUE THREAD

**Issue by yw9381** [whyour/qinglong#1895]
### Clear and concise description of the problem

1. alpine虽然体积小，但是有很多依赖是需要进行编译安装的，比如python的某些库，而alpine本身的C层实现是和debian这类系统是有区别的，导致即使库安装上了，却依然用不了
2. 建议在新建/编辑定时任务的dialog里新增定时规则编写说明和接下来N次的执行时间，方便对照crontab表达式是否编写有误，这块有很多的库都可以直接拿来使用

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by moonlit77** [comment]
是啊，pip install numpy 出错，无法安装，非常麻烦。numpy 出错就 pandas 也没法装

**Comment by whyour** [comment]
已经支持 debian 基础镜像

**Comment by moonlit77** [comment]
感谢大神！

**Comment by sdhzwc** [comment]
基于Debian的镜像 我怎么没找到

**Comment by whyour** [comment]
> 基于Debian的镜像 我怎么没找到

whyour/qinglong:debian
