### ISSUE TITLE
青龙面板设置通知方式为Gotify失败，提示 Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by LiarOnce** [whyour/qinglong#1896]
### Qinglong version

2.15.12

### Steps to reproduce

在系统设置-通知设置将通知方式选为Gotify，填入gotifyUrl和gotifyToken，点击保存

### What is expected?

正常保存并发送一条登录消息

### What is actually happening?

保存失败，提示 Response code 400 (Bad Request)

**Comment by whyour** [comment]
下个版本修复

**Comment by whyour** [comment]
2.15.13 已修复
