### ISSUE TITLE
运行start脚本，无法启动面板

### ISSUE THREAD

**Issue by Marblog** [whyour/qinglong#190]
项目启动成功了，但是有错误[HPM] Error occurred while trying to proxy request /api/user?t=1621992946291 from localhost:8000 to http://127.0.0.1:5678/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_co
mmon_system_errors)

![image](https://user-images.githubusercontent.com/22953256/119590010-89729080-be06-11eb-8356-8dbe93947d3f.png)

**Comment by whyour** [comment]
> 项目启动成功了，但是有错误[HPM] Error occurred while trying to proxy request /api/user?t=1621992946291 from localhost:8000 to http://127.0.0.1:5678/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_co
> mmon_system_errors)
> 
> ![image](https://user-images.githubusercontent.com/22953256/119590010-89729080-be06-11eb-8356-8dbe93947d3f.png)

你这是物理机启动的？

**Comment by Marblog** [comment]
> > 项目启动成功了，但是有错误[HPM] Error occurred while trying to proxy request /api/user?t=1621992946291 from localhost:8000 to http://127.0.0.1:5678/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_co
> > mmon_system_errors)
> > ![image](https://user-images.githubusercontent.com/22953256/119590010-89729080-be06-11eb-8356-8dbe93947d3f.png)
> 
> 你这是物理机启动的？

是的，拉下来的代码，npm了一下

**Comment by whyour** [comment]
@Hanhh 考虑下物理机怎么运行

**Comment by mydaoyuan** [comment]
> > > 项目启动成功了，但是有错误[HPM] Error occurred while trying to proxy request /api/user?t=1621992946291 from localhost:8000 to http://127.0.0.1:5678/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_co
> > > mmon_system_errors)
> > > ![image](https://user-images.githubusercontent.com/22953256/119590010-89729080-be06-11eb-8356-8dbe93947d3f.png)
> > 
> > 
> > 你这是物理机启动的？
> 
> 是的，拉下来的代码，npm了一下

再多运行一个服务看看 npm run start-back

**Comment by nileixing** [comment]
> > > > 项目启动成功了，但是有错误[HPM] Error occurred while trying to proxy request /api/user?t=1621992946291 from localhost:8000 to http://127.0.0.1:5678/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_co
> > > > mmon_system_errors)
> > > > ![image](https://user-images.githubusercontent.com/22953256/119590010-89729080-be06-11eb-8356-8dbe93947d3f.png)
> > > 
> > > 
> > > 你这是物理机启动的？
> > 
> > 
> > 是的，拉下来的代码，npm了一下
> 
> 再多运行一个服务看看 npm run start-back

npm run start-back

> start-back
> nodemon

[nodemon] 2.0.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): back\**\* .env
[nodemon] watching extensions: js,ts,json
[nodemon] starting `ts-node  --transpile-only ./back/app.ts`

C:\Users\nlx\source\repos\qinglong\back\config\index.ts:29
  throw new Error("⚠️  Couldn't find .env file  ⚠️");
        ^
Error: ⚠️  Couldn't find .env file  ⚠️
    at Object.<anonymous> (C:\Users\nlx\source\repos\qinglong\back\config\index.ts:29:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (C:\Users\nlx\source\repos\qinglong\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\nlx\source\repos\qinglong\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\nlx\source\repos\qinglong\back\app.ts:3:1)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by heiyepiaoxie** [comment]
解决pm2启动问题了吗，我现在也是卡在这里⚠️ Couldn't find .env file ⚠️，求助作者SOS

**Comment by whyour** [comment]
> 解决pm2启动问题了吗，我现在也是卡在这里⚠️ Couldn't find .env file ⚠️，求助作者SOS

cp .env.example .env

主要是windows没有crontab，所以没法直接在windows上部署
