### ISSUE TITLE
whyour/qinglong:debian 出现无法确定系统的语言

### ISSUE THREAD

**Issue by elunez** [whyour/qinglong#1902]
### Qinglong version

qinglong:debian:v2.15.12

### Steps to reproduce

执行定时任务，会出现这个提示

![telegram-cloud-photo-size-5-6190315224352011369-y](https://user-images.githubusercontent.com/42142420/232666943-17057761-8837-41fb-b0d9-e95935f2130e.jpg)

### What is expected?

消除这个提示

### What is actually happening?

perl: warning: Please check that your locale settings: LANGUAGE = (unset), LC_ALL = (unset), LANG = "zh_CN.UTF-8"

**Comment by whyour** [comment]
export LC_ALL="C.UTF-8" 加到配置文件 config.sh 里

**Comment by elunez** [comment]
> export LC_ALL="C.UTF-8" 加到配置文件 config.sh 里

可以了，谢谢
