### ISSUE TITLE
使用最新的容器镜像，在面板内设置tg机器人 接口报400错误

### ISSUE THREAD

**Issue by fireinrain** [whyour/qinglong#1904]
### Qinglong version

2.15.12

### Steps to reproduce

使用最新docker镜像启动面板，尝试在面板中修改tg bot通知设置

### What is expected?

设置成功

### What is actually happening?

服务器报接口错误 400
如图所示：
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/14249262/233090866-a006938e-c819-4f1b-8582-16b35cf34649.png">

**Comment by whyour** [comment]
可以使用 2.15.13 测试看具体错误，我测试是可以的
