### ISSUE TITLE
新版青龙，只要修改默认的定时规则  更新脚本的时候就会有两个一样的js

### ISSUE THREAD

**Issue by wangyucst** [whyour/qinglong#1905]
### Qinglong version

 v2.15.12

### Steps to reproduce

只要修改定时规则，更新时都会创建一个默认定时规则的js，100%复现

### What is expected?

修改成旧版那样，不要新建脚本，只更新脚本

### What is actually happening?

每天需要手动删除脚本，很麻烦

### Any additional comments?

![image](https://user-images.githubusercontent.com/124138907/233230653-fde35f4a-ad0e-454d-a6b3-4ed19dffcb36.png)

**Comment by whyour** [comment]
@wangyucst 更新下镜像，或者在系统设置强制更新下

**Comment by wangyucst** [comment]
> @wangyucst 更新下镜像，或者在系统设置强制更新下

我用的是面具的青龙面板，强制更新似乎不起作用
![image](https://user-images.githubusercontent.com/124138907/233233723-431f0554-589b-47d5-bb16-7c53dd83e99b.png)

**Comment by elunez** [comment]
> > @wangyucst 更新下镜像，或者在系统设置强制更新下
> 
> 问题得到解决，感谢回复！

是 debian 版本吗？我 debian v2.15.12 版本遇到过，每次更新仓库都会创建一样的脚本

**Comment by whyour** [comment]
> > > @wangyucst 更新下镜像，或者在系统设置强制更新下
> > 
> > 
> > 问题得到解决，感谢回复！
> 
> 是 debian 版本吗？我 debian v2.15.12 版本遇到过，每次更新仓库都会创建一样的脚本

debian 要更新下镜像，或者面板内系统设置强制更新下
