### ISSUE TITLE
希望消息通知可以支持ntfy

### ISSUE THREAD

**Issue by ysslang** [whyour/qinglong#1907]
### Clear and concise description of the problem

Gotify确实挺好用的, 但是推送不到ios上, 还是差点意思

### Suggested solution

[Notify](https://github.com/binwiederhier/ntfy) 支持推送到ios, 也是开源组件, 用户量也挺大的, 接入也不难, 希望内置支持下

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Potat0000** [comment]
同求

**Comment by Jiraiya8** [comment]
同求，自定义通知，webhookContentType的三个选项都不支持，以下是ntfy的发送示例
```sh
curl \
  -H "Title: Unauthorized access detected" \
  -H "Priority: urgent" \
  -H "Tags: warning,skull" \
  -d "Remote access to phils-laptop detected. Act right away." \
  ntfy.sh/phil_alerts
```

**Comment by xq330** [comment]
同求

**Comment by yv-code** [comment]
直接用 GET，参考 [ntfy 官方文档](https://docs.ntfy.sh/publish/#webhooks-publish-via-get)

**Comment by Potat0000** [comment]
> 直接用 GET，参考 [ntfy 官方文档](https://docs.ntfy.sh/publish/#webhooks-publish-via-get)

请问可以稍微详细一些吗？比如是如何在青龙面板的 notify 中加入 GET 调用的？谢谢！

**Comment by yv-code** [comment]
> 请问可以稍微详细一些吗？比如是如何在青龙面板的 notify 中加入 GET 调用的？谢谢！

你在”系统设置-通知设置“里面设置的自定义通知是支持 ntfy 的 GET 的，POST 没有尝试成功。只需要在 URL 里面将参数填入，类似`https://<host>/<channel>/publish?message=$content&title=$title`，如果需要认证，在 Header 里面填入即可，具体的细节还是参考 ntfy 的官方文档。

如果你需要的是具体的任务支持使用 ntfy，得看你的脚本使用的通知脚本。我发现了有人提了 [PR#1796](https://github.com/whyour/qinglong/pull/1796) 修改了自带的 sendNotify.js ，可以支持任意的 webhook，可以拿来用。

**Comment by Potat0000** [comment]
> 你在”系统设置-通知设置“里面设置的自定义通知是支持 ntfy 的 GET 的，POST 没有尝试成功。只需要在 URL 里面将参数填入，类似`https://<host>/<channel>/publish?message=$content&title=$title`，如果需要认证，在 Header 里面填入即可，具体的细节还是参考 ntfy 的官方文档。
> 
> 如果你需要的是具体的任务支持使用 ntfy，得看你的脚本使用的通知脚本。我发现了有人提了 [PR#1796](https://github.com/whyour/qinglong/pull/1796) 修改了自带的 sendNotify.js ，可以支持任意的 webhook，可以拿来用。

十分感谢！

确实是想要具体的任务可以使用 ntfy。 #1796 似乎关闭了，可能还有些问题。等待之后有更完整的方案吧。

**Comment by whyour** [comment]
通知文件也支持 自定义通知了
