### ISSUE TITLE
有关代理的问题

### ISSUE THREAD

**Issue by Super-member** [whyour/qinglong#1911]
### Qinglong version

latest

### Steps to reproduce

无

### What is expected?

代理设置 报错 

### What is actually happening?

青龙面板显示socket hang up   op clash代理是正常的 青龙代理ip填的是op ip 端口是clash socks 端口 ,一直报错 socket hang up

### System Info

```shell
socket hang up
```

**Comment by itscolor** [comment]
借楼问一下，我任务添加的是task autoSignin.js 但是手动点击运行后，一直转圈，没有日志出现，是什么原因呢？
