### ISSUE TITLE
青龙日志记录问题

### ISSUE THREAD

**Issue by lonesomexz** [whyour/qinglong#1912]
### Qinglong version

2.15.12

### Steps to reproduce

1.在docker 内task 命令执行面板内不显示运行
2.使用task -l 命令 实时打印任务日志 ，日志不会记录

### What is expected?

1.因为青龙默认执行命令是执行完才回显，显示日志,一些特殊需求无法实现。但是如果加上 -l 又不会记录日志后面无法查看日志记录，希望 -l 最后也会生成日志。
2.docker 内终端环境内执行命令,定时任务界面没有运行状态,并且日志关联不上，无法查看是否运行。希望如果终端环境下执行，前台也有状态显示
### What is actually happening?

无

### System Info

```shell
无
```

### Any additional comments?

无

**Comment by whyour** [comment]
为什么不新建任务呢

**Comment by lonesomexz** [comment]
第一个问题，修改task.sh 解决好了
第二个问题 是转发修改新建的话太多了一个一个改 不如写好规则直接发送，还有已经在容器内部，如果还调用api的话，是不是多了一步

**Comment by whyour** [comment]
第一个问题  直接运行脚本的话，需要查询脚本对应哪个任务
第二个问题  可以改成记录，下个版本改

**Comment by whyour** [comment]
或者说支持 直接运行某个任务？

**Comment by lonesomexz** [comment]
> 第一个问题  直接运行脚本的话，需要查询脚本对应哪个任务
> 
> 第二个问题  可以改成记录，下个版本改

是的我发现了，现在要不就是通过api调取运行才行，才能和手动一个脚本，而且直接终端内运行的文件夹好像命名规则和正常的也不一致。
还有一个问题好像api没有接口修改config.sh是吧？没有找到相关呢。
哪里能看到api的汇总吗？除了翻代码……

**Comment by whyour** [comment]
> > 第一个问题  直接运行脚本的话，需要查询脚本对应哪个任务
> > 第二个问题  可以改成记录，下个版本改
> 
> 是的我发现了，现在要不就是通过api调取运行才行，才能和手动一个效果，而且直接终端内运行的文件夹好像命名规则和正常的也不一致。 还有一个问题好像api没有接口修改config.sh是吧？没有找到相关呢。 哪里能看到api的汇总吗？除了翻代码……

可以加一个查询id的过程，目前没有api汇总，https://qinglong.ukenn.top/ 这是别人写的，版本不是最新的。  PR is welcoming

config 得先获取，再更新

**Comment by lonesomexz** [comment]
> develop 镜像已支持，可以测试下

测试更换修改的文件后现在终端运行可以识别运行状态了，日志也关联上了，-l\的日志也有了现在。但是有个问题，通过终端运行的，现在在面板停止，实际上终端还在运行没有停止。

**Comment by whyour** [comment]
> > develop 镜像已支持，可以测试下
> 
> 测试更换修改的文件后现在终端运行可以识别运行状态了，日志也关联上了，-l 的日志也有了现在。但是有个问题，通过终端运行的，现在在面板停止，实际上终端还在运行没有停止。 命令有一种情况检测不到 比如终端内运行python脚本,通过
> 
> ```
>         proc = await asyncio.create_subprocess_shell(
>             f"{cmd} ",
>             stdout=asyncio.subprocess.PIPE,
>             stderr=asyncio.subprocess.PIPE,
>             start_new_session=True  # 将子进程关联到新的进程组
>         )
> ```
> 
> 创建的子进程运行的命令无法监控到 但是在top等能看到

develop 已修复，可以试下

**Comment by lonesomexz** [comment]
> > > develop 镜像已支持，可以测试下
> > 
> > 
> > 测试更换修改的文件后现在终端运行可以识别运行状态了，日志也关联上了，-l 的日志也有了现在。但是有个问题，通过终端运行的，现在在面板停止，实际上终端还在运行没有停止。 命令有一种情况检测不到 比如终端内运行python脚本,通过
> > ```
> >         proc = await asyncio.create_subprocess_shell(
> >             f"{cmd} ",
> >             stdout=asyncio.subprocess.PIPE,
> >             stderr=asyncio.subprocess.PIPE,
> >             start_new_session=True  # 将子进程关联到新的进程组
> >         )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 创建的子进程运行的命令无法监控到 但是在top等能看到
> 
> develop 已修复，可以试下

停用测试了 单独使用 now 和 desi参数正常，一旦使用了 -l 参数就无法停止

**Comment by whyour** [comment]
> create_subprocess_shell

可能跟这个  create_subprocess_shell  有关，-l 与非 -l 实现上就是多了个 tee

**Comment by lonesomexz** [comment]
> create_subprocess_shell

是的，这种我都是加上start_new_session=True，关联一个进程组，然后直接终止进程组来解决！不然的话只是杀掉了子线程，对应的父线程是杀不掉的

**Comment by whyour** [comment]
> > create_subprocess_shell
> 
> 是的，这种我都是加上start_new_session=True，关联一个进程组，然后直接终止进程组来解决！不然的话只是关闭子线程，对应的父线程是关闭不掉的。python按我上面的示例的话，我是直接os.killpg(os.getpgid(proc.pid), signal.SIGTERM)关闭进程组，这样就都关闭了。
> 
> 还发现一个问题，如果定时任务里 命令/脚本 填写 带 -l 参数的，在终端运行后，面板的运行状态也监控不到

develop 已修复

**Comment by whyour** [comment]
> > > > create_subprocess_shell
> 
> > > 
> 
> > > 
> 
> > > 是的，这种我都是加上start_new_session=True，关联一个进程组，然后直接终止进程组来解决！不然的话只是关闭子线程，对应的父线程是关闭不掉的。python按我上面的示例的话，我是直接os.killpg(os.getpgid(proc.pid), signal.SIGTERM)关闭进程组，这样就都关闭了。
> 
> > > 还发现一个问题，如果定时任务里 命令/脚本 填写 带 -l 参数的，在终端运行后，面板的运行状态也监控不到
> 
> > 
> 
> > develop 已修复
> 
> 
> 
> 好像不行吧，我怎么测试带不带l的限制都监控不到运行状态了。。。

有个版本改出问题了，再试

**Comment by lonesomexz** [comment]
> > > > > create_subprocess_shell
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 是的，这种我都是加上start_new_session=True，关联一个进程组，然后直接终止进程组来解决！不然的话只是关闭子线程，对应的父线程是关闭不掉的。python按我上面的示例的话，我是直接os.killpg(os.getpgid(proc.pid), signal.SIGTERM)关闭进程组，这样就都关闭了。
> > 
> > 
> > > > 还发现一个问题，如果定时任务里 命令/脚本 填写 带 -l 参数的，在终端运行后，面板的运行状态也监控不到
> > 
> > 
> > > 
> > 
> > 
> > > develop 已修复
> > 
> > 
> > 好像不行吧，我怎么测试带不带l的限制都监控不到运行状态了。。。
> 
> 有个版本改出问题了，再试下

更新后测试了，状态监控应该可以了,暂时测试的都可以。
但是停止有下面几个不行的情况
1.定时任务内设置是 task xxx now, 终端执行 task -l xxx now 无法结束
2.定时任务内设置是 task -l xxx now, 终端执行 task -l xxx now 无法结束

**Comment by whyour** [comment]
> > > > > > create_subprocess_shell
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 是的，这种我都是加上start_new_session=True，关联一个进程组，然后直接终止进程组来解决！不然的话只是关闭子线程，对应的父线程是关闭不掉的。python按我上面的示例的话，我是直接os.killpg(os.getpgid(proc.pid), signal.SIGTERM)关闭进程组，这样就都关闭了。
> 
> > > 
> 
> > > 
> 
> > > > > 还发现一个问题，如果定时任务里 命令/脚本 填写 带 -l 参数的，在终端运行后，面板的运行状态也监控不到
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > develop 已修复
> 
> > > 
> 
> > > 
> 
> > > 好像不行吧，我怎么测试带不带l的限制都监控不到运行状态了。。。
> 
> > 
> 
> > 有个版本改出问题了，再试下
> 
> 
> 
> 更新后测试了，状态监控应该可以了,暂时测试的都可以。
> 
> 但是停止有下面几个不行的情况
> 
> 1.定时任务内设置是 task xxx now, 终端执行 task -l xxx now 无法结束
> 
> 2.定时任务内设置是 task -l xxx now, 终端执行 task -l xxx now 无法结束

终端停止还是任务里停止，意思是终端里停止不了面板的状态？

**Comment by lonesomexz** [comment]
> > > > > > > create_subprocess_shell
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > >
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > 是的，这种我都是加上start_new_session=True，关联一个进程组，然后直接终止进程组来解决！不然的话只是关闭子线程，对应的父线程是关闭不掉的。python按我上面的示例的话，我是直接os.killpg(os.getpgid(proc.pid), signal.SIGTERM)关闭进程组，这样就都关闭了。
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > > 还发现一个问题，如果定时任务里 命令/脚本 填写 带 -l 参数的，在终端运行后，面板的运行状态也监控不到
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > 
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > develop 已修复
> > 
> > > > 
> > 
> > > > 
> > 
> > > > 好像不行吧，我怎么测试带不带l的限制都监控不到运行状态了。。。
> > 
> > > 
> > 
> > > 有个版本改出问题了，再试下
> > 
> > 
> > 
> > 更新后测试了，状态监控应该可以了,暂时测试的都可以。
> > 
> > 但是停止有下面几个不行的情况
> > 
> > 1.定时任务内设置是 task xxx now, 终端执行 task -l xxx now 无法结束
> > 
> > 2.定时任务内设置是 task -l xxx now, 终端执行 task -l xxx now 无法结束
> 
> 终端停止还是任务里停止，意思是终端里停止不了面板的状态？

不好意思之前没有说清楚，是终端内运行命令，在面板里停止运行，终端内还在运行，并且日志内可以看到，还在继续运行。

**Comment by whyour** [comment]
@lonesomexz 本地测试了下，这两种情况都无法复现

**Comment by lonesomexz** [comment]
> @lonesomexz 本地测试了下，这两种情况都无法复现。终端都可以正常结束

如何直接拉开发版的镜像，我试试看看是不是我漏替换了

**Comment by whyour** [comment]
> > @lonesomexz 本地测试了下，这两种情况都无法复现。终端都可以正常结束
> 
> 如何直接拉开发版的镜像，我试试看看是不是我漏替换了

docker pull whyour/qinglong:develop

**Comment by lonesomexz** [comment]
> > > @lonesomexz 本地测试了下，这两种情况都无法复现。终端都可以正常结束
> > 
> > 
> > 如何直接拉开发版的镜像，我试试看看是不是我漏替换了
> 
> docker pull whyour/qinglong:develop

v2.15.13测试更新到正式版以及解决，暂时没发现其他问题了，谢谢了
