### ISSUE TITLE
自动补全依赖失败

### ISSUE THREAD

**Issue by binge8** [whyour/qinglong#1913]
### Qinglong version

2.15.12

### Steps to reproduce

能分析到缺少的依赖，但每次都失败

### What is expected?

希望真正全自动补齐

### What is actually happening?

🐲青龙日志分析

📆分析 2023年04月24日23时 ~ 2023年04月24日00时 的日志报告：
✅正常运行脚本：33 次
⛔异常运行脚本：4 次，占比 12.12 %
🧐其中:
    🕵️‍♂️Nodejs异常：3 次，占比 9.09 %
    🕵️‍♂️Python异常：1 次，占比 3.03 %
👮‍♂️依赖检测: ☢已开启自动补全依赖,将执行shell命令,请小心恶意脚本👿
👮‍♂️检测到缺失NodeJs依赖:
['axios', 'crypto-js']
💂‍♂️详细错误日志：
🛑脚本：shufflewzc_faker2_main_jd_identical211_585：
- ⚠Python错误：AttributeError: 'str' object has no attribute 'get' 
🛑脚本：shufflewzc_faker2_main_jd_farautomation_448：
- ⚠NodeJs错误：Cannot find module 'axios' 
🛑脚本：shufflewzc_faker2_main_jd_dreamFactory_494：
- ⚠NodeJs错误：Cannot find module 'crypto-js' 
🛑脚本：shufflewzc_faker2_main_jd_joy_park_run_474：
- ⚠NodeJs错误：Cannot find module 'crypto-js' 

🐲青龙自动安装依赖(1/2)

🤖检测是否安装NodeJs依赖: axios
⚙当前正在自动安装NodeJs依赖: axios
🔨执行命令: cd /ql/ && npm install axios
⛔出错了: 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   dev react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @monaco-editor/react@4.2.1
npm ERR! node_modules/@monaco-editor/react
npm ERR!   dev @monaco-editor/react@"4.2.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2023-04-24T15_16_07_241Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-24T15_16_07_241Z-debug-0.log

🐲青龙自动安装依赖(2/2)

🤖检测是否安装NodeJs依赖: crypto-js
⚙当前正在自动安装NodeJs依赖: crypto-js
🔨执行命令: cd /ql/ && npm install crypto-js
⛔出错了: 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   dev react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @monaco-editor/react@4.2.1
npm ERR! node_modules/@monaco-editor/react
npm ERR!   dev @monaco-editor/react@"4.2.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2023-04-24T15_17_25_696Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-24T15_17_25_696Z-debug-0.log

### System Info

docker版qinglong

**Comment by whyour** [comment]
@binge8 脚本问题，找脚本开发者
