### ISSUE TITLE
定时任务和调试超过3600秒都会直接停止

### ISSUE THREAD

**Issue by WinterChenS** [whyour/qinglong#1916]
### Qinglong version

v2.15.12

### Steps to reproduce

python发送上万封邮件，时间很长，执行定时任务或者调试都会在3600秒直接超时停止

### What is expected?

希望能够配置一个参数，用于自行控制超时时间。

### What is actually happening?

python发送上万封邮件，时间很长，执行定时任务或者调试都会在3600秒直接超时停止

**Comment by whyour** [comment]
> ### Qinglong version
> v2.15.12
> 
> ### Steps to reproduce
> python发送上万封邮件，时间很长，执行定时任务或者调试都会在3600秒直接超时停止
> 
> ### What is expected?
> 希望能够配置一个参数，用于自行控制超时时间。
> 
> ### What is actually happening?
> python发送上万封邮件，时间很长，执行定时任务或者调试都会在3600秒直接超时停止
> 
> ### System Info
> _No response_
> 
> ### Any additional comments?
> _No response_

系统默认所有任务 1小时 超时时间，可以使用 task -m 24h xxx.py 执行超时时间，或者改配置文件里的 CommandTimeoutTime

**Comment by whyour** [comment]
下个版本会移除默认超时时间

**Comment by WinterChenS** [comment]
@whyour 谢谢
