### ISSUE TITLE
容器启动后无法正常访问，ql check报错

### ISSUE THREAD

**Issue by blackyao** [whyour/qinglong#1917]
### Qinglong version

最新版

### Steps to reproduce

![image](https://user-images.githubusercontent.com/30308045/236170068-08c7cc11-edbf-4df0-893f-e577a4dc2d20.png)

### What is expected?

正常web管理界面

### What is actually happening?

容器启动后无法正常访问，ql check报错

容器显示unhealthy

**Comment by whyour** [comment]
宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
