### ISSUE TITLE
logo 加载不出来了

### ISSUE THREAD

**Issue by 2219160052** [whyour/qinglong#1918]
### Qinglong version

正式版 v2.15.14

### Steps to reproduce

![image](https://user-images.githubusercontent.com/31033119/236381147-9e1727e8-7926-4627-8bf4-a4e9ae5c469b.png)

### What is expected?

logo能加载出来

### What is actually happening?

logo加载不出来，访问报错403
![image](https://user-images.githubusercontent.com/31033119/236381089-3ee68a59-a7ab-49ce-a9f7-ec54dbf95545.png)

### System Info

```shell
System:
    OS: Linux 5.4 Alpine Linux
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
    Memory: 938.28 MB / 1.84 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.14.2 - /usr/bin/node
    npm: 9.1.2 - /usr/bin/npm
```

**Comment by dossec** [comment]
建议logo放在本地，网络加载挂了不好

**Comment by elunez** [comment]
> 建议logo放在本地，网络加载挂了不好

logo 又不是头像，怎么放本地？还是说进容器改源代码？

**Comment by maryjeck** [comment]
连接到 qn.whyour.cn 时发生错误。PR_END_OF_FILE_ERROR

错误代码：PR_END_OF_FILE_ERROR

**Comment by whyour** [comment]
容器内执行  
```bash
#!/bin/bash
file_list=$(find /ql/static/dist -name "*.js")
for i in $file_list; do
  sed -i 's#qn.whyour.cn#qn.ninesix.cc#g' $i
done

```

**Comment by whyour** [comment]
same https://github.com/whyour/qinglong/issues/1918

**Comment by PillarsZhang** [comment]
现在的版本启用 gzip 静态压缩了，读取的是 `.js.gz`，不重新构建，最简单办法是把它们全删了，反正nginx会动态压缩

本地化这些文件，这个本地挂载的路径对应 `http://xxx/api/static/`，当然也可以把 logo 换成自己想要的
```bash
curl -o data/upload/logo.png https://qn.whyour.cn/logo.png
curl -o data/upload/favicon.svg https://qn.whyour.cn/favicon.svg
curl -o data/upload/version.yaml https://qn.whyour.cn/version.yaml
```

Dockerfile
```Dockerfile
FROM whyour/qinglong:latest

RUN find /ql/static/dist -type f \( -name "*.js" -o -name "*.html" \) -exec sed -i 's|https://qn.whyour.cn/|/api/static/|g' {} +

RUN find /ql/static/dist -type f -name "*.js.gz" -delete
```

docker-compose.yml
```yml
services:
  web:
    build: .
    volumes:
      - ./data:/ql/data
    ports:
      - "25700:5700"
    environment:
      QlBaseUrl: '/' # 部署路径非必须，以斜杠开头和结尾，比如 /test/
    restart: unless-stopped
```
