### ISSUE TITLE
Alpine下docker版青龙，py部分依赖装不上

### ISSUE THREAD

**Issue by GD2021** [whyour/qinglong#1920]
### Qinglong version

2.11.3

### Steps to reproduce

![image](https://user-images.githubusercontent.com/81171294/236599026-f0f4998f-373d-48cc-af65-a65a6b9b54ed.png)
 
已安装的linux依赖
![image](https://user-images.githubusercontent.com/81171294/236599083-c4ec9566-d823-43c7-a47a-336f1a37733b.png)
![image](https://user-images.githubusercontent.com/81171294/236599109-0f90b4ee-3822-4f61-83b5-53007db56b29.png)

### What is expected?

如何正常安装呢

### What is actually happening?

1

**Comment by whyour** [comment]
可以使用 debian 版本 whyour/qinglong:debian，自己翻译下安装失败的日志
