### ISSUE TITLE
docker-compose.yml存在问题

### ISSUE THREAD

**Issue by Cyb3rMut4nt** [whyour/qinglong#1921]
### Qinglong version

2023.5.7

### Steps to reproduce

下载docker-compose.yml文件后：
https://raw.githubusercontent.com/whyour/qinglong/master/docker/docker-compose.yml
运行`docker-compose up -d`
会报错
`ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.web: 'healthcheck'
`

download docker-compose.yml:
https://raw.githubusercontent.com/whyour/qinglong/master/docker/docker-compose.yml
run:
`docker-compose up -d`
throw an error:
`ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.web: 'healthcheck'
`

### What is expected?

修改docker-compose.yml第一行：
`version: '2.1'`
可以正常运行:
`Creating network "qinglong_default" with the default driver`
`Pulling web (whyour/qinglong:latest)...`
`latest: Pulling from whyour/qinglong`
`8572bc8fb8a3: Pull complete`
`302fff22c187: Pull complete`
`f89e9f2eb86a: Pull complete`
`ae1255adff2d: Pull complete`
`a6be967aa0b2: Pull complete`
`6236758761da: Pull complete`
`Digest: sha256:9c3136f2f0f45a009dab06ec56530bc6595570454e20a068827a22e6caf37ffd`
`Status: Downloaded newer image for whyour/qinglong:latest`
`Creating qinglong_web_1 ... `
`Creating qinglong_web_1 ... done`

change docker-compose.yml first line:
`version: '2.1'`
and it worked:
`Creating network "qinglong_default" with the default driver`
`Pulling web (whyour/qinglong:latest)...`
`latest: Pulling from whyour/qinglong`
`8572bc8fb8a3: Pull complete`
`302fff22c187: Pull complete`
`f89e9f2eb86a: Pull complete`
`ae1255adff2d: Pull complete`
`a6be967aa0b2: Pull complete`
`6236758761da: Pull complete`
`Digest: sha256:9c3136f2f0f45a009dab06ec56530bc6595570454e20a068827a22e6caf37ffd`
`Status: Downloaded newer image for whyour/qinglong:latest`
`Creating qinglong_web_1 ... `
`Creating qinglong_web_1 ... done`

### What is actually happening?

参考：https://stackoverflow.com/a/42754309
healthcheck选项是用于docker-compose.yml文件的版本是2.1或3。
`version: '2.1'`
`version: '3'`
如果是版本为2或者1，可能不会工作。

according：https://stackoverflow.com/a/42754309
The healthcheck option was added in docker-compose file format 2.1. If you are using version 2 or version 1, it will not be available. The format version is typically on the first line of docker-compose.yml, as in
`version: '2.1'`
`version: '3'`
Also, the healthcheck option requires Docker Engine 1.12.0 or later.
If you don't meet those requirements, it will not work.

### System Info

```shell
System：Ubuntu 18.04.4 LTS
Docker：Docker version 18.09.7, build 2d0083d
```

**Comment by whyour** [comment]
@Cyb3rMut4nt 删掉就行了，dockerfile已经有健康检测了

**Comment by whyour** [comment]
已经移除相关配置
