### ISSUE TITLE
青龙 所有任务都提示 任务未运行

### ISSUE THREAD

**Issue by gba3455** [whyour/qinglong#1923]
### Qinglong version

2.15.10 ~ 2.15.14

### Steps to reproduce

![image](https://user-images.githubusercontent.com/7631908/236679413-a1c2d5dd-334f-486c-9862-0112f0f5ff45.png)
我的青龙突然所有的任务运行都提示 “任务未运行”
实际也确实是没有运行。

最开始版本是2.15.10，出现问题以后使用ql -l update升级到最新的2.15.14
问题依旧。在issue里没搜索到相关的解决方案，只好来提问一下。
不知道怎么解决。

### What is expected?

![image](https://user-images.githubusercontent.com/7631908/236679413-a1c2d5dd-334f-486c-9862-0112f0f5ff45.png)
我的青龙突然所有的任务运行都提示 “任务未运行”
实际也确实是没有运行。

最开始版本是2.15.10，出现问题以后使用ql -l update升级到最新的2.15.14
问题依旧。在issue里没搜索到相关的解决方案，只好来提问一下。
不知道怎么解决。

### What is actually happening?

![image](https://user-images.githubusercontent.com/7631908/236679413-a1c2d5dd-334f-486c-9862-0112f0f5ff45.png)
我的青龙突然所有的任务运行都提示 “任务未运行”
实际也确实是没有运行。

最开始版本是2.15.10，出现问题以后使用ql -l update升级到最新的2.15.14
问题依旧。在issue里没搜索到相关的解决方案，只好来提问一下。
不知道怎么解决。

**Comment by whyour** [comment]
@gba3455 宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
 

使用宿主机方式更新

**Comment by gba3455** [comment]
> @gba3455 宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
> 
> 使用宿主机方式更新

更新了一下pm2，恢复正常了。多谢大佬。

**Comment by gba3455** [comment]
更新完青龙又不行了。回来补充一下更新pm2的方法，防止下次遇到忘怎么解决。
更新方法 exec进去后 运行 pm2 update

**Comment by ata666** [comment]
> > @gba3455 宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
> > 使用宿主机方式更新
> 
> 更新了一下pm2，恢复正常了。多谢大佬。

怎么更新的pm2啊，

**Comment by dgulan** [comment]
我也碰到相同的问题，任务未运行。
即使是手动点击来运行任务，还是会提示任务未运行。

请问楼主怎么更新的pm2？

> > @gba3455 宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
> > 使用宿主机方式更新
> 
> 更新了一下pm2，恢复正常了。多谢大佬。
