### ISSUE TITLE
2.15.13删除依赖不会自动刷新，老版本可以

### ISSUE THREAD

**Issue by sdhzwc** [whyour/qinglong#1925]
### Qinglong version

2.15.13

### Steps to reproduce
![57f92af4-3d08-4e59-8a59-d6f638efe171](https://user-images.githubusercontent.com/46134044/236740822-177e94dd-ebf2-45f0-8033-742c75cc501b.gif)

具体的话看一下动图

### What is expected?

修改一下

### What is actually happening?

1

**Comment by whyour** [comment]
更新到 2.15.14 建议使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 方式更新
