### ISSUE TITLE
setting系统设置里面的logo无法显示

### ISSUE THREAD

**Issue by getr00t** [whyour/qinglong#1927]
### Qinglong version

版本2.15.14

### Steps to reproduce
![error](https://user-images.githubusercontent.com/12257416/236907383-99bfe0b8-8984-40f9-9c88-ac7f79819524.png)

![logo不显示](https://user-images.githubusercontent.com/12257416/236905202-7e3ab15e-0d2c-45f4-96d8-f609c8177c5f.png)

### What is expected?

setting系统设置里面的logo无法显示，可以把icon图标放到本地的文件吗？我尝试了把logo图标放到ql/upload/文件夹，把url替换成路径，也没有顺利加载图标出来，我很想修复它，但是我不知道为什么还是无法显示logo图标出来，请修复它，谢谢

### What is actually happening?

setting系统设置里面logo无法显示

### System Info
Windows 10 专业版22H2

**Comment by whyour** [comment]
刷新，已恢复
