### ISSUE TITLE
Typo 群辉chat

### ISSUE THREAD

**Issue by bigswordCN** [whyour/qinglong#1933]
### Qinglong version

last

### Steps to reproduce
![image](https://github.com/whyour/qinglong/assets/34957687/1f50fbb3-17b7-4589-b63a-4b18b37f2b2b)
看着挺难受的， 改一下吧。

### What is expected?

群辉 change to 群晖Chat

### What is actually happening?

typo 群辉chat

**Comment by whyour** [comment]
强制更新下

**Comment by bigswordCN** [comment]
done
