### ISSUE TITLE
所有配置文件无法正常显示

### ISSUE THREAD

**Issue by 1229984599** [whyour/qinglong#1935]
### Qinglong version

2.15.14

### Steps to reproduce

![Uploading image.png…]()

### What is expected?

能够正常查看配置文件

### What is actually happening?

配置文件显示为空，f12查看网络请求，返回的data也是空值，挂载的服务器和容器内部查看文件都是正常的，并且脚本也能正常运行。

### System Info

```shell
安装了1panel控制面板，操作系统是腾讯的opencloud，好像是基于centos8
```

**Comment by ptsa** [comment]
我这里也有这样的问题

**Comment by hehe9011** [comment]
一样的问题，看起来像WEB显示错误，而且每次重启系统，依赖都会全部重新安装一遍，日志如下：
`======================4. 启动pm2服务========================
[PM2][WARN] Applications schedule, public, panel not running, starting...
[PM2][WARN] App schedule has option 'wait_ready' set, waiting for app to be ready...
[PM2][WARN] App public has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [schedule] launched (1 instances)
[PM2][WARN] App panel has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [public] launched (1 instances)
[PM2] App [panel] launched (1 instances)
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 121      │ 1s     │ 0    │ online    │ 0%       │ 131.1mb  │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 98       │ 1s     │ 0    │ online    │ 0%       │ 101.5mb  │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 97       │ 1s     │ 0    │ online    │ 0%       │ 72.1mb   │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
====================6. 执行自定义脚本========================
自定义脚本后台执行中...
############################################################
容器启动成功...
############################################################
======================1. 检测配置文件========================
'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
======================2. 安装依赖========================
Writing to /root/.config/pip/pip.conf
======================3. 启动nginx========================
nginx启动成功...
======================4. 启动pm2服务========================
[PM2][WARN] Applications schedule, public, panel not running, starting...
[PM2][WARN] App schedule has option 'wait_ready' set, waiting for app to be ready...
[PM2][WARN] App public has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [schedule] launched (1 instances)
[PM2][WARN] App panel has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [public] launched (1 instances)
[PM2] App [panel] launched (1 instances)
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 114      │ 1s     │ 0    │ online    │ 0%       │ 132.9mb  │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 91       │ 2s     │ 0    │ online    │ 0%       │ 99.9mb   │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 90       │ 2s     │ 0    │ online    │ 0%       │ 71.0mb   │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
====================6. 执行自定义脚本========================
自定义脚本后台执行中...
############################################################
容器启动成功...
############################################################
======================1. 检测配置文件========================
'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
======================2. 安装依赖========================
Writing to /root/.config/pip/pip.conf
======================3. 启动nginx========================
nginx启动成功...
======================4. 启动pm2服务========================
[PM2][WARN] Applications schedule, public, panel not running, starting...
[PM2][WARN] App schedule has option 'wait_ready' set, waiting for app to be ready...
[PM2][WARN] App public has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [schedule] launched (1 instances)
[PM2][WARN] App panel has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [public] launched (1 instances)
[PM2] App [panel] launched (1 instances)
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 114      │ 1s     │ 0    │ online    │ 0%       │ 129.7mb  │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 96       │ 2s     │ 0    │ online    │ 0%       │ 99.9mb   │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 90       │ 2s     │ 0    │ online    │ 0%       │ 71.2mb   │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
====================6. 执行自定义脚本========================
自定义脚本后台执行中...
############################################################
容器启动成功...
############################################################`

**Comment by whyour** [comment]
强制更新下，有次补丁打出问题了

**Comment by 1229984599** [comment]
强制更新后已解决
