### ISSUE TITLE
尝试用docker-compose安装青龙面板，但docker持续重启

### ISSUE THREAD

**Issue by dust2k** [whyour/qinglong#1936]
### Qinglong version

2.15.14

### Steps to reproduce

按照标准的安装步骤，然后执行 `docker-compose up -d`，之后出现
Creating network "opt_default" with the default driver
Creating opt_web_1 ... done

但是这个时候没有办法打开本机的5700端口。。。

用 `docker-compose ps`  看docker信息

  Name                 Command                           State      Ports
【--------------------------------------------------------------】
opt_web_1   ./docker/docker-entrypoint.sh   Restarting   

用`docker-compose logs`命令
web_1  | /ql/shell/share.sh: line 324: /ql/log/task_error.log: No such file or directory
web_1  | /ql/shell/share.sh: line 324: /ql/log/task_error.log: No such file or directory
web_1  | /ql/shell/share.sh: line 324: /ql/log/task_error.log: No such file or directory
web_1  | /ql/shell/share.sh: line 324: /ql/log/task_error.log: No such file or directory
web_1  | /ql/shell/share.sh: line 324: /ql/log/task_error.log: No such file or directory
web_1  | /ql/shell/share.sh: line 324: /ql/log/task_error.log: No such file or directory

### What is expected?

期望能正常运行哈。。

### What is actually happening?

不停的重启

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (2) arm64 Neoverse-N1
    Memory: 10.58 GB / 11.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 12.22.9 - /usr/bin/node
    npm: 8.5.1 - /usr/bin/npm
```

**Comment by dust2k** [comment]
大佬们有碰到这个问题吗？？？

**Comment by whyour** [comment]
> 大佬们有碰到这个问题吗？？？

看容器的错，看你镜像是不是最新的

**Comment by dust2k** [comment]
> > 大佬们有碰到这个问题吗？？？
> 
> 看容器的错，看你镜像是不是最新的。 这个错没影响

我之前装了个老版本，可能没删除干净，重新删除一下。。。
