### ISSUE TITLE
docker部署，一直报错parse error at 7，但是可以进去。

### ISSUE THREAD

**Issue by hyy34** [whyour/qinglong#1938]
### Qinglong version

2.15.14

### Steps to reproduce

日志里一直显示，crond[174]: user root: parse error at 7

### What is expected?

是否对日常使用有影响。

### What is actually happening?

日志：

   │     Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │

   │                                                                 │

   ╰─────────────────────────────────────────────────────────────────╯

Packages are hard linked from the content-addressable store to the virtual store.

  Content-addressable store is at: /ql/data/.pnpm-store/v3

  Virtual store is at:             node_modules/.pnpm

dependencies:

+ got 11.8.6

+ nodemailer 6.9.1

+ tough-cookie 4.1.2

+ tunnel 0.0.6

+ ws 7.5.9

devDependencies: skipped

Done in 2.3s

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动pm2服务========================

[PM2][WARN] Applications schedule, public, panel not running, starting...

[PM2][WARN] App schedule has option 'wait_ready' set, waiting for app to be ready...

[PM2][WARN] App public has option 'wait_ready' set, waiting for app to be ready...

[PM2] App [schedule] launched (1 instances)

[PM2][WARN] App panel has option 'wait_ready' set, waiting for app to be ready...

[PM2] App [public] launched (1 instances)

[PM2] App [panel] launched (1 instances)

┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐

│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │

├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤

│ 2  │ panel       │ default     │ N/A     │ fork    │ 141      │ 3s     │ 0    │ online    │ 0%       │ 109.3mb  │ root     │ disabled │

│ 1  │ public      │ default     │ N/A     │ fork    │ 118      │ 4s     │ 0    │ online    │ 0%       │ 92.9mb   │ root     │ disabled │

│ 0  │ schedule    │ default     │ N/A     │ fork    │ 117      │ 4s     │ 0    │ online    │ 0%       │ 71.4mb   │ root     │ disabled │

└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

====================6. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...

############################################################

crond[174]: crond (busybox 1.36.0) started, log level 8

crond[174]: user root: parse error at 7

crond[174]: user root: parse error at 7

crond[174]: user root: parse error at 7

crond[174]: user root: parse error at 7

crond[174]: user root: parse error at 7

crond[174]: user root: parse error at 7

 无限循环crond[174]: user root: parse error at 7

**Comment by whyour** [comment]
你的定时任务有个定时规则写错了，没影响

**Comment by 1jinghua** [comment]
我也是报这个错，但是进不去 进后台就弹Request failed with status code 500
