### ISSUE TITLE
查看日志的选择框，建议改成固定板式

### ISSUE THREAD

**Issue by lxr760** [whyour/qinglong#194]
这个框，目前是下拉形式。点一下，就会隐藏，当需要多次点击的时候，非常不方便。特别是手机端操作。

建议改成固定展示，不隐藏，放在最右边或者最左，保持一直显示状态

![image](https://user-images.githubusercontent.com/8476457/119664745-3b8d7500-be66-11eb-9cef-672dbe19811c.png)

**Comment by whyour** [comment]
@lxr760 可以搜索

**Comment by lxr760** [comment]
> @lxr760 可以搜索

搜索功能我知道，但是查看多个日志的时候不方便啊。

**Comment by longwangjiang** [comment]
确实不方便，这个还是目录形式那种的好用。建议修改，定时任务那里不能关联日志文件。
