### ISSUE TITLE
docker重启后，青龙面板的订阅和依赖都没了

### ISSUE THREAD

**Issue by xiaxuesis** [whyour/qinglong#1942]
### Qinglong version

2.15.14

### Steps to reproduce

正常安装docker，安装面板，但是docker重启过后，面板的订阅和依赖都不见了

### What is expected?

重启后，面板的配置不能保留吗？

### What is actually happening?

重启后面板的订阅和依赖都不见了

**Comment by liuyijie4416** [comment]
你docker容器没弄持久化吧

**Comment by whyour** [comment]
参考 https://github.com/whyour/qinglong#docker-%E9%83%A8%E7%BD%B2 部署操作
