### ISSUE TITLE
企业微信应用推送不了

### ISSUE THREAD

**Issue by qq527747708** [whyour/qinglong#1945]
### Qinglong version

 v2.15.14

### Steps to reproduce

按照说明里设置了提示提示通知发送失败，请检查参数

### What is expected?

希望可以企业微信应用推送

### What is actually happening?

提示通知发送失败，请检查参数

**Comment by whyour** [comment]
参数有问题，下个版本会返回详情的错误

**Comment by thsrite** [comment]
> 参数有问题，下个版本会返回详情的错误

大佬，企业微信可以添加个消息推送代理地址吗？
server 
{
    listen 443;
    server_name qyapi.weixin.qq.com;

    location /cgi-bin/gettoken {
  		proxy_pass https://qyapi.weixin.qq.com;
	}
	location /cgi-bin/message/send 
	{
  		proxy_pass https://qyapi.weixin.qq.com; 
	}
}

**Comment by whyour** [comment]
> > 参数有问题，下个版本会返回详情的错误
> 
> 大佬，企业微信可以添加个消息推送代理地址吗？ 自建微信代理url http://proxy.***.cn
> 
> ```
> server 
> {
>     listen 80;
>     server_name proxy.***.cn;
> 
>     location /cgi-bin/gettoken {
>   		proxy_pass https://qyapi.weixin.qq.com;
> 	}
> 	location /cgi-bin/message/send 
> 	{
>   		proxy_pass https://qyapi.weixin.qq.com; 
> 	}
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/54088512/240781596-4eecbfec-34a5-4131-bde9-0ba6ee20d4e5.png)

为什么会加代理呢，你这是自定义url？

**Comment by thsrite** [comment]
> > > 参数有问题，下个版本会返回详情的错误
> > 
> > 
> > 大佬，企业微信可以添加个消息推送代理地址吗？ 自建微信代理url http://proxy.***.cn
> > ```
> > server 
> > {
> >     listen 80;
> >     server_name proxy.***.cn;
> > 
> >     location /cgi-bin/gettoken {
> >   		proxy_pass https://qyapi.weixin.qq.com;
> > 	}
> > 	location /cgi-bin/message/send 
> > 	{
> >   		proxy_pass https://qyapi.weixin.qq.com; 
> > 	}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/54088512/240781596-4eecbfec-34a5-4131-bde9-0ba6ee20d4e5.png)
> 
> 为什么会加代理呢，你这是自定义url？

嗯 自定义url
家宽ip经常变动，用一台固定ip的vps搭建nginx，添加上述配置，企业应用可信ip配置vps的ip
这边服务用vps的域名，vps那边通过nginx转发到企业应用的相应接口，这样就可过可信ip限制

**Comment by shenshangshang** [comment]
确实需要这个功能，家宽不搞代理很难的

**Comment by Toylee2019** [comment]
更新到v2.15.16了  这个VPS代理怎么设置呢

**Comment by whyour** [comment]
QYWX_ORIGIN 环境变量

**Comment by zgqq** [comment]
> 参数有问题，下个版本会返回详情的错误

现在能从哪里看到吗
