### ISSUE TITLE
N1升级最新镜像启动不了

### ISSUE THREAD

**Issue by kan3Git** [whyour/qinglong#1946]
### Qinglong version

2.15.14

### Steps to reproduce

服务启动超时
请先按如下方式修复，如果无法解决，可结合日志[提交 issue](https://github.com/whyour/qinglong/issues/new?assignees=&labels=&template=bug_report.yml)
1. 宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
2. 容器内执行 ql -l check、ql -l update
Name resolution failed for target dns:localhost:5500

多次执行 ql -l check、ql -l update都不行

### What is expected?

 ql -l check

### What is actually happening?

=====> 开始检测

changed 1 package in 7s
fetch https://mirrors.aliyun.com/alpine/v3.18/main/aarch64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.18/community/aarch64/APKINDEX.tar.gz
OK: 147 MiB in 82 packages
Writing to /root/.config/pip/pip.conf
Lockfile is up to date, resolution step is skipped
Already up to date

   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │                Update available! 8.3.1 → 8.5.1.                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.5.1   │
   │                Run "pnpm add -g pnpm" to update.                │
   │                                                                 │
   │     Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

Done in 9.5s
 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 WARN  deprecated har-validator@5.1.5: this library is no longer supported
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Already up to date
Progress: resolved 296, reused 274, downloaded 0, added 0, done
Done in 21.7s
---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

安装 /ql 依赖包...

devDependencies: skipped

> @ postinstall /ql
> max setup 2>/dev/null || true

Done in 9.5s
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

安装 /ql/data/scripts 依赖包...

devDependencies: skipped

Done in 5.6s
---> 脚本依赖安装完成

---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<!DOCTYPE html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="shortcut icon" href="./images/favicon.svg">
<link rel="stylesheet" href="./umi.8a0eaca6.css">
<script src="https://gw.alipayobjects.com/os/lib/react/18.2.0/umd/react.production.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
</head>
<body>
<div id="root"></div>
<script src="./umi.efb78224.js"></script>

</body></html>

=====> 面板服务启动正常

=====> 检测nginx服务
   92 nginx: master process nginx -c /etc/nginx/nginx.conf
 7042 nginx: worker process
 7044 nginx: worker process
 7045 nginx: worker process
 7046 nginx: worker process

=====> nginx服务正常

---> pm2日志
2023-05-23T22:40:23: info:    ✌️ DB loaded
2023-05-23T22:40:23: info:    ✌️ Init file down
2023-05-23T22:40:24: info:    ✌️ Sentry loaded
2023-05-23T22:40:27: info:    ✌️ Dependency Injector loaded
2023-05-23T22:40:27: [HPM] Proxy created: /  -> http://localhost:5400/api
2023-05-23T22:40:27: [HPM] Proxy rewrite rule created: "/api/public" ~> ""
2023-05-23T22:40:28: info:    ✌️ Express loaded
2023-05-23T22:40:29: Error: 14 UNAVAILABLE: Name resolution failed for target dns:localhost:5500
2023-05-23T22:40:29:     at callErrorFromStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/call.ts:81:17)
2023-05-23T22:40:29:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client.ts:356:55)
2023-05-23T22:40:29:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
2023-05-23T22:40:29:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
2023-05-23T22:40:29:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
2023-05-23T22:40:29:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
2023-05-23T22:40:29: for call at
2023-05-23T22:40:29:     at ServiceClientImpl.makeUnaryRequest (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client.ts:326:30)
2023-05-23T22:40:29:     at ServiceClientImpl.addCron (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
2023-05-23T22:40:29:     at /ql/back/schedule/client.ts:19:19
2023-05-23T22:40:29:     at new Promise (<anonymous>)
2023-05-23T22:40:29:     at Client.addCron (/ql/back/schedule/client.ts:18:12)
2023-05-23T22:40:29:     at CronService.autosave_crontab (/ql/back/services/cron.ts:593:22)
2023-05-23T22:40:29:     at exports.default (/ql/back/loaders/initData.ts:128:3)
2023-05-23T22:40:29:     at Object.exports.default (/ql/back/loaders/app.ts:16:3)
2023-05-23T22:40:29:     at startServer (/ql/back/app.ts:16:3) {
2023-05-23T22:40:29:   code: 14,
2023-05-23T22:40:29:   details: 'Name resolution failed for target dns:localhost:5500',
2023-05-23T22:40:29:   metadata: Metadata { internalRepr: Map(0) {}, options: {} }
2023-05-23T22:40:29: }
2023-05-23T22:40:29: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-05-23T22:40:29: Error: 14 UNAVAILABLE: Name resolution failed for target dns:localhost:5500
2023-05-23T22:40:29:     at callErrorFromStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/call.ts:81:17)
2023-05-23T22:40:29:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client.ts:356:55)
2023-05-23T22:40:29:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
2023-05-23T22:40:29:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
2023-05-23T22:40:29:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
2023-05-23T22:40:29:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
2023-05-23T22:40:29: for call at
2023-05-23T22:40:29:     at ServiceClientImpl.makeUnaryRequest (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/client.ts:326:30)
2023-05-23T22:40:29:     at ServiceClientImpl.addCron (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
2023-05-23T22:40:29:     at /ql/back/schedule/client.ts:19:19
2023-05-23T22:40:29:     at new Promise (<anonymous>)
2023-05-23T22:40:29:     at Client.addCron (/ql/back/schedule/client.ts:18:12)
2023-05-23T22:40:29:     at CronService.autosave_crontab (/ql/back/services/cron.ts:593:22)
2023-05-23T22:40:29:     at exports.default (/ql/back/loaders/initData.ts:128:3)
2023-05-23T22:40:29:     at Object.exports.default (/ql/back/loaders/app.ts:16:3)
2023-05-23T22:40:29:     at startServer (/ql/back/app.ts:16:3)

=====> 检测后台

[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])
[PM2] Applying action reloadProcessId on app [public](ids: [ 1 ])
[PM2] [schedule](0) ✓
[PM2] [public](1) ✓
[PM2] Applying action reloadProcessId on app [panel](ids: [ 2 ])
[PM2] [panel](2) ✓
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 674      │ 3s     │ 6    │ online    │ 0%       │ 63.8mb   │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 644      │ 6s     │ 6    │ online    │ 109.5%   │ 82.9mb   │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 687      │ 0      │ 339… │ launching │ 0%       │ 0b       │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

=====> 检测结束

**Comment by whyour** [comment]
容器内看下  pm2 logs schedule

**Comment by kan3Git** [comment]
root@qinglong:/ql $ pm2 logs schedule
[TAILING] Tailing last 15 lines for [schedule] process (change the value with --lines option)
/root/.pm2/logs/schedule-out.log last 15 lines:
/root/.pm2/logs/schedule-error.log last 15 lines:
0|schedule | 2023-05-25T16:35:05: Error: server must be bound in order to start
0|schedule | 2023-05-25T16:35:05:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule | 2023-05-25T16:35:05:     at /ql/back/schedule/index.ts:17:12
0|schedule | 2023-05-25T16:35:05:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule | 2023-05-25T16:35:05:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule | 2023-05-25T16:35:09: Error: server must be bound in order to start
0|schedule | 2023-05-25T16:35:09:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule | 2023-05-25T16:35:09:     at /ql/back/schedule/index.ts:17:12
0|schedule | 2023-05-25T16:35:09:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule | 2023-05-25T16:35:09:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule | 2023-05-25T16:35:13: Error: server must be bound in order to start
0|schedule | 2023-05-25T16:35:13:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule | 2023-05-25T16:35:13:     at /ql/back/schedule/index.ts:17:12
0|schedule | 2023-05-25T16:35:13:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule | 2023-05-25T16:35:13:     at processTicksAndRejections (node:internal/process/task_queues:77:11)

0|schedule  | 2023-05-25T16:35:16: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:16:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:16:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:16:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:16:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule  | 2023-05-25T16:35:20: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:20:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:20:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:20:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:20:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule  | 2023-05-25T16:35:23: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:23:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:23:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:23:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:23:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule  | 2023-05-25T16:35:27: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:27:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:27:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:27:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:27:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule  | 2023-05-25T16:35:30: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:30:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:30:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:30:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:30:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule  | 2023-05-25T16:35:33: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:33:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:33:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:33:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:33:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule  | 2023-05-25T16:35:37: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:37:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:37:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:37:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:37:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule  | 2023-05-25T16:35:40: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:40:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:40:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:40:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:40:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule  | 2023-05-25T16:35:44: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:44:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:44:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:44:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:44:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule  | 2023-05-25T16:35:47: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:47:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:47:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:47:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:47:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|schedule  | 2023-05-25T16:35:51: Error: server must be bound in order to start
0|schedule  | 2023-05-25T16:35:51:     at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:683:13)
0|schedule  | 2023-05-25T16:35:51:     at /ql/back/schedule/index.ts:17:12
0|schedule  | 2023-05-25T16:35:51:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/src/server.ts:382:30
0|schedule  | 2023-05-25T16:35:51:     at processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by whyour** [comment]
> server must be bound in order to start

你 5500 端口被占用了？

**Comment by kan3Git** [comment]
root@N1:~# lsof -i:5500
root@N1:~# netstat -anptl | grep 5500
没有啊

**Comment by whyour** [comment]
试过使用 宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>  方式更新吗

**Comment by kan3Git** [comment]
![25db04657969058f73bda4c4a3e91f1](https://github.com/whyour/qinglong/assets/57619461/c4da144a-ccdc-457f-bde7-fd85b456832a)
宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 方式更新过了

**Comment by whyour** [comment]
> node /ql/build/schedule/index.js

node /ql/static/build/schedule/index.js

**Comment by kan3Git** [comment]
root@qinglong:/ql $ node /ql/static/build/schedule/index.js
/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/build/src/server.js:496
            throw new Error('server must be bound in order to start');
            ^

Error: server must be bound in order to start
    at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/build/src/server.js:496:19)
    at /ql/static/build/schedule/index.js:19:12
    at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/build/src/server.js:251:36
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.16.0
root@qinglong:/ql $

**Comment by whyour** [comment]
> root@qinglong:/ql $ node /ql/static/build/schedule/index.js /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/build/src/server.js:496 throw new Error('server must be bound in order to start'); ^
> 
> Error: server must be bound in order to start at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/build/src/server.js:496:19) at /ql/static/build/schedule/index.js:19:12 at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/build/src/server.js:251:36 at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
> 
> Node.js v18.16.0 root@qinglong:/ql $

n1 docker 是 host 模式？

**Comment by kan3Git** [comment]
> > root@qinglong:/ql $ node /ql/static/build/schedule/index.js /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/build/src/server.js:496 throw new Error('server must be bound in order to start'); ^
> > Error: server must be bound in order to start at Server.start (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/build/src/server.js:496:19) at /ql/static/build/schedule/index.js:19:12 at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.14/node_modules/@grpc/grpc-js/build/src/server.js:251:36 at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
> > Node.js v18.16.0 root@qinglong:/ql $
> 
> n1 docker 是 host 模式？

是的

**Comment by whyour** [comment]
> Error: Name resolution failed for target dns:localhost:5500

你这是 localhost 解析不了吗， /ql/static/build/schedule/index.js 把这个文件里的 localhost 改成 127.0.0.1 试试
n1 上 ping localhost 试试

**Comment by kan3Git** [comment]
> 

 在/etc/hosts添加 localhost 解析
127.0.0.1       localhost

**Comment by kan3Git** [comment]
> > Error: Name resolution failed for target dns:localhost:5500
> 
> 你这是 localhost 解析不了吗， /ql/static/build/schedule/index.js 把这个文件里的 localhost 改成 127.0.0.1 试试 n1 上 ping localhost 试试
真是神奇，能ping通127.0.0.1和www.baidu.com，ping localhost提示bad address 'localhost'，
 在/etc/hosts添加 localhost 解析解决了
127.0.0.1       localhost
感谢大佬
