### ISSUE TITLE
建议青龙 支持多账号 登录，或者取消 一个账号同时登陆的限制

### ISSUE THREAD

**Issue by happybeta** [whyour/qinglong#1947]
### Suggested solution

早先可以先在配置文件config/auth.json 里增加多账户的支持。

**Comment by HangJau** [comment]
> ### Suggested solution
> 早先可以先在配置文件config/auth.json 里增加多账户的支持。

大佬，这个具体的格式是什么样的？ 我看现在最新的就一个dict目录，下面是账户信息，如果是多个是否是多层？

**Comment by powersee** [comment]
赞同，目前一台 win 一台 Mac，这边登录那边就被挤掉……希望可以支持多台设备登录。

**Comment by happybeta** [comment]
> > ### Suggested solution
> > 早先可以先在配置文件config/auth.json 里增加多账户的支持。
> 
> 大佬，这个具体的格式是什么样的？ 我看现在最新的就一个dict目录，下面是账户信息，如果是多个是否是多层？

目前不支持呢
