### ISSUE TITLE
怎么设置青龙运行脚本后通知呢？比如server chan

### ISSUE THREAD

**Issue by smartnikocj** [whyour/qinglong#195]
怎么设置青龙运行脚本后通知呢？比如server chan

**Comment by SiupoLeung** [comment]
...自己添加对应的应用变量。。。

**Comment by smartnikocj** [comment]
> ...自己添加对应的应用变量。。。

小白一个，有具体或者大致的操作流程吗？谢谢！

**Comment by BIGBbox** [comment]
> export PUSH_KEY="获取的token"
> 这个是server酱的。。其他的都差不多

我懂了

**Comment by smartnikocj** [comment]
> export PUSH_KEY="获取的token"
> 这个是server酱的。。其他的都差不多

明白了。谢谢！那再请教一个，怎么替换或者删除相应的PUSH_KEY呢？

**Comment by smartnikocj** [comment]
![image](https://user-images.githubusercontent.com/20366111/119996871-b8a12180-c001-11eb-9069-3f9fec6daae3.png)
添加了环境变量害还是不会通知，当时按照telegram的指南安装，跟官网的对比了下，不知道是不是缺少了scripts文件夹？

> export PUSH_KEY="获取的token"
> 这个是server酱的。。其他的都差不多

![image](https://user-images.githubusercontent.com/20366111/119997079-ed14dd80-c001-11eb-8a43-8c33efad426e.png)
添加了环境变量害还是不会通知，当时按照telegram的指南安装，跟官网的对比了下，不知道是不是缺少了scripts文件夹？

**Comment by longwangjiang** [comment]
bot？这个要改bot文件参数的，改完了容器里ql bot运行一遍一般不会有问题。在配置文件里要把通知启动。然后重启容器。

**Comment by smartnikocj** [comment]
> bot？这个要改bot文件参数的，改完了容器里ql bot运行一遍一般不会有问题。在配置文件里要把通知启动。然后重启容器。
> 
> ## 是否自动启动bot，默认不启动，设置为true时自动启动
> AutoStartBot="true"
> 配置文件里这个你没看到？

我这个是启动的。不是telegram的bot哦。是推送到微信的，比如pushplus或者server chan.

**Comment by smartnikocj** [comment]
> export PUSH_KEY="获取的token"
> 这个是server酱的。。其他的都差不多

我用了这种方法，设置了server酱和pushplus，然后运行东东农场微信也没有收到通知。用env查看环境变量里面都有相应的变量。

**Comment by smartnikocj** [comment]
> > export PUSH_KEY="获取的token"
> > 这个是server酱的。。其他的都差不多
> 
> 我用了这种方法，设置了server酱和pushplus，然后运行东东农场微信也没有收到通知。用env查看环境变量里面都有相应的变量。

重新进入docker，env就消失了。不知道怎么添加。。。。。

**Comment by whyour** [comment]
> > > export PUSH_KEY="获取的token"
> > > 这个是server酱的。。其他的都差不多
> > 
> > 
> > 我用了这种方法，设置了server酱和pushplus，然后运行东东农场微信也没有收到通知。用env查看环境变量里面都有相应的变量。
> 
> 重新进入docker，env就消失了。不知道怎么添加。。。。。

env 在config里面配置，docker启动映射config db log目录

**Comment by smartnikocj** [comment]
> > > > export PUSH_KEY="获取的token"
> > > > 这个是server酱的。。其他的都差不多
> > > 
> > > 
> > > 我用了这种方法，设置了server酱和pushplus，然后运行东东农场微信也没有收到通知。用env查看环境变量里面都有相应的变量。
> > 
> > 
> > 重新进入docker，env就消失了。不知道怎么添加。。。。。
> 
> env 在config里面配置，docker启动映射config db log目录

还是不懂怎么弄呀哥，怎么配置呀，有教程或者连接不。谢谢！

**Comment by smartnikocj** [comment]
> > > > export PUSH_KEY="获取的token"
> > > > 这个是server酱的。。其他的都差不多
> > > 
> > > 
> > > 我用了这种方法，设置了server酱和pushplus，然后运行东东农场微信也没有收到通知。用env查看环境变量里面都有相应的变量。
> > 
> > 
> > 重新进入docker，env就消失了。不知道怎么添加。。。。。
> 
> env 在config里面配置，docker启动映射config db log目录

![image](https://user-images.githubusercontent.com/20366111/120054758-79f08300-c064-11eb-8de5-7a6baf25dbfb.png)
是这个？然后怎么添加呢？

**Comment by smartnikocj** [comment]
> > > > export PUSH_KEY="获取的token"
> > > > 这个是server酱的。。其他的都差不多
> > > 
> > > 
> > > 我用了这种方法，设置了server酱和pushplus，然后运行东东农场微信也没有收到通知。用env查看环境变量里面都有相应的变量。
> > 
> > 
> > 重新进入docker，env就消失了。不知道怎么添加。。。。。
> 
> env 在config里面配置，docker启动映射config db log目录

谢谢！搞定了！！感谢！
