### ISSUE TITLE
定時任務沒有執行

### ISSUE THREAD

**Issue by mm10079** [whyour/qinglong#1953]
### Qinglong version

v2.15.15

### Steps to reproduce

1. 從Truechats安裝qinglong，並完成設定
2. 定時任務新增腳本
3. 設定時間
4. 沒有執行

### What is expected?

在幾個禮拜前還能觸發定時執行

### What is actually happening?

1. 系統問題 (重新安裝，排除)
2. 腳本問題 (更換腳本，排除)
3. 設定問題 (乾淨安裝，排除)
4. 版本問題 (可能)

### System Info

```shell
Truenas scale
Truechart-Docker
```

**Comment by whyour** [comment]
镜像使用的哪个版本 whyour/qinglong:latest 还是  whyour/qinglong:develop，docker ps 查看容器状态是否 healthy

**Comment by mm10079** [comment]
> 镜像使用的哪个版本 whyour/qinglong:latest 还是 whyour/qinglong:develop，docker ps 查看容器状态是否 healthy

![image](https://github.com/whyour/qinglong/assets/55078752/1bf5a099-9564-4b30-85ed-7c98c66fd6e8)
Truecharts應該預設是latest
![image](https://github.com/whyour/qinglong/assets/55078752/343c12a6-9751-4c2d-884e-c05a3f468ad4)
手動執行任務還是能正常使用，僅定時執行沒有作業

**Comment by whyour** [comment]
> > 镜像使用的哪个版本 whyour/qinglong:latest 还是 whyour/qinglong:develop，docker ps 查看容器状态是否 healthy
> 
> ![image](https://user-images.githubusercontent.com/55078752/241922175-1bf5a099-9564-4b30-85ed-7c98c66fd6e8.png) Truecharts應該預設是latest ![image](https://user-images.githubusercontent.com/55078752/241922420-343c12a6-9751-4c2d-884e-c05a3f468ad4.png) 手動執行任務還是能正常使用，僅定時執行沒有作業

我没使用过 truecharts，我看 truecharts 自己备份了我的镜像，latest 是一个月之前的。如果用的是docker的话，能看到 服务所用的镜像吗

**Comment by whyour** [comment]
> ```shell
> Truechart-Docker
> ```

你的定时任务规则是怎么写的

**Comment by whyour** [comment]
<img width="1328" alt="image" src="https://github.com/whyour/qinglong/assets/22700758/fb9bc8bb-c355-4140-8a6d-d88eb80165f3">
我使用 tccr.io 的镜像测试是正常的

**Comment by mm10079** [comment]
似乎找到問題了
重開docker後就恢復運作了，但只要調整Crontab時間或是禁用重啟後，就無法正常執行定時任務

**Comment by whyour** [comment]
> 似乎找到問題了 重開docker後就恢復運作了，但只要調整Crontab時間或是禁用重啟後，就無法正常執行定時任務

无法复现

**Comment by zlq1503** [comment]
我也是同样的问题，重启容器后就正常了。 用的是  whyour/qinglong:latest 镜像  v2.15.15版本
