### ISSUE TITLE
docker debian版貌似没有crond，导致任务没法自动执行。

### ISSUE THREAD

**Issue by dominicx** [whyour/qinglong#1955]
### Qinglong version

2.15.15

### Steps to reproduce

切换到debian作为docker基础进行了，但时候貌似这个镜像没有cron。导致压根任务无法得到执行。

docker-entrypoint.sh 中写了crond -f >/dev/null。容器启动这里会报错。

docker exec -it qinglong /bin/bash 之后，crontab -l 显示bash: crontab: command not found
crond -f也是：bash: crontd: command not found

表示这个基础镜像没有带crond 导致压根没有执行。

今天才拉去的docker:debian

### What is expected?

容器自带crond crontab工具。

### What is actually happening?

每次都是

**Comment by whyour** [comment]
没说debian用的是crontab，使用最新镜像，看你容器是否healthy，面板能否正常进入

**Comment by whyour** [comment]
> > 
> 
> 最新镜像，下午才拉的。面板正常进入。

docker ps 容器状态是 healthy 吗，那说明服务正常，你新建一个任务看跑不跑

**Comment by jincandev** [comment]
一直是找不到crond命令，但我尝试修改Docker容器文件`docker-entrypoint.sh`后，可以正常运行，修改如下：
