### ISSUE TITLE
fork: retry: Resource temporarily unavailable 

### ISSUE THREAD

**Issue by happybeta** [whyour/qinglong#1959]
### Clear and concise description of the problem

/ql/shell/api.sh: fork: retry: Resource temporarily unavailable
/ql/shell/api.sh: fork: retry: Resource temporarily unavailable

啥原因 ？

### Suggested solution

na

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
宿主机更新 `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>`
