### ISSUE TITLE
重新启动VPS，docker运行不起来

### ISSUE THREAD

**Issue by SMG0208** [whyour/qinglong#196]
[root@PeriodicGrandiose-VM ~]# systemctl start docker
[root@PeriodicGrandiose-VM ~]# docker exec -it JD bash
Error response from daemon: Container 243a7d68a63c20fe0f96937bb1d9cd8f59e0e9224d5ff07a556e645ef0a76ecd is restarting, wait until the container is running

**Comment by SMG0208** [comment]
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'

**Comment by whyour** [comment]
是什么环境，为啥不识别这个字符
