### ISSUE TITLE
更新死了

### ISSUE THREAD

**Issue by klcb2010** [whyour/qinglong#1961]
### Qinglong version

2.15.15

### Steps to reproduce

[logs.rar.txt](https://github.com/whyour/qinglong/files/11624410/logs.rar.txt)
去掉扩展名  各种修复都试了  没法用 

![截屏图片](https://github.com/whyour/qinglong/assets/32628414/69ccdca0-72de-4574-b59e-dbeaf08c51bb)

**Comment by happybeta** [comment]
我也是 ，这个版本可能CPU、内存占用太大了。
咋回退? 

```
CONTAINER ID   NAME          CPU %      MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
b413217240e5   qinglong      1563.87%   11.06GiB / 31.35GiB   35.28%    8.88MB / 1.14MB   349MB / 4.75GB    4012

```

**Comment by klcb2010** [comment]
> 我也是 ，这个版本可能CPU、内存占用太大了。 咋回退?
> 
> ```
> CONTAINER ID   NAME          CPU %      MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
> b413217240e5   qinglong      1563.87%   11.06GiB / 31.35GiB   35.28%    8.88MB / 1.14MB   349MB / 4.75GB    4012
> ```

导出脚本和数据 删除容器 重新安装指定版本

**Comment by whyour** [comment]
看 pm2 logs
