### ISSUE TITLE
建议 定时任务增加分组功能

### ISSUE THREAD

**Issue by oudaiyi** [whyour/qinglong#1963]
### Clear and concise description of the problem

拉取的仓库太多了，各种定时任务混杂在一起，增加分组功能，将不同仓库的任务放置到不同的组内方便管理

### Suggested solution

拉取的仓库太多了，各种定时任务混杂在一起，增加分组功能，将不同仓库的任务放置到不同的组内方便管理

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by happybeta** [comment]
新版本有视图功能了。
