### ISSUE TITLE
更新后报错

### ISSUE THREAD

**Issue by Lubenwei66** [whyour/qinglong#1964]
### Qinglong version

2.15.14

### Steps to reproduce

更新2.15.15

### What is expected?

解决报错

### What is actually happening?

t/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-06-05T00:15:40: Error: Cannot find module 'http-proxy-middleware'
2|panel    | 2023-06-05T00:15:40: Require stack:
2|panel    | 2023-06-05T00:15:40: - /ql/static/build/loaders/express.js
2|panel    | 2023-06-05T00:15:40: - /ql/static/build/loaders/app.js
2|panel    | 2023-06-05T00:15:40: - /ql/static/build/app.js
2|panel    | 2023-06-05T00:15:40:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2|panel    | 2023-06-05T00:15:40:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-06-05T00:15:40:     at require (node:internal/modules/cjs/helpers:102:18)
2|panel    | 2023-06-05T00:15:40:     at Object.<anonymous> (/ql/back/loaders/express.ts:18:1)
2|panel    | 2023-06-05T00:15:40:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
2|panel    | 2023-06-05T00:15:40:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2|panel    | 2023-06-05T00:15:40:     at Module.load (node:internal/modules/cjs/loader:981:32)
2|panel    | 2023-06-05T00:15:40:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2|panel    | 2023-06-05T00:15:40:     at Module.require (node:internal/modules/cjs/loader:1005:19)
2|panel    | 2023-06-05T00:15:40:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

**Comment by whyour** [comment]
宿主机更新 `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>`
