### ISSUE TITLE
分支导向不对

### ISSUE THREAD

**Issue by maryjeck** [whyour/qinglong#1965]
### Qinglong version

2.15.15

### Steps to reproduce

更新订阅时，我填写的分支为main，为什么更新的orgin，如日志

>开始更新仓库：/ql/data/repo/zero205_JD_tencent_scf_main
>
>error: No such remote 'origin'
>
>error: No such remote 'origin'
>fatal: 'origin' does not appear to be a git repository
>fatal: Could not read from remote repository.
>
>Please make sure you have the correct access rights
>and the repository exists.
>
>## 执行结束... 2023-06-05 10:50:21  耗时 4 秒　　　　　
>
>更新/ql/data/repo/zero205_JD_tencent_scf_main失败，请检查网络...

### What is expected?

分支不对

### What is actually happening?

  无法更新

**Comment by whyour** [comment]
删除`/ql/data/repo/zero205_JD_tencent_scf_main`这个目录，重新拉取，你的目录内容有问题
