### ISSUE TITLE
希望能够支持带path的子目录反向代理

### ISSUE THREAD

**Issue by busyrat** [whyour/qinglong#1967]
### Clear and concise description of the problem

域名被限制了，只能扩展子目录，希望能够增加配置

类似效果参考 alist 中的对子目录进行反向代理

https://alist.nn.ci/zh/faq/howto.html#%E5%A6%82%E4%BD%95%E5%AF%B9%E5%AD%90%E7%9B%AE%E5%BD%95%E8%BF%9B%E8%A1%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86

### Suggested solution

比如
访问 localhost/alist/ --> 反向代理到了 localhost:5244
访问 localhost/ql/ --> 反向代理到了 localhost:5700

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
@busyrat https://t.me/jiao_long/378
