### ISSUE TITLE
V2.15.14 一直升级不了

### ISSUE THREAD

**Issue by cyxnzb** [whyour/qinglong#1968]
### Qinglong version

V2.15.14

## 开始执行... 2023-06-07 21:05:06

使用 gitee 源更新...

开始更新仓库：/ql
Fetching origin
fatal: couldn't find remote ref refs/heads/main
error: Could not fetch origin

更新青龙源文件失败，请检查网络...

### What is expected?

请教如何解决

### What is actually happening?

Fetching origin
fatal: couldn't find remote ref refs/heads/main
error: Could not fetch origin

### System Info

```shell
System:
    OS: Linux 5.15 Alpine Linux
    CPU: (2) x64 AMD EPYC 7K62 48-Core Processor
    Memory: 2.49 GB / 3.66 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 17.8.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
```

**Comment by whyour** [comment]
宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>

**Comment by cyxnzb** [comment]
> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR

好，感谢

**Comment by cyxnzb** [comment]
> 宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>

执行后，数据全没了，啥情况

**Comment by whyour** [comment]
@cyxnzb docker没映射目录吗

**Comment by cyxnzb** [comment]
> @cyxnzb docker没映射目录吗

按理说应该映射了，当初拉docker的时候是按照csdn的教程弄的，然后直接执行您给的指令后，也就是
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR qinglong

**Comment by cyxnzb** [comment]
> @cyxnzb docker没映射目录吗

之后就清空了

**Comment by whyour** [comment]
@cyxnzb 看github readme的命令，csdn不知道哪个版本的

**Comment by cyxnzb** [comment]
> @cyxnzb 看github readme的命令，csdn不知道哪个版本的

问题是，目前来看数据是不是没救了，没备份的话

**Comment by whyour** [comment]
@cyxnzb 找找你以前的命令，看备份在哪
