### ISSUE TITLE
不能正确处理带有空格的文件名

### ISSUE THREAD

**Issue by wavetg** [whyour/qinglong#1970]
### Qinglong version

2.15.15

### Steps to reproduce

仓库中带有空格的文件名会被识别为两个文件，从而导致系统报错，复制文件出错

### What is expected?

ql repo正常运行，更新仓库不出错

实际拉取的文件名是repo/MayoBlueSky_My-Actions_master/function/bilibili/bilibili copy.py

### What is actually happening?

```
更新/ql/data/repo/MayoBlueSky_My-Actions_master成功...


cp: cannot stat 'function/bilibili/bilibili': No such file or directory

cp: cannot stat 'copy.py': No such file or directory

检测到有新的定时任务：


MayoBlueSky_My-Actions_master/bilibili
MayoBlueSky_My-Actions_master/copy.py

开始尝试自动添加定时任务...

```
bilibili copy.py被解释为两个文件

### Any additional comments?

```
whyour/qinglong/shell/update.sh

  for file in ${files}; do
    filename=$(basename $file)
    cp -f $file "$dir_scripts/${uniq_path}/${filename}"
```

files变量以换行符分割路径，路径中如果存在空格，shell会错误的将空格也识别为分隔符
file变量应该用花括号包裹或者使用双引号“${file}”，避免 basename识别变量边界错误

```
  oldIFS=$IFS
  IFS=$'\n'
  for file in ${files}; do
    filename=$(basename "${file}")
    ...
  done
  IFS=$oldIFS
```

我不太会shell，应该有更优雅的方式，或者将files分割为数组再遍历？

**Comment by whyour** [comment]
> 发现修改后虽然不报错了，但是始终无法成功添加定时任务，估计后面还有问题，对带空格的文件名无法处理
> 
> ![image](https://user-images.githubusercontent.com/19207540/244251995-93069cf7-992f-4ef9-90b5-6425cd8ff331.png)

添加失败报什么错

**Comment by whyour** [comment]
2.15.16 修复了黑名单带空格，创建任务暂不修复
