### ISSUE TITLE
不能处理加密的new Env

### ISSUE THREAD

**Issue by wavetg** [whyour/qinglong#1971]
### Qinglong version

2.15.15

### Steps to reproduce

拉取仓库，或者单个脚本时，脚本经过特殊加密，导致

`cron_name=$(grep "new Env" $file | awk -F "\(" '{print $2}' | awk -F "\)" '{print $1}' | sed 's:^.\(.*\).$:\1:' | head -1)` 

解析错误，如果cron_name的值带有引号时，使用add_cron_api "$cron_line:$cmd_task $file:$cron_name:$SUB_ID" 会报错

[对应的脚本](https://github.com/a65101855/zyk/blob/main/tmuyun/tmuyun_dy.js)

### What is expected?

不求处理加密，翻转的js代码，解析出正确的cron_name，只要能正确添加任务不报错即可，任务名什么的无所谓

### What is actually happening?

![image](https://github.com/whyour/qinglong/assets/19207540/d6f4c5bd-4a96-4ece-a79c-76006f1a11b6)

### Any additional comments?

我在cron_name的解析的最后加入了替换所有双引号的操作，能正确添加任务了

**Comment by whyour** [comment]
2.15.16 已修复
