### ISSUE TITLE
docker版本脚本管理与装载文件不同步

### ISSUE THREAD

**Issue by xuxiaohu6** [whyour/qinglong#1974]
### Qinglong version

2.15.15

### Steps to reproduce

使用的是docker版本2.15.15，在安装时把ql/scripts脚本目录装载映射到了本地的一个目录。
当通过青龙面板的脚本管理来修改脚本时（包括修改文件和删除新建文件），（群晖）本地的文件管理目录不发生相应变化。
同样，当用（群晖）本地的文件管理来修改文件时，青龙面板的脚本管理里面的文件也是不变，清空浏览器缓存和cookie等信息也是如此，但通过docker exec -it ql bash，cd scripts，ls来查看的文件却是修改后的（与（群晖）本地的文件管理保持一致），当重启青龙后，青龙面板的脚本管理的脚本就会变成修改后。

### What is expected?

本地的文件管理的文件与青龙面板脚本管理里面的可以实时同步，至少刷新一下网页可以在青龙里面看到新的文件。

### What is actually happening?

none

**Comment by whyour** [comment]
@xuxiaohu6 查看github readme映射目录，早就改成data目录了
