### ISSUE TITLE
执行任务报错 timeout: the monitored command dumped core /ql/shell/otask.sh: line 90: 28427 Segmentation fault      $timeoutCmd $which_program $file_param

### ISSUE THREAD

**Issue by dq1024** [whyour/qinglong#1975]
### Qinglong version

2.15.14

### Steps to reproduce

执行任务报错 timeout: the monitored command dumped core /ql/shell/otask.sh: line 90: 28427 Segmentation fault      $timeoutCmd $which_program $file_param

### What is expected?

执行任务报错 timeout: the monitored command dumped core /ql/shell/otask.sh: line 90: 28427 Segmentation fault      $timeoutCmd $which_program $file_param

### What is actually happening?

执行任务报错 timeout: the monitored command dumped core /ql/shell/otask.sh: line 90: 28427 Segmentation fault      $timeoutCmd $which_program $file_param

### System Info

```shell
执行任务报错 timeout: the monitored command dumped core /ql/shell/otask.sh: line 90: 28427 Segmentation fault      $timeoutCmd $which_program $file_param
```

### Any additional comments?

执行任务报错 timeout: the monitored command dumped core /ql/shell/otask.sh: line 90: 28427 Segmentation fault      $timeoutCmd $which_program $file_param

**Comment by whyour** [comment]
怎么复现的
