### ISSUE TITLE
更新订阅检测到任务却不添加任务

### ISSUE THREAD

**Issue by lq-259** [whyour/qinglong#1976]
### Qinglong version

2.15.15

### Steps to reproduce

手动订阅或自动订阅

### What is expected?

更新订阅检测到任务然后自动添加任务

### What is actually happening?

更新订阅检测到任务却不添加任务

### Any additional comments?

# 开始执行... 2023-06-12 13:20:44

开始更新仓库：/ql/data/repo/smallfawn_QLScriptPublic

From https://gh.yswl.cf/https://github.com/smallfawn/QLScriptPublic
 * branch            main       -> FETCH_HEAD

 + 205a16f...7cc3819 main       -> origin/main  (forced update)

更新/ql/data/repo/smallfawn_QLScriptPublic成功...

检测到有新的定时任务：

smallfawn_QLScriptPublic/凯翼汽车.js
smallfawn_QLScriptPublic/Tank.js
smallfawn_QLScriptPublic/易学家园.js
smallfawn_QLScriptPublic/Coca.py
smallfawn_QLScriptPublic/美数-shib.js
smallfawn_QLScriptPublic/mys.js
smallfawn_QLScriptPublic/dygy.js

## 执行结束... 2023-06-12 13:21:00  耗时 15 秒

**Comment by whyour** [comment]
编辑订阅时，要打开自动添加任务
<img width="488" alt="image" src="https://github.com/whyour/qinglong/assets/22700758/26b6bde0-7779-4ce2-b1f8-af0cd5422301">
