### ISSUE TITLE
浏览器无法启动启动/error 服务启动超时

### ISSUE THREAD

**Issue by yoseg** [whyour/qinglong#1977]
### Qinglong version

青龙v2.15.15

### Steps to reproduce

root@QL:/ql $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-06-12T17:46:52: PM2 log: Stopping app:public id:1
PM2        | 2023-06-12T17:46:52: PM2 log: App [schedule:0] exited with code [0] via signal [SIGINT]
PM2        | 2023-06-12T17:46:52: PM2 log: App [public:1] exited with code [0] via signal [SIGINT]
PM2        | 2023-06-12T17:46:53: PM2 log: pid=95 msg=process killed
PM2        | 2023-06-12T17:46:53: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-06-12T17:46:53: PM2 log: pid=96 msg=process killed
PM2        | 2023-06-12T17:46:53: PM2 log: App [public:1] starting in -fork mode-
PM2        | 2023-06-12T17:46:53: PM2 log: App [schedule:0] online
PM2        | 2023-06-12T17:46:53: PM2 log: Process 2 in a stopped status, starting it
PM2        | 2023-06-12T17:46:53: PM2 log: Stopping app:panel id:2
PM2        | 2023-06-12T17:46:53: PM2 log: App [panel:2] exited with code [0] via signal [SIGINT]
PM2        | 2023-06-12T17:46:53: PM2 log: pid=119 msg=process killed
PM2        | 2023-06-12T17:46:53: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-06-12T17:46:54: PM2 log: App [public:1] online
PM2        | 2023-06-12T17:47:03: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-06-12T17:46:53: debug:   ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-06-12T17:46:53: info:    ✌️ Sentry loaded
1|public   | 2023-06-12T17:46:54: info:    ✌️ DB loaded
1|public   | 2023-06-12T17:46:54: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-06-12T17:46:54: info:    ✌️ DB loaded
2|panel    | 2023-06-12T17:46:54: info:    ✌️ Init file down
2|panel    | 2023-06-12T17:46:55: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-06-12T17:46:55: Error: Cannot find module 'http-proxy-middleware'
2|panel    | 2023-06-12T17:46:55: Require stack:
2|panel    | 2023-06-12T17:46:55: - /ql/static/build/loaders/express.js
2|panel    | 2023-06-12T17:46:55: - /ql/static/build/loaders/app.js
2|panel    | 2023-06-12T17:46:55: - /ql/static/build/app.js
2|panel    | 2023-06-12T17:46:55:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2|panel    | 2023-06-12T17:46:55:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2|panel    | 2023-06-12T17:46:55:     at require (node:internal/modules/cjs/helpers:102:18)
2|panel    | 2023-06-12T17:46:55:     at Object.<anonymous> (/ql/back/loaders/express.ts:18:1)
2|panel    | 2023-06-12T17:46:55:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
2|panel    | 2023-06-12T17:46:55:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2|panel    | 2023-06-12T17:46:55:     at Module.load (node:internal/modules/cjs/loader:981:32)
2|panel    | 2023-06-12T17:46:55:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2|panel    | 2023-06-12T17:46:55:     at Module.require (node:internal/modules/cjs/loader:1005:19)
2|panel    | 2023-06-12T17:46:55:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)

### What is expected?

怎么修复

### What is actually happening?

无法浏览器打开

**Comment by whyour** [comment]
确保你docker映射了数据，使用宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
