### ISSUE TITLE
【京东极速版】不知道是脚本原因还是容器

### ISSUE THREAD

**Issue by kkfive** [whyour/qinglong#198]
![image](https://user-images.githubusercontent.com/82026204/119776462-8c00e300-bef7-11eb-8f14-88aa42908198.png)

如图 账号还没有执行完就结束了。 想问是容器原因还是脚本原因。 

目前我想到的解决方案就是定时多执行几次   各路大神有啥别的高招没

**Comment by shiyanzhizhuo** [comment]
可以改成并发
