### ISSUE TITLE
定时任务视图面板，显示bug

### ISSUE THREAD

**Issue by gbabybus** [whyour/qinglong#1980]
### Qinglong version

v2.15.14

### Steps to reproduce

docker安装
打开网址：5700

### What is expected?

修复这个过滤显示bug

### What is actually happening?

当新建了几个视图，并且关闭全部任务视图

默认的第一个视图首次刷新会显示所有的任务，相当于没有过滤，点击另一个视图，再点击回来才过滤显示

![cf20fd43e69d100d42238c285072b62b01aed5ee](https://github.com/whyour/qinglong/assets/64813827/7233409c-0a6c-4a65-932d-25fe282cc48c)

![c8ef9dc3fe7244b509270712603c0b43b3ccad91](https://github.com/whyour/qinglong/assets/64813827/671f5306-63a9-4b53-b0d0-fd0e9a3cf43e)

### Any additional comments?

麻烦了，谢谢

**Comment by whyour** [comment]
2.15.16 已修复
