### ISSUE TITLE
v2.15.15升级v2.15.16bug

### ISSUE THREAD

**Issue by niyueyeee** [whyour/qinglong#1983]
### Qinglong version

v2.15.15

### Steps to reproduce

v2.15.15升级到v2.15.16  后报错
![image](https://github.com/whyour/qinglong/assets/35424140/ec47c0b5-81a9-4af7-abd7-3657e75bafa5)

### What is expected?

正常升级

### What is actually happening?

升级失败 并且服务器docker不能使用了  重装docker会丢失之前镜像吗
![image](https://github.com/whyour/qinglong/assets/35424140/00dce26c-404f-4bfc-9b53-9b97238d2e66)

**Comment by wlyc1** [comment]
出现同样的问题，有解决方法吗？

**Comment by whyour** [comment]
宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>

**Comment by niyueyeee** [comment]
进错服务器了  所以docker命令没有了
修复方法 按提示处理就好
