### ISSUE TITLE
只能同时运行两个脚本，其余全在排队

### ISSUE THREAD

**Issue by jzksnsjswkw** [whyour/qinglong#1984]
### Qinglong version

v2.15.16

### Steps to reproduce

只能同时跑两个，其余全在排队，config里的MaxConcurrentNum属性根本没读

### What is expected?

根据MaxConcurrentNum限制同时运行任务数

### What is actually happening?

只能同时跑两个

### System Info

```shell
docker v2.15.16 alpine镜像
```

**Comment by jzksnsjswkw** [comment]
确实，两核CPU。现在只能直接进终端用task命令跑。应该根据config里的MaxConcurrentNum属性来的，不知道为什么直接写死为CPU核心数

**Comment by Peterpig** [comment]
我用的debian的镜像。。也遇到了同样的问题。
关键在docker hub找不到老版本的debian的了。。好难受

**Comment by jzksnsjswkw** [comment]
该源码，直接写死999

**Comment by jzksnsjswkw** [comment]
改源码，写死999

**Comment by jzksnsjswkw** [comment]
,

**Comment by Peterpig** [comment]
临时解决方案：


### 安装vim
```
apt install -y vim
vim /ql/static/build/shared/pLimit.js
```

### 编辑为如下

![image](https://github.com/whyour/qinglong/assets/7956973/c45385ff-50d3-422f-840d-525787c899c0)


### pm2重启服务
```
cd /ql
unset http_proxy
unset https_proxy
unset ftp_proxy
unset all_proxy
unset no_proxy
pm2 flush
pm2 startOrGracefulReload  /ql/ecosystem.config.js
```

### 稍等片刻。执行 `pm l` 出现如下内容试一下应该就可以了

![image](https://github.com/whyour/qinglong/assets/7956973/575640b9-b776-4bd4-9e5c-ea526312fa25)

**Comment by daming6666** [comment]
擦，早看到你这个我就不用自己研究那么久了，鸿蒙系统 os.cpus()取不到 cpu 核心数

**Comment by ghostor1d** [comment]
> pLimit



> 等作者修复吧。
> 
> 我自己随便改了一下，10个并发，步骤如下：
> 
> ### 安装vim
> ```
> apt install -y vim
> vim /ql/static/build/shared/pLimit.js
> ```
> 
> ### 编辑为如下
> ![image](https://user-images.githubusercontent.com/7956973/247457399-c45385ff-50d3-422f-840d-525787c899c0.png)
> 
> ### pm2重启服务
> ```
> cd /ql
> unset http_proxy
> unset https_proxy
> unset ftp_proxy
> unset all_proxy
> unset no_proxy
> pm2 flush
> pm2 startOrGracefulReload  /ql/ecosystem.config.js
> ```
> 
> ### 稍等片刻。执行 `pm2 l` 出现如下内容试一下应该就可以了
> ![image](https://user-images.githubusercontent.com/7956973/247458520-575640b9-b776-4bd4-9e5c-ea526312fa25.png)

你好，我完全不懂前端的技术，我知道在工程项目里有plimit.ts这个文件，函数我也查到了。
但是我在docker的容器里面没有看看到这个文件，请问你是在容器里部署的吗，还是说用的其他方法。

**Comment by Peterpig** [comment]
作者已经修复了。可以在界面设置

**Comment by guominfang** [comment]
@Peterpig 我使用的 2.16.3，界面上怎么设置

**Comment by bylengfeng** [comment]
> [@Peterpig](https://github.com/Peterpig) 我使用的 2.16.3，界面上怎么设置

现在可以了，面板没有出现的话，通过api: http://localhost:5600/open/system/config/cron-concurrency
请求后会显示的
