### ISSUE TITLE
并发任务，变量分割bug

### ISSUE THREAD

**Issue by xbabybus** [whyour/qinglong#1987]
### Qinglong version

v2.15.16

### Steps to reproduce

docker安装
打开网址：5700

### What is expected?

修复这个变量值分割bug

### What is actually happening?

变量值里有空格，会把空格当成分隔符，结果导致变量值分割不对，也就是单个值被分割成多个值
假如这个是我从alook浏览器里复制出来的cookie

_lxsdk_cuid=188804e446ac8-0e12502f161f63-5c417507-38400-188804e446bc8; _lxsdk=188804e446ac8-0e12502f161f63-5c417507-38400-188804e446bc8; 
![image](https://github.com/whyour/qinglong/assets/64813827/a6cf912c-caff-4e1a-aef9-81511c9891fb)

我的脚本是这么写的
![image](https://github.com/whyour/qinglong/assets/64813827/021ae4ee-7bf5-4b03-904b-777df0c7d04a)

任务命令
![image](https://github.com/whyour/qinglong/assets/64813827/759bcf6c-633d-4d8d-9717-99861f47453b)

我直接执行，我的面板这个变量只有一个，但是它执行了2次
![image](https://github.com/whyour/qinglong/assets/64813827/9ee03936-e753-4b17-849a-b294fc25c139)

我把变量值的空格去掉，就可以按照预期的样子，只执行1次
![image](https://github.com/whyour/qinglong/assets/64813827/2e25e7a6-0c3e-4565-88c8-d13af23c2dc0)

### Any additional comments?

麻烦了，谢谢

**Comment by whyour** [comment]
2.16.2 已修复
