### ISSUE TITLE
面板无法访问呀

### ISSUE THREAD

**Issue by BIGBbox** [whyour/qinglong#199]
![image](https://user-images.githubusercontent.com/52786394/119832887-30ebe200-bf31-11eb-9535-e340cabba201.png)

啥意思呀，

**Comment by BIGBbox** [comment]
> ![image](https://user-images.githubusercontent.com/52786394/119832887-30ebe200-bf31-11eb-9535-e340cabba201.png)
> 
> 啥意思呀，

![image](https://user-images.githubusercontent.com/52786394/119835334-55e15480-bf33-11eb-9852-cd9e23be0e05.png)

**Comment by whyour** [comment]
还是https ?

**Comment by BIGBbox** [comment]
> 还是https ?

http也不行呀，我不知道哪步出了问题

**Comment by BIGBbox** [comment]
> > 还是https ?
> 
> http也不行呀，我不知道哪步出了问题

1. 拉取镜像/更新镜像

docker pull whyour/qinglong:latest

2. 删除镜像

docker rmi whyour/qinglong:latest

3. 启动容器 

普通服务器

docker run -dit \
   -v $PWD/ql/config:/ql/config \
   -v $PWD/ql/log:/ql/log \
   -v $PWD/ql/db:/ql/db \
   -p 5700:5700 \
   --name qinglong \
   --hostname qinglong \
   --restart always \
   whyour/qinglong:latest

4. 删除容器

docker rm -f qinglong

5. 初次登陆

初次访问 http://<自己ip>:5700


就这样的

**Comment by whyour** [comment]
localhost:5700不行吗

**Comment by BIGBbox** [comment]
> localhost:5700不行吗

我用的是vps、http://vps外部IP：5700

**Comment by whyour** [comment]
服务器上 curl http://127.0.0.1:5700 看看

**Comment by BIGBbox** [comment]
> 服务器上 curl http://127.0.0.1:5700 看看

connect refused 😨😨

**Comment by whyour** [comment]
@BIGBbox 那你就没部署成功

**Comment by BIGBbox** [comment]
> @BIGBbox 那你就没部署成功

我用的CenOs7部署的，怎么没成功呀😨😨

**Comment by whyour** [comment]
@BIGBbox 你服务器上都访问不了5700，怎么算成功

**Comment by BIGBbox** [comment]
> @BIGBbox 你服务器上都访问不了5700，怎么算成功

我刚刚重新创建一个实例，重新操作了，还是不行😨😨

[root@tingling ~]# docker pull whyour/qinglong:latest
latest: Pulling from whyour/qinglong
ddad3d7c1e96: Pull complete 
f845e0f7d73a: Pull complete 
47d471c4d820: Pull complete 
1a88008f9c83: Pull complete 
0d0b7bb7d3b0: Pull complete 
e25842647ddc: Pull complete 
Digest: sha256:4025513275509a01947acbac578d586cc5a43bc095807bc0ec4c38c0eb3245af
Status: Downloaded newer image for whyour/qinglong:latest
docker.io/whyour/qinglong:latest
[root@tingling ~]# docker rmi whyour/qinglong:latest
Untagged: whyour/qinglong:latest
Untagged: whyour/qinglong@sha256:4025513275509a01947acbac578d586cc5a43bc095807bc0ec4c38c0eb3245af
Deleted: sha256:ed9390d021dd6880cbc6903107d9f5d06713e7d872d37feeb71a6775b69b264c
Deleted: sha256:5b1bca4ae81dc5348e5d335c89b89f5d6e57aa0c272283b4c6cdd355f59866bd
Deleted: sha256:2daa56e015f7045ef6d6c7d4e71afc036619d6c548ab27bf4bd55d064a60038f
Deleted: sha256:8ada116b3678d09754ea6bcac9d82ec5a57032a0a3a49a0c2dea924bb1c6c0dc
Deleted: sha256:4665c1f223e4369f77db0e4cac541edd5d92fd473de261783a13a1d852e692a9
Deleted: sha256:8387c0a655934d3480d01f4dc7ad9cee42f9c02d25ada4611253891f3e2ef985
Deleted: sha256:9a5d14f9f5503e55088666beef7e85a8d9625d4fa7418e2fe269e9c54bcb853c
[root@tingling ~]# docker run -dit \
> -v $PWD/ql/config:/ql/config \
> -v $PWD/ql/log:/ql/log \
> -v $PWD/ql/db:/ql/db \
> -p 5700:5700 \
> --name qinglong \
> --hostname qinglong \
> --restart always \
> whyour/qinglong:latest
Unable to find image 'whyour/qinglong:latest' locally
latest: Pulling from whyour/qinglong
ddad3d7c1e96: Pull complete 
f845e0f7d73a: Pull complete 
47d471c4d820: Pull complete 
1a88008f9c83: Pull complete 
0d0b7bb7d3b0: Pull complete 
e25842647ddc: Pull complete 
Digest: sha256:4025513275509a01947acbac578d586cc5a43bc095807bc0ec4c38c0eb3245af
Status: Downloaded newer image for whyour/qinglong:latest
d25c8e2f980efe1f34d2512106cd603dbf9045900c57001435e386fae3a067bf
[root@tingling ~]# docker rm -f qinglong
[root@tingling ~]# curl 127.0.0.1:5700
curl: (7) Failed connect to 127.0.0.1:5700; Connection refused
[root@tingling ~]# curl http://127.0.0.1:5700
curl: (7) Failed connect to 127.0.0.1:5700; Connection refused
[root@tingling ~]# curl http://127.0.0.1:5700
curl: (7) Failed connect to 127.0.0.1:5700; Connection refused

**Comment by whyour** [comment]
@BIGBbox 你也太实在了，不是一二三四都要执行啊，直接启动容器

**Comment by whyour** [comment]
@BIGBbox 学习下docker

**Comment by whyour** [comment]
@BIGBbox 你都把容器杀了，访问啥啊。执行 docker run

**Comment by BIGBbox** [comment]
> @BIGBbox 你都把容器杀了，访问啥啊。执行 docker run

执行过了，用的谷歌云。。

docker run id
然后更新全部都是timeout


--------------------------------------------------------------
开始更新仓库：/ql
Fetching origin
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': Failed to connect to ghproxy
.com port 443: Operation timed out
error: Could not fetch origin
HEAD is now at 4b65cac 修改通知默认提示信息
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': Failed to connect to ghproxy
.com port 443: Operation timed out
更新/ql失败，请检查原因...
开始克隆仓库 https://ghproxy.com/https://github.com/whyour/qinglong-static.git 到 /ql/repo/static
Cloning into '/ql/repo/static'...
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong-static.git/': Failed to connect to 
ghproxy.com port 443: Operation timed out
更新/ql失败，请检查原因...
======================3. 启动nginx========================
nginx启动成功...
======================4. 启动控制面板========================

[PM2][WARN] panel doesn't exist
Use --update-env to update environment variables
[PM2][ERROR] Process or Namespace panel not found

**Comment by whyour** [comment]
@BIGBbox 远程看看  todesk

**Comment by BIGBbox** [comment]
> @BIGBbox 远程看看  todesk

ID：850 099 611 密码：552656

**Comment by whyour** [comment]
@BIGBbox todesk 权限没给够，操作不了

**Comment by BIGBbox** [comment]
> @BIGBbox todesk 权限没给够，操作不了

能看见桌面吗

**Comment by BIGBbox** [comment]
> @BIGBbox todesk 权限没给够，操作不了

十分感谢，实在是受宠若惊
