### ISSUE TITLE
退出登录再重新登录，无法识别到登录地点和IP

### ISSUE THREAD

**Issue by keai-1989** [whyour/qinglong#1990]
### Qinglong version

2.10.13   2.15.3

### Steps to reproduce

？退出登录再重新登进去，有卡顿，转半天才登录进去，登录地点和登录ip全部识别不到
![QQ截图20230624151054](https://github.com/whyour/qinglong/assets/89326912/d57cc999-88e4-48b4-9d7e-974b0f8a909f)
![QQ截图20230624151101](https://github.com/whyour/qinglong/assets/89326912/4ad92418-0d9a-478e-add6-696fc706f80f)

### What is expected?

无

### What is actually happening?

无

**Comment by whyour** [comment]
使用最新版试试
