### ISSUE TITLE
docker下，pip 会因为处于 root 而造成其它依赖无法更新？

### ISSUE THREAD

**Issue by laincat** [whyour/qinglong#1993]
### Qinglong version

2.15.16

### Steps to reproduce

依赖无法正常安装或更新。

### What is expected?

所有相关依赖都会因为：

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

### What is actually happening?

只能通过 命令 pip install --upgrade pip --root-user-action=ignore ，继续。

**Comment by whyour** [comment]
这是个警告，没影响
