### ISSUE TITLE
更新后无法启动青龙面板

### ISSUE THREAD

**Issue by powskey** [whyour/qinglong#1994]
### Qinglong version

2.15.15

### Steps to reproduce

[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-06-25T12:59:37: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:37: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:37: PM2 log: App [panel:2] online
PM2        | 2023-06-25T12:59:37: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:37: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:38: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:38: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:38: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:38: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:38: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:38: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:39: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:39: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:39: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:39: PM2 error: Cancelling versioning data parsing

/root/.pm2/logs/schedule-out.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-06-25T12:56:34: info:    ✌️ Sentry loaded
1|public   | 2023-06-25T12:56:35: info:    ✌️ DB loaded
1|public   | 2023-06-25T12:56:35: debug:   ✌️ 公共服务启动成功！
1|public   | 2023-06-25T12:59:27: info:    ✌️ Sentry loaded
1|public   | 2023-06-25T12:59:27: info:    ✌️ DB loaded
1|public   | 2023-06-25T12:59:27: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-06-25T12:56:36: info:    ✌️ DB loaded
2|panel    | 2023-06-25T12:56:36: info:    ✌️ Init file down
2|panel    | 2023-06-25T12:56:36: info:    ✌️ Sentry loaded
2|panel    | 2023-06-25T12:59:28: info:    ✌️ DB loaded
2|panel    | 2023-06-25T12:59:28: info:    ✌️ Init file down
2|panel    | 2023-06-25T12:59:28: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-06-25T12:59:29: - /ql/static/build/api/user.js
2|panel    | 2023-06-25T12:59:29: - /ql/static/build/api/index.js
2|panel    | 2023-06-25T12:59:29: - /ql/static/build/loaders/express.js
2|panel    | 2023-06-25T12:59:29: - /ql/static/build/loaders/app.js
2|panel    | 2023-06-25T12:59:29: - /ql/static/build/app.js
2|panel    | 2023-06-25T12:59:29:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2|panel    | 2023-06-25T12:59:29:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-06-25T12:59:29:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-06-25T12:59:29:     at Object.<anonymous> (/ql/back/shared/pLimit.ts:1:1)
2|panel    | 2023-06-25T12:59:29:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2|panel    | 2023-06-25T12:59:29:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2|panel    | 2023-06-25T12:59:29:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2|panel    | 2023-06-25T12:59:29:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2|panel    | 2023-06-25T12:59:29:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2|panel    | 2023-06-25T12:59:29:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

/root/.pm2/logs/schedule-error.log last 15 lines:
0|schedule | 2023-06-25T12:59:29:     at require (node:internal/modules/cjs/helpers:110:18)
0|schedule | 2023-06-25T12:59:29:     at Object.<anonymous> (/ql/back/shared/runCron.ts:1:1)
0|schedule | 2023-06-25T12:59:29:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
0|schedule | 2023-06-25T12:59:29:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
0|schedule | 2023-06-25T12:59:29:     at Module.load (node:internal/modules/cjs/loader:1117:32)
0|schedule | 2023-06-25T12:59:29:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
0|schedule | 2023-06-25T12:59:29:     at Module.require (node:internal/modules/cjs/loader:1141:19)
0|schedule | 2023-06-25T12:59:29:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
0|schedule | 2023-06-25T12:59:29:   code: 'MODULE_NOT_FOUND',
0|schedule | 2023-06-25T12:59:29:   requireStack: [
0|schedule | 2023-06-25T12:59:29:     '/ql/static/build/shared/runCron.js',
0|schedule | 2023-06-25T12:59:29:     '/ql/static/build/schedule/addCron.js',
0|schedule | 2023-06-25T12:59:29:     '/ql/static/build/schedule/index.js'
0|schedule | 2023-06-25T12:59:29:   ]
0|schedule | 2023-06-25T12:59:29: }

### What is expected?

.

### What is actually happening?

[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-06-25T12:59:37: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:37: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:37: PM2 log: App [panel:2] online
PM2        | 2023-06-25T12:59:37: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:37: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:38: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:38: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:38: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:38: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:38: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:38: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:39: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:39: PM2 error: Cancelling versioning data parsing
PM2        | 2023-06-25T12:59:39: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T12:59:39: PM2 error: Cancelling versioning data parsing

/root/.pm2/logs/schedule-out.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-06-25T12:56:34: info:    ✌️ Sentry loaded
1|public   | 2023-06-25T12:56:35: info:    ✌️ DB loaded
1|public   | 2023-06-25T12:56:35: debug:   ✌️ 公共服务启动成功！
1|public   | 2023-06-25T12:59:27: info:    ✌️ Sentry loaded
1|public   | 2023-06-25T12:59:27: info:    ✌️ DB loaded
1|public   | 2023-06-25T12:59:27: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-06-25T12:56:36: info:    ✌️ DB loaded
2|panel    | 2023-06-25T12:56:36: info:    ✌️ Init file down
2|panel    | 2023-06-25T12:56:36: info:    ✌️ Sentry loaded
2|panel    | 2023-06-25T12:59:28: info:    ✌️ DB loaded
2|panel    | 2023-06-25T12:59:28: info:    ✌️ Init file down
2|panel    | 2023-06-25T12:59:28: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-06-25T12:59:29: - /ql/static/build/api/user.js
2|panel    | 2023-06-25T12:59:29: - /ql/static/build/api/index.js
2|panel    | 2023-06-25T12:59:29: - /ql/static/build/loaders/express.js
2|panel    | 2023-06-25T12:59:29: - /ql/static/build/loaders/app.js
2|panel    | 2023-06-25T12:59:29: - /ql/static/build/app.js
2|panel    | 2023-06-25T12:59:29:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2|panel    | 2023-06-25T12:59:29:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-06-25T12:59:29:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-06-25T12:59:29:     at Object.<anonymous> (/ql/back/shared/pLimit.ts:1:1)
2|panel    | 2023-06-25T12:59:29:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2|panel    | 2023-06-25T12:59:29:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2|panel    | 2023-06-25T12:59:29:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2|panel    | 2023-06-25T12:59:29:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2|panel    | 2023-06-25T12:59:29:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2|panel    | 2023-06-25T12:59:29:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

/root/.pm2/logs/schedule-error.log last 15 lines:
0|schedule | 2023-06-25T12:59:29:     at require (node:internal/modules/cjs/helpers:110:18)
0|schedule | 2023-06-25T12:59:29:     at Object.<anonymous> (/ql/back/shared/runCron.ts:1:1)
0|schedule | 2023-06-25T12:59:29:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
0|schedule | 2023-06-25T12:59:29:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
0|schedule | 2023-06-25T12:59:29:     at Module.load (node:internal/modules/cjs/loader:1117:32)
0|schedule | 2023-06-25T12:59:29:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
0|schedule | 2023-06-25T12:59:29:     at Module.require (node:internal/modules/cjs/loader:1141:19)
0|schedule | 2023-06-25T12:59:29:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
0|schedule | 2023-06-25T12:59:29:   code: 'MODULE_NOT_FOUND',
0|schedule | 2023-06-25T12:59:29:   requireStack: [
0|schedule | 2023-06-25T12:59:29:     '/ql/static/build/shared/runCron.js',
0|schedule | 2023-06-25T12:59:29:     '/ql/static/build/schedule/addCron.js',
0|schedule | 2023-06-25T12:59:29:     '/ql/static/build/schedule/index.js'
0|schedule | 2023-06-25T12:59:29:   ]
0|schedule | 2023-06-25T12:59:29: }

**Comment by Nicolas-Gong** [comment]
每次更新都导致无法启动，只能删了docker镜像重来，关键是还得升级，不升级又无法导入env，升级后还是无法启动，还得找办法升级到上一个版本，不然环境变量还得一个一个手动建，docker镜像一直不更新，真的太坑爹了，每次升级都得折腾很久，这次折腾好以后再也不升级了

**Comment by MaydayV** [comment]
我也遇到这个问题
[PM2][WARN] Applications schedule, public, panel not running, starting...
[PM2][WARN] App schedule has option 'wait_ready' set, waiting for app to be ready...
[PM2][WARN] App public has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [public] launched (1 instances)
[PM2][WARN] App panel has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [schedule] launched (1 instances)
[PM2] App [panel] launched (1 instances)
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 148      │ 3s     │ 0    │ online    │ 0%       │ 116.9mb  │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 93       │ 5s     │ 0    │ online    │ 0%       │ 99.8mb   │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 225      │ 0      │ 9    │ launching │ 0%       │ 0b       │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
====================6. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...
############################################################

crond[235]: crond (busybox 1.35.0) started, log level 8
crond[235]: user root: parse error at 7
crond[235]: user root: parse error at 7

**Comment by testnet0** [comment]
same error

**Comment by 2478641181** [comment]
crond[162]: crond (busybox 1.36.1) started, log level 8
不执行定时

**Comment by MaydayV** [comment]
<img width="997" alt="image" src="https://github.com/whyour/qinglong/assets/61279703/9c3276eb-0e63-4eda-ae4d-eba19e486501">
继续等待解决

**Comment by testnet0** [comment]
删除了容器重装一遍就好了

**Comment by testnet0** [comment]
> > 删除了容器重装一遍就好了
> 
> 可是那些环境变量和配置啥的咋保存呢

我是启动的时候挂载了/ql/data目录，如果没有挂载可以docker cp 复制这个文件夹出来
