### ISSUE TITLE
部分设备不支持 os.cpus()方法

### ISSUE THREAD

**Issue by daming6666** [whyour/qinglong#1995]
### Qinglong version

 2.15.16

### Steps to reproduce

麒麟990芯片，鸿蒙 3.0 系统，termux-alpine 本地装青龙，npm 直接部署的，p_limit.js/p_limit.ts内使用 os.cpus()获取核心数失败，导致runwithcpulimit()返回的是默认值 0，p_limit报错,建议改为默认值  4，让不能识别核心数的设备默认采取 4 核心。
另外 npm 本地部署拉取依赖成功率太低了（国内网络原因），能否做一个 gz 包解压安装。

### What is expected?

p_limit识别不到 cpu 数量时不会报错而是用默认值代替(建议默认值  4，大部分设备都是 4 核心以上)

### What is actually happening?

p_limit获取的返回值为 0，直接报错

**Comment by inoyna12** [comment]
可以教一下怎么使用npm部署吗？
我是用termux-alpine安装node/npm/python3/pip3这4个后，然后运行npm install -g @whyour/qinglong这个命令，等待一会就报错了，哪里出错了吗

**Comment by daming6666** [comment]
网络问题吧，不太容易，不建议本地部署，报错要自己排错呀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 上午7:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whyour/qinglong] 部分设备不支持 os.cpus()方法 (Issue #1995)




 
可以教一下怎么使用npm部署吗？
 我是用termux-alpine安装node/npm/python3/pip3这4个后，然后运行npm install -g @whyour/qinglong这个命令，等待一会就报错了，哪里出错了吗

**Comment by whyour** [comment]
2.15.17 已修复
