### ISSUE TITLE
无法下载依赖环境，没法玩，很沮丧！

### ISSUE THREAD

**Issue by pkids** [whyour/qinglong#1997]
尊敬的开发者您好，我在群晖安装了青龙 正式版 v2.15.16，依赖管理里我手动添加axios，但是尝试了很多次都失败，在docker的命令行里输入npm install axios，进度条也是0%，麻烦您帮忙看看是怎么回事，有没有什么办法让我们“网络不好的”用户手动导入依赖环境。
（在您提供的demo里我试了下，输入axios能加载成功。）

![image](https://github.com/whyour/qinglong/assets/86213318/a318d8e9-a6ae-4370-9e98-8794133776e8)

![image](https://github.com/whyour/qinglong/assets/86213318/204fb067-63fa-48c1-9bee-df651934e218)

![image](https://github.com/whyour/qinglong/assets/86213318/5701d7a4-504c-45c9-8e9d-dc09b1bce756)

![image](https://github.com/whyour/qinglong/assets/86213318/4ada96a4-f178-4534-bf19-98939323ee52)

**Comment by yoder** [comment]
切换到国内npm源呢

**Comment by pkids** [comment]
> 切换到国内npm源呢

请问怎么切换到国内源啊？是不是先在docker的终端机里输入：npm config set registry https://registry.npmmirror.com

**Comment by pkids** [comment]
![image](https://github.com/whyour/qinglong/assets/86213318/04f1dd96-6300-45bc-ba70-da9ae16090e8)

**Comment by whyour** [comment]
> ![image](https://user-images.githubusercontent.com/86213318/250700987-04f1dd96-6300-45bc-ba70-da9ae16090e8.png)

你这是网络问题吧，你容器内能访问 baidu.com 吗，或者镜像源改为 https://registry.npmjs.org

**Comment by pkids** [comment]
在nas的ssh里能ping到 ， 在容器的终端机里不能ping到
![image](https://github.com/whyour/qinglong/assets/86213318/a2001a2d-52a8-461a-9b79-9adde5dc3eb1)
![image](https://github.com/whyour/qinglong/assets/86213318/d171dcfc-d113-4ccc-9774-7a09351feab4)

**Comment by whyour** [comment]
> 在nas的ssh里能ping到 ， 在容器的终端机里不能ping到 ![image](https://user-images.githubusercontent.com/86213318/250887360-a2001a2d-52a8-461a-9b79-9adde5dc3eb1.png) ![image](https://user-images.githubusercontent.com/86213318/250887482-d171dcfc-d113-4ccc-9774-7a09351feab4.png)

那就是你容器连不上网，是不是群晖的容器要设置 host 模式

**Comment by pkids** [comment]
![image](https://github.com/whyour/qinglong/assets/86213318/3dea8e15-7ca4-4d22-8bd2-040d23023cb4)
![image](https://github.com/whyour/qinglong/assets/86213318/54f55d11-a8f6-433a-adfb-c8ab7b57f01f)
谢谢up主的解答，谢谢同样使用青龙面板前辈的解答，我重新创建了个docker容器，网络选择了上图那个同dockerhost相同，能下载依赖文件了，耶，好开心，准备大干一场，先把阿里云盘签到搞定~~
