### ISSUE TITLE
定时规则问题

### ISSUE THREAD

**Issue by p369349074** [whyour/qinglong#1998]
### Qinglong version

2.15.16

### Steps to reproduce

![image](https://github.com/whyour/qinglong/assets/65352820/c2685037-c651-4869-8a88-9f53c65c187c)

### What is expected?

not sure

### What is actually happening?

![image](https://github.com/whyour/qinglong/assets/65352820/ef5ead3a-05ac-4d50-b81d-7e0b7b64a7a2)
每天6到23小时23分钟运行，但是却隔了两天没有运行，定时有问题呀，

### System Info

```shell
linux docker
```

**Comment by whyour** [comment]
看看日志文件有没有，有可能是没更新上最后运行时间

**Comment by MGxjm** [comment]
> 

存在你说的问题，有新日志但是统计的时间错误，也有另一个问题，我重新本地clone的qinglong跟qinglong-static，清空了所有文件夹纯净启动的用ql -l check命令，看起来日志一切正常但是定时任务不触发
