### ISSUE TITLE
执行定时任务超出下一次定时任务开始执行时间

### ISSUE THREAD

**Issue by Chaomingri** [whyour/qinglong#1999]
### Qinglong version

正式版 v2.15.17

### Steps to reproduce

定义一个定时任务；
运行时间超出下一次定时任务开始时间；

### What is expected?

任务超出下一次任务开始执行时间，结束当前任务再开始执行下一次任务

### What is actually happening?

下一次定时任务无法被前台监控管理；

**Comment by whyour** [comment]
结束当前任务也不太合理，两次任务都可以监控到，任务的运行日志是可以看到的

**Comment by ErixWong** [comment]
参考 #2139 
我写了个daemon.js，可以曲线实现这个功能。
