### ISSUE TITLE
大佬，群组解散了么 还是怎么？还有怎么升级1.1.0版本的界面

### ISSUE THREAD

**Issue by felix-cl** [whyour/qinglong#20]
放个假回去想升级到1.1.0的界面  把镜删除像和删除容器的代码运行了一遍  又把文件夹删除了  然后重新拉取  界面没有改变  反而配置文件，对比工具那里都空白了…… 想进群咨询发现找不到了 前两天还在

**Comment by whyour** [comment]
> 放个假回去想升级到1.1.0的界面 把镜删除像和删除容器的代码运行了一遍 又把文件夹删除了 然后重新拉取 界面没有改变 反而配置文件，对比工具那里都空白了…… 想进群咨询发现找不到了 前两天还在

现在最新的是1.2.0了，你看你镜像是不是cdn，现在latest是最新的

**Comment by felix-cl** [comment]
你好  那我现在再重新运行删除镜像和容器的代码  重新运行pull:latest拉取镜像就是最新1.2么  那个ql文件夹要不要删除掉再拉取镜像

**Comment by felix-cl** [comment]
> > 放个假回去想升级到1.1.0的界面 把镜删除像和删除容器的代码运行了一遍 又把文件夹删除了 然后重新拉取 界面没有改变 反而配置文件，对比工具那里都空白了…… 想进群咨询发现找不到了 前两天还在
> 
> 
> 
> 现在最新的是1.2.0了，你看你镜像是不是cdn，现在latest是最新的

你好 那我现在再重新运行删除镜像和容器的代码 重新运行pull:latest拉取镜像就是最新1.2么 那个ql文件夹要不要删除掉再拉取镜像   第一次玩这个 不太懂

**Comment by whyour** [comment]
> > > 放个假回去想升级到1.1.0的界面 把镜删除像和删除容器的代码运行了一遍 又把文件夹删除了 然后重新拉取 界面没有改变 反而配置文件，对比工具那里都空白了…… 想进群咨询发现找不到了 前两天还在
> > 
> > 
> > 现在最新的是1.2.0了，你看你镜像是不是cdn，现在latest是最新的
> 
> 你好 那我现在再重新运行删除镜像和容器的代码 重新运行pull:latest拉取镜像就是最新1.2么 那个ql文件夹要不要删除掉再拉取镜像 第一次玩这个 不太懂

latest 就是最新的，本地映射目录不需要删除

**Comment by felix-cl** [comment]
> > > > 放个假回去想升级到1.1.0的界面 把镜删除像和删除容器的代码运行了一遍 又把文件夹删除了 然后重新拉取 界面没有改变 反而配置文件，对比工具那里都空白了…… 想进群咨询发现找不到了 前两天还在
> 
> > > 
> 
> > > 
> 
> > > 现在最新的是1.2.0了，你看你镜像是不是cdn，现在latest是最新的
> 
> > 
> 
> > 你好 那我现在再重新运行删除镜像和容器的代码 重新运行pull:latest拉取镜像就是最新1.2么 那个ql文件夹要不要删除掉再拉取镜像 第一次玩这个 不太懂
> 
> 
> 
> latest 就是最新的，本地映射目录不需要删除

好的  谢谢 等下试试  话说群组还会开通么  不懂的方便在群里请教

**Comment by whyour** [comment]
> > > > > 放个假回去想升级到1.1.0的界面 把镜删除像和删除容器的代码运行了一遍 又把文件夹删除了 然后重新拉取 界面没有改变 反而配置文件，对比工具那里都空白了…… 想进群咨询发现找不到了 前两天还在
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 现在最新的是1.2.0了，你看你镜像是不是cdn，现在latest是最新的
> > 
> > 
> > > 
> > 
> > 
> > > 你好 那我现在再重新运行删除镜像和容器的代码 重新运行pull:latest拉取镜像就是最新1.2么 那个ql文件夹要不要删除掉再拉取镜像 第一次玩这个 不太懂
> > 
> > 
> > latest 就是最新的，本地映射目录不需要删除
> 
> 好的 谢谢 等下试试 话说群组还会开通么 不懂的方便在群里请教

目前不会了
