### ISSUE TITLE
qinglong反代怎么设置

### ISSUE THREAD

**Issue by chenhb0618** [whyour/qinglong#200]
添加了代码打印显示调用ipa失败。求教

**Comment by whyour** [comment]
设置什么的反代

**Comment by gethin52** [comment]
server {
    listen       80;
    server_name xxx.com;    #域名
    location / {
       proxy_pass http://127.0.0.1:5701;     #转发地址（项目容器宿主ip及端口）
      }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

**Comment by scccy** [comment]
> server {
> listen 80;
> server_name xxx.com; #域名
> location / {
> proxy_pass http://127.0.0.1:5701; #转发地址（项目容器宿主ip及端口）
> }
> error_page 500 502 503 504 /50x.html;
> location = /50x.html {
> root /usr/share/nginx/html;
> }
> }

你成功了么，我也代理失败了

**Comment by SkysCrystal** [comment]
同求 nginx 反向代理设置方法，好使用域名访问
