### ISSUE TITLE
青龙面板pushplus推送无法正常使用

### ISSUE THREAD

**Issue by jason-547** [whyour/qinglong#2000]
### Qinglong version

2.15.17

### Steps to reproduce

更新ID：5a2caeb
青龙面板pushplus无法使用，显示：通知发送失败，请检查参数
新的token无法保存

### What is expected?

修复该bug

### What is actually happening?

更新之后（7.2）

**Comment by whyour** [comment]
参考 https://www.pushplus.plus

**Comment by jason-547** [comment]
> 对应的 https://www.pushplus.plus 的 token

使用过了 但是还是没办法使用 也没办法保存token 就是只是显示通知发送失败，请检查参数

**Comment by jason-547** [comment]
我退到2.10.15也是这样子

**Comment by hutuxionggege** [comment]
青龙面板pushplus无法使用，显示：通知发送失败，请检查参数
新的token无法保存
