### ISSUE TITLE
一直在发送dns请求

### ISSUE THREAD

**Issue by yxmyxmyyy** [whyour/qinglong#2001]
### Qinglong version

2.15.17

### Steps to reproduce

后台一直在发送dns请求查询o1098464.ingest.sentry.io
，我在adguardhome上看到一秒钟要查几十遍

### What is expected?

![Screenshot_2023-07-05-14-02-25-713_com android browser-edit](https://github.com/whyour/qinglong/assets/30144367/efd631cc-fa79-4ab3-8444-de75d0c2a476)
，我访问这个网站显示404

### What is actually happening?

虽然不会有很严重的影响，但还是会给dns解析程序造成负担

**Comment by whyour** [comment]
adguard 把 sentry 屏蔽了，设成白名单就行了。sentry 是做错误上报的

**Comment by yxmyxmyyy** [comment]
可是解除了还是一直查询，我手动访问测试显示404

**Comment by mewtwo-git** [comment]
@whyour 可以把 sentry 配置为可选项吗？

**Comment by Miroxyz** [comment]
![image](https://github.com/whyour/qinglong/assets/69784329/a42ee891-f7d7-432c-997e-b9ebc5cbd6ff)
😓😓😓

**Comment by choyri** [comment]
建议要么加上开关允许关闭，要么加上相关 catch 别无脑请求……

![image](https://github.com/whyour/qinglong/assets/13994362/dc7a418c-bc58-47c9-aba5-72353b6d7ded)

**Comment by refined-fish** [comment]
开了代理这个请求还是一直走的代理，一直都没发现............都给clash日志整刷屏了

**Comment by cutbuzz** [comment]
> 开了代理这个请求还是一直走的代理，一直都没发现............都给clash日志整刷屏了

我已经给他写了个REJECT的规则了...

**Comment by choyri** [comment]
前后端都有 Sentry，不过主要是后端的 Sentry 请求太多，跳过它的初始化：

```shell
docker exec $(CONTAINER_ID) sed -i '/Sentry\.init/ s/^/return;/' /ql/static/build/loaders/sentry.js
````

**Comment by cutbuzz** [comment]
> 前后端都有 Sentry，不过主要是后端的 Sentry 请求太多，跳过它的初始化：
> 
> ```shell
> docker exec $(CONTAINER_ID) sed -i '/Sentry\.init/ s/^/return;/' /ql/static/build/loaders/sentry.js
> ```

请问这个命令是直接粘贴到终端运行吗？ 报错诶 求指教
![image](https://github.com/whyour/qinglong/assets/84438684/041577ff-bc4c-4d3a-b39a-b37006d8f28e)

**Comment by choyri** [comment]
@cutbuzz 你的 qinglong 版本太低，目录结构和现在的新版不一样，路径去掉 `/static`：

```
/ql/build/loaders/sentry.js
```

**Comment by zhaoyi4j** [comment]
可以跟Homeassistant学习一下么？把问题收集做成一个开关项，让用户进行选择。

**Comment by EVO688** [comment]
1、进入容器
docker exec -it qinglong bash
2、修改/etc/hosts
echo "127.0.0.1 o1098464.ingest.sentry.io" >> /etc/hosts
3、验证修改
cat /etc/hosts
127.0.0.1 o1098464.ingest.sentry.io
4、测试修改
curl https://o1098464.ingest.sentry.io
访问失败、即成功禁止
5、万一要修复，先进入容器，验证看第四步。
sed -i '/o1098464.ingest.sentry.io/d' /etc/hosts

PS：副作用不清楚，网上搜了半天没找到解决办法，包括楼上代码也试了仍然存在访问，用这个屏蔽方法，clash、adguardhome中都不会出现链接了请求了。

**Comment by for7GG** [comment]
> 1、进入容器 docker exec -it qinglong bash 2、修改/etc/hosts echo "127.0.0.1 o1098464.ingest.sentry.io" >> /etc/hosts 3、验证修改 cat /etc/hosts 127.0.0.1 o1098464.ingest.sentry.io 4、测试修改 curl https://o1098464.ingest.sentry.io 访问失败、即成功禁止 5、万一要修复，先进入容器，验证看第四步。 sed -i '/o1098464.ingest.sentry.io/d' /etc/hosts
> 
> PS：副作用不清楚，网上搜了半天没找到解决办法，包括楼上代码也试了仍然存在访问，用这个屏蔽方法，clash、adguardhome中都不会出现链接了请求了。

感谢，可以了，可以把它写成一个脚本，需要时点一下就行  
```
# 非交互式执行 docker exec 命令更新 /etc/hosts 文件
docker exec -i whyour_qinglong bash -c 'echo "127.0.0.1 o1098464.ingest.sentry.io" >> /etc/hosts'

# 输出提示信息
echo "Hosts 文件已更新！"
```
