### ISSUE TITLE
青龙还差点就完美了缺少了2个功能

### ISSUE THREAD

**Issue by InfernalAzazel** [whyour/qinglong#2002]
### Clear and concise description of the problem

问题: 爬取某些数据时 比如新闻 一般可能晚上更新新闻内容，所以我们是需要固定的时间抓取的，但是订阅管理定自动添加任务 的定是规则是随机的。

1. 希望可以在订阅仓库编辑 定时规则 下面在加一个可以自定义的 自动添加任务定时规则
2. 希望可以添加自动安装python 依赖，每次都要手动安装

如果有两个功能 完全可以不用管理青龙了，每次提交新代码就行了。这是非常壮观的举动。
### Suggested solution

无

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
订阅添加任务的时候，会读取脚本描述中的定时规则
```py
'''
cron: 0 10 * * *
'''
```

```js
/**
 * cron: 0 10 * * *
 */
```

依赖并不需要频繁增加，所以手动目前是 ok 的，当然欢迎 pr

**Comment by myfjdthink** [comment]
> 订阅添加任务的时候，会读取脚本描述中的定时规则
请问这个功能是在哪一处代码实现的？
想要修改这个功能

@whyour
