### ISSUE TITLE
建议 青龙把环境变量相关的数据表独立成一个单独的数据库

### ISSUE THREAD

**Issue by xbabybus** [whyour/qinglong#2003]
### Clear and concise description of the problem

有这么个使用场景：本地虚拟机运行多个青龙容器，做分组运行，这几个容器除了环境变量还有日志不一致外，其他的都是一致的。

### Suggested solution

如果能够把环境变量相关的表单独做一个数据库，只需要这么映射数据，就可以快速启动多个容器副本，
一个更改全部更改[除了日志，还有环境变量都是独立的]
![image](https://github.com/whyour/qinglong/assets/64813827/b09dae55-d4f8-4017-a465-31c8d2d4f4d1)

当然没有这么个场景，将环境变量相关的表独立成一个单独的数据库也没有什么影响，只是更灵活，多了一份选择罢了

希望能采纳，谢谢

**Comment by InfernalAzazel** [comment]
我希望这个是可以选择的，我们运行爬虫项目不是很多，几十个，在安装一个数据库很麻烦。

**Comment by ErixWong** [comment]
你可以起一个mysql，然后写个脚本，从mysql中获取对应的环境变量，用青龙API更新到当前容器。
