### ISSUE TITLE
在线更新失败

### ISSUE THREAD

**Issue by yoder** [whyour/qinglong#2004]
### Qinglong version

2.15.14

### Steps to reproduce

系统设置里面更新

### What is expected?

更新成功

### What is actually happening?

`更新中...
## 开始执行..。2823-87-86 20:25:39
使用 gitee 源更新.
开始更新仓库:/q1
fatal: couldn't find remote ref refs/heads/main
更新青龙源文件失败，请检查网络...

**Comment by whyour** [comment]
宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
