### ISSUE TITLE
打不开一直转圈

### ISSUE THREAD

**Issue by KaitouKidgmh** [whyour/qinglong#2007]
### Qinglong version

last

### Steps to reproduce

打开crontab一直转圈

### What is expected?

原来版本可以打开  不知道为什么现在打不开

### What is actually happening?

重装也不行

**Comment by whyour** [comment]
使用宿主机方式更新下，确保原来有映射目录 `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
`
