### ISSUE TITLE
遇到了个问题，不知道个例

### ISSUE THREAD

**Issue by cyxnzb** [whyour/qinglong#2008]
### Qinglong version

latest

### Steps to reproduce

根据Github提供的方式拉镜像安装，安装的版本并不是最新的版本，手动升级后Node js版本又过旧，无法按照依赖库

### What is expected?

直接安装就是最新版

### What is actually happening?

安装的版本并非最新版

**Comment by whyour** [comment]
镜像源问题，修改 docker 源为官方源，lastest 就是最新的了
