### ISSUE TITLE
青龙 不能使用本地代理(127.0.0.1:10808)？

### ISSUE THREAD

**Issue by xiezy1** [whyour/qinglong#2009]
### Qinglong version

 v2.15.11

### Steps to reproduce

青龙不能使用本地代理 至少我的不能走代理 会出现连接拒绝 我能确定我的代理是通的 我在终端是可以访问的
我是使用nodejs
const tunnel = require('tunnel')
const axios = require('axios').default;
axios.get(url, {
            headers,
            proxy: false,
            httpsAgent: tunnel.httpsOverHttp({
                proxy: {
                    host: '127.0.0.1',
                    port: '10808'
                }
            })
        }).then(res => console.log(res))

### What is expected?

青龙不能使用本地代理 至少我的不能走代理 会出现连接拒绝 我能确定我的代理是通的 我在终端是可以访问的
我是使用nodejs
const tunnel = require('tunnel')
const axios = require('axios').default;
axios.get(url, {
            headers,
            proxy: false,
            httpsAgent: tunnel.httpsOverHttp({
                proxy: {
                    host: '127.0.0.1',
                    port: '10808'
                }
            })
        }).then(res => console.log(res))

### What is actually happening?

青龙不能使用本地代理 至少我的不能走代理 会出现连接拒绝 我能确定我的代理是通的 我在终端是可以访问的
我是使用nodejs
const tunnel = require('tunnel')
const axios = require('axios').default;
axios.get(url, {
            headers,
            proxy: false,
            httpsAgent: tunnel.httpsOverHttp({
                proxy: {
                    host: '127.0.0.1',
                    port: '10808'
                }
            })
        }).then(res => console.log(res))

### System Info

```shell
x86_64
```

**Comment by 410463305** [comment]
容器网络用的是host模式还是bridge？bridge不能用127.0.0.1的，试试192.168.x.x

**Comment by whyour** [comment]
你的代理又不在青龙容器内，你要用代理的 ip 地址

**Comment by xiezy1** [comment]
> 你的代理又不在青龙容器内，你要用代理的 ip 地址

明白了 谢谢 大佬

**Comment by tangdasan** [comment]
> > 你的代理又不在青龙容器内，你要用代理的 ip 地址
> 
> 明白了 谢谢 大佬

我正好遇到这个问题了。。我还没明白，怎么弄呢

**Comment by 410463305** [comment]
> 

代理的地址用你的局域网地址，192.168.x.x

**Comment by tangdasan** [comment]
> > 
> 
> 代理的地址用你的局域网地址，192.168.x.x

搞定了，谢谢
