### ISSUE TITLE
关于新版定时任务为空白

### ISSUE THREAD

**Issue by sansuouba** [whyour/qinglong#2011]
### Qinglong version

2.15.17

### Steps to reproduce

已经拉过库了，电脑登录青龙面板的时候，定时任务为空白，什么脚本都没有，但是有运行的日志。但是手机登录的时候，定时任务不为空白。不知道是不是个例。电脑是win11版本。手机是正常的ios

### What is expected?

已经拉过库了，电脑登录青龙面板的时候，定时任务为空白，什么脚本都没有，但是有运行的日志。但是手机登录的时候，定时任务不为空白。不知道是不是个例。电脑是win11版本。手机是正常的ios

### What is actually happening?

已经拉过库了，电脑登录青龙面板的时候，定时任务为空白，什么脚本都没有，但是有运行的日志。但是手机登录的时候，定时任务不为空白。不知道是不是个例。电脑是win11版本。手机是正常的ios

**Comment by sansuouba** [comment]
<img width="995" alt="1689230639532" src="https://github.com/whyour/qinglong/assets/49261637/9dc9a000-2a9f-4918-8c2d-7aaad2d7f77e">

订阅的时候显示添加成功，但是定时任务为空白。

**Comment by whyour** [comment]
你筛选条件有问题？

**Comment by whyour** [comment]
宿主机方式更新下试试 `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
`  注意是否已映射 data 目录
