### ISSUE TITLE
定时任务有时不执行，一旦开始就再也不执行了，手动执行正常

### ISSUE THREAD

**Issue by FairyWorld** [whyour/qinglong#2012]
### Qinglong version

 v2.15.17

### Steps to reproduce

定时任务

### What is expected?

在指定时间执行

### What is actually happening?

没有在指定时间执行，手动执行正常。有有些手动执行一次后定时器又正常了，有些不管手动执行还是重启都无法恢复。还有就是有些是添加后就没有按cron执行，有些是过段时间突然再也不执行了。最后运行时间都是很久之前

### System Info

```shell
docker
```

**Comment by LuluDeer** [comment]
可能因为更新过青龙，新版的特性，在 系统设置-其他设置-定时任务并发数，一般修改为10就行。默认是空好像不会执行任务
