### ISSUE TITLE
升级中断后无法启动

### ISSUE THREAD

**Issue by lwrot** [whyour/qinglong#2014]
### Qinglong version

2.15.17

### Steps to reproduce

在页面升级中刷新，青龙界面无法启动

### What is expected?

不太清楚

### What is actually happening?

/root/.pm2/logs/panel-error.log last 15 lines:
4|panel    | 2023-07-15T21:48:20:  {
4|panel    | 2023-07-15T21:48:20:   code: 14,
4|panel    | 2023-07-15T21:48:20:   details: 'No connection established',
4|panel    | 2023-07-15T21:48:20:   metadata: Metadata { internalRepr: Map(0) {}, options: {} }
4|panel    | 2023-07-15T21:48:20: }
4|panel    | 2023-07-15T21:48:20: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
4|panel    | 2023-07-15T21:48:20: Error: 14 UNAVAILABLE: No connection established
4|panel    | 2023-07-15T21:48:20:     at callErrorFromStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/call.ts:81:17)
4|panel    | 2023-07-15T21:48:20:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/client.ts:356:55)
4|panel    | 2023-07-15T21:48:20:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
4|panel    | 2023-07-15T21:48:20:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
4|panel    | 2023-07-15T21:48:20:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
4|panel    | 2023-07-15T21:48:20:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
4|panel    | 2023-07-15T21:48:20: for call at
4|panel    | 2023-07-15T21:48:20:

**Comment by whyour** [comment]
最新版已修改升级逻辑，会先下载更新，再确认重启，确认前不影响当前系统
