### ISSUE TITLE
登录日志是存在哪里吗？

### ISSUE THREAD

**Issue by zuozihan** [whyour/qinglong#2017]
### Clear and concise description of the problem

登录日志是存在哪里吗？

### Suggested solution

登录日志是存在哪里吗？
![image](https://github.com/whyour/qinglong/assets/45542784/027c48bc-f1db-432a-bdf5-e999dbfa435e)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
db 下的数据库文件里
