### ISSUE TITLE
互助码脚本

### ISSUE THREAD

**Issue by BIGBbox** [whyour/qinglong#202]
不知道为什么一直显示说重来没有运行过签到脚本，是因为使用的签到脚本是别的作者的关系吗

**Comment by whyour** [comment]
https://t.me/qiongqin/80


阅读下

**Comment by yftu** [comment]
> https://t.me/qiongqin/80
> 
> 阅读下

大佬，打不开，提示没有该账户

**Comment by BIGBbox** [comment]
> > https://t.me/qiongqin/80
> > 阅读下
> 
> 大佬，打不开，提示没有该账户

https://t.me/jiaolongjie

**Comment by hunter8605** [comment]
> > > https://t.me/qiongqin/80
> > > 阅读下
> > 
> > 
> > 大佬，打不开，提示没有该账户
> 
> https://t.me/jiaolongjie/80

还是看不了,能分享一下吗?
