### ISSUE TITLE
设置消息推送后没反应

### ISSUE THREAD

**Issue by ksweb2** [whyour/qinglong#2022]
### Qinglong version

v2.15.18

### Steps to reproduce

![Screenshot_20230719_233851](https://github.com/whyour/qinglong/assets/100368718/9cc4777c-4777-4068-abdf-64ce6dbee7af)
![Screenshot_20230719_233906](https://github.com/whyour/qinglong/assets/100368718/5a6752ca-34f9-4684-a940-7dd081e0305c)

### What is expected?

不知道是我安装的问题还是版本问题，重新安装了也是这样。

### What is actually happening?

设置后弹出消息发送，刷新页面后又关闭了，试了plushplus和server都不行

**Comment by whyour** [comment]
PC 上试试，不知道手机上浏览器有没有缓存

**Comment by ksweb2** [comment]
> 

pc上也是这样

**Comment by f8888898** [comment]
我也是有这个问题。电脑手机换了浏览器也是显示成功，但是bot没推送。然后刷新又显示没有绑定

**Comment by JasonSanYe** [comment]
一样、出bug了
企业微信机器人 通知 咋设置都不行、消息发不出去保存了刷新 又变成已关闭

**Comment by ksweb2** [comment]
> 可以手动在配置文件里面添加配置，这样推送是没用问题的 ![image](https://user-images.githubusercontent.com/71380096/254919584-0d1d64bb-e610-41ea-8f1d-49dd5177bf75.png)

**Comment by ksweb2** [comment]
> 可以手动在配置文件里面添加配置，这样推送是没用问题的 ![image](https://user-images.githubusercontent.com/71380096/254919584-0d1d64bb-e610-41ea-8f1d-49dd5177bf75.png)

好的，谢谢谢谢可以了，我昨天也加了刚发现token加错位置了😂
