### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by getr00t** [whyour/qinglong#2025]
### Qinglong version

2.15.19

### Steps to reproduce

报错1：路径”/api/public/health?t=1689916626050“报错500 Internal Server Error如下：

`{
    "code": 500,
    "error": {
        "code": 2,
        "details": "null\n2023-07-21T03:28:04: Error: Cannot find module 'tar'\n2023-07-21T03:28:04: Require stack:\n2023-07-21T03:28:04: - /ql/static/build/services/system.js\n2023-07-21T03:28:04: - /ql/static/build/api/system.js\n2023-07-21T03:28:04: - /ql/static/build/api/index.js\n2023-07-21T03:28:04: - /ql/static/build/loaders/express.js\n2023-07-21T03:28:04: - /ql/static/build/loaders/app.js\n2023-07-21T03:28:04: - /ql/static/build/app.js\n2023-07-21T03:28:04:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\n2023-07-21T03:28:04:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)\n2023-07-21T03:28:04:     at require (node:internal/modules/cjs/helpers:110:18)\n2023-07-21T03:28:04:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)\n2023-07-21T03:28:04:     at Module._compile (node:internal/modules/cjs/loader:1254:14)\n2023-07-21T03:28:04:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n2023-07-21T03:28:04:     at Module.load (node:internal/modules/cjs/loader:1117:32)\n2023-07-21T03:28:04:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n2023-07-21T03:28:04:     at Module.require (node:internal/modules/cjs/loader:1141:19)\n2023-07-21T03:28:04:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {\n2023-07-21T03:28:04:   code: 'MODULE_NOT_FOUND',\n2023-07-21T03:28:04:   requireStack: [\n2023-07-21T03:28:04:     '/ql/static/build/services/system.js',\n2023-07-21T03:28:04:     '/ql/static/build/api/system.js',\n2023-07-21T03:28:04:     '/ql/static/build/api/index.js',\n2023-07-21T03:28:04:     '/ql/static/build/loaders/express.js',\n2023-07-21T03:28:04:     '/ql/static/build/loaders/app.js',\n2023-07-21T03:28:04:     '/ql/static/build/app.js'\n2023-07-21T03:28:04:   ]\n2023-07-21T03:28:04: }\n2023-07-21T03:28:04: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:\n2023-07-21T03:28:04: Error: Cannot find module 'tar'\n2023-07-21T03:28:04: Require stack:\n2023-07-21T03:28:04: - /ql/static/build/services/system.js\n2023-07-21T03:28:04: - /ql/static/build/api/system.js\n2023-07-21T03:28:04: - /ql/static/build/api/index.js\n2023-07-21T03:28:04: - /ql/static/build/loaders/express.js\n2023-07-21T03:28:04: - /ql/static/build/loaders/app.js\n2023-07-21T03:28:04: - /ql/static/build/app.js\n2023-07-21T03:28:04:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\n2023-07-21T03:28:04:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)\n2023-07-21T03:28:04:     at require (node:internal/modules/cjs/helpers:110:18)\n2023-07-21T03:28:04:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)\n2023-07-21T03:28:04:     at Module._compile (node:internal/modules/cjs/loader:1254:14)\n2023-07-21T03:28:04:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n2023-07-21T03:28:04:     at Module.load (node:internal/modules/cjs/loader:1117:32)\n2023-07-21T03:28:04:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n2023-07-21T03:28:04:     at Module.require (node:internal/modules/cjs/loader:1141:19)\n2023-07-21T03:28:04:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)\n2023-07-21T04:07:10: Error: Cannot find module 'tar'\n2023-07-21T04:07:10: Require stack:\n2023-07-21T04:07:10: - /ql/static/build/services/system.js\n2023-07-21T04:07:10: - /ql/static/build/api/system.js\n2023-07-21T04:07:10: - /ql/static/build/api/index.js\n2023-07-21T04:07:10: - /ql/static/build/loaders/express.js\n2023-07-21T04:07:10: - /ql/static/build/loaders/app.js\n2023-07-21T04:07:10: - /ql/static/build/app.js\n2023-07-21T04:07:10:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\n2023-07-21T04:07:10:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)\n2023-07-21T04:07:10:     at require (node:internal/modules/cjs/helpers:110:18)\n2023-07-21T04:07:10:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)\n2023-07-21T04:07:10:     at Module._compile (node:internal/modules/cjs/loader:1254:14)\n2023-07-21T04:07:10:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n2023-07-21T04:07:10:     at Module.load (node:internal/modules/cjs/loader:1117:32)\n2023-07-21T04:07:10:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n2023-07-21T04:07:10:     at Module.require (node:internal/modules/cjs/loader:1141:19)\n2023-07-21T04:07:10:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {\n2023-07-21T04:07:10:   code: 'MODULE_NOT_FOUND',\n2023-07-21T04:07:10:   requireStack: [\n2023-07-21T04:07:10:     '/ql/static/build/services/system.js',\n2023-07-21T04:07:10:     '/ql/static/build/api/system.js',\n2023-07-21T04:07:10:     '/ql/static/build/api/index.js',\n2023-07-21T04:07:10:     '/ql/static/build/loaders/express.js',\n2023-07-21T04:07:10:     '/ql/static/build/loaders/app.js',\n2023-07-21T04:07:10:     '/ql/static/build/app.js'\n2023-07-21T04:07:10:   ]\n2023-07-21T04:07:10: }\n2023-07-21T04:07:10: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:\n2023-07-21T04:07:10: Error: Cannot find module 'tar'\n2023-07-21T04:07:10: Require stack:\n2023-07-21T04:07:10: - /ql/static/build/services/system.js\n2023-07-21T04:07:10: - /ql/static/build/api/system.js\n2023-07-21T04:07:10: - /ql/static/build/api/index.js\n2023-07-21T04:07:10: - /ql/static/build/loaders/express.js\n2023-07-21T04:07:10: - /ql/static/build/loaders/app.js\n2023-07-21T04:07:10: - /ql/static/build/app.js\n2023-07-21T04:07:10:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\n2023-07-21T04:07:10:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)\n2023-07-21T04:07:10:     at require (node:internal/modules/cjs/helpers:110:18)\n2023-07-21T04:07:10:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)\n2023-07-21T04:07:10:     at Module._compile (node:internal/modules/cjs/loader:1254:14)\n2023-07-21T04:07:10:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n2023-07-21T04:07:10:     at Module.load (node:internal/modules/cjs/loader:1117:32)\n2023-07-21T04:07:10:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n2023-07-21T04:07:10:     at Module.require (node:internal/modules/cjs/loader:1141:19)\n2023-07-21T04:07:10:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)\n2023-07-21T12:48:56: Error: Cannot find module 'tar'\n2023-07-21T12:48:56: Require stack:\n2023-07-21T12:48:56: - /ql/static/build/services/system.js\n2023-07-21T12:48:56: - /ql/static/build/api/system.js\n2023-07-21T12:48:56: - /ql/static/build/api/index.js\n2023-07-21T12:48:56: - /ql/static/build/loaders/express.js\n2023-07-21T12:48:56: - /ql/static/build/loaders/app.js\n2023-07-21T12:48:56: - /ql/static/build/app.js\n2023-07-21T12:48:56:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\n2023-07-21T12:48:56:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)\n2023-07-21T12:48:56:     at require (node:internal/modules/cjs/helpers:110:18)\n2023-07-21T12:48:56:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)\n2023-07-21T12:48:56:     at Module._compile (node:internal/modules/cjs/loader:1254:14)\n2023-07-21T12:48:56:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n2023-07-21T12:48:56:     at Module.load (node:internal/modules/cjs/loader:1117:32)\n2023-07-21T12:48:56:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n2023-07-21T12:48:56:     at Module.require (node:internal/modules/cjs/loader:1141:19)\n2023-07-21T12:48:56:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {\n2023-07-21T12:48:56:   code: 'MODULE_NOT_FOUND',\n2023-07-21T12:48:56:   requireStack: [\n2023-07-21T12:48:56:     '/ql/static/build/services/system.js',\n2023-07-21T12:48:56:     '/ql/static/build/api/system.js',\n2023-07-21T12:48:56:     '/ql/static/build/api/index.js',\n2023-07-21T12:48:56:     '/ql/static/build/loaders/express.js',\n2023-07-21T12:48:56:     '/ql/static/build/loaders/app.js',\n2023-07-21T12:48:56:     '/ql/static/build/app.js'\n2023-07-21T12:48:56:   ]\n2023-07-21T12:48:56: }\n2023-07-21T12:48:56: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:\n2023-07-21T12:48:56: Error: Cannot find module 'tar'\n2023-07-21T12:48:56: Require stack:\n2023-07-21T12:48:56: - /ql/static/build/services/system.js\n2023-07-21T12:48:56: - /ql/static/build/api/system.js\n2023-07-21T12:48:56: - /ql/static/build/api/index.js\n2023-07-21T12:48:56: - /ql/static/build/loaders/express.js\n2023-07-21T12:48:56: - /ql/static/build/loaders/app.js\n2023-07-21T12:48:56: - /ql/static/build/app.js\n2023-07-21T12:48:56:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\n2023-07-21T12:48:56:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)\n2023-07-21T12:48:56:     at require (node:internal/modules/cjs/helpers:110:18)\n2023-07-21T12:48:56:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)\n2023-07-21T12:48:56:     at Module._compile (node:internal/modules/cjs/loader:1254:14)\n2023-07-21T12:48:56:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n2023-07-21T12:48:56:     at Module.load (node:internal/modules/cjs/loader:1117:32)\n2023-07-21T12:48:56:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n2023-07-21T12:48:56:     at Module.require (node:internal/modules/cjs/loader:1141:19)\n2023-07-21T12:48:56:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)\n2023-07-21T12:50:06: Error: Cannot find module 'tar'\n2023-07-21T12:50:06: Require stack:\n2023-07-21T12:50:06: - /ql/static/build/services/system.js\n2023-07-21T12:50:06: - /ql/static/build/api/system.js\n2023-07-21T12:50:06: - /ql/static/build/api/index.js\n2023-07-21T12:50:06: - /ql/static/build/loaders/express.js\n2023-07-21T12:50:06: - /ql/static/build/loaders/app.js\n2023-07-21T12:50:06: - /ql/static/build/app.js\n2023-07-21T12:50:06:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\n2023-07-21T12:50:06:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)\n2023-07-21T12:50:06:     at require (node:internal/modules/cjs/helpers:110:18)\n2023-07-21T12:50:06:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)\n2023-07-21T12:50:06:     at Module._compile (node:internal/modules/cjs/loader:1254:14)\n2023-07-21T12:50:06:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n2023-07-21T12:50:06:     at Module.load (node:internal/modules/cjs/loader:1117:32)\n2023-07-21T12:50:06:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n2023-07-21T12:50:06:     at Module.require (node:internal/modules/cjs/loader:1141:19)\n2023-07-21T12:50:06:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {\n2023-07-21T12:50:06:   code: 'MODULE_NOT_FOUND',\n2023-07-21T12:50:06:   requireStack: [\n2023-07-21T12:50:06:     '/ql/static/build/services/system.js',\n2023-07-21T12:50:06:     '/ql/static/build/api/system.js',\n2023-07-21T12:50:06:     '/ql/static/build/api/index.js',\n2023-07-21T12:50:06:     '/ql/static/build/loaders/express.js',\n2023-07-21T12:50:06:     '/ql/static/build/loaders/app.js',\n2023-07-21T12:50:06:     '/ql/static/build/app.js'\n2023-07-21T12:50:06:   ]\n2023-07-21T12:50:06: }\n2023-07-21T12:50:06: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:\n2023-07-21T12:50:06: Error: Cannot find module 'tar'\n2023-07-21T12:50:06: Require stack:\n2023-07-21T12:50:06: - /ql/static/build/services/system.js\n2023-07-21T12:50:06: - /ql/static/build/api/system.js\n2023-07-21T12:50:06: - /ql/static/build/api/index.js\n2023-07-21T12:50:06: - /ql/static/build/loaders/express.js\n2023-07-21T12:50:06: - /ql/static/build/loaders/app.js\n2023-07-21T12:50:06: - /ql/static/build/app.js\n2023-07-21T12:50:06:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\n2023-07-21T12:50:06:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)\n2023-07-21T12:50:06:     at require (node:internal/modules/cjs/helpers:110:18)\n2023-07-21T12:50:06:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)\n2023-07-21T12:50:06:     at Module._compile (node:internal/modules/cjs/loader:1254:14)\n2023-07-21T12:50:06:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n2023-07-21T12:50:06:     at Module.load (node:internal/modules/cjs/loader:1117:32)\n2023-07-21T12:50:06:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n2023-07-21T12:50:06:     at Module.require (node:internal/modules/cjs/loader:1141:19)\n2023-07-21T12:50:06:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)\n\n{\"code\":7,\"killed\":false,\"signal\":null,\"cmd\":\"curl -s http://localhost:5600/api/system\"}",
        "metadata": {
            "content-type": [
                "application/grpc+proto"
            ],
            "date": [
                "Fri, 21 Jul 2023 05:10:18 GMT"
            ]
        }
    }
}`

报错2：路径`/api/env.js`报错502 Bad Gateway，response无任何信息返回

### What is expected?

该如何修复，我docker exec -it qinglong bash进入容器后，使用pnpm i重新按装了一遍依赖后也无法修复bug

### What is actually happening?

`Request failed with status code 500`

**Comment by 365360171** [comment]
我是直接stop，然后rm镜像，再重装就好了，数据没丢

**Comment by whyour** [comment]
1. 首先更新镜像，确保更新到了最新版镜像
2. 然后确保原来映射了 data 目录
3. 使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
