### ISSUE TITLE
有命令行的备份方式么

### ISSUE THREAD

**Issue by 17huiwei** [whyour/qinglong#2027]
### Clear and concise description of the problem

现在只能在webui上解决，很不方便

### Suggested solution

如果有命令行，就可以写成脚本，自动完成各种备份

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
可以在系统设置，创建应用，通过 openapi 进行备份的
