### ISSUE TITLE
无法启动面板

### ISSUE THREAD

**Issue by testwhite** [whyour/qinglong#2032]
### Qinglong version

2.15.16

### Steps to reproduce

已执行ql -l chech 和 ql -l update

### What is expected?

已执行ql -l chech 和 ql -l update

### What is actually happening?

![image](https://github.com/whyour/qinglong/assets/31587423/6e0e225e-c4f7-4e72-b51c-af5c27382f07)

### System Info

```shell
群晖
```

### Any additional comments?

已执行ql -l chech 和 ql -l update

**Comment by whyour** [comment]
1. 首先更新镜像，确保更新到了最新版镜像
2. 确保原来映射了 data 目录
3. 使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新

**Comment by testwhite** [comment]
请问下data目录的路径是什么或者映射方法

**Comment by testwhite** [comment]
/ql/data吗

**Comment by whyour** [comment]
@testwhite 是的
