### ISSUE TITLE
关于面板定时失效的问题

### ISSUE THREAD

**Issue by nmlgbcn** [whyour/qinglong#2033]
### Qinglong version

正常版

### Steps to reproduce

当你登录的时候 定时任务不会自动运行 旧版本都正常 新版有问题

### What is expected?

希望修复

### What is actually happening?

定了时害得我到点没抢到券

**Comment by hy5424** [comment]
同样的问题

**Comment by chaos-zhu** [comment]
同样的问题+1, 有下次运行时间，但是任务并不会跑

**Comment by whyour** [comment]
@chaos-zhu 是几位的定时规则

**Comment by chaos-zhu** [comment]
@whyour `0 * * * * ?` 每分钟跑一次。看面板下次运行时间是正常回显的，但是任务并不会跑，最后运行时间是我手动触发的。设置里面并发数也填了10. 

![image](https://github.com/whyour/qinglong/assets/44160914/6caf5ec2-26f5-43f3-88d7-287cb36a30eb)

**Comment by whyour** [comment]
> @whyour `0 * * * * ?` 每分钟跑一次。看面板下次运行时间是正常回显的，但是任务并不会跑，最后运行时间是我手动触发的。设置里面并发数也填了10.
> 
> ![image](https://user-images.githubusercontent.com/44160914/255782293-6caf5ec2-26f5-43f3-88d7-287cb36a30eb.png)

看下容器内的 /root/.pm2/logs/schedule-out.log

**Comment by whyour** [comment]
> @whyour `0 * * * * ?` 每分钟跑一次。看面板下次运行时间是正常回显的，但是任务并不会跑，最后运行时间是我手动触发的。设置里面并发数也填了10.
> 
> ![image](https://user-images.githubusercontent.com/44160914/255782293-6caf5ec2-26f5-43f3-88d7-287cb36a30eb.png)

容器内执行下 pm2 restart schedule 应该就好了

**Comment by chaos-zhu** [comment]
@whyour 我试试看

> /root/.pm2/logs/schedule-out.log

2023-07-24T10:01:37: debug:   ✌️ 定时服务启动成功！

**Comment by chaos-zhu** [comment]
> > @whyour `0 * * * * ?` 每分钟跑一次。看面板下次运行时间是正常回显的，但是任务并不会跑，最后运行时间是我手动触发的。设置里面并发数也填了10.
> > ![image](https://user-images.githubusercontent.com/44160914/255782293-6caf5ec2-26f5-43f3-88d7-287cb36a30eb.png)
> 
> 容器内执行下 pm2 restart schedule 应该就好了

@whyour 没用，定时任务还是不会执行

**Comment by chaos-zhu** [comment]
往前试了近期好几个版本都不行。**v2.15.13**验证通过，定时功能正常

**Comment by whyour** [comment]
> 往前试了近期好几个版本都不行。**v2.15.13**验证通过，定时功能正常

什么设备

**Comment by chaos-zhu** [comment]
> > 往前试了近期好几个版本都不行。**v2.15.13**验证通过，定时功能正常
> 
> 什么设备

腾讯云轻量
名称: VM-8-9-ubuntu 22.04
类型: Linux
架构: x64
平台: linux
版本: 5.4.0-126-generic

**Comment by whyour** [comment]
> > > 往前试了近期好几个版本都不行。**v2.15.13**验证通过，定时功能正常
> > 
> > 
> > 什么设备
> 
> 腾讯云轻量 名称: VM-8-9-ubuntu 22.04 类型: Linux 架构: x64 平台: linux 版本: 5.4.0-126-generic

定时任务怎么写的

**Comment by chaos-zhu** [comment]
> > @whyour `0 * * * * ?` 每分钟跑一次。看面板下次运行时间是正常回显的，但是任务并不会跑，最后运行时间是我手动触发的。设置里面并发数也填了10.
> > ![image](https://user-images.githubusercontent.com/44160914/255782293-6caf5ec2-26f5-43f3-88d7-287cb36a30eb.png)
> 
> 容器内执行下 pm2 restart schedule 应该就好了

@whyour 规则在这

**Comment by whyour** [comment]
> > > @whyour `0 * * * * ?` 每分钟跑一次。看面板下次运行时间是正常回显的，但是任务并不会跑，最后运行时间是我手动触发的。设置里面并发数也填了10.
> 
> > > ![image](https://user-images.githubusercontent.com/44160914/255782293-6caf5ec2-26f5-43f3-88d7-287cb36a30eb.png)
> 
> > 
> 
> > 容器内执行下 pm2 restart schedule 应该就好了
> 
> 
> 
> @whyour 规则在这

我是说任务，你执行的什么任务，咋写的

**Comment by chaos-zhu** [comment]
> > > > @whyour `0 * * * * ?` 每分钟跑一次。看面板下次运行时间是正常回显的，但是任务并不会跑，最后运行时间是我手动触发的。设置里面并发数也填了10.
> > 
> > 
> > > > ![image](https://user-images.githubusercontent.com/44160914/255782293-6caf5ec2-26f5-43f3-88d7-287cb36a30eb.png)
> > 
> > 
> > > 
> > 
> > 
> > > 容器内执行下 pm2 restart schedule 应该就好了
> > 
> > 
> > @whyour 规则在这
> 
> 我是说任务，你执行的什么任务，咋写的

跑一个js脚本，应该是没加task的原因。抱歉（第一次用

**Comment by whyour** [comment]
@chaos-zhu 下个版本会修复不加task无法运行的问题
