### ISSUE TITLE
请问2.15.20里的备份功能，数据是保存在哪里的？

### ISSUE THREAD

**Issue by jjj333** [whyour/qinglong#2038]
### Clear and concise description of the problem

点击备份，完成后只是显示了一个绿色的√，也不知道数据是在哪里的？多点几次是生成了多份备份还是覆盖的也不知道

### Suggested solution

能否显示一下保存路径？

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jjj333** [comment]
cent browser 5.0.1002.354

**Comment by whyour** [comment]
@jjj333 使用主流浏览器试试

**Comment by jjj333** [comment]
额。。。用了edge（什么插件都没装）还是一样，直接显示个勾就结束了，正常的是该有个保存窗口的吗？我看点了还原是会弹出选择文件窗口的

**Comment by whyour** [comment]
@jjj333 用chrome试试

**Comment by jjj333** [comment]
chrome 内核115的，还是一样
![Snipaste_2023-07-27_20-12-20](https://github.com/whyour/qinglong/assets/11435055/0504b0c8-dc37-4c68-9cd5-e4a5d67681d9)
![Snipaste_2023-07-27_20-12-41](https://github.com/whyour/qinglong/assets/11435055/13896a6c-113b-474e-8fed-3a69ed07f949)

**Comment by whyour** [comment]
> chrome 内核115的，还是一样 ![Snipaste_2023-07-27_20-12-20](https://user-images.githubusercontent.com/11435055/256535055-0504b0c8-dc37-4c68-9cd5-e4a5d67681d9.png) ![Snipaste_2023-07-27_20-12-41](https://user-images.githubusercontent.com/11435055/256535073-13896a6c-113b-474e-8fed-3a69ed07f949.png)

要不然你浏览器禁止弹框下载
<img width="748" alt="image" src="https://github.com/whyour/qinglong/assets/22700758/bf969652-39e8-4815-aa69-f6f721be78b0">

**Comment by jjj333** [comment]
更新到2.16.0就能正常弹出保存框了
