### ISSUE TITLE
依赖管理NodeJs下的canvas 安装失败

### ISSUE THREAD

**Issue by pansamrt** [whyour/qinglong#2039]
### Qinglong version

依赖管理NodeJs下的canvas 安装失败

### Steps to reproduce

依赖管理NodeJs下的canvas 安装失败

### What is expected?

怎么修复？

### What is actually happening?

依赖管理NodeJs下的canvas 安装失败

**Comment by whyour** [comment]
https://github.com/whyour/qinglong/issues/1645#issuecomment-1309856519
