### ISSUE TITLE
对脚本请求url进行监控

### ISSUE THREAD

**Issue by Ocyss** [whyour/qinglong#2041]
### Clear and concise description of the problem

因为有大量的脚本都是加密脚本，我对加密不支持也不会反对，但我觉得应该对所有脚本请求的url进行一个记录。由用户维护一些可信域名，或者用户自己来管理是否有不可信的url请求，因为没有人希望自己的ck被坏人偷走，这是一个很可怕的事情
由于青龙是ts写的，我觉得可能要通过一些别的手段才能记录，我也会去研究下的。

### Suggested solution

由社区维护一份常用且较安全的权威域名，如果有不安全的域名进行通知，由用户来判断是否要添加进白名单。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by inoyna12** [comment]
+1

**Comment by whyour** [comment]
repeat with https://github.com/whyour/qinglong/issues/1656
