### ISSUE TITLE
本地部署模式,提示如下错误

### ISSUE THREAD

**Issue by wingser** [whyour/qinglong#2048]
### Qinglong version

最新版本

### Steps to reproduce

运行 npm install -g @whyour/qinglong
提示如下错误。已经安装node、Python3、pip3等各种组件。
![image](https://github.com/whyour/qinglong/assets/13481389/a564d2d4-a3d5-4a4b-89e6-09175a61414b)

### What is expected?

环境是Ubuntu容器，能否帮忙看戏什么原因。

### What is actually happening?

本地部署失败。
![image](https://github.com/whyour/qinglong/assets/13481389/45105a01-ac26-4487-b2ab-ec5ada7698dc)

### System Info

```shell
System:
    OS: Linux 4.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (4) x64 AMD EPYC 7571
    Memory: 9.20 GB / 15.30 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.20.1 - /usr/bin/node
    npm: 8.19.4 - /usr/bin/npm
    pnpm: 8.6.11 - /usr/bin/pnpm
```

**Comment by longhuishen** [comment]
一样 我也报错

**Comment by whyour** [comment]
建议使用 docker 环境，后期可能会采用下载安装包的方式安装，npm 可能有些依赖依赖你的环境
如果还想尝试，可以 试试 npm i node-pre-gyp 继续安装
