### ISSUE TITLE
执行mjs后缀的js文件，报错无权限

### ISSUE THREAD

**Issue by NNNNzs** [whyour/qinglong#2050]
### Qinglong version

2.15.3

### Steps to reproduce

1. 任意仓库创建.mjs后缀的文件，test1.mjs test2.js
2. 确认仓库拉取配置添加mjs .js
3. 分别执行test1.mjs test2.js文件
4. test2.js可以正常运行 test1报错无权限
<img width="502" alt="image" src="https://github.com/whyour/qinglong/assets/27205495/8e24eb8d-8df4-4b8d-b37c-4a026dc2adbb">

### What is expected?

正常执行

### What is actually happening?

报错 无权限
<img width="527" alt="image" src="https://github.com/whyour/qinglong/assets/27205495/0972ef6c-40d6-44fb-8003-6a28e1622cea">

### System Info

```shell
docker 

System:
    OS: Linux 3.10 Alpine Linux
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
    Memory: 2.09 GB / 3.70 GB
    Container: Yes
    Shell: 5.2.12 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 9.1.2 - /usr/bin/npm
    pnpm: 7.18.1 - /usr/local/bin/pnpm
```

### Any additional comments?

无

**Comment by whyour** [comment]
2.16.0 已支持运行 mjs 文件
