### ISSUE TITLE
登录显示服务启动超时

### ISSUE THREAD

**Issue by honeyallen321** [whyour/qinglong#2051]
### Qinglong version

latest

### Steps to reproduce

服务启动超时,按照以下方法尝试过后还是无法得到解决。
请先按如下方式修复：
1. 宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
2. 容器内执行 ql -l check、ql -l update
3. 如果无法解决，容器内执行 pm2 logs，拷贝执行结果[提交 issue](https://github.com/whyour/qinglong/issues/new?assignees=&labels=&template=bug_report.yml)
Name resolution failed for target dns:localhost:5500

### What is expected?

希望修复这个问题

### What is actually happening?

![screenshot20230804](https://github.com/whyour/qinglong/assets/79709362/a8eac41b-29a9-4bc9-8f8c-47e110bc5973)
![screenshot20230804 (1)](https://github.com/whyour/qinglong/assets/79709362/de8aaf3a-23f1-493a-8c5a-d07a7cd780aa)
![screenshot20230804 (2)](https://github.com/whyour/qinglong/assets/79709362/87befeaa-a52b-48fc-b4ef-6de1b20cd9e7)

### System Info

```shell
PM2         | App [schedule:0] exited with code [1] via signal [SIGINT]          
PM2         | App [schedule:0] starting in -fork mode-                           
PM2         | App [schedule:0] online                                            
0|schedule  | 2023-08-04T12:48:53: Error: Name resolution failed for target dns:l
ocalhost:5500                                                                    
0|schedule  | 2023-08-04T12:48:53:     at Object.onError (/ql/node_modules/.pnpm/
@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server.ts:613:26)            
0|schedule  | 2023-08-04T12:48:53:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.
8.15/node_modules/@grpc/grpc-js/src/resolver-dns.ts:258:25
```

**Comment by whyour** [comment]
你的 hosts 没有 localhost ？

**Comment by maizijuni** [comment]
咋修复
