### ISSUE TITLE
建议添加随青龙面板启动的定时规则（即开机自动运行脚本，不再定时启动）

### ISSUE THREAD

**Issue by wahahaha89** [whyour/qinglong#2052]
### Clear and concise description of the problem

运行自己写的脚本需要开机后一直运行，不希望定时重新执行。故提出此建议。

### Suggested solution

添加开机启动的定时规则

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
@wahahaha89 定时任务添加一个任务，extra 里增加 task xxx.py

**Comment by wahahaha89** [comment]
> @wahahaha89 定时任务添加一个任务，extra 里增加 task xxx.py

非常感谢您的回复，但如果是多个脚本的话，好像只能启动第一个脚本
![1](https://github.com/whyour/qinglong/assets/140935605/85a80d4e-ad63-4390-ad81-a1a7c4569d76)
![2](https://github.com/whyour/qinglong/assets/140935605/34594581-346e-4e65-be4c-6ddad6aa42af)

**Comment by whyour** [comment]
> > @wahahaha89 定时任务添加一个任务，extra 里增加 task xxx.py
> 
> 非常感谢您的回复，但如果是多个脚本的话，好像只能启动第一个脚本 ![1](https://user-images.githubusercontent.com/140935605/258438295-85a80d4e-ad63-4390-ad81-a1a7c4569d76.jpg) ![2](https://user-images.githubusercontent.com/140935605/258438301-34594581-346e-4e65-be4c-6ddad6aa42af.jpg)

task 命令是同步执行的，第一个执行完才会执行第二个。同时执行的话就用 shell 后台执行就行  task x.py &

**Comment by wahahaha89** [comment]
> > > @wahahaha89 定时任务添加一个任务，extra 里增加 task xxx.py
> > 
> > 
> > 非常感谢您的回复，但如果是多个脚本的话，好像只能启动第一个脚本 ![1](https://user-images.githubusercontent.com/140935605/258438295-85a80d4e-ad63-4390-ad81-a1a7c4569d76.jpg) ![2](https://user-images.githubusercontent.com/140935605/258438301-34594581-346e-4e65-be4c-6ddad6aa42af.jpg)
> 
> task 命令是同步执行的，第一个执行完才会执行第二个。同时执行的话就用 shell 后台执行就行 task x.py &

感谢！问题解决了。
