### ISSUE TITLE
青龙面板打不开

### ISSUE THREAD

**Issue by xiaopengzzc** [whyour/qinglong#2064]
### Qinglong version

2.16.0

### Steps to reproduce

打开青龙面板，进不去主页面，就一直在启动中，看了一下日志，没看出所以然来。求解决
![image](https://github.com/whyour/qinglong/assets/136769452/095337d7-fb88-4c2d-bc76-ca9199c85d7a)

![微信图片_20230809114215](https://github.com/whyour/qinglong/assets/136769452/9d454334-5955-46d6-b251-8dfd904f9109)

### What is expected?

得到解决

### What is actually happening?

更新之后可以进去，过了一两天面板进不去了

**Comment by whyour** [comment]
进容器看 pm2 logs

**Comment by xiaopengzzc** [comment]
> 进容器看pm2日志

![image](https://github.com/whyour/qinglong/assets/136769452/c64831bb-040a-4f7a-8033-16a088086c9c)
怎么说

**Comment by SunChongW** [comment]
同样的问题，升级到2.16.0后主页打不开了，直接到xxxx:5700/error 求解决方案 谢谢！

**Comment by SunChongW** [comment]
运行ql check后显示nginx异常，其它项目正常。
=====> 面板服务启动正常                                                                       
                                                                                              
ps: bad -o argument 'command', supported arguments: user,group,comm,args,pid,ppid,pgid,etime,n
ice,rgroup,ruser,time,tty,vsz,sid,stat,rss                                                    
=====> 检测nginx服务                                                                          
                                                                                              
                                                                                              
=====> nginx服务异常，重新启动nginx                                                           
                                                                                              
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)                             
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)                             
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)                             
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)                             
nginx: [emerg] bind() to 0.0.0.0:5700 failed (98: Address in use)                             
nginx: [emerg] still could not bind()                                                         
---> pm2日志                                                                                  
                                                                                              
=====> 检测后台

**Comment by whyour** [comment]
使用宿主机方式更新下

首先更新镜像，确保更新到了最新版镜像
确保原来映射了 data 目录
使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
