### ISSUE TITLE
调用notify.py进行推送出现报错

### ISSUE THREAD

**Issue by nsv2051** [whyour/qinglong#2066]
### Qinglong version

2.16.0

### Steps to reproduce

更新2.16之前，调用notify.py文件可以正常推送到企业微信，最新版本的notify.py文件有新增参数吗

### What is expected?

更新2.16之前，调用notify.py文件可以正常推送到企业微信

### What is actually happening?

Exception in thread wecom_app:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/data/scripts/share/notify.py", line 417, in wecom_app
    response = wx.send_mpnews(title, content, media_id, touser)
  File "/ql/data/scripts/share/notify.py", line 459, in send_mpnews
    send_url = f"https://{self.HOST}/cgi-bin/message/send?access_token={self.get_access_token()}"
AttributeError: 'WeCom' object has no attribute 'HOST'

**Comment by nsv2051** [comment]
> notify.py和sendNotify.js这两个有啥区别尼？应该怎么设置推送啊，我想使用邮箱来接受推送，没看到哪里有使用文档。

分别是给python和js文件用来调用的，将相应的文件引入脚本中来调用就可以，邮箱推送需要配置好邮箱推送的变量，

**Comment by nsv2051** [comment]
> > > notify.py和sendNotify.js这两个有啥区别尼？应该怎么设置推送啊，我想使用邮箱来接受推送，没看到哪里有使用文档。
> > 
> > 
> > 分别是给python和js文件用来调用的，将相应的文件引入脚本中来调用就可以，邮箱推送需要配置好邮箱推送的变量，
> 
> 我测试邮件通知都是配置好了的成功的，就是脚本通知不知道怎么配置尼？也没找到文档，应该怎么配置尼，我看作者说sendNotify.js需要使用内置的，我看desp 文件夹里面有sendNotify.js，但是青龙面板的脚本管理里面并看不到sendNotify.js，只有显示notify.py文件，我就在脚本的同目录自己放了个sendNotify.js，不知道怎么调用，没找到对应的文档使用，我看了sendNotify.js里面的注释说的必填是text 通知头desp 通知体，但是我写进去都没达到通知的效果，甚至报错，你们使用的是哪个版本的sendNotify.js尼？请问应该怎么正确的来调用sendNotify.js里面的api尼

https://gist.github.com/nsv2051/6d5cb33390e9f8b77aef54bdfe2d16a9
简单放了一个调用py文件的demo，你参考着用吧，js的我没用过

**Comment by whyour** [comment]
2.16.1 已修复
