### ISSUE TITLE
【脚本日志modal弹框宽度调整】当前弹窗过窄，宽度能否支持按屏幕宽度的百分比来确定呢

### ISSUE THREAD

**Issue by hulog** [whyour/qinglong#2067]
### Clear and concise description of the problem

FYI

### Suggested solution

当前弹窗过窄，信息被截断有点苦恼，信息展示错位、换行等，对阅读造成一定的困难。宽度能否支持按屏幕宽度的百分比来确定呢

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
百分之多少呢

**Comment by hulog** [comment]
保持跟名称的弹窗一致怎么样？80vw

> 对了，大屏80vw可能会太宽，加个最大宽度max-width

综上推荐如下配置（可适当调整）：

```css
width: 80vw
max-width: 1200px
```

**Comment by whyour** [comment]
> 保持跟名称的弹窗一致怎么样？80vw
> 
> > 对了，大屏80vw可能会太宽，加个最大宽度max-width
> 
> 综上推荐如下配置（可适当调整）：
> 
> ```css
> width: 80vw
> max-width: 1200px
> ```

日志面板需要这么宽吗😄
