### ISSUE TITLE
更新到最新版后启动报错

### ISSUE THREAD

**Issue by fortheday520** [whyour/qinglong#2071]
### Qinglong version

2.16

### Steps to reproduce

PM2        | 2023-08-11T10:04:18: PM2 log: App [schedule:0] online
PM2        | 2023-08-11T10:04:18: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-08-11T10:04:18: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-08-11T10:04:18: PM2 log: App [schedule:0] online
PM2        | 2023-08-11T10:04:19: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-08-11T10:04:19: PM2 log: Script /ql/static/build/schedule/index.js had too many unstable restarts (10). Stopped. "errored"
PM2        | 2023-08-11T10:04:19: PM2 log: App [schedule:0] online
PM2        | 2023-08-11T10:04:19: PM2 log: App [schedule:0] online
PM2        | 2023-08-11T10:04:19: PM2 log: App [schedule:0] online
PM2        | 2023-08-11T10:04:20: PM2 log: App [panel:2] online
PM2        | 2023-08-11T10:04:20: PM2 log: App [schedule:0] online
PM2        | 2023-08-11T10:04:20: PM2 log: App [schedule:0] online
PM2        | 2023-08-11T10:04:20: PM2 log: App [schedule:0] online
PM2        | 2023-08-11T10:04:21: PM2 log: App [schedule:0] online
PM2        | 2023-08-11T10:04:21: PM2 log: App [schedule:0] online

/root/.pm2/logs/schedule-out.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-08-11T10:04:16: info:    ✌️ Sentry loaded
1|public   | 2023-08-11T10:04:16: info:    ✌️ DB loaded
1|public   | 2023-08-11T10:04:16: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-08-11T10:04:18: info:    ✌️ DB loaded
2|panel    | 2023-08-11T10:04:18: info:    ✌️ Init file down
2|panel    | 2023-08-11T10:04:18: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-08-11T10:04:18: - /ql/static/build/api/user.js
2|panel    | 2023-08-11T10:04:18: - /ql/static/build/api/index.js
2|panel    | 2023-08-11T10:04:18: - /ql/static/build/loaders/express.js
2|panel    | 2023-08-11T10:04:18: - /ql/static/build/loaders/app.js
2|panel    | 2023-08-11T10:04:18: - /ql/static/build/app.js
2|panel    | 2023-08-11T10:04:18:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2|panel    | 2023-08-11T10:04:18:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-08-11T10:04:18:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-08-11T10:04:18:     at Object.<anonymous> (/ql/back/shared/pLimit.ts:1:1)
2|panel    | 2023-08-11T10:04:18:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2|panel    | 2023-08-11T10:04:18:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2|panel    | 2023-08-11T10:04:18:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2|panel    | 2023-08-11T10:04:18:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2|panel    | 2023-08-11T10:04:18:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2|panel    | 2023-08-11T10:04:18:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

/root/.pm2/logs/schedule-error.log last 15 lines:
0|schedule | 2023-08-11T10:04:19:     at require (node:internal/modules/cjs/helpers:110:18)
0|schedule | 2023-08-11T10:04:19:     at Object.<anonymous> (/ql/back/shared/runCron.ts:1:1)
0|schedule | 2023-08-11T10:04:19:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
0|schedule | 2023-08-11T10:04:19:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
0|schedule | 2023-08-11T10:04:19:     at Module.load (node:internal/modules/cjs/loader:1117:32)
0|schedule | 2023-08-11T10:04:19:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
0|schedule | 2023-08-11T10:04:19:     at Module.require (node:internal/modules/cjs/loader:1141:19)
0|schedule | 2023-08-11T10:04:19:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
0|schedule | 2023-08-11T10:04:19:   code: 'MODULE_NOT_FOUND',
0|schedule | 2023-08-11T10:04:19:   requireStack: [
0|schedule | 2023-08-11T10:04:19:     '/ql/static/build/shared/runCron.js',
0|schedule | 2023-08-11T10:04:19:     '/ql/static/build/schedule/addCron.js',
0|schedule | 2023-08-11T10:04:19:     '/ql/static/build/schedule/index.js'
0|schedule | 2023-08-11T10:04:19:   ]
0|schedule | 2023-08-11T10:04:19: }

### What is expected?

怎么解决

### What is actually happening?

如题

**Comment by maizijuni** [comment]
一样的问题

**Comment by whyour** [comment]
使用宿主机方式更新下

首先更新镜像，确保更新到了最新版镜像
确保原来映射了 data 目录
使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
