### ISSUE TITLE
未找到认证文件，重新初始化

### ISSUE THREAD

**Issue by wensenz** [whyour/qinglong#2074]
### Qinglong version

 v2.15.15

### Steps to reproduce

登录的时候提示

### What is expected?

登录的时候提示

### What is actually happening?

登录的时候提示

**Comment by wensenz** [comment]
![image](https://github.com/whyour/qinglong/assets/10190672/b06cc236-eab6-4b25-823b-9461e0637c5f)

**Comment by whyour** [comment]
刷新下 重新设置密码不行？
