### ISSUE TITLE
更新面板后报错无法启动

### ISSUE THREAD

**Issue by keyblues** [whyour/qinglong#2075]
### Qinglong version

2.15.14

### Steps to reproduce

版本更新，使用的是面板内置检查更新按钮，更新到2.16.0，然后无法启动。然后就是按照步骤修复，但不成功

### What is expected?

在保留数据的情况下修复

### What is actually happening?

以下是容器内执行 pm2 logs输出的信息
root@3991c6fef1a4:/ql $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-08-16T13:07:47: PM2 log: Stopping app:public id:1
PM2        | 2023-08-16T13:07:47: PM2 log: App [schedule:0] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-16T13:07:47: PM2 log: App [public:1] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-16T13:07:47: PM2 log: pid=592 msg=process killed
PM2        | 2023-08-16T13:07:47: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-08-16T13:07:47: PM2 log: pid=593 msg=process killed
PM2        | 2023-08-16T13:07:47: PM2 log: App [public:1] starting in -fork mode-
PM2        | 2023-08-16T13:07:57: PM2 log: App [schedule:0] online
PM2        | 2023-08-16T13:07:57: PM2 log: App [public:1] online
PM2        | 2023-08-16T13:07:58: PM2 log: Process 2 in a stopped status, starting it
PM2        | 2023-08-16T13:07:58: PM2 log: Stopping app:panel id:2
PM2        | 2023-08-16T13:07:58: PM2 log: App [panel:2] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-16T13:07:58: PM2 log: pid=619 msg=process killed
PM2        | 2023-08-16T13:07:58: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-08-16T13:08:08: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-08-16T13:07:58: debug:   ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-08-16T13:07:57: info:    ✌️ Sentry loaded
1|public   | 2023-08-16T13:08:10: info:    ✌️ DB loaded
1|public   | 2023-08-16T13:08:10: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-08-16T13:08:11: info:    ✌️ DB loaded
2|panel    | 2023-08-16T13:08:11: info:    ✌️ Init file down
2|panel    | 2023-08-16T13:08:13: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-08-16T13:08:18: - /ql/static/build/api/system.js
2|panel    | 2023-08-16T13:08:18: - /ql/static/build/api/index.js
2|panel    | 2023-08-16T13:08:18: - /ql/static/build/loaders/express.js
2|panel    | 2023-08-16T13:08:18: - /ql/static/build/loaders/app.js
2|panel    | 2023-08-16T13:08:18: - /ql/static/build/app.js
2|panel    | 2023-08-16T13:08:18:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
2|panel    | 2023-08-16T13:08:18:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-08-16T13:08:18:     at require (node:internal/modules/cjs/helpers:103:18)
2|panel    | 2023-08-16T13:08:18:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2|panel    | 2023-08-16T13:08:18:     at Module._compile (node:internal/modules/cjs/loader:1159:14)
2|panel    | 2023-08-16T13:08:18:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
2|panel    | 2023-08-16T13:08:18:     at Module.load (node:internal/modules/cjs/loader:1037:32)
2|panel    | 2023-08-16T13:08:18:     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
2|panel    | 2023-08-16T13:08:18:     at Module.require (node:internal/modules/cjs/loader:1061:19)
2|panel    | 2023-08-16T13:08:18:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

### System Info

```shell
Ubuntu 20.04.6 LTS | V20230101-4.4.35_ecoo_81100468-32
armv7l架构
```

**Comment by keyblues** [comment]
按照这个方法试过好几次了，还是不行
root@hi3798mv100:/home/ubuntu# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR 3991c6fef1a4
time="2023-08-18T01:54:30Z" level=info msg="Watchtower 1.5.3"
time="2023-08-18T01:54:30Z" level=info msg="Using no notifications"
time="2023-08-18T01:54:30Z" level=info msg="Only checking containers which name matches \"3991c6fef1a4\""
time="2023-08-18T01:54:30Z" level=info msg="Running a one time update."
time="2023-08-18T01:54:31Z" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no

**Comment by whyour** [comment]
@keyblues 最后要用容器名称

**Comment by keyblues** [comment]
> 



> @keyblues 最后要用容器名称

应该是这样的吧

root@hi3798mv100:/home/ubuntu# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR registry.hub.docker.com/whyour/qinglong:latest
time="2023-08-18T03:49:18Z" level=info msg="Watchtower 1.5.3"
time="2023-08-18T03:49:18Z" level=info msg="Using no notifications"
time="2023-08-18T03:49:18Z" level=info msg="Only checking containers which name matches \"registry.hub.docker.com/whyour/qinglong:latest\""
time="2023-08-18T03:49:18Z" level=info msg="Running a one time update."
time="2023-08-18T03:49:18Z" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2023-08-18T03:49:18Z" level=info msg="Waiting for the notification goroutine to finish" notify=no

**Comment by whyour** [comment]
@keyblues 最后是你 docker run 指定的容器名称

**Comment by keyblues** [comment]
> @keyblues 最后是你 docker run 指定的容器名称

修复已完成，但数据被清除了。。。。蓝廋
好几个手写脚本都没有备份。

**Comment by whyour** [comment]
@keyblues run
