### ISSUE TITLE
版本不对

### ISSUE THREAD

**Issue by alpha302** [whyour/qinglong#2077]
### Qinglong version

v2.10.12

### Steps to reproduce

docker run -dit \
-v /root/ql/config:/ql/config \
-v /root/ql/log:/ql/log \
-v /root/ql/db:/ql/db \
-v /root/ql/scripts:/ql/scripts \
-v /root/ql/jbot:/ql/jbot \
-v /root/ql/repo:/ql/repo \
-p 15700:5700 \
-e ENABLE_HANGUP=true \
-e ENABLE_WEB_PANEL=true \
--name ql \
--hostname ql \
--privileged=true \
--restart always \
whyour/qinglong:latest

### What is expected?

我预期应该是最新的v2.16版本
但是目前是v2.10版本

### What is actually happening?

<img width="1273" alt="image" src="https://github.com/whyour/qinglong/assets/55012418/a21dbed9-d7b1-4bd9-8339-51cf63f08802">

### System Info

```shell
➜  ~ uname -a
Linux src 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

➜  ~ cat /proc/version                   
Linux version 5.4.0-148-generic (buildd@lcy02-amd64-112) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023
```

**Comment by alpha302** [comment]
已解决，lastest 需要换成debain

**Comment by whyour** [comment]
不是这个问题，你镜像源有问题，把你 docker 的镜像源设置删了
