### ISSUE TITLE
你好，我这边更新青龙后出现error

### ISSUE THREAD

**Issue by facaizhang** [whyour/qinglong#2079]
### Qinglong version

最新更新

### Steps to reproduce

1. 宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
2. 容器内执行 ql -l check、ql -l update
3. 如果无法解决，容器内执行 pm2 logs，拷贝执行结果

### What is expected?

解决这个问题并里面文件不会丢失

### What is actually happening?

ng it
PM2        | 2023-08-19T00:03:09: PM2 log: Stopping app:panel id:2
PM2        | 2023-08-19T00:03:09: PM2 log: App [panel:2] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-19T00:03:09: PM2 log: pid=3909 msg=process killed
PM2        | 2023-08-19T00:03:09: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-08-19T00:03:12: PM2 log: App [public:1] online
PM2        | 2023-08-19T00:03:19: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-08-19T00:03:08: debug:   ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-08-19T00:03:08: info:    ✌️ Sentry loaded
1|public   | 2023-08-19T00:03:12: info:    ✌️ DB loaded
1|public   | 2023-08-19T00:03:12: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-08-19T00:03:16: info:    ✌️ DB loaded
2|panel    | 2023-08-19T00:03:16: info:    ✌️ Init file down
2|panel    | 2023-08-19T00:03:16: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/api/system.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/api/index.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/loaders/express.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/loaders/app.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/app.js
2|panel    | 2023-08-19T00:03:19:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2|panel    | 2023-08-19T00:03:19:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-08-19T00:03:19:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-08-19T00:03:19:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2|panel    | 2023-08-19T00:03:19:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2|panel    | 2023-08-19T00:03:19:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2|panel    | 2023-08-19T00:03:19:     at Module.load (node:internal/modules/cjs/loader:1119:32)
2|panel    | 2023-08-19T00:03:19:     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
2|panel    | 2023-08-19T00:03:19:     at Module.require (node:internal/modules/cjs/loader:1143:19)
2|panel    | 2023-08-19T00:03:19:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

### System Info

```shell
ng it
PM2        | 2023-08-19T00:03:09: PM2 log: Stopping app:panel id:2
PM2        | 2023-08-19T00:03:09: PM2 log: App [panel:2] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-19T00:03:09: PM2 log: pid=3909 msg=process killed
PM2        | 2023-08-19T00:03:09: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-08-19T00:03:12: PM2 log: App [public:1] online
PM2        | 2023-08-19T00:03:19: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-08-19T00:03:08: debug:   ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-08-19T00:03:08: info:    ✌️ Sentry loaded
1|public   | 2023-08-19T00:03:12: info:    ✌️ DB loaded
1|public   | 2023-08-19T00:03:12: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-08-19T00:03:16: info:    ✌️ DB loaded
2|panel    | 2023-08-19T00:03:16: info:    ✌️ Init file down
2|panel    | 2023-08-19T00:03:16: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/api/system.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/api/index.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/loaders/express.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/loaders/app.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/app.js
2|panel    | 2023-08-19T00:03:19:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2|panel    | 2023-08-19T00:03:19:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-08-19T00:03:19:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-08-19T00:03:19:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2|panel    | 2023-08-19T00:03:19:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2|panel    | 2023-08-19T00:03:19:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2|panel    | 2023-08-19T00:03:19:     at Module.load (node:internal/modules/cjs/loader:1119:32)
2|panel    | 2023-08-19T00:03:19:     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
2|panel    | 2023-08-19T00:03:19:     at Module.require (node:internal/modules/cjs/loader:1143:19)
2|panel    | 2023-08-19T00:03:19:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)
```

### Any additional comments?

ng it
PM2        | 2023-08-19T00:03:09: PM2 log: Stopping app:panel id:2
PM2        | 2023-08-19T00:03:09: PM2 log: App [panel:2] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-19T00:03:09: PM2 log: pid=3909 msg=process killed
PM2        | 2023-08-19T00:03:09: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-08-19T00:03:12: PM2 log: App [public:1] online
PM2        | 2023-08-19T00:03:19: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-08-19T00:03:08: debug:   ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-08-19T00:03:08: info:    ✌️ Sentry loaded
1|public   | 2023-08-19T00:03:12: info:    ✌️ DB loaded
1|public   | 2023-08-19T00:03:12: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-08-19T00:03:16: info:    ✌️ DB loaded
2|panel    | 2023-08-19T00:03:16: info:    ✌️ Init file down
2|panel    | 2023-08-19T00:03:16: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/api/system.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/api/index.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/loaders/express.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/loaders/app.js
2|panel    | 2023-08-19T00:03:19: - /ql/static/build/app.js
2|panel    | 2023-08-19T00:03:19:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2|panel    | 2023-08-19T00:03:19:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-08-19T00:03:19:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-08-19T00:03:19:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2|panel    | 2023-08-19T00:03:19:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2|panel    | 2023-08-19T00:03:19:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2|panel    | 2023-08-19T00:03:19:     at Module.load (node:internal/modules/cjs/loader:1119:32)
2|panel    | 2023-08-19T00:03:19:     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
2|panel    | 2023-08-19T00:03:19:     at Module.require (node:internal/modules/cjs/loader:1143:19)
2|panel    | 2023-08-19T00:03:19:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

**Comment by whyour** [comment]
使用宿主机方式更新下

首先更新镜像，确保更新到了最新版镜像
确保原来映射了 data 目录
使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
