### ISSUE TITLE
无法进入青龙面板

### ISSUE THREAD

**Issue by Jebe66** [whyour/qinglong#2084]
### Qinglong version

1.36.1

### Steps to reproduce

root@qinglong:/ql $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-08-19T20:19:11: PM2 log: App [schedule:0] online
PM2        | 2023-08-19T20:19:12: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-08-19T20:19:12: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-08-19T20:19:16: PM2 log: App [schedule:0] online
PM2        | 2023-08-19T20:19:18: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-08-19T20:19:18: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-08-19T20:19:22: PM2 log: App [schedule:0] online
PM2        | 2023-08-19T20:19:23: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-08-19T20:19:23: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-08-19T20:19:28: PM2 log: App [schedule:0] online
PM2        | 2023-08-19T20:19:29: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-08-19T20:19:29: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-08-19T20:19:33: PM2 log: App [schedule:0] online
PM2        | 2023-08-19T20:19:35: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-08-19T20:19:35: PM2 log: App [schedule:0] starting in -fork mode-

/root/.pm2/logs/schedule-out.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-08-19T20:06:02: info:    ✌️ Sentry loaded
1|public   | 2023-08-19T20:06:05: info:    ✌️ DB loaded
1|public   | 2023-08-19T20:06:05: debug:   ✌️ 公共服务启动成功！
1|public   | 2023-08-19T20:17:32: info:    ✌️ Sentry loaded
1|public   | 2023-08-19T20:17:36: info:    ✌️ DB loaded
1|public   | 2023-08-19T20:17:36: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-08-19T20:06:12: info:    ✌️ DB loaded
2|panel    | 2023-08-19T20:06:12: info:    ✌️ Init file down
2|panel    | 2023-08-19T20:06:13: info:    ✌️ Sentry loaded
2|panel    | 2023-08-19T20:06:16: info:    ✌️ Dependency Injector loaded
2|panel    | 2023-08-19T20:06:16: [HPM] Proxy created: /  -> http://localhost:5400/api
2|panel    | 2023-08-19T20:06:16: [HPM] Proxy rewrite rule created: "/api/public" ~> ""
2|panel    | 2023-08-19T20:06:17: info:    ✌️ Express loaded
2|panel    | 2023-08-19T20:17:43: info:    ✌️ DB loaded
2|panel    | 2023-08-19T20:17:43: info:    ✌️ Init file down
2|panel    | 2023-08-19T20:17:44: info:    ✌️ Sentry loaded
2|panel    | 2023-08-19T20:17:48: info:    ✌️ Dependency Injector loaded
2|panel    | 2023-08-19T20:17:48: [HPM] Proxy created: /  -> http://localhost:5400/api
2|panel    | 2023-08-19T20:17:48: [HPM] Proxy rewrite rule created: "/api/public" ~> ""
2|panel    | 2023-08-19T20:17:48: info:    ✌️ Express loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-08-19T20:17:49:  {
2|panel    | 2023-08-19T20:17:49:   code: 14,
2|panel    | 2023-08-19T20:17:49:   details: 'Name resolution failed for target dns:localhost:5500',
2|panel    | 2023-08-19T20:17:49:   metadata: Metadata { internalRepr: Map(0) {}, options: {} }
2|panel    | 2023-08-19T20:17:49: }
2|panel    | 2023-08-19T20:17:49: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2|panel    | 2023-08-19T20:17:49: Error: 14 UNAVAILABLE: Name resolution failed for target dns:localhost:5500
2|panel    | 2023-08-19T20:17:49:     at callErrorFromStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/call.ts:81:17)
2|panel    | 2023-08-19T20:17:49:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/client.ts:356:55)
2|panel    | 2023-08-19T20:17:49:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
2|panel    | 2023-08-19T20:17:49:     at Object.onReceiveStatus (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
2|panel    | 2023-08-19T20:17:49:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
2|panel    | 2023-08-19T20:17:49:     at processTicksAndRejections (node:internal/process/task_queues:77:11)
2|panel    | 2023-08-19T20:17:49: for call at
2|panel    | 2023-08-19T20:17:49:

/root/.pm2/logs/schedule-error.log last 15 lines:
0|schedule | 2023-08-19T20:19:12: Error: Name resolution failed for target dns:localhost:5500
0|schedule | 2023-08-19T20:19:12:     at Object.onError (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server.ts:613:26)
0|schedule | 2023-08-19T20:19:12:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/resolver-dns.ts:258:25
0|schedule | 2023-08-19T20:19:18: Error: Name resolution failed for target dns:localhost:5500
0|schedule | 2023-08-19T20:19:18:     at Object.onError (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server.ts:613:26)
0|schedule | 2023-08-19T20:19:18:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/resolver-dns.ts:258:25
0|schedule | 2023-08-19T20:19:23: Error: Name resolution failed for target dns:localhost:5500
0|schedule | 2023-08-19T20:19:23:     at Object.onError (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server.ts:613:26)
0|schedule | 2023-08-19T20:19:23:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/resolver-dns.ts:258:25
0|schedule | 2023-08-19T20:19:29: Error: Name resolution failed for target dns:localhost:5500
0|schedule | 2023-08-19T20:19:29:     at Object.onError (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server.ts:613:26)
0|schedule | 2023-08-19T20:19:29:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/resolver-dns.ts:258:25
0|schedule | 2023-08-19T20:19:35: Error: Name resolution failed for target dns:localhost:5500
0|schedule | 2023-08-19T20:19:35:     at Object.onError (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server.ts:613:26)
0|schedule | 2023-08-19T20:19:35:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/resolver-dns.ts:258:25

PM2      | App [schedule:0] online
0|schedule  | 2023-08-19T20:19:40: Error: Name resolution failed for target dns:localhost:5500
0|schedule  | 2023-08-19T20:19:40:     at Object.onError (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server.ts:613:26)
0|schedule  | 2023-08-19T20:19:40:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/resolver-dns.ts:258:25
PM2         | App [schedule:0] exited with code [1] via signal [SIGINT]
PM2         | App [schedule:0] starting in -fork mode-
PM2         | App [schedule:0] online
0|schedule  | 2023-08-19T20:19:46: Error: Name resolution failed for target dns:localhost:5500
0|schedule  | 2023-08-19T20:19:46:     at Object.onError (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server.ts:613:26)
0|schedule  | 2023-08-19T20:19:46:     at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/resolver-dns.ts:258:25
PM2         | App [schedule:0] exited with code [1] via signal [SIGINT]
PM2         | App [schedule:0] starting in -fork mode-
PM2         | App [schedule:0] online

### What is expected?

解决方法

### What is actually happening?

无法进入青龙面板

**Comment by wwxMan** [comment]
好像是 cdn.jsdelivr.net  这个玩意挂掉了，导致前端的一些js拿不到

**Comment by wwxMan** [comment]
windows 下 修改本机hosts 文件追加域名映射

**Comment by whyour** [comment]
你这是 hosts 没有 localhost 解析，增加下 localhost 127.0.0.1 的解析就行
