### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by hgq5** [whyour/qinglong#2085]
### Qinglong version

2.15.20

### Steps to reproduce

开始检测依赖...

安装 /ql/.tmp/qinglong-master 依赖包...

 Unknown system error -117  Unknown system error -117: Unknown system error -117, stat '/root/.local/share/pnpm/store/v3/files/de/1d87dab80f9b61e4f89997da1c88cd8bb01545d453edfe847296ead6deb440d1b278857507b907c730b6fa57ffb49587ed203f5356fcdb328cb16611891d6e'

依赖检测安装失败，请检查网络...

### What is expected?

no expected

### What is actually happening?

一直更新失败，ql check也无法修复，在安装新的nodejs依赖时也会出错无法安装。

**Comment by whyour** [comment]
使用宿主机方式更新下

首先更新镜像，确保更新到了最新版镜像
确保原来映射了 data 目录
使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新

**Comment by hgq5** [comment]
我最后把容器重新安装过了，后来分析可能是放容器的U盘有问题导致的，更新版本不行，依赖明明安装了却一直提示未安装。
