### ISSUE TITLE
经过测试 notify.py企业微信的调用还是存在问题

### ISSUE THREAD

**Issue by nsv2051** [whyour/qinglong#2086]
### Qinglong version

2.16.1

### Steps to reproduce

调用notify.py发送消息，其他通道正常，企业微信应用消息无法推送，好像是代理地址这一块有问题，我的应用建立时间比较早，不需要代理也能推送

### What is expected?

应该是正常推送，在2.15版本的时候应该没出现过这个问题

### What is actually happening?

企业微信 APP 服务启动
Exception in thread wecom_app:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/data/scripts/share/notify.py", line 417, in wecom_app
    response = wx.send_mpnews(title, content, media_id, touser)
  File "/ql/data/scripts/share/notify.py", line 459, in send_mpnews
    send_url = f"https://{self.ORIGIN}/cgi-bin/message/send?access_token={self.get_access_token()}"
  File "/ql/data/scripts/share/notify.py", line 440, in get_access_token
    req = requests.post(url, params=values)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '127.0.0.1/cgi-bin/gettoken': No scheme supplied. Perhaps you meant http://127.0.0.1/cgi-bin/gettoken?

### System Info

```shell
Need to install the following packages:
envinfo@7.10.0
Ok to proceed? (y) 

  System:
    OS: Linux 5.4 Alpine Linux
    CPU: (4) x64 Intel(R) Celeron(R) CPU N3450 @ 1.10GHz
    Memory: 4.88 GB / 7.62 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.17.0 - /usr/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
  Browsers:
    Chromium: 115.0.5790.170
```

**Comment by nsv2051** [comment]
> QYWX_ORIGIN 要以http开头，你这咋配置的，不需要就把变量删掉

![image](https://github.com/whyour/qinglong/assets/39900381/5fb92ff0-02d9-44ac-8d34-c6ccd3a87362)
![image](https://github.com/whyour/qinglong/assets/39900381/c44949a7-c894-49e1-b7eb-7f1a40059ada)
这是配置及运行结果，附上测试代码
https://gist.githubusercontent.com/nsv2051/6d5cb33390e9f8b77aef54bdfe2d16a9/raw/bfd44744d81905d833f72e1903fdef03f6a48166/notify_demo.py

**Comment by nsv2051** [comment]
![image](https://github.com/whyour/qinglong/assets/39900381/a359aad6-792f-4bc7-81ab-c61266acd5ee)
这是注释掉变量后的推送日志

**Comment by nsv2051** [comment]
`class WeCom:
    def __init__(self, corpid, corpsecret, agentid):
        self.CORPID = corpid
        self.CORPSECRET = corpsecret
        self.AGENTID = agentid
        self.ORIGIN = "https://qyapi.weixin.qq.com"
        if push_config.get("QYWX_ORIGIN"):
            self.ORIGIN = push_config.get("QYWX_ORIGIN")

    def get_access_token(self):
        url = f"{self.ORIGIN}/cgi-bin/gettoken"
        values = {
            "corpid": self.CORPID,
            "corpsecret": self.CORPSECRET,
        }
        req = requests.post(url, params=values)
        data = json.loads(req.text)
        return data["access_token"]

    def send_text(self, message, touser="@all"):
        send_url = f"{self.ORIGIN}/cgi-bin/message/send?access_token={self.get_access_token()}"
        send_values = {
            "touser": touser,
            "msgtype": "text",
            "agentid": self.AGENTID,
            "text": {"content": message},
            "safe": "0",
        }
        send_msges = bytes(json.dumps(send_values), "utf-8")
        respone = requests.post(send_url, send_msges)
        respone = respone.json()
        return respone["errmsg"]

    def send_mpnews(self, title, message, media_id, touser="@all"):
        send_url = f"https://{self.ORIGIN}/cgi-bin/message/send?access_token={self.get_access_token()}"
        send_values = {
            "touser": touser,
            "msgtype": "mpnews",
            "agentid": self.AGENTID,
            "mpnews": {
                "articles": [
                    {
                        "title": title,
                        "thumb_media_id": media_id,
                        "author": "Author",
                        "content_source_url": "",
                        "content": message.replace("\n", "<br/>"),
                        "digest": message,
                    }
                ]
            },
        }
        send_msges = bytes(json.dumps(send_values), "utf-8")
        respone = requests.post(send_url, send_msges)
        respone = respone.json()
        return respone["errmsg"]`
问题可能在这一段，我把5月份的notify.py文件同一位置的代码替换过来后就可以推送了
![image](https://github.com/whyour/qinglong/assets/39900381/221a6eb3-c834-4282-a871-8eb21636dc2a)

**Comment by whyour** [comment]
环境变量有缓存，重启下应该就行了

**Comment by nsv2051** [comment]
找到问题了，notify.py文件第459行多写了一个前缀
![image](https://github.com/whyour/qinglong/assets/39900381/834c67ce-2832-4dca-b3f2-3c2a3f5a64e9)

**Comment by whyour** [comment]
@nsv2051 pr is welcoming 😌

**Comment by nsv2051** [comment]
问题已解决

**Comment by binge8** [comment]
![屏幕截图 2024-12-02 173037](https://github.com/user-attachments/assets/f8fcc82f-fe8c-443e-a6dd-cda36f4dbce9)
![屏幕截图 2024-12-02 173214](https://github.com/user-attachments/assets/1283402f-6b95-42d7-bf81-8a1f498699a6)
我这个怎么还不对，设置好像没问题啊 @nsv2051
