### ISSUE TITLE
SequelizeUniqueConstraintError Validation error

### ISSUE THREAD

**Issue by LYC-axiba** [whyour/qinglong#2089]
### Qinglong version

v2.16.1

### Steps to reproduce

SequelizeUniqueConstraintError Validation error

### What is expected?

SequelizeUniqueConstraintError Validation error

### What is actually happening?

SequelizeUniqueConstraintError Validation error

### System Info

```shell
SequelizeUniqueConstraintError Validation error
```

**Comment by whyour** [comment]
资源重复
