### ISSUE TITLE
用latest拉取的版本为什么不是最新的，而一直是v2.10.13?

### ISSUE THREAD

**Issue by wifisky-feilian** [whyour/qinglong#2090]
### Qinglong version

latest

### Steps to reproduce

docker run -dit \
  -v /Volume1/public/Docker/ql/data:/ql/data \
  -p 5700:5700 \
  -e QlBaseUrl="/" \
  --name qinglong \
  --hostname qinglong \
  --restart always \
  whyour/qinglong:latest

用latest拉取的版本为什么不是最新的，而一直是v2.10.13?

### What is expected?

docker run -dit \
  -v /Volume1/public/Docker/ql/data:/ql/data \
  -p 5700:5700 \
  -e QlBaseUrl="/" \
  --name qinglong \
  --hostname qinglong \
  --restart always \
  whyour/qinglong:latest

用latest拉取的版本为什么不是最新的，而一直是v2.10.13?

### What is actually happening?

docker run -dit \
  -v /Volume1/public/Docker/ql/data:/ql/data \
  -p 5700:5700 \
  -e QlBaseUrl="/" \
  --name qinglong \
  --hostname qinglong \
  --restart always \
  whyour/qinglong:latest

用latest拉取的版本为什么不是最新的，而一直是v2.10.13?

**Comment by whyour** [comment]
docker 的镜像源有问题

**Comment by hcliu987** [comment]
什么源有，我现在用默认源还是这个版本。不想用这个版本

**Comment by whyour** [comment]
> 什么源有，我现在用默认源还是这个版本。不想用这个版本

docker 的镜像源不要配置，然后重启 docker

**Comment by hcliu987** [comment]
收到，已经更新

whyour ***@***.***> 于2023年8月29日周二 22:00写道：
