### ISSUE TITLE
无法通过API获取任务列表

### ISSUE THREAD

**Issue by Airpy** [whyour/qinglong#2094]
### Qinglong version

2.16.1

### Steps to reproduce

```python
def get_all_crons(headers: Dict):
    """
    获取所有任务详情
    """
    url = 'http://10.241.xxx.xxx:5700/open/crons'
    # all_crons = requests.get(url, headers=headers).json()
    response = requests.get(url, headers=headers)
    logger.error(f'headers: {response.request.headers}')
    all_crons = response.json()
```
调用以上函数，headers传入{'Authorization': 'Bearer xxx481e-ba1f-51491f6feedd'}

发现获取环境变量列表可以，但获取crons列表不行，提示{'code': 401, 'message': 'jwt malformed'}

### What is expected?

能获取到任务列表

### What is actually happening?

<img width="1047" alt="image" src="https://github.com/whyour/qinglong/assets/20046478/214b0762-5816-443f-920a-283077e541a2">

**Comment by whyour** [comment]
系统设置里的应用没添加定时任务权限吧

**Comment by Airpy** [comment]
> 系统设置里的应用没添加定时任务权限吧

像是，不过我后来workaround解决了，直接取auth.json中的token来调用就可以
