### ISSUE TITLE
python代码中怎么调用ts中的方法

### ISSUE THREAD

**Issue by zuozihan** [whyour/qinglong#2095]
### Clear and concise description of the problem

python程序登录状态过期了，我想给它禁用掉

### Suggested solution

![image](https://github.com/whyour/qinglong/assets/45542784/7d5eacb5-20a2-492d-9ee5-606a300702f6)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
系统设置里有应用，可以使用 openapi 禁用 https://t.me/jiao_long/166
