### ISSUE TITLE
期待能在cron里面强行定义环境变量

### ISSUE THREAD

**Issue by wudongdefeng** [whyour/qinglong#2096]
### Clear and concise description of the problem

比如变量1，有两个活动A，和B两个长期活动，但是在环境变量中只能设置一个，我想让两个变量分开跑，脚本是加密的，改不了

### Suggested solution

task a.js 变量1=A

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
export 变量1=A && task a.js 可以实现

**Comment by whyour** [comment]
> 从哪个版本开始支持这个功能，我刚刚试了还是读的config.sh

要写到运行命令哪里，为什么还要写到 config.sh 呢

**Comment by wudongdefeng** [comment]
> 后面可能加个和订阅那里一样的参数，任务运行前和任务运行后。现在是有个统一的 task_before, 你可以把你的环境变量写到 task_before.sh 里

这样达不到想要的效果，我想设置多个变量
