### ISSUE TITLE
vps 服务器启动成功以后，登录会自动跳转到带error的地址是什么原因

### ISSUE THREAD

**Issue by rayyzt** [whyour/qinglong#2098]
### Qinglong version

latest

### Steps to reproduce

如题

### What is expected?

如题

### What is actually happening?

如题

**Comment by whyour** [comment]
成功后等待下 docker ps，看容器状态是 healthy 后 再访问，多刷新几次

**Comment by rayyzt** [comment]
我用的是宝塔面板自带的docker，可能是宝塔图形化设置的问题，用命令行以后就可以进入初始化界面了

whyour ***@***.***> 于 2023年9月2日周六 上午11:46写道：
