### ISSUE TITLE
语言更改不了

### ISSUE THREAD

**Issue by davidloman** [whyour/qinglong#2101]
### Qinglong version

v2.16.2

### Steps to reproduce

System Settings --> Other Settings --> Language --> 简体中文

### What is expected?

the interface will be changed to 简体中文

### What is actually happening?

still in English

### System Info

```shell
root@b0b6d72d08ba:/ql $ npx envinfo --system --binaries --browsers

  System:
    OS: Linux 6.2 Alpine Linux
    CPU: (8) x64 Intel(R) Core(TM) i3-N305
    Memory: 5.39 GB / 7.66 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    npm: 9.6.6 - /usr/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
```

### Any additional comments?

I did a fresh install but I couldn't switch languages on the current system while the upgrade from 2.16.1 to 2.16.2 has no problem on my other system.

**Comment by whyour** [comment]
无法复现，什么浏览器
