### ISSUE TITLE
青龙数据备份找不到备份在哪里了

### ISSUE THREAD

**Issue by happyman6776** [whyour/qinglong#2104]
### Qinglong version

v2.15.20

### Steps to reproduce

在青龙-系统设置-其他设置-备份，点击备份，提示备份下载成功。但找不到i备份到哪里了？系统浏览器默认设置下也没有找到备份文件。多次尝试，都无法找到这个数据备份，请指示一下，这个数据备份到底在哪里呢？这个数据备份的文件名是什么呢？

### What is expected?

能提示我找到这个备份数据文件，同时希望能能够自定义备份数据文件路径。

### What is actually happening?

在青龙-系统设置-其他设置-备份，点击备份，提示备份下载成功。但找不到i备份到哪里了？系统浏览器默认设置下也没有找到备份文件。多次尝试，都无法找到这个数据备份。

**Comment by jswxll** [comment]
我也有遇到过，提示备份下载成功，但浏览器并未弹出下载提示（另外一台机器会弹出下载文件），备份文件名是data.tgz，路径在ql/data/下、或者ql/data/bak/下，具体记得不是很清楚了~
另外：你的系统设置--关于页面有正常显示吗？

**Comment by whyour** [comment]
推荐用 chrome
