### ISSUE TITLE
PM2服务出问题

### ISSUE THREAD

**Issue by Alphas-1** [whyour/qinglong#2105]
### Qinglong version

2.16.2

### Steps to reproduce

[PM2] Spawning PM2 daemon with pm2_home=/home/.pm2
[PM2] PM2 Successfully daemonized
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/.pm2/pm2.log last 15 lines:
PM2        | 2023-09-06T11:01:00: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2023-09-06T11:01:00: PM2 log: Time                 : Wed Sep 06 2023 11:01:00 GMT+0800 (GMT+08:00)
PM2        | 2023-09-06T11:01:00: PM2 log: PM2 version          : 5.3.0
PM2        | 2023-09-06T11:01:00: PM2 log: Node.js version      : 18.17.1
PM2        | 2023-09-06T11:01:00: PM2 log: Current arch         : arm64
PM2        | 2023-09-06T11:01:00: PM2 log: PM2 home             : /home/.pm2
PM2        | 2023-09-06T11:01:00: PM2 log: PM2 PID file         : /home/.pm2/pm2.pid
PM2        | 2023-09-06T11:01:00: PM2 log: RPC socket file      : /home/.pm2/rpc.sock
PM2        | 2023-09-06T11:01:00: PM2 log: BUS socket file      : /home/.pm2/pub.sock
PM2        | 2023-09-06T11:01:00: PM2 log: Application log path : /home/.pm2/logs
PM2        | 2023-09-06T11:01:00: PM2 log: Worker Interval      : 30000
PM2        | 2023-09-06T11:01:00: PM2 log: Process dump file    : /home/.pm2/dump.pm2
PM2        | 2023-09-06T11:01:00: PM2 log: Concurrent actions   : 2
PM2        | 2023-09-06T11:01:00: PM2 log: SIGTERM timeout      : 1600
PM2        | 2023-09-06T11:01:00: PM2 log: ===============================================================================

### What is expected?

请大佬帮忙看看这是咋回事啊，以前同一个手机安装的青龙面板还能打开，现在不行了

### What is actually happening?

按步骤拉官网的镜像后，青龙就是pm2服务里的三个板块panel,schedule,总有两个显示launching,然后就打不开

### System Info

```shell
小米8青春版 安卓版本：10
```

### Any additional comments?

联系方式：2827841187@qq.com

**Comment by Alphas-1** [comment]
![126646D5B24A172DA6FC14C0D1649AB4](https://github.com/whyour/qinglong/assets/104542458/70e57a48-b42d-4d15-98da-d0d0539e9fbc)
打开就会这样，有两个一直在lauching,浏览器进入就显示error

**Comment by Alphas-1** [comment]
![C60680BA9CD0EF0359EF8C20DA73A3C8](https://github.com/whyour/qinglong/assets/104542458/d3759ada-b664-464f-82bf-7a164a2e10d2)
我的是zerotermux装了alpine,再拉的青龙面板2.16.2

**Comment by Alphas-1** [comment]
[root@localhost ~]# qinglong
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
======================2. 安装依赖========================

Writing to /home/.config/pip/pip.conf

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动pm2服务========================

[PM2][WARN] Applications schedule, public, panel not running, starting...
[PM2][WARN] App schedule has option 'wait_ready' set, waiting for app to be ready...
[PM2][WARN] App public has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [schedule] launched (1 instances)
[PM2][WARN] App panel has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [public] launched (1 instances)
[PM2] App [panel] launched (1 instances)
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 2  │ panel              │ fork     │ 1    │ launching │ 0%       │ 0b       │
│ 1  │ public             │ fork     │ 0    │ online    │ 31.1%    │ 82.5mb   │
│ 0  │ schedule           │ fork     │ 2    │ launching │ 0%       │ 0b       │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
====================6. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...
############################################################

**Comment by Alphas-1** [comment]
![718520B48930A5C32CB3D3C17529F62A](https://github.com/whyour/qinglong/assets/104542458/b3161955-c68b-4bef-a468-3d3ff5a56c4e)
检测结果我看不懂，求大神指教

**Comment by wintsa123** [comment]
pm2只是个监听线程的软件，你看看node能不能运行先，能运行再看看pm2的配置文件

**Comment by Alphas-1** [comment]
> 

node能不能运行在哪看呀

**Comment by Alphas-1** [comment]
大佬，请问node能不能运行怎么看啊，我是下了个zerotermux跟着别人的教程搞的青龙，第一次运行成功了，后来重装就怎么也不成功，网站：shell - 手机termux安装Linux发行版实现无root安装青龙面板 - 个人文章 - SegmentFault 思否






Alphas
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whyour/qinglong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 下午4:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whyour/qinglong] PM2服务出问题 (Issue #2105)





 
pm2只是个监听线程的软件，你看看node能不能运行先，能运行再看看pm2的配置文件

**Comment by wintsa123** [comment]
> 大佬，请问node能不能运行怎么看啊，我是下了个zerotermux跟着别人的教程搞的青龙，第一次运行成功了，后来重装就怎么也不成功，网站：shell - 手机termux安装Linux发行版实现无root安装青龙面板 - 个人文章 - SegmentFault 思否 Alphas ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "whyour/qinglong" ***@***.***&gt;; 发送时间:&nbsp;2023年9月11日(星期一) 下午4:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [whyour/qinglong] PM2服务出问题 (Issue #2105) pm2只是个监听线程的软件，你看看node能不能运行先，能运行再看看pm2的配置文件 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

直接node /xxx/xxx/xxx.index （替换地址和文件名）

**Comment by whyour** [comment]
pm2 logs 看看没启动成功的原因，估计有些依赖没安装？
