### ISSUE TITLE
【邮箱通知BUG】设置邮箱方式进行通知，一直错误

### ISSUE THREAD

**Issue by carolcoral** [whyour/qinglong#2106]
### Qinglong version

2.16.2

### Steps to reproduce

1. 安装页面选择“邮箱”方式进行通知，尝试了QQ、Gmail、Aliyun都提示错误（以上邮箱的SMTP均在本地foxmail配置成功）
2. 跳过通知设置后在系统页面的“配置”里面手动填写了邮箱相关的内容，再次进行配置，依然存在问题

### What is expected?

设置邮箱方式进行通知，一直错误

### What is actually happening?

设置邮箱方式进行通知，一直错误
建议：通知里面选择邮箱通知的话，开放自定义smtp地址、端口、ssl设置、帐号等配置，而不是单纯的通过别名去控制
PS：邮箱通知里面的“可用列表”网址已经404了（https://nodemailer.com/smtp/well-knows）

**Comment by carolcoral** [comment]
> 密码配置的是 smtp 授权码

阿里云的企业邮箱使用的是密码，目前QQ邮箱才是SMTP的授权码

**Comment by whyour** [comment]
> > 密码配置的是 smtp 授权码
> 
> 阿里云的企业邮箱使用的是密码，目前QQ邮箱才是SMTP的授权码

126 也是授权码，这块你知道有相关的规范吗，你阿里云的测试通了吗

**Comment by carolcoral** [comment]
> > > 密码配置的是 smtp 授权码
> > 
> > 
> > 阿里云的企业邮箱使用的是密码，目前QQ邮箱才是SMTP的授权码
> 
> 126 也是授权码，这块你知道有相关的规范吗，你阿里云的测试通了吗

阿里云的测试通过了：

**Comment by carolcoral** [comment]
> > > 密码配置的是 smtp 授权码
> > 
> > 
> > 阿里云的企业邮箱使用的是密码，目前QQ邮箱才是SMTP的授权码
> 
> 126 也是授权码，这块你知道有相关的规范吗，你阿里云的测试通了吗

阿里云邮件通知方式配置经过测试已经通过并正在使用的有：

1. 群晖DSM7中的邮件告警通知
2. foxmail中的邮件同步收发
3. 1panel面板中的邮件通知
4. halo.run 博客系统中邮件通知
5. twikoo 评论系统中邮件通知

以上方式均经过我本人测试通过配置并且已经正在使用中，所以你说到底是谁的原因

**Comment by carolcoral** [comment]
> > > 密码配置的是 smtp 授权码
> > 
> > 
> > 阿里云的企业邮箱使用的是密码，目前QQ邮箱才是SMTP的授权码
> 
> 126 也是授权码，这块你知道有相关的规范吗，你阿里云的测试通了吗

qq和126可能是使用的授权码方式进行配置，但是我确认企业阿里云邮箱确实是通过`账户-密码`方式进行配置，并且该配置方式已经经过多种方式进行验证和使用
