### ISSUE TITLE
打印不全的BUG

### ISSUE THREAD

**Issue by elin63** [whyour/qinglong#2108]
### Qinglong version

2.16.2

### Steps to reproduce

console.log('1')
console.log('2')
console.log('3')
console.log('4')
console.log('5')
console.log('6')
console.log('7')
console.log('8')
console.log('9')
console.log('10')
console.log('11')
console.log('12')
console.log('13')

## 开始执行... 2023-09-08 13:49:21

1

12
13

### What is expected?

需要打印出所有信息

### What is actually happening?

2.13.8版本开始不能打印出所有信息

**Comment by whyour** [comment]
http://demo.dlww.cc:4433/crontab  demo 环境有示例，可以打印完整
