### ISSUE TITLE
启动bot的时候提示Username for 'https://ghproxy.com':

### ISSUE THREAD

**Issue by ryuurin** [whyour/qinglong#211]
![image](https://user-images.githubusercontent.com/42639499/120076071-7564b280-c0d6-11eb-8cef-cd7872a9f635.png)
这个输什么啊

**Comment by kuilei0926** [comment]
作者删库了，https://github.com/lxrcbw/jddockerbot/tree/master这边有个备份

**Comment by kuilei0926** [comment]
> 作者删库了，[https://github.com/lxrcbw/jddockerbot/tree/master] 这边有个备份(https://github.com/lxrcbw/jddockerbot/tree/master)

**Comment by kuilei0926** [comment]
作者删库了，https://github.com/lxrcbw/jddockerbot/tree/master 这边有个备份
