### ISSUE TITLE
如何通过代码更改环境变量的值

### ISSUE THREAD

**Issue by whobye** [whyour/qinglong#2110]
### Clear and concise description of the problem

我用青龙运行了一个python脚本，里面用到了set集合，但因为脚本是通过cron来控制运行计划的，这样每次运行完脚本后set集合就自动被清空了，如何使集合里的变量永久的保存下来

### Suggested solution

os.environ["CODES"] = ",".join(codes)
通过代码写入不进去

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
你可以写入文件或者通过 openapi 写入环境变量
