### ISSUE TITLE
python3环境依赖torch安装失败

### ISSUE THREAD

**Issue by shixiangkuangmo** [whyour/qinglong#2113]
### Qinglong version

正式版 v2.16.0

### Steps to reproduce

安装python3依赖 torch

### What is expected?

修复问题

### What is actually happening?

python3环境依赖torch安装失败

### System Info
开始安装依赖 torch，开始时间 2023-09-14 09:17:16

ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

依赖安装失败，结束时间 2023-09-14 09:17:17，耗时 1 秒
_No response_

**Comment by whyour** [comment]
你提供的日志显示没有这个依赖，具体可以查询 alpine 如何安装 torch
