### ISSUE TITLE
磁盘IO异常

### ISSUE THREAD

**Issue by zhaoguomanong** [whyour/qinglong#2116]
### Qinglong version

latest

### Steps to reproduce

拉取最新的docker qinglong镜像并启动一个空的容器(什么脚本和订阅都不添加)

运行22小时左右:
![image](https://github.com/whyour/qinglong/assets/7934431/d90eec96-3409-4bed-84b8-4af560cb1dd2)

使用docker stats观察磁盘IO使用情况:

![image](https://github.com/whyour/qinglong/assets/7934431/f5583af7-5ebb-4e4d-97d3-033c2f0ebb97)

在没有跑任何脚本的情况下写入磁盘2GB, 读取磁盘3GB

麻烦帮修一下吧，我现在跑脚本https://github.com/shufflewzc/faker2 基本一天磁盘读写50GB兜底。 一般硬盘根本吃不消这么搞。 虽然没占用空间，但是读写量可以用docker stats 看出来，并且通过硬盘的S.M.A.R.T 信息也能计算出来。

### What is expected?

磁盘IO 正常, 不要出现疯狂读写磁盘

### What is actually happening?

跑脚本基本一天50GB+的读写量， 空跑容器读写2-3GB左右

**Comment by zhqu1148980644** [comment]
同样的问题，服务器十多个docker容器，就尼玛这个容器离谱，周期性的大量读写磁盘，开始还以为是我添加了很多脚本的原因

**Comment by zhaoguomanong** [comment]
你docker ps 看下运行多久了？ 我之前运行14天读写400-500GB

> 同样的问题，服务器十多个docker容器，就尼玛这个容器离谱，周期性的大量读写磁盘，开始还以为是我添加了很多脚本的原因。 下面为5天的磁盘读写。 <img alt="image" width="733" src="https://user-images.githubusercontent.com/29366130/268176964-f4223f05-fd16-495f-ad22-497690b66d29.png">

最新版本更离谱，我14天读写差不多500GB左右，你是不是用的老版本，你的写入量1.39GB还算可以。

如果是用ssd 读取还好，写入太多谁也受不了

**Comment by zhaoguomanong** [comment]
2小时前刚新建的容器，已经给我写了6GB+, 难道在下视频？ 什么样的需求需要写入这么大的数据量：

![image](https://github.com/whyour/qinglong/assets/7934431/ea924f34-07b1-4332-a2e7-50b86bf2a084)


![image](https://github.com/whyour/qinglong/assets/7934431/2dde83c2-826c-436a-901c-0cdabbe4815d)

**Comment by zhqu1148980644** [comment]
傻逼作者，你他妈的随便关issue是吧

**Comment by zhaoguomanong** [comment]
问题没解决居然关闭issue? 难道真的在后台挖矿？ 一天几十上百GB的磁盘读写不是bug?

**Comment by zhqu1148980644** [comment]
贴另一个强制收集用户数据的issue，也无缘无故就关闭了。https://github.com/whyour/qinglong/issues/2115

**Comment by zhaoguomanong** [comment]
> 贴另一个强制收集用户数据的issue，也无缘无故就关闭了。#2115

关闭总得给个理由吧， 这随便关闭问题，你还不如直接不要开issues这个功能。

**Comment by zhaoguomanong** [comment]
现在只能回退旧版本了, v2.11.3 测试了几个小时没问题

**Comment by zhaoguomanong** [comment]
> > 这作者要么不是技术有问题就是人品有问题，我准备寻找替代了，这种B玩意恶心到爆。
> 
> 可以直接回退到2.15.16 试试，跑了几个脚本基本正常，不再疯狂写盘了，问题大概出在2.15.16到2.15.18之间，因为我7.16日升级过一次，那时候已经不正常了。

更正, 2.15.16也有问题，跑一晚上[faker2](https://github.com/shufflewzc/faker2) 写盘2GB+, 
现在直接参考
https://github.com/whyour/qinglong/issues/1561

回退到2.13.3版本。 

跑几天看看

**Comment by abedormancy** [comment]
> > > 这作者要么不是技术有问题就是人品有问题，我准备寻找替代了，这种B玩意恶心到爆。
> > 
> > 
> > 可以直接回退到2.15.16 试试，跑了几个脚本基本正常，不再疯狂写盘了，问题大概出在2.15.16到2.15.18之间，因为我7.16日升级过一次，那时候已经不正常了。
> 
> 更正, 2.15.16也有问题，跑一晚上[faker2](https://github.com/shufflewzc/faker2) 写盘2GB+,
> 
> 回退到2.11.3版本。
> 
> 跑几天看看

请问现在啥情况了 ，这玩意任务没跑也很吃cpu，奇奇怪怪的。而且这磁盘写入量确实有点哈人，就是因为遇到这种问题就搜关键字，果然已经有人踩过坑了 。。

**Comment by chux1995** [comment]
我也发现了，我以前买的2t固态，扔电脑跑了一年也没我这两个月跑容器花的读写多，本来12t读写，现在已经写入到24t了，我还纳闷，这nas系统怎么老是读写硬盘，里里外外检查一遍进程，尝试下关闭这个容器就不读写硬盘了。我先停一段时间容器，再观察一下硬盘读写情况。

**Comment by lollipopkit** [comment]
![0035c88bba23faadf4e676b40eadee6d](https://github.com/whyour/qinglong/assets/10864310/eb73043d-f9bb-4dc0-a98d-b53f68ef3d36)

**Comment by KeithW0726** [comment]
现在有测试出哪个版本没这问题吗？我也打算回退了

**Comment by zhaoguomanong** [comment]
我还在用[v2.11.3] 不敢升级了。 用了两周的数据: 


![image](https://github.com/whyour/qinglong/assets/7934431/22d73233-2f42-42b8-9dcf-7ad91ed34964)

![image](https://github.com/whyour/qinglong/assets/7934431/6846f858-1549-4ce6-9f33-d93382859e9f)

**Comment by KeithW0726** [comment]
> 我还在用[v2.11.3] 不敢升级了。 用了两周的数据:
> 
> ![image](https://private-user-images.githubusercontent.com/7934431/309601437-22d73233-2f42-42b8-9dcf-7ad91ed34964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTQ3MTIsIm5iZiI6MTcwOTU1NDQxMiwicGF0aCI6Ii83OTM0NDMxLzMwOTYwMTQzNy0yMmQ3MzIzMy0yZjQyLTQyYjgtOWRjZi03YWQ5MWVkMzQ5NjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTIxMzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ5ZjkyNTc0OTllMDkxYjhlOGMzODBiZjcwYmYwNmVhNDkyZTE4ZTViMjU3NjBkYTNiNGRjNDJmMjAwY2NhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lBKij62qCixByaIDmceFpdkyNDw0yR6ZKzoMe12FfdM)
> 
> ![image](https://private-user-images.githubusercontent.com/7934431/309602012-6846f858-1549-4ce6-9f33-d93382859e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTQ3MTIsIm5iZiI6MTcwOTU1NDQxMiwicGF0aCI6Ii83OTM0NDMxLzMwOTYwMjAxMi02ODQ2Zjg1OC0xNTQ5LTRjZTYtOWYzMy1kOTMzODI4NTllOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTIxMzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk0NTJlZjhhNDYyODdhOTYzMGQxYjUyNzkyNmU5MzUyZTdiNGUwNzE0Yjg2MDRmNGM1MDIyODM2ODQ2M2NjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6titD2AhQVKNVybUSMO8uQ7O-9AjvR7sneIjZ87CmSA)

这个量不小。。。如果你只是纯打卡脚本的话，日志量的磁盘IO吞吐量也太大了。。。

**Comment by xtay573269555** [comment]
是在跑CDN吗？有没有人抓流量检查下

**Comment by karhow** [comment]
同样的问题，有人解决吗？

**Comment by karhow** [comment]
> 我还在用[v2.11.3] 不敢升级了。 用了两周的数据:
> 
> ![image](https://private-user-images.githubusercontent.com/7934431/309601437-22d73233-2f42-42b8-9dcf-7ad91ed34964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3Njg3NDQsIm5iZiI6MTcyOTc2ODQ0NCwicGF0aCI6Ii83OTM0NDMxLzMwOTYwMTQzNy0yMmQ3MzIzMy0yZjQyLTQyYjgtOWRjZi03YWQ5MWVkMzQ5NjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTExNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDlmMTZmODE0ZmE5ZDgxZjA4MGM2NDJiYjZmOTJhMGYyYTdkYjI3ZGRjNzMzNTk5MjNiYTI2NmE4MjZmNDhmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8lf3MsEPsuit-gzf718zPq6Ko1wN-QYHQXC--O0e3ew)
> 
> ![image](https://private-user-images.githubusercontent.com/7934431/309602012-6846f858-1549-4ce6-9f33-d93382859e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3Njg3NDQsIm5iZiI6MTcyOTc2ODQ0NCwicGF0aCI6Ii83OTM0NDMxLzMwOTYwMjAxMi02ODQ2Zjg1OC0xNTQ5LTRjZTYtOWYzMy1kOTMzODI4NTllOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTExNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjJlN2MxMjljYzI4MTUyZjc5ODJjMDYzMWNmZjBkNzk0NzBhNTU3YTY4MThjYjIyZDA4NjdhNWZiMGEwY2M3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vJaLLi6gtFDs52MJoQTZU6fqdmONcRdArHNjndZzH9E)

2.11.3的目录结构和后端的2.17的不一样，你怎么回退的？我也遇到这个io问题，也想回退了
