### ISSUE TITLE
cron中带/ 任务运行一次后，就不会再运行了

### ISSUE THREAD

**Issue by Xiaobooooo** [whyour/qinglong#2119]
### Qinglong version

2.16.2

### Steps to reproduce

系统centos7.6  青龙2.16.2版本
cron中只要带/ 任务运行一次后，就不会在运行了
![1](https://github.com/whyour/qinglong/assets/97510981/aeca68a9-7d55-4e45-a583-8e9c99378578)

### What is expected?

按照cron命令正常运行定时任务

### What is actually happening?

cron中只要带/ 任务运行一次后，就不会再运行了

**Comment by Xiaobooooo** [comment]
/前面添加范围能够正常运行
如 0 1-23/2 * * *
但是 0 1/2 * * * 在老版本是正常运行的，新版本显示的下次运行时间也是正常有的，但是没运行

**Comment by Xiaobooooo** [comment]
/前面添加范围能够正常运行  如 0 1-23/2 * * *
但是 0 1/2 * * * 在老版本是正常运行的，新版本显示的下次运行时间也是正常有的，但是没运行

**Comment by whyour** [comment]
不是标准规则，前面加个秒就行

**Comment by whyour** [comment]
> /前面添加范围能够正常运行 如 0 1-23/2 * * * 但是 0 1/2 * * * 在老版本是正常运行的，新版本显示的下次运行时间也是正常有的，但是没运行

老版本是哪个版本可以运行

**Comment by pooneyy** [comment]
> 不是标准规则，前面加个秒就行

形如
![image](https://github.com/user-attachments/assets/b216cff8-5c4d-4a16-bd2b-1c5e1458a58c)
 这样的也没法正常触发。虽然“下次运行时间”写了下一次触发时间，但是到点后并没有正常触发
