### ISSUE TITLE
执行ql -l check，进不去后台了

### ISSUE THREAD

**Issue by microyin715** [whyour/qinglong#2120]
### Qinglong version

v2.16.2

### Steps to reproduce

root@qinglong:/ql $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-09-19T10:44:33: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-09-19T10:44:33: PM2 log: App [public:1] starting in -fork mode-
PM2        | 2023-09-19T10:44:35: PM2 log: App [schedule:0] online
PM2        | 2023-09-19T10:44:35: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-09-19T10:44:35: PM2 log: App [public:1] online
PM2        | 2023-09-19T10:44:37: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-09-19T09:57:09: Server need close, singal SIGINT

/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-09-19T09:57:09: ✌️ 定时服务启动成功！
0|schedule | 2023-09-19T10:00:25: ✌️ 定时服务启动成功！
0|schedule | 2023-09-19T10:44:35: ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-09-19T09:57:09: ✌️ Sentry loaded
1|public   | 2023-09-19T09:57:10: ✌️ DB loaded
1|public   | 2023-09-19T09:57:10: ✌️ 公共服务启动成功！
1|public   | 2023-09-19T10:00:25: ✌️ Sentry loaded
1|public   | 2023-09-19T10:00:26: ✌️ DB loaded
1|public   | 2023-09-19T10:00:26: ✌️ 公共服务启动成功！
1|public   | 2023-09-19T10:44:34: ✌️ Sentry loaded
1|public   | 2023-09-19T10:44:35: ✌️ DB loaded
1|public   | 2023-09-19T10:44:35: ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-09-19T10:00:27: ✌️ Dependency Injector loaded
2|panel    | 2023-09-19T10:00:27: ✌️ Express loaded
2|panel    | 2023-09-19T10:00:27: ✌️ init data loaded
2|panel    | 2023-09-19T10:00:27: ✌️ link deps loaded
2|panel    | 2023-09-19T10:00:27: ✌️ init task loaded
2|panel    | 2023-09-19T10:00:27: ✌️ 后端服务启动成功！
2|panel    | 2023-09-19T10:44:36: ✌️ DB loaded
2|panel    | 2023-09-19T10:44:36: ✌️ Init file down
2|panel    | 2023-09-19T10:44:36: ✌️ Sentry loaded
2|panel    | 2023-09-19T10:44:36: ✌️ Dependency Injector loaded
2|panel    | 2023-09-19T10:44:36: ✌️ Express loaded
2|panel    | 2023-09-19T10:44:37: ✌️ init data loaded
2|panel    | 2023-09-19T10:44:37: ✌️ link deps loaded
2|panel    | 2023-09-19T10:44:37: ✌️ init task loaded
2|panel    | 2023-09-19T10:44:37: ✌️ 后端服务启动成功！

### What is expected?

首次安装后执行ql -l check就进不去后台了

### What is actually happening?

服务启动超时
请先按如下方式修复：
1. 宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
2. 容器内执行 ql -l check、ql -l update
3. 如果无法解决，容器内执行 pm2 logs，拷贝执行结果[提交 issue](https://github.com/whyour/qinglong/issues/new?assignees=&labels=&template=bug_report.yml)
2023-09-19T09:57:09: Server need close, singal SIGINT

{"code":52,"killed":false,"signal":null,"cmd":"curl -s http://0.0.0.0:5600/api/system","stdout":"","stderr":""}

**Comment by whyour** [comment]
首次安装为什么要 check，有可能网络不好，依赖没装上
映射好目录，使用宿主机更新
宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
