### ISSUE TITLE
任务自动执行卡住，手动执行没有问题

### ISSUE THREAD

**Issue by papersnake** [whyour/qinglong#2121]
### Qinglong version

2.16.2

### Steps to reproduce

一个简单的shell 脚本任务

task sign189.sh
sh文件空容如下：
`
```
#!/usr/bin/env bash
echo "hello qinglong"
/ql/pan/cloudpan189-go-v0.1.3-linux-amd64/cloudpan189-go sign
```
`

第天定时执行，但是一直卡在第三行，第二行成功执行，
手动停止以后，再手动执行任务就可以成功执行
尝试过修改执行时间，不行
不用sh，直接执行二进制文件命令行也是同样情况，

### What is expected?

这是什么原因， 脚本的姿势有什么不对？

### What is actually happening?

如何让脚本顺利执行

**Comment by whyour** [comment]
http://demo.dlww.cc:4433 把你的代码放到 demo 环境试试

**Comment by papersnake** [comment]
> http://demo.dlww.cc:4433 把你的代码放到 demo 环境试试

demo 环境里有 cloudpan189-go吗，我去试试

**Comment by joevess** [comment]
我也遇见此问题

**Comment by whyour** [comment]
> > http://demo.dlww.cc:4433 把你的代码放到 demo 环境试试
> 
> demo 环境里有 cloudpan189-go吗，我去试试

demo 环境试了下，没有问题
http://demo.dlww.cc:4433/crontab
