### ISSUE TITLE
新版本 2.16.3 可用，你使用的版本为 2.16.2。更新不了！！！

### ISSUE THREAD

**Issue by wifisky-feilian** [whyour/qinglong#2122]
### Qinglong version

新版本 2.16.3 可用，你使用的版本为 2.16.2。更新不了！！！

### Steps to reproduce

更新可用
新版本 2.16.3 可用，你使用的版本为 2.16.2。
1. 定时任务支持设置多定时规则、任务执行前和执行后命令
2. 增加启动环境变量 QlPort, 支持修改 hosts 模式青龙启动端口
3. 消息通知 Bark 增加额外参数: 时效性通知、跳转Url
4. 修复调试脚本日志丢失
5. 环境变量名称增加复制功能
6. 修复系统设置展示版本失败
7. 其他 bug 修复

### What is expected?

新版本 2.16.3 可用，你使用的版本为 2.16.2。更新不了！！！

### What is actually happening?

更新结果（日志）：

下载更新中...
## 开始执行... 2023-09-24 06:41:58

使用 gitee 源更新...

更新青龙源文件成功...

更新青龙静态资源成功...

开始检测依赖...

安装 /ql/.tmp/qinglong-master 依赖包...

Packages are cloned from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm

dependencies:
+ @grpc/grpc-js 1.8.15
+ @otplib/preset-default 12.0.1
+ @sentry/node 7.54.0
+ @sentry/tracing 7.54.0
+ body-parser 1.20.2
+ celebrate 15.0.1
+ chokidar 3.5.3
+ cors 2.8.5
+ cron-parser 4.8.1
+ cross-spawn 7.0.3
+ dayjs 1.11.8
+ dotenv 16.1.4
+ express 4.18.2
+ express-jwt 6.1.2
+ express-rate-limit 7.0.0
+ express-urlrewrite 1.4.0
+ form-data 4.0.0
+ got 11.8.6
+ hpagent 1.2.0
+ http-proxy-middleware 2.0.6
+ iconv-lite 0.6.3
+ js-yaml 4.1.0
+ jsonwebtoken 8.5.1
+ lodash 4.17.21
+ multer 1.4.4
+ nedb 1.8.0
+ node-schedule 2.1.1
+ nodemailer 6.9.3
+ p-limit 3.1.0
+ protobufjs 7.2.3
+ pstree.remy 1.1.8
+ reflect-metadata 0.1.13
+ sequelize 6.32.0
+ serve-handler 6.1.5
+ sockjs 0.3.24
+ sqlite3 <- @whyour/sqlite3 1.0.3
+ tar 6.1.15
+ toad-scheduler 1.6.1
+ typedi 0.10.0
+ uuid 8.3.2
+ winston 3.9.0
+ winston-daily-rotate-file 4.7.1
+ yargs 17.7.2

devDependencies: skipped

> @ postinstall /ql/.tmp/qinglong-master
> max setup 2>/dev/null || true

**Comment by whyour** [comment]
不能弹出来 重启的弹框？什么浏览器

**Comment by jswxll** [comment]
> 不能弹出来 重启的弹框？什么浏览器

我从2.16.2成功更新为2.16.3，系统设置页面显示异常也已得到解决
更新页面有弹窗，但重启后显示版本仍为2.16.2，Portainer面板里重启容器后显示都已正常
