### ISSUE TITLE
QlBaseUrl功能不能正常工作

### ISSUE THREAD

**Issue by baibinghere** [whyour/qinglong#2124]
### Qinglong version

imageId: e050ef2b2e18

### Steps to reproduce

使用该命令启动docker
```
docker run -dit -v ~/ql/data:/ql/data   -p 5700:5700   -e QlBaseUrl="/qinglong/"   --name qinglong   --hostname qinglong   --restart unless-stopped   whyour/qinglong:debian
```

### What is expected?

所有地址应该全部定向到/qinglong

### What is actually happening?

有些地址被hard code到根路径，导致查到不到地址：

![image](https://github.com/whyour/qinglong/assets/9794472/bd93dd65-dab5-4e35-9076-2b2163fec1fc)

**Comment by baibinghere** [comment]
我能看到qinglong使用的是相对地址：

![image](https://github.com/whyour/qinglong/assets/9794472/8fcf51c1-8813-4391-bf0a-38de420ed6c3)

![image](https://github.com/whyour/qinglong/assets/9794472/12ca639e-3164-45ac-9ebb-32993391d7bf)

但Chrome实际请求的，的确是绝对地址：

![image](https://github.com/whyour/qinglong/assets/9794472/29570f30-96c6-4e0e-a3c6-84e0461ff748)

实在不理解是我的配置问题，还是代码的问题。

如果知道任何信息请回复，谢谢！

**Comment by whyour** [comment]
@baibinghere 访问的时候最后加上斜杠
