### ISSUE TITLE
更新后多个脚本运行出错

### ISSUE THREAD

**Issue by poorestexplorer** [whyour/qinglong#2125]
### Qinglong version

2.16.3

### Steps to reproduce

aarch64
执行arm64
在/ql/data/scripts/ELM-main/ELM-main/ELM目录、/ql/data/scripts/ELM-main/ELM-main目录下均未找到文件elm-arm64,尝试拉取远程仓库文件elm-arm64
开始下载elm二进制文件到/ql/data/scripts/ELM-main/ELM-main/ELM目录
下载完成，如需重新下载或更新请先删除该文件
/ql/data/scripts/ELM-main/ELM-main/ELM/elm-arm64
PROT_EXEC|PROT_WRITE failed.

### What is expected?

脚本未执行

### What is actually happening?

运行出错

**Comment by whyour** [comment]
建议咨询脚本开发者
 aarch64
执行arm64
你这架构好像不是一个
