### ISSUE TITLE
希望 Python 脚本也能支持延迟执行

### ISSUE THREAD

**Issue by powersee** [whyour/qinglong#2126]
### Clear and concise description of the problem

目前的 task 执行脚本，好像只对 js 脚本有随机延迟

### Suggested solution

希望后续可以支持 Python 脚本

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
可以在任务在执行前添加 延迟操作
 
<img width="495" alt="image" src="https://github.com/whyour/qinglong/assets/22700758/2bf42533-5ded-4b12-9235-12757123f880">
