### ISSUE TITLE
最新版docker访问5700白屏咋办

### ISSUE THREAD

**Issue by tcscat** [whyour/qinglong#2128]
### Qinglong version

latest

### Steps to reproduce

eage 浏览器访问 5700白屏
arm版的docker

### What is expected?

救命

### What is actually happening?

![image](https://github.com/whyour/qinglong/assets/61655339/63dbffb5-85e4-488b-a52d-84e5cab025f8)

**Comment by YellowLyre** [comment]
进入容器，然后ql check一下，看看panel public sch什么的有没有报错呀

**Comment by whyour** [comment]
@tcscat 你是不是有广告插件，把 cdn 拦截了

**Comment by tcscat** [comment]
还真是， openwrt中ad钙的问题
