### ISSUE TITLE
环境变量的值过长导致面板崩溃

### ISSUE THREAD

**Issue by inoyna12** [whyour/qinglong#2132]
### Qinglong version

2.16.3

### Steps to reproduce

当任意一个环境变量的值的长度超过131064时，会导致运行任务失败，面板打不开等等。。。

### What is expected?

这个可以修复吗

### What is actually happening?

![Screenshot_2023-10-01-23-52-52-101_mark via](https://github.com/whyour/qinglong/assets/86736950/59000886-5a00-4c86-ab00-e39cd5e7cc8b)

**Comment by whyour** [comment]
这是系统的限制，如果环境变量过长，建议使用文件。或者有其他方案，欢迎 PR
