### ISSUE TITLE
go-cqhttp api错误

### ISSUE THREAD

**Issue by sq113** [whyour/qinglong#2134]
### Qinglong version

v2.16.3

### Steps to reproduce

go-cqhttp 无法发送消息
可能是 go-cqhttp api更新导致的出错

### What is expected?

希望可以修复

### What is actually happening?

Error:[data":null,"“message":”请参考 go-cqhttp 端输
出""msg":"SEND_MSG_APLERROR""retcode":100,"status":"failed",“wording":"请
参考go-cqhttp 端输出”]

### Any additional comments?

我试着修改函数后可以正常使用
但是通知设置添加go-cqhttp通知方式还是会报错
```
function gobotNotify(text, desp) {
  return new Promise((resolve) => {
    if (GOBOT_URL) {
      const options = {
        url: `${GOBOT_URL}?access_token=${GOBOT_TOKEN}`,
        json: 
        {   message_type: `private`,
            user_id: `${GOBOT_QQ}`,
            message: `${text}\n${desp}`,
        },
        headers: {
          'Content-Type': 'application/json',
        },
        timeout,
      };
      $.post(options, (err, resp, data) => {
        try {
          if (err) {
            console.log('发送go-cqhttp通知调用API失败！！\n');
            console.log(err);
          } else {
            data = JSON.parse(data);
            if (data.retcode === 0) {
              console.log('go-cqhttp发送通知消息成功🎉\n');
            } else if (data.retcode === 100) {
              console.log(`go-cqhttp发送通知消息异常: ${data.errmsg}\n`);
            } else {
              console.log(`go-cqhttp发送通知消息异常\n${JSON.stringify(data)}`);
            }
          }
        } catch (e) {
          $.logErr(e, resp);
        } finally {
          resolve(data);
        }
      });
    } else {
      resolve();
    }
  });
}
```

**Comment by whyour** [comment]
```js
function gobotNotify(text, desp) {
  return new Promise((resolve) => {
    if (GOBOT_URL) {
      const options = {
        url: `${GOBOT_URL}?access_token=${GOBOT_TOKEN}`,
        body: `message=${text}\n${desp}&${GOBOT_QQ}`,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        timeout,
      };
      $.post(options, (err, resp, data) => {
        try {
          if (err) {
            console.log('发送go-cqhttp通知调用API失败！！\n');
            console.log(err);
          } else {
            data = JSON.parse(data);
            if (data.retcode === 0) {
              console.log('go-cqhttp发送通知消息成功🎉\n');
            } else if (data.retcode === 100) {
              console.log(`go-cqhttp发送通知消息异常: ${data.errmsg}\n`);
            } else {
              console.log(`go-cqhttp发送通知消息异常\n${JSON.stringify(data)}`);
            }
          }
        } catch (e) {
          $.logErr(e, resp);
        } finally {
          resolve(data);
        }
      });
    } else {
      resolve();
    }
  });
}
```

看这样是不是也可以

**Comment by sq113** [comment]
https://docs.go-cqhttp.org/api/#%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF

## 发送消息
终结点：/send_msg

参数
#### 发送消息参数：

| 字段名         | 数据类型 | 默认值 | 说明                                                         |
| -------------- | -------- | ------ | ------------------------------------------------------------ |
| message_type   | string   | -      | 消息类型，支持 private、group，分别对应私聊、群组，如不传入，则根据传入的 *_id 参数判断 |
| user_id        | int64    | -      | 对方 QQ 号 (消息类型为 private 时需要)                         |
| group_id       | int64    | -      | 群号 (消息类型为 group 时需要)                                 |
| message        | message  | -      | 要发送的内容                                                 |
| auto_escape    | boolean  | false  | 消息内容是否作为纯文本发送 (即不解析 CQ 码)，只在 message 字段是字符串时有效 |

#### 响应数据：

| 字段名     | 数据类型 | 说明     |
| ---------- | -------- | -------- |
| message_id | int32    | 消息 ID |

**Comment by whyour** [comment]
我意思是用我发的能不能发送消息，我这边没部署成功

**Comment by sq113** [comment]
> 我意思是用我发的能不能发送消息，我这边没部署成功

不行

**Comment by whyour** [comment]
> ```js
> url: `${GOBOT_URL}?access_token=${GOBOT_TOKEN}`,
>         body: `message=${text}\n${desp}&${GOBOT_QQ}`,
> ```
报什么错，这几个参数和原来一样，你是怎么填写的
url: `${GOBOT_URL}?access_token=${GOBOT_TOKEN}`,
        body: `message=${text}\n${desp}&${GOBOT_QQ}`,

**Comment by whyour** [comment]
> 报什么错，这几个参数和原来一样，你是怎么填写的
> url: `${GOBOT_URL}?access_token=${GOBOT_TOKEN}`,
> body: `message=${text}\n${desp}&${GOBOT_QQ}`,

报什么错，这几个参数和原来一样，你是怎么填写的
url: ${GOBOT_URL}?access_token=${GOBOT_TOKEN},
body: message=${text}\n${desp}&${GOBOT_QQ},

> > 我意思是用我发的能不能发送消息，我这边没部署成功
> 
> 不行

报什么错，这几个参数和原来一样，你是怎么填写的
url: ${GOBOT_URL}?access_token=${GOBOT_TOKEN},
body: message=${text}\n${desp}&${GOBOT_QQ},

**Comment by sq113** [comment]
我上面不是写了吗？
        url: `${GOBOT_URL}?access_token=${GOBOT_TOKEN}`,
        json: 
        {   message_type: `private`,
            user_id: `${GOBOT_QQ}`,
            message: `${text}\n${desp}`,
        },

**Comment by whyour** [comment]
你是不是 url 写错了，看配置文件里的说明 https://docs.go-cqhttp.org/api/#%E5%8F%91%E9%80%81%E7%A7%81%E8%81%8A%E6%B6%88%E6%81%AF
 
<img width="1084" alt="image" src="https://github.com/whyour/qinglong/assets/22700758/9f8c7145-1d0a-4529-bffc-d7f50072edbb">

**Comment by sq113** [comment]
我用的 /send_msg ，但是无论哪种不是都要 user_id吗？
![image](https://github.com/whyour/qinglong/assets/43515787/4afd7da8-fbfe-4edf-a034-1b41c329af76)

**Comment by whyour** [comment]
你看参数说明，GOBOT_QQ 填的是 user_id=xxx 或者 group_id=xxxx，根据你的 url 不同，填写对应参数

**Comment by sq113** [comment]
e

> 你看参数说明，GOBOT_QQ 填的是 user_id=xxx 或者 group_id=xxxx，根据你的 url 不同，填写对应参数 不是直接填 QQ

额，我看错了，不好意思

**Comment by whyour** [comment]
> e
> 
> 
> 
> > 你看参数说明，GOBOT_QQ 填的是 user_id=xxx 或者 group_id=xxxx，根据你的 url 不同，填写对应参数 不是直接填 QQ
> 
> 
> 
> 额，我看错了，不好意思

所以目前的版本有问题吗
