### ISSUE TITLE
设置执行后运行另外一个脚本，一但另外个脚本开始运行点击停止无法停止

### ISSUE THREAD

**Issue by Aellyt** [whyour/qinglong#2135]
### Qinglong version

2.16.3

### Steps to reproduce

设置执行后运行另外一个脚本，一但另外个脚本开始运行点击停止无法停止

### What is expected?

可以停止脚本

### What is actually happening?

设置执行后运行另外一个脚本，一但另外个脚本开始运行点击停止无法停止

**Comment by whyour** [comment]
没太理解你的意思

**Comment by Aellyt** [comment]
![76E213CD-EB50-4181-9EEE-11124A6AE563](https://github.com/whyour/qinglong/assets/83526546/372b9d0a-239f-4b5a-96c8-543714e20c4b)
![D5D903D3-60B1-471B-99C9-83AC5967F8F9](https://github.com/whyour/qinglong/assets/83526546/6b3e32a8-4e15-4e12-82e8-b4b64e2f2775)
设置执行后，运行另外一个脚本，task xxxx.js 这个xxxx.js被运行后，将会无法停止他，会一直启动，不知是我使用有问题，还是停止的逻辑有问题

**Comment by whyour** [comment]
> ![76E213CD-EB50-4181-9EEE-11124A6AE563](https://github.com/whyour/qinglong/assets/83526546/372b9d0a-239f-4b5a-96c8-543714e20c4b)
> 
> ![D5D903D3-60B1-471B-99C9-83AC5967F8F9](https://github.com/whyour/qinglong/assets/83526546/6b3e32a8-4e15-4e12-82e8-b4b64e2f2775)
> 
> 设置执行后，运行另外一个脚本，task xxxx.js 这个xxxx.js被运行后，将会无法停止他，会一直启动，不知是我使用有问题，还是停止的逻辑有问题

两个脚本有关联？

**Comment by Aellyt** [comment]
> > ![76E213CD-EB50-4181-9EEE-11124A6AE563](https://user-images.githubusercontent.com/83526546/272889808-372b9d0a-239f-4b5a-96c8-543714e20c4b.jpeg)
> > ![D5D903D3-60B1-471B-99C9-83AC5967F8F9](https://user-images.githubusercontent.com/83526546/272889823-6b3e32a8-4e15-4e12-82e8-b4b64e2f2775.jpeg)
> > 设置执行后，运行另外一个脚本，task xxxx.js 这个xxxx.js被运行后，将会无法停止他，会一直启动，不知是我使用有问题，还是停止的逻辑有问题
> 
> 两个脚本有关联？

关键性到不大，用到点启动也没事，就是想问下这个停不下的是我使用问题还是bug
