### ISSUE TITLE
大佬帮我看看我这是环境没装好吗？

### ISSUE THREAD

**Issue by WYEEE** [whyour/qinglong#214]
**装bot不启动：**

3、安装python3依赖...

Writing to /root/.config/pip/pip.conf
cp: cannot stat '/ql/repo/SuMaiKaDe_jddockerbot/jbot/requirements.txt': No such file or directory
·ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.

python3依赖安装成功...

4、启动bot程序...

bot启动成功...

=================================================================================
**bot日志：**

nohup: ignoring input

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/ql/jbot/__init__.py", line 1, in <module>
    from telethon import TelegramClient, connection

ModuleNotFoundError: No module named 'telethon'

**Comment by WYEEE** [comment]
环境是Debian 9 

😭

**Comment by whyour** [comment]
@WYEEE 作者库私有了，拉取不到源码，所以报错了
