### ISSUE TITLE
v2.16.3版本所有脚本都不能执行，每个脚本的报错也不一样，请教下大家如何解决

### ISSUE THREAD

**Issue by seryte** [whyour/qinglong#2140]
### Qinglong version

2.16.3

### Steps to reproduce
环境采用的是docker-compose方式部署
用的这个仓库的脚本：https://github.com/shufflewzc/faker2.git， 我随便截几个报错的任务图，都不一样，不太清楚怎么解决了，我尝试了把所有脚本都删了，重新拉这个库，重新添加了也还是一样的报错
<img width="1435" alt="image" src="https://github.com/whyour/qinglong/assets/17977783/76e336e1-17a7-4687-ae01-a5c7523b5c59">

<img width="1081" alt="image" src="https://github.com/whyour/qinglong/assets/17977783/645fac0a-96d8-4668-b765-4cd172a6a728">
<img width="1148" alt="image" src="https://github.com/whyour/qinglong/assets/17977783/8b713397-680f-4859-9400-f2c942b727e9">
<img width="1080" alt="image" src="https://github.com/whyour/qinglong/assets/17977783/5006181e-9f06-45ba-a35e-bd418a1aad49">
<img width="1058" alt="image" src="https://github.com/whyour/qinglong/assets/17977783/907b0260-0343-4e42-9be5-2abb9c1b92d3">
<img width="1211" alt="image" src="https://github.com/whyour/qinglong/assets/17977783/f6aff661-5704-490d-bd61-da713a5f02fc">
<img width="1407" alt="image" src="https://github.com/whyour/qinglong/assets/17977783/5c847b56-2334-4fcd-9fbd-fde436dea046">

### What is expected?

脚本能够正常运行

### What is actually happening?

90%的脚本都无法执行

**Comment by whyour** [comment]
脚本问题，找脚本作者
