### ISSUE TITLE
可不可以设置单个任务加随机延迟

### ISSUE THREAD

**Issue by 717009629** [whyour/qinglong#2142]
### Clear and concise description of the problem

因为大部分任务都不需要随机延迟 ，只是个别任务需要，

### Suggested solution

可不可以设置单个任务加随机延迟，

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
可以在创建任务的时候任务前执行 sleep 命令

**Comment by 717009629** [comment]
好的 谢谢  sleep $[($RANDOM % 10000)+1]
