### ISSUE TITLE
无法安装依赖

### ISSUE THREAD

**Issue by happyhope** [whyour/qinglong#2144]
### Qinglong version

2.16.3

### Steps to reproduce

root@qinglong:/ql $ ql check
## 开始执行... 2023-10-12 13:11:33

=====> 开始检测
npm ERR! code CERT_HAS_EXPIRED
npm ERR! errno CERT_HAS_EXPIRED
npm ERR! request to https://registry.npmmirror.com/pnpm failed, reason: certificate has expired

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-12T05_11_34_784Z-debug-0.log
Writing to /root/.config/pip/pip.conf
Lockfile is up to date, resolution step is skipped
Already up to date

Done in 1.4s
 WARN  GET https://registry.npmmirror.com/pm2 error (CERT_HAS_EXPIRED). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/tsx error (CERT_HAS_EXPIRED). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/pm2 error (CERT_HAS_EXPIRED). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/tsx error (CERT_HAS_EXPIRED). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/pm2: request to https://registry.npmmirror.com/pm2 failed, reason: certificate has expired

This error happened while installing a direct dependency of /root/.local/share/pnpm/global/5
---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

安装 /ql 依赖包...

devDependencies: skipped

> @ postinstall /ql
> max setup 2>/dev/null || true

Done in 1.9s
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

安装 /ql/data/scripts 依赖包...

 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/nodemailer: request to https://registry.npmmirror.com/nodemailer failed, reason: certificate has expired

This error happened while installing a direct dependency of /ql/data/scripts
---> 脚本依赖安装完成

---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<!DOCTYPE html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="shortcut icon" href="https://qn.whyour.cn/favicon.svg">
<link rel="stylesheet" href="./umi.8a0eaca6.css">
<script src="./api/env.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react/18.2.0/umd/react.production.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
</head>
<body>
<div id="root"></div>
<script src="./umi.556f567f.js"></script>

</body></html>

=====> 面板服务启动正常

=====> 检测nginx服务
  205 nginx: master process nginx -c /etc/nginx/nginx.conf
  206 nginx: worker process
  207 nginx: worker process
  208 nginx: worker process
  209 nginx: worker process
  211 nginx: worker process
  212 nginx: worker process
  213 nginx: worker process
  214 nginx: worker process

=====> nginx服务正常

---> pm2日志
2023-10-11T21:36:40: ✌️ DB loaded
2023-10-11T21:36:40: ✌️ Init file down
2023-10-11T21:36:40: ✌️ Sentry loaded
2023-10-11T21:36:41: ✌️ Dependency Injector loaded
2023-10-11T21:36:41: ✌️ Express loaded
2023-10-11T21:36:41: ✌️ init data loaded
2023-10-11T21:36:41: ✌️ link deps loaded
2023-10-11T21:36:41: ✌️ init task loaded
2023-10-11T21:36:41: ✌️ 后端服务启动成功！
2023-10-11T21:37:16: ValidationError: The Express 'trust proxy' setting is true, which allows anyone to trivially bypass IP-based rate limiting. See https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/ for more information.
2023-10-11T21:37:16:     at Object.trustProxy (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:148:13)
2023-10-11T21:37:16:     at Object.wrappedValidations.<computed> [as trustProxy] (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:324:22)
2023-10-11T21:37:16:     at Object.keyGenerator (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:582:20)
2023-10-11T21:37:16:     at /ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:633:32
2023-10-11T21:37:16:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-11T21:37:16:     at /ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:615:5 {
2023-10-11T21:37:16:   code: 'ERR_ERL_PERMISSIVE_TRUST_PROXY',
2023-10-11T21:37:16:   help: 'https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/'
2023-10-11T21:37:16: }

=====> 检测后台

{"code":200,"data":{"isInitialized":true,"version":"2.16.3","publishTime":1695441600,"branch":"master","changeLog":"1. 定时任务支持设置多定时规则、任务执行前和执行后命令
2. 增加启动环境变量 QlPort, 支持修改 hosts 模式青龙启动端口
3. 消息通知 Bark 增加额外参数: 时效性通知、跳转Url
4. 修复调试脚本日志丢失
5. 环境变量名称增加复制功能
6. 修复系统设置展示版本失败
7. 其他 bug 修复
","changeLogLink":"https://t.me/jiao_long/394"}}

=====> 后台服务启动正常

[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])
[PM2] Applying action reloadProcessId on app [public](ids: [ 1 ])
[PM2] [schedule](0) ✓
[PM2] Applying action reloadProcessId on app [panel](ids: [ 2 ])
[PM2] [public](1) ✓
[PM2] [panel](2) ✓
┌────┬────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 23112    │ 2s     │ 1    │ online    │ 0%       │ 134.6mb  │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 23055    │ 19s    │ 1    │ online    │ 1.9%     │ 111.3mb  │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 23054    │ 19s    │ 1    │ online    │ 5.2%     │ 75.0mb   │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

=====> 检测结束

49 verbose npm  v9.6.6
50 error code CERT_HAS_EXPIRED
51 error errno CERT_HAS_EXPIRED
52 error request to https://registry.npmmirror.com/pnpm failed, reason: certificate has expired
53 verbose exit 1
54 timing npm Completed in 70868ms
55 verbose unfinished npm timer reify 1697087495272
56 verbose unfinished npm timer reify:loadTrees 1697087495278
57 verbose code 1
58 error A complete log of this run can be found in: /root/.npm/_logs/2023-10-12T05_11_34_784Z-debug-0.log
^[[A^[[A^Z
[1]+  Stopped                 tail -f /root/.npm/_logs/2023-10-12T05_11_34_784Z-debug-0.log
root@qinglong:/ql $ tail -f -n 1000 /root/.npm/_logs/2023-10-12T05_11_34_784Z-debug-0.log
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.6
2 info using node@v18.17.1
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 5ms
6 timing config:load:builtin Completed in 6ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/root/.npmrc Completed in 2ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:setEnvs Completed in 3ms
15 timing config:load Completed in 25ms
16 timing npm:load:configload Completed in 26ms
17 timing npm:load:mkdirpcache Completed in 1ms
18 timing npm:load:mkdirplogs Completed in 1ms
19 verbose title npm i pnpm@8.3.1
20 verbose argv "i" "--global" "pnpm@8.3.1"
21 timing npm:load:setTitle Completed in 3ms
22 timing config:load:flatten Completed in 7ms
23 timing npm:load:display Completed in 9ms
24 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-10-12T05_11_34_784Z-
25 verbose logfile /root/.npm/_logs/2023-10-12T05_11_34_784Z-debug-0.log
26 timing npm:load:logFile Completed in 19ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 62ms
30 timing config:load:flatten Completed in 2ms
31 timing arborist:ctor Completed in 2ms
32 silly logfile done cleaning log files
33 timing idealTree:init Completed in 11ms
34 timing idealTree:userRequests Completed in 6ms
35 silly idealTree buildDeps
36 silly fetch manifest pnpm@8.3.1
37 silly placeDep ROOT pnpm@ OK for:  want: 8.3.1
38 timing idealTree:#root Completed in 70304ms
39 timing idealTree:node_modules/pnpm Completed in 0ms
40 timing idealTree:buildDeps Completed in 70308ms
41 timing idealTree:fixDepFlags Completed in 4ms
42 timing idealTree Completed in 70334ms
43 timing command:i Completed in 70348ms
44 verbose type system
45 verbose stack FetchError: request to https://registry.npmmirror.com/pnpm failed, reason: certificate has expired
45 verbose stack     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
45 verbose stack     at ClientRequest.emit (node:events:514:28)
45 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:501:9)
45 verbose stack     at TLSSocket.emit (node:events:526:35)
45 verbose stack     at emitErrorNT (node:internal/streams/destroy:151:8)
45 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
45 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
46 verbose cwd /ql
47 verbose Linux 5.10.110
48 verbose node v18.17.1
49 verbose npm  v9.6.6
50 error code CERT_HAS_EXPIRED
51 error errno CERT_HAS_EXPIRED
52 error request to https://registry.npmmirror.com/pnpm failed, reason: certificate has expired
53 verbose exit 1
54 timing npm Completed in 70868ms
55 verbose unfinished npm timer reify 1697087495272
56 verbose unfinished npm timer reify:loadTrees 1697087495278
57 verbose code 1
58 error A complete log of this run can be found in: /root/.npm/_logs/2023-10-12T05_11_34_784Z-debug-0.log

### What is expected?

正常安装依赖

### What is actually happening?

 WARN  GET https://registry.npmmirror.com/request error (CERT_HAS_EXPIRED). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/pm2/-/pm2-5.3.0.tgz error (CERT_HAS_EXPIRED). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/tsx/-/tsx-3.12.10.tgz error (CERT_HAS_EXPIRED). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/request error (CERT_HAS_EXPIRED). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/pm2/-/pm2-5.3.0.tgz error (CERT_HAS_EXPIRED). Will retry in 1 minute. 1 retries left.
 WARN  GET https://registry.npmmirror.com/tsx/-/tsx-3.12.10.tgz error (CERT_HAS_EXPIRED). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmmirror.com/request: request to https://registry.npmmirror.com/request failed, reason: certificate has expired

This error happened while installing a direct dependency of /root/.local/share/pnpm/global/5

依赖安装失败，结束时间 2023-10-12 13:16:50，耗时 72 秒

**Comment by whyour** [comment]
配置文件里的 NpmMirror 换个 镜像源

**Comment by kuqitt** [comment]
@whyour 添加了不管用啊h还是报错
![image](https://github.com/whyour/qinglong/assets/66942822/0ea88cbc-a0d9-4a6a-8e53-0eaa559d809d)

**Comment by whyour** [comment]
> @whyour 添加了不管用啊h还是报错
> 
> ![image](https://github.com/whyour/qinglong/assets/66942822/0ea88cbc-a0d9-4a6a-8e53-0eaa559d809d)
> 
> 

可能是你网络问题

**Comment by kuqitt** [comment]
真的吗 我这是腾xy服务器

**Comment by kuqitt** [comment]
@whyour ======================4. 启动pm2服务========================

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2'
[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:922:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)[39m
[90m    at node:internal/main/run_main_module:23:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

Node.js v18.17.1
您看

**Comment by guzhi-zxy** [comment]
1. 进入docker执行：
pnpm config set registry https://registry.npmjs.org/
2. 然后再安装即可：
pnpm add -g xxx xxx
