### ISSUE TITLE
2.16.3版本无法创建视图

### ISSUE THREAD

**Issue by shusheng129** [whyour/qinglong#2146]
### Qinglong version

2.16.3

### Steps to reproduce

最新版创建视图一直显示请选择操作符，选择了也无效

### What is expected?

无

### What is actually happening?

最新版创建视图一直显示请选择操作符，选择了也无法添加，设置筛选条件时操作符会自动消失

**Comment by whyour** [comment]
@shusheng129 更新下镜像

**Comment by shusheng129** [comment]
好的 我试试看
