### ISSUE TITLE
关于私有库的拉取

### ISSUE THREAD

**Issue by xiaodan01** [whyour/qinglong#2149]
### Clear and concise description of the problem

ql旧版本的时候还有~/.ssh/config这个文件可以修改用来拉取私有仓库，好像新版的都没这个东西了，这种的私有库怎么拉呢
ssh拉库的地址则为：git@github_123:121212/scripts.git

### Suggested solution

1

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
订阅管理里添加私有仓库即可
<img width="189" alt="image" src="https://github.com/whyour/qinglong/assets/22700758/5e0d428a-6cf8-4be6-be44-23f6a233efa7">
