### ISSUE TITLE
请教大佬，重装后出现Error: Cannot find module 'tough-cookie'错误 

### ISSUE THREAD

**Issue by li258w** [whyour/qinglong#215]
日志显示：

🔔京东资产变动通知, 开始!

====================共2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/5/30下午8:20:13=====================

(node:483) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tough-cookie'
Require stack:
- /ql/scripts/chinnkarahoi_jd_scripts_jd_bean_change.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
.....
...
请问是哪里出了问题，怎么解决？多谢！

**Comment by whyour** [comment]
@li258w 不了解 ql repo 命令就用频道里的示例仓库，别瞎写

**Comment by li258w** [comment]
我第一个是拉的示例仓库docker exec -it qinglong ql repo https://ghproxy.com/https://github.com/whyour/hundun.git "quanx" "tokens|caiyun|didi|donate|fold|Env"，出现Error: Cannot find module './jdCookie.js'错误；翻了以前的问题，有个说执行docker exec -it qinglong ql repo https://ghproxy.com/https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"能解决，我就试了一下，没有jdcookie.js问题了，但又出现现在的情况，大佬，帮忙解决一下吧

**Comment by whyour** [comment]
@li258w 删了容器，重新启动下

**Comment by li258w** [comment]
好的，我去试试

**Comment by li258w** [comment]
删了，重新启动。进入界面更新面板任务一直显示运行中，等了几分钟没停，我拉了示例仓库，手动运行显示：
🔔京东赚京豆, 开始!
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module './jdCookie.js'
Require stack:
- /ql/scripts/whyour_hundun_jd_zjd.js
    at Function.Module._resolveFilename

**Comment by whyour** [comment]
@li258w 把示例仓库都拉了，按顺序拉

**Comment by li258w** [comment]
新问题：
开始下载：https://ghproxy.com/https://raw.githubusercontent.com/moposmall/Script/main/Me/jx_cfd.js 

保存路径：/ql/raw/jx_cfd.js

wget: server returned error: HTTP/1.1 404 NOT FOUND
下载 jx_cfd.js 失败，保留之前正常下载的版本...

我都删了再重新来一遍试试。

**Comment by whyour** [comment]
@li258w 这个脚本可能作者删了吧

**Comment by li258w** [comment]
全删以后重新启动容器，按顺序拉仓库没问题了。多谢大佬！！

**Comment by youmengme** [comment]
@whyour 大佬 示例仓库在哪
