### ISSUE TITLE
V2.6.13版本“备份”功能BUG（表面下载完成，实际504超时）

### ISSUE THREAD

**Issue by singyueyang** [whyour/qinglong#2150]
### Qinglong version

V2.6.13

### Steps to reproduce

系统设置 - 其他设置 - 点击备份按钮

### What is expected?

预期是完成备份，并成功下载备份数据。

### What is actually happening?

页面显示“下载成功”的弹窗，但浏览器并没有下载任何数据，更换浏览器同样报错。通过F12查看备份的请求，最后发现接口返回504错误：
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by whyour** [comment]
版本号都不对，把请求截下图？

**Comment by 201907909** [comment]
![image](https://github.com/whyour/qinglong/assets/73740285/8a384fd4-e262-4580-abed-bad5035709db)
请问这种是什么情况？

**Comment by singyueyang** [comment]
> 版本号都不对，把请求截下图？

@whyour  不好意思大佬，版本号写错了，是正式版 v2.16.3，报错信息如下图：
![33333](https://github.com/whyour/qinglong/assets/65761345/9b042aae-97c5-41cc-a490-0f77c3b2eced)

![1698287283(1)](https://github.com/whyour/qinglong/assets/65761345/f574ad38-6af3-40bc-963a-a7978a6156f4)

**Comment by whyour** [comment]
下载过程中你切到定时任务页面了？如果在原来的页面等着呢

**Comment by king07-2046** [comment]
青龙版本2.16.4，备份功能不能使用。点击备份，现在下来只有不到1k 的数据包，打开数据包显示文件损坏，请问问题出在哪里呢？

**Comment by whyour** [comment]
> 青龙版本2.16.4，备份功能不能使用。点击备份，现在下来只有不到1k 的数据包，打开数据包显示文件损坏，请问问题出在哪里呢？

什么浏览器，录个视频看看？

**Comment by king07-2046** [comment]
华为内置浏览器，我用电脑的好几个浏览器备份也是一样备份只有不到1k，是不是青龙缺文件？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月31日(周二) 下午3:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whyour/qinglong] V2.6.13版本“备份”功能BUG（表面下载完成，实际504超时） (Issue #2150)




  
青龙版本2.16.4，备份功能不能使用。点击备份，现在下来只有不到1k 的数据包，打开数据包显示文件损坏，请问问题出在哪里呢？
  
什么浏览器，录个视频看看？

**Comment by singyueyang** [comment]
> 下载过程中你切到定时任务页面了？如果在原来的页面等着呢

@whyour ，在原页面等待的话，最终报一个504错误，然后页面自动就跳到 定时任务 页面去了。

**Comment by king07-2046** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月7日(周二) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whyour/qinglong] V2.6.13版本“备份”功能BUG（表面下载完成，实际504超时） (Issue #2150)




  
下载过程中你切到定时任务页面了？如果在原来的页面等着呢
  
@whyour ，在原页面等待的话，最终报一个504错误，然后页面自动就跳到 定时任务 页面去了。

**Comment by king07-2046** [comment]
下载过程也木有切换到定时任务那里，就一直在原来的备份界面，没几秒就提示弹出下载框，显示数据大小都不到1k，我记得之前我成功备份过，都是六十多M，，后来不知道出了什么问题就没法备份了，现在备份也没有看到504错误提示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月7日(周二) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whyour/qinglong] V2.6.13版本“备份”功能BUG（表面下载完成，实际504超时） (Issue #2150)




  
下载过程中你切到定时任务页面了？如果在原来的页面等着呢
  
@whyour ，在原页面等待的话，最终报一个504错误，然后页面自动就跳到 定时任务 页面去了。

**Comment by whyour** [comment]
> 下载过程也木有切换到定时任务那里，就一直在原来的备份界面，没几秒就提示弹出下载框，显示数据大小都不到1k，我记得之前我成功备份过，都是六十多M，，后来不知道出了什么问题就没法备份了，现在备份也没有看到504错误提示
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月7日(周二) 下午4:46 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [whyour/qinglong] V2.6.13版本“备份”功能BUG（表面下载完成，实际504超时） (Issue #2150) 下载过程中你切到定时任务页面了？如果在原来的页面等着呢 @whyour ，在原页面等待的话，最终报一个504错误，然后页面自动就跳到 定时任务 页面去了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

解压后，里面是什么内容

**Comment by whyour** [comment]
> > 下载过程中你切到定时任务页面了？如果在原来的页面等着呢
> 
> @whyour ，在原页面等待的话，最终报一个504错误，然后页面自动就跳到 定时任务 页面去了。

你 data 目录有多大，备份成功过吗，是 ip 直连容器，还是中间还有个 nginx

**Comment by king07-2046** [comment]
应该是IP直连的青龙，没有服务器，本地盒子装的casaos然后装青龙面板，备份的文件打开失败，打不开。是不是青龙面板中删除了什么东西导致影响备份功能？之前我好像在青龙面板删除过一些文件，可能误删？之前删除过core.208321等类似的文件，这些文件是做什么的？我看生成了好多。有一次青龙运行异常，CPU爆满，然后查看文件系统，发现一堆几百M的core类似文件，每个都几百M，把我空间都挤爆了，我把青龙卸了重装然后删除core类似文件才恢复正常。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月13日(周一) 晚上7:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whyour/qinglong] V2.6.13版本“备份”功能BUG（表面下载完成，实际504超时） (Issue #2150)




   
下载过程中你切到定时任务页面了？如果在原来的页面等着呢
  
@whyour ，在原页面等待的话，最终报一个504错误，然后页面自动就跳到 定时任务 页面去了。
  
你 data 目录有多大，备份成功过吗，是 ip 直连容器，还是中间还有个 nginx

**Comment by whyour** [comment]
2.17.0 已修复

**Comment by king07-2046** [comment]
青龙面板点击更新没法更新，最后显示“显示依赖检测按照失败，请检查网络”



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月18日(周四) 晚上10:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whyour/qinglong] V2.6.13版本“备份”功能BUG（表面下载完成，实际504超时） (Issue #2150)




 
2.17.0 已修复
