### ISSUE TITLE
青龙与傻妞机器人docker compose部署yml文件，通过acme自动更新证书

### ISSUE THREAD

**Issue by Sunnnner** [whyour/qinglong#2151]
### Clear and concise description of the problem

- 一键部署傻妞机器人与青龙面板
- 通过acme自动更新网站证书方便快捷

### Suggested solution

https://github.com/Sunnnner/qinglong-docker-compose

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chenchenno11** [comment]
不是你这个怎么用啊，小白不太会

**Comment by Sunnnner** [comment]
> 不是你这个怎么用啊，小白不太会

- 需要一定的服务器运维能力，比如域名需要有一个，云服务器一台，docker安装(新版本docker自带docker compose), 然后clone项目修改里面的域名直接启动就行(docker compose up -d)
