### ISSUE TITLE
新版代理问题

### ISSUE THREAD

**Issue by dreamfly32** [whyour/qinglong#2153]
### Qinglong version

2.16.4

### Steps to reproduce

当配置了全局代理ALL_PROXY
在task_before.sh配置 curl ifconfig.me -s 执行是正常的，是代理ip
但在定时任务python脚本里，全局代理未生效，是本机ip，之前版本是生效的
r=requests.get('https://httpbin.org/ip')
print(r.text)

### What is expected?

1

### What is actually happening?

1

**Comment by whyour** [comment]
all_proxy
ALL_PROXY 
两个都设置上
