### ISSUE TITLE
python使用tls_client报错

### ISSUE THREAD

**Issue by Xiaobooooo** [whyour/qinglong#2155]
### Qinglong version

2.16.4

### Steps to reproduce

```python
import tls_client

session = tls_client.Session(client_identifier="chrome112", random_tls_extension_order=True)

res = session.get("https://www.baidu.com")
print(res.text)
```
创建Test.py文件，青龙面板运行报错，服务器直接运行正常

![青龙面板运行](https://github.com/whyour/qinglong/assets/97510981/9017be8f-2d09-4abc-8e25-e6fb6aee609e)
![服务器直接运行](https://github.com/whyour/qinglong/assets/97510981/c316af63-2cf8-4fd8-9041-916673f79448)

### What is expected?

能正常运行

### What is actually happening?

同样的代码，服务器正常运行，服务器搭建的青龙面板报错

![青龙面板运行](https://github.com/whyour/qinglong/assets/97510981/9017be8f-2d09-4abc-8e25-e6fb6aee609e)
![服务器直接运行](https://github.com/whyour/qinglong/assets/97510981/c316af63-2cf8-4fd8-9041-916673f79448)

### System Info

```shell
  System:
    OS: Linux 3.10 Alpine Linux
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-26xx v4
    Memory: 380.32 MB / 1.79 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    npm: 9.6.6 - /usr/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm

```

**Comment by whyour** [comment]
可以使用 whyour/qinglong:debian 镜像

**Comment by Xiaobooooo** [comment]
> 可以使用 whyour/qinglong:debian 镜像
