### ISSUE TITLE
check_server 找不到

### ISSUE THREAD

**Issue by OdinZhang** [whyour/qinglong#2158]
### Qinglong version

2.16.4

### Steps to reproduce

执行任务，提示check_server找不到，使用podman debian镜像
![image](https://github.com/whyour/qinglong/assets/25601078/b335ba0e-c67e-469a-a00d-64b54074d25d)

### What is expected?

不应该有此报错

### What is actually happening?

无法找到otask.sh里的check_server命令

**Comment by whyour** [comment]
重新更新下镜像
