### ISSUE TITLE
大佬我自己写了一些.sh想定时任务添加成功跑起来应该怎么弄？

### ISSUE THREAD

**Issue by liuruidong4** [whyour/qinglong#216]
大佬我自己写了一些.sh想定时任务添加成功跑起来应该怎么弄？
容器里运行sh  XXX.sh直接运行就可以了
我知道可以直接加在crontab里但是想用青龙的添加定时任务
sh xx.sh  看了env用了SHELL xx.sh貌似都不行 
小白准备开始研究起来 求解

**Comment by whyour** [comment]
@liuruidong4 面板新建任务   task  *.sh
