### ISSUE TITLE
启动时无法运行bot和extra.sh

### ISSUE THREAD

**Issue by lelemka0** [whyour/qinglong#2160]
### Qinglong version

v2.16.5

### Steps to reproduce

升级到此版本即出现问题，容器启动时无法运行bot和extra.sh。
问题由以下Commit引入：
[Commit 4938635](https://github.com/whyour/qinglong/commit/4938635ef4537f72a49911b9b6cb0f1e34be3d0c)

### What is expected?

`AutoStartBot="true"`时，启动时运行bot。
`EnableExtraShell="true"`时，启动时运行extra.sh。

### What is actually happening?

本次更改后导致容器启动时无法运行bot和extra.sh。
https://github.com/whyour/qinglong/blob/4938635ef4537f72a49911b9b6cb0f1e34be3d0c/shell/share.sh#L308-L313
问题由在`reload_pm2`运行`restore_env_vars`造成，变量`AutoStartBot `,`EnableExtraShell`被清除。

**Comment by whyour** [comment]
再更新下

**Comment by lelemka0** [comment]
> 再更新下

已解决

**Comment by lelemka0** [comment]
> 再更新下

已解决
