### ISSUE TITLE
2.11.3 登录超时

### ISSUE THREAD

**Issue by baigeiapi** [whyour/qinglong#2162]
### Qinglong version

2.11.3

### Steps to reproduce

登录超时，f12查看网络，链接至o1098464.ingest.sentry.io,时间过长

### What is expected?

如何解决连接超时问题

### What is actually happening?

![image](https://github.com/whyour/qinglong/assets/60828962/d8f9c0e3-3284-48cc-9f0f-d5bec81fdb33)

**Comment by baigeiapi** [comment]
用站长工具ping这个网址，好像就广东超时，而我又是广州的机子，这个有没有的改的

**Comment by whyour** [comment]
@baigeiapi 登录超时跟这个没关系，升级到 2.16.5 试试
