### ISSUE TITLE
部署完成以后浏览器打不开青龙面板，一直转圈

### ISSUE THREAD

**Issue by Aabandon** [whyour/qinglong#2164]
### Qinglong version

最新拉取

### Steps to reproduce

部署完成以后浏览器打不开青龙面板

### What is expected?

重新部署多次。重新安装docker多次并重新部署均无法打开

### What is actually happening?

一直在转圈，显示
启动中，请稍后...

### System Info

```shell
edge浏览器，openwrt系统
```

**Comment by abandon-xyz** [comment]
root@qinglong:/ql $ ql check


## 开始执行... 2023-11-02 11:13:49

=====> 开始检测

changed 1 package in 5s
检测到旧的db目录，拷贝到data目录...


检测到旧的scripts目录，拷贝到data目录...


检测到旧的log目录，拷贝到data目录...


检测到旧的config目录，拷贝到data目录...


Writing to /root/.config/pip/pip.conf
Lockfile is up to date, resolution step is skipped
Already up to date

Done in 6s
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 11, reused 1, downloaded 0, added 0
Progress: resolved 29, reused 3, downloaded 0, added 0
Progress: resolved 43, reused 22, downloaded 0, added 0
Progress: resolved 66, reused 28, downloaded 0, added 0
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Progress: resolved 90, reused 30, downloaded 0, added 0
Progress: resolved 128, reused 30, downloaded 0, added 0
Progress: resolved 161, reused 34, downloaded 0, added 0
Progress: resolved 181, reused 37, downloaded 0, added 0
Already up to date
Progress: resolved 181, reused 114, downloaded 0, added 0, done

Done in 16.9s
---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

安装 /ql 依赖包...


devDependencies: skipped


> @ postinstall /ql
> max setup 2>/dev/null || true

Done in 8.7s
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

安装 /ql/data/scripts 依赖包...


devDependencies: skipped

Done in 4.9s
---> 脚本依赖安装完成

---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成


=====> 检测面板

<!DOCTYPE html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="shortcut icon" href="https://qn.whyour.cn/favicon.svg">
<link rel="stylesheet" href="./umi.8a0eaca6.css">
<script src="./api/env.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react/18.2.0/umd/react.production.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
</head>
<body>
<div id="root"></div>
<script src="./umi.9ffa4b49.js"></script>

</body></html>

=====> 面板服务启动正常

=====> 检测nginx服务
   80 nginx: master process nginx -c /etc/nginx/nginx.conf
   81 nginx: worker process
   82 nginx: worker process
   83 nginx: worker process
   85 nginx: worker process

=====> nginx服务正常

---> pm2日志
2023-11-02T11:03:48: ✌️ DB loaded
2023-11-02T11:03:48: ✌️ Init file down
2023-11-02T11:03:48: ✌️ Sentry loaded
2023-11-02T11:03:51: ✌️ Dependency Injector loaded
2023-11-02T11:03:51: ✌️ Express loaded
2023-11-02T11:03:52: ✌️ init data loaded
2023-11-02T11:03:52: ✌️ link deps loaded
2023-11-02T11:03:52: ✌️ init task loaded
2023-11-02T11:03:52: ✌️ 后端服务启动成功！
2023-11-02T11:07:43: ✌️ DB loaded
2023-11-02T11:07:43: ✌️ Init file down
2023-11-02T11:07:44: ✌️ Sentry loaded
2023-11-02T11:13:37: ✌️ DB loaded
2023-11-02T11:13:37: ✌️ Init file down
2023-11-02T11:13:38: ✌️ Sentry loaded
2023-11-02T11:13:41: ✌️ Dependency Injector loaded
2023-11-02T11:13:41: ✌️ Express loaded
2023-11-02T11:13:42: ✌️ init data loaded
2023-11-02T11:13:42: ✌️ link deps loaded
2023-11-02T11:13:42: ✌️ init task loaded
2023-11-02T11:13:42: ✌️ 后端服务启动成功！
2023-11-02T11:14:16: ✌️ DB loaded
2023-11-02T11:14:16: ✌️ Init file down
2023-11-02T11:14:17: ✌️ Sentry loaded
2023-11-02T11:14:20: ✌️ Dependency Injector loaded
2023-11-02T11:14:21: ✌️ Express loaded
2023-11-02T11:14:21: ✌️ init data loaded
2023-11-02T11:14:21: ✌️ link deps loaded
2023-11-02T11:14:21: ✌️ init task loaded
2023-11-02T11:14:09:
2023-11-02T11:14:09:
2023-11-02T11:14:09: #
2023-11-02T11:14:09: # Fatal error in , line 0
2023-11-02T11:14:09: Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
2023-11-02T11:14:09: #
2023-11-02T11:14:09: #
2023-11-02T11:14:09: #
2023-11-02T11:14:09: #FailureMessage Object: 0x7f95ed0798
2023-11-02T11:14:09:
2023-11-02T11:14:09:
2023-11-02T11:14:09: #
2023-11-02T11:14:09: # Fatal error in , line 0
2023-11-02T11:14:09: # Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
2023-11-02T11:14:09: #
2023-11-02T11:14:09: #
2023-11-02T11:14:09: #
2023-11-02T11:14:09: #FailureMessage Object: 0x7fd5b96368

=====> 检测后台



[PM2][WARN] Applications schedule, public, panel not running, starting...
[PM2][WARN] App schedule has option 'wait_ready' set, waiting for app to be ready...
[PM2][WARN] App public has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [schedule] launched (1 instances)
[PM2][WARN] App panel has option 'wait_ready' set, waiting for app to be ready...


#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7ffff46658
/ql/shell/share.sh: line 308:  1017 Trace/breakpoint trap   pm2 startOrGracefulReload ecosystem.config.js

=====> 检测结束


## 执行结束... 2023-11-02 11:20:11 耗时 382 秒

**Comment by abandon-xyz** [comment]
root@QWRT:~# docker logs qinglong
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
复制一份 /ql/sample/config.sample.sh 为 /ql/data/config/config.sh，随后请按注释编辑你的配置文件：/ql/data/config/config.sh

'/ql/sample/config.sample.sh' -> '/ql/data/config/config.sh'

检测到config配置目录下不存在env.sh，创建一个空文件用于初始化...


复制一份 /ql/sample/task.sample.sh 为 /ql/data/config/task_before.sh

'/ql/sample/task.sample.sh' -> '/ql/data/config/task_before.sh'

复制一份 /ql/sample/task.sample.sh 为 /ql/data/config/task_after.sh

'/ql/sample/task.sample.sh' -> '/ql/data/config/task_after.sh'

复制一份 /ql/sample/extra.sample.sh 为 /ql/data/config/extra.sh

'/ql/sample/extra.sample.sh' -> '/ql/data/config/extra.sh'

复制一份 /ql/sample/auth.sample.json 为 /ql/data/config/auth.json

'/ql/sample/auth.sample.json' -> '/ql/data/config/auth.json'

复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'

复制一份 /ql/sample/notify.js 为 /ql/data/deps/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/deps/sendNotify.js'

复制一份 /ql/sample/notify.py 为 /ql/data/deps/notify.py

'/ql/sample/notify.py' -> '/ql/data/deps/notify.py'

======================2. 安装依赖========================

检测到旧的db目录，拷贝到data目录...


检测到旧的scripts目录，拷贝到data目录...


检测到旧的log目录，拷贝到data目录...


检测到旧的config目录，拷贝到data目录...


安装 /ql/data/scripts 依赖包...


   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 8.3.1 → 8.10.2.                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.10.2   │
   │                Run "pnpm add -g pnpm" to update.                 │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm

dependencies:
+ got 11.5.1 (13.0.0 is available)
+ nodemailer 6.8.0 (6.9.7 is available)
+ tough-cookie 4.0.0 (4.1.3 is available)
+ tunnel 0.0.6
+ ws 7.4.3 (8.14.2 is available)

devDependencies: skipped

Done in 10.3s

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动pm2服务========================

[PM2][WARN] Applications schedule, public, panel not running, starting...
[PM2][WARN] App schedule has option 'wait_ready' set, waiting for app to be ready...
[PM2][WARN] App public has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [schedule] launched (1 instances)
[PM2][WARN] App panel has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [public] launched (1 instances)
[PM2] App [panel] launched (1 instances)
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 215      │ 10s    │ 0    │ online    │ 0%       │ 101.1mb  │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 185      │ 15s    │ 0    │ online    │ 0%       │ 89.3mb   │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 184      │ 15s    │ 0    │ online    │ 0%       │ 80.8mb   │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
############################################################

容器启动成功...
############################################################

crond[260]: crond (busybox 1.36.1) started, log level 8
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
======================2. 安装依赖========================

检测到旧的db目录，拷贝到data目录...


检测到旧的scripts目录，拷贝到data目录...


检测到旧的log目录，拷贝到data目录...


检测到旧的config目录，拷贝到data目录...


Writing to /root/.config/pip/pip.conf

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动pm2服务========================

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2][WARN] Applications schedule, public, panel not running, starting...
[PM2][WARN] App schedule has option 'wait_ready' set, waiting for app to be ready...
[PM2][WARN] App public has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [schedule] launched (1 instances)
[PM2][WARN] App panel has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [public] launched (1 instances)


#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7fea5727b8
/ql/shell/share.sh: line 308:   108 Trace/breakpoint trap   pm2 startOrGracefulReload ecosystem.config.js
====================6. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...
############################################################

crond[205]: crond (busybox 1.36.1) started, log level 8

**Comment by abandon-xyz** [comment]
用2.10.13版本是正常的最新的2.16.X都不行

**Comment by Tunglies** [comment]
> 用2.10.13版本是正常的最新的2.16.X都不行

记得新老版本配置文件不同样，不适用旧配置搭建个新的试试呢。

**Comment by abandon-xyz** [comment]
> > 用2.10.13版本是正常的最新的2.16.X都不行
> 
> 记得新老版本配置文件不同样，不适用旧配置搭建个新的试试呢。

用了2.15.0的也可以，2.16.x的都不行，试过了

**Comment by whyour** [comment]
是不是玩客云之类的，参考 https://github.com/whyour/qinglong/issues/897#issuecomment-1239462706

**Comment by abandon-xyz** [comment]
> 是不是玩客云之类的，参考 [#897 (comment)](https://github.com/whyour/qinglong/issues/897#issuecomment-1239462706)

好的 谢谢！我是用的路由器，op系统。目前用2.15.0没问题了。

**Comment by lppsuixn** [comment]
同样的问题，x86 pve lxc容器里跑的docker

**Comment by alphandy79** [comment]
同样是升级到2.16.5，出现这个问题，全部重装了，数据新建了，然后群晖断电开机又出现了。不知道是哪个旧文件作怪

![image](https://github.com/whyour/qinglong/assets/137768524/3a84c113-626d-4710-b467-50d0106d79a2)

**Comment by Tunglies** [comment]
> 同样是升级到2.16.5，出现这个问题，全部重装了，数据新建了，然后群晖断电开机又出现了。不知道是哪个旧文件作怪
> 
> ![image](https://private-user-images.githubusercontent.com/137768524/320200382-3a84c113-626d-4710-b467-50d0106d79a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MTA5MTUsIm5iZiI6MTcxMjQxMDYxNSwicGF0aCI6Ii8xMzc3Njg1MjQvMzIwMjAwMzgyLTNhODRjMTEzLTYyNmQtNDcxMC1iNDY3LTUwZDAxMDZkNzlhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQxMzM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzY1OTdhNmI1MTBhM2IxYThhOGVjZjM1N2NkN2U5ODUzNDZiMzYyZjJhYjU4MmNlZTYwZWIzMGRhYTMwODBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tGO2OwjAVMkBDZnQZi_TItzVyp14CzGJ_u3ck7xYXdc)

issue 已经 closed 了。重新开 issue 并提供环境信息或者 log 供社区 view。

**Comment by linnvirgo** [comment]
> > 是不是玩客云之类的，参考[#897（评论）](https://github.com/whyour/qinglong/issues/897#issuecomment-1239462706)
> 
> 好的，谢谢！我是用的路由器，op系统。目前用2.15.0没问题了。

兄弟能不能把代码发一下，安装旧版一直出错，最新的装了打不开。。。
