### ISSUE TITLE
希望在青龙面板-日志管理  添加显示 日志(.log) 文件的大小

### ISSUE THREAD

**Issue by MistyMoonR** [whyour/qinglong#2169]
### Clear and concise description of the problem

有时候会做些测试和采集数据直接显示，生成日志可能膨胀非常快  

每次都要 SSH 进去并运行以下命令 查看 log日志大小，并控制下业务代码，避免log文件膨胀过快 导致 硬盘容量不够  
```
du -lh ~/ql/data/log
```
但这样会不太方便，所以希望 能在青龙面板上 可以直接看到 对应.log 文件的 大小。  

### Suggested solution

导航到：`日志管理 - [对应任务日志文件夹] - [时间].log`  

在此页面上会有个完整的路径名， 在 `删除按钮` 左边 加个 对应日志 的大小即可。  

再次非常感谢作者开源项目给广大使用者提供便利~  

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
2.17.0 已增加
