### ISSUE TITLE
多合一签到运行空白 手动运行基本上可以

### ISSUE THREAD

**Issue by study875** [whyour/qinglong#217]
多合一签到默认是早上6点进行，但是通常情况下无法进行签到，就显示为空白
![QQ截图20210530213112](https://user-images.githubusercontent.com/53926992/120106527-dac8aa00-c18f-11eb-8da8-cc096366fe62.jpg)
手动签到之后 会显示
JD_DailyBonus.js文件下载完毕
![QQ截图20210530213154](https://user-images.githubusercontent.com/53926992/120106538-e7e59900-c18f-11eb-9a14-43f81e99b560.jpg)
然后才会进行签到，是我这边网络问题吗

**Comment by whyour** [comment]
我看我的日志好像也有，不知道什么原因

**Comment by whyour** [comment]
你换个3点的时间或者其他时间试试
