### ISSUE TITLE
跑脚本时，遇到top: can't open 'stat': Permission denied

### ISSUE THREAD

**Issue by kingjing337** [whyour/qinglong#2170]
### Qinglong version

2.16.5

### Steps to reproduce

1、安装zerotermux apk

2、安装alpine

3、拉取青龙
set -x && echo -e "\n export QL_DIR=/ql\n export QL_BRANCH=master\n export LANG=zh_CN.UTF-8\n export TERMUX_APK_RELEASE=F-DROID\n export SHELL=/bin/bash\n export PNPM_HOME=/home/.local/share/pnpm\n export PATH=$PATH:/home/.local/share/pnpm:/home/.local/share/pnpm/global/5/node_modules\n" >> /etc/profile.d/ql_env.sh 

source /etc/profile && echo -e "nameserver 119.29.29.29\n nameserver 8.8.8.8" > /etc/resolv.conf

sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && apk update -f && apk upgrade && apk --no-cache add -f bash make nodejs npm coreutils moreutils git curl wget tzdata perl openssl nginx jq openssh python3 py3-pip

rm -rf /var/cache/apk/* && apk update && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone

npm config set registry https://registry.npmmirror.com && npm install -g pnpm && pnpm add -g pm2 ts-node typescript tslib && mkdir -p $QL_DIR

git clone -b $QL_BRANCH https://github.com/whyour/qinglong.git $QL_DIR 

cd $QL_DIR && cp -f .env.example .env && chmod 777 $QL_DIR/shell/*.sh && chmod 777 $QL_DIR/docker/*.sh && pnpm install --prod && mkdir -p $QL_DIR/static

git clone -b $QL_BRANCH https://github.com/whyour/qinglong-static.git $QL_DIR/static

ln -s /ql/docker/docker-entrypoint.sh /usr/bin/qinglong && qinglong

### What is expected?

希望帮我看看这种情况怎么解决？是不是我的第三步，安装青龙时，哪儿有问题，导致后来跑脚本出现报错。（如果我用其他人青龙2.10恢复包，则可以跑同样的脚本）

### What is actually happening?

![1](https://github.com/whyour/qinglong/assets/44162854/bbf40e80-8d21-495c-b2ca-4cd5945aa337)
![2](https://github.com/whyour/qinglong/assets/44162854/c656c531-cadf-46ec-a2e8-802f3112abce)
![3](https://github.com/whyour/qinglong/assets/44162854/d03fad7e-ba23-4495-bab2-0e2c3190a024)

我是手机安装zerotermux，用alpine搭建的青龙，跑KingRan脚本的时候报错，crypto-js依赖能够安装， crypto-js/sha1依赖不能安装。怎么解决这个问题或有什么思路么？求教。

### System Info

```shell
小米手机
```

**Comment by whyour** [comment]
拉去青龙第一个 set 命令，加上这两个 export
```sh
export NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules
export PYTHONUNBUFFERED=1
```

**Comment by kingjing337** [comment]
> 拉取青龙第一个 set 命令，加上这两个 export
> 
> ```shell
> export NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules
> export PYTHONUNBUFFERED=1
> ```

![yi yang](https://github.com/whyour/qinglong/assets/44162854/7be182d4-ec43-49f6-9853-228c15136c6a)
![微信图片_20231108001259](https://github.com/whyour/qinglong/assets/44162854/7dd0bd68-de88-4eb3-a188-1d1cf89919c4)

非常感谢大佬的回答，但是一样的问题仍旧存在呢~查询了整个网也没有结果...非常期待您的其他解决方法。

**Comment by whyour** [comment]
@kingjing337 
```shell
set -x && echo -e "\n export QL_DIR=/ql\n export QL_BRANCH=master\n export LANG=zh_CN.UTF-8\n export TERMUX_APK_RELEASE=F-DROID\n export SHELL=/bin/bash\n export PNPM_HOME=/root/.local/share/pnpm\n export PATH=$PATH:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules\nexport NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules\nexport PYTHONUNBUFFERED=1" >>/etc/profile.d/ql_env.sh

source /etc/profile && echo -e "nameserver 119.29.29.29\n nameserver 8.8.8.8" >/etc/resolv.conf
sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && apk update -f && apk upgrade && apk --no-cache add -f netcat-openbsd  netcat-openbsd bash make nodejs npm coreutils moreutils git curl wget tzdata perl openssl nginx jq openssh python3 py3-pip

rm -rf /var/cache/apk/* && apk update && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" >/etc/timezone

npm config set registry https://registry.npmmirror.com && npm install -g pnpm@8.3.1 && pnpm add -g pm2 tsx && mkdir -p $QL_DIR

git clone -b $QL_BRANCH https://github.com/whyour/qinglong.git $QL_DIR

cd $QL_DIR && cp -f .env.example .env && chmod 777 $QL_DIR/shell/*.sh && chmod 777 $QL_DIR/docker/*.sh && pnpm install --prod && mkdir -p $QL_DIR/static

git clone -b $QL_BRANCH https://github.com/whyour/qinglong-static.git $QL_DIR/static

ln -s /ql/docker/docker-entrypoint.sh /usr/bin/qinglong && qinglong

```

**Comment by whyour** [comment]
`crypto-js/sha1` 属于 `crypto-js`，不需要单独安装

**Comment by kingjing337** [comment]
> @kingjing337
> 
> ```shell
> set -x && echo -e "\n export QL_DIR=/ql\n export QL_BRANCH=master\n export LANG=zh_CN.UTF-8\n export TERMUX_APK_RELEASE=F-DROID\n export SHELL=/bin/bash\n export PNPM_HOME=/root/.local/share/pnpm\n export PATH=$PATH:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules\nexport NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules\nexport PYTHONUNBUFFERED=1" >>/etc/profile.d/ql_env.sh
> 
> source /etc/profile && echo -e "nameserver 119.29.29.29\n nameserver 8.8.8.8" >/etc/resolv.conf
> sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && apk update -f && apk upgrade && apk --no-cache add -f netcat-openbsd  netcat-openbsd bash make nodejs npm coreutils moreutils git curl wget tzdata perl openssl nginx jq openssh python3 py3-pip
> 
> rm -rf /var/cache/apk/* && apk update && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" >/etc/timezone
> 
> npm config set registry https://registry.npmmirror.com && npm install -g pnpm@8.3.1 && pnpm add -g pm2 tsx && mkdir -p $QL_DIR
> 
> git clone -b $QL_BRANCH https://github.com/whyour/qinglong.git $QL_DIR
> 
> cd $QL_DIR && cp -f .env.example .env && chmod 777 $QL_DIR/shell/*.sh && chmod 777 $QL_DIR/docker/*.sh && pnpm install --prod && mkdir -p $QL_DIR/static
> 
> git clone -b $QL_BRANCH https://github.com/whyour/qinglong-static.git $QL_DIR/static
> 
> ln -s /ql/docker/docker-entrypoint.sh /usr/bin/qinglong && qinglong
> ```

已完美解决，我大概明白我的错误了，谢谢您~！~

**Comment by MrNiebit** [comment]
我的和你的情况一样，为啥调度不执行

**Comment by sw78159** [comment]
> > @kingjing337
> > ```shell
> > set -x && echo -e "\n export QL_DIR=/ql\n export QL_BRANCH=master\n export LANG=zh_CN.UTF-8\n export TERMUX_APK_RELEASE=F-DROID\n export SHELL=/bin/bash\n export PNPM_HOME=/root/.local/share/pnpm\n export PATH=$PATH:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules\nexport NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules\nexport PYTHONUNBUFFERED=1" >>/etc/profile.d/ql_env.sh
> > 
> > source /etc/profile && echo -e "nameserver 119.29.29.29\n nameserver 8.8.8.8" >/etc/resolv.conf
> > sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && apk update -f && apk upgrade && apk --no-cache add -f netcat-openbsd  netcat-openbsd bash make nodejs npm coreutils moreutils git curl wget tzdata perl openssl nginx jq openssh python3 py3-pip
> > 
> > rm -rf /var/cache/apk/* && apk update && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" >/etc/timezone
> > 
> > npm config set registry https://registry.npmmirror.com && npm install -g pnpm@8.3.1 && pnpm add -g pm2 tsx && mkdir -p $QL_DIR
> > 
> > git clone -b $QL_BRANCH https://github.com/whyour/qinglong.git $QL_DIR
> > 
> > cd $QL_DIR && cp -f .env.example .env && chmod 777 $QL_DIR/shell/*.sh && chmod 777 $QL_DIR/docker/*.sh && pnpm install --prod && mkdir -p $QL_DIR/static
> > 
> > git clone -b $QL_BRANCH https://github.com/whyour/qinglong-static.git $QL_DIR/static
> > 
> > ln -s /ql/docker/docker-entrypoint.sh /usr/bin/qinglong && qinglong
> > ```
> 
> 已完美解决，我大概明白我的错误了，谢谢您~！~

我和你的情况差不多也是手机安装zerotermux，用alpine搭建的青龙。你是怎么解决的？
