### ISSUE TITLE
请问下青龙正式版 v2.16.5的依赖安装问题！

### ISSUE THREAD

**Issue by CheZhangLEO** [whyour/qinglong#2171]
### Clear and concise description of the problem

就是安装依赖的时候忘记点拆分了，导致现在一直在现实安装“curl jq”这个没有的依赖，而且一直显示安装，不想其他凭空打出来的依赖会安装失败，这样一直安装会卡着队列，导致我其他想安装的依赖无法安装，请问怎么解决一下？而且删除和强制删除没有作用，强制删除没了之后刷新下网页发现还在。

### Suggested solution

求大佬

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by THERentropy** [comment]
直接强制删除

**Comment by klcb2010** [comment]
强制删除没问题的

**Comment by sunyiex** [comment]
也有同样的问题，请问解决了吗？

**Comment by sunyiex** [comment]
通过sqlite直接删除了库里的数据，之后重启解决了

**Comment by whyour** [comment]
强制删除就行
