### ISSUE TITLE
2.16.5升级后，运行东东农场脚本自动跳出。。。。

### ISSUE THREAD

**Issue by dreamfrog7** [whyour/qinglong#2174]
### Qinglong version

2.16.5

### Steps to reproduce

1、拉库6dylan6，运行东东农场相关脚本发现有自动跳出停止运行脚本的情况。
 提示：
【京东账号 】 

初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"demotionExp":{"label":"base","hasSetCrowd":false,"bucket":0,"buriedStr":"tsabtest|base64|ZG9uZ2RvbmdmYXJtXzIyMDI2fGJhc2U|tsabtest","running":false,"unionSwitch":0,"expId":"dongdongfarm_22026"},"code":"6","bizCode":null,"todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"enableSign":false,"sysTime":1699771004040,"minSupportAPPVersion":"8.5.4","message":null}

CHRONOCAT 服务的 CHRONOCAT_URL 或 CHRONOCAT_QQ 未设置!!
取消推送
Bark APP发送通知消息成功🎉
2、发现问题就是水果种成功了，或者是异常都会跳出，不再继续运行了

### What is expected?

能够跳过报错，下面的账号可以继续运行脚本

### What is actually happening?

自动停止跳出脚本运行

**Comment by whyour** [comment]
脚本问题找作者
