### ISSUE TITLE
能否支持多用户登录

### ISSUE THREAD

**Issue by shexiaobin** [whyour/qinglong#2177]
### Qinglong version

其他用户登录，就会被挤下来，很麻烦

### Steps to reproduce

![image](https://github.com/whyour/qinglong/assets/26622879/2b2c9bf1-08d4-451c-b68f-e590930929b8)

### What is expected?

允许多用户登录

### What is actually happening?

无

**Comment by whyour** [comment]
repeat https://github.com/whyour/qinglong/issues/1947
