### ISSUE TITLE
push+推送消息失败，求作者大佬更新支持push+新的token

### ISSUE THREAD

**Issue by 86xqs** [whyour/qinglong#218]
push+新用户的token长度都是30多个字符的了，推消息失败提示为：“**push+发送一对一通知消息失败：用户信息状态不合法**”求作者更新支持新的token。

**Comment by BIGBbox** [comment]
> push新的token是30多个字符的，失败提示为：“**push+发送一对一通知消息失败：用户信息状态不合法**”求作者更新支持。

重新登陆plus+,然后重新生成token

**Comment by 86xqs** [comment]
> > push新的token是30多个字符的，失败提示为：“**push+发送一对一通知消息失败：用户信息状态不合法**”求作者更新支持。
> 
> 重新登陆plus+,然后重新生成token

试过N次了，这不是重新生成token的问题，不管更换多少次token长度是不变的，现在注册push+ token都是这个的长度，你们还能用是因为你们注册的早。

**Comment by whyour** [comment]
@86xqs 晚点修复

**Comment by whyour** [comment]
> > > push新的token是30多个字符的，失败提示为：“**push+发送一对一通知消息失败：用户信息状态不合法**”求作者更新支持。
> > 
> > 
> > 重新登陆plus+,然后重新生成token
> 
> 试过N次了，这不是重新生成token的问题，不管更换多少次token长度是不变的，现在注册push+ token都是这个的长度，你们还能用是因为你们注册的早。

我看发通知的脚本没验证token长度啊， 你的错误信息是  http://www.pushplus.plus/send  这个接口返回的吧

**Comment by BIGBbox** [comment]
> > > > push新的token是30多个字符的，失败提示为：“**push+发送一对一通知消息失败：用户信息状态不合法**”求作者更新支持。
> 
> > > 
> 
> > > 
> 
> > > 重新登陆plus+,然后重新生成token
> 
> > 
> 
> > 试过N次了，这不是重新生成token的问题，不管更换多少次token长度是不变的，现在注册push+ token都是这个的长度，你们还能用是因为你们注册的早。
> 
> 
> 
> 我看发通知的脚本没验证token长度啊， 你的错误信息是  http://www.pushplus.plus/send  这个接口返回的吧

应该是plus+报的错，

**Comment by whyour** [comment]
@BIGBbox 那你意思是让我更新啥呢

**Comment by BIGBbox** [comment]
> @BIGBbox 那你意思是让我更新啥呢

不是我不是我🥺🥺

**Comment by whyour** [comment]
@BIGBbox 这个地址是不是变了，我登录了下 是   http://pushplus.hxtrip.com/send

**Comment by BIGBbox** [comment]
> @BIGBbox 这个地址是不是变了，我登录了下 是 http://pushplus.hxtrip.com/send

你这个连接我打开乱码了

plus+给的链接不是这两个嘛
<img width="321" alt="image" src="https://user-images.githubusercontent.com/52786394/120198453-ae2a9600-c254-11eb-846e-6e0ee2f2ee51.png">
<img width="977" alt="image" src="https://user-images.githubusercontent.com/52786394/120198494-b97dc180-c254-11eb-8c7a-9605d2e510f1.png">

**Comment by 86xqs** [comment]
> @BIGBbox 这个地址是不是变了，我登录了下 是 http://pushplus.hxtrip.com/send


原来有两个一样的网站啊，我用的是push+:http://pushplus.hxtrip.com/index，不好意思是我草率了，我刚试了http://www.pushplus.plus/的token推送没问题。

**Comment by 86xqs** [comment]
> > > > push新的token是30多个字符的，失败提示为：“**push+发送一对一通知消息失败：用户信息状态不合法**”求作者更新支持。
> > > 
> > > 
> > > 重新登陆plus+,然后重新生成token
> > 
> > 
> > 试过N次了，这不是重新生成token的问题，不管更换多少次token长度是不变的，现在注册push+ token都是这个的长度，你们还能用是因为你们注册的早。
> 
> 我看发通知的脚本没验证token长度啊， 你的错误信息是 http://www.pushplus.plus/send 这个接口返回的吧

原来有两个一样的网站啊，我用的是push+:http://pushplus.hxtrip.com/index，不好意思是我草率了，我刚试了http://www.pushplus.plus/的token推送没问题。

**Comment by BIGBbox** [comment]
> > > > > push新的token是30多个字符的，失败提示为：“**push+发送一对一通知消息失败：用户信息状态不合法**”求作者更新支持。
> 
> > > > 
> 
> > > > 
> 
> > > > 重新登陆plus+,然后重新生成token
> 
> > > 
> 
> > > 
> 
> > > 试过N次了，这不是重新生成token的问题，不管更换多少次token长度是不变的，现在注册push+ token都是这个的长度，你们还能用是因为你们注册的早。
> 
> > 
> 
> > 我看发通知的脚本没验证token长度啊， 你的错误信息是 http://www.pushplus.plus/send 这个接口返回的吧
> 
> 
> 
> 原来有两个一样的网站啊，我用的是push+:http://pushplus.hxtrip.com/index，不好意思是我草率了，我刚试了http://www.pushplus.plus/的token推送没问题。

😅😅

**Comment by BIGBbox** [comment]
> > > > > > push新的token是30多个字符的，失败提示为：“**push+发送一对一通知消息失败：用户信息状态不合法**”求作者更新支持。
> > 
> > > > > 
> > 
> > > > > 
> > 
> > > > > 重新登陆plus+,然后重新生成token
> > 
> > > > 
> > 
> > > > 
> > 
> > > > 试过N次了，这不是重新生成token的问题，不管更换多少次token长度是不变的，现在注册push+ token都是这个的长度，你们还能用是因为你们注册的早。
> > 
> > > 
> > 
> > > 我看发通知的脚本没验证token长度啊， 你的错误信息是 http://www.pushplus.plus/send 这个接口返回的吧
> > 
> > 
> > 
> > 原来有两个一样的网站啊，我用的是push+:http://pushplus.hxtrip.com/index，不好意思是我草率了，我刚试了http://www.pushplus.plus/的token推送没问题。
> 
> 😅😅可以close掉了
