### ISSUE TITLE
登录地址获取失败

### ISSUE THREAD

**Issue by kokpk** [whyour/qinglong#2180]
### Qinglong version

2.16.5

### Steps to reproduce

登录后查看登录日志登录地址和登录IP都无法获取。

### What is expected?

怎么才能获取正常的登录IP

### What is actually happening?

![image](https://github.com/whyour/qinglong/assets/37227634/01c97ddc-cce0-4218-b9b1-63e9022f4ca6)

**Comment by kokpk** [comment]
直连登录一样获取不到IP

**Comment by kokpk** [comment]
跪求大佬解答

**Comment by otherbanana** [comment]
同样的问题，解决了吗？

**Comment by whyour** [comment]
2.17.0 已修复
