### ISSUE TITLE
建议优化一下日志列表

### ISSUE THREAD

**Issue by kuilei0926** [whyour/qinglong#2181]
### Clear and concise description of the problem

目前日志查看只是一个列表，如果日志较多的话想要找到某个时间点的日志比较麻烦

### Suggested solution

建议可以通过 日期，运行时间段等条件筛选

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
日志管理里 可以通过时间点搜索
