### ISSUE TITLE
部署/更新后一直启动中转圈

### ISSUE THREAD

**Issue by syxf** [whyour/qinglong#2183]
### Qinglong version

2.16.5

### Steps to reproduce

部署完成/更新以后浏览器打不开青龙面板

### What is expected?

正常打开面板

### What is actually happening?

作者你好。我今天两台阿里云的服务器，一台是老版本（应该是2.15.x，具体记不清了）更新到2.16.5的，另一台是全新安装的docker和青龙，都遇到了面板打不开的问题，地址自动跳转/error，显示“启动中，请稍后”。
![图片](https://github.com/whyour/qinglong/assets/72773517/babdcdc8-f3ea-4949-8f7d-e26ba8e001e4)

尝试过ql check了，没能解决，
![图片](https://github.com/whyour/qinglong/assets/72773517/f7250aef-e774-4d29-baad-c1b03d5dc346)
![图片](https://github.com/whyour/qinglong/assets/72773517/d969996a-ad1e-40a6-9df7-0d188ef8c322)

也尝试过这个，同样没能解决https://github.com/whyour/qinglong/issues/897#issuecomment-1239462706

### System Info

```shell
Ubuntu 20.04.4
```

**Comment by whyour** [comment]
容器内执行 pm2 logs 看看

**Comment by vip198926** [comment]
我的也出现同样的问题，

``root@qinglong:/ql $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        |   errno: -30,
PM2        |   code: 'EROFS',
PM2        |   syscall: 'open',
PM2        |   path: '/root/.pm2/logs/panel-out.log'
PM2        | }
PM2        |     at God.logAndGenerateError (/root/.local/share/pnpm/global/5/.pnpm/pm2@5.3.0/node_modules/pm2/lib/God/Methods.js:34:15)
PM2        |     at /root/.local/share/pnpm/global/5/.pnpm/pm2@5.3.0/node_modules/pm2/lib/God/ForkMode.js:87:13
PM2        |     at wrapper (/root/.local/share/pnpm/global/5/.pnpm/async@3.2.4/node_modules/async/internal/once.js:12:16)
PM2        |     at WriteStream.next (/root/.local/share/pnpm/global/5/.pnpm/async@3.2.4/node_modules/async/waterfall.js:96:20)
PM2        |     at WriteStream.<anonymous> (/root/.local/share/pnpm/global/5/.pnpm/async@3.2.4/node_modules/async/internal/onlyOnce.js:12:16)
PM2        |     at Object.onceWrapper (node:events:629:26)
PM2        |     at WriteStream.emit (node:events:514:28)
PM2        |     at WriteStream.emit (node:domain:489:12)
PM2        |     at emitErrorNT (node:internal/streams/destroy:151:8)
PM2        |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-10-17T16:32:58: ✌️ 定时服务启动成功！
0|schedule | 2023-10-17T16:58:37: ✌️ 定时服务启动成功！
0|schedule | 2023-10-18T18:22:11: ✌️ 定时服务启动成功！
0|schedule | 2023-10-18T21:36:04: ✌️ 定时服务启动成功！
0|schedule | 2023-11-19T00:17:34: ✌️ 定时服务启动成功！
0|schedule | 2023-11-19T00:17:33: ✌️ 定时服务启动成功！
0|schedule | 2023-11-19T00:17:34: ✌️ 定时服务启动成功！
0|schedule | 2023-11-19T00:17:34: ✌️ 定时服务启动成功！
0|schedule | 2023-11-19T00:17:34: ✌️ 定时服务启动成功！
0|schedule | 2023-11-19T00:17:34: ✌️ 定时服务启动成功！
0|schedule | 2023-11-19T00:17:34: ✌️ 定时服务启动成功！
0|schedule | 2023-11-19T00:17:34: ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-11-19T00:17:34: ✌️ Sentry loaded
1|public   | 2023-11-19T00:17:36: ✌️ DB loaded
1|public   | 2023-11-19T00:17:36: ✌️ 公共服务启动成功！
1|public   | 2023-11-19T00:17:33: ✌️ Sentry loaded
1|public   | 2023-11-19T00:17:41: ✌️ DB loaded
1|public   | 2023-11-19T00:17:41: ✌️ 公共服务启动成功！
1|public   | 2023-11-19T00:17:34: ✌️ Sentry loaded
1|public   | 2023-11-19T00:17:41: ✌️ DB loaded
1|public   | 2023-11-19T00:17:41: ✌️ 公共服务启动成功！
1|public   | 2023-11-19T00:17:33: ✌️ Sentry loaded
1|public   | 2023-11-19T00:17:36: ✌️ DB loaded
1|public   | 2023-11-19T00:17:36: ✌️ 公共服务启动成功！
1|public   | 2023-11-19T00:17:34: ✌️ Sentry loaded
1|public   | 2023-11-19T00:17:36: ✌️ DB loaded
1|public   | 2023-11-19T00:17:36: ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-11-19T00:17:42: ✌️ Dependency Injector loaded
2|panel    | 2023-11-19T00:17:43: ✌️ Express loaded
2|panel    | 2023-11-19T00:17:43: ✌️ init data loaded
2|panel    | 2023-11-19T00:17:43: ✌️ link deps loaded
2|panel    | 2023-11-19T00:17:43: ✌️ init task loaded
2|panel    | 2023-11-19T00:17:44: ✌️ 后端服务启动成功！
2|panel    | 2023-11-19T00:17:39: ✌️ DB loaded
2|panel    | 2023-11-19T00:17:39: ✌️ Init file down
2|panel    | 2023-11-19T00:17:40: ✌️ Sentry loaded
2|panel    | 2023-11-19T00:17:42: ✌️ Dependency Injector loaded
2|panel    | 2023-11-19T00:17:43: ✌️ Express loaded
2|panel    | 2023-11-19T00:17:43: ✌️ init data loaded
2|panel    | 2023-11-19T00:17:43: ✌️ link deps loaded
2|panel    | 2023-11-19T00:17:43: ✌️ init task loaded
2|panel    | 2023-11-19T00:17:44: ✌️ 后端服务启动成功！

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-11-22T01:28:00:   <rejected> Error: EROFS: read-only file system, open '/ql/data/log/6dylan6_jdpro/2023-11-22-01-13-19.log'
2|panel    | 2023-11-22T01:28:00:       at Object.openSync (node:fs:603:3)
2|panel    | 2023-11-22T01:28:00:       at Object.writeFileSync (node:fs:2324:35)
2|panel    | 2023-11-22T01:28:00:       at Object.appendFileSync (node:fs:2386:6)
2|panel    | 2023-11-22T01:28:00:       at Object.onError (/ql/back/services/subscription.ts:193:12)
2|panel    | 2023-11-22T01:28:00:       at /ql/back/services/schedule.ts:106:11 {
2|panel    | 2023-11-22T01:28:00:     errno: -30,
2|panel    | 2023-11-22T01:28:00:     syscall: 'open',
2|panel    | 2023-11-22T01:28:00:     code: 'EROFS',
2|panel    | 2023-11-22T01:28:00:     path: '/ql/data/log/6dylan6_jdpro/2023-11-22-01-13-19.log'
2|panel    | 2023-11-22T01:28:00:   },
2|panel    | 2023-11-22T01:28:00:   [Symbol(async_id_symbol)]: 86307,
2|panel    | 2023-11-22T01:28:00:   [Symbol(trigger_async_id_symbol)]: 86301,
2|panel    | 2023-11-22T01:28:00:   [Symbol(kResourceStore)]: undefined
2|panel    | 2023-11-22T01:28:00: }

**Comment by a412908937** [comment]
解决了吗  我也是这样，重启服务器后一直 启动中， check 也试过了

**Comment by vadonmo** [comment]
> 容器内执行 pm2 logs 看看

这个疯狂刷代码，貌似有个报错，来不及复制

**Comment by vadonmo** [comment]
> 容器内执行 pm2 logs 看看

![image](https://github.com/whyour/qinglong/assets/8103489/93e4b899-3d03-4c0a-a549-5ad3a8468bdf)

**Comment by crane168** [comment]
> > 容器内执行 pm2 logs 看看
> 
> ![image](https://private-user-images.githubusercontent.com/8103489/293619616-93e4b899-3d03-4c0a-a549-5ad3a8468bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTM4MjMsIm5iZiI6MTcyOTA1MzUyMywicGF0aCI6Ii84MTAzNDg5LzI5MzYxOTYxNi05M2U0Yjg5OS0zZDAzLTRjMGEtYTU0OS01YWQzYTg0NjhiZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDQzODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVlNmMzMWU0NmQ2YzQyYmY5NTRkOGNiNjNjMWYyYjAzYmUxYWM5ZjNiOTAzMTY4MWUyMTE5NjFiOGYwNTVhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._Y1dDjWRWWUzn-aSKncmMv1mn7cOxTCI8UOBZ68hAxw)

哈喽，这个处理了吗？我这现在也是这个错误
