### ISSUE TITLE
无法使用 xxx.eu.org 域名作为本项目电报机器人通知的反代地址

### ISSUE THREAD

**Issue by leic4u** [whyour/qinglong#2189]
### Qinglong version

2.16.5

### Steps to reproduce

参见：https://github.com/whyour/qinglong/issues/851#issuecomment-1833790883 和 https://github.com/whyour/qinglong/issues/851#issuecomment-1833875079

使用两个 `xxx.eu.org` 作为反代地址测试都失败了，用 `xxx.cn` 和 `xxx.run` 都成功了。（其他项目中使用 `xxx.eu.org` 是可以正常通知的，如 ddns-go 项目）

面板系统设置：
![image](https://github.com/whyour/qinglong/assets/32786903/fef3ca36-2f7a-49f9-b24b-386c5cdfd588)

同时，拉取的多个脚本库中的 sendnotify 脚本，也无法使用 `xxx.eu.org` 域名作为 TG 的反代地址。

感觉应该不是脚本问题？应该可能是环境问题？（纯瞎猜

### What is expected?

使用  `xxx.eu.org` 作为 TG 的反代地址，可以正常发送通知。

### What is actually happening?

报错：RequestError: read ECONNRESET

**Comment by whyour** [comment]
http 还是 https

**Comment by leic4u** [comment]
> http 还是 https

填写的地方是不能填 `http` 或者 `https` 的，这个应该是脚本中定义的。

我看了下拉取的脚本库，是用的 `https`。
![image](https://github.com/whyour/qinglong/assets/32786903/05332211-5567-4387-90bb-ece5e08dc999)


面板系统设置用的我不知道在哪看，翻了下本仓库里面的 [sendNotify.js](https://github.com/whyour/qinglong/blob/c6a25e5359f1e9fb3b4c7799ac8162e04a1b5901/sample/notify.js#L648) 文件，也是 `https`。

**Comment by whyour** [comment]
> > http 还是 https
> 
> 填写的地方是不能填 `http` 或者 `https` 的，这个应该是脚本中定义的。
> 
> 我看了下拉取的脚本库，是用的 `https`。 ![image](https://private-user-images.githubusercontent.com/32786903/286977762-05332211-5567-4387-90bb-ece5e08dc999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTgwODAsIm5iZiI6MTcwMTM1Nzc4MCwicGF0aCI6Ii8zMjc4NjkwMy8yODY5Nzc3NjItMDUzMzIyMTEtNTU2Ny00Mzg3LTkwYmItZWNlNWUwOGRjOTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE1MjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OWUzOGIzYmRhODE4OTJkZDE0NjI1NjlkNjJmOTRmZjA1YWY5MTRlZTIzNzA5YmU1NTljNzRlZWM0MTExY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Df9IPGunEQNszAhC05FLNXwTvQqFe_BXGBMwwfQl4Uw)
> 
> 面板系统设置用的我不知道在哪看，翻了下本仓库里面的 [notify.js](https://github.com/whyour/qinglong/blob/c6a25e5359f1e9fb3b4c7799ac8162e04a1b5901/sample/notify.js#L648) 文件，也是 `https`。

我意思你的域名是 http 还是 https

**Comment by leic4u** [comment]
> 我意思你的域名是 http 还是 https

是在 Cloudflare Worker 部署的以下代码：
```
/**
 * Helper functions to check if the request uses
 * corresponding method.
 *
 */
const Method = (method) => (req) => req.method.toLowerCase() === method.toLowerCase();
const Get = Method('get');
const Post = Method('post');

const Path = (regExp) => (req) => {
	const url = new URL(req.url);
	const path = url.pathname;
	return path.match(regExp) && path.match(regExp)[0] === path;
};

/*
 * The regex to get the bot_token and api_method from request URL
 * as the first and second backreference respectively.
 */
const URL_PATH_REGEX = /^\/bot(?<bot_token>[^/]+)\/(?<api_method>[a-z]+)/i;

/**
 * Router handles the logic of what handler is matched given conditions
 * for each request
 */
class Router {
	constructor() {
		this.routes = [];
	}

	handle(conditions, handler) {
		this.routes.push({
			conditions,
			handler,
		});
		return this;
	}

	get(url, handler) {
		return this.handle([Get, Path(url)], handler);
	}

	post(url, handler) {
		return this.handle([Post, Path(url)], handler);
	}

	all(handler) {
		return this.handler([], handler);
	}

	route(req) {
		const route = this.resolve(req);

		if (route) {
			return route.handler(req);
		}

		const description = 'No matching route found';
		const error_code = 404;

		return new Response(
			JSON.stringify({
				ok: false,
				error_code,
				description,
			}),
			{
				status: error_code,
				statusText: description,
				headers: {
					'content-type': 'application/json',
				},
			}
		);
	}

	/**
	 * It returns the matching route that returns true
	 * for all the conditions if any.
	 */
	resolve(req) {
		return this.routes.find((r) => {
			if (!r.conditions || (Array.isArray(r) && !r.conditions.length)) {
				return true;
			}

			if (typeof r.conditions === 'function') {
				return r.conditions(req);
			}

			return r.conditions.every((c) => c(req));
		});
	}
}

/**
 * Sends a POST request with JSON data to Telegram Bot API
 * and reads in the response body.
 * @param {Request} request the incoming request
 */
async function handler(request) {
	// Extract the URl method from the request.
	const { url, ..._request } = request;

	const { pathname: path, search } = new URL(url);

	// Leave the first match as we are interested only in backreferences.
	const { bot_token, api_method } = path.match(URL_PATH_REGEX).groups;

	// Build the URL
	const api_url = 'https://api.telegram.org/bot' + bot_token + '/' + api_method + search;

	// Get the response from API.
	const response = await fetch(api_url, _request);

	const result = await response.text();

	const res = new Response(result, _request);

	res.headers.set('Content-Type', 'application/json');

	return res;
}

/**
 * Handles the incoming request.
 * @param {Request} request the incoming request.
 */
async function handleRequest(request) {
	const r = new Router();
	r.get(URL_PATH_REGEX, (req) => handler(req));
	r.post(URL_PATH_REGEX, (req) => handler(req));

	const resp = await r.route(request);
	return resp;
}

/**
 * Hook into the fetch event.
 */
addEventListener('fetch', (event) => {
	event.respondWith(handleRequest(event.request));
});
```

**Comment by whyour** [comment]
> > 你把 notify.js 里的 https 改成 http 试试，如果可以，后面会把系统设置里的 https 也默认去掉
> 
> 是在脚本管理里面吗？
> 
> 没有搜到 `notify.js` ，是不是修改 `notify.py` ？
> 
> ![image](https://private-user-images.githubusercontent.com/32786903/286984978-8dc55ff4-61c4-4d03-b20f-ced8b96195bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTkzMjEsIm5iZiI6MTcwMTM1OTAyMSwicGF0aCI6Ii8zMjc4NjkwMy8yODY5ODQ5NzgtOGRjNTVmZjQtNjFjNC00ZDAzLWIyMGYtY2VkOGI5NjE5NWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE1NDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OGNjYWJmODlkODY5ZTFhN2M2NDc1ODQ2Yzg0MTRhM2ViOTRiZGE4MWQzMDIzYjFjZTRhZjdlNGU0NDQ3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.teYW6j_VgyRt-9XXCG9KRSmBk2VztbOpKV6JphakLPM)

js 脚本用 sendNotify.js， py 脚本用 notify.py

**Comment by taozhiyu** [comment]
不清楚是否有效，但是我是config.sh里设置的。。。（因为方便脚本读取）

**Comment by denniszzg** [comment]
> 2.17.0 已修复，TG_API_HOST 要带 http 或者 https

感谢开发者的工作，提供这么优秀的软件。

我是国内机器ubuntu22.04.4，青龙版本2.17.1，发 tg 通知的问题经测试如下：

系统设置 - telegramBotApiHost - https://反代地址 --> 系统测试发送OK

配置文件 - export TG_API_HOST="https://反代地址" --> 定时任务发送消息失败

修改为：export TG_API_HOST="反代地址" --> 定时任务发送消息成功（就是不带https://）

供参考。

**Comment by nsv2051** [comment]
> > 2.17.0 已修复，TG_API_HOST 要带 http 或者 https
> 
> 感谢开发者的工作，提供这么优秀的软件。
> 
> 我是国内机器ubuntu22.04.4，青龙版本2.17.1，发 tg 通知的问题经测试如下：
> 
> 系统设置 - telegramBotApiHost - [https://反代地址](https://%E5%8F%8D%E4%BB%A3%E5%9C%B0%E5%9D%80) --> 系统测试发送OK
> 
> 配置文件 - export TG_API_HOST="[https://反代地址](https://%E5%8F%8D%E4%BB%A3%E5%9C%B0%E5%9D%80)" --> 定时任务发送消息失败
> 
> 修改为：export TG_API_HOST="反代地址" --> 定时任务发送消息成功（就是不带https://）
> 
> 供参考。

> ？在对比工具看下有什么不一样，左边是最新的

我也遇到相同问题，但我的js推送用的这个[库](https://github.com/ccwav/QLScript2)里修改过的sendNotify.js文件，py推送用的原版notify.py文件
不同作者使用的推送依赖内容很有可能出现差别，我的解决办法是在配置文件中填写不带前缀的反代地址，例：aaa.bbb.ccc
然后在deps中对推送依赖文件做出统一的修改，适配配置文件中的内容，然后再分发到各个库的目录中，目前推送没有问题了
之所以保持配置文件中的设置是因为我使用的部分加密脚本连带推送部分一起加密了，他们只适配了之前的格式，带前缀的格式读取后无法正常推送，你可以根据自己的情况做选择
notify.py：
![image](https://github.com/whyour/qinglong/assets/39900381/942b82fc-78f2-4430-9e60-2b4ff5629c64)
sendNotify.js
![image](https://github.com/whyour/qinglong/assets/39900381/1291565d-fab2-4d52-9f30-86d722fec547)

**Comment by seryte** [comment]
遇到了一样的问题
最新版[v2.17.3]，仍无法使用 @whyour 
<img width="971" alt="image" src="https://github.com/whyour/qinglong/assets/17977783/1d7aace2-dfe5-447c-8ab8-a0d606815b8f">

**Comment by nsv2051** [comment]
> 遇到了一样的问题 最新版[v2.17.3]，仍无法使用 @whyour <img alt="image" width="971" src="https://private-user-images.githubusercontent.com/17977783/320337323-1d7aace2-dfe5-447c-8ab8-a0d606815b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDg3MDQsIm5iZiI6MTcxMjU0ODQwNCwicGF0aCI6Ii8xNzk3Nzc4My8zMjAzMzczMjMtMWQ3YWFjZTItZGZlNS00NDdjLThhYjgtYTBkNjA2ODE1YjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAzNTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NTE1MjhmNjQxNjg5YjBkYWVkZmQyYTg2YWE4MTlkOTg4ZTg1NzI2YWIwNjE5ODBiZDdiYjc4NzUzN2Q0YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._H1vONpBKwCSCS85xXXHwNtrgp_GUDXlpmfj1Ijl5cQ"> config.sh内加http或https也报错。无法使用 <img alt="image" width="995" src="https://private-user-images.githubusercontent.com/17977783/320339067-f28bbe58-da40-44d1-a3f0-209b3f91a0a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDg3MDQsIm5iZiI6MTcxMjU0ODQwNCwicGF0aCI6Ii8xNzk3Nzc4My8zMjAzMzkwNjctZjI4YmJlNTgtZGE0MC00NGQxLWEzZjAtMjA5YjNmOTFhMGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAzNTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMjMwNjI3NWE1MWQxODJiOTdkMDIzYjUwZWE5ZTczNjM1YzYxMmNkZDIyMzU1ZjYzOGIyODc4MmYzMDE4MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g2m332bt4ZtLJCNHdAV_qFtjKQZClXeRRHEKlFatxqk">

你可以试试换个反代的域名，eu.org貌似被污染了

**Comment by seryte** [comment]
> > 遇到了一样的问题 最新版[v2.17.3]，仍无法使用 @whyour <img alt="image" width="971" src="https://private-user-images.githubusercontent.com/17977783/320337323-1d7aace2-dfe5-447c-8ab8-a0d606815b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDg3MDQsIm5iZiI6MTcxMjU0ODQwNCwicGF0aCI6Ii8xNzk3Nzc4My8zMjAzMzczMjMtMWQ3YWFjZTItZGZlNS00NDdjLThhYjgtYTBkNjA2ODE1YjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAzNTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NTE1MjhmNjQxNjg5YjBkYWVkZmQyYTg2YWE4MTlkOTg4ZTg1NzI2YWIwNjE5ODBiZDdiYjc4NzUzN2Q0YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._H1vONpBKwCSCS85xXXHwNtrgp_GUDXlpmfj1Ijl5cQ"> config.sh内加http或https也报错。无法使用 <img alt="image" width="995" src="https://private-user-images.githubusercontent.com/17977783/320339067-f28bbe58-da40-44d1-a3f0-209b3f91a0a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDg3MDQsIm5iZiI6MTcxMjU0ODQwNCwicGF0aCI6Ii8xNzk3Nzc4My8zMjAzMzkwNjctZjI4YmJlNTgtZGE0MC00NGQxLWEzZjAtMjA5YjNmOTFhMGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAzNTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMjMwNjI3NWE1MWQxODJiOTdkMDIzYjUwZWE5ZTczNjM1YzYxMmNkZDIyMzU1ZjYzOGIyODc4MmYzMDE4MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g2m332bt4ZtLJCNHdAV_qFtjKQZClXeRRHEKlFatxqk">
> 
> 你可以试试换个反代的域名，eu.org貌似被污染了

好吧，可以推荐一个吗？

**Comment by leic4u** [comment]
> @nsv2051 [eu.org](https://eu.org)这个又不行了吗，之前是freenom黄了，我注册的这个，用的好好的，突然从3月27号开始收不到消息了... 有没有推荐的？

建议注册一个便宜的顶级域名来用，比如 .top .xyz 这种，二级域名太容易被污染了。

**Comment by Joshua-auhsoj** [comment]
24.06.22  02:22 使用中国移动流量，cloudflare默认域名，改电脑host，设置里填写http，成功收到通知，填写https报错“Client network socket disconnected before secure TLS connection was established”

设备还在路上，用的Windows版的docker测试，euorg注册的域名还没有消息😂，打算等设备到货后改host直接用默认域名了
