### ISSUE TITLE
京喜工厂拼团瓜分电力活动团ID（activeId）已失效

### ISSUE THREAD

**Issue by shiyanzhizhuo** [whyour/qinglong#219]
京喜工厂

京喜工厂拼团瓜分电力活动团ID（activeId）已失效
请自行抓包替换(Node环境变量为TUAN_ACTIVEID，iOS端在BoxJx)或者联
系作者等待更新

本脚本免费使用 By：https://github.com/whyour/qinglong

**Comment by BIGBbox** [comment]
> 京喜工厂
> 
> 京喜工厂拼团瓜分电力活动团ID（activeId）已失效
> 请自行抓包替换(Node环境变量为TUAN_ACTIVEID，iOS端在BoxJx)或者联
> 系作者等待更新
> 
> 本脚本免费使用 By：https://github.com/whyour/qinglong

+1,我也是
