### ISSUE TITLE
青龙面板脚本运行时间不准确，相差八小时

### ISSUE THREAD

**Issue by dzdzdzd123** [whyour/qinglong#2192]
### Qinglong version

2.16.5

### Steps to reproduce

重装过了，ubuntu20.04+青龙最新版2.16.5

### What is expected?

青龙面板脚本运行时间

### What is actually happening?

青龙面板脚本运行时间不准确，相差八小时，服务器是香港服务器

### System Info

```shell
青龙面板脚本运行时间不准确，相差八小时，服务器是香港服务器
```

### Any additional comments?

![image](https://github.com/whyour/qinglong/assets/37803298/6c647b6b-0455-4713-9438-9e8eb6e86f22)
![image](https://github.com/whyour/qinglong/assets/37803298/d2af4c35-46f9-433d-9caa-bccaf56eb3bc)

**Comment by klcb2010** [comment]
你系统时间没有同步吧

**Comment by whyour** [comment]
改下 ubuntu 时区，改为 +0800 你现在是 +0000
