### ISSUE TITLE
无法使用无头浏览器 puppeteer

### ISSUE THREAD

**Issue by donething** [whyour/qinglong#2194]
### Qinglong version

正式版 v2.16.5

### Steps to reproduce

1. 安装Nodejs的依赖`puppeteer`后
2. 执行爬虫.ts脚本报错
```ts
/root/.local/share/pnpm/global/5/.pnpm/@puppeteer+browsers@1.8.0/node_modules/@puppeteer/browsers/lib/cjs/launch.js:271
                reject(new Error([
                       ^
Error: Failed to launch the browser process! spawn /root/.cache/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome ENOENT
```

上面两步在本地Windows测试是正常的，服务器是 Debian 11 64位

还应该做什么吗？谢谢

### What is expected?

可以启动和爬取数据

### What is actually happening?

报错！

**Comment by whyour** [comment]
要是用 qinglong:debian 镜像，默认 alpine 无法运行 chrome，更多依赖参考 https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux

**Comment by donething** [comment]
> 要是用 qinglong:debian 镜像，默认 alpine 无法运行 chrome，更多依赖参考 https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux

抱歉，忘了来更新了

原来可以直接在控制面板安装`Linux`依赖`chromium`

然后在脚本中引用`puppeteer-core`，启动时指定`executablePath`就可以了
