### ISSUE TITLE
为什么我使用docker compose安装运行的版本不是最新的而是v2.10.13

### ISSUE THREAD

**Issue by 1607lucky** [whyour/qinglong#2198]
### Qinglong version

v2.10.13

### Steps to reproduce

![1901698903](https://github.com/whyour/qinglong/assets/99725454/46d75079-741e-4057-8cc6-bee916ecf858)

使用的是docker-compose.yml的方式
每次都要手动更新
version: ‘3’
services:
  web:
    # alpine 基础镜像版本

    image: whyour/qinglong:latest

    # debian-slim 基础镜像版本

    # image: whyour/qinglong:debian  

    volumes:
      - ./data:/ql/data
    ports:
      - "0.0.0.0:5700:5700"
    environment:

      # 部署路径非必须，以斜杠开头和结尾，比如 /test/

      QlBaseUrl: '/'

    restart: unless-stopped

而且更新也报错

root@4574b99bd38e:/ql $ ql update

开始更新仓库：/ql

Fetching origin
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': OpenSSL SSL_connect: Connection reset by peer in connection to ghproxy.com:443 
error: Could not fetch origin
HEAD is now at ddee69d 更新版本 v2.10.13
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': Failed to connect to ghproxy.com port 443 after 127364 ms: Operation timed out

更新/ql失败，请检查原因...

开始克隆仓库 https://ghproxy.com/https://github.com/whyour/qinglong-static.git 到 /ql/repo/static

Cloning into '/ql/repo/static'...
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong-static.git/': OpenSSL SSL_connect: Connection reset by peer in connection to ghproxy.com:443 

更新/ql失败，请检查原因...

### What is expected?

 安装不应该是发布的最新版吗

### What is actually happening?

无

**Comment by NaroisCool** [comment]
是docker的问题
