### ISSUE TITLE
【建议】Session管理里，cookie 到期后昵称不显示，此处可优化

### ISSUE THREAD

**Issue by zion101** [whyour/qinglong#220]
首先感谢作者的无私付出！
目前在Session管理里，cookie 到期后，昵称会不显示。如果账号多了的话，会有点想不起之前账号所处的顺序，只好去看 cookie 结尾处的 "pt_pin=**************;" ，手动复制、搜索、对比……
这个体验还是有可以优化的空间。比如是否可以将昵称存储在容器内？或者如果能给每一个 cookie 手动添加备注，打上标签，也是一个不错的选项。
希望作者可以考虑，谢谢！

**Comment by Lynkan** [comment]
+1，希望可以为 cookie 添加备注，过期方便提醒朋友重新登录
