### ISSUE TITLE
Python 项目中，白名单为 `domain` （domain.py）的项目无法添加

### ISSUE THREAD

**Issue by flydo** [whyour/qinglong#2200]
### Qinglong version

2.16.5

### Steps to reproduce

```bash
ql repo <repo_url> 'xxx|domain' <blacklist> <dependence> <branch> <extensions>
```
管理后台的订阅管理中，白名单为 `domain` 时，`domain.py` 文件无法添加进项目。将该文件名修改为 `yuming.py` 后，再使用 
```bash
ql repo <repo_url> 'xxx|yuming' <blacklist> <dependence> <branch> <extensions>
```
则该文件 `yuming.py` 能够正常添加。

### What is expected?

脚本正常添加

### What is actually happening?

脚本无法添加

**Comment by whyour** [comment]
<img width="664" alt="image" src="https://github.com/whyour/qinglong/assets/22700758/84f363b4-9c70-48cc-82d4-30e244eed3c9">

**Comment by whyour** [comment]
在订阅管理中增加订阅

**Comment by flydo** [comment]
```bash
tasks/src/find/domain.py
```
目录大概是这样的，是在我这个项目的这个 [`commit`](https://github.com/idev-sig/tasks/tree/7efc468bc628bcf1e6d5c12bc0b3019f76b7c5c8)。不知道是因为在子目录的原因，还是其它原因导致的。
