### ISSUE TITLE
依赖管理中的库更新时是不是有缓存？

### ISSUE THREAD

**Issue by donething** [whyour/qinglong#2201]
### Qinglong version

正式版 v2.16.5

### Steps to reproduce

我有写一个第三方库在任务脚本中调用，更新到`npm`的仓库后，我本地测试`yarn add`就能马上更新到最新版本

可是在青龙控制台去更新， 无论`重装`、`卸载再装`，长时间内获取的都是上个版本

几个小时以上，获取的都是旧版本

我进入青龙容器后执行`npm/pnpm view xx versions` 显示中没有最新版本

但是，我在宿主机内执行上面语句是可以看到有最新版的

### What is expected?

到现在都两个小时了，还不更新版本

### What is actually happening?

实时更新库

**Comment by whyour** [comment]
你可以直接在 配置文件 config.sh 中设置 npmMirror，下个版本会在系统设置中设置不同依赖的源

**Comment by donething** [comment]
> 你可以直接在 配置文件 config.sh 中设置 npmMirror，下个版本会在系统设置中设置不同依赖的源

谢谢，原来可以这样
