### ISSUE TITLE
设置定时任务后重复执行

### ISSUE THREAD

**Issue by daidaic** [whyour/qinglong#2202]
### Qinglong version

2.16.5

### Steps to reproduce

设置定时任务后一直重复执行,无法停止,无法关闭 删除后 后代依然在执行 
<img width="1326" alt="image" src="https://github.com/whyour/qinglong/assets/47729929/cdd9a334-8e98-40bd-ad48-c1bbbe81595f">

### What is expected?

修复此问题

### What is actually happening?

定时任务重复执行  此图为我删掉旧任务 新建的 
<img width="1416" alt="image" src="https://github.com/whyour/qinglong/assets/47729929/18d45d3a-ca71-4c88-8d2d-5a67cec1d48e">

**Comment by daidaic** [comment]
这是我配置的通知,k y可以看到 删除定时任务后 原来的定时任务依旧在执行 
<img width="416" alt="image" src="https://github.com/whyour/qinglong/assets/47729929/c1e31aa7-033d-4441-a376-59a382ba491e">

**Comment by daidaic** [comment]
<img width="1393" alt="image" src="https://github.com/whyour/qinglong/assets/47729929/9e551065-4863-4383-9a67-29246a009855">
就很离谱... 一直在运行 改了脚本名也不行..
<img width="1370" alt="image" src="https://github.com/whyour/qinglong/assets/47729929/45f0b8ae-caa9-4360-a187-5cd9fecd5974">

**Comment by whyour** [comment]
你删除前已经触发了很多次，任务已经存在与队列中，删除目前只会不在往队列塞任务，不会把已经触发的任务清空
