### ISSUE TITLE
拉取后执行脚本那个输入框中，能否增加一个环境变量

### ISSUE THREAD

**Issue by donething** [whyour/qinglong#2203]
### Qinglong version

正式版 v2.16.5

### Steps to reproduce

表示拉取的脚本项目的根目录，如` /ql/data/scripts/jd_tasks`，方便在里面执行命令。当前执行该命令的工作目录是`/ql`。

如果已有请忽略，谢谢

### What is expected?

设置脚本项目的跟模目录，方便编写命令

### What is actually happening?

其它

**Comment by whyour** [comment]
可以在 task_before 中加任意环境变量
