### ISSUE TITLE
脚本管理页面空白，打开报错

### ISSUE THREAD

**Issue by noodles500kg** [whyour/qinglong#2205]
### Qinglong version

V2.16.5

### Steps to reproduce

脚本管理页面无法加载，打开就提示报错
"ELOOP: too many symbolic links encountered, stat '/ql/data/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/defer-to-connect'",
  errno: -40,
  syscall: 'stat',
  code: 'ELOOP',

### What is expected?

![屏幕截图 2023-12-08 192353](https://github.com/whyour/qinglong/assets/30250562/982b6c0f-edf8-409a-a69b-8a01eb879b2d)

### What is actually happening?

之前版本也出现同样的问题。

**Comment by whyour** [comment]
宿主机执行 `docker run --rm -v  /var/run/docker.sock:/var/run/docker.sock  containrrr/watchtower -cR <容器名>`
确保有映射 data 目录
