### ISSUE TITLE
【bug】日志中出现'时，后面的字体颜色会变 需要加个判断

### ISSUE THREAD

**Issue by lxr760** [whyour/qinglong#221]
如图，这里出现'  实际是商品的名字         而不是要做分隔，但是后面的字体颜色跟前面都不一样了

![image](https://user-images.githubusercontent.com/8476457/120266176-f4730a00-c2d3-11eb-90b6-5f0b3b62c8f6.png)

**Comment by whyour** [comment]
@lxr760 ql update更新下

**Comment by lxr760** [comment]
> ql update

当前静态资源版本 934c721...    

 这个是最新版吗？

**Comment by whyour** [comment]
> > ql update
> 
> 当前静态资源版本 934c721...
> 
> 这个是最新版吗？
> 
> 刚才提到的问题依然存在

这个问题最新版肯定没有，你的静态资源是最新的，看你是不是浏览器缓存还是咋了，强制刷新下，要不隐私模式看看

**Comment by lxr760** [comment]
> > > ql update
> > 
> > 
> > 当前静态资源版本 934c721...
> > 这个是最新版吗？
> > 刚才提到的问题依然存在
> 
> 这个问题最新版肯定没有，你的静态资源是最新的，看你是不是浏览器缓存还是咋了，强制刷新下，要不隐私模式看看

已清空缓存，隐私模式下还有出现这个问题


比如，在1310行出现做任务：Marc O'Polo官方旗舰店;等待完成     这里O后面有个‘   这后面的字颜色就会变化

然后在1429行  又出现了做任务：Marc O'Polo官方旗舰店;等待完成         O后面有个‘      这时应该是被系统判断为跟1310行对应

所以后面的字体颜色就变正常了


感觉这里是把''当成了变量值  所以‘’中间的字体颜色都变了


![Snipaste_2021-06-02_09-28-13](https://user-images.githubusercontent.com/8476457/120410246-2ee8af80-c385-11eb-8c37-fbc76e0919e7.jpg)
![Snipaste_2021-06-02_09-28-19](https://user-images.githubusercontent.com/8476457/120410250-314b0980-c385-11eb-97f4-44b39b4bca33.jpg)
