### ISSUE TITLE
还原备份时自己修改后的代码和头像没有正常还原

### ISSUE THREAD

**Issue by QYC-Unity** [whyour/qinglong#2211]
### Qinglong version

正式版 v2.16.5

### Steps to reproduce

1.备份后删除容器和数据，重新部署
2.还原备份
3.自己修改且从订阅依赖中删除的代码文件没有被还原（解压备份文件可以看到该代码文件）
4.头像也没有被还原

### What is expected?

还原备份时可以正确的还原所有代码文件和头像

### What is actually happening?

没有正确还原

**Comment by whyour** [comment]
是在脚本管理修改的代码？

**Comment by whyour** [comment]
恢复失败，可以进容器执行 ql reload data
