### ISSUE TITLE
使用 docker-compose 部署，脚本文件和日志文件无法在页面显示内容，但是请求数据是正常的

### ISSUE THREAD

**Issue by wencaizhang** [whyour/qinglong#2218]
### Qinglong version

image: whyour/qinglong:debian

### Steps to reproduce

使用 README 中推荐的 (docker-compose 文件](https://github.com/whyour/qinglong?tab=readme-ov-file#docker-compose-%E6%8E%A8%E8%8D%90)，镜像使用 whyour/qinglong:debian 版本。

执行启动命令：

```sh
docker-compose up -d
```

进入网页，打开「脚本管理」，选择任意一个文件就能看到。

### What is expected?

文件内容正常显示

### What is actually happening?

页面的文件内容区域一直处于 loading 状态
<img width="1146" alt="image" src="https://github.com/whyour/qinglong/assets/34718241/0794d3b2-3acd-447c-8b6b-f829cb017543">

**Comment by whyour** [comment]
@wencaizhang 使用 chrome

**Comment by wencaizhang** [comment]
可以正常打开了

**Comment by NaroisCool** [comment]
> @wencaizhang 使用 chrome
@wencaizhang 您好，请问能回答一下这个问题吗？谢谢 [(https://github.com/whyour/qinglong/issues/2206)]
