### ISSUE TITLE
进入不了面板

### ISSUE THREAD

**Issue by Xiaojuziaimeiqiu** [whyour/qinglong#2224]
### Qinglong version

2.16.5  版本号

### Steps to reproduce

15 lines:
PM2        | 2023-12-30T23:48:34: PM2 log: pid=5006 msg=failed to kill - retrying in 100ms
PM2        | 2023-12-30T23:48:34: PM2 log: pid=5006 msg=failed to kill - retrying in 100ms
PM2        | 2023-12-30T23:48:34: PM2 log: pid=5006 msg=failed to kill - retrying in 100ms
PM2        | 2023-12-30T23:48:34: PM2 log: pid=5006 msg=failed to kill - retrying in 100ms
PM2        | 2023-12-30T23:48:35: PM2 log: pid=5006 msg=failed to kill - retrying in 100ms
PM2        | 2023-12-30T23:48:35: PM2 log: pid=5006 msg=failed to kill - retrying in 100ms
PM2        | 2023-12-30T23:48:35: PM2 log: pid=5006 msg=failed to kill - retrying in 100ms
PM2        | 2023-12-30T23:48:35: PM2 log: pid=5006 msg=failed to kill - retrying in 100ms
PM2        | 2023-12-30T23:48:35: PM2 log: pid=5006 msg=failed to kill - retrying in 100ms
PM2        | 2023-12-30T23:48:35: PM2 log: pid=5006 msg=failed to kill - retrying in 100ms
PM2        | 2023-12-30T23:48:35: PM2 log: Process with pid 5006 still alive after 15000ms, sending it SIGKILL now...
PM2        | 2023-12-30T23:48:35: PM2 log: App [panel:2] exited with code [0] via signal [SIGKILL]
PM2        | 2023-12-30T23:48:35: PM2 log: pid=5006 msg=process killed
PM2        | 2023-12-30T23:48:36: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-12-30T23:48:46: PM2 log: App [panel:2] online

/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-12-30T23:48:20: ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-12-30T23:48:21: ✌️ Sentry loaded
1|public   | 2023-12-30T23:48:26: ✌️ DB loaded
1|public   | 2023-12-30T23:48:26: ✌️ 公共服务启动成功！

/root/.pm2/logs/schedule-error.log last 15 lines:
0|schedule | 2023-12-30T23:48:53: 
0|schedule | 2023-12-30T23:48:53: <--- Last few GCs --->
0|schedule | 2023-12-30T23:48:53: 
0|schedule | 2023-12-30T23:48:53: 
0|schedule | 2023-12-30T23:48:53: <--- JS stacktrace --->
0|schedule | 2023-12-30T23:48:53: 
0|schedule | 2023-12-30T23:48:53: FATAL ERROR: DateTimePatternGeneratorCache::CreateGenerator Allocation failed - process out of memory

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-12-30T23:48:20: Server need close, singal SIGINT
2|panel    | 2023-12-30T23:48:54: ✌️ depInjectorLoader expressLoader initData linkDeps failed Error: 14 UNAVAILABLE: read ECONNRESET

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-12-30T23:48:45: ✌️ DB loaded
2|panel    | 2023-12-30T23:48:45: ✌️ Init file down
2|panel    | 2023-12-30T23:48:46: ✌️ Sentry loaded
2|panel    | 2023-12-30T23:48:51: ✌️ Dependency Injector loaded
2|panel    | 2023-12-30T23:48:51: ✌️ Express loaded
2|panel    | 2023-12-30T23:48:55: ✌️ 后端服务启动成功！

PM2      | App [schedule:0] exited with code [0] via signal [SIGABRT]
PM2      | App [schedule:0] starting in -fork mode-
PM2      | App [schedule:0] online
0|schedule  | 2023-12-30T23:49:30: ✌️ 定时服务启动成功！
2|panel     | 2023-12-30T23:49:39: 
2|panel     | 2023-12-30T23:49:39: <--- Last few GCs --->
2|panel     | 2023-12-30T23:49:39: 
2|panel     | 2023-12-30T23:49:39: [5308:0xb3ae60b0]    61495 ms: Scavenge 38.4 (43.4) -> 37.4 (43.6) MB, 10.6 / 0.1 ms  (average mu = 0.996, current mu = 0.997) task; 
2|panel     | 2023-12-30T23:49:39: [5308:0xb3ae60b0]    61941 ms: Scavenge 39.0 (43.6) -> 37.8 (43.9) MB, 8.5 / 0.1 ms  (average mu = 0.996, current mu = 0.997) allocation failure; 
2|panel     | 2023-12-30T23:49:39: [5308:0xb3ae60b0]    62589 ms: Scavenge 39.0 (43.9) -> 38.2 (44.1) MB, 16.9 / 0.1 ms  (average mu = 0.996, current mu = 0.997) task; 
2|panel     | 2023-12-30T23:49:39: 
2|panel     | 2023-12-30T23:49:39: 
2|panel     | 2023-12-30T23:49:39: <--- JS stacktrace --->
2|panel     | 2023-12-30T23:49:39: 
2|panel     | 2023-12-30T23:49:39: FATAL ERROR: DateTimePatternGeneratorCache::CreateGenerator Allocation failed - process out of memory
PM2         | App [panel:2] exited with code [0] via signal [SIGABRT]
PM2         | App [panel:2] starting in -fork mode-
2|panel     | 2023-12-30T23:50:07: ✌️ DB loaded
2|panel     | 2023-12-30T23:50:07: ✌️ Init file down
PM2         | App [panel:2] online
2|panel     | 2023-12-30T23:50:09: ✌️ Sentry loaded
2|panel     | 2023-12-30T23:50:14: ✌️ Dependency Injector loaded
2|panel     | 2023-12-30T23:50:14: ✌️ Express loaded
0|schedule  | 2023-12-30T23:50:16: 
0|schedule  | 2023-12-30T23:50:16: <--- Last few GCs --->
0|schedule  | 2023-12-30T23:50:16: iggest step 15.3 ms, walltime since start of marking 157 ms) (average mu = 0.992, current mu = 0.994) finalize[5475:0xb3a840b0]    35282 ms: Mark-sweep (reduce) 19.3 (21.6) -> 18.5 (21.6) MB, 19.7 / 0.0 ms  (+ 47.9 ms in 61 steps since start of marking, biggest step 1.7 ms, walltime since start of marking 83 ms) (average mu = 0.988, current mu = 0.903) finalize i[5475:0xb3a840b0]    48075 ms: Scavenge 19.3 (21.9) -> 18.8 (21.9) MB, 4.1 / 0.0 ms  (average mu = 0.988, current mu = 0.903) allocation failure; 
0|schedule  | 2023-12-30T23:50:16: 
0|schedule  | 2023-12-30T23:50:16: 
0|schedule  | 2023-12-30T23:50:16: <--- JS stacktrace --->
0|schedule  | 2023-12-30T23:50:16: 
0|schedule  | 2023-12-30T23:50:16: FATAL ERROR: DateTimePatternGeneratorCache::CreateGenerator Allocation failed - process out of memory
2|panel     | 2023-12-30T23:50:17: ✌️ depInjectorLoader expressLoader initData linkDeps failed Error: 14 UNAVAILABLE: read ECONNRESET
2|panel     | 2023-12-30T23:50:17: ✌️ 后端服务启动成功！
PM2         | App [schedule:0] exited with code [0] via signal [SIGABRT]
PM2         | App [schedule:0] starting in -fork mode-
PM2         | App [schedule:0] online
0|schedule  | 2023-12-30T23:50:40: ✌️ 定时服务启动成功！
2|panel     | 2023-12-30T23:50:42: 
2|panel     | 2023-12-30T23:50:42: <--- Last few GCs --->
2|panel     | 2023-12-30T23:50:42: 
2|panel     | 2023-12-30T23:50:42: [5545:0xb3ae30b0]    37517 ms: Scavenge 34.2 (43.6) -> 33.3 (43.6) MB, 18.4 / 0.1 ms  (average mu = 0.994, current mu = 0.994) task; 
2|panel     | 2023-12-30T23:50:42: [5545:0xb3ae30b0]    39072 ms: Scavenge 34.8 (43.6) -> 33.5 (43.6) MB, 9.0 / 0.1 ms  (average mu = 0.994, current mu = 0.994) task; 
2|panel     | 2023-12-30T23:50:42: [5545:0xb3ae30b0]    42188 ms: Scavenge 35.3 (43.6) -> 33.6 (43.6) MB, 8.0 / 0.1 ms  (average mu = 0.994, current mu = 0.994) allocation failure; 
2|panel     | 2023-12-30T23:50:42: 
2|panel     | 2023-12-30T23:50:42: 
2|panel     | 2023-12-30T23:50:42: <--- JS stacktrace --->
2|panel     | 2023-12-30T23:50:42: 
2|panel     | 2023-12-30T23:50:42: FATAL ERROR: DateTimePatternGeneratorCache::CreateGenerator Allocation failed - process out of memory
PM2         | App [panel:2] exited with code [0] via signal [SIGABRT]
PM2         | App [panel:2] starting in -fork mode-
2|panel     | 2023-12-30T23:51:19: ✌️ DB loaded
2|panel     | 2023-12-30T23:51:19: ✌️ Init file down
PM2         | App [panel:2] online
2|panel     | 2023-12-30T23:51:20: ✌️ Sentry loaded
2|panel     | 2023-12-30T23:51:25: ✌️ Dependency Injector loaded
2|panel     | 2023-12-30T23:51:25: ✌️ Express loaded
0|schedule  | 2023-12-30T23:51:27: 
0|schedule  | 2023-12-30T23:51:27: <--- Last few GCs --->
0|schedule  | 2023-12-30T23:51:27: 
0|schedule  | 2023-12-30T23:51:27: [5703:0xb3b6b0b0]    56702 ms: Scavenge 19.2 (22.1) -> 18.8 (22.1) MB, 4.0 / 0.0 ms  (average mu = 0.989, current mu = 0.909) allocation failure; 
0|schedule  | 2023-12-30T23:51:27: 
0|schedule  | 2023-12-30T23:51:27: 
0|schedule  | 2023-12-30T23:51:27: <--- JS stacktrace --->
0|schedule  | 2023-12-30T23:51:27: 
0|schedule  | 2023-12-30T23:51:27: FATAL ERROR: DateTimePatternGeneratorCache::CreateGenerator Allocation failed - process out of memory
2|panel     | 2023-12-30T23:51:28: ✌️ depInjectorLoader expressLoader initData linkDeps failed Error: 14 UNAVAILABLE: read ECONNRESET
2|panel     | 2023-12-30T23:51:29: ✌️ 后端服务启动成功！
PM2         | App [schedule:0] exited with code [0] via signal [SIGABRT]
PM2         | App [schedule:0] starting in -fork mode-
0|schedule  | 2023-12-30T23:51:56: ✌️ 定时服务启动成功！
PM2         | App [schedule:0] online
2|panel     | 2023-12-30T23:51:59: 
2|panel     | 2023-12-30T23:51:59: <--- Last few GCs --->
2|panel     | 2023-12-30T23:51:59: 
2|panel     | 2023-12-30T23:51:59: [5771:0xb3afd0b0]    45969 ms: Scavenge 34.6 (43.1) -> 33.5 (43.1) MB, 11.3 / 0.1 ms  (average mu = 0.995, current mu = 0.996) task; 
2|panel     | 2023-12-30T23:51:59: [5771:0xb3afd0b0]    46614 ms: Scavenge 35.1 (43.1) -> 33.6 (43.1) MB, 7.2 / 0.2 ms  (average mu = 0.995, current mu = 0.996) task; 
2|panel     | 2023-12-30T23:51:59: [5771:0xb3afd0b0]    47827 ms: Scavenge 35.2 (43.1) -> 33.6 (43.1) MB, 4.5 / 0.1 ms  (average mu = 0.995, current mu = 0.996) task; 
2|panel     | 2023-12-30T23:51:59: 
2|panel     | 2023-12-30T23:51:59: 
2|panel     | 2023-12-30T23:51:59: <--- JS stacktrace --->
2|panel     | 2023-12-30T23:51:59: 
2|panel     | 2023-12-30T23:51:59: FATAL ERROR: DateTimePatternGeneratorCache::CreateGenerator Allocation failed - process out of memory
PM2         | App [panel:2] exited with code [0] via signal [SIGABRT]
PM2         | App [panel:2] starting in -fork mode-

### What is expected?

预期的话当然是把问题解决了呀

### What is actually happening?

断电   然后重启之后就成这了

**Comment by whyour** [comment]
是开全局代理了？

**Comment by qq846511277** [comment]
ql check 试试看

**Comment by Lua12138** [comment]
在某次设备突然断电后，也遇到该问题（通过Docker部署）

schedule 一直提示OOM。

按照web页面提示操作无效，简单的销毁重新容器后解决。
