### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by tsiens** [whyour/qinglong#2225]
### Qinglong version

2.16.5

### Steps to reproduce

群晖7.2 docker qinglong:later，应该是2.16.5
任何库都报错
在docker bash运行 "
task /ql/data/scripts/node_modules/got/dist/source/create.js" in docker bash

### What is expected?

不报错

### What is actually happening?

/ql/data/scripts/node_modules/got/dist/source/create.js:14
const p_cancelable_1 = require("p-cancelable");
                       ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /ql/node_modules/.pnpm/p-cancelable@4.0.1/node_modules/p-cancelable/index.js from /ql/data/scripts/node_modules/got/dist/source/create.js not supported.
Instead change the require of index.js in /ql/data/scripts/node_modules/got/dist/source/create.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/ql/data/scripts/node_modules/got/dist/source/create.js:14:24) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.2

**Comment by tsiens** [comment]
搞定了，不晓得这是啥情况，百度说是包版本太高不支持require，安装了低版本的。然后报另一个缺失，安装完又是require报错。
包缺失，装包，require不支持，装低版本包。
重复五六次吧，终于运行不报错了

**Comment by tsiens** [comment]
解决了

**Comment by him95** [comment]
请问是要装那个版本的p-cancelable呢？我也是同问题

**Comment by tsiens** [comment]
> 请问是要装那个版本的p-cancelable呢？我也是同问题

忘了，先pnpm install p-cancelable，安装完成后能看到版本比如是7.0.1，然后pnpm install p-cancelable@6.0.1，装完还报错就5.0.1。。用这个方案，缺哪个就装哪个，报require不支持就降低版本

**Comment by tsiens** [comment]
> 请问是要装那个版本的p-cancelable呢？我也是同问题

看问题的最下面更新
