### ISSUE TITLE
脚本里面没有写定时规则的创建任务报错

### ISSUE THREAD

**Issue by Peter-90** [whyour/qinglong#2226]
### Qinglong version

2.16.5

### Steps to reproduce

<img width="524" alt="image" src="https://github.com/whyour/qinglong/assets/22003137/3ae7ff73-19e1-41c2-97f0-03c72886207e">
超市红包雨 -> 添加失败(Constraint error, got value 31 expected range 0-23)

### What is expected?

希望没有写定时任务的脚本直接应用配置文件的默认规则就好了或者随机一个规则，报错导致面板都看不到任务

### What is actually happening?

如上所述

**Comment by whyour** [comment]
这是脚本匹配到的定时不对，建议修改下脚本

**Comment by Peter-90** [comment]
> 这是脚本匹配到的定时不对，建议修改下脚本

<img width="353" alt="image" src="https://github.com/whyour/qinglong/assets/22003137/391d4738-00c0-4d01-bb84-9e9983d42f57">
大佬 你看这个 它没写定时 感觉就默认读配置吧 不然不会创建脚本挺难受的 要手动

**Comment by Peter-90** [comment]
> 这是脚本匹配到的定时不对，建议修改下脚本

还有就是最新的版本禁用的任务，即使手动运行也不会出现在前面，以前的版本是可以的
