### ISSUE TITLE
容器内单个脚本无法下载

### ISSUE THREAD

**Issue by qqwas** [whyour/qinglong#223]
报错如下：wget: error getting response: Connection reset by peer
我从软路由试了wget是正常的

**Comment by muziling** [comment]
可能是 ${raw_url} 要加双引号，链接里带AT等特殊字符
```
update_raw() {
    echo -e "--------------------------------------------------------------\n"
    local raw_url="$1"
    raw_file_name=$(echo ${raw_url} | awk -F "/" '{print $NF}')
    echo -e "开始下载：${raw_url} \n\n保存路径：$dir_raw/${raw_file_name}\n"
    wget -q --no-check-certificate -O "$dir_raw/${raw_file_name}.new" ${raw_url}
```

**Comment by qqwas** [comment]
我试过了直接在容器里面用wget下载也不行，我换了一个自己编译的wget-ssl进去，就可以了。这个版本应该是没有编译ssl进去

> 可能是 ${raw_url} 要加双引号，链接里带AT等特殊字符
> 
> ```
> update_raw() {
>     echo -e "--------------------------------------------------------------\n"
>     local raw_url="$1"
>     raw_file_name=$(echo ${raw_url} | awk -F "/" '{print $NF}')
>     echo -e "开始下载：${raw_url} \n\n保存路径：$dir_raw/${raw_file_name}\n"
>     wget -q --no-check-certificate -O "$dir_raw/${raw_file_name}.new" ${raw_url}
> ```

**Comment by zhudan** [comment]
把busybox的wget换了

`apk search wget`

**Comment by whyour** [comment]
最新镜像已增加 wget
