### ISSUE TITLE
CoreELEC docker安装报错

### ISSUE THREAD

**Issue by JasonLxj** [whyour/qinglong#2235]
### Qinglong version
Docker version 18.09.7, build 18.09.7
最新版本

### Steps to reproduce

docker run -d --restart=unless-stopped --name="qinglong" -v ~/qinglong/config:/config --net=host whyour/qinglong:latest

### What is expected?

localhost:5700页面报错

### What is actually happening?

正常进入

### System Info

```shell
root@CoreELEC:/ql $ uname -a
Linux CoreELEC 3.14.29 #1 SMP Sat Jul 9 23:35:01 CST 2022 aarch64 GNU/Linux
```

### Any additional comments?

root@CoreELEC:/ql $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2024-01-08T22:31:41: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2024-01-08T22:31:41: PM2 log: App [public:1] starting in -fork mode-
PM2        | 2024-01-08T22:31:47: PM2 log: App [schedule:0] online
PM2        | 2024-01-08T22:31:47: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2024-01-08T22:31:50: PM2 log: App [public:1] online
PM2        | 2024-01-08T22:31:57: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2024-01-08T22:31:47: ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2024-01-08T22:31:47: ✌️ Sentry loaded
1|public   | 2024-01-08T22:31:50: ✌️ DB loaded
1|public   | 2024-01-08T22:31:50: ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2024-01-08T22:32:01: ✌️ depInjectorLoader expressLoader initData linkDeps failed Error: 1 CANCELLED: Call cancelled

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2024-01-08T22:31:53: ✌️ DB loaded
2|panel    | 2024-01-08T22:31:53: ✌️ Init file down
2|panel    | 2024-01-08T22:31:54: ✌️ Sentry loaded
2|panel    | 2024-01-08T22:31:57: ✌️ Dependency Injector loaded
2|panel    | 2024-01-08T22:31:58: ✌️ Express loaded
2|panel    | 2024-01-08T22:32:01: ✌️ 后端服务启动成功！

**Comment by JasonLxj** [comment]
$ ql check
## 开始执行... 2024-01-08 23:17:32

=====> 开始检测
npm ERR! code EINVAL
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/pnpm/LICENSE
npm ERR! dest /usr/local/lib/node_modules/.pnpm-LW2coPit/LICENSE
npm ERR! errno -22
npm ERR! EINVAL: invalid argument, rename '/usr/local/lib/node_modules/pnpm/LICENSE' -> '/usr/local/lib/node_modules/.pnpm-LW2coPit/LICENSE'

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-01-08T15_17_35_016Z-debug-0.log
Writing to /root/.config/pip/pip.conf
Lockfile is up to date, resolution step is skipped
Already up to date

Done in 7.8s

**Comment by JasonLxj** [comment]
ql update
## 开始执行... 2024-01-08 23:21:23

使用 github 源更新...

更新青龙源文件成功...

更新青龙静态资源成功...


开始检测依赖...


依赖检测安装成功...

更新包下载成功...
rm: cannot remove '/ql/static/build': Directory not empty
rm: cannot remove '/ql/static/dist': Directory not empty
[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])
[PM2] Applying action reloadProcessId on app [public](ids: [ 1 ])
[PM2] [schedule](0) ✓
[PM2] Applying action reloadProcessId on app [panel](ids: [ 2 ])
[PM2] [public](1) ✓
[PM2] [panel](2) ✓
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 3403     │ 10s    │ 2    │ online    │ 0%       │ 66.0mb   │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 3356     │ 30s    │ 2    │ online    │ 0%       │ 55.2mb   │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 3355     │ 30s    │ 2    │ online    │ 5.3%     │ 49.5mb   │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

## 执行结束... 2024-01-08 23:22:16 耗时 53 秒

**Comment by whyour** [comment]
是不是有全局代理

**Comment by JasonLxj** [comment]
> 是不是有全局代理

没有设置代理

**Comment by whyour** [comment]
@JasonLxj 用 develop 镜像试试

**Comment by JasonLxj** [comment]
> @JasonLxj 用 develop 镜像试试

这个好使，感谢回复
