### ISSUE TITLE
映射的目录web页面不展示

### ISSUE THREAD

**Issue by zxerqw** [whyour/qinglong#2238]
### Qinglong version

正式版 v2.16.5

### Steps to reproduce

增加映射目录

### What is expected?

正确映射目录

### What is actually happening?

Hello，

通过docker-compose安装的青龙，增加了几个映射目录，但是在前端脚本管理中始终找不到这些文件夹，只有一个/ql/data,
进docker内查看是存在这些目录的

volumes:
      - /volume4/docker/ql/data:/ql/data
      - /volume4/docker/bark:/test
      - /volume4/homes/xx/scripts/js:/test00
      - /volume4/homes/xx/scripts/js:/ql/test11
      - /volume4/homes/xx/scripts/python:/ql/data/test22

![image](https://github.com/whyour/qinglong/assets/16666177/ff9a7835-43b8-4be7-b670-90ed27e33635)

---
还有一个问题是我按照另一个ticket内的教程，映射依赖目录，
映射了这个后前端无法启动，/root/.local/share/pnpm/global
![image](https://github.com/whyour/qinglong/assets/16666177/bf7455f3-e31c-4b51-bcf8-fcc2a38295c3)

映射了/usr/local/lib/python3.10/site-packages这个后，python的依赖安装都是失败的，
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'

### System Info

```shell
System:
    OS: Linux 4.4 Alpine Linux
    CPU: (4) x64 Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
    Memory: 4.58 GB / 7.43 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.18.2 - /usr/bin/node
    npm: 9.6.6 - /usr/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
```

**Comment by zxerqw** [comment]
第二个问题，我手动把容器的目录先拷贝一份出来可行吗？会不会影响以后的映像更新之类的

**Comment by whyour** [comment]
映射到 data 目录下的 scripts 目录里，就可以在脚本管理看到

**Comment by whyour** [comment]
依赖可以执行 docker cp 拷贝容器内的文件到机器上

**Comment by zxerqw** [comment]
> 映射到 data 目录下的 scripts 目录里，就可以在脚本管理看到

感谢，问题解决了，尝试了多个目录就是没试映射到scripts下面
