### ISSUE TITLE
请教：如何设置某任务使用单独的推送方式(例如企业微信)，而不是全局的pushplus推送？

### ISSUE THREAD

**Issue by 888iv** [whyour/qinglong#2239]
### Qinglong version

V2.16.5

### Steps to reproduce

请教：如何设置某任务使用单独的推送方式(例如企业微信)，而不是全局的pushplus推送？

### What is expected?

所有任务全局推送的基础中，设置某任务优先级更高并使用另一种推送方式

### What is actually happening?

任务太多推送太频繁导致无法迅速收到重要任务的推送

**Comment by whyour** [comment]
最新版 python 推送可以支持指定额外的推送方式，nodejs 的通知可以在脚本最上面使用 process.env.x 覆盖通知参数
