### ISSUE TITLE
docker-arm64环境下青龙不会自动运行定时任务

### ISSUE THREAD

**Issue by q240627995** [whyour/qinglong#224]
docker-arm64,ql最新版本

如图，本应该半小时运行一次，但是log只有一次，还是我手动运行的。

![image](https://user-images.githubusercontent.com/30516698/120321910-6cfaba80-c316-11eb-9a7a-a6ecaeaf4b87.png)

**Comment by whyour** [comment]
@q240627995 更新下最新的镜像，貌似有一版镜像有问题

**Comment by q240627995** [comment]
> @q240627995 更新下最新的镜像，貌似有一版镜像有问题

感谢您的回复，我删除了docker和镜像后，拉去了最新的镜像重新安装，观察2小时发现还是不能自动跑
![image](https://user-images.githubusercontent.com/30516698/120334567-5149e100-c323-11eb-92ba-82edafa030a4.png)
![image](https://user-images.githubusercontent.com/30516698/120334718-72aacd00-c323-11eb-8980-0e5d102faa9d.png)


如图，半小时运行一次的，日志只有手动的一次
![image](https://user-images.githubusercontent.com/30516698/120334357-2495c980-c323-11eb-9420-8513035ea97a.png)

然后尝试自己创建了一个每分钟都执行一次的任务，仍然无法自动运行
![image](https://user-images.githubusercontent.com/30516698/120334287-19db3480-c323-11eb-870a-0124827b083c.png)

**Comment by 231838238** [comment]
重新拉镜像，要用最新的

**Comment by q240627995** [comment]
> 重新拉镜像，要用最新的

已经是最新的了，我的：
![image](https://user-images.githubusercontent.com/30516698/120342726-a50bf880-c32a-11eb-9ef6-aedeb3bf97d5.png)

dockerhub：
![image](https://user-images.githubusercontent.com/30516698/120342763-accb9d00-c32a-11eb-8de2-ff5c8c61bd50.png)

**Comment by whyour** [comment]
> > 重新拉镜像，要用最新的
> 
> 已经是最新的了，我的：
> ![image](https://user-images.githubusercontent.com/30516698/120342726-a50bf880-c32a-11eb-9ef6-aedeb3bf97d5.png)
> 
> dockerhub：
> ![image](https://user-images.githubusercontent.com/30516698/120342763-accb9d00-c32a-11eb-8de2-ff5c8c61bd50.png)

以前好的吗，删除容器，重新run

**Comment by q240627995** [comment]
> > > 重新拉镜像，要用最新的
> > 
> > 
> > 已经是最新的了，我的：
> > ![image](https://user-images.githubusercontent.com/30516698/120342726-a50bf880-c32a-11eb-9ef6-aedeb3bf97d5.png)
> > dockerhub：
> > ![image](https://user-images.githubusercontent.com/30516698/120342763-accb9d00-c32a-11eb-8de2-ff5c8c61bd50.png)
> 
> 以前好的吗，删除容器，重新run

你好！今天上午尝试删除容器和image，然后重新pull，发现pull得到的image还是和昨天晚上一样，请问我的操作是哪里错了？
image版本：
![image](https://user-images.githubusercontent.com/30516698/120452922-2a43eb80-c3c5-11eb-93d6-8e0e2ceeeed5.png)

我的ssh命令：
![image](https://user-images.githubusercontent.com/30516698/120452850-17c9b200-c3c5-11eb-942f-3ce0530393cf.png)

**Comment by q240627995** [comment]
问题解决了，能正常自动运行。
认真观察后发现，在定时任务那看到的日志，是只会显示手动执行的日志，自动运行的日志不会显示，
![image](https://user-images.githubusercontent.com/30516698/120457056-bc99be80-c3c8-11eb-8a7f-b9e4354f3904.png)

在专门的日志那里，选择你要看的任务，就会有确实有任务执行了
![image](https://user-images.githubusercontent.com/30516698/120457182-d4714280-c3c8-11eb-85c1-35743fcbf7e3.png)

应该和自动运行不会显示 运行中 一样，日志也不会在这定时任务那里显示
