### ISSUE TITLE
最新dev版更新不上

### ISSUE THREAD

**Issue by cyxnzb** [whyour/qinglong#2241]
### Qinglong version

v2.16.5

### Steps to reproduce

无论是在系统设置里更新还是去docker里面更新

### What is expected?

失败

### What is actually happening?

  Virtual store is at:             node_modules/.pnpm
.../node_modules/@whyour/sqlite3 install$ prebuild-install -r napi || node-gyp rebuild
.../node_modules/@whyour/sqlite3 install: gyp ERR! build error 
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack Error: not found: make
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at getNotFoundError (/ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:10:17)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:57:18
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at new Promise (<anonymous>)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at step (/ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:54:21)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:71:22
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at new Promise (<anonymous>)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at subStep (/ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:69:33)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:80:22
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-develop/node_modules/.pnpm/isexe@2.0.0/node_modules/isexe/index.js:42:5
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-develop/node_modules/.pnpm/isexe@2.0.0/node_modules/isexe/mode.js:8:5
.../node_modules/@whyour/sqlite3 install: gyp ERR! System Linux 4.18.0-535.el8.x86_64
.../node_modules/@whyour/sqlite3 install: gyp ERR! command "/usr/bin/node" "/ql/.tmp/qinglong-develop/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
.../node_modules/@whyour/sqlite3 install: gyp ERR! cwd /ql/.tmp/qinglong-develop/node_modules/.pnpm/github.com+whyour+node-sqlite3@4fcd31f80caa3fc292356b9d99258b601c620488/node_modules/@whyour/sqlite3
.../node_modules/@whyour/sqlite3 install: gyp ERR! node -v v18.16.1
.../node_modules/@whyour/sqlite3 install: gyp ERR! node-gyp -v v8.4.1
.../node_modules/@whyour/sqlite3 install: gyp ERR! not ok 
.../node_modules/@whyour/sqlite3 install: Failed
 ELIFECYCLE  Command failed with exit code 1.

### System Info

```shell
System:
    OS: Linux 4.18 Alpine Linux
    CPU: (2) x64 AMD EPYC 7K62 48-Core Processor
    Memory: 5.65 GB / 7.27 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.16.1 - /usr/bin/node
    npm: 9.6.6 - /usr/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
```

**Comment by whyour** [comment]
是在机器上用命令行更新也不行？

**Comment by cyxnzb** [comment]
> 是在机器上用命令行更新也不行？

对，一样的错误提示
Virtual store is at:             node_modules/.pnpm
.../node_modules/@whyour/sqlite3 install$ prebuild-install -r napi || node-gyp rebuild
.../node_modules/@whyour/sqlite3 install: gyp ERR! build error 
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack Error: not found: make
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at getNotFoundError (/ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:10:17)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:57:18
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at new Promise (<anonymous>)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at step (/ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:54:21)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:71:22
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at new Promise (<anonymous>)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at subStep (/ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:69:33)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-develop/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:80:22
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-develop/node_modules/.pnpm/isexe@2.0.0/node_modules/isexe/index.js:42:5
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-develop/node_modules/.pnpm/isexe@2.0.0/node_modules/isexe/mode.js:8:5
.../node_modules/@whyour/sqlite3 install: gyp ERR! System Linux 4.18.0-535.el8.x86_64
.../node_modules/@whyour/sqlite3 install: gyp ERR! command "/usr/bin/node" "/ql/.tmp/qinglong-develop/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
.../node_modules/@whyour/sqlite3 install: gyp ERR! cwd /ql/.tmp/qinglong-develop/node_modules/.pnpm/github.com+whyour+node-sqlite3@4fcd31f80caa3fc292356b9d99258b601c620488/node_modules/@whyour/sqlite3
.../node_modules/@whyour/sqlite3 install: gyp ERR! node -v v18.16.1
.../node_modules/@whyour/sqlite3 install: gyp ERR! node-gyp -v v8.4.1
.../node_modules/@whyour/sqlite3 install: gyp ERR! not ok 
.../node_modules/@whyour/sqlite3 install: Failed
 ELIFECYCLE  Command failed with exit code 1.

**Comment by whyour** [comment]
@cyxnzb 什么机器

**Comment by cyxnzb** [comment]
> Refere

腾讯的轻量应用云服务器

**Comment by whyour** [comment]
@cyxnzb 是执行的这个？docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>

**Comment by cyxnzb** [comment]
> @cyxnzb 是执行的这个？docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>

不，我就执行了ql update，你说的这个好像貌似会丢数据？

**Comment by whyour** [comment]
@cyxnzb 只要你映射了 data 目录就不会，或者你先系统里备份下？

**Comment by cyxnzb** [comment]
> @cyxnzb 只要你映射了 data 目录就不会，或者你先系统里备份下？

好，我先进青龙里面备份下吧

**Comment by cyxnzb** [comment]
> @cyxnzb 只要你映射了 data 目录就不会，或者你先系统里备份下？

面板里面的备份好像很长时间都没有反应，有没有其他方法

**Comment by whyour** [comment]
@cyxnzb 把容器的 /ql/data 目录拷贝出来

**Comment by cyxnzb** [comment]
> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>

输入了这个指令后还是不行
回显：time="2024-01-20T15:43:05Z" level=info msg="Watchtower 1.3.0\nUsing no notifications\nOnly checking containers with name \"qinglong\"\nRunning a one time update."
time="2024-01-20T15:44:01Z" level=info msg="Unable to update container \"/qinglong\": Error response from daemon: Head \"https://registry-1.docker.io/v2/whyour/qinglong/manifests/develop\": net/http: TLS handshake timeout. Proceeding to next."

**Comment by whyour** [comment]
@cyxnzb 你网有问题

**Comment by cyxnzb** [comment]
> @cyxnzb 你网有问题

重新配置了一下docker源之后，它说
time="2024-01-21T05:13:00Z" level=info msg="Watchtower 1.3.0\nUsing no notifications\nOnly checking containers with name \"qinglong\"\nRunning a one time update."
time="2024-01-21T05:14:21Z" level=info msg="Found new whyour/qinglong:develop image (237e299a0334)"
time="2024-01-21T05:14:21Z" level=info msg="Stopping /qinglong (3f8557694e6d) with SIGTERM"
time="2024-01-21T05:14:52Z" level=info msg="Creating /qinglong"
time="2024-01-21T05:14:52Z" level=error msg="Error response from daemon: invalid config for network bridge: invalid endpoint settings:\nnetwork-scoped alias is supported only for containers in user defined networks"
time="2024-01-21T05:14:52Z" level=info msg="Removing image f68ea5af7a09"

**Comment by cyxnzb** [comment]
> @cyxnzb 你网有问题

然后好像直接容器干没了，我重新装吧

**Comment by whyour** [comment]
> invalid config for network bridge: invalid endpoint settings:\nnetwork-scoped alias is supported only for containers in user defined network

你 docker compose 配置文件有问题

**Comment by cyxnzb** [comment]
> > invalid config for network bridge: invalid endpoint settings:\nnetwork-scoped alias is supported only for containers in user defined network
> 
> 你 docker compose 配置文件有问题

我重装了后来，然后目前没啥大问题，就是不知道后续升级的话会不会还出错，然后就是linux依赖管理里面有几个什么bizCode装不上没事吧

**Comment by cyxnzb** [comment]
> > invalid config for network bridge: invalid endpoint settings:\nnetwork-scoped alias is supported only for containers in user defined network
> 
> 你 docker compose 配置文件有问题

重装了，然后恢复数据了，现在正常了，不过依赖管理里面有几个linux的没装没事吧，什么bizcode

**Comment by whyour** [comment]
> > > invalid config for network bridge: invalid endpoint settings:\nnetwork-scoped alias is supported only for containers in user defined network
> > 
> > 
> > 你 docker compose 配置文件有问题
> 
> 重装了，然后恢复数据了，现在正常了，不过依赖管理里面有几个linux的没装没事吧，什么bizcode

翻译下日志，不知道从哪里看到的依赖
