### ISSUE TITLE
建议日志文件不要放在/ql/data

### ISSUE THREAD

**Issue by donething** [whyour/qinglong#2243]
### Clear and concise description of the problem

现在的日志文件放在了`/ql/data/log`下，导致vps中映射`/ql/data`到宿主机的备份目录时，要多备份很多文件

日志也不应该是`data`，建议不要放在`/ql/data`下

谢谢。。

### Suggested solution

建议就放在`/log`下

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
有什么影响？你可以选择你想映射的目录，日志也可以在系统设置里设置自动清理时间
