### ISSUE TITLE
2.17.0初始化页面提交无响应

### ISSUE THREAD

**Issue by aqiu9** [whyour/qinglong#2244]
### Qinglong version

2.17.0

### Steps to reproduce

我通过：
docker pull whyour/qinglong:latest
和
docker run -dit \
  -v $PWD/ql/data:/ql/data \
  -p 5700:5700 \
  -e QlBaseUrl="/" \
  -e QlPort="5700" \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest
跑起来了青龙服务，端口也已经放开，可以在公网正常访问到。但是不知道为什么初始化过程点击任何提交按钮都没有反应（无论是设置通知还是设置账户）？

### What is expected?

顺利完成初始化进入后台。

### What is actually happening?

点击按钮无任何反应，无法初始化。

### System Info

```shell
最新版刚安装完成，未完成初始化，未修改任何文件。
[root@iZ2vcjcri6ty7uppl4m43vZ ~]# docker exec -it f6fe62f7cb83 bash
root@qinglong:/ql $
root@qinglong:/ql $
root@qinglong:/ql $  npx envinfo --system --binaries --browser
Need to install the following packages:
  envinfo@7.11.0
Ok to proceed? (y) y

  System:
    OS: Linux 3.10 Alpine Linux
    CPU: (2) x64 Intel(R) Xeon(R) Platinum
    Memory: 1000.97 MB / 1.72 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.18.2 - /usr/bin/node
    npm: 9.6.6 - /usr/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
```

### Any additional comments?

CentOS7.9
无域名
阿里云服务器

**Comment by whyour** [comment]
我刚用你的 ip 初始化成功了，你本机的网络可能有问题，你用用户名和密码都是 1登录下，另外 issue 不要显示自己的登录地址

**Comment by aqiu9** [comment]
> 我刚用你的 ip 初始化成功了，你本机的网络可能有问题，你用用户名和密码都是 1登录下，另外 issue 不要显示自己的登录地址

万分感谢，确实可以登录了。感谢大佬提醒IP问题，安全问题确实要注意，下次我不会这样了！
但是感觉好奇怪啊，我网路一直通畅，我反复尝试，也换过浏览器尝试，同时也没有开启代理，为什么会出现这样的问题啊？！
再次感谢您如此快速又热心的回复，谢谢！

**Comment by aqiu9** [comment]
怪了，反而在开启代理之后不会再有这个问题，不开启代理修改账号密码时依然有这个问题，可能时校园网的问题吧
