### ISSUE TITLE
debian镜像更新后无法启动

### ISSUE THREAD

**Issue by jzksnsjswkw** [whyour/qinglong#2245]
### Qinglong version

2.16.5 -> 2.17.0

### Steps to reproduce

...

### What is expected?

...

### What is actually happening?

缺少unzip命令

### Any additional comments?

取消重启后进入容器手动`apt install zip`后再次更新可以更新成功，但是有几率下载到alpine版本的 docker-entrypoint.sh 导致缺少crond命令无法启动

**Comment by whyour** [comment]
确保映射 data 目录或者下载备份后，使用下面命令更新下 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>

**Comment by jzksnsjswkw** [comment]
> 确保映射 data 目录或者下载备份后，使用下面命令更新下 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>

主要是更新时应该检测有没有unzip命令

**Comment by whyour** [comment]
> > 确保映射 data 目录或者下载备份后，使用下面命令更新下 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
> 
> 主要是更新时应该检测有没有unzip命令

最新镜像已经添加了这个依赖，系统内升级会一直没有这个依赖
