### ISSUE TITLE
更新最近镜像后恢复数据重启数据没恢复

### ISSUE THREAD

**Issue by mijjjj** [whyour/qinglong#2246]
### Qinglong version

2.17.0

### Steps to reproduce

更新最近镜像后恢复数据重启数据没恢复，多重启几次或者关闭容器后打开恢复了，但是定时列表里面点击运行提示任务未运行
![image](https://github.com/whyour/qinglong/assets/37797122/dfa4e0fd-b44a-48f3-9c87-767e20328d65)

### What is expected?

恢复数据正常运行

### What is actually happening?

任务未运行

**Comment by whyour** [comment]
如无法正常恢复，上传完后，根据提示在容器内执行 ql reload data
