### ISSUE TITLE
您好   这确实是一个很好的工具  但是今天突然代码不能显示了   一直在加载

### ISSUE THREAD

**Issue by xiaoye123456** [whyour/qinglong#2248]
### Qinglong version

2.13.3

### Steps to reproduce

一直比较稳定  只是今天 代码就不能显示了   一直在加载

### What is expected?

一直比较稳定  只是今天 代码就不能显示了   一直在加载

### What is actually happening?

一直比较稳定  只是今天 代码就不能显示了   一直在加载

**Comment by Fashion0421** [comment]
我更新还报错了
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
.../node_modules/@whyour/sqlite3 install$ prebuild-install -r napi || node-gyp rebuild
.../node_modules/@whyour/sqlite3 install: gyp ERR! build error 
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack Error: not found: make
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at getNotFoundError (/ql/.tmp/qinglong-master/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:10:17)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-master/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:57:18
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at new Promise (<anonymous>)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at step (/ql/.tmp/qinglong-master/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:54:21)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-master/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:71:22
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at new Promise (<anonymous>)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at subStep (/ql/.tmp/qinglong-master/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:69:33)
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-master/node_modules/.pnpm/which@2.0.2/node_modules/which/which.js:80:22
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-master/node_modules/.pnpm/isexe@2.0.0/node_modules/isexe/index.js:42:5
.../node_modules/@whyour/sqlite3 install: gyp ERR! stack     at /ql/.tmp/qinglong-master/node_modules/.pnpm/isexe@2.0.0/node_modules/isexe/mode.js:8:5
.../node_modules/@whyour/sqlite3 install: gyp ERR! System Linux 3.10.0-1160.92.1.el7.x86_64
.../node_modules/@whyour/sqlite3 install: gyp ERR! command "/usr/bin/node" "/ql/.tmp/qinglong-master/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
.../node_modules/@whyour/sqlite3 install: gyp ERR! cwd /ql/.tmp/qinglong-master/node_modules/.pnpm/github.com+whyour+node-sqlite3@4fcd31f80caa3fc292356b9d99258b601c620488/node_modules/@whyour/sqlite3
.../node_modules/@whyour/sqlite3 install: gyp ERR! node -v v18.17.0
.../node_modules/@whyour/sqlite3 install: gyp ERR! node-gyp -v v8.4.1
.../node_modules/@whyour/sqlite3 install: gyp ERR! not ok 
.../node_modules/@whyour/sqlite3 install: Failed

**Comment by Fashion0421** [comment]
好了自己进去容器安装了make，重新打包就可以更新

**Comment by whyour** [comment]
可以使用宿主机执行 `docker run --rm -v  /var/run/docker.sock:/var/run/docker.sock  containrrr/watchtower -cR <容器名>`
另外你机器 cpu 是什么，是 arm 的？
