### ISSUE TITLE
添加node源，提示ERR_PNPM_NO_PKG_MANIFEST  No package.json

### ISSUE THREAD

**Issue by 7li7li** [whyour/qinglong#2249]
### Qinglong version

2.17.0

### Steps to reproduce

系统设置>node软件包镜像源码>输入淘宝源后>确认提示以下错误信息
in progress...
 ERR_PNPM_NO_PKG_MANIFEST  No package.json found in /root/.local/share/pnpm/global/5
update node mirror end
我是新装的docker镜像，如果需要手动创建json，我不知道这个json文件应该放在哪个目录下。也不清楚内容写什么

### What is expected?

同上

### What is actually happening?

同上

**Comment by whyour** [comment]
用的是最新的镜像吗，直接在依赖管理里安装一个 node 依赖试试？

**Comment by mimikko-like** [comment]
这题我会，但只会一半，我输入这个就没事儿了，好像是淘宝源的问题 https://registry.npmmirror.com

**Comment by mimikko-like** [comment]
这题我会，但只会一半，我是用脚本安装的依赖，脚本写了依赖的下载地址是淘宝，也出现这个问题，但我换了一个就没事儿了，好像是淘宝源的问题 https://registry.npmmirror.com/

**Comment by 7li7li** [comment]
> 这题我会，但只会一半，我是用脚本安装的依赖，脚本写了依赖的下载地址是淘宝，也出现这个问题，但我换了一个就没事儿了，好像是淘宝源的问题 https://registry.npmmirror.com/

不是淘宝源问题 切换其他源也报错

**Comment by 7li7li** [comment]
了解

**Comment by scccy** [comment]
我也遇到这个情况了，用脚本切换源，依赖安装失败

**Comment by whyour** [comment]
> ERR_PNPM_NO_PKG_MANIFEST  No package.json found in /root/.local/share/pnpm/global/5

系统设置里的切换源呢

**Comment by whyour** [comment]
如果用脚本换源，要确保依赖的源是当前的配置，这个问题可以执行 `pnpm store prune`

**Comment by gyq180** [comment]
> > ERR_PNPM_NO_PKG_MANIFEST  No package.json found in /root/.local/share/pnpm/global/5
> 
> 系统设置里的切换源呢

在2.17.0里的系统设置里切换还是报错
