### ISSUE TITLE
你好，咨询下怎么设置网络代理功能，最好可以指定哪几个定时任务走代理哪几个不走代理

### ISSUE THREAD

**Issue by Shuai-S** [whyour/qinglong#2253]
### Clear and concise description of the problem

你好，咨询下怎么设置网络代理功能，最好可以指定哪几个定时任务走代理哪几个不走代理，有的脚本需要走代理才能访问网络

### Suggested solution

就是给定时任务增加个代理的配置

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
可以在 task_before.sh 中根据 $1 脚本名称来判断增加代理变量
