### ISSUE TITLE
本机部署，报这个错误是什么原因呢

### ISSUE THREAD

**Issue by liuliang520500** [whyour/qinglong#2257]
### Qinglong version

v2.17.0

### Steps to reproduce

![QQ截图20240130112426](https://github.com/whyour/qinglong/assets/37011868/badc68c7-417a-42ef-8374-7c63bff0de89)

### What is expected?

是没有适配最新版本的NODE么，node版本，v20.10.0

### What is actually happening?

npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm ERR! code 1
npm ERR! path /home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install -r napi || node-gyp rebuild
npm ERR! make: Entering directory '/home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/sqlite3/build'
npm ERR!   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
npm ERR!   AR(target) Release/obj.target/../node-addon-api/nothing.a
npm ERR!   COPY Release/nothing.a
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c
npm ERR!   TOUCH Release/obj.target/deps/action_before_build.stamp
npm ERR!   CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3440200/sqlite3.o
npm ERR! make: Leaving directory '/home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/sqlite3/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@20.10.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.11 found at "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/bin/python3"
npm ERR! gyp info spawn /nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/runner/ql/.cache/node-gyp/20.10.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/runner/ql/.cache/node-gyp/20.10.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/runner/ql/.cache/node-gyp/20.10.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c: In function ‘sqlite3VdbeExec’:
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:95855:50: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 95855 |                    zPayload[6] = (u8)(v&0xff); v >>= 8;
npm ERR!       |                                                ~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:95856:11: note: here
npm ERR! 95856 |           case 6:  zPayload[5] = (u8)(v&0xff); v >>= 8;
npm ERR!       |           ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:95857:50: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 95857 |                    zPayload[4] = (u8)(v&0xff); v >>= 8;
npm ERR!       |                                                ~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:95858:11: note: here
npm ERR! 95858 |           case 4:  zPayload[3] = (u8)(v&0xff); v >>= 8;
npm ERR!       |           ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:95858:50: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 95858 |           case 4:  zPayload[3] = (u8)(v&0xff); v >>= 8;
npm ERR!       |                                                ~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:95859:11: note: here
npm ERR! 95859 |           case 3:  zPayload[2] = (u8)(v&0xff); v >>= 8;
npm ERR!       |           ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:95859:50: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 95859 |           case 3:  zPayload[2] = (u8)(v&0xff); v >>= 8;
npm ERR!       |                                                ~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:95860:11: note: here
npm ERR! 95860 |           case 2:  zPayload[1] = (u8)(v&0xff); v >>= 8;
npm ERR!       |           ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:95860:50: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 95860 |           case 2:  zPayload[1] = (u8)(v&0xff); v >>= 8;
npm ERR!       |                                                ~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:95861:11: note: here
npm ERR! 95861 |           case 1:  zPayload[0] = (u8)(v&0xff);
npm ERR!       |           ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c: In function ‘jsonParseValue’:
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:204385:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 204385 |     if( strncmp(z+i,"null",4)==0 && !sqlite3Isalnum(z[i+4]) ){
npm ERR!        |       ^
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:204391:3: note: here
npm ERR! 204391 |   default: {
npm ERR!        |   ^~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c: In function ‘cellArea’:
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208625:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 208625 |       case 5:  area  = p->aCoord[9].f - p->aCoord[8].f;
npm ERR!        |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208626:7: note: here
npm ERR! 208626 |       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208626:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 208626 |       case 4:  area *= p->aCoord[7].f - p->aCoord[6].f;
npm ERR!        |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208627:7: note: here
npm ERR! 208627 |       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208627:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 208627 |       case 3:  area *= p->aCoord[5].f - p->aCoord[4].f;
npm ERR!        |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208628:7: note: here
npm ERR! 208628 |       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208628:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 208628 |       case 2:  area *= p->aCoord[3].f - p->aCoord[2].f;
npm ERR!        |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208629:7: note: here
npm ERR! 208629 |       default: area *= p->aCoord[1].f - p->aCoord[0].f;
npm ERR!        |       ^~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208635:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 208635 |       case 5:  area  = (i64)p->aCoord[9].i - (i64)p->aCoord[8].i;
npm ERR!        |                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208636:7: note: here
npm ERR! 208636 |       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208636:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 208636 |       case 4:  area *= (i64)p->aCoord[7].i - (i64)p->aCoord[6].i;
npm ERR!        |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208637:7: note: here
npm ERR! 208637 |       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208637:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 208637 |       case 3:  area *= (i64)p->aCoord[5].i - (i64)p->aCoord[4].i;
npm ERR!        |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208638:7: note: here
npm ERR! 208638 |       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208638:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 208638 |       case 2:  area *= (i64)p->aCoord[3].i - (i64)p->aCoord[2].i;
npm ERR!        |                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:208639:7: note: here
npm ERR! 208639 |       default: area *= (i64)p->aCoord[1].i - (i64)p->aCoord[0].i;
npm ERR!        |       ^~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c: In function ‘rtreeCallbackConstraint’:
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207746:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 207746 |                 readCoord(pCellData+32, &c); aCoord[8] = c.f;
npm ERR!        |                                              ~~~~~~~~~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207747:7: note: here
npm ERR! 207747 |       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.f;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207748:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 207748 |                 readCoord(pCellData+24, &c); aCoord[6] = c.f;
npm ERR!        |                                              ~~~~~~~~~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207749:7: note: here
npm ERR! 207749 |       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.f;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207750:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 207750 |                 readCoord(pCellData+16, &c); aCoord[4] = c.f;
npm ERR!        |                                              ~~~~~~~~~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207751:7: note: here
npm ERR! 207751 |       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.f;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207752:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 207752 |                 readCoord(pCellData+8,  &c); aCoord[2] = c.f;
npm ERR!        |                                              ~~~~~~~~~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207753:7: note: here
npm ERR! 207753 |       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.f;
npm ERR!        |       ^~~~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207761:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 207761 |                 readCoord(pCellData+32, &c); aCoord[8] = c.i;
npm ERR!        |                                              ~~~~~~~~~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207762:7: note: here
npm ERR! 207762 |       case 8:   readCoord(pCellData+28, &c); aCoord[7] = c.i;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207763:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 207763 |                 readCoord(pCellData+24, &c); aCoord[6] = c.i;
npm ERR!        |                                              ~~~~~~~~~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207764:7: note: here
npm ERR! 207764 |       case 6:   readCoord(pCellData+20, &c); aCoord[5] = c.i;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207765:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 207765 |                 readCoord(pCellData+16, &c); aCoord[4] = c.i;
npm ERR!        |                                              ~~~~~~~~~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207766:7: note: here
npm ERR! 207766 |       case 4:   readCoord(pCellData+12, &c); aCoord[3] = c.i;
npm ERR!        |       ^~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207767:56: warning: this statement may fall through [-Wimplicit-fallthrough=]
npm ERR! 207767 |                 readCoord(pCellData+8,  &c); aCoord[2] = c.i;
npm ERR!        |                                              ~~~~~~~~~~^~~~~
npm ERR! Release/obj/gen/sqlite-autoconf-3440200/sqlite3.c:207768:7: note: here
npm ERR! 207768 |       default:  readCoord(pCellData+4,  &c); aCoord[1] = c.i;
npm ERR!        |       ^~~~~~~
npm ERR! gcc: fatal error: Killed signal terminated program cc1
npm ERR! compilation terminated.
npm ERR! make: *** [deps/sqlite3.target.mk:141: Release/obj.target/sqlite3/gen/sqlite-autoconf-3440200/sqlite3.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Linux 6.2.0-1019-gcp
npm ERR! gyp ERR! command "/nix/store/hdq16s6vq9smhmcyl4ipmwfp9f2558rc-nodejs-20.10.0/bin/node" "/home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/runner/ql/.config/npm/node_global/lib/node_modules/@whyour/qinglong/node_modules/sqlite3
npm ERR! gyp ERR! node -v v20.10.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

**Comment by whyour** [comment]
执行 `npm i -g prebuild-install`，然后再安装下
下个版本会修改下预编译的二进制包

**Comment by whyour** [comment]
重新安装 @whyour/qinglong
