### ISSUE TITLE
对比工具中编辑notify.js后保存出错

### ISSUE THREAD

**Issue by Ling128** [whyour/qinglong#2259]
### Qinglong version

正式版 v2.17.0（docker Debian）

### Steps to reproduce

 打开对比工具，源文件选择notify.js，当前文件编辑后点击保存，出现报错信息，如下图：

![image](https://github.com/whyour/qinglong/assets/9321969/2c8d6bbe-d20a-476b-826e-d0954766d08d)

### What is expected?

编辑后成功保存。

### What is actually happening?

编辑后保存失败。经测试，alpine和debian版本的docker镜像均存在此问题。

**Comment by whyour** [comment]
2.17.1 已修复
