### ISSUE TITLE
请问下大佬们，docker run后不生效，是我命令错了吗？

### ISSUE THREAD

**Issue by boyceavenue** [whyour/qinglong#226]
我用的是centos，拉取镜像后用命令创建容器：docker run --name qinglong -d qinglong
不知道命令哪里有问题了，希望大大们能帮帮忙QAQ

**Comment by q240627995** [comment]
x86运行：
docker run -dit -v $PWD/ql/config:/ql/config -v $PWD/ql/log:/ql/log -v $PWD/ql/db:/ql/db -p 5700:5700 --name qinglong --hostname qinglong --restart always whyour/qinglong:latest

arm64运行：
docker run -dit -v $PWD/ql/config:/ql/config -v $PWD/ql/log:/ql/log -v $PWD/ql/db:/ql/db -p 5700:5700 --name qinglong --hostname qinglong --restart always whyour/qinglong:latest
