### ISSUE TITLE
系统设置保存时报错WHERE parameter "type" has invalid "undefined" value

### ISSUE THREAD

**Issue by laishouchao** [whyour/qinglong#2260]
### Qinglong version

Docker lastest

### Steps to reproduce

常规Docker部署

### What is expected?

None

### What is actually happening?

![image](https://github.com/whyour/qinglong/assets/55373024/8535ba9d-606a-434e-b967-1c3d76223665)

**Comment by wwxiaoqi** [comment]
追踪到对应的执行逻辑手动执行即可，比如：

```log
WARN  GET  https://registry.npm.taobao.org/request error (CERT_HAS_EXPIRED).
```

淘宝 SSL 证书过期，需要修改设置中的 Node 软件包镜像源，手动找到相关逻辑
https://github.com/whyour/qinglong/blob/develop/back/services/system.ts#L137

```log
pnpm config set registry https://registry.npmmirror.com
```

**Comment by whyour** [comment]
镜像不是最新的吧，更新下镜像

**Comment by ishangyi** [comment]
2.17.1也这个报错

**Comment by tangtang666** [comment]
> 镜像不是最新的吧，更新下镜像


2.17.1也有这个问题，但是在配置文件中添加 `NpmMirror="https://registry.npmmirror.com"` 然后重启再添源点击保存不会报错了
