### ISSUE TITLE
建议在重命名脚本处，输入框自动带出现有脚本名

### ISSUE THREAD

**Issue by RachelAlucard** [whyour/qinglong#2263]
### Clear and concise description of the problem

版本：2.17.0
每次重命名脚本时，可能只是改个字母，却总是要重新输一边脚本名，比较麻烦。

### Suggested solution

建议重命名弹出的输入框，默认带上脚本当前名称

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
2.17.1 已支持
