### ISSUE TITLE
希望能在docker image里加个html2text工具

### ISSUE THREAD

**Issue by rendaa** [whyour/qinglong#2264]
### Clear and concise description of the problem

自己写了个某网站的签到脚本（bash的），需从返回的网页里提取某些文字，但那个内容是用grep或awk来提取，因为网页里html tag很多、要找的文字又是孤零零地放在一对html tag中间，所以希望能去除所有tag然后用上下文其它文字来找需要的那个文字。

目前用sed可以获得需要的基本效果，但比较麻烦（要-e好几个表达式）、又可能会有考虑不周全的情况。如果有html2text可能会省事一些。倒是可以直接在docker容器里-v一个宿主机的html2text到容器 /usr/bin/html2text ，但觉得有些破坏观瞻，最好是请青龙作者直接加到image里。

### Suggested solution

如上，在此感谢！

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
发成 js 或者 py 脚本，有相应模块
