### ISSUE TITLE
Docker debian版本，保存设置时报错

### ISSUE THREAD

**Issue by jincandev** [whyour/qinglong#2265]
### Qinglong version

2.17.0

### Steps to reproduce

系统正常运行起来后，点击系统设置->依赖设置->Node 软件包镜像源->输入 https://registry.npmmirror.com ->点击确认按钮。弹出错误提示：WHERE parameter "type" has invalid "undefined" value，且接口返回500

### What is expected?

期望正常设置相关的系统配置项

### What is actually happening?

错误提示：WHERE parameter "type" has invalid "undefined" value，且接口返回500

### System Info

```shell
System:
    OS: Linux 6.2 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD E2-9030 RADEON R2, 4 COMPUTE CORES 2C+2G
    Memory: 2.28 GB / 7.21 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
```

**Comment by whyour** [comment]
@jincandev 镜像不是最新的？再更新下试试
