### ISSUE TITLE
脚本管理-调试，运行后Permission Denied

### ISSUE THREAD

**Issue by jszgz** [whyour/qinglong#2266]
### Qinglong version

2.16.5

### Steps to reproduce

console.log("test");

### What is expected?

test

## 开始执行... 2024-02-05 12:34:45

/ql/shell/otask.sh: line 209: ./test1.swap: Permission denied

**Comment by whyour** [comment]
http://demo.dlww.cc:4433/script  在 demo 环境测试了下没问题，你可以试试

**Comment by icelts** [comment]
解决了么，我也遇到这个问题

**Comment by breakTBB** [comment]
因为你的文件没有加扩展名 加上`.js`就可以了

**Comment by breakTBB** [comment]
> 解决了么，我也遇到这个问题

加扩展名

**Comment by aqiu9** [comment]
有没有人遇到调试界面点击运行后，右侧并不会输出日志，只能切换到日志管理里面去查看？（v2.17.3）
这个功能曾经是好的，不知道什么时候就成这样了。

**Comment by NightGlowww** [comment]
> 有没有人遇到调试界面点击运行后，右侧并不会输出日志，只能切换到日志管理里面去查看？（v2.17.3）
> 
> 这个功能曾经是好的，不知道什么时候就成这样了。

我也遇到了这个问题！
