### ISSUE TITLE
Docker debian版本，如何指定版本

### ISSUE THREAD

**Issue by Wlbak** [whyour/qinglong#2268]
### Qinglong version

2.17.0

### Steps to reproduce

当我使用debian版本的时候，npm的got依赖会报错，指定2.16.5的版本，脚本运行就正常，但是alpine的某些python3依赖又安装不上，所以想请教一下，如何指定debian版本

### What is expected?

请教指定debian版本

### What is actually happening?

新版got报错

**Comment by whyour** [comment]
目前 debian 不支持切换版本，具体报什么错，依赖管理里指定 got 的版本 got@11

**Comment by Wlbak** [comment]
好的，我试试看，能不能解决，谢谢
