### ISSUE TITLE
[BUG]在定时任务那看到的日志，是只会显示手动执行的日志，自动运行的日志不会显示

### ISSUE THREAD

**Issue by q240627995** [whyour/qinglong#227]
认真观察后发现一个bug:
在定时任务那看到的日志，是只会显示手动执行的日志，自动运行的日志不会显示，
![image](https://user-images.githubusercontent.com/30516698/120457924-709b4980-c3c9-11eb-9b8d-f9105fccc2f8.png)

在专门的日志那里，选择你要看的任务，就会有确实有任务（定时自动）执行了
![image](https://user-images.githubusercontent.com/30516698/120458020-8577dd00-c3c9-11eb-9de7-b0e48265b579.png)

应该和 自动运行不会显示 运行中 一样，自动运行的日志也不会在这定时任务那里显示

**Comment by 231838238** [comment]
正常 我的也一样

**Comment by BIGBbox** [comment]
要看完整日志去日志系统看就可以了,这里应该只能看手动运行的日志
