### ISSUE TITLE
ql update fail

### ISSUE THREAD

**Issue by chen497147884** [whyour/qinglong#2270]
### Qinglong version

2.17.0

### Steps to reproduce

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2024-02-08T14:31:53:   code: 'ERR_DLOPEN_FAILED'
2|panel    | 2024-02-08T14:31:53: }
2|panel    | 2024-02-08T14:31:56: Error: Error relocating /ql/node_modules/.pnpm/github.com+whyour+node-sqlite3@4fcd31f80caa3fc292356b9d99258b601c620488/node_modules/@whyour/sqlite3/build/Release/node_sqlite3.node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
2|panel    | 2024-02-08T14:31:56:     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1181:18)
2|panel    | 2024-02-08T14:31:56:     at Module.load (node:internal/modules/cjs/loader:975:32)
2|panel    | 2024-02-08T14:31:56:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2|panel    | 2024-02-08T14:31:56:     at Module.require (node:internal/modules/cjs/loader:999:19)
2|panel    | 2024-02-08T14:31:56:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2|panel    | 2024-02-08T14:31:56:     at require (node:internal/modules/cjs/helpers:102:18)
2|panel    | 2024-02-08T14:31:56:     at bindings (/ql/node_modules/.pnpm/bindings@1.5.0/node_modules/bindings/bindings.js:112:48)
2|panel    | 2024-02-08T14:31:56:     at Object.<anonymous> (/ql/node_modules/.pnpm/github.com+whyour+node-sqlite3@4fcd31f80caa3fc292356b9d99258b601c620488/node_modules/@whyour/sqlite3/lib/sqlite3-binding.js:1:37)
2|panel    | 2024-02-08T14:31:56:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
2|panel    | 2024-02-08T14:31:56:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10) {
2|panel    | 2024-02-08T14:31:56:   code: 'ERR_DLOPEN_FAILED'
2|panel    | 2024-02-08T14:31:56: }

### What is expected?

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2024-02-08T14:31:53:   code: 'ERR_DLOPEN_FAILED'
2|panel    | 2024-02-08T14:31:53: }
2|panel    | 2024-02-08T14:31:56: Error: Error relocating /ql/node_modules/.pnpm/github.com+whyour+node-sqlite3@4fcd31f80caa3fc292356b9d99258b601c620488/node_modules/@whyour/sqlite3/build/Release/node_sqlite3.node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
2|panel    | 2024-02-08T14:31:56:     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1181:18)
2|panel    | 2024-02-08T14:31:56:     at Module.load (node:internal/modules/cjs/loader:975:32)
2|panel    | 2024-02-08T14:31:56:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2|panel    | 2024-02-08T14:31:56:     at Module.require (node:internal/modules/cjs/loader:999:19)
2|panel    | 2024-02-08T14:31:56:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2|panel    | 2024-02-08T14:31:56:     at require (node:internal/modules/cjs/helpers:102:18)
2|panel    | 2024-02-08T14:31:56:     at bindings (/ql/node_modules/.pnpm/bindings@1.5.0/node_modules/bindings/bindings.js:112:48)
2|panel    | 2024-02-08T14:31:56:     at Object.<anonymous> (/ql/node_modules/.pnpm/github.com+whyour+node-sqlite3@4fcd31f80caa3fc292356b9d99258b601c620488/node_modules/@whyour/sqlite3/lib/sqlite3-binding.js:1:37)
2|panel    | 2024-02-08T14:31:56:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
2|panel    | 2024-02-08T14:31:56:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10) {
2|panel    | 2024-02-08T14:31:56:   code: 'ERR_DLOPEN_FAILED'
2|panel    | 2024-02-08T14:31:56: }

### What is actually happening?

update success

### System Info

```shell
centeros7
```

**Comment by whyour** [comment]
docker 可以使用 docker 来更新镜像，更新玩再试试 ql update
