### ISSUE TITLE
其他设置日志删除频率和定时任务并发数无法保存

### ISSUE THREAD

**Issue by huhaku** [whyour/qinglong#2272]
### Qinglong version

正式版 v2.17.1

### Steps to reproduce

打开其他设置,点保存

### What is expected?

正常保存

### What is actually happening?

报错,无法保存
![image](https://github.com/whyour/qinglong/assets/3396694/1ecd3774-9ba7-4ae0-928f-38d22859b126)

### System Info

```shell
whyour/qinglong:debian
```

**Comment by huhaku** [comment]
设置镜像源也是一样的报错
![image](https://github.com/whyour/qinglong/assets/3396694/d50522c8-6d56-4b11-aac0-db89d43e976e)

**Comment by whyour** [comment]
镜像不是最新的吧

**Comment by huhaku** [comment]
> 镜像不是最新的吧

刚刚升级才新拉的镜像,在容器内部点升级也提示没最新的升级了

还有,这个依赖缺少是脚本还是容器的问题
![image](https://github.com/whyour/qinglong/assets/3396694/50fd4839-3790-4a9f-883c-ed68279c00ff)

**Comment by huhaku** [comment]
debain的也不能回退,不然想回退个镜像版本了,之前的版本是没问题的

**Comment by whyour** [comment]
> debain的也不能回退,不然想回退个镜像版本了,之前的版本是没问题的

之前版本指的哪个版本

**Comment by whyour** [comment]
建议提交 issue 前搜索下相关问题

**Comment by whyour** [comment]
> > 镜像不是最新的吧
> 
> 刚刚升级才新拉的镜像,在容器内部点升级也提示没最新的升级了
> 
> 还有,这个依赖缺少是脚本还是容器的问题 ![image](https://private-user-images.githubusercontent.com/3396694/303920367-50fd4839-3790-4a9f-883c-ed68279c00ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTgyNTgsIm5iZiI6MTcwNzY1Nzk1OCwicGF0aCI6Ii8zMzk2Njk0LzMwMzkyMDM2Ny01MGZkNDgzOS0zNzkwLTRhOWYtODgzYy1lZDY4Mjc5YzAwZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMTMyNTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2I4OTY3Yjk1MGQzYTlkYTE5ZjYxNDc3NTFjNTlkOTQwMzE3ZmM0YTNlYTJiMWIzNmMzOTJmZDM2NWIzMWMxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1uJxgX8lwY1rHIMDzUwMM3qM9dRbpT-SM-Dyd0LZrWQ)

运行脚本出现的就是脚本问题，容器依赖有问题，界面就进不去
