### ISSUE TITLE
你好，可以增加WxPusher的推送功能吗？

### ISSUE THREAD

**Issue by sobigworm** [whyour/qinglong#2279]
### Clear and concise description of the problem

2.17.1新版还是没有WxPusher的推送功能，目前用的方法是在替换青龙deps目录下的同名文件，希望可以增加，谢谢

### Suggested solution

[sendNotify.zip](https://github.com/whyour/qinglong/files/14326699/sendNotify.zip)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
repeat https://github.com/whyour/qinglong/issues/2188

**Comment by whyour** [comment]
可以使用自定义通知实现
