### ISSUE TITLE
启动容器总是卡在重新运行中

### ISSUE THREAD

**Issue by qq7984225** [whyour/qinglong#228]
![A88HX)OC6JH6_SY_BD0JBY](https://user-images.githubusercontent.com/85238021/120492286-840bdc00-c3ec-11eb-914c-58db28235417.png)
![QCZCKW)LN)WRUICNZXBMF83](https://user-images.githubusercontent.com/85238021/120492291-853d0900-c3ec-11eb-8f61-d77514878da7.png)

**Comment by whyour** [comment]
什么环境

**Comment by qq7984225** [comment]
vps docker> 什么环境
