### ISSUE TITLE
运行时间不能够精确到秒(s)了

### ISSUE THREAD

**Issue by JXDYYY** [whyour/qinglong#2280]
### Qinglong version

2.17.1

### Steps to reproduce

![Screenshot_20240221_012903](https://github.com/whyour/qinglong/assets/102240507/fc701be3-12de-41d4-a049-b234b8efba5e)
![Screenshot_20240221_013319](https://github.com/whyour/qinglong/assets/102240507/c8038ddf-69fb-4b1c-b8da-d0cd76d7e6d9)
如图可知道，定时00.00没有到秒可以运行，但是cron命令到了秒之后，没有运行

### What is expected?

修复可以支持运行到秒的定时规则，毕竟没升2.17.x之前也行的

### What is actually happening?

不会运行cron到秒的定时规则

**Comment by whyour** [comment]
用最新镜像重建下

**Comment by JXDYYY** [comment]
来了新bug，手动运行不显示日志，最新版，2.17.3






桃花灬缘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whyour/qinglong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月30日(星期六) 中午12:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whyour/qinglong] 运行时间不能够精确到秒(s)了 (Issue #2280)





 
用最新镜像重建下
