### ISSUE TITLE
进入系统日志，跟日志管理报错无法查看日志

### ISSUE THREAD

**Issue by YUXIKUN** [whyour/qinglong#2282]
### Qinglong version

2.17.1

### Steps to reproduce

增加多个脚本会出现

### What is expected?

期望：增加脚本数量多时，可以查看日志管理

### What is actually happening?

![日志管理](https://github.com/whyour/qinglong/assets/76829123/79f7f4ce-8eb1-4237-87c7-dc37296c41fd)
![日志管理1](https://github.com/whyour/qinglong/assets/76829123/e84536ff-aab1-4e0e-9860-5cf43319e225)

### System Info

```shell
{
    "code": 500,
    "message": "ELOOP: too many symbolic links encountered, stat '/ql/data/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log'"
}
```

**Comment by whyour** [comment]
你这日志目录有问题吧

**Comment by YUXIKUN** [comment]
> 你这日志目录有问题吧
没有修改过日志目录，装青龙的时候默认目录，换了另外一台机器装青龙，脚步加多了几个也出现了同样的问题

**Comment by whyour** [comment]
@YUXIKUN 新容器能复现吗，有复现步骤没

**Comment by YUXIKUN** [comment]
> @YUXIKUN 新容器能复现吗，有复现步骤没

这个就是新容器的，旧的设备我卖掉了，复现步骤应该是，拉订阅的时候，有一个是拉几百个脚本下来，后面再拉一些其他的脚本就容易出现，好像是必现的，我看下面有个提bug是说日志超过200还是多少会出现这个问题，具体的复现步骤就没有了

**Comment by whyour** [comment]
@YUXIKUN 那个 bug 说是日志超过 200？ tg 发我下地址看看？

**Comment by YUXIKUN** [comment]
> @YUXIKUN 那个 bug 说是日志超过 200？ tg 发我下地址看看？

https://github.com/whyour/qinglong/issues/2256 你看看这个，感觉有点关联，但是不知道是不是，我这里也是先加载一段时间，然后才报500

**Comment by whyour** [comment]
@YUXIKUN 这跟你这有什么关系

**Comment by YUXIKUN** [comment]
> @YUXIKUN 这跟你这有什么关系
>那就不知道怎么导致的了，没有稳定的复现步骤🤣🤣🤣

**Comment by whyour** [comment]
你 log 目录下还有个 log 目录？

**Comment by YUXIKUN** [comment]
> 你 log 目录下还有个 log 目录？

这个应该是自己写入创建，第一次拉脚步的时候还是正常的

**Comment by whyour** [comment]
> > 你 log 目录下还有个 log 目录？
> 
> 这个应该是自己写入创建，第一次拉脚步的时候还是正常的

不会啊，有脚本目录是 log 开头的？你删除就好了

**Comment by YUXIKUN** [comment]
> > > 你 log 目录下还有个 log 目录？
> > 
> > 这个应该是自己写入创建，第一次拉脚步的时候还是正常的
> 
> 不会啊，有脚本目录是 log 开头的？你删除就好了

也对啊，我去删了看看🤣🤣🤣

**Comment by whyour** [comment]
2.17.4 已修复
