### ISSUE TITLE
订阅管理支持utils文件、任务定时规则、自动安装依赖

### ISSUE THREAD

**Issue by nashaofu** [whyour/qinglong#2286]
### Clear and concise description of the problem

在订阅规则时希望能有下面这些功能：
1. 希望自动安装依赖。
2. 希望能导入utils文件，而不把utils文件添加到任务，在实际编写脚本的时候，会有很多重复逻辑，希望能抽取到公共文件，减少维护工作量。
3. 还有就是订阅的任务能指定cronjob时间吗？不想订阅后还要到任务列表修改定时规则

### Suggested solution

针对问题2，3希望支持指定配置文件，用来指定任务与任务配置

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
2. 订阅里的依赖文件是直接拷贝
3. 脚本里的注释里可以写 crontab 表达式
```js
/**
 * cron: 2 0 * * *
 */
```

```py
'''
cron: 0 9 * * *
'''
```

**Comment by nashaofu** [comment]
怎么让某一个脚本不被添加到任务呢，但是我需要把脚本拉下来

**Comment by whyour** [comment]
@nashaofu 黑名单

**Comment by nashaofu** [comment]
> @nashaofu 黑名单

黑名单好像不会把文件保存下来，我是需要把文件保存下来，但是不添加到任务

**Comment by whyour** [comment]
@nashaofu 上面不是说了依赖文件吗

**Comment by nashaofu** [comment]
> @nashaofu 上面不是说了依赖文件吗

了解
