### ISSUE TITLE
无法设置依赖设置

### ISSUE THREAD

**Issue by caixiaohaier** [whyour/qinglong#2289]
### Qinglong version

2.17.1

### Steps to reproduce

全新安装青龙面板后，进入系统设置-依赖设置，无法设置“代理”以及“软件包安装源”，输入值后点击确认进行保存即报错。

### What is expected?

保存成功

### What is actually happening?

![1708953998322](https://github.com/whyour/qinglong/assets/48126754/33ee0ca3-f09c-4e6f-8804-9be7baebd99b)

### System Info

```shell
Debian12.5操作系统，1Panel面板，安装的青龙面板2.17.1
```

**Comment by whyour** [comment]
是最新版镜像？容器内容空的也报错？

**Comment by liaokongVFX** [comment]
v2.17.2 也有同样的问题。

**Comment by whyour** [comment]
@liaokongVFX 新容器？

**Comment by liaokongVFX** [comment]
> @liaokongVFX 新容器？

嗯嗯，是的

**Comment by whyour** [comment]
> > @liaokongVFX 新容器？
> 
> 嗯嗯，是的

空数据也会吗，还是用的原有数据？用的是最新镜像吗

**Comment by liaokongVFX** [comment]
> > > @liaokongVFX 新容器？
> > 
> > 
> > 嗯嗯，是的
> 
> 空数据也会吗，还是用的原有数据？用的是最新镜像吗

嗯嗯，用的最新镜像。是空数据，新跑的这个服务。

**Comment by masgg** [comment]
> > > > @liaokongVFX 新容器？
> > > 
> > > 
> > > 嗯嗯，是的
> > 
> > 
> > 空数据也会吗，还是用的原有数据？用的是最新镜像吗
> 
> 嗯嗯，当时那天用的最新镜像，安装完成后青龙版本是v2.17.2。是空数据，是新搭的这个服务。原本是想装个python的requests库来着，发现通过依赖管理里面装报错了，原因是用默认的源安装超时了。然后就看到有这个配置，就打算配置一下。配置的时候发现有这个报错了。

这个问题解决了吗？

**Comment by wangfreexx** [comment]
在配置文件里面增加一行NpmMirror="https://registry.npmmirror.com"，然后重启docker就可以保存了

**Comment by whyour** [comment]
demo 环境无法复现，http://demo.ninesix.cc:4433/dependence
