### ISSUE TITLE
2.17.1手动执行任务部显示日志，自动任务正常

### ISSUE THREAD

**Issue by hackgsl** [whyour/qinglong#2291]
### Qinglong version

手动执行任务部显示日志，自动任务正常

### Steps to reproduce

ArmBian系统在控制面板里面从V2.16.*升级到V2.17.0后，出现了手动执行任务时查看不了日志，自动执行正常的，但会导致任务生成的配置文件结果为空。

### What is expected?

昨天从系统内升级到V2.17.1后启动一直转圈，使用docker run --rm -v  /var/run/docker.sock:/var/run/docker.sock  containrrr/watchtower -cR qinglong 命令修复无效
故删除镜像后重新建立镜像并恢复数据，系统登录正常，但日志不恢复，以及手动执行的任务查看不了日志的问题一样存在

### What is actually happening?

看过历史问题说重新建镜像就可以但我重建了2次都一样

**Comment by hackgsl** [comment]
刚刚试着删除镜像，从新拉取2.16.5镜像，重新创建容器，恢复备份数据后测试手动执行任务日志正常
且安装Linux依赖：gcc g++ make libffi-dev openssl-dev 时速度很快，昨天在公司的VM虚拟机centos系统及家里armbian系统恢复后再Linux依赖环节半小时都没完成，只能恢复后强行断网让他失败跳过才行

**Comment by whyour** [comment]
依赖问题要到系统设置中，依赖设置添加镜像源或者代理，确保镜像是最新的

**Comment by DioHamilton2020** [comment]
同样有这个问题，等解决

**Comment by BonjourYY** [comment]
升级到2.17.2，手动执行任务，同样不显示日志，只显示‘任务未运行’，等待解决。

**Comment by dgulan** [comment]
> 升级到2.17.2，手动执行任务，同样不显示日志，只显示‘任务未运行’，等待解决。

同样的问题：手动执行任务，只显示“任务未运行”

**Comment by Chenawsl** [comment]
相同的问题：手动执行任务，只显示“任务未运行”

**Comment by Chenawsl** [comment]
> 升级到2.17.2，手动执行任务，同样不显示日志，只显示‘任务未运行’，等待解决。

相同的问题：手动执行任务，只显示“任务未运行”

**Comment by dgulan** [comment]
> > 升级到2.17.2，手动执行任务，同样不显示日志，只显示‘任务未运行’，等待解决。
> 
> 相同的问题：手动执行任务，只显示“任务未运行”

补充一下：我将群晖重启了以后，2.17.2任务运行正常了。

**Comment by DioHamilton2020** [comment]
看了楼上，重启镜像后，解决了。

**Comment by cyxnzb** [comment]
最新版本还是有这个bug,v2.17..3
