### ISSUE TITLE
token过期问题，api接口修改环境变量

### ISSUE THREAD

**Issue by chenkui-it** [whyour/qinglong#2292]
### Clear and concise description of the problem

京东的token的过期时间很短，最短三天；自己开发京东自动登录的脚本，获取到token后通过api更新到，青龙服务器中；

### Suggested solution

在青龙服务中添加api接口，用于设置环境变量，期望采纳~~

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
https://t.me/jiao_long/166
系统设置-应用管理，添加应用后用 openapi 修改环境变量即可
