### ISSUE TITLE
任务运行时，点击操作_日志，界面显示任务未运行，实际任务在运行

### ISSUE THREAD

**Issue by Jasonandzs** [whyour/qinglong#2295]
### Qinglong version

正式版  v2.17.1

### Steps to reproduce

将任务手动运行，查看运行中的任务日志

### What is expected?

运行中的任务日志应可查看

### What is actually happening?

将任务手动运行，查看运行中的任务日志

**Comment by whyour** [comment]
建议删除容器重建
