### ISSUE TITLE
脚本目录中多了一个100多MB的文件`core`

### ISSUE THREAD

**Issue by donething** [whyour/qinglong#2297]
### Qinglong version

正式版 v2.17.1

### Steps to reproduce

似乎安装依赖后生成的？我删除后，面板页面会闪烁，看到`依赖`那里正在重新安装依赖

### What is expected?

不建议在用户拉取的脚本所在的目录创建，不便备份数据

### What is actually happening?

不建议在用户拉取的脚本所在的目录创建，不便备份数据

**Comment by whyour** [comment]
脚本执行异常出现的，没用

**Comment by donething** [comment]
> 脚本执行异常出现的，没用

没用也能不能写入在别的地方，尽量不要在`/ql/data`目录下。。。
