### ISSUE TITLE
订阅单文件下载失败

### ISSUE THREAD

**Issue by D06F6E67** [whyour/qinglong#2298]
### Qinglong version

2.17.0

### Steps to reproduce

<img width="965" alt="image" src="https://github.com/whyour/qinglong/assets/49577616/4a65d9b8-b184-4839-a187-112cd4364e45">
<img width="1201" alt="image" src="https://github.com/whyour/qinglong/assets/49577616/4a235fb5-8a81-45d7-9e6d-6e2f78db4bbd">
直接用ql raw 是可以的

### What is expected?

订阅中可以正常下载单脚本

### What is actually happening?

订阅中下载 js脚本 失败，保留之前正常下载的版本...

### System Info

```shell
System:
    OS: Linux 5.10 Alpine Linux
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 5.81 GB / 14.87 GB
    Container: Yes
    Shell: 1.36.1 - /bin/ash
  Binaries:
    Node: 18.18.2 - /usr/bin/node
    npm: 9.6.6 - /usr/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnp
```

**Comment by whyour** [comment]
无法复现，建议查看网络问题，看是否需要增加代理
