### ISSUE TITLE
日志界面能否加个自动刷新功能

### ISSUE THREAD

**Issue by lxr760** [whyour/qinglong#230]
有些脚本，运行时间很长，可能你看日志的时候还没跑完

所以，能否加个自动刷新。

当日志界面最下面未出现  “***, 结束! 🕛 *** 秒”     这时判断为脚本未运行完，则自动刷新当前页面，直到脚本跑完

**Comment by whyour** [comment]
加个重新获取操作吧

**Comment by lxr760** [comment]
> 加个重新获取操作吧

或者把日志列表那改成一直显示，需要刷新的时候，再次点击即可。现在日志列表点完就自动隐藏，再次点击会比较麻烦

**Comment by lxr760** [comment]
> > > 加个重新获取操作吧
> > 
> > 
> > 或者把日志列表那改成一直显示，需要刷新的时候，再次点击即可。现在日志列表点完就自动隐藏，再次点击会比较麻烦
> 
> 有人提了个左侧显示日志列表的pr，我这几天看看

左侧固定显示也不错
