### ISSUE TITLE
大佬你好，我安装完成就一直卡在登录界面，登录不进去

### ISSUE THREAD

**Issue by chaotianjiao** [whyour/qinglong#2301]
### Qinglong version

2.11.3

### Steps to reproduce

![image](https://github.com/whyour/qinglong/assets/42534375/0671d674-6cdf-4aa8-ba6f-bb7ec907abb8)

### What is expected?

想要 能够登录进去

### What is actually happening?

![image](https://github.com/whyour/qinglong/assets/42534375/55d6b32b-1276-4f15-abd3-4a45ec51ad59)

**Comment by whyour** [comment]
https://github.com/whyour/qinglong?tab=readme-ov-file#docker-%E6%8E%A8%E8%8D%90  这是 docker 命令，不清楚你的脚本是怎么安装的

**Comment by chaotianjiao** [comment]
大佬你好，我已经把阿里云的系统重装了
安装命令就是按照:
`docker pull whyour/qinglong:latest`
然后是：
`# curl -sSL get.docker.com | sh
docker run -dit \
  -v $PWD/ql/data:/ql/data \
  # 冒号后面的 5700 为默认端口，如果设置了 QlPort, 需要跟 QlPort 保持一致
  -p 5700:5700 \
  # 部署路径非必须，比如 /test
  -e QlBaseUrl="/" \
  # 部署端口非必须，当使用 host 模式时，可以设置服务启动后的端口，默认 5700
  -e QlPort="5700" \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest`
这样的，现在访问还是卡在：
![image](https://github.com/whyour/qinglong/assets/42534375/b8260420-1bad-4d0f-8495-0a5afb132c33)

这个界面进不去

**Comment by chaotianjiao** [comment]
![image](https://github.com/whyour/qinglong/assets/42534375/73e09e14-94c6-44a0-b727-0648c88c971d)
为什么我一点登录jiuxian就显示网络错误

**Comment by whyour** [comment]
阿里云镜像有缓存，使用指定版本或者修改 docker 镜像源

**Comment by mima454188** [comment]
![image](https://github.com/whyour/qinglong/assets/74166821/49153322-0f41-4826-b1e4-7897da661a52)
![image](https://github.com/whyour/qinglong/assets/74166821/184891da-369d-4617-a49c-4f7f9fe79909)
老大 我也是进不去 也check了 然后看pm2 logs 显示这个

**Comment by chaotianjiao** [comment]
> 阿里云镜像有缓存，使用指定版本或者修改 docker 镜像源

大佬，我已经是按照[https://docs.docker.com/engine/install/ubuntu/](url) 来安装的docker了，
错误还是依旧：
![image](https://github.com/whyour/qinglong/assets/42534375/aa9dac6f-ed1c-46a0-b869-ea89fcb636b6)

**Comment by whyour** [comment]
> > 阿里云镜像有缓存，使用指定版本或者修改 docker 镜像源
> 
> 大佬，我已经是按照[https://docs.docker.com/engine/install/ubuntu/](url) 来安装的docker了， 错误还是依旧： ![image](https://private-user-images.githubusercontent.com/42534375/314427470-aa9dac6f-ed1c-46a0-b869-ea89fcb636b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTMwMzMsIm5iZiI6MTcxNDg5MjczMywicGF0aCI6Ii80MjUzNDM3NS8zMTQ0Mjc0NzAtYWE5ZGFjNmYtZWQxYy00NmEwLWI4NjktZWE4OWZjYjYzNmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA3MDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmM2UyMjkyYWY0ZmE5MDVhNjg4NGFjYTU5ZjUyNGY3ZGFhOWZjNjc4OGY0NmE0MjdiMzA4N2NjMWUyNzhkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VuhD-inAEm63-R_lBNWKmiRJ3ZtgSRXH0yWpMHakRz0)

你这是网络有问题
