### ISSUE TITLE
群晖docker拉取的版本还是V2.10.13

### ISSUE THREAD

**Issue by gkgx163** [whyour/qinglong#2304]
### Qinglong version

V2.10.13

### Steps to reproduce

在群晖docker中拉取最新版本，安装后版本号显示为V2.10.13。

### What is expected?

希望更新到最新版本。

### What is actually happening?

在群晖docker中拉取最新版本，安装后版本号显示为V2.10.13。

**Comment by whyour** [comment]
拉取  `whyour/qinglong:2.17.2` 或者修改 docker 镜像源
