### ISSUE TITLE
pushme

### ISSUE THREAD

**Issue by hutuxionggege** [whyour/qinglong#2305]
### Qinglong version

2.17

### Steps to reproduce

push+发送一对多通知消息失败：无效的用户token

### What is expected?

push+发送一对多通知消息失败：无效的用户token

### What is actually happening?

push+发送一对多通知消息失败：无效的用户token

**Comment by whyour** [comment]
使用最新的通知文件，按照提示修改

**Comment by hutuxionggege** [comment]
你好，你的邮件我已经收到，非常感谢。我的微信是：tianyi86913  希望我们保持联系。
