### ISSUE TITLE
系统日志显示所有订阅管理拉库命令[panel][执行任务失败]

### ISSUE THREAD

**Issue by wavetg** [whyour/qinglong#2306]
### Qinglong version

2.17.2

### Steps to reproduce

无论是手动运行还是触发订阅管理定时命令，均显示[panel][执行任务失败]，但在订阅管理中的日志却显示执行成功，错误日志也不对，在demo中添加任意订阅，手动运行，也能得到复现

### What is expected?

正确显示订阅运行状态

### What is actually happening?

![image](https://github.com/whyour/qinglong/assets/19207540/f69e86f9-5456-4e11-b24d-00df79f4fbbb)
[panel][执行任务失败] 命令: SUB_ID=14 ql repo "https://github.com/keven1024/qinglong_helper.git" "" "depend" "depend" "" "" "" "true" "true", 错误信息: "Cloning into '/ql/data/repo/keven1024_qinglong_helper'...\n"

**Comment by whyour** [comment]
2.17.3 已修复
