### ISSUE TITLE
运行脚本日志直接就结束了

### ISSUE THREAD

**Issue by gethin52** [whyour/qinglong#231]
老哥，这种怎么解决啊？
![image](https://user-images.githubusercontent.com/51164894/120610181-7f473680-c485-11eb-9d91-a23cbf66760d.png)

**Comment by gethin52** [comment]
![image](https://user-images.githubusercontent.com/51164894/120610480-c9c8b300-c485-11eb-960a-afad4235aeb1.png)

**Comment by whyour** [comment]
手动在容器内执行呢
