### ISSUE TITLE
青龙面板中定时任务等全是空的

### ISSUE THREAD

**Issue by QQQWLX** [whyour/qinglong#2310]
### Qinglong version

2.17.2

### Steps to reproduce

在群晖DSM7.2.1 docker中安装青龙面板, 不管是哪个版本, 安装后显示版本 2.10.13. 拉库后, 显示拉库成功. 但列表是空的, 打开脚本管理, 会显示 "The "path" argument must be of type string. Received undefined", 所以里面内容也是空的. 

### What is expected?

估计是哪个脚本的环境变量有问题, 但我查不到

### What is actually happening?

![image](https://github.com/whyour/qinglong/assets/39115868/6118ad50-2141-4e99-888a-d8b10264b8ef)
![image](https://github.com/whyour/qinglong/assets/39115868/81d3a6d6-ba29-41f4-a400-67d945415ca7)

**Comment by QQQWLX** [comment]
更新了DSM7.2后, 安装了好多次, 一直这样. 甚至删除所有注册表和images, 新安装, 也是一样.

**Comment by QQQWLX** [comment]
![image](https://github.com/whyour/qinglong/assets/39115868/b733e6ae-b087-4578-ba97-8b1c67139159)
点击脚本管理, 显示 "The "path" argument must be of type string. Received undefined", 我想问题就在"path"上

**Comment by whyour** [comment]
看你的镜像是不是不对，或者镜像改成指定版本 whyour/qinglong:2.17.2

**Comment by QQQWLX** [comment]
![image](https://github.com/whyour/qinglong/assets/39115868/c85caaf4-4b39-468e-aaed-040f16a9543e)
我安装的是debian, latest也试过, 一样. 有一次安装后拉库有显示任务时, 面板上的版本号就变成 2.17.2了, 但第二天登录又和现在一样了. 而且再也回不去了.

**Comment by QQQWLX** [comment]
而且我在命令行查询日志, 任务运行是正常的. 就是面板上无法看到

**Comment by QQQWLX** [comment]
现在发觉用 IP:端口/initialization 就能正常, 版本显示也是v2.17.2了, 望参考
