### ISSUE TITLE
安装依赖没权限

### ISSUE THREAD

**Issue by wenjiamian** [whyour/qinglong#2314]
### Qinglong version

2.17.2

### Steps to reproduce

<img width="777" alt="image" src="https://github.com/whyour/qinglong/assets/34673454/c2befdc2-9da5-428c-adc8-afb320294358">

### What is expected?

没权限

### What is actually happening?

没权限

### System Info

```shell
群晖7.2.1
```

**Comment by whyour** [comment]
换个 lunux 源，依赖一个个装
