### ISSUE TITLE
希望增加WxPusher推送通知

### ISSUE THREAD

**Issue by qwe77889** [whyour/qinglong#2316]
### Clear and concise description of the problem

希望增加WxPusher推送通知

### Suggested solution

希望增加WxPusher推送通知

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by qwe77889** [comment]
希望增加WxPusher推送通知，这个推送挺好用的，排版也很好，标志都可以自己创建，很不错，希望大佬能添加

**Comment by whyour** [comment]
repeat https://github.com/whyour/qinglong/issues/2188

**Comment by whyour** [comment]
可以使用自定义通知实现
