### ISSUE TITLE
由上一版本升级正式版 v2.17.3后，“重新启动”功能失效

### ISSUE THREAD

**Issue by wifisky-feilian** [whyour/qinglong#2321]
### Qinglong version

正式版 v2.17.3

### Steps to reproduce

由上一版本升级正式版 v2.17.3后，“重新启动”功能失效，点击“重新启动”后，跳转到“定时任务”功能

### What is expected?

由上一版本升级正式版 v2.17.3后，“重新启动”功能失效，点击“重新启动”后，跳转到“定时任务”功能

### What is actually happening?

由上一版本升级正式版 v2.17.3后，“重新启动”功能失效，点击“重新启动”后，跳转到“定时任务”功能

**Comment by whyour** [comment]
@wifisky-feilian 使用最新镜像重建下
