### ISSUE TITLE
node的ES6语法

### ISSUE THREAD

**Issue by xiaohuacc** [whyour/qinglong#2322]
### Qinglong version

2.17.3

### Steps to reproduce

青龙面板如何使用nodejs的ES6语法，node脚本import导入依赖运行报错，并没有找到修改package.json文件。

### What is expected?

无

### What is actually happening?

无

**Comment by catlair** [comment]
是import？可以把后缀js改为mjs

**Comment by whyour** [comment]
后缀可以改成 ts
