### ISSUE TITLE
拉取任务一直未运行行

### ISSUE THREAD

**Issue by night-rainy** [whyour/qinglong#2323]
### Qinglong version

v2.17.3

### Steps to reproduce

手动执行拉取任务,日志打印任务未运行

### What is expected?

点击任务可以运行

### What is actually happening?

我点击拉取任务,任务日志打印任务未运行
![image](https://github.com/whyour/qinglong/assets/63355265/c3889265-d508-4af1-9ca4-0394276dfb9a)

**Comment by whyour** [comment]
repo 命令迁移到 订阅管理中，拷贝原始命令，新建订阅，直接粘贴即可
