### ISSUE TITLE
最新的版本中pip源 是如何配置的？

### ISSUE THREAD

**Issue by qq846511277** [whyour/qinglong#2325]
## 安装python依赖时指定pip源
PipMirror="https://pypi.doubanio.com/simple/"
这样的指令是否还有作用

## 安装python依赖时指定pip源
PipMirror="https://pypi.doubanio.com/simple/"
这样的指令是否还有作用

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
@qq846511277 在系统设置—依赖设置中设置，这个变量不需要了
