### ISSUE TITLE
重启后没办法进面板，但是系统在运行

### ISSUE THREAD

**Issue by lkl727** [whyour/qinglong#2326]
### Qinglong version

2.17.3

### Steps to reproduce

已经升级到最新版本了，重启容器后无法进入，但能收到运行后的脚本通知，脚本在运行。
我倒是也设置了清除日志时间 30 天，不知道是不是这问题。
有没有人能帮解决的？

错误提示：
pm2 logs panel
暂无日志

### What is expected?

不能进入青龙面板

### What is actually happening?

错误 i日志

**Comment by netmankind** [comment]
重启服务器试试

**Comment by lkl727** [comment]
这个应该是那个 脚本目录及日志目录下面多出来的那个 文件的问题，估计删除那两个文件就可以好了，
据说是因为设置了  30 天清除日志的问题，说是 30 天时间太长了。

**Comment by lkl727** [comment]
估计这个问题 升级最新的 2.17.4 就可以解决了
