### ISSUE TITLE
通知能否支持anpush

### ISSUE THREAD

**Issue by monyuan** [whyour/qinglong#2334]
### Clear and concise description of the problem

内置的如server酱是不支持tg、whatsapp推送的，用青龙做外贸相关的工作，希望能够支持的

### Suggested solution

建议新增对此支持 https://anpush.com/doc

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
使用自定义通知就可以了
