### ISSUE TITLE
通知能否支持VoceChat

### ISSUE THREAD

**Issue by roadinger** [whyour/qinglong#2336]
### Clear and concise description of the problem

一些三方通知应用都有频率限制

### Suggested solution

希望支持下自建服务VoceChat

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
使用自定义通知，可以实现任何通知

<img width="1054" alt="image" src="https://github.com/whyour/qinglong/assets/22700758/dc730e43-eb14-4cbe-a927-d444d1ce4414">

**Comment by roadinger** [comment]
WEBHOOK_CONTENT_TYPE="text/plain" 时WEBHOOK_BODY怎么填？

export WEBHOOK_BODY="$content" 吗？


我就是要通过接口直接发文本消息，不需要消息模版






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whyour/qinglong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月11日(星期四) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whyour/qinglong] 通知能否支持VoceChat (Issue #2336)





 
使用自定义通知，可以实现任何通知
 image.png (view on web)

**Comment by whyour** [comment]
具体你看接口参数，需要设置什么，不需要的话可以为空

**Comment by roadinger** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "roadinger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月15日(星期一) 晚上6:26
***@***.***&gt;;

主题:&nbsp;回复： [whyour/qinglong] 通知能否支持VoceChat (Issue #2336)




这样设置的，消息发送会直接发$title  $content




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "roadinger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月12日(星期五) 中午11:04
***@***.***&gt;;

主题:&nbsp;回复： [whyour/qinglong] 通知能否支持VoceChat (Issue #2336)



WEBHOOK_CONTENT_TYPE="text/plain" 时WEBHOOK_BODY怎么填？

export WEBHOOK_BODY="$content" 吗？


我就是要通过接口直接发文本消息，不需要消息模版






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "whyour/qinglong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月11日(星期四) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whyour/qinglong] 通知能否支持VoceChat (Issue #2336)





 
使用自定义通知，可以实现任何通知
 image.png (view on web)

**Comment by roadinger** [comment]
content-type: text/plain  时，消息体无法直接发送

**Comment by roadinger** [comment]
content-type: text/plain 时，消息体无法直接发送
![微信截图_20240416101558](https://github.com/whyour/qinglong/assets/13794003/4f7f8bb0-f173-432c-8979-21cc1642e625)

**Comment by roadinger** [comment]
这样不行
![01](https://github.com/whyour/qinglong/assets/13794003/382c1322-2530-4101-b8f3-8db6719ef181)

**Comment by roadinger** [comment]
具体的参数是这些，我该怎么设置
![02](https://github.com/whyour/qinglong/assets/13794003/2e08d91e-5582-4b3e-a734-a6765ec4472a)

**Comment by whyour** [comment]
你用的什么脚本，现在返回什么？

**Comment by whyour** [comment]
<img width="821" alt="image" src="https://github.com/whyour/qinglong/assets/22700758/f1ba62c4-3ba7-473c-b446-2e8dd6e4d102">
下面多了，header 只要 x-api-key 就行

**Comment by roadinger** [comment]
webhookHeaders不添加content-type: text/plain   消息发送报错
加了消息会直接发送 $title   $content
![03](https://github.com/whyour/qinglong/assets/13794003/35f939be-0507-4a12-a2b8-1ee27d4b1f32)

**Comment by roadinger** [comment]
![04](https://github.com/whyour/qinglong/assets/13794003/a1564a0a-b8d0-4ba3-ad7b-e9799678493b)

**Comment by whyour** [comment]
> webhookHeaders不添加content-type: text/plain 消息发送报错 加了消息会直接发送 $title $content ![03](https://private-user-images.githubusercontent.com/13794003/322682717-35f939be-0507-4a12-a2b8-1ee27d4b1f32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzU0NjQsIm5iZiI6MTcxMzIzNTE2NCwicGF0aCI6Ii8xMzc5NDAwMy8zMjI2ODI3MTctMzVmOTM5YmUtMDUwNy00YTEyLWEyYjgtMWVlMjdkNGIxZjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAyMzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNjQyY2Q5YzViMjg3NTFiMzY0NTg5NDJhMTFiMGFjZjYzNGVkYzI3Njk1YWFjOWFjNmM4MDUyMDY3ODM0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JpgGqVbBJeMd_UO5Od0CS-4y1ks7uOJk790RB_SioH4)

不加报什么错

**Comment by roadinger** [comment]
> > webhookHeaders不添加content-type: text/plain 消息发送报错 加了消息会直接发送 $title $content ![03](https://private-user-images.githubusercontent.com/13794003/322682717-35f939be-0507-4a12-a2b8-1ee27d4b1f32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzU0NjQsIm5iZiI6MTcxMzIzNTE2NCwicGF0aCI6Ii8xMzc5NDAwMy8zMjI2ODI3MTctMzVmOTM5YmUtMDUwNy00YTEyLWEyYjgtMWVlMjdkNGIxZjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAyMzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNjQyY2Q5YzViMjg3NTFiMzY0NTg5NDJhMTFiMGFjZjYzNGVkYzI3Njk1YWFjOWFjNmM4MDUyMDY3ODM0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JpgGqVbBJeMd_UO5Od0CS-4y1ks7uOJk790RB_SioH4)
> 
> 不加报什么错

the client request does not include the `Content-Type` header

**Comment by whyour** [comment]
> > > webhookHeaders不添加content-type: text/plain 消息发送报错 加了消息会直接发送 $title $content ![03](https://private-user-images.githubusercontent.com/13794003/322682717-35f939be-0507-4a12-a2b8-1ee27d4b1f32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzU0NjQsIm5iZiI6MTcxMzIzNTE2NCwicGF0aCI6Ii8xMzc5NDAwMy8zMjI2ODI3MTctMzVmOTM5YmUtMDUwNy00YTEyLWEyYjgtMWVlMjdkNGIxZjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAyMzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNjQyY2Q5YzViMjg3NTFiMzY0NTg5NDJhMTFiMGFjZjYzNGVkYzI3Njk1YWFjOWFjNmM4MDUyMDY3ODM0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JpgGqVbBJeMd_UO5Od0CS-4y1ks7uOJk790RB_SioH4)
> > 
> > 
> > 不加报什么错
> 
> the client request does not include the `Content-Type` header

https://github.com/whyour/qinglong/blob/develop/sample/notify.js 用这个最新的通知文件试试

**Comment by roadinger** [comment]
> > > > webhookHeaders不添加content-type: text/plain 消息发送报错 加了消息会直接发送 $title $content ![03](https://private-user-images.githubusercontent.com/13794003/322682717-35f939be-0507-4a12-a2b8-1ee27d4b1f32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzU0NjQsIm5iZiI6MTcxMzIzNTE2NCwicGF0aCI6Ii8xMzc5NDAwMy8zMjI2ODI3MTctMzVmOTM5YmUtMDUwNy00YTEyLWEyYjgtMWVlMjdkNGIxZjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAyMzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNjQyY2Q5YzViMjg3NTFiMzY0NTg5NDJhMTFiMGFjZjYzNGVkYzI3Njk1YWFjOWFjNmM4MDUyMDY3ODM0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JpgGqVbBJeMd_UO5Od0CS-4y1ks7uOJk790RB_SioH4)
> > > 
> > > 
> > > 不加报什么错
> > 
> > 
> > the client request does not include the `Content-Type` header
> 
> https://github.com/whyour/qinglong/blob/develop/sample/notify.js 用这个最新的通知文件试试

修改script目录的sendNotify.js吗

**Comment by whyour** [comment]
@roadinger 你看你脚本引用的哪个通知文件，就替换哪个

**Comment by roadinger** [comment]
> @roadinger 你看你脚本引用的哪个通知文件，就替换哪个

还是不行   怎么联系你   可以联调下

**Comment by roadinger** [comment]
> @roadinger 你看你脚本引用的哪个通知文件，就替换哪个

formatBodyFun函数是不是也得改下

**Comment by whyour** [comment]
> > @roadinger 你看你脚本引用的哪个通知文件，就替换哪个
> 
> formatBodyFun函数是不是也得改下

https://github.com/whyour/qinglong/blob/develop/sample/notify.js 修改了

**Comment by roadinger** [comment]
> > > @roadinger 你看你脚本引用的哪个通知文件，就替换哪个
> > 
> > 
> > formatBodyFun函数是不是也得改下
> 
> https://github.com/whyour/qinglong/blob/develop/sample/notify.js 修改了

环境变量不能带特殊符号$   
WEBHOOK_BODY 不能带$

**Comment by roadinger** [comment]
export WEBHOOK_BODY="\$title
\$content"
这样可以了

**Comment by roadinger** [comment]
export WEBHOOK_BODY="\\$title
\\$content"
这样可以了

**Comment by whyour** [comment]
@roadinger body 可以用单引号，别用双引号

**Comment by roadinger** [comment]
> @roadinger body 可以用单引号，别用双引号

这样也行，已经解决了
