### ISSUE TITLE
2.17.3版本，手动执行任务不记录日志

### ISSUE THREAD

**Issue by nickzhang1102** [whyour/qinglong#2337]
### Qinglong version

2.17.3

### Steps to reproduce

点击任务的运行，任务在运行中，但不记录日志。自动执行任务会有日志。

### What is expected?

应该要有日志

### What is actually happening?

1

**Comment by klcb2010** [comment]
我还以为是我一个人问题

**Comment by TheHot** [comment]
2.17.4 同样找不到日志

**Comment by klcb2010** [comment]
> 2.17.4 同样找不到日志

同样重启设备
