### ISSUE TITLE
大佬我希望增加一个安全入口的功能，减少被扫描登录入口的风险

### ISSUE THREAD

**Issue by xqtcs** [whyour/qinglong#2338]
### Clear and concise description of the problem

大佬虽然有两步验证，但直接输入端口就能进入登录界面，我认为还是不怎么好。

### Suggested solution

希望你增加一个6位的随机字符在URL中作为登录入口。

### Additional context

感谢大佬提供这么好用的程序。

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
<img width="520" alt="image" src="https://github.com/whyour/qinglong/assets/22700758/484a8d71-80b2-4aa8-badc-588d75e8c435">
部署的时候可以加自定义路径

**Comment by xiaocheng2014** [comment]
修改代理配置加上双向认证呗，我就是这样做的。
