### ISSUE TITLE
看不成脚本和日志

### ISSUE THREAD

**Issue by lkl727** [whyour/qinglong#2343]
### Qinglong version

2.17.3

### Steps to reproduce

点击脚本管理时显示
ELOOP: too many symbolic links encountered, stat '/ql/data/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scripts/scrip

点击日志管理时显示
ELOOP: too many symbolic links encountered, stat '/ql/data/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/log/

看不到脚本和日志

### What is expected?

似乎和设置了 3天删除日志有关。。

### What is actually happening?

就是拉了几个脚本库，设置了删除脚本时间后可能发生的这个问题

**Comment by lkl727** [comment]
https://github.com/whyour/qinglong/issues/2282#issuecomment-2051252313
和这个一样，按照他说的，在scripts文件夹里删掉了有个名为scripts的符号链接文件。
在log文件夹下删掉了名为log的符号链接文件。
就全部都恢复了，都正常可以看了

**Comment by ycr269294986** [comment]
同出现这个问题，现在是不是只要映射/ql/data，一个文件夹就行了

**Comment by klcb2010** [comment]
> 同出现这个问题，现在是不是只要映射/ql/data，一个文件夹就行了

https://github.com/whyour/qinglong/issues/2291   重启设备  2.17.2可以了

**Comment by whyour** [comment]
2.17.4 已修复
