### ISSUE TITLE
上传文件 文件名乱码

### ISSUE THREAD

**Issue by Alone4869** [whyour/qinglong#2344]
### Qinglong version

2.17.3

### Steps to reproduce

脚本管理-点击+号-本地文件-选择本地文件(中文文件名)上传后-确认，界面显示当前文件名的文件是空的，点击保存，会生成一个空的正确文件名的文件，刷新页面后，当前路径回显示一个乱码文件名的内容和上传的文件一致的文件，而同名文件名内容为空

### What is expected?

上传正确显示文件名并且内容正常

### What is actually happening?

上传文件 文件名乱码

**Comment by whyour** [comment]
2.17.4 已修复
