### ISSUE TITLE
node 安装的依赖，脚本无法使用

### ISSUE THREAD

**Issue by guicaiyue** [whyour/qinglong#2345]
### Qinglong version

2.17.3

### Steps to reproduce

1. 先在依赖管理安装了 node-fetch 依赖
2. 在脚本管理，package.json 文件中增加  "type":"module",最终结果如下
```json
{
  "name": "dependence",
  "author": "",
  "license": "ISC",
  "type":"module",
  "dependencies": {
    "got": "^11.5.1",
    "nodemailer": "^6.8.0",
    "tough-cookie": "^4.0.0",
    "tunnel": "0.0.6",
    "ws": "^7.4.3"
  }
}

```
4. 新增test.js文件，拷贝如下内容到文件中

```javascript
import fetch from 'node-fetch'; //使用fetch必须加上该代码
async function sendWeather(){
    const appid = "51396431";
    const appsecret = "LNY47Ewu";
    let url = `https://v0.yiketianqi.com/api?unescape=1&version=v61&appid=${appid}&appsecret=${appsecret}&cityid=encodeURIComponent("成都")`;
    let response = await fetch(url);
    if(response.ok){
        let result = await response.text();
        console.log(result);
    }else{
        console.log("发送天气请求失败");
        return false;
    }
}

async function allTasks(){
    await sendWeather();
}

allTasks();
```
5. 调试运行，报错如下
```txt
## 开始执行... 2024-04-23 12:06:21

node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-fetch' imported from /ql/data/scripts/atest1.swap.js
Did you mean to import node-fetch@3.3.2/node_modules/node-fetch/src/index.js?
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.16.1

## 执行结束...   耗时 1 秒
```
### What is expected?

希望知道怎么做，以及原因，为什么依赖装好了，但无法脚本内依旧无法找到
是因为依赖管理安装的是全局包吗？
package.json 文件的意义是局部包吗？
要进 package.json 所在目录执行install 安装局部包吗？

### What is actually happening?

依赖没有找到

### System Info

```shell
docker 部署
```

### Any additional comments?

如果和正常项目脚本开发有差异，不管是nodejs还是python，都希望能有差一点文档，不然门槛太高了

**Comment by whyour** [comment]
后缀改成 ts

**Comment by guicaiyue** [comment]
> 后缀改成 ts

还是失败了
<img width="894" alt="1714189716049" src="https://github.com/whyour/qinglong/assets/43875377/86377a5a-1466-4047-a42c-d24f56d985a3">

**Comment by whyour** [comment]
不需要改 package.json

**Comment by guicaiyue** [comment]
好我再试试

**Comment by guicaiyue** [comment]
> @guicaiyue 你这不是最新镜像吧，node 版本不对

我用的是docker部署，然后通过面板更新

**Comment by whyour** [comment]
@guicaiyue 有备份目录的情况下，可以使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新试试

**Comment by guicaiyue** [comment]
> ```js
> node-fetch
> ```

好的，我已经重新更新了一个新的版本，node版本为v20.12.1
node-fetch 模块脚本已经能正常运行使用了
步骤：
1、一个最新的青龙面板，初始化登录
2、依赖安装node-fetch模块
3、脚本管理新建一个atest.ts文件
4、将内容拷贝进去，点击调试，可以执行获取结果，未出现包依赖问题

但我现在遇到了另一个问题
我通过依赖管理安装 x-crawl 模块
新增 btest.ts 文件使用如下代码
```
import { createCrawl } from 'x-crawl'

const crawlApp = createCrawl({ intervalTime: { max: 3000, min: 1000 } })

crawlApp
  .crawlHTML([
    'https://www.example.com/html-1',
    'https://www.example.com/html-2'
  ])
  .then((res) => {
    // 处理
    console.log(res);
  })
```
调试报错如下，说我使用了CJS模块导入，但我用的是 import ，还是因为这个依赖还引用了其他依赖的原因
<img width="905" alt="1714191961249" src="https://github.com/whyour/qinglong/assets/43875377/5f8b82f0-65ad-4551-a52d-c54239305bb2">

**Comment by guicaiyue** [comment]
测试发现，当我在脚本管理根目录下新增一份 package.json 文件内容如下
```
{
  "name": "dependence",
  "version": "1.0.0",
  "author": "",
  "type": "module",
  "license": "ISC"
}
```
我的 btest.ts 文件就能执行成功，但同时原来执行 ok 的 atest.ts 文件执行失败，提示无法找到依赖模块报错内容如下
<img width="914" alt="1714194324475" src="https://github.com/whyour/qinglong/assets/43875377/063a95a1-8890-48e3-842f-6d3f06a26444">

测试发现重点是 "type": "module" 配置，意思是启用 ESModule ，否则默认 CommonJS 
当我将 "type": "module" 从 package.json 文件内容移除时，这时 atest.ts 能执行成功，btest.ts 不能执行成功，加上两者就反过来了。

**Comment by guicaiyue** [comment]
解决了，一个 node 模块的导出方式决定它是CommonJS 还是 ESModule 。所以不是通过导入方式判断的，所以目录调整如下
<img width="907" alt="1714195346493" src="https://github.com/whyour/qinglong/assets/43875377/388a52d7-a500-44bd-92bb-bc1fca99adcc">
外部 package.json 文件内容不带"type": "module"，使用 CommonJS 模式加载，所以 atest.ts 能调试执行
```
{
  "name": "dependence",
  "version": "1.0.0",
  "author": "",
  "license": "ISC"
}
```
在 esm 文件目录下也新增 package.json 文件内容如下
```
{
    "type": "module"
}
```
所以 node 使用 ESModule 模式加载 btest.ts 文件也能执行

暂未发现其他问题，此帖完结

**Comment by tasty007** [comment]
> 解决了，一个 node 模块的导出方式决定它是CommonJS 还是 ESModule 。所以不是通过导入方式判断的，所以目录调整如下 <img alt="1714195346493" width="907" src="https://private-user-images.githubusercontent.com/43875377/326155870-388a52d7-a500-44bd-92bb-bc1fca99adcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODA1NzgsIm5iZiI6MTcxNDM4MDI3OCwicGF0aCI6Ii80Mzg3NTM3Ny8zMjYxNTU4NzAtMzg4YTUyZDctYTUwMC00NGJkLTkyYmItYmMxZmNhOTlhZGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA4NDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MGNlZjU0NTc2NzVjYzE4MTY4OTJkMjI5ZTgzMjEwODJlYmQ2NmY1N2ZhZTQ4YjFlZjAxNzYzMTBlNGU5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xTqsMPS2hNGZPxKoLawKsAAPZewsBKcgLoifc0DDVew"> 外部 package.json 文件内容不带"type": "module"，使用 CommonJS 模式加载，所以 atest.ts 能调试执行
> 
> ```
> {
>   "name": "dependence",
>   "version": "1.0.0",
>   "author": "",
>   "license": "ISC"
> }
> ```
> 
> 在 esm 文件目录下也新增 package.json 文件内容如下
> 
> ```
> {
>     "type": "module"
> }
> ```
> 
> 所以 node 使用 ESModule 模式加载 btest.ts 文件也能执行
> 
> 暂未发现其他问题，此帖完结

老哥, 你能在python中加载 canvas依赖吗?

**Comment by guicaiyue** [comment]
> > 解决了，一个 node 模块的导出方式决定它是CommonJS 还是 ESModule 。所以不是通过导入方式判断的，所以目录调整如下 <img alt="1714195346493" width="907" src="https://private-user-images.githubusercontent.com/43875377/326155870-388a52d7-a500-44bd-92bb-bc1fca99adcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODA1NzgsIm5iZiI6MTcxNDM4MDI3OCwicGF0aCI6Ii80Mzg3NTM3Ny8zMjYxNTU4NzAtMzg4YTUyZDctYTUwMC00NGJkLTkyYmItYmMxZmNhOTlhZGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA4NDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MGNlZjU0NTc2NzVjYzE4MTY4OTJkMjI5ZTgzMjEwODJlYmQ2NmY1N2ZhZTQ4YjFlZjAxNzYzMTBlNGU5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xTqsMPS2hNGZPxKoLawKsAAPZewsBKcgLoifc0DDVew"> 外部 package.json 文件内容不带"type": "module"，使用 CommonJS 模式加载，所以 atest.ts 能调试执行
> > ```
> > {
> >   "name": "dependence",
> >   "version": "1.0.0",
> >   "author": "",
> >   "license": "ISC"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在 esm 文件目录下也新增 package.json 文件内容如下
> > ```
> > {
> >     "type": "module"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 所以 node 使用 ESModule 模式加载 btest.ts 文件也能执行
> > 暂未发现其他问题，此帖完结
> 
> 老哥, 你能在python中加载 canvas依赖吗?

还没用过，遇到什么问题了嘛？有例子嘛

**Comment by tasty007** [comment]
> > > 解决了，一个 node 模块的导出方式决定它是CommonJS 还是 ESModule 。所以不是通过导入方式判断的，所以目录调整如下 <img alt="1714195346493" width="907" src="https://private-user-images.githubusercontent.com/43875377/326155870-388a52d7-a500-44bd-92bb-bc1fca99adcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODA1NzgsIm5iZiI6MTcxNDM4MDI3OCwicGF0aCI6Ii80Mzg3NTM3Ny8zMjYxNTU4NzAtMzg4YTUyZDctYTUwMC00NGJkLTkyYmItYmMxZmNhOTlhZGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA4NDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MGNlZjU0NTc2NzVjYzE4MTY4OTJkMjI5ZTgzMjEwODJlYmQ2NmY1N2ZhZTQ4YjFlZjAxNzYzMTBlNGU5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xTqsMPS2hNGZPxKoLawKsAAPZewsBKcgLoifc0DDVew"> 外部 package.json 文件内容不带"type": "module"，使用 CommonJS 模式加载，所以 atest.ts 能调试执行
> > > ```
> > > {
> > >   "name": "dependence",
> > >   "version": "1.0.0",
> > >   "author": "",
> > >   "license": "ISC"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 在 esm 文件目录下也新增 package.json 文件内容如下
> > > ```
> > > {
> > >     "type": "module"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 所以 node 使用 ESModule 模式加载 btest.ts 文件也能执行
> > > 暂未发现其他问题，此帖完结
> > 
> > 
> > 老哥, 你能在python中加载 canvas依赖吗?
> 
> 还没用过，遇到什么问题了嘛？有例子嘛

大佬您试试在面板装依赖的python3页面装这个canvas依赖,试试能否成功,
不知道canvas这个依赖的历史版本哪里找.

**Comment by citrusjunoss** [comment]
一样的问题 esm 类型好像有点儿问题。换成 ts，无法解析。用 js 还是加载不到模块
```

## 开始执行... 2025-03-29 14:03:46

TypeError: Unknown file extension ".ts" for /ql/data/scripts/node/esm/weather.swap.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:219:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:245:36)
    at defaultLoad (node:internal/modules/esm/load:120:22)
    at async ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:483:32)
    at async ModuleJob._link (node:internal/modules/esm/module_job:115:19) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

## 执行结束... 2025-03-29 14:03:47  耗时 1 秒　
```

**Comment by citrusjunoss** [comment]
js 模式下

```
## 开始执行... 2025-03-29 14:05:11

node:internal/modules/run_main:122
    triggerUncaughtException(
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'jose' imported from /ql/data/scripts/node/esm/weather.swap.js
Did you mean to import "jose/dist/webapi/index.js"?
    at packageResolve (node:internal/modules/esm/resolve:857:9)
    at moduleResolve (node:internal/modules/esm/resolve:926:18)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:135:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v22.13.1

## 执行结束... 2025-03-29 14:05:11  耗时 1 秒　　　　　
```

依赖是全局安装的
```
 
## 开始执行... 2025-03-29 14:06:18

/usr/local/lib
└── jose@6.0.10


## 执行结束... 2025-03-29 14:06:18  耗时 1 秒　　
```

难道说都要改成本地目录安装么。

**Comment by citrusjunoss** [comment]
import { SignJWT } from '/usr/local/lib/node_modules/jose/dist/webapi/index.js'; 
改为相对路径之后没问题了。看来还只本地目录安装方便一些

**Comment by whyour** [comment]
@citrusjunoss 是没在依赖管理安装？

**Comment by citrusjunoss** [comment]
> [@citrusjunoss](https://github.com/citrusjunoss) 是没在依赖管理安装？

安装了，但是加载不到。导入路径需要写绝对路径。

**Comment by citrusjunoss** [comment]
找不到这个包
![Image](https://github.com/user-attachments/assets/74bdd324-1fa3-4f03-a643-666b0b1e0cb6)
但是实际上是有安装依赖的

![Image](https://github.com/user-attachments/assets/73a5da93-21d3-48b0-8ca0-f26ee095be9f)

@whyour

**Comment by citrusjunoss** [comment]
![Image](https://github.com/user-attachments/assets/35fbab5a-7091-4397-a68f-7cf16ba608d6)
安装目录在这里

**Comment by whyour** [comment]
> ![Image](https://github.com/user-attachments/assets/35fbab5a-7091-4397-a68f-7cf16ba608d6)
> 安装目录在这里

esm 脚本加载依赖有问题，下个版本修复
