### ISSUE TITLE
对比工具左侧的sample文件无法读取。

### ISSUE THREAD

**Issue by EiennoXc** [whyour/qinglong#2346]
### Qinglong version

正式版 v2.17.3

### Steps to reproduce

使用官方说明里docker run的方式拉取的最新版镜像，并没有做特殊设置。在/ql/data/目录下手动建立sample目录，再手动建立config.sample.sh文件，对比工具中依然无法读取到。

### What is expected?

我想知道最新版中对比工具中文件的源地址。（因为配置文件需要经常做更新对比）

### What is actually happening?

![FireShot Webpage Capture 038 - '对比工具 - 青龙' - 192 168 50 164](https://github.com/whyour/qinglong/assets/93081744/3da35fc3-be73-416d-9d4d-9f0fb1c395af)

**Comment by whyour** [comment]
目前不支持自定义对比
