### ISSUE TITLE
 正式版 v2.17.3 telegram通知没了，不能设置

### ISSUE THREAD

**Issue by zhangheng2022** [whyour/qinglong#2347]
### Qinglong version

v2.17.3

### Steps to reproduce

通知设置报错

### What is expected?

通知设置报错

### What is actually happening?

通知设置报错

**Comment by MononeV** [comment]
v2.17.4 同
![image](https://github.com/whyour/qinglong/assets/39477101/fc81cb99-94ef-4f2d-acd9-f93d89c3a616)

**Comment by whyour** [comment]
https://github.com/whyour/qinglong/issues/2354#issuecomment-2094653401
