### ISSUE TITLE
2.17.4 window docker 自动更新更新失败 无法更新

### ISSUE THREAD

**Issue by wzgrx** [whyour/qinglong#2348]
### Qinglong version

2.17.3

### Steps to reproduce

在检查更新点击更新 更新重启后还是2.17.3版本

安装 /ql/.tmp/qinglong-master 依赖包...

Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm

dependencies:
+ @grpc/grpc-js 1.8.15
+ @otplib/preset-default 12.0.1
+ @sentry/node 7.54.0
+ body-parser 1.20.2
+ celebrate 15.0.1
+ chokidar 3.5.3
+ cors 2.8.5
+ cron-parser 4.8.1
+ cross-spawn 7.0.3
+ dayjs 1.11.8
+ dotenv 16.1.4
+ express 4.18.2
+ express-jwt 6.1.2
+ express-rate-limit 7.0.0
+ express-urlrewrite 1.4.0
+ form-data 4.0.0
+ got 11.8.6
+ hpagent 1.2.0
+ http-proxy-middleware 2.0.6
+ iconv-lite 0.6.3
+ ip2region 2.3.0
+ js-yaml 4.1.0
+ jsonwebtoken 8.5.1
+ lodash 4.17.21
+ multer 1.4.5-lts.1
+ nedb 1.8.0
+ node-schedule 2.1.1
+ nodemailer 6.9.3
+ p-queue-cjs 7.3.4
+ protobufjs 7.2.3
+ pstree.remy 1.1.8
+ reflect-metadata 0.1.13
+ request-ip 3.3.0
+ sequelize 6.32.0
+ serve-handler 6.1.5
+ sockjs 0.3.24
+ sqlite3 <- @whyour/sqlite3 1.0.3
+ toad-scheduler 1.6.1
+ tough-cookie 4.0.0
+ typedi 0.10.0
+ uuid 8.3.2
+ winston 3.9.0
+ winston-daily-rotate-file 4.7.1
+ yargs 17.7.2

devDependencies: skipped

> @ postinstall /ql/.tmp/qinglong-master
> max setup 2>/dev/null || true

Done in 6.1s

依赖检测安装成功...

更新包下载成功...

### What is expected?

正常升级

### What is actually happening?

正常更新

### System Info

```shell
window11 edge124
```

**Comment by pzqpeter** [comment]
我也是遇到了同样的问题
