### ISSUE TITLE
视图只能展示三个吗？

### ISSUE THREAD

**Issue by funyhook** [whyour/qinglong#2351]
### Clear and concise description of the problem

视图只能展示三个吗？

### Suggested solution

视图只能展示三个吗？

### Alternative

视图只能展示三个吗？

### Additional context

视图只能展示三个吗？

### Validations

- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by funyhook** [comment]
建议视图增加一个自定义展示个数

**Comment by aqiu9** [comment]
支持！！！

**Comment by whyour** [comment]
视图管理里可以控制是否显示

**Comment by aqiu9** [comment]
大佬您好，楼主的意思应该是视图超过3个就会被折叠，我个人也觉得在PC端  这个3太小了。😉

**Comment by funyhook** [comment]
我的意思是现在默认只展示四个tab页签，第五个，第六个只能在更多这个页签中展示，能不能设置一个tab页签数量变量，自定义展示页签数量

发自我的iPhone

**Comment by charmer21** [comment]
支持支持，比如可以再配置中根据自己需要，设置默认显示的页签个数，这样对于pc端大屏幕来讲，看起来就方便很多了（定时任务页签功能确实非常非常nice）

**Comment by iAmP1us** [comment]
复议
