### ISSUE TITLE
新安装的青龙，过一会设置选项里面无论设置哪个选项都会出现WHERE parameter "type" has invalid "undefined" value

### ISSUE THREAD

**Issue by qwe77889** [whyour/qinglong#2352]
### Qinglong version

2.17.2和2.17.4

### Steps to reproduce

新安装的青龙，过一会设置选项里面无论设置哪个选项都会出现WHERE parameter "type" has invalid "undefined" value

### What is expected?

选项设置正常可以

### What is actually happening?

新安装的青龙，过一会设置选项里面无论设置哪个选项都会出现WHERE parameter "type" has invalid "undefined" value

**Comment by qwe77889** [comment]
顶起来

**Comment by whyour** [comment]
完全新装也有问题？http://demo.ninesix.cc:4433/setting demo环境试试，我这没法复现

**Comment by qwe77889** [comment]
全新安装几次了都是刚开始好好的，几分钟后设置就不行了

**Comment by qwe77889** [comment]
demo环境下，好像没问题，等下我再试试看

**Comment by qwe77889** [comment]
重新安装试了下，系统设置里面的依赖设置和其它设置里面的日志频率 定时并发不能更改，其它的都可以更改，只要更改就会出现那个提示，不知道问题出现在哪里

**Comment by XiaoChenMr** [comment]
最新版2.17.5路过，也是这问题
![image](https://github.com/whyour/qinglong/assets/77822042/4e4ef70f-05c6-46c6-92e7-702d8a90061d)

**Comment by whyour** [comment]
2.17.6 已修复
