### ISSUE TITLE
飞书机器人配置无法写入环境变量

### ISSUE THREAD

**Issue by cyk2018** [whyour/qinglong#2356]
### Qinglong version

2.17.4

### Steps to reproduce

1. 在通知设置中选择通知方式“飞书机器人”
2. 输入larkKey
3. 点击保存会发送一条测试消息，但是没有名为FSKEY的环境变量
4. 运行支持发送通知的任务会发现无法发送成功

### What is expected?

1. 此功能检测是否存在FSKEY变量
2. 如果存在，则更新，不存在则插入

### What is actually happening?

功能不正常，只会发送一条测试信息

### Any additional comments?

感谢作者大大的付出！如需支持也可在此issue评论我来提PR。

**Comment by whyour** [comment]
系统内的通知和脚本通知不通用，需要手动在配置文件里加入 `export FSKEY="xxxx"`
