### ISSUE TITLE
查看定时任务的脚本内容出错

### ISSUE THREAD

**Issue by sulele89757** [whyour/qinglong#2362]
### Qinglong version

2.17.4

### Steps to reproduce

前提：有一些定时任务是没有脚本内容的。
![image](https://github.com/whyour/qinglong/assets/11418032/6a1f3a65-9a86-4bce-a3b5-558b82234b9b)
重现步骤：
1. 打开其他任意有脚本内容的定时任务，查看脚本
![image](https://github.com/whyour/qinglong/assets/11418032/30887368-c274-43d3-a9ef-42a3650635c4)
2. 此时再次打开`前提`中提到的没有脚本内容的定时任务，查看脚本，会发现里面展示了步骤`1`中查看过的脚本内容
![image](https://github.com/whyour/qinglong/assets/11418032/683ef85e-b1b7-4e15-bd26-e9363a734897)

### What is expected?

应该需要在查看脚本内容前，清空之前已加载的脚本。

### What is actually happening?

加载脚本内容错误

### System Info

```shell
System:
    OS: Linux 4.4 Alpine Linux
    CPU: (4) x64 Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz
    Memory: 2.31 GB / 3.75 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.19.1 - /usr/bin/node
    npm: 9.6.6 - /usr/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
```

**Comment by whyour** [comment]
2.17.5 已修复
