### ISSUE TITLE
脚本管理中的调试功能无法输出执行信息

### ISSUE THREAD

**Issue by ywmm3951** [whyour/qinglong#2365]
### Qinglong version

正式版 v2.17.4

### Steps to reproduce

对脚本进行调试测试右边输出面板无任何记录，如下图。
![qinglong](https://github.com/whyour/qinglong/assets/7733631/0d402c73-e834-4138-836f-fc4da63485ab)

### What is expected?

同上

### What is actually happening?

同上

**Comment by whyour** [comment]
刷新下？或者重启下服务

**Comment by ywmm3951** [comment]
> 刷新下？或者重启下服务

都试过了，不行。同时测试v2.10.13版本就正常，执行完会自动停止。
![110](https://github.com/whyour/qinglong/assets/7733631/07244788-824e-4593-bfc8-83cf7d6a91b3)

**Comment by whyour** [comment]
http://demo.ninesix.cc:4433/script demo 环境是没问题的，你这个看下服务都启动正常了吗，浏览器控制台有报错没

**Comment by ywmm3951** [comment]
我又测试了下，发现是间歇性的bug，我用你的demo环境测试时好时坏，下图是坏的情况。
![111](https://github.com/whyour/qinglong/assets/7733631/47d77583-9ce0-4c54-a8db-aff9b81b121f)
不手动点击停止不会停下来，也没有任何输出信息。

**Comment by whyour** [comment]
@ywmm3951 用 chrome 浏览器呢

**Comment by ywmm3951** [comment]
> @ywmm3951 用 chrome 浏览器呢

我用的edge浏览器，和chrome内核一样的，后来又试了safari浏览器，一样的问题，我的版本偶尔能成功，大多数时间不行，你的demo大多数时间没问题，但是偶尔还是会卡住不输出任何信息。但是，定时任务是正常运行的，先不管这个脚本测试功能了。

**Comment by ywmm3951** [comment]
> @ywmm3951 用 chrome 浏览器呢

破案了，http地址没问题，我做了反代，配置了证书，所以https地址下脚本调试无法正常运行。麻烦这个bug如何修复一下，谢谢！

**Comment by whyour** [comment]
最新版还有问题吗

**Comment by ywmm3951** [comment]
> 最新版还有问题吗
还是一样的问题，http访问测试正常，https访问测试不正常，版本：v2.17.5

**Comment by whyour** [comment]
你是不是没转发 websocket 请求

**Comment by ywmm3951** [comment]
> 你是不是没转发 websocket 请求

谢谢！已解决，我在群晖设置反向代理里面额外添加了websocket 支持就好了，这个一般人还真不知道需要额外这样设置。
