### ISSUE TITLE
定时任务模块“日志”功能失效

### ISSUE THREAD

**Issue by DINGYUYU1** [whyour/qinglong#2369]
### Qinglong version

正式版 v2.17.4

### Steps to reproduce

我几天前发现日志没有更新，我怀疑是日志满了，清空后在运行也没有日志。
代码是正常的，调试是有输出的
点击运行后，日志依旧显示“任务未运行”
![Uploading QQ截图20240516121518.jpg…]()

### What is expected?

能正常显示日志

### What is actually happening?

日志功能失效

**Comment by a5412398** [comment]
一样

**Comment by DINGYUYU1** [comment]
我没有进行任何操作，刚才我登录发现有日志了，日志的开始时间为2024-05-17 16:40，好奇怪

**Comment by whyour** [comment]
2.17.5 已修复
