### ISSUE TITLE
更新后 lxk 仓库的部分脚本拉取失败

### ISSUE THREAD

**Issue by wyap-echo** [whyour/qinglong#237]
--------------------------------------------------------------

开始更新仓库：/ql/repo/chinnkarahoi_jd_scripts

Fetching origin
HEAD is now at 50ce2d9b crontab_list.sh
Already up to date.

更新/ql/repo/chinnkarahoi_jd_scripts成功...

检测到有新的定时任务：

chinnkarahoi_jd_scripts_jd_jdzz.js
chinnkarahoi_jd_scripts_jd_fruit.js
chinnkarahoi_jd_scripts_jd_jump.js
chinnkarahoi_jd_scripts_jd_crazy_joy_coin.js
chinnkarahoi_jd_scripts_jd_live.js
chinnkarahoi_jd_scripts_jd_car.js
chinnkarahoi_jd_scripts_jd_bean_change.js
chinnkarahoi_jd_scripts_jd_xtg_help.js
chinnkarahoi_jd_scripts_jd_syj.js
chinnkarahoi_jd_scripts_jd_plantBean.js
chinnkarahoi_jd_scripts_jd_superMarket.js
chinnkarahoi_jd_scripts_jd_live_redrain.js
chinnkarahoi_jd_scripts_jd_xtg.js
chinnkarahoi_jd_scripts_jd_car_exchange.js

开始尝试自动添加定时任务...

task chinnkarahoi_jd_scripts_jd_jdzz.js -> 添加失败(Validation error, cannot resolve alias "url")
东东农场 -> 添加失败(Invalid cron expression)
跳跳乐瓜分京豆 -> 添加失败(Invalid cron expression)
task chinnkarahoi_jd_scripts_jd_crazy_joy_coin.js -> 添加失败(Validation error, cannot resolve alias "joy")
京东直播 -> 添加失败(Invalid cron expression)
task chinnkarahoi_jd_scripts_jd_car.js -> 添加失败(Validation error, cannot resolve alias "url")
京东资产变动通知 -> 添加失败(Invalid cron expression)
家电星推官好友互助 -> 添加失败(Invalid cron expression)
task chinnkarahoi_jd_scripts_jd_syj.js -> 添加失败(Validation error, cannot resolve alias "url")
京东种豆得豆 -> 添加失败(Invalid cron expression)
东东超市 -> 添加失败(Invalid cron expression)
超级直播间红包雨 -> 添加失败(Invalid cron expression)
家电星推官 -> 添加失败(Invalid cron expression)
task chinnkarahoi_jd_scripts_jd_car_exchange.js -> 添加失败(Validation error, cannot resolve alias "url")

是因为脚本内cron 表达式无法读取的问题吗？

**Comment by borpubi** [comment]
+1,同样是在添加任务时报错。

**Comment by BlueSkyClouds** [comment]
一样

**Comment by whyour** [comment]
最新版已修复
