### ISSUE TITLE
服务器资源异常警告 

### ISSUE THREAD

**Issue by uwhatsup** [whyour/qinglong#2374]
### Qinglong version

2.17.4

### Steps to reproduce

任务执行完不发送执行通知日志，只发送 服务器资源异常警告 ,  当前CPU占用 % 内存占用 % 磁盘占用 32% 资源占用详情 ，应该如何关闭？
在配置文件里尝试过修改以下，还是会发送相同的警告

## 资源告警阙值，默认CPU 80%、内存80%、磁盘90%
CpuWarn="100"
MemoryWarn="100"
DiskWarn="100"

## 资源告警阙值，默认CPU 80%、内存80%、磁盘90%
CpuWarn=0
MemoryWarn=0
DiskWarn=0

 

### System Info

```shell
ubuntu 18.04
```

**Comment by whyour** [comment]
最新版已经没有这个功能了，你这哪来的报警
