### ISSUE TITLE
玩客云青龙升级后，无法在线调试

### ISSUE THREAD

**Issue by mayishidai** [whyour/qinglong#2382]
### Qinglong version

 正式版 v2.17.5

### Steps to reproduce

![image](https://github.com/whyour/qinglong/assets/20534392/c3a35846-033f-4bf6-90c9-afb434f33a2d)
![image](https://github.com/whyour/qinglong/assets/20534392/f921f16e-0e7c-4799-a697-e19c39739642)
![image](https://github.com/whyour/qinglong/assets/20534392/74a78407-832d-4cf1-b673-0ae08eefa85e)
![image](https://github.com/whyour/qinglong/assets/20534392/282327e8-c588-4138-a545-3ba5f3afb55a)

脚本管理-》python脚本-》调试-》报错
重启过了，依然无法调试

### What is expected?

能正常调试

### What is actually happening?

写在重现步骤了~~

**Comment by mayishidai** [comment]
![image](https://github.com/whyour/qinglong/assets/20534392/e5c8056d-5b86-43fa-93ef-64b1e29cf1ee)

**Comment by whyour** [comment]
看你 `/ql/shell` 目录下是没有 task.sh 文件了？

**Comment by whyour** [comment]
看你容器里还有 ql 命令吗

**Comment by mayishidai** [comment]
从最新版本的倒数第3个版本升级上来的，casaos面板也无法启动了
![image](https://github.com/whyour/qinglong/assets/20534392/94b448d9-b6b4-4252-bb92-721202553dc0)
![image](https://github.com/whyour/qinglong/assets/20534392/05b8a4aa-ab21-409e-837d-1306690e75e1)

**Comment by mayishidai** [comment]
![image](https://github.com/whyour/qinglong/assets/20534392/70871a92-f9a1-43ff-922a-1e7dc80a05c7)

**Comment by mayishidai** [comment]
![image](https://github.com/whyour/qinglong/assets/20534392/a94e817b-e178-4ea5-be4c-be8e34212c7f)

**Comment by whyour** [comment]
> ![image](https://private-user-images.githubusercontent.com/20534392/334774434-a94e817b-e178-4ea5-be4c-be8e34212c7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODEyMzIsIm5iZiI6MTcxNjk4MDkzMiwicGF0aCI6Ii8yMDUzNDM5Mi8zMzQ3NzQ0MzQtYTk0ZTgxN2ItZTE3OC00ZWE1LWJlNGMtYmU4ZTM0MjEyYzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMDg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZmI4OGZmZTZlZDUxNjBmMGU5ODE1MzE0OWMwNjVmNmE2Mjg3Mzc0ZDVkZDI2OTVmZWZhZDI1NTU0NDY0NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wmpuf3mOD-Pt_F6GKEMDGzgBjzgo2waVdIM7034kNeM)

你这容器不是启动失败了吗，`/usr/local/bin` 容器内的这个目录，你是在面板内升级的？

**Comment by whyour** [comment]
倒数第三个版本 是 `2.17.2` ?

**Comment by mayishidai** [comment]
是的

**Comment by mayishidai** [comment]
[2024-05-29.log](https://github.com/whyour/qinglong/files/15483376/2024-05-29.log)
这个是更新后日志

**Comment by mayishidai** [comment]
我说下我的详细步骤：

**Comment by mayishidai** [comment]
1、我是在青龙网页更新的

**Comment by mayishidai** [comment]
下面是我的详细操作步骤：
1、我是下午调试python脚本发现不是很顺畅
2、我就去看了下最近更新，看到有关于任务启动相关的，我就点了升级（有点印象我当前好像是2.17.2）
3、升级完成后，我在面板点的重新启动
4、发现不能调试了，我又在面板重启了一次
5、然后发现还是不行，我就来git求助了
6、这时候的容器还是在运行的
6、刚看到您让我看ql容器，我想着重启碰碰运气，就重启了容器
7、就再也起不来了

**Comment by whyour** [comment]
> 下面是我的详细操作步骤： 1、我是下午调试python脚本发现不是很顺畅 2、我就去看了下最近更新，看到有关于任务启动相关的，我就点了升级（有点印象我当前好像是2.17.2） 3、升级完成后，我在面板点的重新启动 4、发现不能调试了，我又在面板重启了一次 5、然后发现还是不行，我就来git求助了 6、这时候的容器还是在运行的 6、刚看到您让我看ql容器，我想着重启碰碰运气，就重启了容器 7、就再也起不来了

有备份 data 目录的话，先更新下镜像，然后容器删了重新创建

**Comment by mayishidai** [comment]
好的，我在更新前点了备份，本来以防万一的，没想到真用上了

**Comment by mayishidai** [comment]
我是在青龙面板点的备份

**Comment by whyour** [comment]
> 我是在青龙面板点的备份

或者你可以先看看容器重启报什么错，新建容器的时候应该也能设置映射的目录

**Comment by mayishidai** [comment]
看起来是丢了些东西 
![image](https://github.com/whyour/qinglong/assets/20534392/21949860-5ccc-4a8d-852a-78f1800685d3)

**Comment by mayishidai** [comment]
![image](https://github.com/whyour/qinglong/assets/20534392/5df24093-2c5d-4772-83c6-a239da76fa9a)

**Comment by whyour** [comment]
里面文件好像都没了，容器没用了

**Comment by mayishidai** [comment]
是的，看起来只能重新建容器了，您还需要什么信息么，没有的话，我准备重建了

**Comment by mayishidai** [comment]
我现在的镜像应该是最新的，用的latest版本

**Comment by mayishidai** [comment]
我创一个试试看，我还在想要不要回退到table版本去

**Comment by whyour** [comment]
> latest

latest 就是 stable 版本

**Comment by mayishidai** [comment]
我现在用的上面这个
![image](https://github.com/whyour/qinglong/assets/20534392/dcdc2c58-426b-49eb-b865-ffbc1983a419)
这两个是一样的么。。

**Comment by whyour** [comment]
> 我现在用的上面这个 ![image](https://private-user-images.githubusercontent.com/20534392/334786524-dcdc2c58-426b-49eb-b865-ffbc1983a419.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODM4NTMsIm5iZiI6MTcxNjk4MzU1MywicGF0aCI6Ii8yMDUzNDM5Mi8zMzQ3ODY1MjQtZGNkYzJjNTgtNDI2Yi00OWViLWI4NjUtZmZiYzE5ODNhNDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExNTIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYTNjNGI4MTBjODBlODllMjI1OTczNzU0OTkzZDE5NWE0N2RjZTBlZjkxYjgyMDVkMmI4OWM3MTEyMDJmMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XTJU9S7O8qIKKyRJ_EaMAKJfwW1-aY75Ew1S_cVl8ak) 这两个是一样的么。。

看上去没区别

**Comment by mayishidai** [comment]
好的  ~~~

**Comment by mayishidai** [comment]
重建后可以用了

**Comment by mayishidai** [comment]
借楼请教一个，请问现在青龙不能通过casaos面板，增加容器卷么，我增加后，发现并没有生效
![image](https://github.com/whyour/qinglong/assets/20534392/0a4ab6d7-9bb1-4ac3-9075-97262b653f56)
![image](https://github.com/whyour/qinglong/assets/20534392/309ecd22-70d6-48c0-89e6-3c43d4661650)

**Comment by whyour** [comment]
> 借楼请教一个，请问现在青龙不能通过casaos面板，增加容器卷么，我增加后，发现并没有生效
> 
> ![image](https://github.com/whyour/qinglong/assets/20534392/0a4ab6d7-9bb1-4ac3-9075-97262b653f56)
> 
> ![image](https://github.com/whyour/qinglong/assets/20534392/309ecd22-70d6-48c0-89e6-3c43d4661650)
> 
> 

得重新创建容器
