### ISSUE TITLE
Bark 通知失败

### ISSUE THREAD

**Issue by Rebuilding127** [whyour/qinglong#2385]
### Qinglong version

2.17.5

### Steps to reproduce

```
Bark APP发送通知调用API失败！！

HTTPError: Response code 431 (Request Header Fields Too Large)
    at Request.<anonymous> (/ql/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1717132293308,
    socket: 1717132293308,
    lookup: 1717132293674,
    connect: 1717132293721,
    secureConnect: 1717132293815,
    upload: 1717132293815,
    response: 1717132293861,
    end: 1717132293862,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 366,
      tcp: 47,
      tls: 94,
      request: 0,
      firstByte: 46,
      download: 1,
      total: 554
    }
  }
}
```

### What is expected?

Bark 推送成功

### What is actually happening?

Bark 推送失败

**Comment by whyour** [comment]
@Rebuilding127 使用最新通知文件试试

**Comment by Rebuilding127** [comment]
> @Rebuilding127 使用最新通知文件试试

不知怎么用，可有说明？

**Comment by Rebuilding127** [comment]
> @Rebuilding127 使用最新通知文件试试

修改 `sendNotify.js` 文件？或者是 `notify.py` ？

**Comment by whyour** [comment]
@Rebuilding127 用 sample 的通知文件替换 js 通知文件

**Comment by Rebuilding127** [comment]
> @Rebuilding127 用 sample 的通知文件替换 js 通知文件

还是不行哦。我看源码中对Bark的通知调用方式是Get请求，将内容部分也拼接在url后面，是否是这种做法导致请求内容太大。可否换成post请求呢？

Ps：Bark是支持post请求的。

**Comment by whyour** [comment]
@Rebuilding127 日志提示什么

**Comment by Rebuilding127** [comment]
还是一样的 431 错误，以下是资产统计的运行日志（删除了账号名）

```log
## 开始执行... 2024-05-31 14:49:12


🔔京东资产统计, 开始!

====================共4个京东账号Cookie=================
===========脚本执行时间：2024/05/31 14:49:12============
>>>>>>>>>>>>6Dy提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>

检测到资产变动缓存文件2024-05-30.json，载入...
检测到资产变动缓存文件2024-05-31.json，载入...
******开始查询【京东账号1】*********
【账号1🆔】(已实名)
【账号信息】Plus会员(101分)
【京豆变动】827豆(与昨日21:28比较)
【当前京豆】827豆(≈8.27元)
【特价金币】10币(≈0.00元)
【老农场】散养鸡蛋15枚(19%)
【新农场】种植进度4/5(63.26%)
【话费积分】25.07(近7日将过期4.05)
【超市卡】2.34元(0.28元赠金25天后到期)
🧧🧧🧧红包明细🧧🧧🧧
【红包总额】3.24(总过期0.79)元 
【京喜特价】0.23(将过期0.18)元 
【京东红包】0.05(将过期0.05)元 
【微信小程序】0.56(将过期0.56)元 
【全平台通用】2.40元 

******开始查询【京东账号2】*********
【账号2🆔】(已实名)
【账号信息】Plus会员(101分)
【京豆变动】342豆(与昨日21:29比较)
【当前京豆】342豆(≈3.42元)
【特价金币】10币(≈0.00元)
【老农场】洛川苹果6枚装(71%)
【新农场】种植进度4/5(60.15%)
【话费积分】25.47(近7日将过期4.05)
🧧🧧🧧红包明细🧧🧧🧧
【红包总额】1.75(总过期0.74)元 
【京喜特价】0.21(将过期0.18)元 
【微信小程序】0.56(将过期0.56)元 
【全平台通用】0.98元 

******开始查询【京东账号3】*********
数据获取失败，等待30秒后重试....
京东服务器返回空数据
疑似获取失败,等待10秒后用第二个接口试试....
领现金查询失败，服务器没有返回具体值.
【账号3🆔】(已实名)
【账号信息】Plus会员(102分)
【京豆变动】1豆(与昨日21:30比较)
【当前京豆】1豆(≈0.01元)
【礼品卡额】3.23元
【老农场】红富士3斤(80%)
【新农场】种植进度4/5(45.08%)
【话费积分】25.47(近7日将过期4.05)
【超市卡】6.02元(0.16元赠金16天后到期)
🧧🧧🧧红包明细🧧🧧🧧
【红包总额】0.80(总过期0.75)元 
【京喜特价】0.24(将过期0.19)元 
【微信小程序】0.56(将过期0.56)元 

******开始查询【京东账号4】*********
【账号4🆔】(已实名)
【账号信息】普通会员(100分)
【京豆变动】1812豆(与昨日21:31比较)
【当前京豆】1812豆(≈18.12元)
【特价金币】10币(≈0.00元)
【新农场】种植进度4/5(42.42%)
【话费积分】6.97
【超市卡】4.76元(0.28元赠金16天后到期)
🧧🧧🧧红包明细🧧🧧🧧
【红包总额】2.71(总过期0.75)元 
【京喜特价】0.22(将过期0.19)元 
【微信小程序】0.56(将过期0.56)元 
【全平台通用】1.93元 

添加缓存2024-05-31.json成功!
Bark APP发送通知调用API失败！！

HTTPError: Response code 431 (Request Header Fields Too Large)
    at Request.<anonymous> (/ql/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1717138206884,
    socket: 1717138206884,
    lookup: 1717138206932,
    connect: 1717138206983,
    secureConnect: 1717138207088,
    upload: 1717138207088,
    response: 1717138207139,
    end: 1717138207140,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 48,
      tcp: 51,
      tls: 105,
      request: 0,
      firstByte: 51,
      download: 1,
      total: 256
    }
  }
}

🔔京东资产统计, 结束! 🕛 64.571 秒


## 执行结束...   耗时 65 秒　　　
```

**Comment by Rebuilding127** [comment]
> @Rebuilding127 你这不是最新的通知文件吧

请问下你说的最新的通知文件在哪里？能否说明确点，或者给个链接

**Comment by whyour** [comment]
> > @Rebuilding127 你这不是最新的通知文件吧
> 
> 请问下你说的最新的通知文件在哪里？能否说明确点，或者给个链接

对比工具里有最新的通知文件  https://github.com/whyour/qinglong/blob/develop/sample/notify.js

**Comment by Rebuilding127** [comment]
> 对比工具里有最新的通知文件 https://github.com/whyour/qinglong/blob/develop/sample/notify.js

那就没有问题了，我用的就是最新的通知文件，整个黏贴进去后改了几个Bark参数而已。
而且也不是完全收不到通知，像农场任务是可以的，好像就资产统计不行。难道是脚本问题？

**Comment by whyour** [comment]
> > 对比工具里有最新的通知文件 https://github.com/whyour/qinglong/blob/develop/sample/notify.js
> 
> 
> 
> 那就没有问题了，我用的就是最新的通知文件，整个黏贴进去后改了几个Bark参数而已。
> 
> 而且也不是完全收不到通知，像农场任务是可以的，好像就资产统计不行。难道是脚本问题？
> 
> 

console.log('Bark APP 发送通知调用API失败😞\n', err);
最新版错误提示是这样的，跟你那一样吗

**Comment by Rebuilding127** [comment]
> > > 对比工具里有最新的通知文件 https://github.com/whyour/qinglong/blob/develop/sample/notify.js
> > 
> > 
> > 那就没有问题了，我用的就是最新的通知文件，整个黏贴进去后改了几个Bark参数而已。
> > 而且也不是完全收不到通知，像农场任务是可以的，好像就资产统计不行。难道是脚本问题？
> 
> console.log('Bark APP 发送通知调用API失败😞\n', err); 最新版错误提示是这样的，跟你那一样吗

发现脚本将原先的通知代码copy一份在使用，刚刚修改了那份代码，还是报错。
结尾部分日志如下：
```log
添加缓存2024-06-07.json成功!
Bark APP 发送通知调用API失败😞
 {"code":431,"message":"Request Header Fields Too Large","timestamp":1717723049}

🔔京东资产统计, 结束! 🕛 26.775 秒
```

**Comment by whyour** [comment]
> https://github.com/whyour/qinglong/blob/develop/sample/notify.js

https://github.com/whyour/qinglong/blob/develop/sample/notify.js 使用这个文件再试试

**Comment by whyour** [comment]
> > > > 对比工具里有最新的通知文件 https://github.com/whyour/qinglong/blob/develop/sample/notify.js
> > > 
> > > 
> > > 那就没有问题了，我用的就是最新的通知文件，整个黏贴进去后改了几个Bark参数而已。
> > > 而且也不是完全收不到通知，像农场任务是可以的，好像就资产统计不行。难道是脚本问题？
> > 
> > 
> > console.log('Bark APP 发送通知调用API失败😞\n', err); 最新版错误提示是这样的，跟你那一样吗
> 
> 发现脚本将原先的通知代码copy一份在使用，刚刚修改了那份代码，还是报错。 结尾部分日志如下：
> 
> ```
> 添加缓存2024-06-07.json成功!
> Bark APP 发送通知调用API失败😞
>  {"code":431,"message":"Request Header Fields Too Large","timestamp":1717723049}
> 
> 🔔京东资产统计, 结束! 🕛 26.775 秒
> ```

https://github.com/whyour/qinglong/blob/develop/sample/notify.js 使用这个文件再试试

**Comment by Rebuilding127** [comment]
> > > > > 对比工具里有最新的通知文件 https://github.com/whyour/qinglong/blob/develop/sample/notify.js
> > > > 
> > > > 
> > > > 那就没有问题了，我用的就是最新的通知文件，整个黏贴进去后改了几个Bark参数而已。
> > > > 而且也不是完全收不到通知，像农场任务是可以的，好像就资产统计不行。难道是脚本问题？
> > > 
> > > 
> > > console.log('Bark APP 发送通知调用API失败😞\n', err); 最新版错误提示是这样的，跟你那一样吗
> > 
> > 
> > 发现脚本将原先的通知代码copy一份在使用，刚刚修改了那份代码，还是报错。 结尾部分日志如下：
> > ```
> > 添加缓存2024-06-07.json成功!
> > Bark APP 发送通知调用API失败😞
> >  {"code":431,"message":"Request Header Fields Too Large","timestamp":1717723049}
> > 
> > 🔔京东资产统计, 结束! 🕛 26.775 秒
> > ```
> 
> https://github.com/whyour/qinglong/blob/develop/sample/notify.js 使用这个文件再试试

可以了，发送成功了！

**Comment by detesion** [comment]
> > > > > 对比工具里有最新的通知文件 https://github.com/whyour/qinglong/blob/develop/sample/notify.js
> > > > 
> > > > 
> > > > 那就没有问题了，我用的就是最新的通知文件，整个黏贴进去后改了几个Bark参数而已。
> > > > 而且也不是完全收不到通知，像农场任务是可以的，好像就资产统计不行。难道是脚本问题？
> > > 
> > > 
> > > console.log('Bark APP 发送通知调用API失败😞\n', err); 最新版错误提示是这样的，跟你那一样吗
> > 
> > 
> > 发现脚本将原先的通知代码copy一份在使用，刚刚修改了那份代码，还是报错。 结尾部分日志如下：
> > ```
> > 添加缓存2024-06-07.json成功!
> > Bark APP 发送通知调用API失败😞
> >  {"code":431,"message":"Request Header Fields Too Large","timestamp":1717723049}
> > 
> > 🔔京东资产统计, 结束! 🕛 26.775 秒
> > ```
> 
> https://github.com/whyour/qinglong/blob/develop/sample/notify.js 使用这个文件再试试

我改完了这个文件但是还是不太行，显示url问题，但是我在系统设置-通知设置里头输入相同的url却可以使用，报错的信息如下，实际上我是没有收到bark推送的
[👻 21:23:24]  ----【消息推送】----
[👻 21:23:24]  消息推送完毕
[👻 21:23:24]  Bark APP发送通知调用API失败！！
[❓ 21:23:24]   Invalid URL
执行完毕
