### ISSUE TITLE
希望增加定时任务分组以及折叠

### ISSUE THREAD

**Issue by Cxyofficial** [whyour/qinglong#2387]
### Clear and concise description of the problem

希望增加定时任务分组以及折叠功能
可以让用户自己选择分组
太多定时任务了没法直观查看
如果可以按文件夹分组或者让用户自定义分组就更好了

### Suggested solution

希望增加定时任务分组以及折叠功能
可以让用户自己选择分组
太多定时任务了没法直观查看
如果可以按文件夹分组或者让用户自定义分组就更好了

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
定时任务可以创建视图，筛选任务
