### ISSUE TITLE
Error: Cannot find module './utils/Rebels_jdCommon'

### ISSUE THREAD

**Issue by shizhitao** [whyour/qinglong#2391]
### Qinglong version

2.7.15

### Steps to reproduce

<img width="832" alt="image" src="https://github.com/whyour/qinglong/assets/22495107/21df7c6c-9263-4db4-b276-ceb5207e9d45">

### What is expected?

需要安装哪个依赖才能解决 Error: Cannot find module './utils/Rebels_jdCommon' 这种报错

### What is actually happening?

需要安装哪个依赖才能解决 Error: Cannot find module './utils/Rebels_jdCommon' 这种报错

**Comment by whyour** [comment]
差个文件，跟依赖没关系

**Comment by shizhitao** [comment]
在哪儿可以获取到这个文件？放到什么位置上
