### ISSUE TITLE
发现任务经常不运行

### ISSUE THREAD

**Issue by kokpk** [whyour/qinglong#2393]
### Qinglong version

2.17.5

### Steps to reproduce

最近发现青龙任务经常不运行查看青龙日志显示任务开始然会立马就是任务结束。具体任务日志里又没显示启动过。手动运行又都是正常的。
![photo_2024-06-08_19-46-02](https://github.com/whyour/qinglong/assets/37227634/e9c77e2c-3e1d-4f9f-9e8a-44c5aa24cbf8)

### What is expected?

请问怎么修复。。。

### What is actually happening?

任务无法自动定时运行。

**Comment by whyour** [comment]
任务堆积了，点下系统设置重新启动，有任务没完成，这是哪个版本镜像

**Comment by whyour** [comment]
系统设置并发任务数改大点

**Comment by kokpk** [comment]
MaxConcurrentNum="30" 我设置30 了我也忘记镜像是哪个版本的了都是容器内ql update 升级的

**Comment by whyour** [comment]
> MaxConcurrentNum="30" 我设置30 了我也忘记镜像是哪个版本的了都是容器内ql update 升级的

用的是系统设置里的并发设置，用最新镜像重建下容器吧

**Comment by kokpk** [comment]
> > MaxConcurrentNum="30" 我设置30 了我也忘记镜像是哪个版本的了都是容器内ql update 升级的
> 
> 用的是系统设置里的并发设置，用最新镜像重建下容器吧
好的用系统设置里的并发改成30了
我先docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新下试试。。看看重启完还会这样不。。不行再重建容器试试

**Comment by fanhengkui** [comment]
你把定时规则改为6位试试
