### ISSUE TITLE
删除新增订阅报错

### ISSUE THREAD

**Issue by Soarfree** [whyour/qinglong#2394]
### Qinglong version

2.17.5

### Steps to reproduce

用最新版2.17.5恢复老版备份之后，删除新增订阅开始报错。新增订阅之后报错，刷新实际已添加。删除订阅无效。

### What is expected?

无

### What is actually happening?

报错:Cannot destructure property 'type' of 'doc.interval_schedule' as it is undefined

**Comment by whyour** [comment]
是删不掉吗，能不能复现，具体是用哪个版本的数据恢复的

**Comment by Soarfree** [comment]
是的 ，删除 新增都报错 。但是新增报错之后刷新也添加成功了。删除就删不掉了。备份那个版本的忘记了 应该是2.17.3或者2.17.2

**Comment by whyour** [comment]
无法复现

**Comment by 88825** [comment]
同样发现了这个问题

**Comment by 88825** [comment]
提示Cannot destructure property 'type' of 'doc.interval_schedule' as it is undefined.
