### ISSUE TITLE
cookie管理里添加的cookie一直显示未获取，刷新下显示正常，然后又显示未获取

### ISSUE THREAD

**Issue by ycyfff** [whyour/qinglong#24]
2021年4月10日最新版本的镜像。

**Comment by whyour** [comment]
> 2021年4月10日最新版本的镜像。

贴下截图

**Comment by ycyfff** [comment]
> > 2021年4月10日最新版本的镜像。
> 
> 贴下截图

![image](https://user-images.githubusercontent.com/82076423/114263149-7ce0d700-9a16-11eb-9098-d66517a61476.png)
点击后面的刷新就会显示正常，刷新网页进来是又变成这样了

**Comment by ycyfff** [comment]
刚刚测试了下京豆变动通知，可以正常通知，这状态可能是个bug。

**Comment by ycyfff** [comment]
大佬，可以考虑下在每行cookie后面留个备注的地方嘛
