### ISSUE TITLE
更新不了面板仓库

### ISSUE THREAD

**Issue by dengxiaozhen** [whyour/qinglong#240]
`docker exec -it qinglong ql update`

开始更新仓库：/ql

Fetching origin
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': Could not resolve host: ghproxy.com
error: Could not fetch origin
HEAD is now at b40d381 修复cron name匹配
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': Could not resolve host: ghproxy.com

更新/ql失败，请检查原因...
![image](https://user-images.githubusercontent.com/8529528/120787641-24374180-c562-11eb-8eb8-69b897966559.png)
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/8529528/120787923-724c4500-c562-11eb-955d-a1354d0c1dc2.png">

**Comment by whyour** [comment]
有时候 ghproxy.com 会失败，重新执行一次应该就行了

**Comment by dengxiaozhen** [comment]
> 有时候 ghproxy.com 会失败，重新执行一次应该就行了

重新执行了很多次了 依然还是不行

**Comment by whyour** [comment]
> > 有时候 ghproxy.com 会失败，重新执行一次应该就行了
> 
> 重新执行了很多次了 依然还是不行

那你把config里的 githubproxy 变量删了
