### ISSUE TITLE
docker-debian底层，设置pip源报500错误

### ISSUE THREAD

**Issue by ChenDY2233** [whyour/qinglong#2401]
### Qinglong version

2.17.5

### Steps to reproduce

系统设置 -> 依赖设置 -> Python镜像源
提示 `WHERE parameter \"type\" has invalid \"undefined\" value`
同 issue #2265

### What is expected?

期望正常设置相关的系统配置项

### What is actually happening?

 `WHERE parameter \"type\" has invalid \"undefined\" value`

### System Info

```shell
System:
    OS: Linux 3.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Xeon(R) CPU           E7530  @ 1.87GHz
    Memory: 1.37 GB / 3.70 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.14.0 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
```

### Any additional comments?

![image](https://github.com/whyour/qinglong/assets/39426660/23e94996-eb32-4e5f-8fa1-ee737ba51306)

**Comment by whyour** [comment]
repeat https://github.com/whyour/qinglong/issues/2352
