### ISSUE TITLE
按照导出格式写的导入json文件，但是导入失败。

### ISSUE THREAD

**Issue by xushier** [whyour/qinglong#2402]
### Qinglong version

正式版 v2.17.5

### Steps to reproduce

这是导出的变量：
![image](https://github.com/whyour/qinglong/assets/31540107/ab2823e1-37fe-44c4-a8c2-69605a32878d)

这是导入的变量：
![image](https://github.com/whyour/qinglong/assets/31540107/adaf89bb-41dd-46b1-9cac-0f9bfa58de55)

一样的格式，但是导入显示：
![image](https://github.com/whyour/qinglong/assets/31540107/971d71bb-693e-4ad6-a31b-083b61b5a50a)

### What is expected?

如上所述，希望能修复导入

### What is actually happening?

如上所述

**Comment by whyour** [comment]
有字段确实 name 或者 value，检查下 json 文件

**Comment by xushier** [comment]
> 有字段缺少 name 或者 value，检查下 json 文件

这没错吧

![image](https://github.com/whyour/qinglong/assets/31540107/62b0b981-9e6e-4938-b76c-943b95729b45)

**Comment by whyour** [comment]
name value 不能为空
