### ISSUE TITLE
qinglong-debian增加是否更新apt update选项

### ISSUE THREAD

**Issue by yanghanbin** [whyour/qinglong#2403]
### Clear and concise description of the problem

我的docker设置如下
version: '2'
name: qinglong
services:
  qinglong:
    container_name: qinglong
    stdin_open: true
    tty: true
    restart: always
    deploy:
        resources:
            limits:
                memory: 4GB
    # alpine 基础镜像版本
    #image: whyour/qinglong:latest
    # debian-slim 基础镜像版本
    image: whyour/qinglong:debian
    volumes:
      - /volume1/docker/qinglong/ql:/ql/data
      - /volume2/Download:/ql/download
      - /volume1/docker/qinglong/sources.list:/etc/apt/sources.list
      - /volume1/docker/qinglong/apt.conf:/etc/apt/apt.conf
    ports:
      - "0.0.0.0:5700:5700"
     
因为某些原因，增加了  deb http://ftp.de.debian.org/debian bullseye main non-free
构建启动后，应用初始化，自动安装linux依赖会失败，如果手动运行一下apt update就正常了

### Suggested solution

在首次运行自动安装linux依赖的时候，自动执行一下apt update
后续作为可选配置

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
可以把 apt update 写到配置文件的 extra.sh 里，config 配置里 EnableExtraShell 设置为 true

**Comment by yanghanbin** [comment]
确认有效
