### ISSUE TITLE
在依赖设置里出现System {"type":"systemConfig"} not found

### ISSUE THREAD

**Issue by YvGuo-YY** [whyour/qinglong#2408]
### Qinglong version

版本 正式版 v2.17.6

### Steps to reproduce

在依赖设置里出现System {"type":"systemConfig"} not found

### What is expected?

在依赖设置里出现System {"type":"systemConfig"} not found

### What is actually happening?

在依赖设置里出现System {"type":"systemConfig"} not found
<img width="841" alt="image" src="https://github.com/whyour/qinglong/assets/54350593/733a1107-18c5-4fd6-9c2e-ebe3f068af35">

**Comment by whyour** [comment]
最新版本？再更新试试

**Comment by TangTangH** [comment]
遇到同样的问题，docker安装，版本为2.17.6，检查更新提示已是最新版

**Comment by PikaByter** [comment]
遇到同样的问题，docker安装，版本为2.17.6，检查更新提示已是最新版

**Comment by whyour** [comment]
http://demo.ninesix.cc:4433/setting demo 环境测试没问题，使用镜像重建下？

**Comment by TangTangH** [comment]
更新v2.17.7后恢复正常

**Comment by ywmm3951** [comment]
v2.17.7 还是问题依旧，只要点依赖设置和其他设置这2个栏目就会出现，不具体设置子项都会出现System {"type":"systemConfig"} not found

**Comment by Sco-ohhG** [comment]
![image](https://github.com/whyour/qinglong/assets/103553442/a86f8a0e-3113-4c0d-9cda-eafda8e52d57)
+1遇到

**Comment by wyonyg** [comment]
2.17.7我同样问题，不过我在系统设置>其他设置里重新启动一下就好了
![image](https://github.com/user-attachments/assets/5150d18d-259b-4bb3-966e-7df56a7a5696)

**Comment by ywmm3951** [comment]
> 2.17.7我同样问题，不过我在系统设置>其他设置里重新启动一下就好了 ![image](https://private-user-images.githubusercontent.com/175008573/348182664-5150d18d-259b-4bb3-966e-7df56a7a5696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MDQ4NDYsIm5iZiI6MTcyMDgwNDU0NiwicGF0aCI6Ii8xNzUwMDg1NzMvMzQ4MTgyNjY0LTUxNTBkMThkLTI1OWItNGJiMy05NjZlLTdkZjU2YTdhNTY5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQxNzE1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGFiZjgxZjg4MjkyNGY2OGNmZGE0NzVkZWE1MmM2ODRkNTQ2ZTU0ODM0NDU0YTliMjJiNzUzOGZhZWEwMzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2_aLEhVWrJG4V7VMXeCofaQDqrqnXWQcrqB-k8ouamU)

试了下，确实好了，真神奇！

**Comment by mapleshadow** [comment]
> 2.17.7我同样问题，不过我在系统设置>其他设置里重新启动一下就好了 ![image](https://private-user-images.githubusercontent.com/175008573/348182664-5150d18d-259b-4bb3-966e-7df56a7a5696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwODYwOTIsIm5iZiI6MTcyMjA4NTc5MiwicGF0aCI6Ii8xNzUwMDg1NzMvMzQ4MTgyNjY0LTUxNTBkMThkLTI1OWItNGJiMy05NjZlLTdkZjU2YTdhNTY5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QxMzA5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmNhZjMyMGM5N2Q2OTEzMzA0M2QyMDg2YWI5ZjRjMWIxZTA1YWE3MTQ4Mzc3YjUwOTJiZDQ4YmViNzBhY2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YkV9v6x3tCRELYAUTtM-tyi0lpjJMEweMEzxe3IkFn0)

问题确实存在，用你的方法，搞定了。

**Comment by yaobohan888** [comment]
更新最新版本搞定了，谢谢

**Comment by BA7IEE** [comment]
重启解决问题了好神奇，谢谢
