### ISSUE TITLE
debian12主机部署，使用apt安装的依赖包名有问题！

### ISSUE THREAD

**Issue by xueba0458** [whyour/qinglong#2409]
### Qinglong version

v2.17.6

### Steps to reproduce

debian12系统

### What is expected?

输出如下
`root@qinglong:~# qinglong
+ [[ ! -n /qinglong ]]
+ [[ ! -n /qonglong/data ]]
++ source /etc/os-release
+++ PRETTY_NAME='Debian GNU/Linux 12 (bookworm)'
+++ NAME='Debian GNU/Linux'
+++ VERSION_ID=12
+++ VERSION='12 (bookworm)'
+++ VERSION_CODENAME=bookworm
+++ ID=debian
+++ HOME_URL=https://www.debian.org/
+++ SUPPORT_URL=https://www.debian.org/support
+++ BUG_REPORT_URL=https://bugs.debian.org/
++ echo debian
+ os_name=debian
+ [[ debian == \a\l\p\i\n\e ]]
+ [[ debian == \d\e\b\i\a\n ]]
+ apt update
命中:1 http://deb.debian.org/debian bookworm InRelease
命中:2 http://security.debian.org bookworm-security InRelease
命中:3 http://deb.debian.org/debian bookworm-updates InRelease
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
所有软件包均为最新。
+ apt install -y git curl wget tzdata perl openssl jq nginx procps netcat openssh-client
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
虚拟软件包 netcat 由下面的软件包提供：
  netcat-openbsd 1.219-1
  netcat-traditional 1.10-47
请您明确地选择安装其中一个。

E: 软件包 netcat 没有可安装候选`

### What is actually happening?

debian12主机部署，使用apt安装的依赖包名有问题！netcat在debian12中为虚包，由这些包填实： [netcat-openbsd](https://packages.debian.org/zh-cn/bookworm/mips/netcat-openbsd), [netcat-traditional](https://packages.debian.org/zh-cn/bookworm/mips/netcat-traditional)
具体可以查看https://packages.debian.org/search?lang=zh-cn&arch=mips&keywords=netcat
![image](https://github.com/whyour/qinglong/assets/51258772/4f9c3e99-d962-4556-abd9-45e770e0a89e)

**Comment by whyour** [comment]
已修复
