### ISSUE TITLE
docker下载最新的只有2.10.13版本？

### ISSUE THREAD

**Issue by CaoJ20132014** [whyour/qinglong#2413]
### Clear and concise description of the problem

docker无法下载最新版本

### Suggested solution

docker无法下载最新版本

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by CaoJ20132014** [comment]
官方镜像源下载失败，只能使用阿里云的或者华为云的，但是下载下来都是2.10.13版本的

**Comment by Su0515** [comment]
一样的问题

**Comment by whyour** [comment]
指定版本或者更改为其他源，参考
https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6
