### ISSUE TITLE
青龙面板 运行脚本时

### ISSUE THREAD

**Issue by xiaopengzzc** [whyour/qinglong#2415]
### Qinglong version

2.17.7

### Steps to reproduce

正常登入青龙面板，找到一个脚本，打开旁边的日志，显示只运行了0.57秒，一秒都没有运行到，之前还是好好的，自从6.26日以后就开始了这样

### What is expected?

解决，能正常使用

### What is actually happening?

脚本不能正常使用后debian

### System Info

```shell
debian，谷歌
```

**Comment by xiaopengzzc** [comment]
![微信图片_20240702094939](https://github.com/whyour/qinglong/assets/136769452/64a53e32-bdb8-43fe-8c73-e0fc1a86ee29)

**Comment by whyour** [comment]
这跟系统有啥关系，已经是脚本的日志了

**Comment by wzgrx** [comment]
+1

**Comment by wzgrx** [comment]
解决了吗
