### ISSUE TITLE
循环任务总是会被打断，不清楚什么原因。

### ISSUE THREAD

**Issue by xushier** [whyour/qinglong#2416]
### Qinglong version

正式版 v2.17.6   镜像 Debian 标签

### Steps to reproduce

任务：
![image](https://github.com/whyour/qinglong/assets/31540107/52cb444c-f01d-4cf1-b0a9-aaf71de47f00)

每次运行整整一个小时后就会被打断退出。将面板所有任务都停了也是一样的。
![image](https://github.com/whyour/qinglong/assets/31540107/80b8d590-29a9-46af-bd1c-a7dad79fc43e)

### What is expected?

看别人的是好的，可以一直持续运行。所以是因为debian镜像的原因，还是？

### What is actually happening?

任务打断退出。

### System Info

```shell
Docker
System：Unraid 6.12.10
browser: Chrome 126.0.6478.115
```

**Comment by whyour** [comment]
CommandTimeoutTime  配置文件里这个值清空

**Comment by xushier** [comment]
找到了。看来是更新容器没有自动去掉这个超时配置。

![image](https://github.com/whyour/qinglong/assets/31540107/1dd442ee-8125-4036-893a-70525a6ac646)
