### ISSUE TITLE
青龙面板调用不了chrome

### ISSUE THREAD

**Issue by Rui-xing** [whyour/qinglong#2417]
### Qinglong version

2.17.7

### Steps to reproduce

这是在青龙面板上运行的![image](https://github.com/whyour/qinglong/assets/84909508/8160c362-dcf1-4454-97ad-4f2bf76d9362)

### What is expected?

这是在我本地的机器上运行的![image](https://github.com/whyour/qinglong/assets/84909508/405959fa-7418-4342-b0cd-a521a6ff183e)

### What is actually happening?

我用青龙运行保号脚本 python的pyppeteer依赖 无法调用到chrome
而在我本地机器运行这个保号脚本的时候，pyppeteer是可以正常调用到chrome的

**Comment by whyour** [comment]
使用 debian 版本？

**Comment by Rui-xing** [comment]
> 使用 debian 版本？
docker搭建的
 whyour/qinglong:latest

**Comment by whyour** [comment]
@Rui-xing whyour/qinglong:debian

**Comment by Rui-xing** [comment]
就是说要更新镜像对吧

**Comment by Rui-xing** [comment]
![image](https://github.com/whyour/qinglong/assets/84909508/54993651-5208-494b-9520-284bb2c4a9d7)
可是还是一样的

**Comment by whyour** [comment]
> ![image](https://github.com/whyour/qinglong/assets/84909508/54993651-5208-494b-9520-284bb2c4a9d7)
> 
> 可是还是一样的
> 
> 

这已经调用 chrome 了，具体错误要自己排查一下
