### ISSUE TITLE
拉取私库不成功，私库默认分支无代码，需要指定分支拉取

### ISSUE THREAD

**Issue by aliyy2021** [whyour/qinglong#242]
大佬，你好，拉取0301大佬的私库，提示拉取成功，但是定时任务列表没有，脚本目录也没有，请问这是怎么回事，怎么解决?

![image](https://user-images.githubusercontent.com/77948441/120812263-691da100-c57f-11eb-86d2-b98812c80be8.png)
![image](https://user-images.githubusercontent.com/77948441/120812347-7b97da80-c57f-11eb-9b4a-8485693d89a1.png)

**Comment by whyour** [comment]
不可能吧，todesk 远程看看？

**Comment by MangoDong** [comment]
能不能发一下命令呢

**Comment by aliyy2021** [comment]
> 不可能吧，todesk 远程看看？

大佬，我的设备是N1，能todesk?

**Comment by whyour** [comment]
> > 不可能吧，todesk 远程看看？
> 
> 大佬，我的设备是N1，能todesk?

你不是用电脑连接的n1吗？电脑不是可以下载 todesk ？

**Comment by aliyy2021** [comment]
> > > 不可能吧，todesk 远程看看？
> > 
> > 
> > 大佬，我的设备是N1，能todesk?
> 
> 你不是用电脑连接的n1吗？电脑不是可以下载 todesk ？

大佬，todesk已准备好，怎么联络你？

**Comment by DarkAge2018** [comment]
进入容器里面,输下面两行命令
cd /ql/repo/lxk0301_jd_scripts
git switch master
再更新脚本就好了

**Comment by whyour** [comment]
@DarkAge2018 大佬说的对，这是默认分支的问题

**Comment by aliyy2021** [comment]
> @DarkAge2018 大佬说的对，这是默认分支的问题

感谢大佬们！

**Comment by whyour** [comment]
v2.2.0-062 已添加此功能
