### ISSUE TITLE
搞了个小Demo再现部分脚本报错ssl问题

### ISSUE THREAD

**Issue by sstakill** [whyour/qinglong#2420]
### Qinglong version

 青龙 2.17.7 是目前检测到的最新可用版本了。

### Steps to reproduce

又抽空看了下：

问题大概就是openssl版本过高导致dh参数太短会报错，因为有的服务器dh参数就设置了1024。

最新版青龙用的是OpenSSL 3.3.1 4 运行会报错DH太短。但是青龙低版本例如3.1.4版本，用的OpenSSL为3.1.4，版本就不会报错。建议用tls版本吧。

下面这js脚本访问的中国-电信的某个接口，用nmap看了下dh参数是1024。

```javascript
const got = require("got");

class HttpRequester {
  constructor() {
    this.index = 1; // 示例用户索引
    this.name = "TestUser";
    this.userCount = 1;
    const headers = { Connection: "keep-alive" };
    const retryOptions = { retries: 0, retryDelay: 1000 };
    const timeout = 5000; // 超时时间为 5 秒
    this.got = got.extend({
      headers,
      retry: retryOptions,
      timeout,
      followRedirect: false,
      ignoreInvalidCookies: true,
      https: {
        rejectUnauthorized: false, // 不验证SSL证书
        minVersion: "TLSv1.2", // 设置最低TLS版本
        //ciphers:"ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:!aNULL:!eNULL:!MD5",
        ciphers: "AES128-SHA", // 强制使用较弱的加密算法以触发错误
      },
    });
  }

  log(message) {
    console.log(`[${this.name}] ${message}`);
  }

  async request(options) {
    let response;
    try {
      response = await this.got(options);
      return response;
    } catch (error) {
      if (error.code === "EPROTO") {
        this.log(`请求错误 [EPROTO] [RequestError] ${error.message}`);
      } else {
        this.log(`请求错误 ${error.message}`);
      }
      return null;
    }
  }

  async getSign(params = {}) {
    let sign = false;
    try {
      const url = "https://wapside.189.cn:9001/jt-sign/ssoHomLogin"; 
      const options = {
        method: "GET",
        url,
        searchParams: params,
        responseType: "json",
      };
      const response = await this.request(options);
      const { body, statusCode } = response || {};
      const resultCode = body?.resoultCode || statusCode;

      if (resultCode === 0) {
        sign = body?.sign;
        this.sign = sign;
        this.got = this.got.extend({ headers: { sign } });
      } else {
        this.log(`获取sign失败[${resultCode}]: ${JSON.stringify(body)}`);
      }
    } catch (error) {
      console.log(error);
    } finally {
      return sign;
    }
  }
}

// 示例运行
(async () => {
  const requester = new HttpRequester();
  const params = { ticket: "your_ticket" }; // 实际的ticket，这里为了实现问题随意填。
  const sign = await requester.getSign(params);
  if (sign) {
    console.log("Sign:", sign);
  } else {
    console.log("未能获取sign。");
  }
})();
```

### What is expected?

这是本机能获取到请求。 {"resoultCode":"1","resoultMsg":"请求失败"}

![image](https://github.com/whyour/qinglong/assets/66406703/9c3d4832-37ca-4b85-87ea-b1a8eb20561f)

### What is actually happening?

青龙最新版本

![image](https://github.com/whyour/qinglong/assets/66406703/bda5330c-90dc-40fd-91f2-e84961d56b0c)

**Comment by sstakill** [comment]
> ### Qinglong version
> 青龙 2.17.7 是目前检测到的最新可用版本了。
> 
> ### Steps to reproduce
> 下面这代码是删除某些业务，只留下能触发问题的js脚本。 电脑node用的是v20.12.2可以运行获取到响应，最新版青龙运行会报错DH密钥相关问题。
> 
> ```js
> const got = require("got");
> 
> class HttpRequester {
>   constructor() {
>     this.index = 1; // 示例用户索引
>     this.name = "TestUser";
>     this.userCount = 1;
>     const headers = { Connection: "keep-alive" };
>     const retryOptions = { retries: 0, retryDelay: 1000 }; // 不重试，立即触发错误
>     const timeout = 5000; // 超时时间为 5 秒
>     this.got = got.extend({
>       headers,
>       retry: retryOptions,
>       timeout,
>       followRedirect: false,
>       ignoreInvalidCookies: true,
>       https: {
>         rejectUnauthorized: false, // 不验证SSL证书
>         minVersion: "TLSv1.2", // 设置最低TLS版本
>         //ciphers: "ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:!aNULL:!eNULL:!MD5", 
>         ciphers: "AES128-SHA", // 强制使用较弱的加密算法以触发错误
>       },
>     });
>   }
> 
>   log(message) {
>     console.log(`[${this.name}] ${message}`);
>   }
> 
>   async request(options) {
>     let response;
>     try {
>       response = await this.got(options);
>       return response;
>     } catch (error) {
>       if (error.code === "EPROTO") {
>         this.log(`请求错误 [EPROTO] [RequestError] ${error.message}`);
>       } else {
>         this.log(`请求错误 ${error.message}`);
>       }
>       return null;
>     }
>   }
> 
>   async getSign(params = {}) {
>     let sign = false;
>     try {
>       const url = "https://wapside.189.cn:9001/jt-sign/ssoHomLogin"; // 触发错误的示例网址
>       const options = {
>         method: "GET",
>         url,
>         searchParams: params,
>         responseType: "json",
>       };
>       const response = await this.request(options);
>       const { body, statusCode } = response || {};
>       const resultCode = body?.resoultCode || statusCode;
> 
>       if (resultCode === 0) {
>         sign = body?.sign;
>         this.sign = sign;
>         this.got = this.got.extend({ headers: { sign } });
>       } else {
>         this.log(`获取sign失败[${resultCode}]: ${JSON.stringify(body)}`);
>       }
>     } catch (error) {
>       console.log(error);
>     } finally {
>       return sign;
>     }
>   }
> }
> 
> // 示例运行
> (async () => {
>   const requester = new HttpRequester();
>   const params = { ticket: "your_ticket" }; // 替换为实际的ticket
>   const sign = await requester.getSign(params);
>   if (sign) {
>     console.log("Sign:", sign);
>   } else {
>     console.log("未能获取sign。");
>   }
> })();
> ```
> 
> ### What is expected?
> 这是本机能获取到请求。 {"resoultCode":"1","resoultMsg":"请求失败"}
> 
> ![image](https://private-user-images.githubusercontent.com/66406703/346294691-9c3d4832-37ca-4b85-87ea-b1a8eb20561f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTUzMjQsIm5iZiI6MTcyMDI5NTAyNCwicGF0aCI6Ii82NjQwNjcwMy8zNDYyOTQ2OTEtOWMzZDQ4MzItMzdjYS00Yjg1LTg3ZWEtYjFhOGViMjA1NjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDE5NDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MzVkOGY5NDIxNGViMTBmNTM4MzhjZWU2ZmIzYjAyYzRmYWNjNmQ4YWU3ODEzZjE2MmQyNDdhYTk0YWFiNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L0sH86dQGWPRAsgzrUKHBIsJNTLo71SdlJyAKXAnPG0)
> 
> ### What is actually happening?
> 青龙最新版本
> 
> ![image](https://private-user-images.githubusercontent.com/66406703/346294751-bda5330c-90dc-40fd-91f2-e84961d56b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTUzMjQsIm5iZiI6MTcyMDI5NTAyNCwicGF0aCI6Ii82NjQwNjcwMy8zNDYyOTQ3NTEtYmRhNTMzMGMtOTBkYy00MGZkLTkxZjItZTg0OTYxZDU2YjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDE5NDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlY2NlMDUxMmEyYTFlOTlkMjUyZjIzOGY0ZGE0M2I5ZTAyMDRkY2ZhOWZlMTJjYjEzZDQ0ZTUyZjZkN2U2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bgn1NBJwFJa8RdmQbem2WQbDyuXvnN2vKwRllULqW6w)
> 
> ### System Info
> _No response_
> 
> ### Any additional comments?
> _No response_

**Comment by whyour** [comment]
1. 任务执行前增加 export NODE_OPTIONS="${NODE_OPTIONS} --tls-cipher-list=DEFAULT@SECLEVEL=0"
2. 换 debian 版本镜像 whyour/qinglong:debian
3. extra.sh 修改 openssl.conf 文件，系统系统后自动运行

**Comment by xmoxmo** [comment]
您好，这三天需要全部满足吗，还是只修改第一天加一个变量就可以了？

**Comment by whyour** [comment]
@xmoxmo 一个就行

**Comment by xmoxmo** [comment]
> @xmoxmo 一个就行

收到，谢谢

**Comment by Svenmax** [comment]
> > @xmoxmo 一个就行
> 
> 收到，谢谢

你好，具体怎么修改的麻烦说下，谢谢

**Comment by sola237** [comment]
![image](https://github.com/user-attachments/assets/b20b2a69-de8b-47f4-9326-79fa92247b2a)
添加了第一个还是一样的问题 你们试过后面2种方案吗？
