### ISSUE TITLE
自动更新订阅时，会错误的重复添加定时任务，导致队列中任务数量过度，cpu占用率高

### ISSUE THREAD

**Issue by QYC-Unity** [whyour/qinglong#2422]
### Qinglong version

2.17.6

### Steps to reproduce

在订阅管理中设置定时拉取
获取更新时出现异常
其他脚本的data文件夹下scripts文件夹里出现其他订阅的文件夹，且嵌套创建

### What is expected?

异常拉取时不会产生嵌套任务导致cpu占用过高

### What is actually happening?

产生大量的嵌套任务，占用cpu资源导致系统卡死崩溃
[log.txt](https://github.com/user-attachments/files/16126805/log.txt)

**Comment by whyour** [comment]
最新版已增加的单个任务运行中的实例上限，并会进行告警
