### ISSUE TITLE
js运行时支持ESM

### ISSUE THREAD

**Issue by QQQQQQQQiu** [whyour/qinglong#2424]
### Clear and concise description of the problem

![image](https://github.com/whyour/qinglong/assets/23096078/615848af-0c50-4241-866c-fc44a732285f)

大佬你好，请问如何让系统支持js文件ESM导出呢？

### Suggested solution

// test.js

export const Env = 'xxx'

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
文件后缀改成 mjs

**Comment by QQQQQQQQiu** [comment]
> 文件后缀改成 mjs

确实可以，mjs是node传统兼容esm的方案，要不现代化考虑下把package
