### ISSUE TITLE
定时规则问题

### ISSUE THREAD

**Issue by fanhengkui** [whyour/qinglong#2427]
### Qinglong version

2.17.7

### Steps to reproduce

定时规则5位有时能运行，有时不行，6位反而正常

### What is expected?

如果设置成5位保存后，保存后台日志应该出现创建定时任务成功

### What is actually happening?

如果设置成5位保存后，保存后台日志无变化，6位时反而创建定时任务成功
![image](https://github.com/whyour/qinglong/assets/96706554/3a455aac-848b-44a1-9178-15799d99ac6b)

**Comment by fanhengkui** [comment]
不知道被我捣腾了啥，只有6位的定时规则才能跑
ubuntu 24.04

**Comment by whyour** [comment]
可以使用 debian 版本，5 6 位都有提示，latest 版本 5 位用的是系统内的 crontab，所以没有提示，如果不能支持运行，建议重启下容器
