### ISSUE TITLE
系统日志一直生成空闲队列，日志文件变大

### ISSUE THREAD

**Issue by aidaobali-hn** [whyour/qinglong#2431]
### Qinglong version

2.17.7

### Steps to reproduce

在2.17.4版本中没出现这个问题，升级到2.17.7后出现的，一直生成空闲队列，导致日志文件变大，还有这个版本如果运行多个任务，没有等待任务数量。之前版本是有的。如果运行运行的脚本是高并发的，时间会有波动，不想之前那么稳定，比如高并发脚本每隔100毫秒运行一次，现在出现200-700毫秒间来回波动，感觉可能一直生成的日志导致的，占用了线程
![屏幕截图 2024-07-12 231349](https://github.com/user-attachments/assets/c3563d1f-d873-470d-ab9a-72bfe383639a)

### What is expected?

有什么方法可以停止一直产生空闲队列，或者无损降级，还有怎么删除系统日志

### What is actually happening?

有什么方法可以停止一直产生空闲队列，或者无损降级，还有怎么删除系统日志

### System Info

```shell
CentOS，青龙2.17.7
```

**Comment by whyour** [comment]
其他设置里重新启动下，或者重建下容器

**Comment by drw2005** [comment]
> 1. 其他设置里重新启动下，或者重建下容器
> 2. 可以备份数据使用指定版本镜像进行恢复

大佬，我之前也是这个情况，现在重建容器后好像解决了，但是之前的接近10万条日志如何清理掉？
![QQ截图20240821162427](https://github.com/user-attachments/assets/e7ada904-362c-4a1c-8721-f30ad60b6d5f)

**Comment by whyour** [comment]
@drw2005 data/syslog 目录下的日志文件删掉

**Comment by drw2005** [comment]
> @drw2005 data/syslog 目录下的日志文件删掉

搞定了，感谢指点！
