### ISSUE TITLE
sh的脚本运行时提示“无权限”

### ISSUE THREAD

**Issue by winsphinx** [whyour/qinglong#2432]
### Qinglong version

2.17.8

### Steps to reproduce

今天升级到最新版后，原来正常可运行的任务，提示无权限。
![image](https://github.com/user-attachments/assets/b5ceefaa-453b-446e-a354-621369c51fae)
![image](https://github.com/user-attachments/assets/77428c37-8800-42a2-8aba-51d609e4f99d)

进入容器手工可以正常运行。

### What is expected?

期望能正常运行

### What is actually happening?

无法判断

**Comment by whyour** [comment]
shell 任务咋写的

**Comment by nsv2051** [comment]
我也是，附上shell命令
![image](https://github.com/user-attachments/assets/3e9e34f2-ce05-457e-a29b-79b6dd274ccd)
最新版本在执行任务时加载不到环境变量
![image](https://github.com/user-attachments/assets/f15d8a52-4d61-4dae-a867-12b6e70dd5c5)


> shell 任务咋写的

**Comment by whyour** [comment]
> 我也是，附上shell命令 ![image](https://private-user-images.githubusercontent.com/39900381/348446334-3e9e34f2-ce05-457e-a29b-79b6dd274ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDYzMzQtM2U5ZTM0ZjItY2UwNS00NTdlLWEyOWItNzliNmRkMjc0Y2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzRkNDMyMzk4ODg2MjYxZWQxNDE1YWZjODc0N2I4Zjk1MTNiYjdlM2M1NmUwNmRkZmZmMmQzNzgzODMxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XW_qwuUYCXthbo7GNYvklyosPMRkzkwl0UcVwAqXRw) 最新版本在执行任务时加载不到环境变量 ![image](https://private-user-images.githubusercontent.com/39900381/348446405-f15d8a52-4d61-4dae-a867-12b6e70dd5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDY0MDUtZjE1ZDhhNTItNGQ2MS00ZGFlLWE4NjctMTJiNmU3MGRkNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMjk0ODk5YjEwMDVkM2Y4OGVlMTBlNTMyNTQxMDg2ZDI5NzhhOTM2ZWNjODc1YmUzNDE2NmZjMjFjMmJhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nZTFrU1RuuLgQiCBRyNxmo2AosGt00dqfJc-fIdFQc)
> 
> > shell 任务咋写的

再更新下试试

**Comment by nsv2051** [comment]
> > 我也是，附上shell命令 ![image](https://private-user-images.githubusercontent.com/39900381/348446334-3e9e34f2-ce05-457e-a29b-79b6dd274ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDYzMzQtM2U5ZTM0ZjItY2UwNS00NTdlLWEyOWItNzliNmRkMjc0Y2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzRkNDMyMzk4ODg2MjYxZWQxNDE1YWZjODc0N2I4Zjk1MTNiYjdlM2M1NmUwNmRkZmZmMmQzNzgzODMxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XW_qwuUYCXthbo7GNYvklyosPMRkzkwl0UcVwAqXRw) 最新版本在执行任务时加载不到环境变量 ![image](https://private-user-images.githubusercontent.com/39900381/348446405-f15d8a52-4d61-4dae-a867-12b6e70dd5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDY0MDUtZjE1ZDhhNTItNGQ2MS00ZGFlLWE4NjctMTJiNmU3MGRkNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMjk0ODk5YjEwMDVkM2Y4OGVlMTBlNTMyNTQxMDg2ZDI5NzhhOTM2ZWNjODc1YmUzNDE2NmZjMjFjMmJhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nZTFrU1RuuLgQiCBRyNxmo2AosGt00dqfJc-fIdFQc)
> > > shell 任务咋写的
> 
> 再更新下试试

已更新，环境变量正常了 shell脚本还是同样报错

**Comment by winsphinx** [comment]
一个jd的，一个b站的
![image](https://github.com/user-attachments/assets/6e33ebe3-ccac-43a5-8833-b0c5fc0e9f19)

![image](https://github.com/user-attachments/assets/261b454b-d3a2-4f8a-ae04-444ed8c85a1f)

**Comment by whyour** [comment]
> > > 我也是，附上shell命令 ![image](https://private-user-images.githubusercontent.com/39900381/348446334-3e9e34f2-ce05-457e-a29b-79b6dd274ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDYzMzQtM2U5ZTM0ZjItY2UwNS00NTdlLWEyOWItNzliNmRkMjc0Y2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzRkNDMyMzk4ODg2MjYxZWQxNDE1YWZjODc0N2I4Zjk1MTNiYjdlM2M1NmUwNmRkZmZmMmQzNzgzODMxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XW_qwuUYCXthbo7GNYvklyosPMRkzkwl0UcVwAqXRw) 最新版本在执行任务时加载不到环境变量 ![image](https://private-user-images.githubusercontent.com/39900381/348446405-f15d8a52-4d61-4dae-a867-12b6e70dd5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDY0MDUtZjE1ZDhhNTItNGQ2MS00ZGFlLWE4NjctMTJiNmU3MGRkNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMjk0ODk5YjEwMDVkM2Y4OGVlMTBlNTMyNTQxMDg2ZDI5NzhhOTM2ZWNjODc1YmUzNDE2NmZjMjFjMmJhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nZTFrU1RuuLgQiCBRyNxmo2AosGt00dqfJc-fIdFQc)
> > > > shell 任务咋写的
> > 
> > 
> > 再更新下试试
> 
> 已更新，环境变量正常了 shell脚本还是同样报错

你这任务里的命令咋写的

**Comment by whyour** [comment]
> > shell 任务咋写的
> 
> 一个jd的，一个b站的 ![image](https://private-user-images.githubusercontent.com/5674054/348447137-6e33ebe3-ccac-43a5-8833-b0c5fc0e9f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDMxMzIsIm5iZiI6MTcyMDg0MjgzMiwicGF0aCI6Ii81Njc0MDU0LzM0ODQ0NzEzNy02ZTMzZWJlMy1jY2FjLTQzYTUtODgzMy1iMGM1ZmMwZTlmMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMDM1MzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYzMTIwYjViMDAzZDNiNzMyYjZmM2MyMjU5YTUxODVlMjE5MmFkNTZmYzBkYWEzMTMzMGU2NTk2YWE2ZWU5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Rp0f_6yg4VpZX-CWCmpxfKrxjIPzn7dvFZIpn1S0VuE)
> 
> ![image](https://private-user-images.githubusercontent.com/5674054/348447165-261b454b-d3a2-4f8a-ae04-444ed8c85a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDMxMzIsIm5iZiI6MTcyMDg0MjgzMiwicGF0aCI6Ii81Njc0MDU0LzM0ODQ0NzE2NS0yNjFiNDU0Yi1kM2EyLTRmOGEtYWUwNC00NDRlZDhjODVhMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMDM1MzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWRjODU0NDk4YjYxZmI2MDI5N2Q3NzEyZjNjMTE5MTI0OTRkNmVjODA4ODU3NmM5MTNmZTljZWI3YWI5YjdhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PylhwAMQgSAbgJ-6uK_rOrhaqoA3j0x-Q3Ay2K3q43g)

定时任务的命令咋写的

**Comment by nsv2051** [comment]
> > > > 我也是，附上shell命令 ![image](https://private-user-images.githubusercontent.com/39900381/348446334-3e9e34f2-ce05-457e-a29b-79b6dd274ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDYzMzQtM2U5ZTM0ZjItY2UwNS00NTdlLWEyOWItNzliNmRkMjc0Y2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzRkNDMyMzk4ODg2MjYxZWQxNDE1YWZjODc0N2I4Zjk1MTNiYjdlM2M1NmUwNmRkZmZmMmQzNzgzODMxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XW_qwuUYCXthbo7GNYvklyosPMRkzkwl0UcVwAqXRw) 最新版本在执行任务时加载不到环境变量 ![image](https://private-user-images.githubusercontent.com/39900381/348446405-f15d8a52-4d61-4dae-a867-12b6e70dd5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDY0MDUtZjE1ZDhhNTItNGQ2MS00ZGFlLWE4NjctMTJiNmU3MGRkNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMjk0ODk5YjEwMDVkM2Y4OGVlMTBlNTMyNTQxMDg2ZDI5NzhhOTM2ZWNjODc1YmUzNDE2NmZjMjFjMmJhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nZTFrU1RuuLgQiCBRyNxmo2AosGt00dqfJc-fIdFQc)
> > > > > shell 任务咋写的
> > > 
> > > 
> > > 再更新下试试
> > 
> > 
> > 已更新，环境变量正常了 shell脚本还是同样报错
> 
> 你这任务里的命令咋写的

task xxx.sh

**Comment by winsphinx** [comment]
更新后，目前正常。
感谢修复！

**Comment by whyour** [comment]
> > > > > 我也是，附上shell命令 ![image](https://private-user-images.githubusercontent.com/39900381/348446334-3e9e34f2-ce05-457e-a29b-79b6dd274ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDYzMzQtM2U5ZTM0ZjItY2UwNS00NTdlLWEyOWItNzliNmRkMjc0Y2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzRkNDMyMzk4ODg2MjYxZWQxNDE1YWZjODc0N2I4Zjk1MTNiYjdlM2M1NmUwNmRkZmZmMmQzNzgzODMxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XW_qwuUYCXthbo7GNYvklyosPMRkzkwl0UcVwAqXRw) 最新版本在执行任务时加载不到环境变量 ![image](https://private-user-images.githubusercontent.com/39900381/348446405-f15d8a52-4d61-4dae-a867-12b6e70dd5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDY0MDUtZjE1ZDhhNTItNGQ2MS00ZGFlLWE4NjctMTJiNmU3MGRkNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMjk0ODk5YjEwMDVkM2Y4OGVlMTBlNTMyNTQxMDg2ZDI5NzhhOTM2ZWNjODc1YmUzNDE2NmZjMjFjMmJhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nZTFrU1RuuLgQiCBRyNxmo2AosGt00dqfJc-fIdFQc)
> > > > > > shell 任务咋写的
> > > > 
> > > > 
> > > > 再更新下试试
> > > 
> > > 
> > > 已更新，环境变量正常了 shell脚本还是同样报错
> > 
> > 
> > 你这任务里的命令咋写的
> 
> task xxx.sh

sh 执行问题修复了

**Comment by nsv2051** [comment]
> > > > > > 我也是，附上shell命令 ![image](https://private-user-images.githubusercontent.com/39900381/348446334-3e9e34f2-ce05-457e-a29b-79b6dd274ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDYzMzQtM2U5ZTM0ZjItY2UwNS00NTdlLWEyOWItNzliNmRkMjc0Y2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzRkNDMyMzk4ODg2MjYxZWQxNDE1YWZjODc0N2I4Zjk1MTNiYjdlM2M1NmUwNmRkZmZmMmQzNzgzODMxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XW_qwuUYCXthbo7GNYvklyosPMRkzkwl0UcVwAqXRw) 最新版本在执行任务时加载不到环境变量 ![image](https://private-user-images.githubusercontent.com/39900381/348446405-f15d8a52-4d61-4dae-a867-12b6e70dd5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDIyNTEsIm5iZiI6MTcyMDg0MTk1MSwicGF0aCI6Ii8zOTkwMDM4MS8zNDg0NDY0MDUtZjE1ZDhhNTItNGQ2MS00ZGFlLWE4NjctMTJiNmU3MGRkNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMjk0ODk5YjEwMDVkM2Y4OGVlMTBlNTMyNTQxMDg2ZDI5NzhhOTM2ZWNjODc1YmUzNDE2NmZjMjFjMmJhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nZTFrU1RuuLgQiCBRyNxmo2AosGt00dqfJc-fIdFQc)
> > > > > > > shell 任务咋写的
> > > > > 
> > > > > 
> > > > > 再更新下试试
> > > > 
> > > > 
> > > > 已更新，环境变量正常了 shell脚本还是同样报错
> > > 
> > > 
> > > 你这任务里的命令咋写的
> > 
> > 
> > task xxx.sh
> 
> sh 执行问题修复了

感谢修复 已正常执行

**Comment by Jejz168** [comment]
还有个问题，你看执行结束后面没时间显示，好像debian没修复
