### ISSUE TITLE
执行结束时间显示

### ISSUE THREAD

**Issue by Jejz168** [whyour/qinglong#2435]
### Qinglong version

debian

### Steps to reproduce

…

### What is expected?

…

### What is actually happening?

![IMG_6197](https://github.com/user-attachments/assets/ca1ba8b1-a4c3-4ca1-bbe5-08e8378f68bf)

执行结束这里end_time没起作用

**Comment by whyour** [comment]
看下是不是最新镜像，运行的什么类型的任务

**Comment by Jejz168** [comment]
> 看下是不是最新镜像，运行的什么类型的任务

![IMG_6199](https://github.com/user-attachments/assets/3029c3d2-9d9a-4211-ba46-45ca58ed09ca)


运行的js，用的2.17.7镜像，但是我看显示那个说sh运行不了的，也是显示没有

**Comment by whyour** [comment]
> > 看下是不是最新镜像，运行的什么类型的任务
> 
> ![IMG_6199](https://private-user-images.githubusercontent.com/53441247/348517737-3029c3d2-9d9a-4211-ba46-45ca58ed09ca.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5Mzc0OTUsIm5iZiI6MTcyMDkzNzE5NSwicGF0aCI6Ii81MzQ0MTI0Ny8zNDg1MTc3MzctMzAyOWMzZDItOWQ5YS00MjExLWJhNDYtNDVjYTU4ZWQwOWNhLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwNjA2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDUwY2FmNzBkNmI1NzlhNjBkZDI4MTc4NjNhNjQ2OGJlZGFmNjQ3YjgxNzA4YTQyMjNlOTM3MDY0OTEyNmFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._M6YU5zemAzAggXXyOIg_id8IHJonEJUNty-VON2E6M)
> 
> 运行的js，用的2.17.7镜像，但是我看显示那个说sh运行不了的，也是显示没有

不是一个问题，升到最新版试试

**Comment by Jejz168** [comment]
> > > 看下是不是最新镜像，运行的什么类型的任务
> 
> > 
> 
> > ![IMG_6199](https://private-user-images.githubusercontent.com/53441247/348517737-3029c3d2-9d9a-4211-ba46-45ca58ed09ca.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5Mzc0OTUsIm5iZiI6MTcyMDkzNzE5NSwicGF0aCI6Ii81MzQ0MTI0Ny8zNDg1MTc3MzctMzAyOWMzZDItOWQ5YS00MjExLWJhNDYtNDVjYTU4ZWQwOWNhLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwNjA2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDUwY2FmNzBkNmI1NzlhNjBkZDI4MTc4NjNhNjQ2OGJlZGFmNjQ3YjgxNzA4YTQyMjNlOTM3MDY0OTEyNmFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._M6YU5zemAzAggXXyOIg_id8IHJonEJUNty-VON2E6M)
> 
> > 
> 
> > 运行的js，用的2.17.7镜像，但是我看显示那个说sh运行不了的，也是显示没有
> 
> 
> 
> 不是一个问题，升到最新版试试

已更新，都是重装，系统也重做的，还是没有显示时间

**Comment by Jejz168** [comment]
更新和安装依赖显示都正常，就是运行脚本那不显示

**Comment by whyour** [comment]
> 更新和安装依赖显示都正常，就是运行脚本那不显示

确保是官方镜像，空容器不添加任何内容，运行脚本管理的 ql_sample 有 end_time 吗

**Comment by Jejz168** [comment]
> > 更新和安装依赖显示都正常，就是运行脚本那不显示
> 
> 确保是官方镜像，空容器不添加任何内容，运行脚本管理的 ql_sample 有 end_time 吗

## 开始执行... 2024-07-15 20:55:32

/ql/shell/otask.sh: line 209: ql_sample: command not found

## 执行结束... 2024-07-15 20:55:32  耗时 1 秒　


重装，什么都没有，正常了。看样子是什么依赖影响的，又要怎么排除呢？
