### ISSUE TITLE
2.17.8版本，更新了变量逻辑，task_before问题

### ISSUE THREAD

**Issue by 6dylan6** [whyour/qinglong#2439]
### Qinglong version

2.17.8

### Steps to reproduce

执行脚本，task_before里处理的变量导出无效，env.sh里的及task_before里export的都不能正常js引用

### What is expected?

task_before处理的变量能正常被js引入

### What is actually happening?

不知道这是更新变量逻辑的预期效果还是bug，所以提issue

**Comment by whyour** [comment]
> 补充，刚才测试，export没问题，主要是处理好的env.sh的变量，又被env.js里的覆盖了？

这块和目前的加载逻辑有点冲突，为了防止大变量报错，直接是在 env.js 里加载变量，task_before 会对变量做删减？可能要想办法改 env.js 的变量

**Comment by whyour** [comment]
> > > 补充，刚才测试，export没问题，主要是处理好的env.sh的变量，又被env.js里的覆盖了？
> > 
> > 
> > 这块和目前的加载逻辑有点冲突，为了防止大变量报错，直接是在 env.js 里加载变量，task_before 会对变量做删减？可能要想办法改 env.js 的变量
> 
> 是的，通过task_before处理env.sh的变量，实现重新排序，禁止变量等目的，现在js使用加载env.js的变量，task_before就无法实现了。大佬看看能否好实现同步到env.js，否则只能放弃task_before另寻他法了。

可以使用 whyour/qinglong:develop 镜像试试

**Comment by whyour** [comment]
> > > > > 补充，刚才测试，export没问题，主要是处理好的env.sh的变量，又被env.js里的覆盖了？
> > > > 
> > > > 
> > > > 这块和目前的加载逻辑有点冲突，为了防止大变量报错，直接是在 env.js 里加载变量，task_before 会对变量做删减？可能要想办法改 env.js 的变量
> > > 
> > > 
> > > 是的，通过task_before处理env.sh的变量，实现重新排序，禁止变量等目的，现在js使用加载env.js的变量，task_before就无法实现了。大佬看看能否好实现同步到env.js，否则只能放弃task_before另寻他法了。
> > 
> > 
> > 可以使用 whyour/qinglong:develop 镜像试试
> 
> 可以了大佬，但发现share.sh里的变量没导入，无法引用$dir_config、$dir_scripts等变量，config.sh里的变量正常引用

whyour/qinglong:develop 镜像已更新

**Comment by whyour** [comment]
2.17.9 已修复
