### ISSUE TITLE
添加失败(Constraint error, got value 6181 expected range 0-59)

### ISSUE THREAD

**Issue by Hipple** [whyour/qinglong#244]
请教一下，自动添加定时任务失败是什么原因

开始尝试自动添加定时任务...

618主会场红包雨 -> 添加失败(Constraint error, got value 6181 expected range 0-59)

**Comment by whyour** [comment]
@Hipple 更新过了吗

**Comment by Hipple** [comment]
> @Hipple 更新过了吗

更新过了，也是不行，然后手动添加定时成功了

**Comment by whyour** [comment]
@Hipple 你这是用的私库吗

**Comment by Hipple** [comment]
@whyour 我自己建的备份库，不是私库，库里的其他脚本都添加成功了，只有这一个添加失败了

**Comment by whyour** [comment]
> @whyour 我自己建的备份库，不是私库，库里的其他脚本都添加成功了，只有这一个添加失败了

这个问题没能解决，作者改脚本上面的描述了，你更新下原作者的脚本吧，这个正则匹配比较麻烦，或者你可以直接提pr修改正则

**Comment by Hipple** [comment]
@whyour 明白，辛苦了
