### ISSUE TITLE
请求参数里面包含btc 三个字母就 503 

### ISSUE THREAD

**Issue by Char-Cp** [whyour/qinglong#2440]
### Qinglong version

last

### Steps to reproduce

请求参数里面包含btc 三个字母就 503 
![微信图片_20240717143706](https://github.com/user-attachments/assets/30dc9c4a-e512-4c40-b3be-f15893a0845c)
![微信图片_20240717143748](https://github.com/user-attachments/assets/a2489be2-2312-4975-85f6-ebe4865ff063)

### What is expected?

成功

### What is actually happening?

503

**Comment by whyour** [comment]
http://demo.ninesix.cc:4433/crontab  demo 环境无法复现，你这是服务挂了
