### ISSUE TITLE
关于消息推送设置的提交

### ISSUE THREAD

**Issue by WB967** [whyour/qinglong#2441]
### Qinglong version

 正式版 v2.17.8

### Steps to reproduce

。

### What is expected?

。

### What is actually happening?

大佬您好，我是使用pushplus进行消息推送的，前段时间一直正常，然后添加了jd账号(目前就两个)，消息推送就异常了。查看任务日志显示Push+ 发送一对一通知消息失败(共提示两次)。由于我是两个账号，我想都发给我。
然后我更换了pushplus的token，在配置文件中更换的。问题依旧存在。
我又在设置中进行填写，发现接口(api/user/notification)报500，错误信息为超时，无法保存成功。

但是又有个别任务完成的消息会推送过来。

**Comment by whyour** [comment]
超时可能是网络问题
