### ISSUE TITLE
最新版的环境变量不生效。添加不到sys.path中

### ISSUE THREAD

**Issue by Char-Cp** [whyour/qinglong#2443]
### Qinglong version

正式版 v2.17.8

### Steps to reproduce

我在环境变量里面配置了，但是项目里面识别不了。
![WeChate5a61a21b6282fb4b048e83e85438bc5](https://github.com/user-attachments/assets/283b6ae1-72a6-437f-8824-2f24741355e5)
![WeChatae3d844aac593f0ea119a389b7587725](https://github.com/user-attachments/assets/d98b48a3-870c-48f0-80f5-730129e645d9)
![WeChatc5202332ba05b89a4065a9f25718a0ef](https://github.com/user-attachments/assets/77aa4f05-d3d6-48f6-953f-6b7ebd3e81d8)

### What is expected?

可以sys.path 中有‘/ql/data/scripts/py’

### What is actually happening?

没有

**Comment by Char-Cp** [comment]
测试环境复现。
![WeChat227fb586e5f4d90a30f46f2991810de6](https://github.com/user-attachments/assets/6a935260-c459-4e6f-82a5-6bd626ba648c)

**Comment by Char-Cp** [comment]
我在测试环境复现了。

**Comment by Char-Cp** [comment]
我在测试环境复现了。 
![WeChat7b5d87d7159d7b7595814bceca3d8e58](https://github.com/user-attachments/assets/91b45ff6-f824-417c-bd2a-d5d1e7665316)

**Comment by whyour** [comment]
@Char-Cp 加到配置文件 config 里

**Comment by Char-Cp** [comment]
ok 可以了 谢谢

**Comment by Char-Cp** [comment]
ok 可以了 谢谢
