### ISSUE TITLE
华为云debian11安装依赖全部失败，修改pnpm源地址后还是有部分依赖失败

### ISSUE THREAD

**Issue by longhao1987** [whyour/qinglong#2444]
### Qinglong version

docker 最新版本

### Steps to reproduce

使用这个docker命令运行：docker run -dit \
  -v $PWD/ql/data:/ql/data \
  -p 5700:5700 \
  --name qinglonghost \
  --network host \
  --restart unless-stopped \
  whyour/qinglong:latest

安装依赖失败后会停止安装依赖，最终得到的青龙面板如下，不是最新版本，且无法更新
![image](https://github.com/user-attachments/assets/711ed45d-af38-4521-966a-9dc0d86b91cf)

### What is expected?

正常安装

### What is actually happening?

![image](https://github.com/user-attachments/assets/b229f550-93d7-48cf-b7aa-81c0f608b8cd)

?WARN? GET https://registry.npmjs.org/@ant-design%2Ficons error (ERR_SOCKET_TIMEOUT). Will retry in 1 minute. 1 retries left.
?WARN? GET https://registry.npmjs.org/@types%2Fmulter error (ERR_SOCKET_TIMEOUT). Will retry in 1 minute. 1 retries left.
?WARN? GET https://registry.npmjs.org/@types%2Fcors error (ERR_SOCKET_TIMEOUT). Will retry in 1 minute. 1 retries left.
?WARN? GET https://registry.npmjs.org/@sentry%2Freact error (ERR_SOCKET_TIMEOUT). Will retry in 1 minute. 1 retries left.
?WARN? GET https://registry.npmjs.org/@types%2Fnode error (ERR_SOCKET_TIMEOUT). Will retry in 1 minute. 1 retries left.
?ERR_PNPM_META_FETCH_FAIL? GET https://registry.npmjs.org/@ant-design%2Ficons: request to https://registry.npmjs.org/@ant-design%2Ficons failed, reason: Socket timeout
?ERR_PNPM_META_FETCH_FAIL? GET https://registry.npmjs.org/@types%2Fbody-parser: request to https://registry.npmjs.org/@types%2Fbody-parser failed, reason: Socket timeout
?ERR_PNPM_META_FETCH_FAIL? GET https://registry.npmjs.org/@react-hook%2Fresize-observer: request to https://registry.npmjs.org/@react-hook%2Fresize-observer failed, reason: Socket timeout

### System Info

```shell
Linux hcss-ecs-e0ac 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux
```

**Comment by whyour** [comment]
修改镜像源，或者拉取指定版本，如图配置 npm 源，依赖管理安装依赖

<img width="941" alt="image" src="https://github.com/user-attachments/assets/5212dffd-420f-4b78-a1fe-aced7dd8bf53">

**Comment by longhao1987** [comment]
> 修改镜像源，或者拉取指定版本，如图配置 npm 源，依赖管理安装依赖
> 
> <img alt="image" width="941" src="https://private-user-images.githubusercontent.com/22700758/351361501-5212dffd-420f-4b78-a1fe-aced7dd8bf53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDUxMTQsIm5iZiI6MTcyMTc0NDgxNCwicGF0aCI6Ii8yMjcwMDc1OC8zNTEzNjE1MDEtNTIxMmRmZmQtNDIwZi00Yjc4LWExZmUtYWNlZDdkZDhiZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE0MjY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZmI2YzYwNGVjN2Y1ZTRlZDRjNzk1MzNkMjlkZGQ5ZGQ2ODZhYWU3MDM1NjA2MzhhOWRlMTQ2M2E4ZmZjNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KUf3hibfMa329vq5L2JuhTBtvYZg0KjvV90yEzKtZR0">
。。。。我已经经修改了npm镜像源为[https://registry.npmjs.org](https://registry.npmjs.org，然后重新执行pnpm install也还有部分依赖 失败，重新install后面板还是无法更新版本。。。docker拉取指定版本总是失败，我刚刚尝试拉取whyour/qinglong:2.17.8失败，debian是开了代理的，也还是无法拉取，还有在2.10.12版本中的设置中不存在你图中的依赖管理。
![image](https://github.com/user-attachments/assets/bd4b73b1-d78a-4529-baaa-5e5138efaeb4)

**Comment by longhao1987** [comment]
> @longhao1987 参考 https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6
昨天没看到，，，不过也是这个问题，docker被屏蔽了，换了个俄罗斯的源才拉到你最新的镜像
