### ISSUE TITLE
Windows版本docker，拉取latest版本为10.13，强制升级至最新版本会自动回退至2.10.13

### ISSUE THREAD

**Issue by SCARS0314** [whyour/qinglong#2445]
### Qinglong version

2.17.9

### Steps to reproduce

Windows版本docker，拉取镜像安装版本为2.10.13，强制更新后变为2.17.9，可以正常使用，但几个小时就自己回退到了2.10.13，定时任务都消失了，在设置里强制升级后又返回到了2.17.9，定时任务又重新出现

### What is expected?

请问下是安装问题还是bug，怎么解决？

### What is actually happening?

请问下是安装问题还是bug，怎么解决？

**Comment by whyour** [comment]
镜像源有问题，参考 https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6

**Comment by whyour** [comment]
@SCARS0314 问题是你删了原有的也拉不到最新的镜像，跟系统内的更新没关心。确保你镜像是最新的就行

**Comment by SCARS0314** [comment]
> @SCARS0314 问题是你删了原有的也拉不到最新的镜像，跟系统内的更新没关心。确保你镜像是最新的就行

奥奥，谢谢，那我尝试下那个项目里的镜像源，然后重新拉一下，确定能拉到最新版就算解决了是吧

**Comment by whyour** [comment]
> > @SCARS0314 问题是你删了原有的也拉不到最新的镜像，跟系统内的更新没关心。确保你镜像是最新的就行
> 
> 奥奥，谢谢，那我尝试下那个项目里的镜像源，然后重新拉一下，确定能拉到最新版就算解决了是吧

是的

**Comment by SCARS0314** [comment]
@whyour 换了镜像源，重新部署了下，是最新版，原有的配置都还在，谢谢~~~
