### ISSUE TITLE
canvas无法安装

### ISSUE THREAD

**Issue by ginstt** [whyour/qinglong#2448]
### Qinglong version

V2.11.3

### Steps to reproduce

开始安装依赖 canvas，开始时间 2024/7/27 15:57:46
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/canvas/
ERROR: Could not find a version that satisfies the requirement canvas
ERROR: No matching distribution found for canvas
依赖安装失败，结束时间 2024/7/27 15:58:51，耗时 64.957 秒

开始安装依赖 canvas，开始时间 2024/7/27 15:59:26
ERROR: Could not find a version that satisfies the requirement canvas
ERROR: No matching distribution found for canvas
依赖安装失败，结束时间 2024/7/27 15:59:32，耗时 6.639 秒

### What is expected?

我要运行一个脚本必须要有这个依赖

### What is actually happening?

无法安装这个python3 的canvas

### System Info

```shell
Linux		
1	bizCode	已安装
2	bizMsg	已安装
3	lxm	已安装
4	build-base	已安装
5	pkgconfig	已安装
6	pixman-dev	已安装
7	cairo-dev	已安装
8	pango-dev	已安装
9	make	已安装
10	g++	已安装
11	libc-dev	已安装
12	python3-dev	已安装
13	gcc	已安装
14	musl-dev	已安装
15	libffi	已安装
16	libffi-dev	已安装
17	openssl	已安装
18	openssl-dev	已安装
19	py-pip	已安装
20	mysql-dev	已安装
21	linux-headers	已安装
22	pixman	已安装
23	jpeg-dev	已安装
24	giflib-dev	已安装
25	rust	已安装
26	cargo	已安装
27	alpine-sdk	已安装
28	autoconf	已安装
29	automake	已安装
30	libtool	已安装
```

**Comment by whyour** [comment]
参考 https://github.com/whyour/qinglong/issues/2294#issue-2158343532
