### ISSUE TITLE
v2.17.9似乎会覆盖任务执行前的环境变量

### ISSUE THREAD

**Issue by tttsss-01** [whyour/qinglong#2449]
### Clear and concise description of the problem

我之前是在“执行前“这样设置通知的
![屏幕截图 2024-07-27 174305](https://github.com/user-attachments/assets/d30637b8-c494-4f48-b3b8-23eac987e1c7)
但v2.17.9中，脚本执行时，这两个通知的变量会被覆盖，没有设置通知（我在其他地方不设置这两个变量）。
在之前的版本中，这样的设置是有效的。

### Suggested solution

因为我有多个任务要发往不同的钉钉，所以我这样设置。是否有其他方式，或者可以让这样的设置重新生效。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
看下镜像是不是最新的，还有日志里执行任务前有没有报错

**Comment by tttsss-01** [comment]
> Owner

镜像是最新的，日志是这样的。
![屏幕截图 2024-07-27 232041](https://github.com/user-attachments/assets/a5f0618d-5635-4aba-a0b9-c8a06bf8c94a)

我还尝试了在环境变量中设置，那样是能生效的，就是执行前里export的不行

**Comment by whyour** [comment]
已修复，更新下镜像

**Comment by whyour** [comment]
> > Owner
> 
> 镜像是最新的，日志是这样的。 ![屏幕截图 2024-07-27 232041](https://private-user-images.githubusercontent.com/110894574/352761823-a5f0618d-5635-4aba-a0b9-c8a06bf8c94a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjQ0MDksIm5iZiI6MTcyMjE2NDEwOSwicGF0aCI6Ii8xMTA4OTQ1NzQvMzUyNzYxODIzLWE1ZjA2MThkLTU2MzUtNGFiYS1hMGI5LWM4YTA2YmY4Yzk0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMDU1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjczYTdkMTBlZTZjOTEwZGI0ZmEzMTQzMmVmY2RmMzJiZGY3OTAxMTk3NzFhNjFkZjA4OTc3NzRhYzM3NTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jBL_htt7xUeTZcn3a95-NUgUOcIw32j7w4WGjO1GWjo)
> 
> 我还尝试了在环境变量中设置，那样是能生效的，就是执行前里export的不行

你这是用 QLAPI.notify 进行通知的？

**Comment by tttsss-01** [comment]
我调用notify.py里的，现在可以了，谢谢大佬

**Comment by tttsss-01** [comment]
大佬，我发现RandomDelay还是不能正常生效

**Comment by whyour** [comment]
@tttsss-01 怎么个不能正常

**Comment by tttsss-01** [comment]
> @tttsss-01 怎么个不能正常

执行前 export RandomDelay=30 没有生效，应该是被默认的RandomDelay="" 覆盖了。此外，在环境变量里创建变量RandomDelay=30也不会生效。

**Comment by whyour** [comment]
@tttsss-01 这时候配置这个太晚了，都要执行脚本了，可以在执行前使用 sleep 10 进行延迟
