### ISSUE TITLE
自动重启，感觉像启动不起来，日志如下

### ISSUE THREAD

**Issue by cjh19831115** [whyour/qinglong#245]
Use --update-env to update environment variables

[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])

[PM2][ERROR] Process 0 not found

**Comment by whyour** [comment]
什么环境，执行下  ql update 呢

**Comment by cjh19831115** [comment]
重启了几次，突然要更新bot依赖，更新完就好了
