### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by mengy822** [whyour/qinglong#2450]
### Qinglong version

2.17.8

### Steps to reproduce

重启后内存大概在77mb左右，随着时间推移大概在第十天内存占用到达3gb，top查看进程发现大量python任务（这些任务实际已经执行完了）在占用

### What is expected?

任务结束后释放内存

### What is actually happening?

内存未释放

**Comment by whyour** [comment]
脚本未正常结束，建议增加任务超时时间
 task -m 10s xxx.py
