### ISSUE TITLE
replace fs operation with fs-extra

### ISSUE THREAD

**Issue by gweesin** [whyour/qinglong#2451]
### Clear and concise description of the problem

I noticed that utils have lots of methods could be replaced by fs-extra to improve readability and performance.

- [x] I'm willing to work for this.

### Suggested solution

replace operating file system with fs-extra

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
fs-extra has no significant performance optimization, and I don't think it's necessary
