### ISSUE TITLE
容器内特定域名ping不通,建议涉及到alpine 使用旧版本3.12

### ISSUE THREAD

**Issue by zjk2017** [whyour/qinglong#2452]
### Clear and concise description of the problem

版本3.10 alpine 版本 
容器内特定域名 bad address 例如
 bad address 'cmallapi.haday.cn'

### Suggested solution

查看容器的 alpine 版本
cat /etc/alpine-release
3.20.0
最后发现是 alpine 版本的问题
alpine 3.13, 3.14, 3.15 3.20 的版本 dns 解析都有问题，官方一直没处理

只能回滚 alpine 版本，用 alpine 3.12 版本

建议涉及到alpine 使用旧版本3.12

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
repeat https://github.com/whyour/qinglong/issues/2452

**Comment by hkxiaoyao** [comment]
@zjk2017 大佬，请问一下，如何回滚呀
