### ISSUE TITLE
nodejs依赖无法安装

### ISSUE THREAD

**Issue by adnogpu** [whyour/qinglong#2453]
### Qinglong version

2.17.9

### Steps to reproduce

![image](https://github.com/user-attachments/assets/e2f91c13-52e9-4ad6-8aa3-e7dcefa38fbb)
![image](https://github.com/user-attachments/assets/48058ca5-1495-485c-8bd2-92121e8474ae)
开始安装依赖 cjs，开始时间 2024-08-02 16:32:24

 ERROR  The configured global bin directory "/root/.local/share/pnpm" is not in PATH
For help, run: pnpm help add

依赖安装失败，结束时间 2024-08-02 16:32:27，耗时 2 秒

### What is expected?

安装依赖

### What is actually happening?

安装失败

开始安装依赖 cjs，开始时间 2024-08-02 16:32:24

 ERROR  The configured global bin directory "/root/.local/share/pnpm" is not in PATH
For help, run: pnpm help add

依赖安装失败，结束时间 2024-08-02 16:32:27，耗时 2 秒

### System Info

```shell
![image](https://github.com/user-attachments/assets/e2f91c13-52e9-4ad6-8aa3-e7dcefa38fbb)
![image](https://github.com/user-attachments/assets/48058ca5-1495-485c-8bd2-92121e8474ae)
开始安装依赖 cjs，开始时间 2024-08-02 16:32:24

 ERROR  The configured global bin directory "/root/.local/share/pnpm" is not in PATH
For help, run: pnpm help add

依赖安装失败，结束时间 2024-08-02 16:32:27，耗时 2 秒
```

**Comment by whyour** [comment]
删除容器，用最新镜像重建吧，看不出来你的环境有什么问题

**Comment by adnogpu** [comment]
> 删除容器，用最新镜像重建吧，看不出来你的环境有什么问题

感谢重新拉取了最新镜像可以正常安装了
