### ISSUE TITLE
随机延迟运行任务不生效

### ISSUE THREAD

**Issue by pooneyy** [whyour/qinglong#2458]
### Qinglong version

正式版 v2.17.9

### Steps to reproduce

config.sh
```sh
RandomDelay="3600"
RandomDelayFileExtensions=""
RandomDelayIgnoredMinutes=""
```

![image](https://github.com/user-attachments/assets/e37f7ba7-edf9-470c-9570-e6eba6144404)

![image](https://github.com/user-attachments/assets/72fd3580-0032-4a33-a211-9ed6e83bf9c0)

脚本里运行的是我自己编译的可执行文件，发现设置`RandomDelay`后随机延迟不生效

### What is expected?

希望任务随机延迟至多3600秒开始运行

### What is actually happening?

任务需要运行的可执行文件没有后缀名

当前设置了`RandomDelay="3600"`，且`RandomDelayFileExtensions=""`为空，任务准时运行

**Comment by whyour** [comment]
没有后缀识别不了，你在任务执行前加随机延迟，或者自己脚本实现随机延迟
