### ISSUE TITLE
python脚本在调用QLAPI的时候无法发送邮件通知，原因可能是config.sh文件中的SMTP_SERVER和SMTP_SERVICE 这两个变量写错了，或者是notify.py读取环境变量时没有读到SMTP_SSL这些变量

### ISSUE THREAD

**Issue by chunhai24** [whyour/qinglong#2459]
### Qinglong version

2.17.9

### Steps to reproduce

我自己修改python脚本向用邮件通知，一直失败，反复检查调试，发现可能是notify.py里边SMTP_***的名称写错了导致读取变量失败，我在docker容器中看到的代码其中某一个位置用的SMTP_SERVICE,但是我在github上发现都是用的SMTP_SERVER。也许是不是应该更新一下docker的镜像了
![image](https://github.com/user-attachments/assets/38713da0-8ee4-4fae-9d21-6cc7ecebfeff)
![image](https://github.com/user-attachments/assets/f49f858c-dccb-4ebe-a88f-ff58f9120e7f)
![image](https://github.com/user-attachments/assets/2dc8b853-ea7b-4f0e-a4ad-17623c5cfc23)

### What is expected?

希望能够稳定发送邮件通知

### What is actually happening?

无法发送

**Comment by whyour** [comment]
<img width="994" alt="image" src="https://github.com/user-attachments/assets/6fbf2e22-4631-467b-af2a-a8badfeaac28">
python 脚本和 JavaScript 脚本参数不一样
