### ISSUE TITLE
准点运行设置了无效

### ISSUE THREAD

**Issue by darkelf123** [whyour/qinglong#2462]
### Qinglong version

2.17.4

### Steps to reproduce

在config里设置了RandomDelay="300"
同时设置RandomDelayIgnoredMinutes="00,30"
但是js脚本在0分和30分准点的时候运行还是会添加一个随机延迟，这是为什么啊

### What is expected?

能准点运行

### What is actually happening?

按照说明添加了设置但貌似没有效果

**Comment by whyour** [comment]
RandomDelayIgnoredMinutes="0 30"

**Comment by darkelf123** [comment]
> RandomDelayIgnoredMinutes="0 30"

谢谢指导
