### ISSUE TITLE
任务无法正常结束

### ISSUE THREAD

**Issue by pooneyy** [whyour/qinglong#2463]
### Qinglong version

v2.17.9

### Steps to reproduce

运行完毕任务后显示`/ql/shell/share.sh: line 464: task_after: unbound variable`
![image](https://github.com/user-attachments/assets/3249ce77-380a-47c3-a89b-125b0cb6d572)

但是任务并没有设置执行后的脚本
![image](https://github.com/user-attachments/assets/c4847f19-8efb-4f22-aaac-20d5725aeb9c)

### What is expected?

怎样才能让任务正常结束呢？

### What is actually happening?

运行完毕任务后显示`/ql/shell/share.sh: line 464: task_after: unbound variable`，无法正常结束

**Comment by xiaobei206** [comment]
我也遇到了，怎么解决呢？

**Comment by whyour** [comment]
2.17.10 已修复
