### ISSUE TITLE
2.17.6无法升级

### ISSUE THREAD

**Issue by formyangel1219** [whyour/qinglong#2465]
### Qinglong version

2.17.6

### Steps to reproduce

2.17.6 在系统设置中更新，下载更新，提示最新版本2.17.9，点击更新，下载完成后提示重启，点击后无响应，自动跳转到任务页，更新失败
点击重启也无效

### What is expected?

版本更新

### What is actually happening?

更新失败

### System Info

```shell
拾光坞NAS，无docker命令行
```

**Comment by formyangel1219** [comment]
下载更新中...
## 开始执行... 2024-08-13 11:25:00

使用 gitee 源更新...

更新青龙源文件成功...

更新青龙静态资源成功...


开始检测依赖...

安装 /ql/.tmp/qinglong-master 依赖包...

Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm

dependencies:
+ @grpc/grpc-js 1.8.15
+ @otplib/preset-default 12.0.1
+ @sentry/node 7.54.0
+ body-parser 1.20.2
+ celebrate 15.0.1
+ chokidar 3.5.3
+ cors 2.8.5
+ cron-parser 4.8.1
+ cross-spawn 7.0.3
+ dayjs 1.11.8
+ dotenv 16.1.4
+ express 4.18.2
+ express-jwt 6.1.2
+ express-rate-limit 7.0.0
+ express-urlrewrite 1.4.0
+ form-data 4.0.0
+ got 11.8.6
+ hpagent 1.2.0
+ http-proxy-middleware 2.0.6
+ iconv-lite 0.6.3
+ ip2region 2.3.0
+ js-yaml 4.1.0
+ jsonwebtoken 8.5.1
+ lodash 4.17.21
+ multer 1.4.5-lts.1
+ nedb 1.8.0
+ node-schedule 2.1.1
+ nodemailer 6.9.3
+ p-queue-cjs 7.3.4
+ protobufjs 7.3.0
+ pstree.remy 1.1.8
+ reflect-metadata 0.1.13
+ request-ip 3.3.0
+ sequelize 6.32.0
+ serve-handler 6.1.5
+ sockjs 0.3.24
+ sqlite3 <- @whyour/sqlite3 1.0.3
+ toad-scheduler 1.6.1
+ tough-cookie 4.0.0
+ typedi 0.10.0
+ uuid 8.3.2
+ winston 3.9.0
+ winston-daily-rotate-file 4.7.1
+ yargs 17.7.2

devDependencies: skipped


> @ postinstall /ql/.tmp/qinglong-master
> max setup 2>/dev/null || true

Done in 37.2s

依赖检测安装成功...

更新包下载成功...

## 执行结束... 2024-08-13 11:25:56 耗时 56 秒　　　　　

然后弹出重启的框，点击跳转到任务列表，没法更新。

**Comment by whyour** [comment]
使用 docker 更新镜像的方式更新下

**Comment by whyour** [comment]
录个视频看看？

**Comment by formyangel1219** [comment]
已经解决了， 删除整个docker，换成初始的2.16.0，再执行更新，就是最新的了
