### ISSUE TITLE
拒绝一些py工具文件自动生成定时任务

### ISSUE THREAD

**Issue by guicaiyue** [whyour/qinglong#2467]
### Clear and concise description of the problem

我现在有一个自己的库，库里是python脚本，有些脚本需要库更新时自动加载任务，有些不用，是工具，但库更新时会自动加任务了，怎么配置这种py文件不加载任务，就像需要加任务时如下配置一样
/**
 * 任务名称
 * name: script name
 * 定时规则
 * cron: 1 9 * * *
 */

### Suggested solution

在开头注释中，像如下一样支持配置
/**
 * 任务名称
 * name: script name
 * 定时规则
 * cron: 1 9 * * *
 */

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
订阅里增加黑名单 a.py|b.py，不匹配包含 a 或者 b 的文件

**Comment by guicaiyue** [comment]
> 订阅里增加黑名单 a.py|b.py，不匹配包含 a 或者 b 的文件

不行，效果不对，我只是不想这个工具类被当成定时任务被加载，而不是不要这个工具类文件，这么配置后，我在脚本管理里面，发现这个文件都没有了，这个工具类也就不能通过面板测试了

**Comment by whyour** [comment]
@guicaiyue 依赖可以加到依赖文件的配置里，和黑名单配置一样

**Comment by guicaiyue** [comment]
![image](https://github.com/user-attachments/assets/3b2fdfca-0182-4e24-8184-dfc87184cb8b)
![image](https://github.com/user-attachments/assets/d7485260-902c-402c-a661-408f2b02e6ec)


> @guicaiyue 依赖可以加到依赖文件的配置里，和黑名单配置一样

试了下依赖参数，这个参数没效果，我加了也不会删自己编写的工具类生成的定时任务，我删了这些错误的定时任务，重新拉去，也会继续创建定时任务，做不到我想要脚本管理有这个文件，但定时任务不会有这个文件任务

**Comment by roiding** [comment]
必须得放到单独的文件夹下嘛？

**Comment by roiding** [comment]
> [@guicaiyue](https://github.com/guicaiyue) 黑名单和依赖文件同时用啊，不用加斜杠

貌似你这个意味着就是utils不是单独的文件夹咯
