### ISSUE TITLE
更新面板失败

### ISSUE THREAD

**Issue by HIMHERO** [whyour/qinglong#247]
Fetching origin
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': SSL certificate problem: certificate is not yet valid
error: Could not fetch origin
HEAD is now at b2454a5 修复config sample
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': SSL certificate problem: certificate is not yet valid

使用docker exec -it qinglong ql update命令更新提示如上错误.
pve虚拟机+op的dockerman

**Comment by whyour** [comment]
再运行几次呢，是每次都失败吗

**Comment by HIMHERO** [comment]
感谢大佬的回复，刚刚又试了一次，成功了，也没有出现面板打开白屏的情况。还没来得及删掉这条

**Comment by HIMHERO** [comment]
更新成功了
