### ISSUE TITLE
修改依赖设置提示System {"type":"systemConfig"} not found

### ISSUE THREAD

**Issue by nianqing126** [whyour/qinglong#2472]
### Qinglong version

2.17.9

### Steps to reproduce

系统设置--依赖设置，输入软件源地址后点击确认会出现浮动提示System {"type":"systemConfig"} not found  ，同时右侧提示in progress...
update mirror error

### What is expected?

影响修改软件源

### What is actually happening?

影响修改软件源

**Comment by whyour** [comment]
其他设置里 点下重新启动

**Comment by nianqing126** [comment]
> 其他设置里 点下重新启动
没用的，但是原因我已经找到了。因为我改了ver/lib/docker，因为盒子存储太小，直接吧优盘mount成了ver/lib/docker，如果不改就没事

**Comment by s1sunny** [comment]
老版本没有这个问题，盒子自带容量小，挂载docker到外置硬盘是必要的，如何解决呢？

**Comment by s1sunny** [comment]
重启了一下面板，好了。

**Comment by Tiande** [comment]
> 其他设置里 点下重新启动

有用👍
