### ISSUE TITLE
未找到认证文件，重新初始化

### ISSUE THREAD

**Issue by muzidaishua** [whyour/qinglong#2473]
### Qinglong version

1

### Steps to reproduce

![0064982d051cf2704f732c7d30837b4](https://github.com/user-attachments/assets/fb0c1cb4-c6f4-4337-a278-81d1de95a0d2)
日志报错：crond[166]:user root:parse error at 7
请问该问题如何解决，日志中目前脚本正常运行，打开IP登陆时需要重新初始化配置

### What is expected?

1

### What is actually happening?

1

**Comment by whyour** [comment]
说明版本，看映射目录对不对，使用 pc 浏览器试试，app 不是官方的
