### ISSUE TITLE
2.17.5版本的通知文件如何更新

### ISSUE THREAD

**Issue by inoyna12** [whyour/qinglong#2475]
### Qinglong version

2.17.9

### Steps to reproduce

我在2.17.5版本中使用了系统设置里的备份，然后在2.17.9版本中恢复了备份

### What is expected?

修复一下

### What is actually happening?

订阅仓库后目录下生成的notify.py文件还是2.17.5版本里的，后来我尝试去修改这个文件，但是每次更新订阅后通知文件又恢复成原样。

**Comment by inoyna12** [comment]
最外层的通知文件已经是最新了
我录了个视频，最外层的通知文件33.9kb，仓库目录的通知文件31.6kb，我删了仓库目录的文件，然后在订阅管理那又重新生成，结果还是31.6kb
https://file.uhsea.com/2408/8584e190fc222d30b9f18b0d41ae8b6bXT.mp4

**Comment by whyour** [comment]
@inoyna12 把订阅的通知文件依赖去掉，你用的仓库内的通知文件

**Comment by inoyna12** [comment]
我如果用了仓库的通知文件就不会发这个issue了，你能复现这个问题吗   不能的话我就重新装面板了，暂时就不用备份功能了

**Comment by inoyna12** [comment]
![Screenshot_2024-08-20-10-05-02-551_mark via](https://github.com/user-attachments/assets/ec23e8f4-7a6b-4349-bc40-5f51567a66a4)

**Comment by whyour** [comment]
@inoyna12 你 data 目录是不是有 deps 目录，把里面的通知文件删了

**Comment by inoyna12** [comment]
ok了老铁
