### ISSUE TITLE
添加QlBaseUrl="/"参数无法访问

### ISSUE THREAD

**Issue by tinyhugh** [whyour/qinglong#2480]
### Qinglong version

2.17.9

### Steps to reproduce

在docker容器添加QlBaseUrl="/ql/"参数无法访问，打开页面会显示nginx的欢迎页

### What is expected?

正常访问

### What is actually happening?

其他页面

**Comment by whyour** [comment]
访问的时候也要是 ip+port+/ql

**Comment by tinyhugh** [comment]
> 访问的时候也要是 ip+port+/ql

用这种方式访问的时候是404 Not Found  nginx

**Comment by tinyhugh** [comment]
QL_DIR=/ql
QL_BRANCH=master
QlBaseUrl="/ql/"
目前参数配置有这些内容，通过 ip:5700/ql/ 访问是404错误，通过 域名/ql/ 访问时nginx欢迎页（已经设置好/ql/二级目录反代），通过 ip:5700 访问也是nginx欢迎页。

**Comment by whyour** [comment]
参数配置是在哪配置的？QlBaseUrl 这个参数是容器启动的时候给的

**Comment by tinyhugh** [comment]
参数配置就是docker容器的环境变量，我用的是1panel面板，下面是完整的配置
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules:
LANG=C.UTF-8
NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules
SHELL=/bin/bash
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
PYTHON_VERSION=3.11.9
PYTHON_PIP_VERSION=24.0
PYTHON_SETUPTOOLS_VERSION=65.5.1
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/e03e1607ad60522cf34a92e834138eb89f57667c/public/get-pip.py
PYTHON_GET_PIP_SHA256=ee09098395e42eb1f82ef4acb231a767a6ae85504a9cf9983223df0a7cbd35d7
PNPM_HOME=/root/.local/share/pnpm
PS1=\u@\h:\w $ 
QL_DIR=/ql
QL_BRANCH=master
QlBaseUrl="/ql/"

**Comment by tinyhugh** [comment]
> 参数配置是在哪配置的？QlBaseUrl 这个参数是容器启动的时候给的 https://github.com/whyour/qinglong?tab=readme-ov-file#docker-%E6%8E%A8%E8%8D%90

参数配置就是docker容器的环境变量，我用的是1panel面板，下面是完整的配置
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules:
LANG=C.UTF-8
NODE_PATH=/usr/local/bin:/usr/local/pnpm-global/5/node_modules:/usr/local/lib/node_modules:/root/.local/share/pnpm/global/5/node_modules
SHELL=/bin/bash
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
PYTHON_VERSION=3.11.9
PYTHON_PIP_VERSION=24.0
PYTHON_SETUPTOOLS_VERSION=65.5.1
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/e03e1607ad60522cf34a92e834138eb89f57667c/public/get-pip.py
PYTHON_GET_PIP_SHA256=ee09098395e42eb1f82ef4acb231a767a6ae85504a9cf9983223df0a7cbd35d7
PNPM_HOME=/root/.local/share/pnpm
PS1=\u@\h:\w $
QL_DIR=/ql
QL_BRANCH=master
QlBaseUrl="/ql/"

**Comment by whyour** [comment]
@tinyhugh 为什么 baseurl 多两个引号

**Comment by tinyhugh** [comment]
> @tinyhugh 为什么 baseurl 多两个引号

我看更新日志里提到是用这种格式

**Comment by whyour** [comment]
> > @tinyhugh 为什么 baseurl 多两个引号
> 
> 我看更新日志里提到是用这种格式

面板填的时候，应该是不需要引号
