### ISSUE TITLE
2.17.9 无法启动

### ISSUE THREAD

**Issue by zuozihan** [whyour/qinglong#2483]
### Qinglong version

2.17.9

### Steps to reproduce

pm2 logs日志报错，无法启动

### What is expected?

/root/.pm2/logs/panel-error.log last 15 lines:
3|panel    | 2024-08-30T16:36:26:   sql: 'UPDATE `Crontabs` SET `status`=$1,`updatedAt`=$2',
3|panel    | 2024-08-30T16:36:26:   parameters: {}
3|panel    | 2024-08-30T16:36:26: }
3|panel    | 2024-08-30T16:36:26: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
3|panel    | 2024-08-30T16:36:26: Error:
3|panel    | 2024-08-30T16:36:26:     at Database.<anonymous> (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/sqlite/query.js:236:27)
3|panel    | 2024-08-30T16:36:26:     at /ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/sqlite/query.js:234:50
3|panel    | 2024-08-30T16:36:26:     at new Promise (<anonymous>)
3|panel    | 2024-08-30T16:36:26:     at Query.run (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/sqlite/query.js:234:12)
3|panel    | 2024-08-30T16:36:26:     at /ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/sequelize.js:650:28
3|panel    | 2024-08-30T16:36:26:     at SQLiteQueryInterface.bulkUpdate (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/abstract/query-interface.js:930:12)
3|panel    | 2024-08-30T16:36:26:     at Function.update (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/model.js:3351:28)
3|panel    | 2024-08-30T16:36:26:     at exports.default (/ql/back/loaders/initData.ts:84:3)
3|panel    | 2024-08-30T16:36:26:     at Object.exports.default (/ql/back/loaders/app.ts:14:3)
3|panel    | 2024-08-30T16:36:26:     at startServer (/ql/back/app.ts:15:3)

### What is actually happening?

请帮我解决下

**Comment by whyour** [comment]
把这个文件发下 /root/.pm2/logs/panel-error.log

**Comment by BenMake** [comment]
无法启动+1

/ql $pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2024-09-02T17:01:03: PM2 log: App [schedule:1] starting in -fork mode-
PM2        | 2024-09-02T17:01:03: PM2 log: App [public:2] starting in -fork mode-
PM2        | 2024-09-02T17:01:13: PM2 log: App [schedule:1] online
PM2        | 2024-09-02T17:01:13: PM2 log: App [public:2] online
PM2        | 2024-09-02T17:01:13: PM2 log: App [panel:3] starting in -fork mode-
PM2        | 2024-09-02T17:01:24: PM2 log: App [panel:3] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/update-error.log last 15 lines:
/root/.pm2/logs/update-out.log last 15 lines:
0|update   | 2024-09-02T17:01:07: ✌️ 更新服务启动成功！

/root/.pm2/logs/schedule-out.log last 15 lines:
1|schedule | 2024-05-09T10:11:34: ✌️ 定时服务启动成功！
1|schedule | 2024-07-07T17:39:59: ✌️ 定时服务启动成功！
1|schedule | 2024-07-08T00:46:57: ✌️ 定时服务启动成功！
1|schedule | 2024-07-11T00:58:41: ✌️ 定时服务启动成功！
1|schedule | 2024-07-24T09:04:57: ✌️ 定时服务启动成功！
1|schedule | 2024-08-22T10:32:32: ✌️ 定时服务启动成功！
1|schedule | 2024-09-02T16:27:45: ✌️ 定时服务启动成功！
1|schedule | 2024-09-02T16:58:11: ✌️ 定时服务启动成功！
1|schedule | 2024-09-02T17:01:36: ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
2|public   | 2024-07-11T00:58:39: ✌️ Sentry loaded
2|public   | 2024-07-11T00:58:52: ✌️ DB loaded
2|public   | 2024-07-11T00:58:52: ✌️ 公共服务启动成功！
2|public   | 2024-07-24T09:04:50: ✌️ Sentry loaded
2|public   | 2024-07-24T09:05:09: ✌️ DB loaded
2|public   | 2024-07-24T09:05:09: ✌️ 公共服务启动成功！
2|public   | 2024-08-22T10:32:29: ✌️ Sentry loaded
2|public   | 2024-08-22T10:32:42: ✌️ DB loaded
2|public   | 2024-08-22T10:32:42: ✌️ 公共服务启动成功！
2|public   | 2024-09-02T16:27:48: ✌️ DB loaded
2|public   | 2024-09-02T16:27:48: ✌️ 公共服务启动成功！
2|public   | 2024-09-02T16:58:10: ✌️ DB loaded
2|public   | 2024-09-02T16:58:10: ✌️ 公共服务启动成功！
2|public   | 2024-09-02T17:01:42: ✌️ DB loaded
2|public   | 2024-09-02T17:01:42: ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
3|panel    | 2024-09-02T16:28:08: ✌️ Init task loaded
3|panel    | 2024-09-02T16:58:00: ✌️ Sentry loaded
3|panel    | 2024-09-02T16:58:18: ✌️ DB loaded
3|panel    | 2024-09-02T16:58:19: ✌️ Init file down
3|panel    | 2024-09-02T16:58:33: ✌️ Dependency loaded
3|panel    | 2024-09-02T16:58:36: ✌️ Init data loaded
3|panel    | 2024-09-02T16:58:36: ✌️ Link deps loaded
3|panel    | 2024-09-02T16:58:36: ✌️ Init task loaded
3|panel    | 2024-09-02T17:01:35: ✌️ Sentry loaded
3|panel    | 2024-09-02T17:01:51: ✌️ DB loaded
3|panel    | 2024-09-02T17:01:51: ✌️ Init file down
3|panel    | 2024-09-02T17:02:01: ✌️ Dependency loaded
3|panel    | 2024-09-02T17:02:08: ✌️ Init data loaded
3|panel    | 2024-09-02T17:02:08: ✌️ Link deps loaded
3|panel    | 2024-09-02T17:02:08: ✌️ Init task loaded

/root/.pm2/logs/panel-error.log last 15 lines:
3|panel    | 2024-09-02T16:58:38:     at startServer (/ql/back/app.ts:14:3)
3|panel    | 2024-09-02T16:58:38: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
3|panel    | 2024-09-02T16:58:38: TypeError: Sentry.setupExpressErrorHandler is not a function
3|panel    | 2024-09-02T16:58:38:     at exports.default (/ql/back/loaders/express.ts:136:10)
3|panel    | 2024-09-02T16:58:38:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
3|panel    | 2024-09-02T16:58:38:     at startServer (/ql/back/app.ts:14:3)
3|panel    | 2024-09-02T17:02:17: TypeError: Sentry.setupExpressErrorHandler is not a function
3|panel    | 2024-09-02T17:02:17:     at exports.default (/ql/back/loaders/express.ts:136:10)
3|panel    | 2024-09-02T17:02:17:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
3|panel    | 2024-09-02T17:02:17:     at startServer (/ql/back/app.ts:14:3)
3|panel    | 2024-09-02T17:02:18: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
3|panel    | 2024-09-02T17:02:18: TypeError: Sentry.setupExpressErrorHandler is not a function
3|panel    | 2024-09-02T17:02:18:     at exports.default (/ql/back/loaders/express.ts:136:10)
3|panel    | 2024-09-02T17:02:18:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
3|panel    | 2024-09-02T17:02:18:     at startServer (/ql/back/app.ts:14:3)


cat  /root/.pm2/logs/panel-error.log
2024-05-25T12:55:19: 
2024-05-25T12:55:19: <--- Last few GCs --->
2024-05-25T12:55:19: 
2024-05-25T12:55:19: [210:0xb3a73430] 1392253180 ms: Mark-Compact 238.1 (255.1) -> 238.0 (254.6) MB, 623.98 / 0.00 ms  (average mu = 0.879, current mu = 0.309) allocation failure; scavenge might not succeed
2024-05-25T12:55:19: [210:0xb3a73430] 1392253796 ms: Mark-Compact 239.9 (254.6) -> 239.7 (258.6) MB, 586.11 / 0.00 ms  (average mu = 0.775, current mu = 0.049) allocation failure; scavenge might not succeed
2024-05-25T12:55:19: 
2024-05-25T12:55:19: 
2024-05-25T12:55:19: <--- JS stacktrace --->
2024-05-25T12:55:19: 
2024-05-25T12:55:19: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
2024-05-25T12:55:19: ----- Native stack trace -----
2024-05-25T12:55:19: 
2024-09-02T16:28:09: TypeError: Sentry.setupExpressErrorHandler is not a function
2024-09-02T16:28:09:     at exports.default (/ql/back/loaders/express.ts:136:10)
2024-09-02T16:28:09:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
2024-09-02T16:28:09:     at startServer (/ql/back/app.ts:14:3)
2024-09-02T16:28:09: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-09-02T16:28:09: TypeError: Sentry.setupExpressErrorHandler is not a function
2024-09-02T16:28:09:     at exports.default (/ql/back/loaders/express.ts:136:10)
2024-09-02T16:28:09:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
2024-09-02T16:28:09:     at startServer (/ql/back/app.ts:14:3)
2024-09-02T16:58:38: TypeError: Sentry.setupExpressErrorHandler is not a function
2024-09-02T16:58:38:     at exports.default (/ql/back/loaders/express.ts:136:10)
2024-09-02T16:58:38:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
2024-09-02T16:58:38:     at startServer (/ql/back/app.ts:14:3)
2024-09-02T16:58:38: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-09-02T16:58:38: TypeError: Sentry.setupExpressErrorHandler is not a function
2024-09-02T16:58:38:     at exports.default (/ql/back/loaders/express.ts:136:10)
2024-09-02T16:58:38:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
2024-09-02T16:58:38:     at startServer (/ql/back/app.ts:14:3)
2024-09-02T17:02:17: TypeError: Sentry.setupExpressErrorHandler is not a function
2024-09-02T17:02:17:     at exports.default (/ql/back/loaders/express.ts:136:10)
2024-09-02T17:02:17:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
2024-09-02T17:02:17:     at startServer (/ql/back/app.ts:14:3)
2024-09-02T17:02:18: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-09-02T17:02:18: TypeError: Sentry.setupExpressErrorHandler is not a function
2024-09-02T17:02:18:     at exports.default (/ql/back/loaders/express.ts:136:10)
2024-09-02T17:02:18:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
2024-09-02T17:02:18:     at startServer (/ql/back/app.ts:14:3)

@whyour 🙏

**Comment by whyour** [comment]
> 无法启动+1
> 
> /ql $pm2 logs [TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option) /root/.pm2/pm2.log last 15 lines: PM2 | 2024-09-02T17:01:03: PM2 log: App [schedule:1] starting in -fork mode- PM2 | 2024-09-02T17:01:03: PM2 log: App [public:2] starting in -fork mode- PM2 | 2024-09-02T17:01:13: PM2 log: App [schedule:1] online PM2 | 2024-09-02T17:01:13: PM2 log: App [public:2] online PM2 | 2024-09-02T17:01:13: PM2 log: App [panel:3] starting in -fork mode- PM2 | 2024-09-02T17:01:24: PM2 log: App [panel:3] online
> 
> /root/.pm2/logs/panel-error.log last 15 lines: 3|panel | 2024-09-02T16:58:38: at startServer (/ql/back/app.ts:14:3) 3|panel | 2024-09-02T16:58:38: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason: 3|panel | 2024-09-02T16:58:38: TypeError: Sentry.setupExpressErrorHandler is not a function 3|panel | 2024-09-02T16:58:38: at exports.default (/ql/back/loaders/express.ts:136:10) 3|panel | 2024-09-02T16:58:38: at Object.exports.default (/ql/back/loaders/app.ts:26:16) 3|panel | 2024-09-02T16:58:38: at startServer (/ql/back/app.ts:14:3) 3|panel | 2024-09-02T17:02:17: TypeError: Sentry.setupExpressErrorHandler is not a function 3|panel | 2024-09-02T17:02:17: at exports.default (/ql/back/loaders/express.ts:136:10) 3|panel | 2024-09-02T17:02:17: at Object.exports.default (/ql/back/loaders/app.ts:26:16) 3|panel | 2024-09-02T17:02:17: at startServer (/ql/back/app.ts:14:3) 3|panel | 2024-09-02T17:02:18: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason: 3|panel | 2024-09-02T17:02:18: TypeError: Sentry.setupExpressErrorHandler is not a function 3|panel | 2024-09-02T17:02:18: at exports.default (/ql/back/loaders/express.ts:136:10) 3|panel | 2024-09-02T17:02:18: at Object.exports.default (/ql/back/loaders/app.ts:26:16) 3|panel | 2024-09-02T17:02:18: at startServer (/ql/back/app.ts:14:3)
> 
> cat /root/.pm2/logs/panel-error.log 2024-05-25T12:55:19: 2024-05-25T12:55:19: <--- Last few GCs ---> 2024-05-25T12:55:19: 2024-05-25T12:55:19: [210:0xb3a73430] 1392253180 ms: Mark-Compact 238.1 (255.1) -> 238.0 (254.6) MB, 623.98 / 0.00 ms (average mu = 0.879, current mu = 0.309) allocation failure; scavenge might not succeed 2024-05-25T12:55:19: [210:0xb3a73430] 1392253796 ms: Mark-Compact 239.9 (254.6) -> 239.7 (258.6) MB, 586.11 / 0.00 ms (average mu = 0.775, current mu = 0.049) allocation failure; scavenge might not succeed 2024-05-25T12:55:19: 2024-05-25T12:55:19: 2024-05-25T12:55:19: <--- JS stacktrace ---> 2024-05-25T12:55:19: 2024-05-25T12:55:19: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory 2024-05-25T12:55:19: ----- Native stack trace ----- 2024-05-25T12:55:19: 2024-09-02T16:28:09: TypeError: Sentry.setupExpressErrorHandler is not a function 2024-09-02T16:28:09: at exports.default (/ql/back/loaders/express.ts:136:10) 2024-09-02T16:28:09: at Object.exports.default (/ql/back/loaders/app.ts:26:16) 2024-09-02T16:28:09: at startServer (/ql/back/app.ts:14:3) 2024-09-02T16:28:09: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason: 2024-09-02T16:28:09: TypeError: Sentry.setupExpressErrorHandler is not a function 2024-09-02T16:28:09: at exports.default (/ql/back/loaders/express.ts:136:10) 2024-09-02T16:28:09: at Object.exports.default (/ql/back/loaders/app.ts:26:16) 2024-09-02T16:28:09: at startServer (/ql/back/app.ts:14:3) 2024-09-02T16:58:38: TypeError: Sentry.setupExpressErrorHandler is not a function 2024-09-02T16:58:38: at exports.default (/ql/back/loaders/express.ts:136:10) 2024-09-02T16:58:38: at Object.exports.default (/ql/back/loaders/app.ts:26:16) 2024-09-02T16:58:38: at startServer (/ql/back/app.ts:14:3) 2024-09-02T16:58:38: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason: 2024-09-02T16:58:38: TypeError: Sentry.setupExpressErrorHandler is not a function 2024-09-02T16:58:38: at exports.default (/ql/back/loaders/express.ts:136:10) 2024-09-02T16:58:38: at Object.exports.default (/ql/back/loaders/app.ts:26:16) 2024-09-02T16:58:38: at startServer (/ql/back/app.ts:14:3) 2024-09-02T17:02:17: TypeError: Sentry.setupExpressErrorHandler is not a function 2024-09-02T17:02:17: at exports.default (/ql/back/loaders/express.ts:136:10) 2024-09-02T17:02:17: at Object.exports.default (/ql/back/loaders/app.ts:26:16) 2024-09-02T17:02:17: at startServer (/ql/back/app.ts:14:3) 2024-09-02T17:02:18: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason: 2024-09-02T17:02:18: TypeError: Sentry.setupExpressErrorHandler is not a function 2024-09-02T17:02:18: at exports.default (/ql/back/loaders/express.ts:136:10) 2024-09-02T17:02:18: at Object.exports.default (/ql/back/loaders/app.ts:26:16) 2024-09-02T17:02:18: at startServer (/ql/back/app.ts:14:3)
> 
> @whyour 🙏

启动依赖有问题，删除容器，更新最新镜像重新创建下
