### ISSUE TITLE
定时任务如何设置每隔40秒启动脚本

### ISSUE THREAD

**Issue by iptag** [whyour/qinglong#2484]
### Qinglong version

2.17.9

### Steps to reproduce

设置为*/40 * * * *实际是每分钟的0秒和40秒启动脚本，不符合预期

### What is expected?

想在task_before中添加以下脚本，看小问号的提示，不知道能否支持bash命令，或者有大佬提供下解决方案？

### What is actually happening?

谢谢！

**Comment by whyour** [comment]
支持 bash 命令

**Comment by iptag** [comment]
> 支持 bash 命令

试了下，确实可行，之前只会用task py或者js，能用task sh的话，可扩展性就更强了！
