### ISSUE TITLE
依赖管理页面不显示

### ISSUE THREAD

**Issue by edwinzjh** [whyour/qinglong#2486]
### Qinglong version

2.17.10

### Steps to reproduce

![屏幕截图 2024-09-01 153031](https://github.com/user-attachments/assets/37672030-c92c-469e-b1b3-fc1a8394ea2f)

### What is expected?

![屏幕截图 2024-09-01 153200](https://github.com/user-attachments/assets/a231e652-e6c3-4403-a099-b45c80e5ab62)

### What is actually happening?

或许是因为取值失败等原因max-height值设成了0，改成1000或其他值就能恢复。
![屏幕截图 2024-09-01 153432](https://github.com/user-attachments/assets/30c655f8-3e1e-4d8c-a718-03f736835c2d)

**Comment by whyour** [comment]
已修复，更新下
