### ISSUE TITLE
Contact for Security Issue

### ISSUE THREAD

**Issue by 4rdr** [whyour/qinglong#2487]
### Qinglong version

v2.17.8

### Steps to reproduce

Is there an email or way through Github to submit a security bug in private?

有没有通过电子邮件或 Github 的方式私下提交安全漏洞？

### What is expected?

Is there an email or way through Github to submit a security bug in private?

有没有通过电子邮件或 Github 的方式私下提交安全漏洞？

### What is actually happening?

Is there an email or way through Github to submit a security bug in private?

有没有通过电子邮件或 Github 的方式私下提交安全漏洞？

**Comment by whyour** [comment]
imwhyour@gmail.com

**Comment by whyour** [comment]
2.17.11 已修复
