### ISSUE TITLE
莫名其妙的启动不了

### ISSUE THREAD

**Issue by ADolphin-02** [whyour/qinglong#2489]
### Qinglong version

2.17.7

### Steps to reproduce

//

### What is expected?

前几天还好好的，定位两天才找到无缘无故服务器重启的原因

### What is actually happening?

docker自启ql后服务器一直重启，查看日志是如下───────────┴──────────┴──────────┴──────────┴──────────┘
Error grabbing logs: invalid character '\x00' looking for beginning of value
root@armbian:~# 

### System Info

```shell
//
```

### Any additional comments?

//

**Comment by ADolphin-02** [comment]
原因未知, 启动后能运行一两分钟, 然后把日志天数从原来的5天弄成58天就能正常使用了

**Comment by whyour** [comment]
@ADolphin-02 是日志文件太多了？可以手动清理下，最新版修复了清理文件的一个问题，可以更新试试

**Comment by ADolphin-02** [comment]
更新最新版解决
