### ISSUE TITLE
快速安装青龙的所有依赖

### ISSUE THREAD

**Issue by aspnmy** [whyour/qinglong#2491]
@[TOC](青龙面板v2.17.10 -快速安装青龙面板的所有依赖的实践)

# 操作步骤及说明
- 下面是青龙面板docker版本，node的system默认的版本，这些文件要先备份一遍
```shell
root@ee5aa36921f0:/ql $ node -v
v20.15.1
root@ee5aa36921f0:/ql $ npm -v
10.8.0
root@ee5aa36921f0:/ql $ npx -v
10.8.0
root@ee5aa36921f0:/ql $ pnpm -v
8.3.1
```
- 输入
```shell
 which node
```
- 找到 默认system版本node所在的安装目录dirpath
```shell
#首先生成备份目录并，备份默认组件
mkdir -p dirpath（默认安装目录）/backup
cp -r  dirpath（默认安装目录）/{"node","npm","npx","pnpm"}  backup/*
```
# 第一步，安装fnm nodejs管理器
```shell
cd ~
git clone https://github.com/Schniz/fnm.git
bash fnm/.ci/install.sh -d ~/.fnm
echo 'eval "$(fnm env --use-on-cd)"' >> .bashrc # 此项用于不同文件夹下使用不同NodeJS版本。
source ~/.bashrc
fnm --version
```
# 第二步，配置镜像源环境，国内选阿里源
```shell
echo "export
FNM_NODE_DIST_MIRROR=https://mirrors.aliyun.com/nodejs-release/" >> ~/.bashrc
```
# 第三步，fnm使配置配置生效
```shell
source ~/.bashrc
```
# 第四步，安装除canvas以外的其他依赖
```shell 
pnpm -g install date-fns axios ts-node typescript png-js crypto-js md5 dotenv got ts-md5 tslib @types/node requests tough-cookie jsdom download tunnel fs ws js-base64 jieba
```
# 第五步，fnm降级安装nodejs到12以下，安装依赖canvas
```shell
fnm install v11.15.0
```
# 第六步配置默认nodejs为当前v20.15.0配置当前会话node版本为v11.15.0
```shell
fnm use v1.15.0
```

# 第七步npm降级到node v11.15.0匹配的v6.7.0
## 1、 更新npm镜像源
```shell
npm config set registry http://registry.npmmirror.com
```

### 2.2 然后把v11.15.0版本的组件复制到system的安装位置上
+ 下面有两种处理方式，网上搜索的是删除system，这样做的话会因为配置文件找不到造成错误
* 所以我们使用第二种方式，通过备份system下的node以后，把v11.15.0的node npm pnpm npx 覆盖到system下即可，然后
### 2.4 安装依赖canvas
```shell
npm -g canvas
```

### 2.5依赖全部安装完毕，这个时候可以把system原来版本的20.15的node、npm、npx文件恢复回去，或者直接使用最新v22.15的版本

# 查看我在git上最新的文章记录
* https://github.com/whyour/qinglong/issues/2491

**Comment by whyour** [comment]
1. 依赖建议使用依赖管理安装，镜像源设置在系统设置/依赖设置中
2. canvas 可以使用 next 版本试试
