### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by ivhhs** [whyour/qinglong#2493]
### Qinglong version

2.17.9

### Steps to reproduce

ql update后无法启动

### What is expected?

ql update后无法启动

### What is actually happening?

[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2024-09-07T08:32:34: PM2 log: App [schedule:7] starting in -fork mode-
PM2        | 2024-09-07T08:32:34: PM2 log: App [public:8] starting in -fork mode-
PM2        | 2024-09-07T08:32:34: PM2 log: App [schedule:7] online
PM2        | 2024-09-07T08:32:34: PM2 log: App [panel:9] starting in -fork mode-
PM2        | 2024-09-07T08:32:34: PM2 log: App [public:8] online
PM2        | 2024-09-07T08:32:44: PM2 log: App [panel:9] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/update-out.log last 15 lines:
/root/.pm2/logs/update-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
7|schedule | 2024-08-18T13:07:30: ✌️ 定时服务启动成功！
7|schedule | 2024-08-20T10:37:29: ✌️ 定时服务启动成功！
7|schedule | 2024-08-21T22:36:07: ✌️ 定时服务启动成功！
7|schedule | 2024-08-23T12:24:08: ✌️ 定时服务启动成功！
7|schedule | 2024-08-24T16:06:50: ✌️ 定时服务启动成功！
7|schedule | 2024-08-26T14:07:34: ✌️ 定时服务启动成功！
7|schedule | 2024-08-30T14:07:29: ✌️ 定时服务启动成功！
7|schedule | 2024-09-06T10:53:03: ✌️ 定时服务启动成功！
7|schedule | 2024-09-07T08:16:58: ✌️ 定时服务启动成功！
7|schedule | 2024-09-07T08:19:16: ✌️ 定时服务启动成功！
7|schedule | 2024-09-07T08:19:46: ✌️ 定时服务启动成功！
7|schedule | 2024-09-07T08:25:24: ✌️ 定时服务启动成功！
7|schedule | 2024-09-07T08:28:14: ✌️ 定时服务启动成功！
7|schedule | 2024-09-07T08:31:30: ✌️ 定时服务启动成功！
7|schedule | 2024-09-07T08:32:34: ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
8|public   | 2024-09-07T08:16:57: ✌️ Sentry loaded
8|public   | 2024-09-07T08:16:58: ✌️ DB loaded
8|public   | 2024-09-07T08:16:58: ✌️ 公共服务启动成功！
8|public   | 2024-09-07T08:19:16: ✌️ DB loaded
8|public   | 2024-09-07T08:19:16: ✌️ 公共服务启动成功！
8|public   | 2024-09-07T08:19:46: ✌️ DB loaded
8|public   | 2024-09-07T08:19:46: ✌️ 公共服务启动成功！
8|public   | 2024-09-07T08:25:24: ✌️ DB loaded
8|public   | 2024-09-07T08:25:24: ✌️ 公共服务启动成功！
8|public   | 2024-09-07T08:28:14: ✌️ DB loaded
8|public   | 2024-09-07T08:28:14: ✌️ 公共服务启动成功！
8|public   | 2024-09-07T08:31:30: ✌️ DB loaded
8|public   | 2024-09-07T08:31:30: ✌️ 公共服务启动成功！
8|public   | 2024-09-07T08:32:34: ✌️ DB loaded
8|public   | 2024-09-07T08:32:34: ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
9|panel    | 2024-09-07T08:28:15: ✌️ Init task loaded
9|panel    | 2024-09-07T08:31:30: ✌️ Sentry loaded
9|panel    | 2024-09-07T08:31:30: ✌️ DB loaded
9|panel    | 2024-09-07T08:31:30: ✌️ Init file down
9|panel    | 2024-09-07T08:31:31: ✌️ Dependency loaded
9|panel    | 2024-09-07T08:31:31: ✌️ Init data loaded
9|panel    | 2024-09-07T08:31:31: ✌️ Link deps loaded
9|panel    | 2024-09-07T08:31:31: ✌️ Init task loaded
9|panel    | 2024-09-07T08:32:34: ✌️ Sentry loaded
9|panel    | 2024-09-07T08:32:35: ✌️ DB loaded
9|panel    | 2024-09-07T08:32:35: ✌️ Init file down
9|panel    | 2024-09-07T08:32:35: ✌️ Dependency loaded
9|panel    | 2024-09-07T08:32:35: ✌️ Init data loaded
9|panel    | 2024-09-07T08:32:35: ✌️ Link deps loaded
9|panel    | 2024-09-07T08:32:35: ✌️ Init task loaded

/root/.pm2/logs/panel-error.log last 15 lines:
9|panel    | 2024-09-07T08:31:31:     at startServer (/ql/back/app.ts:14:3)
9|panel    | 2024-09-07T08:31:31: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
9|panel    | 2024-09-07T08:31:31: TypeError: Sentry.setupExpressErrorHandler is not a function
9|panel    | 2024-09-07T08:31:31:     at exports.default (/ql/back/loaders/express.ts:136:10)
9|panel    | 2024-09-07T08:31:31:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
9|panel    | 2024-09-07T08:31:31:     at startServer (/ql/back/app.ts:14:3)
9|panel    | 2024-09-07T08:32:35: TypeError: Sentry.setupExpressErrorHandler is not a function
9|panel    | 2024-09-07T08:32:35:     at exports.default (/ql/back/loaders/express.ts:136:10)
9|panel    | 2024-09-07T08:32:35:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
9|panel    | 2024-09-07T08:32:35:     at startServer (/ql/back/app.ts:14:3)
9|panel    | 2024-09-07T08:32:35: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
9|panel    | 2024-09-07T08:32:35: TypeError: Sentry.setupExpressErrorHandler is not a function
9|panel    | 2024-09-07T08:32:35:     at exports.default (/ql/back/loaders/express.ts:136:10)
9|panel    | 2024-09-07T08:32:35:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
9|panel    | 2024-09-07T08:32:35:     at startServer (/ql/back/app.ts:14:3)

**Comment by whyour** [comment]
使用 docker 方式更新镜像后重建下，或者容器中执行 ql check，但是安装依赖根据网络不同可能比较耗时
