### ISSUE TITLE
定时任务视图列表在创建太多视图，没有滚动条点不到最下面视图管理的问题

### ISSUE THREAD

**Issue by zjk2017** [whyour/qinglong#2495]
### Clear and concise description of the problem

定时任务--更多--视图列表
我有30多个订阅链接，并给每个订阅都创建了视图，一共创建了40个视图，我要缩放到很小很小才能创建新视图、查看对应的视图里面有什么脚本，不然就点不到最后面的创建视图和视图管理的菜单 ，如果少创建一点视图，那肯定没啥问题

### Suggested solution

建议加个滑动条或者你认为较好的方式 来解决不缩放点不到最下面视图管理的功能  或者说建议使用者少创建点视图

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zjk2017** [comment]
定时任务--点击“更多”   指的这个地方

**Comment by whyour** [comment]
2.17.11 已修复
