### ISSUE TITLE
PYTHONPATH 为空，导致无法 python 脚本无法正常获取环境变量

### ISSUE THREAD

**Issue by yelochick** [whyour/qinglong#2498]
### Qinglong version

2.17.10

### Steps to reproduce

PYTHONPATH 为空，导致 otask.sh 224行 PYTHONPATH=“:/ql/shell/preload:/ql/data/config”
在config.sh配置PYTHONPATH到任意路径后脚本能正常获取到环境变量

### What is expected?

python 脚本可以正常获取环境变量

### What is actually happening?

没有

**Comment by whyour** [comment]
2.17.11 已修复
