### ISSUE TITLE
添加linux镜像源报错

### ISSUE THREAD

**Issue by Air433up** [whyour/qinglong#2501]
### Qinglong version

2.17.10 debian-python

### Steps to reproduce

![image](https://github.com/user-attachments/assets/402020bc-4be3-46c0-bc87-06dedaec557e)

### What is expected?

如上图

### What is actually happening?

如上图

**Comment by Air433up** [comment]
> 其他设置，点下重新启动

重启多次依旧如此，有类似Ubuntu系统这样直接改文件的方法嘛，进入容器内不知道是哪个文件储存的镜像链接

**Comment by whyour** [comment]
> > 其他设置，点下重新启动
> 
> 重启多次依旧如此，有类似Ubuntu系统这样直接改文件的方法嘛，进入容器内不知道是哪个文件储存的镜像链接

容器删了，重建。你这是有次地址写错了？

**Comment by Air433up** [comment]
是这样子的，第一我加https://mirrors.hust.edu.cn这个Linux源后点击确认直接卡住，确认那里一直转圈，等了5.6分钟还是如此我就刷新了一下，然后就是如上图报错了，我刚刚重装了容器依旧是这个情况

**Comment by Air433up** [comment]
> 是这样子的，第一我加https://mirrors.hust.edu.cn这个Linux源后点击确认直接卡住，确认那里一直转圈，等了5.6分钟还是如此我就刷新了一下，然后就是如上图报错了，我刚刚重装了容器依旧是这个情况

现在又好了，可能是我网络问题，谢谢大佬解答了
