### ISSUE TITLE
青龙面板安装在极空间NAS上，极空间docker引擎日志每隔5秒发生一次报错

### ISSUE THREAD

**Issue by ccwforever** [whyour/qinglong#2505]
### Qinglong version

2.17.11

### Steps to reproduce

青龙面板部署在极空间NAS上

### What is expected?

请求检查一下问题

### What is actually happening?

![111](https://github.com/user-attachments/assets/7e13fcb8-83db-4103-916a-acb6492d51fb)

**Comment by whyour** [comment]
没有设备，不清楚是在做什么，建议咨询相关厂商

**Comment by Estelle00** [comment]
请问解决了吗
