### ISSUE TITLE
青龙的update.js会监听5300端口导致和AdGuard Home默认的5300端口冲突问题

### ISSUE THREAD

**Issue by QYC-Unity** [whyour/qinglong#2506]
### Qinglong version

正式版 v2.17.11

### Steps to reproduce

同时运行docker版青龙面板和AdGuard Home，会导致端口被占用

### What is expected?

默认端口不冲突

### What is actually happening?

默认的5300端口和AdGuard Home冲突

**Comment by whyour** [comment]
启动的时候增加 环境变量 UPDATE_PORT，修改 update 服务端口
