### ISSUE TITLE
青龙面板升级

### ISSUE THREAD

**Issue by marcohard** [whyour/qinglong#2508]
### Qinglong version

2.17.8

### Steps to reproduce

docker下在升级2.17.11时检查更新有新版本就点更新，完成后重启依旧是老版本
![image](https://github.com/user-attachments/assets/9e5033ae-0cf4-4d5a-aef1-aa1eed021cd4)

### What is expected?

如何才能升级到新版

### What is actually happening?

成功后重启刷新页面依旧是老版本

**Comment by aspnmy** [comment]
docker版本要去更新docker镜像版本 而不是系统内更新，这样是无效的

**Comment by marcohard** [comment]
这个是青龙面板的更新，不是docker，是在docker的环境下更新的，之前有过一次更新是成功的，这次为啥不成功？

**Comment by marcohard** [comment]
![image](https://github.com/user-attachments/assets/2217ef16-3081-4b68-ad89-9c6e7d2e8f1a)

**Comment by marcohard** [comment]
![image](https://github.com/user-attachments/assets/cfe8d6a6-be75-41db-a4e8-ff698460f228)
更新完成重启后依旧是旧版本

**Comment by aspnmy** [comment]
青龙面板的docker版本升级 我一向来是升级docker镜像的，容器内部升级是不持久的，特别是docker重新拉起以后

**Comment by aspnmy** [comment]
你一定要尝试容器内升级，升级完成以后必须 自行提交commit 一个新的镜像，重新以新镜像进行拉起，保证数据不回滚回去``

**Comment by aspnmy** [comment]
进入容器内命令行 `ql update` 升级完成后再宿主机命令行输入

**Comment by whyour** [comment]
要升级下镜像

**Comment by marcohard** [comment]
结果青龙搞坏了，只能重新再整

**Comment by aspnmy** [comment]
> 结果青龙搞坏了，只能重新再整

只能说太性急了 你没有快照需要重建 多少累

**Comment by liang5064** [comment]
原来还好好的，我手贱去更新docker，青龙再也起不来了。只是运行了“docker exec -it qinglong ql update”，最终也显示更新成功，就是再也打不开青龙面板了。

**Comment by aspnmy** [comment]
> 原来还好好的，我手贱去更新docker，青龙再也起不来了。只是运行了“docker exec -it qinglong ql update”，最终也显示更新成功，就是再也打不开青龙面板了。

生产环境就不应该随便升级 升级前需要 备份一下
