### ISSUE TITLE
群辉 chat  Error: {"error":{"code":105,"errors":"autoblock"},"success":false}

### ISSUE THREAD

**Issue by tianzuizhiyi** [whyour/qinglong#2511]
### Qinglong version

正式版 v2.17.3

### Steps to reproduce

群辉 chat  集成的时候 突然出现了  Error: {"error":{"code":105,"errors":"autoblock"},"success":false} 原来都是都正常的

### What is expected?

感觉是被自动锁定了，但是不知道是什么被锁定了

### What is actually happening?

集成就会出现，无法弹通知了

**Comment by whyour** [comment]
找群晖相关去看吧
