### ISSUE TITLE
青龙版本2.17.11运行一个js脚本，报错：SSL routines:tls_process_ske_dhe:dh key too small:ssl/statem/statem_clnt.c:2314: 

### ISSUE THREAD

**Issue by zpiz** [whyour/qinglong#2515]
### Qinglong version

2.17.11

### Steps to reproduce

在运行一个js脚本的时候遇到此报错，按照之前的一个issue提供的方法https://github.com/whyour/qinglong/issues/2420，在web界面“执行前”添加命令：export NODE_OPTIONS="${NODE_OPTIONS} --tls-cipher-list=DEFAULT@SECLEVEL=0"，手动运行脚本仍然报相同错误，还请指教

### What is expected?

希望可以通过不降级青龙的方法解决此问题

### What is actually happening?

最新版无法运行某个js脚本

**Comment by whyour** [comment]
命令加到 config.sh，或者还用 whyour/qinglong:debian 镜像

**Comment by zpiz** [comment]
> 命令加到 config.sh，或者还用 whyour/qinglong:debian 镜像

可以了，多谢
