### ISSUE TITLE
建议增加单个脚本并发功能

### ISSUE THREAD

**Issue by mmeiwenlong** [whyour/qinglong#2517]
### Clear and concise description of the problem

假如同时来几个线报的等一个一个跑完接着一个一个来，如增加单个脚本并发功能，就不用等了，来一个跑一个，可以同时开跑，只要机器吃得消，感觉挺好

### Suggested solution

增加单个脚本并发功能

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
https://github.com/whyour/qinglong?tab=readme-ov-file#%E5%86%85%E7%BD%AE%E5%91%BD%E4%BB%A4

# 并发执行，无论是否设置了随机延迟，均立即运行，前台不产生日，直接记录在日志文件中，且可指定账号执行
task <file_path> conc <env_name> <account_number>(可选的)
