### ISSUE TITLE
使用-m命令后的日志问题

### ISSUE THREAD

**Issue by xiaolong52** [whyour/qinglong#2521]
### Qinglong version

2.17.11

### Steps to reproduce

使用如下命令后task -m 2h XXXX.js 手动执行和自动执行的日志是分开的，手动执行任务后，在定时页面就查看不到自动执行的日志了。

### What is expected?

日志能够合并在一起

### What is actually happening?

手动执行和自动执行的日志是分开的，手动执行任务后，在定时页面就查看不到自动执行的日志了。

**Comment by whyour** [comment]
2.17.12 已修复
