### ISSUE TITLE
建议把首页分类栏放开，自适应平铺或者可以勾选那些可以显示在上面，如图

### ISSUE THREAD

**Issue by ZiDuNet** [whyour/qinglong#2522]
### Clear and concise description of the problem

![image](https://github.com/user-attachments/assets/f11d2375-197f-4cb3-8388-c75da68e9082)

### Suggested solution

![image](https://github.com/user-attachments/assets/f11d2375-197f-4cb3-8388-c75da68e9082)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
更多 -> 视图设置，可以设置哪些视图显示，也可以调整顺序

**Comment by Smithcaige** [comment]
> 更多 -> 视图设置，可以设置哪些视图显示，也可以调整顺序

但是这个好像只有四个，不想超过四个视图点击更多再去查看，我想让他显示多一点，如果太多再点击更多查看

**Comment by whyour** [comment]
2.17.12 增加为 10 个

**Comment by Smithcaige** [comment]
多谢了。另外消息推送能否加一个按照订阅或者其他 推送消息。我常用企微bot，以此为例。比如我订阅京东，推送企微bot1；我订阅美团，推送企微bot2。或者按照上面的优化分视图独立推送也可发自我的 iPhone在 2024年10月26日，16:01，whyour ***@***.***> 写道：﻿
2.17.12 增加为 10 个
