### ISSUE TITLE
疯狂请求一堆域名，无法排查来源

### ISSUE THREAD

**Issue by YujiaCheng1996** [whyour/qinglong#2527]
### Qinglong version

docker debian

### Steps to reproduce

为了dotnet环境安装方便切换到debian版docker镜像，把整个网络dns都卡死了，排查半天确定是青龙，但后续再无法排查具体来源。哪怕重新compose up也无效。

### What is expected?

方便排查

### What is actually happening?

![1728615612440](https://github.com/user-attachments/assets/8bae032c-0cff-4d8b-b465-ee86d739f889)
![1728615576407](https://github.com/user-attachments/assets/84907846-78ca-417d-91ca-ad81681332e0)
疯狂dns，那就是在疯狂请求这些乱七八糟的网站，同时看青龙里没有任何任务在执行，连进去使用ps查看进程也没有任何异常。
只订阅了几个签到库，都没有在运行。

**Comment by whyour** [comment]
咋确定是青龙自己请求的

**Comment by YujiaCheng1996** [comment]
> 咋确定是青龙自己请求的

这个ip是docker分配给青龙的，青龙一停立马消停了。

**Comment by whyour** [comment]
> > 咋确定是青龙自己请求的
> 
> 
> 
> 这个ip是docker分配给青龙的，青龙一停立马消停了。

建个空容器分配个 ip 也有这些请求？

**Comment by YujiaCheng1996** [comment]
> > > 咋确定是青龙自己请求的
> > 
> > 
> > 这个ip是docker分配给青龙的，青龙一停立马消停了。
> 
> 建个空容器分配个 ip 也有这些请求？

我没有说是青龙请求的，只是我完全没有办法排查是谁请求的，使用ps命令完全没有其他进程在跑，但是请求还在继续。

**Comment by whyour** [comment]
> > > > 咋确定是青龙自己请求的
> > > 
> > > 
> > > 这个ip是docker分配给青龙的，青龙一停立马消停了。
> > 
> > 
> > 建个空容器分配个 ip 也有这些请求？
> 
> 我没有说是青龙请求的，只是我完全没有办法排查是谁请求的，使用ps命令完全没有其他进程在跑，但是请求还在继续。

那你只能一个个脚本排查了

**Comment by YujiaCheng1996** [comment]
> > > > > 咋确定是青龙自己请求的
> > > > 
> > > > 
> > > > 这个ip是docker分配给青龙的，青龙一停立马消停了。
> > > 
> > > 
> > > 建个空容器分配个 ip 也有这些请求？
> > 
> > 
> > 我没有说是青龙请求的，只是我完全没有办法排查是谁请求的，使用ps命令完全没有其他进程在跑，但是请求还在继续。
> 
> 那你只能一个个脚本排查了

并且切换回alpine的镜像就没有这个情况，只有debian的镜像会有这些请求。
