### ISSUE TITLE
变量文件过大导致报错The environment variable is too large. It is recommended to use task_before.js instead of task_before.sh

### ISSUE THREAD

**Issue by 1934103887** [whyour/qinglong#2529]
### Qinglong version

2.17.11

### Steps to reproduce

![Uploading 微信截图_20241012140522.png…]()

### What is expected?

![Uploading 微信截图_20241012140914.png…]()

### What is actually happening?

在禁用部分环境变量后此提示消失
The environment variable is too large. It is recommended to use task_before.js instead of task_before.sh
测试了一下  如果将变量备注删除即可正常运行
感觉是文件变量备注太多导致  希望可以优化一下

**Comment by whyour** [comment]
这是个提醒，就是变量太多了
