### ISSUE TITLE
登陆日志卡住

### ISSUE THREAD

**Issue by rickychaw** [whyour/qinglong#2535]
### Qinglong version

2.17.11

### Steps to reproduce

打开系统设置==>登陆日志

### What is expected?

正常记录，显示

### What is actually happening?

集帅们，这是怎么回事呢？八月份开始就没有记录了，导出数据重装面板再导入还是这样。。
![image](https://github.com/user-attachments/assets/d3a63ed5-9644-47c9-879e-4e3e065cc0b4)

### System Info

```shell
Debian12
```

**Comment by whyour** [comment]
2.17.12 已修复
