### ISSUE TITLE
点依赖设置和其它设置时，出现System {"type":"systemConfig"} not found

### ISSUE THREAD

**Issue by carrieyz** [whyour/qinglong#2540]
### Qinglong version

v2.17.11

### Steps to reproduce

点依赖设置和其它设置时，出现System {"type":"systemConfig"} not found。
使用win桌面版docker部署的。

### What is expected?

请问碰到这种问题是win桌面版问题，还是？

### What is actually happening?

请问碰到这种问题是win桌面版问题，还是？

**Comment by whyour** [comment]
repeat https://github.com/whyour/qinglong/issues/2472#issuecomment-2295098086
