### ISSUE TITLE
任务可以增加重试功能吗

### ISSUE THREAD

**Issue by longweiqiang** [whyour/qinglong#2551]
### Clear and concise description of the problem

有些签到类型的任务，因为网络原因导致请求失败，虽然有配置推送，但是有时候也会遗漏消息。能否增加一个重试机制，当某些原因导致请求失败后，按一定的重试规则来二次发起请求。因为如果无脑配置多个执行时间的话，有可能会触发网站风控，所以希望能更加智能一些，只有当请求失败后再二次调用

### Suggested solution

增加重试功能

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by fanhengkui** [comment]
这个在于脚本，青龙只是提供框架，怎么弄是写脚本的需要考虑的。你可以用代理

**Comment by longweiqiang** [comment]
> 这个在于脚本，青龙只是提供框架，怎么弄是写脚本的需要考虑的。你可以用代理
好的，感谢回复
