### ISSUE TITLE
在鸿蒙端开发客户端登录提示desktop

### ISSUE THREAD

**Issue by xiaobingtech** [whyour/qinglong#2554]
### Clear and concise description of the problem

在鸿蒙端开发客户端登录提示desktop

### Suggested solution

鸿蒙登录显示mobile

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
给个 鸿蒙 的 userAgent 看看

**Comment by xiaobingtech** [comment]
Mozilla/5.0 (Phone; OpenHarmony5.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 ArkWeb/4.1.6.1 Mobile

**Comment by xiaobingtech** [comment]
已提交PR
