### ISSUE TITLE
打开ip:5700显示nginx页面

### ISSUE THREAD

**Issue by ximury** [whyour/qinglong#2560]
### Qinglong version

latest

### Steps to reproduce

docker-compose一键启动，
打开ip:5700显示nginx页面
<img width="1123" alt="image" src="https://github.com/user-attachments/assets/38737ef2-4a41-450f-a218-883eab6a9578">

### What is expected?

正常显示配置页面

### What is actually happening?

无

**Comment by whyour** [comment]
启动的时候增加了 baseUrl 吗

**Comment by OnceNever** [comment]
同样的问题，启动命令docker run -dit -v $PWD/ql/data:/ql/data -p 5700:5700 -e QlBaseUrl="/opt/ql" -e QlPort="5700"  --name qinglong --hostname qinglong  --restart unless-stopped dockerpull.org/whyour/qinglong

**Comment by OnceNever** [comment]
> 同样的问题，启动命令docker run -dit -v $PWD/ql/data:/ql/data -p 5700:5700 -e QlBaseUrl="/opt/ql" -e QlPort="5700" --name qinglong --hostname qinglong --restart unless-stopped dockerpull.org/whyour/qinglong

好像QlBaseUrl不能写别的，改回/就可以了
