### ISSUE TITLE
无法通过api进行备份

### ISSUE THREAD

**Issue by 895090595** [whyour/qinglong#2561]
### Qinglong version

正式版 v2.17.12

### Steps to reproduce

通过脚本进行导出备份,代码如下:
```
host="http://192.168.1.40"
# 登录
token=$(curl -s "$host:5700/open/auth/token?client_id=6-2kqgdErHwc&client_secret=m23hbNa_ySb8lZProv0zNzmw" | jq -r '.data.token')
echo "*** 青龙登录成功,token为: $token"
# 下载文件
# 创建目标目录（如果不存在的话）
mkdir -p /ql/data/temp
# 使用 curl 发起请求并保存文件
timestamp=$(date +"%Y%m%d%H%M%S")
output_file="/ql/data/temp/qinglong_export_data.tgz"
# curl -o $output_file -L -H "Authorization: Bearer $token" "$host:5700/open/api/system/data/export?t=$timestamp"
```

### What is expected?

有没有其他备份方式(导出备份压缩包到指定目录)?

### What is actually happening?

输出信息:
`{"code":401,"message":"jwt malformed"}`
应用设置,已全部勾选
![image](https://github.com/user-attachments/assets/16e2db65-1b02-43f3-afb1-f9ef0f89fd3c)

### Any additional comments?

用此方式获取的token可以正常更新脚本/获取脚本列表/... , 但是不能导出备份

**Comment by whyour** [comment]
`$host:5700/open/api/system/data/export`  多了个 api

**Comment by 895090595** [comment]
> `$host:5700/open/api/system/data/export` 多了个 api

去掉url中的api后404了
`curl -o $output_file -L -H "Authorization: Bearer $token" "$host:5700/open/system/data/export?t=$timestamp"
``{"code":404,"message":"Not Found"}`

**Comment by whyour** [comment]
> > `$host:5700/open/api/system/data/export` 多了个 api
> 
> 
> 
> 去掉url中的api后404了
> 
> `curl -o $output_file -L -H "Authorization: Bearer $token" "$host:5700/open/system/data/export?t=$timestamp"
> 
> ``{"code":404,"message":"Not Found"}`

请求 method 不对
https://qinglong.online/api/system#%E5%AF%BC%E5%87%BA%E6%95%B0%E6%8D%AE

**Comment by 895090595** [comment]
> > > `$host:5700/open/api/system/data/export` 多了个 api
> > 
> > 
> > 去掉url中的api后404了
> > `curl -o $output_file -L -H "Authorization: Bearer $token" "$host:5700/open/system/data/export?t=$timestamp"
> > ``{"code":404,"message":"Not Found"}`
> 
> 请求 method 不对 https://qinglong.online/api/system#%E5%AF%BC%E5%87%BA%E6%95%B0%E6%8D%AE

对了,感谢回复, 我自己的问题
