### ISSUE TITLE
日志的默认名是脚本名，能否自定义改成任务名

### ISSUE THREAD

**Issue by iptag** [whyour/qinglong#2568]
### Clear and concise description of the problem

目前日志名称都是脚本名，但是我有多个任务但执行同一个脚本，导致生成的日志名都是脚本名_序号的形式，查看日志十分不方便，如下图所示
![image](https://github.com/user-attachments/assets/7dc54839-55d2-4f7c-8380-a6506b3a7df5)

### Suggested solution

能否增加日志名称使用任务名的选项，多一个选择

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by whyour** [comment]
repeat https://github.com/whyour/qinglong/issues/2557
