### ISSUE TITLE
System {"type":"systemConfig"} not found

### ISSUE THREAD

**Issue by cyxnzb** [whyour/qinglong#2573]
### Qinglong version

2.17.12

### Steps to reproduce

在删除完原容器后重新执行
docker run -dit \
   -v $PWD/ql/config:/ql/config \
   -v $PWD/ql/log:/ql/log \
   -v $PWD/ql/db:/ql/db \
   -p 5700:5700 \
   --name qinglong \
   --hostname qinglong \
   --restart always \
   whyour/qinglong:latest
之后执行完必要的安装步骤后，在没有做任何措施，拉任何库的情况下，点击系统设置》依赖设置，会提示“System {"type":"systemConfig"} not found”

### What is expected?

System {"type":"systemConfig"} not found

### What is actually happening?

System {"type":"systemConfig"} not found

**Comment by cyxnzb** [comment]
找到了，参见：https://github.com/whyour/qinglong/issues/2472

**Comment by whyour** [comment]
@cyxnzb 你这启动命令不对啊，看下项目 readme

**Comment by cyxnzb** [comment]
> @cyxnzb 你这启动命令不对啊，看下项目 readme

按照readme重新部署后第一次运行还是会出现这个问题，必须按照https://github.com/whyour/qinglong/issues/2472 去重新启动才行，这是为啥呢

**Comment by cyxnzb** [comment]
> @cyxnzb 你这启动命令不对啊，看下项目 readme

以及我发现用develop镜像的话，之前遇到的问题基本上都不会复现了

**Comment by whyour** [comment]
> > @cyxnzb 你这启动命令不对啊，看下项目 readme
> 
> 按照readme重新部署后第一次运行还是会出现这个问题，必须按照#2472 去重新启动才行，这是为啥呢

没法复现这个，demo 环境就是每次定时重建的

**Comment by cyxnzb** [comment]
> > > @cyxnzb 你这启动命令不对啊，看下项目 readme
> > 
> > 
> > 按照readme重新部署后第一次运行还是会出现这个问题，必须按照#2472 去重新启动才行，这是为啥呢
> 
> 没法复现这个，demo 环境就是每次定时重建的

啥意思
