### ISSUE TITLE
仓库运行没多久 就提示磁盘满 SequelizeDatabaseError SQLITE_FULL: database or disk is full

### ISSUE THREAD

**Issue by eleven520** [whyour/qinglong#2587]
### Qinglong version

2.17.12

### Steps to reproduce

提示  SequelizeDatabaseError SQLITE_FULL: database or disk is full

### What is expected?

如何解决？

### What is actually happening?

仓库无法运行 提示磁盘溢出

**Comment by whyour** [comment]
这个把磁盘改大？
