### ISSUE TITLE
任务界面能不能添加一个查看脚本的命令

### ISSUE THREAD

**Issue by Acr05s** [whyour/qinglong#259]
有些活动并不入口，希望大佬添加一下，方便查看。

**Comment by whyour** [comment]
你这话前面是啥意思，任务里目前没法关联脚本，只是去运行脚本

**Comment by lxr760** [comment]
> 你这话前面是啥意思，任务里目前没法关联脚本，只是去运行脚本

楼主意思应该跟我之前提的一样，就是多一个查看脚本的页签

**Comment by whyour** [comment]
> > 你这话前面是啥意思，任务里目前没法关联脚本，只是去运行脚本
> 
> 楼主意思应该跟我之前提的一样，就是多一个查看脚本的页签

这个加不了，老兄，除非添加任务的时候关联脚本

**Comment by lxr760** [comment]
> > > 你这话前面是啥意思，任务里目前没法关联脚本，只是去运行脚本
> > 
> > 
> > 楼主意思应该跟我之前提的一样，就是多一个查看脚本的页签
> 
> 这个加不了，老兄，除非添加任务的时候关联脚本

那单独加个查看脚本的页签能否实现？

类似这样

![image](https://user-images.githubusercontent.com/8476457/121284423-66b89f80-c90f-11eb-82df-c37853f385c8.png)

**Comment by whyour** [comment]
> > > > 你这话前面是啥意思，任务里目前没法关联脚本，只是去运行脚本
> > > 
> > > 
> > > 楼主意思应该跟我之前提的一样，就是多一个查看脚本的页签
> > 
> > 
> > 这个加不了，老兄，除非添加任务的时候关联脚本
> 
> 那单独加个查看脚本的页签能否实现？
> 
> 类似这样
> 
> ![image](https://user-images.githubusercontent.com/8476457/121284423-66b89f80-c90f-11eb-82df-c37853f385c8.png)

这个是可以做，但是作用不大吧

**Comment by lxr760** [comment]
> > > > > 你这话前面是啥意思，任务里目前没法关联脚本，只是去运行脚本
> > > > 
> > > > 
> > > > 楼主意思应该跟我之前提的一样，就是多一个查看脚本的页签
> > > 
> > > 
> > > 这个加不了，老兄，除非添加任务的时候关联脚本
> > 
> > 
> > 那单独加个查看脚本的页签能否实现？
> > 类似这样
> > ![image](https://user-images.githubusercontent.com/8476457/121284423-66b89f80-c90f-11eb-82df-c37853f385c8.png)
> 
> 这个是可以做，但是作用不大吧

方便看下脚本里写的活动入口    或者变量环境设置啥的         感觉如果做上这个功能   还是有用的

还请大佬考虑
