### ISSUE TITLE
cdn请求失败（ERR_ADDRESS_INVALID）导致loading白屏的问题

### ISSUE THREAD

**Issue by zbuhui** [whyour/qinglong#2591]
### Qinglong version

2.15.20

### Steps to reproduce

点击’配置文件‘发现页面一直显示’loading‘，调试看了下https://cdn.staticfile.org/monaco-editor/0.33.0/min/vs/loader.js这个请求失败导致。还有几个https://o1098464.ingest.sentry.io/api/6122818/envelope/?sentry_key=3406424。。。这样的，也是ERR_ADDRESS_INVALID

### What is expected?

在cdn出问题的时候能正常加载配置文件、脚本等

### What is actually happening?

我想主要问题还是loader.js这个。想着把cdn地址改一下，但没找到在哪里改。也许手动下载到容器中更好。这两个方式能否开放呢？

**Comment by whyour** [comment]
这块的 cdn 11 个月前都去掉了，使用 最新版镜像即可

**Comment by zbuhui** [comment]
> 这块的 cdn 11 个月前都去掉了，使用 最新版镜像即可

老版本用户有办法吗？用的很稳定，不太想升级
