### ISSUE TITLE
从页面和从命令行都无法升级

### ISSUE THREAD

**Issue by mayishidai** [whyour/qinglong#2593]
### Qinglong version

2.17.9

### Steps to reproduce

![image](https://github.com/user-attachments/assets/7f9677a0-268c-4d3b-b565-112bd7ee67a6)
![image](https://github.com/user-attachments/assets/086b18ef-b454-41e3-9da1-6491651cbbd6)

### What is expected?

正常升级

### What is actually happening?

![image](https://github.com/user-attachments/assets/e69aabed-77d4-4f47-bdf5-b2093d45314b)

**Comment by whyour** [comment]
使用错误提示里的宿主机方式更新
