### ISSUE TITLE
python脚本无法获取环境变量

### ISSUE THREAD

**Issue by DX39** [whyour/qinglong#2597]
### Qinglong version

debian-2.17.12

### Steps to reproduce

所有python脚本都无法获取环境变量，试了好几个系统，还是一样的结果，js脚本就能正常获取。

### What is expected?

修复

### What is actually happening?

有遇到同样问题的人吗

**Comment by whyour** [comment]
无法复现，可以在 demo 环境试试
http://demo.ninesix.cc:4433

**Comment by DX39** [comment]
通过提供的demo 环境测试
：http://demo.ninesix.cc:4433/
测试脚本：`
import os

test = os.environ.get('test')
print(test)`
变量名：test
变量值：123
在脚本管理里面调试脚本输出：`## 开始执行... 2024-12-14 13:22:22


123

## 执行结束... 2024-12-14 13:22:24  耗时 2 秒　`
在定时任务里运行输出：`## 开始执行... 2024-12-14 13:22:56

None

## 执行结束... 2024-12-14 13:22:57  耗时 1 秒　　`

**Comment by DX39** [comment]
`import os

test = os.environ.get('test')
print(test)`

**Comment by whyour** [comment]
> 通过提供的demo 环境测试 ：http://demo.ninesix.cc:4433/ 测试脚本：` import os
> 
> test = os.environ.get('test') print(test)` 变量名：test 变量值：123 在脚本管理里面调试脚本输出：`## 开始执行... 2024-12-14 13:22:22
> 
> 123
> 
> ## 执行结束... 2024-12-14 13:22:24 耗时 2 秒　`
> 在定时任务里运行输出：`## 开始执行... 2024-12-14 13:22:56
> 
> None
> 
> ## 执行结束... 2024-12-14 13:22:57 耗时 1 秒　　`

任务里填的是脚本名称，要么用 task 命令执行，要么就直接脚本名称

**Comment by DX39** [comment]
原理如此，打扰了大佬。
