### ISSUE TITLE
并发执行任务

### ISSUE THREAD

**Issue by leifengwl** [whyour/qinglong#26]
比如设置了多账号，能否根据账号数量均匀分出线程，同时执行活动，这样就不用等前面账号运行完才执行

**Comment by whyour** [comment]
> 比如设置了多账号，能否根据账号数量均匀分出线程，同时执行活动，这样就不用等前面账号运行完才执行

已经有大佬的pr了，下个大版本应该会加

**Comment by landcruser** [comment]
> > 比如设置了多账号，能否根据账号数量均匀分出线程，同时执行活动，这样就不用等前面账号运行完才执行
> 
> 已经有大佬的pr了，下个大版本应该会加

这个就无敌了，不用多容器了，期待

**Comment by leifengwl** [comment]
> > 例如设置了多账号，能否根据账号数量均匀分出线程，同时执行活动，这样就不用等前面账号运行完才执行
> 
> 已经有大佬的pr了，下个大版本应该会加

好的  谢谢

**Comment by w13689226302** [comment]
就等并发了

**Comment by whyour** [comment]
2.0已支持

**Comment by l8higher** [comment]
问一下老哥们，这需要加什么环境变量来打开吗？
