### ISSUE TITLE
Cookie无法添加的问题

### ISSUE THREAD

**Issue by ddy4633** [whyour/qinglong#260]
![image](https://user-images.githubusercontent.com/31069404/120980413-2ccd8900-c7a9-11eb-880f-8b5a58779452.png)

**Comment by fisherxt** [comment]
同遇到。
前端页面一直转圈圈
后端倒是不受影响，脚本执行能正常读取cookie。

**Comment by whyour** [comment]
没法复现，更新下镜像重启下容器

**Comment by fisherxt** [comment]
> 没法复现，更新下镜像重启下容器

又看了下，好像问题是访问这个api

http://[ip]:5700/api/cookies?t=xxxxxxx

响应是 EMPTY 引起的

**Comment by whyour** [comment]
@fisherxt 执行下  ql update 试试，镜像也更新下

**Comment by 0md** [comment]
同遇到。
前端页面一直转圈圈

**Comment by fisherxt** [comment]
> 同遇到。
> 前端页面一直转圈圈

你是不是挂的境外VPS？我自己的情况，经过排查，一直转圈是因为青龙面板会根据cookie从京东api拉取账号信息。如果境外ip访问京东api速度慢，账号又较多的时候，会导致访问api的时间大于JS脚本设定的超时时间（好像是1分钟），这样后端就会传送一个EMPTY响应给前端，前端也就不会载入cookie信息，导致一直转圈圈。

**Comment by 0md** [comment]
> > 同遇到。
> > 前端页面一直转圈圈
> 
> 你是不是挂的境外VPS？我自己的情况，经过排查，一直转圈是因为青龙面板会根据cookie从京东api拉取账号信息，全部cookie的信息都拉取完，传送一个json数据给前端，然后列表显示。如果境外ip访问京东api速度慢，账号又较多的时候，会导致访问api的时间大于JS脚本设定的超时时间（好像是1分钟），这样后端就会传送一个EMPTY响应给前端，前端也就不会载入cookie信息，导致一直转圈圈。

北京华为云，发现是因为账户中含有中文，把中文编码后重新添加就好了
