### ISSUE TITLE
task无法运行脚本，运行1s就结束无任何报错和日志，node运行则正常

### ISSUE THREAD

**Issue by schalkiii** [whyour/qinglong#2600]
### Qinglong version

正式版 v2.17.12

### Steps to reproduce

面板webui 显示运行1s就结束无任何报错和日志
![image](https://github.com/user-attachments/assets/66b6e8ae-14c2-4dc7-b6ab-0bebe05d8665)

进入容器内部使用task 也是相同的结果
![image](https://github.com/user-attachments/assets/890ad89a-ba63-4187-9510-880520a7cf82)

使用node运行则正常
![image](https://github.com/user-attachments/assets/2ab480a7-ddb5-483b-ae2c-046b7086c946)

### What is expected?

ql task应该也要能正常运行js脚本

### What is actually happening?

task无法运行js脚本，运行1s就结束无任何报错和日志，node运行则正常

**Comment by whyour** [comment]
<img width="746" alt="image" src="https://github.com/user-attachments/assets/a2ecece9-bf47-4851-99bc-1ed0acd3dee4" />

demo 环境无法复现 http://demo.ninesix.cc:4433/crontab

检查下自己的 config.sh 和脚本

**Comment by schalkiii** [comment]
我在 http://demo.ninesix.cc:4433 完成了复现。 在有BILI_GITHUB_PROXY这个环境变量的情况下运行smzdm 签到即可复现。
![image](https://github.com/user-attachments/assets/2ba21d5c-8c11-4457-91f1-7c035ba37439)

禁用该变量则恢复正常
![image](https://github.com/user-attachments/assets/d7320fef-f5a0-4b36-b35d-dc3f23794650)

需要注意的是， 这个问题不只在这个脚本上会出现， 也不是在所有js脚本上都会出现。 会出现类似情况的还有Faker库的部分脚本， 我想或许不是js脚本本身的问题？

**Comment by whyour** [comment]
@schalkiii 不用或许，就是脚本问题。你在你脚本里搜索 GITHUB 关键词，我估计你能找到答案

**Comment by whyour** [comment]
env.js 会对有 GITHUB 环境变量时，跳过运行
