### ISSUE TITLE
CommandTimeoutTime设置时间于定时规则冲突

### ISSUE THREAD

**Issue by zzywcjagn** [whyour/qinglong#2601]
### Qinglong version

v2.17.12

### Steps to reproduce

在使用配置文件定义CommandTimeoutTime变量数值大于下一次的定时规则 会导致同一个任务同时运行多个进程

### What is expected?

希望可以添加保持运行的功能，或者在下次定时规则启动的时候之前 结束掉正在运行的脚本

### What is actually happening?

在使用抽奖的脚本需要保持开启，CommandTimeoutTime的变量时间就会大于下次定时规则的时间 就会同时抽奖导致频繁
![image](https://github.com/user-attachments/assets/767d8d0b-96e9-460c-a3a7-7c0456ae395c)

**Comment by whyour** [comment]
目前支持一个任务最多运行 5 个实例，是否删除原来的实例，目前需要自己考虑下

**Comment by zzywcjagn** [comment]
看样子并没有起到作用 我后台显示有的客户端单任务同时运行了16个实例  据了解他定时错误每小时运行了一次，在我修改了脚本自动关闭的话 会修复这个，但是不知道为何会有的时候会把面板的任务状态显示未运行，实际是正在运行。所以希望可以添加一个开关来避免
![image](https://github.com/user-attachments/assets/20321f27-e06d-488e-a8e9-519592f51571)
![image](https://github.com/user-attachments/assets/4240ae2a-f5fe-44be-910f-6b188f7f1b1d)
下面是后台别人运行了16个实例的截图
![677c24866d369c863e15c70c06ffcb8](https://github.com/user-attachments/assets/679b13c2-53b5-4857-8e21-a67035f5d0cd)
