### ISSUE TITLE
重启容器日志中  ./docker/docker-entrypoint.sh: line 20: nginx: command not found

### ISSUE THREAD

**Issue by D06F6E67** [whyour/qinglong#2603]
### Qinglong version

2.17.10

### Steps to reproduce

使用的whyour/qinglong:debian 镜像，升级之后重启了docker然后就看到启动日志里有  ./docker/docker-entrypoint.sh: line 20: nginx: command not found 错误。 同样使用这镜像然后重新构建容器能正常运行，挂载的数据目录是同一个应该不是数据问题。

### What is expected?

原来的容器可以正常启动

### What is actually happening?

启动日志中有  ./docker/docker-entrypoint.sh: line 20: nginx: command not found 异常

**Comment by whyour** [comment]
你的镜像有问题，先更新镜像，再重建下容器
