### ISSUE TITLE
升级到最新版通知配置 $title变量和 $content 替换没有效果

### ISSUE THREAD

**Issue by helwod** [whyour/qinglong#2605]
### Qinglong version

2.17.13

### Steps to reproduce

问题1 ：通知设置参数信息 如WEBHOOK_BODY 字段设置的变量 ，没有更新到 配置文件
![image](https://github.com/user-attachments/assets/b5a34ca3-aeef-4cbb-864d-d0685e8fc70d)
![image](https://github.com/user-attachments/assets/75613cb3-b41d-4d28-90f5-7662d58d4467)
问题2 通知参数获取值是系统参数，$title和$content 变量没有取值导致通知不执行
![image](https://github.com/user-attachments/assets/cbd1094e-235a-4e0c-9ae8-9160e3d6d419)
问题3 通知配置关闭是或者选择的是其他通知时， 还是调用wxpusher 通知日志
![image](https://github.com/user-attachments/assets/455f2720-cda0-401b-bc26-cba5505ee267)

### What is expected?

1.通知设置参数修改保存自动更新配置参数，或者那就不通知就不需要配置参数，
2.上一个版本时正常 设置参数是能正常调用$title和$content 变量 替换的
3.参数url没有设置时，不调用

### What is actually happening?

$title和$content 变量没有取值导致通知不执行

### System Info

```shell
docker ，X86 ，谷歌浏览器
```

**Comment by whyour** [comment]
系统通知和脚本的通知不是同一个，config.sh 配置参考 https://github.com/whyour/qinglong/issues/2303#issuecomment-2001866837
3 只是个提示，可以自己删掉 1272 行
