### ISSUE TITLE
2.17.13青龙，js脚本执行会有 punycode 依赖废弃的提示

### ISSUE THREAD

**Issue by shitou158** [whyour/qinglong#2607]
### Qinglong version

2.17.13

### Steps to reproduce

直接运行一个nodejs脚本
![image](https://github.com/user-attachments/assets/8acbdaee-bcb4-457c-a514-9f5a4840e871)

### What is expected?

这个警告不再显示，其实也无所谓，就是看着别扭

### What is actually happening?

punycode 废弃提示

**Comment by whyour** [comment]
你的镜像不是最新的？http://demo.ninesix.cc:4433/script demo 环境没有

**Comment by shitou158** [comment]
> 你的镜像不是最新的？http://demo.ninesix.cc:4433/script demo 环境没有

![image](https://github.com/user-attachments/assets/c2100ff4-cab8-4f37-8b1e-9c7b6e915f84)
是最新的，今天刚拉的

**Comment by shitou158** [comment]
> 你的镜像不是最新的？http://demo.ninesix.cc:4433/script demo 环境没有

那可能是我本的问题，打扰大佬了

**Comment by shitou158** [comment]
> > 你的镜像不是最新的？http://demo.ninesix.cc:4433/script demo 环境没有
> 
> ![image](https://private-user-images.githubusercontent.com/88788426/397992224-c2100ff4-cab8-4f37-8b1e-9c7b6e915f84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzkwMjksIm5iZiI6MTczNDg3ODcyOSwicGF0aCI6Ii84ODc4ODQyNi8zOTc5OTIyMjQtYzIxMDBmZjQtY2FiOC00ZjM3LThiMWUtOWM3YjZlOTE1Zjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE0NDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMWYxNDA2NDg4ODU0ZGFiNWIyZGQ1MjU3ZGE5Mjg4ZjA2ZWQ2NmQ4MzllZjRiYTFkNDUwYmYzNzIyOWU4NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PIJ-2gUVbNLmeoKuXYkAfOkvrz6MJb1HGcj82_jkPM0) 是最新的，今天刚拉的

我又试了试  只要使用  let request = require("request");  这个 request 依赖就会有提示

**Comment by whyour** [comment]
> request

这个库官方废弃了，换个库吧

**Comment by whyour** [comment]
https://www.npmjs.com/package/request

<img width="871" alt="image" src="https://github.com/user-attachments/assets/9ec6cca0-612c-4608-8479-dd2b57734eef" />
