### ISSUE TITLE
System {"type":"systemConfig"} not found

### ISSUE THREAD

**Issue by Kuron88** [whyour/qinglong#2609]
### Qinglong version

2.17.11

### Steps to reproduce

系统设置--依赖设置，点开就报这个错误System {"type":"systemConfig"} not found

### What is expected?

修复

### What is actually happening?

重新拉的也会这样，最新的版本也有这个问题，然后青龙跑不了京东的脚本

**Comment by whyour** [comment]
https://github.com/whyour/qinglong/issues/2472
