### ISSUE TITLE
无法删除日志

### ISSUE THREAD

**Issue by yuntian123456** [whyour/qinglong#264]
删除日志失败，日志如下：

_开始执行... 2021/6/8上午12:45:15

查找旧日志文件中...
/ql/shell/rmlog.sh: line 11: /bin/ls: Argument list too long
删除旧日志执行完毕
执行结束.._

![image](https://user-images.githubusercontent.com/19453085/121058518-ff0d3200-c7f2-11eb-9485-570914a55547.png)

**Comment by yuntian123456** [comment]
实际查看也确实没有删除任何日志文件

**Comment by whyour** [comment]
最新版已修复
