### ISSUE TITLE
无法运行任务 argument list too long

### ISSUE THREAD

**Issue by qq7984225** [whyour/qinglong#266]
佬 这个问题又出现了 用的vps部署的docker
![04FEC014-373C-49CA-8F36-8B13706E885D](https://user-images.githubusercontent.com/85238021/121098915-75c52200-c829-11eb-85f5-e72eae54b145.jpeg)

**Comment by qq7984225** [comment]
修复不了吗

**Comment by qq7984225** [comment]
？

**Comment by whyour** [comment]
大佬给个pr吧，或者删你账号

**Comment by qq7984225** [comment]
啊这什么意思

**Comment by whyour** [comment]
> 啊这什么意思

出现这个错，就是你加的账号太多了，或者你关闭 autohelp

**Comment by qq7984225** [comment]
好吧我才加了20个

**Comment by whyour** [comment]
@qq7984225 不可能吧，你看你code目录的文件多长

**Comment by qq7984225** [comment]
之前重复加了cookie 最新的有1100行

**Comment by whyour** [comment]
@qq7984225 20个号这么长？

**Comment by qq7984225** [comment]
code log里面显示65个cookie。。啊这

**Comment by whyour** [comment]
@qq7984225 结案了吧

**Comment by qq7984225** [comment]
大佬辛苦了

**Comment by fzls** [comment]
试试这个方案
[解决 青龙面板中存放的cookie数目过多（如超过45）时，会报 Argument list too long 而无法正常执行部分脚本的问题](https://gist.github.com/fzls/14f8d1d3ebb2fef64750ad91d268e4f6)
