### ISSUE TITLE
6月7日更新了2.2以后，不读取写在config.sh里的助力码了。

### ISSUE THREAD

**Issue by danteswx** [whyour/qinglong#267]
因为cfd的助力码现在读不出来，所以更新前一直写在config.sh里，以前一直正常的，昨天更新后，运行cfd，助力码读取不到了，刚才试了把助力码写到log里，能正确读取。请检查下昨天的更新有没有这方面的问题。

**Comment by lynn0804** [comment]
![image](https://user-images.githubusercontent.com/52002734/121140990-11c44d00-c86d-11eb-8d82-c4308875b3e4.png)
ye页面无法加载出来了  一片空白
