### ISSUE TITLE
Cookie界面几个建议

### ISSUE THREAD

**Issue by lxr760** [whyour/qinglong#268]
1、增加账号重复检测功能，当添加Cookie时，检测是否和现有账号冲突，如已存在，弹个对话框询问是否覆盖。以免列表中出现2个同样的Cookie

2、除昵称列、增加京东ID列、备注列

脚本的提醒好像是按京东ID来的，会和昵称对不上。（ID列原来有的，后来的版本不知道为什么去掉了）

备注列用于自己填写信息，方便区分账号。特别是Cookie过期时，昵称列会消失，找对应的账号人非常麻烦

**Comment by strawferry** [comment]
建议能否通过 扫码直接获取 cookie 然后直接替换,这样比较快捷方便
