### ISSUE TITLE
更新4月10日下午镜像后，手动不能添加cookie。

### ISSUE THREAD

**Issue by reviveymj** [whyour/qinglong#27]
[qinglong] 你好 
今天下午更新了最新的镜像，目前手动无法添加cookie。显示NOT FOUND
尝试替换之前备份的cookie.sh  进入面板 没有cookie显示。右上角仍然显示 NOT FOUND。只是面板不显示但其实添加成功。还可以运行脚本任务。

**Comment by reviveymj** [comment]
![image](https://user-images.githubusercontent.com/78457555/114267837-a4449d80-9a30-11eb-9d2e-f6340621163c.png)

**Comment by reviveymj** [comment]
![image](https://user-images.githubusercontent.com/78457555/114267869-d0601e80-9a30-11eb-9981-0ef23787d11c.png)

**Comment by reviveymj** [comment]
![image](https://user-images.githubusercontent.com/78457555/114267929-20d77c00-9a31-11eb-9b00-20c89e89e44f.png)
![image](https://user-images.githubusercontent.com/78457555/114267977-5d0adc80-9a31-11eb-8e54-5e961014204f.png)
替换了之前的cookie.sh后，cookie其实成功添加的。但是面板不显示

**Comment by whyour** [comment]
rebuild 下

**Comment by reviveymj** [comment]
面板已经从新rebuild过了，全部删除镜像容器，映射目录也全部删除 从新拉去镜像。依旧如此。不知道是哪里的问题。
![image](https://user-images.githubusercontent.com/78457555/114270201-b2e58180-9a3d-11eb-8d8c-9ecbbe9568e3.png)
docker run -dit \
   -v /opt/docker/qinglong/config:/ql/config \
   -v /opt/docker/qinglong/log:/ql/log \
   -v /opt/docker/qinglong/db:/ql/db \
   -v /opt/docker/qinglong/scripts:/ql/scripts \
   -p 5777:5700 \
   -e ENABLE_HANGUP=true \
   -e ENABLE_WEB_PANEL=true \
   --name qinglong \
   --hostname qinglong \
   --restart always \
   --network bridge \
   whyour/qinglong:latest

**Comment by reviveymj** [comment]
解决了 ，我从新清除了一下chrome的cookie。

**Comment by reviveymj** [comment]
![image](https://user-images.githubusercontent.com/78457555/114270562-a8c48280-9a3f-11eb-9960-99a01fe07712.png)
清理完浏览器的cookie，一切正常了

**Comment by cno888888** [comment]
还有个解决办法就是，删除cookie。sh的文件，然后重启面板，可以暂时解决，当然ck要重新添加，所以建议备份，这样方便下次一次性添加全部ck，但是问题还是会存在的，不能根治，所以，大佬看看是什么原因导致的

**Comment by whyour** [comment]
> ![image](https://user-images.githubusercontent.com/78457555/114270562-a8c48280-9a3f-11eb-9960-99a01fe07712.png)
> 清理完浏览器的cookie，一切正常了

应该是你刷新页面就行了，rebuild完要刷新页面

**Comment by whyour** [comment]
> 还有个解决办法就是，删除cookie。sh的文件，然后重启面板，可以暂时解决，当然ck要重新添加，所以建议备份，这样方便下次一次性添加全部ck，但是问题还是会存在的，不能根治，所以，大佬看看是什么原因导致的

ck现在是数据库存储，和cookie.sh 没关系，要映射db目录，你看看频道的指南

**Comment by cno888888** [comment]
> > 还有个解决办法就是，删除cookie。sh的文件，然后重启面板，可以暂时解决，当然ck要重新添加，所以建议备份，这样方便下次一次性添加全部ck，但是问题还是会存在的，不能根治，所以，大佬看看是什么原因导致的
> 
> ck现在是数据库存储，和cookie.sh 没关系，要映射db目录，你看看频道的指南

我是路由器docker，直接看日志，启动容器没问题，但是找不到或获取不到ck。sh文件，不存在文件权限的问题，就是因为获取不到ck，sh文件，导致面板启动不来，解决办法就是路由器ssh登录删除ck。sh文件，不用重建，然后重启容器就行了，
