### ISSUE TITLE
临时屏蔽ck的功能，把未指定的脚本也屏蔽了

### ISSUE THREAD

**Issue by sducxh** [whyour/qinglong#270]
配置：
# 屏蔽京喜牧场 3 4 5账号不执行
case $1 in
   raw_jx_mc)
     TempBlockCookie="3 4 5"
     ;;
esac

运行：
# 运行红包雨脚本，把上面配置的屏蔽账号也屏蔽了
开始执行... 2021/6/8下午12:32:45

🔔618主会场红包雨, 开始!

====================共2个京东账号Cookie=========

**Comment by whyour** [comment]
@sducxh 加文件后缀

**Comment by sducxh** [comment]
> @sducxh 加文件后缀

thx，没有看sample的注释
另外，注释掉配置，按理应该账号解禁，可还是在被屏蔽

**Comment by sducxh** [comment]
> > @sducxh 加文件后缀
> 
> thx，没有看sample的注释
> 另外，注释掉配置，按理应该账号解禁，可还是在被屏蔽

重启容器也不行，从容器日志看 有的任务执行所有账号，有的还是在屏蔽。

**Comment by sducxh** [comment]
从面板执行的任务 依旧读取的屏蔽配置；在容器内用task命令 执行的全部帐号

**Comment by ycyfff** [comment]
同一个问题，加了.js后缀，会执行屏蔽当前任务，同时，也会屏蔽其他任务。请大佬修复。

**Comment by whyour** [comment]
我测试了下，没这个问题。你看你们的参数对不对

**Comment by GFBG-IT** [comment]
我这边也有这个问题，后缀名也是有的
case $1 in
chinnkarahoi_jd_scripts_jd_jxnc.js )
TempBlockCookie="8"
;;
chinnkarahoi_jd_scripts_jd_jxmc.js )
TempBlockCookie="3 4 5 6 7 8"
;;
esac
从面板运行脚本会屏蔽掉3 4 5 6 7 8

**Comment by whyour** [comment]
@GFBG-IT 所有脚本都会屏蔽掉？

**Comment by GFBG-IT** [comment]
@whyour 是的，所有的脚本都会屏蔽掉，注释了case还是存在，只能重启容器恢复正常

**Comment by ycyfff** [comment]
> @whyour 是的，所有的脚本都会屏蔽掉，注释了case还是存在，只能重启容器恢复正常

对的，面板上运行其他脚本也会被屏蔽

**Comment by whyour** [comment]
@ycyfff 注释了不能恢复的问题确认了，把tempcookie设置为空就可以恢复

**Comment by whyour** [comment]
最新版已修复

**Comment by ycyfff** [comment]
面板执行任务任然会
