### ISSUE TITLE
日志不显示，是什么问题，文件夹里有日志

### ISSUE THREAD

**Issue by okboy32** [whyour/qinglong#271]
![image](https://user-images.githubusercontent.com/19381683/121129679-e129e680-c85f-11eb-8b4e-255abfa05cde.png)
![image](https://user-images.githubusercontent.com/19381683/121129750-fd2d8800-c85f-11eb-83b5-695bb9363091.png)

**Comment by whyour** [comment]
首先日志在右上角选择，其次更新下你的版本
![image](https://user-images.githubusercontent.com/22700758/121141827-f9a0fd80-c86d-11eb-9d67-88da3f8eed83.png)
最新版有版本号 https://t.me/jiaolongwang/102
