### ISSUE TITLE
大佬新版我发现个问题，之前配置文件是增加 chinnkarahoi，现在需要增加chinnkarahoi_jd_scripts

### ISSUE THREAD

**Issue by dreamfrog7** [whyour/qinglong#272]
大佬新版我发现个问题，之前配置文件是增加 chinnkarahoi，现在需要增加chinnkarahoi_jd_scripts，不然执行ql code会提示未运行过日志，这样修改了配置文件后，导致机器人无法正常运行了。
机器人运行 /bean 1 ,提示 something wrong,I'm sorry
[Errno 2] No such file or directory: '/ql/log/chinnkarahoi_jd_bean_change/'
说明机器人默认调用的是 chinnkarahoi_jd_bean_change 这个日志，但是实际上产生的日志是 chinnkarahoi_jd_scripts_jd_bean_change 就是差了 jd_scripts 这个路径，如果不加这个路径的话，就没法ql code....
很是矛盾，请大佬指点下。

**Comment by whyour** [comment]
@dreamfrog7 你的bot代码有点老，去找个新点的吧

**Comment by dreamfrog7** [comment]
> @dreamfrog7 你的bot代码有点老，去找个新点的吧

大佬，从哪里找新的，请指示下，谢谢

**Comment by dreamfrog7** [comment]
> @dreamfrog7 我也不知道，原作者私有了

能提供个比较新的吗？
群里发的那个机器人备份的行吗？我用的那个jbot，还有一个整体项目备份，哪个比较新呢？请赐教，谢谢

**Comment by dreamfrog7** [comment]
> @dreamfrog7 我也不知道，原作者私有了

我邮箱 bddsxxk@163.com能分享下吗？

**Comment by whyour** [comment]
@dreamfrog7 我是不知道，不是我不给你？

**Comment by dreamfrog7** [comment]
> @dreamfrog7 我是不知道，不是我不给你？

好的谢谢谢谢大佬指点

**Comment by dreamfrog7** [comment]
> @dreamfrog7 我是不知道，不是我不给你？

dalao 

> @dreamfrog7 我是不知道，不是我不给你？

大佬，执行ql code的时候提示未运行，是不是必须得修改配置文件，增加jd_scripts路径？

**Comment by whyour** [comment]
@dreamfrog7 是的，你去github上找找别人的备份

**Comment by dreamfrog7** [comment]
谢谢大佬 感谢感谢

**Comment by dreamfrog7** [comment]
用了网上的备份的，还是报错。。。。

**Comment by dreamfrog7** [comment]
[https://mopo-blog.ddnsfree.com/2021/05/14/qinglong-docker-config/#more](url) 用的这个教程 还是报错

**Comment by dreamfrog7** [comment]
> @dreamfrog7 是的，你去github上找找别人的备份

大佬，搞定了。。。找的新的代码，谢谢感谢大佬，打扰多时，见谅，也是一种迫切学习的态度，比较心急，大佬多见谅。

**Comment by l8higher** [comment]
兄弟可以给一下新的代码吗
