### ISSUE TITLE
老哥求问一下昨晚更新的go-cqhttp推送问题

### ISSUE THREAD

**Issue by w1915591935** [whyour/qinglong#274]
配置如下: [https://cdn.jsdelivr.net/gh/w1915591935/yimuapp.cn@master/mmexport1623148708438.jpg](url) 
我的理解是:
export GOBOT_URL ="http://127.0.0.1/send_group_msg"
export GOBOT_TOKEN = "访问秘钥"
export GOBOT_QQ = "qq群号"
go-cqhttp运行图
[https://cdn.jsdelivr.net/gh/w1915591935/yimuapp.cn@master/20210608012212.png](url)

**Comment by Fcatme** [comment]
GOBOT_URL 里面大概是需要填入 http://127.0.0.1:5700/send_group_msg

**Comment by Fcatme** [comment]
export GOBOT_QQ="group_id=QQ群号"

**Comment by z594024037** [comment]
> GOBOT_URL 里面大概是需要填入 http://127.0.0.1:5700/send_group_msg

请问gocq那边的配置是需要设置哪里 监听http还是正向ws什么的 我的青龙和gocq不在同一个服务器上

**Comment by Fcatme** [comment]
监听http
