### ISSUE TITLE
重启容器费了，找不到原因

### ISSUE THREAD

**Issue by cjh19831115** [whyour/qinglong#276]
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'
/ql/shell/share.sh: eval: line 59: unexpected EOF while looking for matching `"'

**Comment by whyour** [comment]
什么设备

**Comment by cjh19831115** [comment]
> 什么设备

n1盒子，刷的荒野无灯的固件，我只能把镜像配置文件全部删除，重新搞了一遍，现在好了

**Comment by wangbo667** [comment]
我也是，删了重新下载总是重启中
