### ISSUE TITLE
请问一下大佬，能不能留个联系方式指导一下，运行起来了，不知道咋生效

### ISSUE THREAD

**Issue by 1477553657** [whyour/qinglong#284]
现在是在docker容器里面运行起来了，项目也可以跑起来，OA管理系统也跑起来了，Session管理里面加入了自己在京东的pt_key=***;pt_pin=***;但是就是不生效，请大佬伸出援助之手，指点迷津

**Comment by whyour** [comment]
> 现在是在docker容器里面运行起来了，项目也可以跑起来，OA管理系统也跑起来了，Session管理里面加入了自己在京东的pt_key=_**;pt_pin=**_;但是就是不生效，请大佬伸出援助之手，指点迷津

用最新的容器重新试试

**Comment by lxr760** [comment]
OA管理系统 是啥

**Comment by 1477553657** [comment]
![image](https://user-images.githubusercontent.com/30653545/121453325-95984980-c9d3-11eb-8fc7-f28111302669.png)
![image](https://user-images.githubusercontent.com/30653545/121453377-a9dc4680-c9d3-11eb-9eec-22a8c738720d.png)
就是这个系统，不起作用，也不知道这些脚本咋触发

**Comment by whyour** [comment]
https://t.me/jiaolongwang  读读指南吧

**Comment by 1477553657** [comment]
大佬，恕我愚钝，你的指南里面值放了2个仓库地址，仓库进去README也没有具体使用说明啊，我真的是研究不明白了，求指点


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whyour/qinglong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月10日(星期四) 晚上9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whyour/qinglong] 请问一下大佬，能不能留个联系方式指导一下，运行起来了，不知道咋生效 (#284)





 
https://t.me/jiaolongwang  读读指南吧
