### ISSUE TITLE
容器总是重启中

### ISSUE THREAD

**Issue by wangbo667** [whyour/qinglong#286]

**Comment by wangbo667** [comment]
![image](https://user-images.githubusercontent.com/83823602/121295866-50680f00-c922-11eb-90ae-8d24cf687a24.jpeg)

**Comment by wangbo667** [comment]
![image](https://user-images.githubusercontent.com/83823602/121295940-6ece0a80-c922-11eb-9ac3-f8c8a5137554.jpeg)![image](https://user-images.githubusercontent.com/83823602/121295941-6ece0a80-c922-11eb-81da-6db3bd6a9353.jpeg)

**Comment by wangbo667** [comment]
删容器后重新载入就这样了

**Comment by Ouyuzhi** [comment]
删除config.sh文件第113行114行115行=号后面的空格
![image](https://user-images.githubusercontent.com/24583123/121310991-8b743d80-c936-11eb-98ef-bf68388dfbfc.png)
