### ISSUE TITLE
有一个很玄学的问题

### ISSUE THREAD

**Issue by ylwzbk** [whyour/qinglong#292]
日志提示 ：🔔618主会场红包雨, 开始!

==============📣系统通知📣==============
618主会场红包雨
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取
https://bean.m.jd.com/bean/signIndex.action

🔔618主会场红包雨, 结束! 🕛 0.009 秒
面板添加了 cookie依旧这样

**Comment by Acr05s** [comment]
我今天从5点开始也变这样了，重新拉了docker直接不运行js了

**Comment by ylwzbk** [comment]
重启已经死机.......

**Comment by yuntian123456** [comment]
是大佬要跑路了，删除了所有脚本内容，都变成空白了……且用且珍惜吧……
