### ISSUE TITLE
又出现了识别不了cookie 的bug

### ISSUE THREAD

**Issue by YYplus** [whyour/qinglong#295]
反复执行更新解决不了问题

**Comment by Mountaincnc** [comment]
是这样吗
[![2gJIMV.png](https://z3.ax1x.com/2021/06/10/2gJIMV.png)](https://imgtu.com/i/2gJIMV)
填入cookie后点击确定 一直转圈
F12有500报错
[![2gYERI.png](https://z3.ax1x.com/2021/06/10/2gYERI.png)](https://imgtu.com/i/2gYERI)
