### ISSUE TITLE
关于批量添加定时任务的问题

### ISSUE THREAD

**Issue by MangoDong** [whyour/qinglong#296]
是否可以批量选择本地任务。

**Comment by lxr760** [comment]
同问


原因大家都懂

**Comment by Acr05s** [comment]
直接编辑crontab.list

**Comment by lxr760** [comment]
> 直接编辑crontab.list

保存里面web里面看不生效

**Comment by MangoDong** [comment]
编辑完，重启



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月10日(周四) 上午10:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whyour/qinglong] 关于批量添加定时任务的问题 (#296)




  
直接编辑crontab.list
  
保存以后web里面看不生效
