### ISSUE TITLE
请问在线同步脚本的时候，名字怎么不加前缀

### ISSUE THREAD

**Issue by lxr760** [whyour/qinglong#297]
比如之前用的是chinnkarahoi库

添加以后  脚本会有chinnkarahoi_jd_scripts_***这样的前缀

如果去掉这个       添加以后脚本名字直接为jd_***.js

**Comment by 1477553657** [comment]
大佬，我运行起来了，但是不能做京东任务，咋办，可以指点一下吗，那个控制面板定时任务不生效

**Comment by whyour** [comment]
你可以用 ql repo 命令的依赖文件参数 拉取的都不带前缀，然后手动加任务
