### ISSUE TITLE
能否加入webshell功能 

### ISSUE THREAD

**Issue by liu269569205** [whyour/qinglong#298]
直接网页端操作命令行

**Comment by whyour** [comment]
这个功能的作用体现在哪

**Comment by liu269569205** [comment]
就是 不要开ssh客户端  直接在web界面操作命令 类似群晖的gateone

**Comment by imwcc** [comment]
webshell 对于高级用户用起来非常方便
不用每次都 ssh，然后docker exec, 省事。
