### ISSUE TITLE
昨天6.9 -6.10更新问题

### ISSUE THREAD

**Issue by Acr05s** [whyour/qinglong#299]
1。应该5点左右自动更新后，提示
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取 https://bean.m.jd.com/
2。重新拉docker后，定时任务似乎没有自动运行
查看日志，面板启动后无动作，终端ps查看也无新增进程 
3。删除所有任务后重新拉库
老佬自己库可以正确添加任务，lxk库无法识别任务名，而且定时都都设置为0 6 * * * 
4。手机执行的任务直接显示任务结束

**Comment by Hyy2001X** [comment]
+1,今天9点多尝试全新安装，手动执行任务同样是提示请先获取京东账号一cookie，定时任务都是0 6 * * *，有些执行任务直接结束

**Comment by Acr05s** [comment]
> +1,今天9点多尝试全新安装，手动执行任务同样是提示请先获取京东账号一cookie，定时任务都是0 6 * * *，有些执行任务直接结束

--------------------------
我好像看到LXK库文件全是1k,没内容了。

**Comment by cynizy** [comment]
我用n1刷的joy1大神的ce双系统，docker跑脚本，从6月8号开始控制面板一直打不开，怎么更新都打不开，求大神看看

**Comment by Acr05s** [comment]
> +1,今天9点多尝试全新安装，手动执行任务同样是提示请先获取京东账号一cookie，定时任务都是0 6 * * *，有些执行任务直接结束

看大佬恢复了，应该是有个搞破坏删了内容

**Comment by ldcr1319** [comment]
> 我用n1刷的joy1大神的ce双系统，docker跑脚本，从6月8号开始控制面板一直打不开，怎么更新都打不开，求大神看看

按f12看一下,我早晨也说打不开,发现是几个js文件下载不下来
