### ISSUE TITLE
手动运行定时任务 只会运行一个ck，提示  共1个京东账号Cookie   如果到定时的时间点自动运行就不会这样

### ISSUE THREAD

**Issue by buse88** [whyour/qinglong#301]
手动运行定时任务 只会运行一个ck，提示  共1个京东账号Cookie   如果到定时的时间点自动运行就不会这样

**Comment by kirito8** [comment]
> 手动运行定时任务 只会运行一个ck，提示 共1个京东账号Cookie 如果到定时的时间点自动运行就不会这样

我手动运行会提示Error: Cannot find module './jdCookie.js'
