### ISSUE TITLE
助力码会增加奇怪的my

### ISSUE THREAD

**Issue by 9527cfc** [whyour/qinglong#304]
运行qc code脚本获取助力码，在多次运行该脚本，或者服务器长时间运行后，会增加my的数量，导致需要经常修改配置文件中的前缀。
我没有定位到错误所在，因为我找不到脚本文件在哪里。
尝试清除所有日志能暂时解决，但第二天会复现。
另外，清除旧日志，如何改成清除今天之外所有日志。

**Comment by Acr05s** [comment]
定时任务 ql rmlog 7 就是删除的7日前，改成2或者1？
--

**Comment by 9527cfc** [comment]
好的我试试

**Comment by 9527cfc** [comment]
现在清除所有日志也仍然会增加my了，我现在是mymymyfruit1

**Comment by whyour** [comment]
https://t.me/jiaolongwang  看看最新的指南吧，用最新的镜像试试
