### ISSUE TITLE
❗️京喜工厂商品列表详情, 发生错误!

### ISSUE THREAD

**Issue by shyg866** [whyour/qinglong#305]
SyntaxError: Unexpected token u in JSON at position 0

> at JSON.parse (<anonymous>)

> at /ql/scripts/whyour_jx_products_detail.js:64:70

> at /ql/scripts/whyour_jx_products_detail.js:121:3984

> at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by whyour** [comment]
脚本删了吧
