### ISSUE TITLE
有没有详细的教程啊

### ISSUE THREAD

**Issue by 13071558875** [whyour/qinglong#307]
docker run -dit \
   -v $PWD/ql/config:/ql/config \
   -v $PWD/ql/log:/ql/log \
   -v $PWD/ql/db:/ql/db \
   -p 5700:5700 \
   --name qinglong \
   --hostname qinglong \
   --restart always \
   whyour/qinglong:latest
卡在了这里，不知道这个怎么用

**Comment by 13071558875** [comment]
> docker run -dit
> -v $PWD/ql/config:/ql/config
> -v $PWD/ql/log:/ql/log
> -v $PWD/ql/db:/ql/db
> -p 5700:5700
> --name qinglong
> --hostname qinglong
> --restart always
> whyour/qinglong:latest
> 卡在了这里，不知道这个怎么用

面板登录提示密码错误是怎么回事

**Comment by whyour** [comment]
https://t.me/jiaolongwang  看使用指南

**Comment by 13071558875** [comment]
> https://t.me/jiaolongwang 看使用指南

折腾了半天，用服务器弄好了。本地不知道怎么操作
