### ISSUE TITLE
手动执行脚本报错

### ISSUE THREAD

**Issue by kirito8** [whyour/qinglong#308]
手动执行脚本时会报错，提示Error: Cannot find module './jdCookie.js'
![image](https://user-images.githubusercontent.com/22957293/121509779-905ded80-ca19-11eb-8342-6b138ccceaf3.png)

**Comment by wanghaolyj** [comment]
怎么解决的

**Comment by wanghaolyj** [comment]
> 手动执行脚本时会报错，提示Error: Cannot find module './jdCookie.js'
> ![image](https://user-images.githubusercontent.com/22957293/121509779-905ded80-ca19-11eb-8342-6b138ccceaf3.png)

怎么解决的，我也出现这个问题了
