### ISSUE TITLE
最新版的cookie界面怎么把昵称给去掉了

### ISSUE THREAD

**Issue by lxr760** [whyour/qinglong#31]
账号的用户名和昵称     有的人一样       有的人不一样

建议用户名 昵称都保留       方便查看账号

**Comment by whyour** [comment]
> 账号的用户名和昵称 有的人一样 有的人不一样
> 
> 建议用户名 昵称都保留 方便查看账号

因为多账号获取耗时很长，改成异步验证状态了，查看账户，你可以在ck后面补充你要的信息

**Comment by nick814** [comment]
如何在ck后面补充自己要的账号备注啊 我更新好了最新的 账户会自动排序了  我原来记录下来的次序都乱了

**Comment by nick814** [comment]
我发现我就一个docker 弄上去次序乱了 其他docker都次序对的。。。 妖怪

**Comment by whyour** [comment]
> 我发现我就一个docker 弄上去次序乱了 其他docker都次序对的。。。 妖怪

可以拖拽排序
