### ISSUE TITLE
在面板手动执行任务报错

### ISSUE THREAD

**Issue by DarkAge2018** [whyour/qinglong#312]
只在定时任务里面的日志才会出现
`/usr/local/bin/task: line 14: [[: "3: syntax error: operand expected (error token is ""3")
/usr/local/bin/task: line 14: [[: 4": syntax error: invalid arithmetic operator (error token is """)`
一直重复这个，有几十行，然后可以正常运行脚本
而在命令行执行task命令却没有上述错误提示
日志文件里面也没有

只要有cookie就报错，全部禁用之后也不会出现

**Comment by whyour** [comment]
这个貌似是你加了  tempBlockCookie  你看下你的配置文件吧
