### ISSUE TITLE
如何拉取同一个库里的多分支？

### ISSUE THREAD

**Issue by jogn61** [whyour/qinglong#315]
请问如何拉取同一个库里的不同的分支，希望完善拉取脚本库五个参数的逻辑说明。
另外两个建议：
1.建议把脚本库定时与脚本任务定时分开显示，以便于管理。
2.建议增加取消订阅功能，比如取消订阅某一个脚本库后自动删除相关定时任务并清理数据。

**Comment by whyour** [comment]
执行 ql repo 就能看见，订阅功能可以得3.0了，先关闭了
