### ISSUE TITLE
能否加入一个按时间线显示所有日志的功能

### ISSUE THREAD

**Issue by fqxufo** [whyour/qinglong#318]
类似github actions的界面效果，一个列表按时间先后顺序显示所有任务的日志

**Comment by whyour** [comment]
算是一个功能，但是优先级比较低

**Comment by lxr760** [comment]
不过有个问题，如果同时有2个或以上的脚本同时运行，中间脚本就会互相插


我在docker里看屏显就是这样，所有在跑的脚本都不停的刷屏
