### ISSUE TITLE
能否添加分页变量

### ISSUE THREAD

**Issue by xianyu21** [whyour/qinglong#319]

**Comment by whyour** [comment]
给谁添加分页变量

**Comment by xianyu21** [comment]
> 给谁添加分页变量

给定时任务添加一个分页 变量
因为我的屏幕比较小
需要滚动屏幕去选择分页
有时候手动运行任务 运行图标并没有发生改变
就需要刷新去查看任务 之前选好的分页 也恢复成默认了

**Comment by whyour** [comment]
下个版本，定时任务分页中设置每页调试永久生效
