### ISSUE TITLE
添加定时任务不能添加了

### ISSUE THREAD

**Issue by shusheng110** [whyour/qinglong#32]
添加和修改定时任务均不能点确定，点了没有反应~

**Comment by whyour** [comment]
@shusheng110 截图看看，用最新的镜像试试或者rebuild下

**Comment by shusheng110** [comment]
![image_2021-04-11_19-17-25](https://user-images.githubusercontent.com/33216795/114302205-98bda900-9afa-11eb-9903-9edebd5ef700.png)
就这个界面 怎么点都不行 没反应 镜像是拉的最新的 rebuild也试过了

**Comment by whyour** [comment]
@shusheng110 这不是编辑任务吗，还是新建任务
是点确定没反应吗，右键查看元素，进console看有没有报错

**Comment by shusheng110** [comment]
> @shusheng110 这不是编辑任务吗，还是新建任务
> 是点确定没反应吗，右键查看元素，进console看有没有报错

![QQ截图20210411200940](https://user-images.githubusercontent.com/33216795/114303665-e38eef00-9b01-11eb-8374-6779f7a6d981.png)
怎么点击都没反应，这是编辑的 console 也没有任何显示

**Comment by shusheng110** [comment]
![QQ截图20210411201125](https://user-images.githubusercontent.com/33216795/114303712-1c2ec880-9b02-11eb-80cf-b1ca5b5f7d56.png)
有错误出现了

**Comment by whyour** [comment]
> ![QQ截图20210411201125](https://user-images.githubusercontent.com/33216795/114303712-1c2ec880-9b02-11eb-80cf-b1ca5b5f7d56.png)
> 有错误出现了

这都是超时，你是不是容器的pm2服务有问题了
你先执行  `docker exec -it qinglong pm2 logs -f panel`

然后再点确定看看

**Comment by shusheng110** [comment]
![QQ截图20210411202049](https://user-images.githubusercontent.com/33216795/114303997-6f554b00-9b03-11eb-95f8-e8c4aa79409c.png)
运行之后出现这个 然后点了还没反应 @whyour

**Comment by whyour** [comment]
> ![QQ截图20210411202049](https://user-images.githubusercontent.com/33216795/114303997-6f554b00-9b03-11eb-95f8-e8c4aa79409c.png)
> 运行之后出现这个 然后点了还没反应 @whyour

你有todesk吗，远程看看，这可能是网络问题吧，因为接口都超时了

**Comment by shusheng110** [comment]
> > ![QQ截图20210411202049](https://user-images.githubusercontent.com/33216795/114303997-6f554b00-9b03-11eb-95f8-e8c4aa79409c.png)
> > 运行之后出现这个 然后点了还没反应 @whyour
> 
> 你有todesk吗，远程看看，这可能是网络问题吧，因为接口都超时了

------------------ToDesk-------------------
请使用ToDesk对我电脑进行远程控制
我的设备代码:550 295 744 连接密码:233875
ToDesk下载地址:
https://www.ToDesk.com

**Comment by whyour** [comment]
> > ![QQ截图20210411202049](https://user-images.githubusercontent.com/33216795/114303997-6f554b00-9b03-11eb-95f8-e8c4aa79409c.png)
> > 运行之后出现这个 然后点了还没反应 @whyour
> 
> 你有todesk吗，远程看看，这可能是网络问题吧，因为接口都超时了

已修复，rebuild下
