### ISSUE TITLE
出现奇怪的错误？列表过长？

### ISSUE THREAD

**Issue by 9527cfc** [whyour/qinglong#320]
日志-京喜农场
开始执行... 2021/6/12下午6:51:44

/usr/local/bin/task: line 20: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 20: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 20: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 20: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 20: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 20: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 20: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 20: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 20: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 20: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 118: /bin/date: Argument list too long
/usr/local/bin/task: line 123: /usr/bin/tee: Argument list too long

执行结束...

**Comment by fzls** [comment]
试试这个方案
[解决 青龙面板中存放的cookie数目过多（如超过45）时，会报 Argument list too long 而无法正常执行部分脚本的问题](https://gist.github.com/fzls/14f8d1d3ebb2fef64750ad91d268e4f6)
