### ISSUE TITLE
拉取仓库0 6 * * * 错误

### ISSUE THREAD

**Issue by Fcatme** [whyour/qinglong#325]
如果拉取其它仓库大部分脚本 任务定时都是0 6 * * * 
![image](https://user-images.githubusercontent.com/33803252/121783644-64419880-cbe2-11eb-8687-4363694355d0.png)

这是什么BUG 如果是读取仓库docker文件夹里面的crontab_list.sh的话 讲道理里面的配置是没什么问题

**Comment by sstakill** [comment]
看那个库吧！我拉取也会这样。直接服务器改，没用，一刷新就覆盖了。我最后放弃那个库了(脚本几十个懒得改了)

**Comment by whyour** [comment]
这个建议你删掉异常的定时任务，然后再执行下ql repo命令

**Comment by Fcatme** [comment]
> 这个建议你删掉异常的定时任务，然后再执行下ql repo命令

这个方式我操作过了 看到你在TG频道推送过类似问题 重新 ql repo后依旧是这样

**Comment by whyour** [comment]
> > 这个建议你删掉异常的定时任务，然后再执行下ql repo命令
> 
> 这个方式我操作过了 看到你在TG频道推送过类似问题 重新 ql repo后依旧是这样

是最新的镜像？确认是不是真的脚本中没写cron表达式

**Comment by Fcatme** [comment]
> > > 这个建议你删掉异常的定时任务，然后再执行下ql repo命令
> > 
> > 
> > 这个方式我操作过了 看到你在TG频道推送过类似问题 重新 ql repo后依旧是这样
> 
> 是最新的镜像？确认是不是真的脚本中没写cron表达式

是最新镜像 如果是只读取脚本中的表达式 那还真是我这边问题 。。 有部分脚本里面没有带表达式。 但是 仓库docker文件里的 crontab_list.sh 包含了所有脚本的cron表达式...

**Comment by whyour** [comment]
> > > > 这个建议你删掉异常的定时任务，然后再执行下ql repo命令
> > > 
> > > 
> > > 这个方式我操作过了 看到你在TG频道推送过类似问题 重新 ql repo后依旧是这样
> > 
> > 
> > 是最新的镜像？确认是不是真的脚本中没写cron表达式
> 
> 是最新镜像 如果是只读取脚本中的表达式 那还真是我这边问题 。。 有部分脚本里面没有带表达式。 但是 仓库docker文件里的 crontab_list.sh 包含了所有脚本的cron表达式...

目前不支持读取仓库的 crontab.list，因为有的仓库可能没有，还没想好这块怎么做

**Comment by Fcatme** [comment]
> > > > > 这个建议你删掉异常的定时任务，然后再执行下ql repo命令
> > > > 
> > > > 
> > > > 这个方式我操作过了 看到你在TG频道推送过类似问题 重新 ql repo后依旧是这样
> > > 
> > > 
> > > 是最新的镜像？确认是不是真的脚本中没写cron表达式
> > 
> > 
> > 是最新镜像 如果是只读取脚本中的表达式 那还真是我这边问题 。。 有部分脚本里面没有带表达式。 但是 仓库docker文件里的 crontab_list.sh 包含了所有脚本的cron表达式...
> 
> 目前不支持读取仓库的 crontab.list，因为有的仓库可能没有，还没想好这块怎么做

或许可以给 ql repo 增加读取目录crontab.list文件参数 比如 -cron_docker 优先读取docker文件里面的crontab来设定脚本的cron执行时间 如果没带这个参数就直接读取脚本里面的cron表达式。

**Comment by whyour** [comment]
> > > > > > 这个建议你删掉异常的定时任务，然后再执行下ql repo命令
> > > > > 
> > > > > 
> > > > > 这个方式我操作过了 看到你在TG频道推送过类似问题 重新 ql repo后依旧是这样
> > > > 
> > > > 
> > > > 是最新的镜像？确认是不是真的脚本中没写cron表达式
> > > 
> > > 
> > > 是最新镜像 如果是只读取脚本中的表达式 那还真是我这边问题 。。 有部分脚本里面没有带表达式。 但是 仓库docker文件里的 crontab_list.sh 包含了所有脚本的cron表达式...
> > 
> > 
> > 目前不支持读取仓库的 crontab.list，因为有的仓库可能没有，还没想好这块怎么做
> 
> 或许可以给 ql repo 增加读取目录crontab.list文件参数 比如 -cron_docker 优先读取docker文件里面的crontab来设定脚本的cron执行时间 如果没带这个参数就直接读取脚本里面的cron表达式。

这功能看后期了，不行就要 ql repo命令改成指定参数名的，这个任务先关了
