### ISSUE TITLE
修改了TempBlockCookie后，会屏蔽掉所有脚本的ck

### ISSUE THREAD

**Issue by sstakill** [whyour/qinglong#326]
只要改了下TempBlockCookie，所有脚本几十行保错，然后会屏蔽掉TempBlockCookie里面的ck

重启，加后缀都试了，我看历史有人也提出了bug，现在最新版也有

**Comment by woboo110** [comment]
确实出现这个问题了

**Comment by woboo110** [comment]
貌似有的任务屏蔽正确，有的任务屏蔽错误
