### ISSUE TITLE
能加一个自动更新互助码的完美了

### ISSUE THREAD

**Issue by Nicotinamide** [whyour/qinglong#33]
希望能在运行脚本以后自动更新互助码和更新账号间互助，不然添加账号后更新互助码太麻烦了

**Comment by isimply** [comment]
不是已经有了吗？我的设置每两小时自动更新互助码和互助方式

**Comment by YoYulyvW** [comment]
> 不是已经有了吗？我的设置每两小时自动更新互助码和互助方式

在哪里？？

**Comment by isimply** [comment]
看青龙的代码就知道

**Comment by landcruser** [comment]
> 不是已经有了吗？我的设置每两小时自动更新互助码和互助方式

具体如何做呢？

**Comment by isimply** [comment]
> > 不是已经有了吗？我的设置每两小时自动更新互助码和互助方式
> 
> 具体如何做呢？

扫描日志内最近的互助码并提取出来，互助方式根据每个活动的生成对应的互助方式

**Comment by xxp2277** [comment]
能否将export_sharecodes导出的互助码自动粘贴到config.sh的相应位置（或者将互助码另存为一个文件，再在读取config.sh的基础上另外读取这个互助码文件从而实现全自动的账户内互助）

**Comment by isimply** [comment]
> 能否将export_sharecodes导出的互助码自动粘贴到config.sh的相应位置（或者将互助码另存为一个文件，再在读取config.sh的基础上另外读取这个互助码文件从而实现全自动的账户内互助）

可以的，我就是这样实现的

**Comment by yuntian123456** [comment]
> > 能否将export_sharecodes导出的互助码自动粘贴到config.sh的相应位置（或者将互助码另存为一个文件，再在读取config.sh的基础上另外读取这个互助码文件从而实现全自动的账户内互助）
> 
> 可以的，我就是这样实现的

怎么实现的？？

**Comment by xxp2277** [comment]
> 
> 
> > 能否将export_sharecodes导出的互助码自动粘贴到config.sh的相应位置（或者将互助码另存为一个文件，再在读取config.sh的基础上另外读取这个互助码文件从而实现全自动的账户内互助）
> 
> 可以的，我就是这样实现的

手动实现的？还是自动实现的？

**Comment by isimply** [comment]
自动获取日志中的互助码再根据变量，自动替换掉，并根据CK数量，生成互助方式

**Comment by whyour** [comment]
2.0已支持
