### ISSUE TITLE
青龙拉库后自动添加cron的功能

### ISSUE THREAD

**Issue by Spheniscidaer** [whyour/qinglong#330]
拉库后获取cookie之类的其他脚本全被自动添加了cron定时任务。
如果单独排除这种脚本，这个库的其他脚本无法执行（其他脚本依赖这个cookie.js脚本）。

脚本中有cron设置的自动添加定时任务，没有的能否不自动添加定时任务？

**Comment by whyour** [comment]
ql repo 命令可以加白黑名单，自己设置就行了
