### ISSUE TITLE
最新版还是拉不到脚本

### ISSUE THREAD

**Issue by woboo110** [whyour/qinglong#331]
如图
![image](https://user-images.githubusercontent.com/68997087/121806948-94da0e80-cc84-11eb-9f00-856f38ece788.png)

**Comment by whyour** [comment]
最新版已修复，执行 ql update之后再执行 ql repo命令

**Comment by woboo110** [comment]
> 最新版已修复，执行 ql update之后再执行 ql repo命令

有的库可以，但是胖虎库拉了没反应

**Comment by whyour** [comment]
@woboo110 没反应不是已经添加过了吗？

**Comment by woboo110** [comment]
> @woboo110 没反应不是已经添加过了吗？
没有
![image](https://user-images.githubusercontent.com/68997087/121807921-c359e880-cc88-11eb-98b6-ae0b93ae2d33.png)

**Comment by whyour** [comment]
@woboo110 你命令咋写的

**Comment by woboo110** [comment]
> @woboo110 你命令咋写的

ql repo https://github.com/panghu999/panghu.git “jd_”

**Comment by whyour** [comment]
> > @woboo110 你命令咋写的
> 
> ql repo https://github.com/panghu999/panghu.git “jd_”

![image](https://user-images.githubusercontent.com/22700758/121808134-bee1ff80-cc89-11eb-8491-3add724998c4.png)
没问题。再执行下  ql update 吧

**Comment by woboo110** [comment]
> > > @woboo110 你命令咋写的
> > 
> > 
> > ql repo https://github.com/panghu999/panghu.git “jd_”
> 
> ![image](https://user-images.githubusercontent.com/22700758/121808134-bee1ff80-cc89-11eb-8491-3add724998c4.png)
> 没问题。再执行下 ql update 吧

奇怪，我去掉白名单可以了

![image](https://user-images.githubusercontent.com/68997087/121808392-d2419a80-cc8a-11eb-850d-8b677f906751.png)

**Comment by woboo110** [comment]
> > > @woboo110 你命令咋写的
> > 
> > 
> > ql repo https://github.com/panghu999/panghu.git “jd_”
> 
> ![image](https://user-images.githubusercontent.com/22700758/121808134-bee1ff80-cc89-11eb-8491-3add724998c4.png)
> 没问题。再执行下 ql update 吧

可以了，感谢

**Comment by liuhui886** [comment]
![6FB4AACC-FC3B-4648-A6DD-91668E1527EC](https://user-images.githubusercontent.com/68602592/121808515-788da000-cc8b-11eb-846d-afda82d9b443.jpeg)
这个还是回来了
