### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by myderr** [whyour/qinglong#332]
/usr/local/bin/task: line 21: /usr/bin/perl: Argument list too long

由于log/code里面的文件太大导致的
配置AutoHelpOther改为false可以不报错，但是没有助力了

**Comment by hdstar2009** [comment]
看来除了删除账号数量，无解了。
从LXK的Auto_help.sh出现这个问题，awk grep sed操作参数过长；用JSTool面板也出现这个问题；用青龙也出现，加上最近搜索实践看来是解决不了这个问题了，只能分多docker来跑多账号。

**Comment by fzls** [comment]
试试这个方案
[解决 青龙面板中存放的cookie数目过多（如超过45）时，会报 Argument list too long 而无法正常执行部分脚本的问题](https://gist.github.com/fzls/14f8d1d3ebb2fef64750ad91d268e4f6)
