### ISSUE TITLE
更新到v2.2.0-063后ql repo第三个参数失效

### ISSUE THREAD

**Issue by oracle91** [whyour/qinglong#334]
比如命令ql repo https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"
第三个参数"^jd[^_]|USER"全部都没有下载

**Comment by whyour** [comment]
最新版已修复，执行下 ql update，然后执行 ql repo命令
