### ISSUE TITLE
定时任务列表页: 记录重复

### ISSUE THREAD

**Issue by imbls** [whyour/qinglong#337]
ENV: Host
VERSION: Latest
DESC: 定时任务列表页: 点击某条记录的日志查看, 关闭日志查看后, 列表页末尾会多出一条重复记录, 页面刷新之后, 记录消失.
关闭日志页面之后调用的接口: /api/crons/{cronId}?t={timestamp}
![2qWOqU.png](https://z3.ax1x.com/2021/06/15/2qWOqU.png)
![2qfpGR.png](https://z3.ax1x.com/2021/06/15/2qfpGR.png)
![2qf8eS.png](https://z3.ax1x.com/2021/06/15/2qf8eS.png)

**Comment by whyour** [comment]
> ENV: Host
> VERSION: Latest
> DESC: 定时任务列表页: 点击某条记录的日志查看, 关闭日志查看后, 列表页末尾会多出一条重复记录, 页面刷新之后, 记录消失.
> 关闭日志页面之后调用的接口: /api/crons/{cronId}?t={timestamp}
> ![20210614144905.png](https://camo.githubusercontent.com/f2f5ef64d8a7e47443f30de47a0afd9a4cb8d690527db0a3b1c20074a9465bbf/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30362f31342f7559464e375a6b577347444c516c452e706e67)
> ![20210614150635.png](https://camo.githubusercontent.com/f1acbcd8957f92f3ecf76adfe204ba9d4b9483aafbe6e14a4b274b1cc7666673/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30362f31342f5a4c42653945545573506c4b6937332e706e67)
> ![20210614144953.png](https://camo.githubusercontent.com/d8135824cb5ee732138856b3be61b888cfe3700c51caa2fc6626a2a7f2c6d07f/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30362f31342f454877316252794a65334d6e704f562e706e67)

你这图片看不到，执行下 ql update 然后刷新下页面，这个问题应该是没有的

**Comment by imbls** [comment]
手动执行了ql update, 刷新页面, 问题还是出现 (换了图床, 图片应该能看到了)
![20210615230435](https://user-images.githubusercontent.com/41299079/122078382-1ec5db00-ce2f-11eb-9698-e42bd55d3f0f.png)
![20210615230508](https://user-images.githubusercontent.com/41299079/122078135-f0480000-ce2e-11eb-9163-3846d0a9aff6.png)

**Comment by whyour** [comment]
你的db目录映射了吗

**Comment by imbls** [comment]
映射了, 按照下列指令运行的容器
docker run -dit \
   -v $PWD/ql/config:/ql/config \
   -v $PWD/ql/log:/ql/log \
   -v $PWD/ql/db:/ql/db \
   -p 5700:5700 \
   --name qinglong \
   --hostname qinglong \
   --restart always \
   whyour/qinglong:latest
目前就发现只有在最后一页和倒数第二页会出现关闭日志窗口之后会重复追加记录的情况, 不知道是不是跟repo的仓库有关系...改天再试试其他仓库...
