### ISSUE TITLE
每次更新后以前手动添加的cron全不见了

### ISSUE THREAD

**Issue by vhzn** [whyour/qinglong#34]
大佬辛苦了，每次更新后以前手动添加的cron全不见了，替换更新前备份的映射的crontab.list也没用，只能一个个手动添加，这个可以解决吗？感谢

**Comment by whyour** [comment]
> 大佬辛苦了，每次更新后以前手动添加的cron全不见了，替换更新前备份的映射的crontab.list也没用，只能一个个手动添加，这个可以解决吗？感谢

好好看看频道的通知，要映射db目录，原始任务都存在于db目录的文件里，不在crontab.list里
