### ISSUE TITLE
repo第三方库黑名单跟依赖冲突的情况下该怎么处理？

### ISSUE THREAD

**Issue by Spheniscidaer** [whyour/qinglong#342]
repo https://github.com/passerby-b/JDDJ.git "jddj_|jd_" "jddj_getck|jddj_cookie|jddj_fruit_code" "jddj_cookie|jdCookie|index|ddj_fruit_code"

**Comment by whyour** [comment]
@Spheniscidaer 依赖不受黑白名单影响

**Comment by Spheniscidaer** [comment]
谢谢dalao解答。我自己也试出来了，赶紧就关了。
