### ISSUE TITLE
Session请求500错误

### ISSUE THREAD

**Issue by Sooongz** [whyour/qinglong#343]
![image](https://user-images.githubusercontent.com/1811858/122009347-93c3f100-cdec-11eb-8984-43fdae4f8328.png)

多数情况都是这个500错误，update后偶尔能成功一次。
当添加了新的cookie或修改了cookie后又会500错误

**Comment by Sooongz** [comment]
![image](https://user-images.githubusercontent.com/1811858/122145340-a3dcde80-ce87-11eb-93a7-03a2a2de30a4.png)
使用了host模式，提示不能配置port。
请问如何访问到面板？

另外我是在macOS上部署的docker。

**Comment by whyour** [comment]
> ![image](https://user-images.githubusercontent.com/1811858/122145340-a3dcde80-ce87-11eb-93a7-03a2a2de30a4.png)
> 使用了host模式，提示不能配置port。
> 请问如何访问到面板？
> 
> 另外我是在macOS上部署的docker。

你mac怎么访问不了那个api，端口只是警告，没啥关系

**Comment by qiangxinglin** [comment]
@Sooongz host模式就是直接连在宿主机网络, 没有中间的NAS层, 就无所谓端口映射了, 直接`localhost:5700`, 或者 `域名:5700`

**Comment by Sooongz** [comment]
@qiangxinglin @whyour 是的，加上host访问不到面板。

**Comment by Sooongz** [comment]
https://github.com/docker/for-mac/issues/2716  好像是macOS上不支持host。

**Comment by qiangxinglin** [comment]
@Sooongz mac上的docker是通过虚拟机实现的, 也就是说即使host生效, 他也会把端口都映射到你的虚拟机上而不是mac上

**Comment by whyour** [comment]
> [docker/for-mac#2716](https://github.com/docker/for-mac/issues/2716) 好像是macOS上不支持host。

直接用 docker desktop 不行吗

**Comment by Sooongz** [comment]
用的就是 docker desktop
