### ISSUE TITLE
接口502

### ISSUE THREAD

**Issue by JasonLxj** [whyour/qinglong#344]
http://localhost:5701/api/user?t=1623746599064 提示502.不能进入登录页面
环境： Mac mini
![image](https://user-images.githubusercontent.com/15604758/122022319-0dfa7280-cdf9-11eb-8c16-ed484d86e04f.png)

**Comment by whyour** [comment]
> http://localhost:5701/api/user?t=1623746599064 提示502.不能进入登录页面
> 环境： Mac mini
> ![image](https://user-images.githubusercontent.com/15604758/122022319-0dfa7280-cdf9-11eb-8c16-ed484d86e04f.png)

容器内的服务没启动成功，你执行  docker logs qinglong 看看

**Comment by JasonLxj** [comment]
======================1. 检测配置文件========================

检测到默认nginx配置文件，删除...


'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

======================2. 更新源代码========================

--------------------------------------------------------------

开始更新仓库：/ql

Fetching origin
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ghproxy.com:443
error: Could not fetch origin
HEAD is now at 32c8bb5 修复删除临时脚本列表文件
remote: Enumerating objects: 758, done.
remote: Counting objects: 100% (451/451), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 758 (delta 342), reused 400 (delta 321), pack-reused 307
Receiving objects: 100% (758/758), 503.29 KiB | 106.00 KiB/s, done.
Resolving deltas: 100% (459/459), completed with 35 local objects.
From https://ghproxy.com/https://github.com/whyour/qinglong
   32c8bb5..52dab53  master     -> origin/master
 * [new branch]      develop    -> origin/develop
 * [new tag]         v2.2.0     -> v2.2.0
 * [new tag]         v2.1.0     -> v2.1.0
Updating 32c8bb5..52dab53
Fast-forward
 .github/workflows/ build.yml                     |    6 +-
 .github/workflows/docker.yml                     |    9 +-
 back/api/cookie.ts                               |   28 +-
 back/api/cron.ts                                 |   33 +-
 back/config/index.ts                             |    5 +
 back/data/cron.ts                                |    3 +
 back/loaders/initData.ts                         |   35 +-
 back/schedule.ts                                 |    3 +-
 back/services/cookie.ts                          |   45 +-
 back/services/cron.ts                            |  220 +-
 docker/Dockerfile                                |   11 +-
 docker/docker-entrypoint.sh                      |    5 +-
 package.json                                     |    2 +
 pnpm-lock.yaml                                   | 9826 ++++++++++++++++++++++
 sample/config.sample.sh                          |  104 +-
 sample/notify.js                                 |   70 +-
 shell/api.sh                                     |   66 +-
 shell/bot.sh                                     |   14 +-
 shell/reset.sh                                   |   26 +
 shell/rmlog.sh                                   |   14 +-
 shell/share.sh                                   |   26 +-
 shell/task.sh                                    |   20 +-
 shell/update.sh                                  |  191 +-
 src/app.tsx                                      |   19 +
 src/assets/fonts/SourceCodePro-Regular.otf.woff  |  Bin 0 -> 86532 bytes
 src/assets/fonts/SourceCodePro-Regular.ttf       |  Bin 0 -> 138680 bytes
 src/assets/fonts/SourceCodePro-Regular.ttf.woff2 |  Bin 0 -> 52228 bytes
 src/assets/logo.png                              |  Bin 65119 -> 0 bytes
 src/layouts/defaultProps.tsx                     |    2 +-
 src/layouts/index.less                           |   12 +
 src/layouts/index.tsx                            |   13 +-
 src/pages/config/index.tsx                       |   16 +-
 src/pages/cookie/index.tsx                       |  189 +-
 src/pages/cookie/modal.tsx                       |   12 +-
 src/pages/crontab/index.tsx                      |  135 +-
 src/pages/crontab/logModal.tsx                   |   66 +-
 src/pages/crontab/modal.tsx                      |   10 +-
 src/pages/diff/index.tsx                         |    8 +-
 src/pages/diy/index.tsx                          |   12 +-
 src/pages/log/index.less                         |    0
 src/pages/log/index.module.less                  |   37 +
 src/pages/log/index.tsx                          |  141 +-
 src/pages/login/index.tsx                        |   10 +-
 src/pages/setting/index.tsx                      |   11 +-
 src/styles/variable.less                         |    1 +
 src/utils/http.ts                                |   12 +-
 src/version.ts                                   |    2 +
 47 files changed, 11016 insertions(+), 454 deletions(-)
 create mode 100644 pnpm-lock.yaml
 create mode 100644 shell/reset.sh
 create mode 100644 src/assets/fonts/SourceCodePro-Regular.otf.woff
 create mode 100644 src/assets/fonts/SourceCodePro-Regular.ttf
 create mode 100644 src/assets/fonts/SourceCodePro-Regular.ttf.woff2
 delete mode 100644 src/assets/logo.png
 delete mode 100644 src/pages/log/index.less
 create mode 100644 src/pages/log/index.module.less
 create mode 100644 src/styles/variable.less
 create mode 100644 src/version.ts

更新/ql失败，请检查原因...

开始克隆仓库 https://gitee.com/whyour/qinglong-static.git 到 /ql/repo/static

Cloning into '/ql/repo/static'...
remote: Enumerating objects: 129, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 129 (delta 57), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (129/129), 3.92 MiB | 4.59 MiB/s, done.
Resolving deltas: 100% (57/57), done.

更新/ql/repo/static成功...

重启青龙面板(后台重启)...

重启面板完成(请5s后刷新页面)...

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__


                          Runtime Edition

        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.

                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/


                        -------------

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
Use --update-env to update environment variables
[PM2][WARN] No process found

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动控制面板========================

[PM2][WARN] panel doesn't exist
[PM2] Starting /ql/build/app.js in fork_mode (1 instance)
[PM2] Done.
┌─────┬──────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name     │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ panel    │ default     │ N/A     │ fork    │ 110      │ 0s     │ 0    │ online    │ 0%       │ 30.3mb   │ root     │ disabled │
└─────┴──────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
控制面板启动成功...

======================5. 启动定时任务========================

[PM2][WARN] schedule doesn't exist
[PM2] Starting /ql/build/schedule.js in fork_mode (1 instance)
[PM2] Done.
┌─────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ panel       │ default     │ N/A     │ fork    │ 110      │ 0s     │ 0    │ online    │ 0%       │ 59.6mb   │ root     │ disabled │
│ 1   │ schedule    │ default     │ N/A     │ fork    │ 139      │ 0s     │ 0    │ online    │ 0%       │ 19.0mb   │ root     │ disabled │
└─────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
定时任务启动成功...

############################################################

容器启动成功...

请先访问5700端口，登录成功面板之后再执行添加定时任务...
############################################################

crond[147]: crond (busybox 1.31.1) started, log level 8
crond[147]: USER root pid 647 cmd run-parts /etc/periodic/15min

**Comment by JasonLxj** [comment]
> > http://localhost:5701/api/user?t=1623746599064 提示502.不能进入登录页面
> > 环境： Mac mini
> > ![image](https://user-images.githubusercontent.com/15604758/122022319-0dfa7280-cdf9-11eb-8c16-ed484d86e04f.png)
> 
> 容器内的服务没启动成功，你执行 docker logs qinglong 看看

日志如上个回复，看起来也没什么问题

**Comment by ylinz** [comment]
我也遇到了，但是任务能正常运行。我的容器已经启动了5天了,重启容器之后正常

**Comment by JasonLxj** [comment]
> 我也遇到了，但是任务能正常运行。我的容器已经启动了5天了,重启容器之后正常

我现在登录不进去，没法执行命令。执行的时候提示要先登录

**Comment by whyour** [comment]
> > 我也遇到了，但是任务能正常运行。我的容器已经启动了5天了,重启容器之后正常
> 
> 我现在登录不进去，没法执行命令。执行的时候提示要先登录

你这是要代理，还是不要，不要的话，把githubproxyurl的参数删了

**Comment by jiuli12** [comment]
我也遇到了这个 502的问题请问怎么解决的呢？

**Comment by PP88PP** [comment]
> > http://localhost:5701/api/user?t=1623746599064 提示502.不能进入登录页面
> > 环境： Mac mini
> > ![image](https://user-images.githubusercontent.com/15604758/122022319-0dfa7280-cdf9-11eb-8c16-ed484d86e04f.png)
> 
> 容器内的服务没启动成功，你执行 docker logs qinglong 看看

======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...


'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    15 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...


'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    14 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...


'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

**Comment by iqiancheng** [comment]
可以更换到 whyour/qinglong:pre 可以解决此问题
