### ISSUE TITLE
关于定时脚本运行以后不停止的问题

### ISSUE THREAD

**Issue by xiaorizi01** [whyour/qinglong#347]
定时脚本到时间自动运行后，脚本任务已经结束，可脚本却还在不停的运行，一直在后台空运行，导致一天下来会有几十个脚本的定时任务结束后，还一直在后台同时运行，！小服务器 cpu直接百分百！顶不住啊，直接卡死！望大佬看下这个问题

**Comment by whyour** [comment]
> 定时脚本到时间自动运行后，脚本任务已经结束，可脚本却还在不停的运行，一直在后台空运行，导致一天下来会有几十个脚本的定时任务结束后，还一直在后台同时运行，！小服务器 cpu直接百分百！顶不住啊，直接卡死！望大佬看下这个问题

不是定时任务有1小时执行时间限制吗，你不是用的最新版本吗

**Comment by xiaorizi01** [comment]
我好像忘记了。我设置的好像是6小时，我擦。罪过罪过



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: whyour ***@***.***&gt;
发送时间: 2021年6月16日 21:32
收件人: whyour/qinglong ***@***.***&gt;
抄送: xiaorizi01 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[whyour/qinglong] 关于定时脚本运行以后不停止的问题 (#347)





  
定时脚本到时间自动运行后，脚本任务已经结束，可脚本却还在不停的运行，一直在后台空运行，导致一天下来会有几十个脚本的定时任务结束后，还一直在后台同时运行，！小服务器 cpu直接百分百！顶不住啊，直接卡死！望大佬看下这个问题
  
不是定时任务有1小时执行时间限制吗，你不是用的最新版本吗
