### ISSUE TITLE
too long 有办法直接或间接解决吗 

### ISSUE THREAD

**Issue by atpx4869** [whyour/qinglong#348]
ARG_MAX也改过了并重新编译了 没什么效果

**Comment by mrccccj** [comment]
同样的问题，跪求解决方法

**Comment by hdstar2009** [comment]
> 同样的问题，跪求解决方法

貌似无解。不过谷歌到有老外说这种情况可以尝试更改代码写法。不会写代码，可能理解错。

**Comment by fzls** [comment]
试试这个方案
[解决 青龙面板中存放的cookie数目过多（如超过45）时，会报 Argument list too long 而无法正常执行部分脚本的问题](https://gist.github.com/fzls/14f8d1d3ebb2fef64750ad91d268e4f6)
