### ISSUE TITLE
diy一直更新错误。

### ISSUE THREAD

**Issue by qq9700** [whyour/qinglong#35]
新版重新装，找不到diy.sh，还有extta.sh

**Comment by qq9700** [comment]
whyour本地仓库不存在,从gayhub拉取ing...
/usr/local/bin/diy: line 35: local: can only be used in a function
fatal: repository 'whyour_hundun' does not exist
whyour本地仓库拉取失败,请检查!


执行结束...



Fetching origin
HEAD is now at bdfec42 修复diy脚本语法
Already up to date.


执行结束...

**Comment by shusheng110** [comment]
更新之后好像都是这个错误了

**Comment by landcruser** [comment]
解决了吗？都是

**Comment by whyour** [comment]
0416最新版已修复
