### ISSUE TITLE
定时任务显示bug，任务未运行但状态显示为运行

### ISSUE THREAD

**Issue by lxr760** [whyour/qinglong#350]
![Snipaste_2021-06-16_15-34-16](https://user-images.githubusercontent.com/8476457/122177660-68a6d380-ceb8-11eb-9559-bf8b2625739a.jpg)
界面显示这么多进程在运行，实际没有任何脚本在跑
![Snipaste_2021-06-16_15-34-38](https://user-images.githubusercontent.com/8476457/122177734-79efe000-ceb8-11eb-8278-9ba90fc0cf34.jpg)

脚本自动定时跑完或者手动执行跑完以后，都会出现这个错误。即实际已不运行这个脚本，但显示为运行状态

**Comment by VectorZhao** [comment]
对，今晚的更新依然没有修复这个bug。。。。
等下次更新吧

**Comment by whyour** [comment]
是因为执行了  ql update 还是这些任务一直持续很长时间都是运行中，任务最长运行时间没有设置吗，另外显示运行中，是脚本没执行结束，你top出来的没显示所有进程

**Comment by lxr760** [comment]
> 是因为执行了 ql update 还是这些任务一直持续很长时间都是运行中，任务最长运行时间没有设置吗，另外显示运行中，是脚本没执行结束，你top出来的没显示所有进程

任务不管是定时还是手动，执行完毕以后，界面还是会处于运行状态。不是ql update之后造成。

我top那个图       是我docker刚重启完，截图完整，下面已经没进程了，但是web里有10几个脚本显示为运行状态
