### ISSUE TITLE
Session管理里不显示Cookies

### ISSUE THREAD

**Issue by noyyhi** [whyour/qinglong#352]
但是任务可以正常运行。因为Cookies不显示，我又添加了一次，现在每个账号要运行两次，怎么解决呢。

**Comment by Acr05s** [comment]
是不是 弄了 adblock这类插件

**Comment by noyyhi** [comment]
> 是不是 弄了 adblock这类插件

应该不是，手机浏览器也不显示。

**Comment by zxfandyy** [comment]
> 但是任务可以正常运行。因为Cookies不显示，我又添加了一次，现在每个账号要运行两次，怎么解决呢。

我也遇到这个bug，修改了cookie信息，旧的cookie删不掉了，cookie重复，session页面也没有显示，临时的解决方式是进入后台修改cookie.sh，但是也没法完全解决，过一段时间，cookie又被自动覆盖了，苦恼
