### ISSUE TITLE
ql bot 的GithubProxyUrl不生效

### ISSUE THREAD

**Issue by lcylgs** [whyour/qinglong#353]
在配置文件里配置了GithubProxyUrl参数，并且ql update的时候参数是生效的。
但是ql bot却不生效。

日志显示：
2、下载bot所需文件...

开始更新仓库：/ql/repo/dockerbot

Fetching origin
fatal: unable to access 'https://github.com/SuMaiKaDe/bot.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
error: Could not fetch origin
HEAD is now at 29f4d09 修复 自动添加定时任务提示错误
fatal: unable to access 'https://github.com/SuMaiKaDe/bot.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

查看bot.sh 发现参数和update.sh 一致。
问题比较诡异。

**Comment by lcylgs** [comment]
直接修改url为url="${github_proxy_url}://ghproxy.com/ttps://github.com/SuMaiKaDe/bot.git"一样提示无法下载

**Comment by whyour** [comment]
> 直接修改url为url="${github_proxy_url}://ghproxy.com/ttps://github.com/SuMaiKaDe/bot.git"一样提示无法下载

GithubProxyUrl="https://ghproxy.com/"  配置里加这个参数

**Comment by lcylgs** [comment]
已经配置了GithubProxyUrl="https://ghproxy.com/"

**Comment by whyour** [comment]
@lcylgs 你能访问github吗，不需要就把这个参数删掉
