### ISSUE TITLE
新版本才更新，提示[PM2][ERROR] Process or Namespace panel not found，进不去面板了，大佬赶紧修复下

### ISSUE THREAD

**Issue by wzal2008** [whyour/qinglong#354]

**Comment by laulay2033** [comment]
升级后container一直重启动啊！

**Comment by whyour** [comment]
5-10分钟后拉取最新镜像试试

**Comment by MoLing-Dong** [comment]
大佬虽然不想催但是我还是用不了

**Comment by wzal2008** [comment]
还是不行，进不了面板

**Comment by bontheway** [comment]
======================1. 检测配置文件========================

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

======================2. 启动nginx========================

nginx启动成功...

======================3. 启动控制面板========================

======================1. 检测配置文件========================

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

======================2. 启动nginx========================

nginx启动成功...

======================3. 启动控制面板========================

======================1. 检测配置文件========================

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

======================2. 启动nginx========================

nginx启动成功...

======================3. 启动控制面板========================

**Comment by whyour** [comment]
拉取最新镜像试试

**Comment by MoLing-Dong** [comment]
拉了一晚上了，一直重启。

**Comment by fisherxt** [comment]
删容器删文件夹重新拉镜像安装，无限重启...+1

**Comment by bontheway** [comment]
> 拉取最新镜像试试

可以了
