### ISSUE TITLE
centos7 按照tg教程安装 提示错误

### ISSUE THREAD

**Issue by zxc125643** [whyour/qinglong#355]
docker: Error response from daemon: driver failed programming external connectivity on endpoint QL (51bbef265af0a92d306174c8ad75cdf6f918f01b6b09a7c1f97696f43eea1819):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5700 -j DNAT --to-destination 172.17.0.2:5700 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)).

**Comment by whyour** [comment]
> docker: Error response from daemon: driver failed programming external connectivity on endpoint QL (51bbef265af0a92d306174c8ad75cdf6f918f01b6b09a7c1f97696f43eea1819): (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5700 -j DNAT --to-destination 172.17.0.2:5700 ! -i docker0: iptables: No chain/target/match by that name.
> (exit status 1)).

重启下 docker    systemctl restart  docker
