### ISSUE TITLE
添加自己写的脚本，如何让它执行完后也能发送通知？

### ISSUE THREAD

**Issue by powersee** [whyour/qinglong#357]
我在 /ql/scripts/ 里面自己放了脚本，可以通过 task a.js 来执行这个脚本，也可以通过面板来添加定时任务。但是执行完成后，输出的日志只保存在本地，似乎没法像 jd 脚本那样，通过 config.sh 里面的配置，将日志发送到 tg 或者 pushplus。

想请问大佬，怎样才能实现自己的脚本日志，执行完也可以发送通知？

**Comment by lxr760** [comment]
你要在js里定义推送

**Comment by powersee** [comment]
已了解了，多谢。
