### ISSUE TITLE
Could not resolve host: ghproxy.com

### ISSUE THREAD

**Issue by colakele** [whyour/qinglong#358]
Fetching origin
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': Could not resolve host: ghproxy.com
error: Could not fetch origin
HEAD is now at ba4abbf 修复entrypoint判断
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': Could not resolve host: ghproxy.com

更新/ql失败，请检查原因...

开始克隆仓库 https://ghproxy.com/https://github.com/whyour/qinglong-static.git 到 /ql/repo/static

Cloning into '/ql/repo/static'...
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong-static.git/': Could not resolve host: ghproxy.com

更新/ql失败，请检查原因...

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动控制面板========================

[PM2][ERROR] Script not found: /ql/build/app.js
======================1. 检测配置文件========================

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

======================2. 更新源代码========================

**Comment by b08240** [comment]
同样的错误，好几天了都这样

开始更新仓库：/ql
Fetching origin
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': Failed to connect to ghproxy.com port 443: Connection refused
error: Could not fetch origin
HEAD is now at 52dab53 更新版本号
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong.git/': Failed to connect to ghproxy.com port 443: Connection refused
更新/ql失败，请检查原因...
开始克隆仓库 https://ghproxy.com/https://github.com/whyour/qinglong-static.git 到 /ql/repo/static
Cloning into '/ql/repo/static'...
fatal: unable to access 'https://ghproxy.com/https://github.com/whyour/qinglong-static.git/': Failed to connect to ghproxy.com port 443: Connection refused
更新/ql失败，请检查原因...
======================3. 启动nginx========================
nginx启动成功...
======================4. 启动控制面板========================
Use --update-env to update environment variables
[PM2][ERROR] Process or Namespace panel not found

**Comment by whyour** [comment]
如果能直接访问github  就把 config 里的 githubproxyurl 删了吧

**Comment by necan** [comment]
ghproxy.com 偶尔抽风，重新执行一遍命令即可。
