### ISSUE TITLE
dust仓库为ssh拉取方式 具体该如何操作 拉取

### ISSUE THREAD

**Issue by doube1008** [whyour/qinglong#36]

**Comment by Liquid-w** [comment]
同样的问题，更新了最新的docker1.2.0版本，发现monk-coder和hundun这两个仓库都无法拉取了

**Comment by doube1008** [comment]
有人说 修改   vi /root/.ssh/id_rsa   一行一个key

**Comment by Liquid-w** [comment]
好的，我去试试

**Comment by Liquid-w** [comment]
> 有人说 修改 vi /root/.ssh/id_rsa 一行一个key

你的意思是把之间的空格，改成回车吗？

**Comment by doube1008** [comment]
> > 有人说修改vi /root/.ssh/id_rsa一行一个键
> 
> 你的意思是把之间的空间，改成回车吗？

嗯

**Comment by Liquid-w** [comment]
> > > 有人说修改vi /root/.ssh/id_rsa一行一个键
> > 
> > 
> > 你的意思是把之间的空间，改成回车吗？
> 
> 嗯

我改完了，又复制回容器了，但是还是不好使，依旧报错Load key "/root/.ssh/id_rsa": invalid format

**Comment by doube1008** [comment]
![image](https://user-images.githubusercontent.com/28523974/114335845-33ac9680-9b80-11eb-9cbc-75d246accd3a.png)
ren人家是这样的  我还没试过

**Comment by Liquid-w** [comment]
> ![image](https://user-images.githubusercontent.com/28523974/114335845-33ac9680-9b80-11eb-9cbc-75d246accd3a.png)
> ren人家是这样的 我还没试过

有用有用，我刚复查，发现我多加了1个空格，改完格式就好了,monk-oder的库可以更新了，但是hundun的那个显示没有仓库

**Comment by doube1008** [comment]
> > ![图像](https://user-images.githubusercontent.com/28523974/114335845-33ac9680-9b80-11eb-9cbc-75d246accd3a.png)
> > ren人家是这样的我还没试过
> 
> 有用有用，我刚复查，发现我多加了1个空格，改完格式就好了，monk-oder的库可以更新了，但是hundun的那个显示没有仓库

都删库了 等吧

**Comment by 5wszxt** [comment]
怎么我文件夹下找不到这个文件啊，，😂

**Comment by VectorZhao** [comment]
> > ![image](https://user-images.githubusercontent.com/28523974/114335845-33ac9680-9b80-11eb-9cbc-75d246accd3a.png)
> > ren人家是这样的 我还没试过
> 
> 有用有用，我刚复查，发现我多加了1个空格，改完格式就好了,monk-oder的库可以更新了，但是hundun的那个显示没有仓库

请问这些key是什么内容啊，方便贴出来吗，我去试试，谢谢
