### ISSUE TITLE
按照指南启动了容器，docker ps 也能查到了，但是ip + 端口 无法访问？

### ISSUE THREAD

**Issue by TEAMO233** [whyour/qinglong#360]
各位老哥，这种有解决办法么？

**Comment by TEAMO233** [comment]
![WechatIMG201](https://user-images.githubusercontent.com/48355264/122411058-097bb880-cfb7-11eb-91df-cb2697666a05.png)

**Comment by TEAMO233** [comment]
就是一直访问不了面板

**Comment by whyour** [comment]
@TEAMO233 在容器里执行   或者执行    docker exec -it qinglong ps -A | grep nginx | grep -v grep

**Comment by TEAMO233** [comment]
> docker exec -it qinglong ps -A | grep nginx | grep -v grep

![image](https://user-images.githubusercontent.com/48355264/122412220-f7e6e080-cfb7-11eb-9f5d-77804b05ba35.png)
是这样的 但是还是不行访问

**Comment by whyour** [comment]
> > docker exec -it qinglong ps -A | grep nginx | grep -v grep
> 
> ![image](https://user-images.githubusercontent.com/48355264/122412220-f7e6e080-cfb7-11eb-9f5d-77804b05ba35.png)
> 是这样的 但是还是不行访问

执行  docker exec -it qinglong curl http://127.0.0.1:5700

然后  curl http://127.0.0.1:5700

**Comment by TEAMO233** [comment]
> docker exec -it qinglong curl http://127.0.0.1:5700

![image](https://user-images.githubusercontent.com/48355264/122412780-72176500-cfb8-11eb-97f5-a16d7a0b9d8e.png)
执行了是种。不过还是访问不了

**Comment by whyour** [comment]
> > docker exec -it qinglong curl http://127.0.0.1:5700
> 
> ![image](https://user-images.githubusercontent.com/48355264/122412780-72176500-cfb8-11eb-97f5-a16d7a0b9d8e.png)
> 执行了是种。不过还是访问不了

那是你服务器防火墙问题了，5700物理机没问题

**Comment by TEAMO233** [comment]
> > > docker exec -it qinglong curl http://127.0.0.1:5700
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/48355264/122412780-72176500-cfb8-11eb-97f5-a16d7a0b9d8e.png)
> > 执行了是种。不过还是访问不了
> 
> 那是你服务器防火墙问题了，5700物理机没问题

好吧  我在看看 谢谢🙏

**Comment by whyour** [comment]
> > > > docker exec -it qinglong curl http://127.0.0.1:5700
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/48355264/122412780-72176500-cfb8-11eb-97f5-a16d7a0b9d8e.png)
> > > 执行了是种。不过还是访问不了
> > 
> > 
> > 那是你服务器防火墙问题了，5700物理机没问题
> 
> 好吧 我在看看 谢谢🙏

你查下机器的
