### ISSUE TITLE
argument list too long

### ISSUE THREAD

**Issue by clare88** [whyour/qinglong#369]
![image](https://user-images.githubusercontent.com/83801724/122666417-a751cc00-d1df-11eb-9e19-6eac1bb03cae.png)
请问whyour大神这个是是什么原因？有时候没事有时候又跳出来。

**Comment by hdstar2009** [comment]
账号多，无解，请不要代挂。因为代挂，新版青龙都改了。

**Comment by fzls** [comment]
试试这个方案
[解决 青龙面板中存放的cookie数目过多（如超过45）时，会报 Argument list too long 而无法正常执行部分脚本的问题](https://gist.github.com/fzls/14f8d1d3ebb2fef64750ad91d268e4f6)
