### ISSUE TITLE
大佬，我更新之后现在突然发现cookie界面没有显示cookie了

### ISSUE THREAD

**Issue by 5wszxt** [whyour/qinglong#37]
大佬，我更新之后现在突然发现cookie界面没有显示cookie了
然后f12看了下有个api指向cookies，但是访问是验证未找到，麻烦你看一下下，cookie文件里面还有数据，系统都正常运行

**Comment by 5wszxt** [comment]
![Uploading 20210412_211450.jpg…]()

**Comment by 5wszxt** [comment]
![20210412_211442](https://user-images.githubusercontent.com/18243984/114400105-3ea6fd00-9b67-11eb-980e-04127bfecbc3.jpg)

**Comment by 5wszxt** [comment]
ck已经重新批量添加了，现在可以了，，，，但是那个更新说的dust的私钥我却没有找到，，拉了几次了，，，看issues他们说的id_rsa文件，但是我却一直拉不出来，，，更新仓库的时候就一直提示无权限。。。

**Comment by Acr05s** [comment]
这个不显示 感觉是 页面读的cookie.db 但是，以前config里面原来有cookie，编辑页面没有去保存一下的操作，就不会写到db里面，所以就不显示了，

**Comment by 5wszxt** [comment]
这个之前发现了，就是db文件里面没有，，，，，我想问下你有作者说的那个密钥文件吗？就是什么id_rsa文件

**Comment by whyour** [comment]
> 大佬，我更新之后现在突然发现cookie界面没有显示cookie了
> 然后f12看了下有个api指向cookies，但是访问是验证未找到，麻烦你看一下下，cookie文件里面还有数据，系统都正常运行

使用最新镜像试试，或者rebuild下
