### ISSUE TITLE
2.8版本无法调整env变量顺序以及通知功能失效

### ISSUE THREAD

**Issue by GFBG-IT** [whyour/qinglong#372]
2.8版本无法调整env变量顺序以及通知功能失效

**Comment by whyour** [comment]
ql update下

**Comment by sydaint** [comment]
> ql update下
导出互助吗的命令貌似一起失效了

互助码格式呢

**Comment by ye-cao** [comment]
ql update后还是不能按照需要的顺序排列。

**Comment by sydaint** [comment]
我的可以直接拖动顺序  不知道你的行不行 不行重启下docker试试

**Comment by ye-cao** [comment]
拖动后切换回去又变回来了，停止docker后，直接修改env.sh，再启动docker也会变回去。

**Comment by sydaint** [comment]
> 拖动后切换回去又变回来了，停止docker后，直接修改env.sh，再启动docker也会变回去。

我的x86版本没有这个问题，拖动后刷新或者切换标签回来不会恢复原样，没有重启测试

**Comment by ye-cao** [comment]
又测试了一下，确实还是存在问题，拖动后，不按照拖动的那个规律排列，也不是每次排列不变化，有时候也变化，但是变化不是想要的那个规律，测试的是黑群晖6.23docker，AMD64环境

**Comment by sydaint** [comment]
实在不行就完全重新安装试试把
我限制用2.2的镜像创建docker版本还是2.8 不知道什么情况
选在半夜更新版本，没时间提前禁用ql update  哎

**Comment by Acr05s** [comment]
一次不要拖太多，拖一下，点一下其它功能切换一下，再切回去，有麻烦，还是可以调整的

**Comment by sydaint** [comment]
能解决就好，估计不是实时保存的  拖动之后等一会再刷新看

**Comment by ye-cao** [comment]
直接删除变量重建了，拖动弄不到我要的排列结果。

**Comment by c939984606** [comment]
> > ql update下
> 
> 日志-互助码
> 开始执行... 2021/6/21上午8:58:42
> 
> /usr/local/bin/ql: line 447: /ql/shell/code.sh: No such file or directory
> 
> 执行结束...
> 
> 导出互助吗的命令貌似一起失效了
> 互助码格式呢

cd shell&wget https://raw.githubusercontent.com/whyour/qinglong/080540de0ee86b656b01a2af17efba275f8a964d/shell/code.sh

**Comment by Kylin2021** [comment]
> > > ql update下
> > 
> > 
> > 日志-互助码
> > 开始执行... 2021/6/21上午8:58:42
> > /usr/local/bin/ql: line 447: /ql/shell/code.sh: No such file or directory
> > 执行结束...
> > 导出互助吗的命令貌似一起失效了
> > 互助码格式呢
> 
> cd shell&wget https://raw.githubusercontent.com/whyour/qinglong/080540de0ee86b656b01a2af17efba275f8a964d/shell/code.sh

/ql/shell/code.sh: line 10: ((: user_num <= : syntax error: operand expected (error token is "<= ")
这个怎么破 老哥
