### ISSUE TITLE
2.8版本互助失效

### ISSUE THREAD

**Issue by HuTao1996** [whyour/qinglong#376]
更新2.8版本之后互助失效了

**Comment by HuTao1996** [comment]
公告移除了，但是希望大佬告诉怎么弄互助

**Comment by sydaint** [comment]
目前是在配置文件右上角选择task_before.sh里面修改，但是具体变量名以及格式未知

**Comment by Acr05s** [comment]
把code 内容复制进去，没有效果

**Comment by sydaint** [comment]
我的ql code都不能运行了

**Comment by 4rat** [comment]
> 我的ql code都不能运行了

2.8版本 我在定时任务都没有找到ql code

**Comment by sydaint** [comment]
> > 我的ql code都不能运行了
> 
> 2.8版本 我在定时任务都没有找到ql code

新安装版本是没有的，只有删除日志跟更新面板的命令  我是自己输入的  结果不行

**Comment by Acr05s** [comment]
哪个屌大的知道怎么添加互助码了么

**Comment by allonmymind** [comment]
> 哪个屌大的知道怎么添加互助码了么

吊大的大哥搞定后能否带我一jio

**Comment by qsect** [comment]
青龙每次更新后都不能启动，只能重建，这次重建，Cookie怎么添加呢？按照变量添加，名称自己随便填，值填写Cookie，发现无法使用呢。

**Comment by hrj5032188** [comment]
吊大的大哥搞定后能否带我一jio

**Comment by Acr05s** [comment]
> 吊大的大哥搞定后能否带我一jio

作者大佬已经发了方法了

**Comment by allonmymind** [comment]
> 青龙每次更新后都不能启动，只能重建，这次重建，Cookie怎么添加呢？按照变量添加，名称自己随便填，值填写Cookie，发现无法

> > 吊大的大哥搞定后能否带我一jio
> 
> 作者大佬已经发了方法了

大佬的tg群能推一个吗

**Comment by Acr05s** [comment]
> > 青龙每次更新后都不能启动，只能重建，这次重建，Cookie怎么添加呢？按照变量添加，名称自己随便填，值填写Cookie，发现无法
> 
> > > 吊大的大哥搞定后能否带我一jio
> > 
> > 
> > 作者大佬已经发了方法了
> 
> 大佬的tg群能推一个吗

没有群，只有一个频道。jiaolongwang

**Comment by allonmymind** [comment]
> jiaolongwang

谢谢老哥

**Comment by qsect** [comment]
> > > 青龙每次更新后都不能启动，自己重新新建，这重建，cookie怎么添加呢？
> > 
> > 
> > > > 吊大的大哥搞定后还能带我一jio
> > > 
> > > 
> > > 作者大佬已经发了方法了
> > 
> > 
> > 大佬的tg群能推一个吗
> 
> 没有群，只有一个频道。

我的是新建的，log下没有文件，不会弄互助，请问新的怎么建互助呢？config.sh下具体怎么填写啊

**Comment by qsect** [comment]
> > > 青龙每次更新后都不能启动，只能重建，这次重建，Cookie怎么添加呢？按照变量添加，名称自己随便填，值填写Cookie，发现无法
> > 
> > 
> > > > 吊大的大哥搞定后能否带我一jio
> > > 
> > > 
> > > 作者大佬已经发了方法了
> > 
> > 
> > 大佬的tg群能推一个吗
> 
> 没有群，只有一个频道。jiaolongwang

比如东东农场互助，是这么写吗：
export MyFruit1=""
export MyFruit2=""

如果1助2,2助1是不是就写：
export ForOtherFruit1="${MyFruit2}"
export ForOtherFruit2="${MyFruit1}"

**Comment by Acr05s** [comment]
> > > > 青龙每次更新后都不能启动，只能重建，这次重建，Cookie怎么添加呢？按照变量添加，名称自己随便填，值填写Cookie，发现无法
> > > 
> > > 
> > > > > 吊大的大哥搞定后能否带我一jio
> > > > 
> > > > 
> > > > 作者大佬已经发了方法了
> > > 
> > > 
> > > 大佬的tg群能推一个吗
> > 
> > 
> > 没有群，只有一个频道。jiaolongwang
> 
> 比如东东农场互助，是这么写吗：
> export MyFruit1=""
> export MyFruit2=""
> 
> 如果1助2,2助1是不是就写：
> export ForOtherFruit1="${MyFruit2}"
> export ForOtherFruit2="${MyFruit1}"

不需要export　不过似乎后面要加一个逻辑代码才可以。大佬发了示例的，已实测可以行

**Comment by 4rat** [comment]
> > > > > 青龙每次更新后都不能启动，只能重建，这次重建，Cookie怎么添加呢？按照变量添加，名称自己随便填，值填写Cookie，发现无法
> > > > 
> > > > 
> > > > > > 吊大的大哥搞定后能否带我一jio
> > > > > 
> > > > > 
> > > > > 作者大佬已经发了方法了
> > > > 
> > > > 
> > > > 大佬的tg群能推一个吗
> > > 
> > > 
> > > 没有群，只有一个频道。jiaolongwang
> > 
> > 
> > 比如东东农场互助，是这么写吗：
> > export MyFruit1=""
> > export MyFruit2=""
> > 如果1助2,2助1是不是就写：
> > export ForOtherFruit1="${MyFruit2}"
> > export ForOtherFruit2="${MyFruit1}"
> 
> 不需要export　不过似乎后面要加一个逻辑代码才可以。大佬发了示例的，已实测可以行

有没有可以自动格式化的？日志中的互助码都是这样。。

======账号1开始======
【京东账号1（jd_7b1416309b509）京东农场】c70d26678480ad7d68b7ded67a
【京东账号1（jd_7b1416309b509）京东萌宠】MTE1NDQ5MDAwMDAwNDM2MTIxNTM=
【京东账号1（jd_7b1416309b509）种豆得豆】4npkonas6yspspypg7mnjssip2rbq
【京东账号1（jd_7b1416309b509）东东工厂】T0R0wY8VXRIxr9xvIKfQCjVWnYaS5kRrbA
【京东账号1（jd_7b1416309b509）京喜工厂】VJSwm6U0cxg9uXkgig==
注意：京喜农场 种植种子发生变化的时候，互助码也会变！！
【京东账号1（jd_7b1416309b509）京喜农场】{"smp":"af46f652f2781ef2bc8bc48a75fd5296","active":"jdnc_1_lilng21305_2","joinum":1}
【京东账号1（jd_7b1416309b509）crazyJoy】f93I9i_EOKt9zd5YaBeE
【京东账号1（jd_7b1416309b509）闪购盲盒】T02wvIKfQCjVQmoaT5kRrbA
【京东账号1（jd_7b1416309b509）财富岛】undefned
【京东账号1（jd_7b1416309b509）签到领现金】eU9Ya08m7cmXYT3w
======账号1结束======

======账号2开始======
【京东账号2（jd_tEwERiybzJMV）京东农场】1bd28deb3e244249ca83ec7a
【京东账号2（jd_tEwERiybzJMV）京东萌宠】MTE1NDUyjEwMDAwMDAwNDE=
【京东账号2（jd_tEwERiybzJMV）种豆得豆】4larfd6ua4ecroppfwxq7fbu3ei
【京东账号2（jd_tEwERiybzJMV）东东工厂】T0205KkcBtegDasCjVWnYaS5kRrbA
【京东账号2（jd_tEwERiybzJMV）京喜工厂】O54xSON8PgVQ==
注意：京喜农场 种植种子发生变化的时候，互助码也会变！！
【京东账号2（jd_tEwERiybzJMV）京喜农场】{"smp":"50e5293ec2b617103049edd5c2c","active":"jdnc_1_heii210113_2","joinnum":1}
【京东账号2（jd_tEwERiybzJMV）crazyJoy】a2qVKdJPTV0QjoF7g==
【京东账号2（jd_tEwERiybzJMV）闪购盲盒】T0205KkcBGtegi-7opsCjVQmoaT5kRrbA
【京东账号2（jd_tEwERiybzJMV）财富岛】undefined
【京东账号2（jd_tEwERiybzJMV）签到领现金】eU91E5_uDyfsQ51
======账号2结束======

**Comment by anleihn** [comment]
> 大佬发了示例的，已实测可
实例在那？

**Comment by hrj5032188** [comment]
> > > > > 青龙每次更新后都不能启动，只能重建，这次重建，Cookie怎么添加呢？按照变量添加，名称自己随便填，值填写Cookie，发现无法
> > > > 
> > > > 
> > > > > > 吊大的大哥搞定后能否带我一jio
> > > > > 
> > > > > 
> > > > > 作者大佬已经发了方法了
> > > > 
> > > > 
> > > > 大佬的tg群能推一个吗
> > > 
> > > 
> > > 没有群，只有一个频道。jiaolongwang
> > 
> > 
> > 比如东东农场互助，是这么写吗：
> > export MyFruit1=""
> > export MyFruit2=""
> > 如果1助2,2助1是不是就写：
> > export ForOtherFruit1="${MyFruit2}"
> > export ForOtherFruit2="${MyFruit1}"
> 
> 不需要export　不过似乎后面要加一个逻辑代码才可以。大佬发了示例的，已实测可以行

这以后的脚本都要自己手写吗

**Comment by HuTao1996** [comment]
已确定以后互助要手动添加，互助码也会变

**Comment by fanyh123** [comment]
> > > > > > 青龙每次更新后都不能启动，只能重建，这次重建，Cookie怎么添加呢？按照变量添加，名称自己随便填，值填写Cookie，发现无法
> > > > > 
> > > > > 
> > > > > > > 吊大的大哥搞定后能否带我一jio
> > > > > > 
> > > > > > 
> > > > > > 作者大佬已经发了方法了
> > > > > 
> > > > > 
> > > > > 大佬的tg群能推一个吗
> > > > 
> > > > 
> > > > 没有群，只有一个频道。jiaolongwang
> > > 
> > > 
> > > 比如东东农场互助，是这么写吗：
> > > export MyFruit1=""
> > > export MyFruit2=""
> > > 如果1助2,2助1是不是就写：
> > > export ForOtherFruit1="${MyFruit2}"
> > > export ForOtherFruit2="${MyFruit1}"
> > 
> > 
> > 不需要export　不过似乎后面要加一个逻辑代码才可以。大佬发了示例的，已实测可以行
> 
> 这以后的脚本都要自己手写吗

code运行的内容是互助码变量,在所有变量前面加上 export  然后复制到配置文件下面保存就行了
类似图片这样
![image](https://user-images.githubusercontent.com/15026816/124286106-30261b80-db81-11eb-96cc-287d920604a5.png)
