### ISSUE TITLE
2.8找不到cookie列表

### ISSUE THREAD

**Issue by afeiwei001** [whyour/qinglong#377]

**Comment by zachnaran** [comment]
环境变量不知道是干啥用的

**Comment by langhun** [comment]
和你一样，自动更新后 所有cookie没了

**Comment by langhun** [comment]
> 和你一样，自动更新后 所有cookie没了

刚刚重启了一下服务 又全出来了

**Comment by sydaint** [comment]
更新后不要直接编辑变量，重启一次直接就能恢复原来的cookie
全选批量改名未JD_COOKIE即可

**Comment by qsect** [comment]
新搭建的如何输入cookie？环境变量那怎么设置？跟以前不一样了
