### ISSUE TITLE
版本更新建议

### ISSUE THREAD

**Issue by liuyichenchen** [whyour/qinglong#382]
可以在面板设置里面加一个检测更新吗？或者用户在访问面板的时候系统检测有没有更新然后提示用户是否需要更新，不然现在重启机器就自动更新了，需要修改脚本代码才可以屏蔽掉

**Comment by whyour** [comment]
大佬有想法可以提

**Comment by liuyichenchen** [comment]
用户打开面板，系统后台检测更新，提示在顶部，有更新，列出更新内容，提示用户是否需要更新，是就执行更新，否就不执行，重启更新的就不要加了，有时候用户不想使用新版本，机器出问题要重启，现在的版本会强制更新，另外一个建议每次大更新类似这次的互助码，用户都不知道怎么填写，以后更新可以简单列举说明一下吗，最好有个示范这样更直观，文字简单说明好多小白不会的，不是人人都是大佬你，懂代码

**Comment by whyour** [comment]
@liuyichenchen 我知道这个需求，但是没想清楚怎么实现🤣，我是小弟

**Comment by liuyichenchen** [comment]
打开面板读取青龙的某个参数和服务器的做对比，这样可行？具体的我也不懂，需要大佬自行解决了，😂

**Comment by whyour** [comment]
@liuyichenchen 首先得把静态资源打包进镜像，我看看会大多少

**Comment by liuyichenchen** [comment]
好的，另外环境变量在值太长的情况显示的时候不是很友好，整个页面都是这一个，可以列表显示的时候只显示一部分吗？

**Comment by whyour** [comment]
@liuyichenchen 截图看看，值有最大宽度限制

**Comment by liuyichenchen** [comment]
![image](https://user-images.githubusercontent.com/80599155/122753815-5e744300-d2c5-11eb-8c45-015ae324947a.png)

**Comment by Zy143L** [comment]
你这个Cookie这么长没必要了...JD只需要两个一个是pt_key和一个pt_pin

**Comment by wxjbb** [comment]
> 你这个Cookie这么长没必要了...JD只需要两个一个是pt_key和一个pt_pin

人家是有几百个号才会这么长

**Comment by shanke0303** [comment]
> @liuyichenchen 我知道这个需求，但是没想清楚怎么实现🤣，我是小弟

现在本地有版本号，可以直接拉raw仓库的src/version.ts解析进行比较
