### ISSUE TITLE
有没有遇到 无 cookie问题

### ISSUE THREAD

**Issue by ylwzbk** [whyour/qinglong#385]
服务器明明就是有cookie   一跑脚本就说没cookie 升级2.8版本

**Comment by moumoufa** [comment]
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './jdCookie.js'

是这样吗？

**Comment by wwjjhh1995** [comment]
> internal/modules/cjs/loader.js:905
> throw err;
> ^
> 
> Error: Cannot find module './jdCookie.js'
> 
> 是这样吗？

是的，我也是，求解。

**Comment by moumoufa** [comment]
> > internal/modules/cjs/loader.js:905
> > throw err;
> > ^
> > Error: Cannot find module './jdCookie.js'
> > 是这样吗？
> 
> 是的，我也是，求解。


我是看到别人，然后解决了，把下面的 仓库拉一下。就OK了
docker exec -it qinglong ql repo https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"
