### ISSUE TITLE
重启机器后，青龙面板进不去，网页报错代码如下

### ISSUE THREAD

**Issue by qq9700** [whyour/qinglong#39]
<html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html>

**Comment by qq9700** [comment]
没缓存的浏览器白屏

**Comment by whyour** [comment]
还是报错吗，你这信息没法定位，建议重新run下机器，并且使用最新镜像
