### ISSUE TITLE
青龙面板每天早上无法打开

### ISSUE THREAD

**Issue by yihanxx** [whyour/qinglong#392]
每天早上打开青龙5700都是白板 需要重启才能使用。想请教一下，具体是什么原因导致。

使用的是阿里云服务器

**Comment by Fox04117** [comment]
我的也是同样的问题，求回复

**Comment by WYEEE** [comment]
老大帮忙看看，我也是bot最后一条消息是5:29分的，七点多起床就无法打开了。

portainer看容器信息，发现端口号没了。
![image](https://user-images.githubusercontent.com/47712978/123016743-d9407980-d3fd-11eb-8fd4-8b03d0f7a7b2.png)

网络信息也空了
![image](https://user-images.githubusercontent.com/47712978/123016819-fd9c5600-d3fd-11eb-87f1-e53f5560ad39.png)


求救不想天天重装呀~~

**Comment by WYEEE** [comment]
我需要发哪个log文件可以帮助分析呢？~

**Comment by whyour** [comment]
> 我需要发哪个log文件可以帮助分析呢？~

查看下  docker logs qinglong
