### ISSUE TITLE
青龙如何自己配置助力信息

### ISSUE THREAD

**Issue by qqjayzhe** [whyour/qinglong#394]
青龙如何自己配置助力信息

**Comment by tinpont** [comment]
同问，现在改了之后配置互助比较困难，希望还是把自动互助的功能恢复。

**Comment by HuTao1996** [comment]
> 同问，现在改了之后配置互助比较困难，希望还是把自动互助的功能恢复。

作者就是想删除，所以移除了全自动化助力

**Comment by yuntian123456** [comment]
过于方便和自动化就导致各种代挂的经济行为，所以作者故意移除，提高门槛。所以你们不用再要求了。薅不薅得到羊毛，各凭实力吧。毕竟，薅羊毛本身就是一种包含一定技术实力的事情，不是面向普通大众和小白的。
