### ISSUE TITLE
请求更新一下后端的cookie管理的api

### ISSUE THREAD

**Issue by wxjbb** [whyour/qinglong#395]
http://[ip]:5700/api/cookies?t=xxxxxxx
这些cookie增删改的api在2.8版本里面貌似，不适用了，新版里面没有cookie.db和cookie.sh了

**Comment by moumoufa** [comment]
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './jdCookie.js'

我这个是什么情况啊？是楼主你说得这种嘛

**Comment by wxjbb** [comment]
> internal/modules/cjs/loader.js:905
> throw err;
> ^
> 
> Error: Cannot find module './jdCookie.js'
> 
> 我这个是什么情况啊？是楼主你说得这种嘛

不是啊，我们说的不是同一个东西
