### ISSUE TITLE
ENV怎么填，跟之前版本不一样了

### ISSUE THREAD

**Issue by andrew-0905** [whyour/qinglong#398]
共0个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/6/23 下午5:30:19=====================

==============📣系统通知📣==============
家电星推官
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取
https://bean.m.jd.com/bean/signIndex.action

名称填什么？ 值应该填cookie吧？

**Comment by whyour** [comment]
https://t.me/jiaolongwang/120
