### ISSUE TITLE
大佬，我用的青龙2.2，有个问题，手动点开始，再点停止，无法停止，日志仍然在输出

### ISSUE THREAD

**Issue by prcxu** [whyour/qinglong#402]
大佬，我用的青龙2.2，有个问题，手动点开始，再点停止，无法停止，日志仍然在输出

**Comment by hrj5032188** [comment]
别怕 2.8也有这个问题

**Comment by prcxu** [comment]
哈哈



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月24日(星期四) 下午5:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 大佬，我用的青龙2.2，有个问题，手动点开始，再点停止，无法停止，日志仍然在输出 (#402)





 
别怕 2.8也有这个问题
