### ISSUE TITLE
求助多个cookie无法识别

### ISSUE THREAD

**Issue by woboo110** [whyour/qinglong#404]
新版填一个cookie可以正常运行，填入多个cookie就识别不了，显示如下

![image](https://user-images.githubusercontent.com/68997087/123211366-f5bfdd00-d4f5-11eb-858e-21615addb104.png)

**Comment by whyour** [comment]
@woboo110 用频道的task_before把你的覆盖下

**Comment by woboo110** [comment]
> @woboo110 用频道的task_before把你的覆盖下

搞定了。感谢
