### ISSUE TITLE
大佬，我的最新版在拉库的时候遇到问题，百度半天不会解决，特此来请教

### ISSUE THREAD

**Issue by dreamfrog7** [whyour/qinglong#407]
在容器中执行  ql repo https://github.com/photonmang/quantumultX.git "JDscripts"
提示：
开始更新仓库：/ql/repo/photonmang_quantumultX

Fetching origin
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

更新/ql/repo/photonmang_quantumultX成功...
![laku](https://user-images.githubusercontent.com/25612506/123293783-db621f80-d546-11eb-9402-f482ab21ae2b.png)

**Comment by Acr05s** [comment]
ql repo https://ghproxy.com/https://github.com/photonmang/quantumultX.git "JDscripts" 可以拉啊，我拉了，感谢分享这三个js

**Comment by Acr05s** [comment]
不过joy好像还是有问题
