### ISSUE TITLE
请问自定义脚本，怎么才能正确添加定时任务。

### ISSUE THREAD

**Issue by reviveymj** [whyour/qinglong#41]
![image](https://user-images.githubusercontent.com/78457555/115103319-e3c62a80-9f05-11eb-8be4-e5e0dc458b57.png)
请问青龙，我按照提供extra.sh的模板，可拉取您的脚本和柘的脚本到本地 。/ql/config/crontab.list 添加到这个定时目录对吗？
怎么才能正确添加自定义脚本的定时任务到面板呢？还请指教方法~！

**Comment by landcruser** [comment]
为什么我不能这两个脚本拉取到本地，显示不存在啊

**Comment by whyour** [comment]
> ![image](https://user-images.githubusercontent.com/78457555/115103319-e3c62a80-9f05-11eb-8be4-e5e0dc458b57.png)
> 请问青龙，我按照提供extra.sh的模板，可拉取您的脚本和柘的脚本到本地 。/ql/config/crontab.list 添加到这个定时目录对吗？
> 怎么才能正确添加自定义脚本的定时任务到面板呢？还请指教方法~！

使用最新的diy命令拉取
diy https://ghproxy.com/https://github.com/whyour/hundun.git "quanx/jx|quanx/jd" tokens >> $QL_DIR/log/diy_pull.log 2>&1
