### ISSUE TITLE
查看几个脚本日志后网页空白

### ISSUE THREAD

**Issue by lynn0804** [whyour/qinglong#412]
## Date: 2021-06-20

在定时任务界面 查看超过两个左右的日志的时候网页就会空白 只能刷新页面才能显示内容

**Comment by whyour** [comment]
截图看看

**Comment by zorgzola** [comment]
可能这个问题：
cdn.jsdelivr.net
被去广告了，放行就解决了。

**Comment by lynn0804** [comment]
> 截图看看

![image](https://user-images.githubusercontent.com/52002734/124259874-9dc24f80-db61-11eb-9ce0-6390a4de6710.png)
