### ISSUE TITLE
请求添加"png-js"依赖

### ISSUE THREAD

**Issue by shanke0303** [whyour/qinglong#418]
现在不少脚本用到这个了，麻烦加一下。手动添加的话，每天定时ql update都被还原回来了

**Comment by 17huiwei** [comment]
docker exec -it qinglong bash -c "cd scripts && npm i -S png-js"

**Comment by shanke0303** [comment]
> docker exec -it qinglong bash -c "cd scripts && npm i -S png-js"

嗯，这个我会，但是只要执行ql update，package.json就会同步为作者的

**Comment by tkjune** [comment]
> > docker exec -it qinglong bash -c "cd scripts && npm i -S png-js"
> 
> 嗯，这个我会，但是只要执行ql update，package.json就会同步为作者的

那不加-S 不保存到 package.json 里就行了吧? 这个库应该也不怎么需要更新

**Comment by shanke0303** [comment]
> > > docker exec -it qinglong bash -c "cd scripts && npm i -S png-js"
> > 
> > 
> > 嗯，这个我会，但是只要执行ql update，package.json就会同步为作者的
> 
> 那不加-S 不保存到 package.json 里就行了吧? 这个库应该也不怎么需要更新

一些新的脚本可是用到这个依赖了，我猜是用来解决图形验证问题的

**Comment by BlueSpiderGIGI** [comment]
> > > docker exec -it qinglong bash -c "cd scripts && npm i -S png-js"
> > 
> > 
> > 嗯，这个我会，但是只要执行ql update，package.json就会同步为作者的
> 
> 那不加-S 不保存到 package.json 里就行了吧? 这个库应该也不怎么需要更新

没用的，只要安装过，ql update 一定会检测依赖，一样会还原回去的

**Comment by whyour** [comment]
@BlueSpiderGIGI 不加 -S 不会写进 package.json 所以检测不出来，你更新试试

**Comment by BlueSpiderGIGI** [comment]
> @BlueSpiderGIGI 不加 -S 不会写进 package.json 所以检测不出来，你更新试试

不能~我一直都是用npm install png-js canvas，一样会检测到依赖变化，没有加过-S -g之类的

**Comment by BlueSpiderGIGI** [comment]
![image](https://user-images.githubusercontent.com/25193974/123890211-6c8f2700-d989-11eb-9e71-b33587f16094.png)
安装时未用带参数安装的canvas png-js，ql update后检测到依赖变化
![image](https://user-images.githubusercontent.com/25193974/123890375-af50ff00-d989-11eb-8dbb-f52a86455ce8.png)
更新后已丢失

**Comment by whyour** [comment]
安装依赖后执行  cp /ql/sample/package.json /ql/scripts

**Comment by BlueSpiderGIGI** [comment]
> 安装依赖后执行 cp /ql/sample/package.json /ql/scripts

可以，有效
那看来每次会同步ql/scripts里面的package.json的变化

**Comment by whyour** [comment]
> > 安装依赖后执行 cp /ql/sample/package.json /ql/scripts
> 
> 可以，有效
> 那看来每次会同步ql/scripts里面的package.json的变化

不加-S以前是不修改package.json的，最新的修改了

**Comment by shuaixiaomi** [comment]
请问安装png-js 一直报错怎么办？
![image](https://user-images.githubusercontent.com/77660384/150496603-5dd2e750-5c67-4673-bd44-5f232efe6ff8.png)
