### ISSUE TITLE
机器人生成的获取cookie二维码不能用了

### ISSUE THREAD

**Issue by bertms** [whyour/qinglong#422]
/getcookie 能正常生成二维码，但是扫码以后提示升级京豆APP到最新版，已经是最新版了，请教各位大佬如何弄

**Comment by whyour** [comment]
这是机器人的问题吧

**Comment by bertms** [comment]
机器人一直都好好的，升级2.8以后就这样了

**Comment by bertms** [comment]
报这个错误
发生了某些错误
21

**Comment by whyour** [comment]
@bertms 大佬，青龙只是启动了下机器人，你去机器人仓库看看

**Comment by bertms** [comment]
> @bertms 大佬，青龙只是启动了下机器人，你去机器人仓库看看

感谢大佬我去仓库看了，有人遇到了此问题，但是没人回复如何解决。
