### ISSUE TITLE
无法 启动控制面板 panel 的status为stopped

### ISSUE THREAD

**Issue by devilloki** [whyour/qinglong#423]
4. 启动控制面板
panel 的status为stopped，
打开网页显示从空白。

硬件：树莓派ZERO W

**Comment by devilloki** [comment]
这是pm2的日志
`0|panel  | Error: Cannot find module 'reflect-metadata'
0|panel  | Require stack:
0|panel  | - /ql/build/app.js
0|panel  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
0|panel  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|panel  |     at require (internal/modules/cjs/helpers.js:92:18)
0|panel  |     at Object.<anonymous> (/ql/back/app.ts:1:1)
0|panel  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
0|panel  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
0|panel  |     at Module.load (internal/modules/cjs/loader.js:950:32)
0|panel  |     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
0|panel  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|panel  |     at Module._compile (internal/modules/cjs/loader.js:1085:14) {
0|panel  |   code: 'MODULE_NOT_FOUND',
0|panel  |   requireStack: [ '/ql/build/app.js' ]
0|panel  | }
`

**Comment by whyour** [comment]
ql reset
ql update
