### ISSUE TITLE
求问大佬如何迁移青龙

### ISSUE THREAD

**Issue by MinanaYaa** [whyour/qinglong#424]
大佬怎么迁移青龙呢

**Comment by doghappy** [comment]
启动容器时，会把 config 和 db 目录映射到物理机，只需要备份这些文件即可。
迁移时，上传这些文件，再次启动容器时，映射你刚刚上传的文件路径即可。

**Comment by MinanaYaa** [comment]
> 启动容器时，会把 config 和 db 目录映射到物理机，只需要备份这些文件即可。
> 迁移时，上传这些文件，再次启动容器时，映射你刚刚上传的文件路径即可。
感谢
