### ISSUE TITLE
访问ip+端口提示未找到授权令牌令牌

### ISSUE THREAD

**Issue by imqimu** [whyour/qinglong#426]
{"code":401,"message":"No authorization token was found"}

**Comment by imqimu** [comment]
![image](https://user-images.githubusercontent.com/72058508/123739746-bcaeb080-d8d9-11eb-9b95-03241345012c.png)
在宿主机和容器内执行curl都提示未找到授权令牌

**Comment by whyour** [comment]
@imqimu ql update 
ql check

**Comment by imqimu** [comment]
![image](https://user-images.githubusercontent.com/72058508/123740091-64c47980-d8da-11eb-84c7-7430f8ce3b81.png)

**Comment by whyour** [comment]
@imqimu 不去5700登录面板？

**Comment by whyour** [comment]
@imqimu 你端口都绑错了吧，没绑5700，绑5600干啥

**Comment by imqimu** [comment]
映射的5600，这两天拉镜像本地都是空文件夹，今天试了试5600映射的文件夹内有文件，但是网站无法访问了

**Comment by whyour** [comment]
@imqimu 端口映射跟文件夹映射有啥关系？

**Comment by imqimu** [comment]
但也挺迷惑的，这个是映射5700的文件夹
![image](https://user-images.githubusercontent.com/72058508/123740518-28dde400-d8db-11eb-9a9b-d5710fe16eb1.png)
这个是5600
![image](https://user-images.githubusercontent.com/72058508/123740574-3e530e00-d8db-11eb-82a2-c367a91cc36f.png)
好像少了auth.json

**Comment by whyour** [comment]
@imqimu 映射是命令加的，你没问数据的话，容器删了，换个映射目录

**Comment by imqimu** [comment]
我在试一下吧，感谢大佬回复

**Comment by whyour** [comment]
@imqimu 跟5600 5700 没关系，看你的映射目录

**Comment by imqimu** [comment]
问题已解决，换了映射目录，可以访问了。
再次感谢。
