### ISSUE TITLE
青龙docker镜像拉下来了，但是里面啥都没有

### ISSUE THREAD

**Issue by Mr-xiao90** [whyour/qinglong#428]
里面就这点东西，啥都没有，这是咋回事？
![image](https://user-images.githubusercontent.com/20120426/123826285-35d9f200-d932-11eb-855e-8479adac203a.png)

**Comment by Mr-xiao90** [comment]
![image](https://user-images.githubusercontent.com/20120426/123826432-57d37480-d932-11eb-82c5-768eeb35ef53.png)

**Comment by Mr-xiao90** [comment]
![image](https://user-images.githubusercontent.com/20120426/123826596-7e91ab00-d932-11eb-9802-f7cc5aca1ced.png)

**Comment by Mr-xiao90** [comment]
![image](https://user-images.githubusercontent.com/20120426/123826707-98cb8900-d932-11eb-8b54-10855dd7f10b.png)

**Comment by Mr-xiao90** [comment]
![image](https://user-images.githubusercontent.com/20120426/123826759-a41eb480-d932-11eb-8f18-485ce6bb015a.png)

**Comment by whyour** [comment]
本来就是这样 https://t.me/jiaolongwang

**Comment by Mr-xiao90** [comment]
> 本来就是这样https://t.me/jiaolongwang

哦谢谢，原来这个还需要手动运行代码拉仓库
