### ISSUE TITLE
面板里的js hangup运行不了

### ISSUE THREAD

**Issue by rogerujn** [whyour/qinglong#43]
面板里的js hangup运行不了，必须手动输入命令docker exec -it qinglong js hangup才能启动挂机。

**Comment by whyour** [comment]
> 面板里的js hangup运行不了，必须手动输入命令docker exec -it qinglong js hangup才能启动挂机。

这个挂机程序不是个定时任务，建议还是使用一次性命令，后面会从初始化数据中去掉这个任务
