### ISSUE TITLE
2.2版泄漏ck风险是哪?没办法?

### ISSUE THREAD

**Issue by hdstar2009** [whyour/qinglong#431]
刚刚熟悉2.2的使用才1个月不到,真不想又开始学新的2.8

**Comment by ChellyL** [comment]
绕过登录 shell

**Comment by whyour** [comment]
> 刚刚熟悉2.2的使用才1个月不到,真不想又开始学新的2.8

你可以按照最新代码的提交自己修复下

**Comment by hdstar2009** [comment]
> > 刚刚熟悉2.2的使用才1个月不到,真不想又开始学新的2.8
> 
> 你可以按照最新代码的提交自己修复下

是将那些修复token的文件，如 /ql/back/loaders/express.ts 去覆盖docker里面的文件就可以了？

**Comment by MangoDong** [comment]
大佬说的


复制2个文件到一个目录  
我这里复制到了/root/ql/config/
然后我的容器名字叫qinglong
以上都是需要改的
例如 sudo docker cp 你放的位置/express.ts 容器名字:/ql/back/loaders


sudo docker cp /root/ql/config/express.ts qinglong:/ql/back/loaders


sudo docker cp /root/ql/config/util.ts qinglong:/ql/back/loaders/config

**Comment by hdstar2009** [comment]
就express.ts和util.ts两个文件？我看更新修复token的有好几个文件

**Comment by hdstar2009** [comment]
> 大佬说的
> 
> 复制2个文件到一个目录
> 我这里复制到了/root/ql/config/
> 然后我的容器名字叫qinglong
> 以上都是需要改的
> 例如 sudo docker cp 你放的位置/express.ts 容器名字:/ql/back/loaders
> 
> sudo docker cp /root/ql/config/express.ts qinglong:/ql/back/loaders
> 
> sudo docker cp /root/ql/config/util.ts qinglong:/ql/back/loaders/config

你第二个文件应该拷贝错误目录了，/ql/back/loaders/config这个目录是不存在的，/ql/back/config这个目录下有util.ts

**Comment by whyour** [comment]
直接使用最新的2.2镜像试试

**Comment by hdstar2009** [comment]
> 直接使用最新的2.2镜像试试

用新镜像生成新容器？那么之前容器设置好的任务，改好的脚本等等内容都没了吧，很多脚本并不是直接ql repo回来的，task的cron时间也改过。

**Comment by whyour** [comment]
@hdstar2009 你不能备份下scripts目录？

**Comment by hdstar2009** [comment]
> 直接使用最新的2.2镜像试试

我是不是将修改的那些文件，修复token的，全部替换掉现在容器里面的旧文件，就算修复成功？

**Comment by whyour** [comment]
@hdstar2009 要编译，cron数据不会变，唯一就是scripts目录找不到脚本

**Comment by hdstar2009** [comment]
> @hdstar2009 你不能备份下scripts目录？

用新镜像生成的容器，cron那些数据不会变？我改过很多cron的，特别是所有脚本的开头，panghu999_jd_scripts这种加库头，我都去掉了都直接是jd_syj.js这样，之后手工更新个别脚本不再拉库。
有没有办法备份出cron的数据，用新的镜像生成容器后将cron数据和scripts数据都恢复回去？

**Comment by whyour** [comment]
@hdstar2009 cron数据个env数据都在db目录，这个目录映射的，跟其他没关系
