### ISSUE TITLE
   whyour/qinglong:2.2.0部署后，启动后还是更像成最新版了。

### ISSUE THREAD

**Issue by piaoyun** [whyour/qinglong#434]
whyour/qinglong:2.2.0

第一次部署好，进去就变成最新版。容器没有启动。没有执行命令

**Comment by piaoyun** [comment]
![QQ截图20210701122030](https://user-images.githubusercontent.com/3724475/124064129-ca457100-da66-11eb-9a7b-3ae79a989e72.png)
![QQ截图20210701122048](https://user-images.githubusercontent.com/3724475/124064132-cd406180-da66-11eb-85bb-43fed9f8460b.png)

**Comment by whyour** [comment]
用最新镜像
