### ISSUE TITLE
2.2的最新docker镜像创建后卡BUG无法正常启动

### ISSUE THREAD

**Issue by s1sunny** [whyour/qinglong#435]
======================1. 检测配置文件========================
,'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
,======================2. 启动nginx========================
,nginx启动成功...
,======================3. 启动控制面板========================
,[PM2][ERROR] Script not found: /ql/build/app.js

一直反复循环

**Comment by mjyhj** [comment]
一样启动不了
![1](https://user-images.githubusercontent.com/22577418/124064171-d7626000-da66-11eb-9ba7-13fd37169877.png)

**Comment by hdstar2009** [comment]
果然谨慎是好态度

**Comment by imqimu** [comment]
一样的

**Comment by hege009** [comment]
缺少文件

**Comment by hege009** [comment]
效果一样

**Comment by yanyuwangluo** [comment]
2.2.0文件里面没有面板文件。面板文件放进去。面板能启动。提示找不到app.js 怀疑pm2没有建立软连接

**Comment by miRemid** [comment]
same

**Comment by zq1121734772** [comment]
same

**Comment by whyour** [comment]
用最新镜像
