### ISSUE TITLE
extra.sh 拉取自定义仓库显示更新失败

### ISSUE THREAD

**Issue by study875** [whyour/qinglong#44]
extra.sh 拉取自定义仓库显示
whyour_jd_collectBlueCoin.js
wget: server returned error: HTTP/1.1 308 Permanent Redirect
更新 whyour_jd_collectBlueCoin.js 失败，使用上一次正常的版本...

**Comment by whyour** [comment]
> extra.sh 拉取自定义仓库显示
> whyour_jd_collectBlueCoin.js
> wget: server returned error: HTTP/1.1 308 Permanent Redirect
> 更新 whyour_jd_collectBlueCoin.js 失败，使用上一次正常的版本...

建议使用 diy 命令拉取
`diy https://ghproxy.com/https://github.com/whyour/hundun.git "quanx/jx|quanx/jd" tokens >> $QL_DIR/log/diy_pull.log 2>&1`

**Comment by study875** [comment]
你好问下 monk 的 dust 仓库 这样设置好像拉取不了，是我 extra.sh 脚本弄错了吗

**Comment by whyour** [comment]
> 你好问下 monk 的 dust 仓库 这样设置好像拉取不了，是我 extra.sh 脚本弄错了吗
> 
> https://raw.githubusercontent.com/dockere/jd-base/master/sample/diy.sh

那个仓库私有了，不能这么拉取。你去柘和尚大佬群里看看，怎么拉取

**Comment by study875** [comment]
我找了一圈，找不到拓和尚的群，方便告知吗？如果不方便留言 可以私信我吗 真的是谢谢你了

**Comment by whyour** [comment]
@study875 https://t.me/joinchat/ePOwj93Mn-w5NmU5

**Comment by study875** [comment]
我这边找了下只有布道场

**Comment by study875** [comment]
非常感谢
