### ISSUE TITLE
内部助力问题

### ISSUE THREAD

**Issue by xwuchen** [whyour/qinglong#441]
升级到最新版本，就没有内部助力了，看了最新说明，需要在task_before.sh中添加代码，一直没看明白，哪位大神指导一下?感谢！

**Comment by hixuchang** [comment]
同求一个详细格式

**Comment by MoLing-Dong** [comment]
https://blog.mo0.top助力自行查看

**Comment by MoLing-Dong** [comment]
> [https://blog.mo0.top助力自行查看](https://blog.mo0.top)

**Comment by MoLing-Dong** [comment]
https://blog.mo0.top

助力自行查看
