### ISSUE TITLE
更新面板后 进不去了

### ISSUE THREAD

**Issue by SoYang95** [whyour/qinglong#442]
![image](https://user-images.githubusercontent.com/25340441/124226520-d6e7c900-db3b-11eb-8ad9-5f416a264b80.png)

![image](https://user-images.githubusercontent.com/25340441/124226468-be77ae80-db3b-11eb-9c01-15ad75c0319a.png)

![image](https://user-images.githubusercontent.com/25340441/124226489-c8011680-db3b-11eb-95fb-6c96329567b5.png)

**Comment by whyour** [comment]
ql check
