### ISSUE TITLE
2.8 和2.2 拉取镜像都同时出现not found: /ql/build/app.js 试了几次了

### ISSUE THREAD

**Issue by lichen780** [whyour/qinglong#445]
2.8 和2.2 拉取镜像都同时出现not found: /ql/build/app.js 查看镜像 这文件存在的。。
2.2 和2.8的都是这问题

![2.8](https://p.pstatp.com/origin/pgc-image/8800cbf14fd5408bbb590562d81f37db)

**Comment by whyour** [comment]
把容器要删掉

**Comment by lichen780** [comment]
> 把容器要删掉

删掉容器了的，开始以为服务器文件，为此我还买了个月抛鸡来测试  还是同样的情况

**Comment by whyour** [comment]
你是镜像没拉到最新的？有镜像cdn？

**Comment by lichen780** [comment]
> 你是镜像没拉到最新的？有镜像cdn？

拉的最新的  没用cdn
docker pull whyour/qinglong

**Comment by lichen780** [comment]
镜像也试过  拉github的文件本地生成镜像也试过 都是这样

**Comment by whyour** [comment]
REPOSITORY           TAG       IMAGE ID       CREATED        SIZE
whyour/qinglong      latest    d254fd268b3e   41 hours ago   289MB

看创建时间你的是不是最新的

**Comment by lichen780** [comment]
> REPOSITORY TAG IMAGE ID CREATED SIZE
> whyour/qinglong latest d254fd268b3e 41 hours ago 289MB
> 
> 看创建时间你的是不是最新的

最新的
