### ISSUE TITLE
不能自动执行任务。

### ISSUE THREAD

**Issue by 13810169** [whyour/qinglong#449]
2.8的刚安装后 一切正常，但是只要更新几天之后，就不能自动执行任务了，每次都得重新安装，就想着用2.2的，结果2.2的安装之后自动更新一次直接连界面都进不去了。。。。

**Comment by whyman365** [comment]
我也是，现在是重装回2.2以后自动运行不能获取环境变量，手动运行就有

**Comment by yhboss** [comment]
看了下日志，原来是因为容器刚启动时拉库，但有的库失效了，导致后续crond没有启动，可以删掉失效库重启容器或者手动启动crond，拜托大佬修一下吧

**Comment by kissyouhunter** [comment]
> 看了下日志，原来是因为容器刚启动时拉库，但有的库失效了，导致后续crond没有启动，可以删掉失效库重启容器或者手动启动crond，拜托大佬修一下吧

以前没有这个问题吧
我说怎么日志一个都没生产

**Comment by yhboss** [comment]
> > 看了下日志，原来是因为容器刚启动时拉库，但有的库失效了，导致后续crond没有启动，可以删掉失效库重启容器或者手动启动crond，拜托大佬修一下吧
> 
> 以前没有这个问题吧
> 我说怎么日志一个都没生产

不知道以前有没有，最近很多脚本作者跑路，库都失效了

**Comment by kissyouhunter** [comment]
> > > 看了下日志，原来是因为容器刚启动时拉库，但有的库失效了，导致后续crond没有启动，可以删掉失效库重启容器或者手动启动crond，拜托大佬修一下吧
> > 
> > 
> > 以前没有这个问题吧
> > 我说怎么日志一个都没生产
> 
> 不知道以前有没有，最近很多脚本作者跑路，库都失效了

你说的log是在哪看到的
我想看下我的

**Comment by yhboss** [comment]
> > > > 看了下日志，原来是因为容器刚启动时拉库，但有的库失效了，导致后续crond没有启动，可以删掉失效库重启容器或者手动启动crond，拜托大佬修一下吧
> > > 
> > > 
> > > 以前没有这个问题吧
> > > 我说怎么日志一个都没生产
> > 
> > 
> > 不知道以前有没有，最近很多脚本作者跑路，库都失效了
> 
> 你说的log是在哪看到的
> 我想看下我的

我看的是docker的日志

**Comment by kissyouhunter** [comment]
> > > > > 看了下日志，原来是因为容器刚启动时拉库，但有的库失效了，导致后续crond没有启动，可以删掉失效库重启容器或者手动启动crond，拜托大佬修一下吧
> > > > 
> > > > 
> > > > 以前没有这个问题吧
> > > > 我说怎么日志一个都没生产
> > > 
> > > 
> > > 不知道以前有没有，最近很多脚本作者跑路，库都失效了
> > 
> > 
> > 你说的log是在哪看到的
> > 我想看下我的
> 
> 我看的是docker的日志

看到了
卡在wenmoux的仓库了

**Comment by whyour** [comment]
> > > > > > 看了下日志，原来是因为容器刚启动时拉库，但有的库失效了，导致后续crond没有启动，可以删掉失效库重启容器或者手动启动crond，拜托大佬修一下吧
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 以前没有这个问题吧
> 
> > > > > 我说怎么日志一个都没生产
> 
> > > > 
> 
> > > > 
> 
> > > > 不知道以前有没有，最近很多脚本作者跑路，库都失效了
> 
> > > 
> 
> > > 
> 
> > > 你说的log是在哪看到的
> 
> > > 我想看下我的
> 
> > 
> 
> > 我看的是docker的日志
> 
> 
> 
> 看到了
> 
> 卡在wenmoux的仓库了

贴下图

**Comment by kissyouhunter** [comment]
> > > > > > > 看了下日志，原来是因为容器刚启动时拉库，但有的库失效了，导致后续crond没有启动，可以删掉失效库重启容器或者手动启动crond，拜托大佬修一下吧
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > 以前没有这个问题吧
> > 
> > 
> > > > > > 我说怎么日志一个都没生产
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 不知道以前有没有，最近很多脚本作者跑路，库都失效了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 你说的log是在哪看到的
> > 
> > 
> > > > 我想看下我的
> > 
> > 
> > > 
> > 
> > 
> > > 我看的是docker的日志
> > 
> > 
> > 看到了
> > 卡在wenmoux的仓库了
> 
> 贴下图

![1135DC4C-B4D1-4E34-B636-5D1A033003FA](https://user-images.githubusercontent.com/63334206/124513531-958e3c80-de0d-11eb-92df-4b2e0c948e90.jpeg)

**Comment by whyour** [comment]
> > > > > > > > 看了下日志，原来是因为容器刚启动时拉库，但有的库失效了，导致后续crond没有启动，可以删掉失效库重启容器或者手动启动crond，拜托大佬修一下吧
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > 以前没有这个问题吧
> > > 
> > > 
> > > > > > > 我说怎么日志一个都没生产
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > > 不知道以前有没有，最近很多脚本作者跑路，库都失效了
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 你说的log是在哪看到的
> > > 
> > > 
> > > > > 我想看下我的
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 我看的是docker的日志
> > > 
> > > 
> > > 看到了
> > > 卡在wenmoux的仓库了
> > 
> > 
> > 贴下图
> 
> ![1135DC4C-B4D1-4E34-B636-5D1A033003FA](https://user-images.githubusercontent.com/63334206/124513531-958e3c80-de0d-11eb-92df-4b2e0c948e90.jpeg)

这是容器的启动日志？

**Comment by yhboss** [comment]
> > > > > > > > > 看了下日志，原来是因为容器刚启动时拉库，但有的库失效了，导致后续crond没有启动，可以删掉失效库重启容器或者手动启动crond，拜托大佬修一下吧
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > 以前没有这个问题吧
> > > > 
> > > > 
> > > > > > > > 我说怎么日志一个都没生产
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > > > 不知道以前有没有，最近很多脚本作者跑路，库都失效了
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > 你说的log是在哪看到的
> > > > 
> > > > 
> > > > > > 我想看下我的
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 我看的是docker的日志
> > > > 
> > > > 
> > > > 看到了
> > > > 卡在wenmoux的仓库了
> > > 
> > > 
> > > 贴下图
> > 
> > 
> > ![1135DC4C-B4D1-4E34-B636-5D1A033003FA](https://user-images.githubusercontent.com/63334206/124513531-958e3c80-de0d-11eb-92df-4b2e0c948e90.jpeg)
> 
> 这是容器的启动日志？

是的，查看了容器启动日志就是卡在了失效的库那，导致后面crond不启动，所以自动任务不能运行了

**Comment by whyour** [comment]
@yhboss 容器日志怎么可能有这个，更新仓库的任务是异步执行的，跟容器启动没关系

**Comment by yhboss** [comment]
@whyour 这个启动日志可以在容器刚启动时，portainer的日志管理看到

**Comment by yhboss** [comment]
@whyour 
![image](https://user-images.githubusercontent.com/17646640/124737006-25390580-df4a-11eb-8ecf-66afb1360938.png)

**Comment by whyour** [comment]
> @whyour
> ![image](https://user-images.githubusercontent.com/17646640/124737006-25390580-df4a-11eb-8ecf-66afb1360938.png)
> 重启了容器，更新完后才会显示crond started

你这是什么环境的docker

**Comment by yhboss** [comment]
@whyour 

> > @whyour
> > ![image](https://user-images.githubusercontent.com/17646640/124737006-25390580-df4a-11eb-8ecf-66afb1360938.png)
> > 重启了容器，更新完后才会显示crond started
> 
> 你这是什么环境的docker

arm64的

**Comment by 13810169** [comment]
> @yhboss 容器日志怎么可能有这个，更新仓库的任务是异步执行的，跟容器启动没关系

是这样的,只要有失效的库，就会卡住，那个日志不会继续往下走，青龙的面板可以进去，但是不会自动执行已经添加的任务。

**Comment by whyour** [comment]
> @whyour
> 
> > > @whyour
> > > ![image](https://user-images.githubusercontent.com/17646640/124737006-25390580-df4a-11eb-8ecf-66afb1360938.png)
> > > 重启了容器，更新完后才会显示crond started
> > 
> > 
> > 你这是什么环境的docker
> 
> arm64的

晚点远程看看，测试测试，我这amd的好像没问题啊

**Comment by whyour** [comment]
> > @yhboss 容器日志怎么可能有这个，更新仓库的任务是异步执行的，跟容器启动没关系
> 
> 是这样的,只要有失效的库，就会卡住，那个日志不会继续往下走，青龙的面板可以进去，但是不会自动执行已经添加的任务。

我懂你意思，既然容器启动成功了，肯定最后执行到 crond -f 了，你也是arm的？

**Comment by 13810169** [comment]
> > > @yhboss 容器日志怎么可能有这个，更新仓库的任务是异步执行的，跟容器启动没关系
> > 
> > 
> > 是这样的,只要有失效的库，就会卡住，那个日志不会继续往下走，青龙的面板可以进去，但是不会自动执行已经添加的任务。
> 
> 我懂你意思，既然容器启动成功了，肯定最后执行到 crond -f 了，你也是arm的？

我是amd64的，我昨天重启机器后，就发现再没执行过任务，除了一个通知删除脚本的，其他都没有，我下午试着一个个看自己添加的那些仓库，只要有跑不过去，失效的就都注释掉，之后就正常了，只要在启动日志那里全部跑完，没有卡住，就可以自动执行任务。

**Comment by whyour** [comment]
> > > > @yhboss 容器日志怎么可能有这个，更新仓库的任务是异步执行的，跟容器启动没关系
> 
> > > 
> 
> > > 
> 
> > > 是这样的,只要有失效的库，就会卡住，那个日志不会继续往下走，青龙的面板可以进去，但是不会自动执行已经添加的任务。
> 
> > 
> 
> > 我懂你意思，既然容器启动成功了，肯定最后执行到 crond -f 了，你也是arm的？
> 
> 
> 
> 我是amd64的，我昨天重启机器后，就发现再没执行过任务，除了一个通知删除脚本的，其他都没有，我下午试着一个个看自己添加的那些仓库，只要有跑不过去，失效的就都注释掉，之后就正常了，只要在启动日志那里全部跑完，没有卡住，就可以自动执行任务。

你咋看的启动日志，启动日志有拉取仓库的？

**Comment by 13810169** [comment]
> > > > > @yhboss 容器日志怎么可能有这个，更新仓库的任务是异步执行的，跟容器启动没关系
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 是这样的,只要有失效的库，就会卡住，那个日志不会继续往下走，青龙的面板可以进去，但是不会自动执行已经添加的任务。
> > 
> > 
> > > 
> > 
> > 
> > > 我懂你意思，既然容器启动成功了，肯定最后执行到 crond -f 了，你也是arm的？
> > 
> > 
> > 我是amd64的，我昨天重启机器后，就发现再没执行过任务，除了一个通知删除脚本的，其他都没有，我下午试着一个个看自己添加的那些仓库，只要有跑不过去，失效的就都注释掉，之后就正常了，只要在启动日志那里全部跑完，没有卡住，就可以自动执行任务。
> 
> 你咋看的启动日志，启动日志有拉取仓库的？

portainer里面看的，启动的时候确实是有拉取仓库的内容。本来120多条，我在portainer里面点了一下青龙的重启，在日志我看到在拉仓库，进去青龙面板以后果然多了10几条任务。

**Comment by whyour** [comment]
@13810169 不用portainer呢，服务器里直接启动容器试试

**Comment by 13810169** [comment]
> @13810169 不用portainer呢，服务器里直接启动容器试试

呃......portainer也只是个docker容器而已，两者相互隔离的,这一个容器还能影响另一个容器吗？

**Comment by whyour** [comment]
@13810169 那你觉得他是怎么拿到别的容器的启动日志的

**Comment by 13810169** [comment]
> @13810169 那你觉得他是怎么拿到别的容器的启动日志的

我来反馈了，说下操作过程。
1.先把portainer关闭。
2.进入青龙面板设置一个任务时间为21.10分。
3.添加一个失效的仓库。
4.命令行方式先停止青龙，然后命令行方式再启动青龙。
5.等到21.10分，发现设置的定时任务并没有执行。多等了3分钟也没有执行。
6.进入青龙面板，把失效的库删除。
7.把刚才的定时任务设置为21.15分。
8.然后通过命令行方式停止青龙，然后再启动青龙。
9.等21.15分，进入青龙面板的日志，查看发现任务在21.15分执行完毕。
10.查看青龙的update脚本日志，发现第一次启动的时候就是那个失效的库没有跑完。第二次启动的时候所有自己添加的库都跑完了，一切正常。

**Comment by 13810169** [comment]
> @13810169 容器启动不执行update，你查看update日志是？
1.下面是第一次启动时间点的update日志里面extra.log（截取最后一段）。
--------------------------------------------------------------

开始更新仓库：/ql/repo/hyzaw_scripts

Fetching origin（到这里就再没有了）
2.下面是第二次启动时间点的update日志里面extra.log（截取最后一段）
开始更新仓库：/ql/repo/ZCY01_daily_scripts

Fetching origin
HEAD is now at faa1ec3 update jd_try.js
Already up to date.
Current branch main is up to date.

更新/ql/repo/ZCY01_daily_scripts成功...


## 执行结束... 2021-07-08 21:14:36  耗时 62 秒

可以看到第二次没有失效库的时候，这里是有执行结束的。第一次有失效的库，到失效库哪里就没有下文了。
并且update任务在定时任务面板里面还设置了禁用。但是每次启动容器都会自动执行update。一旦update里面的extra有失效的仓库链接，那进去容器之后定时任务就不执行。

**Comment by 13810169** [comment]
> @13810169 容器启动不执行update，你查看update日志是？
1.下面是第一次启动时间点的update日志里面extra.log（截取最后一段）。
--------------------------------------------------------------

开始更新仓库：/ql/repo/hyzaw_scripts

Fetching origin（到这里就再没有了）
2.下面是第二次启动时间点的update日志里面extra.log（截取最后一段）
开始更新仓库：/ql/repo/ZCY01_daily_scripts

Fetching origin
HEAD is now at faa1ec3 update jd_try.js
Already up to date.
Current branch main is up to date.

更新/ql/repo/ZCY01_daily_scripts成功...


## 执行结束... 2021-07-08 21:14:36  耗时 62 秒

可以看到第二次没有失效库的时候，这里是有执行结束的。第一次有失效的库，到失效库哪里就没有下文了。
并且update任务在定时任务面板里面还设置了禁用。但是每次启动容器都会自动执行update。一旦update里面的extra有失效的仓库链接，那进去容器之后定时任务就不执行。

**Comment by whyour** [comment]
@13810169 那就是你在自定义脚本里加了 ql repo命令？

**Comment by 13810169** [comment]
> @13810169 那就是你在自定义脚本里加了 ql repo命令？

是的。
