### ISSUE TITLE
面板diy命令 

### ISSUE THREAD

**Issue by syfirefox** [whyour/qinglong#45]
diy https://ghproxy.com/https://github.com/whyour/hundun.git "quanx/jx|quanx/jd" tokens  本来是拉取不包含tokens的脚本 但是执行后 好像只拉取到了包含tokens的脚本。

**Comment by whyour** [comment]
@syfirefox git_pull 更新下代码，再执行下

**Comment by syfirefox** [comment]
OK了。。
