### ISSUE TITLE
更新后面板登录显示空白

### ISSUE THREAD

**Issue by duanpingbo** [whyour/qinglong#450]
ql check 显示正常

root@qinglong:/ql $ ql check
=====> 开始检测

=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="https://qinglong.whyour.cn/g5.ico"
    />
    <link rel="stylesheet" href="/umi.c31cc144.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.2
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.27/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/javascript/javascript.js"></script>
    <script src="/umi.476c556e.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   45 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
10728 nginx     0:00 nginx: worker process
10729 nginx     0:00 nginx: worker process
10730 nginx     0:00 nginx: worker process
10731 nginx     0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-07-04T15:28:22:       ################################################
2021-07-04T15:28:22:     
2021-07-04T15:28:28: info:    ✌️ DB loaded and connected!
2021-07-04T15:28:28: info:    ✌️ Dependency Injector loaded
2021-07-04T15:28:28: info:    ✌️ Express loaded
2021-07-04T15:28:28: info:    ✌️ init data loaded
2021-07-04T15:28:28: info:    
2021-07-04T15:28:28:       ################################################
2021-07-04T15:28:28:       🛡️  Server listening on port: 5600 🛡️ 
2021-07-04T15:28:28:       ################################################
2021-07-04T15:28:28:     
2021-07-04T15:28:58: info:    ✌️ DB loaded and connected!
2021-07-04T15:28:58: info:    ✌️ Dependency Injector loaded
2021-07-04T15:28:58: info:    ✌️ Express loaded
2021-07-04T15:28:58: info:    ✌️ init data loaded
2021-07-04T15:28:58: info:    
2021-07-04T15:28:58:       ################################################
2021-07-04T15:28:58:       🛡️  Server listening on port: 5600 🛡️ 
2021-07-04T15:28:58:       ################################################
2021-07-04T15:28:58:     

=====> 检测后台

{"code":200,"data":{"username":"root"}}

=====> 后台服务启动正常

=====> 检测结束

**Comment by whyour** [comment]
容器没问题，你在服务器上执行  curl http://127.0.0.1:5700 看看

**Comment by duanpingbo** [comment]
> 容器没问题，你在服务器上执行 curl http://127.0.0.1:5700 看看

感谢回复。
root@debian:~# curl http://127.0.0.1:5700 
curl: (56) Recv failure: 连接被对方重设

**Comment by whyour** [comment]
> > 容器没问题，你在服务器上执行 curl http://127.0.0.1:5700 看看
> 
> 
> 
> 感谢回复。
> 
> root@debian:~# curl http://127.0.0.1:5700 
> 
> curl: (56) Recv failure: 连接被对方重设
> 
> 

docker ps 青龙的5700端口绑上了吗

**Comment by duanpingbo** [comment]
> > > 容器没问题，你在服务器上执行 curl http://127.0.0.1:5700 看看
> > 
> > 
> > 感谢回复。
> > root@debian:~# curl http://127.0.0.1:5700
> > curl: (56) Recv failure: 连接被对方重设
> 
> docker ps 青龙的5700端口绑上了吗


docker run -dit \
   -v $PWD/ql/config:/ql/config \
   -v $PWD/ql/log:/ql/log \
   -v $PWD/ql/db:/ql/db \
   -p 5700:5700 \
   --name qinglong \
   --hostname qinglong \
   --restart always \
   whyour/qinglong:latest

用的这个启动容器，大概是绑上了？

**Comment by whyour** [comment]
@duanpingbo docker ps 看看 或者看看你有代理啥的关了

**Comment by duanpingbo** [comment]
@whyour 
root@debian:~# docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED       STATUS        PORTS                                       NAMES
7b79d0eb856d   whyour/qinglong:latest   "./docker/docker-ent…"   2 hours ago   Up 2 hours    0.0.0.0:5700->5700/tcp, :::5700->5700/tcp   qinglong

我没有使用代理。。。。
之前更新的，脚本还在运行，就是面板是空白了。
容器删除从新启动过，还是一样的结果。郁闷

**Comment by whyour** [comment]
@duanpingbo 你以前是好的？

**Comment by duanpingbo** [comment]
@whyour 对，前天更新之后不行的

**Comment by whyour** [comment]
@duanpingbo todesk 远程看看

**Comment by duanpingbo** [comment]
@whyour 
ID:               896495212
Password:         498520

**Comment by whyour** [comment]
> 498520

连不上？软件权限给了吗

**Comment by duanpingbo** [comment]
@whyour ToDesk:
代码:201 601 614
033508
