### ISSUE TITLE
更新bug

### ISSUE THREAD

**Issue by YYplus** [whyour/qinglong#453]
老大，更新完无限重启，执行了一下ql updata，每次重启后，它都会执行那个任务，然后无限重启面板，死循环了，有点搞笑，哈哈哈

**Comment by whyour** [comment]
@YYplus 咋会死循环？谁重启会执行update?你是不是有啥没搞清楚

**Comment by YYplus** [comment]
> @YYplus咋会死循环？谁重启会执行更新？你是不是有啥没搞清楚
它刚才更新完就默认执行了，ql updata了，手动暂停了一次好了

**Comment by whyour** [comment]
@YYplus 那是状态显示问题吧，你再执行重启后还是运行中吗？

**Comment by YYplus** [comment]
对，刚才执行完又开始运行（它更新完不是默认要重启吗，重启后它的那个任务又是运行状态，它重启完自动打开，我没干预，反复循环），不是显示问题，面板一直在刷新，手动暂停一次现在好了，我可能是个例

**Comment by whyour** [comment]
@YYplus 那是运行状态，不是真的运行，是状态有问题，重启完谁自动打开了？日志会自动打开？你是什么浏览器

**Comment by YYplus** [comment]
但页面一直在刷新，只是运行状态的话页面应该是不会刷新的吧，浏览器是谷歌稳定最新版

**Comment by whyour** [comment]
@YYplus 这不可能啊，只有打开任务日志，显示完成才会自动刷新

**Comment by YYplus** [comment]
难道是我浏览器的问题吗，可能是啥东西bug了

**Comment by whyour** [comment]
@YYplus todesk 远程看看

**Comment by YYplus** [comment]
我刚才测试了好多次无法复现，不要在意，明天周一，老大早点睡吧，不然明天又要摸鱼，哈哈哈

**Comment by whyour** [comment]
@YYplus 你是咋测试的？面板手动运行 ql update ？

**Comment by YYplus** [comment]
对，
