### ISSUE TITLE
IP:5700登录青龙面板空白

### ISSUE THREAD

**Issue by yyffdsc** [whyour/qinglong#454]
![image](https://user-images.githubusercontent.com/86830072/124395584-80df7500-dd37-11eb-9cef-fb938a7eb17c.png)
青龙2.2，第二天登录空白面板，是什么原因呢大佬，centos7
用过指令docker restart qinglong     docker exec -it qinglong ql update 没有用

**Comment by MangoDong** [comment]
我盲猜 可能是因为自信安装了 cancas等模块

**Comment by yyffdsc** [comment]
不懂？有解决方法吗？

**Comment by henanxiaoli** [comment]
我跟你一样，没有任何奇怪的操作，等大佬回复

**Comment by henanxiaoli** [comment]
我是n1

**Comment by whyour** [comment]
> 我是n1

docker exec -it qinglong curl http://localhost:5700

**Comment by MangoDong** [comment]
服务器也是一样的操作吗？

**Comment by whyour** [comment]
@MangoDong 一样的，就是查看面板状态，2.8可以直接ql check

**Comment by henanxiaoli** [comment]
@whyour 感谢大佬回复，但是我执行完docker exec -it qinglong curl http://localhost:5700也重启了还是白屏，在这之前执行过docker exec -it qinglong nginx -c /etc/nginx/nginx.conf 
![image](https://user-images.githubusercontent.com/84007026/124531653-8c1ec780-de41-11eb-873a-52694f3da97b.png)
![image](https://user-images.githubusercontent.com/84007026/124531677-980a8980-de41-11eb-9b3d-bbea12526b09.png)

**Comment by op523** [comment]
666

**Comment by MangoDong** [comment]
面板空白是指的，网页是没有呈现内容，执行打开，依旧是空白的那种网页，图标啊，均在。

**Comment by ravizhan** [comment]
是因为cdn.jsdelivr.net被墙了
换成cdn.ravi.cool就行了
具体方法百度
