### ISSUE TITLE
从青龙2.8才加入，助力码给我搞晕了

### ISSUE THREAD

**Issue by passionThis** [whyour/qinglong#455]
说之前log路径下code有什么文件，放在before文件后面，2.8就没有啊，before文件是空的，code文件也没有，想了下就放在config.sh里面，多个账号多个助力码。export 助力码名称=”账号1助力码@账号2助力码“，这样写对吗，执行时候没有生效。。

**Comment by whyour** [comment]
> 说之前log路径下code有什么文件，放在before文件后面，2.8就没有啊，before文件是空的，code文件也没有，想了下就放在config.sh里面，多个账号多个助力码。export 助力码名称=”账号1助力码@账号2助力码“，这样写对吗，执行时候没有生效。。

把code.sh弄成定时任务，拷贝频道的before_task文件到你的里面
