### ISSUE TITLE
直接执行没有问题，通过qinglong执行js 会崩溃卡住，但是找不到任何报错信息

### ISSUE THREAD

**Issue by Tsukasa007** [whyour/qinglong#459]
![image](https://user-images.githubusercontent.com/28201662/124596495-ebf28e00-de94-11eb-80ba-63ed6c92090f.png)

日志就是这样卡住，状态还是运行中

![image](https://user-images.githubusercontent.com/28201662/124561831-e97e3d00-de70-11eb-84b5-50eeeab8821f.png)
进程也是正常，找不到原因，请大佬出手！

**Comment by Tsukasa007** [comment]
不知道什么导致卡住，为什么说卡住，因为有次我console.log  日志答应到一半就停了，{"a":123123,"b":123456.   就这样

**Comment by Tsukasa007** [comment]
![image](https://user-images.githubusercontent.com/28201662/124621276-b8bbf900-deac-11eb-8b91-1eeca1a9fafe.png)
node 进程没了

**Comment by Tsukasa007** [comment]
直接 命令行 执行 task xxxx.js 又没问题，没有头绪

**Comment by Tsukasa007** [comment]
![image](https://user-images.githubusercontent.com/28201662/124698237-fbb4b580-df1a-11eb-9d54-442198f3ac25.png)
我把这改成exec 手动执行就没问题了，但是不知道有没有别的影响

**Comment by whyour** [comment]
> ![image](https://user-images.githubusercontent.com/28201662/124698237-fbb4b580-df1a-11eb-9d54-442198f3ac25.png)
> 我把这改成exec 手动执行就没问题了，但是貌似定时执行的onClose 又触发不了

远程看看？ todesk

**Comment by Tsukasa007** [comment]
可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 下午5:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 直接执行没有问题，通过qinglong执行js 会崩溃卡住，但是找不到任何报错信息 (#459)





  

 我把这改成exec 手动执行就没问题了，但是貌似定时执行的onClose 又触发不了
  
远程看看？ todesk

**Comment by Tsukasa007** [comment]
滴滴 819582890  q

**Comment by whyour** [comment]
> 819582890

不在线

**Comment by Tsukasa007** [comment]
我加你

**Comment by whyour** [comment]
@Tsukasa007 你这是啥？

**Comment by Tsukasa007** [comment]
qq

**Comment by whyour** [comment]
@Tsukasa007 qq 远程不了 用 todesk

**Comment by Tsukasa007** [comment]
------------------ToDesk-------------------
请使用ToDesk对我电脑进行远程控制
我的设备代码:350156082

**Comment by whyour** [comment]
@Tsukasa007 密码

**Comment by Tsukasa007** [comment]
------------------ToDesk-------------------
请使用ToDesk对我电脑进行远程控制
我的设备代码:350156082 连接密码:861920
ToDesk下载地址:
https://www.ToDesk.com

**Comment by whyour** [comment]
@Tsukasa007 只能看到壁纸，你这是软件没权限？

**Comment by Tsukasa007** [comment]
我设置一下

**Comment by Tsukasa007** [comment]
ok

**Comment by Tsukasa007** [comment]
大拇指！
