### ISSUE TITLE
diy 参数拉取文件夹问题

### ISSUE THREAD

**Issue by syfirefox** [whyour/qinglong#46]
面板diy拉取github  命令 diy xxxx xxx "AAA" 拉取文件  不仅只拉取AAA路径下文件 还会同时拉取项目下 AAAXXX路径下文件。

**Comment by syfirefox** [comment]
我试过 会的。。如果是AAAXXX 只会拉取AAAXXX 如果是拉取AAA 会拉取2个文件夹的内容。你试试？

**Comment by whyour** [comment]
> 我试过 会的。。如果是AAAXXX 只会拉取AAAXXX 如果是拉取AAA 会拉取2个文件夹的内容。你试试？AAA和AAAXXX是path那个参数·····命令 diy url "AAA"

远程看看，todesk
