### ISSUE TITLE
拉取单个py脚本后会被重命名，导致的导包问题

### ISSUE THREAD

**Issue by xuanxiaomai** [whyour/qinglong#460]
拉取单个py脚本后会被重命名，两个py被拉取下来后，此时文件名已被更改，导包会出现问题，而面板不支持编辑，让这简单的问题变得复杂

**Comment by whyour** [comment]
> 拉取单个py脚本后会被重命名，两个py被拉取下来后，此时文件名已被更改，导包会出现问题，而面板不支持编辑，让这简单的问题变得复杂

这种情况你要用 ql repo命令吧， ql raw 命令适合依赖文件都存在的脚本

**Comment by xuanxiaomai** [comment]
😥好吧，是我没整明白，因为repo整个拉下来太多了，我只需要两个文件

**Comment by whyour** [comment]
@xuanxiaomai 你可以用黑白名单

**Comment by xuanxiaomai** [comment]
好的，谢谢大佬，但是我不是很懂repo后面参数的含义，有说明吗

**Comment by whyour** [comment]
@xuanxiaomai 你直接输入 ql repo 会提示
