### ISSUE TITLE
case屏蔽某个ck不执行某个脚本2.80-065失效

### ISSUE THREAD

**Issue by wssh13** [whyour/qinglong#461]
某个ck不执行某个脚本设置无效
## 如果只是想要屏蔽某个ck不执行某个脚本，可以参考下面 case 这个命令的例子来控制，脚本名称包含后缀
 case $1 in
   panghu999_jd_scripts_jd_beauty.js)
     TempBlockCookie="6 8 10"
     ;;
     cfdtx.js)
     TempBlockCookie="2 3 4 5 6 7 9 10 11 12 13 14"
     ;;
  esac

**Comment by whyour** [comment]
目前没有这个功能
