### ISSUE TITLE
2.8跑一会儿cpu占用率始终居高不下

### ISSUE THREAD

**Issue by donggua1118** [whyour/qinglong#462]
2.2不存在这个问题，请问老大怎么排查这个占用很高的问题
![488C50DB-744A-4270-8650-60CBD5143C2C](https://user-images.githubusercontent.com/79329274/124681611-7d94e680-defb-11eb-9ba1-03e665fc201b.png)
![FA255F9F-DD98-4959-A96D-404F9AD3C463](https://user-images.githubusercontent.com/79329274/124681615-7f5eaa00-defb-11eb-80e5-b56a31550d30.png)

**Comment by ioxuy** [comment]
你好,请问这是什么APP

**Comment by wingswing** [comment]
用gtking跑这个？好浪费呀 n1就行了
