### ISSUE TITLE
自动任务手动暂停 手动任务手动暂停 进程无法正常退出

### ISSUE THREAD

**Issue by Tsukasa007** [whyour/qinglong#463]
这是自动任务手动停止![image](https://user-images.githubusercontent.com/28201662/124845339-1c3b4900-dfc9-11eb-805c-fa92c6158a28.png)

这是手动任务手动停止
![image](https://user-images.githubusercontent.com/28201662/124845656-bf8c5e00-dfc9-11eb-9273-e97e9731a85f.png)

**Comment by Tsukasa007** [comment]
貌似手动是因为spawn改成exec 后才出现的，之前测试的时候貌似spawn手动启动是正常退出进程

**Comment by Tsukasa007** [comment]
貌似 node 崩溃的问题还是存在。。。定时 手动都会有 ，可以留个联系方式吗

**Comment by whyour** [comment]
> 貌似 node 崩溃的问题还是存在。。。定时 手动都会有 ，可以留个联系方式吗

我tg账号就是github的
