### ISSUE TITLE
请教Canvas如何安装到docker里

### ISSUE THREAD

**Issue by a620620** [whyour/qinglong#468]
请教Canvas如何安装到docker里

**Comment by jackberry** [comment]
apk add --no-cache build-base g++ cairo-dev pango-dev giflib-dev && cd scripts && npm install canvas --build-from-source

**Comment by a620620** [comment]
> apk add --no-cache build-base g++ cairo-dev pango-dev giflib-dev && cd scripts && npm install canvas --build-from-source

大佬执行的时候报错啊~
![12](https://user-images.githubusercontent.com/54564580/125228222-03070500-e307-11eb-8c69-5bb85d4bf520.png)

**Comment by whyour** [comment]
自定义脚本 extra.sh 中添加  pnpm install -g canvas  要使用070最新版
