### ISSUE TITLE
068镜像arm机器更新失败

### ISSUE THREAD

**Issue by pool8964** [whyour/qinglong#472]
amd 机器可以用
arm更新镜像后一直重启中
Error response from daemon: Container 53e82c9594e4dc6954638cad23d1fa068b0206581c9e68e65884f75f1cfbf0d3 is restarting, wait until the container is running

**Comment by pool8964** [comment]
仓库下载到本地，然后docker build-t qinglong .
docker run也不行，机器aarch64

**Comment by whyour** [comment]
docker logs -f qinglong 看看
