### ISSUE TITLE
环境变量页面直接拖拽调整顺序问题

### ISSUE THREAD

**Issue by hua12lao** [whyour/qinglong#473]
1、环境变量页面直接拖拽调整顺序时候，会出现跨多行操作失效。
2、同时偶尔出现两次操作页面显示顺序调整成功，但刷新页面后数据顺序并未改变。
猜测可能是UI改变了数据库顺序没变？ PS：不知道是普遍问题还是我机子的原因（2.8版本）

**Comment by ericting** [comment]
我也是和你一样，不是机子问题吧
