### ISSUE TITLE
更新容器以后，cookie管理界面“空白”异常

### ISSUE THREAD

**Issue by Liquid-w** [whyour/qinglong#48]
使用最新镜像，运行环境为群晖里面docker，配置完毕以后，cookie管理界面完全空白，尝试过重新启动容器，git_pull，包括rebuild面板，都无法解决问题。
![image](https://user-images.githubusercontent.com/66705441/115336881-9c27f300-a1d2-11eb-8f90-a14a2046e8ae.png)

**Comment by whyour** [comment]
@Liquid-w 换个浏览器呢

**Comment by Liquid-w** [comment]
用最新版本的Edge，还有Firefox均显示同样内容，尝试过清楚浏览器缓存，包括Ctrl + F5刷新，均无法解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 中午1:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 更新容器以后，cookie管理界面“空白”异常 (#48)





 
@Liquid-w 换个浏览器呢

**Comment by whyour** [comment]
@Liquid-w docker restart qinglong试试

**Comment by Liquid-w** [comment]
还是不行，之前试过了。刚我重装了1.1.0版本的，就有cookie管理界面，但问题是那个版本太低了，git_pull以后也无法升级到1.2.0，无法自动添加cron定时。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 下午2:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 更新容器以后，cookie管理界面“空白”异常 (#48)





 
@Liquid-w docker restart qinglong试试

**Comment by whyour** [comment]
@Liquid-w 有时间远程下

**Comment by whyour** [comment]
@Liquid-w 或者看下浏览器报啥错

**Comment by Liquid-w** [comment]
浏览器倒是没报错，手动把cookie.sh挂载到容器内，任务可以正常运行。
另外就是除了cookie管理的标签不正常以外，其他的都很正常。
查看了下cookie那个标签的响应，{"code":200,"data":[]}，主要就是数据为空，很奇怪。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 下午3:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 更新容器以后，cookie管理界面“空白”异常 (#48)





 
@Liquid-w 或者看下浏览器报啥错

**Comment by whyour** [comment]
@Liquid-w 要新建，不要直接改cookie.sh你这就是数据库没数据，改了重启就没了

**Comment by Liquid-w** [comment]
好，我再新建个容器试试。但是之前我替换cookie.sh的原因是cookie管理界面不可用，只能采取替换方式，倒不是先替换才没cookie管理界面，而是先没界面，不得已才替换。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 下午4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 更新容器以后，cookie管理界面“空白”异常 (#48)





 
@Liquid-w 要新建，不要直接改cookie.sh你这就是数据库没数据，改了重启就没了

**Comment by Liquid-w** [comment]
新建容器还是不行，我实在是不知道怎么着了，我就把config/db/log这三个文件夹映射出来了，但是就算不映射，一样没那个cookie管理界面。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 下午4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 更新容器以后，cookie管理界面“空白”异常 (#48)





 
@Liquid-w 要新建，不要直接改cookie.sh你这就是数据库没数据，改了重启就没了

**Comment by whyour** [comment]
@Liquid-w 远程看看todesk

**Comment by Liquid-w** [comment]
好，我现在下载一个






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 更新容器以后，cookie管理界面“空白”异常 (#48)





 
@Liquid-w 远程看看todesk

**Comment by Liquid-w** [comment]
624 206 689
462 366




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 更新容器以后，cookie管理界面“空白”异常 (#48)





 
@Liquid-w 远程看看todesk

**Comment by Liquid-w** [comment]
> @Liquid-w 远程看看todesk
624 206 689
462 366
我这边准备好了，群晖docker部署的，5700端口

**Comment by travis-joe** [comment]
我也一样的问题

**Comment by Liquid-w** [comment]
最终大佬给我解决了，我出现这个问题的原因是，使用了Adguard过滤广告，其中的一条规则匹配到了“cookie-warpper“这个字段，因此被过滤了，建议你关闭类似软件，或者逐条尝试关闭规则，定位以后，去掉该规则即可。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "travis ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 晚上7:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 更新容器以后，cookie管理界面“空白”异常 (#48)





 
我也一样的问题

**Comment by travis-joe** [comment]
感谢
