### ISSUE TITLE
重装了容器，命令执行错误

### ISSUE THREAD

**Issue by li258w** [whyour/qinglong#482]
openwrt更新版本，重新安装了容器，
![image](https://user-images.githubusercontent.com/64025840/125191225-fd141400-e273-11eb-9e21-bde82e230e42.png)
执行docker exec -it qinglong ql update或者拉取脚本文件的命令均不能正常执行，退回openwrt原始版本也同样问题。执行命令后，刷屏“y”。
请问大佬，是我哪里姿势不对吗？

**Comment by whyour** [comment]
你这截图我不知道你这是干啥了
