### ISSUE TITLE
web无法打开，pm2 logs 显示 More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss

### ISSUE THREAD

**Issue by ID404** [whyour/qinglong#488]
pm2 status 可以看到panel 的statu为errored

pm2 logs 如下 ：
/root/.pm2/pm2.log last 15 lines:
PM2        | 2021-07-13T12:15:48: PM2 log: App [panel:0] online
PM2        | 2021-07-13T12:15:48: PM2 log: App [panel:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-07-13T12:15:48: PM2 log: App [panel:0] starting in -fork mode-
PM2        | 2021-07-13T12:15:48: PM2 log: App [panel:0] online
PM2        | 2021-07-13T12:15:49: PM2 log: App [panel:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-07-13T12:15:49: PM2 log: App [panel:0] starting in -fork mode-
PM2        | 2021-07-13T12:15:49: PM2 log: App [panel:0] online
PM2        | 2021-07-13T12:15:50: PM2 log: App [panel:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-07-13T12:15:50: PM2 log: App [panel:0] starting in -fork mode-
PM2        | 2021-07-13T12:15:50: PM2 log: App [panel:0] online
PM2        | 2021-07-13T12:15:50: PM2 log: App [panel:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-07-13T12:15:50: PM2 log: App [panel:0] starting in -fork mode-
PM2        | 2021-07-13T12:15:50: PM2 log: App [panel:0] online
PM2        | 2021-07-13T12:15:51: PM2 log: App [panel:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-07-13T12:15:51: PM2 log: Script /ql/build/app.js had too many unstable restarts (16). Stopped. "errored"

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
1|schedule | 2021-07-13T12:15:42: info:
1|schedule | 2021-07-13T12:15:42:       ################################################
1|schedule | 2021-07-13T12:15:42:       🛡️  Schedule listening on port: 5500 🛡️
1|schedule | 2021-07-13T12:15:42:       ################################################
1|schedule | 2021-07-13T12:15:42:

/root/.pm2/logs/panel-out.log last 15 lines:
0|panel    | 2021-07-13T12:15:48: info:    ✌️ DB loaded and connected!
0|panel    | 2021-07-13T12:15:48: info:    ✌️ Dependency Injector loaded
0|panel    | 2021-07-13T12:15:48: info:    ✌️ Express loaded
0|panel    | 2021-07-13T12:15:49: info:    ✌️ DB loaded and connected!
0|panel    | 2021-07-13T12:15:49: info:    ✌️ Dependency Injector loaded
0|panel    | 2021-07-13T12:15:49: info:    ✌️ Express loaded
0|panel    | 2021-07-13T12:15:50: info:    ✌️ DB loaded and connected!
0|panel    | 2021-07-13T12:15:50: info:    ✌️ Dependency Injector loaded
0|panel    | 2021-07-13T12:15:50: info:    ✌️ Express loaded
0|panel    | 2021-07-13T12:15:50: info:    ✌️ DB loaded and connected!
0|panel    | 2021-07-13T12:15:50: info:    ✌️ Dependency Injector loaded
0|panel    | 2021-07-13T12:15:50: info:    ✌️ Express loaded
0|panel    | 2021-07-13T12:15:51: info:    ✌️ DB loaded and connected!
0|panel    | 2021-07-13T12:15:51: info:    ✌️ Dependency Injector loaded
0|panel    | 2021-07-13T12:15:51: info:    ✌️ Express loaded

/root/.pm2/logs/panel-error.log last 15 lines:
0|panel    | 2021-07-13T12:15:49:     at Persistence.treatRawData (/ql/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/persistence.js:242:11)
0|panel    | 2021-07-13T12:15:49:     at /ql/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/persistence.js:281:38
0|panel    | 2021-07-13T12:15:49:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
0|panel    | 2021-07-13T12:15:50: Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
0|panel    | 2021-07-13T12:15:50:     at Persistence.treatRawData (/ql/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/persistence.js:242:11)
0|panel    | 2021-07-13T12:15:50:     at /ql/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/persistence.js:281:38
0|panel    | 2021-07-13T12:15:50:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
0|panel    | 2021-07-13T12:15:50: Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
0|panel    | 2021-07-13T12:15:50:     at Persistence.treatRawData (/ql/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/persistence.js:242:11)
0|panel    | 2021-07-13T12:15:50:     at /ql/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/persistence.js:281:38
0|panel    | 2021-07-13T12:15:50:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
0|panel    | 2021-07-13T12:15:51: Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
0|panel    | 2021-07-13T12:15:51:     at Persistence.treatRawData (/ql/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/persistence.js:242:11)
0|panel    | 2021-07-13T12:15:51:     at /ql/node_modules/.pnpm/nedb@1.8.0/node_modules/nedb/lib/persistence.js:281:38
0|panel    | 2021-07-13T12:15:51:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)

**Comment by whyour** [comment]
你db目录下的数据貌似有问题，删了重新加吧
