### ISSUE TITLE
面板失效了

### ISSUE THREAD

**Issue by guakeliao** [whyour/qinglong#49]
面板失效了,显示不出来了。最新的镜像

**Comment by whyour** [comment]
@guakeliao 报什么错

**Comment by guakeliao** [comment]
1.2版本正常。latest不正常，而且看dockerhub上。latest的镜像代码只有90多M

**Comment by whyour** [comment]
> 1.2版本正常。latest不正常，而且看dockerhub上。latest的镜像代码只有90多M

镜像再上传了，30分钟后试试
