### ISSUE TITLE
如何跳过update更新package依赖检测？

### ISSUE THREAD

**Issue by bibubi** [whyour/qinglong#491]
每次ql update以后，就检测package。。搞到我之前配置的依赖都被删除

**Comment by a620620** [comment]
> 每次ql update以后，就检测package。。搞到我之前配置的依赖都被删除

大佬你的依赖项都有哪些怎么装的呀，教教我啦~

**Comment by whyour** [comment]
在 extra.sh 使用 pnpm install -g xxx 安装依赖，不要用 -S
