### ISSUE TITLE
update命令并没有执行run_extra_shell！！

### ISSUE THREAD

**Issue by bibubi** [whyour/qinglong#495]
①update命令并没有执行run_extra_shell！！导致config配置了EnableExtraShell="true"也无法执行extra.sh！！
![image](https://user-images.githubusercontent.com/18078927/125546263-7bc21464-c617-4a1f-9e49-75ebbb20e8d9.png)

②序号错误
![image](https://user-images.githubusercontent.com/18078927/125546404-82ea3ec4-b90a-4645-a2b1-8a740f491e9f.png)

**Comment by whyour** [comment]
使用  ql extra 执行，早都不执行了
