### ISSUE TITLE
面板在运行过程中出现了空白

### ISSUE THREAD

**Issue by MangoDong** [whyour/qinglong#499]
环境：centos7 
面板在运行过程中出现了空白，运行curl 0.0.0.0:5700 发现图标之类正常显示 但是后端的信息好像没有链接上来。
运行ql extra   显示让登录。

**Comment by MangoDong** [comment]
pm2 reload panel？

**Comment by MangoDong** [comment]
bash docker-entrypoint.sh

**Comment by whyour** [comment]
ql check ？

**Comment by MangoDong** [comment]
> ql check ？

2.2。。。 内置账号48.。。

**Comment by whyour** [comment]
> > ql check ？
> 
> 2.2。。。 内置账号48.。。

用2.8吧😄

**Comment by whyour** [comment]
或者你检查下 pm2 里的进程状态
