### ISSUE TITLE
1.2版本的git_pull.log显示删除失效的任务失败

### ISSUE THREAD

**Issue by guakeliao** [whyour/qinglong#50]
检测到有失效的定时任务：

jd_speed

开始尝试自动删除定时任务如下：

jd_speed

curl: (3) URL using bad/illegal format or missing URL
 删除失败
成功删除失效的脚本与定时任务

**Comment by whyour** [comment]
> 检测到有失效的定时任务：
> 
> jd_speed
> 
> 开始尝试自动删除定时任务如下：
> 
> jd_speed
> 
> curl: (3) URL using bad/illegal format or missing URL
> 删除失败
> 成功删除失效的脚本与定时任务

最新版已修复，git_pull两次即可
