### ISSUE TITLE
关于CK问题。

### ISSUE THREAD

**Issue by guilty-love** [whyour/qinglong#507]
大佬们请教一个问题，CK不是保存在evn.sh中么。我把这个文件备份了 。然后重新安装了青龙。
但在是变量中，只能一个CK，里面包括了全部
并不像现在的，一行一个CK。
有什么办法解决这个问题么？
希望能导出导出CK功能，是一行一个

**Comment by kudan520** [comment]
db 里面。

**Comment by whyour** [comment]
> 大佬们请教一个问题，CK不是保存在evn.sh中么。我把这个文件备份了 。然后重新安装了青龙。
> 但在是变量中，只能一个CK，里面包括了全部
> 并不像现在的，一行一个CK。
> 有什么办法解决这个问题么？
> 希望能导出导出CK功能，是一行一个

备份db目录，里面存了定时任务和环境变量数据
