### ISSUE TITLE
重新build失败导致页面打不开了。

### ISSUE THREAD

**Issue by ailongIdo** [whyour/qinglong#51]
![image](https://user-images.githubusercontent.com/44966849/115643617-a91e2100-a34f-11eb-86c7-79e23cb91c87.png)

**Comment by whyour** [comment]
@ailongIdo rebuild 失败了，你直接拉取最新镜像

**Comment by ailongIdo** [comment]
> @ailongIdo rebuild 失败了，你直接拉取最新镜像

我拉取了最新的镜像
![image](https://user-images.githubusercontent.com/44966849/115644539-58a7c300-a351-11eb-9f6e-a6f1497836d2.png)

**Comment by whyour** [comment]
@ailongIdo 那你rebuild干啥

**Comment by whyour** [comment]
@whyour 重新启动容器

**Comment by ailongIdo** [comment]
> @whyour 重新启动容器

![image](https://user-images.githubusercontent.com/44966849/115645129-6578e680-a352-11eb-9fe0-40cfa523a40a.png)
![image](https://user-images.githubusercontent.com/44966849/115645157-6e69b800-a352-11eb-8046-0f2406e64883.png)
重启了。。不行

**Comment by whyour** [comment]
@ailongIdo 重新run

**Comment by ailongIdo** [comment]
> @ailongIdo 重新run

![image](https://user-images.githubusercontent.com/44966849/115646652-2e580480-a355-11eb-8daa-318c4277a85f.png)
![image](https://user-images.githubusercontent.com/44966849/115646672-3748d600-a355-11eb-9aca-4775a827d765.png)
docker不熟，现在变成这样了。。

**Comment by whyour** [comment]
@ailongIdo 看下穷奇频道指南

**Comment by ailongIdo** [comment]
> @ailongIdo 看下穷奇频道指南

那个是什么？？？有电报群吗？

**Comment by ailongIdo** [comment]
> @ailongIdo 看下穷奇频道指南
我把容器删了重新啦了一份！现在好了！有电报群吗，git首页的那个失效了。

**Comment by whyour** [comment]
> > @ailongIdo 看下穷奇频道指南
> > 我把容器删了重新啦了一份！现在好了！有电报群吗，git首页的那个失效了。

目前没有
