### ISSUE TITLE
日志看不到啊 一直都是loading

### ISSUE THREAD

**Issue by shiyanzhizhuo** [whyour/qinglong#512]
日志看不到啊 一直都是loading
2.8  071版本出现的~

**Comment by whyour** [comment]
ql update下试试

**Comment by kudan520** [comment]
看来有同款，，，，。  害得我以为自己哪里出错折腾半天。

**Comment by yiceho** [comment]
同意问题

**Comment by whyour** [comment]
贴下你们的chrome版本号，操作系统。
更新最新的chrome就好了

**Comment by kudan520** [comment]
嗯  更换谷歌浏览器 一切正常了 ，之前是QQ浏览器出现问题。

**Comment by aliyy2021** [comment]
重新拉下镜像正常了

**Comment by yiceho** [comment]
windows正常
手机不行。
![IMG_20210729_152831](https://user-images.githubusercontent.com/61497579/127450223-b7ae8759-5a6d-471a-8e45-f0703f7fc1da.jpg)
![IMG_20210729_152812](https://user-images.githubusercontent.com/61497579/127450240-6614e9fd-3101-4cae-ab7b-2b1cedf9ad30.jpg)
![IMG_20210729_152707](https://user-images.githubusercontent.com/61497579/127450255-7280da59-b106-4e2d-9f23-5c53df269b38.jpg)

**Comment by whyour** [comment]
更新最新版
