### ISSUE TITLE
页面显示bug

### ISSUE THREAD

**Issue by YYplus** [whyour/qinglong#514]
佬，很抱歉大晚上打扰您，但这个BUG看着真是难受，执行了5次更新，换了浏览器，问题还是存在，具体见图
![image](https://user-images.githubusercontent.com/65841378/127021263-ea9e6553-2361-4b35-b1f6-b2ae82ae87d3.png)

**Comment by whyour** [comment]
@YYplus 你这啥情况，啥浏览器，版本号，系统

**Comment by YYplus** [comment]
> @YYplus 你这啥情况，啥浏览器，版本号，系统

版本	Windows 10 家庭中文版
版本号	21H1
安装日期	‎2021/‎5/‎20
操作系统内部版本	19043.1110
体验	Windows Feature Experience Pack 120.2212.3530.0

Google Chrome 已是最新版本
版本 92.0.4515.107（正式版本） （64 位）

Microsoft Edge
版本 92.0.902.55 (官方内部版本) (64 位)

**Comment by YYplus** [comment]
只有定时任务和环境变量两个页面出现了这个问题

**Comment by whyour** [comment]
> > @YYplus 你这啥情况，啥浏览器，版本号，系统
> 
> 版本 Windows 10 家庭中文版
> 版本号 21H1
> 安装日期 ‎2021/‎5/‎20
> 操作系统内部版本 19043.1110
> 体验 Windows Feature Experience Pack 120.2212.3530.0
> 
> Google Chrome 已是最新版本
> 版本 92.0.4515.107（正式版本） （64 位）
> 
> Microsoft Edge
> 版本 92.0.902.55 (官方内部版本) (64 位)

5分钟后更新下，上次改出来的问题

**Comment by YYplus** [comment]
好
