### ISSUE TITLE
用面板修改的配置文件config.sh 后报错

### ISSUE THREAD

**Issue by shenmadouyaowen** [whyour/qinglong#515]
V2.8.0-071在面板修改配置文件后可能提交的的格式有误,导致如下图报错
![image](https://user-images.githubusercontent.com/12426724/127091096-ae6a4477-83ee-42ad-b53d-12fe5730d47a.png)

**Comment by whyour** [comment]
ql update 下

**Comment by shenmadouyaowen** [comment]
可以了,谢谢大佬
