### ISSUE TITLE
昨天突然看不到日志，进入docker看到提示空间不够，所以问一下如果我要3天删除一次日志应该怎么设置命令？

### ISSUE THREAD

**Issue by etotakeo** [whyour/qinglong#516]
我也不晓得是不是日志占用了空间，反正把/ql/log全部删掉就可以正常跑了,清出来差不多600M的空间，能看日志。所以如果我要3天删除一次日志的话，需要怎么设置命令？ql rmlog 3 然后定时30 7 */3 * *是这样么大佬

然后node_modules文件夹占用1019MB 正不正常

**Comment by whyour** [comment]
是这样，你可以手动执行一次删除日志


node_modules大小不正常，你用了他们的安装依赖吧。删除node_module 重新 ql check试试

**Comment by etotakeo** [comment]
好的， 感谢大佬~
