### ISSUE TITLE
面板修改配置文件问题

### ISSUE THREAD

**Issue by acoolbook** [whyour/qinglong#518]
更新最新版后，用面板修改配置文件，鼠标将光标移到修改的地方，只能键入一个字符，之后光标自动跳转到文件的最后一行，重新将光标移到修改的地方，键入一个字符后又自动跳转到最后一行。

**Comment by whyour** [comment]
浏览器版本，系统版本

**Comment by acoolbook** [comment]
> 浏览器版本，系统版本

Google Chrome 已是最新版本版本 92.0.4515.107（正式版本） （64 位）

**Comment by acoolbook** [comment]
> > 浏览器版本，系统版本
> 
> Google Chrome 已是最新版本版本 92.0.4515.107（正式版本） （64 位）
少部分时候进去可以修改，大部分时候进去无法修改

**Comment by gamesang520** [comment]
Google Chrome 已是最新版本
版本 92.0.4515.131（正式版本） （64 位），Windows10 64位专业版。这次更新后确实配置文件里面编辑变得很难用。增删都很麻烦。自动跳光标，快捷键粘贴 都有问题

**Comment by whyour** [comment]
@gamesang520 最新版还跳？你更新下
