### ISSUE TITLE
关于读取配置文件日志文件信息显示loading

### ISSUE THREAD

**Issue by kent9111** [whyour/qinglong#519]
测试 pc端浏览器除qq浏览器，其他都正常，右边多了个预览。

手机浏览器全部阵亡。。

建议 恢复以前的版本预览功能用处不大，手机不适应

**Comment by whyour** [comment]
ql update下试试手机浏览器

**Comment by kent9111** [comment]
反复更新，都不行，手机依然loading

**Comment by whyour** [comment]
系统版本，浏览器版本

**Comment by kent9111** [comment]
m安卓 11  miui12.5 系统自带浏览器

**Comment by whyour** [comment]
下载个chrome试试？miui这个我没有，估计是又可能不兼容，其他浏览器试过吗

**Comment by kent9111** [comment]
手机试过edge 浏览器 也不行

**Comment by kent9111** [comment]
能关那个功能吗，感觉挺鸡肋的，手机也不能用

**Comment by kent9111** [comment]
![Uploading Screenshot_2021-07-28-23-43-02-644_com.android.browser.jpg…]()

**Comment by kent9111** [comment]
![Screenshot_2021-07-28-23-42-55-426_com android browser](https://user-images.githubusercontent.com/29189526/127353572-25f5d139-108a-4c5b-88d5-1d7ade7c699d.jpg)
![Screenshot_2021-07-28-23-42-39-991_com android browser](https://user-images.githubusercontent.com/29189526/127353579-b9bcbe5b-1097-4f52-be29-d0aa896245ff.jpg)

**Comment by whyour** [comment]
有的截图看不到，下一步有个功能要用这个编辑器，所以统一换了。要先看看兼容性

**Comment by kent9111** [comment]
就2张图。

**Comment by kent9111** [comment]
这个需要浏览器开什么功能吗

**Comment by aliyy2021** [comment]
手机miui12.5 自带浏览器，edge，百度，全部loading..... ,电脑都可以

**Comment by biewenwoshishui021** [comment]
请教楼上两位，小米手机怎么安装青龙？能否私聊请教？
