### ISSUE TITLE
作者大佬  困惑我好几天的问题 麻烦帮我解决下

### ISSUE THREAD

**Issue by a2323010404** [whyour/qinglong#52]
本人用的 openwrt下docker  qinglong 
重启docker之后    网页面板 显示502 Bad Gateway  看不见面板   
重新拉取镜像  也还是这个情况    每次都是清空所有  重装docker 才可以  

作者大佬 知道是什么问题么

**Comment by whyour** [comment]
@a2323010404 你是用的host模式？

**Comment by a2323010404** [comment]
对 是的  host模式

**Comment by whyour** [comment]
> 对 是的 host模式

你是说重启的时候会报502, 只有新建的时候正常？

**Comment by a2323010404** [comment]
对 第一次拉镜像的时候  直接就可以用   重启就报错502了

**Comment by whyour** [comment]
@a2323010404 远程看看，todesk ？

**Comment by a2323010404** [comment]
大佬有V 么 加下   我可能需要全部重做虚拟机了    docker被我弄费了。。

**Comment by a2323010404** [comment]
我现在重做 虚拟机

**Comment by a2323010404** [comment]
重做虚拟机之后 挂在上之前用的 docker虚拟盘 又能用了。。   大佬还要帮我看一下么

**Comment by whyour** [comment]
@a2323010404 你重启下看是不是出错，出错的话远程看看

**Comment by a2323010404** [comment]
haode

**Comment by a2323010404** [comment]
刚才重启了   还没有报错   如果再这样的情况 我再联系您吧   大佬   万分感谢
