### ISSUE TITLE
最新版本镜像Nginx启动报错，无法运行

### ISSUE THREAD

**Issue by icandura** [whyour/qinglong#521]
启动容器后报这个故障

> nginx: [emerg] open() "/etc/nginx/conf.d/default.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:90

然后初始化命令里面在复制Nginx配置的时候是说

>检测到有Nginx默认配置

我觉得是不是没有复制Nginx默认配置造成的

**Comment by icandura** [comment]
找到前面的信息部分了

```
 ======================1. 检测配置文件========================

复制一份 /ql/sample/config.sample.sh 为 /ql/config/config.sh，随后请按注释编辑你的配置文件：/ql/config/config.sh

'/ql/sample/config.sample.sh' -> '/ql/config/config.sh'

检测到config配置目录下不存在env.sh，创建一个空文件用于初始化...


复制一份 /ql/sample/task.sample.sh 为 /ql/config/task_before.sh

'/ql/sample/task.sample.sh' -> '/ql/config/task_before.sh'

复制一份 /ql/sample/task.sample.sh 为 /ql/config/task_after.sh

'/ql/sample/task.sample.sh' -> '/ql/config/task_after.sh'

复制一份 /ql/sample/extra.sample.sh 为 /ql/config/extra.sh

'/ql/sample/extra.sample.sh' -> '/ql/config/extra.sh'

复制一份 /ql/sample/auth.sample.json 为 /ql/config/auth.json

'/ql/sample/auth.sample.json' -> '/ql/config/auth.json'

复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'

检测到默认nginx配置文件，删除...


'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

======================2. 安装依赖========================

检测到 /ql/scripts 的依赖包有变化，运行 npm install...

Progress: resolved 1, reused 0, downloaded 0, added 0
?WARN? deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Progress: resolved 5, reused 0, downloaded 0, added 0
Progress: resolved 6, reused 0, downloaded 6, added 0
Progress: resolved 7, reused 0, downloaded 6, added 0
Progress: resolved 17, reused 0, downloaded 8, added 0
Progress: resolved 32, reused 0, downloaded 22, added 0
?WARN? GET https://registry.npmjs.org/extend error (ECONNRESET). Will retry in 10 seconds. 2 retries left.
Progress: resolved 57, reused 0, downloaded 43, added 0
Progress: resolved 82, reused 0, downloaded 69, added 0
Progress: resolved 110, reused 0, downloaded 96, added 0
Progress: resolved 140, reused 0, downloaded 117, added 0
Progress: resolved 157, reused 0, downloaded 138, added 0
Progress: resolved 181, reused 0, downloaded 162, added 0
Progress: resolved 187, reused 0, downloaded 187, added 0
Progress: resolved 188, reused 0, downloaded 187, added 0
Progress: resolved 205, reused 0, downloaded 193, added 0
Packages: +210
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /ql/scripts/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 210, reused 0, downloaded 208, added 85

dependencies:
+ crypto-js 4.1.1
+ download 8.0.0

.8.2
+ http-server 0.12.3
+ qrcode-terminal 0.12.0
+ request 2.88.2 deprecated
+ tough-cookie 4.0.0
+ tunnel 0.0.6
+ ws 7.5.3 (8.0.0 is available)

Progress: resolved 210, reused 0, downloaded 210, added 210, done
Collecting requests
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.2-py3-none-any.whl (59 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2021.5.30 charset-normalizer-2.0.4 idna-3.2 requests-2.26.0 urllib3-1.26.6

======================3. 启动nginx========================
```
最后到了启动nginx那里就报没有默认配置文件，是不是在第一步中
> 检测到默认nginx配置文件，删除...
这个地方被删掉了？

**Comment by whyour** [comment]
是的，这个配置文件没用，我改成清空这个文件吧，因为这个文件监听端口会重复

**Comment by icandura** [comment]
我觉得是不是nginx的版本问题，我后面进入镜像看了一下，nginx.conf 配置文件里面写的是

>  include /etc/nginx/conf.d/*.conf;

/etc/nginx/conf.d/ 这个路径下面明明有了 front.conf 了，但是nginx不认，非要找 default.conf。
我的临时解决方法是直接在 nginx.conf 里面改成

> include /etc/nginx/conf.d/front.conf;

至少先能正常使用了

**Comment by whyour** [comment]
> 我觉得是不是nginx的版本问题，我后面进入镜像看了一下，nginx.conf 配置文件里面写的是
> 
> > include /etc/nginx/conf.d/*.conf;
> 
> /etc/nginx/conf.d/ 这个路径下面明明有了 front.conf 了，但是nginx不认，非要找 default.conf。
> 我的临时解决方法是直接在 nginx.conf 里面改成
> 
> > include /etc/nginx/conf.d/front.conf;
> 
> 至少先能正常使用了

你是什么设备，现在还是每次启动容器都报错？还是ql update也报错？

**Comment by icandura** [comment]
用的Linux服务器，系统版本如下

> Linux U-NAS 4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux

平常主要用 Portainer 来管理Docker，Docker版本如下

> Docker version 17.12.0-ce, build c97c6d6

之前遇到这个故障就是首次创建容器的时候出现，然后一直启动不了。
自从修改过 nginx.conf 内容后还没重启过容器，也没 update 过。

**Comment by shu0802** [comment]
最新的2.8.2也出现不能访问面板
![1fabfdca078cf54cb1586fbc7372310](https://user-images.githubusercontent.com/43750373/129835595-798d60df-3bd2-4b19-8a25-81b3d1a65cf8.png)

**Comment by sstutu** [comment]
配置文件挂载的有，，，，，，root@OpenWrt:~/data/docker_data/qinglong# docker-compose down
[+] Running 1/1
 ⠿ Container qinglong  Removed                                            11.4s
root@OpenWrt:~/data/docker_data/qinglong# docker run -dit \
    -v ./config:/ql/config \
        -v ./log:/ql/log \
        -v ./db:/ql/db \
        --net host \
        --name qinglong \
        --hostname qinglong \
    --restart always \
    whyour/qinglong:latest
docker: invalid reference format.
See 'docker run --help'.
-bash: -v: command not found
-bash: -v: command not found
-bash: --net: command not found
-bash: --name: command not found
-bash: --hostname: command not found
root@OpenWrt:~/data/docker_data/qinglong# docker run -dit \
   -v $PWD/config:/ql/config \
   -v $PWD/log:/ql/log \
   -v $PWD/db:/ql/db \
   --net host \
   --name qinglong \
   --hostname qinglong \
   --restart always \
   whyour/qinglong:latest
dffdcfc525f5af58494cfde23a8cc6ebd87f7c065803ca8a22b0cc9775b44fdd
root@OpenWrt:~/data/docker_data/qinglong# docker -logs -fn 100 qinglong
Unable to parse logging level: ogs
root@OpenWrt:~/data/docker_data/qinglong# docker logs -fn 100 qinglong
复制一份 /ql/sample/config.sample.sh 为 /ql/data/config/config.sh，随后请按注释                                                                         编辑你的配置文件：/ql/data/config/config.sh

'/ql/sample/config.sample.sh' -> '/ql/data/config/config.sh'

检测到config配置目录下不存在env.sh，创建一个空文件用于初始化...


复制一份 /ql/sample/task.sample.sh 为 /ql/data/config/task_before.sh

'/ql/sample/task.sample.sh' -> '/ql/data/config/task_before.sh'

复制一份 /ql/sample/task.sample.sh 为 /ql/data/config/task_after.sh

'/ql/sample/task.sample.sh' -> '/ql/data/config/task_after.sh'

复制一份 /ql/sample/extra.sample.sh 为 /ql/data/config/extra.sh

'/ql/sample/extra.sample.sh' -> '/ql/data/config/extra.sh'

复制一份 /ql/sample/auth.sample.json 为 /ql/data/config/auth.json

'/ql/sample/auth.sample.json' -> '/ql/data/config/auth.json'

复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'

复制一份 /ql/sample/notify.js 为 /ql/data/deps/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/deps/sendNotify.js'

复制一份 /ql/sample/notify.py 为 /ql/data/deps/notify.py

'/ql/sample/notify.py' -> '/ql/data/deps/notify.py'

======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
