### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by gamesang520** [whyour/qinglong#529]
/usr/local/bin/ql: line 460: /ql/log/update/2021-08-01-16-55-58_reset.log: No such file or directory 这个问题怎么处理大佬

**Comment by whyour** [comment]
ql update，你这是执行啥报的错

**Comment by gamesang520** [comment]
什么也没有执行脚本不运行了，然后ql update 以后出现上面的报错。清理日志重启容器后恢复正常
