### ISSUE TITLE
更新 2.8.1 -001后出错，不能运行

### ISSUE THREAD

**Issue by Michaol** [whyour/qinglong#530]
root@qinglong:/ql $ ql update
/ql/shell/share.sh: line 198: syntax error near unexpected token `<<<'
/ql/shell/share.sh: line 198: `<<<<<<< HEAD'
/ql/shell/api.sh: line 173: syntax error near unexpected token `<<<'
/ql/shell/api.sh: line 173: `<<<<<<< HEAD'
/usr/local/bin/ql: line 241: reset_romote_url: command not found
/usr/local/bin/ql: line 242: git_pull_scripts: command not found

**Comment by whyour** [comment]
再执行一次呢，你这拉代码冲突了

或者执行 docker exec -it qinglong git reset --hard origin/master

然后 ql update

**Comment by Michaol** [comment]
> 再执行一次呢，你这拉代码冲突了
> 
> 或者执行 docker exec -it qinglong git reset --hard origin/master
> 
> 然后 ql update

正常了，谢谢大佬！
