### ISSUE TITLE
请问提示“HEAD is now at 9219cbe 测试kill任务进程”是什么意思？面板进不去白屏了，脚本也不运行

### ISSUE THREAD

**Issue by ufxymsn** [whyour/qinglong#533]
开始更新仓库：/ql

Fetching origin
HEAD is now at 9219cbe 测试kill任务进程
Already up to date.

更新/ql成功...

开始更新仓库：/ql/repo/static

Fetching origin
HEAD is now at 9a78be3 copy static at 2021-08-03 04:08:57
Already up to date.

更新/ql/repo/static成功...

当前版本 v2.8.1-002...

重启面板中...

**Comment by whyour** [comment]
ql check
