### ISSUE TITLE
大佬看看报错Couldn't find .env file

### ISSUE THREAD

**Issue by slain01** [whyour/qinglong#535]
没有设置更新面板的定时任务，但是每天凌晨左右面板服务都会停止并且无法开启，只能重启容器
这是pm2的日志
/root/.pm2/logs/schedule-error.log last 15 lines:
1|schedule |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
1|schedule |     at require (internal/modules/cjs/helpers.js:92:18)
1|schedule |     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
1|schedule |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
1|schedule | Error: ⚠️  Couldn't find .env file  ⚠️ 
1|schedule |     at Object.<anonymous> (/ql/back/config/index.ts:29:9)
1|schedule |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
1|schedule |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
1|schedule |     at Module.load (internal/modules/cjs/loader.js:950:32)
1|schedule |     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
1|schedule |     at Module.require (internal/modules/cjs/loader.js:974:19)
1|schedule |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
1|schedule |     at require (internal/modules/cjs/helpers.js:92:18)
1|schedule |     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
1|schedule |     at Module._compile (internal/modules/cjs/loader.js:1085:14)

**Comment by whyour** [comment]
你这不是最新的吧，最新的日志最前面应该有时间 ql update下

**Comment by slain01** [comment]
> 你这不是最新的吧，最新的日志最前面应该有时间 ql update下

刚刚更新了下自动重启后过几秒还是会报错，.env文件也存在，只能重启容器才能正常
![image](https://user-images.githubusercontent.com/43878954/128286513-d0cce6b6-1318-42f7-b631-ec496213b705.png)
![image](https://user-images.githubusercontent.com/43878954/128286675-ee1d5da6-1f21-4a2e-99e0-1558d5c19693.png)

**Comment by slain01** [comment]
![image](https://user-images.githubusercontent.com/43878954/128286844-8010b5b9-d6bd-43e3-b9e3-b23104988f1d.png)

**Comment by whyour** [comment]
远程看看吧

**Comment by slain01** [comment]
> 远程看看吧

好的.怎么联系呢

**Comment by whyour** [comment]
todesk

**Comment by slain01** [comment]
> todesk

ToDesk:
设备代码:868 022 193
临时密码:671423

**Comment by slain01** [comment]
> todesk

大佬是我网络掉了吗，刚才我看到点了下就没动了

**Comment by whyour** [comment]
@slain01 不好意思，刚开会，你这样再跑跑吧，看今晚有没有问题

**Comment by slain01** [comment]
> @slain01 不好意思，刚开会，你这样再跑跑吧，看今晚有没有问题

好，谢谢啦
