### ISSUE TITLE
青龙面板支持ipv6吗？

### ISSUE THREAD

**Issue by forgiveme0** [whyour/qinglong#537]
我的纯ipv6服务器搭好之后进不去面板

**Comment by whyour** [comment]
arm架构的nginx好像加上ipv6会报错，你手动给nginx配置里加上试试

**Comment by secondpaul** [comment]
作者大大你好，请问给nginx加上ipv6是指重新编译nginx加上ipv6编译选项吗？还有我想问下你的nginx是如何编译的，因为我`nginx -V`看到了一些动态编译选项有buildozer目录的，不是很明白是怎么回事。

**Comment by whyour** [comment]
> 作者大大你好，请问给nginx加上ipv6是指重新编译nginx加上ipv6编译选项吗？还有我想问下你的nginx是如何编译的，因为我`nginx -V`看到了一些动态编译选项有buildozer目录的，不是很明白是怎么回事。

监听端口的时候加上 listen [::]:5700; 配置就行了
