### ISSUE TITLE
ql update这个提示该怎么解决？

### ISSUE THREAD

**Issue by Spheniscidaer** [whyour/qinglong#539]
开始更新仓库：/ql

Fetching origin
HEAD is now at 60e42f0 更新版本号

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@626051c02bc0.(none)')

更新/ql成功...

Fetching origin
HEAD is now at 775fafb copy static at 2021-08-06 11:12:09

更新/ql/repo/static成功...

当前版本 v2.8.1...

重启面板中...

**Comment by Spheniscidaer** [comment]
开始更新仓库：/ql

Fetching origin
HEAD is now at 60e42f0 更新版本号

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@626051c02bc0.(none)')

更新/ql成功...

Fetching origin
HEAD is now at 775fafb copy static at 2021-08-06 11:12:09

更新/ql/repo/static成功...


当前版本 v2.8.1...

重启面板中...

**Comment by whyour** [comment]
ql check
