### ISSUE TITLE
作者大佬  502问题又出现了   

### ISSUE THREAD

**Issue by a2323010404** [whyour/qinglong#54]
![image](https://user-images.githubusercontent.com/80669127/115941617-a69b0300-a4d8-11eb-8045-b2bb3374679b.png)
我正常用 今天一早打开   就出现502了 

您 有时间远程么

**Comment by whyour** [comment]
> ![image](https://user-images.githubusercontent.com/80669127/115941617-a69b0300-a4d8-11eb-8045-b2bb3374679b.png)
> 
> 我正常用 今天一早打开   就出现502了 
> 
> 
> 
> 您 有时间远程么

可以，todesk

**Comment by a2323010404** [comment]
好的  535 730 928       
       168 350

**Comment by whyour** [comment]
@a2323010404 现在可以吗，刚才有事

**Comment by a2323010404** [comment]
可以的  可以的大佬  我时刻等着呢

**Comment by a2323010404** [comment]
大佬 您直接链接就可以了

**Comment by a2323010404** [comment]
我换了一个  OPENWRT  再试试 可能是之前的版本太老     再用两天看看 。。

**Comment by a2323010404** [comment]
4.25  今天又502了，，，

**Comment by whyour** [comment]
> 4.25 今天又502了，，，

502问题我也遇到了，貌似是网络问题，你使用2.0试试，看还有没有这个问题

**Comment by whyour** [comment]
执行 ql update 刷新页面
