### ISSUE TITLE
关于go-cqhttp推送

### ISSUE THREAD

**Issue by mandxy** [whyour/qinglong#544]
这个推送是不是根本用不了，我本地测试了没问题，远程也测试了没问题，就青龙里面用不了。
![image](https://user-images.githubusercontent.com/43473135/128672491-1e941e20-db1e-47c8-a0ad-665ea2bc5abd.png)

**Comment by WildSaCk** [comment]
go-cqhttp 的问题，URL 没有转码，看我最新的 merge，手动拉一下

**Comment by mandxy** [comment]
@WildSaCk  merge是啥 我现在要怎么弄

**Comment by whyour** [comment]
scripts 目录下的 sendNotify.js 文件删掉，ql update, ql check

**Comment by mandxy** [comment]
@whyour @WildSaCk  一样的 还是如上图一样的错误，青龙2.2可以推送，只是太长的文字推送不了

**Comment by WildSaCk** [comment]
> @whyour @WildSaCk 一样的 还是如上图一样的错误，青龙2.2可以推送，只是太长的文字推送不了

看错了看错了，405 是接口的问题，脚本用的是 POST，你那个接口应该是 GET ，你的 go-cqhttp 版本或者配置有问题

**Comment by mandxy** [comment]
> > @whyour @WildSaCk 一样的 还是如上图一样的错误，青龙2.2可以推送，只是太长的文字推送不了
> 
> 看错了看错了，405 是接口的问题，脚本用的是 POST，你那个接口应该是 GET ，你的 go-cqhttp 版本或者配置有问题

不是的呀，我用发包工具测试没问题呀，我这个接口就是post的

**Comment by WildSaCk** [comment]
> > > @whyour @WildSaCk 一样的 还是如上图一样的错误，青龙2.2可以推送，只是太长的文字推送不了
> > 
> > 
> > 看错了看错了，405 是接口的问题，脚本用的是 POST，你那个接口应该是 GET ，你的 go-cqhttp 版本或者配置有问题
> 
> 不是的呀，我用发包工具测试没问题呀，我这个接口就是post的

这我就真不知道了，我这边是没问题的，不知道你那边的环境还有版本是啥样的

**Comment by tengfeiy-19** [comment]
我的一直报 [ERROR]: 错误: 请先添加 (0) 为好友

**Comment by mandxy** [comment]
已经设置好了

**Comment by tengfeiy-19** [comment]
我的好了，自己的错。
