### ISSUE TITLE
使用ql update 面板打不开

### ISSUE THREAD

**Issue by BCYDTZ** [whyour/qinglong#545]
![image](https://user-images.githubusercontent.com/72110372/128848017-073ee54f-472c-4eec-b936-2f559a121125.png)

**Comment by shu0802** [comment]
什么设备上搭建的，我在群晖docker上搭建的也是这样

**Comment by BCYDTZ** [comment]
> 什么设备上搭建的，我在群晖docker上搭建的也是这样

群晖docker

**Comment by bonnyandsky** [comment]
同样群晖ｄｏｃｋｅｒ　也是这样。
