### ISSUE TITLE
重新拉取面板以后页面打不开了。user接口报502错误

### ISSUE THREAD

**Issue by 15991491954** [whyour/qinglong#550]
user接口控制台报错Failed to load resource: the server responded with a status of 502 (Bad Gateway)
![(FH2AS4X7(LS(5BJ23Y 4O5](https://user-images.githubusercontent.com/56535457/129202915-3c8d72ed-c0e0-4f29-84a5-c922e34f75e1.png)

**Comment by 15991491954** [comment]
新建容器拉取也一样，怎么拉都不行   更新代码以后也是这样

**Comment by coolguy001tv** [comment]
@15991491954  一样的情况，看已经关闭了，怎么解决的？
