### ISSUE TITLE
ARM装好青龙后发现容器一直在自动重启

### ISSUE THREAD

**Issue by Checkra2n** [whyour/qinglong#551]
用docker logs qinglong 查看日志发现
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

======================2. 安装依赖========================

======================3. 启动nginx========================

nginx: [emerg] host not found in upstream "localhost:5600" in /etc/nginx/conf.d/front.conf:2

大佬怎么解决

**Comment by Checkra2n** [comment]
解决了 ，host模式下一直重启，换了指定IP端口映射就好了

**Comment by beenewtree** [comment]
> 解决了 ，host模式下一直重启，换了指定IP端口映射就好了

你好，请问如何换端口映射？

**Comment by sorrymyself** [comment]
rm: cannot remove '/ql/log/task_error.log': No such file or directory

今天自动更新后，无限重启的日志

**Comment by whyour** [comment]
> rm: cannot remove '/ql/log/task_error.log': No such file or directory
> 
> 
> 
> 今天自动更新后，无限重启的日志

更新镜像

**Comment by Defeatable1** [comment]
/ql/shell/share.sh: line 311: /ql/log/task_error.log: No such file or directory
更新了最新镜像后一直在报错。。。
