### ISSUE TITLE
环境变量中禁用所有cookie后，等于没有禁用

### ISSUE THREAD

**Issue by wdy3334** [whyour/qinglong#553]
版本：2.8.1
因为自己的原因没有更新最新版，不知道最新版有没有这个问题，环境变量中禁用所有cookie后，脚本运行时，就和没有禁用是一样的，单独禁用某个cookie没有问题

**Comment by whyour** [comment]
修复好久了
https://github.com/whyour/qinglong/commit/d8587b64a5ce070a82f3b872ee4a3c7669f470dd#diff-be4b7aefa3a41346a81a81e7fc7277fc75d5065a49c983b4e62bd405b12ddc39
