### ISSUE TITLE
最新的镜像无法运行

### ISSUE THREAD

**Issue by datout** [whyour/qinglong#555]
OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown

面板起不来，看到人家说改源，也不行
docker exec -it qinglong npm config set registry
Error response from daemon: Container 2a3a2d1741ca554097b94fc26f10f27c72f7846d751f718c0c63273494fbca4d is restarting, wait until the container is running
一直是restarting状态

**Comment by whyour** [comment]
等10分钟重新拉取镜像
