### ISSUE TITLE
代码调试浏览器多窗口问题

### ISSUE THREAD

**Issue by shenmadouyaowen** [whyour/qinglong#558]
大佬,使用代码调试,然后在打开另外一个窗口就卡了,无法展示任何信息(例如:任务列表,日志列表)等

**Comment by whyour** [comment]
> 大佬,使用代码调试,然后在打开另外一个窗口就卡了,无法展示任何信息(例如:任务列表,日志列表)等

调试功能还没实现完，截下图

**Comment by shenmadouyaowen** [comment]
> > 大佬,使用代码调试,然后在打开另外一个窗口就卡了,无法展示任何信息(例如:任务列表,日志列表)等
> 
> 调试功能还没实现完，截下图

又没有问题了,可能是早上运行太多程序,然后导致卡慢了
