### ISSUE TITLE
是否支持不同账号消息推送到不同地址？

### ISSUE THREAD

**Issue by aidevjoe** [whyour/qinglong#56]
例如登录了两个账号；

例如：
账号1推送到 Token1
账号2推送到 Token2

**Comment by ck1397** [comment]
这样更适合咸鱼卖家是吧

**Comment by aidevjoe** [comment]
@ck1397 

抱歉，没有考虑到这点。

因为有给几个朋友挂脚步，知识单纯希望对方收到自己账号的通知。

没有考虑到这个功能会方便售卖脚本的。

**Comment by ck1397** [comment]
你可以用push+ 可以对多

**Comment by aidevjoe** [comment]
> 你可以用push+ 可以对多

感谢，我研究下
