### ISSUE TITLE
大佬，能不能账号同时在线

### ISSUE THREAD

**Issue by simaxuan** [whyour/qinglong#563]
青龙大佬，最近出了个xdd的扫码，但是每当一扫码，青龙就被强制退出了，管理青龙很不方便，能不能让账号共存同时在线，不会因为账号在别的地方登录而强制退出？

**Comment by whyour** [comment]
> 青龙大佬，最近出了个xdd的扫码，但是每当一扫码，青龙就被强制退出了，管理青龙很不方便，能不能让账号共存同时在线，不会因为账号在别的地方登录而强制退出？

那让账号在多少地方同时在线合适呢，一般系统都是只支持多端在线吧

**Comment by MoonBegonia** [comment]
> > 青龙大佬，最近出了个xdd的扫码，但是每当一扫码，青龙就被强制退出了，管理青龙很不方便，能不能让账号共存同时在线，不会因为账号在别的地方登录而强制退出？
> 
> 那让账号在多少地方同时在线合适呢，一般系统都是只支持多端在线吧

其实最简单的解决方案是 jwt token 不存到文件里，将 jwt 的密钥存到文件里，用文件里的密钥去判断 jwt token 的有效性，这样就支持多端登录了。没必要保存 token 和限制在线数量。
