### ISSUE TITLE
青龙好像不支持Server酱Turbo？

### ISSUE THREAD

**Issue by backdreamliu** [whyour/qinglong#565]
我把push_key设置为SCT开头的值，收不到任何消息反馈。

**Comment by whyour** [comment]
> 我把push_key设置为SCT开头的值，收不到任何消息反馈。

需要怎么支持下，大佬可以提pr

**Comment by Andrew201801** [comment]
> 我把push_key设置为SCT开头的值，收不到任何消息反馈。

你填错地方了，有专门填server酱SCT的地方
