### ISSUE TITLE
请问：TG_PROXY_AUTH=“”这个怎么填？

### ISSUE THREAD

**Issue by shenzt68** [whyour/qinglong#570]
## 如需使用，请自行解除下一行的注释
export TG_PROXY_HOST=""
## 如需使用，请自行解除下一行的注释
export TG_PROXY_PORT=""
## Telegram 代理的认证参数（选填）
export TG_PROXY_AUTH=""

自己建的HTTP，有用户名与密码。这里怎么填帐号和密码呢？

**Comment by shenzt68** [comment]
自顶一下

**Comment by whyour** [comment]
你如果没有就不填，直接上面host和port填了就行了

具体说明就是 https://github.com/koichik/node-tunnel  里的  TG_PROXY_AUTH

**Comment by shenzt68** [comment]
谢了，已经解决
