### ISSUE TITLE
点击 脚本管理 -> .env 文件 出现 403 错误

### ISSUE THREAD

**Issue by ueiu** [whyour/qinglong#573]
我做了 nginx 反代，但是点击其他文件不会出现错误，只有 .env 文件才会，会是我反代问题吗？作者大佬有遇到过这个问题不？

青龙版本：2.8.3-001

![WX20210822-031803](https://user-images.githubusercontent.com/39592269/130332736-0d946853-548e-4f85-a56d-d36eda621264.png)

**Comment by whyour** [comment]
我测试了下，没问题。应该是你反代有点问题吧

**Comment by ueiu** [comment]
> 我测试了下，没问题。应该是你反代有点问题吧

今天重新看了下 是我之前配置的一个 security.conf 禁用了 <.> 开头的文件，谢谢大佬
