### ISSUE TITLE
2.8.4重启容器后nginx会清空导致访问不了

### ISSUE THREAD

**Issue by yanyuwangluo** [whyour/qinglong#575]
2.8.4重启容器后检测到默认的nginx会清空清空后就访问不了
![image](https://user-images.githubusercontent.com/70591645/130344581-88803946-2b32-4f5f-8370-bb018d0f06d5.png)

**Comment by CHNTDCS** [comment]
我是群晖，停止容器，重置一下。
然后就可以启动了。然后在docker exec -it qinglong ql update
问题解决。

**Comment by zhang-001** [comment]
> 我是群晖，停止容器，重置一下。
> 特克特 · 特执行官 - 它青龙 ql 更新

服务器的怎么重置呢 用命令
