### ISSUE TITLE
青龙面板什么内容都没显示，打开F12发现user?t=xxx资源502了

### ISSUE THREAD

**Issue by libre1222** [whyour/qinglong#577]
![image](https://user-images.githubusercontent.com/61275597/130354382-1391169b-74d7-49fa-a371-6915600d4e56.png)

**Comment by libre1222** [comment]
重启服务器都不行，更新了ql update也不行

**Comment by cfaka** [comment]
同样的问题

**Comment by sekaiacg** [comment]
我用ql check解决了

**Comment by libre1222** [comment]
两条命令先后执行了 也不行...

**Comment by 124754649** [comment]
ql repo https://github.com/passerby-b/JDDJ.git "jddj_fruit.js|jddj_fruit_collectWater.js|jddj_bean.js|jddj_plantBeans.js|jddj_getPoints.js" 直接结束

/usr/local/bin/ql: line 470: jddj_bean.js: command not found
/usr/local/bin/ql: line 470: jddj_plantBeans.js: command not found
/usr/local/bin/ql: line 470: jddj_getPoints.js: command not found
/usr/local/bin/ql: line 470: jddj_fruit_collectWater.js: command not found
fatal: ambiguous argument '>>': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
## 开始执行... 2021-08-22 22:28:12

**Comment by stoneliulei** [comment]
![image](https://user-images.githubusercontent.com/9544719/130377047-3d4118df-02ed-4f10-ae47-010237e6844b.png)
 一样

**Comment by stoneliulei** [comment]
docker exec -it qinglong ql check

执行了没用

**Comment by stoneliulei** [comment]
docker exec -it qinglong ql check
docker exec -it qinglong ql update

分别执行 解决

**Comment by libre1222** [comment]
可以容器 git log 一下，可能看看本地最新更新日志，结果发现是我的7月1号就停止了...... 得手动更新

**Comment by linyongfu2013** [comment]
update 成功
check 成功
无法打开面板

再执行一次update，失败
重启容器，依旧无法打开面板

**Comment by whyour** [comment]
> update 成功
> check 成功
> 无法打开面板
> 
> 再执行一次update，失败
> 重启容器，依旧无法打开面板

你这几句话能会知道个啥，你执行的日志呢

**Comment by linyongfu2013** [comment]
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.15
fatal: unable to access 'https://github.com/whyour/qinglong.git/': Failed to connect to github.com port 443: Network unreachable
error: Could not fetch origin
fatal: unable to access 'https://github.com/whyour/qinglong.git/': Failed to connect to github.com port 443: Network unreachable
fatal: unable to access 'https://github.com/whyour/qinglong-static.git/': Failed to connect to github.com port 443: Network unreachable
error: Could not fetch origin
fatal: unable to access 'https://github.com/whyour/qinglong-static.git/': Failed to connect to github.com port 443: Network unreachable
## 开始执行... 2021-08-24 14:21:14

开始更新仓库：/ql

Fetching origin
HEAD is now at a5ff8dd 更新readme图片

更新/ql失败，请检查原因...

开始更新仓库：/ql/repo/static

Fetching origin
HEAD is now at a841503 copy static at 2021-08-23 07:33:53

更新/ql失败，请检查原因...


@whyour

**Comment by linyongfu2013** [comment]
![image](https://user-images.githubusercontent.com/4011963/130570848-3b666d5b-3571-4cb6-9b10-7383a6fdc58e.png)

浏览器访问面板，docker logs 没有日志，浏览器F12 的network 里也没有请求，直接就返回502

**Comment by whyour** [comment]
> ![image](https://user-images.githubusercontent.com/4011963/130570848-3b666d5b-3571-4cb6-9b10-7383a6fdc58e.png)
> 
> 浏览器访问面板，docker logs 没有日志，返回502
> 
> `GET http://192.168.2.19:5700/api/user?t=1629788210648 502 (Bad Gateway)`

pm2 logs panel  看看

fatal: unable to access 'https://github.com/whyour/qinglong.git/': Failed to connect to github.com port 443: Network unreachable
你这访问不了 github.com

**Comment by linyongfu2013** [comment]
偶尔访问不了，前面已经更新成功过一次的

删掉容器后重建可以了，谢谢。
