### ISSUE TITLE
更新2.84-002后，不能拉库脚本更新

### ISSUE THREAD

**Issue by Sunshineno11** [whyour/qinglong#580]
更新2.84-002后，不能拉库脚本更新

**Comment by SNAKEXGC** [comment]
不能识别以前拉取命令后面的限制词，删除限制词的拉取链接可以拉取，希望whyour大佬修复一下！辛苦了哈！

**Comment by SNAKEXGC** [comment]
root@qinglong:/ql $ ql repo https://ghproxy.com/https://github.com/shufflewzc/faker2.git "jd_|jx_|gua_|jddj_|getJDCookie" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace.js|JDJRValidator_Pure|sign_graphics_validate"
cat: '>>': No such file or directory
## 开始执行... 2021-08-23 09:39:23

/usr/local/bin/ql: line 470: /usr/local/bin/ql: line 470: /usr/local/bin/ql: line 470: /usr/local/bin/ql: line 470: /usr/local/bin/ql: line 470: ZooFaker_Necklace.js: command not found
JDJRValidator_Pure: command not foundutils: command not foundsign_graphics_validate: command not found/usr/local/bin/ql: line 470: 

USER: command not found

/usr/local/bin/ql: line 470: backUp: command not found
getJDCookie: command not found
/usr/local/bin/ql: line 470: jddj_: command not found
/usr/local/bin/ql: line 470: gua_: command not found
/usr/local/bin/ql: line 470: jx_: command not found
fatal: ambiguous argument '>>': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
## 开始执行... 2021-08-23 09:39:23


## 执行结束... 2021-08-23 09:39:23 耗时 0 秒
root@qinglong:/ql $

**Comment by zq1121734772** [comment]
看来不止我一个人遇到了问题

**Comment by 21ki** [comment]
大早上都是这个错

**Comment by bluewatercg** [comment]
看来不止我一个人遇到了问题

**Comment by anyung533** [comment]
我也是，什么时候解决

**Comment by anyung533** [comment]
我也是，什么时候解决

**Comment by 21ki** [comment]
我看已经解决了.版本回退了,可以再取试试
