### ISSUE TITLE
禁用任务bug，日志bug

### ISSUE THREAD

**Issue by SNAKEXGC** [whyour/qinglong#585]
禁用任务的时候会多出来一个新的任务显示已禁用，刷新一下就恢复正常了，比较随机，有时出现，有时候又不会出现，但是大部分时间会出现这个bug
![image](https://user-images.githubusercontent.com/78722169/130384516-690a291f-e2f1-4bde-a84c-efc749d8f62d.png)
拉取脚本的时候，看不到日志，但是我能收到拉取成功的通知，面板里面也能出现任务
![image](https://user-images.githubusercontent.com/78722169/130384579-5c1fb0ba-6f3c-470f-b921-88c0686cb795.png)

版本是最新版2.8.4-003

**Comment by SNAKEXGC** [comment]
辛苦whyour大佬了！

**Comment by SNAKEXGC** [comment]
同时希望新增一个地方用来查看登录的ip等信息

**Comment by whyour** [comment]
> 同时希望新增一个地方用来查看登录的ip等信息

需求bug分开写😀

**Comment by whyour** [comment]
更新最新版
