### ISSUE TITLE
2.8.4版本后api出现401错误

### ISSUE THREAD

**Issue by ChokiJ** [whyour/qinglong#588]
更新到2.8.4版本后xdd扫码就不能用了，提示
`[container.go:254]  {"code":401,"message":"Format is Authorization: Bearer [token]"}`

**Comment by mhb518340** [comment]
一样

**Comment by mhb518340** [comment]
xd，你解决了吗？

**Comment by zhouguangyou1994** [comment]
ninja扫码登陆{"data":{"errcode":264},"message":"出错了，请退出重试"}
