### ISSUE TITLE
任务定时 schedule 的日期之间不小心多了加空格，就会导致任务失效（被注释# ）

### ISSUE THREAD

**Issue by rubnet** [whyour/qinglong#590]
任务定时的`split(' ')` 过于[严格](https://github.com/whyour/qinglong/blob/master/back/services/cron.ts#L34) ，建议 [split(' ')](https://github.com/whyour/qinglong/blob/master/back/services/cron.ts#L348)  改成 `split(/ +/)`
例如: 1&nbsp;&nbsp; * * *  * 可以保存，但是却不会执行任务=

**Comment by whyour** [comment]
注释了，但是是执行的，这个被pm2 服务运行了

**Comment by rubnet** [comment]
> 注释了，但是是执行的，这个被pm2 服务运行了

你可以试试 `crontab -l ` 看看,
任务前面被注释#

**Comment by whyour** [comment]
@rubnet pm2 l 看看 schedule里面跑的啥

**Comment by rubnet** [comment]
更新到最新版后没问题了，抱歉

**Comment by whyour** [comment]
@rubnet split是有问题的，但是任务应该是运行的。感谢你的split

**Comment by whyour** [comment]
@rubnet 我才知道split还能用正则🤣

**Comment by rubnet** [comment]
> @rubnet 我才知道split还能用正则🤣
如果用正则，这行最好也统一改一下
https://github.com/whyour/qinglong/blob/master/back/services/cron.ts#L348

**Comment by whyour** [comment]
@rubnet

**Comment by whyour** [comment]
@rubnet 👍🏻

**Comment by rubnet** [comment]
> @rubnet 👍🏻

等等还有[这个地方](https://github.com/whyour/qinglong/blob/63149c03f5d5d62c87c4cb1645496f60f721b9e8/back/schedule.ts#L28)，然后就应该全部一致了
