### ISSUE TITLE
jwt令牌问题

### ISSUE THREAD

**Issue by lonelyman0108** [whyour/qinglong#591]
ninja页面打开时会请求青龙的api，例如`api/envs`，每一此调用都需要jwt令牌

https://github.com/MoonBegonia/ninja/blob/52ee4774de6233df97ecdd92ee76c3133ebe7947/backend/ql.js#L31

这个令牌是从青龙的auth.json里面读取的，这一步都没啥问题
但是如果管理员退出登录了青龙，就会直接清空jwt令牌

https://github.com/whyour/qinglong/blob/be4e1001684ebec049cb9495f367abf5a5ae2502/back/api/auth.ts#L47

再让ninja去调用api的时候就会失败
解决方法就是管理员登录青龙后不能logout，直接关闭窗口才行
而且因为jwt令牌的有效期是三天
https://github.com/whyour/qinglong/blob/82880c3f06ba9e3532e265adea927a5c55d2ddca/back/services/auth.ts#L56
还需要每隔三天就重新登陆一次

这应该算是一个bug吧，希望能修复下

**Comment by lonelyman0108** [comment]
直接把jwt有效时间改成30天完事，反正ninja端获取令牌是在服务器内获取的

**Comment by whyour** [comment]
3天怎么算是bug呢？token没有了，为什么不跳转登录页面去登陆？

**Comment by lonelyman0108** [comment]
> 3天怎么算是bug呢？token没有了，为什么不跳转登录页面去登陆？

也是，隔两天登陆一次就完事了
