### ISSUE TITLE
能否设置同时执行的最大任务数量

### ISSUE THREAD

**Issue by siyue666** [whyour/qinglong#592]
一到半夜任务多，服务器就炸了

**Comment by Huiaei** [comment]
配置文件的那个不清楚是不是
` ## 设置批量执行任务时的并发数，默认同时执行5个任务`
`MaxConcurrentNum="5"`

**Comment by siyue666** [comment]
> 配置文件的那个不清楚是不是
> ` ## 设置批量执行任务时的并发数，默认同时执行5个任务`
> `MaxConcurrentNum="5"`

这个我改了完全没效果

**Comment by whyour** [comment]
> > 配置文件的那个不清楚是不是
> > ` ## 设置批量执行任务时的并发数，默认同时执行5个任务`
> > `MaxConcurrentNum="5"`
> 
> 这个我改了完全没效果

现在的定时任务时用 crond跑的，没有并发限制
