### ISSUE TITLE
执行ql update会移除掉pnpm install got@11安装的模块

### ISSUE THREAD

**Issue by Spheniscidaer** [whyour/qinglong#593]
然后执行tsc就会报错，只能再重新执行pnpm install got@11

<img width="851" alt="image" src="https://user-images.githubusercontent.com/18514810/130540047-7d0da031-9d5a-49fd-b732-bdd47021ce0c.png">
<img width="951" alt="image" src="https://user-images.githubusercontent.com/18514810/130540089-f9828efd-19a3-4d2a-bbc5-c4b86cbdb72c.png">
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/18514810/130540129-f73bb5ad-2ac9-4d73-9dd3-d6b473b3d0aa.png">

**Comment by whyour** [comment]
got本来ql update就会自动装了，不需要单独安装，只不过部分人没装上，才手动装。tsc的错误跟got没有关系，那是提示你没有node的类型声明文件，要装 @types/node，你直接 pnpm install -g @types/node 就行了。got不是给tsc服务的
