### ISSUE TITLE
疑难杂症_不完整运行所有的ck.

### ISSUE THREAD

**Issue by ZeroMah** [whyour/qinglong#594]
一共5个ck

1. 在面板中,手动运行脚本的话,只会跑第2.3.4.5个ck的任务
2. 但是如果是脚本根据cron自动触发,或者我用bot后台运行脚本的话就会正常跑完1.2.3.4.5

请问大佬这两个触发的逻辑有什么不同吗,还是我的设置没有设置好?

**Comment by whyour** [comment]
没有区别，把你的task_before里面的代码注释试试
