### ISSUE TITLE
群晖docker安装的面板，用更新面板的任务更新后就网页打不开了

### ISSUE THREAD

**Issue by bonnyandsky** [whyour/qinglong#595]
每次用更新面板的任务更新后。网页打开都会出错。上次更新到2.8.3的时候是403的错。今天从2.8.3更新到2.8.4就是500的错误了。删掉容器和镜像，重新拉镜像安装就没问题

**Comment by whyour** [comment]
我没有群晖，下次遇到问题远程看看吧，如果 update 服务进不去，主要看容器是否正常，另外就是 容器里执行 pm2 logs panel 看日志是否正常

**Comment by bonnyandsky** [comment]
> 我没有群晖，下次遇到问题远程看看吧，如果 update 服务进不去，主要看容器是否正常，另外就是 容器里执行 pm2 logs panel 看日志是否正常

执行面板升级任务后只是打不开面板网页前端，日志和后端一切正常。包括脚本都能在后台正常运行，机器人命令和推送也能正常运行。
打不开网页会提示403或者500错误，底下还有一个ngiex的单词（不知道有没有拼错）个人怀疑是升级面板后老的面板进程没杀掉，还是占用着端口，新的就打不开了。重启容器也没用。删除重新拉镜像安装就没事。

**Comment by whyour** [comment]
那就是nginx启动有问题，下次有问题远程看下

**Comment by bonnyandsky** [comment]
> 那就是nginx启动有问题，下次有问题远程看下

怎么联系你？qq还是什么？下次出现同样问题，我好让你远程看看

**Comment by whyour** [comment]
https://t.me/jiaolongwang

**Comment by bonnyandsky** [comment]
> https://t.me/jiaolongwang

我关注平台了。但是没找到联系方式。我看到现在可以升级2.8。5了 打算升级下。如果有问题 刚好你可以远程看下

**Comment by whyour** [comment]
@bonnyandsky @whyour
