### ISSUE TITLE
打开不了登陆页面

### ISSUE THREAD

**Issue by shyg866** [whyour/qinglong#597]
?
umi.b042ca56.js:1 GET http://192.168.1.119:5665/api/user?t=1629785597238 502 (Bad Gateway)
umi.b042ca56.js:1 
Response {useCache: false, type: "basic", url: "http://192.168.1.119:5665/api/user?t=1629785597238", redirected: false, status: 502, …}
body: (...)
bodyUsed: false
headers: Headers {}
ok: false
redirected: false
status: 502
statusText: "Bad Gateway"
type: "basic"
url: "http://192.168.1.119:5665/api/user?t=1629785597238"
useCache: false

**Comment by whyour** [comment]
https://t.me/jiaolongwang/163

好好看通知
