### ISSUE TITLE
传递task执行参数给task_before和task_after 这是什么意思？是task code.sh 不用在复制互助码到task_before了？

### ISSUE THREAD

**Issue by dreamfrog7** [whyour/qinglong#600]
我目前是在容器中 执行  task code.sh 以后复制代码到 task_before 中，这次2.8.5升级中提到的“传递task执行参数给task_before和task_after 这是什么意思？” 还需要我之前的那种操作吗？

**Comment by whyour** [comment]
早都不需要复制了吧，这个更新跟那个没关系，只不过before、after能拿到任务执行时的参数了

https://t.me/jiaolongwang/120

**Comment by dreamfrog7** [comment]
那我需要把before文件中复制过来的代码删除了吗？能否提供一个最新的before文件？

**Comment by dreamfrog7** [comment]
3. 互助功能可实现方法很多
   其中一种就是把以前log目录下，子目录code里的最新的文件内容拷贝到task_before.sh中，最下面添加部分代码，具体参考附件

我之前看的是这个 6月21日青龙v2.8.0更新的说明

**Comment by whyour** [comment]
往下看，用频道最新的那两个文件，然后改自己的脚本前缀就行
