### ISSUE TITLE
账号过多，任务超时导致后面账号执行不到

### ISSUE THREAD

**Issue by Mr-Coffee666** [whyour/qinglong#603]
任务超时时间支持白名单吗，或者说分帐号单独跑

**Comment by whyour** [comment]
在 config.sh 里 case 可以根据脚本名设置你需要的参数

**Comment by Mr-Coffee666** [comment]
请问有使用案例吗？比如说我有6个账户执行jd_try.js脚本，每个脚本执行时间大概是50分钟。设置的任务超时时间为1h
