### ISSUE TITLE
【任务列表排序】

### ISSUE THREAD

**Issue by sanmulaila** [whyour/qinglong#604]
现在任务列表排序是按照状态排的，希望可以加一个按照名称排序
以下是排序方法(未测试)
逻辑: 当状态相同时，按照名称排序，按照汉字的拼音排序

src/pages/crontab/index.tsx
line :230
....
data.data.sort((a: any, b: any) => {
            const sortA = a.isDisabled ? 4 : a.status;
            const sortB = b.isDisabled ? 4 : b.status;
            if (sortA !== sortB) {
              return CrontabSort[sortA] - CrontabSort[sortB];
            } else {
              // 按照名称排序
              return a.name.localeCompare(b.name);
            }
          }),
....

**Comment by whyour** [comment]
![image](https://user-images.githubusercontent.com/22700758/130725785-d61ded16-0000-4bbd-9a47-52d7163a2d9e.png)
点一下呢？

**Comment by sanmulaila** [comment]
新版已经可以了，感谢大佬，我原来用的是2.8.2
