### ISSUE TITLE
希望新增账号备注的功能

### ISSUE THREAD

**Issue by guakeliao** [whyour/qinglong#61]
希望新增账号备注的功能。cookie列表增加一个账号备注的功能

**Comment by yang7758258** [comment]
大佬，你能找到scripts这个文件夹吗，里面没有，自己新建的又没用

**Comment by Acr05s** [comment]
> 大佬，你能找到scripts这个文件夹吗，里面没有，自己新建的又没用

映射对了么？

**Comment by guakeliao** [comment]
你应该是没有影射对哦。
-v $PWD/ql/scripts:/ql/scripts \

**Comment by yang7758258** [comment]
已经解决了，哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月6日(星期四) 上午9:35
收件人: ***@***.***&gt;; 
抄送: "3：00 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 希望新增账号备注的功能 (#61)





 
你应该是没有影射对哦。
 -v $PWD/ql/scripts:/ql/scripts \
