### ISSUE TITLE
登录失败次数过多

### ISSUE THREAD

**Issue by guoxiang1216** [whyour/qinglong#621]
请10000秒后重试，在哪重置，现在登不上啦

**Comment by fckcg** [comment]
我的是直接需要5天才能登陆，是用上面的命令来解决吗？

**Comment by whyour** [comment]
@fckcg 是的， ql resetlet

**Comment by FairyWorld** [comment]
> [root@VM-8-13-centos ~]# docker exec -it qinglong1 bash //qinglong1 容器名
> root@qinglong:/ql $ ql
> 命令输入错误...
> 
> 本脚本用法：
> 
> 1. update                                                                                        # 更新并重启青龙
> 2. extra                                                                                           # 运行自定义脚本
> 3. raw                                                                                # 更新单个脚本文件
> 4. repo         # 更新单个仓库的脚本
> 5. rmlog                                                                              # 删除旧日志
> 6. bot                                                                                             # 启动tg-bot
> 7. check                                                                                         # 检测青龙环境并修复
> 8. resetlet                                                                                      # 重置登录错误次数
> 
> **看懂了没有！**

重置后可以了

**Comment by NewLife996** [comment]
怎么知道是哪个IP在尝试登陆面板@whyour

**Comment by mamamii** [comment]
重置后再登录，依然给出长时间的提示怎么办？？？
