### ISSUE TITLE
镜像启动失败

### ISSUE THREAD

**Issue by xiaoming3039** [whyour/qinglong#626]
新拉取的青龙镜像 在arm和x86设备上都无法启动

**Comment by whyour** [comment]
@xiaoming3039 你看你备份的db目录下的crontan.db文件是不是很大，确认后

**Comment by xiaoming3039** [comment]
> @xiaoming3039你看你备份的先db目录下的crontan.db文件是不是很大，确认后别有成就

软路由和docker都是全新安装的
