### ISSUE TITLE
青龙2.9.0，经常性服务器状态良好，访问面板白屏。必须重启服务器才能恢复

### ISSUE THREAD

**Issue by X156** [whyour/qinglong#630]

**Comment by zanjie1999** [comment]
/api/user 直接502，docker log没有任何报错

**Comment by whyour** [comment]
@zanjie1999 进容器看  pm2 logs panel ，或者贴 ql check日志

**Comment by zanjie1999** [comment]
> pm2 logs panel

```
1|panel  | 2021-08-31T14:19:23: Error: ⚠️  Couldn't find .env file  ⚠️
1|panel  | 2021-08-31T14:19:23:     at Object.<anonymous> (/ql/back/config/index.ts:31:9)
1|panel  | 2021-08-31T14:19:23:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
1|panel  | 2021-08-31T14:19:23:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
1|panel  | 2021-08-31T14:19:23:     at Module.load (internal/modules/cjs/loader.js:937:32)
1|panel  | 2021-08-31T14:19:23:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
1|panel  | 2021-08-31T14:19:23:     at Module.require (internal/modules/cjs/loader.js:961:19)
1|panel  | 2021-08-31T14:19:23:     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
1|panel  | 2021-08-31T14:19:23:     at require (internal/modules/cjs/helpers.js:92:18)
1|panel  | 2021-08-31T14:19:23:     at Object.<anonymous> (/ql/back/app.ts:3:1)
1|panel  | 2021-08-31T14:19:23:     at Module._compile (internal/modules/cjs/loader.js:1072:14)

```

**Comment by whyour** [comment]
@zanjie1999 你这 .env 文件怎么被删了？  cp .env.example .env

**Comment by zanjie1999** [comment]
> @zanjie1999 你这 .env 文件怎么被删了？ cp .env.example .env

 
@whyour 不清楚，之前是更新报其他的错（具体不记得了）然后check和update操作了一波就报没有.env的错了

```
root@qinglong:/ql $ cat /ql/.env
MONGODB_URI='mongodb://'
YIYAN_MONGODB_URI=''

CRON_PORT=5500
PORT=5600

LOG_LEVEL='debug'

SECRET='whyour'

```
是在/ql下面的.env吗？这个文件是有的喔

**Comment by whyour** [comment]
> > @zanjie1999 你这 .env 文件怎么被删了？ cp .env.example .env
> 
> @whyour 不清楚，之前是更新报其他的错（具体不记得了）然后check和update操作了一波就报没有.env的错了
> 
> ```
> root@qinglong:/ql $ cat /ql/.env
> MONGODB_URI='mongodb://'
> YIYAN_MONGODB_URI=''
> 
> CRON_PORT=5500
> PORT=5600
> 
> LOG_LEVEL='debug'
> 
> SECRET='whyour'
> ```
> 
> 是在/ql下面的.env吗？这个文件是有的喔

pm2 delete panel 
ql update

**Comment by zanjie1999** [comment]
> > > @zanjie1999 你这 .env 文件怎么被删了？ cp .env.example .env
> > 
> > 
> > @whyour 不清楚，之前是更新报其他的错（具体不记得了）然后check和update操作了一波就报没有.env的错了
> > ```
> > root@qinglong:/ql $ cat /ql/.env
> > MONGODB_URI='mongodb://'
> > YIYAN_MONGODB_URI=''
> > 
> > CRON_PORT=5500
> > PORT=5600
> > 
> > LOG_LEVEL='debug'
> > 
> > SECRET='whyour'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 是在/ql下面的.env吗？这个文件是有的喔
> 
> pm2 delete panel
> ql update

然后再
pnpm i
ql check
一顿操作后nginx报502的问题解决了

**Comment by whyour** [comment]
> > > > @zanjie1999 你这 .env 文件怎么被删了？ cp .env.example .env
> > > 
> > > 
> > > @whyour 不清楚，之前是更新报其他的错（具体不记得了）然后check和update操作了一波就报没有.env的错了
> > > ```
> > > root@qinglong:/ql $ cat /ql/.env
> > > MONGODB_URI='mongodb://'
> > > YIYAN_MONGODB_URI=''
> > > 
> > > CRON_PORT=5500
> > > PORT=5600
> > > 
> > > LOG_LEVEL='debug'
> > > 
> > > SECRET='whyour'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 是在/ql下面的.env吗？这个文件是有的喔
> > 
> > 
> > pm2 delete panel
> > ql update
> 
> 然后再
> pnpm i
> ql check
> 一顿操作后nginx报502的问题解决了
> （顺带给后面来的人提一下，最近淘宝镜像源爆炸，可以 npm config set registry https://registry.npmjs.org/ 换回官方npm源）

主要是淘宝源的问题吗，不行把切换源的就删了😀
