### ISSUE TITLE
青龙不能登录，显示要过200000多秒后才能再试！

### ISSUE THREAD

**Issue by kaisyaliu** [whyour/qinglong#633]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/21167524/131284288-3a42fc7a-aca8-4096-ac91-b1f125e0c428.png">
请问怎么解决？

**Comment by Gaoswatou** [comment]
docker exec -it qinglong bash  # 青龙为容器名称
进入之后执行下方命令：
ql resetlet

**Comment by kaisyaliu** [comment]
> docker exec -it qinglong bash # 青龙为容器名称
> 进入之后执行下方命令：
> ql resetlet

感谢！已经解决！
