### ISSUE TITLE
导入配置 环境变量异常问题

### ISSUE THREAD

**Issue by a327777892** [whyour/qinglong#639]
备份的整个青龙映射目录 直接覆盖恢复,面板 环境变量里面的内容不显示，但是实际变量环境又存在 可以执行,不知道是不是bug…

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by LongxianShi** [comment]
备份太多了，重装只需要备份config文件夹和db文件夹，config文件夹下的auth.json记录的是青龙账号密码tokern, config.sh是你的环境变量配置，db文件夹中的dnv是你的CK！覆盖时config文件夹中的auto.json最好不要覆盖让青龙自己生成！

**Comment by whyour** [comment]
> 备份的整个青龙映射目录 直接覆盖恢复,面板 环境变量里面的内容不显示，但是实际变量环境又存在 可以执行,不知道是不是bug…
> 
> <sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

覆盖之后执行一次ql update
