### ISSUE TITLE
不知道为啥 一直登录不了

### ISSUE THREAD

**Issue by pythonxue** [whyour/qinglong#640]
不知道 为啥 突然登陆不了.检测 修复都做了 升级到2.9.1了  怎么解决呀

**Comment by zwb0619** [comment]
pnpm add -g pnpm

ql update

然后就可以登陆了。之前也是登陆不了，这么操作下可以了

**Comment by pythonxue** [comment]
还是登陆不了 悲伤了 操作好几次了 重启了好几次

**Comment by zwb0619** [comment]
晚上8点左右？怎么远程？

whyour ***@***.***> 于 2021年9月1日周三 15:25写道：

**Comment by whyour** [comment]
@zwb0619 todesk 向日葵，8点不行太晚了

**Comment by zwb0619** [comment]
现在不行，在上班干活。

whyour ***@***.***> 于 2021年9月1日周三 15:28写道：

**Comment by jichun29** [comment]
一样一样   更新到2.9.1就登录不了了

**Comment by jichun29** [comment]
pnpm add -g pnpm

ql update

我也试了不行  重启什么的都不行
