### ISSUE TITLE
ql repo拉已经404的库，就会产生stoped进程，如果长时间不禁用或者删除就会堆积很多这样的进程。

### ISSUE THREAD

**Issue by Spheniscidaer** [whyour/qinglong#653]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/18514810/131886950-3fa62dab-6c43-47bc-8bc5-9ff4871750e2.png">
<img width="950" alt="image" src="https://user-images.githubusercontent.com/18514810/131887010-251e0628-b5a9-4b5d-8e4d-a2eb413f3155.png">

**Comment by whyour** [comment]
你这是什么机器，我这容器内看不到 stopped 的进程
