### ISSUE TITLE
更新后，无法登录，错误401,需要怎么破

### ISSUE THREAD

**Issue by damondengxin** [whyour/qinglong#656]
![image](https://user-images.githubusercontent.com/19447869/131946135-bf06fcc3-0951-44b9-854a-d58d7c4bfc36.png)
![image](https://user-images.githubusercontent.com/19447869/131946234-931d6bf5-a7d6-4264-b8c4-179e9026698c.png)

**Comment by happyzjhao** [comment]
重新创建？

**Comment by damondengxin** [comment]
没重新创建，我手动把服务拉起来的，因为更新了容器，出现容器中api接口502
