### ISSUE TITLE
2.9.1今天突然出现密码尝试次数过多，后面回家发现后台直接无法访问，附上check

### ISSUE THREAD

**Issue by NewLife996** [whyour/qinglong#666]
## 开始执行... 2021-09-05 22:48:29

=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.8b3a2272.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.17
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.34/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/javascript/javascript.js"></script>
    <script src="/umi.9374af57.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   78 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
27181 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-09-05T18:01:10: info:    task jd_validate_Worker.js pid: 24550 closed 0
2021-09-05T18:53:09: info:    task jd_joy_new.js pid: 24512 closed 0
2021-09-05T22:23:55: info:    ✌️ DB loaded and connected!
2021-09-05T22:23:55: info:    ✌️ Dependency Injector loaded
2021-09-05T22:23:55: info:    ✌️ Express loaded
2021-09-05T22:23:55: info:    ✌️ init data loaded
2021-09-05T22:23:55: info:    
2021-09-05T22:23:55:       ################################################
2021-09-05T22:23:55:       🛡️  Server listening on port: 5600 🛡️
2021-09-05T22:23:55:       ################################################
2021-09-05T22:23:55:     
2021-09-05T22:43:43: info:    ✌️ DB loaded and connected!
2021-09-05T22:43:43: info:    ✌️ Dependency Injector loaded
2021-09-05T22:43:43: info:    ✌️ Express loaded
2021-09-05T22:43:43: info:    ✌️ init data loaded
2021-09-05T22:43:43: info:    
2021-09-05T22:43:43:       ################################################
2021-09-05T22:43:43:       🛡️  Server listening on port: 5600 🛡️
2021-09-05T22:43:43:       ################################################
2021-09-05T22:43:43:     

=====> 检测后台

{"code":401,"message":"jwt expired"}

=====> 后台服务启动正常

=====> 检测结束

## 执行结束... 2021-09-05 22:48:32  耗时 3 秒

**Comment by LongxianShi** [comment]
进入容器，
![image](https://user-images.githubusercontent.com/26238082/132131677-37b28d1a-7331-49a4-8203-2683f38ee324.png)

**Comment by NewLife996** [comment]
> 进入容器，
> ![image](https://user-images.githubusercontent.com/26238082/132131677-37b28d1a-7331-49a4-8203-2683f38ee324.png)
> 

我可以进去，界面和你一样

**Comment by NewLife996** [comment]
> 进入容器，
> ![image](https://user-images.githubusercontent.com/26238082/132131677-37b28d1a-7331-49a4-8203-2683f38ee324.png)

![image](https://user-images.githubusercontent.com/81276828/132131803-d8d39173-acd7-4b3a-8412-b5c977b65b7b.png)

**Comment by NewLife996** [comment]
![image](https://user-images.githubusercontent.com/81276828/132131863-35ea0325-4d28-4ce6-8ae2-4e4995415ef6.png)

**Comment by idragonet** [comment]
我的也是登录不了，提示失败次数过多。

**Comment by NewLife996** [comment]
> 我的也是登录不了，提示失败次数过多。

登陆不了可以重置次数，我是直接打不开后台了

**Comment by msn1983aa** [comment]
> 我的也是登录不了，提示失败次数过多。

解决了么？

**Comment by msn1983aa** [comment]
这个问题感觉是被人扫到了在试密码

**Comment by rootphantomer** [comment]
我的好像也被扫了，咋重置？？？

**Comment by rootphantomer** [comment]
ql resetlet  找到了。

**Comment by Chenmr1008** [comment]
哪位大佬解答一下怎么重置
@NewLife996
