### ISSUE TITLE
打不开！！

### ISSUE THREAD

**Issue by otherbanana** [whyour/qinglong#68]
大佬好，日志出现
检测到默认nginx配置文件，删除...

======================2. 启动nginx========================
nginx: [emerg] host not found in upstream "localhost:5600" in /etc/nginx/conf.d/front.conf:2

这样的问题如何解决呀？我手动添加一个front.conf文件依旧无效

**Comment by otherbanana** [comment]
解决了

**Comment by xiongerdong** [comment]
您好，请问这个怎么解决，我现在也有这个问题。
