### ISSUE TITLE
open/envs添加环境变量接口貌似POST不通

### ISSUE THREAD

**Issue by huiyi9420** [whyour/qinglong#681]
<img width="1120" alt="iShot2021-09-08 17 11 27" src="https://user-images.githubusercontent.com/36962444/132481837-4d1f9a4a-5d83-4392-b9dc-b923407c32cd.png">

青龙版本2.9.1最新版本
ql check运行过
ql update也运行过问题依旧
请大佬指教

**Comment by huiyi9420** [comment]
已解决，原来是body需要提交数组结构的数据才行

**Comment by horryruo** [comment]
兄弟怎么解决的？我post过去是200返回，而且返回的是我目前存在的cookies，但是新cookies没有成功添加
我的代码是这样的`s = requests.session()
    tss = str(int(time.time() * 1000))
    url = 'http://host/open/envs?t=%s'%tss
    data = []
    data_json = {
        "value": "111",
        "name": "111"
    }
    data.append(data_json)
    res = s.post(url,data= json.dumps(data),headers=headers)
    res.encoding = 'utf-8'
    print(res.json())`

headers是这样的`headers = {
    'Authorization': 'Bearer %s'%token,
    'Content-Type': 'application/json;charset=UTF-8',
    }`
