### ISSUE TITLE
/open/auth/token    获取不到token，返回的html网页

### ISSUE THREAD

**Issue by jiujiu-666** [whyour/qinglong#683]

**Comment by hpkaiq** [comment]
> _No description provided._

大佬怎么解决的，我也是这样

**Comment by jiujiu-666** [comment]
nginx问题，看docker文件夹里front文件

**Comment by hpkaiq** [comment]
> nginx问题，看docker文件夹里front文件

感谢大佬，搞定了

**Comment by bymao** [comment]
?怎么解决的？求解答

**Comment by whyour** [comment]
@bymao ql check  https://t.me/jiaolongwang/166

**Comment by bymao** [comment]
> @bymao ql check https://t.me/jiaolongwang/166

谢谢大佬。搞定了
