### ISSUE TITLE
配置文件下没有env.sh文件选项，怎么解决

### ISSUE THREAD

**Issue by 1312007470** [whyour/qinglong#684]
![image](https://user-images.githubusercontent.com/35362226/132499217-ca4e834d-2668-4658-b4a9-dec8cedf94f4.png)

**Comment by 1312007470** [comment]
然后手动添加变量必须SFP到目录，到找到文件后手动修改才行，太麻烦了这种

**Comment by whyour** [comment]
不允许改那个，去环境变量添加

**Comment by 1312007470** [comment]
好的，感谢大佬抽空回复
