### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by mingxiaoyu** [whyour/qinglong#69]
应该有内存泄露问题。内存每小时都在涨。几天 下来内存就不见1.5G。重启docker内存才能释放

**Comment by ilaotan** [comment]
这个问题以前e大的脚本也有. 我现在都是定时任务凌晨重启docker

**Comment by whyour** [comment]
最新版2.0已使用了一些方法，具体表现需要再观察
主要可能是执行的脚本未退出，我猜测

**Comment by Acr05s** [comment]
感觉 node进程挂起没有释放资源 我的运行一个月下来，内存占用８Ｇ

**Comment by qiangxinglin** [comment]
建议reopen, 问题仍未解决, 粗略观察 `ps -aux`, 里面剩余了大量的 `git fetch` 等拉取命令, `ql task`的内存目前应该是没问题, 问题应该出在 `ql repo` 上
