### ISSUE TITLE
建议对比工具可以自由选择对比文件

### ISSUE THREAD

**Issue by huiyi9420** [whyour/qinglong#697]
qinglong如今用处也越来越多了，各路神仙各显神通已经玩出了各种花样，配置文件也越来越多，各种配置文件如果直接覆盖还需要重新配置，希望可以开放自由选择对比文件，方便扩展的配置文件对比差异使用

**Comment by whyour** [comment]
那去哪选择你需要的文件，你意思是选择config下的文件和一个远程文件，还是本地文件

**Comment by huiyi9420** [comment]
都是config目录下我觉得就行了，就像现在config.sample.sh和config.sh对比一样，
用户自由选择那两个文件对比就行了，默认还是原来的配置文件对比，你觉得如何，只是可选左右框的其他文件对比；
如果能直接和远程文件对比也可以但是这不得增加书签功能么，感觉可能会比直接从config目录下选择两个文件对比更麻烦点吧

**Comment by huiyi9420** [comment]
> 那去哪选择你需要的文件，你意思是选择config下的文件和一个远程文件，还是本地文件

都是config目录下我觉得就行了，就像现在config.sample.sh和config.sh对比一样，
用户自由选择那两个文件对比就行了，默认还是原来的配置文件对比，你觉得如何，只是可选左右框的其他文件对比；
如果能直接和远程文件对比也可以但是这不得增加书签功能么，感觉可能会比直接从config目录下选择两个文件对比更麻烦点吧

**Comment by whyour** [comment]
已支持

**Comment by huiyi9420** [comment]
已更新，辛苦啦

whyour ***@***.***>于2021年9月29日 周三23:40写道：

**Comment by yushizui** [comment]
> 已支持
2.17.0好像又不支持这个功能了希望恢复

**Comment by whyour** [comment]
@yushizui 你要对比什么呢

**Comment by yushizui** [comment]
> @yushizui 你要对比什么呢

有些签到脚本更新后,类似这种config.yml.sample文件会更新和已经配置好的config.yml对比修改配置比较方便
