### ISSUE TITLE
配置文件和环境变量具体区别是什么 ，我把助力码放进环境变量和配置文件都能用 ，但是ck放进配置文件就不能用

### ISSUE THREAD

**Issue by 717009629** [whyour/qinglong#701]
配置文件和环境变量具体区别是什么 ，我把助力码放进环境变量和配置文件都能用 ，但是ck放进配置文件就不能用

**Comment by Biercenter** [comment]
> 配置文件和环境变量具体区别是什么 ，我把助力码放进环境变量和配置文件都能用 ，但是ck放进配置文件就不能用

请问助力码如何写在配置文件？名称写什么？谢谢

**Comment by 717009629** [comment]
> > 配置文件和环境变量具体区别是什么 ，我把助力码放进环境变量和配置文件都能用 ，但是ck放进配置文件就不能用
> 
> 请问助力码如何写在配置文件？名称写什么？谢谢

export key=value

**Comment by whyour** [comment]
区别就是环境变量的会合并导出，配置文件你写啥就是啥。ck放到配置文件肯定也可以，export key=value

**Comment by Biercenter** [comment]
> > > 配置文件和环境变量具体区别是什么 ，我把助力码放进环境变量和配置文件都能用 ，但是ck放进配置文件就不能用
> > 
> > 
> > 请问助力码如何写在配置文件？名称写什么？谢谢
> 
> export key=value

OK，了解了，正在看，谢谢解答
