### ISSUE TITLE
环境变量注释掉后，会恢复成重启前的缺省值

### ISSUE THREAD

**Issue by mjyhj** [whyour/qinglong#704]
例如我当前已经设置了
PUSHPLUS1：AAA
PUSHPLUS2：BBB
然后重启docker，再把PUSHPLUS2：设置成空白，就生效
这时候如果把PUSHPLUS2注释掉
会恢复成重启前的缺省值PUSHPLUS2：BBB

https://raw.githubusercontent.com/JDHelloWorld/jd_scripts/main/jd_env_copy.js
用这个可以导出来看发现的

**Comment by whyour** [comment]
大佬知道这是为什么吗，你去容器内执行应该没有这个缓存吧

**Comment by huiyi9420** [comment]
我也发现，环境变量注释掉后无法清除
