### ISSUE TITLE
能否支持数据库，用数据库好方便对数据库进行操作。修改对接其他程序也更便利。

### ISSUE THREAD

**Issue by atyvcn** [whyour/qinglong#708]
能否支持数据库，最先看见db文件还以为是以为是数据库。用数据库好方便对数据库进行操作。修改对接其他程序也更便利。虽然纯文本形式的读取效率比用数据库高。但是这样操作感觉很麻烦。觉得还是数据库比较方便。后期是否考虑添加这种方式尼？安装青龙时可以选择数据库方式或者本地文件读取

**Comment by whyour** [comment]
现在也是一种数据库，如果要更换的话，得做一次数据迁移。有bug就很麻烦。随意得等下个大版本了，或者大佬可以提PR

**Comment by atyvcn** [comment]
这种一行一个json方式存储方式，不如数据库操作方便。虽然可使用接口查询但是不够精确。如果使用其他程序来进行更改又涉及到权限问题。所以说如果采用改为mysql的方法或者安装时二选一这样就有了更多的扩展性。开放接口也可以使用sql命令来进行操作。希望3.0版本能给我带来全新的体验。
