### ISSUE TITLE
卡在检测配置文件

### ISSUE THREAD

**Issue by PP88PP** [whyour/qinglong#711]
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    15 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    15 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    14 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    14 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    14 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    14 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    14 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    14 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    14 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    15 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    14 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    15 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

检测到默认nginx配置文件，清空...

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 10:    14 Illegal instruction     (core dumped) pm2 l > /dev/null 2>&1

**Comment by PP88PP** [comment]
本来想尝试解决，系统英勇就义不认盘了，售后见

**Comment by whyour** [comment]
这貌似是系统有问题，建议检查服务器系统，然后用新镜像重新启动
