### ISSUE TITLE
青龙进不去，显示服务异常

### ISSUE THREAD

**Issue by Laker360** [whyour/qinglong#719]
服务异常，请手动执行ql check检查服务状态，

**Comment by Laker360** [comment]
docker exec -it qinglong ql update      更新没有用，还是进不去面板

**Comment by Fcatme** [comment]
docker exec -it qinglong ql check

**Comment by Laker360** [comment]
=====> 后台服务异常，重置基础环境并重启后台

---> 1. 开始检测配置文件

检测到默认nginx配置文件，清空...

**Comment by Laker360** [comment]
然后呢，还是不行

**Comment by chavelee** [comment]
我也是

**Comment by whyour** [comment]
什么机器，ql check 只能打印这么点日志？

**Comment by zvzl** [comment]
同样的问题，登录页面提示服务异常，请手动执行ql check检查服务状态。

**Comment by CoderAWei** [comment]
我也是这样。执行了ql check还是不行。阿里云的CentOS7

**Comment by zvzl** [comment]
更新最新镜像后，已经恢复正常

**Comment by ufxymsn** [comment]
> 什么机器，ql check 只能打印这么点日志？

请问我的脚本命令里为什么没有ql check？

                                                                                  
root@qinglong:/ql $ ql                                                                         
命令输入错误...                                                                                
                                                                                               
本脚本用法：                                                                                   
1.  update                                           # 更新并重启青龙                          
1.  extra                                            # 运行自定义脚本                          
3.  raw <fileurl>                                    # 更新单个脚本文件                        
4.  repo <repourl> <path> <blacklist> <dependence>   # 更新单个仓库的脚本                      
5.  rmlog <days>                                     # 删除旧日志                              
6.  code                                             # 获取互助码                              
6.  bot                                              # 启动tg-bot                              
7.  reset                                            # 重置青龙基础环境
