### ISSUE TITLE
环境变量删不掉

### ISSUE THREAD

**Issue by bugme2** [whyour/qinglong#720]
![Screenshot_2021-09-22-12-19-16-68_11d59881ebb69c15251b128bef75a7ea](https://user-images.githubusercontent.com/40169265/134287903-36440451-ebac-4ca4-91b0-75bac58baa4a.jpg)
重装镜像
ql update
ql check
都试过，还是删不掉

**Comment by BIGBbox** [comment]
把ql文件夹删了试试

**Comment by bugme2** [comment]
> 把ql文件夹删了试试

我只是要删个别变量，把ql删了不就全没了

**Comment by whyour** [comment]
@bugme2 已知问题，建议先设置为空，再删除。目前没定位到具体原因

**Comment by whyour** [comment]
> > 把ql文件夹删了试试
> 
> 我只是要删个别变量，把ql删了不就全没了

在电脑上访问下，看下具体的错误信息。

**Comment by bugme2** [comment]
> > > 把ql文件夹删了试试
> > 
> > 
> > 我只是要删个别变量，把ql删了不就全没了
> 
> 在电脑上访问下，看下具体的错误信息。

电脑刚刚试了倒是没有错误，手机连上WiFi后也能删，就是流量删不掉，但是面板可以正常访问，其他网页也能正常打开，有点奇怪。
