### ISSUE TITLE
v2.9.3 并发数量配置无效，设置10看到同时执行的任务都20多个

### ISSUE THREAD

**Issue by evan766** [whyour/qinglong#725]
`## 设置批量执行任务时的并发数，默认同时执行5个任务
MaxConcurrentNum="5"`
配置没起作用

**Comment by xcodebin** [comment]
+1，2.9.5版本，我设置了20，批量运行200个脚本，刚开始是20个一起并发，后面慢慢的就变成只有5个以内并发了，无法维持长时间的20个并发量
