### ISSUE TITLE
大佬关于网络连接路

### ISSUE THREAD

**Issue by guilty-love** [whyour/qinglong#729]
![S10923-23082656](https://user-images.githubusercontent.com/54766361/134534534-4b3c83f7-d075-4cda-8dcb-bd8d5bd0dda8.png)
大佬能看下么？
tcp和udp连接的问题

我设置20个任务同时跑，udp连接路能干到4000并且还有增长的趋势
我现在只能把udp数限制为1000，但也直接满值，会有些任务提示网络异常 api出错啥的~现在设置10个任务同时跑了，感觉像有些任务跑完了并不及时断开连接一样，有些运行中的任务我查看当前日志显示任务已结束但在列表中看任务依然在运行，希望大佬能观注下，这个问题并不是这个版本才有，之前就有但没去注意~

**Comment by wingswing** [comment]
关注一下，一直都有的问题，解决了是不是能减少资源占用呢？
