### ISSUE TITLE
更新/ql成功...  /ql/config/extra.sh文件不存在，跳过执行...

### ISSUE THREAD

**Issue by happy-happ** [whyour/qinglong#73]
![image](https://user-images.githubusercontent.com/72593907/117681570-d0e10600-b1e4-11eb-81ea-e1836769ae0a.png)
大佬。这个pull后config没有这个文件，具体要怎样添加呢

**Comment by seasky8866** [comment]
/ql/config/extra.sh文件不存在，跳过执行..

**Comment by whyour** [comment]
这个没啥影响，我把这个提示去了
