### ISSUE TITLE
能不能添加几个运行键

### ISSUE THREAD

**Issue by hong0980** [whyour/qinglong#730]
能不能页面上添加几个运行键比如能直接运行ql updat，,ql extra，ql resetlet等等。。

**Comment by whyour** [comment]
像这种应该是没进页面之前要执行ql resetlet，除过update操作可以加以外，其他操作貌似都没啥意义

**Comment by hong0980** [comment]
感谢大佬回复！有时在extra.sh中自己加个小脚本运行下要是有键不是很方便，还是清除登陆之类应该很方便的。
