### ISSUE TITLE
【功能需求】定时任务配置添加是否日志推送配置项

### ISSUE THREAD

**Issue by iamsxm** [whyour/qinglong#738]
![image](https://user-images.githubusercontent.com/45477640/134833353-cde1e70e-0d75-470e-a86f-2e98e1aca448.png)
希望能够在定时任务配置界面，添加上是否通过单选框。
现在所有的定时任务都会通知，早上一起来20条消息，黑门子烦

**Comment by kuilei0926** [comment]
请区别定时任务的通知和青龙的通知

**Comment by kuilei0926** [comment]
> > 请区别定时任务的通知和青龙的通知
> 
> 你好，指的是定时任务的通知，现在没有控制选项，所有的定时任务都会推送通知

那你可以一个个去进行修改脚本代码让脚本不进行通知，青龙不能决定脚本是否通知，脚本是否通知是脚本自身代码决定的，不是青龙决定的

**Comment by xcodebin** [comment]
> > > 请区别定时任务的通知和青龙的通知
> > 
> > 
> > 你好，指的是定时任务的通知，现在没有控制选项，所有的定时任务都会推送通知
> 
> 那你可以一个个去进行修改脚本代码让脚本不进行通知，青龙不能决定脚本是否通知，脚本是否通知是脚本自身代码决定的，不是青龙决定的

将脚本的console日志输出，作为青龙面板系统通知进行管控，未尝不是一个新的功能亮点。这样就可以不用在js/python脚本里分别实现通知func了（青龙面板已系统层实现通知了不是么哈哈）

**Comment by shinyypig** [comment]
@xcodebin 确实，青龙面板如果能直接设置是否推送日志就好了。
