### ISSUE TITLE
屏蔽掉某个游戏不玩，以下设置不会生效。

### ISSUE THREAD

**Issue by ycyfff** [whyour/qinglong#74]
case $1 in
  chinnkarahoi_jd_jxnc)
    TempBlockCookie="1 2 3"  #京喜农场
    ;;
  chinnkarahoi_jd_pet)
    TempBlockCookie="1"  #东东萌宠
    ;;
  chinnkarahoi_jd_dreamFactory)
    TempBlockCookie="1 2 3"  #京喜工厂
    ;;
  chinnkarahoi_jx_cfdtx)
    TempBlockCookie="1 2 3"  #财富岛提现
    ;;
  chinnkarahoi_jd_try)
    TempBlockCookie="1 2"  #京东试用
    ;;
  ZCY01_jd_try)
    TempBlockCookie="23"  #京东试用
    ;;
esac

**Comment by ycyfff** [comment]
问题没解决呢，先别关闭。

**Comment by cctv180** [comment]
请问解决了么，我也想屏蔽部分账号不执行，放上去也没效果啊
