### ISSUE TITLE
环境变量能不能支持多个环境变量拼接啊

### ISSUE THREAD

**Issue by li-xunhuan** [whyour/qinglong#744]
比如我有一个`JD_A`，还有一个`JD_B`，我在配置`JD_COOKIE`的时候直接在值那里写`$JD_A&$JD_B`

**Comment by kuilei0926** [comment]
一直都可以，JD_A&JD_B

**Comment by li-xunhuan** [comment]
> 一直都可以，JD_A&JD_B

不需要单独再加一个`$`符号嘛？

**Comment by powelpaul** [comment]
不需要，只是A和B中间用&就可以，也可以A&B&C
