### ISSUE TITLE
为什么每次更新面板都会丢失模块？

### ISSUE THREAD

**Issue by inoyna12** [whyour/qinglong#749]
每次更新都会丢失模块，每次都要重新安装，我安装位置都在ql/scripts目录。
怎么禁用面板的更新，定时任务那里明明显示的已禁用，但是面板还是会在后台偷偷更新
![Uploading Screenshot_2021-09-30-08-58-00-086_mark.via.jpg…]()

**Comment by Jsongcloud** [comment]
如果是DOCKER版本，进入青龙，命令 docker exec -it qinglong bash
安装相关缺失的文件，比如我 npm -i tough-cookie
