### ISSUE TITLE
某些cron解析失败，默认成了 0 6 * * *

### ISSUE THREAD

**Issue by guakeliao** [whyour/qinglong#77]
某些cron解析失败，默认成了 0 6 * * *。连0301的脚本也有许多变成了0 6 * * *

**Comment by whyour** [comment]
哪些脚本

**Comment by guakeliao** [comment]
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/9064387/117767143-1b08cc80-b263-11eb-9bf9-d92532122b5c.png">

**Comment by whyour** [comment]
你全删了，重新拉取一次呢

**Comment by guakeliao** [comment]
我确认了一下，0301没有匹配到的。脚本里面没有写cron。
