### ISSUE TITLE
大佬，青龙一直启动不了

### ISSUE THREAD

**Issue by aliyy2021** [whyour/qinglong#772]
一直卡着启动不了，日志显示如下：

检测到默认nginx配置文件，清空...
,
一直卡着这样不动

**Comment by aliyy2021** [comment]
删掉容器，删掉镜像，重新安装都不行

**Comment by whyour** [comment]
@aliyy2021 镜像是最新的？

**Comment by aliyy2021** [comment]
> @aliyy2021 config下的 env.sh 和 config.sh 备份下，然后把里面的内容清空下。你应该是这两个文件内容有问题

谢大佬，是config.sh文件有问题，我昨天更新这个文件了
