### ISSUE TITLE
14日的DOCKER版本NG错误

### ISSUE THREAD

**Issue by caolicong** [whyour/qinglong#777]
刚好在推送后DCOKER重新安装，NG启动失败
======================3. 启动nginx========================

nginx: [emerg] unknown directive "client_body_buffer_size:" in /etc/nginx/nginx.conf:18

**Comment by caolicong** [comment]
补充下，回退后正常

**Comment by aliyy2021** [comment]
我更新镜像也是这个问题

**Comment by dengrenbocq** [comment]
解决办法

**Comment by dengrenbocq** [comment]
docker image inspect whyour/qinglong
看下GraphDriver data里面的overlay2 对应的id
然后 （我的id是 72aadbca9b2593c4da655ac7d4320da4929568937e67374a0a1e39d46d8ab571）
cd   /var/lib/docker/overlay2/72aadbca9b2593c4da655ac7d4320da4929568937e67374a0a1e39d46d8ab571/diff/ql/docker
修改里面的nginx.conf 18行冒号删除
 我是这样解决的

**Comment by vvlang** [comment]
unraid的路径是/var/lib/docker/btrfs/subvolumes/（id）/ql/docker/nginx.conf
