### ISSUE TITLE
通过Client ID和Client Secret获取到对应的token，但是在使用的时候提示"jwt malformed"

### ISSUE THREAD

**Issue by Jesn** [whyour/qinglong#778]
1、通过 `http://localhost:4080/open/auth/token?client_id=XXXX&client_secret=XXXX`获取到对应的token，eg：
```
{
    "code": 200,
    "data": {
        "token": "23c45f74-e3a9-485f-8576-94d2c8beebaf",
        "token_type": "Bearer",
        "expiration": 1636875776
    }
}
```

2、通过这个token去正常请求其他的接口，结果提示 "jwt malformed"

**Comment by whyour** [comment]
openapi 是以 open 开头，把 /api换成/open

**Comment by xiezy1** [comment]
![image](https://github.com/whyour/qinglong/assets/63857131/dda022de-70db-4e7c-806e-e4de52c7230e)
![image](https://github.com/whyour/qinglong/assets/63857131/773f0723-7c4f-42bc-b587-768cada00b6a)

其他接口没问题  我想更新定时任务

**Comment by xiezy1** [comment]
青龙版本 v2.15.11

**Comment by whyour** [comment]
@xiezy1 你把 cron 能写对吗
