### ISSUE TITLE
extra添加命令后更新面板后依然掉依赖

### ISSUE THREAD

**Issue by Stdocdure** [whyour/qinglong#779]
修改extra.sh文件后更新青龙面板后依然会掉依赖，请问大神们怎么解决？本人设备是群晖。
#!/usr/bin/env bash
bash -c "pnpm install -g typescript"
bash -c "pnpm install axios date-fns"
bash -c "pnpm install crypto -g"
bash -c "pnpm install jsdom"
bash -c "pnpm install png-js"
bash -c "pnpm install -g npm"
bash -c "pnpm i png-js"
bash -c "pip3 install requests"
bash -c "apk add --no-cache build-base g++ cairo-dev pango-dev giflib-dev && cd scripts && pnpm install canvas"
bash -c "apk add python3 zlib-dev gcc jpeg-dev python3-dev musl-dev freetype-dev"
bash -c "cd /ql/scripts/ && apk add --no-cache build-base g++ cairo-dev pango-dev giflib-dev && pnpm i && pnpm i -S ts-node typescript @types/node date-fns axios png-js canvas"

**Comment by lukemin** [comment]
#!/usr/bin/env bash
## 添加你需要重启自动执行的任意命令，比如 ql repo
## 安装node依赖使用 pnpm install -g xxx xxx
## 安装python依赖使用 pip3 install xxx
pip3 install requests
##npm config set registry https://registry.npmjs.org
##npm config set registry http://registry.npm.taobao.org
npm install -g typescript
npm install axios date-fns
npm install -g crypto 
npm install png-js
npm install -g npm
npm install -g jsdom
cd scripts
apk add --no-cache build-base g++ cairo-dev pango-dev giflib-dev python3 zlib-dev gcc jpeg-dev python3-dev musl-dev freetype-dev
npm i -S ts-node typescript @types/node date-fns axios png-js canvas --build-from-source

**Comment by Stdocdure** [comment]
> 把bash -c 及“删除掉，只要里面的命令就可以了。

大佬，我最早的版本就是你说的样子，一样的问题，我才换成这样又试了试还是不行。

**Comment by whyour** [comment]
```bash
#!/usr/bin/env bash
pnpm install -g typescript axios date-fns crypto jsdom png-js canvas @types/node typescript ts-node
pip3 install requests
apk add --no-cache build-base g++ cairo-dev pango-dev giflib-dev
apk add zlib-dev gcc jpeg-dev python3-dev musl-dev freetype-dev
```

加到 extra 试试，然后加个 ql extra定时任务执行看看
