### ISSUE TITLE
如何拉取自己的私有仓库

### ISSUE THREAD

**Issue by zhuiyue132** [whyour/qinglong#787]
私钥在哪加呢，求解巨佬。

**Comment by zengaorong** [comment]
兄弟，是在哪里加啊，和青龙有关吗

**Comment by zengaorong** [comment]
已经知晓，ssh拉取是需要选择的 git旁边就是ssh,然后要配置个公匙，按照这样关键词搜索 ssh-keygen

**Comment by zhuiyue132** [comment]
![image](https://user-images.githubusercontent.com/26954775/168637375-8e039242-4080-4dca-a9be-37c7b569ed50.png)
打码的分别是你的PAT和拉库代理。国外机器可以不用代理。

**Comment by zhuiyue132** [comment]
```js
ql repo https://oauth2:${PAT}@${proxySite}/${repoUrl}  ${allowList} ${blockList} ${dependencies} ${branch}
```
