### ISSUE TITLE
大批量运行脚本导致N1设备死机

### ISSUE THREAD

**Issue by guakeliao** [whyour/qinglong#79]
大批量运行脚本导致N1设备死机。我看了一下设备的状态。cpu满载100%。内存2G全用完。

**Comment by whyour** [comment]
> 我测试把0301的脚本全部运行的。所以可能运行了六十几个。
> 能不能设置一个队列，并发数改小一点。然后顺序执行，你看如何？

可以

**Comment by qq66711607** [comment]
同样的情况有出现在我的n1

**Comment by whyour** [comment]
https://t.me/qiongqiya/88
使用最新版试试
