### ISSUE TITLE
求助大神群晖里的docker怎么启动这个容器

### ISSUE THREAD

**Issue by diyuxiyang** [whyour/qinglong#790]
如题，镜像已下载，但是直接启动容器无法通过5700打开，应该是需要设置的，但是群晖里的docker是无法使用run 口令的，直接报错，想请教大神此情况下该怎么设置安装启动容器

**Comment by powelpaul** [comment]
群晖的docker是直接可以用鼠标点击启动的，也用不上命令行啊，你直接网页连接群晖不就好了
