### ISSUE TITLE
v2.9.10 手机版登录白屏/转圈

### ISSUE THREAD

**Issue by xsj684135** [whyour/qinglong#794]
内外网都试过，手机Safari不正常，电脑一切正常 具体情况如下：
当SESSIONID/COOKIE过期后，浏览器会提示登录失效请重新登录。（时间有点久，忘记了 大致是这么个意思）
手机以后就再也登录不上了，PC是正常的。
一直转圈圈，有时候刷新就是一直白屏。
请问大佬是个例还是BUG？

**Comment by xsj684135** [comment]
哦对了，并且还换过iOS版的Chrome，问题依旧，但是电脑Chrome使用F12选择iPhone又可以，就很迷

**Comment by ggggggggggithub** [comment]
我也是，登陆过期，再访问网页白屏，手机chrome正常，我的电脑端都不行，换UA也不行
