### ISSUE TITLE
配置通知pushplus失败

### ISSUE THREAD

**Issue by gaoweida1** [whyour/qinglong#797]
![image](https://user-images.githubusercontent.com/54660733/138538144-6a93cf03-0cc2-4e92-bdde-1ea0b901260b.png)

push.plus官网通知能过正常收到

**Comment by leon-titan** [comment]
同样问题，是翻车了吗

**Comment by leon-titan** [comment]
解决了，发现在通知设置里面配不管用，自己在环境变量里面添加PUSH_PLUS_TOKEN解决了
