### ISSUE TITLE
NodeJs安装3个依赖的问题

### ISSUE THREAD

**Issue by bonnyandsky** [whyour/qinglong#803]
第一个依赖：
![image](https://user-images.githubusercontent.com/30990861/138806813-2cee0ea9-9dff-489f-b762-781f06fdf4aa.png)
第二个依赖：
![image](https://user-images.githubusercontent.com/30990861/138806834-041cbadd-fb96-4e9e-8c5b-42d8b2b00fad.png)
第三个依赖：
![image](https://user-images.githubusercontent.com/30990861/138806863-d64b2d99-8ab2-438e-ba90-4859f399f2ba.png)
![image](https://user-images.githubusercontent.com/30990861/138806880-7ccfd94e-86bc-4f65-a655-975ce4d08d28.png)
其他依赖没什么问题
![image](https://user-images.githubusercontent.com/30990861/138806902-70291dd3-4304-433f-bb81-5aa9c6a5fe0e.png)

**Comment by mjyhj** [comment]
![1](https://user-images.githubusercontent.com/22577418/139531544-54363582-813f-411b-aa44-86f5990d40a2.png)
这样就可以了
