### ISSUE TITLE
[2.10.0] ql repo cron不执行 && 其余task任务状态混乱

### ISSUE THREAD

**Issue by Galaxy-yy** [whyour/qinglong#804]
repo命令手动执行有效。cron从未自己执行，不产生日志。
普通task任务cron有效，正常产生日志，任务状态完全不对，一些上次运行是空的，一些上次运行时间是上一天的某个时候。个别log里有记录到异常：Format is Authorization: Bearer [token] 更新任务状态失败。

pm2里没有异常。或者有其他什么地方，能查看异常日志，麻烦告知一下，我去抓出来，不然这两个问题实在没有地方入手，重启，从上一个版本update上来，问题依旧。

edit: 我算是看明白了，应该又是老问题，退出登录后没了token，update_cron失败了，所以task的状态都是空的，好在这次任务给运行了。repo命令应该是先获取用户信息，没token直接退出执行了。我开始怀疑我自己了，这个面板正确用法究竟是啥，是登录后不点退出，直接关网页嘛？但是现在登录源码里给了有效期，时间一过不就是和我点退出登录一样了吗。

**Comment by jy1989** [comment]
repo命令手动执行有效。cron从未自己执行   +1

**Comment by Galaxy-yy** [comment]
> repo命令手动执行有效。cron从未自己执行 +1

啊...这...莫要回复啦，都好久了。这是ql update上来有的bug，作者应该没精力管，删了容器装新一点的版本就没问题了。
