### ISSUE TITLE
全新2.0，定时任务不能执行。

### ISSUE THREAD

**Issue by hnlymmx** [whyour/qinglong#81]
全新安装，拉取仓库顺利。手动脚本正常，就是定时任务不能执行。

**Comment by whyour** [comment]
> 全新安装，拉取仓库顺利。手动脚本正常，就是定时任务不能执行。

怎么定时任务不能执行，你看config下的crontab.list有内容吗

**Comment by hnlymmx** [comment]
> > 全新安装，拉取仓库顺利。手动脚本正常，就是定时任务不能执行。
> 
> 怎么定时任务不能执行，你看config下的crontab.list有内容吗

crontag.list内有内容

**Comment by whyour** [comment]
> > > 全新安装，拉取仓库顺利。手动脚本正常，就是定时任务不能执行。
> > 
> > 
> > 怎么定时任务不能执行，你看config下的crontab.list有内容吗
> 
> crontab.list内有内容
> 4个示例拉下来后，里面共有92行定时任务，手动可执行，但是自动任务不执行。

没道理啊，去看看日志，有没有生成日志

**Comment by ysyzc** [comment]
> > > > 全新安装，拉取仓库顺利。手动脚本正常，就是定时任务不能执行。
> > > 
> > > 
> > > 怎么定时任务不能执行，你看config下的crontab.list有内容吗
> > 
> > 
> > 作者大大，更新2.0以后定时任务只有4个，而且手动运行更新面板时出错，全新安装也不行。
> 
> 所有任务要手动添加，看频道通知，手动出错，出什么错

明白了，谢谢
