### ISSUE TITLE
依赖管理，删除不了

### ISSUE THREAD

**Issue by mjyhj** [whyour/qinglong#817]
名称：add;gcc;libffi-dev;musl-dev;openssl-dev;python3-dev
名称：@types/node

像这样名称带符号的，直接删除不了

**Comment by mjyhj** [comment]
![1](https://user-images.githubusercontent.com/22577418/140805095-886543b6-5cb2-47af-8567-58327ab02abe.png)
![2](https://user-images.githubusercontent.com/22577418/140805099-8b2c9f9e-51c2-4983-b7b4-a3de619c0d46.png)
![3](https://user-images.githubusercontent.com/22577418/140805103-59af04df-31dd-4c89-8a4b-74fac0dce0a1.png)

**Comment by xx0114** [comment]
这个问题什么时候修复，能出个强制删除也行
