### ISSUE TITLE
添加cookie出错，请大佬解惑。

### ISSUE THREAD

**Issue by tom2021511** [whyour/qinglong#82]
N1，flippy的57+o，上个版本最开始部署好一切正常，后来就出错。登录控制面板，出现页面显示不完全。登录OpenWrt，也是各种页面显示不完全。重新刷OpenWrt，重新部署青龙，其它都正常，就是添加cookie总是出错。期间还把N1刷回安卓系统再刷回，也是不行。国内国外均访问正常，节点也换了很多个，都是添加出错。删除旧版青龙，装的全新2.0，还是出错。请大佬解惑。

![微信截图_20210511142301](https://user-images.githubusercontent.com/84003246/117769739-a9cb1880-b266-11eb-90b8-a31af2044435.png)

**Comment by whyour** [comment]
@tom2021511 docker启动的时候加上 —net host
