### ISSUE TITLE
提示 '服务异常，请手动执行ql check检查服务状态' check后无法安装青龙依赖

### ISSUE THREAD

**Issue by DJLZB** [whyour/qinglong#820]
====> 后台服务异常，重置基础环境并重启后台

---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

检测到 /ql 的依赖包有变化，运行 npm install...

 WARN  Moving @ant-design/icons that was installed by a different package manager to "node_modules/.ignored
 ERROR  EEXIST: file already exists, rename '/ql/node_modules/@ant-design/icons' -> '/ql/node_modules/.ignored/@ant-design/icons'
at ignored/    

安装 /ql 的依赖包运行不成功，再次尝试一遍...

运行 npm install...

 WARN  Moving @ant-design/icons that was installed by a different package manager to "node_modules/.ignored
 ERROR  EEXIST: file already exists, rename '/ql/node_modules/@ant-design/icons' -> '/ql/node_modules/.ignored/@ant-design/icons'
at ignored/    

npm install 运行不成功，请进入 /ql 目录后手动运行 npm install...

**Comment by wfinewy** [comment]
解决了吗

**Comment by 896965554** [comment]
怎么解决的
