### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by jwdstef** [whyour/qinglong#826]
跑了很多任务，跑到第二天的时候所有任务就都失败了查看日志如下：
/ql/shell/api.sh: line 158: /bin/date: Argument list too long
/ql/shell/api.sh: line 172: /usr/bin/curl: Argument list too long
/ql/shell/api.sh: line 172: /usr/bin/jq: Argument list too long
/ql/shell/api.sh: line 173: /usr/bin/jq: Argument list too long
/usr/local/bin/task: line 304: /bin/cat: Argument list too long
删除所有日志后，重启启动又好了，大佬是因为日志太多青龙卡住了么

**Comment by whyour** [comment]
把你的task_before.sh清掉试试

**Comment by fzls** [comment]
试试这个方案
https://gist.github.com/fzls/14f8d1d3ebb2fef64750ad91d268e4f6
