### ISSUE TITLE
TG设置正确却显示400错误

### ISSUE THREAD

**Issue by cytown** [whyour/qinglong#828]
最新的docker

在docker里面直接运行curl https://api.telegram.org/botxxxx/update 是成功的。

但在设置界面，选择TG通知，里面的TOKEN和USER_ID都正确设置后会显示400错误。

**Comment by cytown** [comment]
重新启动两次后设置OK了。

**Comment by fireinrain** [comment]
这个问题现在的版本依然会出现 报400错误，有一个很不方便的问题是看不到服务响应日志
