### ISSUE TITLE
系统设置中无法配置通知，我使用pushplus，保存token后，提示：通知发送失败，请检查参数

### ISSUE THREAD

**Issue by lxyer** [whyour/qinglong#830]
系统设置中无法配置通知，我使用pushplus，保存token后，提示：通知发送失败，请检查参数

**Comment by cncherisher** [comment]
遇到了同样的问题，确定token是正确的

**Comment by whyour** [comment]
https://www.pushplus.plus/send

pushplus是这个地址，看你们的是不是不是同一个

**Comment by gomingge** [comment]
> https://www.pushplus.plus/send
> 
> pushplus是这个地址，看你们的是不是不是同一个

使用这个地址的颁发的token, 但是也是通知发送失败

**Comment by liuyr88** [comment]
遇到了同样的问题，确定token是正确的

**Comment by jkingben** [comment]
也一样，两个plus都试了，token都没法用。

**Comment by ctaoist** [comment]
用GOCqhttp也是一样的，返回`{"code":400,"data":"通知发送失败，请检查参数"}`
