### ISSUE TITLE
时间显示错误问题

### ISSUE THREAD

**Issue by T3rdW** [whyour/qinglong#831]
![image](https://user-images.githubusercontent.com/14792476/140288936-9d571b58-6ab1-42e3-bcb6-4d481d6c2f76.png)
版本 V2.10.1
刚更新完发现的,之前的版本没有注意是否有此现象.不确定是否是新版本导致的还是旧版本遗留下来的BUG

**Comment by zhanglei0310** [comment]
发现存在该问题，也提过issue不过好像一直没修

**Comment by T3rdW** [comment]
下个版本应该就修复了,已经看到提交了
