### ISSUE TITLE
docker无法启动报错如下

### ISSUE THREAD

**Issue by tiantianxiaoxiaoxyz** [whyour/qinglong#833]
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 11:    50 Trace/breakpoint trap   (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 11:    51 Trace/breakpoint trap   (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 11:    50 Trace/breakpoint trap   (core dumped) pm2 l > /dev/null 2>&1

**Comment by feiniao025** [comment]
同样报错

**Comment by denzhengwei** [comment]
同报错，老哥们有人解决了嘛？

**Comment by tiantianxiaoxiaoxyz** [comment]
> 同报错，老哥们有人解决了嘛？

没解决，暂时用V3-BOT应急

**Comment by whyour** [comment]
> > 同报错，老哥们有人解决了嘛？
> 
> 没解决，暂时用V3-BOT应急

最新的镜像？

**Comment by denzhengwei** [comment]
> > > 同报错，老哥们有人解决了嘛？
> > 
> > 
> > 没解决，暂时用V3-BOT应急
> 
> 最新的镜像？

对，更新了最新镜像之后就死了，容器起不来，镜像ID 03a635b407f9

**Comment by whyour** [comment]
@denzhengwei 远程下？

**Comment by denzhengwei** [comment]
> @denzhengwei 远程下？

可以啊，怎么远程？

**Comment by whyour** [comment]
@denzhengwei todesk 向日葵

**Comment by denzhengwei** [comment]
> todesk

好，向日葵走一波，我下载一个

**Comment by denzhengwei** [comment]
> @denzhengwei todesk 向日葵

732691393
1w9igu

**Comment by feiniao025** [comment]
降级到2.10.0解决了。

**Comment by whyour** [comment]
> > @denzhengwei todesk 向日葵
> 
> 732691393 1w9igu

更新下镜像试试

**Comment by tiantianxiaoxiaoxyz** [comment]
目前在dockerhub上找别人备份的2.9.9版本装上后恢复了。

**Comment by denzhengwei** [comment]
> > > @denzhengwei todesk 向日葵
> > 
> > 
> > 732691393 1w9igu
> 
> 更新下镜像试试

情况依旧，报错一样

**Comment by Janet-Baker** [comment]
如果青龙最新镜像出现
`cp: cannot create regular file '/etc/nginx/conf.d/front.conf': No such file or directory`

原因是 容器内不存在目录 `/etc/nginx/conf.d`

那么，可以运行
`mkdir conf.d&&docker cp conf.d 容器名:/etc/nginx/conf.d&&rm -rf conf.d`
创建一个 `conf.d` 文件夹并复制进去

**Comment by whyour** [comment]
> 如果青龙最新镜像出现 `cp: cannot create regular file '/etc/nginx/conf.d/front.conf': No such file or directory`
> 
> 原因是 容器内不存在目录 `/etc/nginx/conf.d`
> 
> 那么，可以运行 `mkdir conf.d&&docker cp conf.d 容器名:/etc/nginx/conf.d&&rm -rf conf.d` 创建一个 `conf.d` 文件夹并复制进去

大佬，这跟你那个是一个问题吗？需要不同issue去粘贴？

**Comment by guoqing1977** [comment]
> > 如果青龙最新镜像出现 `cp: cannot create regular file '/etc/nginx/conf.d/front.conf': No such file or directory`
> > 原因是 容器内不存在目录 `/etc/nginx/conf.d`
> > 那么，可以运行 `mkdir conf.d&&docker cp conf.d 容器名:/etc/nginx/conf.d&&rm -rf conf.d` 创建一个 `conf.d` 文件夹并复制进去
> 
> 大佬，这跟你那个是一个问题吗？需要不同issue去粘贴？

就是在容器中创建一个nignx的配置文件夹，测试过了，可以启动了。

**Comment by whyour** [comment]
@guoqing1977 你看这个bug的错误跟你说的一样吗

**Comment by guoqing1977** [comment]
> @guoqing1977 你看这个bug的错误跟你说的一样吗
我说找不到front.conf

**Comment by zjlloveo0** [comment]
@whyour 大佬 这个错误我也遇到了
======================1. 检测配置文件========================
,
,'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
,'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
,./docker/docker-entrypoint.sh: line 11:    15 Trace/breakpoint trap   (core dumped) pm2 l > /dev/null 2>&1

用pre和latest都不行😂

**Comment by whyour** [comment]
@zjlloveo0 什么机器

**Comment by zjlloveo0** [comment]
> 
> 
> @zjlloveo0 什么机器

玩客云 刷的armbian

**Comment by Rexloong** [comment]
一样的情况，也是玩客云armbian
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 12:    15 Trace/breakpoint trap   (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 12:    15 Trace/breakpoint trap   (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 12:    15 Trace/breakpoint trap   (core dumped) pm2 l > /dev/null 2>&1
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
./docker/docker-entrypoint.sh: line 12:    15 Trace/breakpoint trap   (core dumped) pm2 l > /dev/null 2>&1

**Comment by Grayson-test1** [comment]
一样的情况，现在用的2.9版本

**Comment by zjlloveo0** [comment]
这是自动回复邮件，您收到这封邮件表示您发送的邮件已发送到我的邮箱，我看到后将尽快给您回复。
