### ISSUE TITLE
能有办法集成Selenium吗

### ISSUE THREAD

**Issue by lustime** [whyour/qinglong#834]
能有办法集成Selenium吗

**Comment by lustime** [comment]
搞定 打扰啦

**Comment by chenbaker** [comment]
> 搞定 打扰啦

求教，怎样搞定的？我在面板 依赖管理 中安装几次，都是失败。应该怎样安装？谢谢！

**Comment by hong0980** [comment]
https://github.com/OreosLab/checkinpanel/blob/master/ins_selenium.sh 这个能帮你正确安装
