### ISSUE TITLE
最新版docker无法启动求助

### ISSUE THREAD

**Issue by feiniao025** [whyour/qinglong#837]
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

./docker/docker-entrypoint.sh: line 11:    47 Trace/breakpoint trap   (core dumped) pm2 l > /dev/null 2>&1

**Comment by denzhengwei** [comment]
同报错求解

**Comment by denzhengwei** [comment]
ARM32架构armbian

**Comment by hunter-sn** [comment]
Linux iZrpbfcok3tfvyZ 4.9.0-16-amd64 #1 SMP Debian 4.9.272-2 (2021-07-19) x86_64 GNU/Linux

docker logs

./docker/docker-entrypoint.sh: line 9: /bin/cp: Argument list too long
/ql/shell/share.sh: line 106: /bin/ln: Argument list too long
/ql/shell/share.sh: line 106: /bin/ln: Argument list too long
/ql/shell/share.sh: line 106: /bin/ln: Argument list too long
======================1. 检测配置文件========================

**Comment by tiantianxiaoxiaoxyz** [comment]
楼主的问题有解决吗？

**Comment by feiniao025** [comment]
> 楼主的问题有解决吗？

装2.10.0解决了。

**Comment by denzhengwei** [comment]
> > 楼主的问题有解决吗？
> 
> 装2.10.0解决了。

怎么装2.10.0啊老哥，docker pull whyour/qinglong:2.10.0这条命令无效

**Comment by tiantianxiaoxiaoxyz** [comment]
> > 楼主的问题有解决吗？
> 
> 装2.10.0解决了。

老哥，咋退回2.10.0啊，找不到找个镜像了

**Comment by cnrodney** [comment]
> > > 楼主的问题有解决吗？
> > 
> > 
> > 装2.10.0解决了。
> 
> 怎么装2.10.0啊老哥，docker pull whyour/qinglong:2.10.0这条命令无效

同求

**Comment by zjlloveo0** [comment]
> > > > 楼主的问题有解决吗？
> > > 
> > > 
> > > 装2.10.0解决了。
> > 
> > 
> > 怎么装2.10.0啊老哥，docker pull whyour/qinglong:2.10.0这条命令无效
> 
> 同求

同求

**Comment by whyour** [comment]
@zjlloveo0 docker pull whyour/qinglong:pre  这个目前是2.10.0

**Comment by zjlloveo0** [comment]
> @zjlloveo0 docker pull whyour/qinglong:pre 这个目前是2.10.0

谢谢大佬回复

**Comment by mqds2016** [comment]
运行下
mkdir conf.d&&docker cp /root/conf.d QL:/etc/nginx/conf.d&&rm -rf conf.d
