### ISSUE TITLE
安装依赖时提示python pip no such package

### ISSUE THREAD

**Issue by zackandyou** [whyour/qinglong#838]
![image](https://user-images.githubusercontent.com/93066053/140474593-9c1c4f6a-5bbc-437d-a77d-ad29a816dc6f.png)

**Comment by heroarrow** [comment]
已更新2.10.1

**Comment by whyour** [comment]
用2.10.2的镜像试试

**Comment by heroarrow** [comment]
> 用2.10.2的镜像试试
![image](https://user-images.githubusercontent.com/93066053/140596165-e22687a2-a1e8-44c5-9692-196c1af484d7.png)
