### ISSUE TITLE
拉不了啊

### ISSUE THREAD

**Issue by tzxiaozhen88** [whyour/qinglong#84]
错误
Status: Downloaded newer image for whyour/qinglong:latest
docker: Error response from daemon: create opt/ql/config: "opt/ql/config" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by whyour** [comment]
> 错误
> Status: Downloaded newer image for whyour/qinglong:latest
> docker: Error response from daemon: create opt/ql/config: "opt/ql/config" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
> See 'docker run --help'.

run启动的时候映射目录以 / 开头
