### ISSUE TITLE
希望开发拉取github仓库分支功能

### ISSUE THREAD

**Issue by yufeiyang2008** [whyour/qinglong#840]
希望开发拉取github仓库分支功能

**Comment by F-Light** [comment]
手动 git clone -b 分支名

**Comment by yufeiyang2008** [comment]
> 手动 git clone -b 分支名

我知道这个，我意思是ql repo拉取分支

**Comment by Cp0204** [comment]
ql repo xxxxxxxxxxxxxxxxx "main"
