### ISSUE TITLE
11.6号晚上到11.7上午，尝试安装一直失败

### ISSUE THREAD

**Issue by 475488889** [whyour/qinglong#843]
11.6号晚上到11.7上午，尝试安装一直失败，安装完毕后，执行qinglong]# docker exec -it qinglong bash
一直提示Error response from daemon: Container 9a74027d24d3e5c55baeaac186c0c062b5b70a1c63552a0b17141bb9d6a17192 is restarting, wait until the container is runni
，

**Comment by zjlloveo0** [comment]
我也是，玩客云arm32，日志
cp: cannot create regular file '/etc/nginx/conf.d/front.conf': No such file or directory
,'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

**Comment by zjlloveo0** [comment]
> 我也是，玩客云arm32，日志 cp: cannot create regular file '/etc/nginx/conf.d/front.conf': No such file or directory ,'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

还有个错误日志大概是docker/docker-entrypoint.sh: line 11   暂时复现不了

**Comment by huangtianxing** [comment]
树莓派4B也是这样

**Comment by whyour** [comment]
@zjlloveo0 你可以启动容器的时候指定entrypoint, 然后看容器内是不是没有/etc/nginx/conf.d目录了

**Comment by zjlloveo0** [comment]
> @zjlloveo0 你可以启动容器的时候指定entrypoint, 然后看容器内是不是没有/etc/nginx/conf.d目录了

好的 我试试看

**Comment by phoenixxie0** [comment]
@whyour 确实是这个问题。检查之后发现/etc/nginx/conf.d/是不存在的。

**Comment by Kkwoai** [comment]
如果青龙最新镜像出现
cp: cannot create regular file '/etc/nginx/conf.d/front.conf': No such file or directory
docker stop 容器名 停止容器 然后运行
mkdir conf.d&&docker cp conf.d 容器名:/etc/nginx/conf.d&&rm -rf conf.d
最后在启动容器 就可以了

**Comment by whyour** [comment]
> @whyour 确实是这个问题。检查之后发现/etc/nginx/conf.d/是不存在的。

更新下最新的镜像
