### ISSUE TITLE
今天安装青龙面板脚本运行不了

### ISSUE THREAD

**Issue by BAIGGGU** [whyour/qinglong#845]
![image](https://user-images.githubusercontent.com/64839801/140636114-381d7a55-1390-48c1-874f-67945bfb2503.png)

**Comment by mqds2016** [comment]
同问兄弟

**Comment by w1915591935** [comment]
+1阿

**Comment by xinxuanjvshi** [comment]
你看下执行了吗可能是执行完再显示日志

**Comment by BAIGGGU** [comment]
> 你看下执行可以是执行完再显示日志

不是的，点击执行并没有执行

**Comment by markjackym** [comment]
Task 前面多了bash,我也这样

**Comment by mqds2016** [comment]
> Task 前面多了bash,我也这样

解决了吗，头疼

**Comment by markjackym** [comment]
> > Task 前面多了bash,我也这样
> 
> 解决了吗，头疼

无解，我都重装了，以为是我自己的问题🙃

**Comment by whyour** [comment]
@markjackym 把你们环境说下

**Comment by markjackym** [comment]
> @markjackym 把你们环境说下

centos7.9宝塔面板里的docker,最新镜像

**Comment by mqds2016** [comment]
> @markjackym 把你们环境说下

centos 7.6 x86-64，青龙2.10.2

**Comment by BAIGGGU** [comment]
> @markjackym把你们环境说下

centos7.6 qinglong:latest

**Comment by whyour** [comment]
@BAIGGGU 执行如下，看下日志

type task &>/dev/null
type task >/dev/null 2>&1

cd /ql/shell
ls -alh

把输出贴出来，没有输出，写没有输出

**Comment by BAIGGGU** [comment]
> @BAIGGGU 执行如下，看下日志
> 
> type task &>/dev/null type task >/dev/null 2>&1
> 
> cd /ql/shell ls -alh
> 
> 把输出贴出来，没有输出，写没有输出

![image](https://user-images.githubusercontent.com/64839801/140642571-603c8b01-744a-410d-913f-24717806a192.png)

**Comment by mqds2016** [comment]
> @BAIGGGU 执行如下，看下日志
> 
> type task &>/dev/null type task >/dev/null 2>&1
> 
> cd /ql/shell ls -alh
> 
> 把输出贴出来，没有输出，写没有输出

没有这个路劲

**Comment by whyour** [comment]
@BAIGGGU 容器内执行

**Comment by mqds2016** [comment]
> @BAIGGGU 执行如下，看下日志
> 
> type task &>/dev/null type task >/dev/null 2>&1
> 
> cd /ql/shell ls -alh
> 
> 把输出贴出来，没有输出，写没有输出

drwxr-xr-x 2 root root 4.0K Nov  6 20:24 .
drwxr-xr-x 1 root root 4.0K Nov  7 00:06 ..
-rwxrwxrwx 1 root root 6.7K Nov  6 20:24 api.sh
-rwxrwxrwx 1 root root 1.2K Nov  6 20:24 bot.sh
-rwxrwxrwx 1 root root 3.3K Nov  6 20:24 check.sh
-rw-r--r-- 1 root root  163 Nov  6 20:24 notify.js
-rwxrwxrwx 1 root root  192 Nov  6 20:24 notify.sh
-rwxrwxrwx 1 root root 1.2K Nov  6 20:24 rmlog.sh
-rwxrwxrwx 1 root root 8.7K Nov  6 20:24 share.sh
-rwxrwxrwx 1 root root  12K Nov  6 20:24 task.sh
-rwxrwxrwx 1 root root  20K Nov  6 20:24 update.sh

**Comment by markjackym** [comment]
> @BAIGGGU 执行如下，看下日志
> 
> type task &>/dev/null type task >/dev/null 2>&1
> 
> cd /ql/shell ls -alh
> 
> 把输出贴出来，没有输出，写没有输出

ls -alh
total 84K
drwxr-xr-x 2 root root 4.0K Nov  7 11:35 .
drwxr-xr-x 1 root root 4.0K Nov  7 15:28 ..
-rwxrwxrwx 1 root root 6.7K Nov  7 11:35 api.sh
-rwxrwxrwx 1 root root 1.2K Nov  7 11:35 bot.sh
-rwxrwxrwx 1 root root 3.3K Nov  7 11:35 check.sh
-rw-r--r-- 1 root root  163 Nov  7 11:35 notify.js
-rwxrwxrwx 1 root root  192 Nov  7 11:35 notify.sh
-rwxrwxrwx 1 root root 1.2K Nov  7 11:35 rmlog.sh
-rwxrwxrwx 1 root root 8.7K Nov  7 11:35 share.sh
-rwxrwxrwx 1 root root  12K Nov  7 11:35 task.sh
-rwxrwxrwx 1 root root  20K Nov  7 11:35 update.sh

**Comment by whyour** [comment]
![image](https://user-images.githubusercontent.com/22700758/140642914-46edf450-4501-4787-98ca-1a9f886e1fda.png)
有能力的修改下 /ql/shell/share.sh 里的 130行 137行的双中括号改成单中括号，再ql repo试试

**Comment by markjackym** [comment]
> ![image](https://user-images.githubusercontent.com/22700758/140642914-46edf450-4501-4787-98ca-1a9f886e1fda.png) 有能力的修改下 /ql/shell/share.sh 里的 130行 137行的双中括号改成单中括号，再ql repo试试

貌似没有用

**Comment by mqds2016** [comment]
> ![image](https://user-images.githubusercontent.com/22700758/140642914-46edf450-4501-4787-98ca-1a9f886e1fda.png) 有能力的修改下 /ql/shell/share.sh 里的 130行 137行的双中括号改成单中括号，再ql repo试试

改了，也没法运行脚本，呜呜呜

**Comment by whyour** [comment]
@mqds2016 远程试试？todesk，向日葵

**Comment by mqds2016** [comment]
> @mqds2016 远程试试？todesk，向日葵

好，怎么直接发你连接信息吗

**Comment by mqds2016** [comment]
> @mqds2016 远程试试？todesk，向日葵

好，直接回复链接信息吗

**Comment by whyour** [comment]
@mqds2016 嗯。直接发吧

**Comment by mqds2016** [comment]
> @mqds2016 嗯。直接发吧

todesk
763008237
086550

**Comment by mqds2016** [comment]
> @mqds2016 嗯。直接发吧

麻烦你啦，后续怎么更改端口的

**Comment by zgs2021** [comment]
怎么解决的，可否告知一下

**Comment by mqds2016** [comment]
> 怎么解决的，可否告知一下

作者大佬去写更新了，晚点更新下应该就可以了

**Comment by zgs2021** [comment]
嗯，好的

**Comment by w1915591935** [comment]
等着哈哈

**Comment by whyour** [comment]
https://t.me/jiao_long/214

**Comment by Janet-Baker** [comment]
如果青龙最新镜像出现
`cp: cannot create regular file '/etc/nginx/conf.d/front.conf': No such file or directory`

原因是 容器内不存在目录 `/etc/nginx/conf.d`

那么，可以运行
`mkdir conf.d&&docker cp conf.d 容器名:/etc/nginx/conf.d&&rm -rf conf.d`
创建一个 `conf.d` 文件夹并复制进去
