### ISSUE TITLE
面板tg发消息走代理报错

### ISSUE THREAD

**Issue by passerby-b** [whyour/qinglong#851]
同一脚本调用同一通知脚本,用nodejs命令运行可以发tg消息,用面板任务运行脚本发tg消息就报错,国内vps,tg设置的代理

/ql/scripts/node_modules/tunnel-agent/index.js:177
    var error = new Error('tunneling socket could not be established, ' + 'cause=' + cause.message)
                ^

Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:10809
    at ClientRequest.onError (/ql/scripts/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET'
}

**Comment by vc5** [comment]
同样的问题

**Comment by IITII** [comment]
设置 TG_API_HOST 环境变量, 走  TG API 反代

**Comment by IITII** [comment]
详见 sendnotify
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/33705067/210510895-e6f561c0-4bac-41ac-b369-4aa426b1bebb.png">

**Comment by IITII** [comment]
//tg推送HTTP代理设置(不懂可忽略,telegram机器人通知推送功能中非必填)
let TG_PROXY_HOST = ''; //例如:127.0.0.1(环境变量名:TG_PROXY_HOST)
let TG_PROXY_PORT = ''; //例如:1080(环境变量名:TG_PROXY_PORT)
let TG_PROXY_AUTH = ''; //tg代理配置认证参数
//Telegram api自建的反向代理地址(不懂可忽略,telegram机器人通知推送功能中非必填),默认tg官方api(环境变量名:TG_API_HOST)
let TG_API_HOST = 'api.telegram.org';

**Comment by leic4u** [comment]
> 设置 TG_API_HOST 环境变量, 走 TG API 反代

请问下大佬，我在配置文件里面，和青龙面板-系统设置-通知设置里面，都设置了反代地址（该反代地址在同一台 NAS 里面 docker 部署的 ddns-go 和 nevinee 的 qb 项目里面都可以正常使用），但脚本执行通知，和通知设置的保存测试还是报这个错误，大概会是什么原因呢？

我昨天尝试搞了一下，发现在

脚本配置文件：
![image](https://github.com/whyour/qinglong/assets/32786903/8547afea-e96a-478e-aac9-a2a56b6865d2)

脚本执行报错：
![image](https://github.com/whyour/qinglong/assets/32786903/730348c1-3b0e-448d-b172-328b7e87ab9a)

面板系统设置：
![image](https://github.com/whyour/qinglong/assets/32786903/fef3ca36-2f7a-49f9-b24b-386c5cdfd588)
