### ISSUE TITLE
2.10.7运行脚本报错

### ISSUE THREAD

**Issue by Chase2179** [whyour/qinglong#856]
/ql/shell/api.sh: line 4: /bin/cat: Argument list too long
/ql/shell/api.sh: line 4: /usr/bin/jq: Argument list too long
/usr/local/bin/task: line 87: /bin/date: Argument list too long
/usr/local/bin/task: line 98: /bin/date: Argument list too long
/usr/local/bin/task: line 99: /bin/date: Argument list too long
/usr/local/bin/task: line 103: /bin/cat: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/awk: Argument list too long
/usr/local/bin/task: line 103: /bin/grep: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/head: Argument list too long
/usr/local/bin/task: line 116: /bin/date: Argument list too long
/usr/local/bin/task: line 117: /bin/date: Argument list too long
/usr/local/bin/task: line 118: -  : syntax error: operand expected (error token is "-  ")
/ql/shell/api.sh: line 4: /bin/cat: Argument list too long
/ql/shell/api.sh: line 4: /usr/bin/jq: Argument list too long
/usr/local/bin/task: line 87: /bin/date: Argument list too long
/usr/local/bin/task: line 98: /bin/date: Argument list too long
/usr/local/bin/task: line 99: /bin/date: Argument list too long
/usr/local/bin/task: line 103: /usr/local/bin/task: line 103: /bin/grep: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/perl: Argument list too long
/bin/cat: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/awk: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/head: Argument list too long
/usr/local/bin/task: line 116: /bin/date: Argument list too long
/usr/local/bin/task: line 117: /bin/date: Argument list too long
/usr/local/bin/task: line 118: -  : syntax error: operand expected (error token is "-  ")
/ql/shell/api.sh: line 4: /bin/cat: Argument list too long
/ql/shell/api.sh: line 4: /usr/bin/jq: Argument list too long
/usr/local/bin/task: line 87: /bin/date: Argument list too long
/usr/local/bin/task: line 98: /bin/date: Argument list too long
/usr/local/bin/task: line 99: /bin/date: Argument list too long
/usr/local/bin/task: line 103: /usr/local/bin/task: line 103: /bin/grep: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/awk: Argument list too long
/bin/cat: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/head: Argument list too long
/usr/local/bin/task: line 116: /bin/date: Argument list too long
/usr/local/bin/task: line 117: /bin/date: Argument list too long
/usr/local/bin/task: line 118: -  : syntax error: operand expected (error token is "-  ")
/ql/shell/api.sh: line 4: /bin/cat: Argument list too long
/ql/shell/api.sh: line 4: /usr/bin/jq: Argument list too long
/usr/local/bin/task: line 87: /bin/date: Argument list too long
/usr/local/bin/task: line 98: /bin/date: Argument list too long
/usr/local/bin/task: line 99: /bin/date: Argument list too long
/usr/local/bin/task: line 103: /bin/cat: Argument list too long/usr/local/bin/task: line 103: /usr/bin/head: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/perl: Argument list too long

/usr/local/bin/task: line 103: /bin/grep: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/awk: Argument list too long
/usr/local/bin/task: line 116: /bin/date: Argument list too long
/usr/local/bin/task: line 117: /bin/date: Argument list too long
/usr/local/bin/task: line 118: -  : syntax error: operand expected (error token is "-  ")
/ql/shell/api.sh: line 4: /bin/cat: Argument list too long
/ql/shell/api.sh: line 4: /usr/bin/jq: Argument list too long
/usr/local/bin/task: line 87: /bin/date: Argument list too long
/usr/local/bin/task: line 98: /bin/date: Argument list too long
/usr/local/bin/task: line 99: /bin/date: Argument list too long
/usr/local/bin/task: line 103: /usr/local/bin/task: line 103: /bin/cat: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/awk: Argument list too long
/bin/grep: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/head: Argument list too long
/usr/local/bin/task: line 116: /bin/date: Argument list too long
/usr/local/bin/task: line 117: /bin/date: Argument list too long
/usr/local/bin/task: line 118: -  : syntax error: operand expected (error token is "-  ")
/ql/shell/api.sh: line 4: /bin/cat: Argument list too long
/ql/shell/api.sh: line 4: /usr/bin/jq: Argument list too long
/usr/local/bin/task: line 87: /bin/date: Argument list too long
/usr/local/bin/task: line 98: /bin/date: Argument list too long
/usr/local/bin/task: line 99: /bin/date: Argument list too long
/usr/local/bin/task: line 103: /bin/cat: Argument list too long
/usr/local/bin/task: line 103: /usr/bin/perl: Argument list too long
/usr/local/bin/task: line 103: /usr/local/bin/task: line 103: /usr/bin/head: Argument list too long/bin/grep: Argument list too long

/usr/local/bin/task: line 103: /usr/bin/awk: Argument list too long
/usr/local/bin/task: line 116: /bin/date: Argument list too long
/usr/local/bin/task: line 117: /bin/date: Argument list too long
/usr/local/bin/task: line 118: -  : syntax error: operand expected (error token is "-  ")

**Comment by fzls** [comment]
试试这个方案
https://gist.github.com/fzls/14f8d1d3ebb2fef64750ad91d268e4f6
