### ISSUE TITLE
新版本，全部依赖几天后自动失效。

### ISSUE THREAD

**Issue by shuxin8795** [whyour/qinglong#861]
![image](https://user-images.githubusercontent.com/65381978/141060291-0207d661-4827-491b-b96e-1391d0d0932f.png)

/bin/bash: line 1: npm: command not found

依赖安装失败，结束时间 2021/11/10 下午2:10:16，耗时 0.079 秒

**Comment by wonderhong** [comment]
我也是，装好了过一段时间就变成安装失败了

**Comment by Muceball** [comment]
进容器后，npm install -g xxxx
不需要用这个依赖管理。
进容器的方法docker exec -it 你的青龙名称或者是容器id bash

**Comment by naiveclub** [comment]
> 进容器后，npm install -g xxxx 不需要这个依赖管理。 进容器的方法docker exec -it 你的青龙或者是容器id bash

用这个方法安装青龙依赖会报错

**Comment by Muceball** [comment]
进容器后，npm install -g xxxx，用这个方法安装依赖（记得把xxxx换成自己需要安装的依赖名称）后不需要在青龙中配置任何依赖了呀。就压根不需要青龙管理依赖了。
这个命令是全局安装依赖，用这个方法安装的依赖只要你的docker没有重做，依赖就不会失效，也压根不需要青龙管理，一劳永逸。
如下图。这是我的，提示缺啥依赖直接容器内安装一次就好了。
![image](https://user-images.githubusercontent.com/51481074/142722151-c869a9a3-7092-4471-a916-7cfbbbdbd206.png)

![image](https://user-images.githubusercontent.com/51481074/142722139-d1864bbb-783a-4458-a774-2e7b21e7b663.png)
