### ISSUE TITLE
运行久了docker占用到了5G，能清理吗

### ISSUE THREAD

**Issue by lostme01** [whyour/qinglong#864]
运行久了docker占用到了5G，能清理吗

**Comment by woaicandy** [comment]
检查这个目录，正常是日志占用大  一堆错误日志
docker/btrfs/subvolumes/********/root/.pm2/

**Comment by SekiBetu** [comment]
> 检查这个目录，正常是日志占用大 一堆错误日志 docker/btrfs/subvolumes/********/root/.pm2/

和日志无关，docker的垃圾很多很多，我的青龙已经10G了
