### ISSUE TITLE
调试脚本疑问，新建js脚本，点击脚本管理-调试-运行，没有反应

### ISSUE THREAD

**Issue by yonggithub** [whyour/qinglong#865]
点击**脚本管理-调试-运行**，没有反应。
请教一下正确的使用姿势？
![image](https://user-images.githubusercontent.com/25076827/141120715-626f60c4-73b0-45e3-bbdb-099bd1700aeb.png)

**Comment by underlaw** [comment]
编辑 保存也没有用了
