### ISSUE TITLE
ql repo独立库能否加个参数实现，一些脚本作者不提供依赖脚本现在就有点尴尬了。

### ISSUE THREAD

**Issue by Spheniscidaer** [whyour/qinglong#872]
如果加参数实现，对于没有提供依赖的脚本作者，可以直接放到scripts目录执行脚本。

有依赖冲突的脚本，就独立文件防止依赖冲突。

**Comment by synoman** [comment]
唉，最近发现新版本往往都会导致容器无法启动，于是乎干脆禁用了UPDATE，好死不死，我还装了WATCHOVER，好了，这次更新又中招了

**Comment by Spheniscidaer** [comment]
> 唉，最近发现新版本往往都会导致容器无法启动，于是乎干脆禁用了UPDATE，好死不死，我还装了WATCHOVER，好了，这次更新又中招了

问题不大。提供依赖脚本的，拉库补个sendNotify.js 脚本。没提供依赖脚本的补sendNotify.js跟jdCookie.js脚本即可。开发者这样改还是有利的，虽然目前有这个问题，后面肯定会优化改进的

**Comment by whyour** [comment]
@Spheniscidaer 目前系统会从scripts目录下的所有文件里找你需要的依赖，但是你的 ql repo命令要声明你要这两个依赖，作者没提供，你命令里要声明你要，才会去找。可以读读源码

**Comment by synoman** [comment]
所以啊，应该提供一个稳定版，然后搞个beta版或者DEMO版供懂技术的测试，雷排的差不多了，小白再上

**Comment by whyour** [comment]
@synoman 什么事不需要时间？我是全职吗

**Comment by Spheniscidaer** [comment]
目前我是觉得拉库加参数实现独立库，会比较合理些。

> @Spheniscidaer 目前系统会从scripts目录下的所有文件里找你需要的依赖，但是你的 ql repo命令要声明你要这两个依赖，作者没提供，你命令里要声明你要，才会去找。可以读读源码

谢谢dalao解答。公告频道的说明没看仔细
