### ISSUE TITLE
建议保留2-3个旧版镜像

### ISSUE THREAD

**Issue by rTnrWE** [whyour/qinglong#876]
更新2.10.3后，无法打开面板，重新安装仍然无法打开面板，建议保留2-3个旧版镜像，方便新版出问题后，手动拉回旧版本安装

**Comment by zhudan** [comment]
可以回滚到上个版本，起来容器是可以起来的，定时任务可以跑，只是panel是坏的。

`git reset --hard && git checkout af5561cbbfb60fe269c4b4b7538c3ce70853d5d7`

**Comment by rTnrWE** [comment]
> 可以回滚到上个版本，起来容器是可以起来的，定时任务可以跑，只是panel是坏的。
> 
> `git reset --hard && git checkout af5561cbbfb60fe269c4b4b7538c3ce70853d5d7`

多谢

执行命令返回
fatal: not a git repository (or any of the parent directories): .git

**Comment by rTnrWE** [comment]
等作者大佬修复吧，我昨天已经把之前的容器和数据都清空，重新安装了，面板进不去没办法重新添加任务

**Comment by zhudan** [comment]
> fatal: not a git repository (or any of the parent directories): .git

容器里边儿执行，容器在重启过程中有时间窗口可以登录进去执行的

**Comment by ukhack** [comment]
附议。建议tag保留几个版本，每次都是last和pre，像今天这种情况，last是坏掉的
[PM2][WARN] panel doesn't exist
Use --update-env to update environment variables
[PM2][ERROR] Process or Namespace panel not found
但是pre也是坏掉的
/ql/shell/share.sh: line 273: pip3: command not found
这俩都不能用
![C58F8D09701F6FDA228E109372DA20D8](https://user-images.githubusercontent.com/17568491/141405517-e97facba-c3a5-4d9f-b19e-8d916b96209d.png)

**Comment by ggfvictor** [comment]
> 容器里边儿执行，容器在重启过程中有时间窗口可以登录进去执行的

作者您好，容器内执行过 还是没办法用 进不去面板

**Comment by xyskwjy** [comment]
> 附议。建议tag保留几个版本，每次都是last和pre，像今天这种情况，last是坏掉的 [PM2][WARN] panel doesn't exist Use --update-env to update environment variables [PM2][ERROR] Process or Namespace panel not found 但是pre也是坏掉的 /ql/shell/share.sh: line 273: pip3: command not found 这俩都不能用 ![C58F8D09701F6FDA228E109372DA20D8](https://user-images.githubusercontent.com/17568491/141405517-e97facba-c3a5-4d9f-b19e-8d916b96209d.png)

你这pre是没有依赖，重装依赖

**Comment by ccquan** [comment]
> > 附议。建议tag保留几个版本，每次都是last和pre，像今天这种情况，last是坏掉的 [PM2][WARN] panel doesn't exist Use --update-env to update environment variables [PM2][ERROR] Process or Namespace panel not found 但是pre也是坏掉的 /ql/shell/share.sh: line 273: pip3: command not found 这俩都不能用 ![C58F8D09701F6FDA228E109372DA20D8](https://user-images.githubusercontent.com/17568491/141405517-e97facba-c3a5-4d9f-b19e-8d916b96209d.png)
> 
> 你这pre是没有依赖，重装依赖

dalao，请问怎么装？
搞了一上午，我试了apk add装了Python，但装不了pip，不知道是哪个包名

**Comment by whyour** [comment]
@ccquan py3-pip

**Comment by hong0980** [comment]
最好用还是2.9.7

**Comment by Se7enMuting** [comment]
备份在此：
[hushunxu/qinglong_base](https://registry.hub.docker.com/r/hushunxu/qinglong_base/tags)

**Comment by fzls** [comment]
已提pr解决，以后的所有版本均会保留
