### ISSUE TITLE
最新版还是有问题

### ISSUE THREAD

**Issue by zhudan** [whyour/qinglong#877]
![image](https://user-images.githubusercontent.com/1744697/141415779-4b82293a-6753-4029-81a1-b6a7b57c4765.png)

**Comment by ggfvictor** [comment]
+1还是有问题 面板还是进不去

**Comment by zhudan** [comment]
搞定了， touch /ql/db/app.db &&  pm2 restart all

**Comment by hongyunfei** [comment]
> 搞定了，touch /ql/db/app.db && pm2 restart all

大佬牛逼，面板进不去按照你的命令修复了。

**Comment by lancer-wang** [comment]
> 搞定了， touch /ql/db/app.db && pm2 restart all

![image](https://user-images.githubusercontent.com/69783837/141423797-904affe6-6b42-404d-adf0-3a2d0be4cb12.png)
我的为什么还是进不去
