### ISSUE TITLE
最新版依然打不开

### ISSUE THREAD

**Issue by lancer-wang** [whyour/qinglong#879]
一直都是这个
![image](https://user-images.githubusercontent.com/69783837/141429017-70850120-28a9-401c-a3cf-6d9e197ab73b.png)

**Comment by NuadaHu** [comment]
api/system这个接口报错了

**Comment by lancer-wang** [comment]
> api/system

怎么搞啊?这个

**Comment by hongyunfei** [comment]
> > 接口/系统
> 
> 怎么搞啊？

touch /ql/db/app.db && pm2 restart all

**Comment by lancer-wang** [comment]
> > > 接口/系统
> > 
> > 
> > 怎么搞啊？
> 
> touch /ql/db/app.db && pm2 restart all

![image](https://user-images.githubusercontent.com/69783837/141431420-d986bfa7-4386-423a-9094-72d6fca15644.png)

还是打不开

**Comment by lancer-wang** [comment]
> api/system这个接口报错了

![image](https://user-images.githubusercontent.com/69783837/141431938-a9ea44d3-b1a0-489b-9cce-6ee6d776c799.png)
不过确实是这个报错

**Comment by lancer-wang** [comment]
建议使用 最后一行改用,yanyuwangluo/qinglong:2.9.5
实测备份版可用
