### ISSUE TITLE
想要屏蔽某个账号不玩某些小游戏,case命令失效，无法使用。

### ISSUE THREAD

**Issue by ycyfff** [whyour/qinglong#88]
case $1 in
  chinnkarahoi_jd_jxnc)
    TempBlockCookie="1 2"  #京喜农场
    ;;
  chinnkarahoi_jd_pet)
    TempBlockCookie="1"  #东东萌宠
    ;;
  chinnkarahoi_jd_dreamFactory)
    TempBlockCookie="1 2"  #京喜工厂
    ;;
  chinnkarahoi_jx_cfdtx)
    TempBlockCookie="1 2 3"  #财富岛提现
    ;;
  chinnkarahoi_jd_try)
    TempBlockCookie="1 2"  #京东试用
    ;;
  ZCY01_jd_try)
    TempBlockCookie="7 8"  #京东试用
    ;;
esac

**Comment by whyour** [comment]
#74 相同问题
