### ISSUE TITLE
升级后无法登录后台，一直提示：服务异常，请执行 ql check检查服务状态

### ISSUE THREAD

**Issue by borpubi** [whyour/qinglong#882]
升级后无法登录后台，一直提示：服务异常，请执行 ql check检查服务状态。
然而执行ql check也无法正常登录，还是报同样的错误。
环境：群晖Docker
版本：
2.10.0-->2.10.1-->2.10.2都是自动升级，后台偶尔有报错，但基本运行ql check后可以正常登录。
2.10.2-->2.10.3后无法正常登录，多次运行ql check 仍报错，重启后循环重启。
2.10.3-->2.10.4后无法正常登录，多次运行ql check 仍报错，重置Docker也无法登录，删除文件后拉最新版仍旧报错。
2.10.4-->2.10.5后无法正常登录，多次运行ql check 仍报错，重置Docker也无法登录，删除文件后拉最新版仍旧报错。
报错信息如下 ：
![image](https://user-images.githubusercontent.com/28093885/141429153-f1a3ffef-af2a-41e3-9f41-47ffc33efd6c.png)

ql check 执行结果如下:
[log.log](https://github.com/whyour/qinglong/files/7525802/log.log)

**Comment by hongyunfei** [comment]
touch /ql/db/app.db && pm2 restart all

**Comment by Yue-xin97** [comment]
> 
> 
> touch /ql/db/app.db && pm2 restart all

我也是这个问题，使用这个命令后没有效果

**Comment by hongyunfei** [comment]
> > touch /ql/db/app.db && pm2 restart all
> 
> 我也是这个问题，使用这个命令后没有效果

我用这个命令后顺利登录面板

**Comment by borpubi** [comment]
> 
> 
> touch /ql/db/app.db && pm2 restart all

![image](https://user-images.githubusercontent.com/28093885/141432844-7704e2be-7ad8-4fa3-b2a8-323de8c07780.png)
![image](https://user-images.githubusercontent.com/28093885/141432855-a40f97a8-10e3-4aea-a8d2-88f0b4a15001.png)
没有效果,除了在DB目录中创建了一个APP.DB文件以外.

**Comment by borpubi** [comment]
对了,上面的那个log.log文件里面不全.实际执行ql check 的时候,还会有这几行结果显示:
`
root@qinglong:/ql $ ql check                                                           
/ql/shell/share.sh: line 170: syntax error near unexpected token `<<<'                 
/ql/shell/share.sh: line 170: `<<<<<<< HEAD'                                           
/ql/shell/share.sh: line 170: syntax error near unexpected token `<<<'                 
/ql/shell/share.sh: line 170: `<<<<<<< HEAD'                                           
/ql/shell/check.sh: line 9: fix_config: command not found                              
/ql/shell/check.sh: line 14: npm_install_2: command not found                          
/ql/shell/check.sh: line 20: npm_install_2: command not found     `

**Comment by Muceball** [comment]
@borpubi @hongyunfei @Yue-xin97 @yaming116 进入容器内 执行ql update就可以了

**Comment by borpubi** [comment]
> ql update

更惨……
![image](https://user-images.githubusercontent.com/28093885/141438975-06320958-09ee-411f-9e66-324b94715034.png)
![image](https://user-images.githubusercontent.com/28093885/141439046-b7085cd3-c1c6-42e2-934b-66af4ec78f33.png)

**Comment by Muceball** [comment]
> > ql更新
> 
> 还是一样。 ![图片](https://user-images.githubusercontent.com/28093885/141438975-06320958-09ee-411f-9e66-324b94715034.png) ![图片](https://user-images.githubusercontent.com/28093885/141443968-6b48d7cf-5915-4df6-bc4e-ccf323266c9f.png)

额。。不是2.10.5么。我升级后就是2.10.5了。。不过升级后也没有什么卵用。。脚本没有一个可以用的。我已经回退了。。哎~
用这个镜像把docker pull whyour/qinglong:pre，貌似python环境有点小问题。。真的是无语的很
找到这两个命令，可以安装pip3 和pip 但是有些东西还是搞不定。。。
apk add py3-pip
pip3 install pip

**Comment by PineappleBeer** [comment]
我进控制台依次执行了
``
ql check
``
``
touch /ql/db/app.db && pm2 restart all
``
``
ql update
``
然后就可以进去了，仅供参考。

**Comment by borpubi** [comment]
我重新建了docker,好了.
