### ISSUE TITLE
建议把 tag 打开，能让使用者回退到某个正常版本

### ISSUE THREAD

**Issue by BillScott1024** [whyour/qinglong#884]
建议把 tag 打开，能让使用者遇到错误能够回退到某个正常版本，而不至于崩溃，现在只能用别人备份的2.10.2 版本
，感觉不太安全

![image](https://user-images.githubusercontent.com/22955480/141433403-89352f1f-144b-467f-9deb-0e1ce67aa9d2.png)

**Comment by Se7enMuting** [comment]
特意不开的吧。。。

**Comment by maryjeck** [comment]
我要到是能用了。但那个升级命令又没了，停在2.10.4了

**Comment by hongyunfei** [comment]
> 我要到是能用了。但那个升级命令又没了，停在2.10.4了

看看你的定时任务正常不，我的定时全部失效了

**Comment by rTnrWE** [comment]
最新版还是不能用，用别人备份的镜像，心里没底，强烈建议留几个旧的稳定版

**Comment by yduis6554** [comment]
> 最新版还是不能用，用别人备份的镜像，心里没底，强烈建议留几个旧的稳定版

不是有么，下面那个pre不就是旧版么？2.10 我拉了试了。

**Comment by BillScott1024** [comment]
> > 最新版还是不能用，用别人备份的镜像，心里没底，强烈建议留几个旧的稳定版
> 
> 不是有么，下面那个pre不就是旧版么？2.10 我拉了试了。

想用 2.10.2 的，这个版本比较稳定。。我现在是用了别人备份的镜像

**Comment by witnessus** [comment]
刚刚又更新了一下，依然是崩溃的。建议作者先回退昨晚的版本吧
