### ISSUE TITLE
建议 dockers 镜像先回退到昨天的版本

### ISSUE THREAD

**Issue by witnessus** [whyour/qinglong#889]
Fedora x64 版本。依然不行。报错如下：
`======================4. 启动控制面板========================

[PM2][WARN] panel doesn't exist
Use --update-env to update environment variables
[PM2][ERROR] Process or Namespace panel not found`

**Comment by fzls** [comment]
试试最新版本，这个是因为之前版本/etc/nginx/conf.d目录不存在而导致的
