### ISSUE TITLE
sendNotify.js位置问题

### ISSUE THREAD

**Issue by huasuifengqu** [whyour/qinglong#891]
sendNotify.js和拉取的库里的脚本不在一起导致一些脚本报错，只能手动复制过去

**Comment by fzls** [comment]
看青龙2.10.4的更新日志的其他说明第一条

>  其他说明
>  以前的repo命令需要其他依赖文件的，需要自己改ql repo后面的依赖参数，加上`jdCookie.js|sendNotify.js`或者其他文件

**Comment by huasuifengqu** [comment]
> 看青龙2.10.4的更新日志的其他说明第一条
> 
> > 其他说明
> > 以前的repo命令需要其他依赖文件的，需要自己改ql repo后面的依赖参数，加上`jdCookie.js|sendNotify.js`或者其他文件

谢谢了
