### ISSUE TITLE
好奇怪，一直提示node:internal/modles/cjs/loader:936

### ISSUE THREAD

**Issue by tboyre** [whyour/qinglong#896]
node:internal/modles/cjs/loader:936
throw err

error:cannot find module './sendnotify'
后面还有一堆报错…
环境是群晖，依赖都装了

**Comment by MK-D-Luffy** [comment]
咋整呀，我也

**Comment by whyour** [comment]
@MK-D-Luffy repo命令依赖那里加上sendNotify

**Comment by MK-D-Luffy** [comment]
> @MK-D-Luffy repo命令依赖自己外加sendNotify

在安装脚本的时候吗？

**Comment by whyour** [comment]
@MK-D-Luffy ql repo xxx xxx xxx "加上 sendNotify.js"

**Comment by wz-dazhi** [comment]
@whyour  大佬, 这个命令ql repo xxx xxx xxx "加上 sendNotify.js"   xxx 是具体的地址吗? 还是什么? 不会用呐

**Comment by tboyre** [comment]
我是用faker维护的库，讲一下我是怎么解决的，重新删docker后，删除所有映射文件里面的内容，下载最后版本的青龙，重新映射，然后去faker的tg群，重新找新的拉脚本的命令，拉下来就行了…
遇到这种问题，大概率是因为用了网上的老的拉库命令，更新一下就行了…此帖终结…

**Comment by tboyre** [comment]
> @MK-D-Luffy repo命令依赖那里加上sendNotify

有幸遇到大佬…膜拜大佬先…

**Comment by shadowby** [comment]
> 我是用faker维护的库，讲一下我是怎么解决的，重新删docker后，删除所有映射文件里面的内容，下载最后版本的青龙，重新映射，然后去faker的tg群，重新找新的拉脚本的命令，拉下来就行了… 遇到这种问题，大概率是因为用了网上的老的拉库命令，更新一下就行了…此帖终结…

大佬客服将faker库新拉库命令在这里贴一下,我几乎所有脚本都报这个错,处于瘫痪状态

**Comment by yanhao98** [comment]
> > 我是用faker维护的库，讲一下我是怎么解决的，重新删docker后，删除所有映射文件里面的内容，下载最后版本的青龙，重新映射，然后去faker的tg群，重新找新的拉脚本的命令，拉下来就行了… 遇到这种问题，大概率是因为用了网上的老的拉库命令，更新一下就行了…此帖终结…
> 
> 大佬客服将faker库新拉库命令在这里贴一下,我几乎所有脚本都报这个错,处于瘫痪状态

`ql repo https://ghproxy.com/https://github.com/shufflewzc/faker2.git "jd_|jx_|gua_|jddj_|getJDCookie" "activity|backUp" "^jd[^_]|USER|ZooFaker_Necklace.js|JDJRValidator_Pure|sign_graphics_validate|sendNotify|ql"`

**Comment by yanhao98** [comment]
> > @MK-D-Luffy repo命令依赖那里加上sendNotify
> 
> 有幸遇到大佬…膜拜大佬先…

```
ql repo https://ghproxy.com/https://github.com/shufflewzc/faker2.git "jd_|jx_|gua_|jddj_|getJDCookie" "activity|backUp" "^jd[^_]|USER|ZooFaker_Necklace.js|JDJRValidator_Pure|sign_graphics_validate|sendNotify|ql"
```

**Comment by wz-dazhi** [comment]
把sendNotify.js 放到 ql/scripts/asd920_Auto-jd  这个目录下就好了. 青龙更新后所有的js都放到对应的仓库目录下了

**Comment by Cold5721** [comment]
ql repo https://********************git "jd_|jx_|gua_|jddj_|getJDCookie" "activity|backUp" "^jd[^_]|USER|function|utils|sendNotify|ZooFaker_Necklace.js|JDJRValidator_|sign_graphics_validate|ql"


这样就好了.兄弟们

**Comment by EchoChan314** [comment]
> @MK-D-Luffy ql repo xxx xxx xxx "加上 sendNotify.js"

有些库本身是没有sendNotify，比如https://github.com/Aaron-lv/JavaScript.git，这种情况下要怎么配置？我已经新建/ql/deps并放置了sendNotify、jdCookie.js等文件，并没有自动复制到Aaron-lv/JavaScript这个库的文件夹下。10.7版本。

**Comment by whyour** [comment]
> > @MK-D-Luffy ql repo xxx xxx xxx "加上 sendNotify.js"
> 
> 有些库本身是没有sendNotify，比如https://github.com/Aaron-lv/JavaScript.git ，这种情况下要怎么配置？我已经新建/ql/deps并放置了sendNotify、jdCookie.js等文件，并没有自动复制到Aaron-lv/JavaScript这个库的文件夹下。10.7版本。

ql update下。再执行 ql repo

**Comment by lysk** [comment]
> 我是用faker维护的库，讲一下我是怎么解决的，重新删docker后，删除所有映射文件里面的内容，下载最后版本的青龙，重新映射，然后去faker的tg群，重新找新的拉脚本的命令，拉下来就行了… 遇到这种问题，大概率是因为用了网上的老的拉库命令，更新一下就行了…此帖终结…

问下 faker的tg群是多少呢
