### ISSUE TITLE
ql repo 的各个参数好像已经没用了；新面板二级文件夹下保存和删除功能有问题

### ISSUE THREAD

**Issue by requireCool** [whyour/qinglong#901]
1. 现在不管怎么填参数，都会把repo里所有文件都复制到scripts对应的文件夹里去，导致/ql/repo和/ql/scripts两个目录的内容其实没区别，特别是`ql repo`参数中需要屏蔽的脚本一样会被拉到scripts里去

2. 脚本管理中删除二级文件夹下的脚本报错ENOENT: no such file or directory, unlink '/ql/scripts/***-notify.py'
不止删除功能，修改二级文件夹下的文件后点击保存，虽然提示保存成功，但是刷新一下文件又变成以前的了。感觉这两个问题应该是操作路径里的"/"打成了"-"造成的

**Comment by mjyhj** [comment]
不知道是不是修复了，我的/ql/repo和/ql/scripts文件夹内容是正确的。
/ql/scripts里只有自己需要拉的脚本，/ql/repo里是整个仓的文件
