### ISSUE TITLE
2.10.7 脚本管理中编辑脚本后保存的文件名错误

### ISSUE THREAD

**Issue by Shark-Lucas** [whyour/qinglong#908]
2.10.7版本，脚本管理中编辑拉取的库中的脚本，点击保存后，文件命名还是按之前的方式，会添加库的名字为前缀，但目前版本脚本文件是在以库的名字命名的文件夹中，文件名不需要添加库名前缀
![QQ截图20211114211145](https://user-images.githubusercontent.com/38132162/141682474-00d9b35f-a4fa-4c6e-9243-2b5a76dbf7cd.png)

**Comment by kan3Git** [comment]
我也遇到同样的问题

**Comment by magickzl** [comment]
同样的问题，这有办法解决吗

**Comment by StarLevi** [comment]
> 同样的问题，这有办法解决吗

暂时使用别的工具编辑吧，vim或者宝塔面板文件管理
