### ISSUE TITLE
2.10.7版本系统设置pushplus

### ISSUE THREAD

**Issue by Muceball** [whyour/qinglong#912]
pushplus就一直提示“通知发送失败，请检查参数”，一直用的这个token，不可能有问题
![image](https://user-images.githubusercontent.com/51481074/141731091-0629fd4c-7160-454f-a9d2-ea6af4db8673.png)

**Comment by whyour** [comment]
pushplus.plus 注意是不是同一网站

**Comment by Muceball** [comment]
@whyour http://www.pushplus.plus/确认就是这个网址。我刚复现这个问题了，同一个token，前面几次通过的，点了几次后不通过了，估计是pushplus限流了。。建议作者弄个提示，点确认后直接保存token吧。
