### ISSUE TITLE
2.10.7脚本管理

### ISSUE THREAD

**Issue by Muceball** [whyour/qinglong#915]
1.修改脚本有bug，点击保存后会生成一个上级目录-文件名的新文件。例如修改my目录下的abc.js文件，点击保存后新加了一个名为my-abc.js的文件。

2.新建文件没法选中的目录中新建（加个类似mv的操作也行）。

**Comment by zubeeee** [comment]
+10086 这2个bug确实难受 不能编辑脚本了

**Comment by magickzl** [comment]
同样的问题，现在导致完全不能使用了，之前好好的，重装下就成这样了。
