### ISSUE TITLE
消息黑名单设置

### ISSUE THREAD

**Issue by pengtoo** [whyour/qinglong#917]
首先感谢大佬开发的工具真的很好用，部署后用pushplus一段时间了，每天可以收到很多消息，试着在原始脚本里面更改，可是脚本太多无法一一完成修改消息通知，面板中是否有地方可以直接更改设置消息黑名单呢？

**Comment by fzls** [comment]
可以以 互助研究院 的这个config.sh 模板为基准，里面基本有各种配置
> https://t.me/update_help/43?single

其中屏蔽通知的是这个
```shell
 # Ninja 环境变量
## 1、通知黑名单
### 使用 & 分隔，例如 东东乐园&东东萌宠
export NOTIFY_SKIP_LIST
```

**Comment by pengtoo** [comment]
已经设置过了 还是没有生效 ，是不是要重启下容器呢？
