### ISSUE TITLE
脚本管理-里面的脚本展开能否按照名称字母顺序排序?虽然

### ISSUE THREAD

**Issue by aTenb** [whyour/qinglong#919]
脚本管理-里面的脚本展开能否按照名称字母顺序排序?虽然现在脚本按照库文件夹分类了,但是打开文件夹,里面的脚本还是乱序的,给人很乱的感觉,不便于直接找脚本(虽然可以搜索),按字母顺序排序好会更方便试用.

当然这个只是优化的建议,大佬有时间可以搞一下吧 希望

**Comment by shadowby** [comment]
的确建议排个序
