### ISSUE TITLE
canvas依赖安装失败，下载的文件不存在！

### ISSUE THREAD

**Issue by aliyy2021** [whyour/qinglong#926]
龙大，你好！
   canvas依赖安装失败，看了日志显示下载文件错误，看了官方库里也没有这个版本的文件。

![image](https://user-images.githubusercontent.com/77948441/142205582-c5422481-4e6c-41f0-8a91-ec59015565a3.png)
![image](https://user-images.githubusercontent.com/77948441/142205761-8607fa0b-91b7-4e84-a432-b30414ef3784.png)

**Comment by naiveclub** [comment]
同这个问题，现在解决了吗？

**Comment by aliyy2021** [comment]
> 同这个问题，现在解决了吗？

没有，

**Comment by aliyy2021** [comment]
> 同这个问题，现在解决了吗？

这个要装在PYTHON3哪里才可以

**Comment by SekiBetu** [comment]
> > 同这个问题，现在解决了吗？
> 
> 这个要装在PYTHON3哪里才可以

青龙的docker采用的精简版linux，需要安装编译依赖
```shell
apk add build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev
```

**Comment by HorrZzz** [comment]
同样的问题

**Comment by FairyWorld** [comment]
> ```shell
> build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev
> ```

装了这几个还是安装canvas失败了

**Comment by FairyWorld** [comment]
最新版本泽呢么都装不上node-canvas

**Comment by FairyWorld** [comment]
最新版本怎么都装不上node-canvas

**Comment by 2604237845** [comment]
> > > 同这个问题，现在解决了吗？
> > 
> > 
> > 这个要装在PYTHON3哪里才可以
> 
> 青龙的docker采用的镜像为alpine linux，所以安装canvas前需要安装相关的编译依赖
> 
> ```shell
> apk add build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev
> ```
> 
> ![image](https://user-images.githubusercontent.com/38283893/175983105-1abe6513-993f-4eeb-a570-0ef34c260cf9.png) ![image](https://user-images.githubusercontent.com/38283893/175983153-0c903b7c-b56a-4d12-81e8-809db08acc40.png)

感谢大佬的方法，已解决！！！
