### ISSUE TITLE
deps为什么不直接作为公关依赖？

### ISSUE THREAD

**Issue by mjyhj** [whyour/qinglong#927]
特意放在这里，然后还要复制到各个2级目录去。
造成多次重复读写，还有多份相同文件。
既然这样的话，为什么不直接写死加载deps目录作为各个仓的公共依赖

**Comment by aTenb** [comment]
+10086 感觉现在每个仓都有依赖 很烦 deps作为公共依赖 这样大家仓库只用写脚本就行

**Comment by fzls** [comment]
> +10086 感觉现在每个仓都有依赖 很烦 deps作为公共依赖 这样大家仓库只用写脚本就行

因为那样需要各个仓库去协调这件事吧<_<

**Comment by aTenb** [comment]
> 

依赖文件和脚本文件确实放在一个文件夹里很乱,青龙确实可以引导脚本作者去规范,青龙做了硬性要求,作者回去适应的
