### ISSUE TITLE
请问哪里有openapi的文档？

### ISSUE THREAD

**Issue by taotao2010** [whyour/qinglong#931]
如题，找了半天没有发现openapi的相关文档，请问文档在哪里呢？

**Comment by Ubugs** [comment]
建议浏览器f12自己抓包

**Comment by fzls** [comment]
> 如题，找了半天没有发现openapi的相关文档，请问文档在哪里呢？

看源码，自己搜对应接口吧，代码还是挺清晰的
> https://github.com/whyour/qinglong/blob/develop/back/api/index.ts
