### ISSUE TITLE
拉库的时候是否可以设置只更新已有脚本而不是拉取所有脚本?

### ISSUE THREAD

**Issue by aTenb** [whyour/qinglong#932]
不是主库的,删除了大部分重复的脚本.再次更新的时候 又把删了的拉回来了

**Comment by xuexijiaoben** [comment]
兄弟，脚本怎么拉取呀，求指点一下，我是面板和ninjia都布署好了，n1 openwrt建的容器，进面板里没有脚本，非常感谢
