### ISSUE TITLE
为什么收不到每天汇总的通知？

### ISSUE THREAD

**Issue by felixb018** [whyour/qinglong#938]
是不是应该执行任务之后，每天会发一个通知到设置好的消息通道里？我怎么从来没收到过，系统设置时的测试消息是能收到的，是在哪里漏了一步吗？该怎么做呢？小白请教，谢谢！

**Comment by tinpont** [comment]
在qinglong界面设置之后，还需要改一下config.sh配置文件里面的参数。这两个地方不是做同一个事情的
