### ISSUE TITLE
无法自动删除日志

### ISSUE THREAD

**Issue by yuxuan0107** [whyour/qinglong#940]
面板设置的日志删除是两天,但是部分脚本的日志从创建到目前一直都有存在,请问如何解决,另外有无手动清空日志或者手动批量清空日志功能?

**Comment by bake1490** [comment]
添加定时任务
ql rmlog <days>

**Comment by wonderhong** [comment]
> 添加定时任务 ql rmlog 3

只能用定时任务删吗，面板自带的删除日志功能为什么不起作用呀😂
