### ISSUE TITLE
青龙端口到底是5600 还是 5700

### ISSUE THREAD

**Issue by YYJavaGit** [whyour/qinglong#947]
![image](https://user-images.githubusercontent.com/50813117/142984930-d654c09d-2faf-4c9e-9e72-5a682fedadc1.png)
![image](https://user-images.githubusercontent.com/50813117/142984955-bd8ee298-9a1b-4db6-898a-3beb73f54ba4.png)

    image: whyour/qinglong:latest
    ports:
      - 5600:5600
 这样能进去

**Comment by citytc** [comment]
现在是5600  以前是5700

**Comment by xzw38** [comment]
还好看到了，刚刚再试怎么都进不去面板，把docker run里面的5700改成5600竟然就进去了。。

**Comment by kwy-hu** [comment]
偶也是搞一天才发现
