### ISSUE TITLE
nginx: [emerg] open() "/run/nginx/nginx.pid" failed (2: No such file or directory) 请问这个报错是什么原因？

### ISSUE THREAD

**Issue by Spheniscidaer** [whyour/qinglong#949]
好像也不影响使用。面板也正常，版本2.10.9改了端口5600
<img width="529" alt="image" src="https://user-images.githubusercontent.com/18514810/143230063-002be5d8-d2fb-4308-88f0-100deb02ebfe.png">
<img width="432" alt="image" src="https://user-images.githubusercontent.com/18514810/143230113-405d353c-ff4a-4b24-b0c3-940a42c677c5.png">
<img width="721" alt="image" src="https://user-images.githubusercontent.com/18514810/143230172-d14252ae-2a82-456b-97d6-de6262559aa6.png">

**Comment by Spheniscidaer** [comment]
感觉2.10.9的镜像有问题似的。先安装2.10.8，再升级到2.10.9没问题。直接docker-compose部署2.10.9就这个报错
<img width="546" alt="image" src="https://user-images.githubusercontent.com/18514810/143232623-dc26fe42-de56-4c68-8798-ac05884582ed.png">
直接部署2.10.9后使用ql check好像也有点问题，每次使用都会重新安装依赖
<img width="650" alt="image" src="https://user-images.githubusercontent.com/18514810/143232927-4bb3824e-7907-43b7-87bf-e9ce1d7227f5.png">

这是我的docker-compose.yml文件
<img width="381" alt="image" src="https://user-images.githubusercontent.com/18514810/143233035-4efa4e95-9a68-4fe3-88c1-261d060771c5.png">

**Comment by Spheniscidaer** [comment]
是2.10.9改了这个5600端口的问题？
<img width="723" alt="image" src="https://user-images.githubusercontent.com/18514810/143234477-25025a15-b35c-4b66-9a9d-84c6113b2d54.png">

**Comment by thy486** [comment]
```
少创建了一个文件夹啊，昨天就修复了
```

**Comment by Spheniscidaer** [comment]
> 少创建了一个文件夹啊，昨天就修复了

没明白。最新版本不就是2.10.9么？

**Comment by gankyui** [comment]
土办法,手动touch一个nginx.pid文件
1. docker exiec -it qinglong bash
2. mkdir /run/nginx/ && !$
3. touch nginx.pid 
4. exit
5. docker restart qinglong

**Comment by gankyui** [comment]
> 
土办法,手动touch一个nginx.pid文件

docker exec -it qinglong bash
mkdir /run/nginx/ && !$
touch nginx.pid
exit
docker restart qinglong

**Comment by Spheniscidaer** [comment]
> 土办法,手动touch一个nginx.pid文件
> 
> docker exec -it qinglong bash mkdir /run/nginx/ && !$ touch nginx.pid exit docker restart qinglong

谢谢dalao
