### ISSUE TITLE
不管怎么更新都只有4个脚本!

### ISSUE THREAD

**Issue by shiyanzhizhuo** [whyour/qinglong#95]
[不管怎么更新都只有4个脚本!
![1](https://user-images.githubusercontent.com/48113345/117901205-6f608a80-b2fd-11eb-900c-4144b3cda6b8.png)
![2](https://user-images.githubusercontent.com/48113345/117901208-7091b780-b2fd-11eb-9d74-95361b6a89c2.png)

**Comment by syfirefox** [comment]
2.0新版已经不内置脚本 都是靠自定义命令拉取

**Comment by woboo110** [comment]
自己拉取仓库啊

**Comment by shiyanzhizhuo** [comment]
> 自己拉取仓库啊

小白不懂,具体咋搞?

**Comment by whyour** [comment]
> > 自己拉取仓库啊
> 
> 小白不懂,具体咋搞?

看频道通知

https://t.me/qiongqiya/79
https://t.me/qiongqiya/80
