### ISSUE TITLE
请教一下大佬 用树莓派的docker部署的  用树莓派IP:5700访问不了青龙面板

### ISSUE THREAD

**Issue by wang2879644** [whyour/qinglong#950]
'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'

检测到默认nginx配置文件，清空...

======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'

======================2. 安装依赖========================

检测到 /ql/scripts 的依赖包有变化，运行 npm install...

   ╭──────────────────────────────────────────────────────────────────╮

   │                                                                  │

   │                Update available! 6.22.2 → 6.23.2.                │

   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v6.23.2   │

   │                 Run pnpm add -g pnpm to update.                  │

   │                                                                  │

   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │

   │                                                                  │

   ╰──────────────────────────────────────────────────────────────────╯

Progress: resolved 1, reused 0, downloaded 0, added 0

 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

Progress: resolved 17, reused 0, downloaded 0, added 0

Progress: resolved 32, reused 0, downloaded 12, added 0

Progress: resolved 64, reused 0, downloaded 41, added 0

Progress: resolved 86, reused 0, downloaded 60, added 0

Progress: resolved 122, reused 0, downloaded 98, added 0

Progress: resolved 147, reused 0, downloaded 114, added 0

Progress: resolved 164, reused 0, downloaded 135, added 0

Progress: resolved 179, reused 0, downloaded 147, added 0

Progress: resolved 199, reused 0, downloaded 165, added 0

Packages: +211

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Progress: resolved 211, reused 0, downloaded 184, added 0

Packages are hard linked from the content-addressable store to the virtual store.

  Content-addressable store is at: /root/.pnpm-store/v3

  Virtual store is at:             node_modules/.pnpm

Progress: resolved 211, reused 0, downloaded 208, added 46

Progress: resolved 211, reused 0, downloaded 211, added 211, done

dependencies:

+ crypto-js 4.1.1

+ download 8.0.0
      
+ got 11.8.3

+ http-server 0.12.3 (14.0.0 is available)

+ qrcode-terminal 0.12.0

+ request 2.88.2 deprecated

+ tough-cookie 4.0.0

+ tunnel 0.0.6

+ ws 7.5.6 (8.3.0 is available)

======================3. 启动nginx========================

nginx: [emerg] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)

nginx启动成功...

======================4. 启动控制面板========================

[PM2] Starting /ql/build/app.js in fork_mode (1 instance)

[PM2] Done.

┌─────┬──────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐

│ id  │ name     │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │

├─────┼──────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤

│ 0   │ panel    │ default     │ N/A     │ fork    │ 105      │ 0s     │ 0    │ online    │ 0%       │ 33.3mb   │ root     │ disabled │

└─────┴──────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

控制面板启动成功...

======================5. 启动定时任务========================

[PM2] Starting /ql/build/schedule.js in fork_mode (1 instance)

[PM2] Done.

┌─────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐

│ id  │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │

├─────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤

│ 0   │ panel       │ default     │ N/A     │ fork    │ 105      │ 3s     │ 0    │ online    │ 128.6%   │ 61.5mb   │ root     │ disabled │

│ 1   │ schedule    │ default     │ N/A     │ fork    │ 144      │ 0s     │ 0    │ online    │ 0%       │ 21.9mb   │ root     │ disabled │

└─────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

定时任务启动成功...

======================7. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...

请先访问5700端口，登录成功面板之后再执行添加定时任务...

############################################################

**Comment by snakeJohn** [comment]
楼主解决了吗？我也遇到了

**Comment by wang2879644** [comment]
> 楼主解决了吗？我也遇到过

解决了 把青龙面板的容器网络改成host  然后树莓派IP:5600

**Comment by particlewong** [comment]
2.10.9无法访问面板临时解决办法:
容器内执行命令
mkdir -p /run/nginx
nginx -c /etc/nginx/nginx.conf

https://comments.app/view/gdJHL3oV/5445

**Comment by snakeJohn** [comment]
> > 楼主解决了吗？我也遇到过
> 
> 解决了 把青龙面板的容器网络改成host 然后树莓派IP:5600

我也解决了
