### ISSUE TITLE
反馈一下2.10.9 问题

### ISSUE THREAD

**Issue by underlaw** [whyour/qinglong#951]
一是端口从5700，用ｑｌ　ｃｈｅｃｋ变到了5600，安装了几次5600商品有时能启用，有时不行。安装依赖实际没安上，显示安上了

后来用了，ｌｓｓｕｅｓ里好心人的办法，才解决
2.10.9无法访问面板临时解决办法:
容器内执行命令
mkdir -p /run/nginx
nginx -c /etc/nginx/nginx.conf

**Comment by aTenb** [comment]
2.10.9安装不了依赖 多个依赖报错 退回2.10.8了
