### ISSUE TITLE
docker run后无法访问5700端口

### ISSUE THREAD

**Issue by AndyZhuAZ** [whyour/qinglong#955]
使用readme里的命令运行，宿主机的端口也开了，防火墙也没问题，开在80端口上的其他东西也是正常的，青龙安装后连宿主机都curl 127.0.0.1:5700失败:curl: (56) Recv failure: Connection reset by peer。
```
docker run -dit \
  -v $PWD/ql/config:/ql/config \
  -v $PWD/ql/log:/ql/log \
  -v $PWD/ql/db:/ql/db \
  -v $PWD/ql/repo:/ql/repo \
  -v $PWD/ql/raw:/ql/raw \
  -v $PWD/ql/scripts:/ql/scripts \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:latest

```
<img width="1061" alt="截屏2021-11-26 下午8 48 19" src="https://user-images.githubusercontent.com/24852023/143583429-0dfa800e-6ca4-43c8-be94-6226b384ba88.png">

**Comment by ligusx** [comment]
一样，升级后就打不开了

**Comment by ningtt** [comment]
我大概找到了问题，是因为 镜像内的nginx服务没有启动， 等待up主修复吧
![image](https://user-images.githubusercontent.com/61641974/143606130-d02c7d38-1779-4a85-a701-5aad1590d7a7.png)

**Comment by jokerping** [comment]
我也是，折腾一晚上，一直怀疑自己服务。看日志才发现

docker exec -it qinglong bash

mkdir -p /run/nginx
nginx -c /etc/nginx/nginx.conf

临时解决办法

**Comment by lloveyoutjq** [comment]
5600好像能正常访问
