### ISSUE TITLE
面板没法访问 接口提示：event rejected due to rate limit

### ISSUE THREAD

**Issue by yikus-tjq** [whyour/qinglong#957]
访问的是这个接口 https://o1051273.ingest.sentry.io/api/6047851/envelope/?sentry_key=ea2fede373244db99c536210b910d9da&sentry_version=7
会提示这个 event rejected due to rate limit’
页面是空白的

**Comment by 21ki** [comment]
我也想知道这个是什么问题
mark

**Comment by 21ki** [comment]
弱弱的问一下这个https://o1051273.ingest.sentry.io/api/6047851/envelope/?sentry_key=ea2fede373244db99c536210b910d9da&sentry_version=7作什么用的

**Comment by huagegege** [comment]
同样的问题，mark

**Comment by limubai1223** [comment]
问题解决了吗

**Comment by huagegege** [comment]
> 问题解决了吗

据说是解决了，更新下版本吧

**Comment by lloveyoutjq** [comment]
> 问题解决了吗

我换了个低版本就好了，但是定时任务一多 就会把服务器卡死

**Comment by HelperInCa** [comment]
v2.10.2 同样问题

**Comment by HelperInCa** [comment]
> > 问题解决了吗
> 
> 我换了个低版本就好了，但是定时任务一多 就会把服务器卡死

哪个版本呢，v2.10.2 同样问题

**Comment by HelperInCa** [comment]
> > > 问题解决了吗
> > 
> > 
> > 我换了个低版本就好了，但是定时任务一多 就会把服务器卡死
> 
> 哪个版本呢，v2.10.2 同样问题

把定时任务清光就好了
