### ISSUE TITLE
功能请求: 仅在任务执行完成时更新 最后运行时长(last_running_time)

### ISSUE THREAD

**Issue by fzls** [whyour/qinglong#964]
## 背景
当前在任务开始或者结束时都会调用 api.sh 中的 update_cron 来更新任务相关信息，其中包括最后运行时长。

https://github.com/whyour/qinglong/blob/e1294852855c3bf0e23f1fa19c10c2d1a555bd72/shell/task.sh#L104

https://github.com/whyour/qinglong/blob/e1294852855c3bf0e23f1fa19c10c2d1a555bd72/shell/task.sh#L119

其中 开始时未传入runningTime，update_cron 内部会取默认值 0

https://github.com/whyour/qinglong/blob/e1294852855c3bf0e23f1fa19c10c2d1a555bd72/shell/api.sh#L157

然后在 /crons/status 接口中会将传入的 last_running_time 原样更新到 任务的db对象中

https://github.com/whyour/qinglong/blob/e1294852855c3bf0e23f1fa19c10c2d1a555bd72/back/api/cron.ts#L281-L285

https://github.com/whyour/qinglong/blob/e1294852855c3bf0e23f1fa19c10c2d1a555bd72/back/services/cron.ts#L97-L112

## 问题
在上面这样的流程下，当开始一个新的任务后，其任务状态的最后运行时长就会变成 0 ，最终显示为 - 

https://github.com/whyour/qinglong/blob/e1294852855c3bf0e23f1fa19c10c2d1a555bd72/src/pages/crontab/index.tsx#L181-L183

![image](https://user-images.githubusercontent.com/13483212/143769288-b39b454c-cbd7-45d7-b5c7-9dd23affa6cc.png)

这样的话，这个字段在任务运行过程中将没有任何意义，只能说明他正在运行中，而这个信息也可以由右侧的 `状态`  字段来得知。

**同时，这也会导致想要根据 `最后运行时长` 字段倒序来看看哪些任务耗时较久时，若某些任务目前正常运行中，则无法正确的将他们排序**

## 预期
希望能修改 `last_running_time` 这个字段的更新逻辑，仅在其运行完成（也就是它不为0）的时候才尝试覆盖该值。这样即使在运行中，也可以显示最后一次成功完成时的耗时，而不是一个没有意义的 `-`

示例：假如最后一次运行时长是 20分2秒 ，我希望开始新一轮的运行后，会显示 20分2秒 而不是 - 

![image](https://user-images.githubusercontent.com/13483212/143769510-625820b2-7397-4bd2-ac77-96b26b4437c6.png)

![image](https://user-images.githubusercontent.com/13483212/143769501-b75480f2-ee30-434b-b761-7b8799e04c6b.png)

## 修改处
在进行任务状态字段更新的地方，判断一下传入的 `last_running_time` 的值，仅在其非 0 的情况下，才放入 $set 中。

**因为我没了解过TypeScript，所以不知道这里该咋写才能实现这个目的，希望作者可以帮忙处理下0-0**

https://github.com/whyour/qinglong/blob/e1294852855c3bf0e23f1fa19c10c2d1a555bd72/back/services/cron.ts#L97-L112

**Comment by fzls** [comment]
@whyour 大佬帮忙瞅瞅0-0  应该上面最后列出那个地方价格判断就好，但我没用过typescript，不知道该咋写哈哈

**Comment by whyour** [comment]
https://github.com/whyour/qinglong/commit/61bb6535fbbe7c0611d7bb017f074528c70bd63a
