### ISSUE TITLE
脚本调试运行有问题

### ISSUE THREAD

**Issue by klmmlk** [whyour/qinglong#967]
选择Python调试脚本时没有传入文件的绝对地址导致报错，建议调试时先进入脚本所在的目录再调用python运行文件，避免找不到依赖，虽然可以定义运行目录，但是这个应该是框架做的事情，希望修复。。
![QQ截图20211129223205](https://user-images.githubusercontent.com/12571901/143886811-b63edd95-7d99-4b5c-90bc-b62cc62fcac2.png)

**Comment by alphaerp** [comment]
为什么你可以用调试功能，我2.13.3调试，点击运行没任务反应， 能否请教一下如何使用？
