### ISSUE TITLE
青龙白屏 CORS报错

### ISSUE THREAD

**Issue by alisonjoe** [whyour/qinglong#968]
![image](https://user-images.githubusercontent.com/11343723/143918131-fb4a8cc9-c6b7-46d1-a6ad-001fc7a5d651.png)
![image](https://user-images.githubusercontent.com/11343723/143918493-7690964d-0d97-4e43-99d1-cf447578994c.png)

**Comment by alisonjoe** [comment]
今天发现是新版的Chrome不支持
https://developer.chrome.com/blog/private-network-access-update/?utm_source=devtools#both-ends-https

**Comment by naiveclub** [comment]
青龙的logo加载不出来是不是也是这个原因？应该怎么解决啊，我最新版chrome能出来登录页面，就是logo加载不出来，换个别的浏览器就直接白屏了

**Comment by alisonjoe** [comment]
网上有几个解决方案，我个人用的第二种，暂时先这么解决，你可以试下
方法一：
安装 chrome 插件 Allow-Control-Allow-Origin （未验证）
方法二：
浏览器输入 chrome://flags
搜索
Block insecure private network requests
选择 Disabled 再 Relaunch
![image](https://user-images.githubusercontent.com/11343723/145095100-4d309ac7-ad76-46da-8a5b-e0e516de20ed.png)

**Comment by yyetss** [comment]
我擦还真是....今天折腾了好多遍都不行.竟然是主题问题

**Comment by zynowhere** [comment]
牛，切下主题就好了

**Comment by hu-qi** [comment]
是的，暗黑主题问题

![image](https://user-images.githubusercontent.com/17986122/145745407-75cb02e6-b6d6-42fb-b21c-353e118abd8e.png)

先用手机检查更新，更新完毕就行了
![image](https://user-images.githubusercontent.com/17986122/145745515-62a5630c-0ebc-4e07-be9e-0d2a6309ed00.png)

**Comment by wodepig** [comment]
26年1月也遇到这个问题了, 设置里找不到Block insecure private network requests, 用edge安装了个Allow CORS: Access-Control-Allow-Origin插件并启用解决了问题
