### ISSUE TITLE
提示：“登陆已过期，请重新登录” 页面全白无登录框

### ISSUE THREAD

**Issue by ACTIONMOVER** [whyour/qinglong#971]
![image](https://user-images.githubusercontent.com/92711524/144002941-9d365a2b-f8f3-40f4-9853-eab12abbb4f8.png)

第一天晚上部署好新的docker镜像后
第二天就出现这种情况
求个解决办法~

**Comment by ACTIONMOVER** [comment]
有没有能重置登录记录的办法？或者重置账户信息？

**Comment by alisonjoe** [comment]
新版本 chrome 吧 看 issue 968 能不能解决
https://github.com/whyour/qinglong/issues/968

**Comment by hu-qi** [comment]
更新就能解决，或者先别用暗黑模式


![image](https://user-images.githubusercontent.com/17986122/145745847-177070bf-b5f0-4068-9e44-88c81c58a96e.png)

https://github.com/whyour/qinglong/issues/968#issuecomment-992062867
