### ISSUE TITLE
希望添加linuxdeploy支持

### ISSUE THREAD

**Issue by 363137946** [whyour/qinglong#973]
看了下脚本有termux支持，
希望支持linuxdeploy，主要是环境变量/usr/bin,
linuxdeploy的/usr/local/bin有问题

**Comment by inoyna12** [comment]
linuxdeploy我前段时间可以安装啊，也能用。
termux怎么安装的？

**Comment by gold-huiyun** [comment]
linuxdeploy确实很厉害，但是毕竟用户极少，不太会支持
