### ISSUE TITLE
建议更新版本时添加重试功能，重试时使用第三方链接https://ghproxy.com/

### ISSUE THREAD

**Issue by spiritLHL** [whyour/qinglong#979]
国内安装好像经常链接GitHub失败，报错如下：

开始更新系统

开始更新仓库：/ql

Fetching origin

fatal: unable to access 'https://github.com/whyour/qinglong.git/': Failed to connect to github.com port 443 after 129641 ms: Operation timed out

error: Could not fetch origin

HEAD is now at eab476c 更新版本号 v2.10.11

建议添加更新失败重试功能，重试时使用https://ghproxy.com/链接GitHub。

首次更新时裸连，重试更新时使用https://ghproxy.com/

**Comment by HelperInCa** [comment]
ghproxy 已经开始拉黑一些 JD 库了

**Comment by spiritLHL** [comment]
自建代理解决问题，cf，FastGitHub，选择很多，只是原生有写就不那么麻烦了。
