### ISSUE TITLE
大佬，cpu占用超级高，这是为什么？

### ISSUE THREAD

**Issue by gxlwrc** [whyour/qinglong#983]
最近总是发现unraid的cpu全红，看了后台进程是一个叫node /ql/build/schedule.js的进程，总是占用cpu达到了90%以上，这是什么原因呢？

**Comment by lancer-wang** [comment]
去看一下你计划任务数量,是不是变成了几千个几万个

**Comment by gxlwrc** [comment]
是的，我一直没注意，直到我打开了青龙，里面从8页变成了566页的js，我没办法，只能重新部署了，这是什么原因呢？

**Comment by gxlwrc** [comment]
> 去看一下你计划任务数量,是不是变成了几千个几万个

**Comment by gxlwrc** [comment]
> 去看一下你计划任务数量,是不是变成了几千个几万个
是的，我一直没注意，直到我打开了青龙，里面从8页变成了566页的js，我没办法，只能重新部署了，这是什么原因呢？

**Comment by lancer-wang** [comment]
> 是的，我一直没注意，直到我打开了青龙，里面从8页变成了566页的js，我没办法，只能重新部署了，这是什么原因呢？

鬼知道为什么,我发现是有几个拉库的定时任务,拉完之后不停而是无限循环拉库,一分钟就能拉100多个,多个一模一样的计划任务同时执行,服务器就这么炸了
可能跟多线程之类的油管

**Comment by lancer-wang** [comment]
建议1.停止并删除容器2.删除镜像,3删除本地文件
然后从头搞一遍,看还有没有

**Comment by gxlwrc** [comment]
> > 是的，我一直没注意，直到我打开了青龙，里面从8页变成了566页的js，我没办法，只能重新部署了，这是什么原因呢？
> 
> 鬼知道为什么,我发现是有几个拉库的定时任务,拉完之后不停而是无限循环拉库,一分钟就能拉100多个,多个一模一样的计划任务同时执行,服务器就这么炸了 可能跟多线程之类的油管

额，现在总算知道咋回事了，备份好ck，不行就重新部署，谢谢解答

**Comment by JuvenileQ** [comment]
中挖矿病毒了，我也中毒了，在使用docker安装完，阿里云安全预警，给我提示。你可以根剧这个脚本检查一下你的服务器
![image](https://user-images.githubusercontent.com/39209399/188878999-936527bf-9451-4cbd-aa5a-d020ab74a6d5.png)
