### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by qirenzhidao** [whyour/qinglong#988]
现在面板可以从定时任务点脚本跳转到编辑脚本界面，这一点非常好。
我的建议是，在脚本编辑界面，右上角的位置，添加锁定的按钮。。
锁定：任何repo或者raw的方式均不再更新此脚本，也不会删除此脚本，除非手动将其解锁。
这功能适合手动编辑脚本后保存，以免下次更新后再覆盖。

**Comment by nzmd** [comment]
支持
