### ISSUE TITLE
暗色主题下无法显示面板

### ISSUE THREAD

**Issue by chrimersong** [whyour/qinglong#989]
![Snipaste_2021-12-09_17-21-42](https://user-images.githubusercontent.com/36675963/145369339-ded2bc6e-3523-4705-8a37-580f46acae05.png)
v2.10.11
ql check检查面板和后台都正常
手机访问也正常，就是PC端打开一片空（dark theme下一片漆黑），加载资源显示两个失败（看图）
试过 #968 没效果，也换过edge访问、无痕访问，问题一样
大神看看是哪里出了问题
# 已解决 https://github.com/whyour/qinglong/issues/989#issuecomment-989816523

**Comment by woaicandy** [comment]
试试把主题换成浅色模式，不要用深色

**Comment by itgoyo** [comment]
好家伙改主题这个有效

**Comment by chrimersong** [comment]
牛啊牛啊，搞定了，什么神奇的bug哈哈哈，我还重新部署了一遍都没解决，还真是深色主题的原因
希望 @whyour 看看，是否能解决一下这个bug，支持一下深色主题？

**Comment by zhiwu2006** [comment]
哪里修改主题呢

**Comment by zhiwu2006** [comment]
> 

要去哪里修改主题呢

**Comment by zwb0619** [comment]
都进不去要怎么改啊？

**Comment by ttxhxz** [comment]
是修改浏览器主题还是系统主题？浏览器主题我这边修改后不生效

**Comment by lzz199507** [comment]
mac 深色模式 会出现这种情况， 换成浅色就可以了

**Comment by langliang3241** [comment]
我Firefox 95 深色模式下无面板界面，Chrome下可以正常显示，下午以为是系统问题，重装Firefox 不行 又重新安装青龙 还是一样

**Comment by chrimersong** [comment]
> 都进不去要怎么改啊？

清除浏览器的cookie就能进去了
![Snipaste_2021-12-09_20-40-12](https://user-images.githubusercontent.com/36675963/145398319-e8613135-23f8-4954-85f7-fbd2da847824.png)
![Snipaste_2021-12-09_20-40-35](https://user-images.githubusercontent.com/36675963/145398338-b258b941-dc90-4d0c-a01b-fe77b4ad9bf2.png)

**Comment by chrimersong** [comment]
> 哪里修改主题呢

青龙面板->系统设置->更多设置

**Comment by zwb0619** [comment]
> > 都进不去要怎么改啊？
> 
> 清除浏览器的cookie就能进去了 ![Snipaste_2021-12-09_20-40-12](https://user-images.githubusercontent.com/36675963/145398319-e8613135-23f8-4954-85f7-fbd2da847824.png) ![Snipaste_2021-12-09_20-40-35](https://user-images.githubusercontent.com/36675963/145398338-b258b941-dc90-4d0c-a01b-fe77b4ad9bf2.png)
我必须要重新登陆才能进设置面板。按你这个方法还是进不去，提示我登陆超时需要重新登陆
后来我在mac系统的偏好设置里面把改为亮色模式，可以打开登陆界面，正常登陆就进去了

**Comment by chrimersong** [comment]
@zwb0619 对，第一步是修改系统主题，因为面板默认是跟着浏览器主题的，而浏览器又默认跟着系统主题，所以在默认情况下，首先确保浏览器或者系统是亮色主题才能进去。

**Comment by chrimersong** [comment]
@zwb0619 对，第一步是修改系统主题，因为面板默认是跟着浏览器主题的，而浏览器又默认跟着系统主题，所以在默认情况下，首先确保浏览器或者系统是亮色主题才能进去。
