### ISSUE TITLE
所有的脚本都不行

### ISSUE THREAD

**Issue by jjss520** [whyour/qinglong#99]
京东极速版 -> 添加成功
东东超市 -> 添加成功
赚京豆 -> 添加成功
取关京东店铺和商品 -> 添加成功
(node:3377) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tough-cookie'
Require stack:
- /ql/scripts/sendNotify.js
- /ql/shell/notify.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)

不知道是怎么回事，手动运行脚本也这样

**Comment by whyour** [comment]
> 京东极速版 -> 添加成功
> 东东超市 -> 添加成功
> 赚京豆 -> 添加成功
> 取关京东店铺和商品 -> 添加成功
> (node:3377) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tough-cookie'
> Require stack:
> 
> * /ql/scripts/sendNotify.js
> * /ql/shell/notify.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:725:27)
> 
> 不知道是怎么回事，手动运行脚本也这样

手动执行下ql update
