### ISSUE TITLE
Python依赖安装错误

### ISSUE THREAD

**Issue by dclemon** [whyour/qinglong#990]
pip3 install lxml报错，是不是系统版本太低了？

**Comment by dclemon** [comment]
解决了，打包的linux缺少一些必要的环境
安装python3-dev,gcc,musl-dev,libxslt-dev，然后pip3 install wheel,pip3 install lxml即可

**Comment by Tamshen** [comment]
想问问具体的安装方法，安装`requests-html`，报错。

`docker exec -it qinglong bash` 进入 **docker** 没 `apt-get` 和 `yam`....

系统: 
`Linux version 4.15.0-142-generic (buildd@lgw01-amd64-036) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021
`

```log
  Using cached lxml-4.7.1.tar.gz (3.2 MB)

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kcxgah5s/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kcxgah5s/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-29c9_0gv
         cwd: /tmp/pip-install-kcxgah5s/lxml/
    Complete output (3 lines):
    Building lxml version 4.7.1.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by dclemon** [comment]
> 想问问具体的安装方法，安装`requests-html`，报错。
> 
> `docker exec -it qinglong bash` 进入 **docker** 没 `apt-get` 和 `yam`....
> 
> 系统: `Linux version 4.15.0-142-generic (buildd@lgw01-amd64-036) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 `
> 
> ```
>   Using cached lxml-4.7.1.tar.gz (3.2 MB)
> 
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kcxgah5s/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kcxgah5s/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-29c9_0gv
>          cwd: /tmp/pip-install-kcxgah5s/lxml/
>     Complete output (3 lines):
>     Building lxml version 4.7.1.
>     Building without Cython.
>     Error: Please make sure the libxml2 and libxslt development packages are installed.
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ```

在网页端依赖管理里面选linux依赖，依次安装python3-dev,gcc,musl-dev,libxslt-dev，安装完后再安装python依赖，wheel和lxml

**Comment by Tamshen** [comment]
>>安装requests-html，报错。
>>......略

> 在网页端依赖管理里面选linux依赖，依次安装python3-dev,gcc,musl-dev,libxslt-dev，安装完后再安装python依赖，wheel和lxml

解决了，谢谢大佬。

-------------
这个需要一步步依次安装，不能使用网页端新建依赖的自动拆分。
记录下流程：依赖管理
Linux
```
python3-dev
gcc
musl-dev
libxslt-dev
```
Python3
```
wheel
lxml
requests-html
```

**Comment by orency** [comment]
上面的方法是用wheel编译出本机架构的文件,在一些低性能机器,比如树莓派上会造成死机
在死机n次后,看到https://github.com/whyour/qinglong/issues/1162#issuecomment-1041138224
突然想到也可以这样安装lxml,无需本机编译
命令行
`sudo docker exec -it qinglong bash`
`apk add py3-lxml`
或者直接在依赖管理linux中直接新建依赖py3-lxml即可
另外提下青龙的linux依赖安装bug,不存在的包依然会报安装成功

**Comment by Humetea** [comment]
千万不要在低性能机器上，使用青龙依赖安装lxml，血的教训，机器崩了
