### ISSUE TITLE
深色模式不显示登录界面，完全黑屏

### ISSUE THREAD

**Issue by qilongcainiao** [whyour/qinglong#996]
深色模式不显示登录界面，完全黑屏

**Comment by sonce** [comment]
一样黑屏不显示~~~

**Comment by sonce** [comment]
![image](https://user-images.githubusercontent.com/887972/145910885-3f145641-0cae-4923-9a29-7f93618bf26c.png)

**Comment by whyour** [comment]
@sonce https://t.me/jiao_long/237   更新最新版，刷新下

**Comment by zhudan** [comment]
更新
已经是最新版了！
青龙 2.10.11 是目前检测到的最新可用版本了。

**Comment by zhudan** [comment]
> 更新 已经是最新版了！ 青龙 2.10.11 是目前检测到的最新可用版本了。

强制更新就可以了
