### ISSUE TITLE
为啥每次电脑重启（就是虚拟机重启）后青龙面板配置就初始化了？

### ISSUE THREAD

**Issue by 664873568** [whyour/qinglong#998]
都是直接关机，Docker Quickstart Terminal没操作其他的
试了两次数据都丢失了
有大佬指教吗，是不是我有哪个步骤没有操作o(╥﹏╥)o
还是说本地虚拟机就是这毛病？

**Comment by yanzhang4013** [comment]
docker rm 容器ID -f  
移除错误的容器后，再原来的QL文件夹上一级重新配置一次，进入就可以了。
注：可能会需要进入容器内执行ql check命令进行修复一次。
----------------------------
进行上述操作前，记得备份一下环境变量参数，防止意外。
